### ISSUE TITLE
Gagarin forcing access one single-card remotes

### ISSUE THREAD

**Issue by mn200** [mtgred/netrunner#1003]
When I run against Gagarin, it seems that if there is just one card in a remote, the game forces me to access that card. My understanding of the rules is that I can decline to access because there is an additional cost, but still get credited with a successful run. This is important for things like Desperado and Dirty Laundry, where you may just be in it for the money.

If there is more than one card, then I can access them piecemeal as I choose, which does seem right.

**Comment by cupello** [comment]
I am a noob in this program so forgive me if I am saying something stupid.

Seems like the problem is not with the Gagarin's implementation - even without using Gagarin you are forced to access. One way to solve the problem is always asking which card the player wants to access. Am I wrong?

**Comment by zaroth** [comment]
Without Gagarin's ability the runner *should be* forced to access all cards after a successful run according to rules. With Gagarin it's optional only because there is an additional costs, which the runner can always opt out of.

**Comment by cupello** [comment]
Sorry guys and thanks for the clarification.

**Comment by nealterrell** [comment]
I wrote some code in Leela that should help solve this issue.
