### ISSUE TITLE
Ice Carver lowers Lotus Field's strength

### ISSUE THREAD

**Issue by CrushU** [mtgred/netrunner#1009]
In a game, Runner has Ice Carver in play, and runs a server with a Lotus Field. Lotus Field is listed as 3 strength, when you shouldn't be able to lower Lotus Field's strength.

**Comment by zaroth** [comment]
Pinging @JoelCFC25 who recently plays a lot with ice strength :)

**Comment by JoelCFC25** [comment]
Lotus Field immunity to strength lowering doesn't exist yet.

**Comment by nealterrell** [comment]
I think this can be done, actually... by having Lotus Field give itself a strength bonus equal to the negative of whatever other bonuses other cards have requested. I'll try.

**Comment by nealterrell** [comment]
Nevermind, this doesn't account for bonuses from Lag Time etc.
