### ISSUE TITLE
Genetics Pavilion doesn't cap card effects

### ISSUE THREAD

**Issue by SimonS** [mtgred/netrunner#1012]
Just had a game where someone played Diesel with GP in play and it still drew 3 cards. I expect it only caps manual click-to-draw interactions.

**Comment by JoelCFC25** [comment]
Genetics Pavilion is not implemented at this time.

**Comment by SimonS** [comment]
1ah ha, that makes sense- thanks, and sorry for the invalid report!

**Comment by JoelCFC25** [comment]
No worries! There are some new people contributing lately so maybe one of them will get inspired and tackle this one!
