### ISSUE TITLE
Theo Bag & Brain Damage

### ISSUE THREAD

**Issue by gumOnShoe** [mtgred/netrunner#1015]
Handsize for Theo recalculates every time your credit total changes; but, it doesn't account for Brain Damage and this leads to a lot of players having to reset hand sizes.

Reported by vinegarymink

**Comment by JoelCFC25** [comment]
Thanks for the report! We need to add a method for pooling together all sources of modification to `:max-hand-size` so that Bagbiter can determine the correct value both with brain damage while in play and with things like Beach Party when he leaves play.
