### ISSUE TITLE
Cards completely disappear if you use street peddler with insufficient credits

### ISSUE THREAD

**Issue by jjfs85** [mtgred/netrunner#1022]
Whatever card you intended on installing using Street Peddler goes poof. It is not: in the heap, grip, stack, or on the table.

**Comment by Saintis** [comment]
To reproduce:
1. Install street peddler
2. Click it to bring up the card selection
3. Reduce credits to be unable to pay for a card (including cost reduction)
4. Select card (that you are unable to pay for)
5. Street peddler is used, msg appears. Card disappears

**Comment by nealterrell** [comment]
I'll look into it, thanks for the report and the reproduction steps.

**Comment by nealterrell** [comment]
I have a fix for this in the pipeline. It will just cancel the Street Peddler action if you can't afford the card selected.
