### ISSUE TITLE
Forced out of server after successfully breaking ASH trace (runner)

### ISSUE THREAD

**Issue by Whoopidoo** [mtgred/netrunner#1024]
There was a performance issue when breaking an ASH trace as the runner.  ID's were Kate VS Engineering the Future.  During a Stimhack run on a remote server, after successfully breaking a Janus 1.0, Heimdal 1.0 via clicks, and an ICHI 1.0, ASH trace initiated, with the runner successfully matching the trace.  A prompt came up warning that you must access all cards in the remote, however, after clicking the OK button, instead of accessing cards, runner was booted from the server.  A repeated attempt at the run procured the same results.  Runner was then disconnected from the game.

Runner had MG shrike, Study Guide, and Corroder installed as breakers, as well as two Multithreader and a Magum Opus.  Two Dyson mem chips, an Astrolabe, and two R&D interface were installed as well.  Corp had, from the outermost position, Janus 1.0, Heimdal 1.0 and Ichi 1.0 installed as ICE on a remote.  Remote server contained 1 ASH, as well as two other unrezzed cards.

**Comment by zaroth** [comment]
Unfortunately this doesn't sound like it would be easy to reproduce... could you try to narrow down/isolate the problem?

**Comment by Whoopidoo** [comment]
Well, if I had to guess, it would be an issue of an ASH trace ending in the runner's favor while there is more than 1 unrezzed card remaining in the remote.  Or possibly just a problem with allowing the runner to access cards other than ASH after a failed trace.  I don't know how much more I can narrow it down.  I just wanted to be as specific as possible.

**Comment by zaroth** [comment]
Well, writing a unit test for ASH would be a good first step then. I was sure one existed, but there isn't one: https://github.com/mtgred/netrunner/blob/master/src/clj/test/cards-upgrades.clj . There is only a bit of a check for it in https://github.com/mtgred/netrunner/blob/master/src/clj/test/games-scenarios.clj

If after writing a comprehensive unit test for the card the problem still isn't found, then I don't know :)

**Comment by Whoopidoo** [comment]
UPDATE:  There is no bug, it was my own mistake.  I didn't realize you had to manually click the installed cards to access them, and instead hit the "done" button, ending the run.  ASH works fine.

**Comment by nealterrell** [comment]
No problem :).
