### ISSUE TITLE
Architect shows the card installed via R&D install subroutine to spectators

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1026]
When player was installing The Future Perfect from R&D via first Architect subroutine, I was able to see the TFP card for a brief moment in the top left of play area (next to removed from game, currents...). Spectators shouldn't be privvy to any corp-only information. (This may also work that way for the runner, haven't tested - it would be even worse)

**Comment by nealterrell** [comment]
`:play-area` needs to not be rendered to spectators.

**Comment by sjohnc** [comment]
This can be closed now right?
