### ISSUE TITLE
Medium "click on card to access less cards" does not work properly

### ISSUE THREAD

**Issue by Lasica** [mtgred/netrunner#1027]
It should be more clear when you can access less cards using medium. The phrase "Runner may click on medium to access less cards" is lacking "before runner starts accessing".

At the current state clicking on medium mid accessing causes delayed window which should only appear before runner starts accessing. Also clicking on medium mid accessing adds virus counters on it.

**Comment by JoelCFC25** [comment]
Thanks for the report. I'll look into it soon.

**Comment by JoelCFC25** [comment]
It looks like both issues will be resolved by adding `(empty? (get-in @state [:runner :prompt])` to the requirement to do the click ability.
