### ISSUE TITLE
A bug of IT department's "add strength to a rezzed ICE"

### ISSUE THREAD

**Issue by tefering** [mtgred/netrunner#1036]
When "add strength to a rezzed ICE" is used, the "Select a target for IT Department" shows up but nothing can be done. You can not either add strength or close the window by pressing the "Done" button. As the window does not disappear, you can not proceed the game.

**Comment by JoelCFC25** [comment]
Thanks for the report. The call to `ice-strength-bonus` in IT Department's code is passing an insufficient number of arguments and generating a bug. We'll look into it!
