### ISSUE TITLE
Records latest 'win' instead of earliest

### ISSUE THREAD

**Issue by Zach-ER** [mtgred/netrunner#1037]
Hi, 
running archives vs pe, i won the game, then continued to access the rest of the cards, flatlined, and it changed to 'losing' the game. It should ignore subsequent win conditions after an agenda-point win.

**Comment by GordonsBeard** [comment]
Does it actually mark this game as a win for whoever wins last (in the backend database), or does the backend take the first win condition and just allows the rest to play out however you wish?

**Comment by zaroth** [comment]
This behavior is intended. You continued to play, therefore the game continued to report the game state. If you "kept accessing cards in archives" after winning in real life netrunner, you would get "flatlined" too, whatever that would mean.  I think it wouldn't be wise to freeze the state of the game after one player wins, especially in this phase of development - there are too many situations where game state needs manual fixing for us to just freeze the game after a win. 

Actually there is a related problem to jinteki PE, which is actually confusing - if stealing a winning agenda (not fetal) work with no cards in grip, runner gets both a win and a flatline message. Unlike case described in this issue, this can't be solved by simply stopping play after winning action, as this happens simultaneously.

**Comment by PesiTheWizard** [comment]
I understand that it is better this way. I write this because now that Obokata Protocol is here; it, too, can have the runner steal it, flatline, then win on points and it will count as a runner win.
