### ISSUE TITLE
Registering accounts doesn't check for e-mail uniqueness

### ISSUE THREAD

**Issue by chokh1443** [mtgred/netrunner#1039]
Today, I accidentally find out, I can sign up to jinteki.net for the same email address with already existed.

I've never used coffee script before, however as I suppose 262~286 line on server.coffee is not checking the unique email address.
it seems not a unique set on database neither.

**Comment by Merlin8000** [comment]
What are the actual negative effects of that?

**Comment by chokh1443** [comment]
when I forgot whether I joined for not.
...
    if user
      res.send {message: 'Username taken'}, 422
    else
....
      db.collection('users').findOne email: req.body.email, (err, email) ->
        if email
			res.send {message: 'email already registered'}, 422
        else
   ...
          email = req.body.email.trim().toLowerCase()
          req.body.emailhash = crypto.createHash('md5').update(email).digest('hex')
          req.body.registrationDate = new Date()
...
maybe works for it

**Comment by Saintis** [comment]
@nealterrell is this still an issue now with the server rewrite?
