### ISSUE TITLE
Trashing Director Haas scores it even if not accessed

### ISSUE THREAD

**Issue by dersam** [mtgred/netrunner#1042]
if Director Haas is trashed from HQ without being accessed, it will still be scored as an agenda.

**Comment by JoelCFC25** [comment]
Can you be as detailed as possible about the circumstances in which this happened? I've tried trashing Director Haas from HQ as Corp when over my hand limit, tried having one discarded by a Utopia Shard...still haven't seen this occur.

**Comment by dersam** [comment]
I'll have to try and reproduce myself. It happened consistently in one
game, so there must have been some other circumstances causing this, not
just the base case. I suspect it might be if there is already one installed
and rezzed, but I'll try it out and let you know.

**Comment by JoelCFC25** [comment]
We're hot on the case now in #1181. Do you remember if Film Critic was used by the Runner the times when you saw this?
