### ISSUE TITLE
What e-mail did I register with (for Gravatar images)

### ISSUE THREAD

**Issue by mn200** [mtgred/netrunner#1046]
If I registered with an e-mail address, which I assume I did, I have no idea which address it was. I would like to know so that I can set it up with a Gravatar image.  Some sort of information in a tab labelled "Account" or "Settings" or similar might help with this.

**Comment by nealterrell** [comment]
@domtancredi is working on this in #1047.

**Comment by NoahTheDuke** [comment]
Seems that displaying ones email never did get added, so I'm reopening this.

**Comment by AIM-54-Phoenix** [comment]
Thank you.

**Comment by NoahTheDuke** [comment]
Email is now displayed, as of #5064.
