### ISSUE TITLE
I've Had Worse triggering after a flatline

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1050]
I've Had Worse shouldn't trigger when there is more damage dealt to the runner than he has hands in his grip (e.g. Scorched Earth vs hand of 3 with IHW and no other meat damage prevention).

**Comment by JoelCFC25** [comment]
Adding `(not (:winner @state))` onto the existing `:req` for the trash effect in I've Had Worse seems to solve this.

**Comment by queueseven** [comment]
I think this should be done in the game engine, not in the card itself. After checking for damage prevention, when the damage is > Hand size, don't resolve any more effects (don't now if this will work 100%)

**Comment by JoelCFC25** [comment]
I got this to work fine in an initial attempt, but did it in a way that the flatline occurs without trashing any cards from the Runner's hand. If we want that, then the `doseq` that trashes all Runner cards needs to be called twice--once with `:cause type` passed to `trash` in the case of the Runner surviving, once with only `:unpreventable true` passed in the case of them flatlining.
