### ISSUE TITLE
Same Old Thing Freezing Game

### ISSUE THREAD

**Issue by sermittens** [mtgred/netrunner#1054]
I was playing MaxX against RP and tried to use SoT to legwork.  I clicked legwork and it started a legwork run but the SoT menu asking me to select an event to play remained.  I was unable to close the menu and had to concede the game.

I tried adding clicks and clicking a different event as well as hitting 'done' without selecting an event.

It is possible that I clicked SoT twice due to a small amount of lag.

**Comment by Saintis** [comment]
Was unable to reproduce in my local environment. Probably need some lag to test this.

Did discover that if you choose an event that you cannot pay for (e.g. Legwork with 1 credit) the SoT is still used up but no event played (does display "used SoT to play Legwork").

**Comment by sermittens** [comment]
The using up but not playing also happens with SMC.

**Comment by JoelCFC25** [comment]
In the case of SMC, I think there has been a ruling to the effect that you can pop SMC, fail to find anything you can install, but SMC is still trashed and you shuffle.
