### ISSUE TITLE
Anyone use Emacs + CIDER?

### ISSUE THREAD

**Issue by jaerme** [mtgred/netrunner#1060]
Sorry for the newbie question. I'm trying to follow the development guide, but whenever I make a change and then compile the file (C-c C-k), I'm not seeing my changes. I have tried uninstalling the cards and then reinstalling. It only seems to work after I kill CIDER and jack in again.

**Comment by Saintis** [comment]
I use emacs but found CIDER too much hassle. Just running a repl through lein instead.

**Comment by nealterrell** [comment]
Not an Emacs user, but if you make changes to a card, you need to run `(load-file "src/clj/game/cards.clj")` in a REPL for the card changes to take effect. Don't know if that's helpful to you.

**Comment by jaerme** [comment]
@nealterrell I have tried that also inside the CIDER repl, but with no luck. I will try @Saintis suggestion and use lein. Appreciate the quick responses!

**Comment by jaerme** [comment]
I'm still having the same issue with lein repl. The only way I am able to see my change is to restart the game server and reload the REPL. I'll keep investigating.

**Comment by holguinj** [comment]
@jaerme try `M-x cider-refresh` ([docs](https://github.com/clojure-emacs/cider#code-reloading)). That should reload all of the namespaces on the classpath and save you from killing and restarting cider.

**Comment by queueseven** [comment]
Hey @jaerme, any news on this issue? Did @holguinj 's suggestion help you? If not, feel free to reopen this issue.

**Comment by jaerme** [comment]
cider-refresh did not work, it threw an error.
