### ISSUE TITLE
Fall Guy attempts to prevent Chronos Protocol Damage

### ISSUE THREAD

**Issue by grimwalker** [mtgred/netrunner#1064]
I don't know if it's because the card is revealed and thus is visible to Fall Guy, but when applying targeted Net Damage with CP, it gave the option to prevent the trash using Fall Guy.

**Comment by JoelCFC25** [comment]
Thanks for the report. This can be fixed by adding `:unpreventable true` to the line in Chronos Protocol where it's trashing the selected card, but I wonder if a better solution is to address it in the core trashing functions--prevention should never be kicking in for non-installed trash targets.
