### ISSUE TITLE
Log the Hunting Grounds trash effect in the chat.

### ISSUE THREAD

**Issue by matthewrmettler** [mtgred/netrunner#1065]
If someone plays [Hunted Grounds](http://netrunnerdb.com/en/card/09035), the log says that three cards are installed facedown, but it doesn't explicitly say what card caused the effect in the chat, or that Hunting Grounds was trashed.

This might also occur for other cards that are trashed and cause effects, I'm not sure.

**Comment by JoelCFC25** [comment]
Thanks for the report! We can add a `:msg` to this Hunting Grounds ability--you're right, it would improve clarity.
