### ISSUE TITLE
Chronos Protocol + damage prevention

### ISSUE THREAD

**Issue by Amphiprison** [mtgred/netrunner#1067]
According to this:

https://www.reddit.com/r/Netrunner/comments/3l9d9x/lucas_ruling_on_chronos_vs_prevention_and_ribs/

which, admittedly, is a terrible source, Chronos Protocol only cares about the first net damage that makes it past prevention.  As currently programmed, preventing the first point of net damage in a round seems to prevent CP's identity from triggering on the next point of unprevented net damage.

**Comment by JoelCFC25** [comment]
Just verified that this will be fixed by #1099!
