### ISSUE TITLE
Cloned cards with The Supplier

### ISSUE THREAD

**Issue by ovidenov** [mtgred/netrunner#1068]
Hi,

First time for me to post here: great work on www.jinteki.net .
I spotted a minor issue.
I was using The Supplier and it had two hardware cards on it. On my next turn i used a click to install the hardware card, but it just cloned and did not remove it from the supplier. I decided I can trash the hardware card, but it was just cloning itself.

Regards,
Oleg

**Comment by JoelCFC25** [comment]
> On my next turn i used a click to install the hardware card

I'm not following you here--if The Supplier is hosting cards, you are meant to see a prompt come up when your turn begins asking if you want to install 1 of the hosted cards. The prompt includes a list of card titles and you click one to install it. No clicks should be used up for this. 

Can you describe in a little more detail what you clicked and in what order? What were the hosted cards?

**Comment by JoelCFC25** [comment]
@ovidenov: Can you follow up on this one? I haven't been able to replicate it, but again, I'm not entirely sure what you attempted.
