### ISSUE TITLE
List of small enhancements/feedback

### ISSUE THREAD

**Issue by ovidenov** [mtgred/netrunner#1069]
First of all, really great work.
FFG should really hire you, big time :).
I've played quite few games already on jinteki.net and it is good experience, compared to OCTGN.

1. If I click on Ice and want to trigger the effect of some of the subroutines, a popup appears.
I would expect that by clicking anywhere on the screen that popup is gone.
At the moment I need to click on that ice in order to remove the popup.
 
2. 
The chat: 
The nicknames might be colored, so everyone can track better.

Regards,
Oleg

**Comment by zaroth** [comment]
Hey, please don't group multiple issues in one, it makes stuff way harder to track. I'll repost your first suggestion in a new issue. For the purposes of second one, we have avatars.
