### ISSUE TITLE
Loop on run

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#107]
I was playing ( Oziride ) VS ( Balancer ) at 15:00 ( GMT +1 ).

Andromeda VS Titan ( I hope this data help log digging )

I made a run on archives ( to "false" trigger Security Testing + Masanori + Desperado ) but on "Successful Run" ( I know there isn't any agendas so I click it ) the "interface" ask me again to click "Successful Run"; now, either I click on "Successful" or "Jack Out" the "interface" continue to ask me what to do; If I click "Successful Run" it show me all the card in the archives, (and ask again) if I jack out it said "Oziride jacks out." and ask again.
Desperado will gain me 1 credit each time.
Those are the card in the archive:
Oziride accesses PAD Campaign, Reclamation Order, Nebula, PAD Campaign, Reclamation Order, Cyberdex Virus Suite, Hedge Fund, Hedge Fund, Hedge Fund, Crisium Grid.

( Maybe "Cyberdex Virus Suite" ? It's the first time happens to me and also the first time I run on "Cyberdex Virus Suite" ).

**Comment by mtgred** [comment]
Thanks for reporting the issue. There was a issue preventing the run from ending if the Corp has an active prompt (Cyberdex Virus Suite in this case). The issue is now fixed and will be deployed with the next server update.
