### ISSUE TITLE
Uniqueness not checked when installing Runner cards from hand

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#1071]
This used to work, but is now broken. I believe it's because `in-play?` just flat out does not work. It uses `(:side card)` thinking that will return `:runner` or `:corp`, when it really returns "Runner" or "Corp".

**Comment by Saintis** [comment]
Problem lies in the `all-installed` function. Changing the `(= side :runner)` to `(= (side-str side) "Runner")` solves the problem.

**Comment by nealterrell** [comment]
Don't change that `all-installed`... there are cards without unit tests that use the function. `in-play?` needs to call `all-installed` appropriately.

**Comment by Saintis** [comment]
`side-str` should allow for both `"Runner"` and `:runner` to be passed in correctly. To get `in-play?` to call `all-installed` 'correctly' you would need a `side-keyword` function then, since the side is taken directly from the card...

**Comment by JoelCFC25** [comment]
Is this resolved or still hanging out there?

**Comment by nealterrell** [comment]
Still exists.

**Comment by JoelCFC25** [comment]
I'm not sure--it could be an artifact of my yet-to-be-merged changes, but at this moment in dev after installing a Kati Jones I'm not able to install a second copy.

**Comment by JoelCFC25** [comment]
This is definitely resolved now for installs straight from hand. I'll have a solution for the cards that host and install with a full unit test of everything soon.
