### ISSUE TITLE
Multiple hosted pawns crash the game

### ISSUE THREAD

**Issue by otorandell** [mtgred/netrunner#1072]
Hey there!
I was playing some street chess Exile deck, and i noticed (i actually played a lot of games with it, to do a consistent issue report) that when there is 2 or 3 pawns hosted on a single ice and you make a succesful run, the game crashes for several seconds (not lag) and then you cant pass the "Successful Run-Jack Out" option panel, rarely, the game recovers and let you install one pawn, but seems to crash again when the second pawn has to trigger. Single pawn on board works good, the problem only occurs when 2+ are hosted on ICE (i tested it with all pawns in the same ICE).
Thanks for your attention!

PD: Another minor and not important related issue is that the just trashed pawn can return itself to the board while the rules say that this cannot occur.

**Comment by JoelCFC25** [comment]
Thanks for the report! We have this one on record at #1021--not sure yet how it will be handled. :)
