### ISSUE TITLE
Accelerated Beta Test firing incomplete

### ISSUE THREAD

**Issue by merceeiro** [mtgred/netrunner#1073]
Hi,

playing Agenda Next Design when trying to fire ABT it did not work correctly:
  - non ICE card where sent to archive but ICE card was not shown (message to select card was shown but no cards)

example:
2 cards where sent to archive but third card was not presented to select (a message was show asking to select but no card)

This happen twice in the same game and then we quit (game played today).

When I played the same identity and agenda 2 weeks ago it was working fine.

best regards,

Francisco

**Comment by JoelCFC25** [comment]
Francisco, try using ABT again now that the server has been restarted and see if it works successfully for you. There was a slight modification to its behavior in #1058.

**Comment by tolaasin** [comment]
I played today, doesn't look fixed atm. fired abt, 3 cards in the top area of the board, BBG, ice and another ABT. Installed the ice, the other two cards stayed in the top.

**Comment by JoelCFC25** [comment]
This behavior is now intentional--non-ICE or ICE you choose not to install will have to be manually trashed. In the case of Foundry+ABT, you'll have to put cards back into R&D manually if you fire The Foundry.

**Comment by merceeiro** [comment]
i confirm that is fixed.
used it yesterday.
