### ISSUE TITLE
RSVP + Gagarin

### ISSUE THREAD

**Issue by Arikiba** [mtgred/netrunner#1074]
There doesn't seem to be an option for me to make RSVP (NBN ice) fire its subroutine. Normally, I can just tell the player in chat, but when I run Gagarin, that means that I can't let the run be successful without the runner auto-accessing a card (even though with the RSVP sub, they shouuldn't be able to). Am I maybe doing something wrong, or is that just still an unsupported feature?

**Comment by JoelCFC25** [comment]
You're not doing anything wrong--it's just that RSVP is completely unimplemented at this time. Sorry! Hopefully someone will eventually get inspired and tackle this one.

**Comment by Arikiba** [comment]
Aha, okay. Thank you!

**Comment by NBKelly** [comment]
Eight years late, but this is implemented in #7539 :)
