### ISSUE TITLE
Foundry misfiring with ABT

### ISSUE THREAD

**Issue by nialbima** [mtgred/netrunner#1075]
I just ABT'ed, and tried to use the Foundry to prevent an agenda from going to the trash. It went there anyways. I wasn't sure this was the correct ruling, but this BGG thread seems to indicate as much:

https://boardgamegeek.com/thread/1232168/accelerated-beta-test-and-foundry 

(basically, when it fires, the other two cards you looked at get shuffled, so ABT loses track of them and doesn't replace them)

**Comment by JoelCFC25** [comment]
Thanks for the report. This is a known limitation of ABT as currently implemented. When it was reworked a couple months ago (see #772), I noted at the time that it wouldn't handle the interaction with The Foundry correctly. So unfortunately in this case (after firing The Foundry) you have to manually put remaining ICE into R&D and then shuffle it. 

Obviously you wouldn't have had any way of knowing beforehand the limitation. Some of the other developers have some things in testing that may soon help corner case situations like this by using Javascript popups (toasts, I guess they're called) to alert players to things.

**Comment by nialbima** [comment]
Thanks! That's a good workaround/can the alerts (toasts?) have Pop-Up Window on them? 

In other "why are you playing these cards" problems, I was using Howler in that same deck, and it couldn't fire if they chose to let it (i.e. not bypassing, not jacking out, not clicking, not paying). The only trigger menu option that appeared on screen was the "derez" button, which might make sense since that's the effect Howler triggers with its sub and nothing else I can think of installs via a sub then forces an immediate encounter. Any ideas?

**Comment by JoelCFC25** [comment]
Interesting. Howler is working for me in my test environment. Can you add any details? For example, which server was Howler on and at what position? Have you done a forced refresh of the site since it was restarted today? I'm grabbing at straws on the last one.

**Comment by JoelCFC25** [comment]
If you experience the Howler issue again, please make a new issue for it.
