### ISSUE TITLE
Moving "Watch" button

### ISSUE THREAD

**Issue by danielchamberlain** [mtgred/netrunner#1078]
Would it be possible to place the "Watch" button in a different location than the "Join" button? Right now, if the game fills up, the watch button moves to where the join button was previously. As a result, people often click on the watch button by accident. One solution could be to keep the join button visible but just disable it and/or gray it out once the game is filled.

**Comment by zaroth** [comment]
A simpler solution could be to keep Watch on the right and Join on the left, so Join simply disappears instead of making something jump into its place :)

**Comment by zaroth** [comment]
Fixed this some time ago when adding lobby faction icons.
