### ISSUE TITLE
Feature Suggestion: Import of Octgn Deck Format or txt format export

### ISSUE THREAD

**Issue by ichigokuto** [mtgred/netrunner#1079]
would be really helpful if there was an option to upload/import octgn deck form, as well as the octgn export file. Have a lot of decks on netrunnerdb that i would like to migrate over easily and having to build each deck from scratch into jinteki.net is time consuming.
many thanks

Rob

**Comment by JoelCFC25** [comment]
> Have a lot of decks on netrunnerdb that i would like to migrate over easily and having to build each deck from scratch into jinteki.net is time consuming.

You shouldn't need to do this--importing decks in text format is already supported. On NRDB, do an Export to Plain Text, then copy everything *except* the couple lines at the bottom (starting where it says how much influence you used). Paste it into the big decklist text box here.

**Comment by ichigokuto** [comment]
Incerdible!! Never thought to try this. Thanks for the response and thats great!! Jinteki.net ftw!

**Comment by nealterrell** [comment]
You don't even have to go that far. You can just highlight the text of the decklist, for example on this page: http://netrunnerdb.com/en/decklist/30354/stealth-kit-mwl. Copy everything; the site will filter out the important bits.
