### ISSUE TITLE
ICE's card menu appears underneath installed ICE and Runner cards

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#108]
When I click on a piece of ICE and the menu appears, the Runner and other ICE cards are over top of the menu and block clicking. In certain scenarios this will prevent the menu being clicked entirely (seems like a CSS z-index issue to me).

Windows 7
Google Chrome 40.0.2214.111 m

**Comment by JoelCFC25** [comment]
Closing this for now--if it becomes an issue again we'll reopen it.

**Comment by JoelCFC25** [comment]
Reopening this because it's becoming an issue as I try working on Worlds Plaza and Awakening Center.
