### ISSUE TITLE
Testrun + Parasite

### ISSUE THREAD

**Issue by itsTuttle** [mtgred/netrunner#1081]
Had an issue with Testrun where I got Parasite out of my Heap onto a piece of ice. Parasite did not bounce back to the top of the Stack after the turn was completed.

**Comment by JoelCFC25** [comment]
Thanks for the report. When Test Run's `:end-turn` effect fires, it's only looking in `[:runner :rig :program]` for the card chosen to be installed, so it'll miss Parasite, which would be found in `:hosted` on a piece of Corp ICE. By extension this probably also means that if you shift the program you installed onto a Runner card that can host (Scheherazade, Dinosaurus, et al) after install, it will also fail to go back onto the Stack in that case.

**Comment by nealterrell** [comment]
Yeah... this one is going to be annoying.
