### ISSUE TITLE
"0 Games" Issue

### ISSUE THREAD

**Issue by a340** [mtgred/netrunner#1083]
I think this might be my computer (not a server issue), but I know little to nothing about all that technology.  

When I arrive at jinteki.net, I see "0 game" always.  When I click on the "play" tab, it still shows 0 game.  When I start a game, it allows me to pick a side and start, but doesn't load for me to select a deck.  I can still usually participate in the chat lobby. 

I have tried three browsers, Shift/F5, deleting cookies/cache, all to no avail.  If there are any suggestions that would be awesome sauce.

**Comment by nealterrell** [comment]
What browser and operating system?

**Comment by a340** [comment]
I'm on Windows 10, I have used Chrome Firefox and IE.  None have worked for me.

**Comment by mtgred** [comment]
It's most likely a websocket issue. Are you trying to access the website from work or a place with network restrictions?

**Comment by a340** [comment]
No I'm at my house, though I do have an internet filter.  Could that be affecting it?

**Comment by nealterrell** [comment]
Yes, that is most likely it. When the site first loads, we show a 0 for active games, then once a WebSocket connection is made to the server, the game list is downloaded and that number is changed. Try whitelisting the site, including the subdomain `ws.jinteki.net`. (If you can, just whitelist `*.jinteki.net`.)

**Comment by a340** [comment]
That fixed it!  Thanks a ton.

**Comment by domtancredi** [comment]
If that fixed the issue, would you mark it as "Complete" @a340

**Comment by a340** [comment]
Definitely, how do I do that?  I'm new to github.

**Comment by nealterrell** [comment]
I got ya.

**Comment by domtancredi** [comment]
Teamwork makes the dream work
