### ISSUE TITLE
Industrial Genomics - # of facedown cards?

### ISSUE THREAD

**Issue by dinte** [mtgred/netrunner#1084]
A super non-essential feature request. I'd love for an at-a-glance way to see how many cards are facedown in archives. An advancement-like number on the ID would suffice. It would just be a nice reminder for everyone involved and save a lot of counting cards in archives.

**Comment by Saintis** [comment]
Could change it so say (x + y) where x is number of face-up cards and y is number of facedown cards.

**Comment by JoelCFC25** [comment]
How about X↑ +  Y↓

**Comment by dinte** [comment]
That seems like a clear enough way to display it.

**Comment by bmatsuo** [comment]
The number of faceup cards isn't really important, is it? The important numbers are (total cards) and (facedown cards). Would it be work to use just these numbers?

> Archives (0 / 10)
> Archives (1 / 11)
