### ISSUE TITLE
Agenda point ambushes asking to trash after firing 

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1089]
News team (and possibly shikyu) firing from not-Archives still ask you whether to trash them even if you choose to take them to your score area. It works correctly, but can get pretty confusing.

**Comment by JoelCFC25** [comment]
This would still be a good one to fix. I've tried several things--both in the card definitions themselves and the core trashing functions, all without success.

**Comment by Saintis** [comment]
Maybe if you add a check to see that the card is not in `:scored` in the not-in-archives check [here](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core-runs.clj#L111). And reload the card and all that.

**Comment by JoelCFC25** [comment]
No dice, unfortunately.

**Comment by Saintis** [comment]
What if we use `when-completed` on the `:access` [trigger ](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core-runs.clj#L109)(if necessary), then reload the card, then check if the card is in archives or score area?
