### ISSUE TITLE
Haarpsichord Studios + Gang Sign interaction is flawed

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1091]
Haarpsichord Studios prevents a steal if the Runner has stolen an agenda on his last turn but then manages to steal one during the subsequent Corp turn (most probably by Gang Sign, but there are other ways).  

The `:req` on Haarpsichord is simply looking to see if `:stole-agenda` exists in `[:runner :register]`, a value that obviously needs to persist for things like Punitive Counterstrike. It needs to be tightened up somehow or made to look for a different condition that is then reset at the end of the Runner's turn.

**Comment by nealterrell** [comment]
Should use the new `turn-flag?` system.
