### ISSUE TITLE
Bernice Mai still gets accessed even after unsuccessful trace

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1092]
After Bernice Mai trace fires and is unsuccessful, she should be completely gone from the server - but as it currently happens, she stays there and remains as an option during access.

>Bernice Mai is not set up to trash herself if the trace is unsuccessful.
>but it's a little more involved than just adding `:unsuccessful {:effect (effect (trash card))}`  into the trace, because while that does make Bernice trash, the Runner still sees the "ghost" of the card in the server's contents when accessing, even though it's no longer there.
The card image doesn't stay, but it's still in the list of server contents, so if it had been on R&D the Runner still sees "Card from deck" ​and​ the upgrade as things to access

**Comment by JoelCFC25** [comment]
To be clear, the card is also currently missing the bit that causes it to trash itself upon an unsuccessful trace.

**Comment by queueseven** [comment]
Yeah, old problem. The run is succesful, the `:successful-run` event trigger (`:trace` prompt is created), but then the access code is run, creating the `:runner :prompt`, which contains Bernice May. 

The event system is fundamentally broken in this regard and can't handle such cases.

**Comment by queueseven** [comment]
A workaround would be to manually adjust the prompt in the `:unsuccessful` part, but I don't know if it's worth it.....

**Comment by nealterrell** [comment]
I think I fixed this.
