### ISSUE TITLE
Nasir — is it automated? , Ideas

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#1097]
I do not code, so I apologize if it seems I am out of place by recommending an idea. 

Nasir's ability doesnt seem to be automated, and it makes it a bit difficult/annoying to use the ID. Maybe it could be implemented that, when encountering an ICE, you click on Nasir's ID in order to go down to 0 credits, so as to allow the runner to first use their credits and then click on Nasir to do the rest and show in the log that Nasir's ability fired. 

On the other hand, though this might clutter up the interface, add a button for "go to 0 credits" and a button "gain 5 credits" so as to make going up and down in credits easier for Nasir or in other circumstances that may require manual credit manipulation.

**Comment by JoelCFC25** [comment]
> Maybe it could be implemented that, when encountering an ICE, you click on Nasir's ID in order to go down to 0 credits, so as to allow the runner to first use their credits and then click on Nasir to do the rest and show in the log that Nasir's ability fired.

This is actually precisely the way Nasir works. After the Corp rezzes a piece of ICE, you click the ID when you are ready (i.e., after you've done any spending or used abilities in 2.3 of the timing chart). Pretty soon we are going to have little popup notifications informing the Runner for things that aren't obvious like this. 

![screen shot 2016-01-12 at 10 36 27 am](https://cloud.githubusercontent.com/assets/10407969/12269728/67a7e62e-b918-11e5-8756-80807f05c1f6.png)


You can keep on top of card implementation and unit test status by visiting [our tracking sheet in Google Drive](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/edit?usp=sharing)!

**Comment by benticurus** [comment]
i see, thank you!
