### ISSUE TITLE
muertos gang

### ISSUE THREAD

**Issue by wrathofmine** [mtgred/netrunner#1098]
Just had a game where i trashed Muertos gang (runner tagged) and tried to rez my tollbooth for free.
Log said i rezzed tollboth but ice stayed unrezzed and I had 8 more credits.
For the remainder of the game, no way to rez this tollboth (even after trashing and re-installing it), everything else was ok, even rezzing other ice.

**Comment by nealterrell** [comment]
Did you have more than 8 credits after trashing Muertos? Were there any rez-cost-modifications in play? (Reina, ...). I am unable to reproduce this exact scenario, but I'll keep looking.

**Comment by wrathofmine** [comment]
I was playing against Reina, which explain why I couldnt rez with 8 creds (hum... sorry..).
I should have had 0 creds after trashing the muertos. Game gave me 8 (for a total of 8) and log said I rezzed the tollbooth for free.
Must be Reina that messed up with the free rez. 
Regarding why I wasnt able to rez it manually is probably because I stupidly put my creds manually to 8 before trying to rerez.

**Comment by nealterrell** [comment]
OK, thanks. The Tollbooth didn't rez because Muertos is coded to give you credits equal to the card's rez cost, then call the rez function... but that doesn't take Reina's ability into account. I will change Muertos to rez with no rez cost.
