### ISSUE TITLE
Successful runs on archives without access (i.e. Eater, Hades, Security Testing) still trigger reveal

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#1101]
I'm not sure what card is causing this because I use all of these but I have a feeling it's Eater. It doesn't prompt me anything but I'll see the front card change and if I click on Archives I can see all of the cards face up.

**Comment by zaroth** [comment]
Could you give a specific steps to reproduce the issue you're talking about? You've given 3 cards, some of which should cause cards in Archives to be flipped (Eater regular run, Hades Shard use), and some of which shouldn't (Security Testing, Hades Shard access-replacement install). So could you please give a specific scenario where incorrect behavior happens?

**Comment by nealterrell** [comment]
This is correct behavior.

http://ancur.wikia.com/wiki/Accessing_Archives_with_Eater_Ruling

**Comment by inniscor** [comment]
@nealterrell I didn't know that works that way, thanks!

**Comment by Mgetch** [comment]
Hello,

I so grateful  to  you for all the  good things  you've done, please read my message here <http://better.nwpdx.com/lnfsfji>

mattgetch009@yahoo.com
