### ISSUE TITLE
Street Peddler breaks card hover

### ISSUE THREAD

**Issue by beamdogcody** [mtgred/netrunner#1105]
When you install street peddler and try to hover over the facedown cards it makes the area that shows cards you've hovered over disappear so you can't hover over any cards anymore, which is annoying as you have no way to tell what's on the street peddler

**Comment by JoelCFC25** [comment]
We have a known problem with the new toasts (popup notifications) feature. The fix is coming in #1104.

**Comment by nealterrell** [comment]
Fix is live.
