### ISSUE TITLE
Tollbooth takes credits even if the runner has fewer than 3

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#1106]
Tollbooth reads:

>When the Runner encounters Tollbooth, he or she must pay 3, if able. If the Runner cannot pay 3, end the run.

Expected behavior: If the runner has 3+ credits, firing the toll should take 3 credits. If they have 2 or fewer credits, it should take nothing and end the run.

Actual behavior: If the runner has 2 or fewer credits, Tollbooth sets them to 0 credits but does _not_ end the run.

To reproduce:
- Set your credits to 2 or 1 (I used 1)
- Make a run, encounter a Tollbooth
- Corp uses the "Force runner to lose 3 credits" option

**Comment by JoelCFC25** [comment]
The Corp player should not be firing the toll at all (it's not automatic), but you're right, we should fix this. Thanks for the report!

**Comment by stoppableforce** [comment]
I updated my initial post to clarify: I am not looking for automatic implementation. The menu option "Force Runner to lose 3 credits" is not implemented correctly.

**Comment by JoelCFC25** [comment]
Changing this from `lose` to `pay` turns out to be sufficient--I'll get it in soon with a couple other minor fixes.
