### ISSUE TITLE
Edward Kim doesn't have his ability disabled after accessing operations in Archives

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1107]
There is some code in Kim's ID that would suggest such an interaction with trashed operations was intended:
> `:events {:access {:once :per-turn`
> `:req (req (= (:type target) "Operation"))`
> `:effect (effect (trash target))`
> `:msg (msg "trash " (:title target) (if (some #{:discard} (:zone target)) ", but it is already trashed."))}}}`

It doesn't work though, since currently cards in archives aren't accessed per se - only agendas and specific traps firing from archives are.

**Comment by JoelCFC25** [comment]
History on this one is found in #420.

**Comment by zaroth** [comment]
Looks like this case could use a unit test once it's fixed, then :)
