### ISSUE TITLE
Clicking a card with only 1 card-action should show still show the menu

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#111]
Clicking on a card with only 1 card-action should still show the menu of actions. Currently many Corp and Runner actions are unintentionally triggered because someone clicks on the card to see what actions are available and causes the only action to occur.

From a User Experience perspective, this is bad, as it makes it hard to tell which cards are actually implemented and working. From a game pace perspective, it wastes time because now the player needs to correct their board state.

**Comment by dimarco70** [comment]
Seconded. Having a pop-up m for rezzing and derezzing would avoid several misclicks.

**Comment by JoelCFC25** [comment]
We can now have a system for making Runner one-option cards cancellable, as well as #1034 for optionally doing the same to Corp cards.
