### ISSUE TITLE
Deckbuilder allows you to use 6 copies of a card and still shows as tournament valid

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#1112]
if you type in the cards and use a different number on each line the deck builder doesn't pick up on the duplicated cards, like on this totally tournament legal deck: https://dl.dropboxusercontent.com/u/168938/tournament-valid.png

**Comment by eedok** [comment]
for easy copy/pasting:

Near-Earth Hub: Broadcast Center
49 cards
Influence: 8/8 ●​●​●​●​●​●​●​●​○​○​○​○​○​○​○​○​○​
Agenda points: 20
Tournament valid

Agenda (11)
1 15 Minutes
3 AstroScript Pilot Program ○​○​○​
2 AstroScript Pilot Program ○​○​
1 AstroScript Pilot Program ○​
1 Breaking News
3 Project Beale
Asset (9)
3 Jackson Howard
1 Jackson Howard
2 Jackson Howard
3 PAD Campaign
ICE (12)
2 Guard
2 Pop-up Window
2 Quandary
2 Tollbooth
2 Wall of Static
2 Wraparound
Operation (13)
2 Biotic Labor ●​●​●​●​●​●​●​●​
2 Fast Track
2 Hedge Fund
1 Hedge Fund
3 Hedge Fund
3 Sweeps Week
Upgrade (4)
1 Cyberdex Virus Suite
3 SanSan City Grid ○​○​○​

**Comment by zaroth** [comment]
Nice catch! Thanks for the report, I'll look at it.

**Comment by zaroth** [comment]
Just for the reference, issue #323 mentioned this and my first fix apparently solved the issue only when the number of cards in each line was the same :)
