### ISSUE TITLE
Silhouette triggers successful run twice

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#1114]
Example: when I run on HQ with a security testing it triggers the two credits, asks me for an expose, then triggers again. I've found this causes double viruses on pheromones and hemorrhage. This does not occur when I press "Done" instead of accessing. It may be related to my use of Eater, not sure.

**Comment by JoelCFC25** [comment]
Does this happen every time? There seems to be an increase lately in the reports of doubled effects, so it's possible that latency issues are a factor here.

**Comment by inniscor** [comment]
It seems pretty consistent. In cases when I've already exposed everything on the board I've been able to hit "Done" instead of pressing a card and the effects don't double.

**Comment by JoelCFC25** [comment]
Actually, now that I think about it, this matches the pattern of the problem identified with Retrieval Run, which I've finally verified. If you use RR to install Femme Fatale or Parasite from the Heap, you get this duplicated Successful Run / Jack out prompt. 

Both your issue and those two Retrieval Run cases all have something in common--they use the card targeting system and click something on the game board.

**Comment by JoelCFC25** [comment]
Sadly, this is still an issue. Leela hitting an agenda in R&D and then bouncing an unrezzed card back to HQ yields the duplicate "Successful Run / Jack Out" prompt.

**Comment by nealterrell** [comment]
Fixed again!
