### ISSUE TITLE
Add a method to conveniently save game logs

### ISSUE THREAD

**Issue by spherelin** [mtgred/netrunner#1117]
Would it be possible to create a button or click box either in game or at game setup to allow one or both users to receive an emailed copy of the game log?

**Comment by zaroth** [comment]
I don't think e-mailing game logs will happen, however a button to copy/save the game log in a convenient format would be a nice feature.

**Comment by Saintis** [comment]
The current "game over" screen could have this sort of functionality.

**Comment by NoahTheDuke** [comment]
The game log is now saved, as per #5064. No email or "click to export" yet, but selecting and copy-pasting are trivial.
