### ISSUE TITLE
[Request] Change order of Advance/Score menu on agendas

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#1118]
Assets have the option to advance on the bottom of the context menu.  Sometimes when trying to over-advance agendas, I've found myself reflexively clicking score.  This is normally not an issue, but Mushin No Shin doesn't allow the agenda to be scored until the start of the next turn.  

For consistency, I think it would be good to keep Advance as the last menu item for both card types.

**Comment by JoelCFC25** [comment]
![screen shot 2016-06-23 at 3 16 27 pm](https://cloud.githubusercontent.com/assets/10407969/16318614/88988d6c-3955-11e6-823a-7a8688b14119.png)
