### ISSUE TITLE
Duplication cards

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#112]
Taking back to HQ / Grip the card on TOP of Archives / Heap without opening it (so, only the top card) will duplicate the card that start to exists either in the trash pile and in the player's hand.

**Comment by mtgred** [comment]
I just tried to reproduce your scenario but it didn't lead to card duplication.

If both players drag and drop the same card at the same time, then it leads card duplication. I think it's what happened to you. That issue will be fixed soon.

**Comment by mtgred** [comment]
The issue has been fixed.
