### ISSUE TITLE
Pressing "yes" to pay for "Snare!" with 0 credits broke the game

### ISSUE THREAD

**Issue by leachrode** [mtgred/netrunner#1120]
![image](https://cloud.githubusercontent.com/assets/3635752/12380424/7118af94-bd6a-11e5-86e8-eb82145c94e7.png)

Screenshot of the game situation after we got stuck. The runner Account Siphon'd me down to 0 credits then ran the Snare! in server 1. I accidentally pressed yes when the "Pay 4 to pay for Snare!" popup came up and saw an orange notice saying "You don't have the credits to pay for snare" or something similar but the runner still saw that they were waiting for me to use it. I trashed it manually to end the run but she couldn't end turn.

Possible contributing factor: the snare had just been advanced three times with Queen's Gambit

**Comment by Saintis** [comment]
This is known. I broke it, sorry. Fix is in #1104.

Temporary fix should be to not select "Yes" if you cannot pay.
