### ISSUE TITLE
Unable to edit and choose decks.

### ISSUE THREAD

**Issue by izram123** [mtgred/netrunner#1121]
Recently, 

I have been getting this when i get to my deck builder. I cant make new decks because the ID's are not there to be chosen and the cards cant seem to be verified as their subtypes

![untitled](https://cloud.githubusercontent.com/assets/16754914/12386294/74c9d7ae-bdff-11e5-853d-5fd26f3e773f.png)

**Comment by zaroth** [comment]
Have you tried hard refresh (Ctrl+F5)?

**Comment by izram123** [comment]
the issue seems to be solved. Thanks

**Comment by izram123** [comment]
A friend of mine is having the same issue
