### ISSUE TITLE
Turntable + R&D multiaccess

### ISSUE THREAD

**Issue by thebigunit3000** [mtgred/netrunner#1122]
When running R&D with multiaccess (only seen with Medium and R&D Interface, but there may be others) -- if an agenda is accessed, you can click turntable to choose to swap that agenda.  After that agenda is swapped and the run is over, instead of ending the run, there's a prompt for "successful run / jack out".  (instead of having the normal menu of options)

Hitting "jack out" gets around this, but I (and other people I was spectating) have accidentally hit successful run and accessed more cards than we should have.

I'll upload a screenshot if I can catch it doing this error again.

**Comment by JoelCFC25** [comment]
This is the same issue as #1114--right now anything that does targeting in the UI upon a successful run is resulting in this lingering prompt. No idea what to do about it yet.
