### ISSUE TITLE
Some  card interactions/bugs that shouldnt be

### ISSUE THREAD

**Issue by Grimstringer** [mtgred/netrunner#1124]
You can host on djinn already installed programms where this shouldnt be able

you can play cerebral cast ignoring the made a run cost

you can activate house of knives after accessing cards (psychic field ) and kill someone. that's illegal too

**Comment by zaroth** [comment]
The djinn's host installed program ability is a workaround for clickless install (e.g. SMC, CC, Hayley's ability). Unlikely to be changed anytime soon.

If Cerebral Cast bug is confirmed, it should be easy to do - AFAIK a similar card with a run cost (Power Shutdown) works with the run cost.

3rd requires strict implementation of paid abilities windows - also unlikely to be done soon, if ever.

Please in the future refrain from "grouping" issues on GitHub - it makes them a lot harder to browse. Describe one problem per GitHub issue - and give them descriptive titles. Thanks for helping!

**Comment by JoelCFC25** [comment]
Confirmed Cerebral Cast is missing the requirement--will pop it into my next collection of fixes (waiting on #1077 to get merged).
