### ISSUE TITLE
Successful Indexing run makes R&D non-operable

### ISSUE THREAD

**Issue by dtelad11** [mtgred/netrunner#1127]
After a successful Indexing run, I get the option to resolve the Run Effect. I click it and see the top five cards of R&D. However, now I cannot drag them back into R&D. I can drag them into Archives. While that is happening, the Corp cannot drag them to R&D either. After I move all five cards to Archives and fully resolve Indexing, *sometimes* the Corp can drag the cards to R&D, sometimes he or she cannot.

I played a bunch of Indexing lately, sometimes this happens and sometimes not. I could not identify a clear pattern. I don't think it ever happens with the first Indexing of the game, sometimes it happens with second or third one (sometimes it does not).

Thank you!

**Comment by JoelCFC25** [comment]
What web browser are you using?

**Comment by dtelad11** [comment]
I am using Chrome, tried both on Linux and Windows 7.

**Comment by JoelCFC25** [comment]
There are cases where dropping onto R&D requires *very* precise mouse movements, and sometimes visibly offset quite a ways from where you'd expect it to be. I don't know what causes this, but when I've experienced it the card almost has to be over the discard pile for R&D to get the colored halo on it. Sorry that isn't very helpful, but without clear reproduction steps I am kind of grasping at straws on this one...

**Comment by dtelad11** [comment]
I see what you mean with regards to mouse movement, that would make sense if the Indexing would not prevent the Corp player from dragging into R&D as well. I will pay more attention that time it happens.

I'll pay more attention next time this happens and try to figure out how to reproduce that. Between multiple Apocalypse plays and multiple Indexing plays, interface breaking is not that surprising. Thanks!
