### ISSUE TITLE
Casting Call + Improved Tracers

### ISSUE THREAD

**Issue by enkwolf** [mtgred/netrunner#1128]
Playing the combination showed +1 str bonus on tracers as if the agenda was already scored even though it was sitting in the server. The runner also had 2x tracers in their scoring area.

**Comment by nealterrell** [comment]
This is because agendas installed `:face-up` get their events initialized, to support the Renovation agendas. I didn't account for Casting Call in that implementation. Any agenda that handles events will see this incorrect behavior.

**Comment by greyfield** [comment]
Something similar happens with Government Takeover. I had an opponent Casting Call it and promptly activate it for three credits. It took a good five minutes of FAQ wrangling to convince him that wasn't how Casting Call worked. I worry a newer player may not be quite as sure.
