### ISSUE TITLE
Datasucker strength lowering propagates to the next ICE after trashing Parasited ICE 

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1129]
Steps to reproduce:
- install 2 ICE on one server, rez both, in observed case outer was Next Silver, inner Ichi 1.0
- Parasite NEXT Silver with 0 counters
- Install Datasucker, get 1 virus counter on it
- run on the protected server, use Datasucker counter to trash NEXT Silver
- Ichi 1.0 now has strength reduced to 3, while it should keep it strength at 4

It would also be very nice to add this case to our Datasucker/Parasite unit tests ;-)

**Comment by nealterrell** [comment]
Yeah, all the fiddling with automatically advancing the run arrow has this side effect. @JoelCFC25's function for trashing the current ice should trigger the `:pass-ice` event.
