### ISSUE TITLE
Gordian Blade does not keep its strength until end of the run

### ISSUE THREAD

**Issue by dimarco70** [mtgred/netrunner#113]
Decoder Gordian Blade should keep its strength upgrades until the end of the run. When multiple code gate are encountered during the run, such strength modification is not kept memorized.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

**Comment by dimarco70** [comment]
I have not checked them , but it might be worthy to remember that also
Snowball and Pipeline should follow the same behavior :D

Thank you for your wonderful work!

Mauro

**Comment by mtgred** [comment]
Snowball, Pipeline and Battering Ram already had the right strength logic. Only Gordian Blade was missing it.
