### ISSUE TITLE
Cybernetics Court and Cerebral Imaging not playing nicely together

### ISSUE THREAD

**Issue by jmbostwick** [mtgred/netrunner#1131]
Hey there -- I've notice in multiple games that these two cards (Cybernetics Court and Cerebral Imaging) don't play nicely together, resulting in improperly-calculated maximum hand sizes routinely. The issue seems to be in regards to changing numbers of credits; once credits change, the hand size is recalcluated based on the new number of credits, but consistently does not include the additional bonus from Cybernetics Court.

**Comment by JoelCFC25** [comment]
Thanks for the report--this is essentially the same fundamental issue as #1015. Max hand size adjustments aren't pooled together and applied to the base value.
