### ISSUE TITLE
Ambushes should have a message when the corp declines to use them

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#1136]
lots of people forget to tell when they decline so it results in awkward waiting

**Comment by zaroth** [comment]
When fixing this, also worth considering is the new console, Maya, from [Kala Ghoda](http://imgur.com/a/smvGZ) - it apparently allows the runner to put the ambushes from R&D at the bottom before corp gets a chance to fire them.

**Comment by nealterrell** [comment]
Are we sure on that interpretation? It's missing the language of Film Critic, and "immediately __after__ accessing" has to be different than "whenever you access".

**Comment by zaroth** [comment]
No, not sure. In fact, I suspect you're right and the ambushes can't be prevented as discussed on Stimhack Slack later, due to lack of "stop accessing" part.

**Comment by Saintis** [comment]
Maybe a general msg on optional abilities, such as "`player` declines to use `card`"?

**Comment by JoelCFC25** [comment]
I think this is safe to close now since @Saintis refactored ambushes to use `installed-access-trigger`, which presents a wait prompt to the Runner that is cleared after the Corp decides on activating the ambush.
