### ISSUE TITLE
Imp + Future Perfect can freeze the game

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#1137]

**Comment by beamdogcody** [comment]
also gets broken by Demolition Run

**Comment by PeterH139** [comment]
Screenshot of bug for clarity. The Psi Game prompt remains visible but none of the options do anything. I imped before selecting creds for Psi Game.
![imp future perfect bug](https://cloud.githubusercontent.com/assets/1383575/13036344/cde2e8d6-d35c-11e5-815e-1f87eebaeffe.png)

**Comment by zaroth** [comment]
For the future, if you resolve such freezes, try to use `/close-prompt` command to go forward with the game. Thanks for the report!

**Comment by jcsung** [comment]
Also Maya

**Comment by yang573** [comment]
To clarify what jcsung was saying, using Maya on The Future Perfect can cause issues. Here's a screenshot of one such game.
![screenshot 7](https://cloud.githubusercontent.com/assets/14100935/17572546/23f812f8-5f23-11e6-81db-8754a0b8a556.png)
