### ISSUE TITLE
Ash 2X3ZB9CY in HQ root prevents successful run via Sneakdoor Beta

### ISSUE THREAD

**Issue by SevenCs** [mtgred/netrunner#1138]
My opponent (Spark Agency) installed Ash 2X3ZB9CY in the root of HQ.  I made a run on Archives using Sneakdoor Beta, and when the Ash trace triggered I got my Desperado credit but not the credits from my ID (Gabriel Santiago).  After the run completed (I trashed Ash), I was unable to play Emergency Shutdown, which I assume is because the game state didn't consider my successful run on HQ to be successful.

**Comment by SevenCs** [comment]
Here's the chat log from the game, in case it helps:

SevenCs spends to use Sneakdoor Beta to make a run on Archives.
beckman uses Pop-up Window to gain 1 .
SevenCs sets credit to 6 (-1).
beckman has no further action.
SevenCs continues the run.
beckman spends 4 to rez Bastion.
SevenCs uses Faust to trash Datasucker and add 2 strength.
SevenCs uses Faust to trash Same Old Thing and break 1 subroutine.
beckman has no further action.
SevenCs continues the run.
beckman spends 2 to rez Ash 2X3ZB9CY.
beckman uses Ash 2X3ZB9CY to initiate a trace with strength 4 (4 + 0 ) (prevent the Runner from accessing cards other than Ash 2X3ZB9CY).
SevenCs spends 0 to increase link strength to 0.
beckman uses Ash 2X3ZB9CY to prevent the Runner from accessing cards other than Ash 2X3ZB9CY.
beckman has no further action.
SevenCs uses Desperado to gain 1 .
SevenCs
It didnt' give me my Gabe credits. :/
SevenCs sets credit to 8 (+1).
SevenCs sets credit to 9 (+1).
SevenCs pays 3 to trash Ash 2X3ZB9CY.
SevenCs
and now it's not letting me play a card from my grip
SevenCs
ahhhh, it must be something with Ash's coding that makes it think I didn't make a successful run on HQ
SevenCs trashes Emergency Shutdown from their Grip.
SevenCs sets click to 0 (-1).
SevenCs
I'm playing Emergency Shutdown on Tollbooth
beckman
tollbooth?
SevenCs
yeah :)
beckman derezzes Tollbooth.
SevenCs is ending their turn 15 with 6 and 1 cards in their Grip.

**Comment by kevkcc** [comment]
I had a quick look at this just now and #1085 should fix this.

**Comment by nealterrell** [comment]
A full fix for all lingering Sneakdoor issues is in #1304.
