### ISSUE TITLE
when 7+ remote servers show up

### ISSUE THREAD

**Issue by tehv1s1on** [mtgred/netrunner#114]
luckly i have duo monitors but when someone drops down a 7th server i lose the right side of the screen and cant chat or see the big size cards. Need a scroll bar at the bottom or something. I had to drag to 2nd screen and make one giant window

**Comment by mtgred** [comment]
The easiest solution is to decrease the browser zoom level.

It's not straightforward so i will add it to the FAQ section.

**Comment by tehv1s1on** [comment]
I know this prob isn't the place butI can not seem to login anymore. Anyway to reset my password?
 

     On Friday, February 20, 2015 12:36 PM, Minh Tran <notifications@github.com> wrote:
   

 The easiest solution is to decrease the browser zoom level.It's not straightforward so i will add it to the FAQ section.—
