### ISSUE TITLE
Celebrity Gift Issue

### ISSUE THREAD

**Issue by lightburied** [mtgred/netrunner#1140]
I was playing against a Jinteki: PE deck, and for my opponent's second and 3rd click, he played celebrity gift. However, I did not see cards, nor did they receive credits for the card. We were were at turn 11 when this happened. My opponent tried to reveal cards but ended up looking at his deck and shuffling it multiple times. I don't know if anyone else has had this problem, but it seems like a good thing to fix

**Comment by nealterrell** [comment]
I have never heard of anything like this issue. Did he have 3 credits to pay for the play? Did he get charged 2 clicks and 3 credits?

**Comment by lightburied** [comment]
Yes and yes.

**Comment by JoelCFC25** [comment]
Was there some confusion about what he needed to do? He should have seen the targeting reticule and then selected up to 5 cards in his hand--they get a green halo when selected--to reveal them. There shouldn't have been any looking in his deck, that part sounds very odd.

**Comment by lightburied** [comment]
I don't know. Its been a while since that game. I didn't ask about that. It may have been an odd one-off.

**Comment by JoelCFC25** [comment]
I'm going to close this, as we know the card works and it seems to have been a case of user confusion.
