### ISSUE TITLE
Sundew Problem

### ISSUE THREAD

**Issue by cjchristopher** [mtgred/netrunner#1141]
Sundew gives the corp two credits even when the runner uses their first click to initiate a run on the sundew server.

Observed so far when the run is ended by a piece of ice - not sure if it would still happen if the run were successful and/or the dew was trashed, but in any case, it shouldn't matter - simply initiating the run on the correct server should prevent Sundew from firing.

**Comment by zaroth** [comment]
Connected to #1115 .

**Comment by cjchristopher** [comment]
Seems so, but this was paying out on first click, not second.

**Comment by mtgred** [comment]
Thanks for reporting the issue.

The problem has been solved. The fix will be deployed with the next server update.

**Comment by zaroth** [comment]
There are still problems when a click is gained via Joshua B - Sundew fires on the second click then, not the first one.

**Comment by JoelCFC25** [comment]
And if Wyldside is in play, Sundew won't pay out at all if the Runner does something other than run it with his first click.

**Comment by mtgred** [comment]
This commit fceb19c4eb29050313d59fa05a74fe7cd2ef5eaa should normally fix all cases, including Wyldside and Joshua.
