### ISSUE TITLE
Turntable doesn't switch off Mandatory Upgrades

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1142]
Reproduction steps:

* score Mandatory Upgrades on corp turn
* on Runner turn install turntable and steal a Vitruvius, swapping it for ManUp
* on Corp's turn Corp still has 4 clicks

**Comment by zaroth** [comment]
I bet it doesn't switch off some other persistent effect agendas too, like Self-Destruct-Chips ;-)

**Comment by JoelCFC25** [comment]
Try triggering `:leave-play` on the agenda being swapped away. Also look at #839, because I'm fairly sure that this worked back then.

**Comment by JoelCFC25** [comment]
Now I see that I broke it again at #852.

**Comment by JoelCFC25** [comment]
I'll have a solution shortly--`forfeit` needs to be updated to only call `deactivate` on the agenda if it's in the Corp score area. Right now it's doing it to everything. Will fix it up and write a couple tests.
