### ISSUE TITLE
When an agenda is scored using Plan B, agenda counters on the card in the score area are not usable

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#1146]
I know, Plan B.

When I use Plan B to score an agenda as Titan Transnational, an agenda counter is placed on it but clicking the card in the score area results in a context menu instead of allowing me to use the agenda.

I'm able to work around it by pulling the card from R&D then shuffling and using /counter 0.

**Comment by JoelCFC25** [comment]
It seems that it might matter what the agenda was. Can you supply that detail? I tried scoring a Project Atlas via Plan B in Titan and while a bit unorthodox, I was able to spend the Atlas counter and get the effect. The agenda gave a context menu with "Score" in addition to the standard ability which normally just happens immediately when you click.

**Comment by Merlin8000** [comment]
In my case it was a Project Atlas.  I wasn't able to spend the counter and clicking the menu items did nothing either.  If I score an installed atlas by advancing it, I don't have this issue.  

Did you have to click on the counter number?  When I clicked on the card, All I got was the menu.

**Comment by Merlin8000** [comment]
I just tested again and I think I missed that the ability was one of the menu items (my mind must have assumed it was an "Advance" menu item).  So I guess the actual issue is that it still offers to score.

**Comment by JoelCFC25** [comment]
After researching this, the fact that a scored Project Atlas brings up a context menu is a known and intentional side effect of a different change.  See #1005 for the discussion.

**Comment by Mgetch** [comment]
Hey,

I  think  this app is gonna be  helpful for  you, read more here <http://choice.horsecreekpottery.com/lnezvy>

My best to you, mattgetch009@yahoo.com

**Comment by Mgetch** [comment]
Hi,

Have  you seen  that place  already? It's just spectaculous,  you've got to look at it  here <http://cause.blackdragonbarnworks.com/lnnsdje>

Best wishes, mattgetch009@yahoo.com
