### ISSUE TITLE
Ghost Runner credits are not available for Psi game unless they are taken in advance

### ISSUE THREAD

**Issue by rubyfell** [mtgred/netrunner#1149]
The issue can be duplicated by running a server with Caprice with only one real credit. The Psi game interface only allows spending 0 or 1. 

A workaround is, of course, to take the Ghost Runner credit(s) first, but this gives the corp the advantage of not having to remember that those credits are available. And, once I've taken the credit(s), if they are not spent, they remain in the credit pool (not 100% on that point, but the alternative implies that they are lost).

**Comment by Quarg** [comment]
As a workaround to leaving an incorrect board-state, you can use the /counter command and manually adjust credits that are not spent.

**Comment by zaroth** [comment]
As much as I'd love to see a more convenient solution to using recurring credits/ghost runner ones, this one is unlikely to see any resolution until #362 sees some improvement.
