### ISSUE TITLE
Plascrete Carapase, Tennin & Angel Arena

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#115]
Plascrete and other prevention effects don't trigger when the corp plays a card like Scorched Earth this is a big bug bear as it means the corp get to see more of your cards that are in your hand and can change up the way the game continues.

Tennin ability doesn't work at all for the most part this isn't a problem until you have no advanceable stuff in play as you can't just play the advancement on any of your ICE or Asset to bluff them as other cards or even just for trick of light use which also don't work but can at least be worked around.

Angel Arena dosn't work at all which altho isn't played alot having the ability to work round it by been able to put cards at the bottom of your deck or look at the top card of your deck would be nice.

**Comment by phette23** [comment]
FYI it looks like Angel Arena was just implemented in commit 4683dedc4e8a764286a45c16330fe426c24ad25e today. Not sure how often the actual jinteki.net installation is updated but that specific card's been addressed.

**Comment by mtgred** [comment]
Tennin Institute has been implemented few days ago. Damage is more tricky to implement but it's on the TODO list.

**Comment by PinkWarrior** [comment]
Thanks for the updates it's good to see. I really like jinteki.net it's easy to get your head around.

**Comment by PinkWarrior** [comment]
In regard to damage would it be possible to do the prevention in a manual way? Maybe by giving the runner a prompt when their going to take damage and allow them to reduce it kinda like a trace then they can move cards and tokens them self.

**Comment by mtgred** [comment]
Damage prevention has been finally implemented last week.
