### ISSUE TITLE
Double Drawing on turn start

### ISSUE THREAD

**Issue by nicelammy** [mtgred/netrunner#1150]
Playing yesterday as corp i was able to doubleclick relatively fast on turn start and draw an extra card. Maybe there was a phantom trigger somewhere, or I wasn't reading the board state properly but this could be a ping/input issue.

**Comment by JoelCFC25** [comment]
This is probably fundamentally the same as #468. The discussion in the other issue about possible safeguards against this goes a bit over my head. :) 

I know this is not a very satisfying response, but double-clicking on buttons is not really a good idea in the app. Along those lines, if you can leave just the slightest pause in between clicks when repeatedly advancing an agenda or clicking some card with a single ability, you should be able to keep everything synced up (i.e., clicks or credits spent track with the visible outcome).

**Comment by JoelCFC25** [comment]
We'll continue all discussion of this problem in the original issue that I linked in my previous post.
