### ISSUE TITLE
Chronos Protocol pop-up bugged (Gemini and IHW involved)

### ISSUE THREAD

**Issue by enkwolf** [mtgred/netrunner#1153]
Gemini hits for two separate 1 net damage instances at trace 5. Since they're both fired simultaneously, there is no time to use CP ability first, and the pop-up gets bugged at least in a situation where the "second" net damage already hit an I've Had Worse. Unable to choose a card, had to close manually and ask the runner to discard the chosen card and then close their side of the prompt manually.

**Comment by JoelCFC25** [comment]
I feel like the "kicker" system for the constellation ICE needs to be redone entirely. This same sort of program is likely to exist with Taurus and Sagittarius when the Runner has program/hardware trashing prevention abilities--using prevention on the first target will probably prevent both when it shouldn't. The kicker needs to hold off until the original resolves.

**Comment by nealterrell** [comment]
I have a fix for this coming.
