### ISSUE TITLE
Sneakdoor beta +nerve agent

### ISSUE THREAD

**Issue by Grimstringer** [mtgred/netrunner#1158]
i did sneakdoor run, nerve got 1 counter, ok so far, 2nd run with sneakdoor, i got 1 acess only, nerve didnt get any counters, i tried again, 1 access, i tried again, 0 cards accessed??

should have been 1,1+1,1+2

**Comment by JoelCFC25** [comment]
Thanks for the report. Sneakdoor + Nerve Agent simply won't work right at this time (see #955). As a workaround, right before you hit Successful Run you can use the `/counter n` console command to adjust Nerve Agent's counters to what they should be.
