### ISSUE TITLE
Resolution / Card Size

### ISSUE THREAD

**Issue by ionas** [mtgred/netrunner#1164]
I did not play this game for ages.
From the outside the card sizes are very small compared to the rest of the UI.

I did CMD & + the interface and then used the browser's inspector to decrease font sizes, line-heights and some box heights, its a 5min hack to show the difference:

<img width="1680" alt="screen shot 2016-01-29 at 23 05 55" src="https://cloud.githubusercontent.com/assets/106845/12689414/0b21f34a-c6dd-11e5-867c-d91fea496470.png">
<img width="1680" alt="screen shot 2016-01-29 at 23 04 50" src="https://cloud.githubusercontent.com/assets/106845/12689415/0b566cf6-c6dd-11e5-8ae2-e5fed763a751.png">

... or is it my retina display?

**Comment by nealterrell** [comment]
It is your Retina display :). We make no attempt to scale for high-resolution monitors; the browser's zoom function does that well enough :).

**Comment by jhli** [comment]
It is a standard mac diplay that does hidpi things. When zooming cards stay rather small compared to ultra huge fonts.

**Comment by nemmons** [comment]
With respect, does 1080p still count as 'high resolution'? Unfortunately, zooming only works to a point because the elements on the left of the screen get crowded and then start disappearing, far sooner than the cards actually become visible.
(That being said I think this is a fantastic application and am very greatful to everyone who has contributed to it)

**Comment by nealterrell** [comment]
We could potentially, in the long term, come up with separate scaling measures for the UI vs the game board, but I don't think that will be a priority for a long time. Sorry :(.

**Comment by ionas** [comment]
My tip: You should get away from setting heights of containers and use line-height and paddings. Those line-heights and paddings should be set in REM, so should be font-sizes aside the one in html/body. Then you can add a single setting that changes the html/body font size. By doing so you can scale the whole font related part of the interface. Then one can zoom the interface and shrink/grow the fonts like fitting.

At the moment if I just zoom the interface in firefox, safari, chrome, the fonts grow HUGE and the boxes overlap but the cards are still tiny.

**Comment by Fyren** [comment]
I'm a new player who happens to have poor eyesight (even when wearing glasses).  I really wish I could scale up the UI even more to get larger text, but ran into the same problem regarding only being able to zoom in so far using my browser.  Before I can get text to a reasonable size, the UI no longer fits and I get a vertical scrollbar and can't see the bottommost and topmost rows of cards at the same time.

I think the single biggest thing is that when I hover on a card, the larger display on the right side above the chat/log still has text smaller than is comfortable for me.
