### ISSUE TITLE
Mutate doesn't initialize the installed ICE

### ISSUE THREAD

**Issue by Sonnydk** [mtgred/netrunner#1165]
Wanted to prevent an Ice Wall from dying to a parasite by advancing it, but the only available option was to derez it.

**Comment by JoelCFC25** [comment]
I can't reproduce this yet in my test environment. Were there any other cards in play that could have been pertinent? Any chance you can get a screenshot when the server is up and running again? 

![screen shot 2016-01-30 at 6 39 31 am](https://cloud.githubusercontent.com/assets/10407969/12695709/550a42b6-c71c-11e5-8cf9-4126aa8d8a92.png)

**Comment by Sonnydk** [comment]
The only other factors I can remember from that match was that I was playing against Reina. I think a Xanady was in play. There was a lot of Crescentus derezzing going on, although not on that particular Ice Wall.

I also tried to use the /counter command instead, which didn't do anything. Then I found out there was a /adv-counter command that I should probably have used instead.

I can't say that I've been in that situation often, most likely a first. If it happens again I'll certainly screenshot it. But for now I guess it's "can't reproduce" tag for this report.

**Comment by Sonnydk** [comment]
Alright. I've located the problem. It has nothing to do with Ice Wall or Parasite at all.

It appears to be a problem with Ice that has been installed by the card Mutate. Mutated ice can't fire subroutines.

![ice problem](https://cloud.githubusercontent.com/assets/16972463/12767219/4ec37f5a-ca08-11e5-90c0-071cee4fe5b0.JPG)

**Comment by JoelCFC25** [comment]
Mutate is a really zany chunk of code. But my first guess upon looking it over is that it never does a `card-init` of the installed ICE. This could be a simple fix (famous last words).

**Comment by JoelCFC25** [comment]
Easy one line fix--thanks for the report and for isolating the cause!
