### ISSUE TITLE
Feature Request - Add Discard button

### ISSUE THREAD

**Issue by jjthejetplane246** [mtgred/netrunner#1170]
Since jinteki.net launched, we've never been able to play on mobile devices. The only feature standing in the way of this was not being able to drag cards to the discard pile. I suggest adding a Discard button to the list of options given when clicking on a card. It might be possible to just do this when it is the end of your turn (when you have no clicks left). This would avoid having to hit an extra button every time you wanted to play Hedge Fund for example. Just a thought, keep up the great work guys!

**Comment by jjthejetplane246** [comment]
If this can't be done for complexity reason or otherwise, I'd be curious to hear why. I just think it could be an easy fix (although there could be edge cases I'd imagine, Indexing for example). It would add a lot of flexibility for users which is always a plus.

**Comment by zaroth** [comment]
There is a preliminary drag&drop support for touchscreen in #496. Feel free to test and update it if you can :)

**Comment by zaroth** [comment]
Also, for discarding, there is a `/discard #n` command, for example `/discard #3` - although I heard reports of it not working, so it may need looking into.

**Comment by jjthejetplane246** [comment]
I still can't get it to drag&drop, but the discard command seems to working fine which is perfect! It's a little more effort, but definitely makes mobile playable which is what I was looking for, thanks for the quick response! Love what you guys are doing, keep it up.
