### ISSUE TITLE
Runner Rig Bouncing [Chrome]

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#1176]
Players are reporting an issue with the Runner's Rig bouncing (or shifting) in Chrome browser (latest version: i.e. Version 48.0.2564.97 (64-bit)) 

Please report any specs, screenshots, and/or steps to repeat the issue so we can resolve it

**Comment by Saintis** [comment]
Might be related to flex changes in the latest version of Chrome. https://chromium.googlesource.com/chromium/src/+/29bbe02ea15d8b335c442107db89bd1d003f745e

**Comment by nealterrell** [comment]
This was not happening to me on my desktop, until I went to About and saw that Chrome needed to restart to install an update. Upon restart to version 48.0.2564.97 m, the bug started happening.

**Comment by zaroth** [comment]
It seems to only happen when playing as a runner. An example may be found during [Inermis's stream](http://www.twitch.tv/inermis/v/40156627?t=21m30s) - just watch for 15-60 seconds and see what happens to installed cards.
