### ISSUE TITLE
Detect unreleased cards

### ISSUE THREAD

**Issue by dodgepong** [mtgred/netrunner#1178]
NetrunnerDB now has unreleased cards public on their API, and it seems that people can play with unreleased cards on Jinteki.net. Some players seem to not realize that these cards are not yet released or legal. It would be nice if the legality-checker could detect cards that are not yet released and fail upon detection.

**Comment by zaroth** [comment]
Wouldn't be an issue if #1148 was used.

**Comment by dodgepong** [comment]
That's fair, though since unimplemented cards can "work" in the sense that you can add them to your deck and play with them manually, people might want to have fun playing with unreleased cards on a mutually-agreed basis, in which case fetching unreleased cards is still acceptable. The problem happens when someone makes a game and a random person joins, and their opponent is playing with unreleased cards unbeknownst to them. If there was a way to tip off all players to the presence of unreleased cards in their opponents' decks, that would probably suffice...unless they ignore that notification.

**Comment by zaroth** [comment]
Opting for simplicity right now and keeping 3 deck states:
- Tournament legal (valid deck as per normal deckbuilding rules + MWL compliant + only cards in current rotation)
- casual play (only needs to be valid)
- invalid

I see a quite narrow use case of people wanting to play with unreleased cards, but still stick to MWL or the other way around, but I think these cases aren't too popular and can just be talked and agreed upon.

**Comment by dodgepong** [comment]
That is probably fine, assuming "only cards in current rotation" excludes unreleased cards.
