### ISSUE TITLE
Dragging cards to R & D with an upgrade on R & D is needlessly difficult

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#1186]
Becomes really apparent when playing things like Precognition on an R & D with Caprice Nisei on it

**Comment by JoelCFC25** [comment]
I don't disagree with the sentiment, but "needlessly" could be read in a way that implies something was consciously done to make it as onerous as it is--I very much doubt this to be the case. I've seen the behavior before but never explored it enough to determine that the presence of an upgrade is the key factor, which is useful information for sure.

@domtancredi, I assume it would be useful to catalog browser and OS combos where this is happening, if not all of them.

**Comment by domtancredi** [comment]
@eedok Can you create a step-by-step setup of the game board? 
Also, any browser + OS that you're using?

**Comment by JoelCFC25** [comment]
For me on MacOS Chrome or Safari, you can only drag things onto R&D as the Corp when an upgrade is installed if the **mouse pointer** (ignore the dragged card image) is placed in the green or orange outlined areas shown below: 

![rnd_drag](https://cloud.githubusercontent.com/assets/10407969/12855728/ac43824c-cc06-11e5-95e2-ee5ac04dc930.png)

**Comment by domtancredi** [comment]
So we could change the z-index of the dashboard, creating this view:

http://puu.sh/mX8SF/112d5eb437.png

**Comment by zaroth** [comment]
Is this fixed after #1191?

**Comment by domtancredi** [comment]
Basically, yes but now the issue is reversed. 

Maybe if we have a new enhancement where you hover over it and reveals both to click on in some way
