### ISSUE TITLE
Losing connection to server

### ISSUE THREAD

**Issue by BartlebyFranks** [mtgred/netrunner#1188]
Hey,

I keep losing connection with the server mid-game. It eventually reconnects, but the game appears to be frozen for me. My wifi connection seems okay. thanks.

Eric

**Comment by JoelCFC25** [comment]
Sorry to hear you're having difficulty. Unfortunately, connectivity issues are hard for us to diagnose. There are so many things that could be in play--hardware/software on your end, issues between you and your provider, issues between your provider and jinteki.net's host, etc.
