### ISSUE TITLE
Server is not closing/dismissing ended/disconnected games

### ISSUE THREAD

**Issue by dimarco70** [mtgred/netrunner#119]
And they keep piling up. Now it signals 42 open games, but several of them are played by the same users...

**Comment by Agnate** [comment]
This seems to be happening to me while playing games. My opponent and I seem to get desynced (my commands don't register for him and vice-versa, including chat messages). We leave the game, but I can no longer create or join new games until I refresh the browser.

**Comment by CptHilts** [comment]
This seems to be happening again. Is there a possible fix in the works? Maybe a game cap or time limit?

**Comment by Agnate** [comment]
It was fixed in an update, but the update caused bugs with run events, so he rolled it back until he can get those fixed, I believe.

**Comment by Agnate** [comment]
This bug seems to be back again. Server has 62 games going with multiple containing the same people (most with only a single account in each game). The lag from it is unbearable. :(

**Comment by mtgred** [comment]
The ghost games issue should be fixed now.

One issue causing a lot of unnecessary traffic has been found as well and fixed. The server should be much faster now.
