### ISSUE TITLE
Feature Request: Random roll command

### ISSUE THREAD

**Issue by bmatsuo** [mtgred/netrunner#1195]
I think it would be good if it were possible to roll an N-sided die, visible to both players in the chat log. I don't think it deserves a button/prompt in the UI. But a `/roll` command would be nice.

> /roll 3
> _bmatsuo tosses a die [1-3] and rolls a 1_

I think there are some spots where this could provide minor utility.
- Randomizing psi games (or giving the opponent the appearance of randomization).
- Sometimes you don't know what to do.

**Comment by nealterrell** [comment]
Nice idea. Why would you want it visible to both players though?

**Comment by bmatsuo** [comment]
If the opponent can see the result it is more like a real tabletop where you could see a die rolled by your opponent. I think it adds an interesting element as well because when your opponent knows/believes your decisions are randomized they will behave differently.

**Comment by nealterrell** [comment]
Agreed, but so far the most important (IMO) use case we've presented is for psi games, in which case you 100% don't want the opponent to see your roll. How about printing "bmatsuo tosses a die [1-3]" in the log, and then show the result in a toast only to the rolling player?

**Comment by bmatsuo** [comment]
I don't really think it's a big deal. Before the psi game the player can (in secret) decide to bet `(roll + X)%3`, shifting the roll value by some arbitrary value X. Then the opponent has almost no information from the roll.
