### ISSUE TITLE
Menus duplicate

### ISSUE THREAD

**Issue by jmm13** [mtgred/netrunner#1203]
It happens about halfway through a game- my menu will start duplicating itself and overwriting parts, eventually unable to click on anything because none of it works anymore. I thought at first it was because i upgraded to win10 (firefox as browser), but it now does it on a win7 machine (firefox again) too. it seems to have started sometime on February 7, 2016.

**Comment by munkhi** [comment]
Further to this, just had the same issue. Both were triggered by playing Trope and it occurred at the start of the runner's next turn, where the game attempts to add a power counter to the installed Trope card. The runner's menu/action buttons get overwritten - I have included two screenshots of the menu degradation. First is of general play a few turns afterward where I lost the ability to end my turn (no button!). Then during a run attempt, a button for "Gain Credit" was shown (but non-functional).
![ss](https://cloud.githubusercontent.com/assets/17125240/12889335/509a9602-ce76-11e5-8ae5-5feb2895136f.png)
![ss2](https://cloud.githubusercontent.com/assets/17125240/12889346/576727b6-ce76-11e5-864c-7b5aee10f8e0.png)
Win 10, Firefox 43.0.4

**Comment by jmm13** [comment]
i'm playing trope as well, and now that you mention it- that is when my last game's menus were messed up.  Thanks for tracking it down.

**Comment by domtancredi** [comment]
Guys, it's Trope. There's an issue, already documented, to do with counters on programs that are "non-virus":

https://github.com/mtgred/netrunner/issues/1196

It throws a JavaScript error which creates this duplicate-menu defect. Once this is merged and the server restarted, I bet it'll work.

Try hard-refresh post this implementation and using Trope.

For now, try Trope and see if that recreates it. If it does, it's still present as a defect.

**Comment by JoelCFC25** [comment]
Should be fixed as of last night's restart.
