### ISSUE TITLE
Caprice Not Automated?

### ISSUE THREAD

**Issue by Dissinger** [mtgred/netrunner#1205]
Caprice Nisei triggers after the runner passes the last ice and she didn't fire off despite being rezzed well ahead. I thought it would trigger upon saying no further actions and she never went off and my server was gutted. Caprice is not an optional trigger she doesn't have may in her text box, she must fire if rezzed and so I'm confused as to why she didn't fire. If it mattered he inside jobbed the first ice and derezzed the second, but Caprice only checks for the runner to pass the ice, not how it was done or if an encounter happened.

**Comment by Dissinger** [comment]
http://netrunnerdb.com/bundles/netrunnerdbcards/images/cards/en/04114.png

The relevant card.

**Comment by JoelCFC25** [comment]
In our system, cards like Caprice really need to be manually triggered to avoid a whole host of potential complications. I'll add a note to this effect in the card status sheet to make it more clear!
