### ISSUE TITLE
Constellation Protocol and DBS

### ISSUE THREAD

**Issue by HannibalRex** [mtgred/netrunner#1207]
It was my first jnet game, but I'm pretty sure this wasn't an user error. When I had both of them rezzed at the same time (Shh, secret tech) the automation of both of them broke. As soon as I trashed DBS, the Constellation Protocol worked properly again.

**Comment by JoelCFC25** [comment]
Thanks for the report. There is a big rework of "when your turn begins" handling underway, so I expect it'll get sorted out when that is complete and goes live. Keep an eye on #282 for the discussion and updates!

**Comment by HannibalRex** [comment]
I'll try if derezzing Constellation Protocol before my start of turn will do as a workaround for now. Looks like it's possible to set the number of advancement counters on ice manually, if you have to.

**Comment by JoelCFC25** [comment]
These cards work correctly in tandem now that #1218 is deployed!
