### ISSUE TITLE
Rezzed Hostile Infrastructure + Psychic Field  VS  Adam + Neutralize All Threats

### ISSUE THREAD

**Issue by a340** [mtgred/netrunner#1208]
Played a game as the corp (NEH), runner was Adam.  I had a rezzed Hostile Infrastructure, runner ran on unrezzed Psychic Field.  Upon accessing, Neutralize All Threats fired and trashed the Psychic Field before the psi game occurred.  Runner should have died (psi game first, corp wins, Adam has enough cash/auto trashes Psychic Field with NAT, Hostile Infrastructure fires and kills runner) but that didn't happen because of the early trashing of PF.

**Comment by JoelCFC25** [comment]
There isn't a way of doing this correctly at the moment--the code that handles accessing cards doesn't have a way to "pause" while waiting for the psi result to be determined, even though the event triggers are ordered correctly (`:access` comes before `:pre-trash`).

**Comment by a340** [comment]
No problem, just wanted to bring it up.  Thanks for doing all the work you do.

**Comment by nealterrell** [comment]
I have a fix for this coming.
