### ISSUE TITLE
Punitive Counterstrike deals meat damage for forfeited agendas

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#1220]
I encountered this when forfeiting two three point agendas with Artist Colony. The next turn the corp was able to deal 12 damage despite the agendas currently being worth 0 points. I'm not sure if the same problem exists with Data Dealer or Frame Job.

**Comment by nealterrell** [comment]
It 99% does exist with those too. We record # of points stolen, not the actual agenda(s) stolen, so that will need a change in the core engine.

**Comment by sjohnc** [comment]
https://twitter.com/ANR_RulesWiki/status/694589091241799680

**Comment by zaroth** [comment]
So there's no need for update, I guess :)

**Comment by JoelCFC25** [comment]
Agreed. Further confirmation that this is a reversal of the previous ruling:  https://twitter.com/ANRthoughts/status/700896626299244544
