### ISSUE TITLE
Runner hand size not reset if Bagbiter trashed by Corporate Town

### ISSUE THREAD

**Issue by jcsung** [mtgred/netrunner#1224]
Unfortunately neglected to take screenshot or copy log before leaving game, but description follows:

Was playing as Gagarin versus a Chaos Theory using Opus/Bagbiter.  Runner had 10 credits in hand.  Rezzed Corporate Town at end of previous runner turn and trashed Bagbiter at start of my turn.  On following turn, Runner (10 credits, no hand size modifiers) played Game Day to try to draw to 5 cards, but instead drew to 10.

**Comment by jcsung** [comment]
I see actually that the previous "Theo Bagbiter and brain damage" bug report actually covers this and also one for Cybernetics Court + CI, this should be merged into there, sorry.

**Comment by JoelCFC25** [comment]
No, this is fine as a new issue--Bagbiter's `:leave-play` effect needs to restore base hand size to 5 in addition to dropping the watch state. Thanks for the report!
