### ISSUE TITLE
Harbinger trashed by Corp disappears from game

### ISSUE THREAD

**Issue by AmeliaMesdag** [mtgred/netrunner#1226]
When Harbinger is trashed by the corp (ie Ichi), the card is completely removed from the game state, and is not in archives, the board, or any special areas.

**Comment by JoelCFC25** [comment]
Thanks for the report! If this happens, Harbinger actually gets stuffed into `[:rig :facedown]` like it should...but in the Corp's portion of the state. Whoops!

Wrapping this into a `resolve-ability` for the Runner fixes it.
