### ISSUE TITLE
Director Hass extra click wouldn't go away when trashed

### ISSUE THREAD

**Issue by Lisum** [mtgred/netrunner#1227]
I had a Director Hass rezzed on World's Plaza for at least one turn. The runner ran and trashed Hass, putting it in their score pile. For the remainder of the game, I still received 4 clicks per turn.

**Comment by JoelCFC25** [comment]
Thanks for the report, I've confirmed it. In fact the same problem happens if Worlds Plaza isn't involved at all. This card was modified in a big refactoring at #1185, so I'll probably ask @Saintis to peek at this when he can.

**Comment by JoelCFC25** [comment]
I've got this one isolated now. In the `deactivate` function, line 46 does: 

```   (when (:installed card)
     (when-let [in-play (:in-play (card-def card))]
       (apply lose state side in-play)))```

The problem here is that `(:installed card)` will always be false for Corp cards. Instead this needs to be `(installed? card)`.

**Comment by JoelCFC25** [comment]
Update: I can get the Corp's clicks per turn to go back down if a non-hosted Director Haas is trashed, but still stuck on how to get `deactivate` to work on one hosted on a Worlds Plaza.
