### ISSUE TITLE
Crisium Grid doesn't fire vs. Sneakdoor Beta

### ISSUE THREAD

**Issue by Beermanbarman** [mtgred/netrunner#1229]
As the title reads, more or less! Crisium grid installed and rezzed on Archives should negate the "if successful, treat as a run on HQ" clause on Sneakdoor Beta, but does not.

**Comment by JoelCFC25** [comment]
Thanks for the report. We knew about this one but it's good to have an issue for it. Search on Sneakdoor and you'll find that there is virtually nothing that Sneakdoor does right at the moment beyond use up 2 MU, haha.

**Comment by nealterrell** [comment]
Fix submitted in #1290.
