### ISSUE TITLE
It's A Trap! - "When exposed" is not firing

### ISSUE THREAD

**Issue by MauiChris** [mtgred/netrunner#1230]
When "It's A Trap!" is exposed, it triggers 2 net damage. i don't know when this stop working, it's been 2 week or so since i last played Jinteki. It's currently not firing when the card is rezzed.

**Comment by JoelCFC25** [comment]
I'm not clear on which part is not working for you--the net damage upon expose, or the subroutine? Rezzed cards by definition cannot be exposed. 

Either way, in my test environment both the net damage upon being exposed and the "Runner must trash an installed card" subroutine are working normally. I'm wondering if either you or your opponent had not done a forced refresh of the site lately...

**Comment by MauiChris** [comment]
Hi Joel, 
It's the net damage upon expose. the subroutine is fine.
Chris

**Comment by JoelCFC25** [comment]
Can you confirm that you've done a forced refresh (Ctrl-F5 on Windows browsers, Shift + reload page on MacOS browsers)?

**Comment by MauiChris** [comment]
i guess i'm confusing when exposed & when rezzed... chalk this one up to newbie misunderstanding.
