### ISSUE TITLE
Fisk + Daily Business show interaction: only last draw can be put back

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1233]
As per Joel's observation:
> FIS + DBS: the Corp is correctly given 4 cards, but only the final 2 are available to select as the one to put on the bottom of R&D.

**Comment by nealterrell** [comment]
I think this could be solved with the same tweak I did for #1288: have FIS suppress the corp's draw event, then trigger it once with all cards that were drawn. DBS would then allow choices to target any of the targets of the draw event.
