### ISSUE TITLE
Make Adam pull directives from DB instead of making him include them in his deck

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1239]
A bandaid on the Adam situation was put in place in #1232. However, it's not ideal. As per @nealterrell:

> the game engine doesn't have the ability to load cards from thin air; the web server sends the entire decklist to the game server when creating a game, and those are the only cards the server knows about.
> This will need to change for the spoiled card Rebirth

**Comment by zaroth** [comment]
As per @saintis, generating cards code is at create-deck in core-turns.

**Comment by Saintis** [comment]
Maybe label this as dev...

Will have a look at this and see what can be done, should be relevant for Rebirth as well.

**Comment by nealterrell** [comment]
This can be done now.
