### ISSUE TITLE
Globalsec Security Clearance + The Supplier = Stuck

### ISSUE THREAD

**Issue by scifantasy** [mtgred/netrunner#1241]
With both The Supplier (with hosted cards) and Globalsec Security Clearance in play, the following happens:

"Start Turn" doesn't start turn.

Once you've clicked "Start Turn," typing anything in the chat bar triggers "Start Turn" to become "Take Clicks," at which point The Supplier activates.

Globalsec Security Clearance never activates.

This looks like a result of the new start-of-turn stuff, naturally. Law of Unintended Consequences...

**Comment by JoelCFC25** [comment]
Thanks for the report.  @nealterrell, here's a snippet from the REPL: 

```game.main=> Error  do start-turn nil #<ClassCastException java.lang.ClassCastException: java.lang.Boolean cannot be cast to clojure.lang.IFn> 
Stack trace: [game.core$card_flag_fn_QMARK_.invoke(core-flags.clj:18), game.core$start_turn$fn__4090.invoke(core-turns.clj:125), clojure.core$filter$fn__4264.invoke(core.clj:2605), clojure.lang.LazySeq.sval(LazySeq.java:40), clojure.lang.LazySeq.seq(LazySeq.java:56) ... ```

**Comment by JoelCFC25** [comment]
`true` is not a function, so if we change the line in GSC from: 

`:flags {:runner-phase-12 true}`   to: 

`:flags {:runner-phase-12 (constantly true)}`

...all seems to be well!
