### ISSUE TITLE
Blackguard + add'l costs

### ISSUE THREAD

**Issue by TalionKris** [mtgred/netrunner#1244]
Currently, using Blackguard forces the rez of cards like Archer, which it shouldn't, due to the ruling about additional costs (i.e. the Runner can't force the Corp to pay them).

Here's the current list of cards it interacts with:

Archer
Bribery
Cortez Chip
Enforcer 1.0
Running Interference

**Comment by zaroth** [comment]
The runner's cards you mentioned look pretty situational and rarely played, especially in this situation. I'd rather worry about:

Corporate Town
Ibrahim Salem

**Comment by JoelCFC25** [comment]
Archer, Enforcer 1.0, Corporate Town, and Ibrahim Salem look like they can be handled pretty easily--`(when (:additional-cost (card-def target)))` blah blah, throw an optional prompt at the Corp player asking if they want to rez or decline. 

Bribery and Running Interference apply `rez-cost-bonus` to their targets and are contingent on mid-run trickery like Raymond Flint or Snitch. I don't remember how these bonuses are represented in state so I don't know offhand if Blackguard could pick them out.

**Comment by zaroth** [comment]
Also, a big one - **Hacktivist Meeting**.
