### ISSUE TITLE
Awakening Center and Breaker Bay Grid interaction

### ISSUE THREAD

**Issue by NightComesOn** [mtgred/netrunner#1246]
Unlike ice protecting the server, ice hosted on Awakening Center are considered to be "in the server." As such, Breaker Bay Grid should reduce the rez cost of that hosted ice.

**Comment by JoelCFC25** [comment]
Thanks for the report. For any enterprising contributors looking to get their feet wet, the `:req` on Breaker Bay Grid needs to be expanded to check the `:zone` of the target's host, if it has one.
