### ISSUE TITLE
Accessing "OK" when accessing HQ

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1247]
A bug spotted in a spectated game, the second time I saw it happen with Leela:

Corp advances a card in Server 1.
Corp advances a card in Server 1.
Corp advances a card in Server 1.
Corp uses AstroScript Pilot Program to place 1 advancement token on a card in Server 1.
Corp scores Global Food Initiative and gains 3 agenda points.
Runner can access cards in HQ by clicking on Gang Sign.
Runner can access cards in HQ by clicking on Gang Sign.
Runner can access cards in HQ by clicking on Gang Sign.
Runner uses Gang Sign to access 2 card from HQ.
Runner accesses Sweeps Week.
Runner accesses Swordsman.
Runner uses Gang Sign to access 2 card from HQ.
Runner accesses Swordsman.
Runner accesses Data Raven.
Runner uses Gang Sign to access 2 card from HQ.
Runner accesses Sweeps Week.
**Runner accesses OK.**

**Comment by zaroth** [comment]
It may be very hard to track, so if anyone can produce reliable reproduction steps, it'd be most welcome.

**Comment by JoelCFC25** [comment]
Keep an eye out for this one--I have a strong suspicion that #1328 fixed it, though.

**Comment by zaroth** [comment]
Main issue in #1662.
