### ISSUE TITLE
Museum of History counts unrezzed copies when determining how many cards can be shuffled back

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1248]
Museum of History is missing a `(rezzed? %)` check in the filter that checks for how many active copies are installed.

**Comment by benhosp** [comment]
This seems to be back.

**Comment by JoelCFC25** [comment]
I'm not able to replicate this yet. With 1 rezzed copy of MoH and when unrezzed copy, I am prompted to choose just a single card to shuffle back into R&D.

**Comment by benhosp** [comment]
It's consistently offering to let me select more cards (I have to manually click on "done") when I have more than one copy installed.
<img width="1518" alt="screen shot 2016-07-17 at 2 35 20 pm" src="https://cloud.githubusercontent.com/assets/8769601/16954912/b595d2b6-4da0-11e6-8a7d-067daf22e6d3.png">
