### ISSUE TITLE
Crash Space has a blank menu option

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#125]
Looks like Crash Space has a blank menu option for using the credit on it for removing tags. Probably a general bug related to all token/credit-removal options, though.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

**Comment by Agnate** [comment]
I had a feeling my fix wasn't sufficient. Sorry for the bad code I submitted!
