### ISSUE TITLE
Turntable used to give Mandatory Upgrades to Corp doesn't add clicks-per-turn for Corp

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1260]
Apparently Joel in #1183 didn't foresee that someone might actually want to GIVE someone mandatory upgrades via turntable (and I don't blame him for that, it's a super obscure case). In the case where ManUps are turntabled away for another copy of ManUps, the clicks are properly taken away for the stolen ManUps, but they aren't given back for the one that's given in exchange.

**Comment by JoelCFC25** [comment]
It's actually worse than you describe. First, giving the benefit of a ManUps swapped back to the Corp is probably the same bug as #1125. 

Next, I kind of punted on deactivating the agenda swapped away from the Corp and did a `doseq` deactivate on *everything* in the Runner's score area. So if you either steal or swap a ManUps first and then do more Turntabling later in the game, ManUps (and each copy if there are multiple) will drop the Corp's clicks per turn every time. So this needs to narrow things down to find the precise `:cid` of what was just swapped.
