### ISSUE TITLE
Darwin bugging out on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by Arepo** [mtgred/netrunner#1262]
Whenever I play the card (in any browser) the start of the turn goes weird - clicking on 'start turn' has no effect until I start clicking around, often for over a minute. Then I don't get the Darwin prompt, and have to add counters and deduct money manually.

**Comment by Saintis** [comment]
@nealterrell recently rewrote the start of turn triggers. Did you get a button stating "Take Clicks" where the "Start Turn" button used to be?

The intended use is for you to click on Darwin if you want add a counter, and then click "Take Clicks" to start your turn.

Did you have any other cards that trigger on the start or your turn installed also, maybe a Wyldside or Aesop's?

If you could also provide a screen-shot of the issue happening it would help us track down the problem.

**Comment by JoelCFC25** [comment]
This is the same bug as #1241.  The first line of Darwin needs to change from: 

`:flags {:runner-phase-12 true}`   to: 
`:flags {:runner-phase-12 (req true)}`

**Comment by Arepo** [comment]
@Saintis In case your questions are still relevant:

> Did you get a button stating "Take Clicks" where the "Start Turn" button used to be?

Yeah, once it starts responding again this is the first change.

> Did you have any other cards that trigger on the start or your turn installed also, maybe a Wyldside or Aesop's?

Quite a few - Wyldside, Data Folding, Daily Casts etc. No others with optional effects though.
