### ISSUE TITLE
Removing tags does not reduce Resistor strength

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#1266]
Removing a tag with the action does not reduce the strength of a Resistor.

This specific one had a parasite on it so was not trashed when the tag was removed.

Please see attached screenshot. Note Runner has 0 tags but Resistor is at 1 strength.

<img width="1440" alt="screen shot 2016-02-21 at 21 29 26" src="https://cloud.githubusercontent.com/assets/13198563/13205603/924ec8c6-d8e3-11e5-941a-8ecbb7eb0e73.png">

**Comment by JoelCFC25** [comment]
We could probably add an event for `:removed-tag` and have Resistor listen for it, then doing `update-ice-strength`.
