### ISSUE TITLE
Leela and HQ Multiaccess with bounce effects.

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#1271]
If there are less cards in the Corporations HQ/hand prior to accessing than the total amount Leela is allowed to access (HQI's, Legwork) and if an agenda is stolen, Leela cannot access additional cards up to the allowed maximum after a bounce.

eg. Corp has 2 cards in hand, Leela has 2 HQI's installed on the board.
Successful run on HQ results in accessing cards, Leela steals an agenda on the first access, bounces a card to HQ. A second access is triggered, but a third is not.

Run/access on HQ prematurely ends.

**Comment by nealterrell** [comment]
:( I don't see this one getting resolved for a while. The accessed cards are determined when successful run is triggered; "Access card from HQ" is just a UI trick to make you think the next card you access is randomly determined when you click the button. HQ multiaccess with Leela will never access a card bounced during the middle of the multiaccess, and I can't think of an easy fix off the top of my head.

**Comment by nealterrell** [comment]
I might be able to fix this next week. I'll let you know.
