### ISSUE TITLE
goog is not defined on self host server

### ISSUE THREAD

**Issue by glass4pk** [mtgred/netrunner#1272]
I build the progrom on a server of windows 2012.
I follow the guild and build up successfully. But when I run it and access it at port 1042, it doesn't run well.
The menus didn't show up. I F12 it and it said that " goog is not defined", before it is "Unexpected token < " on the  html line. 
![error of jinteki](https://cloud.githubusercontent.com/assets/1888886/13245907/5467c1f2-da4b-11e5-9540-6bf4e79d12c3.jpg)

**Comment by aaryn101** [comment]
:+1: I am seeing this as well after using Docker Compose to bring up the environment.

**Comment by glass4pk** [comment]
: = (
can't find the bug...
looks like some of the file is missing while compline the Jar or sth...
I just build it follow the guild from the github index, didn't build up the development guide.
Should I follow the development guide and build up to find the bug ?
Or should I just delete the progarm and redo everything?

**Comment by zaroth** [comment]
For the easiest possible setup, I'd reccomend taking a look at https://github.com/astrostl/nrdev

**Comment by mtgred** [comment]
The problem is your browser can't find the compiled Clojurescript file in dev mode.

You have to run `lein figwheel` and keep it running. The compiled Clojurescript files might be missing because you stopped Figwheel.

**Comment by aaryn101** [comment]
Is the Docker Compose environment supported?

After running `docker-compose up prod` or `docker-compose up dev` I see these same errors.

**Comment by glass4pk** [comment]
https://github.com/astrostl/nrdev 
This is great. I didn't find this at the first time ...
But then I want to translate the pages for our guys, so I gonna need to setup...
Thanks everyone , really helps a lot !
