### ISSUE TITLE
Globalsec Security Clearance 

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1273]
It doesn't appear to subtract a click from the Runner.

**Comment by Kiv** [comment]
Possibly it subtracts the click before 4 clicks are added instead of after the 4 are added?

**Comment by JoelCFC25** [comment]
The Wyldside+MaxX fix in #1254 looks like the exact fix required for this.

**Comment by nealterrell** [comment]
A little trickier since it's "you may", but the same kind of tweak should work. I can tackle it on Friday unless someone else wants to dive in.

**Comment by nealterrell** [comment]
Coming in #1283.
