### ISSUE TITLE
Public support is repeatedly scored at the beginning of corp turn after turntabling

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1276]
Public support scored. Agenda also turntabled later in game. Beginning of corp turn, Pub Support is scored again at the beginning of every corp turn.

**Comment by tolaasin** [comment]
bug appears after turntabling

**Comment by JoelCFC25** [comment]
Thanks for the report. This is a Turntable problem that I described in #1260. I will have a fix for this very soon.
