### ISSUE TITLE
Accelerated Diagnostics - order of prompts is confusing

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1278]
If you use Accelerated Diagnostics on operations that themselves have prompts (such as Shipment from SanSan which prompts for # of counters and target or Interns which prompts for target card and target server) the nested prompts seem to get all mixed up with each other and with AD asking you to play more Operations. 

It makes it easy to misclick and decline to fire the rest of the operations in the AD, which then leaves them stuck in the exile zone.

Would be it be possible to have the first AD operation resolve all its other prompts, before prompting for the 2nd AD operation?

**Comment by Kiv** [comment]
Discussed with Joel the idea of fixing the interleaving prompts issues by having AD simply moving the 3 cards to the exile zone and associating those cards with an event handler that makes them playable from the exile zone. 

At that point AD's job is done and the user can click one at a time on the operations to fully resolve each one before starting another one. 

The typical use case for this is Power Shutdown combos, where there will always be 3 operations in there so it's fine to manually drag any non-operations to the Archives afterwards.

**Comment by nealterrell** [comment]
I have an improvement coming in #1494, which should be future-proof.
