### ISSUE TITLE
Feature Request: Identical cards overlap

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1279]
It's common in play to overlap identical cards to save space on the board. Examples include un-iced servers containing nothing but PAD Campaigns, recurring credit cards like Prepaid VoicePAD, and hardware with passive effects like HQ Interface. This would be a pretty major feature and require a lot of careful design, but given the horizontal nature of the corp meta I think it would be extremely welcome.

From what little of the code I have read, it would mostly be a matter of drawing cards with the same names in overlapping position. Situations in which those cards have tokens (mostly recurring credits) would be more complicated, as you would want to combine the tokens into a single pile while overlapped. It could be that a few new card tags is all that is needed; something like `:stackable`, `:stackable-recurring-creds`, etc. I think tags would be the best way to go as some cards with counters you would never want to stack (like Imp).

The last complicated scenario that comes to mind is overlapping servers. Probably the best way to do this would again be to overlap the cards with a small margin to the left for the cards on the bottom, and then stack the server titles under one another starting from the top of the topmost card.

If there is any traction on this feature I'd be glad to put some mock-ups together. I'm reading though the Clojure manual at the moment so I might even hop into development if I feel confident.

**Comment by zaroth** [comment]
There already is a solution in the works to the asset spam by @domtancredi . As for the approach described here, I'm not convinced the resulting complications/edge cases are worth the hassle...

**Comment by NoahTheDuke** [comment]
Implemented in #4326
