### ISSUE TITLE
Feature Request: Heap/Archives movable sorted popup

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1282]
The biggest thing I miss about OCTGN is its handling of the heap view.

In OCTGN, you can view a popup that shows all cards in your heap, and this popup is draggable and resizable to any convenient location on the screen. The view is sorted alphabetically to make it easy to scan through, and if you have multiple cards with the same name and facedown state they're grouped together with a "2x" on them. You can open your heap and also the opponent's heap.

On Jinteki I'm constantly opening and closing the popups to check what is where, especially playing MaxX or knowing what Clone Chip can target. It could be a big usability win to have this info more easily visible.

**Comment by NoahTheDuke** [comment]
Not going to implement this. Currently outside our skill set and focus
