### ISSUE TITLE
Stacking Daily Business Show's

### ISSUE THREAD

**Issue by fabiodrucker** [mtgred/netrunner#129]
When multiple DBS's are rezzed this happens:

1) You draw cards A, B, C.
2) It asks: Which of (A, B) you want in the bottom.
3) If you pick A, it asks (usually) which of (B, C) you want to put in the bottom. However, sometimes it asks you which of (A, C) you want to put in the bottom. If you pick A again, nothing goes to the bottom and you "draw" two cards total instead of one.

Since there's no manual way to put things on the bottom of R&D, recovering manually from this is hard.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
