### ISSUE TITLE
No board updates on Firefox

### ISSUE THREAD

**Issue by Flutterella** [mtgred/netrunner#1292]
Hi,

sometimes when playing on Jinteki.net, I will be disconnected, get a prompt saying reconnecting was succesful but any subsequent changes to the board or messages in text won't be displayed. Oddly enough attempting to say change credits or say something in text will show up for my opponent.

Windows 7, Firefox

**Comment by zaroth** [comment]
We do need some more robust reconnect framework, that is true. For details, look at #418.
