### ISSUE TITLE
Blacklist + Harbinger interaction

### ISSUE THREAD

**Issue by kevkcc** [mtgred/netrunner#1295]
Steps to reproduce:

1. Corp rezzes Blacklist
2. Runner trashes Harbinger (Aesop's or something)
3. Harbinger isn't installed facedown.

The problem is :trash-effect puts the card in the heap before the :effect is fired, normally this isn't a problem but Blacklist obviously prevents this. Perhaps we need a new key :pre-trash-effect? I took a look and :pre-trash is something else entirely.

**Comment by JoelCFC25** [comment]
Would it be too crude to just add a check to Harbinger's `:req` to see if `:discard` is in `[:runner :locked]`?

**Comment by nealterrell** [comment]
It's a touch crude, but I think it's a fine solution.
