### ISSUE TITLE
Darwin makes 'Start Turn' button unresposive for runner

### ISSUE THREAD

**Issue by shizusreq** [mtgred/netrunner#1296]
Hi,
When Darwin is installed it seems to introduce a delay at the start of the runner's turn. The runner's 'Start Turn' button remains unresponsive for a few seconds. Usually when I post something to chat it turns into the 'Take Clicks' button and I can proceed  with my turn. Happens pretty consistently.

**Comment by Saintis** [comment]
Do you have anything else installed that would cause the "Start of Turn" window to happen (as described in https://github.com/mtgred/netrunner/pull/1218), e.g. a Daily Casts or Wyldside?

**Comment by JoelCFC25** [comment]
This has been fixed in #1274, but there hasn't been a restart since it was merged so it's not live yet.

**Comment by shizusreq** [comment]
Cool, sorry for the double.
Missed that thread.
