### ISSUE TITLE
Adjusted Chronotype does not prevent losing a click with Troll encounter

### ISSUE THREAD

**Issue by josemgarcia** [mtgred/netrunner#1297]
If I am not mistaken, Adjusted Chronotype should prevent losing a click when the on encounter ability of Troll fires and the runner loses the trace.

Now, I ran on my last click to R&D, while having a Starlight Crusade Funding and a Gene Conditioning Shoppe, so I already lost a click, but could have used Adjusted Chronotype again. I clicked on the "Lost 1 click" prompt, but it ended the run instead saying that I couldn't lose a click.

**Comment by JoelCFC25** [comment]
My "haven't investigated this fully" take is that because Troll uses `(pay state side card :click 1)`, the required `:runner-loss` event is not triggering.
