### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by t4eaxel** [mtgred/netrunner#13]
Important:
-Improve chat so we can see the other people who are currently logged-in/online.

Not Important.
-A tool of some sort so we can help you with adding more card programming. 
-A client version would be nice.
-This is kinda not that important but if our playing field looked similiar like this it would be awesome http://cf.geekdo-images.com/images/pic1396996_md.jpg

**Comment by zaroth** [comment]
Moved friendlist suggestion to #1253. Try to keep the issue titles  descriptive, it really helps with bookkeeping.

**Comment by Heartthrob-** [comment]
yeah sorry about that. It's been ages since I submitted all of these bugs.
Thanks for all the work you guys do btw, it's amazing.

Spencer
