### ISSUE TITLE
Feature request: add click symbol to log entry for normal runs made not through card abilities

### ISSUE THREAD

**Issue by raistdart** [mtgred/netrunner#1302]
Hi there. Forgive me if this has been posted elsewhere or is in the wrong place, but I've not used this site before and my cursory search revealed no similar issue pending.

When the runner makes a normal run (sans card), the game log shows the line of text saying that "so-and-so makes a run on such-and-such server," with no click symbol in the line. However, when running via a card, such as account siphon, the click symbol is shown in the line of text describing the action.

I find that, when perusing the log and tracking the runner's actions (whichever side I am playing), I often overlook those lines without the click symbol and find them harder to identify. Would it be possible to change the text to "spends [click] to make a run on server" instead? Thanks!

**Comment by nealterrell** [comment]
Yep, should be easy.

**Comment by JoelCFC25** [comment]
It will be a good addition for the point in the future when we can handle additional run costs...just so you can see "Runner spends [Click][Click][Click]" to run a Ruhr Valley with ELP active (!). Or there could be future cards that tack on additional credit costs to runs, who knows.

**Comment by raistdart** [comment]
Sorry to add this on after the initial request, but would it also be possible to add the click symbol in the log for clicks used by the corp to advance cards? I think this would also make the game log a lot easier to read. Thanks!

**Comment by meatcompute** [comment]
Starting on this
