### ISSUE TITLE
Caprice not ending the run in 4.3 run timing window

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#1309]
I don't know how to reproduce this, I am only recording a game log from someone who reported this in chat. Runner is running on Server 2, containing an unrezzed ice, Caprice Nisei and a face-down Project Atlas.

SanGURU makes a run on Server 2.
Anarchistas has no further action.
SanGURU continues the run.
Anarchistas has no further action.
Anarchistas uses Caprice Nisei to start a Psi game.
SanGURU spends 1 .
Anarchistas spends 0 .
__Anarchistas uses Caprice Nisei to end the run.__
__SanGURU steals Project Atlas and gains 2 agenda points.__
__SanGURU pays 1  to trash Caprice Nisei.__

Valencia vs. Titan. Nothing terribly remarkable going on. Jackson rezzed in Server 1. Runner has Datasucker, Corroder, Mimic, Grimoire. 

The most interesting bit is this screenshot from later in the game:

![image](https://cloud.githubusercontent.com/assets/10083341/13556007/90c926c6-e384-11e5-9f97-8e953b3eca5e.png)

I'm not sure what the yellow half-highlight is on Caprice, but it may be related? Perhaps not, as it went away from I left and rejoined the game.

**Comment by zaroth** [comment]
just a shot in the dark - have you tried firing caprice in 4.3 'action before access' window to reproduce the issue? it has caused some similar issues in the past, and the log indicates that caprice was used in this window (albeit incorrectly, since caprice should fire as the first thing in 4.1 window).

**Comment by nealterrell** [comment]
It's definitely from using in 4.3. @Saintis is working on it.
