### ISSUE TITLE
Chairman Hiro bug

### ISSUE THREAD

**Issue by Sabin76** [mtgred/netrunner#1312]
Chairman Hiro was trashed by the corp in a game, but was immediately sent to my score area.  He tried to drag him off to trash again, but it kept being added and the points racked up until I won.  When I dragged it off, it did the same thing.

![jinteki bug hiro](https://cloud.githubusercontent.com/assets/13073029/13561875/bae9239a-e3e6-11e5-91da-0c848052c677.PNG)

**Comment by zaroth** [comment]
Seems as the same issue as #1181, which already has fix in the master tree. I don't think it's deployed on the live server yet, though.
