### ISSUE TITLE
Employee Strike functionality

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#1313]
Initially I thought this card hasn't been fully implemented. But the card automation spreadsheet says full functionality. So I'm unsure whether if this is a bug or not, but figured I'll just report it.

As I play Employee Strike a lot, I've had to resolve a lot of effects manually. The most prominent example is Haarpsichord Studios.
1 - Runner makes a run and steal an agenda
2 - Employee Strike is played
3 - Runner accesses another agenda (same turn) but "you've access but cannot steal" prompt is shown

Other examples include:
Cybernetics Division - hand size has to be manually added.
Tennin Institute - corp still gets prompt when their turn begins.

It works fine with identities like Spark Agency, Weyland: Building a Better World, and Jinteki: PE.

**Comment by titonosfe15** [comment]
Also don't work in RP. Causing Fatal error when the runner try and inside job in a remote.

**Comment by GrantZilla1979** [comment]
Another RP bug -

Runner plays Employee Strike - should be able to then run all remotes.  Only centrals are available to run when command is clicked.  Issue persists when current is manually trashed.  However seems to return to normal functionality at beginning of next Corp turn but only if ES remains out of play.

**Comment by nealterrell** [comment]
I can't replicate (heh) the Inside Job issue, but I have identified and fixed Employee Strike and Cerebral Static interactions with:

* Tennin, Blue Sun, MaxX: disable their special flags related to start-of-turn effects
* Cerebral Imaging, Chaos Theory, Cybernetics Division, Harmony Medtech, and NBN: TWIY (card text that doesn't always tie to in-game events, usually a one-time thing)
* Haarpsichord Studios, Replicating Perfect (special cases)

**Comment by Repulze** [comment]
Encountered this against SYNC. Paid 3 credits instead of 2 for removing tags.
