### ISSUE TITLE
Resize handle for player's hand

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1318]
When playing Cerebral Imaging it's very difficult to see anything once you have 10+ cards in HQ. On OCTGN we used to be able to drag and resize the HQ view to make more space and see cards clearly.

**Comment by queueseven** [comment]
Should now be possible since the log pane is also resizable now. I'll take a look if I find the time

**Comment by domtancredi** [comment]
So basically, add a scrollbar to HQ // Grip?

**Comment by domtancredi** [comment]
Haven't had a ton of time... adding a scrollbar may be ideal. Or resizing it with handles/grips.

**Comment by danhut** [comment]
Closed via #2902
