### ISSUE TITLE
Donations/volunteers for support/reliability?

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#132]
I love this project.  Its only downside is the relatively poor performance and reliability of the production app. 

Question for benevolent dictator @mtgred: Is there any way that support in the form of donations or some devops magic could improve reliability?  I for one would be happy to chip in on the former and help source some of the latter if that's helpful.

Just trying to understand if there's a performance bottleneck related to hosting costs or production setup that we could improve.  If anyone else seconds this sentiment or has skills to donate this is the thread.

**Comment by arbiterofcool** [comment]
I have devops skills and some related hosting capacity. Is this something that can be coordinated with me?

**Comment by athayn** [comment]
Agree. Put a donation banner on the front page. I think the player base would endure that over the lag issues.

**Comment by JHonaker** [comment]
@mtgred I've been talking with some people on the Jinteki chat. I'm planning on trying to work on some async capabilities in the engine.

**Comment by eah13** [comment]
There's been a noticeable difference in performance lately.  I think most of the credit still goes to @mtgred but thanks everyone who's chipped in!

**Comment by eah13** [comment]
Closing this issue for now.
