### ISSUE TITLE
Legwork run shows 'Runner accesses OK' as additional log

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1325]
Legwork run from Geist, chat says
runner accesses Enigma
runner accesses Assassin
Runner accesses OK.
Runner accesses Adonis Campaign.

**Comment by tolaasin** [comment]
4 cards in HQ at the time

**Comment by JoelCFC25** [comment]
Thanks for the report. We have this in already at #1247.

**Comment by tolaasin** [comment]
Ok. I did search for legwork in the issues list first and it didn't come up.

**Comment by JoelCFC25** [comment]
Yeah sorry, I forgot that the earlier one wasn't specific to Legwork, but the root cause I think is the same--multi-access of HQ. I'm hoping both of these will be taken care of by #1328.

**Comment by JoelCFC25** [comment]
I am pretty confident this is fixed now, but please report it if you see it again!

**Comment by zaroth** [comment]
Main issue in #1662.
