### ISSUE TITLE
Apex ability facedown installs give negative effect

### ISSUE THREAD

**Issue by enkwolf** [mtgred/netrunner#1327]
Whenever Apex installs a card facedown with his ability and the card has an ongoing ability that affects hand size or MU (or probably any of the left hand dials), the card's effect is applied negatively. examples:

Brain Cage: -3 hand size
Q-Coherence Chip: -1 MU
Heartbeat: -1 MU
(probably all similar cards, but these are the ones in my deck)

I guesstimate that the game is removing the effect of the card when it goes facedown (which is required behavior for Apocalypse), but since in this case the effect was never granted in the first place, the outcome is negative modifiers. 

I do not remember whether this happens with Hunting Grounds or not.

**Comment by JoelCFC25** [comment]
It seems that the changes in #1331 have (however unwittingly) fixed this!
