### ISSUE TITLE
Mumbad Construction Corp + Dedication Ceremony

### ISSUE THREAD

**Issue by greyfield** [mtgred/netrunner#1332]
When you use Dedication Ceremony on Mumbad Construction Corp and then move the tokens you just put onto a new agenda, Jnet refuses to let you score the agenda that turn. Presumably it links the DC "can't-score" status to the advancement counters instead of the card given those counters.

**Comment by JoelCFC25** [comment]
Thanks for the report. Someone spotted this in chat already and it's been fixed in #1328. When that gets merged and deployed it'll work correctly!
