### ISSUE TITLE
gabe and crisium grid

### ISSUE THREAD

**Issue by fejj06** [mtgred/netrunner#1333]
hello opponent had crisium grid installed in hq, i had gabe with security testing, john masonori, and can't recall if desperado. when ran hq, asked to access cris or hand, clicked crisium grid and something like an infinite list of unrezzed card in hq came up. thank you

**Comment by JoelCFC25** [comment]
This will be fixed when #1328 is merged and deployed. :+1:

**Comment by fejj06** [comment]
thanks a bunch
anaheim represent
