### ISSUE TITLE
Lakshmi SmartFabrics

### ISSUE THREAD

**Issue by pjbrand** [mtgred/netrunner#1334]
Hi, first of all, I'd like to thank you for being so dedicated to Jinteki.net. You guys are great!

Moving on to the issue, I just finished up a game as Gagarin with two Lakshmi Smartfabrics on the board, one with 9 counters, one with 7, and I could use neither of them on the runner's turn to prevent them from accessing Project Atlas in a remote. I had Ice Wall and Project Atlas in hand ( 
![ejwgdju](https://cloud.githubusercontent.com/assets/16831873/13699085/c4e99546-e73d-11e5-9d92-70c7ada0d3fa.png)
 ) and Atlas is worth 2 points, so I think this might be a bug. 

Clicking Lakshmi and selecting "Spend X counters" didn't change the state, including the removal of counters. 

Thanks for taking a look at this!

**Comment by JoelCFC25** [comment]
Yep, I did that wrong. Back to the drawing board!
