### ISSUE TITLE
Using Nisei Mk II counter at Corp-requested step 4.3 doesn't end the run

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1336]
Steps to reproduce: 

1. Score a Nisei Mk II
2. Have the Runner initiate a run
3. As the Corp, hit "Action before access" to request the 4.3 window
4. Runner hits "Successful run"
5. Corp gets the "Rez and take actions before successful run" prompt and spends the Nisei counter...but the run does not end.

**Comment by stoppableforce** [comment]
Maybe related: if the runner begins a run but has not chosen a target for their Net-Ready Eyes, a Nisei counter will also not end the run.
