### ISSUE TITLE
Blue Sun Ability

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#134]
- Creating a new remote with an upgrade.
- Putting an Agenda.
- Rezzing Upgrade (like "off the grid").

new turn.
- Use Blue Sun Ability to retake the upgrande.

Now I can't advance the agenda...

**Comment by osiridecascioli** [comment]
(tested more the once )

**Comment by mtgred** [comment]
There is indeed an issue with Upgrade in remote servers. When the Upgrade is trashed or moved, the other cards in the remote server seems to be "locked" and can't be advanced or moved. Reinstalling an upgrade in the remote server somehow unlock the other cards.

I haven't had time to analyse the issue but It's on the todo list.

**Comment by mtgred** [comment]
I finally found what caused the issue. It has been fixed and will be deployed with the next server update.
