### ISSUE TITLE
Label influence dots with numbers for huge influence values in deckbuilder

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1341]
One picture worth a thousand words:

http://i.imgur.com/aueCFEO.png

To prevent it from happening, make it so for total influence values above a certain threshold influence points aren't displayed as individual dots anymore. Use numbers instead, e.g. '22 o (red), 11 o (violet)', etc.

**Comment by Tondo** [comment]
If no one's looking into this already, I'll take a crack at it. Looks like a nice intro into the front-end code.

**Comment by domtancredi** [comment]
If this is merged and deployed, can this issue be closed?
