### ISSUE TITLE
Scavenging an Imp doesn't seem to reset the once-per-turn limitation

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1345]
Play Imp, use it to trash something, then Scavenge it into itself, then run on another trashable card. It didn't give me the option to use the Imp the 2nd time.

**Comment by JoelCFC25** [comment]
The `resolve-trash` function can do one quick thing as its last act--dissociate the `:cid` of the card being trashed from `[:per-turn]` in the game state.
