### ISSUE TITLE
Executive Boot Camp allowing illegal triggers

### ISSUE THREAD

**Issue by Saibrock** [mtgred/netrunner#1346]
At the beginning of the turn, if you use Executive Boot Camp to rez a card, then take your mandatory draw, that card will trigger its start-of-turn abilities. This should not happen, since the triggering condition had already passed by the time the card was rezzed. It would appear that cards with start-of-turn triggers are treating the mandatory draw as their triggering condition.

**Comment by zaroth** [comment]
Confirmed with EBC + PAD Campaign.

**Comment by nealterrell** [comment]
I can fix this tomorrow in the same way that The Supplier addresses the issue.

**Comment by nealterrell** [comment]
Submitted.
