### ISSUE TITLE
Chat log: improving message on creating new server

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#1347]
When the corp create a new server the message is:
"${USER} spends  to install a card in New remote."
It would be useful writing the server number.

**Comment by zaroth** [comment]
I agree, however it's useful to keep an indication of the fact that it's a new server to be able to easily differentiate from installing in an existing one. So the text should be IMHO added, not replaced, like _(...) install a card in New remote - Server 8_.

**Comment by queueseven** [comment]
Well, it's always the server with the highest number... :-)

**Comment by JoelCFC25** [comment]
Implemented at #1692!
