### ISSUE TITLE
Sneakdoor Beta gets into loop with Product Placement on HQ

### ISSUE THREAD

**Issue by victhetrader** [mtgred/netrunner#1349]
setup: Product Placement on HQ, Snekdoor Beta installed on Leprechaun (directly from hand), no ice on Archives

issue: after accessing both choices ("Card from hand" and "Product Placement") with Sneakdoor Beta, "access Product Placement" option stayed active and wouldn't go away (tried multiple accessing and all other actions we could trigger).

**Comment by JoelCFC25** [comment]
HQ runs when upgrades are present are completely jacked up on the live server at the moment. This will be fixed at the next restart when #1328 goes live!
