### ISSUE TITLE
PAD Factory (possibly Museum of History?) Influence Broken

### ISSUE THREAD

**Issue by pjbrand** [mtgred/netrunner#1353]
Sometime during the last update, the PAD Factory was broken.

![image](https://cloud.githubusercontent.com/assets/16831873/13786780/31472728-eaa7-11e5-9136-8b6ea0c9ff44.png)

My deck previously checked out (except for inclusion of Business First, of course) in terms of influence before the last patch, but now it's labeled 'invalid' due to basic deckbuilding rules. I tried subtracting and re-adding the Caprice and PAD Factory and determined that PAD Factory was the issue. I don't think it's checking whether 3 PAD Campaigns are in the deck. It could be the Museum of History too, although I have 54 cards in that deck. 

Thanks for looking into this!

**Comment by pjbrand** [comment]
Oh whoops, I referred to another deck that included Museum. Reference: 
![image](https://cloud.githubusercontent.com/assets/16831873/13786908/c032c816-eaa7-11e5-8e3e-4e47f1390eec.png)

**Comment by Saintis** [comment]
PAD Factory and Product Recall was forgotten from the list of alliance card, hence their conditions were not checked. Is being fixed in #1352.

**Comment by pjbrand** [comment]
Okay! Sorry for the redundancy. Thanks again.
