### ISSUE TITLE
Test Run + Scavenge Combo still returning program to stack when turn ends

### ISSUE THREAD

**Issue by famebyproxy** [mtgred/netrunner#1354]
Test Run/Scavenge combo returns program to top of stack when Runner's turn ends.

• Has occurred with Femme and Battering Ram
• Runner typically has tags, and has Magnum Opus installed - no other board state commonalities observed
• Occurs regardless of whether actions are taken in between the two programs.
• Outside of the return to stack, the other card functionalities appear to be correct.

**Comment by JoelCFC25** [comment]
Thanks for the report. Sorry, I mistakenly blew up the part of the `:req` in Test Run that would prevent this. Will fix it soon...
