### ISSUE TITLE
Hostage can't find kati jones

### ISSUE THREAD

**Issue by srusenaid** [mtgred/netrunner#136]
Hostage doesn't work with kati jones yet.

**Comment by mtgred** [comment]
Hosting shows only connections card you can play. The problem is probably that you didn't have 2 credits left after playing Hosting to install Kati Jones.

It can be quite confusing. I will modify the UI in the future to display cards that can't be played with greyed out buttons.

**Comment by dimarco70** [comment]
Please consider that Hostage let pick you a card even though you cannot play. Playing it is indeed optional, so you should be able to pick a connection you do not have credits to pay for, simply to add it to your hand. Suboptimal, yet allowed.

**Comment by JoelCFC25** [comment]
Fixed at #513.
