### ISSUE TITLE
Counter visibility on subwindow open

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#1363]
example:
I'm playing as corp
the runner, Geist, install some cloud icebreaker, like 2 shiv, so either have a counter with "2" on it.
Opening the Heap of the runner, the strenght counter on the 2 installed icebreaker is still visible and hide a little bit the card in the Heap.

Was Nice if the counter is hided by the subwindow

**Comment by zaroth** [comment]
Can you post a screenshot? I can't reproduce your issue on live server: http://i.share.pho.to/876b0eb8_o.png

**Comment by osiridecascioli** [comment]
![screenshot from 2016-03-17 14-39-54](https://cloud.githubusercontent.com/assets/1135292/13847595/435391f6-ec4e-11e5-92a2-07946d669c75.png)

I hope the file will be uploaded.
I'm on Linux (Ubuntu 15.10) using Chrome Version 49.0.2623.87 (64-bit)
