### ISSUE TITLE
"Confirm delete" button deletes the currently selected deck

### ISSUE THREAD

**Issue by postinternetsyndrome** [mtgred/netrunner#1364]
If I select a deck in the deck builder, press delete and then select another deck, the confirm delete button will stay in place, but pressing it will delete the newly selected deck. This is counterintuitive and I assume the intention is for the button to go away if you navigate away from the currently selected deck.

**Comment by mtgred** [comment]
Hi,

It will be fixed soon.

Cheers,
Minh
