### ISSUE TITLE
Muslin No Shin prevents scoring of agendas other than the one chosen

### ISSUE THREAD

**Issue by GameofDroids** [mtgred/netrunner#1366]
I was playing a fun game of Beale or No Beale earlier. I had an agenda I had originally placed with a mushin left out for a few turns in server 1. In a later turn, I mushined an ambush into a new server, used my third click to advance the agenda in server 1 and attempted to score. I was unable to "due to Mushin No Shin" indicated in an orange alert in the top right of the screen. I should be able to score. Perhaps a leftover tag from the original install is being recalled by the newer Mushin play? Hope you can fix it. Thanks!

**Comment by zaroth** [comment]
Seems similar to #1332.
