### ISSUE TITLE
Populist Rally gives corp clicks

### ISSUE THREAD

**Issue by totsuzenheni** [mtgred/netrunner#1368]
Populist Rally gives the corp a permanent addition click every turn after the turn on which it was resolved. That is, on the first corp turn after Populist Rally is played they have 2 clicks, the second they have 3 clicks, the third they have 4 clicks, the fourth they have 5 clicks, and so on.

I was playing Silhouette vs, Jinteki black tree.

**Comment by JoelCFC25** [comment]
Thanks for the report. Forgot to add `(unregister-events card)` in the `:corp-turn-ends` effect.
