### ISSUE TITLE
Security Testing's 'gain 2 credits' triggers on corp turn

### ISSUE THREAD

**Issue by totsuzenheni** [mtgred/netrunner#1369]
More specifically, the corp played An Offer You Can't Refuse, nominating the same server that the runner had nominated as the Security Testing server. When the run was successful 'gain 2 credits' triggered.

N.b. I did check with FFG if Security Testing was meant to trigger on the corp's turn and Damon Stone replied 'No, "this turn" refers back to the first part of the effect, choosing a server at the beginning of your turn.'

**Comment by nealterrell** [comment]
Thanks for the report. if someone wants to pick this up, you just need to `dissoc` the selected server from ST at the end of runner's turn.
