### ISSUE TITLE
Hardwired Corp IDs do not allow outside Agendas

### ISSUE THREAD

**Issue by mattsigal** [mtgred/netrunner#1371]
A few friends and I did a Hardwired draft yesterday and wanted to try the decks out again via Jinteki.net. The cards are all available (awesome!) but we came across one small issue:

After selecting a specific corp ID (e.g., Fringe Applications - which is Weyland based), we are unable to include agendas from other factions (e.g., Unorthodox Predictions, from Jinteki). Is it possible to make the 4 Corp IDs actually coded as neutral (similar to the Shadow) to allow all agendas to be included?

**Comment by zaroth** [comment]
Could you provide a rules source to the statement that other than Shadow draft IDs are allowed agendas outside of their faction? I was under the impression that it's an ability unique to the Shadow, but I might be wrong.

**Comment by mattsigal** [comment]
Of course!  In the Hardwired Draft Starter pack, on Card 4, it states:

> "All standard Android: Netrunner rules are observed, except that games are played to 6 agenda points, instead of 7, and that **you may use agendas from every faction in your Corp deck**."

**Comment by zaroth** [comment]
Yeah, found it quite quickly, thanks :) This should be a small change in deckbuilder.
