### ISSUE TITLE
Genetics Pavilion interacts with Fisk Investment Seminar poorly.

### ISSUE THREAD

**Issue by MontyWhittaker** [mtgred/netrunner#1374]
When I have Genetics Pavilion in play, and Fisk is played, the Runner draws the number of cards that he/she is supposed to, but the Corp draws no cards. More intriguingly, when I attempt to rectify this, by manually adding clicks/drawing on the Corp's behalf, the Corp is still unable to draw. It seems that GP limits ANY draw by either of the two players to just two during the Runner's turn presently.

**Comment by JoelCFC25** [comment]
Thanks for the report. This isn't directly from Genetics Pavilion, but rather an oversight in the edits to the core `draw` function I made to support GP.
