### ISSUE TITLE
Palana gaining credit when Runner deck empty

### ISSUE THREAD

**Issue by Runetter** [mtgred/netrunner#1381]
Had a game where Noise had Wyldside out, but had no cards left. Palana still gained a credit when Wyldside triggered.

**Comment by JoelCFC25** [comment]
Thanks for the report. We already have the root issue in at #1358. :+1:

**Comment by Runetter** [comment]
Ah, sorry, did not see it.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has just been fixed.
