### ISSUE TITLE
Installing Tech Trader off of Street Peddler gives you the credit from the newly installed Tech Trader

### ISSUE THREAD

**Issue by jakodrako** [mtgred/netrunner#1384]
The Tech Trader installed off of a Street Peddler is not active at the time that it would trigger, so this should not work this way. It seems like Street Peddler is not registering that the [trash] ability has been used until after it has resolved; it should register when the ability is triggered.

**Comment by zaroth** [comment]
For people similarly confused as me, @jakodrako probably meant Tech trader. Edited the post to clarify it.

**Comment by JoelCFC25** [comment]
Nudging [line 771](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards-resources.clj#L771) down to be the last thing done in the `when` fixes this.

**Comment by Mgetch** [comment]
Hi,

I've met a friend recently and he  surprised  me  with   really great news, please  read it here <http://benefit.urbantreasurehunt.com/lnhwve>


All the best, mattgetch009@yahoo.com
