### ISSUE TITLE
Start of Turn can trigger twice

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#1387]
Start of Turn button was triggered twice on Corp side (due to double-click or press and hold). This caused the Corp to gain 6 clicks and draw 2 cards. Also increment turn counter twice.

Screenshot:
![screen shot 2016-03-24 at 20 17 39 2](https://cloud.githubusercontent.com/assets/13198563/14033554/29b8093c-f213-11e5-9746-fd4aad3e5430.png)

**Comment by zaroth** [comment]
I think it's the same issue as #1150, with the root cause same as #468.

**Comment by JoelCFC25** [comment]
Let's keep any progress on this in the original issue.
