### ISSUE TITLE
Visual indicators of main ICE subtypes: B/C/S

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1388]
Using the framework put down by Saintis for Femme Fatale counter, we could consider using similar (maybe a bit less visually prominent) counters for ICE subtypes. This would make it easy to tell what subtype a piece of ICE is at a glance, even for beginners: 

- **B**(arrier) 
- **C**(ode gate) 
- **S**(entry)

Some kind of color coding of the counters could be also nice to make it even more clear when you're encountering a code gate / sentry / barrier. To take it further, breakers could also have similar symbol(s) with matching color to signify which types they can break.

Cards that would gain the most from this kind of display:

- Tinkering
- Paintbrush
- Chimera
- Changeling
- Lycan
- Wendigo
- Mother Goddess
- Rielle "Kit" Peddler: Transhuman
- Sub Boost

**Comment by Saintis** [comment]
Some of these will be improved by #1990.

**Comment by JoelCFC25** [comment]
Are we able to close this now? Seems like it was mostly addressed.

**Comment by zaroth** [comment]
Definitely :)
