### ISSUE TITLE
Silhouette (ID) + Blackguard (Console) + forcing an Agenda to rez

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#139]
If the runner is playing Silhouette, has Blackguard installed, and uses the ability to expose and force-rez an Agenda that's installed, the Agenda is rezzed and it's ability fires (for example Superior Cyberwalls gave the Corp creds = # of rezzed Barriers).

Agenda ability should not be fired and I'm not sure if it should be rezzed either, but the main issue being the ability being fired.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
