### ISSUE TITLE
lein uberjar fails - no core/request-phase-32

### ISSUE THREAD

**Issue by cwgreene** [mtgred/netrunner#1394]
```
java.lang.RuntimeException: No such var: core/request-phase-32, compiling:(test/cards-identities.clj:213:5)
Exception in thread "main" java.lang.RuntimeException: No such var: core/request-phase-32, compiling:(test/cards-identities.clj:213:5)
```

And indeed, nowhere in the source is there a core/request-phase-32. Perhaps it was not committed? Commenting this line of code out results in a successful build.

**Comment by JoelCFC25** [comment]
It existed until last night but the feature to request an ability window prior to the opponent's turn actually ending (e.g., for Hayley) has been reverted. Discussions are ongoing about how to proceed.

**Comment by zaroth** [comment]
Fixed by recent minh's commits.

**Comment by JoelCFC25** [comment]
Actually not...the same test fails in a different place now.
