### ISSUE TITLE
Feature suggestion: core decks

### ISSUE THREAD

**Issue by ZoeB** [mtgred/netrunner#1398]
To make Jinteki.net easier to use for newcomers to the game, it might be worth giving new users the core set's seven decks in their deckbuilder screen automatically (or even two of the proposed teaching decks, one corp and one runner).  That way, people still learning the game can play it here without having to learn the deckbuilding interface first.  I realise this may seem trivial to more experienced players, but given how some people might be new to the site, the game and even tabletop games in general, it might make the whole process less intimidating.  New users could go straight from signing up to playing.

**Comment by JoelCFC25** [comment]
Thanks for the suggestion. Someone else previously requested the same at #1096. :)

**Comment by ZoeB** [comment]
Ack, sorry, I should have checked first.  That's great that it's being considered though, thanks!
