### ISSUE TITLE
The Foundry ID should trigger after first Shipment from Mirrormorph ICE install (with Amazon Industrial Zone)

### ISSUE THREAD

**Issue by nateparkes** [mtgred/netrunner#1399]
Greetings (first time bug write-up, apologies for any mistakes, and thank you for your effort)

**What should happen:** When I play Shipment from Mirrormorph, and choose a piece of ICE as the first of my three cards to install, and install it in a server with Amazon Industrial Zone, I should have the ability to rez the ICE immediately, which should immediately trigger the Foundry's ability (to search for another copy of the ICE), BEFORE I select my second Mirrormorph card to install.

Order:
1 - Play Shipment from Mirrormorph
2 - Select card to play for first install
2- Select server for Shipment from Mirrormorph's first install
3- Rez installed ICE using Amazon Industrial Zone
4- Trigger Foundry ID ability, add ICE to hand
5 - Select card to play for second Mirrormorph install
6- Select server to install
7 - etc

**What is happening now:** The Amazon Industrial Zone zone is triggering AFTER the selection of the second card to be installed, and the Foundry is triggering after the selection of the third card.

1 - Play Shipment from Mirrormorph
2- Resolve Shipment from Mirrormorph's first install
3- Select second card to install
4- Prompted to rez first installed ICE using Amazon Industrial Zone
5 - Select target server for second ICE install
6 - Select third card to install
7 - Trigger Foundry ID on first rezzed ICE
8 - Prompted to rez second installed ICE using Amazon Industrial Zone
9 - Select target server for third ICE install
10 - Prompted to rez third ICE using Amazon Industrial Zone

Thanks again for all your effort; I'm a busy new dad, and if weren't for Jinteki, I doubt I'd ever get a chance to play Netrunner. The website is excellent.

**Comment by JoelCFC25** [comment]
This can be fixed using `:priority` values on these cards' prompts. Shipment from Mirrormorph's should be `:priority -1` so everything else will come before it. Amazon Industrial Zone should be `:priority 2` and The Foundry should be `:priority 1`.  This will yield the correct sequencing--though what it might mean for interactions with any of the other dozens of cards that generate prompts is anyone's guess.

**Comment by Mgetch** [comment]
Hi,

I'm writing a review on  an interesting  book right now,  please read some extracts here <http://chance.theattorneysearchgroup.com/lncku> and tell me what you think.

All best, mattgetch009@yahoo.com
