### ISSUE TITLE
Run events do not work anymore

### ISSUE THREAD

**Issue by dimarco70** [mtgred/netrunner#140]
Hi,

several run events (Account Siphon and Legwork at least) do not work properly anymore.
Indeed, when played, the event is removed from the game (while it should end in the heap) and the run is not started.

Mauro

**Comment by Agnate** [comment]
Same for Indexing, which did this a moment ago to me.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The update of this morning seems to cause the problem. The server has been reverted to the previous version so the run events should work again. I will investigate the issue this evening.

**Comment by mtgred** [comment]
The problem has been fixed.
