### ISSUE TITLE
Retrieval run triggers twice

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1400]
Didn't check for duplicates, I guess this affects other cards as well.

I used Retrieval Run to install a program from Archives; after that, the run didn't end, but the [Sucessfull run]/[Jack out] prompt showed up. I installed another program, then the prompt didn't popped up a third time.

**Comment by zaroth** [comment]
Yeah, we already have that mentioned in #1114, investigation by Joel shows that these two are likely related. Any circumstances that could affect the Retrieval Run? From what I've gathered, it doesn't happen every time.

**Comment by queueseven** [comment]
Yeah, it's a duplicate (#1114). I installed Femme Fatale, as Joel mentioned.
