### ISSUE TITLE
The ice installed by Howler have no options

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#1403]
Ice installed by Howler have no options to click - so Ichi 2.0, for example, on click only gives a "Derez" option (and not the "Trash 1 Program" and "trace3..." options as well). However, they seem to work fine once re-rezzed.

![See this screenshot](https://cloud.githubusercontent.com/assets/4217801/14155298/12c4fe60-f6b9-11e5-981c-662f67f00d67.png)

**Comment by JoelCFC25** [comment]
Thanks for the report. Howler needs to include a line to do a `card-init` on the ICE that gets installed.
