### ISSUE TITLE
figwheel runs fine but sitll error on goog

### ISSUE THREAD

**Issue by glass4pk** [mtgred/netrunner#1404]
Get the newest version and try to set up , the mongod , lein figwheel , java jar , and coffee server.coffee are both runs well and listen to their ports .
However, when access the localhost:1042 , the website shows errer on socket (figwheel) and main.
can't figure why...met this situation before?
website runs here :　http://120.76.27.208:1042/

![error on new](https://cloud.githubusercontent.com/assets/1888886/14173403/3ae841a6-f770-11e5-96eb-5fe9189d332a.jpg)

**Comment by glass4pk** [comment]
reinstall node-gyp and run fine now

**Comment by glass4pk** [comment]
Same server , old version runs fine , but the new version is not.

**Comment by queueseven** [comment]
Yeah, the cljs stuff is a bitch, especially with figwheel. Sometimes I have to restart the cljs compiler and figwheel, and sometimes figwheel doesnt work at all. It reloads the code, but random errors occur in the generated javascript. If I kill figwheel and reload the webpage manuall, the problem goes away.

**Comment by domtancredi** [comment]
@glass4pk what version are you using for everything?

**Comment by Saintis** [comment]
I've started to use `lein cljsbuild auto dev` instead as it seems to have fewer problems.

**Comment by erbridge** [comment]
I think the problem here is that there is a route bound to `/*`, which captures the jQuery url, returning HTML, which is obviously invalid JavaScript. And since jQuery isn't loaded, `$` is undefined. This only seems to happen under certain conditions which I'm not clear on, though.

**Comment by queueseven** [comment]
It's not only that. Sometimes the JS generated by the cljs compiler is just invalid (it contains a syntax error). If I kill and restart `lein` and `figwheel`, then it compiles without errors o_O

**Comment by erbridge** [comment]
So the syntax errors are probably due to not actually having the libraries installed. Run `npm install` and `bower install` for them.
