### ISSUE TITLE
Card art on run changes to encountered ICE

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1408]
I was spectating a game recently and saw the following:

The Professor vs Titan Transnational
1) The runner installed Keyhole
2) The runner clicked to run R&D, stated action was erroneous, and took back the click
3) The runner clicked Keyhole to initiate a run on R&D
4) The corp rezzed Checkpoint
5) The card art for Keyhole aiming at R&D changed to the card art for Checkpoint

I haven't seen the issue occur since.

**Comment by JoelCFC25** [comment]
I think Checkpoint is the only ICE that will currently do this to any run initiated from a card, because it swaps itself into `[:run :run-effect]` in the game state. I would consider this cosmetic only, although it's still true that Checkpoint will bug when there are multiple run effects (e.g. during a Dirty Laundry run).

**Comment by zaroth** [comment]
As long as both Keyhole and Checkpoint effects resolved after a successful run, this is not a bug - the Checkpoint card art is there to remind the players of effect happening after the run is successful.

**Comment by FarCryFromHuman** [comment]
As far as I remember, both card effects resolved, but I can't be sure about _when_ the card art changed. If it changed before Keyhole resolved, this still seems wrong to me. At the very least it was jarring enough that I did a double-take. I'll try to reproduce the scenario if I get time to play later this week.

**Comment by zaroth** [comment]
With current code, it should change as soon as the trace from Checkpoint subroutine is declared successful. True, optimally it should stack these run effects on the run arrow to reflect both of them, but this needs some tinkering with CSS and run arrows to allow stacking.

**Comment by zaroth** [comment]
As mentioned, this is not a bug. Possible improvement on the state of affairs described in #1426.
