### ISSUE TITLE
Commercial Bankers Group has functionality of Bio-Ethics Association

### ISSUE THREAD

**Issue by Saibrock** [mtgred/netrunner#1409]
Commercial Bankers Group (Weyland asset from Democracy and Dogma) has the text, "When your turn begins, gain 3c if there is no ice protecting this server."
Bio-Ethics Association (Jinteki asset from Democracy and Dogma) has the text, "When your turn begins, do 1 net damage if there is no ice protecting this server."

Currently, CBG has BEA's functionality; it does not give the corp credits, and it deals net damage to the runner, despite reporting a gain of credits in the log.

**Comment by JoelCFC25** [comment]
Sorry--copy/paste thing I forgot to fix, since these cards are otherwise identical.
