### ISSUE TITLE
Card interaction bug: Qianju PT +  Joshua B. should prevent tag

### ISSUE THREAD

**Issue by Fireblaze** [mtgred/netrunner#1410]
Using Qianju PT should prevent tag from Joshua B. Right now the runner gets a tag at the end of turn (Qianju PT doesnt trigger)

**Comment by JoelCFC25** [comment]
Qianju PT is just completely broken at present, regardless of Joshua B.'s presence. Clicking it in the "when your turn begins" window doesn't make you lose a click once you take clicks, and as you discovered it's not preventing a tag either.
