### ISSUE TITLE
When Indexing cards are sometimes not able to be dragged back to R&D from the temp zone.

### ISSUE THREAD

**Issue by MasterPrudent** [mtgred/netrunner#1413]
Indexing normally works fine but on occasion I am unable to drag cards from the temp zone back to R&D and the cards are trapped in the temp zone. This appears to happen when the corp is Jinteki and the only other commonality I can remember is that there was a caprice in the top 5 cards every time. The browser used was Firefox 45.0.1 and the OS Windows 7.

**Comment by MasterPrudent** [comment]
It happened again but this time against The Foundry. It worked fine the first time but then bugged out the second time.

**Comment by MasterPrudent** [comment]
It seems to happen on the second indexing. Cards can be dragged to the trash but not back to R&D. Also when clicking on cards with a rez cost the log will report that I rezzed them (or a message will flash saying I don't have the creds to rez them.)

**Comment by zaroth** [comment]
was there an upgrade on R&D when you tried to resolve the drag&drop from indexing? A screenshot would be useful.

**Comment by MasterPrudent** [comment]
There were no upgrades on R&D. I'll grab a screenshot the next time it happens.

**Comment by queueseven** [comment]
I just tried it and I could use multiple Indexings just fine. But sometimes I can't drag agendas to R&D, so something fishy is going on with drag&drop.

**Comment by zaroth** [comment]
Well, the difficulty of R&D dragging was already mentioned in #1186, that's why I asked about upgrades.

**Comment by MasterPrudent** [comment]
I've played it a few times since and it's been fine. ¯\_(ツ)_/¯

**Comment by queueseven** [comment]
So I'll close this. If this issue pops up again feel free to reopen.

**Comment by MasterPrudent** [comment]
It bugged out again :(. I got a screenshot
![untitled](https://cloud.githubusercontent.com/assets/18226801/14421059/da05153e-0012-11e6-90ed-b3b850e23ffa.png)

**Comment by MasterPrudent** [comment]
(There were five cards in the temp zone. This was taken just after I trashed one.)
