### ISSUE TITLE
Chronos Protocol doesn't trigger at all

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#1416]
As the title suggests. I'd only just started playing as Chronos Protocol (after a break) so I don't know when this happened.

(sorry, this is not the most useful issue description)

**Comment by JoelCFC25** [comment]
I probably broke it with the Tori Hanzo + Titanium Ribs PR. I'll try and make time tonight to have a look.

**Comment by JoelCFC25** [comment]
I think I'll have something for this shortly.

**Comment by CallMeDutch** [comment]
Just played a game and its still bugged, any updates on when it will be fixed?

**Comment by JoelCFC25** [comment]
This patch is neither merged nor deployed yet. After it gets merged it will be functional after the next game server restart. An item will be put into the site News header when that occurs. Only mtgred is privy to the details of when restarts happen.
