### ISSUE TITLE
Chat box reports lots of code when preventing damage with Feedback Filter

### ISSUE THREAD

**Issue by emilyfrog** [mtgred/netrunner#1417]
Not sure if it's helpful to post this here; I assume it's similar to the Plascrete Carapace bug submitted earlier.  

EDIT: should have said - it was when preventing damage caused by the new card Bio-Ethics Association and yes, I should have trashed it sooner...

**Comment by JoelCFC25** [comment]
Thanks for the report. This does turn out to be a duplicate of #1415. I'm submitting the fix shortly!
