### ISSUE TITLE
Suggestion: Monochrome background

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#142]
While I love the beanstalk image, it's quite distracting sometimes. I'd love to see an option to turn it on/off and having a simple, monochrome background if I wish (like a dark gray).

mtgred, this is my favourite Netrunner online play site (OCTGN obviously hates us Mac users) which I visit on a daily basis! Please keep up the good work.

**Comment by DominicKexel** [comment]
As a workaorund, you could disable the CSS that sets the background if it really bothers you.

Look for the *bla*-bg div's and uncheck the background-image CSS.

![bild 2](https://cloud.githubusercontent.com/assets/3126597/8956037/3b34181e-35f2-11e5-8b97-a86ecb04c8e8.png)

Of course, you could also simply change the URL to an image of your choice.

**Comment by HongkongKoma** [comment]
Thanks for the reply. Unfortunately, my coding skills are on a 10-print-"Hello"-20-goto-10-Level :-)

**Comment by queueseven** [comment]
Player profiles are on our TODO-list. Once they are implemented, we can think about user settings :-)

**Comment by zaroth** [comment]
#1047 is relevant here.

**Comment by queueseven** [comment]
The easiest way ATM is to use a plugin like [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb) and play with the CSS, like 

    .lobby-bg {
      background-image: url("http://orig06.deviantart.net/8a89/f/2013/156/9/4/android__netrunner_doppelganger_by_howi3-d67x4l0.jpg") !important;
    }
