### ISSUE TITLE
Hostile Infrastructure triggers when Runner plays a Current and Corp has a current

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1423]
It shouldn't trigger as the Corp trashes their own card.

**Comment by JoelCFC25** [comment]
Can you add some specifics on this one? I am not able to reproduce it so far. There is an explicit attempt to avoid this in [line 231](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core-rules.clj#L231) of the `trash` function. I had HostInf rezzed with an ELP active, and when the Runner played Hacktivist Meeting no net damage occurred.

**Comment by Kiv** [comment]
Ask Calimsha, he mentioned it in Slack chat.

**Comment by JoelCFC25** [comment]
I searched and found the conversation, but I as I read it, I understood him to be thinking aloud rather than reporting something he'd seen occur on the site.

**Comment by zaroth** [comment]
I say let's revisit the issue **if someone who actually experienced it shows up.**
