### ISSUE TITLE
Card art invisible

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1424]
Install and rez a card that doesn't have art yet (Mumbad City Hall for example)
Overwrite it and rez a card that does have art. The art doesn't show.

Sometimes I had this happen when a card without art was trashed, and a card with art was next to it and it moved inwards to fill the space.

**Comment by queueseven** [comment]
Yeah, I noticed this, too.

**Comment by queueseven** [comment]
Back in the good, old days, the text of the cards was also displayed when the image could not be shown. This was removed due to performance reasons/bandwith.

**Comment by erbridge** [comment]
Does this still happen?

**Comment by zaroth** [comment]
sadly, at the moment all the asset spoilers have art on NRDB, so to test I had to delete our lord and savior's Jackson Howard's `/img/cards/04015.png`... But I managed to confirm, with a bit different reproduction steps.

- Starting hand:
![840021](https://cloud.githubusercontent.com/assets/840021/19337537/401c1568-9116-11e6-94ff-3a94363e24eb.png)
- played Green Level Clearance:
![jinteki_-_2016-10-13_07 26 38](https://cloud.githubusercontent.com/assets/840021/19337556/6cb54356-9116-11e6-90ff-09253d331b3a.png)
- installed Howard and PAD in separate remotes:
![jinteki_-_2016-10-13_07 27 36](https://cloud.githubusercontent.com/assets/840021/19337570/9f179dda-9116-11e6-87d8-304ebb7509d4.png)
- shuffled with Howard:
![jinteki_-_2016-10-13_07 27 55](https://cloud.githubusercontent.com/assets/840021/19337573/a62671e6-9116-11e6-883a-2f3552f36a0a.png)
