### ISSUE TITLE
Stacking of cards representing run events

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1426]
As mentioned in #1408, it would be useful to allow additional run events to be displayed together above the run arrow, as in the mentioned Checkpoint-Keyhole interaction. The way cards are stacked in servers in upgrades can be reused here.

Also, Security Testing and Patron, being mandatory run effects, could also be coded to add their card art to run arrow - and also make use of the new feature.

**Comment by NoahTheDuke** [comment]
Done did in some PR a couple months ago.
