### ISSUE TITLE
Trope lets you undershuffle

### ISSUE THREAD

**Issue by SohumB** [mtgred/netrunner#1427]
Trope isn't an "upto" or "may" card; when you use it you have to shuffle exactly that many cards into your stack.  (Or as many as possible, if you have less in your heap.) The current implementation implements it as "upto", though.

Thanks!

**Comment by zaroth** [comment]
Before we implement this, I'd like jakodrako's opinion on this, to prevent another Apocalypse HI fiasco ;-) . Also it would be neat to update ANCUR to reflect this if it's true: http://ancur.wikia.com/wiki/Trope

**Comment by SohumB** [comment]
I'm working off this tweet
https://twitter.com/anr_ruleswiki/status/665382739294601216,  but it makes
sense given the wording.

I'm never quite sure what the process for updating ancur is. Is a twitter
ruling from ancur twitter sufficient? A twitter ruling from Damon or Lukas?

**Comment by zaroth** [comment]
ANCUR makes do for what they have available AFAIK. For me, a word from jakodrako or a tweet from ANCUR is good enough.
