### ISSUE TITLE
Net Shield preventing all damage instead of first damage

### ISSUE THREAD

**Issue by dollopuss** [mtgred/netrunner#1429]
When Net Shield is prompted with preventing net damage, it will prevent all damage instead of 1 net damage.  It will also be prompted for other net damage in the same turn even if it was used.

**Comment by erithtotl** [comment]
This isn't new either, its always been like that.

**Comment by JoelCFC25** [comment]
In my experience, Net Shield works as long as there is only 1 source of net damage. With 2 or more sources (e.g., 2 rezzed copies of Hostile Infrastructure), when you use Net Shield it will wrongly prevent both simultaneous instances of 1 net damage.

**Comment by nealterrell** [comment]
I have a fix for this coming. Net Shield still won't be perfect -- we don't have a way for it to stop showing the Damage Prevention dialog after the first damage is dealt -- but it will no longer block all instances of simultaneous damage.
