### ISSUE TITLE
PAD Factory/Mumbad Construction Company Combo Not Allowing Score

### ISSUE THREAD

**Issue by cylerparent** [mtgred/netrunner#1432]
When you use PAD Factory to place Advancement Tokens on Mumbad Construction Company, then use MCC to move the tokens onto a face up agenda, the system will not allow a score of that agenda, stating the error: "Cannot score due to PAD Factory".

Below is a screenshot of the error:
![screenshot 2016-04-07 16 54 19](https://cloud.githubusercontent.com/assets/18338710/14370334/2569ef4c-fce2-11e5-9d4f-4cf4f626eb05.png)

and here is a copy of the log:
![mcc-padfactory error](https://cloud.githubusercontent.com/assets/18338710/14370460/2a6b7ba4-fce3-11e5-9885-3558ccef7d37.png)

**Comment by JoelCFC25** [comment]
Thanks for the report. PAD Factory needs the same turn-flag tightening that Dedication Ceremony got in #1328.
