### ISSUE TITLE
Suggestion: Make Leela bouncing instant

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#1435]
Title, don't let corp do any actions before Leela has bounced (or decided not to).

**Comment by JoelCFC25** [comment]
I don't think we want to do this for at least two reasons:  
* The Runner can have multiple "when you steal" abilities that they should be able to order as they wish--e.g., Leela and Gang Sign(s). 
* Coding in prevention of Corp actions/abilities would probably be a big endeavor, and would probably add an extra UI step for the Runner to indicate when they're all done and passing priority over to the Corp

Although the system is heavily automated, we already have lots of other areas where it's incumbent on the players to know and apply the rules correctly, so my 2 credits is that this should remain as-is.

**Comment by queueseven** [comment]
I agree with @JoelCFC25 here, but I could think of sending a toast message to the corp as well to inform the corp player that the runner may want to bounce a card/use a effect.

**Comment by erbridge** [comment]
Is this still an issue?

**Comment by queueseven** [comment]
Since we have blocking prompts now, it should not be an issue.
