### ISSUE TITLE
Surat City Grid's rez discount only works on cards installed in the same server

### ISSUE THREAD

**Issue by RJayz** [mtgred/netrunner#1437]
When using Surat City Grid's ability to rez other cards with a discount whenever a card is rezzed in or protecting the same server as Surat City Grid, I ran into the following issue:

- The card works fine when rezzing a card in the same server. I get the following message in my chat log:
Rjayz spends 2 to rez Ash 2X3ZB9CY.
Rjayz uses Surat City Grid to rez Heimdall 1.0, lowering the rez cost by 2 .
Rjayz spends 6 to rez Heimdall 1.0. (Heimdall 1.0 normally costs 8 credits)
The Heimdall 1.0 is located in the same server as the Surat City Grid and Ash.

- Whenever I rez a card in a different server, I do not get the discount, and get the following chat messages:
Rjayz spends 2 to rez Ash 2X3ZB9CY.
Rjayz uses Surat City Grid to rez Eli 1.0.
Rjayz spends 3 to rez Eli 1.0. (So no discount)

The Eli 1.0 was located on HQ, the Surat City Grid and Ash in a remote server. I also tested reproducing the issue with ICE, assets and upgrades, and in each case if the card was installed in the same server I received the discount, and if it wasn't I didn't.

**Comment by JoelCFC25** [comment]
Thanks--missed this last time I fixed SCG. Hopefully this is the last problem with it.
