### ISSUE TITLE
PSI events being initiated twice

### ISSUE THREAD

**Issue by repoman1000** [mtgred/netrunner#1438]
I've had several games where the PSI event (either from Caprice or TFP) being initiated twice. 

Here's is such an event as seen from the game log. In this scenario the runner access R&D with 1 R&D Interface. His first access is a TFP and I (the corp) win the PSI game. His second access is a TFP and they (the runner) win. This wins him the game. I check RnD out of curiosity and find the top 2 cards to be Celeb Gift and Nisei MKII. Further down in the deck I find the other 2 TFPs 9 and 15 cards down. 

Olo started their turn 17 with 8  and 5 cards in their Grip.
Olo spends  and 2  to install Corroder.
Olo spends  to make a run on R&D.
Olo spends 3  to increase the strength of Corroder to 5.
repoman has no further action.
Olo spends 1  to use Corroder to break 1 barrier subroutine.
Olo spends 1  to use Corroder to break 1 barrier subroutine.
Olo continues the run.
repoman has no further action.
Olo uses Desperado to gain 1 .
Olo accesses 3 cards.
Olo uses Desperado to gain 1 .
Olo accesses 3 cards.
repoman spends 2 .
Olo spends 1 .
repoman spends 0 .
Olo spends 0 .
Olo steals The Future Perfect and gains 3 agenda points.
Olo wins the game.

**Comment by Saintis** [comment]
Due to this bit:
> Olo uses Desperado to gain 1 .
Olo accesses 3 cards.
Olo uses Desperado to gain 1 .
Olo accesses 3 cards.

I would guess in this case the runner accidentally double clicked the successful run button due to lag or something, hence causeing all cards to be accessed twice.

**Comment by JoelCFC25** [comment]
All discussion of "doubled effects" and solutions will take place in #468, the original issue for this problem.
