### ISSUE TITLE
Titan Transnational + Corporate Sales Team

### ISSUE THREAD

**Issue by DavePickles** [mtgred/netrunner#1442]
Titan Transnational currently adds an extra credit to those stored on Corporate Sales Team when it is scored - it should be 1 agenda counter and 10 credits

**Comment by JoelCFC25** [comment]
Thanks for the report. We don't currently have a way of distinguishing agenda or power counters from non-recurring credits. They all just get treated in the code as `:counter`. Virus counters do as well, but they get some special CSS based on the card holding them having the Virus subtype. 

So unfortunately, there's no way to represent this right now.
