### ISSUE TITLE
Heritage Committee + Mumba City Hall interaction isssues

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1443]
1. When mumbad city hall + heritage committee is played, the shuffle happens first, then puts the card on top. This is wrong, we need a way to delay the shuffle after the whole `play-instant` is finished, since just putting it after it doesn't seem to be enough.
2. According to unofficial FAQ http://ancur.wikia.com/wiki/Democracy_and_Dogma_UFAQ, you are allowed to click MCH, search through your deck (seeing whether top 3 cards are worthwhile to draw), and then decide whether to play HC or eg. install mumba temple and only after this the deck shuffles. This could be implemented by adding a "Manual" option in MCH dialog. This would allow you to search through the deck, see it in order and click the alliance card you want using a targeting prompt.

**Comment by queueseven** [comment]
Hey @nealterrell, when can we expect your PR? :-)

**Comment by nealterrell** [comment]
Hopefully tomorrow!
