### ISSUE TITLE
Daily Business + Political dealings

### ISSUE THREAD

**Issue by Sp00kyI3** [mtgred/netrunner#1450]
When drawing extra cards with Daily Business, Political Dealings doesn't recognize anything after the first card as valid to reveal and install. If its the first on daily i was ok. any other card it doesn't register.

**Comment by queueseven** [comment]
The problem is that Daily Business Show does not actually `draw` the cards, it just `take`s them from the deck, so the `:corp-draw` event does not contain the extra cards.

**Comment by queueseven** [comment]
Maybe we should add a `:pre-draw` event where DBS changes the number of cards to draw, then does its "put to bottom of deck" logic in the `:draw` event.

I don't know if there are others cards that needs to know what cards where drawn or how many besides PD.

**Comment by Sp00kyI3** [comment]
That would be cool

**Comment by queueseven** [comment]
Another card that is affected is Raman Rai

**Comment by Saintis** [comment]
Per the new FAQ Raman Rai would not be affected by this.
