### ISSUE TITLE
Chronos prompt locks up on multiple simultaneous net damage

### ISSUE THREAD

**Issue by NBHS** [mtgred/netrunner#1453]
I've got two rezzed Hostile Infrastructures in play as Chronos. The runner trashes a card, triggering two net damage.

The chatlog registers two net damage, but doesn't apply either.
The Chronos prompt shows the correct cards, but clicking the cards does nothing. (/close-prompt must be used.)
The runner can't even /take-net afterward to correct the error.

Chrome on Windows 7, Jankteki installed.

**Comment by JoelCFC25** [comment]
Simultaneous instances of damage are problematic in other respects right now, e.g. prevention (see #1429).

**Comment by nealterrell** [comment]
I have a fix for this coming.
