### ISSUE TITLE
Feature request: make alt-art a preference 

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1454]
It's great that donors get something special with alt-art cards. But, on a smaller screen especially, many of the alt-art cards have barely readable text. A number of the cards are dark-text on a dark background - and this makes them tough to read, especially for those users who have less good eyesight. In terms of making the site accessible, particularly for those who are less visually-abled, please could you make alt-arts switchable in preferences?

**Comment by queueseven** [comment]
Related: #70 and #1047

**Comment by nealterrell** [comment]
This is a feature now.
