### ISSUE TITLE
Feature request: treat temporary credits like recurring credits.

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#1457]
Here is a simple solution idea for fixing the behaviour interaction between recurring credit cards, and bad publicity (particularly that it automatically spends bad publicity credits first, even if you need to spend stealth credits).

Any effects that give temporary credits, could create a temporary UI item that can be clicked on to take credits from that pool, in the same way as you would take recurring credits.

An alternative method of fixing this type of interaction, would be to make recurring credits add credits to the temporary pool; which would mean that order matters, and the temporary credit system would need to be able to handle temporary credits for more than just runs, which could get messy if done wrong.

**Comment by NoahTheDuke** [comment]
Implemented with #4262
