### ISSUE TITLE
Chronos Protocol + 0 cards in hand doesn't end the game.

### ISSUE THREAD

**Issue by MrHuds0n** [mtgred/netrunner#1459]
If the runner has no cards in hand and I play something that does 1 net damage (such as Neural EMP), the prompt asks me to select a card even though there are no cards and doesn't finish the game.

**Comment by JoelCFC25** [comment]
Thanks for the report! I had to fix something else with Chronos Protocol already in my pending PR, so I'll add this in as well. It will be in #1449.
