### ISSUE TITLE
Suggestion: Make a mini guide. 

### ISSUE THREAD

**Issue by Ian517** [mtgred/netrunner#146]
Except from left clicking and dragging things around we cant figure out what else we can do. Like add counters or target cards for ability uses. Cards like Imp and Aesop's Pawnshop effects are marked as done, but many players can't figure out how to automate their effects. Thank you in advance!

**Comment by mtgred** [comment]
Mythbuider wrote a guide here: https://mythbuilder.wordpress.com/2015/03/25/the-definitive-guide-to-netiquette-on-jinteki-net-wip/

For Imp and Aesop's Pawnchop, simply click on the card.

**Comment by Ian517** [comment]
You rule!!
