### ISSUE TITLE
Faerie implemented incorrectly?

### ISSUE THREAD

**Issue by se4n** [mtgred/netrunner#1460]
<img width="198" alt="screen shot 2016-04-22 at 12 32 49 pm" src="https://cloud.githubusercontent.com/assets/1520529/14748364/436727f2-0887-11e6-909a-c026e5fda282.png">

Faerie shouldn't be breaking "any number of subroutines" for free, it should break each individual subroutine for free. Typically, this difference doesn't matter, but it does in interactions with Midway Station Grid. Faerie should be breaking each sub individually for free, as a separate break. Not sure if it's actually doing that, based on the screenshot pasted here.

**Comment by JoelCFC25** [comment]
Since we don't have Midway Station Grid or Interrupt 0 implemented, this one is currently cosmetic only (you still have to manually pay extra for those effects)--but yes, it would be good to have the message be accurate.

**Comment by queueseven** [comment]
But do you really want to click Faerie 5 times to break all subs of that Komainu? 

Well, I guess in 99.99% of the cases it's obvious which subs you break with Faerie (all) and you just pump+trash, and fixing this message is trivial, so let's fix it for the sake of correctness

**Comment by queueseven** [comment]
I took a look at how Faerie is implemented. At the moment, it trashed itself if you use its ability, which is technically not correct (and technically correct is the best kind of correct). It should be trashed after the encounter ends; but I think it is too much hassle for too little benefit to change it and we should leave Fairie as it is now.

**Comment by zaroth** [comment]
so after #1522 I think Faerie will print "break a sentry subroutine" and get trashed. I don't think that's any less confusing then before, so reopening this.

**Comment by JoelCFC25** [comment]
I have a proposal that I just tested and found to work:

In `continue`, right after triggering the `:pass-ice` event, we also check if that ICE was rezzed, and if so, trigger a new `:encounter-ends` event. Then Faerie can `assoc` something like `:used true` into itself after you use it and have an event hook for `:encounter-ends` with `:req (req (:used card))`.

**Comment by Saintis** [comment]
[Builder of Nations](https://netrunnerdb.com/en/card/11038) could also use `:encounter-ends`, since the new Errata means it should trigger on a bypass.

**Comment by erbridge** [comment]
Why not just use `:pass-ice` itself, rather than adding a new event?

**Comment by JoelCFC25** [comment]
New functionality went in at #2197!
