### ISSUE TITLE
Typing in chat bar causes whole screen to move to the right

### ISSUE THREAD

**Issue by GoomBard** [mtgred/netrunner#1467]
With games against corps with large amounts of assets, the chat bar will move to the right, off the screen, and you have to keep zooming out to keep up. If you don't keep up, typing in the chat bar will cause the whole screen to move to the right, causing a large black bar to appear on the right of the screen and rendering you unable to see the left of the screen (including the manual +- for credits etc and most of your grip).

**Comment by JoelCFC25** [comment]
Is this still happening?

**Comment by GoomBard** [comment]
Well it is, but now there's a scroll bar on the bottom during games so the
issue is no longer a problem. Thanks!
