### ISSUE TITLE
Astrolabe posts draw message even though the draw is prevented

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#1469]
After drawing two cards already with a rezed genetics pavilion on the table i ran into a crick. It fired and installed a sundew from archives. The astrolabe i had installed posted to the log that i drew a card but the actual card draw was prevented.

 In short: Don't post to the log that a card is drawn if the draw is prevented.

**Comment by JoelCFC25** [comment]
There are a _lot_ of cards that will be similarly afflicted. I don't know of a way to suppress the log message at this time (or just a portion of the message if the card draws and does something else, such as Lawyer Up).

**Comment by Balkmeister** [comment]
prehaps make the message conditional? Like first check the number of cards, then do the action then check again. if the number of cards in hand is the same dont output the log message?

**Comment by NBHS** [comment]
Problem is that this is a much more wide-ranging bug than just this circumstance. Log messages are also displayed for bugged (non-functional) damage in the case of #1453

**Comment by Saintis** [comment]
Should be fixed in #1509.
