### ISSUE TITLE
Space Camp in Archives blocks The Future Perfect psi game from happening

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#147]
I've had this happen several times, where there were Space Camp(s) in archives in addition to the Future Perfect. The order they went into archives might matter, but what happens is that while the runner is seeing the psi game prompt ("do you want to pay 0, 1, or 2?"), the corp is just seeing the Space Camp prompt, and once you resolve Space Camp, it doesn't then bring up the psi game, it just assumes the run was over and then runner lost.

Unsure whether or not the runner still loses credits spent on psi game.
Unsure whether order or number of Space Camps in archives affects this.
Unsure if the corp could still access the psi game if they resolved Space Camp BEFORE the runner finished resolving their psi game (might just happen because the runner clicks too fast).

**Comment by JoelCFC25** [comment]
This should be obsolete now that access order choice was implemented at #485.
