### ISSUE TITLE
Decklist randomly disappearing after playing?

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#1472]
I have 2 accounts at jinteki.net, made another because I had different name at stimhack and jinteki and I wanted to participate the SHL. I've been playing some games with both accounts, and this bug appeared with both.

It has only appeared after I have played with this specific deck: https://netrunnerdb.com/en/decklist/34257/mumba-neh-utah-regional-winner-26-players- . First time the deck was named, latter time it wasn't. I just played one game with the deck, and when I go to see my decklist, the deck isn't appearing there. It hasn't dropped lower into list, it has just disappeared.

**Comment by domtancredi** [comment]
What was the name of the deck? Can you list the steps to recreate this defect? Is this still an issue?

**Comment by Nipazz** [comment]
The decks reappeared after closing and reopening the browser.

One of the names was default name ("New deck") and the other had customed name, can't remember what it was. Haven't seen this problem since.

**Comment by domtancredi** [comment]
If it isn't reproducable, can we close the Issue and keep an eye on it if it surfaces again?
