### ISSUE TITLE
Ice: Builder

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#148]
Builder charges the corp 1 cred for each subroutine.

**Comment by JoelCFC25** [comment]
Submitted [a patch for this](https://github.com/mtgred/netrunner/pull/149) and some other stuff just now.

**Comment by CptHilts** [comment]
Cool. Thanks!!!

**Comment by eah13** [comment]
@CptHilts this pull request was merged.  Can this issue be closed now?

**Comment by CptHilts** [comment]
sure

**Comment by eah13** [comment]
Cool.  @CptHilts you or mtgred are the only ones who can do that.  The button's down at the bottom of the page.

**Comment by JoelCFC25** [comment]
@mtgred this one can be closed.
