### ISSUE TITLE
Trashing an installed, unrezzed Research Station lowers Corp's max hand size by 2

### ISSUE THREAD

**Issue by odward** [mtgred/netrunner#1485]
During one game, twice I trashed an unrezzed Research Station from the root of HQ and the Corp's max hand size was changed to 3 both times.

**Comment by JoelCFC25** [comment]
This is broader in scope than just Research Station. If you put a Red Herrings in a remote with an agenda but *leave it unrezzed*, the Runner is made to pay 5c extra to steal the agenda if they access and trash the Red Herrings first.

**Comment by Saintis** [comment]
Was this fixed? I was unable to reproduce this on `master`.

**Comment by JoelCFC25** [comment]
Hmm. The Research Station bit I verified at the time, but now it's not happening for me anymore. The unrezzed Red Herrings thing is, though--and I presume Strongbox and Old Hollywood Grid would be the same.

**Comment by zaroth** [comment]
if you want to find out which commit caused the fix, `git bisect` may be a good idea.

**Comment by JoelCFC25** [comment]
I think I have this one nailed now. In `resolve-trash-end`, before doing the `resolve-ability` on the declared `trash-effect`, do a `(when (or (= (:side card) "Runner") (:rezzed card))`
