### ISSUE TITLE
Feature Request: More buttons when doing a run

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1487]
Related to #1343

Maybe also add a `ETR` button, so `jack out` events are not triggered when the runner jacks out before telling the corp to not break an ETR subroutine

Maybe also a `Undo` button that is only visible at the outer most position?

**Comment by NoahTheDuke** [comment]
When is "ETR" necessary? And now we have an Undo command!

**Comment by queueseven** [comment]
I think it's no longer required, since there's also the 'fire all subs' button, which you can use if you want to end the run without triggering jack out events.
