### ISSUE TITLE
Some buttons beyond reach when there are too many

### ISSUE THREAD

**Issue by prchad** [mtgred/netrunner#1493]
When i use a 184-card Professor deck i find it impossible to SMC some of my programs because they are outside the screen. If buttons are in 2 columns when more than some 40 the problem will be solved.

**Comment by Saintis** [comment]
Similar issues arise when you use Atlas even in normal size decks. It would probably be usefu to rewrite the selection menus related with tutoring.

**Comment by domtancredi** [comment]
What do you think about a max-height to the panel? And then a scrollbar so you can select all available options?

Example:
http://puu.sh/ppCbC/a93e864458.png

**Comment by domtancredi** [comment]
Should keep this open as a new commit is made. This causes an overflow issue on the Run menu. 

Structurally, we need to figure out if we can move the menu outside the button.

**Comment by NoahTheDuke** [comment]
Somewhat implemented with #4326
