### ISSUE TITLE
Valley Grid doesn't reduce the runner's hand size

### ISSUE THREAD

**Issue by LCJK** [mtgred/netrunner#1495]
Valley Grid does not reduce the runner's hand size after they break all the subs on a piece of ice.

**Comment by queueseven** [comment]
It's just not implemented, like everything related to subroutines (except their very own effect, which is also manual)

**Comment by JoelCFC25** [comment]
Yep--as noted in the [card status sheet](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/edit?ts=56794018#gid=809032251), Valley Grid has to be fired manually when appropriate.
