### ISSUE TITLE
Darwin causes game to become unresponsive on successful run

### ISSUE THREAD

**Issue by Dysgruntler** [mtgred/netrunner#1498]
Once Darwin is installed by the runner a successful run will cause the game to become unresponsive at the 'Successful Run' / 'Jack out' prompt. Clicking successful run will trigger the correct successful run actions, however the run will never end and the prompt will not close. This happens regardless of whether Darwin was actually used during he run.

NOTE: this may also happen on unsuccessful runs, has not been tested.

In addition, as soon as Darwin is installed, any interaction with Darwin will cause significant delay, giving the appearance of nothing having happened, usually until another item is interacted with.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is a side effect of the recent change on the data source side (NetrunnerDB) of cards with cost X now having a null value instead of 0.
