### ISSUE TITLE
The Turning Wheel - Inverted State Counter

### ISSUE THREAD

**Issue by gar0u** [mtgred/netrunner#1499]
When the Runner makes an unsuccessful run, The Turning Wheel is incorrectly granted +1 counter.

When the runner makes a successful run, there is no effect on the counter state of The Turning Wheel.

Probably just a backwards invariant, but I do not know the code base...

**Comment by JoelCFC25** [comment]
Check the card text again--The Turning Wheel gains counters when a run ends. The successful/unsuccessful status of that run is not specified.

**Comment by gar0u** [comment]
My mistake.  Thank you.  After reading the card more closely, I believe it is functioning properly, and am closing this issue.
