### ISSUE TITLE
Suggestion: Make a counter add/remove tool.

### ISSUE THREAD

**Issue by Ian517** [mtgred/netrunner#150]
Hello, i know u have a lot of work but it would make a huge difference if the Jenteki.net had a tool for that work. It would make Hivemind, Contract Killer and Trick of Light realy playable even tho it is not done yet. 

Also that would improve the popularity of the Site before it is complete.

**Comment by nealterrell** [comment]
There still isn't such a tool, but I thought you might like to know that we have lately implemented Hivemind and Trick of Light, two of the more important token-related cards. AFAIK all the remaining cards with counters can be faked.

**Comment by JoelCFC25** [comment]
This one seems obsolete for now (until some future card comes along that can't be accommodated).
