### ISSUE TITLE
Interaction between Sensie Actors Union and Daily Business Show not captured in log

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1508]
Cenedra rezzes Sensie Actors Union.
Cenedra uses Sensie Actors Union to draw 3 cards.
Cenedra uses Daily Business Show to draw additional cards.
Cenedra uses Daily Business Show to add 1 card to bottom of R&D.

If I understand this, four cards get drawn, two get put back on the bottom of R&D? The automation was right (I think) but the log doesn't show that.

**Comment by JoelCFC25** [comment]
The number of cards put on the bottom of R&D is equal to the number of rezzed copies of Daily Business Show. If there is only one DBS, then only 1 card (of however many were drawn at once) gets bottomed.

**Comment by tolaasin** [comment]
According to the ufaq,

The Corp draws four cards, adds one of the drawn cards to the bottom of R&D due to Daily Business Show’s ability, then adds any card from HQ to the bottom of R&D due to Sensie Actors Union’s ability.

So shouldn't the log show two cards bottomed?

**Comment by JoelCFC25** [comment]
Ah, I didn't look at the Sensie Actors Union text. So ultimately this is just a missing `:msg` inside the `resolve-ability` of SAU, not a problem of these two cards in combination.

**Comment by tolaasin** [comment]
cool. I assumed it was doing the right thing, but just not reporting it - glad that's the case'
