### ISSUE TITLE
Can't Login or Sign Up.

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#151]
As of Monday morning 4/6, @9:25 EST, I cannot log in to Jinteki.net. After entering my information and clicking "Log In", the screen loads/flashes, and then returns me to wherever I was previously, still claiming that I'm not logged in. 

When I try to make a new account, clicking the "Sign Up" button after entering my credentials does nothing (doesn't even remove the account information window), and as far as I can tell, does not actually create a new account.

**Comment by mtgred** [comment]
There seems to be an issue login and sign up with Firefox and Safari. It works fine with Chrome on my machine though.

I will investigate the issue. In the meanwhile, can you try in Chrome?

**Comment by mtgred** [comment]
The login issue has been fixed. You should be able to login and sign up now.

**Comment by thehunter518** [comment]
That resolved it, thank you! (I should have mentioned the browser though - I was actually using Chrome)
