### ISSUE TITLE
Bazaar and Replicator don't combine successfully

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1511]
Replicator and Bazaar installed, install Spy Camera, Replicator brings another copy into hand, but Bazaar doesn't appear to see that (I imagine as it's triggering before Replicator).

**Comment by queueseven** [comment]
Actually it's not only the order of events that could be wrong, it's also a problem that the event handler of Replicator creates a prompt, and then Bazaar fires before the prompt is resolved (and thus brefore the other Hardware from Replicator in Grip). Old enginge problem, new cards.

**Comment by yojimbosteel** [comment]
Yes, the trigger for Bazaar seems to depend on whether there is a copy in hand already. Hence the incorrect interaction with Replicator.

**Comment by nealterrell** [comment]
I will have a fix for this soon

**Comment by nealterrell** [comment]
https://gfycat.com/WhimsicalBrilliantAcornbarnacle
