### ISSUE TITLE
Employee Strike does not disable SYNC

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1513]

**Comment by nealterrell** [comment]
Which part of SYNC? The flip, or cost adjustments?

**Comment by queueseven** [comment]
The cost adjusents. Didn't test the flip to be honest, but I guess the :disabled flag on identitities prevent abilities (?)

**Comment by JoelCFC25** [comment]
I think SYNC would need a `:leave-play` that checks which side is showing and then undoes the trash cost bonus or tag removal cost bonus as needed. To subsequently re-enable it, I'm not sure...maybe an `:effect` that only works after game turn 0 and does the opposite of the `:leave-play`?
