### ISSUE TITLE
OMG Push your Luck is broken!!!1111!!!!!!

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1514]
you don't actually lose the spent credits and the messge is wrong.

**Comment by IanWhalen** [comment]
Not sure if I'm missing something, but I had trouble repro-ing either manually or using these tests:

```
(deftest push-your-luck-correct-guess
  "Push Your Luck - Corp guesses correctly"
  (do-game
    (new-game (default-corp)
              (default-runner [(qty "Push Your Luck" 1)]))
    (take-credits state :corp)
    (play-from-hand state :runner "Push Your Luck")
    (prompt-choice :corp "Odd")
    (prompt-choice :runner 3)
    (is (= 0 (:credit (get-runner))) "Corp guessed correctly")))

(deftest push-your-luck-incorrect-guess
  "Push Your Luck - Corp guesses incorrectly"
  (do-game
    (new-game (default-corp)
              (default-runner [(qty "Push Your Luck" 1)]))
    (take-credits state :corp)
    (play-from-hand state :runner "Push Your Luck")
    (prompt-choice :corp "Even")
    (prompt-choice :runner 3)
    (is (= 6 (:credit (get-runner))) "Corp guessed incorrectly")))
```

Is there some interaction with another card that I'm missing?

**Comment by queueseven** [comment]
mmhh... I tested it and it seems to work (mostly) fine. Someone on Slack said it was broken and I just created this issue. 

Nonetheless, the following should be added 

`(show-wait-prompt :runner "Corp to guess odd or even)`

Otherwise, it seems to the runner the card has no effect at first.....

**Comment by JoelCFC25** [comment]
Yeah I was wrong about spent credits not being lost--was expecting to see an explicit usage of `lose`, but forgot that they're automatically spent when doing a `:choices :credit`.

**Comment by queueseven** [comment]
@IanWhalen feel free to PR your tests.

**Comment by IanWhalen** [comment]
Will do but I'd like to include the prompt changes too, and the show-wait-prompt/clear-wait-prompt functions aren't interacting exactly as I was expecting them too.  Going to work on that hopefully this weekend, and also spend that time figuring out exactly how to step through with the intellij debugger.

**Comment by IanWhalen** [comment]
@queueseven This is low prio, but when you get a chance can you look at this gist with a proposed impl of these prompts:

https://gist.github.com/IanWhalen/267eca339b70da43b255bc11ee896b3d/revisions?diff=split

Line 1 is adding _two_ identical prompts to the runner's prompt queue rather than one - that means that clearing the prompt on line 6 doesn't clear the runner's full prompt queue.  Should I be declaring the wait prompts somewhere else?
