### ISSUE TITLE
Palana Gets a Credit at the Start of a Game Against Adam

### ISSUE THREAD

**Issue by Saracenar** [mtgred/netrunner#1517]
I think when the game starts, Palana's ability treats the installation of the Directives as a draw somehow, and it gains a credit. Pretty minor and easily accounted-for bug, but I thought I'd mention it.

Thanks

**Comment by queueseven** [comment]
The call to `draw` has to replaced with  `take`/`concat` (like DBS does it (wrongly))

**Comment by IanWhalen** [comment]
Any reason I can't just add `{:suppress-event true}` as follows?

    (draw state :runner (count (filter in-hand? directives)))))}}})

becomes

    (draw state :runner (count (filter in-hand? directives)) {:suppress-event true})))}}})

It seems to work with the test I've written.

**Comment by zaroth** [comment]
Yeah, as I recall, the `:suppress-event` was initially added specifically as a way to prevent Palana from firing for Andromeda, mulligans... I guess we missed Adam.

**Comment by Saracenar** [comment]
Thanks guys : )

**Comment by queueseven** [comment]
didn't know about `:suppress-event`. Seems fine.
