### ISSUE TITLE
Utopia Shard issues?

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#152]
Just had a game freeze up with these errors when a Utopia Shard was used:
![screenshot 2015-04-07 at 10 59 53 pm](https://cloud.githubusercontent.com/assets/1702745/7039665/0e512db2-dd7a-11e4-86bd-569d39f52d75.png)

**Comment by mtgred** [comment]
There a bug with Utopia Shard indeed. It should be fixed now.

**Comment by eah13** [comment]
:sunglasses:
