### ISSUE TITLE
Unable to Score an Adequately Advanced Agenda

### ISSUE THREAD

**Issue by Saracenar** [mtgred/netrunner#1524]
This could be a weird one. I had a once-advanced NAPD Contract in play at the start of my turn. I then advanced it three times, so that I could score it, but when I clicked on the agenda to score it, I was not presented with the option to do so. Instead, I got a message that I was "unable to pay for NAPD Contract". I think what happened was, the game didn't recognise that I had adequately advanced the agenda and assumed that when I clicked on it I was trying to continue advancing it, and the message was telling me that I didn't have the clicks to do that. Alternatively, the game may have thought that I needed to spend 4 credits to score it. Although I did have 4 credits when I scored it. I dunno.

I added more clicks and it allowed me to continue advancing it, but not to score it, even though it had more advancement counters on it than it needed now.

I tried adding it to my hand and re-installing it, but that didn't do anything. I tried putting it in a new server, but that didn't help either. I was only allowed to advance it. Unfortunately my opponent won before I could try with any other agendas, but then, even though I had not scored any agendas, the message box announced that I had won. This is likely probably not related but I thought I would mention it.

If you need more information about the board state, I can provide it. It was New Angeles Sol against Val. The NAPD was in a remote server with 3 ICE protecting it. I had no agendas scored and my opponent had three. Not sure what else matters, or if I'd even be able to replicate it.

Thanks

**Comment by zaroth** [comment]
What comes to mind after reading these two parts:

> I had a **once-advanced** NAPD Contract in play at the start of my turn. I then advanced it **three times**, so that I could score it, but when I clicked on the agenda to score it, I was not presented with the option to do so. 

>  It was New Angeles Sol against **Val**. 

You do realize that NAPD's advancement requirement increases by 1 for every bad pub you have? So not being able to score a 4-advanced NAPD is absolutely correct in this situation. Although the second part:

> I added more clicks and it allowed me to continue advancing it, but not to score it, even though it had more advancement counters on it than it needed now.

Is kind of worrying, I admit.

**Comment by Saracenar** [comment]
Ah. Nevermind. I completely forgot about that part of the card. That's embarrassing.
