### ISSUE TITLE
Feature request: Tracking clicks - icons & colours

### ISSUE THREAD

**Issue by shizusreq** [mtgred/netrunner#1527]
Currently all actions are recorded in chat, which is great but can get a bit overwhelming depending on the speed of the game and the complexity of the interactions.

What I would suggest is icons representing clicks which change colour depending on who's turn it is.  When a click is used, an icon changes into a symbol that represents the action taken (take credits, draw or play a card, use an installed card, make a run, etc.). When you hover over an icon it displays the relevant information (what card was played, which server a run was made on, etc.). At the end of each turn the symbols are recorded in numbered rows and put into a dialogue box similar to the current chat box.

This wouldn't replace chat, but would provide a simple and clear breakdown of the clicks spent each round. Not sure how doable this is on a technical level. A simpler solution that might help is to change the text colour in chat according to who's turn it is.

**Comment by queueseven** [comment]
> What I would suggest is icons representing clicks which change colour depending on who's turn it is. When a click is used, ...

sounds interesting. maybe you can create a mock up of how it should look like? I could image something like:

[run symbol]: Server 3
[run symbol]: HQ (Account Siphon)
[click symbol]: Magum Opus


> change the text colour in chat according to who's turn it is.

I thought of this myself, because it's not only useful, but also quite simple.

**Comment by shizusreq** [comment]
In my mind it looks something like this:
![click tracker sample](https://cloud.githubusercontent.com/assets/14749212/15295041/0284b6b2-1b8f-11e6-86d0-5ae94e0adc1c.png)

The top row (row 2) would be the active player's click tracker and the symbols change when they use their clicks. When the turn ends the active player's row moves down with the recorded actions in place (row 1). The symbols in each row should be the colour of the side or ID who's turn it was (was too much of a hassle to colourise the sample...).

When you hover over any of the symbols the relevant information appears. With regards to something like Account Siphon, I would place the "Play card" symbol in the tracker and when you hover over it the card appears (like it currently does when the name appears in chat). What would be awesome is if you could link the symbols with the entries in chat, so that when you click on a symbol the chat scrolls to the relevant section.

**Comment by queueseven** [comment]
What happens if you have more than 4 clicks? 

For example. Biotic Labor decks, or Hyper/Medium decks that aim to do a 13 click turn?

**Comment by shizusreq** [comment]
The proposed size of the click tracker window in the sample should be able to cope with that amount of clicks. Since the clicks would be coloured and the turns numbered, each turn doesn't have to be limited to a row. If the amount of clicks can't fit into one row, they flow into the next. I was thinking five symbols across would be the optimal size.

**Comment by Quarg** [comment]
Personally, I think the simpler, more sensible thing, would probably just to be to make actions from clicks have a more distinct visual form in the chat log:
![jinteki_action_log](https://user-images.githubusercontent.com/6743892/43012075-43669724-8c3d-11e8-9389-941b60017145.png)

**Comment by NoahTheDuke** [comment]
Not gonna implement this. Screen space is already tight and this would exacerbate it.
