### ISSUE TITLE
Use crosshair targeting for more cards...

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1531]
like Mumabd City Hall (open the deck like Jackson opens Archives, so you can see the order of your deck and decide if you want to play Heritage or Salem)

also Archer (when playing e.g. Titan or having agendas with counters in general (or even Political Grafity), you want to see _which_ Hostile Takeover you forfeit).

**Comment by zaroth** [comment]
As for the mumbad city hall - how about opening the deck + crosshair targetting only if a "Manual select" button is clicked? Or at least highlighting the valid targets (alliance cards).

**Comment by queueseven** [comment]
Yeah, highlighting sounds good. Or maybe use transparency on invalid targets.

**Comment by nealterrell** [comment]
The Archer thing is coded into the `pay-cost` routines, when a `:forfeit` key is part of a costs vector. Should be relatively simple to change the prompt type.

**Comment by Saintis** [comment]
Maybe also using crosshairs to select servers to run on / install in.
