### ISSUE TITLE
Subliminal Messaging Not Returning To Hand

### ISSUE THREAD

**Issue by pjbrand** [mtgred/netrunner#1537]
Hi, 

It seems that you're aware of this issue based on the card implementation status page, but the Subliminal Messaging + SanSan Shipment with Jeeves is probably going to be extremely common in the upcoming meta. Manually dragging from Archives does work, but I find myself straining through the log to see if the opposing player had run at all last turn. It gets quite taxing on the mind when the Jeeves deck revolves around 3 Subliminal and 3 SanSan Shipment.

Thanks for looking into this.

**Comment by JoelCFC25** [comment]
There was a substantial effort put in at #1251 by @kevkcc for this card--not sure if he's still planning to resubmit it.

**Comment by Kiv** [comment]
+1, this would be great to have in. Unlike in a physical game, it's very difficult to keep an eye on the full contents of Archives because the Archives popup covers your board.

**Comment by kevkcc** [comment]
I haven't had the time to do any development because I've been out of the country for the last couple months and still will be for awhile yet. But I will continue to work on it when I can.

**Comment by nealterrell** [comment]
This has been deployed!
