### ISSUE TITLE
Feature Request: accept card names without accents

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1538]
I often try to import cards like Deja Vu and it won't let me, because it wants me to type the accents. Monolingual English people aren't used to doing this and might not know how at all.

**Comment by Kiv** [comment]
Looks pretty straightforward to compare what the user typed to the card title with the accents stripped, but I don't know where in the code to hook in something like this:

https://github.com/expez/superstring/blob/master/src/superstring/core.cljs#L495

**Comment by queueseven** [comment]
Could go into a new file `utils.cljs` and then imported into `deckbuilder.cljs` (or go directly into `deckbuilder.cljs`) and then used in the `search` function. Feel free to try it yourself and creating a pull request ;-)

**Comment by zaroth** [comment]
I think I can advise you both to wait a bit, since NRDB will soon provide `title_normalized` and `text_normalized`, so if that's the only use case, probably no need for importing libraries. https://github.com/zaroth/netrunner-cards-json/issues/14

**Comment by queueseven** [comment]
Good news! That makes it easier
