### ISSUE TITLE
Activist Support/Paparazzi is not giving a tag

### ISSUE THREAD

**Issue by CoryDCode** [mtgred/netrunner#1539]
Activist Support's condition is "if you have no tags," but the game seems to be treating it as "when not tagged." It's rarely important, but it is slightly wrong.

**Comment by CoryDCode** [comment]
(Also - I'd like to try my hand at fixing this one, but don't have the time for a couple more hours. If I haven't submitted a pull request for this by tomorrow, have at it, though.)

**Comment by JoelCFC25** [comment]
The `:corp-turn-begins` event for Activist Support needs to use this `:req`:  

`:req (req (= 0 (:tag runner)))`
