### ISSUE TITLE
Queen's Gambit does not prevent card access

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#1542]
As the title states, Queen's Gambit does not prevent access to the target card. This matters particularly when the runner plays Gambit on an unrezzed upgrade, then runs said server to trash the asset/agenda in that server.

**Comment by JoelCFC25** [comment]
For the time being, I've updated the card status sheet to mark this one "Partial" with a note about its limitation.

**Comment by Saintis** [comment]
This could probably be solved by adding a `can-access?` flag check and checking this for each card when accessing.

Have added to my list..
