### ISSUE TITLE
Ixodidae gives credits for psi games

### ISSUE THREAD

**Issue by TeachMeToAim** [mtgred/netrunner#1546]
Currently Ixodidae gives credits to the runner when corp spend money during psi games. Spend is not the same as lose though, so this is wrong.

**Comment by JoelCFC25** [comment]
Thanks for the report. It would probably work to pass `{:suppress-event true}` in the two uses of `lose` in `resolve-psi`.

**Comment by JoelCFC25** [comment]
Update: I tried my idea and it didn't work.

**Comment by Saintis** [comment]
Works if you change the `lose` to `gain` the negative amount in psi-games.
