### ISSUE TITLE
Limit length of deck names

### ISSUE THREAD

**Issue by Armeroth** [mtgred/netrunner#1548]
Now have this issue:

![add](https://cloud.githubusercontent.com/assets/19567803/15533322/db885c1e-226c-11e6-80d8-355750ee03b6.jpg)

**Comment by zaroth** [comment]
Looks like in my search for sanitizing user input I missed that deck name length was unlimited. Sanitizing user input is important after all, it seems.
I suppose a 60 char deck name limit should be sufficient.

**Comment by Armeroth** [comment]
Ok. but now I cannot edit it.

**Comment by Saintis** [comment]
A fix would be to wrap deck titles or at least hide extended titles. Should be a quick fix on the client side.

**Comment by queueseven** [comment]
As a simple workaround, install a browser plugin that allows you to inject CSS, and add

```
.deck-collection .deckline h4 {
  text-overflow: ellipsis;
	width: 260px;
	overflow: hidden;
}
```

this should be added to the site's CSS as well in addition to the limit of the deck name.

**Comment by Saintis** [comment]
Should be fixed now.
