### ISSUE TITLE
Silhouette, Account Siphon & Psychic Field - incorrectly ordered

### ISSUE THREAD

**Issue by sodwyer** [mtgred/netrunner#155]
The scenario:
Silhouette plays Account Siphon against the Corp who has 5 creds and an unrezzed Psychic Field.
The run is successful and the following happens:
- sil ability triggers, runner is asked to choose a target for the expose
- runner chooses the unrezzed Psy Field
- runner is asked to choose Run Ability or Access for the acc siphon, runner chooses run ability and corpo now has 0 creds
- psy field psi game is triggered, easy win for runner because corp has 0 creds.

Expected behaviour:
The expose triggers at 4.4 and so the psi game should also trigger 4.4 while the corp still has 5 creds.
The acc siphon choice should occur afterwards, at 4.5

**Comment by JoelCFC25** [comment]
This can be made to work correctly by changing Silhouette's ability to be manually triggered just like Laramy Fisk.
