### ISSUE TITLE
runner can move ice to grip; attempting to install makes the ICE disappear

### ISSUE THREAD

**Issue by sea-sparks** [mtgred/netrunner#1551]
# The Issue

As runner, I was able to move corp ICE to my grip during a game. I was able to click on the ice to spend a click to install the ICE, giving me the same menu you'd expect (central, existing remote, new server, etc). Upon doing this, it triggered the corp's ability for the corp (they were playing EtF, and so they gained a credit), and according to the corp player the ICE seemed to have disappeared from the game (i.e. completely gone, not moved to the "removed from game" zone).

# What Happened

I doubt the context matters, but just in case: I was playing MaxX, I spent my last click installing a parasite on a Wall of Static in the middle (position 2 of 3) of a remote server, changed my mind, and tried to drag the parasite back to my grip. Instead, I got the ICE in my grip, though the parasite was trashed appropriately. Afterward, I gave myself a click and attempted to install the ICE in front of the server it came from. I can't remember if it charged either of us the install cost (in the screenshot it said it did, but I didn't verify this with my credit total, alas), but it claimed to install it, but disappeared it instead.

## System Specs

I'm running OSX 10.11.5, and my browser is Chrome 50.0.2661.102 (64-bit).

# Recreation

I'm not going to sucker someone on jinteki into letting me wreck their ICE even more than anarch usually does, so I haven't tried to repeat this myself. I imagine it's a simple matter of the runner dragging a piece of ICE from the corp's board into their grip, similar to how one would e.g. manually apply Archangel's trace effect. The ICE I did this to was rezzed at the time; I have not verified on unrezzed ICE. After this, the runner can spend a click to install the ICE, at which point it will likely disappear.

# Screenshots

Proof! 
![image](https://cloud.githubusercontent.com/assets/16215824/15548775/deef46c8-2277-11e6-8419-31a4b2e1daf4.png)
![image](https://cloud.githubusercontent.com/assets/16215824/15548782/e57ba2fc-2277-11e6-9221-ff29dab374e3.png)

**Comment by JoelCFC25** [comment]
Thanks for the report. This issue was previously submitted at #1161. You have to take care that you are actually hovering over the Parasite when you start your click and drag--but yes, this is something that needs to be prevented entirely.

**Comment by sea-sparks** [comment]
Oh rad, thanks! Sorry for the duplicate---was searching for the wrong keywords.
