### ISSUE TITLE
Salsette Slums + Trashing Crisium Grid = Crisium Grid PermaActive?

### ISSUE THREAD

**Issue by MHGray** [mtgred/netrunner#1553]
Had this happen in a game today, had Crisium Grid on HQ rezzed. Runner ran HQ and trashed Crisium using Salsette Slums thus removing it from the game. From then on whenever he ran HQ successfully he did not get his Datasucker virus tokens. Haven't tried this with other 'on successful run' effects but would suspect the same.

**Comment by JoelCFC25** [comment]
Thanks for the report. Just from a quick look at what Salsette Slums is doing, the code is missing anything that would `deactivate` the card (all it's doing is moving it to the `[:rfg]` zone). Thus, Crisium's suppression effect is lingering on.
