### ISSUE TITLE
Stolen/Turntabled Chronos Project Not Triggering with 24/7

### ISSUE THREAD

**Issue by se4n** [mtgred/netrunner#1555]
This is certainly an edge case but I'll describe what happened in a game today -- I, playing PE, had a naked Chronos Project on the table, with a Profiteering and a full House of Knives scored. The runner had Turntable installed, ran on the Chronos Project, and instead of stealing, swapped it with my full House of Knives. Now I had a Chronos Project and a Profiteering in my score area, and they had the full House of Knives in theirs. My turn, I play 24/7 News Cycle -- sacrificing the Profiteering, trying to trigger the Chronos Project, but it won't work.

My assumption is that since the Chronos Project was never actually *scored* (just stolen and then moved to my score area) that perhaps 24/7 needs fixing? That is, it seems to be trying to retrigger an existing thing that happens when a card is scored -- but in this case, because of Turntable (and soon with Exchange of Information), there will be cards with "when scored" abilities in the Corp's score area that were never actually scored per se.

**Comment by JoelCFC25** [comment]
I noted this at #1125, which I closed at the time because I have no idea how to handle this case.

**Comment by se4n** [comment]
Ah, thanks, sorry for the duplicate report. I didn't see #1125.

**Comment by JoelCFC25** [comment]
No, it's no problem--it was closed after all!
