### ISSUE TITLE
Dragging cards doesn't seem to work using Microsoft Edge.

### ISSUE THREAD

**Issue by the-squid** [mtgred/netrunner#1556]
It seems to want to try to copy the image instead of dragging, meaning you can't discard if you are over hand size at the end of turn.

/discard is the only option, and I couldn't work out what n was relative to :(

**Comment by the-squid** [comment]
No worries. Any way to get some clarity on using /discard?

**Comment by JoelCFC25** [comment]
`/discard #1`: discards leftmost card in hand, `/discard #2`: discard 2nd card from left, and so on.

**Comment by Neurothustra** [comment]
@queueseven Edge isn't IE, just so that no one gets confused. It's not just a name change either, different rendering engine.

**Comment by queueseven** [comment]
@Neurothustra That's true, but the behaviour is the same. `<div>`s are not dragable by default.

**Comment by Saintis** [comment]
I suggest we add this to the `bestbrowser` section on the help page. Something about drag'n'drop not working on IE or Edge.

**Comment by lopter** [comment]
Hello, this seems to be broken on Firefox (57) as well.
