### ISSUE TITLE
Installed a card over one of my servers, second server merged into it?

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#156]
I had a rezzed Director Haas installed in Server 1 and an unrezzed Adonis Campaign in Server 2. I installed a Jackson Howard over top, causing Director Haas to be trashed (as expected). Server 2 then merged into Server 1, such that there was a Jackson Howard AND an Adonis Campaign in my Server 1. It said "Server 1 (2)" meaning it even registered that there were 2 cards there.

Server 0 contained an unrezzed Eli 1.0 ICE and a rezzed Haas Arcology AI with 2 counters on it.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It will fixed soon.

**Comment by Agnate** [comment]
Just replying here to say that this happened to me again today.

**Comment by JoelCFC25** [comment]
Fixed at #394.
