### ISSUE TITLE
Publishing survey results

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1569]
Hi,

I was wondering if you intend to publish the player survey results in any fashion. I'd certainly like to see the numbers and popular suggestions, and I doubt I'm alone in this.

Thanks!

**Comment by JoelCFC25** [comment]
Yes, they will be published. We've been making progress on the graphs, and I think most of the content will go into the next Quarterly Progress Report on the wiki here.

**Comment by FarCryFromHuman** [comment]
That's great to hear, thanks!
