### ISSUE TITLE
Haas Arcology AI missing menu text and chat response

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#157]
I had a Haas Arcology AI rezzed with counters on it. Clicking on it showed an empty menu item (which is used to use a counter). Clicking on the empty menu item showed no chat message, so my opponent didn't see that I used it.

Card functioned properly to give me a click, though.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

**Comment by JoelCFC25** [comment]
GRNDL Refinery has this same issue (needs the :label bit added).

**Comment by mtgred** [comment]
Thanks for reporting the issue Joel. GRNDL Refinery has been fixed and will be deployed with the next server update.
