### ISSUE TITLE
Lily Lockwell + Political Dealings

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#1574]
This may just be an issue with the end turn timing window but when I rez Lily Lockwell with Daily Business Show after the runner's last click and then do corp draw the corp draw is just one card. Political Dealings may be helping mess this up as that's when I try that combo.

**Comment by JoelCFC25** [comment]
See #696 for discussion of the end-turn issues. There was a feature that could handle this correctly for awhile, but it was rolled back. It may return in the future in a different form.

**Comment by JoelCFC25** [comment]
Only fixable by bringing back #1337 feature.
