### ISSUE TITLE
NEW Features : BAD PUB

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#158]
A lot of player forget they can use bad pubs when they make a run.

When the corps get Bad Pub, it would be great if the Bad Pub appears on the Runner's ID with a counter on it (number of Bad Pub).
When you make a run, you can click on the Bad Pub to take one credit, exactly like a recurrent credit card works. The number on the Bad Pub is decreased.
When the run is finished, the number on the Bad Pub reset to it's initial value.

**Comment by eah13** [comment]
+1.  Nice solution.  The bad pub credits could also appear on the Run arrow when it is created, possibly on a little bad pub chit. This solution is great too because for new or inexperienced players it clearly indicates that the bad pub is tied to a run.

**Comment by JoelCFC25** [comment]
Implemented at #400!
