### ISSUE TITLE
You should be able to set your agenda points negative

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1583]

**Comment by Salem2612** [comment]
When Agenda Points are 0, clicking on the "-" button of the Agenda Points does not set the Agenda Points to -1. The Agenda Points stay to 0.

Salem sets agenda point to 1 (-1).
Salem sets agenda point to 0 (-1).
Salem sets agenda point to 0 (-1).

**Comment by queueseven** [comment]
Yeah, it made sense in the past when there was no Shi.kyu or News Team....

**Comment by domtancredi** [comment]
Do we want to set min / max limits? What else should go < 0?

Example:
http://puu.sh/poW0w/618bd2b40d.png

**Comment by domtancredi** [comment]
Basically, this is handled in the deduce function, which checks for limits prior to modifying:

`(swap! state update-in [side attr] (if (or (= attr :memory)
                                             (= attr :hand-size-modification))
                                       ;; Memory or hand size mod may be negative
                                       #(- % value)
                                       #(max 0 (- % value))))
`

https://github.com/mtgred/netrunner/blob/master/src/clj/game/core-costs.clj

**Comment by domtancredi** [comment]
Ready to be closed
