### ISSUE TITLE
NEW Feature : TAG

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#159]
A lot of player forget that the runner is tagged.

It would be great if the tag appears on the runner's ID with a number on it (number of tags)
When the runner untags himself, the number decreased. When this number is 0, the tag disappears.

to avoid problem of display with Bad Pub ( #158 ) , you should specify two distinct locations for tags and bad pubs on the runner's ID.

**Comment by queueseven** [comment]
Implemented with https://github.com/mtgred/netrunner/pull/600
