### ISSUE TITLE
Mr. Li and Genetics Pavilion interation

### ISSUE THREAD

**Issue by fmarvez** [mtgred/netrunner#1594]
Genetics Pavilion reads: The Runner cannot draw more than 2 cards during his or her turn.
Mr. Li reads: Draw 2 cards. Add 1 of these cards to the bottom of your stack.

Issue: The runner is not prevented from drawing more cards after using Mr. Li or after previously drawing cards during their turn.
Fix: The runner should be prevented from drawing more than 2 cards on their turn even when using Mr. Li.

**Comment by JoelCFC25** [comment]
The issue is that Mr. Li is using `take` and not `draw`, and only at the end manually firing the `:runner-draw` event trigger, but without a numeric value.

**Comment by queueseven** [comment]
The problen is that Daily Business Show also does not `draw` the cards. Related issue: #1450.

Basically all cards that `take` cards needs to be reworked to either use `draw` (or have `take` trigger the draw event or something).
