### ISSUE TITLE
Leela Patel and Legwork not working

### ISSUE THREAD

**Issue by KyotoBliss** [mtgred/netrunner#1597]
Played Against Palana ID and each time Legwork was played, could only access one card.

**Comment by KyotoBliss** [comment]
Also - he Slummed a Crisium that was on HQ one turn before. 
1. Slummed a Crisium
2. Played Legwork as next click and only access one card. 
Next turn - 
1. Played Legwork on HQ with no ice and no upgrades
2. Could only access one card.

**Comment by queueseven** [comment]
>  Slummed a Crisium

Does that mean there was a rezzed Crisium Grid on HQ when you played Legwork or does that mean that there was a rezzed Crisium Grid on HQ and then you trashed it before playing Legwork?

Since Crisium Grid prevents Legwork from firing its ability, if there's an issue, it sounds like an issue with Crisium Grid, and not Leela or Legwork.

**Comment by KyotoBliss** [comment]
Run 1 - Crisium was slummed - so out of the game
Run 2 - Legwork into HQ - access was limited to one card and run ended. 
Next turn
Run 1 - Legwork into HQ, access was limited to one card again. HQ had no ice and no Crisium or other upgrades. 

I am not a programmer but I guess your suggestion that it could be Crisium is also possible. Sorry to not be of more help. Just wanted to report the issue.

**Comment by queueseven** [comment]
Thanks for your report. I can just not make sense of the word *slummend*, so when you had said *trashed*, it would be more clear what happened :-)

**Comment by KyotoBliss** [comment]
Ah, sorry about that. The Crisium card was removed out of the game by the Salsette Slums card. [Link here.](https://netrunnerdb.com/en/card/10059)

**Comment by queueseven** [comment]
Ah, ok, Salsette Slums. Now I understand and feel stupid :-)

Good news, this is already fixed. Reported in #1553 and fixed in #1584.

Just waiting for the next merge and server restart.
