### ISSUE TITLE
Add an "End the run" button...

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1598]
...to the runner's run menu in addition to "jack out" (for the case when the runner doesn't break an ETR sub and doesn't want to wait for the corp to do it via the ice).

**Comment by Salem2612** [comment]
Good idea to not trigger the "when Jack out" ability of cards like Au Revoir or Reflection.

**Comment by queueseven** [comment]
Exactly

**Comment by JoelCFC25** [comment]
Can this be closed now that we have the ability to let Runners click ICE and let subs fire?

**Comment by zaroth** [comment]
Definitely.
