### ISSUE TITLE
Suggestion: Runner Fires Ice Subroutines (especially HB click ice)

### ISSUE THREAD

**Issue by AlecGamble** [mtgred/netrunner#1605]
Okay so I've been feeling for a while that firing ice effects seems more innately like an action the runner should be in charge of. I think if it was changed to be this way around the game would play a lot smoother because then you wouldn't need to explain when you're allowing specific subroutines to fire or not. Especially since in a lot of cases the corp hasn't seen some of the shenanigans I've been pulling and prematurely fires the subroutines which we then have to go back and fix after a lot of explaining.

One situation where I definitely think the runner should have actions for the ice are ones where they can pay a click or two to ignore subs.

**Comment by JoelCFC25** [comment]
This same discussion is going on in #1599--maybe you can join the party there! :)
