### ISSUE TITLE
Mumbad City Grid and jack out timing

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#1607]
With the way Mumbad City Grid is currently implemented, it does not correctly interact with the runner jacking out.

MCG's trigger condition is "when the runner passes a piece of ice", which occurs before they have the opportunity to jack out.

However, with the current implementation, MCG can only be used if the runner clicks "continue", ie: the runner's opportunity to jack out is before MCG can be used.

**Comment by JoelCFC25** [comment]
The `:req` for the MCG ability could just be simplified to `(req this-server)`. I guess the way I did it initially was too restrictive.
