### ISSUE TITLE
Forfeiting Posted Bounty causes crash

### ISSUE THREAD

**Issue by fmarvez** [mtgred/netrunner#1611]
When the corp scores and then attempts to forfeit a Posted Bounty, the game crashes for the corp user with the following error:

Uncaught TypeError: $(...).Yj is not a function

Obviously not helpful as it's minified but there you are.

**Comment by nealterrell** [comment]
I have a fix, thanks. Game is attempting to give the corp agenda points equal to the points of the now-missing agenda.
