### ISSUE TITLE
Turning Wheel keeping multiple accesses on Sneakdoor Beta run

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1614]
I just saw a Leela player who had previously used Turning Wheel to dig R&D get a full 4-card access on HQ on a later turn without spending any TW tokens. The run on HQ was initiated via Sneakdoor Beta, so the problem may lie there. I had the runner make two additional runs, one via SB and one normal, and no extra accesses were given.

The extra runs were made after the corp trashed Turning Wheel via tags, so I don't have the best test case for this. I'll try to replicate when I'm not at work.

**Comment by nealterrell** [comment]
Yes, it looks like Sneakdoor is the reason. We'll probaby have to do a minor rework of the card now that we have better engine functionality for programming it.
