### ISSUE TITLE
Searchlight Trace Crashes Corps Interface

### ISSUE THREAD

**Issue by meatpopup** [mtgred/netrunner#1618]
Hallo,

after firing a sub on Searchlight, the corp can't use the "Boost trace Strenght?" pop-up.
"/close-prompt" leaves the corp with "Waiting for Runner to boost Link strength", which you can't skip.
Love my Searchlight :)

Thx very much for the good work. Have a nice WE, guys.

**Comment by nealterrell** [comment]
You should be able to `/close-prompt` the "Waiting" too, but thanks for the report.

**Comment by JoelCFC25** [comment]
It really doesn't like the form `:base advance-counters`--generating an arity error referencing line 396 in core-abilities.clj.
