### ISSUE TITLE
"Freedom through Equality"

### ISSUE THREAD

**Issue by Humanoidss** [mtgred/netrunner#1620]
"Freedom through Equality" triggers even while in the score area (meaning, it will trigger each time an agenda is scored, even if it has already been added to the score area).

**Comment by JoelCFC25** [comment]
The root cause here is the same as discussed in #1609.

**Comment by Humanoidss** [comment]
All right, sorry about that, then.

**Comment by nealterrell** [comment]
No problem, always better to report any issues you see :).
