### ISSUE TITLE
Liberated Chela

### ISSUE THREAD

**Issue by Nords3x4** [mtgred/netrunner#1628]
Just a heads up, when I use Liberated Chela, Sacrificing an agenda on the runners side works fine on , but it does not prompt the corp with the option to sacrifice an agenda.  Because the second part of the card never resolves, Liberated Chela is not removed from the game and the scores are not automatically adjusted.  I doubt too many people are playing this card, so maybe not a lot of feedback on it.  Thanks for making Jinteki.net so great, you rock!

Nordrunner

**Comment by JoelCFC25** [comment]
Thanks for the report. This card worked when I originally implemented it, but is now throwing an arity error from all the new simultaneous event improvements made lately. @nealterrell and I will get to the bottom of it.

**Comment by JoelCFC25** [comment]
In the spirit of full disclosure, this was my error (forgot a parameter to `show-wait-prompt`), not something introduced by Neal's changes. :)
