### ISSUE TITLE
Ramujan Reliant damage prevention not working

### ISSUE THREAD

**Issue by commissarfeesh** [mtgred/netrunner#1631]
When clicking on Ramujan Reliant BMI to prevent damage, does not interrupt/override the prompt "do you want to prevent damage", meaning you have to actually click 'done', suffer the damage, **then** you get the Ramujan prompt asking how much damage you want to prevent.

**Comment by JoelCFC25** [comment]
Thanks for the report. While this is being fixed, the ability also needs `:req (req (> (count (:deck runner)) 0))` added to ensure that the Stack has at least 1 card in it.

**Comment by nealterrell** [comment]
My bad.

**Comment by commissarfeesh** [comment]
Thanks guys, for taking the time to fix this for the one Ramujan player in existence 😅
