### ISSUE TITLE
Allow cards in the "current" zone to have abilities

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1633]
e.g. for targeted marketing

**Comment by JoelCFC25** [comment]
Didn't I already do this for Targeted Marketing? 

![screen shot 2016-06-13 at 9 15 41 pm](https://cloud.githubusercontent.com/assets/10407969/16029155/159421e2-31ac-11e6-9f26-799e930a0c19.png)

**Comment by queueseven** [comment]
Mmmh, my opponent told me it didn't work...

I tested it myself and it seems to work.
