### ISSUE TITLE
15 Minutes ability text missing

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1637]
![image](https://cloud.githubusercontent.com/assets/3126597/16009513/577308d2-317d-11e6-944f-452918e9f4e3.png)

**Comment by nealterrell** [comment]
How did you even get this menu to come up?

**Comment by queueseven** [comment]
I clicked on 15 Minutes in the runner's Scored Area.

**Comment by nealterrell** [comment]
I can't get this menu to show for me. The agenda should not have a "Score" option in the scored area; it should have a single ability, and clicking the agenda should auto-trigger that ability. This is what happens on my local server.

**Comment by queueseven** [comment]
Strange. This picture is from a game on j.net. I don't  have a working dev environment at the moment, so I can't investigate it myself

**Comment by JoelCFC25** [comment]
I get the same behavior as @queueseven is seeing in my dev environment.
