### ISSUE TITLE
suppress similar messages

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1641]
For example, when using Snitch, you get the following log:

> queueseven spends  to make a run on Server 1.
> queueseven uses Snitch to expose Ichi 1.0.
> queueseven exposes Ichi 1.0 protecting Server 1 at position 1.
> queueseven uses Snitch to jack out.
> queueseven jacks out.
> queueseven uses Au Revoir to gain 1 .
> queueseven uses Au Revoir to gain 1 .
> queueseven is ending their turn 5 with 6  and 4 cards in their Grip.

The messages 

> queueseven exposes Ichi 1.0 protecting Server 1 at position 1.

and

> queueseven jacks out.

should be prevented.

**Comment by JoelCFC25** [comment]
The duplicated expose message is fixed in #1651, at least.
