### ISSUE TITLE
Dinosaurus does not update strength of ICE breaker....

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#1643]
...when the ICE breaker is hosted after installing it (e.g. SMC it into play, then host it on Dinosaurus.

![image](https://cloud.githubusercontent.com/assets/3126597/16035862/9a6c576e-3219-11e6-8f09-91a66761f462.png)

**Comment by JoelCFC25** [comment]
I'm baffled by why the obvious fix isn't working.

**Comment by nealterrell** [comment]
What's the obvious fix?
