### ISSUE TITLE
Worlds Plaza does not place credits on Adonis

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#1644]
When using Worlds Plaza's click to install and rez ability, no credits are placed on Adonis. It just sits there with no credits on it.

**Comment by JoelCFC25** [comment]
Can you try it again, by chance? It's working for me--this was in my dev environment just now: 

![screen shot 2016-06-15 at 7 29 52 pm](https://cloud.githubusercontent.com/assets/10407969/16101851/9d0038ee-332f-11e6-8261-e91743827a9d.png)

**Comment by Quarg** [comment]
Just managed to replicate it.

If you do not have the money to rez it, it gets hosted on it face up, making it appear rezzed, when it isn't, it should probably check that you are able to pay it's rez costs

**Comment by JoelCFC25** [comment]
Ah, that is a key piece of information--thanks.

**Comment by JoelCFC25** [comment]
I think hosting on Corp cards in servers needs larger scale improvement, as I discovered when trying to work on Full Immersion RecStudio yesterday. Just using the `host` function leaves (as you discovered) the installed card in a face-up state even though it's not rezzed (yet).
