### ISSUE TITLE
Jinteki Biotech: Life Imagined ---> NOT WORKING

### ISSUE THREAD

**Issue by hikata** [mtgred/netrunner#1645]
Jinteki Biotech: Life Imagined ID isn't working when I use the Brewery. The log says that it fired, but no net damage is dealt and the the log doesn't say "[name] wins" when used appropriately. It also takes a good while to show up in the log after using it. 

I don't know if this happens when using the other Biotech abilities.

**Comment by JoelCFC25** [comment]
Thanks for the report--this has already been fixed at #1626 and is awaiting deployment at the next restart.
