### ISSUE TITLE
Corp can add cards from hand to the Runner's zones

### ISSUE THREAD

**Issue by rdhambrick** [mtgred/netrunner#1646]
By dragging a card from hand to the Runner's Grip, a message in the chat box pops up, "<corp player>  moves a card from their HQ to Grip." Doing this causes the card to disappear completely.

Similarly, the Corp can put a card from hand into the Runner's Stack, prompting the message 
 "<corp player>  moves a card from their HQ to the top of Stack." Doing this actually puts the corp card into the Stack, where the Runner can see it if he/she looks.

Lastly, the Corp can drag a card from Archives to the Runner's Grip, prompting the message "<corp player> moves a card from their Archives to Grip." The card is added to the Runner's Grip and has the red back like all Runner cards.

None of these should be possible as far as I know.

**Comment by JoelCFC25** [comment]
Correct, up to this point there have been few restrictions on what can be dragged where. Related: #1551, #1161 (contains limited discussion of a remedy).
