### ISSUE TITLE
Cyberdex Virus Suit ends accesses (on Archives?)

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#1647]
I'm not sure how it works in general, but I just accessed Archives with an agenda and a CVS in it. Accessed CVS first. At this point I think in the past I got text saying I access CVS? Because that also doesn't show anymore. Corp chooses if they purge or not and I get the option to trash CVS. After this I could not access the agenda anymore, there was no prompt for it.

**Comment by nealterrell** [comment]
Thanks, I have a fix coming.
