### ISSUE TITLE
Liberated Chela still bugged

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#1649]
Greetings,

The popup interface wouldn't let me click on "no" to avoid forfeiting a agenda. Game and chat froze up for a bit. I had to use /close-prompt to cancel and runner adjusted everything manually.

**Comment by JoelCFC25** [comment]
Thanks. I see it now--the use of `as-agenda` in the case of the Corp saying "No" is missing the `card` parameter.
