### ISSUE TITLE
Argus Security / not working correctly

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#165]
Played a game against Argus Security: when I was offered to take 1 tag or 2 meat dmg (after stealing an agenda), the tag never got placed, and the run wouldnt end when I asked for a tag.

I would then have to put the tag manually and jack out from the run.

**Comment by JoelCFC25** [comment]
@benticurus have you been able to replicate this? Maybe the server was just having a bad day. :)

**Comment by JoelCFC25** [comment]
Closing this since there have been no further reports of it. If it crops up again reliably, please open a new issue.
