### ISSUE TITLE
Shi.Kyu bugged

### ISSUE THREAD

**Issue by tukokun** [mtgred/netrunner#1655]
Played a few games tonight where when Shi.kyu was in archives, runner couldnt access/make run successful while Shi.Kyu was there. Option became available once Shi.Kyu was removed from archives

**Comment by JoelCFC25** [comment]
Thanks--this is almost certainly the same bug as with Cyberdex Virus Suite that was fixed at #1648. When that gets deployed, Shi.Kyu in Archives should work again.
