### ISSUE TITLE
Shock! is only accessed once in Archives regardless of number of copies in Archives

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#1658]
When Shock! is in Archives and the runner makes a successful run on Archives, The runner is prompted to access each copy of Shock! in the server.  After clicking on any one of the copies, the access dialog is closed and only one net damage is done (even if there are agendas which haven't been accessed yet).

As a work-around, the runner can run /take-net n where n is the number of additional copies of Shock! in Archives.

**Comment by JoelCFC25** [comment]
Thanks--this is fixed at #1648 and awaiting deployment. See #1655 and #1647 for previous reports of this issue.
