### ISSUE TITLE
The Agenda counter on Domestic Sleepers does not trigger an Agenda point.

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#1659]
Snake Eyes started their turn 19 with 0  and 3 cards in HQ.
Snake Eyes spends  to use Domestic Sleepers to place 1 agenda counter on Domestic Sleepers.

Snake Eyes
gg

Snake Eyes
huh

Snake Eyes
Sleepers not programmed for the point
Snake Eyes sets agenda point to 7 (+1).

kwind
guess not

kwind
gg! later

**Comment by JoelCFC25** [comment]
Thanks for the report. This always worked in the past, it just didn't get adjusted in the counter rework recently.
