### ISSUE TITLE
Hostile Infrastructure triggering in error

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#166]
Submitting this on behalf of a player with no Github account: 

Hostile Infrastructure is rezzed and a Corp current is active. The Runner steals an agenda and the current is trashed, but Hostile Infrastructure fired, dealing the 1 net damage. 

I think this means the code is treating the current as being trashed by the Runner, when really it's just trashing itself.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
