### ISSUE TITLE
Crisium Grid prevents the successful use of Turning Wheel Counters

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#1663]
My opponent was only able to single-access in spite of using 6 TTW counters, which should have let him access 3 additional cards.

When we rewound the scene with me de-rezzing the Crisium Grid, he was able to access the additional cards.

**Comment by JoelCFC25** [comment]
Thanks for the report. Changing TTW's `:successful-run` event hook to `pre-access` instead seems to be doing the job.
