### ISSUE TITLE
Iain Sterling's ability doesn't trigger after rebirth

### ISSUE THREAD

**Issue by dgilbert418** [mtgred/netrunner#1667]
After using Rebirth to change identities Andromeda into Iain Sterling, Iain Sterling's ability doesn't automatically trigger at the beginning of subsequent rounds. However, I noticed it does trigger automatically if I install something at the beginning of the turn using Supplier.

**Comment by JoelCFC25** [comment]
I think this was a temporary glitch during the last update. It is working now.
