### ISSUE TITLE
Modded BUG

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#167]
When playing Modded (the Shaper operation) the game freezes if the runner doesn't use the drop menu to choose which card to install through Modded; e.g., if the runner plays Modded but then clicks directly on the card that they want to install from hand, then the drop menu doesn't go away and the game freezes (or doesnt allow the runner to do anything else).

I think sometimes it gets fixed if the runner moves the intalled card back into hand, and then uses the drop menu from Modded; but this doesnt always work, and the game cannot be continued.

**Comment by benticurus** [comment]
I recognize this is more an error on part of the player than the system; but if the player makes this simple mistake, the whole game may be lost.

**Comment by JoelCFC25** [comment]
Modded uses the card targeting system now as of #863, so this interface glitch can't occur anymore.
