### ISSUE TITLE
Salem's Hospitality and Targeted Marketing freezing games

### ISSUE THREAD

**Issue by Tr33beard** [mtgred/netrunner#1670]
Using Mumbad City Hall to play Salem's Hospitality is crashing the game. The UI freezes up on the user's side and no more actions can be taken. In addition, the chat log stops sending to the user. Actions the user takes will occur on the other player's side and anything typed into the chat window, while not viewable by the player who played Salem's Hospitality, will show up on the opposite end. This issue has occured every time in this scenario during my testing.

**Comment by Tr33beard** [comment]
Turns out, it just happens whenever Salem's is played, not just with City Hall

**Comment by JoelCFC25** [comment]
Thanks--I've posted a News item that Targeted Marketing and Salem's Hospitality are not playable right now. We'll get to the bottom of it soon (these are both working fine for me in my dev environment).

**Comment by JoelCFC25** [comment]
These are working now.
