### ISSUE TITLE
When Accelerated Beta Test triggers The Foundry, cards in the temporary zone should be shuffled into R&D

### ISSUE THREAD

**Issue by benhosp** [mtgred/netrunner#1672]

**Comment by JoelCFC25** [comment]
I'm dubious that this can be automated in a nice way, [as indicated here](https://github.com/mtgred/netrunner/pull/772#issuecomment-144440817) when recursive installs were added to ABT.

**Comment by nealterrell** [comment]
I CAN FIX THIS NOW.
