### ISSUE TITLE
multiple gang signs

### ISSUE THREAD

**Issue by MauiChris** [mtgred/netrunner#1674]
it looks like there's a new bug that started today. i was playing Leela & had 2 hq interfaces up with 2 gang signs, when the corp scored an agenda. THe prompts opened up (gang sign, gang sign, leela). i triggered the 1st gang sign & accessed an adonis campaign, which gave the prompt to trash & i did. This closed the the prompts on my side & the corp player had the "waiting for runner actions" prompt still active.

I was unable to access the 2nd card (HQ interface) on the first gang sign access. I was unable to trigger the 2nd gang sign & unable to trigger Leela's ID ability.

**Comment by JoelCFC25** [comment]
It's all working as expected for me in dev, trying on live momentarily.

**Comment by MauiChris** [comment]
just to clarify, if there's no trashing of a card, it seems to work ok.

Thanks Joel!

**Comment by JoelCFC25** [comment]
It's all working fine for me on live as well. Can you confirm you have done a forced refresh since yesterday's restart?

**Comment by MauiChris** [comment]
yes, i have. it's happened a few times. i'll report back if it continues to happen or if i can add more info

**Comment by JoelCFC25** [comment]
I'm not certain of this, but it could be possible to see this behavior if you have the current client code but your opponent did not...

**Comment by queueseven** [comment]
We should really Start versioning our Javascript files

**Comment by MauiChris** [comment]
quick update. I haven't seen this issue since. Maybe it was the other player running old client code?
