### ISSUE TITLE
Game state error when attempting to rez a Zealous Judge

### ISSUE THREAD

**Issue by Makai** [mtgred/netrunner#1675]
More specifically, I tagged the runner with SEA Source on click 1, Trashed a Resource on click 2, and installed Zealous Judge on click 3 and attempted to rez him right away. Instead of rezzing the judge I got a pop-up mentioning a game state error had occurred. Playing with SYNC as the ID.

**Comment by nealterrell** [comment]
Got it, will fix. Not an error with Zealous Judge code, it's with `can-rez?`.
