### ISSUE TITLE
Dedicated Neural Net triggers on the second and third sucessful HQ-run too

### ISSUE THREAD

**Issue by meatpopup** [mtgred/netrunner#1676]
Like the title suggests, Dedicated Neural Net should only trigger once per turn. 
You can workaround by both bit 0.
Thx for the great work. Have a nice one :)

**Comment by JoelCFC25** [comment]
My initial guess is that the problem lies in `resolve-ability-eid`, where we find that `check-psi` comes before `(if (can-trigger ...`

**Comment by nealterrell** [comment]
Good thought @JoelCFC25, but `check-psi` calls `can-trigger?` itself. I think it's because `check-psi` doesn't call `register-once` to note that the once-per-turn flag was hit. I'll try a fix.
