### ISSUE TITLE
Game crash when manually discarding card from grip

### ISSUE THREAD

**Issue by Angedelo** [mtgred/netrunner#1680]
3 separate occurrences of this issue, where runner (testing Null) manually trashed a card from grip when encountering an ice with a parasite on it. Game immediately crashed and was unrecoverable.

**Comment by JoelCFC25** [comment]
Is this still happening? I have a hunch it could have been fixed by #1709.

**Comment by JoelCFC25** [comment]
Closing this issue, since it sounds like it isn't happening anymore. Please create a new issue if it crops up again!
