### ISSUE TITLE
New Construction problem on installing an agenda.

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#1681]
New Construction panicked on installing an agenda on its fourth advancement. I don't know whether it's a bug with agendas or the fourth advancement or whatever as I don't normally run it (it was for a draft).

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.ClassCastException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by JoelCFC25** [comment]
Thanks for the report--this card is bugged, period. Doesn't have to be installing an agenda and doesn't have to be on the 4th advancement.
