### ISSUE TITLE
Freelance Coding Contract trashes are prevented by Sacrificial Construct

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#1682]
Sacrificial Construct should only prevent installed programs/hardware from being trashed anyway, so I'm not sure why this is triggering.

**Comment by JoelCFC25** [comment]
Thanks for the report. Runner trash prevention--at the level of the game engine--doesn't check that the thing being trashed was installed. FCC has to pass `:unpreventable true` as a parameter to the `trash` call.
