### ISSUE TITLE
Exchange of Information on Mandatory Ugrades does not automatically add a click every turn

### ISSUE THREAD

**Issue by promisedlandt** [mtgred/netrunner#1687]
If the corp scores Mandatory Upgrades, the click gets added automatically every turn.
Given a Mandatory Upgrades in the runner's score area, when the corp plays Exchange of Information on the Mandatory Upgrades, it gets added to their score area, but does not automatically add the click every turn.

Could be similar to #1555 / #1125, just with Exchange of Information instead of Turntable.

**Comment by JoelCFC25** [comment]
Thanks for the report--unfortunately this one is expected. Those are indeed the relevant issues, since EoI just reused a large chunk of Turntable's code.
