### ISSUE TITLE
BUG Kim trashes Agenda instead of Operation

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#169]
Kim was running an unprotected RnD with Medium; accessed various cards, including Corporate Shuffle and NAPD Contracts, but instead of trashing the operation, it trashed the agenda. The chat also said that Corporate Shuffle was trashed, even though it was NAPD.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
