### ISSUE TITLE
Replicating Perfection won't let you run subs

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#1693]
I ran each of the centrals and it still didn't give me the option to run remotes.

For reference, my first run was via Jak Sinclair, so I thought that might be relevant at first. But doing 'normal' runs didn't make any difference.

**Comment by JoelCFC25** [comment]
I can't reproduce this in dev yet--will try on live later tonight.

**Comment by lbrentcarpenter** [comment]
I was having the same issue. Jak was letting me run remotes (when clearly I shouldn't), and normal runs after a Jak run on a central wouldn't let me run remotes.

**Comment by JoelCFC25** [comment]
Never mind my first response, I'm seeing the issue now.
