### ISSUE TITLE
runner rezzed corp card during indexing run

### ISSUE THREAD

**Issue by MauiChris** [mtgred/netrunner#1694]
I had an interesting glitch today. The runner ran my R&D with Indexing. One of the five cards was Keegan Lane & the runner clicked on it to drag back to R&D. In the chat window i see "runnername rezzes Keegan Lane". he couldn't complete the indexing run & it broke the game. 

First time it's happened. There were other indexing runs during this game that were completed without issue. Could be a one off glitch or something more serious, either way, here's the bug report.

![runner rez corp card](https://cloud.githubusercontent.com/assets/17242505/16400522/0f3d73ee-3c91-11e6-9480-bb6552ad4298.jpg)

**Comment by Saintis** [comment]
Am able to reproduce this. Will have a look.

Thanks for the report!
