### ISSUE TITLE
Inside Job + DDoS

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#1698]
Situation:  2 ICE Server.  Outermost ICE is already rezzed.  Innermost ICE is unrezzed.

Runner activates DDoS and plays Inside Job on the server.

Inside Job applies to the first ICE which is fine, but was unable to rez the inner ICE due to DDoS.

DDoS should only work on the outermost ICE, which although it was bypassed, still at least exists.

I don't know if this changes anything, but it was discovered when I typed "rez-all" after I conceded.   I didn't have enough money to rez the inner ICE anyway, but it wasn't letting rez the ICE in question manually.

**Comment by nealterrell** [comment]
Right now (for simplicity) DDoS looks at the run's current position and compares it to the number of ice in the server. If the two are the same, then NO ice can be rezzed. I have a minor refactoring coming soon that should fix this issue either way.

**Comment by JoelCFC25** [comment]
Fixed at #1697.
