### ISSUE TITLE
Immolation Script

### ISSUE THREAD

**Issue by parmer** [mtgred/netrunner#1699]
I'm a Runner using Immolation Script:

When using Immolation Script when the run is successful, there seems to be this NPE that happens. As a runner, my only option is to just jack out. It's a bit of an edge case, but I can imagine there are some who want to actually count their run as successful even though they don't access Archives. Note that the Immolation Script effect still fires. 

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by parmer** [comment]
This is what Archives had protecting it: 

![image](https://cloud.githubusercontent.com/assets/2737888/16440967/44b057e0-3d7b-11e6-9b74-59b28b5fa784.png)

**Comment by parmer** [comment]
In archives was just the first 2 cards. (I was using Immolation Script to trash a rezzed copy of Ice Wall). The Rainbow was from an unrelated, later turn.

![image](https://cloud.githubusercontent.com/assets/2737888/16440988/60320ad6-3d7b-11e6-8401-69f3c3a82bd2.png)

**Comment by JoelCFC25** [comment]
Thanks for the report. This card was coded before all the fancy new "wait for completion" stuff we have now. I have redesigned it to trigger on `:successful-run` like it's supposed to and will be submitting it soon.
