### ISSUE TITLE
Ice Analyzer not accumulating credits

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#170]
Realize this isn't an often-used card, but someone played it against me this morning...

The only part that is working is the message when the Corp rezzes an ice--no credits get added to the card, and clicking on it doesn't do anything (since there's nothing to spend). I can't figure out what is wrong looking at the code...does it need  **:data counter** added at the top?

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

The problem was that the Corp triggers the event by rezzing the ICE and Ice Analyzer can't find itself on the Corp board. `add-prop` must specify `:runner` to make it search the runner's board
