### ISSUE TITLE
Interactions with Guru Davinder, Snare, Salsette...

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#1703]
Okay, I appreciate this is the edgiest of edge cases, but I'll try and capture what happened and see what you guys make of it.

I had Guru, Salsette and three RDIs installed. By the time I accessed R&D I had four credits left. First card was Snare. I paid the four credits to retain Guru and trashed normally (forgot to click Salsette). Second card was another Snare. I avoided the damage but Guru auto-trashed as I didn't have any credits. I then remembered Salsette was a thing so removed Snare from the game. At this point it ended my turn, missing out on the last two accesses.

The third card was the agenda I needed to win, so my opponent graciously conceded, but I doubt that's relevant.

I'll try and do a little testing to help pinpoint the issue (if possible) and update here.

**Comment by JoelCFC25** [comment]
This is a Guru Davinder problem. It is coded a bit too expansively--given the existence of Imp and Salsette Slums, and Ghost Runner, I suppose it should probably never trash itself automatically based on the amount in your credit pool.

**Comment by qmsm** [comment]
Just to be clear, Guru was correct to trash as I couldn't afford to save it. It was the premature turn ending that was the problem.

**Comment by JoelCFC25** [comment]
You're right, I retract my previous comment. This is a Salsette Slums issue.

**Comment by nealterrell** [comment]
Needs to call `close-access-prompt`. I'll push with some other fixes.
