### ISSUE TITLE
Timing Issue with Manhunt // Bankjob

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#1704]
Manhunt should happen at 4.4 (When Successful)
Bankjob should happen at 4.5 (Instead of Access)

In a Making News Ayrahaba Tech game I was playing, somebody wanted to do a Bankjob run at zero credits, and through the Jnet timing windows was able to pay for the Manhunt trace using the credits he got from the Bank Job.

**Comment by JoelCFC25** [comment]
I can get Bank Job's access replacement delayed until after Manhunt now, but I'm still trying to figure out how to give the Runner a choice of multiple Bank Jobs to use (theoretically there can be multiples with different amounts left on them).

**Comment by nealterrell** [comment]
This is a player education issue. Joel is working on automating the card, but even that presents issues, including extra UI actions when you don't want to use Bank Job. (Currently, simply don't click the card if you don't want to use it. But if it's automated, every run on a remote will show "Take Bank Job credits?", requiring a No click to proceed.)
