### ISSUE TITLE
Continuing HQ Run after Trashing Vikram 1.0 with Forked

### ISSUE THREAD

**Issue by alcohollywood** [mtgred/netrunner#1707]
Please describe the circumstances of your error here.
Corp trashed before clicking Continue. Whenever I clicked Continue, the red 'report to GitHub' error message appeared and I could not move forward. Solution was to jack out and manually do a normal run afterward, with no problems.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.IndexOutOfBoundsException
   :message nil
   :at [clojure.lang.PersistentVector arrayFor "PersistentVector.java" 158]}]
 :trace
 [[clojure.lang.PersistentVector arrayFor "PersistentVector.java" 158]
  [clojure.lang.PersistentVector nth "PersistentVector.java" 162]
  [clojure.lang.RT nth "RT.java" 853]
  [game.core$continue invokeStatic "core-actions.clj" 333]
  [game.core$continue invoke "core-actions.clj" 328]
  [game.main$handle_do invokeStatic "main.clj" 72]
  [game.main$handle_do invoke "main.clj" 69]
  [game.main$run$fn__22568 invoke "main.clj" 86]
  [game.main$run invokeStatic "main.clj" 80]
  [game.main$run invoke "main.clj" 76]
  [game.main$_main$fn__22586 invoke "main.clj" 128]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by nealterrell** [comment]
Do you remember anything else about the structure of the server? Central or remote? Any other ice installed? Position of the Vikram? Thanks.

**Comment by alcohollywood** [comment]
Funny enough, this happened again in a subsequent game. 

First game (the one I reported on): The Vikram was the only ice in front of HQ. I ran a Forked on it, used Mimic (with Ice Carver and Net-Ready Eyes) to break it, Corp trashed it. When I tried to click 'Continue,' the red error message popped up on the upper-right corner.

Second game, I Forked through a Cobra with Mimic that was in position 1 on R&D (outermost). Same thing happened. I was able to successfully Knifed other ice, so maybe the problem is specific to Forked?

**Comment by nealterrell** [comment]
OK, I definitely have a lead and a fix on this. Thank you for your reports. Until the fix goes live, you should be fine if the corp waits to trash the ice until after you have passed it (or, safest of all, after the run has ended). Just explain when starting the run.

**Comment by nealterrell** [comment]
A fix is being deployed tonight.
