### ISSUE TITLE
unknown bug at game end, FTE or TTW possibly involved?

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#1711]
I got the report-this-on-github error message when I won a game as kate vs palana. I had 2 foods and a Freedom Through Equality scored, ran HQ and used Turning Wheel to access 2 extra, stole a nisei (as the 1st card accessed) and won. I don't exactly remember whether the bug message popped up after I finished accessing the other 2 cards, or if it popped up immediately, but I think it was after all 3 accesses finished.

I also think I have seen this before, when FTE was involved but TTW wasn't, but my memory is kinda foggy there. Just saying FTE is more likely the culprit.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [game.core$resolve_prompt invokeStatic "core-actions.clj" 131]}]
 :trace
 [[game.core$resolve_prompt invokeStatic "core-actions.clj" 131]
  [game.core$resolve_prompt invoke "core-actions.clj" 105]
  [game.main$handle_do invokeStatic "main.clj" 72]
  [game.main$handle_do invoke "main.clj" 69]
  [game.main$run$fn__22568 invoke "main.clj" 86]
  [game.main$run invokeStatic "main.clj" 80]
  [game.main$run invoke "main.clj" 76]
  [game.main$_main$fn__22586 invoke "main.clj" 128]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment]
We've had a lot of changes to access routines lately. If this crops up again, please resubmit it.
