### ISSUE TITLE
The Board does not go into runner score area when trashing while accessing in HR

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#1716]
While using The Turning Wheel, trashing the board by the Runner when accessed via The Turning Wheel, goes to the Archives and not to the Runner's score area.

**Comment by JoelCFC25** [comment]
This also means Director Haas, Victoria Jenkins, and Chairman Hiro will have the same problem. It's a side effect of #1690 that I didn't think of--the fix will be to add logic that the card is installed _and_ rezzed in the case of a Corp card.

**Comment by JoelCFC25** [comment]
I have a fix for this, but it might be considered too crude. Make the previously changed line in `resolve-trash-end` this instead: 

`(when (or (= (:side card) "Runner") (:rezzed card) (:when-unrezzed trash-effect))`

...and put `:when-unrezzed true` in the `:trash-effect` of the 4 executives. This stops Red Herrings/Strongbox effects if they're trashed while unrezzed (the goal of the previous fix) but still lets the Runner get 2 points for the execs if they trash an installed unrezzed copy or one from R&D/HQ.

**Comment by Saintis** [comment]
Looking at Red Herrings etc. and the Executives I wonder if it would be better to instead rewrite how the steal cost / "still when this card is trashed" cards work. Would it be possible to write them so that when they are rezzed / when a run against them is initiated the effect stays until the run ends? This way `:trash-effect` does not need to be invoked perhaps.

**Comment by JoelCFC25** [comment]
We have the run flag system, which is how I refactored Old Hollywood Grid.

**Comment by McBEASTse** [comment]
I can confirm that using Medium in R&D and trashing Victoria Jenkins puts her in the Archives also.
I was running Whizzard and using his credits for trashing.
