### ISSUE TITLE
Punitive Counterstrike doesn't take Notoriety into account

### ISSUE THREAD

**Issue by mtgred** [mtgred/netrunner#1719]
Opponent score 3/5 Agenda and 2 Notoriety.

Punitive Counterstrike only deal 3 damages.

Possibly an issue with Chairman Hiro or other executives.

**Comment by nealterrell** [comment]
Are you sure Notoriety should be counted? It wasn't "stolen".

**Comment by queueseven** [comment]
Cards that get "added" to the score area are not stolen. So Punitive Counterstrike works correct here.

**Comment by mtgred** [comment]
My bad. Read the card incorrectly.
