### ISSUE TITLE
No discard on mobile device

### ISSUE THREAD

**Issue by philippelachance** [mtgred/netrunner#172]
Hi, I've tried playing today on a Ipad and there seems to be no way to discard cards, the drag and drop function not working. Now I understand that it might not be conceived for mobile but if there is a way that im not aware of, please let me know, I would really appreciate. Thanks!

**Comment by mtgred** [comment]
Hi, drag and drop is not supported on mobile browsers. The only solution as far as I know would be to create a mobile app unfortunately.

**Comment by DominicKexel** [comment]
The UI could be changed to listen for the touchstart/touchend etc. events.

Also, there's [Touch Punch](https://github.com/furf/jquery-ui-touch-punch/). Maybe that's an option.

**Comment by queueseven** [comment]
I'm currently working on touch support.

You can see my progess on [my touch branch](https://github.com/queueseven/netrunner/tree/touch)

Moving from HQ to RnD and Archives works, moving from Archives to HQ and RnD works also.

Moving ICE or cards in remote does currently not work. Also, it would be nice when the card you are moving follows your finger, but as of now I was unable to get it to work. I would be glad if someone with more CSS/JS knowlegde wants to take a look.

**Comment by JoelCFC25** [comment]
Fixed at #1217!
