### ISSUE TITLE
Sometime, the run ends before a card is trashed by the runner

### ISSUE THREAD

**Issue by mtgred** [mtgred/netrunner#1721]
It results in bad pubs being cleared before it can be used to pay for the trash cost.

**Comment by nealterrell** [comment]
I'm trying to look into this, but basic tests are passing. Remember any other details? I know you were playing Val, but where were you trashing from, what were you trashing, etc?

**Comment by artturipi** [comment]
I think it happens at least when running on a remote containing only a CVS and nothing else. I'm pretty sure it happens on centrals too if the last card accessed is CVS. Probably also other cards where the Corp can trigger something, like Snare! (+IG to make the BP matter)

**Comment by nealterrell** [comment]
You nailed it, @artturipi.
