### ISSUE TITLE
The All-Seeing I, Off-Campus Apartment + trash prevention interaction incorrect

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1724]
Not sure how you guys want to handle this, but The **All-Seeing I** prompts for the runner to prevent resource trashing when cards like **Fall Guy** are in play. Per the rules, TASI should trash all resources regardless of the amount of prevention. It's not technically "unpreventable" but for all intents and purposes it seems like it could be implemented this way. My major concern here is UI confusion, but I think the implementation is also a bit broken (saw a guy prevent **Off-Campus Apartment** from being trashed via Fall Guy and none of the hosted resources were trashed after TASI finished resolving).

**Comment by nealterrell** [comment]
Prevention happens normally with All-Seeing I. Here is ANCUR on the topic: https://twitter.com/mn200/status/659588748867338240 . If Fall Guy prevents Off-Campus Apartment's trashing, then that's fine, but everything on the apartment should be trashed. It's probably an error with ASI's coding with respect to hosted cards.

**Comment by FarCryFromHuman** [comment]
Ah, I thought I'd read the opposite ruling somewhere. There is still the outstanding defect with ASI and OCA, so at least there's an issue in place for it now.

**Comment by erbridge** [comment]
Does this still happen? I thought I saw a fix for it...?

**Comment by JoelCFC25** [comment]
Confirmed that this is still an issue.

**Comment by Saintis** [comment]
@nicohasa was this fixed in #3284?

**Comment by nicohasa** [comment]
Nope, just tested. All-Seeing I does not try to trash hosted resources (at all), apparently.

I'll make a fix.
