### ISSUE TITLE
Out of the Ashes losing heap ability when trashed from stack

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1729]
I just played a game where I had a copy of Out of the Ashes trashed from the top of my stack by Kala Ghoda Real TV. OotA didn't give me the normal prompt at the start of my turn. I drug it from my heap into my grip and trashed it manually and then it resumed giving me the prompt next turn.

**Comment by JoelCFC25** [comment]
Probably needs to employ `:mill-effect` like Subliminal Messaging does.

**Comment by FarCryFromHuman** [comment]
Closing this since it was repaired last restart.
