### ISSUE TITLE
UPDATE: Rezzing Marked Accounts before Corp turn begins causes NullPointer error

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#173]
Update: It seems that rezzing Marked Accounts before click "Start Turn" for the Corp causes there to be a NullPointer error and crashes the game.

I've been playing on a locally installed version of the jinteki.net server, and I encountered this error several times while playing (which causes the game to crash).

Corp goes to start their turn and this error happens:
Error in Thread  0 do start-turn nil #<NullPointerException java.lang.NullPointerException>
Error in Thread  0 do start-turn nil #<NullPointerException java.lang.NullPointerException>

Details about the table layout:
Corp hand: 2 tollbooth, priority req, sea source, and closed accounts
Corp table: 2 wall of static and a data raven on the table

![netrunner_error](https://cloud.githubusercontent.com/assets/659758/7418229/5b9752d2-ef3a-11e4-87a3-f448fdb99384.PNG)

Let me know if you need more details!

**Comment by Agnate** [comment]
Just wanted to update this issue with some reproducible errors. It seems rezzing Marked Accounts before the Corp turn begins seems to be causing the issue.

**Comment by mtgred** [comment]
Thanks for reporting the issue and how to reproduce it. It has been fixed and will be deployed with the next server update.
