### ISSUE TITLE
*** stack smashing detected *** while running server.coffee

### ISSUE THREAD

**Issue by glass4pk** [mtgred/netrunner#1731]
Getting *** stack smashing detected *** at running server.coffee on ubuntu, which runs nothing but jinteki , is code error or system problem?

![image](https://cloud.githubusercontent.com/assets/1888886/16613055/ca9b662a-439c-11e6-8578-20c86aa62cb2.png)

**Comment by Saintis** [comment]
Have never seen that before and have no idea what could be wrong. Know that setting everything up can be tempremental at points though.

Maybe @zaroth has some idea since he runs Arch Linux. I just use my Mac.

**Comment by queueseven** [comment]
I've also never seen this before.

**Comment by queueseven** [comment]
Maybe it's a Problem with the native code packages. Try deleting the node_modules folder and run npm install again.

**Comment by glass4pk** [comment]
git the source code and $ lein uberjar again , problem solved...
but found that the figwheel couldn't run well...
