### ISSUE TITLE
Damage problem

### ISSUE THREAD

**Issue by 0j3t3c4l0r** [mtgred/netrunner#1732]
I was playing a game with Cibernetics, humanity upgraded against Adam, twice in the game he run into a server with an Overwriter with 3 counters and a Project junebug with 2 counters havin just 2 cards in hand that would make him be flatlined and after I clicked to use the triggered ability when he accessed both cards the ability didn't triggered it could be because of one of the directives

**Comment by FarCryFromHuman** [comment]
Did you have enough credits to fire the effects?

**Comment by nealterrell** [comment]
This is an issue with advanceable assets not correctly delaying the access code until their access routine is complete.
