### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by SageFault** [mtgred/netrunner#1739]
You have a website, it allows logins, you're not using HTTPS.
Also, the EFF have released [Certbot](https://certbot.eff.org/), so you can now get TLS certificates for free with minimal effort.

**Comment by domtancredi** [comment]
+1 for using Let's Encrypt: https://letsencrypt.org

**Comment by erbridge** [comment]
One for dev?

**Comment by zaroth** [comment]
It's not an issue of jinteki code per se, it's more suited for reverse proxy IMHO. That said, since I created repo for that, added issue where it's relevant: https://github.com/zaroth/betajin-pupfiles/issues/7

**Comment by mtgred** [comment]
The server is finally using HTTPS.

There were a lot of troubles due to Cloudflare mixed with websocket. But everything is now solved.

**Comment by danhut** [comment]
Nice one!!!

Sent from my iPhone

On 12 Feb 2017, at 3:34 pm, Minh Tran <notifications@github.com<mailto:notifications@github.com>> wrote:


The server is finally using HTTPS.

There were a lot of troubles due to Cloudflare mixed with websocket. But everything is now solved.

-

**Comment by SageFault** [comment]
Yay!

**Comment by domtancredi** [comment]
Awesome
