### ISSUE TITLE
Prompt for choosing Patron server appears twice

### ISSUE THREAD

**Issue by josemgarcia** [mtgred/netrunner#1744]
I had Jak Sinclair and Patron installed, so when I start my turn the prompt to do actions before taking clicks appears. I click first on Patron, and then on Jak. The problem is that, after taking my clicks, the prompt for Patron is shown again. Apart from that, both cards work normally.

**Comment by nealterrell** [comment]
Thanks for the report. Patron's ability needs a `:once :per-turn` so that it won't trigger at turn-begins if it was used during Step 1.2.

**Comment by drobati** [comment]
https://github.com/drobati/netrunner/blob/master/src/clj/game/cards-resources.clj#L689

Looks like it's already there. Maybe in the wrong part of the function?

**Comment by nealterrell** [comment]
That pertains to the draw part of the ability (once per turn, draw instead of accessing). We need the once-per-turn to apply to the server selection too.

**Comment by nealterrell** [comment]
This is trickier than I thought. The server selection needs to be once-per-turn per card, AND the draw effect needs to be once-per-turn per card. We don't have an easy way right now to have two different once-per-turn abilities on non-unique cards.

**Comment by Saintis** [comment]
Can you not just make a `req` that a target server has not already been selected? Or would that be much to easy?
