### ISSUE TITLE
Turning Wheel message

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#1746]
When corp triggers an ETR sub the message for The Turning Wheel is displayed incorrectly.

<img width="235" alt="screen shot 2016-07-08 at 17 33 31" src="https://cloud.githubusercontent.com/assets/13198563/16692710/48a09dc4-4532-11e6-9fdc-9fe094febc9f.png">
(No user name when counter added - triggered by Snowflake ETR)
<img width="227" alt="screen shot 2016-07-08 at 17 34 09" src="https://cloud.githubusercontent.com/assets/13198563/16692709/48997152-4532-11e6-8d5a-359d803e8d4d.png">
(Wrong user name when counter added - triggered by Clairvoyant Mirror ETR)

**Comment by FarCryFromHuman** [comment]
The wording should probably be "places a power counter on" instead of "adds a power counter to."
