### ISSUE TITLE
Full Immersion Recstudio

### ISSUE THREAD

**Issue by mountainmello** [mtgred/netrunner#1752]
the card allows you to host up to 2 agendas/ assets.  trash cost increases by 3 for each hosted card.  This ability is not active in Jinteki

thanks

**Comment by JoelCFC25** [comment]
This card isn't implemented yet. You can always check the status of a card by [checking our tracking sheet](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/pubhtml) (linked on the site's About tab).
