### ISSUE TITLE
The spectator dropdown in not showing who currently spectating a game

### ISSUE THREAD

**Issue by kevintame** [mtgred/netrunner#1753]
I've tried this in a few browsers and the issue persists.

<img width="685" alt="spectators not working" src="https://cloud.githubusercontent.com/assets/1868988/16711754/6789054c-463a-11e6-8c27-66c5c96972f2.png">

**Comment by JoelCFC25** [comment]
The fix is submitted at #1742 but is neither merged nor deployed.
