### ISSUE TITLE
font size fix?

### ISSUE THREAD

**Issue by raistdart** [mtgred/netrunner#1755]
Hi, guys. I appreciate all the improvements you've made recently, including the re-sizable chat window. However, as it currently stands, re-sizing the chat window doesn't really help because zooming out to see the gobs of servers corps are making these days also decreases the font size significantly. Is there any chance you could make it so that the font size is fixed, instead of changing with the zoom? Or maybe make it so that it is possible to select whatever font size you want in game? Thanks!

**Comment by erbridge** [comment]
The problem zooming was used to solve is now fixed via scrolling, so I think this can be closed.
