### ISSUE TITLE
Allow spectator to view hands

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#1756]
This is a thread to track the enhancement as a game option to allow spectators to view the hands of players, without allowing the opponent to view the hand.

**Comment by domtancredi** [comment]
Fix is most likely in gameboardcljs, **hand-view** method, possibly the ":openhand" attribute

**Comment by nealterrell** [comment]
`:openhand` will reveal the hand to the other player as well. We'll need a distinct state variable for this feature.

**Comment by zaroth** [comment]
Related to #769.

**Comment by JoelCFC25** [comment]
Implemented at #1762.
