### ISSUE TITLE
Q-coherence chip self trash on discard

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#176]
I was discarding a program at the end of the turn because I had more  than my hand limit and my q-coherence chip go to my trash pile

**Comment by mtgred** [comment]
Apparently it's supposed to be that way.
https://boardgamegeek.com/thread/1164776/q-coherence-chip-trash-effect-ruling-ffg

**Comment by mtgred** [comment]
Apparently there is an erratta on the card in the rule faq 2.0. The trigger only applies for installed programs.

The card will be corrected tomorrow.

**Comment by mtgred** [comment]
The card has been fixed.
