### ISSUE TITLE
Punitive Counterstrike Does 2 Damage when Runner Accesses Global Food

### ISSUE THREAD

**Issue by beardsley-james** [mtgred/netrunner#1761]
Per the FAQ: 

79 Punitive Counterstrike
•	 Should read: “If successful, do meat damage to the Runner equal
to the number of printed agenda points on agendas he or she stole
during his or her last turn.

I was playing a game and a runner stole a global food initiative and then punitive counter strike did 2 damage but it should have done 3.

**Comment by JoelCFC25** [comment]
Thanks, this one is on the to-do list. Remember, the new FAQ came out less than 12 hours ago, and this one is a reversal of a previous ruling. _Technically_ the site is still right, since the new FAQ doesn't become effective until July 18th. ;)

**Comment by beardsley-james** [comment]
I didn't know it was new because it wasn't blue! Wasn't going to win that game anyway.

**Comment by JoelCFC25** [comment]
Fixed at #1846.
