### ISSUE TITLE
Lost click on Jak Sinclair run not lost.

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#1764]
Made a Jak Sinclair run on R&D, opponent rezzed an Enigma and fired subroutines.

When I took my clicks after run ended I gained 4 clicks, whereas I expected to only gain 3 clicks.

**Comment by FarCryFromHuman** [comment]
As of the new FAQ, this interaction is actually correct.

**Comment by Saintis** [comment]
You sure? Runner gets clicks in 1.1 and "When your turn begins" happens in 1.3 according to the new runner turn structure.

**Comment by FarCryFromHuman** [comment]
Had to scrutinize the new FAQ here, but it looks like the newly added "gain clicks" window for the runner (1.1) does happen before the "trigger start of turn effects" window (1.3). It's the opposite for the corp: first start of turn effects (1.2), then mandatory draw (1.3), then gain clicks (2.1). Weird, and might be a wrench in your game turn state machine later?

**Comment by JoelCFC25** [comment]
In the current FAQ, gaining clicks is lumped into 1.2 along with "when your turn begins" effects. Moving the two lines of code where gaining clicks happens out of `end-phase-12` into `start-turn` before the block that checks for `:runner-phase-12` will allow Jak + Enigma to work. It does make the MaxX + Wyldside test fail, but that is actually based on the outdated turn structure anyway. The only thing left would be to change the UI button shown at the conclusion of 1.2 from "Take Clicks" to "Take Actions".
