### ISSUE TITLE
Pawn is broken

### ISSUE THREAD

**Issue by cspieker** [mtgred/netrunner#1767]
I install Pawn on an ICE and I can't see it.  The opponent said they could see it, but i couldn't, so couldn't click on it to perform actions.    
Tried with both Chrome and Firefox.  Problem did not happen at 3:30pm Pacific DT.  But does now.

Also, maybe related, when opponent played Oversight AI, the OAI on the card appeard facedown to me (but not to my opponent)

**Comment by JoelCFC25** [comment]
Thanks--all the recent issues are fallout of new features in last night's update. We are aware of everything and hope to make progress today.
