### ISSUE TITLE
Rebirth not working (tested on Andromeda, Val)

### ISSUE THREAD

**Issue by Stephen986** [mtgred/netrunner#1769]
Rebirth is not doing anything after selecting the runner to rebirth to.

Tested rebirthing from: Andromeda, Val
Tested rebirthing into: Leela, Gabe, Noise

Using Chrome / Windows 10.

**Comment by JoelCFC25** [comment]
Thanks for the report. I think there is an extra step required now during deployment to support Rebirth that got missed. This has happened a couple times before. We'll check into it today.

**Comment by nealterrell** [comment]
Thanks, fix incoming.
