### ISSUE TITLE
Power shutdown with advancement tokens

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#177]
Opponent used power shutdown on ice wall with advancement tokens. Advancement tokens disappeared.

**Comment by JoelCFC25** [comment]
I think you must mean Emergency Shutdown (and it applies to the use of Crescentus too)--but yeah this is a bug. Derezzing ice that hosts advancements should not result in losing them.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
