### ISSUE TITLE
Runner was unable to return cards to the top on the corps stack with Indexing

### ISSUE THREAD

**Issue by cring002** [mtgred/netrunner#1770]
The runner used Indexing. When looking at the top five cards the runner was unable to put them back on the Corps RnD. The cards were: Architect, Nisei Mark 2, Hedge Fund, Lotus Field and Chrysalis. Sadly it does not look like the stack trace gives you anything to go by. The bug has not been tested again so I do not know if it is reproducible.

Steps to reproduce:
1. Start a game with Indexing in your deck
2. Make an Indexing run
3. Observe that you cannot drag the cards back to RnD

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by JoelCFC25** [comment]
Thanks--we have this one in at #1768. You can keep track of updates on the situation in that issue. This is related to the new features in last night's update. For the time being there is a warning to players in the site News header about Indexing and other broken cards.

**Comment by cring002** [comment]
That's cool, I did not search the DB to be fair because, well, I am lazy.
