### ISSUE TITLE
Mumbad Virtual Tour + NBN: Controlling the Message

### ISSUE THREAD

**Issue by benhosp** [mtgred/netrunner#1774]
If the runner accesses an installed, unrezzed Mumbad Virtual Tour and is able to trash it, they don't see what the card they accessed was or that they were forced to trash it before NBN: Controlling the Message triggers and initiates a trace.

**Comment by JoelCFC25** [comment]
By "able to trash it", do you mean the automatic forced trash occurred, or you saw the toast alerting you that you have to use eligible recurring credits to trash, if able? 

I may be misunderstanding the scenario but this is what I see when I try this (log message at lower right shows the forced trash of the MVT): 

![screen shot 2016-07-15 at 2 22 14 pm](https://cloud.githubusercontent.com/assets/10407969/16886069/9f7d48da-4a97-11e6-851e-6d504639a4be.png)

**Comment by benhosp** [comment]
It's possible that what I mean is that they miss the log message indicating that they were forced to trash it. I've had at least 2 opponents now get very confused about why a trace is happening when they didn't trash anything.

Possibly if there was just something that said "you are forced to pay $5 to trash this" and they had to click "ok", and THEN the trash happens and triggers Controlling the Message, it would be better.

**Comment by Saintis** [comment]
In general I think a lot of the automatic interactions could have more explicit notices (like the steal prompts for agendas) to emphasise something is happening.
