### ISSUE TITLE
[COSMETIC] (0) displayed in upper left corner of Archives when empty; issue with HQ card count

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1778]
When a new game starts the corp's archives shows the new face-up/face-down card counts under the Archives tag, but it also shows the old (0) amount behind the tag. The count goes away as soon as there are any cards in archives. I've yet to see if the count comes back if Archives is emptied out again by recursion effects.

In the same game the HQ tag was missing and (0) displayed in the upper left of the identity card even though the corp player had cards in hand.

**Comment by Saintis** [comment]
Done some investigating. To do with the `content` of a server being an empty array rather than nil after the private game info rework. Easy fix to change the logic on displaying a header on server from `when content` to `when (not-empty content)`
