### ISSUE TITLE
Changeling advancing

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#178]
There is no option to advance changeling when installed.

**Comment by JoelCFC25** [comment]
This one [has already been patched](https://github.com/mtgred/netrunner/commit/d25c7895f86f842789644c1a123f413f46fcadc6), probably just waiting on another restart for it to be effective.

**Comment by mtgred** [comment]
Changeling was still not working actually. It has been properly fixed now and will be deployed with the next server update.

**Comment by CptHilts** [comment]
Thanks mtgred! and Joel!
