### ISSUE TITLE
Trying to undo a premature play of hostage

### ISSUE THREAD

**Issue by theodox** [mtgred/netrunner#1781]
Please describe the circumstances of your error here.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.ClassCastException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by nealterrell** [comment]
_Please describe the circumstances of your error here._ What does "undo" mean in this context? What UI action did you take when the game showed the error? Thanks.

**Comment by theodox** [comment]
I was trying to return the catd to my hand, but that generated the error

**Comment by nealterrell** [comment]
I'm going to assume this issue is the same as #1790 and has been fixed.
