### ISSUE TITLE
Typing "null" into chat crashes the game

### ISSUE THREAD

**Issue by junkmail22** [mtgred/netrunner#1782]
I'm not even sure if this is a real bug or a weird coincidence, but over multiple trials typing the word "null" into chat would shortly afterwards crash the game for everyone involved, including spectators.

**Comment by nealterrell** [comment]
Huh, that's a new one. Confirmed, but not sure where it's crashing. The UI locks up, but no JavaScript error in the console. Not a server-side error, I think...

**Comment by junkmail22** [comment]
Can this take "weirdest bug" award for this year?

Playing Null has singlehandedly ruined a morning of Netrunner.

**Comment by nealterrell** [comment]
If you put literally anything else in the message (even "Null.") then the game doesn't seem to lock up.

**Comment by benhosp** [comment]
This is why languages that aren't strongly-typed are bad.

I knew this was going to happen at some point somewhere. BBC had an article a while back about people with names like "Jennifer Null" who crash databases.

**Comment by junkmail22** [comment]
Is it a problem with the card lookup? The thing that gives the images for cards when you mouse over their names?

**Comment by nealterrell** [comment]
Doubtful. The card name is actually "Null: Whistleblower", so "Null" itself
wouldn't trigger the card image, the same way "Noise" doesn't.

**Comment by junkmail22** [comment]
I mean, perhaps it's looking for a card called "null" as in a null reference to a card.

**Comment by nealterrell** [comment]
I don't think that's the issue, but I know you're trying to be helpful and I definitely appreciate it :). I'll try looking into this soon, as it would allow spectators to ruin games and that's no good.

**Comment by junkmail22** [comment]
Sorry if I've been smug reporting, I just find this bug hilarious and can't stop thinking about it :P

**Comment by nealterrell** [comment]
I've confirmed there's not an error in the game engine, which updates the game state with the "null" message just fine, and replies with a game diff to the UI server correctly. That reply is passed correctly to the client socket, which receives it and renders it correctly. The next UI action you take is correctly passed as a command to the server, which receives it and sends back the correct state diff. The UI receives that diff, but doesn't render it -- so here's the error. It does handle further commands just fine as well -- if I monitor the server traffic, additional commands from the game are sent correctly to the server and replies are received correctly. They just aren't rendered. There are no JavaScript errors reported, though, which is going to make this tedious to fix.
