### ISSUE TITLE
15 Minutes + Exchange of Information

### ISSUE THREAD

**Issue by benhosp** [mtgred/netrunner#1783]
After I used Exchange of Information to swap a scored 15 Minutes for an agenda in the Runner's score area, I wasn't able to click and use the 15 Minutes ability.

**Comment by Saintis** [comment]
Only the agenda going to the corp area will have its abilities enabled currently. The way agenda swap works will have to be reworked a bit to make 15 Minutes to work properly.

**Comment by JoelCFC25** [comment]
Related issues: #1687, #1555, #1125.
