### ISSUE TITLE
Canceled a self-modifying code

### ISSUE THREAD

**Issue by Montoli** [mtgred/netrunner#1784]
Please describe the circumstances of your error here.

Clicked "self modifying code" to trigger it.  Decided, upon reflection that I didn't really want to use it now.  Hit cancel.  Got this error.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by nealterrell** [comment]
@mtgred are you still starting the game server with the special JVM option?

**Comment by nealterrell** [comment]
Looks like the code to look for "Cancel" as a prompt option is broken, so SMC gets invoked with "Cancel" as the targeted card, which... yeah.

**Comment by nealterrell** [comment]
I guess that would happen when I accidentally turn "Cancel" into "Can cel". :rage:
