### ISSUE TITLE
Null strength penalty added to ice incorrectly when previous ice was destroyed

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1788]
This seems to occur during a run when a previously Parasited ice is destroyed via being at 2 or less strength when Null's ability is triggered. The next ice on the server is also at -2 (in this case it was a NEXT Silver, which had its strength display as -1).

**Comment by nealterrell** [comment]
I imagine Datasucker will have the same problem, then.

**Comment by nealterrell** [comment]
Did you Continue the run and then the next ice was at -2, or was the -2 applied to the "previous" ice that just fell into the destroyed ice's place?

**Comment by FarCryFromHuman** [comment]
Continued the run and the next ice was -2. Server was NEXT Silver (position
0), NEXT Gold (position 1). Parasite was played on the Gold. Two turns went
by, the runner ran, activated Null which immediately trashed the Gold, then
continued, Silver was at -2. Not sure if that happened on trash or on run
continue.

**Comment by nealterrell** [comment]
OK, so Datasucker doesn't have this issue because an ice that gets trashed mid-run calls `:pass-ice`, and Datasucker resets when an ice is passed, but Null persists for the entire run.
