### ISSUE TITLE
Mutate does not trigger Foundry Ice Pull

### ISSUE THREAD

**Issue by enochj** [mtgred/netrunner#1791]
The Mutate card allows a coporation to rez a piece of ice on their own turn. With the Foundry identity, this rez should allow the corporation to add a copy of the ice to HQ. This is not implemented.

**Comment by JoelCFC25** [comment]
Mutate needs `(trigger-event state side :rez newice)` inserted somewhere, probably right after the `:corp-install` event is manually triggered.
