### ISSUE TITLE
Alternative Art is displaying when it shouldn't

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#1792]
The alternative art covers are displaying for cards when they shouldn't.

### Research:

Function **image-url** in _cardbrowser.cljs_ retrieves the card url via :code. 
Function **get-non-alt-art** should be defining a function of retrieving the "Alternatives" for grouping and organizing by first card

**Code structure for Corroder:**
(non-alt): http://www.jinteki.net/img/cards/01007.png
(alt): http://www.jinteki.net/img/cards/00529.png

**HTML structure:**
`<img src="/img/cards/01011.png" class="card bg" data-reactid=".7.0.1.2.0.0.3.0.0.0.1">`

**Comment by nealterrell** [comment]
FWIW this _doesn't_ happen on my dev environment, where no users are marked as donors.

**Comment by domtancredi** [comment]
Fixed in Pull Request #1795
