### ISSUE TITLE
Null Point exception (related to runs)

### ISSUE THREAD

**Issue by jbrz** [mtgred/netrunner#1793]
awwww nullpoint exception, cmon fam, that's sad :(

Probably don't need circumstances to find it, but:
Turn 1 (as runner, Andy) run into a snare (pro), take 3 net, tagged.
Run other remote server (b/c YOLO), run into agenda (dedicated neural net), press steal.  It's stolen.  But error message, and the steal agenda prompt remains open.  Close the prompt, and the successful run prompt is there.  dafuq.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by jbrz** [comment]
Just played another game - made a run, jacked out with Snitch, same error, same run prompt remained open.

**Comment by JoelCFC25** [comment]
There is a fix in place to prevent a lot of these spurious NPEs from appearing, but it sounds like it has to be passed as a parameter when launching the game server and it didn't happen last time. After the next restart there should be a lot less of this.

**Comment by JoelCFC25** [comment]
Is this still happening?

**Comment by jbrz** [comment]
I don't believe so - I think I recall talking with neal about it at some point in general chat, but it was so long ago I don't remember the takeaways from that.  I haven't seen it in relation to the same in-game events, but admittedly haven't been trying to reproduce it.  I can try to do exactly that this evening after work.

**Comment by JoelCFC25** [comment]
We'll close this for now. If you experience a bunch of these again, just create a new issue at that time--thanks!
