### ISSUE TITLE
NBN: Controlling the Message requires /close-prompt command

### ISSUE THREAD

**Issue by benhosp** [mtgred/netrunner#1796]
Intermittently (meaning: sorry, I can't give more details about how to reproduce), I've seen the runner need to use /close-prompt to get out of a run after Controlling the Message's trace fires.

**Comment by nealterrell** [comment]
Any chance you remember what was being trashed?

**Comment by efaydian** [comment]
Was playing as CTM yesterday with a friend (as Valencia) in a few games and we had this come up a few times.

It only comes up for us when the runner matches the trace strength from the ID.  The trace fails but the game state doesn't move on from there until the runner issues a close-prompt command.  If the trace fires successfully it closes properly.

**Comment by JoelCFC25** [comment]
Thanks, that is very helpful additional information.

**Comment by JoelCFC25** [comment]
I have now replicated the issue. Just for future issue reports, it is also very helpful to know what the prompt says! :)

**Comment by benhosp** [comment]
Sorry for the lack of specificity, but I've only ever seen it happen as the corp player.
