### ISSUE TITLE
Corp cards hosted on other cards appearing face down

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1799]
So far I've seen this happen with both Casting Call and Oversight AI. I was spectating both times so this might be a spectator-only issue.

**Comment by NorwegianLegion** [comment]
You can add Bioroid Efficiency Research as well. Card was face down when opponent played it.

**Comment by Saintis** [comment]
Played with OAI yesterday and I think my opponent could see it. I would assume this is a spectator issue caused by the private game info rework.

**Comment by FarCryFromHuman** [comment]
@NorwegianLegion: Were you spectating or playing as runner? Your comment implies you were playing but I wanted to be clear for @Saintis.

**Comment by nealterrell** [comment]
I may have fixed this when implemented Full Immersion RecStudio. Is the only reproducible case OAI/Casting Call for spectators?

**Comment by NorwegianLegion** [comment]
@FarCryFromHuman  I was playing as runner. My opponent could see the card was face up, but I couldn't.
