### ISSUE TITLE
Hayley install bug

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#180]
In the hayley install flow, if you install from grip by clicking a card instead of using the dialog it crashes the game withthese errors:

![screenshot 2015-05-02 at 10 11 32 pm](https://cloud.githubusercontent.com/assets/1702745/7443452/bdedd66a-f118-11e4-8a87-2d8f213d3fef.png)

**Comment by JoelCFC25** [comment]
Adding this label not to shame anyone, but just that this and #167 remind me of the Smith and Dale "Dr. Kronkheit" sketch of the 1920s: 

SMITH: Doctor, it hurts when I do *this*.
DALE: Don't *do* that.

**Comment by queueseven** [comment]
TBH, that really sucks and is a serious UI issue and should be fixed some day. Related: #587 and #290

**Comment by aiannacc** [comment]
I'm guessing this is moot by now.

**Comment by JoelCFC25** [comment]
Hayley uses card targeting now, so this one can't happen anymore.
