### ISSUE TITLE
run prompt

### ISSUE THREAD

**Issue by izram123** [mtgred/netrunner#1801]
Please describe the circumstances of your error here.

Stack Trace:
```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by Saintis** [comment]
Thank you for the report, however to fix this we need more details about what preceded the error. 

Was this cause by the prompt to make a run or a prompt during a run? 

What cards did you and your opponent have installed?

Which side were you on? Anything else that could be relevant.

**Comment by izram123** [comment]
this was at the begining of the game nothing was on board and we just
started the game
