### ISSUE TITLE
Scrubbed not lowering encountered ice by -2

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#1802]
Card  automation status shows this as being implemented. ? Thanks!

**Comment by JoelCFC25** [comment]
It definitely used to work. Investigating...

**Comment by JoelCFC25** [comment]
I'll have a fix for this today. Pro tip for any budding contributors--don't test a fix for something like this against...say....LOTUS FIELD. Like I just did for 10 minutes.
