### ISSUE TITLE
Enhanced Login Protocol does not fire

### ISSUE THREAD

**Issue by beardsley-james** [mtgred/netrunner#1806]
It is supposed to cost an extra click for the runner's first run every turn but it has to be done manually.

**Comment by JoelCFC25** [comment]
This card has never been implemented. Here's the [card implementation status sheet](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/pubhtml) (as linked on the site's About tab).

**Comment by beardsley-james** [comment]
Well that explains it.

**Comment by JoelCFC25** [comment]
It's waiting for a comprehensive "additional run costs" framework that can handle ELP, Ruhr Valley, and whatever else might come down the pike in the future that makes the Runner spend something in addition to the basic 1 click.

**Comment by JoelCFC25** [comment]
Finally implemented!

**Comment by beardsley-james** [comment]
noticed that in a match, good work!
