### ISSUE TITLE
Hades Shard (New BUG)

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#181]
Previously Hades would steal agendas but wouldn't flip cards in Archives after "accessing all cards". That bug was fixed, but now —although cards get flipped— agendas don't get stollen. So the runner needs to do a free manual run in order to steal the agendas. 

I don't know if this is intentional, but yeah, I post it in case this is a bug.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
