### ISSUE TITLE
React Button

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#1812]
Hey, is there any way to implement a react button? I can't tell you how many times I've wanted to clone chip/clot, use political operative, ect. The corp either doesn't see chat to notice that I've typed WAIT or is clicking so fast that there's no time. Thanks!

**Comment by JoelCFC25** [comment]
Thanks for the suggestion. We have this in already at #1348. Add your comments and monitor progress in that issue.
