### ISSUE TITLE
Deckbuilder integration: Uploading decks

### ISSUE THREAD

**Issue by gereons** [mtgred/netrunner#1813]
I'd like to add "Upload to Jinteki.net" to Net Deck, and I've figured out how to use POSTs to `/login` and `/data/decks` to upload a deck. Using cookies as auth tokens for a non-browser client seems weird, though, so I'm wondering whether I'm on the right track here, or if there's some other API endpoints I should use.

**Comment by nealterrell** [comment]
There is no API for user authentication and we don't have a plan for one.

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed a long time ago by allowing to import NRDB decks.
