### ISSUE TITLE
Card search box on Cards page/tab appears behind the cards

### ISSUE THREAD

**Issue by Kraken-Attacken** [mtgred/netrunner#1815]
As the title suggests, the search function appears behind the cards on the card page. I made a temporary fix for myself by accessing **inspect element** on the page, and added a z-index element style to it so it can appear in front, but that is tedious and the box still partially blocks at least one card, so I was wondering if there was some way to fix the issue. This issue was not present until between a few days and a week ago.

Thanks in advance

**Comment by JoelCFC25** [comment]
Any chance you can supply a screenshot and indicate what browser you're using? It seems normal for me in both Chrome and Safari in OS X.

**Comment by Kraken-Attacken** [comment]
![before](https://cloud.githubusercontent.com/assets/20628471/17087454/a04fb3f4-51d8-11e6-8f5f-694219140dd4.png)

I'm using Chrome. In this screenshot, you can see that the search box is not visible.

![during](https://cloud.githubusercontent.com/assets/20628471/17087465/0ed53f60-51d9-11e6-8b21-2c4818cbfee6.png)

In this screen shot, you can see that I've opened the inspect panel on the page and have highlighted the z-index style property that I added, with the value set to 0.

![after](https://cloud.githubusercontent.com/assets/20628471/17087511/e8f4cbe8-51d9-11e6-9205-1ca9993f044c.png)

And here, the value is set to 1, and the search box is brought to the front. It was behind the card image before.

**Comment by elmarco** [comment]
I get the same issue with chromium on f24, I applied the same fix, it's easy to provide a patch :)
