### ISSUE TITLE
Off-Campus Apartment shows cards face down after hosting Street Peddler

### ISSUE THREAD

**Issue by NickCornhill** [mtgred/netrunner#1816]
I was spectating a game and a player played Off-Campus Apartment and the turn later hosted Street Peddler on it. After that, all cards hosted on Off-Campus Apartment were shown face down, and hovering over the card would not show what card was hosted. What card was hosted did appear in the game log.
![offcampus](https://cloud.githubusercontent.com/assets/3474447/17087939/909f45f4-51d9-11e6-8580-cf7f77c545d9.PNG)

**Comment by JoelCFC25** [comment]
Thanks for the report. We have this one in at #1811--the fix is coming soon!
