### ISSUE TITLE
 Temüjin Contract locked to a server even after changing zone

### ISSUE THREAD

**Issue by unitled** [mtgred/netrunner#1819]
I realise the card has only just been automated, but wanted to point this out!

I was playing a game and hastily clicked the wrong server for my Temujin on install; I clicked RnD when I was intending to put it on Archives. Moving it back to my hand didn't allow me to replay it, and this didn't work via my stack or heap either. The other copy of Temujin in my heap had the same issue; it was locked to archives, but I couldn't play it.

Thank you!

**Comment by JoelCFC25** [comment]
Note for anyone else that might take this one before I get to it: `dissoc-card` can be modified to drop `:server-target` from deactivated cards instead of `:named-target`, then Diwan (the last remaining card using `:named-target`) can switch to using `:server-target` instead.
