### ISSUE TITLE
Connection lost when selecting a deck

### ISSUE THREAD

**Issue by Salem2612** [mtgred/netrunner#1825]
I am playing on Jinteki.net with Chrome on Win7 since many years. Since few days, in the new game panel when I click on "Select deck" then select a deck the following things happen:

- The red message appears: "Connection to the server lost. Attempting to reconnect."
- The button "New game" becomes unusable (transparent).
- The buttons "Start" and "Swap side" disappear.
- The button "Leave" stays usable.
- I am kicked from the game.
- I must click on the button "Leave" or CTRL+F5 to reload the play tab and join or create another game.
- The Chrome's console says:
 - "Failed to load resource: net::ERR_CONNECTION_ABORTED"
 - "WebSocket connection to 'ws://ws.jinteki.net/socket.io/?..... failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET"

This appears with few Corp decks (SYNC, NEH, Harishandra, Blue Sun). Others (HB EtF, Harmony Medtech, RP, Foundry) work fine. One Blue Sun Bootcamp Glacier works.

Any idea if it's from my side or yours ?

**Comment by nealterrell** [comment]
This happens when the game server is down You can recognize that this has happened because the site's game count will be very low compared to usual.

**Comment by Salem2612** [comment]
The game server is now alive. When I select several of my decks, the message "Connection to the server lost. Attempting to reconnect." appears and the deck is not selected. I've tried with several decks and several more simple card combinations. The best simple combinations I've found is the following:

This deck works:
> 1 Housekeeping
> 1 Punitive Counterstrike

This crashes:
> 1 Punitive Counterstrike
> 1 Housekeeping

**Comment by Salem2612** [comment]
The ID doesn't matter.

**Comment by Salem2612** [comment]
If a deck crashes when selected, it can't even be deleted is the deckbuilder list. I click on **Delete**, **Confirm Delete**, F5, the deck is still here. A deck that doesn't crash is normally deleted.
