### ISSUE TITLE
Comet and run events

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#183]
Comet's built-in implementation doesn't wait for run events to finish, forcing you to play the second event before you can react to run stages.  Inconvenient for Mr. Ken Tenma :)

Edit: Comet's memory is also not recognized.

**Comment by JoelCFC25** [comment]
I don't know how to fix the "wait for run resolution" bit, but I did submit a [patch for the missing MU](https://github.com/mtgred/netrunner/pull/185).

**Comment by eah13** [comment]
@JoelCFC25 thanks!

**Comment by JoelCFC25** [comment]
I'm closing this because the MU fix is done and the newer issue has a nice comprehensive discussion of all the factors in play with regard to run event resolution.
