### ISSUE TITLE
Bhagat trigger

### ISSUE THREAD

**Issue by pandamannoah** [mtgred/netrunner#1838]
Bhagat will trigger on a successful HQ run if installed after the runner has already successfully run HQ that turn.

Example:
Click 1 run HQ, successful run (no Bhagat)
Click 2 install Bhagat
Click 3 run HQ, Successful run, Bhagat triggers 

Bhagat should not trigger in this condition because Bhagat triggers on the **first** time a run is successful against HQ each turn.

**Comment by Saintis** [comment]
Fixing this should also solve any problems with rebirthing into Gabe, Silhouette or Laramy.

Those three, plus SecTesting and Patron (and Bhagat) are the only ones that trigger on first successful run on something.

Should be useful to add some kind of `first-run-on-server?` function.

**Comment by kevkcc** [comment]
Sundew is affected too i think
