### ISSUE TITLE
The Future Perfect triggers psi game on Full Immersion RecStudio

### ISSUE THREAD

**Issue by Kaermo** [mtgred/netrunner#1839]
Just played a game in which The Future Perfect was installed and hosted on Full Immersion RecStudio.

When accessing The Future Perfect triggered a psi game even though it was installed and the psi game should no longer be triggered.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is the result of a now-outdated macro `installed`, which only checks the first keyword of a card's `:zone` to see if it's either `:rig` (Runner card) or `:servers` (Corp card). This is not sufficient to identify hosted cards in either case.

**Comment by nealterrell** [comment]
`installed` can use `get-nested-host` to pull the card's "root" nested host if the card is hosted; the function will return the card itself if it is not hosted. THAT is the card whose zone needs to be tested.
