### ISSUE TITLE
Film Critic & Scrubbed

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#1842]
Greetings! Agendas hosted on Film Critic are still face down. Not a huge deal, but just fyi. Secondly, was Scrubbed fixed? I still can't get the -2 strength to trigger on the first piece of ice encountered. Thanks!

**Comment by JoelCFC25** [comment]
Confirmed the Film Critic issue. Scrubbed is working for me--note that the Corp must hit "No more action" before the strength reduction will be shown, since that's what currently triggers the `:encounter-ice` event.

**Comment by JoelCFC25** [comment]
Film Critic is still hosting agendas facedown. Anyone got a clue on this one?
