### ISSUE TITLE
Employee Strike does not work against Blue Sun

### ISSUE THREAD

**Issue by mattchainsaw** [mtgred/netrunner#1843]
Blue sun still retains the ability to add cards to HQ and gain credits when Employee Strike is in play. This has happened on multiple occasions.

**Comment by nealterrell** [comment]
Employee Strike and Cerebral Static do not remove activated abilities from cards, they simply disable the automated events that they trigger. It's up to the players to not click to use cards when those cards have been blanked.

**Comment by nealterrell** [comment]
#1846 may fix this.
