### ISSUE TITLE
Vulcan Coverup not triggerable by 24/7 News Cycle

### ISSUE THREAD

**Issue by TheRealC** [mtgred/netrunner#1845]
Hiya there.

I was playing a game some hours ago as Titan Transnational against a Valencia-Rebirthed-into-Quetzal. I had two Vulcan Coverups in my score area; one of them I had scored myself (it had the Titan Transnational agenda counter on it), one I had been sent by a Turntable. I went for the obvious play, which was, clearly:

Power Shutdown my R&D into Archives -> Jackson Howard three 24/7 News Cycles into R&D -> Accelerated Diagnostics to play my three 24/7s.

Now the expected behaviour would be that I could re-trigger Vulcan Coverup's "When scored, do 2 meat damage." However, I could not target neither of the Coverups ("my own" or the Turntabled one) with the 24/7 News Cycles; clicking on them, even after very explicitly choosing to use each 24/7, in turn and order, did nothing (I'm 99.9% sure I was using Accelerated Diagnostics right).

Possible causes I could think of: Turntable screwed up my agenda zone (still weird that the "real" Coverup didn't work), 24/7 got confused since its additional cost of forfeiting an agenda suddenly no longer applied, Rebirth somehow broke it, the Agenda Counter from Titan Transnational somehow broke it.

Since it's the only real win condition of that overly janky Titan deck, it would be nice to see this fixed.

I have not been able to confirm whether you are normally able to 24/7 a Vulcan; maybe that just doesn't work at all for some reason.

As an aside, we used console commands to resolve the damage, and I hit his only I've Had Worse on the second 24/7. It was worth the try.

Cheers, and thanks for all your hard work,

The Real C

**Comment by Saintis** [comment]
Had a look at the code. This is due to an incorrect check for 24/7 (I think). 
The `:choices` req is currently:
```clojure
:choices {:req #(and (is-type? % "Agenda")
                                (= (first (:zone %)) :scored)
                                (:abilities %))}
```

But the relevant attribute for 24/7 is `:effect` and not `:abilities`. This should be an easy fix.

**Comment by TheRealC** [comment]
Awesome, thanks!

**Comment by Saintis** [comment]
Actually might not be that easy... related to #1555.

The `:abilities` bit seems to be intended to ensure only agendas on the corp side are targetable. Adding an explicit side check: that the card is in `[:corp :scored]` and not `[:runner :scored]` would replace the use of `:abilities`

**Comment by kevkcc** [comment]
I'm working on this as part of my agenda PR
