### ISSUE TITLE
Jinteki: Potential Unleashed and Guru Davinder interaction

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#1848]
Jinteki: Potential Unleashed still automatically triggers after Guru Davinder blocks damage. I know the pack is still new so this isn't an urgent one, just something I observed.

To reproduce:
1. Runner installs Guru Davinder
2. Jinteki: PU deals 1 net damage (e.g. Bio-ethics Association, Neural EMP)

Thanks for all the work.

**Comment by nealterrell** [comment]
This has been fixed but not deployed.
