### ISSUE TITLE
New Angeles City Hall cannot prevent the tag from Snatch and Grab

### ISSUE THREAD

**Issue by kyokorebit** [mtgred/netrunner#1850]
When the runner chooses to take the tag instead of getting their resource trashed, the prompt appears, but there should also be another prompt to prevent the tag if you have NACH installed.

**Comment by JoelCFC25** [comment]
This ruling explains why the tag was made unpreventable: http://ancur.wikia.com/wiki/Snatch_and_Grab_Tag_Is_a_Cost_Ruling

**Comment by nealterrell** [comment]
Thanks for the report, but as Joel said this is working as intended.
