### ISSUE TITLE
Functionality: Update API for netrunnerdb

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#1852]
netrunnerdb is retiring its current API, so we may need to update our fetch routines. 

They are also renaming faction "neutral" into "neutral-runner" and "neutral-corp"; need to investigate if that affects the API

**Comment by Saintis** [comment]
Whoever looks into this might also look at NRDB API for loading DotW and player's own decks.

**Comment by Saintis** [comment]
Should be done now.
