### ISSUE TITLE
Duplicated Cards (Runner Side Only?)

### ISSUE THREAD

**Issue by MontyWhittaker** [mtgred/netrunner#1853]
I had two consecutive games against Runners (I was running an IG deck that used Bio-Ethics, the only card I used that I know of that interacted directly with the Runner), in which they reported duplicate cards. Both games were against Shapers, and the first reported that he had a Levy in his hand. Three Levy AR Lab Accesses had already been played and removed from the game, and the total number of cards on the field, in the runner's grip, and in the stack and heap was 45. After the game, we didn't double-check to see if any cards were missing from the deck. The next game I played, the same issue was reported, with the Runner reporting that he had a second card of which he only had one copy in the deck, and later, a third copy of a different card, which he only had two instances of in the deck. Sorry, I didn't think to take screenshots or anything.

**Comment by JoelCFC25** [comment]
Unfortunately I think this will be impossible to follow up on without information from the Runner who experienced it. The sequence of events (and cards involved) from the moment when the card got duplicated would be ideal.

**Comment by JoelCFC25** [comment]
If this happens again, please have the other player report it, including *plenty* of details.
