### ISSUE TITLE
NullPointerException using Fairie

### ISSUE THREAD

**Issue by bigfleet** [mtgred/netrunner#1855]
I used Faerie to break subs on a newly rezzed Komainu with 3 subs attaching.

Have not tried to reproduce.  Perhaps the stack trace may be suggestive.

Stack Trace:

``` clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [clojure.lang.Numbers gt "Numbers.java" 3864]
  [game.core$play_ability$fn__4428 invoke "core-actions.clj" 179]
  [game.core$check_req invokeStatic "core-abilities.clj" 109]
  [game.core$check_req invoke "core-abilities.clj" 105]
  [game.core$can_trigger_QMARK_ invokeStatic "core-abilities.clj" 142]
  [game.core$can_trigger_QMARK_ invoke "core-abilities.clj" 137]
  [game.core$resolve_ability_eid invokeStatic "core-abilities.clj" 87]
  [game.core$resolve_ability_eid invoke "core-abilities.clj" 72]
  [game.core$resolve_ability invokeStatic "core-abilities.clj" 68]
  [game.core$resolve_ability invoke "core-abilities.clj" 10]
  [game.core$play_ability invokeStatic "core-actions.clj" 187]
  [game.core$play_ability invoke "core-actions.clj" 171]
  [game.main$handle_do invokeStatic "main.clj" 75]
  [game.main$handle_do invoke "main.clj" 72]
  [game.main$handle_command invokeStatic "main.clj" 147]
  [game.main$handle_command invoke "main.clj" 137]
  [game.main$run$fn__23865 invoke "main.clj" 173]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 163]
  [game.main$_main$fn__23881 invoke "main.clj" 226]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by nealterrell** [comment]
Now that's very strange.

It looks like a routine to take 1 recurring credit is being invoked. (Evidence: the call to `check-req` is triggering the `:req` on line 179 of core-actions.clj, which deals with the automatically-hooked "take 1 recurring credit" ability. Card abilities are numbered starting at 0, so Faerie's two abilities are numbered 0 and 1. When the server is told to invoke a card's ability, it is given the number to invoke. Line 179 checks that number against a count of the number of abilities on the card... if the ability number is equal to the ability count (not a valid ability number), then we interpret that command as being intended for the auto-hooked recurring credits ability. 

So either the UI somehow told the game server to invoke Ability 2 on Faerie (there is no such ability), OR the Faerie card itself somehow "lost" its 2 abilities, and the server was told to invoke Ability 0.  Very interesting.

**Comment by bigfleet** [comment]
It's quite possible there was a bad pub on the board.
