### ISSUE TITLE
24/7 accelerated diagnostics interaction

### ISSUE THREAD

**Issue by PowerfulWizard** [mtgred/netrunner#1856]
24/7 doesn't resolve when playing it through accelerated diagnostics with just one agenda on the score area. If you have 2+ agendas scored it resolves normally (ingoring the aditional cost of forefeiting an agenda, as it should) .

**Comment by Saintis** [comment]
24/7 has a `req` of more than one agenda scored. This should probably be removed or changed to at least one agenda scored. Relevant line [here](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards-operations.clj#L5).
