### ISSUE TITLE
Efficiency Commitee getting stuck without advanced forever

### ISSUE THREAD

**Issue by LunaSong** [mtgred/netrunner#1857]
When i was playing with a friend of mine, he scored Efficiency Commitee and during a turn he used to get clicks, but then next turn he was still stuck without advancing, he tried spending all agenda counters, and the next turn he was still stuck without advancing.
Card was in a server with an upgrade, Efficiency Committee was the second Agenda scored.

**Comment by JoelCFC25** [comment]
Efficiency Committee was recently modified in #1847, but I'm not sure why `register-persistent-flag` was used instead of `register-turn-flag`. In any case, this one is for @kevkcc!
