### ISSUE TITLE
Director Haas trash: Runner doesn't score 2 points

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#186]
If the Runner trashes Director Haas, it neither adds the card to the Runner's score area nor gives the Runner 2 agenda points. 

Chairman Hiro is coded the exact same way, so I imagine if one is bugged they both are, but I haven't tested with Chairman Hiro yet.

**Comment by JoelCFC25** [comment]
Confirmed just now--Chairman Hiro is also bugged in the same way.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
