### ISSUE TITLE
Andy [Rebirth] Ian Sterling

### ISSUE THREAD

**Issue by ScrnDoorSubmrine** [mtgred/netrunner#1863]
When using Rebirth to switch from Andy to Ian Sterling, his two credit start of turn ability doesn't trigger when corp has more agendas. Thanks!

**Comment by NorwegianLegion** [comment]
I did some testing and it looks like either The Supplier or Security Testing is causing the issue. Hope this helps.

**Comment by Saintis** [comment]
So this issue only appears when you rebirth into Ian with The Supplier or Sec Testing installed?

If that's the case then the issue could be related to `:runner-phase-12` stuff.

**Comment by NorwegianLegion** [comment]
That's correct. Just to make sure, I tested this with a normal Ian deck and his ability was working fine (even with The Supplier and Sec. Testing installed).

**Comment by nealterrell** [comment]
I am unable to reproduce this. I have a test that does the following:

1. Corp scores Breaking News.
2. Runner (Andy) installs The Supplier. Runner clicks to host Underworld Contact on The Supplier. Runner installs Security Testing. Runner plays Rebirth, selects Iain. Runner ends turn with 2 credits. (Cost of The Supplier.)
3. Corp takes credits.
4. Runner starts turn. Runner sees prompts to install off The Supplier and to select a Security Testing target. Runner has 4 credits from Iain's ability popping.

Can you be more specific about what you tested?

**Comment by NorwegianLegion** [comment]
![netrunner capture](https://cloud.githubusercontent.com/assets/12424752/18220555/dea669de-7138-11e6-8799-6f8cdb032a67.JPG)

I hope this screenshot helps.

1. Corp scores 15 minutes
2. Runner installed Supplier, hosted Temüjin Contract, and played Rebirth into Ian.
3. Corp turn
4. Runner used Supplier to install Temüjin Contract. No log text saying that Ian gained 2 credits.

**Comment by JoelCFC25** [comment]
I'm not sure why it isn't firing automatically, but in my testing you can just click on Iain Stirling either before hitting Start Turn or after hitting Start Turn and finishing the install from The Supplier and you'll get the 2 credits.

**Comment by JoelCFC25** [comment]
This is still happening. We probably already know this, but just to recap--if Andromeda plays Rebirth to turn into Iain Stirling with no cards installed, Iain will on the next turn immediately start firing his ability if the Runner behind on points. If at any point he subsequently installs The Supplier, the ability stops firing. Both Iain and The Supplier have `:drip-economy true` in common.

**Comment by NoahTheDuke** [comment]
This doesn't happen anymore.
