### ISSUE TITLE
Data leak reversal doesn't check if the Runner is tagged

### ISSUE THREAD

**Issue by Kiv** [mtgred/netrunner#1864]

**Comment by JoelCFC25** [comment]
I see it right there on line 275 of `cards-resources.clj`:   `:req (req tagged)`. Can't replicate this.

**Comment by Kiv** [comment]
Sorry, it's working correctly. Someone reported it to me on one of my videos but on closer look, Paparazzi was installed. So he was just confused that it said 0 Tags but I was still tagged.
