### ISSUE TITLE
Doppelganger run ending

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#1865]
I think the fix in #1849 broke Doppelganger. Nothing happens when you pick "yes" on the prompt, so I'm guessing the run is getting ended immediately or just not triggering.

**Comment by posttrib777** [comment]
I've noticed the exact same thing
run ends short

**Comment by nealterrell** [comment]
This is because we are firing "successful run ends" before killing the run information. Doppelganger does trigger a new run, but that run is immediately killed once the "successful run ends" trigger finishes resolving, because the code thinks that the OLD run is now finally done and can be killed.
