### ISSUE TITLE
Khan icebreaker install discount not applied

### ISSUE THREAD

**Issue by Lokkij** [mtgred/netrunner#1873]
The 1-credit discount Khan provides when installing an icebreaker through her ability is not applied, and I can't see anything in the relevant source code that indicates that the discount is implemented.

Khan's card text for reference (emphasis mine):
> The first time you pass a piece of ice each turn, you may install an icebreaker from your hand, **lowering the install cost by 1**.

**Comment by Saintis** [comment]
Seems the discount was forgotten when the card was implemented. Should be easy to fix.

Just update [Khan's install](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards-identities.clj#L389) to reduce cost by one using `(install-cost-bonus state side [:credit -1])`

**Comment by JoelCFC25** [comment]
My goof--sorry.
