### ISSUE TITLE
Pop Up Window grants corp too much energy

### ISSUE THREAD

**Issue by simianspaceman** [mtgred/netrunner#1876]
Hey guys,

the Card "Pop Up window", does not eliminate the Corp's ability to gain a credit after the first credit is granted, when encountered by a runner. 

The card also has the the ability for the runner to pay a credit to not  end the run. The runner is never prompted to do this. The run can be terminated by the corp at any time.

**Comment by JoelCFC25** [comment]
Thanks for posting. I have a feeling you may be overestimating the degree to which the game system is automated. There are many parts of the system that move things along for you more or less correctly, but there are also lots of areas where it is left to players to know and implement the rules correctly. For example, there is nothing preventing a player from firing an ICE subroutine over and over, nor is there anything preventing a Runner from just advancing past a piece of ICE without using breakers to deal with it.

**Comment by simianspaceman** [comment]
Sorry I am a bit new to all of this. Yes as i play a bit more i am seeing that I have indeed overestimated.

**Comment by Saintis** [comment]
The ability for Runner to pay 1 credit is PR'd in #1684 as well. For now the runner can simply adjust their credits accordingly.
