### ISSUE TITLE
"Successful run" prompt available when targeted marketing with Sol

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#1880]
When New Angeles Sol gets an agenda stolen, they can refire targeted marketing. This gives them the ability to choose a card to name. While the card is being named, the runner gets a "successful run" prompt, and if they click they get another access on the server. If runner doesn't click, then the prompt disappears when the corp finishes choosing. Note: if the runner has used something like the turning wheel or medium to access additional cards, then these apply to the second successful run too.

**Comment by JoelCFC25** [comment]
It doesn't look like New Angeles Sol is using `:delayed-completion`, which is probably needed here.

**Comment by nealterrell** [comment]
You're right Joel, it needs that tag in the `:yes-ability`, so the final `play-instant` call will assume the eid of Sol's effect.
