### ISSUE TITLE
Multiple run triggers on single runs

### ISSUE THREAD

**Issue by Amphiprison** [mtgred/netrunner#1881]
So the Runner ran R&D with an R&D Interface while I had Prisec installed and unrezzed.  Runner accesssed Space Camp, Prisec, and Hades Fragment in R&D.  Space Camp triggered twice, Prisec triggered three times.  Not sure what else might have messed with it.

**Comment by nealterrell** [comment]
This looks like an issue with Prisec, which needs to use `continue-ability` in `:access` and mark its `:yes-ability` as `:delayed-completion true`.
