### ISSUE TITLE
Shi.Kyū and Shock! in archives

### ISSUE THREAD

**Issue by DocCroaker** [mtgred/netrunner#1882]
When Shi.Kyū is in the corp archives it triggers more than once per card. At one point I had two in archives and it triggered 3 times.
During the same game I had a similar issue with Shock!

In a second game, the Shi.Kyū continuously triggered until the runner flatlined.

**Comment by Saintis** [comment]
Could be something related to the other issues of runs not ending properly...

Remember how the run was made, if any upgrades were installed in the root of archives, and if any other cards were accessed (agendas or such)?

**Comment by nealterrell** [comment]
Yes, the exact other cards involved here are probably the culprits, so anything you remember would help.

**Comment by DocCroaker** [comment]
Sorry, I'm not able to remember the exact other cards. Both times it happened I was using the same deck. I am willing to start up a game with the intent to recreate this situation, if someone else can test it with me. Or if it does happen again I'll capture more specifics.
