### ISSUE TITLE
Pawn + Scheherazade + Deep Red

### ISSUE THREAD

**Issue by Neophos** [mtgred/netrunner#1886]
http://imgur.com/a/NI4Wm

If you, in response to the "Do you want to use Deep Red's ability"-prompt, click on Scheherazade to host the Pawn, nothing will happen, but once you press OK on the prompt you will get Scheherazade's prompt, and then once you've clicked on Pawn for that, then when you click on a piece of ICE for Pawn's ability, you will get one on the ICE and one on Scheherazade.

The pawn created by Scheherazade disappears if it goes into the heap - The heap says that X cards are in it, but you can only see and select X - 1 cards, with the Pawn being hidden. In all other ways the Pawn seems to behave normally.

**Comment by JoelCFC25** [comment]
This troika of cards is very problematic and they are a pain in the rear to use--so much clicking. There are a couple of approaches here. Deep Red can be un-automated so it stops reacting to the `:runner-install` event. I could also try bumping up the `:priority` of Scheherazade's "host something that's already installed" prompt, but I'm not sure that'll work yet.

**Comment by JoelCFC25** [comment]
Actually, boosting the priority of that Scheherazade prompt seems to do the trick.
