### ISSUE TITLE
Imp Virus counters and purge

### ISSUE THREAD

**Issue by DocCroaker** [mtgred/netrunner#1889]

**Comment by DocCroaker** [comment]
sigh... wrong button
I did a purge as the corp, the runner had an imp out with one virus counter left. The purge successfully removed two virus counters from Medium, but did not remove the last virus counter from Imp. I took a screen shot, in case other cards on the table matter. The Imp was hosted on a Djinn, and that Djinn was hosted on a Leprechaun.

**Comment by JoelCFC25** [comment]
Thanks for the report. The `purge` function is currently coded to only look one level deep for hosted cards, so anything doubly-hosted (or deeper) won't get touched.
