### ISSUE TITLE
Priority issue for multiple damages occurs in the same time.

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#189]
If a series of multiple damages occurs in the same time, players are unable to choose the order.
Since "I've Had Worse", the order is important.

Example : 
Runner got 2 Agendas in his/her score area and only two cards in hand which one is "I've Had Worst". Jinteki PE scores a Philotic Entanglement.
2 net damages occurs because of the Agenda and 1 net damage occurs because of the ability of PE in the same time.
The corp can choose in which order. 
0% of winning chance by starting with the Philotic.
50% of winning chance by starting with the PE.

**Comment by eah13** [comment]
+1.  This is a more general issue with simultaneous things like accessing from archives as well.  Seems like there would need to be general support for simultaneous things in the game where the active player would choose resolution order.  Accessing a 2 card server is another case.

**Comment by nealterrell** [comment]
One year later... I think we're ready to tackle this.

**Comment by nealterrell** [comment]
This is now fixed.
