### ISSUE TITLE
The Turning Wheel / Nisei II counter interaction - automation problem

### ISSUE THREAD

**Issue by NotTopGearRH** [mtgred/netrunner#1893]
I recently ran into this issue in a casual game - currently there is no window for Corp players to use their Nisei Tokens to end the run after the runner has spent some of their Turning Wheel tokens.  In the game, a window exists for this to take place;  however on JNet, if you select "Action Before Access", you either have to pre-emptively end the run (not costing the runner their tokens) or allow the game state to pass to "Successful Run" at which point the runner spends the TTW tokens and immediately accesses their ton of cards.

I'm not sure what the solution to this is...

**Comment by Saintis** [comment]
I think the easiest solution for now would be to select "Action before Access" and inform the other player that they should spend TTW tokens at that point (before allowing run to be successful).

A potential (slightly incorrect rules-wise) solution on the coding side would be to not allow token spending after the last corp action window.

A proper coding solution would be to set some kind of flag when an ability is used just before "Successful Run" (after "Action before Access" window closes) to allow the Corp to perform abilities after the runner.
