### ISSUE TITLE
Hemorrhage Activations Cause Game to Crash

### ISSUE THREAD

**Issue by ejg51241** [mtgred/netrunner#1898]
Hey guys,

I'm finding that using hemorrhage's ability twice in a row causes the game to crash/players to get disconnected.  I think it might be because there's no prompt for the runner to wait for the Corp to discard the first card before asking for the second.

Thanks!

**Comment by Saintis** [comment]
That is likely the case. This should use the wait prompt framework.

**Comment by JoelCFC25** [comment]
Any revision should also prevent the Hemorrhage ability from being used in the first place if the Corp hand is empty.
