### ISSUE TITLE
It is easy to accidentally de-rez a corp card

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#19]
A large number of corp cards do not have any abilities implemented at this time.  However, all corp cards that have been rezzed automatically get access to the "derez" ability.  Because of the way ability logic works, where if there is only one available ability, it is simply executed when the card is clicked on, clicking on an unimplemented card to see if it is implemented will de-rez it without warning.

This can be easily worked around by re-gaining the credits and re-rezzing, but in the long term a more elegant solution is probably desired.

**Comment by eah13** [comment]
+1 to this.  Clicking a corp card should always bring up a menu, even if there's only one item in the menu, to prevent accidental rezzing and de-rezzing of cards form misclicks.  This happens often with Ash.

**Comment by JoelCFC25** [comment]
Closing since there is a duplicate open issue.
