### ISSUE TITLE
Vikram and Medium

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#1900]
When firing the Medium, the Runner is still able to access additional cards with Medium.

They should still gain extra virus counters (which does not count as "using" the card), but not be able to gain additional accesses (which does).

**Comment by JoelCFC25** [comment]
Vikram (as noted in the card implementation status sheet) has only partial functionality. Both it and Wendigo are unable to prevent use of paid abilities on programs. In this instance, it is incumbent on the Runner to know that they must click Medium and choose to access 0 additional cards.

**Comment by HubGitAccoutn** [comment]
Cool, cheers.
