### ISSUE TITLE
Space Camp and Medium interaction

### ISSUE THREAD

**Issue by wombat929** [mtgred/netrunner#1908]
Hello,
When doing an R&D run using Medium, if Space Camp triggers, there's an access error.  Here's the interaction:

Runner runs R&D with multiple accesses because of medium and encounters Space Camp.
Corp gets the option to use Space Camp's advancement tokens AND the runner gets access to the Successful Run button
If the Runner clicks "Successful Run" before the corp uses the advancement tokens, the run starts over with additional accesses. 
For instance, if the runner begins the run with 4 virus counters on medium, the first access is for 5 cards. If this bug occurs, the runner starts over with 10 cards, then 16, and so on.  Here's the log from the corp view:

"lunalovegood sets virus counters to 4 on Medium.
lunalovegood spends  to make a run on R&D.
wombat929 has no further action.
lunalovegood accesses 5 cards.
lunalovegood accesses 10 cards.
lunalovegood steals Global Food Initiative and gains 2 agenda points.
lunalovegood accesses 16 cards.
lunalovegood left the game."

Thanks for all your hard work on this project!
wombat929
briley@curragh-labs.org

**Comment by JoelCFC25** [comment]
Thanks--Space Camp needs to use `continue-ability` and show wait prompts to the Runner, much the same as was done with Award Bait.
