### ISSUE TITLE
Khan and Caprice bug

### ISSUE THREAD

**Issue by MasterPrudent** [mtgred/netrunner#1916]
This is a niche one given the lack of devoted Khan players but here goes:

When Khan's ability is triggered on a server with one piece of ICE and a rezzed Caprice (ie so both Kahn and Caprice trigger at the same time) it can cause a bug. Caprice's psi game will trigger but the runner will be given a successful run even if the corp wins the psi game. 

I forgot to get a screenshot of this but will do so if I run into it again.

**Comment by nealterrell** [comment]
OK, I have a fix for this.
