### ISSUE TITLE
Uniqueness rez/install should prompt to trash, not prevent the action

### ISSUE THREAD

**Issue by dodgepong** [mtgred/netrunner#1927]
If the runner already has a unique non-console installed, Jinteki.net currently prevents them from installing another copy of that card entirely. This isn't exactly correct -- players are allowed to install new copies of unique cards, but upon doing so, all existing copies of that card that are installed are trashed.

Similarly, if the corp has a unique card rezzed, other copies of that card are entirely prevented from being rezzed unless the unique card is trashed. In reality, players are allowed to rez multiple copies of unique cards, but upon doing so, existing copies are trashed.

This is relevant especially now that Temujin Contracts exists, as many players who aren't familiar with the rules of unique cards assume that once you install a Temujin, it's stuck there until it's empty, not realizing that they are, in fact, allowed to install another one and trash the previous one. Similarly on the Corp side, new players might not realize that you can rez another copy of Caprice Nisei, trashing an existing one, if needed.

My suggestion is to provide the player with a confirmation prompt when they attempt to install another copy of a unique card, or rez another copy of a unique card, rather than prevent the install/rez altogether and assume the player knows they are allowed to trash the existing ones.

**Comment by nealterrell** [comment]
It will probably be easiest to make this a toast, similar to the "You can't afford to do that" toast that @Saintis created. Toasts are non-interactive so it would have to implore the player to trash the existing Unique card themselves. I think that will be easier than layering another prompt into the install process.

**Comment by dodgepong** [comment]
A toast would work, as long as it was clear to players that trashing unique cards for the purposes of installing/rezzing other copies of that card is "legal." (Excluding consoles, of course.)
