### ISSUE TITLE
Remove fresh card highlight from stolen agendas

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#1935]
The highlight indicating that the card was freshly installed doesn't ever go away if the Runner steals the agenda very next turn. It should be removed right then.

**Comment by nealterrell** [comment]
The real problem is that the highlight is only removed by iterating `all-installed`. This does not consider cards that were trashed, scored, stolen, or RFG'd.

**Comment by nealterrell** [comment]
OTOH, this may be as simple as updating `deactivate` to dissoc `:new` from the card.

**Comment by JoelCFC25** [comment]
Very likely. I'll try it...
