### ISSUE TITLE
Shi-Kyu fires from R&D

### ISSUE THREAD

**Issue by triorph** [mtgred/netrunner#1937]
There seems to be some bug with Shi-Kyu half-firing on the runner's side from R&D. If it is accessed from R&D then they have to use the /close-prompt action to be able to continue playing the game.

**Comment by JoelCFC25** [comment]
The `:req (req (not= (first (:zone card)) :deck))` needs to be bumped out to the topmost level.

**Comment by zaroth** [comment]
Are there any more cases of lingering halo after this fix?
