### ISSUE TITLE
0 point and -1 point agendas are not handled correctly by The Board.

### ISSUE THREAD

**Issue by triorph** [mtgred/netrunner#1938]
0 point agendas should be worth -1, and -1 point agendas (news team etc.) should be -2, however with the board only 1+ point agendas are handled correctly when calculating the sum.

**Comment by JoelCFC25** [comment]
I think The Board needs a rethink. Even if this issue gets fixed, it's not doing anything to modify the actual `:agendapoints` values of things in the Runner's area. So in the unlikely event that a Runner forfeits a News Team while The Board is active, I doubt the Runner's score would get adjusted correctly.
