### ISSUE TITLE
Rezzed Blacklist not preventing Trope from moving cards out of Heap

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1946]
This one surprises me, since `move` has a check to see that the origin zone isn't locked.

**Comment by ch1102chiou** [comment]
Update the brief test results:
Test git commit hex: 547bfe952b171f8878bd5c67faac74ee757a49fa.
Step1: rez Blacklist as an asset.
Step2: runner use 4 ways to let cards remove from heap:

1. clone chip -> clone chip cannot be trigger util I trash the Blacklist.
2. pawn ->  pawn will be trashed but cannot install a Rook from the heap. 
3. déjà vu -> **card leave from the heap**.
4. trope -> **card leave from the heap.**

This issue can be duplicated confirm.

**Comment by Saintis** [comment]
Déjà Vu and Trope uses `move` while clone-chip uses `runner-install` which suggests the issue is in `move`.

**Comment by Saintis** [comment]
`runner-install` checks for `:locked` in [core-installing:302](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core-installing.clj#L302). `move` does not seem to check for `:locked`. 

Since `move` is used by `move-card` which is called when the user manually drags a card it is probably best not to check for lock there and instead create a new function that wraps a `move` call in a `:locked` check. Alternatively add a `:force` flag to `move` so that `:locked` can be bypassed for some reason.

**Comment by JoelCFC25** [comment]
Ark Lockdown is another card that Blacklist fails to block.

**Comment by JoelCFC25** [comment]
Some progress here...

Lines 66-69 of `move` do contain a locked zone check, but it reads: 
`(not (seq (get-in @state [side :locked zone]))`

Compare to the check in `runner-install`, which is: 
`(empty? (get-in @state [side :locked (-> card :zone first)]))`

If we change line 69 of `move` to use the same check as in `runner-install`, Deja Vu and Trope are prevented from moving cards out of the Heap--yay!  However, now they can't be manually dragged out of the Heap either--boo!

Ark Lockdown with a rezzed Blacklist still moves cards out of the Heap with this check, but that makes sense, because `side` in this case will be `:corp` as it's the Corp playing the card, so the function will check `[:corp :locked :discard]`, correctly see nothing, and do the move.

**Comment by JoelCFC25** [comment]
Think I've got it all now. If we add `force` as a key to `move`, then manual dragging is enabled by adding `:force true` to the params of the `move` calls in `move-card`. Then Ark Lockdown just needs to do `move state :runner` to make sure locked status is checked in the right place.
