### ISSUE TITLE
Edward Kim not trashing on access after Retrieval Run

### ISSUE THREAD

**Issue by asherstuhlman** [mtgred/netrunner#1947]
After using Retrieval Run and accessing no other cards in the turn, if Edward Kim accesses an operation, it won't be trashed.

**Comment by JoelCFC25** [comment]
Thanks for the report. I think it will probably be sufficient to check that there is no `:run-effect` in `[:run]` in addition to the other checks in the `:req` for the `:successful-run-ends` event listener in Ed Kim.
