### ISSUE TITLE
Crisium Grid is broken

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#1949]
@Saintis did some initial investigation. 

Examples where it's working:
* Stops the replacement ability on Account Siphon

Examples where it's broken:
* Install Temujin Contract and target a server with a rezzed Crisium, run it, and Temujin pays out credits
* Install Desperado and run a server with a rezzed Crisium, Desperado pays out 1 credit

**Comment by NorwegianLegion** [comment]
Crisium Grid doesn't prevent Off The Grid from being trashed either.
