### ISSUE TITLE
Temujin Contracts only resolves on first successful run

### ISSUE THREAD

**Issue by carlsondc** [mtgred/netrunner#1952]
Was playing as Silhouette. Turn 1 was
- Install  Temujin Contract (targeting archives)
- Run archives: prompted for TC and for Silhouette's ability (?), TC correctly resolves (counts down, increments credits)
- Run archives: prompted for TC and silhouette, credits on TC do not change, credit total doesn't change

This did not resolve itself on the following turn. Later in the game I installed TC (targeting HQ) and, again, it resolved correctly the first time and then had no effect on later runs.

**Comment by JoelCFC25** [comment]
Thanks for the report. We already started investigating this earlier today--it's an unintended consequence of some changes in #1928. @nealterrell is on the case!
