### ISSUE TITLE
Adam Decks include directives they shouldn't

### ISSUE THREAD

**Issue by datlo** [mtgred/netrunner#1954]
When I play Adam, I get 1 of each directive in my deck when I don't run any beyond the three I need for the jinteki.net deckbuilder.

**Comment by Saintis** [comment]
This has recently been changed. You now don't need to add the directives explicitly, they will be added automatically. See #1936.

**Comment by datlo** [comment]
Kk, but then the bug is that the deckbuilder says the deck is invalid " (minimum 48) (not enough directives) " when my deck is 45 cards with the directives removed

**Comment by Saintis** [comment]
Ah. It appears the client side code has not been updated.

**Comment by datlo** [comment]
Alright. Sorry for the duplicate issue. Didn't know if you'd get a notification for a comment.

**Comment by JoelCFC25** [comment]
Fix has been fully deployed now.
