### ISSUE TITLE
Employee Strike/RP interaction when Employee Strike trashed on runner turn

### ISSUE THREAD

**Issue by kevkcc** [mtgred/netrunner#1956]
I'm not 100% sure that this interaction is wrong but...

Steps:
1. Employee Strike is in play
2. Runner replaces it with another current (i.e. Rumor Mill on the Runner turn)
3. For that turn, the Runner is able to run on remotes even if they hadn't run on a central previously.

**Comment by Saintis** [comment]
I think this is a bug with Employee Strike / RP interaction. But it is probably a hassle to fix.

**Comment by mattchainsaw** [comment]
Chronos Protocol is a similar identity. The ability to `enable-corp-damage-choice` is set at both `:runner-phase-12` and `:corp-phase-12`. This interaction does work, however, even though the state is turned off at the `:leave-play` trigger. 


Since RP enables the runs on the `:leave-play` trigger and disables the runs on the `:runner-phase-12`, I thought I could reproduce this Chronos Protocol, but the test passed.


```
(deftest chronos-protocol-employee-strike
  ;; Chronos Protocol - Issue #1958 also affects chronos protocol
 (do-game
   (new-game
     (make-deck "Chronos Protocol: Selective Mind-mapping" [(qty "Pup" 1)])
     (default-runner [(qty "Employee Strike" 1) (qty "Scrubbed" 3)]))
   (play-from-hand state :corp "Pup" "HQ")
   (take-credits state :corp)
   (play-from-hand state :runner "Employee Strike")
   (run-on state :hq)
   (let [pup (get-ice state :hq 0)]
     (core/rez state :corp pup)
     (card-subroutine state :corp pup 0)
     (is (empty? (:prompt (get-corp))) "No choice because of Employee Strike")
     (card-subroutine state :corp pup 0)
     (is (= 2 (count (:discard (get-runner)))))
     (run-jack-out state)
     (take-credits state :runner)
     (take-credits state :corp)
     (play-from-hand state :runner "Scrubbed")
     (run-on state :hq)
     (card-subroutine state :corp pup 0)
     (is (boolean (:prompt (get-corp))) "Employee Strike out of play - Ability turned on correctly"))))
```

**Comment by nealterrell** [comment]
I got this.

**Comment by nealterrell** [comment]
Thanks for the test, @mattchainsaw -- all fixed.
