### ISSUE TITLE
Doppleganger/Temujin/Security Testing/Silhoutte buggy interaction

### ISSUE THREAD

**Issue by rodrigoSantamaria** [mtgred/netrunner#1959]
It seems that esp. Security Testing and Silhoutte + Temujin or other 'when the run is successful' actions (such as my oponent having an ash on another server) makes strange things.
A concrete example:
I install Temujin (selecting archives) and select an already installed Security Testing on the archives too. I also have a Doppleganger and I'm using Silhoutte as id. 
When i successfully run Archives, both Temujin and ST trigger just fine (it also gives me the option to trigger Slhoutte, which is buggy). I re-run archives with Doppleganger and the second succesful run, although gives me the option to trigger Temujin, does not get the creds.

Please describe the circumstances of your error here. Stack Trace:    clojure Error do continue #error { :cause nil :via  {:type java.lang.NullPointerException :message nil :at nil}  :trace   }

**Comment by JoelCFC25** [comment]
This will almost certainly be fixed by #1953.
