### ISSUE TITLE
Controlling the Message fails to trigger when a runner card has been trashed earlier that turn

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#1962]
For example, if the runner uses a Street Peddler before trashing the first corp card, CTM will not trigger.

I'm not 100% sure this is the issue, but it seems to fit every time CTM fails to trigger in a game I'm playing.

**Comment by JoelCFC25** [comment]
Thanks for the report. I've verified it, but for now I'm baffled why this is happening. CtM requires the target of the `:runner-trash` event be: installed, a Corp card, and be the first instance of `:runner-trash`. I don't see how the first 2 of these could possibly be the case. This will need more investigation.

**Comment by artturipi** [comment]
Well, if you use Street Peddler, it seems pretty likely that's a runner-trash -event. So then trashing a corp card is no longer the first runner-trash, right?

**Comment by JoelCFC25** [comment]
Yeah, I realized that a bit ago and then had to go AFK. I didn't realize this, but `trash` already supports `:suppress-event true` (thanks, whoever did that), so this might be an easy one.
