### ISSUE TITLE
Cards trashed by damage message displaying when no cards trashed 

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1969]
This is a small cosmetic thing:

![image](https://cloud.githubusercontent.com/assets/12355388/18611834/a730a1c2-7d04-11e6-8fd7-0457e9e46aea.png)

When all the points of damage from a given source are prevented, the new cards trashed due to damage message still displays, but with no listed cards.

As a side note, it might be nice to have a message indicating which choice the runner makes when Argus triggers. It's implied by the damage prevention, but I think the log would look cleaner and more intuitive if it said "RunnerName chooses to take 2 meat damage" after resolving the dialogue.

**Comment by Saintis** [comment]
The "akkyle23 suffers 2 meat damage." statement is the message that the choice for Argus sends currently. This could probably be made more explicit by referencing Argus.
