### ISSUE TITLE
Old Holywood Grid Bugged

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#1972]
Hi 
I just ran into an issue with Old Holywood Grid on R&D not working. I am unsure if it's the whole thing or just because it was a The Future Perfect that caused it but after losing the psi game the runner stole the agenda despite it been the only TFP seen all game because it was a multi access run as well i couldn't really put the game back in to a correct state.

**Comment by nealterrell** [comment]
This is most likely a problem with TFP and not Old Hollywood.
