### ISSUE TITLE
The Source and The Future Perfect interaction

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#1976]
The Source incorrectly triggers before TFP's psi game. I "accidentally" stole TFP even when I answered "no" to The Source.
I think the way it's supposed to work is, Psi game should trigger first. If Runner wins the psi game, The Source should trigger. Otherwise, The Source does not trigger because steal is prevented.

The following sequence also broke my game:
1. Run Archives with TFP in it
2. Answered 'No' to The Source 
3. Did /close-prompt for TFP's psi game
4. Got stuck in "successful run/jack out" menu for all eternity

Thanks for the work.

**Comment by nealterrell** [comment]
TFP has a number of issues and should probably be rewritten so that failing the psi game is what prevents the steal, instead of the current implementation in which the steal is prevented by default, and then short-circuited if the psi-game succeeds.
