### ISSUE TITLE
Heartbeat and trashed due to damage message

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#1977]
When Heartbeat is used to prevent damage, and a face down card is trashed, the card's name is not displayed in the following trashed due to damage message (or this is the same issue as #1969 and Heartbeat needs a message that lists what cards it used to pay for its ability, including face down cards).

![image](https://cloud.githubusercontent.com/assets/12355388/18656820/c27aacbc-7eb1-11e6-97ca-951ac1e81591.png)

**Comment by Saintis** [comment]
I think the solution would be to have Heartbeat print the card that was trashed. For example:

> taegunv uses Heartbeat to prevent 1 damage, trashing a facedown Harbinger.

The "trashes ... due to damage" statement will be printed if all damage is prevented so it's probably best to put the information with Heartbeat.
