### ISSUE TITLE
Leela bounce order

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#1979]
Not sure whether this is a a known issue or not ...

Corp legworks HQ with 2 ice on R&D
sees an agenda, bounces inner ice (we think) - sees another agenda, bounces the ice which is now the inner ice - but only one of the ice bounces resolves.

Shockeh uses Desperado to gain 1 .
Shockeh accesses Quicksand.
Shockeh accesses Project Beale.
Shockeh steals Project Beale and gains 2 agenda points.
Shockeh accesses Breaking News.
Shockeh steals Breaking News and gains 1 agenda point.
Shockeh uses Leela Patel: Trained Pragmatist to add ICE protecting R&D at position 0 to HQ.

**Comment by JoelCFC25** [comment]
I can't reproduce this on a couple of initial attempts--it all appears to work fine.

**Comment by tolaasin** [comment]
perhaps write it off to the rng gods then.

**Comment by JoelCFC25** [comment]
To be fair, there have been lots of isolated, hard-to-reproduce issues involving Legwork over time. I've always suspected that it's not helpful to be clicking things as fast as possible, but can't substantiate that, and don't know if that's what people are actually doing.

**Comment by jbrz** [comment]
Tested multiple scenarios, couldn't duplicate.
