### ISSUE TITLE
Kaplan + Comet + Starlight Crusade Funding

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#198]
I was testing my deck and I think I found a bug; I made a test to be sure.
Given:
Identity: Kaplan,
Comet hardware on the Rig,
Starlight Crusade Funding on the Rig.
If as my first click I play an event, specially an event of subtype "double", I was expecting to play another event (maybe another double) all at 1 click cost.
Now, it cost me 3 click.

**Comment by eah13** [comment]
Playing two doubles with Comet would cost 3 clicks because you must still pay the one click additional cost.  Playing a double and a normal event should cost only 2 clicks.

**Comment by osiridecascioli** [comment]
Sorry but I disagree; Starlight C.F. should prevent any additional click costing, so, for example:
on click 1: Lucky find (1 click because Starlight C.F.) then Comet allow me to play 1 more event, Lucky Find, and no additional click costing because Starlight C.F.

**Comment by eah13** [comment]
Oh you're exactly right.  Sorry, forgot about Starlight Crusade.  With that and Comet you can play two of any normal or double event for 1c.

I think your original issue then should be about Startlight Crusade not working correctly.  Sure enough, it's shown as [only partially implemented on the big ol spreadsheet](https://www.dropbox.com/s/rpkhxafgile5spp/Cards%20status.xlsx).

**Comment by JoelCFC25** [comment]
Starlight Crusade Funding implemented at #752.
