### ISSUE TITLE
Khan ability providing additional discounts

### ISSUE THREAD

**Issue by unitled** [mtgred/netrunner#1983]
Haven't had a chance to chase this bug at all, but here's what happened:

I ran on a server, Corp didn't rez the ice, I pass it and decline to use Khan's ability. Continue and access. Next click I install a Keyhole, for which I'm charged 3cr. Looks like her discount was carried over?

Thank you!

**Comment by JoelCFC25** [comment]
Thanks for the report. Khan will need a `:cancel-effect` that will dissoc `:cost` from `[:bonus]` in the game state.

**Comment by nealterrell** [comment]
The discount should be applied after the prompt is shown, not before.
