### ISSUE TITLE
Hosting nested Full Immersion RecStudios prevents interaction

### ISSUE THREAD

**Issue by erbridge** [mtgred/netrunner#1993]
Create a hosted structure something like this:

```
FIR A
  -> FIR B
      -> Asset A
      -> Asset B
  -> Asset C
```

When a Runner attempt to access cards, they can only access:

- FIR A
- FIR B
- Asset C

Clicks on the other cards are ignored.

In fact, if you access all 3 accessible assets, the run ends automatically, which makes me think there's an issue with nested hosting in the code, rather than interaction being blocked by invisible click handlers.

This is only try for the runner. The corp can interact with their cards as normal. Both sides also get card previews when they hover over the deeply nested cards, even if they can't be accessed by the runner.

**Comment by Saintis** [comment]
The problem is in `access :remote` in `core-runs.clj:458`. The list of cards to access only checks for the first level of `:hosted`, not recursively.
