### ISSUE TITLE
Asset/agenda install over upgrade, or vice versa

### ISSUE THREAD

**Issue by ichigokuto** [mtgred/netrunner#1996]
doubt this hasnt been suggested before but couldnt see it at first glance. if not, would be a nice to have.
Can we have a prompt when installing a upgrade in a facedown asset/agenda server, or vice versa, where it gives the option to auto-trash the installed card(s) when installing... therefore hiding the type of the card installed?
Currently if you're installing an upgrade, it'll put it by the agenda/asset... when IRL you could trash at the same time you install.
(the automation of J.net removes a bluffing op. doing it manually in j.net kinda gives the game away)
Suggestion - when installing the card it give prompt of cards installed which are suitable for trashing.
hope this makes sense.

cheers

Rob

**Comment by erbridge** [comment]
Would also avoid the instant overwrite that can happen from misclicks and is annoying to fix.

**Comment by Saintis** [comment]
I think this is important to fix. Solution could be to show a recursive prompt asking if you want to trash any installed cards when installing into an existing server. Cards that have to be trashed (agenda / asset) could be emphasized. When hitting done the install goes ahead and any mandatory trashed would be performed.

I'll look into this.

**Comment by ichigokuto** [comment]
nice one! thats fantastic! 
thanks for this

**Comment by Saintis** [comment]
I'll keep the issue open until I have a fix working and merged into the master branch.

**Comment by ichigokuto** [comment]
oops, sry my bad. thank thanks again

**Comment by erbridge** [comment]
Could do this like Jackson. Show a prompt with "Select cards to trash before installing", with "Trash" and "Cancel" options. Then show a toast if they try to trash without selecting the asset. Or preselected the asset for minimum clicks.

**Comment by Saintis** [comment]
That's a good idea

**Comment by nealterrell** [comment]
I'd prefer a method that does not add clicks to every single install operation. Perhaps only show the reminder if the server contains an upgrade and nothing else, as that is the only use case that can't be done manually. (If there is more than one card, you can drag to trash before the install and the server won't be destroyed.)

**Comment by erbridge** [comment]
It would only need to add clicks when installing in a server with something else already installed in it (which is a small fraction of installs, excluding ice).

An alternative would be to add a seperate menu option called "Install with Trash" or "Replace" or something, though I expect that might be confusing to someone who doesn't know why it's there.

**Comment by Saintis** [comment]
Alternatively, trigger the install, then show a prompt to trash any card. On "Done" any cards that have to be trashed (Agenda, Asset, Region) will be autotrashed. That means you only have 1 more click when you install in a server with other cards in it.

This would solve the main issue of the trash triggering instantly when you install, thus removing some bluffing aspects.

**Comment by JoelCFC25** [comment]
Got more requests for this feature in Stimslack over the weekend.

**Comment by nealterrell** [comment]
I'm trying this in reverse. Instead of an option to auto-trash, get rid of it completely. Every install of a second card into a server looks the same to the Runner, with a second card appearing in the server. If that card is a second agenda/asset, the Corp is shown a prompt to trigger the automatic trashing of the old card. The delay that this causes should look identical to the delay you'd get from manually dragging an Upgrade to the trash to make it look like an old agenda/asset.
