### ISSUE TITLE
Problem leaving a game

### ISSUE THREAD

**Issue by erbridge** [mtgred/netrunner#1997]
If a game host leaves the game, the other player loses the "Leave Game" button, and needs to refresh the page to leave the game. There is also no message in the log.

**Comment by Saintis** [comment]
I get this sometimes on my local dev server. Does this happen in production as well?

**Comment by erbridge** [comment]
Yes. It started happening recently. Not sure if it's everytime, though.

**Comment by Saintis** [comment]
The "Leave Game" button is added [here](https://github.com/mtgred/netrunner/blob/master/src/cljs/netrunner/main.cljs#L59). My hunch is that `(:started game)`  is cleared when the host leaves the game, thus hiding the button.

Will add to my list and do some investigating.

**Comment by erbridge** [comment]
That would make sense, since "Concede" is also removed.

**Comment by erbridge** [comment]
I think this might actually be to do with timeouts. It occurs when waiting a while (maybe analysing a game) after the game ends.
