### ISSUE TITLE
Snitch causing massive slowdown

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#200]
When i use snitch to expose a card it asks me if i want to jack out. There are two problems here:
1. Regardless of what i answer i return to the "Continue" / "Jack out" menu and have to select jack out again. 
2. When i click "Yes" or "No" in the snitch "Do you want to jack out?" menu it locks up the gui. I can't type anything and the "Do you want to jack out?" menu is still there even though i clicked yes or no. Oddly enough things seem to go back to normal as soon as the opponent types something in chat. I have been able to reproduce this on several occasions.

**Comment by Balkmeister** [comment]
It appears that typing before i answer the "do you want to jack out?" question does nothing.

**Comment by Balkmeister** [comment]
it appears any action from the opponent, not just typing frees up the snitch freeze.

**Comment by mtgred** [comment]
Thanks for reporting the issue. Snitch has been fixed. The fix will be deployed with the next server update.
