### ISSUE TITLE
Harmony Medtech is stuck on "casual"

### ISSUE THREAD

**Issue by benticurus** [mtgred/netrunner#2005]
I have legal decks that show up as "casual" no mater what i do as long as im usinf the Medtech ID

**Comment by nealterrell** [comment]
Have you tried changing the ID, save, then change it back and Save?

**Comment by Saintis** [comment]
Did that resolve the issue?

**Comment by JoelCFC25** [comment]
This is definitely the required fix. There is still an item in the News header about this, but you have to scroll to the bottom.
