### ISSUE TITLE
Trashes cards message displaying when all damage is prevented

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2007]
This might be a different case than last time:

![image](https://cloud.githubusercontent.com/assets/12355388/18859260/c310eb90-842f-11e6-8388-2c4beb9542f8.png)

Damage triggered off of Mamba's paid ability, and prevented with Deus X.

**Comment by Saintis** [comment]
This one might just be the same issue, not sure if the fix I provided for that one has been deployed. Will investigate this evening. Thanks for reporting all these bugs though :smile:

**Comment by FarCryFromHuman** [comment]
I thought I saw the fix deployed, so I threw this issue together. I barely have time to play, and I certainly don't have time to learn Clojure, but taking five minutes to report an issue is a contribution I can make :)

**Comment by Saintis** [comment]
Looks like it's just since the fix is not deployed. This is what I get on when I run it locally on `master`:
<img width="198" alt="screen shot 2016-09-28 at 16 38 31" src="https://cloud.githubusercontent.com/assets/13198563/18918135/1bfb2c96-859a-11e6-8d9f-e27bcd1c867e.png">
