### ISSUE TITLE
chat window is covering the card images

### ISSUE THREAD

**Issue by spoonfunk** [mtgred/netrunner#202]
Ever since the servers were rebooted on may 21st the chat window is extending up into the area where the card images are displayed.

**Comment by mtgred** [comment]
I'm experiencing the same problem with Chrome (version 43.0) on my Macbook.

With Chrome (version 42.0) on my iMac it works fine. On Firefox and Safari it's ok too.

It looks like the lastest Chrome update broke things. I will search for a solution. In the meanwhile please use another browser.

**Comment by mtgred** [comment]
The layout has been changed to work on Chrome 43.
