### ISSUE TITLE
NPE when Runner lets Archangel/Chrysalis trace fire

### ISSUE THREAD

**Issue by jbrz** [mtgred/netrunner#2024]
Please describe the circumstances of your error here.
Accessed a chrysalis in R&D, clicked "yes" to "allow all subs to fire" text > npe.

Presumably because it was not installed yet still acted as encountered ice...

Stack Trace:
```clojure
Error do choice Yes #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at nil}]
 :trace
 []}
```

**Comment by jbrz** [comment]
happens with archangel as well.

**Comment by JoelCFC25** [comment]
These cards got broken by @saintis PR that allowed Runners to trigger subroutines on ICE.

**Comment by jbrz** [comment]
Yeah I found the interaction, figured I'd let y'all fix it.
