### ISSUE TITLE
Won't play cards from grip

### ISSUE THREAD

**Issue by spoonfunk** [mtgred/netrunner#203]
Several times today I have been unable to continue games due to not being able to play cards from my grip. It seems to be only when I am playing the runner.

**Comment by GordonsBeard** [comment]
If a card is not implemented then nothing will happen when you click the card. Have you made sure the card is supported?

**Comment by JoelCFC25** [comment]
A card being unimplemented doesn't stop it from being playable from your hand--they can be played and the right number of credits will be deducted.

**Comment by JoelCFC25** [comment]
Closing this for now. If it comes back and there are reliable ways to reproduce it, just open a new issue for it.
