### ISSUE TITLE
Tri-Maf Contact incorrect (uninstall) triggers

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#2031]
Misclicked Tri-Maf Contact in my grip and it installed. When I moved it back to my grip, I took 3 meat damage. When I accidentally used Dr. Lovegood to blank it out, I also took 3 meat damage.

**Comment by Repulze** [comment]
I'm guessing Archangel will also trigger take 3 meat damage.

**Comment by JoelCFC25** [comment]
So frustrating...this has been fixed and re-broken like 6 times in the past.

**Comment by Repulze** [comment]
Take your time to fix it, I'm one of the few who plays that card anyway. xD
