### ISSUE TITLE
A number of cards are triggering unnecessarily from archives

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2037]
Archangel, snare, for example.

**Comment by zaroth** [comment]
Related to #1965 ?

**Comment by Saintis** [comment]
Will look into it. Have an idea what could be the problem.

**Comment by Saintis** [comment]
Could not reproduce locally. Will assume it's a duplicate of #1965. Fix has been merged in #1985.

**Comment by nealterrell** [comment]
#1985 is live, @Saintis.

**Comment by Saintis** [comment]
Maybe related to multiaccess bug? Let me know if it happens again / any steps to reproduce it.

**Comment by JoelCFC25** [comment]
I also can't reproduce a Snare! activating in Archives (yet).

**Comment by tolaasin** [comment]
To be clear, snare wasn't activating but was prompting, as was archangel. There was no snare fire but it was included in the list of cards which must be accessed.

**Comment by JoelCFC25** [comment]
Sorry, I misspoke--by activating I did mean "generating a prompt".

**Comment by Saintis** [comment]
Will investigate further...

**Comment by JoelCFC25** [comment]
However, I *have* confirmed the issue with multiple agendas in Archives and the run immediately ending after the Runner accesses the first of them.

**Comment by JoelCFC25** [comment]
We figured out "can't steal all agendas in Archives". Expect that fix in #2042 as well.

**Comment by JoelCFC25** [comment]
@tolaasin: any more cases of this spotted? Meaning Archangel/Snare!/etc showing as things that have to be accessed in Archives?

**Comment by tolaasin** [comment]
Not recently, but I haven't been playing against many decks that have snare or archangel.

**Comment by JoelCFC25** [comment]
With no further reports or follow-up confirmation, I'm closing this. If it crops up again we can reopen it.
