### ISSUE TITLE
R&D Multi-access Bugged (Medium, RDI, TTW...)

### ISSUE THREAD

**Issue by Sotomatic** [mtgred/netrunner#2038]
When accessing cards with medium, would list the same card multiple times instead of new cards.  I.E accessing 4 cards accessed 4 sure gambles

![image](https://cloud.githubusercontent.com/assets/22602019/19051947/8a2c0a44-897a-11e6-874b-a8ae236f2c5f.png)

**Comment by Kaethela** [comment]
This seems to be happening with _all_ multi-access cards, or at least all R&D multi-access. Used Maker's Eye a few times across different games and every single time hit the same card multiple times in a row. Interestingly, in one case, I was able to trash two of them but not the third, and the Corp drew and installed that card. This has... interesting implications.

**Comment by finnbar** [comment]
Ah, I think I found it! See https://github.com/mtgred/netrunner/commit/2ae9946c2e2adadcb227c468b436ceb60a1a456c#diff-f3a5327ba97bdfb06a4a6c5ea6ce1669R363

Notably the use of "first", when it should probably be some variable pointing to whatever card is being accessed out of R&D. I have no idea how to fix it, but I think that's where you're looking.

**Comment by JoelCFC25** [comment]
I think we're close on a fix...more tonight perhaps.
