### ISSUE TITLE
Bug: Medium + Hivemind combo

### ISSUE THREAD

**Issue by abokovyy** [mtgred/netrunner#2043]
When you have Medium + Hivemind combo and access R&D, virus counters are working correctly only to the point when they are Medium counters. For Hivemind counters you get the last accessed card all X times where X is the number of counters on Hivemind.

E.g.
1 counter on Medium and 6 counters on Hivemind. Run on R&D.

Accessing project and stealing it.
Accessing second card and trashing it.
Accessing Hedge Fond 6 times in a row.

**Comment by JoelCFC25** [comment]
Thanks--we already have the multi-access bug in at #2038. The fix is coming in #2042.
