### ISSUE TITLE
Close-prompt during Celebrity Gift or Mushin No Shin

### ISSUE THREAD

**Issue by Spionbil** [mtgred/netrunner#2046]
After unintentionally clicking the wrong card and closing the prompt I noticed that the game starts behaving very strangely past that point. This lasts seemingly forever as I made a deck containing nothing but Mushin No Shin, Celebrity Gift and Pad Campaigns to put down on the board and went through my entire deck.

When the prompt is closed on either of the two cards with or without the other in hand the following will happen.

The next card, not the one you closed the prompt on, will behave as the other one. 

In a sequence played as such. Where ok means it works as intented and not ok is the "opposite"

> Close-prompt mushin
>    play mushin - ok
>       play gift - not ok
>          play mushin - not ok
>             play mushin - ok

You close the Mushin which makes the next Celebrity Gift behave as a Mushin, which in turn makes the next Mushin after that behave as a Celebrity Gift. 
However, any number of consecutive number of Mushins or Celebrity Gifts will behave normally past the first. They behave normally until the other card is played.

The behaviour is only reversed for the for the first card played after the other. Alternating Mushin and Celebrity Gift will guarantee the reversed behavior every card. They are always "the first card of the other kind."

Expecting this to be related to doubles or perhaps targeted operations. I have tried both with Corporate Shuffle and Reuse.

Corporate Shuffle does not alter its behavior as far as I have been able to tell. Perhaps because it is not a targeted card.

Reuse however also shares the same problem as Celebrity Gift and Mushin. With three targeted cards in the deck the order seems to work out to this.

The same things apply as before. Consecutives operations work past the first etc.

The operation you are playing right now will become what the card of the last one you played says it is.

> Close-prompt gift
> play reuse - becomes gift
> play mushin - becomes reuse
> play gift - becomes mushin

I also tried some non double targeted operations.

Rework and Lateral Growth but also combined with reuse to see if the behavior is somehow not consistent between double or normal operations.
The behavior is still consistent from what I can tell. It still becomes what the last card played says it is. 

In all cases the text above the hand looks proper. Rework asks you to pick a card, Celebrity Gift asks you to pick five. But if the card that is actually "in effect" allows more or less it allows this despite the text. Rework can target five cards to trash as Reuse and gift is forced to shuffle in the first card clicked.

I have not tried this with an opponent who also uses targeted events to see if it breaks across players nor have I tried it as a runner. But I expect it to be the same for the runner.

**Comment by Saintis** [comment]
I am guessing this has to do with the `close-prompt` command not cancelling any logic that lies behind the card, hence the next targetting card resolves the previous' prompt logic.

Workaround would be to just allow the card to trigger and adjusting the game state manually (e.g. Celebrity Gift revealing 0 cards).

**Comment by nealterrell** [comment]
I can change `/close-prompt` to trigger `effect-completed` for the currently-active prompt, signifying that it is "done".

**Comment by zaroth** [comment]
This would certainly help usability of that command.
