### ISSUE TITLE
Multi-access lockup

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#205]
As reported on live server, multi-access is locking up the game. Verified with Maker's Eye, Medium, R&D Interface, and Legwork. When accessing, the first accessed card is shown in a prompt. After the prompt is closed, the *second* card is shown, but attempting to close this prompt gives the server-console error

`Error  do choice nil #<NullPointerException java.lang.NullPointerException>`

Unlocking the server by typing a message returns the Runner to the "Successful Run/Jack Out" prompt; choosing Successful Run repeats the error in the same loop.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The fix has been deployed.
