### ISSUE TITLE
Deckbuilder can't change count of AstroScript Pilot Program cards

### ISSUE THREAD

**Issue by sars1492** [mtgred/netrunner#2052]
When I add the new card **AstroScript Pilot Program** in *Deckbuilder*, only one this card is added to my deck and I can't rise count of cards of the same type by clicking to + in card list.  The content (number) of field next to *Add to deck* button has no effect. 

Other cards seem work fine (I've tested only core set decks)

**Comment by JoelCFC25** [comment]
Relatively recently (say, a month or so), AstroScript Pilot Program received errata that limits it to 1 copy per deck. See page 2 of [the official FAQ](https://images-cdn.fantasyflightgames.com/filer_public/aa/d3/aad35e6c-afdb-4de4-b034-ec5b5b748106/adn_faq_v312.pdf).

**Comment by sars1492** [comment]
I'm very sorry for false issue. I started play netrunner only two day ago and I'm still trying only core decks. 
Thank you for clarification.

**Comment by JoelCFC25** [comment]
No need to be sorry! It is a bit annoying that they did something that makes it impossible to build a legal NBN deck using a single core set, but APP was pretty widely agreed to be very powerful.
