### ISSUE TITLE
Enhancement Suggestion - Recurring/Stealth Credits

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#2056]
There are situations in which a runner can erroneously gain credits during a run through mis-spent recurring credits, i.e., if a runner uses Stimhack and then breaks a sentry using Switchblade and takes the stealth credits. Similarly, when a corp has Bad Publicity, the runner can take Whizzard credits to trash fibers, and the bad pub credits will persist beyond the run.

Would it be possible to instead add recurring/stealth credits taken during a run to the "Credits for run" pile that Stimhack and Bad Pub use so they clear automatically after the run? I can't think of a situation where this would negatively impact the game state, and with the upcoming popularity of Net Mercur and Stealth it may be worth adding.

**Comment by LiteSpecter** [comment]
Ah, this method is not 100% foolproof, since if the runner takes Whizzard credits _after_ trashing a card but before competing the run, credits will still be wrong.

**Comment by Saintis** [comment]
Improving the general recurring credits / stealth credit logic would be very useful but does require some thought.

Changing stealth cards to take credits from a selected source could be feasible first step. As in when you boost / use Switchblade you get a target crosshair to select stealth credit source to take from (e.g. Silencer, Ghost Runner, Net Mercur...)

**Comment by erbridge** [comment]
What about BlacKat?

**Comment by Quarg** [comment]
Related / Alternative method of handling this issue: https://github.com/mtgred/netrunner/issues/1457

**Comment by NoahTheDuke** [comment]
Implemented with #4262
