### ISSUE TITLE
Selecting but not entering a private game prompts for password on next non secured game

### ISSUE THREAD

**Issue by squogfloogle** [mtgred/netrunner#2061]
Steps to reproduce:
1) Find a game that is Private
2) Click watch on that game
3) Click watch on another non private game
4) You are now prompted for a password on the non private game - should be able to enter.

**Comment by Saintis** [comment]
Can confirm this happens - _if_ you don't click "cancel" on the password enter prompt.

Also, if you then click "watch" on a different game (or at least the private game you clicked on in step 2 above) you enter (spectating) the game you selected in step 3 above.

Some odd behaviour all around.
