### ISSUE TITLE
Encountering Archangel from a central prompts the runner for successful run after the encounter ends

### ISSUE THREAD

**Issue by Kaethela** [mtgred/netrunner#2070]
Running on a central server (HQ or R&D especially) and hitting an Archangel that is not installed but is in hand or in R&D will prompt the runner to have a successful run after the encounter ends. This has the effect of repeating the access step of the run. If they hit Archangel _again_ they could conceivably be stuck in an infinite loop. A /close-prompt is needed to put an end to this.

**Comment by JoelCFC25** [comment]
Can you try this again since there was a restart this morning? I cannot currently reproduce this.

**Comment by Kaethela** [comment]
As soon as I get the chance I'll make a couple dummy decks to test this out with and report back.

**Comment by tolaasin** [comment]
something related to this happened just now - single access on HQ accessed archangel, but then also triggered access of another card.

rojazu spends  and 4  to install Temüjin Contract.
rojazu uses Temüjin Contract to target HQ.
rojazu spends  to make a run on HQ.
tomdidiot has no further action.
rojazu uses Net-Ready Eyes to give Paperclip +1 strength.
rojazu sets credit to 0 (-1).
rojazu continues the run.
tomdidiot has no further action.
rojazu uses Temüjin Contract to gain 4 .
rojazu accesses Archangel from HQ.
tomdidiot pays 3  to force the Runner to encounter Archangel.
tomdidiot uses Archangel to initiate a trace with strength 6 (6 + 0 ) (Add 1 installed card to the Runner's Grip).
rojazu spends 0  to increase link strength to 0.
rojazu uses Temüjin Contract to gain 4 .
rojazu accesses Global Food Initiative from HQ.
tomdidiot uses Archangel to add 1 installed card to the Runner's Grip.
tomdidiot adds Datasucker to the Runner's Grip.

tomdidiot
It accessed two cards from hq

**Comment by JoelCFC25** [comment]
Confirmed, getting lingering "Successful Run / Jack Out" prompt *yet again*. UGH.

**Comment by tolaasin** [comment]
yay. a reproducible bug :)

**Comment by JoelCFC25** [comment]
To be clear though, the log snippet above was not _automatically_ a 2 card access. The rojazu player saw the spurious prompt and chose to hit Successful Run again, thus the extra access and extra Temujin payout. Obviously the prompt should not be there at all, but the extras wouldn't have happened if they had chosen Jack Out.

**Comment by tolaasin** [comment]
got it. I'll let him now.
