### ISSUE TITLE
BOOM!'d after Consulting Visit

### ISSUE THREAD

**Issue by karmaportrait** [mtgred/netrunner#2072]
Opponent played 'Consulting Visit' and then I was visiting Whizzard in BOOM!'d afterlife. Console showed BOOM! counting as only one click, played after two clicks for Consulting Visit. Have not tried to re-create or test outside of that match.

**Comment by nealterrell** [comment]
This is the correct interaction, assuming Consulting Visit was played on the first click.

**Comment by karmaportrait** [comment]
Yeah, that was entirely my mistake. Misread the cards.

**Comment by nealterrell** [comment]
No problem :).
