### ISSUE TITLE
I'm getting reports of draft decks "crashing" the game

### ISSUE THREAD

**Issue by gumOnShoe** [mtgred/netrunner#2074]
I created the arena mode over the weekend and several people have reported that they can't install anything as runner in many of their games. Clicking things just stops working. Can't tell you much more than that, but I've only heard of it affecting runner and the disappointment that follows.

**Comment by JoelCFC25** [comment]
If you are in contact with any of these folks directly, please have them supply some details--e.g., which identity is being used, a decklist, can they confirm they've done a forced refresh in recent times, are they using a supported browser (i.e., not IE or Edge), are they getting the red error popup, things like that. A link to this new mode would be useful as well. Thanks!

**Comment by JoelCFC25** [comment]
Wondering now if this is the same as #2112.
