### ISSUE TITLE
glitch with making an entrance

### ISSUE THREAD

**Issue by aac168** [mtgred/netrunner#2075]
If you choose the wrong cards to trash, no way to fix the draw if you start over. If you try to place the trashed cards back on your stack then click done, will glitch the next few draws. (i.e. whatever cards are put on the stack in the 2nd phase will be overwritten) 

Example of my glitch:
In my game, I had IHW, IHW, Liberated, Liberated, SOT. I trashed SOT and 2x Liberated by mistake. 

I wanted all 5, just in a different order, so I dragged SOT, then 2x liberated to stack. Finished the card prompts by just ordering the two IHW together. The next 4 draws ended up being IHW x4 then SOT. 

Not sure how code is written, but seems like the Liberateds got overwritten when I interrupted the MAE card prompts by manual fixing the stack by adding the Liberateds back. 

Perhaps there could be a way to code so that first trashed cards to go in a temporary zone hidden from corp, then 2nd phase you choose cards left to rearrange, then finalize or start over? Right now it seems like the trash phase is a hard trash that can't be reversed. 

Thank you!

**Comment by nealterrell** [comment]
Thanks for the report. Probably not worth fixing -- in the future, I imagine a `/close-prompt` during the reorder phase would let you drag everything back into place and play the event again.

**Comment by JoelCFC25** [comment]
Agreed. The thing to do in this case is play out the card to conclusion, then drag cards back and take an extra click to play it over again.
