### ISSUE TITLE
Bug with Research Station (upgrade)

### ISSUE THREAD

**Issue by abokovyy** [mtgred/netrunner#2093]
It seems to end the run when accessed (as soon as you access it, so if you accessed it first, you can't access cards in HQs).

**Comment by JoelCFC25** [comment]
Was it rezzed or unrezzed? If it can be confirmed, this sounds exactly the same as #2092.

**Comment by jbrz** [comment]
@JoelCFC25 I think I can confirm it's the same bug as #2092 - it just happened to me with Heinlein grid on HQ (Dirty Laundry run.  Still got laundry money, but run was just over instantly.)

**Comment by abokovyy** [comment]
It was rezzed. And no multi-access cards.
