### ISSUE TITLE
Crisium Grid bugs

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#2095]
Runners are having issues trashing Crisium Grid when installed. It abruptly ends the run. Same thing happened when using Leela +  2 Gang Signs + 2 HQ Interfaces. Crisium showed up as one of the accessed cards and when clicked ended the run.

Thanks!

**Comment by JoelCFC25** [comment]
Same as #2093 and #2092. Fix is pending at #2064.
