### ISSUE TITLE
Prevent effects do not work

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#21]
When an effect is triggered, there is no window to trigger prevent effects.  This can be pretty tricky to work around as some damage is done automatically (stealing an agenda from Jinteki: Personal Evolution, for instance), and this CAN result in a Flat-line result (which does not seem to end the game, so that may be fine).  Any cards lost here can be pulled back into the Grip from the Heap, but they've now been exposed to the corp player, reducing any surprise effect they might have.

This isn't utterly game-breaking, but is probably a problem for competitive play.

**Comment by mtgred** [comment]
Damage prevention has been finally implemented #211

**Comment by JoelCFC25** [comment]
@anathomical this one can be closed. :+1:
