### ISSUE TITLE
Ruhr Valley problems

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#2109]
Ruhr Valley is wrongly blocking the ability to run its server in some cases. In response to the `:runner-spent-click` event, this is problematic:  `:req (req (<= 1 (:click runner)))`

This means that if the Runner does _anything_ other than run the Ruhr Valley server on their first click, the `prevent-run-on-server` function will kick in and block off that server in the UI when attempting runs. 

Possibly related to this issue is the fact that `:runner-spent-click` actually fires before the click itself is deducted.

**Comment by erbridge** [comment]
Probably worth looking at making behave more like ELP and Service Outage.

**Comment by erbridge** [comment]
My initial thought it to make it so that the additional costs can take a function as well as a vector, and call the function if there is one.

**Comment by JoelCFC25** [comment]
YES. Additional costs are badly in need of work. There are whole pile of cards that can't work due to the way additional costs are represented right now--e.g., Donut Taganes can't work because of how "forfeit an agenda" is coded, which eventually makes `merge-costs` fail when you try to play a 24/7 News Cycle.

**Comment by danhut** [comment]
I still am not sure how to handle Ruhr Valley even with the additional cost changes to handle everything else ... eg. you play an event that let's you run.  Card is discarded.  Then you choose the target server - and hit the additional cost and realise you cannot run it.  Nasty stuff... need to think on it.

**Comment by NoahTheDuke** [comment]
Will be closed with @presheaf's run cost refactor coming in netrunner-future.
