### ISSUE TITLE
Shilouette and Blackguard make game crash

### ISSUE THREAD

**Issue by brokenimage321** [mtgred/netrunner#2119]
Twice now, I've had the game crash while using Shilouette and Blackguard in a combo.

Specifically, after making a run on HQ, Shil prompts me to pick a card to expose. Blackguard forces Corp to rez it. Sometime during this process, the game:

1) switches from the normal "target" cursor (for picking the card to expose) to the generic "hand" cursor.

2) throws an error. 

3) crashes; I can end the turn, but Corp still shows "Waiting for Runner."

The timing may have something to do with it too; as I recall, it happens on the last click of the turn.

**Comment by JoelCFC25** [comment]
Thanks. I made an error in my recent tweak of Blackguard--sorry about that.
