### ISSUE TITLE
Employee strike is not disabling HB ETF

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2120]
On the first turn after ES was played, ETF did not gain a credit on installing a card. But in subsequent turns, it did. Nothing apparently unusual about the board state.

**Comment by JoelCFC25** [comment]
You probably know what I'm going to type...yet again this is something I can't reproduce!

**Comment by tolaasin** [comment]
Happens :(. There were 18 spectators in the game (Josh was corping) so I'm pretty sure I wasn't imagining it. Much in game discussion.

**Comment by JoelCFC25** [comment]
Understood...it's not a question of belief, but rather "how are there so many things happening I can't verify"? Frustrating!

**Comment by tolaasin** [comment]
I should maybe just capture the chat log and a screenshot next time ... might help I think.

**Comment by tolaasin** [comment]
There were 18 spectators in the game. Josh was corping!

**Comment by JoelCFC25** [comment]
Any further occurrences of this one?

**Comment by tolaasin** [comment]
not recently
