### ISSUE TITLE
Edward Kim is forced to pay to trash Boom!

### ISSUE THREAD

**Issue by karmaportrait** [mtgred/netrunner#2121]
Accessing Boom! from R&D, Edward Kim does not auto-trash at not cost but is given dialogue box to pay to trash.

**Comment by JoelCFC25** [comment]
Thanks for the report. The `access-non-agenda` function contains code that pre-dates the advent of operations with a trash cost, so it is structured in a way that assumes you hit an asset or upgrade and have to decide whether or not to pay the cost. So it needs some new escape hatch to account for Edward Kim's effect.

**Comment by benhosp** [comment]
I tested this; Kim does auto-trash the operation at no cost, but it also gives him the dialog box asking him if he'd also like to pay the trash cost.

![screen shot 2016-11-05 at 2 05 47 pm](https://cloud.githubusercontent.com/assets/8769601/20032478/059cfd64-a361-11e6-8038-c3fbc672cb62.png)
