### ISSUE TITLE
Ruhr Valley and Enhanced Log In Protocols Prevent Run on Server

### ISSUE THREAD

**Issue by lord-xaphan** [mtgred/netrunner#2123]
When ruhr valley and enhanced login protocols are installed the runner cannot initiate a run. Not clear if each individually can cause the issue

**Comment by erbridge** [comment]
ELP should only prevent runs when the Runner only has 1 click and hasn't made a non-card ability run that turn. Is that not the case? If not, please provide more details.

Ruhr Valley issues captured in #2109.

**Comment by lord-xaphan** [comment]
I observed with both active and rezzed. It may be that Ruhr alone is
causing the issue as in #2109.

**Comment by JoelCFC25** [comment]
We'll just keep the previous issue for all progress, since this is only a Ruhr Valley issue.
