### ISSUE TITLE
How flexible is the codebase?

### ISSUE THREAD

**Issue by brokenimage321** [mtgred/netrunner#2125]
So sorry for the spam, but I'm not sure how else to contact y'all...

I'm having a lot of fun with Jinteki.net--so much so, I'm wondering if it might be possible to re-skin(?) it for another game. Specifically, the MLPCCG, to my knowledge, has no online play outside of an aggressive ruleset for OCTGN. Netrunner shares a few similarities with MLPCCG, but most importantly, Jinteki already has the code to display and shuffle cards and execute card instructions, which seem to be some of the hardest parts from my (inexperienced) perspective.

Though there's legal and technical hurdles to handle, do you think it would be possible to re-program Jinteki to work with another game? If so, might it be possible to get a copy of the code to play with?

If not, no problem; it's just a fun idea.

**Comment by zaroth** [comment]
There is absolutely no problem with reusing this codebase for another game - the code is available right here on github and the license is open source (MIT), allowing forks and modifications as long as you credit the original authors somewhere and include a copy of the license.

How much of it will be re-usable is another question. Unless the card game you have in mind is a Netrunner reskin/spinoff, I doubt you'll find much more useful stuff except for the absolute barebones (chat, lobby, server-game client communication, basic card display CSS). That said, reading the code and understanding how it's done can be still very helpful in implementing your own card game.

And what better why to learn than by doing - our [Getting Started guide](https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development) is this way :)
