### ISSUE TITLE
Tri-Maf Contact

### ISSUE THREAD

**Issue by DavePickles** [mtgred/netrunner#2128]
Does 3 damage when trashed from hand due to damage or due to hand size - card text should not be active when not installed.

**Comment by JoelCFC25** [comment]
You must mean Tri-maf Contact, but yes, inadvertently introduced (for like the 8th time) as of my change at #2100. Rolodex will have the similar problem. I think it can be fixed by adding `:req (req installed)` to the `:trash-effect`

**Comment by JoelCFC25** [comment]
Think I'm close to a solution that will stop Tri-maf/Rolodex from firing when lost from the Grip while preserving I've Had Worse's ability to do it.
