### ISSUE TITLE
minor log issue with ELP

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2129]
TheBigBoy spends 2  and  to play Enhanced Login Protocol.
TheBigBoy uses Enhanced Login Protocol to .
TheBigBoy uses Jeeves Model Bioroids to gain .

second line is borked

**Comment by JoelCFC25** [comment]
`:msg` can't go entirely silent. This conditional message needs to be done with `system-msg` inside the `:effect`.

**Comment by erbridge** [comment]
Any reason we can't just not print the message if `:msg` is `nil`?
