### ISSUE TITLE
Recurring credits refresh when a card is hosted

### ISSUE THREAD

**Issue by squogfloogle** [mtgred/netrunner#2132]
If the recurring credits are used from Sahasrara and then the program is later hosted on Saheherazade, the recurring credits are refreshed. I didn't have a change to try this with other hosting, but it may also trigger refreshes.

**Comment by JoelCFC25** [comment]
It should be noted that this is against the rules. If someone is installing Sahasrara at paid ability speed, they should host it on Scheherazade first before taking credits from it.

**Comment by squogfloogle** [comment]
True, but I spectated a game where they used it to fix later in the turn as
they'd forgotten to host on installing.

Not within the rules, but I can see people doing it reasonably often
anyway!

**Comment by JoelCFC25** [comment]
This would require an awful lot of work for an extremely niche use case. We have the `/counter` console command to make corrections as needed.
