### ISSUE TITLE
Mother Goddess with the Barrier subtype did  not trigger Paperclip install prompt

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2133]
Fairly self-explanatory!

**Comment by JoelCFC25** [comment]
Keeping with the theme, I can't reproduce this on an initial attempt. 

![screen shot 2016-10-31 at 8 56 25 am](https://cloud.githubusercontent.com/assets/10407969/19856566/01c071f2-9f48-11e6-9a17-21f720266fa3.png)

More information is needed. Was the Mother Goddess previously rezzed before the run was initiated, or had the Runner already approached it and it got rezzed and gained Barrier during the run?

**Comment by JoelCFC25** [comment]
Mother Goddess gains Barrier in response to the `:rez` event and Paperclip is reacting to the same event but requiring that the ICE already have Barrier. Not sure how to handle this one off the top of my head.

**Comment by tolaasin** [comment]
It was rezzed on approach.

**Comment by nealterrell** [comment]
Since Paperclip is a runner card, it's getting the rez event before MG gets it. MG could potentially duplicate its "gain subs" code into its own `:effect`, which is triggered when the card is rezzed, BEFORE (I think) the `:rez` event is triggered.
