### ISSUE TITLE
Accelerated beta test not permitting ICE install, draws 6 cards

### ISSUE THREAD

**Issue by bendbound** [mtgred/netrunner#2135]
When ABT is scored, it draws 6 cards from R&D. It allowed me to install/rez one ICE, but the other ICE cards in the temporary zone could not be installed.

**Comment by nealterrell** [comment]
This sounds like a double-execute bug as in #468. Most likely the card triggered twice, causing 2 events of "Draw 3" to trigger, and overlapping the prompts to select a card from the Temporary Zone (which can cause targeting issues). Do you recall if you were clicking quickly to score the ABT?

**Comment by bendbound** [comment]
No, I clicked once and waited a bit while I read the cards that came up.

**Comment by bendbound** [comment]
Actually, then when I clicked the ice to install it, it drew 3 more cards
instead of installing the ice.
