### ISSUE TITLE
Atman is breaking ICE of all strengths

### ISSUE THREAD

**Issue by bendbound** [mtgred/netrunner#2136]
Site allows Atman with 7 strength to break ICE of any strength for one credit.

**Comment by nealterrell** [comment]
We do not restrict the use of icebreakers in any way.

**Comment by bendbound** [comment]
So it's up to the player to jack out if the strengths don't match?

**Comment by nealterrell** [comment]
It's up to the Corp to execute any subroutines that the runner is unable to break.

**Comment by bendbound** [comment]
Okay. I'm new to the web based game, so I didn't know how much automation
to expect.

Thanks again.
