### ISSUE TITLE
Popup window is not yielding credits

### ISSUE THREAD

**Issue by bendbound** [mtgred/netrunner#2137]
When encountered, popup window does not provide the corp with a credit.

**Comment by nealterrell** [comment]
Pop-up Window has an explicit card ability to gain 1cr, since "encountering" is a difficult event to automatically trigger without a ton of manual user interaction.

**Comment by bendbound** [comment]
So the corp player manually adds a credit?

**Comment by nealterrell** [comment]
Yep!

**Comment by bendbound** [comment]
Got it, thank you.
