### ISSUE TITLE
HQ upgrade access on gang sign

### ISSUE THREAD

**Issue by fortmacborn** [mtgred/netrunner#2139]
Hello, just wanted to give an update from a game I was just playing. Installed, unrezzed cresium grid, runner has 3x gang sign. When I scored an agenda, gang sign access also gave runner an access on the grid.

Sorry I didnt take screenshots, but here is the chat log if that helps. I believe that the grid was installed after two of the gang signs but before the third.

11spoons takes a mulligan.
Nordrunner keeps their hand.

11spoons
gl hf
11spoons started their turn 1 with 5 and 5 cards in HQ.
11spoons spends  to install ICE protecting R&D.
11spoons spends  to install ICE protecting HQ.

Nordrunner
u2
11spoons spends  to install a card in Archives.
11spoons is ending their turn 1 with 5 and 3 cards in HQ.
Nordrunner started their turn 1 with 5 and 9 cards in their Grip.
Nordrunner spends  to play Career Fair.
Nordrunner spends 1  to install Earthrise Hotel.
Nordrunner spends  to play Career Fair.
Nordrunner installs Daily Casts.
Nordrunner spends  to install Security Testing.
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 1 with 5  and 4 cards in their Grip.
11spoons started their turn 2 with 5 and 3 cards in HQ.
11spoons spends  to draw a card.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons is ending their turn 2 with 7 and 5 cards in HQ.
Nordrunner started their turn 2 with 5 and 4 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner spends  and 1  to install Datasucker.
Nordrunner spends  to make a run on Archives.
11spoons has no further action.
Nordrunner uses Security Testing to gain 2  instead of accessing.
Nordrunner spends  to gain 1 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 2 with 10  and 5 cards in their Grip.
11spoons started their turn 3 with 7 and 5 cards in HQ.
11spoons spends  to draw a card.
11spoons spends 5  and  to play Hedge Fund.
11spoons uses Hedge Fund to gain 9 .
11spoons spends 10  and  to play Restructure.
11spoons uses Restructure to gain 15 .
11spoons is ending their turn 3 with 16  and 5 cards in HQ.
Nordrunner started their turn 3 with 10  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner spends  and 4  to install Temüjin Contract.
Nordrunner uses Temüjin Contract to target Archives.
Nordrunner spends  to make a run on Archives.

11spoons
ty for donating or coding, btw
11spoons has no further action.

Nordrunner
donating, and np. :)
Nordrunner uses Temüjin Contract to gain 4 .
Nordrunner uses Security Testing to gain 2  instead of accessing.
Nordrunner spends  and 3  to install Mongoose.
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 3 with 12  and 5 cards in their Grip.
11spoons started their turn 4 with 16 and 5 cards in HQ.
11spoons spends  to install ICE protecting Archives.
11spoons spends  to draw a card.
11spoons spends  and 1  to install ICE protecting R&D.
11spoons is ending their turn 4 with 15  and 5 cards in HQ.
Nordrunner started their turn 4 with 12  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner spends 1  and  to play Special Order.
Nordrunner adds Gordian Blade to their Grip and shuffles their Stack.
Nordrunner spends  and 4  to install Gordian Blade.
Nordrunner spends  to make a run on Archives.
11spoons spends 2  to rez Bailiff.
Nordrunner jacks out.
Nordrunner spends  to gain 1 .
Nordrunner trashes Femme Fatale from their Grip.
Nordrunner is ending their turn 4 with 10  and 5 cards in their Grip.
11spoons started their turn 5 with 13 and 5 cards in HQ.
11spoons spends  to install a card in HQ.
11spoons spends  to draw a card.
11spoons spends  to install ICE protecting Server 1 (new remote).
11spoons is ending their turn 5 with 13  and 5 cards in HQ.
Nordrunner started their turn 5 with 10  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Server 1.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner spends  to make a run on Server 1.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Security Testing to gain 2  instead of accessing.
Nordrunner spends  to draw a card.
Nordrunner spends 2  and  to play Inside Job.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner accesses Jackson Howard from HQ.
Nordrunner pays 3  to trash Jackson Howard from HQ.
Nordrunner accesses Prisec from the root of HQ.
11spoons spends 2  to use Prisec to do 1 meat damage and give the Runner 1 tag.
Nordrunner trashes Drive By due to damage.
Nordrunner pays 3  to trash Prisec from the root of HQ.
Nordrunner spends  and 2  to remove 1 Tag .
Nordrunner is ending their turn 5 with 4  and 4 cards in their Grip.
11spoons rezzes Prisec.
11spoons adds Prisec to HQ and gains 0 .
11spoons started their turn 6 with 11 and 5 cards in HQ.
11spoons spends  to install a card in HQ.
11spoons spends  to draw a card.
11spoons spends  to gain 1 .
11spoons trashes a card from their HQ.
11spoons is ending their turn 6 with 12  and 5 cards in HQ.
Nordrunner started their turn 6 with 4 and 4 cards in their Grip.
Nordrunner uses Security Testing to target Server 1.
Nordrunner spends  to draw a card.
Nordrunner spends  and 2  to install Corroder.
Nordrunner spends  to make a run on Archives.
genepiolo123 joined the game as a spectator.
genepiolo123 joined the game as a spectator.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons uses Bailiff to gain 1 .
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Temüjin Contract to gain 4 .
Nordrunner accesses Shock! from Archives.
11spoons uses Shock! to do 1 net damage.
Nordrunner trashes Inside Job due to damage.
Nordrunner spends  to draw a card.
Nordrunner is ending their turn 6 with 5  and 4 cards in their Grip.
11spoons started their turn 7 with 13 and 5 cards in HQ.
11spoons spends  and 1  to install ICE protecting Server 1.
11spoons spends  to install a card in Server 1.
11spoons spends  to gain 1 .
11spoons is ending their turn 7 with 13  and 4 cards in HQ.
Nordrunner started their turn 7 with 5 and 4 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends 2  and  to play Dirty Laundry.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons uses Bailiff to gain 1 .
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Temüjin Contract to gain 4 .
Nordrunner uses Security Testing to gain 2  instead of accessing.
Nordrunner uses Dirty Laundry to gain 5 .
Nordrunner spends  to draw a card.
Nordrunner spends  and 1  to install Gang Sign.
Nordrunner is ending their turn 7 with 12  and 4 cards in their Grip.
11spoons rezzes Jackson Howard.
11spoons started their turn 8 with 14 and 4 cards in HQ.
11spoons spends  to use Jackson Howard to draw 2 cards.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons trashes a card from their HQ.
11spoons trashes a card from their HQ.
11spoons is ending their turn 8 with 16  and 5 cards in HQ.
Nordrunner started their turn 8 with 12  and 4 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  to draw a card.
genepiolo123 disconnected.
Nordrunner spends  to make a run on R&D.
11spoons spends 5  to rez Hive.
Nordrunner jacks out.
Nordrunner spends  and 3  to install Daily Casts.
Nordrunner is ending their turn 8 with 9  and 5 cards in their Grip.
11spoons started their turn 9 with 11 and 5 cards in HQ.
11spoons spends  and 1  to install ICE protecting Archives.
11spoons removes Jackson Howard from the game.
11spoons uses Jackson Howard to shuffle Jackson Howard and 2 cards into R&D.
11spoons spends  to install a card in Server 1.
11spoons spends  to gain 1 .
11spoons is ending their turn 9 with 11  and 4 cards in HQ.
Nordrunner started their turn 9 with 9 and 5 cards in their Grip.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  to draw a card.
Nordrunner spends 5  and  to play Sure Gamble.
Nordrunner uses Sure Gamble to gain 9 .
Nordrunner spends  and 4  to install Earthrise Hotel.
Nordrunner is ending their turn 9 with 11  and 5 cards in their Grip.
11spoons spends 4  to rez Adonis Campaign.
11spoons started their turn 10 with 7 and 4 cards in HQ.
11spoons uses Adonis Campaign to gain 3 .
11spoons spends  to draw a card.
11spoons spends  and 1  to install ICE protecting HQ.
11spoons spends  to gain 1 .
11spoons is ending their turn 10 with 10  and 5 cards in HQ.
Nordrunner started their turn 10 with 11  and 5 cards in their Grip.
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner spends 5  and  to play Sure Gamble.
Nordrunner uses Sure Gamble to gain 9 .
Nordrunner spends  and 3  to install Desperado.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to make a run on Server 1.
11spoons spends 4  to rez Data Raven.
Nordrunner sets tag to 1 (+1).

Nordrunner
fire
11spoons uses Data Raven to initiate a trace with strength 3 (3 + 0 ) (Add 1 power counter).
Nordrunner spends 2  to increase link strength to 3.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses Adonis Campaign from Server 1.
Nordrunner pays 3  to trash Adonis Campaign from Server 1.
Nordrunner spends  and 2  to remove 1 Tag .
Nordrunner is ending their turn 10 with 8  and 5 cards in their Grip.
11spoons started their turn 11 with 6 and 5 cards in HQ.
11spoons spends 5  and  to play Hedge Fund.
11spoons uses Hedge Fund to gain 9 .
11spoons spends  to install a card in Server 1.
11spoons spends  to gain 1 .
11spoons is ending their turn 11 with 11  and 4 cards in HQ.
Nordrunner started their turn 11 with 8  and 5 cards in their Grip.
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to make a run on Archives.
11spoons spends 4  to rez Spiderweb.
Nordrunner jacks out.
Nordrunner spends  and 3  to install Daily Casts.
Nordrunner spends  and 2  to install The Turning Wheel.
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 11 with 6  and 5 cards in their Grip.
11spoons spends 2  to rez Public Support.
11spoons started their turn 12 with 5 and 4 cards in HQ.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons is ending their turn 12 with 8  and 5 cards in HQ.
Nordrunner started their turn 12 with 6  and 5 cards in their Grip.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Earthrise Hotel to draw 2 cards.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to make a run on HQ.
11spoons spends 5  to rez Hive.
Nordrunner uses Datasucker to give -1 strength to Hive.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses The Cleaners from HQ.
Nordrunner steals The Cleaners and gains 3 agenda points.
nullpointer joined the game as a spectator.
Nordrunner accesses Prisec from the root of HQ.
11spoons spends 2  to use Prisec to do 1 meat damage and give the Runner 1 tag.
Nordrunner trashes Career Fair due to damage.
Nordrunner pays 3  to trash Prisec from the root of HQ.
Nordrunner spends  and 2  to remove 1 Tag .
Nordrunner spends  to gain 1 .
Nordrunner spends  to gain 1 .
Nordrunner trashes Special Order from their Grip.
Nordrunner is ending their turn 12 with 3  and 5 cards in their Grip.
11spoons adds Hive to HQ and gains 5 .
11spoons started their turn 13 with 6 and 5 cards in HQ.
11spoons spends  to draw a card.
11spoons spends 3  and  to play Punitive Counterstrike.
11spoons uses Punitive Counterstrike to initiate a trace with strength 5 (5 + 0 ) (Do meat damage equal to the number of agenda points stolen last turn).
Nordrunner spends 0  to increase link strength to 1.
11spoons uses Punitive Counterstrike to do meat damage equal to the number of agenda points stolen last turn.
Nordrunner trashes Temüjin Contract, "Freedom Through Equality", Temüjin Contract due to damage.
11spoons does 3 meat damage.
11spoons spends  and 1  to install ICE protecting HQ.
11spoons is ending their turn 13 with 2  and 5 cards in HQ.
Nordrunner started their turn 13 with 3  and 2 cards in their Grip.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target HQ.
Nordrunner spends  to draw a card.
Nordrunner spends  to draw a card.
Nordrunner spends  to make a run on HQ.
11spoons spends 2  to rez Bailiff.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons uses Bailiff to gain 1 .
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Desperado to gain 1 .
Nordrunner uses Security Testing to gain 2  instead of accessing.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner spends  to draw a card.
Nordrunner is ending their turn 13 with 7  and 5 cards in their Grip.
11spoons started their turn 14 with 1 and 5 cards in HQ.
11spoons uses Public Support to add it to their score area as an agenda worth 1 agenda point.
11spoons spends  to install a card in Server 1.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons is ending their turn 14 with 3  and 5 cards in HQ.
Nordrunner started their turn 14 with 7  and 5 cards in their Grip.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  to draw a card.
Nordrunner spends  and 1  to install Gang Sign.
Nordrunner spends  to play Rebirth.
Nordrunner uses Rebirth to change identities.
Nordrunner NOTE: passive abilities (Kate, Gabe, etc) will incorrectly fire if their once per turn condition was met this turn before Rebirth was played. Please adjust your game state manually for the rest of this turn if necessary.
Nordrunner is ending their turn 14 with 8  and 5 cards in their Grip.
11spoons started their turn 15 with 3 and 5 cards in HQ.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons spends  to install a card in HQ.
11spoons is ending their turn 15 with 5  and 5 cards in HQ.
Nordrunner started their turn 15 with 8  and 5 cards in their Grip.
Nordrunner uses Daily Casts to gain 2 .
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  and 2  to install Kati Jones.
nullpointer left the game.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 15 with 9  and 5 cards in their Grip.
11spoons started their turn 16 with 5 and 5 cards in HQ.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons spends  and 2  to install ICE protecting Server 1.
11spoons is ending their turn 16 with 5  and 5 cards in HQ.
Nordrunner started their turn 16 with 9  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to draw a card.
Nordrunner spends  to gain 1 .
Nordrunner trashes Datasucker from their Grip.
Nordrunner trashes Desperado from their Grip.
Nordrunner is ending their turn 16 with 10  and 5 cards in their Grip.
11spoons adds Hive to HQ and gains 5 .
11spoons started their turn 17 with 10  and 6 cards in HQ.
11spoons spends 10  and  to play Restructure.
11spoons uses Restructure to gain 15 .
11spoons spends 10  and  to play Restructure.
11spoons uses Restructure to gain 15 .
11spoons spends  and 1  to install ICE protecting R&D.
11spoons is ending their turn 17 with 19  and 4 cards in HQ.
Nordrunner started their turn 17 with 10  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  to play Drive By.
Nordrunner exposes Jackson Howard in Server 1.
Nordrunner uses Drive By to trash Jackson Howard.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner is ending their turn 17 with 10  and 5 cards in their Grip.
11spoons started their turn 18 with 19  and 4 cards in HQ.
11spoons spends  to draw a card.
11spoons spends  and 3  to install ICE protecting Server 1.
11spoons spends  to install a card in Server 1.
11spoons is ending their turn 18 with 16  and 4 cards in HQ.
Nordrunner started their turn 18 with 10  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  and 1  to install Gang Sign.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 18 with 10  and 5 cards in their Grip.
11spoons started their turn 19 with 16  and 4 cards in HQ.
11spoons spends 1  and  to play Oversight AI.
11spoons uses Oversight AI to rez Curtain Wall at no cost.
11spoons rezzes Curtain Wall at no cost.
11spoons spends  to draw a card.
11spoons spends  to gain 1 .
11spoons is ending their turn 19 with 16  and 5 cards in HQ.
Nordrunner started their turn 19 with 10  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner spends  to gain 1 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 19 with 13  and 5 cards in their Grip.
11spoons adds Curtain Wall to HQ and gains 14 .
11spoons started their turn 20 with 30  and 6 cards in HQ.
11spoons spends  and 3  to install ICE protecting Server 1.
11spoons spends  and 4  to install ICE protecting Server 1.
11spoons spends  to gain 1 .
11spoons is ending their turn 20 with 24  and 5 cards in HQ.
Nordrunner started their turn 20 with 13  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends  and 3  to install Mongoose.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 20 with 11  and 5 cards in their Grip.
11spoons started their turn 21 with 24  and 5 cards in HQ.
11spoons trashes a card in Server 1.
11spoons spends  to install a card in Server 1.
11spoons spends  to gain 1 .
11spoons spends  to gain 1 .
11spoons is ending their turn 21 with 26  and 5 cards in HQ.
Nordrunner started their turn 21 with 11  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to draw a card.
Nordrunner spends 5  and  to play Sure Gamble.
Nordrunner uses Sure Gamble to gain 9 .
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 21 with 16  and 5 cards in their Grip.
11spoons started their turn 22 with 26  and 5 cards in HQ.
11spoons rezzes Jackson Howard.
11spoons removes Jackson Howard from the game.
11spoons uses Jackson Howard to shuffle Restructure, Restructure, Jackson Howard into R&D.
11spoons spends  to install a card in Server 1.
11spoons spends  and 1  to advance a card in Server 1.
11spoons spends  and 1  to advance a card in Server 1.
11spoons is ending their turn 22 with 24  and 5 cards in HQ.
Nordrunner started their turn 22 with 16  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends  to use Kati Jones to gain 21 .
Nordrunner spends  to make a run on R&D.
11spoons spends 5  to rez Hive.
Nordrunner uses Datasucker to give -1 strength to Hive.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses an unseen card from R&D.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner spends  to gain 1 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 22 with 36  and 5 cards in their Grip.
11spoons started their turn 23 with 19  and 5 cards in HQ.
11spoons spends  and 1  to advance a card in Server 1.
11spoons spends  and 1  to advance a card in Server 1.
11spoons spends  and 1  to advance a card in Server 1.
11spoons trashes a card from their HQ.
11spoons is ending their turn 23 with 16  and 5 cards in HQ.
Nordrunner started their turn 23 with 36  and 5 cards in their Grip.
Nordrunner uses Security Testing to target Archives.
Nordrunner spends 2  and  to play Dirty Laundry.
Nordrunner uses Datasucker to give -1 strength to Hive.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses an unseen card from R&D.
Nordrunner accesses an unseen card from R&D.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner uses Dirty Laundry to gain 5 .
Nordrunner spends  to draw a card.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner spends  to gain 1 .
Nordrunner is ending their turn 23 with 37  and 5 cards in their Grip.
11spoons started their turn 24 with 16  and 5 cards in HQ.
11spoons scores High-Risk Investment and gains 3 agenda points.
Nordrunner uses Gang Sign to access 1 card from HQ.
Nordrunner accesses BOOM! from HQ.
Nordrunner pays 1  to trash BOOM! from HQ.
Nordrunner accesses Crisium Grid from the root of HQ.
Nordrunner uses Gang Sign to access 1 card from HQ.
Nordrunner accesses Scorched Earth from HQ.
Nordrunner accesses Crisium Grid from the root of HQ.
Nordrunner uses Gang Sign to access 1 card from HQ.
Nordrunner accesses Hedge Fund from HQ.
Nordrunner accesses Crisium Grid from the root of HQ.
11spoons spends  to use High-Risk Investment to gain 36 .
Nordrunner uses Leela Patel: Trained Pragmatist to add ICE protecting Server 1 at position 4 to HQ.
11spoons spends  and 4  to install ICE protecting Server 1.
IzzyIqbal joined the game as a spectator.
11spoons spends 5  and  to play Hedge Fund.
11spoons uses Hedge Fund to gain 9 .
11spoons is ending their turn 24 with 52  and 4 cards in HQ.
Nordrunner started their turn 24 with 36  and 5 cards in their Grip.
Nordrunner uses Security Testing to target HQ.
Nordrunner spends  to make a run on HQ.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner jacks out.
Nordrunner spends  to make a run on HQ.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner jacks out.
Nordrunner spends  to make a run on HQ.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner jacks out.
Nordrunner spends  to use Kati Jones to store 3 .
Nordrunner is ending their turn 24 with 36  and 5 cards in their Grip.
11spoons started their turn 25 with 52  and 4 cards in HQ.
11spoons spends  to draw a card.
11spoons spends  to install a card in Server 1.
11spoons spends  to draw a card.
11spoons trashes a card from their HQ.
11spoons is ending their turn 25 with 52  and 5 cards in HQ.
Nordrunner started their turn 25 with 36  and 5 cards in their Grip.
Nordrunner uses Security Testing to target HQ.
Nordrunner spends  to make a run on HQ.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner jacks out.
Nordrunner spends  to make a run on HQ.
Nordrunner places a power counter on The Turning Wheel.
Nordrunner jacks out.
Nordrunner spends  to make a run on R&D.
Nordrunner uses Datasucker to give -1 strength to Hive.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
Nordrunner uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
Nordrunner uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses an unseen card from R&D.
Nordrunner accesses an unseen card from R&D.
Nordrunner steals High-Risk Investment and gains 3 agenda points.

Nordrunner
oops return remote card please
11spoons moves a card from their Server 1 to HQ.
Nordrunner accesses an unseen card from R&D.
Nordrunner accesses an unseen card from R&D.
Nordrunner spends  to make a run on Archives.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons has no further action.
Nordrunner continues the run.
Nordrunner spends 1  to use Corroder to break 1 barrier subroutine.
11spoons uses Bailiff to gain 1 .
11spoons has no further action.
Nordrunner continues the run.
11spoons has no further action.
Nordrunner uses Temüjin Contract to gain 4 .
Nordrunner uses Desperado to gain 1 .
Nordrunner accesses Shock! from Archives.
11spoons uses Shock! to do 1 net damage.
Nordrunner trashes Dirty Laundry due to damage.
Nordrunner is ending their turn 25 with 37  and 4 cards in their Grip.
11spoons started their turn 26 with 53  and 6 cards in HQ.
11spoons spends 2  and  to play SEA Source.
11spoons uses SEA Source to initiate a trace with strength 39 (3 + 36 ) (Give the Runner 1 tag).

Nordrunner
nice

Nordrunner
gg

11spoons
gg
Nordrunner spends 0  to increase link strength to 0.
11spoons uses SEA Source to give the Runner 1 tag.
11spoons spends 3  and  to play Scorched Earth.
11spoons uses Scorched Earth to do 4 meat damage.
Nordrunner trashes The Turning Wheel, Desperado, Passport, Corroder due to damage.
11spoons spends 3  and  to play Scorched Earth.
11spoons uses Scorched Earth to do 4 meat damage.
Nordrunner trashes due to damage.
Nordrunner is flatlined.
11spoons wins the game.

11spoons
I'm going to fill out the bug report, btw

11spoons
on the gang sign letting you access my crisium grid

Nordrunner
ya

Nordrunner
ive noticed that

Nordrunner
not cool
IzzyIqbal disconnected.

Nordrunner
thanks for the game

11spoons
ty as well
Nordrunner left the game.
!11spoons uses a command: /rez-all
11spoons rezzes Crisium Grid at no cost.
11spoons rezzes Curtain Wall at no cost.
11spoons rezzes Hive at no cost.
11spoons rezzes Hive at no cost.
11spoons rezzes Data Raven at no cost.
11spoons rezzes Curtain Wall at no cost.
11spoons rezzes Data Raven at no cost.

**Comment by JoelCFC25** [comment]
Not to worry, this was previously reported at #2113, and the fix has gone in at #2131 but is not yet live on the server. It will be after the next restart.
