### ISSUE TITLE
Parasites disappear

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#214]
Played with Chaos Theory and every Parasite I used on 0 strength ICE (2 Yaguras) disappeared from the game. Not in heap or in stack.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The Parasite code automating the ICE trashing was quite buggy and caused all sorts of problem. It has been removed so now the ICE has be trashed manually but at least it shouldn't have ill effects anymore.
