### ISSUE TITLE
Card selection lists have no text

### ISSUE THREAD

**Issue by rubyfell** [mtgred/netrunner#2144]
When a card is played that creates a list of cards from which to select, e.g. Self-Modifying Code, Deja Vu, Same Old Thing, the list is displayed, but the buttons making up the list have no text.

This affected games both yesterday and today. I have done hard refreshes several times. 

I am running Chrome Version 53.0.2785.143 (64-bit) on MacOS.

**Comment by JoelCFC25** [comment]
There has been a restart--is this still happening?

**Comment by JoelCFC25** [comment]
Pretty sure this was a temporary glitch when Intervention updates were occurring. If it was still happening we'd have heard about it by now.
