### ISSUE TITLE
Harishchandra Ent. + Salem's Hospitality + Mumbad City Hall

### ISSUE THREAD

**Issue by benhosp** [mtgred/netrunner#2146]
I got an error while trying to play Salem's Hospitality via Mumbad City Hall with the Runner's grip revealed by Harishchandra Ent.

(Haven't tried it without the runner's hand revealed or without Mumbad City Hall, so I don't know if those interactions are red herrings...)
![screen shot 2016-11-05 at 1 42 44 pm](https://cloud.githubusercontent.com/assets/8769601/20032320/69e782f6-a35e-11e6-9c3f-09df9eaab82d.png)

**Comment by JoelCFC25** [comment]
The stack trace would be especially helpful...

**Comment by JoelCFC25** [comment]
Can't reproduce in my development environment, but haven't tried on the live server yet.

**Comment by JoelCFC25** [comment]
Now that there has been a restart, can you try again and see if you still get this error?

**Comment by benhosp** [comment]
If clicking the "report on github" button was supposed to post the stack trace, you should know that that button seemed to redirect to a broken link...

**Comment by JoelCFC25** [comment]
Thanks--the link is generated here: https://github.com/mtgred/netrunner/blob/master/src/cljs/netrunner/gameboard.cljs#L130

URL:  https://github.com/mtgred/netrunner/issues/new?body=

At least at this moment it appears to be working. Maybe a temporary connectivity hiccup?
