### ISSUE TITLE
Targeted Marketing Server Error

### ISSUE THREAD

**Issue by raegar** [mtgred/netrunner#2148]
When playing Targeted Marketing the pop-up appears to enter the name of the card to select and allows you to filter the selection but once selected the page pops up a red textbox with "Your last action caused a game error on the server" and you cannot proceed.

**Comment by JoelCFC25** [comment]
This sounds like the same as #2146, and it's not happening for me in dev, so I think this is a temporary glitch related to a snafu that occurred during the process of setting Intervention cards as legal. I expect it'll go away after the next restart.

**Comment by JoelCFC25** [comment]
Now that there has been a restart, can you try again and see if you still get this error?
