### ISSUE TITLE
Jinteki: Personal Evolution ID ability firing twice when Agenda is stolen

### ISSUE THREAD

**Issue by mvelic** [mtgred/netrunner#2149]
Played a game on 11/6/16 - I was playing Jinteki: PE versus Geist. Whenever the runner stole an agenda, PE's ID ability would fire twice in a row. I didn't capture the whole game state, but I do have a screenshot of the prompt asking me the resolution order.

I can tell you that the Geist deck was the standard build, and it had Film Critic in play. Neither player could conclude why it was firing twice.

![image](https://cloud.githubusercontent.com/assets/1065914/20038768/356cabf6-a407-11e6-9dd5-7f1dc1c8c4bd.png)

**Comment by mvelic** [comment]
Attempted a second game/test (against Andromeda), and the ID ability worked as per normal. Could not replicate.

**Comment by JoelCFC25** [comment]
Let's chalk this up to the latency gods, since there have been no follow-on reports. If it somehow crops up again repeatedly, we can reopen or make a new issue.
