### ISSUE TITLE
Gauntlet not allowing access of more than 1 card

### ISSUE THREAD

**Issue by karmaportrait** [mtgred/netrunner#2150]
Gauntlet prompts to ask how many ICE on HQ all subs were broken on but runner does not access greater than 1 card.
Reproduced multiple times, selecting 1 or 2 as number of ICE with all subs broken.

**Comment by JoelCFC25** [comment]
Confirmed, thanks for the report.

**Comment by JoelCFC25** [comment]
This one turned out to be pretty easy. The effect needs to be wrapped inside a `resolve-ability`--`target is `:hq`, not the number the Runner chooses. Further, it would probably be better to have Gauntlet not even ask if the run has a replacement effect (i.e. no access will occur at all).
