### ISSUE TITLE
Preview cards by hovering on title in chat (or on accesses)

### ISSUE THREAD

**Issue by GordonsBeard** [mtgred/netrunner#216]
Whenever you access something that does not require any interaction (like Hedge Fund), the only thing that's displayed is: "You accessed Hedge Fund".

If a user wishes to know what Hedge Fund is, they need to open up a separate tab and look up the card, which is technically against the rules. It would be nice to be able to hover over the text "Hedge Fund" (or any card text in chat) and have the card preview image appear where the card preview images normally appear.

**Comment by nealterrell** [comment]
This is a good idea. It would require a lot of work to retool all printouts of card titles, but it's doable.
