### ISSUE TITLE
identical card trashed multiple times during HQ access with Disposable HQ

### ISSUE THREAD

**Issue by gsalinas** [mtgred/netrunner#2161]
Runner runs on HQ; I have 3 Jacksons in hand and Disposable HQ installed in the Root.
Runner accesses card from hand first; it's Jackson, and they trash it. Then accesses upgrade, triggering Disposable, and I try to bottom an agenda and one of the other two Jacksons, but they end up trashing all 3 from hand.

In another game they seemed to get an extra HQ access during the resolution of Disposable, as well.

**Comment by lostie** [comment]
I've tried to replicate the issue you described without success :/

Could you provided more detailed information about what other cards were in play on both Runner and Corp side, was the Runner using any run abilities, etc.

**Comment by gsalinas** [comment]
Afraid not :/

if anyone's worked on Disposable HQ since I posted this I'd assume it got fixed in an earlier change to how it functioned.
