### ISSUE TITLE
Mumbad Virtual Tour Effect Extended

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#2162]
A run on a server with an unrezzed Mumbad Virtual Tour led to a force trash on both the upgrade and an asset in the server.

![screenshot 3](https://cloud.githubusercontent.com/assets/14100935/20242894/09452868-a90d-11e6-9159-329820e71d44.png)

The corp reinstalled the asset, but after access, I was forced to trash it again despite the lack of the upgrade.

![screenshot 8](https://cloud.githubusercontent.com/assets/14100935/20242885/c9461830-a90c-11e6-8819-c1190b756af3.png)

**Comment by JoelCFC25** [comment]
Thanks for the report. MVT's use of `:when-unrezzed` is obsolete, I missed updating this card in #2130. It needs to be `:when-inactive` instead.
