### ISSUE TITLE
Enhancment Medium & Paperclip

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#2166]
First off It's great that medium now allows us to access less cards than the total amount of counters now. This is just a small annoyance but it would be great if the little drop down box started at the highest value rather than at 0. As it's just more clicking to get access's when doing multi runs and am sure 99% of the time people want to access as many cards as they can.

Could we get something similar as the buff to strength off ICE like that of other breakers for paperclip, maybe one for strength & one for subs so it can be just click on which ever is highest?

**Comment by nealterrell** [comment]
The Medium list is supposed to start at the max, but there was a broken deploy. I don't know if the fix has gone up yet, but you can try refreshing your cache. Either way, we hear ya, that's how we want the card to work.

We don't accurately track the # of subroutines on ice, particularly in cases where an ice has multiple instances of the same subroutine... so automating Paperclip in the way you suggest won't be possible for the near future.

**Comment by JoelCFC25** [comment]
> It's great that medium now allows us to access less cards than the total amount of counters now
Actually it's been possible to do this for several months now, but it was a real hack job and was occurring at the wrong place in the timing structure.

**Comment by PinkWarrior** [comment]
I see well thanks for letting me know
