### ISSUE TITLE
Misusing Blockade Runner

### ISSUE THREAD

**Issue by CarterJohns** [mtgred/netrunner#2168]
After using Blockade Runner, I clicked Sneakdoor Betta in my hand instead of in the list. This installed Sneakdoor Beta, then I clicked Sneakdoor Beta in the list in hopes of fixing it. At that point the game seemed to crash. I was no longer able to interact with the game or type in the chat, and when I left the game and rejoined as a spectator it did not appear. Thanks for the awesome work you guys!

**Comment by JoelCFC25** [comment]
There is an ancient closed issue that I can't find right now that was basically this same thing. If you click a card in hand instead of using the UI presented, it'll go all kinds of haywire. I'm not sure how this would easily be prevented.

**Comment by nealterrell** [comment]
Blockade Runner should use a targeting prompt, not a choices just.

**Comment by JoelCFC25** [comment]
I think I did a choices because it would be possible with the targeting prompt for the Runner to simply not put a card back into the stack. But we could live with that I guess, and already do elsewhere.
