### ISSUE TITLE
Old Hollywood Grid vs Gang Sign

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2169]
I had Old Hollywood Grid installed and rezzed on HQ, scored an agenda, runner fired Gang Sign and was apparently forced to steal an agenda from HQ with it. Later during a regular run on HQ, Old Hollywood Grid did function as expected, denying the steal on an accessed agenda.

**Comment by JoelCFC25** [comment]
Thanks for the report. OHG is currently coded in a way that only works for agenda accesses occurring during runs.
