### ISSUE TITLE
Personal Workshop & Beth KRC stopped working mid game

### ISSUE THREAD

**Issue by FightingWalloon** [mtgred/netrunner#2170]
I was playing a game yesterday. I mistakenly clicked on Femme from my HQ and installed her when I meant to host her on Personal Workshop. I dragged the card back to my HQ, reset my clicks and credits, and then tried to click on Personal Workshop to host her. The game would not let me do that. The card brought up the menu to host her card, but when I clicked on it nothing happened.

After my next turn started, it let me then host Femme on PW. But I noticed that it no longer processed the bonus click that I should have gotten from Beth KRC. The next turn when I tried to use PW at the start of my turn remove a counter from Femme, it also would not allow that.

The game ended shortly after this.

**Comment by JoelCFC25** [comment]
> I mistakenly clicked on Femme from my HQ and installed her when I meant to host her on Personal Workshop.

Did you give a response to the "Choose an ICE" prompt that Femme brings up when it gets installed? If you ignored this--or responded to it after dragging FF back to your hand--that is very likely the cause of the problems.

**Comment by FightingWalloon** [comment]
Great question. I do recall, but that is likely the issue. I remember doing some stuff with 'close-prompt.' 
Glad to know it was user error and not a problem with the program.
