### ISSUE TITLE
Jackson shuffle issue when targeting 0 cards (presumably SMC is similar)

### ISSUE THREAD

**Issue by jbrz** [mtgred/netrunner#2171]
When using Jackson to shuffle for 0 (on a run following Indexing, though presumably it doesn't matter), I tried to Jackson, selecting 0 cards.  Now AFAIK, that should still shuffle, unless I'm just flat out wrong about the rules.  It didn't.  Presumably this happens with other targeted shuffle effects when maybe it shouldn't (SMC only one that comes to mind at the moment for me).

By all means, tell me I'm an idiot if I'm wrong.

**Comment by JoelCFC25** [comment]
Thanks--we've known for a long time that it gets this wrong, but it just got lost in the shuffle of a zillion other things. It's good to have an actual issue for it.

**Comment by JoelCFC25** [comment]
Adding a `:cancel-effect (req (shuffle! state side :deck))` inside the `resolve-ability` of the `rfg-and-shuffle-rd-effect` function seems like it might do the trick.

**Comment by JoelCFC25** [comment]
I don't know how to handle implementing the case of "failing to find" with SMC. Adding a `:cancel-effect` to shuffle is no good because it prevents the payment of the 2 credits and trashing of the card altogether.
