### ISSUE TITLE
Silhouette expose and HQ access log

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2173]
(I have searched the existing issues, and think this is what #1585 relates to, not sure if always been an issue or recently become broken.)

When Silhouette runs HQ and exposes a Psychic Field:

The log displays the exposure;
The log displays the upcoming card accessed from HQ;
A prompt waits to resolve the Psychic Field.

Now, the HQ access doesn't *resolve* until the Psychic Field game and any subsequent damage resolve, but the accessed card shouldn't even be known until the psi game is over and damage resolved. Knowledge of the card about to be accessed could give extra information to a player when deciding what to bid on the psi game/whether to prevent damage.

**Comment by JoelCFC25** [comment]
This looks like an ordering issue in the `msg-handle-access` function in core/runs.clj

The title of the card(s) is written to the game log before `handle-access` is even called.
