### ISSUE TITLE
Employee Strike didn't auto-trash when runner scores an agenda

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#2174]
Layout of the board right before trash:
https://puu.sh/sudDw/bde5e7a239.png

Runner scored High-Risk Investments (no trash of ES)

**Comment by JoelCFC25** [comment]
This is not a bug. Employee Strike is a Runner current. Runner currents are trashed with **the Corp** scores an agenda. Runners do not score agendas, they _steal_ them.

**Comment by domtancredi** [comment]
Of course. Ugh, misinterpreted the rule.
