### ISSUE TITLE
Bug with Plan B after Medical Breakthrough & Mushin No Shin

### ISSUE THREAD

**Issue by JimRoepcke** [mtgred/netrunner#2175]
From my friend who doesn't have or want a GitHub account:

> Using Firefox 49.0.2 on fully patched Ubuntu Linux 14.04.
> 
> Playing as Corporation, I had already scored one Medical Breakthrough agenda (https://netrunnerdb.com/en/card/05005) which states:
> "Lower the advancement requirement of each Medical Breakthrough by 1." I have found that this effect is implemented correctly in jinteki.net when subsequent Medical Breakthrough agendas are scored independently.
> 
> However, with another Medical Breakthrough sitting in my hand, I used Mushin No Shin (https://netrunnerdb.com/en/card/05015) to install a Plan B asset (https://netrunnerdb.com/en/card/05023) with 3 agenda counters on it. The runner accessed the Plan B asset on their turn and I was prompted by Plan B to select the agenda in my hand to score. It would not allow me to score the Medical Breakthrough agenda in my hand (the second one) with only 3 agenda counters on Plan B.
> 
> I did try manually adding another agenda counter to Plan B and having the runner access it again and this time it did score the second Medical Breakthrough - but with 4 agenda counters. So it appears that Plan B does not recognize that previous Medical Breakthroughs have been scored and to adjust the number of required agenda counters accordingly. Other "regular" agendas appear to be scored correctly by Plan B.

**Comment by JoelCFC25** [comment]
Thanks for the report. Plan B will have to check if the targeted agenda has `:advancement-cost-bonus`, maybe. I won't have time to try this until tonight.
