### ISSUE TITLE
"Showing Off" event not working with Medium (Or multiple Mediums)

### ISSUE THREAD

**Issue by Phyraga** [mtgred/netrunner#2177]
Currently, when you use the access ability of Showing Off, instead of accessing cards from the bottom of RND upwards, it just accesses from the top anyway.

**Comment by JoelCFC25** [comment]
Thanks for the report. The code in Showing Off pre-dates all of the `when-completed` framework and a recent change to the access code that was necessary to support improved (and more technically correct) Medium/Nerve Agent functionality. 

This card probably needs to register event handlers to reverse the order of the deck as a delayed completion effect at `:successful-run` and then reverse it back at `:run-ends`.
