### ISSUE TITLE
Magnet ICE not making hosted Parasite (when directly installed onto it) blank

### ISSUE THREAD

**Issue by Phyraga** [mtgred/netrunner#2178]
Parasite was still fully interacting with Magnet when directly installed onto. Gained a counter, and was also trashing Magnet when Null's ID ability was used to lower the ICE's STR to zero.

**Comment by JoelCFC25** [comment]
Thanks--we knew about this one but it got lost in the shuffle. Good to have an issue for it.

**Comment by Phyraga** [comment]
No worries, thought I'd report this and the Showing Off bugs to try do my part!
