### ISSUE TITLE
using Hades shard  on R+D run doesn't count for Obelus-Draw

### ISSUE THREAD

**Issue by ANR-PeterPan** [mtgred/netrunner#2180]
My opponent used Hades Shard on a R+D run (Medium with 0 counters installed too) and only draw one card automaticly (ten cards in archives at this moment, only 6 in stack left).

**Comment by JoelCFC25** [comment]
Thanks--we are aware that this use case doesn't work (it only recently became popular). It's going to require some really ugly hacks to support. Use the `/draw` console command after the run as a workaround.
