### ISSUE TITLE
Shipment from Kaguya doesn't work on ICE Woodcutter

### ISSUE THREAD

**Issue by ANR-PeterPan** [mtgred/netrunner#2181]
As we know that placing an advancement token on a card isnt the same as advancing itself it should work.
I don't know if it is the same issue with Tyrant or Salvage, but I think so.

**Comment by JoelCFC25** [comment]
It's correct that placing an advancement token is not the same as advancing a card, but Shipment from Kaguya's very text stipulates that the target must be a card that "can be advanced". So an unrezzed Woodcutter, per its own text--"can only be advanced when rezzed"--is not an eligible target.
