### ISSUE TITLE
Find the Truth + Top Hat interaction

### ISSUE THREAD

**Issue by discarded** [mtgred/netrunner#2183]
If the first successful run of the turn is on R/D, the prompt for Top Hat triggers first, whereas  you would want to trigger Find the Truth to know whether to use Top Hat.

**Comment by JoelCFC25** [comment]
Thanks for the report. Adding `:interactive (req true)` to the successful run event handler for both of these cards will let you choose the order of resolution.

**Comment by discarded** [comment]
Cheers for your work. Glad it's an easy fix
