### ISSUE TITLE
Implement Reaver

### ISSUE THREAD

**Issue by shazzner** [mtgred/netrunner#2184]
Please implement Apex's latest card Reaver. I implemented the code myself but as I don't have contributor rights, I'm unable to create a pull request.

`"Reaver"
   {:events {:runner-trash {:req (req (and (first-event state :runner :runner-trash) (:installed target)))
                     :effect (effect (draw :runner 1))
                     :msg "to draw 1 card"}}}`

**Comment by JoelCFC25** [comment]
You would need to clone this repository, create a new branch in your own repo with the code, and then you could submit the PR from that.

**Comment by JoelCFC25** [comment]
On a related note, was discussing this card in Stimhack Slack this morning, and most people think it's meant to trigger on "first time this turn" trash of a Corp card as well, the FFG news article notwithstanding. That would square with the text as written, too. I guess it will remain to be seen--but the 4 influence rating would make more sense that way. Historically the FFG news articles have been shot through with rules errors and other flat-out wrong references.

**Comment by nealterrell** [comment]
Either way, we encourage you to follow the "typical" GitHub workflow and take official credit in the git logs for your submission. Fork this project. Clone it to your desktop. Implement the code in your repo, sync to GItHub upstream, and then submit a Pull Request :).

**Comment by shazzner** [comment]
Created PQ, apologies for getting back to this so late!
