### ISSUE TITLE
Paige Piper/Frantic Coding interaction

### ISSUE THREAD

**Issue by sperry023** [mtgred/netrunner#2190]
Although I have not seen it confirmed, it appears that Paige Piper and Frantic Coding have the same interaction as Accelerated Beta Test and The Foundry: During resolution of Frantic Coding (install), Paige Piper will trigger and the shuffle away the other 9 cards you looked at, saving them from the heap. Currently, the other cards are being trashed.
![paige frantic](https://cloud.githubusercontent.com/assets/13188311/20871600/5a35908c-ba65-11e6-9972-90e0c59e26a5.png)

**Comment by JoelCFC25** [comment]
U-G-H.

**Comment by nealterrell** [comment]
Seriously. Ugh.

**Comment by nealterrell** [comment]
I dreamed about this issue last night and may have a solution, which may turn out to be the incoherent ramblings of my unconscious mind. We'll see.

**Comment by JoelCFC25** [comment]
> I dreamed about this issue last night

This is a cry for help, everyone.

**Comment by kevkcc** [comment]
lmao... should make sure it's the proper interaction before fixing though

**Comment by nealterrell** [comment]
I expect this to be the correct interaction based on the ABT/Foundry ruling.
