### ISSUE TITLE
Opponent ID, deck, discard in middle of screen

### ISSUE THREAD

**Issue by FightingWalloon** [mtgred/netrunner#2193]
I've only had this when watching games, but the cards for ID, deck, and discard are showing up in the middle of the screen rather than at the top. Cards they play appear above them rather than below them.
[Jinteki.pdf](https://github.com/mtgred/netrunner/files/634572/Jinteki.pdf)

I'm using Chrome and have updated the source code.

**Comment by JoelCFC25** [comment]
Thanks--this is getting fixed in #2191.
