### ISSUE TITLE
Problem with New Backgrounds.

### ISSUE THREAD

**Issue by MontyWhittaker** [mtgred/netrunner#2194]
Since I changed backgrounds, I haven't been able to start games, even after refreshing. My game begins, but I get no prompt to keep or mulligan my hand.
![screen shot 2016-12-06 at 12 10 26 pm](https://cloud.githubusercontent.com/assets/17957733/20937625/5205dfd6-bbad-11e6-8356-36b7608f0a0e.png)

**Comment by JoelCFC25** [comment]
What browser are you using? If Chrome, do you have Jankteki running?

**Comment by MontyWhittaker** [comment]
I had been using Chrome, with Jankteki. I thought I had disabled Jankteki, but after looking at it again, I think I had just "hidden" it. After truly disabling it, it works now. Sorry about that.
