### ISSUE TITLE
Saving a new deck doesn't refresh the deckbuilder list

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#2198]
To replicate:

1. Click "New Corp deck"
2. Click "Save"

Expected result: Deck shows up on the list
Actual result: Deck does not show up in the list

**Comment by FightingWalloon** [comment]
Was having same problem. Deck does show up after refreshing the browser with Ctrl + f5.

**Comment by domtancredi** [comment]
Now works with latest update!
