### ISSUE TITLE
No easy way to remove agenda counters once placed

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#22]
Trick of Light and Exploratory Romp are hard to work with because once an item has agenda counters on it, there's no easy way to remove them.

Interestingly, moving the item back to HQ and re-installing it causes it to be re-installed with the same number of agenda counters it had when it was picked up (possibly an unrelated bug).  Moving the item to Archives, then to HQ, and then re-installing it results in it having zero agenda counters, as intended, and allows for a manual work-around.

**Comment by JoelCFC25** [comment]
Trick of Light now works. Exploratory Romp is completely unimplemented for now. A recent fix has taken care of the problem of advancements being retained when something is brought back to HQ and then reinstalled. 

Exploratory Romp won't be too bad of a card to do, I think.

**Comment by JoelCFC25** [comment]
I'm close on Exploratory Romp--removal of advancement works, but I'm still trying to get it to neatly close out the run instead of giving another prompt.

**Comment by queueseven** [comment]
Fixed with #605
