### ISSUE TITLE
Using Null's ability on ice hosting Parasite crashes the game

### ISSUE THREAD

**Issue by Evilpyro25** [mtgred/netrunner#2201]
Expected result: Parasite hosted on ice with 2 strength. Null makes a run on the server with this ice, and trashes a card from grip to lower the strength of the ice by 2, firing parasite and trashing the ice.

Actual result: Null makes a run on the same server described above, and trashes a card from grip. The game then locks up, and "choose a card to trash" prompt does not disappear (even after /close-prompt). /jack-out or /end-run does nothing, and the corp cannot manually trash (i.e. click and drag). Chat displays heavy lag. Cards trashed in the encounter show up in archives and heap, but cannot be interacted with.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is happening in my development environment as well.
