### ISSUE TITLE
Targeted Marketing unable to select valid Runner cards

### ISSUE THREAD

**Issue by Oniya** [mtgred/netrunner#2202]
I've had a couple of games last night where I played Targeted Marketing going to specify Account Siphon or Blackmail. The options that appeared as I was trying to input data seemed to only be from the Flashpoint cycle and even included some Corp cards.

**Comment by JoelCFC25** [comment]
Thanks--we are aware that this is currently broken, hence the note in the top item of the News header. Expect it to work normally again after the next restart.

**Comment by JoelCFC25** [comment]
Working again.
