### ISSUE TITLE
Parasite: Hivemind, Ice Wall

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#221]
Parasite's interactions with Hivemind and Ice Wall/Fire Wall are broken. Parasite doesn't use the bonus counters on Hivemind for its trash effect, and it also does not take into account Ice Wall and Fire Wall's +strength counters when deciding to trash them.

**Comment by nealterrell** [comment]
Just adding on: NEXT Bronze too.

**Comment by nealterrell** [comment]
Curtain Wall, Gutenberg, Crick, Meru Mati, Turing, Wraparound.

**Comment by mtgred** [comment]
Draco and IQ too.

There is currently no code for handling ICE strength which is problematic with Parasite.

Cards like Datasucker, Ice Carver, Stronger Together, Experimental Data are also not taken into account.

I guess It's better to remove the trash code from Parasite until ICE strength is properly implemented.

**Comment by nealterrell** [comment]
I think I can make this happen with a :strength function in card defs and a core function to use it when available.

**Comment by mtgred** [comment]
Sure go ahead :)

**Comment by nealterrell** [comment]
I'm making good progress on this and have one question.

In card-init, we have:

    (resolve-ability state side cdef c nil)
    (when-let [events (:events cdef)]
      (register-events state side events c))

Is the order of these two statements (run the card's `:effect`, then register the card's `:events`) important? I am working on Superior Cyberwalls, and would like its `:effect` (when scored) to trigger an updating of all rezzed Barrier strengths. In order to do that, it needs to handle a new event I created... but with the order of code above, the event won't have been registered by the time the agenda's effect is run. By reversing the order I can fix Superior Cyberwalls, but I don't know if that will break anything else. Can you think of cards/systems that rely on this order, where a card's effect is executed with the knowledge that its events are not yet registered?

**Comment by nealterrell** [comment]
Also, how do you feel about showing an ICE's current strength in orange like is done with pumped icebreakers, if the current strength is not the same as the base strength? I did this on accident but kind of like it. So a Curtain Wall will show an orange 10 over its strength icon if it is the outermost piece of ice; or no orange number if it is not on the outside. Effects from Datasucker, Superior Cyberwalls, ICE Carver, etc. also show orange strength numbers if the total effect leaves the ICE at a non-base strength

**Comment by konradhildebrand** [comment]
To add, the same problem is also with Shadow - Parasite does not see counters on it.

**Comment by nealterrell** [comment]
Thanks Konrad, I submitted a fix for all the ice mentioned in #232 including Shadow, and it looks like that went live this morning. Let us know how it looks :).
