### ISSUE TITLE
Unable to chat, create games, or join games

### ISSUE THREAD

**Issue by brettwilliams** [mtgred/netrunner#2211]
Since the restart I am unable to send chats (though I can see the discussion).  I can only see private games, and cannot create games.  I have tried chrome and edge on windows (and cleared browsing data for chrome), chrome and firefox on OSX.

All give me the same problem.  I can see in the main chat that two other people are having the same issue, but I'm unable to discuss it with them.  They apparently are able to join on a different machine (I am not).

**Comment by yehaaa6** [comment]
also unable to join, see a majority of games, or chat. doesn't work on Firefox or Chrome in Windows 10. I tried disabling IPv6 as per someone's suggestion on the main chat, but that doesn't seem to have worked.

**Comment by JoelCFC25** [comment]
The [provider seems to be having isolated service disruptions](https://www.cloudflarestatus.com/), which might explain why it's working for some people but not all. Not sure if anything can be done short of waiting for them to patch it all up.

**Comment by sazmer** [comment]
Same for me. 
Throws error: Uncaught TypeError: zF.Md is not a function(…) when trying to create game and a similar one trying to chat. Thinking maybe its referring to another js-file with that function and the pointers off due to caching issues..

**Comment by kevart** [comment]
I've disabled all browser extensions, cleared my cache refreshed the page, logged out and in, updated Chrome (Version 55.0.2883.87 (64-bit))

but getting `Throws error: Uncaught TypeError: zF.Md is not a function(…)` too.

**Comment by deimos2020** [comment]
I can see people chatting in the general chat and the such but in the play tab i cant see any games

**Comment by cyberewok** [comment]
Having exactly the same issues as OP. Tried on Firefox, Chrome and IE after clearing cache refreashing and logging in or out. Also have tried on multiple internet connections just in case router/ISP is caching or routing weirdly. On windows located in Australia currently if that information is somehow relevant.

**Comment by sazmer** [comment]
Working again for me!

**Comment by brettwilliams** [comment]
And for me as well, after a forced refresh this morning.

On Sun, Dec 11, 2016 at 7:34 AM, Samuel Henriksson <notifications@github.com
