### ISSUE TITLE
After accessing Sapper, the Runner accesses an additional card

### ISSUE THREAD

**Issue by Oniya** [mtgred/netrunner#2212]
I've noticed in a couple of games that if the Runner accesses Sapper from HQ (not sure about R&D) the Runner gets to access an additional card. This happens whether or not the runner trashes Sapper.

**Comment by JoelCFC25** [comment]
Was the Sapper subroutine allowed to fire in all cases?

**Comment by JoelCFC25** [comment]
I see the problem. If the Runner responds to the "Trash Sapper?" prompt before the Corp player completes the "trash a program" prompts, the extra prompt appears.
