### ISSUE TITLE
Incorrect double access on HQ

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#2213]
Playing as Kit, made a run on HQ, used Peregrine to break, de-rez a firewall and then had a successful run.

First access was Sapper, which fires from HQ. I let it fire, and didn't trash it. The successful run button came up again, and it let me access a 2nd card from HQ.

**Comment by JoelCFC25** [comment]
Thanks--duplicate of #2212. We'll diagnose and track progress in that issue. For the time being, don't hit Successful Run when you are shown this extra prompt, hit Jack Out instead.

**Comment by agileminor** [comment]
Agreed - looks like he beat me in reporting the issue by 17 seconds! :)
