### ISSUE TITLE
Double credit on Net Mercur during first run

### ISSUE THREAD

**Issue by TugtetguT** [mtgred/netrunner#2218]
The fist time on your run when you spend a stealth credit if you also click Net Mercur BEFORE you decide whether to "put 1 credit on NM/draw 1 card" and pick credit option the NM will gain 2 credits.

It's probably not an "actual" bug since you're supposed to decide NM option immediately after you spend the first stealth credit, but it is quite subtle and easy to miss this during the tension of the game.

**Comment by danhut** [comment]
Can you give me exact steps? I played around with this but could only get NM to take one credit.

**Comment by TugtetguT** [comment]
Yes of course.

Imagine you run:


This is your second run, so your recurring stealth credits are gone, but there's plenty on NM.


1st encounter is a sentry which you need 2 stealth credits to break, you have 3 credits on NM.


(clicks with the mouse)

Click NM

Click NM


________________________________
Fra: danhut <notifications@github.com>
Sendt: 20. januar 2017 10:54:08
Til: mtgred/netrunner
Cc: TugtetguT; Author
Emne: Re: [mtgred/netrunner] Double credit on Net Mercur during first run (#2218)


Can you give me exact steps? I played around with this but could only get NM to take one credit.

-

**Comment by TugtetguT** [comment]
Got that sent off prematurely...


Okay the scenario is this:


Imagine you have no recurring stealth credits, but there's plenty on NM.

You run and encounter a sentry, which you need 2 stealth credits to break, there is have 5 credits on NM.

(clicks with the mouse)
Click NM
Click NM
Click boost and/or break

Click boost and/or break (Pretend it's switchblade)

Click add 1 stealth credit on the prompt for NM - this should make NM go back up to 5. (1 too many)


The important part is that you take several credits off of NM before you click the prompt. The more you take the more extra credits go on NM.


It works perfectly if you click the prompt before taking your second NM credit, but it's quite natural to take the amount of credits you need from NM, before you do anything else, which is what creates the bug.


Btw it doesn't occur only on the first run, but any run on which you click NM several times before clicking the prompt.

It's a minor bug, but it's easy to miss when you play, I've done it several times before noticing.


Hope this helps!


Best regards :)

Asger - TugtetguT



________________________________
Fra: Asger Sloth
Sendt: 21. januar 2017 11:34:17
Til: mtgred/netrunner
Emne: Sv: [mtgred/netrunner] Double credit on Net Mercur during first run (#2218)


Yes of course.

Imagine you run:


This is your second run, so your recurring stealth credits are gone, but there's plenty on NM.


1st encounter is a sentry which you need 2 stealth credits to break, you have 3 credits on NM.


(clicks with the mouse)

Click NM

Click NM


________________________________
Fra: danhut <notifications@github.com>
Sendt: 20. januar 2017 10:54:08
Til: mtgred/netrunner
Cc: TugtetguT; Author
Emne: Re: [mtgred/netrunner] Double credit on Net Mercur during first run (#2218)


Can you give me exact steps? I played around with this but could only get NM to take one credit.

-
