### ISSUE TITLE
Find the Truth and Omar Keung order

### ISSUE THREAD

**Issue by commissarfeesh** [mtgred/netrunner#2219]
Using Omar's ability with Find the Truth installed should allow Find the Truth to trigger before deciding which server to redirect to. Currently You are forced to pick the server first. Similar to the Top Hat issue which was fixed previously, imagine the fix will also be similar.

**Comment by JoelCFC25** [comment]
This will actually be quite complex to tackle, because Omar Keung's effect comes at `:pre-successful-run` (skipping boring technical details) and Find the Truth comes at `:successful-run`.

**Comment by commissarfeesh** [comment]
Ah, didn't realise. Hope a fix is possible as it's quite a potentially potent combo.

**Comment by nealterrell** [comment]
Your interpretation actually is not correct. Omar Keung is a constant ability, whereas Find the Truth is a triggered ability. Constant abilities always take precedence over triggered abilities; you only get to "choose the order" when the types of the abilities are the same. 

This is the reason why you also cannot install Temujin on Archives, do an Omar run on Archives, resolve Temujin on successful run first (taking money) and then switch to another server. Omar must resolve first, and by the time Temujin resolves you are no longer on Archives.

See [this blog post by Jakodrako](http://ancur.wikia.com/wiki/User_blog:Jakodrako/Ability_Types_and_Resolution_Primer).

**Comment by commissarfeesh** [comment]
Fair point! Genuinely misinterpreted the interaction there, had Omar pegged as a triggered ability when the run was successful, but I can see that you're correct. No need for any change then :)
