### ISSUE TITLE
MaXXX and Motivation

### ISSUE THREAD

**Issue by Meronim** [mtgred/netrunner#2220]
Dear Developers,

Today I found a bug which is the following:
If I play MaXXX - Maximum Punk Rock and play Motivation, then at the beginning of the turn Motivation always triggers first. I'd like to trigger MaX's ability first, then motivation, but the game doesn't let me do it.

I would be very grateful if you could fix this bug.

Thank you: Meronim

**Comment by JoelCFC25** [comment]
Thanks for the report! This can be easily accommodated by adding `:runner-draw true` and `:runner-phase-12` as flags to Motivation.

**Comment by Meronim** [comment]
Could you alert me when the changes are on? :)

**Comment by JoelCFC25** [comment]
When restarts occur to deploy new cards and changes, a News header update goes in describing things.

**Comment by Meronim** [comment]
thank you
