### ISSUE TITLE
Net Mercur + Advanced Concept Hopper (or any other corp decision)

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2221]
It's possible to have both players prompts waiting for the other player. For example, the runner makes a run (ACH fires, corp is shown the options, runner is shown the message about waiting for corp to make a decision), then if the runner takes a stealth credit, firing Net Mercur before the decision is made, corp gets the message about runner deciding on Net Mercur, but runner also can't make a decision because the ACH decision message is still shown. This is quite easily solved by doing /close-prompt on either side if it's not an easy fix, but figured it's worth a report regardless.

**Comment by nealterrell** [comment]
Well that's cute. Not sure how to resolve this one...

**Comment by ouroboros8** [comment]
Prevent the player who's waiting for their opponents' action from interacting with the game?

**Comment by Saintis** [comment]
This feels like a standard "don't click things while waiting on the other player" case.
