### ISSUE TITLE
Account Siphon incorrectly gives money before tags can be avoided.

### ISSUE THREAD

**Issue by james-scott-meta** [mtgred/netrunner#2228]
Scenario: a runner makes an Account Siphon run on an undefended HQ (surprise Hayley Siphon!) with one credit in the bank and New Angeles City Hall on the field. After using the run ability, they have 11 credits in the bank and the interface asks them if they want to avoid tags, at which point they can use NACH's tag avoidance to pay 4 and go down to 7 credits post-run.

This behavior is incorrect, as the runner should not be able to use their ill-gotten credits until after the opportunity to avoid tags has passed, as per the FAQ: http://ancur.wikia.com/wiki/FAQ_1.2.18

**Comment by nealterrell** [comment]
Working on this.
