### ISSUE TITLE
Multiple Daily Business Show is Wrong

### ISSUE THREAD

**Issue by bdorfman** [mtgred/netrunner#223]
It prompts you multiple times to put cards underneath, but it gives you the wrong options after the first which can lead to you having an extra card and no way to manually fix it. 

E,g, I drew A B and C. It asked whether i wanted to put card A or B on the bottom and I said A. Then it asked A or C (isntead of B or C) and I said A again. Now B and C are both in my hand.

**Comment by nealterrell** [comment]
I submitted a fix for this in #224. Thanks for the report.

**Comment by JoelCFC25** [comment]
When this gets closed out, the previous bug report for stacking DBS (#129) can get closed out as well.
