### ISSUE TITLE
Having issue when using Peregrine 

### ISSUE THREAD

**Issue by Chrisyang1155** [mtgred/netrunner#2232]
While using Peregrine, I clicked the add 3 strength, but it returned to my hand and derezzed the ice sometimes.

**Comment by JoelCFC25** [comment]
Are you double-clicking, by chance?

**Comment by Chrisyang1155** [comment]
I don't think so.  I only click once, and this happened 3 times today.  The log didn't show I spend 3 to add 3 strength.  Peregrine just went back my hand and derezzed DNA Tracker twice and Ravana 1.0 once.

**Comment by Chrisyang1155** [comment]
![aaa](https://cloud.githubusercontent.com/assets/6079074/21211293/557dd58a-c2bd-11e6-855d-a92dc17dbd41.png)

I found the problem.  When there is a "Match strength of __" command, the Break sub command became add strength, and the add strength command became derezzed.

**Comment by Chrisyang1155** [comment]
And every breakers have the same problem.

**Comment by erbridge** [comment]
This is likely to be an indexing issue. The auto pump is added separately from the other abilities (I think), so I wouldn't be surprised if the wrong ability index is passed to the backend.
