### ISSUE TITLE
Rumor Mill + trashable "as 2 agenda points" executives

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#2241]
Rumor Mill is only applying to installed Corp cards right now, when it should apply equally to cards in R&D or HQ. Thus, the Runner is wrongly getting the trashable execs as 2 agenda points if Rumor Mill is active and the Runner trashes one of these from R&D or HQ.

**Comment by kyzen** [comment]
Hi, I'm a new contributor and I'll be submitting a pull request for this today
