### ISSUE TITLE
Unable to close archives late in the game

### ISSUE THREAD

**Issue by RotomAppliance** [mtgred/netrunner#2243]
In several of my corp games in the last few days, I've found myself unable to close the archives window, even though the "close" button is still appearing. 

This seems to only happen late in the game, making me think it occurs when archives reaches a certain size. 

As the archives window is fairly large and covers alot of the playing area, it makes it very difficult to continue the game, as most of the corp board is obscured, and any new menus you try to bring up (say JHow) appear under the archives window. 

Apologies if mentioned already somewhere, couldn't see it.

**Comment by NorwegianLegion** [comment]
When running into this issue, I just use Zoom function on my browser. Then I can close the archives window.

**Comment by erbridge** [comment]
I think there are two usability improvements to be had here:

1. Clicking archives should toggle the popup, so you should be able to close it by clicking archives again.
2. The popup should have a maximum size, after which it becomes scrollable.

Regarding the actual issue, do you know if this happens when the popup is large enough to spread to the runner's side of the board?

**Comment by RotomAppliance** [comment]
@NorweiganLegion, zooming didn't make any difference. The archives window still covered exactly what it did before, and still wouldn't close. 

@erbridge, that's a possibility. It covers most of my board, but it might be just at the point where it's reaching the runner board too.

**Comment by stoppableforce** [comment]
It doesn't seem to be related to size, in my experience; it's the same issue that was causing people to be unable to click a menu item if it overlapped a card. Figured this out when the second half of "Close" on my heap window was between two of the corp's servers, miraculously. I was able to click the 'se' to close it, but not the 'Clo' that overlapped an installed card.

This is the bug that won't die, seemingly.

**Comment by danhut** [comment]
What I can see as the issue - the cards on the board have a style applied .gameboard .counters which has a z-index (depth) of 10.  If I turn this to zero then the Close button is perfectly clickable.

If I try to give the Close button which is part of the popup a higher z-index via CSS it still cannot be clicked so not sure what is going on - but certainly the above works.

.gameboard .popup a {
    display: inline-block;
    margin: 0 10px 8px 4px;
    z-index: 120;

**Comment by erbridge** [comment]
That's interesting. The popup should be above the counters by virtue of having `z-index: 20`. Are actually seeing the counters overlayed on top of the popup?

**Comment by danhut** [comment]
No they are underneath.  I tried this in both Chrome and Firefox on a Mac.  Worth noting it is a laptop (recent) so less screen real estate.  

I have a runner with hardware, programs, and resources so make them come down the screen.

Then dump a ton of corp stuff in the bin and open the window.  Gets very hard to select "Close" as the pointer seems to be interacting with the underlying card.

I did note that the Hyperlink element that contains "Close" does not seem to see the z-index at all - here is output from inspector:

```
element.style {
}
<style>…</style>
.gameboard .popup a {
    display: inline-block;
    margin: 0px 10px 8px 4px;
}
<style>…</style>
a {
    text-decoration: none;
    color: rgb(255, 165, 0);
    cursor: pointer;
    transition: all 0.2s ease-in-out;
}
<style>…</style>
* {
    box-sizing: border-box;
}
Inherited from div.item.active
<style>…</style>
#main .carousel-inner .item {
    padding-top: 31px;
    height: 100%;
    color: rgb(255, 255, 255);
}
<style>…</style>
.active {
    color: rgb(255, 165, 0);
    transition: all 0.2s ease-in-out;
}
Inherited from body
Style Attribute {
    cursor: default;
}
<style>…</style>
body {
    color: rgb(51, 51, 51);
    background-color: rgb(0, 0, 0);
    font-family: "Titillium Web", "Helvetica Neue", sans-serif;
    font-size: 13px;
    line-height: 18px;
}


```
I applied z-index by changing the source code but still no good.  But I won't claim to understand front-end much.

Some research below - but I fixed all this and still no good.
Quote"
The z-index attribute can only be used on positioned elements (absolute, relative or fixed). "
[(http://stackoverflow.com/questions/7245896/link-using-z-index-cant-be-clicked-even-though-its-on-top-in-both-firefox-i)]

**Comment by erbridge** [comment]
Do you think you could post a screenshot of a board state that causes the issue? Before and after would be great. Thanks.

**Comment by danhut** [comment]
<img width="1268" alt="noissue-closeclickable" src="https://cloud.githubusercontent.com/assets/11830223/21962508/981ebef0-db7b-11e6-815c-935b443f9b92.png">
<img width="1264" alt="withissue-cannothitcloseeasily" src="https://cloud.githubusercontent.com/assets/11830223/21962509/981f82ae-db7b-11e6-95c7-af0e8ae937fd.png">

**Comment by lostie** [comment]
I had exactly the same problem several times, and I've only managed to get rid of it by going into inspect mode and modify the CSS of the block
