### ISSUE TITLE
London Library + On the Lam funny interaction

### ISSUE THREAD

**Issue by lostie** [mtgred/netrunner#2244]
At the moment, it seems that the _condition_ of London Library to trash any **programs** at the end of the Runners turn does not take into account the **type** of card **hosted**, at least I've ran into a funny interaction where I've hosted On the Lam on London Library and at the end of my turn, On the Lam was trashed :D

**Comment by JoelCFC25** [comment]
Yep, this card by far pre-dates the concept of hosting something other than a program on it. Just needs more precision in the `:runner-turn-ends` event.

**Comment by lostie** [comment]
🏆
