### ISSUE TITLE
Issue with clicking cards after using Endless Hunger

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#2246]
Used Endless Hunger to break a subroutine on Quandry to get into a remote server, after passing 1 piece of unrezzed ice. Server had a SanSan and a Melange Mining in it. Game told me to click on cards to access, but wouldn't let me click on anything. I jacked out, re-did the run and then it let me click.

But then the click issue continued for the rest of the game. Using heartbeat, I couldn't select cards to trash to prevent meat damage. Once, it wouldn't let me install a card facedown at the start of the turn as Apex, etc.

Board state:
Corp was NBN making news. They had 2 ice on R&D (1 rezzed data raven, one un rezzed), 1 unrezzed ice on HQ, no ice on Archives, no other remotes. They had 1 breaking news scored

I was Apex. Had Endless Hunger/Heartbeat/E3/Harbinger out and 2 facedown installed cards. No agendas scored on runner side.

**Comment by JoelCFC25** [comment]
Thanks for the *very* detailed reproduction steps and board setup. I am not able to reproduce this on an initial attempt, but this "can't click on cards in remote" sounds awfully similar to part of the problems reported in #2242.

**Comment by JoelCFC25** [comment]
Did you have On the Lam installed at any point?

**Comment by agileminor** [comment]
Had to think about this one. I didn't have it installed face up, but it was probably one of my face down Apex installed cards at some point. Can't be 100% sure, but I didn't need it in the match up so I would have used it to feed Apex's cards.

**Comment by JoelCFC25** [comment]
If you still have this deck, it might be worth trying again now that On the Lam has been fixed. Even if you were feeding it to Apex as a facedown card it still might've been screwing with things.
