### ISSUE TITLE
Successful run / Jackout both stuck after accessing agenda with the source + Leela

### ISSUE THREAD

**Issue by triorph** [mtgred/netrunner#2248]
![image](https://cloud.githubusercontent.com/assets/20156553/21333262/78b1e254-c6b3-11e6-8383-cfbf791028b7.png)

I was Andromeda rebirthed into Leela and I forgot to Dr Lovegood my copy of the source, so I had to pay 3 to steal the agenda, and then I triggered Leela before I triggered the source. I was unable to click on the R&D ice, and then the prompt was stuck on "Successful Run" and "Jack Out" and there seemed to be no way to fix this. Similarly if I clicked Successful run it actually let me access an additional card.

**Comment by JoelCFC25** [comment]
We've determined On the Lam to be the root cause here. Still trying to figure out why or what to do about it.
