### ISSUE TITLE
Trashing Medium during the access phase with Sapper causes infinite accesses

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2249]
Game was Weyland: BoN vs Quetzal, with only a Medium installed with around 6 counters. Quetz player hit the Sapper during access, W player trashed Medium, accesses continued as expected but then never stopped.

**Comment by JoelCFC25** [comment]
Have a suspicion that this could be related to #2212, for which a fix is pending.

**Comment by JoelCFC25** [comment]
This should be fixed now, although Sapper needs one more tweak to not fire at all if the Runner has no programs installed, otherwise the Runner will have to use the console command to dismiss a wait prompt.
