### ISSUE TITLE
On the Lam + Leela

### ISSUE THREAD

**Issue by pandamannoah** [mtgred/netrunner#2252]
When playing as Leela when I install On the Lam things start to get wonky. 

The two most pronounced issues are Leela bounces no longer work (No response when clicking on cards to bounce no matter how many times I click or how long I wait, have tried waiting up to 1-2 minutes) and similarly when accessing a remote server with more than one card in it I get no response when clicking on cards in that server to access them. I've had to work around by asking my opponent to manually bounce/trash cards at these times. Bounces seem to work again after On the Lam is trashed but I haven't been able to test the accessing cards out of remotes bug after trashing On the Lam.
The minor issues just seem to be general slowness and a bug where after successful runs where an agenda is stolen the menu will stick on "successful run"/"jack out" and clicking either will cause triggered events to happen but will not cause a successful run or will not let you actually jack out. Only solution I've found is to have opponent do a "/end-run" command. Then, the interface gets more sluggish after installing On the Lam and seems to miss more inputs, having to click on make a run more than once to get the menu to open up for instance.

**Comment by JoelCFC25** [comment]
For whatever reason, On the Lam seems to be the cause for this issue, as well as #2248 and #2242. I am reproducing it now, so thanks for this key piece of info--but it's not throwing exceptions in the game server, and isn't producing Javascript errors on the front end, so I'm stumped for now.
