### ISSUE TITLE
Hunting Grounds + Reaver

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2253]
If you have any number of Reavers installed while popping Hunting Grounds, HG will not install the full 3 facedown cards. Rather it will be (3 - number of Reavers).

**Comment by JoelCFC25** [comment]
Thanks for the report. `(take 3 (:deck runner))` needs to become: `(take 3 (get-in @state [:runner :deck]))`

**Comment by artturipi** [comment]
Awesome. This has been a real pain when playing Apex, to the extent that I've been avoiding the interaction. Looking forward to unleashing the full potential. :)
