### ISSUE TITLE
Remove Tag - button missing

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2254]
It seems like the latest update may have gotten rid of the tag removal action button. Did not find it in the usual place during a game when I was tagged, anyhow.

**Comment by JoelCFC25** [comment]
So far most people seem to be solving this with just a forced refresh.

**Comment by tolaasin** [comment]
This hasn't worked for me, even after a forced refresh.

**Comment by JoelCFC25** [comment]
Thanks all--we've found the problem. Hopefully getting a "pants on fire emergency" patch out today.
