### ISSUE TITLE
Run arrow positioning is off

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#2255]
Run arrow positioning is off, now that it's _position: relative_

Solution is to use specific positioning, or refactor to be position: absolute

From this commit:
https://github.com/mtgred/netrunner/commit/3c77a8ef13efd25a9f0b3a37627b362c45b76a27

**Comment by erbridge** [comment]
Alternative solution is #2240, which also deals with the fact that the arrow covers ice menus.
