### ISSUE TITLE
No Horizontal Scrolling on Firefox

### ISSUE THREAD

**Issue by Priyome** [mtgred/netrunner#2261]
At some point in the last three days I lost the ability to scroll horizontally. Normally this isn't that problematic, but when there is a long row of servers, resources, hardware, or programs, my screen aligns with the outermost one and I lose the ability to interact with any cards or command buttons that are not in the frame of view.

**Comment by zaroth** [comment]
Did you update your firefox version during this period/install any addons?

**Comment by Priyome** [comment]
I did not update firefox at all during this time, or install any addons. I'm running version [48.0.2] since that is the last supported build on my machine. 

Thank you all for the work you put into the development and upkeep of jinteki.net
