### ISSUE TITLE
Old Hollywood grid blocking all agenda steals (maybe +Blackmail issue?)

### ISSUE THREAD

**Issue by rajgiriUW** [mtgred/netrunner#2262]
In a recent game Old Hollywood Grid was rezzed, Runner Blackmail'ed in and trashed it. Then Runner ran back in and could not steal the agenda (Atlas). Installing Atlas in a new server or archives did NOT stop the issue, they still could not steal.

This bug popped up in R&D access of a new Atlas and all other agendas (Sales Team and GFI) that could not be stolen.

I am not sure if Blackmail is the issue with the interaction as I've had other games without this issue popping up.

**Comment by JoelCFC25** [comment]
Thanks for the report--OHG was recently modified at #2235 to fix a different problem, so this is obviously an unintended side effect. 

Initially I wonder if `:post-access-card {:effect (effect (clear-persistent-flag! card :can-steal))}` should instead be: `:post-access-card {:effect (effect (clear-persistent-flag! target :can-steal))}`
