### ISSUE TITLE
Parasite not counting up

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#227]
I ran into a case today where my opponent had a parasite installed on one of my cards. It counted up a counter per turn untill it hit 2 then it stoped counting up.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The Parasite code automating the ICE trashing was quite buggy and caused other issues as well so it has been removed. Now the ICE needs to be trashed manually but at least it shouldn't break games anymore.
