### ISSUE TITLE
Hostile Infrastructure + Net Damage Prevention During Run

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#2275]
Opponent was IG with a Hostile Infrastructure and Breaker Bay Grid in a server. I ran on that server (with Imp and Deus X installed), Imped the Hostile Infrastructure, then went to trash the Breaker Bay Grid with money. After the access, we had a deadlock - I was trying to prevent net damage (from the first trash), but instead I was just given the "successful run / jack out" prompt, and my opponent was waiting for me to prevent net damage, so they couldn't let the run end. Clicking either "Successful run" or "Jack out" did nothing, and the prompt could not be closed with /close-prompt or /end-run. Basically, sad times.

This was on Firefox 50.1.0, but I feel like that doesn't matter here.

**Comment by JoelCFC25** [comment]
Thanks for the report. This is an Imp problem, specifically with the `trash-no-cost` and `resolve-trash-no-cost` functions. Curiously, the former declares `eid` in the `let` statement but then never uses it. These don't seem to support "when completed", so I've verified that you'll see this exact same problem if you Imp a card in any situation that would result in a Corp effect firing--e.g., Imp any installed card against NBN: Controlling the Message.

**Comment by finnbar** [comment]
Ahh, I see. I'm not doing very well at this "guessing what the cause of the bug is" game...
Also, it seems that "/jack-out" does work, which is weird considering the "Jack Out" button seems not to.

**Comment by nealterrell** [comment]
Jacking out works with the menu only if both players do not have an active prompt up. It's one of those legacy systems that I've been working to get rid of one day. 99% of "can't jack out" problems are because Corp has a prompt showing (typically a "waiting" prompt); if they `/close-prompt` you can usually jack out with the menu.

**Comment by nealterrell** [comment]
Should be good now.
