### ISSUE TITLE
Archives Interface Infinite Run - Cannot Jack OUt

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#2276]
When playing Whizzard I ran an empty archives with Archives Interface out. I clicked the option to remove a card from the game. This led to a Run is successful pop-up, which then reprompted me to pick the AI choice again. My Temujin emptied out additional times as well. /close-prompt and /end-run were not successful, but did log a run ended and prompt closed.

**Comment by JoelCFC25** [comment]
Thanks for the report. Archives Interface just needs a `not-empty` check of Archives before prompting.
