### ISSUE TITLE
Reaver + Hunting Grounds

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#2277]
Issue:

When Hunting Grounds trashes to install 3 cards face down, Reaver triggers first and confuses Hunting Grounds.

What ends up happening is that with Reaver you draw one (or two/three, depending on how many Reavers you have installed) of the cards that you were supposed to install face down via Hunting Grounds paid ability, and you install that many less cards face down.

I have reproduced this more than once, but the time I noticed it the most was when doing it on my opponent's turn to try to double down on Reaver/Wasteland "each turn" triggers.

**Comment by JoelCFC25** [comment]
Interesting. This should have been fixed by #2267, which I thought had gotten pushed out.

**Comment by JoelCFC25** [comment]
Discussed earlier today, the submitter was referring to what he'd seen a few days ago not knowing that this has been fixed.
