### ISSUE TITLE
Immolation Script + Archives Interface bug

### ISSUE THREAD

**Issue by kmcclean** [mtgred/netrunner#2281]
Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do choice Steal #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [clojure.lang.Numbers gt "Numbers.java" 3864]
  [game.core$steal$fn__6476 invoke "runs.clj" 46]
  [game.core$do_effect invokeStatic "abilities.clj" 260]
  [game.core$do_effect invoke "abilities.clj" 256]
  [game.core$do_ability invokeStatic "abilities.clj" 241]
  [game.core$do_ability invoke "abilities.clj" 214]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$trigger_event_simult invokeStatic "events.clj" 177]
  [game.core$trigger_event_simult doInvoke "events.clj" 139]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [game.core$steal invokeStatic "runs.clj" 42]
  [game.core$steal invoke "runs.clj" 36]
  [game.core$resolve_steal$fn__6490 invoke "runs.clj" 72]
  [game.core$effect_completed invokeStatic "events.clj" 240]
  [game.core$effect_completed invoke "events.clj" 236]
  [game.core$resolve_steal_events invokeStatic "runs.clj" 63]
  [game.core$resolve_steal_events invoke "runs.clj" 58]
  [game.core$resolve_steal invokeStatic "runs.clj" 70]
  [game.core$resolve_steal invoke "runs.clj" 65]
  [game.core$access_agenda$fn__6538 invoke "runs.clj" 172]
  [game.core$do_effect invokeStatic "abilities.clj" 260]
  [game.core$do_effect invoke "abilities.clj" 256]
  [game.core$do_ability invokeStatic "abilities.clj" 241]
  [game.core$do_ability invoke "abilities.clj" 214]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_ability invokeStatic "abilities.clj" 109]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$prompt_BANG_$fn__6007 invoke "abilities.clj" 309]
  [game.core$resolve_prompt invokeStatic "actions.clj" 145]
  [game.core$resolve_prompt invoke "actions.clj" 115]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__26829 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__26864 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment]
Can you indicate which cards you had active in your rig at the time?

**Comment by kmcclean** [comment]
Kati Jones, Black Orchestra, Archives Interface, and a Knight. It was an
Immolation Script run on archives.

**Comment by JoelCFC25** [comment]
Thanks. This is very likely a problem from the combination of Immolation Script and Archives Interface. I am seeing the prompts from these two cards getting interleaved. It would help if you could supply precisely the order in which you saw the prompts from these cards and how you responded to them.

**Comment by JoelCFC25** [comment]
I have Immolation Script and Archives Interface working on conjunction without errors now, but it's still not clear to me which of these should resolve first, and whether or not the Runner even has a choice. Can you use Archives Interface on a piece of ICE that wasn't in Archives originally but got there from resolving Immolation Script first?

**Comment by kmcclean** [comment]
Honestly, I have no clue. The runner get to choose which fires first, but I
don't know if that is included when determined Archives.


On Jan 2, 2017 2:50 PM, "Joel Koepp" <notifications@github.com> wrote:

I have Immolation Script and Archives Interface working on conjunction
without errors now, but it's still not clear to me which of these should
resolve first, and whether or not the Runner even has a choice. Can you use
Archives Interface on a piece of ICE that wasn't in Archives originally but
got there from resolving Immolation Script first?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mtgred/netrunner/issues/2281#issuecomment-270018912>,
or mute the thread

**Comment by nealterrell** [comment]
@JoelCFC25 I'm going to surmise that Archives Interface is supposed to go first always, as its trigger ("Whenever you access cards") seems to come before Immolation Script's ("Instead of accessing a piece of ice").

**Comment by JoelCFC25** [comment]
Crap.

**Comment by JoelCFC25** [comment]
Verdict from @jakodrako is in--Runner is meant to be able to choose the order of resolution. However, Archives Interface is not supposed to be able to a piece of ICE that arrives in Archives during access as a result of Immolation Script trashing it. That could be tricky.

**Comment by JoelCFC25** [comment]
@Saintis suggested just making all copies of Archives Interface resolve first, since they aren't allowed to target cards trashed by Immolation Script. So I should have a patch for this soon.
