### ISSUE TITLE
Rumor Mill + trashed Cybernetics Court

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#2282]
It looks like this is the only asset or upgrade affected by this...

If Rumor Mill is in play and suppressing the effect of a rezzed Cybernetics Court--reducing the Corp max hand size from 9 back to the standard 5--trashing the Court by any method (Runner paying to trash in a run, voluntary overwrite by Corp, or card effect like Product Recall) will result in the max hand size dropping by 4 again, even though the card's effect is nullified by Rumor Mill.

**Comment by kyzen** [comment]
Created pull request #2343  as potential fix
