### ISSUE TITLE
All resources unresponsive

### ISSUE THREAD

**Issue by dqaupop** [mtgred/netrunner#2283]
Midway through a game as runner, I suddenly found that I could not trigger any of my resources' paid effects. When I clicked on any of them, I got the notification "unable to pay for [insert resource]", the same one you get when trying to use an ability without enough clicks. I was unable to fix this problem and have no idea what might have caused it.

**Comment by nealterrell** [comment]
Unfortunately there's not much we can do with this. Next time a screenshot would be helpful; GitHub will even let you paste them into the issue box when writing your report.
