### ISSUE TITLE
Allow users to mark which Data Packs and Expansions they own

### ISSUE THREAD

**Issue by Saurbaum** [mtgred/netrunner#2284]
The reason for this is two fold.

Firstly to aid in building decks that you can build in meat space using the tools here.  Secondly to help you remember which sets you own when it comes time to buy more.

**Comment by JoelCFC25** [comment]
The deckbuilder here is intentionally bare-bones. A feature-rich deckbuilder is out of scope for the site, and there are other sites ([Meteor Decks](https://meteor.stimhack.com), [NetrunnerDB](http://www.netrunnerdb.com)) that do these things and many others already--and do them well.

**Comment by nealterrell** [comment]
As Joel said, this is not something we'll be implementing, as there are excellent options elsewhere.
