### ISSUE TITLE
Baba Yaga hosting functions erratically or stops functioning once 1 program is hosted

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#2285]
Have managed to replicate this reliably both in a real game and in testing, so I guess it's an actual bug.

Steps to replicate:

1. Install Baba Yaga (I do not believe the method of doing so matters, but I was installing it from my grip).
2. Click Baba Yaga and choose ":click: Install a non-AI icebreaker on Baba Yaga"; choose an icebreaker and install it (I was using Faerie, have since tested with Yog.0 and Breach). Faerie should be installed hosted on Baba Yaga.
3. Click Baba Yaga and choose the same option (have tested with Yog.0, Breach, and Faerie in grip, so there *are* valid targets). **No selection reticle or prompt will appear; in fact, nothing will happen. ** No error appears in the Javascript console. 
4. Install a second icebreaker (I have tested this part with both Yog.0 and Breach). Click Baba Yaga and choose "Host an installed non-AI icebreaker on Baba Yaga". **Usually, no selection reticle or prompt will appear; in fact, nothing will happen. However, sometimes, Baba Yaga will offer to install a non-AI icebreaker from your grip as if you had clicked the option from step 2 instead.** There does not seem to be any rhyme or reason I can discern as to when it will do the wrong thing instead of doing nothing.

I should add that the paid abilities on Baba Yaga seem to work fine - strength can be boosted and subroutines broken. It's just the hosting that seems to get screwed up.

**Comment by JoelCFC25** [comment]
#2273 fixes this, but it's not live yet.
