### ISSUE TITLE
SMC + Reaver issue 

### ISSUE THREAD

**Issue by YodaSensei** [mtgred/netrunner#2288]
I just had this weird problem playing with Self-Modifying Code and Reaver 
* I used SMC to fetch a program, I was prompted which program, and answered Cache 
* Reaver trigerred, and let me draw a card, which was the last Cache from the deck
* SMC effect failed and no program was installed, (and SMC cost was still paid)

If I understand the rules correctly, what should happen is 
* trash SMC, and draw from Reaver
* then select which program to deck from the remaining cards in the deck

edit : I had the same issue again with CyberCypher instead of Cache, I can add the following details 
* Jinteki assumed the fetched program was actually installed : cost was paid, and MU usage adjusted

**Comment by JoelCFC25** [comment]
Thanks for the report. All of what SMC is doing (including generating the list of choices) will need to be wrapped into a `resolve-ability` that occurs after the self-trash, so any copies of Reaver can do draws before determining what can be fetched from the Stack.

**Comment by artturipi** [comment]
Was about to post that SMC installs first and Reaver then draws, but I guess if it happens to draw the program you were about to install it will fail. Definitely worth fixing seeing how Reaver is seeing quite a lot of play in multiple decks.

**Comment by danhut** [comment]
Fix for this here 
[PR](https://github.com/mtgred/netrunner/pull/2337)
