### ISSUE TITLE
Multiple decks saved in deckbuilder makes UI unusable (very slow/unresponsive)

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2289]
A friend said he deleted all decks in and noticed a boost in UI speed. I did it too and the difference was massive, previously I had probably 100+ decks easily. The UI became more and more responsive after each deletion. My guess is the DOM becomes massive with many decks (even if it is all hidden on the Deck Builder tab) and all changes in the DOM (like changing visible buttons during gameplay) then take a lot of time to resolve. The site's been in use for such a long time that decks are starting to pile up for long time users and I'm sure I'm not the only one with this issue, there's also no clear indication why it's happening, so I think it can be quite frustrating (I know I'm definitely enjoying the game more now that every button press doesn't take a second to resolve).

**Comment by erbridge** [comment]
We should look at making it an infinite scroll, using e.g. https://github.com/seatgeek/react-infinite. It should be a relatively easy drop in replacement for the list container.

**Comment by JoelCFC25** [comment]
Related: #1505
