### ISSUE TITLE
Reaver/Wasteland requirements are slightly off

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2291]
"Wasteland"
   {:events {:runner-trash {:req (req (and (first-event state :runner :runner-trash) (:installed target)))
                     :effect (effect (gain :credit 1))
                     :msg "to gain 1[Credit]"}}}

Steps to reproduce:
Have Faust
Have Reaver/Wasteland
Have Spy Cam
Boost Faust Str
Trash Spy Cam
-> No trigger

This seems to be because runner trashing a non-installed card (via Faust, other options exist) is the first runner-trash event.

**Comment by JoelCFC25** [comment]
It's possible to pass `:suppress-event true` as an argument to a usage of `trash`--that might take care of the Faust instance, but I suppose there are dozens more (Freelance Coding Contract, etc).

**Comment by artturipi** [comment]
Hmm..it seems that Faust itself can trigger Reaver/Wasteland as well. Had this happen in a game now and I remember seeing it before, too. This seems weird, since the requirement does state that the target must be installed. This was during a run, but I can't recall what else was installed or what I trashed to Faust. Had a somewhat big rig and it was during a run. It definitely does not happen every time, though. Perhaps if it's the first card trashed and there's a copy installed? Or a copy installed face down? Maybe if it's an event that's trashed where "installed" doesn't have the same meaning (like...Dirty Laundry run going on, trashing Dirty Laundry?)

**Comment by JoelCFC25** [comment]
Is it right to describe a general rule that we would never want to record or having cards listen for a player trashing one of their own not-installed cards? Trying to resolve this without breaking anything else.

**Comment by artturipi** [comment]
Hmm...I don't think it's safe to assume it'll never be relevant, but with the current card pool I couldn't find a case where it would matter. I guess you can figure out the solution if/when FFG prints something that needs this.

**Comment by JoelCFC25** [comment]
If tracking the number of cards leaving the hand ever becomes important, that can be done by listening for the `:card-moved` event. 

> And I'm guessing IQ strength is tied to cards in HQ

Yes.

**Comment by JoelCFC25** [comment]
I didn't have any luck trying the solution I initially came up with--caused a whole bunch of existing tests to fail.
