### ISSUE TITLE
Account Siphon run "ends" too early to use Bad Publicity on New Angeles City Hall

### ISSUE THREAD

**Issue by dodgepong** [mtgred/netrunner#2292]
If the corp has 1 bad pub, and I have a NACH and 3 credits, and I Account Siphon an open HQ, I should have 4 credits (from the 1 bad publicity) to avoid both tags. However, when I click the "Run Ability" button to activate Account Siphon when the run is successful, the "run ends" sound plays and I lose the bad publicity from my credit pool before I have the chance to avoid tags via NACH. Somehow, the run is considered over before the decision to avoid tags has been made, thus losing the bad publicity credit too early.

**Comment by JoelCFC25** [comment]
Thanks--making Siphon's replacement effect `:delayed-completion true` will fix this.
