### ISSUE TITLE
Muertos Gang Member triggers when trashed while hosted

### ISSUE THREAD

**Issue by paholg** [mtgred/netrunner#2294]
If Muertos Gang Member is trashed while hosted (say, on Street Peddler) but not installed, the corp player is still given a prompt to rez for free.

**Comment by JoelCFC25** [comment]
Thanks for the report. `:leave-play` needs to be `:trash-effect` instead--not sure how I missed this one the last time I tidied up Tri-maf Contact and Rolodex.
