### ISSUE TITLE
Rumor Mill under Street Peddler still affects corp cards

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2297]
GitHub is having issues attaching the screenshot, but a player with Jackson Howard rezzed couldn't use him while a Street Peddler with Rumor Mill under it was in play. I'm guessing the same thing happens if Rumor Mill is installed face down via Apex or Hunting Grounds as well.

**Comment by JoelCFC25** [comment]
Remarkable...

**Comment by JoelCFC25** [comment]
What was the order of effects here? I just tried installing a Jackson but leaving him unrezzed, then as Runner playing a Peddler making sure Rumor Mill was one of the facedown cards. On the next Corp turn, rezzing Jackson and using him worked as expected.

**Comment by FarCryFromHuman** [comment]
Order was Street Peddler was already down, corp player installed Jackson, rezzed and attempted to use him on his turn.

**Comment by JoelCFC25** [comment]
Thanks. That does seem to be the difference, for reasons that make no sense whatsoever to me. For the record, if a Jackson is installed and rezzed _before_ Street Peddler hosts a facedown Rumor Mill, that Jackson will also work as expected.

**Comment by FarCryFromHuman** [comment]
What about a Jackson installed and rezzed after Rumor Mill is face down from Apex/Hunting Grounds?

**Comment by JoelCFC25** [comment]
> ChopBot, which the runner activated during the corp turn (I didn't realize this was possible either)
Not related to the issue at hand, but this is very easily fixed by adding `:req (req (:runner-phase-12 @state))` to Chop Bot's ability.

**Comment by JoelCFC25** [comment]
> What about a Jackson installed and rezzed after Rumor Mill is face down from Apex/Hunting Grounds?

Jackson works as expected in this case. Something is up with the hosting code.
