### ISSUE TITLE
Chysalis is worded poorly

### ISSUE THREAD

**Issue by xasil** [mtgred/netrunner#2299]
Doesn't really give the runner a proper window to break it. When it says 'allow chysalis to fire' I figured that might I was encountering it. Nope. It just auto did 2 net. Make it like Archangel.

**Comment by JoelCFC25** [comment]
You were encountering it. The message says "Allow Chrysalis subroutine to fire?". I thought that would be clear enough to indicate if you respond "Yes", you are going to be hit with 2 net damage. It already does work like Archangel except that the Corp does not get a decision on whether or not to trigger the encounter--it's required.

**Comment by JoelCFC25** [comment]
Maybe we should just change the message to:  "You are encountering Chrysalis. Allow subroutine to fire?"

**Comment by xasil** [comment]
Seems good.
