### ISSUE TITLE
No way for manual meat/net damage

### ISSUE THREAD

**Issue by Heartthrob-** [mtgred/netrunner#23]
Not sure about brain.

**Comment by queueseven** [comment]
Is there a situation where you need to manually do net-/meat- or brain damage? Are there any cards that would do damage that are not implemented?

**Comment by Heartthrob-** [comment]
Doubtful now, I need to go update these since they were submitted months ago. Thx for all the great work, jnet is amazing 

Spencer Healey
Marketing Communication Senior//
ProPay Inc. // A TSYS Company
spencer.healey@propay.com
801.227.9836
