### ISSUE TITLE
Multiple Daily Business Show Interaction

### ISSUE THREAD

**Issue by Kijdhefgi** [mtgred/netrunner#230]
When you have multiple Daily Business Shows installed, the unrezzed ones are counted as being rezzed as long as there is one rezzed.  I had two installed, one was unrezzed, and the next turn prompted me to draw three and discard two.
I don't really know much about Clojure so I doubt this will work, but I believe you'd just have to add a check to see if the cards you're filtering for are also rezzed.

    [dbs (->> (:corp @state) :servers seq flatten (mapcat :content)
    (filter #(= (:rezzed %) (filter #(= (:title %) "Daily Business Show"))) count)

**Comment by nealterrell** [comment]
Thanks for the report. Right idea with the suggested fix, but the right syntax would be

`(filter #(and (:rezzed %) (= (:title %) "Daily Business Show")))`
