### ISSUE TITLE
Accelerated Diagnostics + Draw is semi-buggy

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#2307]
This is kinda a strange interaction to begin with, but Accelerated Diagnostics technically does not remove cards from R&D, so if one of the cards you play is a draw card, it should first draw any cards in your AD pile that you did not play, and then from R&D.

For example (happened in a game yesterday). R&D is Reuse, CVS, Blue Level Clearance, Power Shutdown, Power Shutdown. AD fired hits Reuse + CVS + BLC. I play Reuse first, then BLC and 2x Power Shutdowns are drawn. Correct behaviour is to end the AD and draw the CVS and then 1 of the PS, leaving the other in R&D.

**Comment by nealterrell** [comment]
This is a known issue that has to be manually resolved for now.
