### ISSUE TITLE
Baba Yaga hosting already installed programs double charges you for installing

### ISSUE THREAD

**Issue by loafcast** [mtgred/netrunner#2308]
Hosting a program on Baba Yaga not directly from your grip causes the program to be treated as a fresh install on Baba Yaga. For example, when the following occurs:

1. Have both Baba Yaga and Self Modifying Code installed;
2. Fetch an icebreaker with Self Modifying Code, installing it;
3. Use the "host installed icebreaker..." function on Baba Yaga to host the newly installed icebreaker

The icebreaker is moved to being hosted by Baba Yaga, but is treated as a fresh install, while not forgetting about the previous install (that is, it charges you again for the install cost, and subtracts the associated MU, without freeing up the MU from the first install).

**Comment by JoelCFC25** [comment]
It needs the same extra line that Djinn and Scheherazade have to gain back the right amount of MU, offseting what gets deducted by runner-install.

**Comment by danhut** [comment]
Joel - I have a fix for this based on what you have above.  Hope you don't mind me taking it - trying to learn the project.  

I found another issue to look at which is the Click Baba Yaga and install from hand ability.  If I try to install Yog on it when I cannot pay for it - i still lose the click.
