### ISSUE TITLE
ABT + Hasty/24/7 News Cycle Bug

### ISSUE THREAD

**Issue by discarded** [mtgred/netrunner#2309]
I use Hasty Relocation to stack r&d with three big ice, then play 24/7 targeting ABT. The three ice go to the temp zone as normal, the first ice selected is installed and rezzed as normal, but then the last two are instantly shuffled into r&d.

This has happened three times in a row, on different days and against different opponents.  ABT fires normally when advanced and scored in the same games.

**Comment by JoelCFC25** [comment]
I tried this in my dev environment and successfully installed all 3 ICE. So at least on an initial attempt, I am not able to reproduce it.

**Comment by triorph-emacs** [comment]
You're not playing in the foundry are you?
