### ISSUE TITLE
[Feature suggestion] Pre-built core set decks

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#2313]
Over the years I've seen a lot of new players coming on to try Jnet. They're usually looking to play some core set games. So, I've been working on a few pre-built core set decks for some months now. Though I'm not sure if it's a good idea to have them as pre-builts on Jnet. FFG might not like it and all.

Here are the decks:
[Haas-Bioroid](https://netrunnerdb.com/en/deck/view/847842)
[Weyland](https://netrunnerdb.com/en/deck/view/847821)
[Criminal](https://netrunnerdb.com/en/deck/view/847855)
[Shaper](https://netrunnerdb.com/en/deck/view/847819)

Peace

**Comment by ZoeB** [comment]
For what it's worth, I agree with this.  I'd love to offer newcomers to the game to play online with me, and to help them out with their first few times playing it... but it'll put them off if, before they can even start to play a game, I have to explain how to make a deck.

It would be a small but very friendly amendment to add in the regular core set decks suggested by the manual, or perhaps [the one Stimhack recommends for beginners](https://stimhack.com/teaching-netrunner-on-the-fly/).  Something much simpler than the latest tournament winning decks, at any rate.

Thank you!

**Comment by ZoeB** [comment]
e.g. you could have https://www.jinteki.net/data/decks default to something like this:

`[{"name":"Core shaper","cards":[{"qty":3,"card":"Armitage Codebusting"},{"qty":3,"card":"Access to Globalsec"},{"qty":3,"card":"Crypsis"},{"qty":3,"card":"Sure Gamble"},{"qty":3,"card":"Infiltration"},{"qty":2,"card":"Sacrificial Construct"},{"qty":1,"card":"Aesop's Pawnshop"},{"qty":2,"card":"Pipeline"},{"qty":2,"card":"Net Shield"},{"qty":2,"card":"Magnum Opus"},{"qty":3,"card":"Gordian Blade"},{"qty":2,"card":"Battering Ram"},{"qty":1,"card":"The Toolbox"},{"qty":2,"card":"The Personal Touch"},{"qty":2,"card":"Rabbit Hole"},{"qty":2,"card":"Akamatsu Mem Chip"},{"qty":3,"card":"Tinkering"},{"qty":3,"card":"The Maker's Eye"},{"qty":2,"card":"Modded"},{"qty":3,"card":"Diesel"}],"identity":{"title":"Kate \"Mac\" McCaffrey: Digital Tinker","side":"Runner","code":"01033"},"date":"2017-02-24T22:05:09.365Z","username":"__demo__"},{"name":"Core Jinteki","cards":[{"qty":3,"card":"Priority Requisition"},{"qty":3,"card":"PAD Campaign"},{"qty":2,"card":"Chum"},{"qty":3,"card":"Enigma"},{"qty":1,"card":"Akitaro Watanabe"},{"qty":2,"card":"Precognition"},{"qty":2,"card":"Neural EMP"},{"qty":3,"card":"Nisei MK II"},{"qty":3,"card":"Wall of Thorns"},{"qty":3,"card":"Neural Katana"},{"qty":2,"card":"Hunter"},{"qty":1,"card":"Zaibatsu Loyalty"},{"qty":3,"card":"Snare!"},{"qty":2,"card":"Melange Mining Corp."},{"qty":3,"card":"Private Security Force"},{"qty":2,"card":"Data Mine"},{"qty":3,"card":"Project Junebug"},{"qty":2,"card":"Cell Portal"},{"qty":3,"card":"Hedge Fund"},{"qty":3,"card":"Wall of Static"}],"identity":{"title":"Jinteki: Personal Evolution","side":"Corp","code":"01067"},"date":"2017-02-24T22:09:54.396Z","username":"__demo__"}]`

**Comment by JoelCFC25** [comment]
If this is going to be pursued at any point, note that all of the suggested decks will be rendered as Casual play only as of October 1 due to the recently announced Core 2.0 and rotation.

**Comment by ZoeB** [comment]
That makes sense, and I think it's safe to say anyone using these decks will be playing casually anyway!

**Comment by Repulze** [comment]
Incidentally, I'm working on Core 2.0 decks atm. It is trickier compared to Core 1.0 because more cards and options are available.

Still, thanks for giving this a bump. I thought people just forgot about it.

**Comment by JoelCFC25** [comment]
New user accounts are now stocked by default with the 7 Revised Core Set only decks (all faction cards plus neutrals).
