### ISSUE TITLE
Trashing Chairman Hiro as Corporation adds him to the runner's score area.

### ISSUE THREAD

**Issue by szhang1000** [mtgred/netrunner#2319]
Playing as the Corporation, attempting to trash Chairman Hiro from hand at the end of the turn caused him to be added to the runner's score area instead. Dragging him back to hand and trashing him from hand did not address the issue.

Installing Chairman Hiro into a new server and then trashing him by writing over him also resulted in this issue. The only way I discovered to avoid this was to use '/discard #n' commands to manually trash him from hand.

This appears to be an issue that has been closed in the past [#1181 and #1312]. The runner had not previously accessed Chairman Hiro in that game. Playing as the Corporation on the previous day, I had trashed Chairman Hiro from hand before without causing the issue. There was no use of Film Critic, but it's possible the Runner may have saw Chairman Hiro in R&D through use of Spy Camera [I don't remember.]

I'm attaching a full transcript of the game in question in case it helps address the issue.

[Transcript.rtfd.zip](https://github.com/mtgred/netrunner/files/706183/Transcript.rtfd.zip)

**Comment by JoelCFC25** [comment]
Good lord, this again.

**Comment by JoelCFC25** [comment]
Can't reproduce this currently--neither by trashing from hand nor by overwriting an active copy.

**Comment by szhang1000** [comment]
My current guess would be that it's related to seeing him in R&D through Spy Camera - that's the only potentially unusual event that might have occurred in that game. Other possible option is that it's due to the runner repeatedly running Archives before the trashing, but that seems more unlikely.

**Comment by JoelCFC25** [comment]
**However**--thanks very much for the log, that was vital. The issue here is that `:access true` lingers in the game state after a Runner hits a Shock! in Archives. This key is normally dropped from the state after access finishes, and it's what the trashable execs check for. I presume the same will apply for other cards that work when accessed there, such as Space Camp.

**Comment by JoelCFC25** [comment]
All Spy Camera does is look at the title of the top card in R&D and print it to the log, so that's not part of the equation here.

**Comment by JoelCFC25** [comment]
Update: I tried Space Camp and CVS in Archives, both of them properly dissoc `:access true` from the state after their effects finish.

**Comment by danhut** [comment]
Looks to be because we don't get a prompt for handling the Shock! access to remove the :access true per the below.  Will check in a fix which removes this flag if it exists when the run ends too.

```

(defn- finish-prompt [state side prompt card]
  (when-let [end-effect (:end-effect prompt)]
    (end-effect state side (make-eid state) card nil))
  ;; remove the prompt from the queue
  (swap! state update-in [side :prompt] (fn [pr] (filter #(not= % prompt) pr)))
  ;; This is a dirty hack to end the run when the last access prompt is resolved.
  (when (empty? (get-in @state [:runner :prompt]))
    (when-let [run (:run @state)]
      (when (:ended run)
        (handle-end-run state :runner)))
    (swap! state dissoc :access)))
```
