### ISSUE TITLE
Controlling the Message missing trigger

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2321]
If the runner trashes a corp card from HQ (or R&D) before trashing the first installed corp card, CTM will not trigger. The problem is similar to the Reaver issue. Perhaps a solution that fixes one can be applied to the other.

Reaver issue:
https://github.com/mtgred/netrunner/issues/2291

**Comment by JoelCFC25** [comment]
More and more this is pointing to a need to distinguish at the game event level between trashing things and trashing _installed_ things. I.e., `:runner-trash`, `:runner-trash-installed`, etc.
