### ISSUE TITLE
Underway Renovation should log which card it trashes

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2324]
Similar to the enhancement for Jinteki: PU, Underway Renovation's advance ability should print what card it trashes from the runner's stack to the game log. I'll try and form a comprehensive list of cards that have this effect so a sweeping pass can be made.

Here's a list of all cards that mention the runner's stack, it seems like a good starting point: [https://netrunnerdb.com/find/?q=x%3Astack](url) 

There's quite a few cards here that are probably missing some messaging, as well as a couple Red Sand cards that will absolutely fall into this category.

Edited my garbage grammar also.

**Comment by danhut** [comment]
I took a look at this and mostly done.  The only cards that need improvement I could find are:
Khala Goda Real TV
MaXX
Personality Profiles
Underway Renovation
Ramujan-reliant 550 BMI
Rolodex

Tired now and will finish the change off in a day or so.

**Comment by danhut** [comment]
Submitted this change - 
(https://github.com/mtgred/netrunner/pull/2333)
