### ISSUE TITLE
Runner's turn starting repeatedly, possibly involving City Surveillance

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#2325]
I've been having issues where the runner's turn starts again after they hit the end of turn button. The card City Surveillance seems to be involved, I've played a couple games using it and those have been when the issue has occurred. The Runner has been able to end their turn by taking a tag, removing it and removing their new clicks.I've been playing Spark Agency when these errors have occurred.

Edit: upon further testing, This occurs when city surveillance has been rezzed and still happens on the turn the runner trashes City Surveillance. This also has occurred at the start of the runner's turn and causes the start of turn to occur twice.

**Comment by danhut** [comment]
I have a fix for this.  It gets into an infinite loop if you pay a credit right now with the runners clicks going up and you pay infinite credits too.
