### ISSUE TITLE
Geist issues I'mma try to reproduce: a) whacky MU b) R&D multi-access

### ISSUE THREAD

**Issue by Bondmonger** [mtgred/netrunner#2327]
I've been playing a lot of Geist games lately and I'm seeing two particular bugs often:

1. The first is MU getting whacky with the interaction between temporary link (Forger/Sports Hopper) and cloud breakers.  It's something to do with 2 link being attained, then dropping down to 1 (often with cloud breakers being trashed), then back up to 2.  I'm seeing it in probably half my games so I should be able to nail down a "reproduce" pretty easily.

2. The second issue is weirder and less common - I'm occasionally getting inexplicable multi-accesses into R&D during runs in which I've triggered Geist's draw ability.  This one is tougher since it doesn't com eup as often (maybe every fifth game), but I'll be sure to track the precise cards interacting over the course of that run.

Nathan 0

**Comment by LiteSpecter** [comment]
I was experiencing the first issue in an earlier build that happened when installing or trashing programs off Street Peddler, but I believe that particular bug has been fixed

**Comment by Bondmonger** [comment]
Yeah, plus it's super easy to fix in-game (since MU overages don't even trigger a prompt and can be manually adjusted).  Minor issue, #1.

I suspect #2 is the result of me triggering stuff at improper windows (I've got two game logs with it happening and in both cases I had effectively fired a Peddler at 4.5 of an R&D access, just going too fast).

**Comment by Bondmonger** [comment]
Not to generate cash for trashing/interacting, just moving on with my turn without ending the run right away.  Bad!

**Comment by danhut** [comment]
For the first issue - the only way i could find to make it happen was to allow myself to go to negative MU, then play forger/sports hopper - and it will be broken.  Given this is an illegal move ...  Did you have any luck reproducing another way?

**Comment by Kaethela** [comment]
I had this happen in an earlier game where I installed Peddler, used it for another Peddler, then used the second one for a Shiv. It took me to -1 MU despite having 2 Link the entire time.
