### ISSUE TITLE
Project Atlas z index issue

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#2329]
![netrunner project atlas bug](https://cloud.githubusercontent.com/assets/22971454/22231572/6c5a3ab4-e1b2-11e6-9e92-8dfad5b6bc53.PNG)
I've encountered issues with Project Atlas and its menu being covered by the pane for HQ. I assume this is related to #2239 somewhat but don't know how to fix it immediately.

**Comment by erbridge** [comment]
Can you provide a screenshot of the issue you're experiencing, please?

**Comment by danhut** [comment]
Only happens in Chrome. having a poke about
