### ISSUE TITLE
Using Hades Shard outside a run acts like a run?

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#2330]
Currently if the runner uses an installed Hades Shard outside a run the game seems to lock the runner into a run with "Continue/Jack Out" prompts in addition to giving the corp a window to react. This bug could cascade potentially cascade into other unintended actions, depending on how the players proceed with the erroneous run prompts. (i.e., successful/unsuccessful run triggers)

**Comment by JoelCFC25** [comment]
I think this one's pretty simple. The line in Hades Shard's ability that starts: 

`(swap! state update-in [:run :cards-accessed]` ....(blah blah) 

...should get wrapped in a `(when (:run @state)`
