### ISSUE TITLE
News Team not leaving archives after runner adds it to score area.

### ISSUE THREAD

**Issue by HyenaMars** [mtgred/netrunner#2331]
As the title states, and [as can be seen here](http://prnt.sc/dzhkdk), News team remains in archives after the runner chooses to add it to their score area.  
Issue might be related to #932

**Comment by danhut** [comment]
I tested and it works fine.  Also tried with Temujin running on archives as per your screenshot.   Any idea on the sequence of events here?

**Comment by HyenaMars** [comment]
If I'm not mistaken, he used his first click to thrash  Ibrahim Salem, after that I rezzed a blacklist. Not quite sure what happened prior to that though, sorry.

**Comment by danhut** [comment]
That combo broke it nicely ;)
