### ISSUE TITLE
Heap window implementation when runner deck size is large

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2334]
In [this video](https://www.youtube.com/watch?v=jDmnDeijb6Q#t=29m14s) the player has a 102 card MaxX deck, and he's playing against PU. At 29:14 he opens the heap window and, well... it's amusing but you guys probably want to fix it. Not sure if you want to add scroll bars or just layer the cards or what.

**Comment by danhut** [comment]
Made a tweak here - now the whole top bar of the discard popup will close the pane on click.
