### ISSUE TITLE
Personal Evolution dealing 3 net damage per steal/score

### ISSUE THREAD

**Issue by Kaethela** [mtgred/netrunner#2336]
Jinteki: Personal Evolution is firing three separate triggers for 1 net damage each every time an agenda is scored or stolen. This was happening during the entirety of the game and was consistent across all agendas.

**Comment by danhut** [comment]
do you have any screen capture or means to reproduce this? I just tried and it seemed fine

**Comment by Kaethela** [comment]
I didn't have a chance to take a screenshot, will try to reproduce.

**Comment by Kaethela** [comment]
Happened again. Interestingly, only started happening midway through the game but continued until the end of the game once it started.

Kaethela accesses an unseen card from R&D.
Kaethela steals House of Knives and gains 1 agenda point.
Kaethela places 2 power counters on Aaron Marrón.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Temüjin Contract due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Forger due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes The Turning Wheel due to damage.

Kaethela accesses Fetal AI from HQ.
Shinji16 uses Fetal AI to do 2 net damage.
Kaethela trashes The Turning Wheel, Shiv due to damage.
Kaethela pays 2 to steal Fetal AI.
Kaethela steals Fetal AI and gains 2 agenda points.
Kaethela places 2 power counters on Aaron Marrón.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Forger due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Forger due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes due to damage.

Kaethela steals The Future Perfect and gains 3 agenda points.
Kaethela wins the game.
Kaethela places 2 power counters on Aaron Marrón.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Forger due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes Forger due to damage.
Shinji16 uses Jinteki: Personal Evolution to do 1 net damage.
Kaethela trashes due to damage.

**Comment by danhut** [comment]
Might need to see what else was installed - i tried with Aaron Marron but looks ok.  

wozzit accesses House of Knives from Server 2.
wozzit steals House of Knives and gains 1 agenda point.
wozzit places 2 power counters on Aaron Marrón.
wozza uses Jinteki: Personal Evolution to do 1 net damage.
wozzit trashes Forger due to damage.

**Comment by JoelCFC25** [comment]
Absent any other smoking gun, this just seems like yet another instance of latency causing events to get registered multiple times as in #468.

**Comment by mvelic** [comment]
I experienced this a while back too - related to closed issue 2149 - https://github.com/mtgred/netrunner/issues/2149
