### ISSUE TITLE
Architect R&D sub logs itself twice

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2339]
When you rez an Architect and fire the first sub, log shows the same log text for it twice (maybe once when you see the 5 cards, then again when you select one?).

**Comment by JoelCFC25** [comment]
Architect's first sub is using both `:msg` and `:activatemsg`. The `:msg` should be dropped.

**Comment by jaerme** [comment]
Joel,

I was just testing this. Did you mean the `:msg` field should be dropped and replaced with a `:label` field? I tested removing `:msg` and there was no longer a label for the first subroutine. Thanks.

**Comment by JoelCFC25** [comment]
Yeah, `:msg` changed to `:label` and the word "look" capitalized.
