### ISSUE TITLE
Stim Dealer breaks maxx

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#234]
Installing the stim dealer in maxx turns off the max start of turn ID ability and the stim dealer counter gaining. have not tested in any other id.

**Comment by eah13** [comment]
+1

**Comment by mtgred** [comment]
Thanks for reporting the issue. I'll work on it this weekend.

**Comment by mtgred** [comment]
Stim Dealer was broken. It's fixed now.
