### ISSUE TITLE
Bhagat effect activating on Archive and R&D Run

### ISSUE THREAD

**Issue by Vitesse0** [mtgred/netrunner#2341]
*This issue is different from #1838. 

The runner made a successful run on R&D with Bhagat installed. Without runner trying to cheat, Bhagat went off, trashing the top card of my deck.

The runner made a successful run on Archives with Bhagat installed. Without runner trying to cheat, Bhagat went off, trashing an agenda from the top into archives... lol.

Unfortunately, I didn't get a good screenshot because I was initially confused and assumed I misread Bhagat's card text.

After the game, I copied the chat log and marked each instance with "****". If you use find function, you will find both instances. Thank you for providing us with an awesome site to play Netrunner. Let me know how else I can help.

ANSI File.
[Chatlog.txt](https://github.com/mtgred/netrunner/files/737208/Chatlog.txt)

![image](https://cloud.githubusercontent.com/assets/25409364/22400548/a9b5e9f2-e57d-11e6-8a16-12e7a833a778.png)

**Comment by sdapalsch** [comment]
I can confirm the issue.

![capture](https://cloud.githubusercontent.com/assets/16731967/22400876/98bbd798-e586-11e6-8ef1-b13d25b7ca58.JPG)

If I have time, I'll look into a fix tonight.

**Comment by nealterrell** [comment]
Bhagat's `:req` is missing an `and` around the two conditions.
