### ISSUE TITLE
Old Hollywood Grid prevents stealing any future accessed agenda

### ISSUE THREAD

**Issue by tgmoore** [mtgred/netrunner#2344]
Accessed High-Risk Investment in remote server with rezzed Old Hollywood Grid. Prevented the steal on that run, the next run on the same server on the same turn after previously trashing OHG, a run initiated manually between player turns on the same server, a run initiated manually on the Corp's turn and a run a few turns in the future on R&D while accessing a completely different agenda.

In game, the bug was handled by removing accessed agendas from the game and manually adding agenda points. OHG didn't affect stealing a Hostile Takeover later in the game with a HT in the runner's score area, so it seems to be working correctly otherwise.

**Comment by danhut** [comment]
I could not reproduce this.  Questions
1/ You say you initiated a run between turns.  Why and how did you do this?
2/ You say the run in between turns was on the same server - but since the agenda and OHG were stolen it would not exist any omre?
3/ Do you have screenshots / chat log?

**Comment by tgmoore** [comment]
Unfortunately, no screenshots or chat log, this is my first bug report.

1. I added a click manually and made the run. I was testing what condition would end the OHG effect. Just kinda poking around to see what was up.

2. The server was protected by ICE.

**Comment by PesiTheWizard** [comment]
This just happened to me as corp as well. And this is after the purported Old Hollywood Grid fix of Wednesday Jul 26th - 20:51. I had it on a remote server. They ran, I rez, they trash and run again and are stealblocked. After that they countersurveillance'd R&D and everything they found was blocked by Old Hollywood Grid. This persisted to later turns.

( Mentioning the other bugreport for completeness #2262 )

**Comment by JoelCFC25** [comment]
> purported Old Hollywood Grid fix

I'm not wild about the usage of this word, as I very definitely fixed an OHG issue--just not this one, which as indicated could not previously be reproduced. So more will need to be done. Curiously there are 3 existing tests for OHG which are all passing.

**Comment by ashbc** [comment]
Just encountered a similar bug. Click 3 run R&D, trash a rezzed OHG and see an agenda on the top. Click 4 run R&D and the site still prevents stealing.

**Comment by JoelCFC25** [comment]
Update from duplicate report: 
> 1. trashing a rezzed Old Hollywood Grid, then running the same server prevents from stealing the agenda. I've verified this at least once.
> 2. Attempting to steal an agenda from a server where there was no Old Hollywood Grid present at any point fails to steal the agenda.
> 3. Attempting to steal an agenda from a central server does not allow for a steal either. 

So far, I cannot replicate #1 in dev. Run remote with rezzed OHG and an agenda, try to steal agenda, fail, trash OHG, end run. Run same server, successfully steal the agenda. Still checking the rest.

**Comment by JoelCFC25** [comment]
OK, ***finally*** there is something reproducible. The order in which cards are accessed does seem to matter. Either on a remote or when installed on a central where an agenda is about to be accessed, if OHG is trashed _first_, then the flags are not being cleared properly and subsequent attempts to steal that ought to work are failing. If the agenda is accessed first the initial steal is correctly prevented, but accessing and trashing OHG last somehow clears the flags correctly and allows later steal attempts to work properly.

**Comment by PesiTheWizard** [comment]
Probably not relevant but I figure I should report anyway.
Had a game where the runner accessed and trashed OHG but never bothered to actually access the agenda. Following this, they had to problems stealing agendas from R&D.
