### ISSUE TITLE
Account disappeared after not playing for long

### ISSUE THREAD

**Issue by hugeheadliang** [mtgred/netrunner#2347]
I didn't play on jinteki for several months and when I try to log in today I found my account didn't exist. I had to sign up again (using the same email address) and found that all the decklists I saved are gone. I also have no access to alternative art now, which I had before.

My email is liangzimou@gmail.com and my user name is hugeheadliang

**Comment by Kaethela** [comment]
This is probably due to the database wipe that happened recently which took out all the accounts. If you're a donor, mtgred has been manually going through the list and restoring alt-arts.

**Comment by nealterrell** [comment]
This is indeed what happened. Now that you are re-registered @mtgred can re-authorize your alt arts.
