### ISSUE TITLE
Add sealed identities

### ISSUE THREAD

**Issue by Salem2612** [mtgred/netrunner#2350]
Hello,
Could you please add the sealed identities used on anrsealed.com ? Today we are playing with The Professor and Custom Biotics because they have no abilities. We don't play with draft identities because we play in the format 45 cards per deck and 7 agenda points to win. Maybe the cards must be on NetrunnerDB first ? Here are the features of the 2 identities :

**Runner**
- Name: "M4rg4ux : Haired New Born"
- Faction: No faction (as in Draft format)
- Link: 0
- Text box: No ability
- Influence limit: Infinite (as in Draft format)
- Minimum deck size: 45 cards (as in the base game)
- Score to win: 7 points (as in the base game)

**Corp**
- Name: "Ludiworld : Gaming Everywhere"
- Faction: No faction (as in Draft format)
- Text box:
You can use agendas from all factions in this deck.
The number of agenda points required in this deck is reduced by 2.
The trash cost of all **transaction** and **advertisement** assets is increased by 2.
- Influence limit: Infinite (as in Draft format)
- Minimum deck size: 45 cards (as in the base game)
- Score to win: 7 points (as in the base game)

**The number of agenda points required in this deck is reduced by 2.**
That means that 18-19 agenda points are required for a 45-49 cards deck.

**The trash cost of all **transaction** and **advertisement** assets is increased by 2.**
Here is the code inspired from Encryption Protocol, Weyland 1 and Rebranding Team that I think is good but not tested:
`{:events {:pre-trash {:req (req (or (has-subtype? target "Transaction")
                                       (has-subtype? target "Advertisement")))
                         :effect (effect (trash-cost-bonus 2))}}}`

I would like to do it myself but Clojure + setting the whole dev environment is too damn hard for me. Thank's a lot if you can answer to this request, and anyway thank you for this amazing website.

**Comment by JoelCFC25** [comment]
My 2 credits: the site should support officially released cards only. This would require wide-ranging changes (including to the deckbuilder code). I'm not in favor of adding features to support custom formats. ANrena, for example, simply builds on the existing draft format rules and didn't require anything extra to be done.

**Comment by nealterrell** [comment]
I agree with Joel, we don't have the manpower to support custom formats that use non-standard cards. We can advise you on forking the project and setting up your own server if you really want automated support for your custom format, but I can't see it being merged into the main site.

And from a technical standpoint, yes, we use NetrunnerDB's list of cards and don't have a way of implementing cards that aren't on their site.

**Comment by Salem2612** [comment]
OK I understand that you don't want to support alternat-fan-made formats.
