### ISSUE TITLE
Remove from game macro

### ISSUE THREAD

**Issue by mn200** [mtgred/netrunner#2357]
While Stinson is not implemented in particular, but I think it might be generally helpful to be able to manually move cards to the removed from game area.

**Comment by JoelCFC25** [comment]
Stinson should be live now (maybe not all the way there, not sure if the interaction with currents is correct). For general need to remove a card from the game, the `/rfg` console command already exists. See the site's Help tab.

**Comment by mn200** [comment]
Fantastic; I must have missed `/rfg` when I looked before.  Thanks!
