### ISSUE TITLE
Multiple Conspiracy Breaker (Paperclip, Black Orchestra, MKUltra) prompts

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2360]
Not a big issue, but if you have multiple of the same conspiracy breaker in the archives and encounter the right type of ice, the install prompt will also be shown multiple times. I think it could sometimes be relevant to install multiple or to install one that you already have installed, but if you answer "No" on the first prompt, it seems like the single prompt would be enough. It's at least slightly confusing for the user (when they decline an install, but the prompt is still there).

**Comment by nealterrell** [comment]
Working on it. I like your idea of having the first No prevent the others from asking.
