### ISSUE TITLE
Sifr + Quicksand interaction does not work correctly

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#2361]
Another strange rules interaction. 

If sifr is installed, the runner can use it on a quicksand to reduce its strength to 0. When the runner encounters quicksand, it goes up by 1 strength. The runner must use Sifr before the quicksand gains its counter, however in Jnet, quicksand gains its counter automatically and then the runner chooses to use Sifr to reduce its strength to 0.

Unsure on the best way to work through this, but currently quicksand is the only ice in the game that has this workaround with Sifr, so a special case of only reducing to 1 on quicksand could be implemented.

**Comment by JoelCFC25** [comment]
No, there are no automatic events on Quicksand. It is manually triggered by the Corp player.
