### ISSUE TITLE
Firing Sifr's ability on an unrezzed ICE reveals what the ICE is

### ISSUE THREAD

**Issue by defconclown** [mtgred/netrunner#2363]
As the tittle. If the runner uses Sifr's ability to reduce STR to 0 on an unrezzed piece of ICE the chat message pops up and says it normal 'Runner uses Şifr to lower their maximum hand size by 1 and lower the strength of ICE to 0.'

**Comment by JoelCFC25** [comment]
Thanks. The ability needs a `:req (req (rezzed? current-ice))`.
