### ISSUE TITLE
Exiting/entering new games stays on old game

### ISSUE THREAD

**Issue by alcohollywood** [mtgred/netrunner#2367]
Reporting a bug in which, after joining or spectating a game and leaving, starting a new game (whether as player or spectator) takes me back to previous game.

First time: Spectated a game (sorry, cannot remember circumstances or IDs/users), exited, then attempted to start a Corp game twice. Both times, clicking 'Start' after picking decks took me back to that spectated game. Had to Ctrl+F5 to fix.

Second time: Finished a game with another player, left game, then attempted to spectate another. Hitting 'Watch' took me back to the end of my previously played game instead. Had to Ctrl-F5 to fix. 

Thanks!

**Comment by lpoulter** [comment]
Also experiencing same. logging out and back in fixes the issue.

**Comment by MGillett** [comment]
I am also experiencing this issue. Have been refreshing the tab after every game as a workaround.

**Comment by JoelCFC25** [comment]
No reports in over 2 months. Closing.
