### ISSUE TITLE
Underway Renovation accidentally revealing cards

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#2370]
I know no one ever uses [Underway Renovation](https://netrunnerdb.com/en/card/08077), so here's a quick reminder: it's a face-up 3/1 that when advanced:

- trashes the top card of the Runner's stack if it has 0-3 advancements, OR
- trashes the top two cards of the Runner's stack if it has 4+ advancements.

However, it looks like even if it has 0-3 advancements, Underway Renovation prints a message as though it had trashed two cards, thus accidentally revealing the top card of the Runner's stack.

![2017-02-15_53](https://cloud.githubusercontent.com/assets/1972929/22984660/1a960590-f374-11e6-90a5-787de34d428a.png)

As you can see this Underway had a single advancement on it; Temujin was indeed in the trash but Ghost Runner was on top of the deck.

You can also see it happen in [this Metropole Grid video](https://youtu.be/etz47JSPJ04?t=7m48s); the message from the first advancement says that it trashed Inti & Sifr, but only Inti is in the bin; th esecond advancement says it trashed Sifr & Self-Modifying Code, but only Sifr was actually trashed.

**Comment by JoelCFC25** [comment]
In the `let` of `:msg`, we have this: 

`adv4? (>= (:advance-counter (get-card state card)))`   

Greater than or equal to what? Missing. Needs to be a 4 in there.

**Comment by danhut** [comment]
My bad... fixed !
