### ISSUE TITLE
Error after scoring Accelerated Beta Test and rezzing Wall of Static using the agenda'a ability

### ISSUE THREAD

**Issue by jaturul** [mtgred/netrunner#2377]
Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do choice Server 1 #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [game.core$resolve_prompt invokeStatic "actions.clj" 145]}]
 :trace
 [[game.core$resolve_prompt invokeStatic "actions.clj" 145]
  [game.core$resolve_prompt invoke "actions.clj" 115]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__27233 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__27268 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by danhut** [comment]
Did you see this again?  I am unable to reproduce.   If you do see it can you provide steps/cards in play?

**Comment by jaturul** [comment]
Hi Dan,
I did not see the error again. But I can tell you that it may have been
caused by my mouse. What I mean is that it malfunctions sometimes and
double-clicks instead of single-clicking. So I may have pressed one of the
buttons twice almost instantly.
Hope this helps in some way,
Jacek

**Comment by danhut** [comment]
Thanks Jacek - there is something about spamming buttons and/or latecy that causes errors so sounds feasible.  I am new-ish to the project and don't understand that part yet.
