### ISSUE TITLE
Hostile Infrastructure fires when Film Critic hosting agenda is trashed

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#2382]
When a Film Critic hosting an agenda is trashed (tested with Voter Intimidation) then Hostile Infrastructure counts the agenda as being trashed by the runner, dealing 1 net damage. 

As far as I'm aware this is incorrect as the agenda is trashed by a change of the game state, not either player.

**Comment by JoelCFC25** [comment]
The `move` function contains `trash-hosted` function for use when a card is moving to a new zone. Maybe it could use some additional logic that would add `:suppress-event true` in the case of hosted cards being inactive.
