### ISSUE TITLE
Disconnection every hour or so won't let me back in the game.

### ISSUE THREAD

**Issue by Venuil** [mtgred/netrunner#2383]
[#418](https://github.com/mtgred/netrunner/issues/418)

[#340](https://github.com/mtgred/netrunner/issues/340)

For whatever reason, about every hour and a half to two hours I disconnect for a second, then reconnect but can't access the game anymore. This makes it almost impossible for me to play on jinteki.net, but I started a beginners group that meets on Discord to learn and play Netrunner on jinteki.net, so as the disconnects have become more frequent, I have been less able to teach and play with my group of newbies. We are a growing group, but this is a growing problem for us. I've read that HTML5 Local Storage could fix this issue, but I'm not a computer guy. Apparently, for a dev, it's quite easy:

[Local Storage How-To](https://www.smashingmagazine.com/2010/10/local-storage-and-how-to-use-it/)

[Another How-To Local Storage Page](http://julip.co/2010/01/how-to-build-a-chrome-extension-part-2-options-and-localstorage/)

I was using Opera for my browser until this issue got worse. I switched to Chrome, but the problem is the same there.

Without a feature to keep me and others in games that disconnect briefly, I won't be able to grow with my jinteki.net group and we may have to move to another site. Thank you!

**Comment by kevart** [comment]
Same over here :-(

**Comment by LongHairedHippy** [comment]
Same here.  It seems to happen to me every 5-10 min.  Very frustrating.  I've even tried disabling my firewall, which otherwise works fine.

**Comment by mystermerry** [comment]
Same issue. Is there a workaround?

**Comment by JoelCFC25** [comment]
Much more robust game rejoin functionality is now live!
