### ISSUE TITLE
Team sponsorship allows installing runner cards from the heap

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#2386]
Found this out accidentally while checking to make sure I hadn't blasted through a clot trigger while the TS trigger was active. Clicking the runner's heap selected the top card of the heap for my TS shenanigans, letting me install a runner card (cloak) in a new remote. Later confirmed that this is incredibly repeatable, just whenever you have a team sponsorship trigger, click on any of the runner's cards in their heap and you can install it in any server.

At this moment I'm unsure what happens when they run it, but have confirmation that Leela cannot bounce them back into hand.

**Comment by JoelCFC25** [comment]
TS `:choices` targeting needs `(= (:side %) "Corp)` added as a condition.
