### ISSUE TITLE
Cannot login if using '+' character in username

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#2388]
If your email contains a + sign (eg. gustavo+garcia@hotmail.com) your registration is accepted and you can launch a password recovery, but you cannot login as you get a data validation error: "Invalid login or password"

**Comment by danhut** [comment]
What are you using as username when you log in?  This works fine for me - but note you have to login via username which is NOT your email address.  A 16-character limit exists for the username

**Comment by inniscor** [comment]
That explains it, I think I was using my email to login. Thanks!
