### ISSUE TITLE
Eater and Archives Interface

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#2389]
I know the software can't enforce every rule, I was just wondering if that was the case here, or it was an interaction that hadn't come up before.

My understanding is that if you Eater on an Archives run you can't use Archives Interface because you would have to access the card to use AI's replacement effect, and obviously Eater prevents that.

In my last game I wasn't sure of the rule so said okay, and it allowed him to remove my card.

**Comment by JoelCFC25** [comment]
This is a bug. Archives Interface would need to check that `[:run :max-access]` is not 0 before firing the effect.
