### ISSUE TITLE
Blanking the Black File with Dr. Lovegood when Corp has scored 7 points doesn't result in Corp win

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#2397]
The Black File - https://netrunnerdb.com/en/card/10099
Dr. Lovegood - https://netrunnerdb.com/en/card/09042

If the Corp has scored 7 points with The Black File installed, they do not win the game.
If the Runner blanks The Black File with Dr. Lovegood, the expected result is the Corp instantly winning. This is because the effect on The Black File ceases to have an effect on the game state, allowing the Corp to win.

Currently, this is not the case on the site. The Runner is able to blank the Black File, preventing it from gaining counters while also preventing the Corp from winning after they have scored 7 points.

**Comment by JoelCFC25** [comment]
I'm pretty sure it works if The Black File gets _trashed_, as the card has a `trash-effect` that gains 0 agenda points to trigger the game win if applicable. But in order to work when blanked by Lovegood, I think it would also need a `:leave-play` effect that does the same.
