### ISSUE TITLE
Deckbuilder reading Quarantine System as Net Quarantine

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#2398]
When pasting my deck from NRDB (using the Jinteki.net format) and extra Net Quarantine is loaded into the deck on Jinteki, making the deck invalid.

Appears "Quarantine System" is parsed as "Net Quarantine" instead. Might be due to NRDB problem that was recently fixed. 

Might be fixed by updating card data.

Deck: 

> 1 Chronos Project
> 2 False Lead
> 3 Global Food Initiative
> 3 Project Atlas
> 2 Show of Force
> 2 Commercial Bankers Group
> 2 Corporate Town
> 3 Encryption Protocol
> 1 Executive Boot Camp
> 3 Jackson Howard
> 3 Museum of History
> 3 PAD Campaign
> 3 Public Support
> 1 Quarantine System
> 2 Snare!
> 1 Cyberdex Virus Suite
> 2 Oberth Protocol
> 2 Diversified Portfolio
> 2 Friends in High Places
> 1 Paywall Implementation
> 1 Stock Buy-Back
> 1 Meru Mati
> 2 Spiderweb
> 2 Mausolus
> 2 Archer
> 3 Tour Guide
> 1 Excalibur

**Comment by JoelCFC25** [comment]
This should work fine after a data fetch.
