### ISSUE TITLE
Accessing cards from HQ as Silhouette causes double-access after resolving her Expose effect

### ISSUE THREAD

**Issue by KaynSD** [mtgred/netrunner#2405]
After a successful first run on HQ per turn while playing as "**[Silhouette: Stealth Operative](https://netrunnerdb.com/en/card/05030)**", the _Expose_ effect is triggered after an access (which in itself is wrong), but then returns to the Successful Run prompt, which can not be jacked out from unless _/close-prompt_ is entered by both players. 

This could also cause double access if the runner player is not paying attention.

**[Blackguard](https://netrunnerdb.com/en/card/04085)** was also in play prompting a forced Rez of this exposed card, which may be the source of this problem.

**Comment by JoelCFC25** [comment]
Sigh, feel like this has been fixed so many times previously...

**Comment by JoelCFC25** [comment]
I'm going to need more details to investigate this. An initial basic reproduction attempt (1 unrezzed asset in a remote, Silhouette with only Blackguard installed) yielded a correct order of effects and no duplicated prompts/extra accesses.

**Comment by KaynSD** [comment]
Other than that, cards that could potentially cause havoc that were
installed were Snitch which will have fired during that run and Sneakdoor
Beta.

Can't remember if it was a Sneakdoor run that triggered this bug off the
top of my head. I believe I forced the Rez of ice, but do not believe that
it was anything that had an additional on Rez effect.

Other cards installed will have been Compromised Employee, German Drip,
London Library, but can't see how they'd affect things.

**Comment by JoelCFC25** [comment]
Any subsequent instances of this?
