### ISSUE TITLE
Decked before starting.

### ISSUE THREAD

**Issue by MontyWhittaker** [mtgred/netrunner#2412]
Started a game, the display was wonky and I couldn't start. And I also "lost" because I was decked before beginning.

![image](https://cloud.githubusercontent.com/assets/17957733/23772665/70479e80-04e1-11e7-95d0-4306fa5febf9.png)

**Comment by MontyWhittaker** [comment]
(Possibly) important addendum--I was using Jinteki: Potential Unleashed.

**Comment by haradan** [comment]
This just happened to me as well. I was playing as NEXT Design.

**Comment by danhut** [comment]
I would say we have totally NFI how this could happen...  what was "wonky" on the display? Maybe there is a clue there...

**Comment by MontyWhittaker** [comment]
Just occurred again. Was playing against Edward Kim (from what I saw before starting), using IG. 

![image](https://cloud.githubusercontent.com/assets/17957733/25103851/9047be3e-2383-11e7-8db8-7a6dbe8867f3.png)

**Comment by JoelCFC25** [comment]
I notice you are using the Jankteki plugin. I don't have any basis on which to suspect it, but has this ever happened when that plugin was not in use?

**Comment by haradan** [comment]
I don't use any plugins, though I've only seen this happen once.

**Comment by LiteSpecter** [comment]
I think this is similar to what happens when you click through multiaccess too fast. If you click "start a game" too fast or multiple times this might happen

**Comment by artturipi** [comment]
If one player is changing their deck when the other presses "start game" this happens. I think it happened to me this way, anyhow.
