### ISSUE TITLE
Maw + Hostile Infrastructure interaction

### ISSUE THREAD

**Issue by twistyb** [mtgred/netrunner#2424]
Currently Maw's ability is triggering Hostile Infrastructure, and the Runner is taking net damage. According to the card it is the Corp that trashes the card, so Hostile shouldn't trigger.

"The first time each turn you access a card not in Archives and do not steal or trash it, the Corp must trash 1 card from HQ at random."

**Comment by JoelCFC25** [comment]
Needs to use `(trash state :corp (first (shuffle (:hand corp))))` instead of `trash-cards`.
