### ISSUE TITLE
cards section - lists close

### ISSUE THREAD

**Issue by negroscuro** [mtgred/netrunner#2427]
When i try to see cards for a specific set, i deploy the list and while I search for the one i am interested in, the list collapses and I have to do it over and over again.

**Comment by JoelCFC25** [comment]
I think this is the same thing as #997. It is really aggravating, I agree.

**Comment by negroscuro** [comment]
sorry if it already exist. feel free to delete or close this one.

**Comment by negroscuro** [comment]
i tested it wiht chrome...

**Comment by danhut** [comment]
@jwarwick  Didn't you fix this?  Am i dreaming?

**Comment by jwarwick** [comment]
No, I don't think I fixed this (though I did do quite a bit of work on the card filters). Might have accidentally fixed it, but I doubt it.

There was some context in another bug that indicated maybe we were doing something "not the React way" and hence the lists were redrawing without saving their state.

**Comment by NoahTheDuke** [comment]
Can't reproduce this.
