### ISSUE TITLE
J. Masanori false positive trigger

### ISSUE THREAD

**Issue by ende23r** [mtgred/netrunner#2433]
I had John Masanori installed, ran HQ. The Corp rezzed Crisium Grid before the run was successful. I didn't draw a card; so far, so good. I trash Crisium Grid.
I run HQ again. This is the first successful run this turn. Masanori won't draw me a card. That's a bug (I think; I might be misunderstanding the rules). 

I looked at similar bugs, and it looks like #2404 fixed a similar issue with Find the Truth; a line
`:req (req (first-event? state side :successful-run))`
was changed to be instead
`:req (req (= 1 (count (get-in @state [:runner :register :successful-run]))))`

Masanori has that same phrase on line 639. Does he need an update?

**Comment by danhut** [comment]
Nice work tracking down the fix.
