### ISSUE TITLE
Project Atlas + Forfeit effects

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2434]
From the frontpage chatlog:

LukeArielThursday Mar 16th - 17:35
I know this should go on github but i don't have an account on there: seems that the forfeit effects from Jemison/Quarantine system aren't calculating entirely correctly

LukeArielThursday Mar 16th - 17:36
e.g., Quarantine system installed- rez, forfeit Project Atlas to QS ability. rez Veritas (should be for free) but it costs 2$

LukeArielThursday Mar 16th - 17:36
As if Atlas was a 1-pointer

LukeArielThursday Mar 16th - 17:38
Another instance: Oberth installed, install High-Risk investment on Oberth. Rez Oberth, forfeit Atlas. Should place 3 counters from Jemison's ability, but only places 2.

LukeArielThursday Mar 16th - 17:39
Project Atlas may be the common denominator, cause I don't recall it working like that when I've forfeited Corporate Sales team but I can't say for sure

LukeArielThursday Mar 16th - 17:44
Just did a quick check, and it does seem to be Project Atlas that's throwing things off

**Comment by JoelCFC25** [comment]
I can't reproduce this yet. Forfeiting an Atlas to QS yields me a 4credit discount on a DNA Tracker, for example. Were there other things in your removed from game zone prior to the forfeit of these copies of Atlas? Similarly, forfeiting an Atlas to rez an Oberth in Jemison sees me place 3 advancements.

**Comment by danhut** [comment]
could not repro either

**Comment by artturipi** [comment]
Hm, yeah. As I noted, this was picked up from the chat, so could be anything. Perhaps old version of codes or whatever client side. Can probably be closed?
