### ISSUE TITLE
Fetal AI's net damage ignored when trashed via Imp

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2440]
When the runner accesses Fetal AI, it would normally do 2 net damage. However, if it is trashed by using Imp, this effect doesn't happen.

**Comment by JoelCFC25** [comment]
Related to #2275, I'm pretty sure.

**Comment by JoelCFC25** [comment]
Struck my first comment. The interaction will actually work correctly if the Runner holds off on using Imp until the "Pay 2c to steal" prompt appears--but the problem is that there are no timing restrictions on when Imp can be clicked.

**Comment by JoelCFC25** [comment]
I have a solution for this, but have to do some more testing to make sure it doesn't break other stuff. Basically swapping some temporary keys into state for the relatively new 4.5.x steps of the access step.

**Comment by nealterrell** [comment]
This should be good now.
