### ISSUE TITLE
Triggering Accelerated Beta Test with Bifrost Array forced a deck shuffle after the first piece of ice was installed in NEXT Design

### ISSUE THREAD

**Issue by Evilpyro25** [mtgred/netrunner#2446]
Playing NEXT Design, opponent was Andromeda.

After firing Bifrost, and using it to trigger Accelerated Best Test, 2 pieces of ice and 1 operation were shown off the top of R&D. When the first piece of ice (an Architect) was installed and rezzed, the cards in the temporary zone were shuffled back into the deck.

**Comment by LiteSpecter** [comment]
This is expected behavior from The Foundry, interesting to see out of Next Design

**Comment by danhut** [comment]
Could not reproduce this at all.
