### ISSUE TITLE
Trapped in a run

### ISSUE THREAD

**Issue by Radiea** [mtgred/netrunner#245]
Sometimes, when the runner is trying to exit a run or when the run is completing, the runner instead gets "Continue" and "Jack Out" options instead, where neither option does anything. This seems to happen when the runner jacks out and the corp goes 'no further action' simultaneously, but also seems to happen with e.g. Argus Security, after triggering the Argus agenda steal penalty.

**Comment by nealterrell** [comment]
Sounds like a gnarly race condition. Argus works fine with normal access conditions. @mtgred, I don't know enough Clojure to answer this, but can we put locks on parts of the run code based on game ID, so you can't get Jack Out and No Action firing at the same time?
