### ISSUE TITLE
Daemons/Self-Modifying Code : More memory than you should have

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2450]
This was tested with Leprechaun and Self-Modifying Code.

1)Install Leprechaun normally. (=m-1)
2)Use ability on leprechaun to install a program from hand onto it, Pick Self-Modifying code. (=m-1)
3)Use Self-Modifying Code to install some program. This program is not hosted on leprechaun. (=m+1)

You have apparently been 'refunded' the memory on a program that never cost memory at all.

**Comment by danhut** [comment]
The :card-moved listener on Leprechaun needs an extra check - if the destination is trash don't refund the MU as this is taken care of by the trash code.

**Comment by PesiTheWizard** [comment]
Further testing:

Point 2) It makes no difference weather you install it directly onto the leprechaun or install it first normally, then have leprechaun host it.

This also happens when hosted on Djinn.

Other programs do not show this bug, be they self-trashing (Faerie), with a self-trashing activated ability(Deus X) or purge-trash viruses(clot). It seems to be specific to Self-Modifying Code.

**Comment by danhut** [comment]
Is SMC the only program of those with a delayed completion?  Ie. Choose stuff from a bunch of menus?  I spent a while on this and made it worse.  Licking my wounds

**Comment by PesiTheWizard** [comment]
More testing:

Hyperdriver and Trope work normally when used off of Leprechaun, but when dragged from the RFG area to grip, increase memory by the amount they normally cost, as if they were still installed.

**Comment by PesiTheWizard** [comment]
The most recent Metropole Grid video as of this comment shows the bug in action exactly at the 2 hour mark.
Schehereazade is hosting SMC, so it's not even limited to Daemons that have you ignore the memory cost.
SMC has trashed itself when he is selecting the program to install. Memory has been refunded at this point. After he picks the program to install he gains 2 more memory.

**Comment by JoelCFC25** [comment]
I don't know when SMC was given `:delayed-completion`, nor does it make any sense why it should have it. Regardless, I finally took a look at this. SMC is trashing itself both on [line 694](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/programs.clj#L694) and on [line 707](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/programs.clj#L707), so there's the problem.

**Comment by danhut** [comment]
Nice one Joel.  Fix one problem to cause another... I had just traced the problem back to myself
