### ISSUE TITLE
Möbius continues to give 4 credits on any successful run on R&D

### ISSUE THREAD

**Issue by parmer** [mtgred/netrunner#2456]
When you play Möbius the first time, it works great: it prompted me for a second run, then paid out 4 credits after a successful second run. However, any successful run on R&D after that kept granting 4 credits (chat log said it was from Möbius). After playing a second Möbius, each successful run on R&D granted 8 credits (2 sets of 4, presumably from the 2 different Möbius plays).

**Comment by JoelCFC25** [comment]
Sorry about that, will fix in next patch.

**Comment by parmer** [comment]
No problem! Just trying to be helpful
