### ISSUE TITLE
Scoring Agenda and Terminal Operation

### ISSUE THREAD

**Issue by zodoh** [mtgred/netrunner#2458]
Whenever an agenda has enough advancement token on it the corp is always able to score it, even during the runner turn.
I don't know if it is done on purpose but as the players are generally fair, they won't score it when they can't do it and thus, this doesn't really matter.

However, whenever the Corp play a Terminal Operation (Violet Level Clearance for example) the Corp should not be able to score the project.

Action phase is ended, there is no more window to score.

-> This seems more to be a improvement than a bug, and the case being really rare... very minor.

Regards

**Comment by danhut** [comment]
I am not sure if we should change this -while technically correct it would seem to block some abilities for players to unpick mistakes.  Same as scoring on the wrong turn.  Dunno!

Terminal sets this into state which would be the point of logic
```
(swap! state assoc-in [:corp :register :terminal] true)
```
