### ISSUE TITLE
Suffering net/brain damage with Titanium Ribs doubles the damage taken

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#2459]
Titanium Ribs: https://netrunnerdb.com/en/card/08045

When suffering brain damage (such as from Amped Up or Brain Cage), the system gives a prompt for selecting which card to discard. After the card is selected, the system discards another card and adds an additional brain damage. 

This duplication effect does not happen for Meat damage, but it does happen for Net damage.

When interacting with Clan Vengeance, the system counts it as a single instance of damage (adding a single counter despite the duplication effect).

==

**Example Log**
!valranoth uses a command: /take-net 1
valranoth uses Titanium Ribs to trash Black Orchestra.
valranoth trashes Déjà Vu due to damage.
valranoth places 1 power counter on Clan Vengeance.

valranoth spends 1  and  to play Amped Up.
valranoth uses Amped Up to gain  and suffer 1 brain damage.
valranoth places 1 power counter on Clan Vengeance.
valranoth uses Titanium Ribs to trash Mad Dash.
valranoth trashes I've Had Worse due to damage.

!valranoth uses a command: /take-meat 1
valranoth uses Titanium Ribs to trash Amped Up.

**Comment by JoelCFC25** [comment]
Thanks for the report. Line 837 in Titanium Ribs should read: `(damage-defer state side dtype 0)` instead of the current `(damage-defer state side :meat 0)`.
