### ISSUE TITLE
Fairchild series allow invalid choices

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2461]
The Fairchild ice series have subroutines that allow the runner to choose between paying credits or trashing installed cards. According to ANCUR rulings, the runner must choose an option that they can fulfill, if any.

More specifically: If no cards are installed, they must pay credits. If they don't have enough credits, they must trash an installed card. If they have fewer than the requisite credits AND have no installed cards, the subroutine does nothing.

Jinteki.net seems to allow the runner to select an option that they cannot fulfill, when they are able to fulfill the other.

**Comment by JoelCFC25** [comment]
There are countless things the site allows users to do that technically they should not be able to--but yes, these subroutines could be improved.

**Comment by danhut** [comment]
I don't know if this is implementable in a clean fashion.  For example, it is hard to know if someone can pay due to things like Ghost Runner.  I think we need to rely in the players here.

**Comment by JoelCFC25** [comment]
Agreed, sources of eligible credits that aren't in your pool are the problem with reliably assessing if the Runner can pay.

**Comment by Saintis** [comment]
I think this will rely on runner and corp knowing the correct interaction and will not be fixed.
