### ISSUE TITLE
Stimhack deals double damage with Titanium Ribs

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#2466]
**_Situation:_** Runner plays Stimhack with Titanium Ribs installed. 

**_Expected Result:_** At the end of the run, Stimhack deals 1 brain damage. Titanium Ribs allows the runner to select which card is trashed from the damage.

**_Actual Result:_** At the end of the run, Stimhack deals 1 brain damage. Titanium Ribs allows the runner to select which card is trashed. After that is resolved, the runner takes an additional point of brain damage.

**Example Log**
valranoth spends  to play Stimhack.
valranoth jacks out.
valranoth uses Stimhack to take 1 brain damage.
valranoth uses Titanium Ribs to trash Frantic Coding.
valranoth places 1 power counter on Clan Vengeance.
valranoth trashes Medium due to damage.

======

Hope you folks are doing alright. Thanks for the hard work you put into making this a fun platform.

**Comment by JoelCFC25** [comment]
When did this happen? This should have been fixed at #2455.

**Comment by PesiTheWizard** [comment]
Tested just now. Still happens. Main server.

**Comment by JoelCFC25** [comment]
Fascinating.

**Comment by PesiTheWizard** [comment]
Reported in chat again just now. This will probably be noticed more as more people play Clan Vengeance.
