### ISSUE TITLE
Various less important things.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2469]
- [x] **1)** Using Top Hat doesn't tell the corp what # card from the top was accessed.
- [x] **2)** An Exploratory Romp run technically ends before the card to lose counters is chosen. Corp could abuse this unintentionally.
- [x] **3)** Using Information Sifting gives 2 accessing logs for each card accessed.
- [x] **4)** Accessing Mumbad Virtual Tour with Neutralize All Threats installed and not being able to pay for it gives a lot more yellow warnings than one would expect.
- [x] **5)** First Responders doesn't care who did the damage.
- [ ] **6)** Apocalypse'd runner cards stop being active without triggering leave-play. Good for Muertos Gang Member, bad for Origami and cards that define an ability like Raymond Flint. (TODO: Encompasses enough to warrant it's own issue)
~~**7)** Manually increasing Bad Publicity with the control panel seems to trigger Raymond Flint.~~
*Probably not actually a bug*
- [x] **8)** Playing Möbius with Doppelgänger installed can mess things up somehow so that the runner gains 4 credits on every successful R&D run, just like the first bug with it. This can build up when playing other Möbii. Playing Möbius with Same Old Thing sometimes doesn't make the 2nd run happen.
- [x] **9a)** Using Sacrifice to forfeit an agenda worth -1 points causes corp to lose 1 credit and gain 1 Bad Publicity. This happens weather it's a 0-pointer with Political Graffiti or a -1point ambush that has made it's way to the corp's score area.
~~**9b)** Sacrificing an "Political Graffiti"-ed agenda this way refunds the lost agenda points twice over. After sacrificing a 0-pointer with 3 Graffitis, then scoring a 2-pointer, the corp had 5 agenda points. (The 2-pointer was Corporate War. Having a negative credit balance when doing so brings it up to 0.)~~
*Is a PG-only issue*
- [x] **10)** Haas-Bioroid: Stronger Together and Employee Strike interact strangely. Strengths seem to not be updated until a run is made. Can lead to a visual situation where if the current goes away and then a bioroid is rezzed outside of a run, some of them have the strength bonus and some don't.
- [x] **11)** Installing ICE with a scored ABT doesn't ignore the additional install cost of Network Exchange.

**Comment by JoelCFC25** [comment]
2 and 5 are easy, at any rate...7 is expected because Raymond uses a watch state. 

6 just makes me cringe, been over that ground so many times I can't bear to look at it anymore.

**Comment by JoelCFC25** [comment]
Have identified previous erroneous fix for Möbius and it'll be patched soon.

**Comment by JoelCFC25** [comment]
For 10, the problem lies in the `enable-identity` function. Even if you gave HB:ST an `:effect` to run `update-all-ice` (currently doesn't have one) when ES leaves play, the aforementioned function runs an identity's effect before it registers events, so nothing would happen.

**Comment by danhut** [comment]
Number 4 is "interesting".  The same toasts are shown multiple times on the UI - it is not some weird looping function call at least.

I assume this is something to do with having multiple simultaneous toasts - from can-pay? and MVC itself.  And then something to do with how this interacts on the client side.  See picture here- with a timestamp replacing the normal message.
<img width="275" alt="screen shot 2017-04-16 at 7 57 33 pm" src="https://cloud.githubusercontent.com/assets/11830223/25071417/810e7226-22e0-11e7-9e66-459b98a1182e.png">

**Comment by danhut** [comment]
For 9a - do you agree the corp should not be able to target agendas worth zero or less?

**Comment by JoelCFC25** [comment]
9a: Correct, agendas worth 0 or less cannot be targeted by Sacrifice.

**Comment by PesiTheWizard** [comment]
I just had issue 4 happen with Code Siphon, fetching a program that resulted in -1 Memory while taking a tag from it. It alternated Yellow and Red warnings.

**Comment by PesiTheWizard** [comment]
For #6, Would it be possible to create a :turned-facedown trigger that can be added to relevant cards, copying the :leave-play ?

**Comment by Saintis** [comment]
Issue 6 might get solved if we decide to go ahead with a card definition restructure.

**Comment by PesiTheWizard** [comment]
I think it's time to close this one.
