### ISSUE TITLE
Datasucker strength reduction carries to next ICE

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#247]
If a piece of ICE is destroyed by lowering strength with parasite-datasucker, then the strength reduction seems to be passed to the next ICE defending the server.

(I had encountered this in an older version, but didn't have time to report it at the time, I couldn't see a report for it, it may already have been fixed, if so then sorry!)

**Comment by nealterrell** [comment]
Thanks for the report. (Note to self) This occurs because Runner's `continue` will only trigger `:ice-passed` if the ice at the current run position is still there, which it is not. Need to trigger `:ice-passed` regardless of whether the ice is still there.
