### ISSUE TITLE
NASX not triggering

### ISSUE THREAD

**Issue by darkmite2** [mtgred/netrunner#2473]
I was using NASX and never got any prompts to pay $2 to add counters when IUSE would trigger. I'm not sure if it triggers off any other card or not, as game play stopped.

**Comment by JoelCFC25** [comment]
This card needs an `:implementation` note to signal that the adding of power counters must be done manually (although this is listed as manually triggered in the [card status sheet](https://docs.google.com/spreadsheets/d/1ICv19cNjSaW9C-DoEEGH3iFt09PBTob4CAutGex0gnE/pubhtml)). There no events in the system capable of indicating "you just gained credits from a card ability".
