### ISSUE TITLE
Excalibur/Offer you cant refuse interaction

### ISSUE THREAD

**Issue by argon-wolf** [mtgred/netrunner#2474]
Runner ran and triggered an Excalibur subroutine (cannot make another run this turn) on their turn. Corp then played Offer You Cant Refuse on their turn and the runner opted to run. Run fizzled. 

Reset game state and attempted again with same result

Video: https://youtu.be/iBs9WoqLB7g

**Comment by JoelCFC25** [comment]
Thanks for the report. This is legacy code that predates the `turn-flag` system. It's putting a key in the Runner's register, which is not wiped until start of the Runner's next turn.
