### ISSUE TITLE
Clicking Whizzard ID as Corp

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#248]
I clicked on Whizzard's ID while the runner was accesssing cards from R&D, and then ... well this happened: 

![idclickbug](https://cloud.githubusercontent.com/assets/6743892/8158623/ba86140a-1356-11e5-8335-f19ca30b5b5e.png)

For reference and in case it makes a difference; I was playing Tennin.

**Comment by JoelCFC25** [comment]
I've seen this ID glitch happen occasionally--once I was playing NBN:MN against Quetzal and the runner player clicked on *my* ID (for some reason known only to him). His Quetzal disappeared and was replaced by another copy of my NBN:MN.

**Comment by Quarg** [comment]
Based on that I might guess that it's to do with the IDs using reccuring credits.

**Comment by nealterrell** [comment]
Actually it is probably for any identity that has an active ability. When the ability is used, `(update!)` is called to update the card. There is special logic for identities in `update!`... if an identity ability is used, the code assumes it's the acting player's identity, and updates that player's state with the information of the OTHER player's identity.

**Comment by mtgred** [comment]
Thanks for reporting the issue. This has been fixed.
