### ISSUE TITLE
Feature Request: Console Commands

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#2484]
Issues specific to Microsoft Edge Browser include the inability to move cards by clicking and dragging. If a player makes an error, the game state can be difficult if not impossible to rectify. The addition of the following console command would allow board states to be fixed

Return targeted card (installed or in archives/heap) to HQ/Grip

Also, the "Console Commands" paragraph under the "Help" doesn't list all the available commands

**Comment by danhut** [comment]
All console commands are there again.  Will be fixed in next code push

**Comment by danhut** [comment]
Added a move-hand command for this.  Will be in next code push
