### ISSUE TITLE
dragging card to heap causes fatal error.

### ISSUE THREAD

**Issue by posttrib777** [mtgred/netrunner#2493]
When attempting to drag cards to heap my game crashes and I instantly disconnect.

**Comment by JoelCFC25** [comment]
What web browser?

**Comment by posttrib777** [comment]
Safari

**Comment by JoelCFC25** [comment]
OK. If you can supply considerably more detail, it's possible this can be investigated. Was it on a mobile device? What card were you dragging to the heap? Was it in the midst of another ability being resolved? Does it happen with any card? Can you provide a precise series of reproduction steps?

**Comment by posttrib777** [comment]
Sure Joe. I'll do my best to help with the details. 

I'm using my IMac 

If I overdraw and at turns end, discard. Any card will bring the crash.
One of the last games I played I was playing against Housekeeping which demands a discard upon installing the first card. That worked fine. I'm also able to use the command to discard but the problem is that I'm not in the habit to do so. /discard#n

It appears to be the drag to heap motion that is problematic no matter what the circumstances are for discard obligation.

Let me know if you feel you need any more info.

Ben

**Comment by JoelCFC25** [comment]
Safari and MacOS versions might help. Surprised we haven't gotten a report of this before, Safari should be pretty common. I've used Safari almost daily for 2 years and have never seen this--currently on Safari Version 10.1 (12603.1.30.0.34) and Sierra 10.12.4.

Tricky one!

**Comment by posttrib777** [comment]
Sorry for the late reply Joe.

I'm running 10.11.6

El Capitan

**Comment by danhut** [comment]
I tried on Safari Version 10.0.1 (11602.2.14.0.7)  -no issues.

**Comment by posttrib777** [comment]
I’ve scheduled a service appointment with apple to see if my difficulty is local.

I will let you know what the result is if I find the problem is on my end.

Thanks for the investigative work Joe and Dan.

Regards,

Ben

**Comment by JoelCFC25** [comment]
Will reopen if needed in the future, for now I don't know what can be done about this.
