### ISSUE TITLE
"Lose all credits" + BP = going to negative credits.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2494]
As the title says, when Heinlein Grid zeroes out the runner's credit pool, the (N this run) part remains. When the run ends they lose those, going to < 0.

**Comment by JoelCFC25** [comment]
Just add this to Heinlein Grid's current `:effect`: 

`(lose :runner :run-credit :all)`

**Comment by PesiTheWizard** [comment]
Testing reveals that this also happens when popping Sacrificial Clone, and when Installing Theophilius Bagbiter from a Street Peddler(provided you have more temporary credits than Bagbiter's cost).

(Yet to be checked: Universal Connectivity Fee. Is there any way to play operations during runs?)
