### ISSUE TITLE
Strange glitch?

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2495]
Friend was playing Smoke against my Palana, and played a Legwork. The following happened:

> Segin spends 2(C) and @ to play Legwork.
> Zankoku spends 2(C) to rez Himitsu-Bako.
> Zankoku has no further action.
> Segin uses Paperclip to increase strength by 1 and break 1 barrier subroutine.
> Segin continues the run.
> Zankoku has no further action.
> Segin uses Desperado to gain 1(C).
> Segin accesses DNA Tracker from HQ.
> Segin accesses from .

Then the run abruptly ended. No bugs occurred.

**Comment by danhut** [comment]
What else was in play?

**Comment by JoelCFC25** [comment]
Can you ask the friend if he/she was clicking through prompts very quickly?
