### ISSUE TITLE
Top Hat revealing accessed cards to corp

### ISSUE THREAD

**Issue by bubbathegoat** [mtgred/netrunner#2496]
Currently when the Runner is accessing one of the top 5 cards of R&D using Top Hat, that card is revealed to the Corp.  I believe this card is simply accessed, so the corp should not know what card was accessed, but should know which number from the top the card was.

**Comment by JoelCFC25** [comment]
I think `handle-access` would need to be altered to take a `:silent true` parameter or similar. Right now it's calling `msg-handle-access` in the middle of this function, which is what's revealing the title of the card.
