### ISSUE TITLE
Freeze when trashing Jackson Howard

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#250]
He was in an unprotected server. I accessed. It asked if I paid 3 to trash. When I clicked yes everything froze up (including chat). Tried clicking no but already frozen

**Comment by nealterrell** [comment]
Do you remember who your opponent was, and what other cards were on the table? (Especially anything affecting trash or rez costs.)

**Comment by qmsm** [comment]
I was playing Hechigenio (but I fear that's not what you meant). I think he was playing Blue Sun. Afraid I can't remember any other specifics (will screenshot next time).

**Comment by qmsm** [comment]
I wondered afterwards if Jackson Howard had ever been trashed before? Because usually he gets 'removed from game' for his ability.

**Comment by qmsm** [comment]
I know now that you can trash Jackson without the game crashing so I'm gonna say this was a one off fluke and close the issue.
