### ISSUE TITLE
Oracle May doesn't print cost to log

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2502]
When used, Oracle May's message is as follows:
[player name] uses Oracle May, names [card type] and reveals [card name].

It should read something like:
[player name] spends a [click] to use Oracle May, names [card type] and reveals [card name].

I noticed the same problem with Paperclip:
[player name] uses Paperclip to increase strength by 3 and break 3 barrier subroutines.

Maybe this?
[player name] spends 3 [credits] to use Paperclip, increase its strength by 3 and break 3 barrier subroutines.

**Comment by JoelCFC25** [comment]
Similar to #2503--the report of costs spent comes when you use `:msg`. Oracle May cannot because the contents of the message differs so much based on the outcome. When building log messages with `system-msg` you'd have to insert the costs paid manually.
