### ISSUE TITLE
Many extra copies of SMC in stack after LEVY

### ISSUE THREAD

**Issue by TugtetguT** [mtgred/netrunner#2508]
![skaermbillede 2017-04-19 kl 13 26 41](https://cloud.githubusercontent.com/assets/24543646/25178266/6dbd32f8-2505-11e7-801b-1ad048db9c15.png)

From the issues thread it looks like the MU and hosted SMC issue is already reported, I think this might be related? Anyway played LEVY and found 7 copies of SMC in my stack, they were fully functional, but when discarded the extra copies disappeared.

- Tug

**Comment by JoelCFC25** [comment]
95% sure this was fixed by #2512.
