### ISSUE TITLE
Non-MWL Compliant decks listed as "Invalid" versus "Casual"

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#2509]
With the new MWL being implemented on jnet. Casual decks that do not follow the new MWL guidelines, but follow basic deck building rules (ie. core only decks) are being listed as "invalid" as opposed to "casual only".

**Comment by danhut** [comment]
Already resolved in next code push.  I had not quite comprehended what Casual meant when I updated the deck builder.

Please close this issue

**Comment by danhut** [comment]
https://github.com/mtgred/netrunner/pull/2497
