### ISSUE TITLE
Unable to create casual labeled (core only) Non-MWL decks

### ISSUE THREAD

**Issue by FlyingZergling** [mtgred/netrunner#2510]
It looks like NAPD Most Wanted List has been tied pretty strongly to Basic Deckbuilding, I'm unable to engineer a deck that follows basic deckbuilding rules but not MWL without it being labelled Invalid, or rather some people in chat have noticed a change and they don't have Github accounts.

Normally a deck that does so is labelled Casual Only, and this is basically a requirement for people playing in formats like Core-Only. It worked until a while ago it seems, so something recent broke it a little and it's hard to notice right away because I'm guessing the majority of users go for full tournament compliance anyway. :/

**Comment by danhut** [comment]
Already resolved in next code push.  I had not quite comprehended what Casual meant when I updated the deck builder.

Please close this issue

**Comment by danhut** [comment]
Here by the way: https://github.com/mtgred/netrunner/pull/2497
