### ISSUE TITLE
MCA Informant causes Film Critic to create errors

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2516]
I hosted an agenda on Film Critic, then corp played MCA Informant on it. I attempted to use the double click ability in order to add the agenda to my score area, but all it did was spend my clicks without actually doing anything. It might've been attempting to add the hosted MCA Informant, instead?

**Comment by JoelCFC25** [comment]
Thanks for the report. 

Line 520 of Film Critic reads: 
`:effect (req (let [c (move state :runner (first (:hosted card)) :scored)]`

So it's "blindly" moving the first thing in the list of what's hosted on Film Critic to the score area. Prior to MCA there would have been no situation in which anything else could have gotten hosted. Maybe it needs to scan for the first agenda it finds, or use card targeting.
