### ISSUE TITLE
During Interdiction, corp is still able to rez cards after the runner ends turn

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2517]
Interdiction blocks the corp from rezzing non-ice cards on the runner's turn.

The rez/ability window at the end of the runner's turn should still be part of the runner's turn, but it seems to be treated otherwise, as the corp is somehow allowed to rez assets after the runner has clicked End Turn but before the corp has clicked Start Turn.

**Comment by JoelCFC25** [comment]
See #696 for the original discussion of how the end of turn paid ability window is handled. For awhile we had a feature to handle this correctly (see #1337), but lamentably it was rolled back due to player misunderstanding and people constantly using it when they didn't need to.

**Comment by Saintis** [comment]
Do note that the corp has a window to rezz non-ice cards in the window at 1.1, before "start of turn" triggers happen. (See FAQ 1.6). 

I would say that makes the current interaction correct with regards to Interdiction.

**Comment by Saintis** [comment]
I say this is working as intended.
