### ISSUE TITLE
fairchild in deckbuilder

### ISSUE THREAD

**Issue by Tinend** [mtgred/netrunner#2518]
I uploaded a deck (a txt-file). I used the fairchild ices, more specific:
2x fairchild 1.0
2x fairchild 2.0
2x fairchild 3.0
1x fairchild
The deckbuilder interpreted it as:
2x fairchild
2x fairchild
2x fairchild
1x fairchild
And assumed it was a perfectly legal deck.
So there are 2 minor bugs:
The deckbuilder didn't recognise fairchild x.0 and the deckbuilder didn't recognise the deck it as incorrect.

Edit:
Example Text:
Deck Created with CardGameDB.com Android: Netrunner Deckbuilder

Total Cards: (49)

Identity: 
1x Haas-Bioroid (Intervention) 

Agenda: (9)
3x Accelerated Beta Test (Core) 
1x Corporate Sales Team (Business First)  
2x Global Food Initiative (Data and Destiny) ■ ■ 
3x Project Vitruvius (Cyber Exodus) 

Asset: (13)
3x Adonis Campaign (Core) 
2x Jackson Howard (Opening Moves) ■ ■ 
2x Brain-Taping Facility  (The Valley) 
2x Estelle Moon (Terminal Directive) 
1x Eve Campaign (Humanity's Shadow) 
3x Marilyn Campaign (Terminal Directive) 

ICE: (18)
1x Fairchild (Martial Law) 
3x Fairchild 1.0 (23 Seconds) 
3x Fairchild 2.0 (Blood Money) 
1x Fairchild 3.0 (Escalation) 
1x Heimdall 1.0 (Core) 
3x Ichi 1.0 (Core) 
1x Markus 1.0 (The Source) 
1x Ravana 1.0 (The Liberated Mind) 
1x Sherlock 2.0 (23 Seconds) 
1x Zed 2.0 (Daedalus Complex) 
2x Eli 2.0 (Terminal Directive) 

Operation: (8)
2x Enhanced Login Protocol (The Spaces Between) 
3x Friends in High Places (Martial Law) 
3x Biotic Labor (Core) 

Upgrade: (1)
1x Ash 2X3ZB9CY (What Lies Ahead)

**Comment by danhut** [comment]
Which browser are you using? Works fine for me in firefox

Or are you keeping the data pack in the brackets? We don't support that. ie. This will not work:
1x Fairchild (Martial Law)
3x Fairchild 1.0 (23 Seconds)
3x Fairchild 2.0 (Blood Money)
1x Fairchild 3.0 (Escalation)

But this will:
2x fairchild 1.0
2x fairchild 2.0
2x fairchild 3.0
1x fairchild

**Comment by Tinend** [comment]
I'm using firefox. I just copied the text format from http://www.cardgamedb.com/index.php/androidnetrunner/android-netrunner-deckbuilder . That always worked fine doing that, even if the isn't as you describe it.

Of course I can easily fix the problem each time by hand, that isn't the problem. However it was a little bit annoying to finding myself playing a game where my deck didn't make sense. Since I know the problem now I will not have trubble by it, but others might. (No idea, where they get their text files from) I'd be fine if I get some kind of message that the deck isn't what it is supposed to be. (Since there were to many Fairchilds)

 

Yours faithfully

Ulrich Brodowksy

 

Gesendet: Sonntag, 30. April 2017 um 00:17 Uhr
Von: "Dan Hutchins" <notifications@github.com>
An: mtgred/netrunner <netrunner@noreply.github.com>
Cc: Tinend <ulrich.brodowsky@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [mtgred/netrunner] fairchild in deckbuilder (#2518)


Which browser are you using? Works fine for me in firefox

Or are you keeping the data pack in the brackets? We don't support that. ie. This will not work:
1x Fairchild (Martial Law)
3x Fairchild 1.0 (23 Seconds)
3x Fairchild 2.0 (Blood Money)
1x Fairchild 3.0 (Escalation)

But this will:
2x fairchild 1.0
2x fairchild 2.0
2x fairchild 3.0
1x fairchild

**Comment by danhut** [comment]
We don't support that format - it can cause the issues you are seeing.
If you look at netrunner.db there is a Jinteki.net specific format which strips the pack names as I described.  The Text format is not supported.

**Comment by Tinend** [comment]
As I said, the problem wasn't that the format wasn't supported. While that is true, I can easily fix that each time I create a new deck. It was rather that the illegal deck was considered legal. Since I like playing on Jinteki.net and haven't done anything in exchange, (except allowing others to play against me) I was trying to be helpful. If you have more pressing issues to solve, I can understand that.

However, I want to add, that you can abuse this bug to cheat. Contrary to other ways to cheat, your opponent has a good chance of never realising what has happened, since you never see his whole deck. So they get away with it.

Of course most people don't want to cheat and those who do might never stumble upon this bug. So maybe it can simply be ignored. Still for completeness:

Here is a "NBN: Controlling the Message" Deck that is considered legal to illustrate how it works. This example isn't playable but you could always do it in a smarter way:


1 Project Bale sfdsa 
3 Project Bale sfdsaer 
3 Project Bale sfdsa d
3 Project Bale sfdsa rt
3 Project Bale sfdsa s
3 Jackson Howard dsf
3 Jackson Howard fds
3 Jackson Howard fwsd
3 Jackson Howard fwe
3 Jackson Howard gr
3 Jackson Howard fdsfga
3 Jackson Howard dgfreh
3 Jackson Howard rehthvcx
3 Jackson Howard reg
3 Jackson Howard drezhg
3 Jackson Howard fhteh
3 Jackson Howard gerhth
3 Jackson Howard greqy
3 Jackson Howard erghr
3 Jackson Howard greh4t
3 Jackson Howard hre64u5

**Comment by danhut** [comment]
I understand now.  Thanks.  It is pretty interesting and I will take a look.  We do check for max 3 copies of a card already - so something funky is going on.

**Comment by Saintis** [comment]
I would guess current implementation checks for multiple copies using exact name and not the "matching" name

**Comment by danhut** [comment]
I don't really understand the text input processing yet.  I have a fix at least which is to just reload the decks when you save the new one.  Probably better to fix on input if I can,
