### ISSUE TITLE
Have to select Chimera subtype twice

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#252]
This is possibly the lowest priority issue ever, but if it's never logged it'll never be looked at.

Anyway, you get prompted to select a subtype, you click one, the chat window confirms that you've selected it, but the choose subtype prompt stays there. If you select it again, the chat window confirms it again and then it disappears.

Obviously clicking it twice is not a big issue. But you do pause for a few seconds waiting to see if it's lag, before realising it needs another nudge. And I've no idea what would happen if you tried selecting a different subtype second time around.

**Comment by mtgred** [comment]
A fix has been deployed this morning. It should work correctly now.

**Comment by JoelCFC25** [comment]
Confirmed that this one has been fixed by 009acdbea0b81d90d64c6eec9f832054e1631e69. @qmsm, you can close it. :+1:

**Comment by qmsm** [comment]
Roger
