### ISSUE TITLE
Marilyn Campaign shuffles into deck after draw when it runs out

### ISSUE THREAD

**Issue by ouroboros8** [mtgred/netrunner#2520]
#2516 When a Marilyn Campaign is trashed at the beginning of turn after the last two credits are removed from it, mandatory draw occurs before (or simultaneously with?) the prompt to shuffle the campaign back into the deck.

What should happen is that the last two credits should be removed from the campaign, and the player prompted to choose whether to shuffle, before mandatory draw.

**Comment by JoelCFC25** [comment]
One approach for this would be to add:
`{:corp-phase-12 (req (= 2 (get-in card [:counter :credit])))}`

So when Marilyn is about to be emptied, the Corp gets the mini-window to manually fire start of turn items before taking the mandatory draw. Then Marilyn will be shuffled back in before you perform the draw.
