### ISSUE TITLE
The Shadow Net & Fisk Investment Seminar interaction issue 

### ISSUE THREAD

**Issue by TheShadowNet** [mtgred/netrunner#2522]
**Prerequisites:** 
1) The Runner has The Shadow Net installed
2) The Runner has Fisk Investment Seminar in their heap. 

**Actions** 
1) On the runner's first click the use The Shadow Net 
2) The runner selects Fisk Investment Seminar as the event to be played from their heap. 
3) The runner selects an agenda (actual agenda or fan site) to be forfeited. 

**Expected result:** 
1) The agenda is forfeited 
2) Fisk Investment Seminar triggers (Runner and Corp both draw 3 cards) 

**Actually Result:** 
1) The agenda is forfeited 
2) Fisk Investment Seminar does **not** trigger.

**Comment by JoelCFC25** [comment]
I am not addressing this until the Terminal Directive UFAQ is released.

**Comment by JoelCFC25** [comment]
This doesn't augur well for your interpretation though: [Priority events on ANCUR](http://ancur.wikia.com/wiki/Priority)

**Comment by JoelCFC25** [comment]
The [Terminal Directive UFAQ is now released](https://netrunnerdb.com/en/set/td/rulings). The Shadow Net cannot be used to play Priority events.
