### ISSUE TITLE
The Proffesor is counting wrongly new Universal Influence

### ISSUE THREAD

**Issue by Reznorcito** [mtgred/netrunner#2525]
I just added a "Cerberus Lady H1" to an Professor deck and it is counting it as 1 influence spent when it is the first copy of the program so that influence shouldn't be counting at all.

FYI, this was stated by Michael Boggs on his interview on "Run Last Click".

**Comment by danhut** [comment]
Simple to fix - do you have a link to show this?  Maybe on ANCUR or an UFAQ

**Comment by gereons** [comment]
I don't think there's a written statement/clarification yet, but go to http://runlastclick.blogspot.de/2017/05/episode-77-mwl-12-w-michael-boggs.html and skip to the 41 minute mark to hear Michael Boggs explain the intent.
