### ISSUE TITLE
Dragging cards from grip to heap for discard says "trashing" of the card.

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#2527]
When you have too many cards in grip, you have to discard at the end of the turn. This is the only instance of the game where cards enter the heap as "discarded" instead of "trashed" (Important because of Skorpios). The #1 use case for dragging cards from grip to heap is discarding at the end of the turn, and yet when you do the drag the Jinteki.net log says uses the word "trashes" instead of "discards". 

Easy fix: Change the word trashes to discards in the log for this operation
Harder fix: Create a "discard" phase when the player has more cards than hand size, and change the message appropriately.

Ideally with an informed player they won't try and RFG a discarded card but even in Competitive tab I've had to challenge someone RFGing a discarded Black Orchestra.

**Comment by FarCryFromHuman** [comment]
They might have code in place that knows what zone a card has been moved from when it enters a new zone. If so, this might be rather trivial to fix, while leaving the trash message intact when cards are trashed from other zones. Fingers crossed!

**Comment by JoelCFC25** [comment]
It is the `move-card` function [here](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core/actions.clj#L61-L98).
