### ISSUE TITLE
Illegal Arms Factory bad pub interaction

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#2529]
Illegal Arms Factory says, "If the Runner trashes Illegal Arms Factory while it is installed, etc"

It is currently implemented as any trash effect:

````clojure
 {:derezzed-events {:runner-turn-ends corp-rez-toast}
  :events {:corp-turn-begins ability}
  :abilities [ability]
  :trash-effect {:req (req (= :servers (first (:previous-zone card))))
                 :effect (effect (gain :corp :bad-publicity 1)
                                 (system-msg :corp (str "takes 1 bad publicity from Illegal Arms Factory")))}})
````

I don't know enough about Clojure to make the change myself, but it seems like an additional condition on the `trash-effect` statement should do the trick:

````clojure
 :trash-effect {:when-inactive false
                :req (req (= :servers (first (:previous-zone card))))
````

Depending on how `:when-inactive false` works, this should also take care of the [UFAQ ruling](https://netrunnerdb.com/en/card/13045) that it only gives a bad pub when rezzed.

**Comment by SugoiFactory** [comment]
It should also be noted that the corp overwriting it with an agenda or asset should not give bad publicity.

**Comment by JoelCFC25** [comment]
Thanks. I'm aware of both of these issues, but just have no prospect of time to work on it anytime soon.

**Comment by danhut** [comment]
I fixed the part mentioned by @SugoiFactory 

Can you explain the original issue?  Right now the trash-effect will only fire if the card is installed & rezzed - this is default behaviour.  I don't see the effect firing from any other runner action.
