### ISSUE TITLE
Dbs not drawing when triggered in both runner and corp turns

### ISSUE THREAD

**Issue by lpoulter** [mtgred/netrunner#2532]
If dbs triggers on runner turn it only draws one on corps mandatory draw.

**Comment by danhut** [comment]
I just tried it with Fisk to force this to happen and it works fine.  Can you give steps to reproduce? ta!

**Comment by JoelCFC25** [comment]
I have a suspicion that in the original scenario, the first ability that triggered a Corp draw was activated after the Runner had already hit End Turn, in which case DBS would be "used" for the duration of the next Corp turn.

**Comment by JoelCFC25** [comment]
Any further instances of this, or was anyone able to confirm that my hunch was correct?

**Comment by JoelCFC25** [comment]
This can only be fixed by resurrecting the features in #1337.
