### ISSUE TITLE
[QOL] Discard wording (for Skorpios)

### ISSUE THREAD

**Issue by Repulze** [mtgred/netrunner#2533]
Just a small, QOL suggestion.

Currently when a player discards a card manually, the log says "(the Corp) **trashes** a card from their HQ" or "(the Runner) **trashes** X from their Grip". It would be clearer and technically accurate if it said: "(the Corp)  **discards** a from their HQ" and "(the Runner) **discards** X from their Grip" instead.

Great work as usual guys

**Comment by danhut** [comment]
Already fixed. Will be live at some point. Please close this.

Sent from my iPhone

On 7 May 2017, at 1:46 pm, Repulze <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a small, QOL suggestion.

Currently when a player discards a card manually, the log says "(the Corp) trashes a card from their HQ" or "(the Runner) trashes X from their Grip". It would be clearer and technically accurate if it said: "(the Corp) discards a from their HQ" and "(the Runner) discards X from their Grip" instead.

Great work as usual guys

-
