### ISSUE TITLE
The Future Perfect and Film Critic interaction causes runner inability to select Jack Out/Successful Run

### ISSUE THREAD

**Issue by zelmor** [mtgred/netrunner#2534]
Runner made normal run on RnD, but gets stuck on the Jack Out/Successful Run box. Can interact with button Jack Out (visible in chat log) but nothing happens. From chat:

mauichris continues the run.
Zelmor has no further action.
mauichris uses Desperado to gain 1 .
mauichris accesses an unseen card from R&D.
Zelmor uses The Future Perfect to start a psi game.
mauichris uses Film Critic to host The Future Perfect instead of accessing it.
mauichris spends  and 5  to play Sure Gamble.
mauichris uses Sure Gamble to gain 9 .
mauichris uses Desperado to gain 1 .
mauichris accesses an unseen card from R&D.
!mauichris uses a command: /close-prompt
!mauichris uses a command: /close-prompt
mauichris jacks out.
mauichris jacks out.
!mauichris uses a command: /close-prompt
mauichris jacks out.

Using /end-run didn't fix the issue either.
![future_perfect_bug](https://cloud.githubusercontent.com/assets/4656427/25786023/0e861e20-338e-11e7-8049-874f1341a91d.png)

**Comment by danhut** [comment]
The issue here seems to be if the Psi Game has started before you hit Film Critic.  If you hit it when prompted with "you must access" it is fine.
