### ISSUE TITLE
Hosting Adept on Dhegdheer after installing does not properly boost strength

### ISSUE THREAD

**Issue by Kaethela** [mtgred/netrunner#2535]
Installing Adept on Dhegdheer after the former is already installed (e.g. through SMC) your MU will update properly but Adept will still count it's own MU and won't have increased strength. This can be fixed by moving Adept back to hand and reinstalling it directly with Dhegdheer.

**Comment by danhut** [comment]
Can you provide exact steps ?  I tried this several times and could not reproduce - even by popping an SMC.

**Comment by Kaethela** [comment]
Sure. Install Dhegdheer (method irrelevant), install SMC, pop SMC for Adept, use Dhegdheer's "host an installed program" function to host Adept. Your available MU will update but Adept's strength will not. Screenshot of end result attached, I was able to reproduce this in a test game a few minutes ago.
![adept hosted](https://cloud.githubusercontent.com/assets/22601892/26030093/f408b828-3815-11e7-8cee-270f1df6dd07.PNG)

**Comment by Ingwar** [comment]
The same issue also occurs with Savant hosted on Dhegdheer.
