### ISSUE TITLE
Problems with Aryabhata Tech

### ISSUE THREAD

**Issue by MrLongbottom** [mtgred/netrunner#2541]
While playing with a deck using 3x [Aryabhata Tech](https://netrunnerdb.com/en/card/10070), I noticed a few things not functioning the way I would have imagined.

I should note that since these problems all have something to do with trace and therefore require two players to test, I could be wrong about this stuff. All of these problems are just from my experience actually playing with the card.

Also I'm not a rules expert so some of these "problems" may just be me misunderstanding how the card is supposed to work

- [x] If the runner has no credit to lose you don't get the credit for a successful trace.
- [ ] If the runner trashes a [Aryabhata Tech](https://netrunnerdb.com/en/card/10070) and there is a ability that triggers on the trashing that initiates a trace (like [NBN: Controlling the Message](https://netrunnerdb.com/en/card/11017)) then [Aryabhata Tech](https://netrunnerdb.com/en/card/10070) effect will still trigger even though it should already be considered trashed for the first ability to trigger. (this might just be a problem with [NBN: Controlling the Message](https://netrunnerdb.com/en/card/11017) not allowing the trashing to go through at the correct timing).

**Comment by JoelCFC25** [comment]
Bullet point 2 is a longstanding known bug, but nothing specific to CtM or Aryabhata. It's a system bug related to when trash effects fire relative to when trashing should actually occur.

**Comment by danhut** [comment]
For Bullet 1 - i tested and it works fine.  Maybe you had some other cards in play that effect it.

In addition you can see in the core they are distinct actions:
```
(effect (gain :credit 1)
(lose :runner :credit 1))
```
Let us know if you find the trigger.

**Comment by JoelCFC25** [comment]
I'm pretty sure this is fixed simply by tossing `(unregister-events state side card)` at the very start of the `resolve-trash` function. Not sure if anything else breaks yet.

**Comment by Saintis** [comment]
Can point 2 be solved with more application of `delayed-completion` perhaps?

**Comment by NoahTheDuke** [comment]
I "solved" this issue with regards to Jinja in #4353 by having Jinja's `req` see if it's on the trash-list. I tried expanding it to "everything" instead of just Jinja, but most abilities don't care if the card is on the trash-list, so it's hard.

**Comment by NoahTheDuke** [comment]
This has been fixed for a little while from the Trash Effects refactor.
