### ISSUE TITLE
Adam directives

### ISSUE THREAD

**Issue by mLodon** [mtgred/netrunner#2546]
When a game starts with Adam as the runner, the promt asks you to select your starting directives but none are shown.

The deck does not include any copies of the directives, but this hasn't been an issue before.

**Comment by JoelCFC25** [comment]
Can you confirm that you've done a forced refresh of the site since the update?

**Comment by danhut** [comment]
Can confirm this is broken until you do a forced refresh then it is fine.

**Comment by JamieRed** [comment]
Hi, i still have issues with Adam identity, i did the forced cache refresh but nothing happen.
Mac user

**Comment by mLodon** [comment]
I have, and still they won't show.

I'm on windows 10, using chrome and jankteki installed.

**Comment by mLodon** [comment]
Tried again today and the directives work just fine. 
Don't know if you did anything, but still; thanks! 👍
