### ISSUE TITLE
Rebirth In MaxX

### ISSUE THREAD

**Issue by SnarkAttack** [mtgred/netrunner#2547]
My opponent attempted to play Rebirth in MaxX to change into Whizzard, but rebirth did not actually change the ID. On their next starting turn, MaX still triggered, but with some unexpected trashing. 
Screenshot with chat text included.

![maxx jinteki bug](https://cloud.githubusercontent.com/assets/4582488/26286248/70875850-3e2e-11e7-8500-42e71a05807c.png)

**Comment by JoelCFC25** [comment]
Can you confirm that you've done a forced refresh of the site since the update?
