### ISSUE TITLE
1.1.1.1/cache refresh validation errors

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#2548]
I was just looking at the cache refresh reminders, somewhat telling you what cards are illegal in the format. My decks are showing Jemison Astronautics and Mind game as illegal, even though they came from the two most recent cycles. Relatively minor issue but something to maybe look at.

Edit: Checked using a stripped down version of one of my decks. Cards from Flashpoint and Red Sand are falsely being marked invalid.

**Comment by danhut** [comment]
Problem here is that we have future dated packs from the year 4096 in the database so the check for the two newest cycles does not work right:

```
netrunner.deckbuilder=> (sets-in-two-newest-cycles s)
({:name "Daedalus Complex", :available "2017-02-23", :cycle "Red sand"} {:name "Station One", :available "2017-03-23", :cycle "Red sand"} {:name "Earth's Scion", :available "4096-01-01", :cycle "Red sand"} {:name "Terminal Directive", :available "2017-04-27", :cycle "Terminal directive"} {:name "Blood and Water", :available "4096-01-01", :cycle "Red sand"} {:name "Free Mars", :available "4096-01-01", :cycle "Red sand"} {:name "Crimson Dust", :available "4096-01-01", :cycle "Red sand"})

```

So the function `sets-in-two-newest-cycles `needs a tweak to drop anything not yet released.

**Comment by JarekWarsaw** [comment]
Is it possible that `npm run fetch` wasn't run after release? Terminal Directive should not be included in `sets-in-two-newest-cycles` results. Function first filters out big boxes, but based on results it failed to do so.

>So the function `sets-in-two-newest-cycles` needs a tweak to drop anything not yet released.

It was intentionally designed to return all sets from newest cycle, even if some of them weren't released yet. We have another checkbox to warn about using not-yet-released cards.

**Comment by danhut** [comment]
Possible - let me ask on the Slack channel as I am not sure MT is watching here.

**Comment by snotz** [comment]
I have tested it with my server and the code is working fine.  Here's a clip showing that it works.
![screen shot 2017-05-22 at 9 57 39 am](https://cloud.githubusercontent.com/assets/28867005/26312473/b0beabce-3ed5-11e7-92c1-99f4489c418e.png)

**Comment by JarekWarsaw** [comment]
`sets-in-two-newest-cycles` should as a final step map `set` to `setname`. Later on `group-cards-from-restricted-sets` expects list of strings (names of sets), but gets mixed list of strings and objects.
