### ISSUE TITLE
Door to door and Jak Sinclair

### ISSUE THREAD

**Issue by afonsomota** [mtgred/netrunner#2549]
In one of my games a set of interactions provoked a strange behaviour.

Corp had a "Door to door" current active. When I triggered Jak Sinclair after taking clicks, the "Door  to door" trace would appear in the middle of the run. Both corp and runner used "/close-prompt" in order to do the trace manually later (since the runner is the active player). After the turn completion, "End the turn" does not appear, instead Take Clicks appears and it will only disappear after the "Door to Door" trace is completed. If the command "/close-prompt" is used the same thing happens after reducing the number of clicks to 0. "End the turn" will only appear after the "Door to door" trace is completed.

**Comment by JoelCFC25** [comment]
Thanks for the report. 

> When I triggered Jak Sinclair after taking clicks

This would be an easy thing to disallow by adding `:req (req (:runner-phase12 @state))` to Jak's ability, since it shouldn't be allowed to activate after you've taken clicks.
