### ISSUE TITLE
Adding R&D Interface to a deck

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#255]
When I start typing R&D in the 'Add cards' box it finds it in the list, but when I click on it it appears in the box as "R&amp;D Interface". When I press enter or click 'Add to deck' it then doesn't work (presumably trying to add a name that now doesn't match).

If I delete the offending amp; it still doesn't work immediately. The workaround is deleting and then retyping the e, but that's only learned from playing around. Other people may have given up?

In case it's a browser issue, I'm running Chrome 43.0.2357.124 m on Windows 7.

**Comment by JoelCFC25** [comment]
This is a long-standing issue (see #60). The solution for this card is to type directly into the Decklist area instead of using the Add Cards prompt.

**Comment by qmsm** [comment]
Ah, I searched on the first page but didn't dig deeper. My mistake
