### ISSUE TITLE
Rebirth bugged on at least criminal and shaper

### ISSUE THREAD

**Issue by Krachn** [mtgred/netrunner#2550]
Cannot pick all ID's, only 2: In the case of shaper its Ayla and Smoke.
Steps to reproduce:
1. Create a shaper deck (tested with kate) with rebirth.
2. Play rebirth
3. Prompt now only displays Ayla and Smoke

If you play as Ayla, only smoke appears in the prompt. Also tested with Criminal's gabriel.

Enforced refreshed before testing, as well as confirmed in chat for other users.

Does seem to be another issue than #2547

**Comment by danhut** [comment]
I can see this in the live server but not on my dev machine.  No clue unless it is the live database needing an update based on some recent changes in the deckbuilder.  Trying to find out if this got done.

**Comment by JarekWarsaw** [comment]
I've been debugging on production yesterday and it looks like db has been updated (regarding Cache Refresh related changes).

**Comment by danhut** [comment]
@JarekWarsaw Did you find a way to run figwheel on prod?  I really cannot fathom this issue as I don't see it on my laptop at all.  Given the rebirth looks at all cards in the atom @all-cards I am stumped.

**Comment by JarekWarsaw** [comment]
No, I've manually debugged client-side JS.
