### ISSUE TITLE
Scrubbed - not lowering str

### ISSUE THREAD

**Issue by darkmite2** [mtgred/netrunner#2551]
Scrubbed in play was not lowering the strength of the first piece of ICE encountered. ID being used was Null, if that matters.

**Comment by danhut** [comment]
Was anything else in play?  I just tested and it works fine in isolation, and with Null's ability included.

**Comment by darkmite2** [comment]
Yes. My bad.. Parasite was on first ICE encountered too.

**Comment by danhut** [comment]
No problems.  Can you please close this issue?
