### ISSUE TITLE
When running Hades Shard simultaneously when Jackson Howard is rezzed and accessed

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#2554]
Runner had Hades shard installed.
Corp rezzed Jackson Howard, started shuffling.
Runner trashed Hades to access agendas in Archives
Corp already shuffled in 1 of the 2 agendas. 
Runner tried to access both, was able to steal one, but the Corp took the other.
A prompt displayed to the Runner for them to access the other agenda but clicking it led to this error (because it was probably back in R&D).

Not sure what the rules are.

Stack Trace:
```clojure
Error do choice Steal #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers gt "Numbers.java" 229]
  [clojure.lang.Numbers gt "Numbers.java" 3864]
  [game.core$steal$fn__6558 invoke "runs.clj" 46]
  [game.core$do_effect invokeStatic "abilities.clj" 260]
  [game.core$do_effect invoke "abilities.clj" 256]
  [game.core$do_ability invokeStatic "abilities.clj" 241]
  [game.core$do_ability invoke "abilities.clj" 214]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$trigger_event_simult invokeStatic "events.clj" 177]
  [game.core$trigger_event_simult doInvoke "events.clj" 139]
  [clojure.lang.RestFn invoke "RestFn.java" 533]
  [game.core$steal invokeStatic "runs.clj" 42]
  [game.core$steal invoke "runs.clj" 36]
  [game.core$resolve_steal$fn__6572 invoke "runs.clj" 72]
  [game.core$effect_completed invokeStatic "events.clj" 244]
  [game.core$effect_completed invoke "events.clj" 240]
  [game.core$resolve_steal_events invokeStatic "runs.clj" 63]
  [game.core$resolve_steal_events invoke "runs.clj" 58]
  [game.core$resolve_steal invokeStatic "runs.clj" 70]
  [game.core$resolve_steal invoke "runs.clj" 65]
  [game.core$access_agenda$fn__6635 invoke "runs.clj" 207]
  [game.core$do_effect invokeStatic "abilities.clj" 260]
  [game.core$do_effect invoke "abilities.clj" 256]
  [game.core$do_ability invokeStatic "abilities.clj" 241]
  [game.core$do_ability invoke "abilities.clj" 214]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_ability invokeStatic "abilities.clj" 109]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$prompt_BANG_$fn__6069 invoke "abilities.clj" 309]
  [game.core$resolve_prompt invokeStatic "actions.clj" 147]
  [game.core$resolve_prompt invoke "actions.clj" 117]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__30073 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__30108 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment]
There's not going to be any solution for this other than "players need to understand the rules and timing windows and apply them correctly."

**Comment by JarekWarsaw** [comment]
It's all about [Timing Priority](http://ancur.wikia.com/wiki/Timing_Priority). In your example Corp has rezzed Jackson and started shuffling. It means, that Corp had Priority and could do as many paid abilities as they want before passing Priority to Runner.

For example: Corp clicks to install Jackson. After that action Corp has Priority. They can rez Jackson and pop it to shuffle Archives. Then they can do other paid abilities. After they're done, Runner can act (paid abilities) before Corp can take another click (or trigger other paid abilities).

During Runner's turn Priorities go to Runner. So in that case Runner could install Hades Shard and immediately pop it, accessing cards before Jackson can shuffle them back to R&D.

Back to your error. In either case if Runner will pop Hades Shard and Agendas not-yet-accessed will be removed from Archives, an error will occur.

**Comment by Saintis** [comment]
Is there a wait-prompt when the corp uses Jackson? If not maybe that would help things to at least make runner aware that Jackson is being used.

**Comment by domtancredi** [comment]
No wait prompt but that would make sense right? 

I'm ok with closing this issue given it's a "know the rules" situation.
