### ISSUE TITLE
Cache Refresh Format not accurate

### ISSUE THREAD

**Issue by Brototurret** [mtgred/netrunner#2558]
Hi there.. I built some Cache Refresh decks , and they aren't being flagged as such. 

Notably Aaron Marron and Data Ward are apparently invalid. 

Cache refresh allows anything from Flashpoint and Red Sands currently , so I wanted to bring this to your attention. Thanks guys !

**Comment by danhut** [comment]
This has been fixed already - just waiting on a push to the live server.  Don't know exactly when that will be.

Can you close this? thanks for the report!
