### ISSUE TITLE
Mental Health Clinic adds 2 to runner's hand size

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#256]
...when it should only add one.

**Comment by JoelCFC25** [comment]
The code looks correct and it's always worked for me in the past: 

`"Mental Health Clinic"
   {:effect (effect (gain :runner :max-hand-size 1))
    :leave-play (effect (lose :runner :max-hand-size 1))
    :events {:corp-turn-begins {:msg "gain 1 [Credits]" :effect (effect (gain :credit 1))}}}`

Are you sure you didn't get a lag spike or something?

**Comment by mtgred** [comment]
For some reasons, abilities are sometime triggered twice. In some games I played, it happened with other cards as well. I'm not sure why though.

**Comment by qmsm** [comment]
It happened multiple times in the same game. Could it have anything to do with there being multiple copies out (each one increased it by two when rezzed)?

Not ruling out a random ghost of course.

**Comment by Astrochelys** [comment]
I'm pretty sure there's a small but easy to circumvent bug with mental health clinic. I was playing against a corp who rezzed one. My max hand size went to 6. I got a brain damage. My max hand size went to 5. Then I trashed the mental health clinic. My max hand size stayed at 5 ( should be 4, but easy to correct by manually setting max hand size). After manually setting max hand size to 4, corp rezzed another mental health clinic. Max hand size went from 4 to 6.  

This might be what the first poster observed as well.

**Comment by marckubischta** [comment]
This has been broken in my games with MHC over the last few days as well.

**Comment by JoelCFC25** [comment]
Tested just now and MHC seems to work properly--both with multiples out, having one trashed, etc. This was among several fixed by 009acdbea0b81d90d64c6eec9f832054e1631e69 and can probably be closed, @qmsm (unless @mtgred gets to it first).

**Comment by qmsm** [comment]
Happy to take your word for it :+1:
