### ISSUE TITLE
Salem's Hospitality card list 

### ISSUE THREAD

**Issue by MHGray** [mtgred/netrunner#2560]
Salem's Hospitality does not have a full card list available. In the picture below I'm searching for Chameleon (which I triple checked I was spelling correctly), but it is not an available option. Trying to manually notify your opponent of this so you can pick a card before their hand is revealed is impossible as the chat box gets disabled while the prompt is up.

![image](https://cloud.githubusercontent.com/assets/8196735/26506742/6d72efc6-4202-11e7-9da9-ee214dec5472.png)

May just be an issue with the list or filter itself as I was watching a stream the other day and the same thing happened with an anarch trying to switch ID's with Rebirth. Only Alice Merchant was available to switch to.

**Comment by JoelCFC25** [comment]
Something is busted with the cards atom, this bugged for the same reason as Rebirth (as you surmised).
