### ISSUE TITLE
Careful Planning does not log which card was targeted

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2562]
Rules are still followed, and the corp will be given the toast that it cannot rez the targeted card due to Careful Planning if she tries to do so, but the text log makes no mention of which card was targeted (or that a card was even targeted at all), which can make decision-making based around that difficult.

**Comment by Saintis** [comment]
Logging which card was selected would be easiest fix.

A clearer solution would be to have a label on the card like the Femme counter or as for CyCy / Sec Testing / Patron
