### ISSUE TITLE
Archives Interface nonfunctional with Hades Shard access

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2563]
Simple issue: when Hades Shard is used to access cards in Archives with Archives Interface installed, you don't receive the option to use the Archives Interface ability. You ought to be able to do so.

**Comment by JoelCFC25** [comment]
Simple to describe, extremely challenging to solve. There was a reason Archives Interface had to be moved off the `:pre-access` event, I just can't remember what it was.

**Comment by HubGitAccoutn** [comment]
Oh, I wasn't suggesting the fix would necessarily be simple!

I'm not sure how it all works programmatically or what the :pre-access event is, but Archives Interface certainly happens before access in game terms at the moment, since it's always a bit awkward that you don't get to see the flipped cards before choosing to use it (just for that odd occassion when everything in Archives turns out to be an agenda and you have to RFG one instead of stealing it!).
