### ISSUE TITLE
Unregistered S&W does not allow runner to trash a bioroid

### ISSUE THREAD

**Issue by wumbabum** [mtgred/netrunner#2565]
I and two other players have had the problem where unregistered S&W, after accessing hq, does not allow trashing. I can click on the card and it gives me a crosshair, but clicking on any ice, rezzed bioroid or otherwise, does nothing.

I thought I submitted this before, but I don't see any issues authored by me, so here it is again.

**Comment by Saintis** [comment]
Unregistered S&W only allows trashing cards _in a server_, hence I would say this is working as intended in not allowing the runner to trash ice (since ice is installed _protecting a server_ and not _in a server_).

**Comment by JoelCFC25** [comment]
Correct, Unregisted S&W can only target appropriately subtyped assets or upgrades _not_ installed in the root of central servers.
