### ISSUE TITLE
Maya traps you in an infinite access loop

### ISSUE THREAD

**Issue by dezzmont** [mtgred/netrunner#2574]
Maya, when used to access a card, traps you infinitely accessing the top card of R&D over and over again. Even /close-prompt seems to not be a great way to escape.

**Comment by kevnburg** [comment]
I was playing the game with dezzmont as the Runner. Here's exactly what would happen:

After using Maya's ability (and then avoiding the tag with New Angeles City Hall + and then accessing a second card with my RnD interface) I would return to the "successful run / jack out" options. Pressing jack out did nothing and /close-prompt did nothing so I would basically be forced to press successful run again.

After pressing successful run again and accessing cards, I would often be brought BACK to the "successful run / jack out" options and be again basically forced to press successful run. The number of repetitions of this process required to escape the loop varied (so not quite an infinite, but unknown # of repetitions).

**Comment by JoelCFC25** [comment]
Not verified yet, but a cursory look has me guessing that the problem here is having tag avoidance in play in combination with Maya. So I'm betting this happens with Forger, et al as well.

**Comment by JarekWarsaw** [comment]
I've experienced similar problems in the past (usually in Archives), but haven't been able to pinpoint them. I use On the Lam though, so tag avoidance seems like a good guess.

**Comment by JoelCFC25** [comment]
Lines 421-22 of Maya need some work (don't know if I can indent properly on here): 

```(when-completed (tag-runner state :runner 1)```
  ```(do (close-access-prompt state side)```
  ```(effect-completed state side eid)))))}```
