### ISSUE TITLE
live-edu videos are locked

### ISSUE THREAD

**Issue by Kallin** [mtgred/netrunner#2577]
I wanted to watch those live-edu coding videos linked in the development guide, but it turns out you have to pay to watch more than a few minutes of them. 

Why not post them on youtube? I think they'd be a great resource for contributors but are pretty much inaccessible at the moment.

**Comment by JoelCFC25** [comment]
The hosting site appears to have undergone quite a change in the time since those videos were posted, since it definitely was not like that before.

**Comment by nealterrell** [comment]
I will see if I can put them up on YouTube, but I don't know if it will be possible, since I live streamed them and don't have a copy of the entire video as one piece.

**Comment by msbeck** [comment]
Having the same problem. I'd really like to watch them all! 

Sorry for the dup thread (3201). 

Does their dashboard offer a video download for the content creator? If not, perhaps it can be ripped provided a sufficient membership.

**Comment by msbeck** [comment]
Any volunteers to get a membership, dl the videos, and try for a refund?
