### ISSUE TITLE
Oberth and Rumor Mill

### ISSUE THREAD

**Issue by BlueHg** [mtgred/netrunner#2579]
Rezzing Oberth Protocol while Rumor Mill is active still forces me to sacrifice an agenda, contrary to the UFAQ ruling. Unknown if this also applies to Ibrahim Salem.

**Comment by JoelCFC25** [comment]
Yep, the way Rumor Mill affects cards does not scan for additional costs, so Oberth Protocol, Ibrahim Salem, and Corporate Town will all be afflicted by this.

**Comment by Saintis** [comment]
Judging from the Rumor Mill test, this is intentionally done...
