### ISSUE TITLE
Steve Cambridge vs events that make runs on HQ.

### ISSUE THREAD

**Issue by Absotively** [mtgred/netrunner#2580]
Observed the following:

- My opponent, playing as Steve Cambridge, had two cards in the heap. Neither was an Inside Job.
- They used Inside Job to make a run on HQ. The run was successful.
- They used Steve's ability, choosing Inside Job and one of the other cards.

Since Inside Job hadn't finished resolving, they shouldn't have been able to choose it.

Presumably related to #322.

**Comment by JarekWarsaw** [comment]
In addition to that:
Steve has 1 card in heap and plays Inside Job on HQ. Steve's ability should not trigger, as he doesn't have 2 cards in Heap when the run is successful.
> [event] is trashed when its effects are resolved.

**Comment by danhut** [comment]
Can't we just ignore the event that most recently hit the discard pile when assessing Steve ?
