### ISSUE TITLE
Game crash with Project Vitrovirus

### ISSUE THREAD

**Issue by leodasvacas** [mtgred/netrunner#2590]
How to reproduce:
1. Take counter from Project Vitrovirus to grab a card from archives.
2. There is no way to cancel the dialog so ignore it.
3. Remove a card from archives.
4. Click that card in the Project Vitrovirus dialog.
5. Game crashes (becomes totally unresponsive, including chat).

A nice fix would be to add a "Cancel" option to Project Vitrovirus.

**Comment by Saintis** [comment]
Might be easiest to change Vitruvius to use the same targeting mechanism that Jackson uses.
