### ISSUE TITLE
AgInfusion vs Sneakdoor Beta

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#2592]
As reported [here](https://www.reddit.com/r/Netrunner/comments/6gqz2e/sneakdoor_ag_infusion/):

> I was running against Ag Infusion. I ran a sneakdoor click and Ag trashed their ice and bounced me over to a remote server. I had a successful run and jinteki.net bounced me over to HQ.

**Comment by danhut** [comment]
I could not reproduce this.  When I bounced to a remote that was the server I accessed.

**Comment by NoahTheDuke** [comment]
Maybe they got it wrong? If it's unreproducable, I can close this.

**Comment by JoelCFC25** [comment]
Post here if this reliably occurs again. For now, closing due to no further reports.

**Comment by msbeck** [comment]
I just had it happen. Ran on archives, they trashed an unrezzed ice and moved me to a remote with no cards installed and one unrezzed ice. Once I passed the unrezzed ice into an empty server, sneakdoor redirected me into HQ.

**Comment by msbeck** [comment]
@nealterrell suggest re-opening for investigation again under the circumstances outlined.
