### ISSUE TITLE
Game freezes with a bounced street peddler

### ISSUE THREAD

**Issue by M-Hawkins** [mtgred/netrunner#2594]
This edge case arises from clicking on a street peddler during an effect that removes it from the board. 

1. Have an installed street peddler
2. Fire archangel's subroutine
3. Attempt to click street peddler (No prompt appears, as expected)
4. Resolve subroutine and have it bounce the street peddler
5. Street peddler is returned to hand and its prompt appears

Game freezes at this point for both players, including chat. No part of the interface is responsive, including the street peddler prompt. /close-prompt does not work.

**Comment by JoelCFC25** [comment]
I'm dubious that this can be prevented easily. At some point it falls on the players to know and apply the rules correctly--there are already a zillion other instances where we aren't preventing players from clicking things when technically they shouldn't.
