### ISSUE TITLE
Feature Request: [Opponent] is typing

### ISSUE THREAD

**Issue by mervin39** [mtgred/netrunner#2598]
I'd love it if there was a visual indication that my opponent is typing in the chat box. Often I get to the end of a game, write gg and then count to ten in case they want to discuss the game.  I'm always worried I've left the game just as they are about to hit return!

**Comment by danhut** [comment]
I am no UI type .. first attempt at this looks nasty!  Where should the "opponent is typing" message appear though?    Not in your own typing box for sure.  Maybe it does not work with this UI lay out?

<img width="160" alt="typing" src="https://user-images.githubusercontent.com/11830223/28243524-ab4db6ec-6a10-11e7-8481-83af155b46f5.png">

**Comment by PesiTheWizard** [comment]
This sort of thing is usually a GIF that only animates when the opponent has something in their chatbox.

**Comment by danhut** [comment]
yeah that seem do-able.. need to go find a shiny GIF
