### ISSUE TITLE
Recurring Credits - New Timing Chart

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#2599]
Per new FAQ, recurring credits refilling and beginning of turn triggers are now two separate steps. (1.3 and 1.4 respectively)

Cards such as Cyberfeeder need to not refresh when used to pay for cards like Darwin

My own fault for playing the Whale, but still an issue. I noticed the same problem with Multithreader and Mammon. Perhaps I should start questioning my icebreaker suite choices.

**Comment by danhut** [comment]
I think I broke this when doing the FAQ 4.0 updates.  

What happens now is:
1. Runner clicks Start Turn
2. Start of Turn triggers happen like Darwin - if any are installed
3. Runner clicks Take Clicks - this fires recurring credit refill

Old code was:
1. Runner clicks Start Turn - this fires recurring credit refill
2. Start of Turn triggers happen like Darwin - if any are installed
3. Runner clicks Take Clicks 

In retrospect I think the original implementation was correct - just there was no specific ruling for it. Agree?  Does that also work for Jak Sinclair.  Let me know - cheers

**Comment by ouroboros8** [comment]
Yep old system seems correct to me.
