### ISSUE TITLE
Message when runner accesses a server with no cards in it

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2600]
It would be nice if, when the runner successfully runs a server with no cards in it (IE: empty HQ with nothing in the root), there was a message akin to:

"There are no cards to access in [server]."

**Comment by JoelCFC25** [comment]
Do you mean a prompt which must be dismissed by the Runner? Or a message printed to the game log?

**Comment by FarCryFromHuman** [comment]
I think just a message in the log would suffice, a prompt seems like overkill.
