### ISSUE TITLE
Penalty for Blanked+Trashed directives

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2602]
Directives that are blanked (Dr. Lovegood) and trashed in the same turn subtract their bonus beyond normal.
(Experienced HQ-access size of 0)

Possible relation to the Cybernetics Court issue.

**Comment by JoelCFC25** [comment]
Looks like this can be fixed by adding `(not (:disabled card))` as a condition in `deactivate`.
