### ISSUE TITLE
Full Immersion RecStudo's Hosted Cards Duplicated in Archives when Trashed with Apocalypse

### ISSUE THREAD

**Issue by lukesimm** [mtgred/netrunner#2606]
As above:

When trashed with Apocalypse, all cards hosted on Full Immersion RecStudio are then duplicated within Archives.

Steps to reproduce:

1. Host cards on a Full Immersion RecStudio (tested with one face down agenda, one face up Asset, Sandburg)
2. Trash all cards after making three main server runs as a runner with Apocalypse
3. Look into Archives as Corp, and find duplicates of the two cards on Studio.

**Comment by JoelCFC25** [comment]
Apocalypse is still a hugely problematic card that causes a whole host of issues.

**Comment by danhut** [comment]
This happened for me too when I tried to reproduce it.

@JoelCFC25 I wonder what the performance impact would be of some sort of  "card de-duplication" function as cards move into a new location?   I have seen similar issues which I have put down to lag.  Based on the :cid we should never have move than one of a card... but I do worry about performance.  I have no insight in the live server load.
