### ISSUE TITLE
Bugs only reported in chat

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2608]
- [x]  MCA informant played on Aaron Marrón with counters -> Counters used. -> Aaron trashed with MCA ability = Total tags : -1 _(Feature, not a bug)_

- [ ] "Advanced Assembly Lines seems to be bugged"
"2 in grave when Ad Blitz scored. 1 placed in grave after"
"*Rebranding Team"
"Play Ad Blitz, it only lets me resurrect the 2"
"In addition, when firing the one that was resurrected, it did not seem to realize that Data Raven was a non-agenda card"
"The Rebranding Team + 2 AAL + Ad Blitz combo has worked on Jnet before, I wonder what's up with it now"

- [x] "Maw is BUGGED! if you pair with edward kim it'll still trigger maw even I the ID trashes an operation"

~~"Mutate card need a bit of work. If you have two same ICE rezzed you cannot distuinguish from the UI which ICE you are targeting for trash"~~ _(Is fine)_

- [x] "is the Cleaners not triggering off Mr. Stone a known bug, or does the Cleaners actually not trigger off Mr. Stone?"

- [x] "I know I'm probably the only player this matters for, but Jnet doesn't have the interaction between AR-Enhanced Security and Persephone implemented. So if I'm playing you and you've scored an AR, be sure to give me the tags when I start milling! I keep forgetting."

**Comment by JoelCFC25** [comment]
Re: number 2, I'm not familiar with the combo and I can't understand the description sufficiently to follow what is meant to happen vs. what actually did happen.

**Comment by PesiTheWizard** [comment]
Tested just now. Using Ad Blitz with Rebranding Team scored doesn't let you choose any copy of Advanced Assembly Line that was on the field when Rebranding Team was scored. AALs that were in archives when it was scored are valid targets.

**Comment by JoelCFC25** [comment]
Does "on the field" mean "installed" in this case? Was it rezzed or unrezzed? Sorry, I'm not trying to be dense, but I am still not 100% on the setup and reproduction steps.

**Comment by PesiTheWizard** [comment]
Yes.

I installed 3 of them, rezzed 2, then cracked one. Then I installed and scored Rebranding team. I then rezzed the last of them and cracked both. I then Played Ad Blitz. The only one that I could bring back was the (in archives view) the leftmost one, which I assume is the one at the bottom of archives. I did this twice, and it matters not which one you click first, only the bottom one can be brought back.

**Comment by JoelCFC25** [comment]
Confirmed using the `/card-info` tool that an installed asset gains "Advertisement" after Rebranding Team is scored and that subsequent trashing of that asset has it revert to its default subtypes.

**Comment by JoelCFC25** [comment]
Re: MCA and Aaron, this is a limitation of what's possible with the implementation. The tag given by MCA Informant is supposed to be a "faux" tag not capable of being removed by things like Aaron's ability, but the system doesn't currently prevent that. So this is a case where players need to know and apply the rules.

**Comment by danhut** [comment]
@JoelCFC25 Not really following this one - but I added this to the move function some time ago:
`(when (#{:discard :hand} to) (reset-card state side moved-card))`


The reset-card fn makes it so any card sent to trash is defaulted.  This was to handle cards like Egret not permanently changing cards.  Is this part of the issue?

**Comment by JoelCFC25** [comment]
Yep, definitely.

**Comment by danhut** [comment]
Maybe the reset could be made to only affect ICE to sort this out?

**Comment by Saintis** [comment]
Fixed Kim + Maw.

**Comment by Saintis** [comment]
I would say "feature not a bug" as well for the MCA Informant issue currently, due to how it is implemented. So the players will have to be aware that the MCA tag is not implemented correctly.

**Comment by PesiTheWizard** [comment]
Tested Mutate UI in several ways, Interface is fine. Not even Tenma Line could make it non-obvious.

But in doing so, I noticed that if you Mutate into TMI, the trace doesn't happen and TMI is just rezzed. This is surely not how it should work.

**Comment by JoelCFC25** [comment]
It is really far more valuable to have new confirmed bugs split out into their own issues. I'm doing that to Persephone + AR-Enhanced now.

**Comment by JoelCFC25** [comment]
Just tested The Cleaners + rezzed Mr. Stone:  Runner correctly received 2 meat damage when taking a tag.

**Comment by Saintis** [comment]
I'm marking MCA + Aaron as feature, not bug for now
