### ISSUE TITLE
Mid-run ice-trash : Newly slotted ice affected by used Datasucker counters

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2611]
The setup: I run on a 3-ice server, parasite is on 2nd ice. Pass first ice, use Datasucker counters to Para-trash 2nd ice.

The already-passed outermost ice falls into the 2nd slot, at which point the Datasucker counters used on the now-trashed ice affect it.

It's a good thing the outermost ice didn't have it's own parasite, or this might have been game-wrecking.

**Comment by PesiTheWizard** [comment]
Testing revealed: This effect doesn't happen until the corp clicks to let the runner through.

**Comment by JoelCFC25** [comment]
Fascinating. This was super-heavily tested back in the day.

**Comment by PesiTheWizard** [comment]
Update: This also applies equally to Wyrm's strength-lowering ability.

**Comment by JoelCFC25** [comment]
Something is wrong in the `continue` function. The run arrow is not pointing at the right place in this scenario after Para-suckering the middle of the 3 ICE, meaning something is goofy with `[:run :position]`.

**Comment by JoelCFC25** [comment]
I think I might have this now, but will need some serious testing of several ice-trashing scenarios to make sure it's OK. I have Parasite doing a `dec` of `[:run :position]` before firing the `continue`, and Datasucker responding to additional events (`:encounter-ice`, `:approach-ice`).

**Comment by JoelCFC25** [comment]
I was about to write a test for this and then figured there _must_ already be one--[which there is](https://github.com/mtgred/netrunner/blob/master/src/clj/test/cards/programs.clj#L71). Then I realized why this test isn't catching the issue...the ICE is installed in the wrong order.
