### ISSUE TITLE
Cards with names that are superstrings of other card names don't display in chat

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#2613]
Ex: 'Mass Commercialization' displays as 'Commercialization'. This could be fixed by bracketing card names (ie: [Mass Commercialization]) when printing to chat. Any other solution would require a lot of work, I'd expect.

**Comment by danhut** [comment]
This does not happen for me - can you post a screen shot?  I reproduced simply by typing Mass Commercialization into chat and sending it.  Maybe you are doing something else?

**Comment by FarCryFromHuman** [comment]
I just tested and you are right, I wasn't able to reproduce. The most likely cause I can think of is that when Mass Commercialization was typed into the log, there was an extra space between the words that I didn't notice. Regardless, I'll close this.
