### ISSUE TITLE
Alice Merchant crashes game when corp has 0 cards in HQ

### ISSUE THREAD

**Issue by artturipi** [mtgred/netrunner#2615]
Ran on a remote, encountered Mind Game, got bounced to Archives. Had Hactivist Meetings up with corp at 1 card in HQ. Also had Archives Interface in play, so UI prompted for order, chose Alice, after which corp rezzed Crisium Grid on HQ (probably just forgot to do that before successful run triggers), trashing the last card for Hactivists. Game was stuck for me 100% (could not write in chat etc, tried rejoining as spectator, got a black screen), not sure about corp side.

**Comment by JoelCFC25** [comment]
Actually, upon re-reading...I don't think this will be fixable. The Corp player rezzed Crisium Grid at an incorrect time (which there isn't sufficient code support to prevent, as hinted at in other bug reports).

**Comment by JoelCFC25** [comment]
> Also had Archives Interface in play, so UI prompted for order, chose Alice

This part is definitely wrong in the system, and will be fixed in #2643.
