### ISSUE TITLE
Loss of click and error message when interacting with Knight

### ISSUE THREAD

**Issue by zelmor** [mtgred/netrunner#2621]
Please describe the circumstances of your error here.
1. Knight is hosted on ice.
2. Click knight with other than last click of runner's turn
3. click Done instead of selecting an ICE (change of mind)

Error:  Click is lost when paying the ability (normal I guess)
Error: Red error popped up, linking to submission form.

Stack Trace:
```clojure
Error do choice Done #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [game.core$resolve_prompt invokeStatic "actions.clj" 147]}]
 :trace
 [[game.core$resolve_prompt invokeStatic "actions.clj" 147]
  [game.core$resolve_prompt invoke "actions.clj" 117]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 145]
  [game.main$handle_command invoke "main.clj" 134]
  [game.main$run$fn__30816 invoke "main.clj" 180]
  [game.main$run invokeStatic "main.clj" 170]
  [game.main$run invoke "main.clj" 164]
  [game.main$_main$fn__30851 invoke "main.clj" 234]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

**Comment by JoelCFC25** [comment]
> Error: Click is lost when paying the ability (normal I guess)
Yes, this is expected. To stop the lost click in the case of changing one's mind and not actually rehosting Knight, the cost vector would have to be moved to get nested inside the `resolve-ability`.
