### ISSUE TITLE
Bugs with cards nobody uses

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2623]
This is mostly from testing the limits of jnet's interface involving nesting hosted cards.

- [x] Rezzing ice hosted on Awakening Center with Architects of Tomorrow's ID ability doesn't rez the ice.
  - The unrezzed ice are valid targets, but rezzing them doesn't turn the ice face-up.
- [x] You can't host Oversight AI on ice hosted on Awakening Center.
  - The unrezzed ice simply aren't valid targets.
- [x] Hosting Bioroid Efficiency Research on ice hosted on Awakening Center doesn't actually rez the ice that it's hosted on.
  - The unrezzed ice are valid targets, and Bioroid Efficiency Research is successfully hosted on the ice if targeted, but the ice remains face-down and unrezzed.
- [x] You can't use Casting Call to install an agenda hosted on Full Immersion RecStudio.
  - Most runner cards allow you to host after the fact to make up for the behavior of cards such as Self-modifying Code and Clone Chip, but RecStudio has no such option.

**Comment by JoelCFC25** [comment]
OAI's card targeting is outdated--the 3rd clause should be changed to `(installed? %)`. Haven't looked at the rest yet.

**Comment by JoelCFC25** [comment]
Will be worth trying to steal `:can-host` from Full Immersion (where it debuted) on Awakening Center, which predates it by a lot.

**Comment by JoelCFC25** [comment]
Sure enough, that fixes all the Awakening Center limitations.
