### ISSUE TITLE
Tennin Institute ability overstays its welcome.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2624]
After a turn of no runs, I tried to use first click to trash a resource. This happened.

> Pesi uses Tennin Institute: The Secrets Within to place 1 advancement token on a card in Server 1.
Pesi uses NeoTokyo Grid to gain 1 .
Pesi started their turn 13 with 5 and 4 cards in HQ.
uses to place 1 advancement token on Wireless Net Pavilion.
Pesi spends to gain 1 .
Pesi
wait, what?

I paid the proper 4 to do it, too.

**Comment by JoelCFC25** [comment]
I can't reproduce this one, but Tennin should have `(:corp-phase-12 @state)` added as a condition for usage.

**Comment by JoelCFC25** [comment]
Any repeats of this one?

**Comment by PesiTheWizard** [comment]
I tried to test it later, the bug didn't reappear. I don't know what might have caused it.

**Comment by JoelCFC25** [comment]
Can reopen if it crops up again. The usage restriction has been added.
