### ISSUE TITLE
Alice + Archives Interface + Empty Archives

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2629]
When Alice runs on empty Archives with its Interface installed, she doesn't get to RFG the card that the corp discards due to her ID ability. 

Everything works fine as long as there is at least 1 card already in Archives when the run is successful.

In case it matters, this was the first run of the game. Nothing was RFG'd already.

**Comment by JoelCFC25** [comment]
Effectively the same as #2563--have to make ArchInt(s) work at the correct point in the timing sequence somehow.
