### ISSUE TITLE
Kakugo/Caprice missing trigger

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#2630]
Kakugo doesn't deal its 1 net damage on passing when it is the innermost ice and Caprice Nisei causes the run to end.

**Comment by JoelCFC25** [comment]
Working for me. Would need more details to investigate further.

![screen shot 2017-07-14 at 9 25 39 pm](https://user-images.githubusercontent.com/10407969/28235788-1d7c30f4-68db-11e7-9b80-e7e804099e2f.png)
