### ISSUE TITLE
Steve Cambridge chat log is incorrect 

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2631]
Runner rebirths into Steve Cambridge - the player 'echo' is the corp, not the runner.

Pinsel uses Sneakdoor Beta to make a successful run on HQ.
echo uses Steve Cambridge: Master Grifter to add Deuces Wild to their Grip. Corp removes Deuces Wild from the game.

**Comment by JoelCFC25** [comment]
Lines 792 and 797 need to be: `system-msg state :runner`
