### ISSUE TITLE
Can't save any decks in deck builder

### ISSUE THREAD

**Issue by cmw23** [mtgred/netrunner#2632]
I have tried to save 7 decks (mix between runner and corp), but none of them actually get saved.

**Comment by JoelCFC25** [comment]
This isn't enough information to go on. What web browser are you using?

**Comment by cmw23** [comment]
internet explorer. I name the decks, select the identity, add the cards, hit save and when the decks screen comes up it isn't there. need any other info?

**Comment by JoelCFC25** [comment]
Internet Explorer is not a supported browser. Try using Firefox, Chrome, or Safari.

**Comment by cmw23** [comment]
Works beautifully now. Sorry for that oversight and thanks for the help.
