### ISSUE TITLE
Miraju subroutine functionality - draw should be optional

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2633]
The card draw when resolving the Miraju subroutine is optional for the corp (unlike the shuffling back in of an HQ card). As currently implemented, it forces the draw and then forces the Corp to pick a card to shuffle back into R&D. I would have thought it ought to give a little pop-up option to draw or not before forcing the Corp to choose a card to shuffle back.

**Comment by JoelCFC25** [comment]
Was faster to just do it as-is initially--if you don't intend to draw a card, why even click to activate the sub? Could be redone, just not a huge priority.
