### ISSUE TITLE
Obokata Protocol's Additional Cost

### ISSUE THREAD

**Issue by defconclown** [mtgred/netrunner#2635]
The text of Obokata Protocol is "As an additional cost to steal Obokata Protocol, the Runner must suffer 4 net damage." If you prevent the damage you haven't paid the additional cost. Obokata Protocol can be stolen and Feedback Filter used to prevent the damage.

**Comment by JoelCFC25** [comment]
The new function(s) that made damage able to be handled as a true additional cost need to make it be `{:unpreventable true}`.
