### ISSUE TITLE
Gauntlet could benefit from Corp confirmation

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2636]
Gauntlet can be problematic in real games as it currently works. The Runner "awards" themselves extra accesses when they access but this isn't checked against anything. Theoretically, this isn't a problem, but in reality a lot of Runners mistakenly award themselves extra accesses when they haven't broken all subs on a piece of ICE: omitting to break the AI sub of Swordsman, say, or the Psi game on Aiki (especially if no cards left to draw!). The trouble is that this doesn't become apparent to the Corp until after the extra accesses have occurred, by which stage is it hard to reverse the result of any extra accesses, and impossible to reverse the hidden information that has been revealed from HQ (pretty important!).

It would make it an extra click box for Gauntlet runs, but I wonder if the Corp getting a verification box for the number of bonus accesses would resolve this? It's a user problem rather than a coding one, but honest mistakes with Gauntlet seem to happen surprisingly often, and they kind of ruin the game when they do.

**Comment by danhut** [comment]
Honestly I am not sure about having both players confirm this data.  Should the whole interaction instead get moved to the corp? In which case the corp can get it wrong too.  

Same thing applies for things like Persephone and some new card coming I forget the name of.
