### ISSUE TITLE
[Feature] Multilingualize card text

### ISSUE THREAD

**Issue by nitamago** [mtgred/netrunner#2637]
__Can card text be multilingualized ?__ 

Is the current system design easy to translate card text?
If so, I will help translate text.

I want introduce  Netrunner to my friends. 
But they are not good at english. 
So they can not understand card abilities.

**Comment by danhut** [comment]
It looks like translations are available here:
https://github.com/zaroth/netrunner-cards-json/tree/master/translations

So it is possible - but we'd need to have some UI work to overlay the translated text for non-English users.  Likely not going to happen unless someone new takes this on.
