### ISSUE TITLE
Discarding Chairman Hiro via Maw causes him to be added to Runner score area

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#2638]
**Situation:** Corp has Chairman Hiro in hand. Runner has Maw installed. Runner triggers Maw.

**Expected Result:** If Maw hits Chairman Hiro, it should go in the trash unrevealed.

**Actual Result:** Maw forces the Corp to discard Chairman Hiro. The Corp places Chairman Hiro in the Runner's score area, and grants the runner 2 points.

======

Keep up the good work, debugging team!

**Comment by JoelCFC25** [comment]
I. Hate. Maw.

**Comment by danhut** [comment]
More a Hiro issue?  He does not really know if he is still being accessed when his effect happens - just checks if an access is taking place.  

Fix done - but a better one would be to have the :access flag removed on the access-agenda & access-non-agenda functions once stealing or trashing is declined - and to have the :access flag set per card to equal the CID of the card being accessed - then have Hiro check that... did not have the energy!
