### ISSUE TITLE
Archives Interface and Crisium Grid

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2639]
I know Archives Interface has a few issues at the minute, so this might be the same as something else, or get fixed by some fix for another issue, but I just thought I'd flag that Archives Interface doesn't seem to work on the run where you trash a Crisium Grid on Archives. (It isn't dependent on successful run, only accessing cards, so it should work)

This came up with Alice Merchant as the Runner, just in case that is an extra spanner in the works: first run of the turn so it was the "ID-triggering" run that was being nullified by the Crisium Grid for Alice purposes. I haven't tried it in other circumstances.

**Comment by JoelCFC25** [comment]
It is the same underlying cause as the others--this card is wrongly linked to the `:successful-run` event for complex reasons I knew at one point (because I did it) but have forgotten.
