### ISSUE TITLE
Net Ready Eyes only shows up for first encounter

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#264]
There was an old issue for Net Ready Eyes but didn't seem the same as this.

The increased strength for your target only shows up for the first encounter and then disappears rather than "for the remainder of the run".

**Comment by JoelCFC25** [comment]
I thought this was easy, but was reminded that the code currently can't distinguish between pumps that last for the remainder of the run and those that only last for the duration of a single encounter if a program receives both kinds (this is also afflicts Snowball).
