### ISSUE TITLE
Hellion Beta Test's implementation is slightly wrong

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#2641]
I have a feeling this is going to be tagged with "who the hell designed this game anyway."

Presently, Hellion Beta Test allows you to pick fewer than 2 legal targets to trash. That's actually not quite correct. Per the UFAQ, if the Runner only has 1 installed non-program card, the corp is forced to trash one of _their own installed cards,_ because Hellion Beta Test says "trash 2 installed non-program cards," not "_up to_ 2."

So if the Corp has some ice installed, and the Runner has, say, 1 program and 1 resource, and trashes an accessed card, the corp can play Hellion Beta Test - and while they can trash the 1 resource, they also have to trash an installed corp card because it's the only legal second target for the effect.

**Comment by JoelCFC25** [comment]
Up until very recently, the engine had no capability to require a minimum number of selections, only a maximum number that you could stop short of and proceed even if it wasn't allowed rules-wise. That changed in #2521.
