### ISSUE TITLE
Jarogniew Mercs protect themselves from Grip / Rezzing ICE in HQ

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2642]
- [ ] As long as a resource is installed, damage that hits Jarogniew Mercs in Grip prevents that trash, displaying a message that they can't be trashed.

- [x] A Priority Requisition score or operations that let you rez ice for free can target ice still in HQ. When those pieces of Ice are then installed, they are installed rezzed.

**Comment by JoelCFC25** [comment]
I can fix the problem with Jarogniew in hand, but there's another one I noticed. If it's installed along with 1 other resource, it can't be trashed--which is correct. But if that _other_ resource gets trashed first, Jarogniew remains untrashable, which would be wrong.
