### ISSUE TITLE
Accountsiphon interaction with Counter surveilence

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2644]
vincentkbl spends  and 1  to install Counter Surveillance.
vincentkbl spends  to play Account Siphon.
vincentkbl uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
vincentkbl spends 1  to use Eater to break ICE subroutine and access 0 cards this run.
amm has no further action.
amm uses Kakugo to do 1 net damage.
vincentkbl trashes Dirty Laundry due to damage.
vincentkbl continues the run.
vincentkbl sets credit to 15 (-1).
vincentkbl sets credit to 14 (-1).
amm has no further action.
vincentkbl continues the run.
amm has no further action.
vincentkbl uses Account Siphon to access cards by paying 8 .
vincentkbl accesses Biotic Labor from HQ.
vincentkbl accesses Fetal AI from HQ.
amm uses Fetal AI to do 2 net damage.
vincentkbl trashes Special Order, Logos due to damage.
vincentkbl pays 2 to steal Fetal AI.
vincentkbl steals Fetal AI and gains 2 agenda points.
vincentkbl accesses Hokusai Grid from HQ.
vincentkbl accesses Ben Musashi from HQ.

**Comment by JoelCFC25** [comment]
Counter Surveillance needs an additional check that the existing run does not already have a replacement effect.
