### ISSUE TITLE
Wasteland shouldn't trigger when you trash corp cards

### ISSUE THREAD

**Issue by kanuahs** [mtgred/netrunner#2645]
[Wasteland](https://netrunnerdb.com/en/card/09036) gives 1 credit when you trash one the corp's installed cards. It should only give credits when the runner trashes his own cards.

**Comment by JoelCFC25** [comment]
This must be due to a relatively recent change, this card is very old and it's never occurred before.

**Comment by danhut** [comment]
I have some history here.. turns out Reaver and Wasteland are actually looking for different events.  Reaver wants any installed card trash, while Wasteland wants any trash of YOUR cards.  Will sort it out.
