### ISSUE TITLE
Invesificator installed on a piece of ice??! 

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2646]
![untitled](https://user-images.githubusercontent.com/18687557/28232306-3ffada6e-68ad-11e7-8a3a-b626f202326a.png)
How is that even possible?

**Comment by JoelCFC25** [comment]
This is probably more of a Dedicated Processor than an Inversificator issue. There is no provision in Inversificator's code for hosting it on anything, but there is with DP.

**Comment by danhut** [comment]
"spends 6c to install Inversificator on Crick" in the logs - so more like an install issue?
