### ISSUE TITLE
Improved Tracers improves the trace of Information Overload's encounter effect

### ISSUE THREAD

**Issue by Spionbil** [mtgred/netrunner#2652]
Pretty much what the title says. Improved Tracers improves the trace of Information Overload's encounter effect despite it not being a subroutine.  
The related card Troll which also has a trace on encounter does not benefit from Improved Tracers.

Steps to reproduce.

1. Score Improved Tracers.
2. Fire the encounter effect on Information Overload. 

Reproduction rate appears to be 100%

**Comment by JoelCFC25** [comment]
This would be expected--the event that Improved Tracers listens for doesn't carry with it any indication of what _kind_ of ability it came from, just that it came from a card with the Tracer subtype.

**Comment by Saintis** [comment]
Somethinh @NoahTheDuke might be able to look at in the Trace rewrite, maybe?

**Comment by NoahTheDuke** [comment]
Yeah, I'm definitely looking into how to handle this. Sadly, modifying the `eid` doesn't work how I'd hoped, so I have to venture into other avenues.

**Comment by kevkcc** [comment]
Fixed in #3643. Closing.
