### ISSUE TITLE
Meteor Mining scoring

### ISSUE THREAD

**Issue by limnrix** [mtgred/netrunner#2653]
The prompt to gain 7c on scoring Meteor Mining repeats itself and won't close. First time, I was able to click on it much later after both players /close-prompt-ed and make it resolve, but second time it kept looping.

**Comment by danhut** [comment]
Just tried it twice and it works fine.  Any other steps to reproduce this?

**Comment by limnrix** [comment]
It was specifically when the meat damage option was unavailable. I'll see what else might be going on. Thanks!

**Comment by JoelCFC25** [comment]
The "take credits" and "do nothing" options are missing `(effected-completed state side eid)`.

**Comment by limnrix** [comment]
Sometimes instead of looping, the runner is just stuck waiting for the corp to resolve until they close prompt.
