### ISSUE TITLE
Personality Profiles lies about the discard

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2654]
Just had a game against Personality Profiles. It caused me to discard Order of Sol. Order of Sol was the top card of the heap and was visible from the main board. Log said I discarded Crash Space. Crash Space had been discarded earlier in the game and was at the bottom of the heap.

**Comment by JoelCFC25** [comment]
Line 654 should be `(:title (last (:discard runner)))` instead of `(:title (first (:discard runner)))`.
