### ISSUE TITLE
Ayla with Rebirth - NVRAM cards go into Heap

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#2655]
They should go.... somewhere else ??? RFG?  Some other RAM?   Nowhere?

**Comment by JoelCFC25** [comment]
I understand the ruling to be "nowhere" (remain facedown).

**Comment by stoppableforce** [comment]
They should stay facedown in NVRAM; the Runner no longer has a way to interact with NVRAM if they Rebirth out of Ayla.

I can gather from the Ayla code that NVRAM cards are currently hosted on her, which means they'd need to be hosted on the new identity. That's as far as my knowledge goes.
