### ISSUE TITLE
The Board lowers runner's points whenever corp scores

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2658]
Twice now I have noticed the runner having less points than they should, both times when The Board was rezzed. My only hypothesis that fits the observed is that when the corp scores an agenda while The Board is rezzed, the runner's points are lowered by an amount equal to ( Point amount of scored agenda + 1).

**Comment by JoelCFC25** [comment]
The logic in the `:card-moved` event handler is too broad, which is why it's returning true when an agenda winds up in the Corp scored area.

**Comment by wombat929** [comment]
Also, if you trash two copies of The Board, they should each count as two points in the runner's score area but they do not.
