### ISSUE TITLE
Data Loop - Runner manually puts 2 cards on stack, but cards are revealed in log

### ISSUE THREAD

**Issue by dollopuss** [mtgred/netrunner#2666]
I don't think manually putting 2 cards on stack is best since it reveals the cards put on the stack in the log. I think a clickable ice option for the runner where they choose the 2 cards without revealing them would be best?

**Comment by JoelCFC25** [comment]
Agreed. Data Loop needs a `:runner-abilities` block added that forces them to add 2 cards (or 1 if that's all they have) back onto the Stack.

**Comment by PesiTheWizard** [comment]
Remember this when implementing Loki
