### ISSUE TITLE
Something is up with Political Operative + IG:Growing Solutions

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2667]
I just had a game where the runner had Political Operative installed and was running on R&D. I had 4 face-down cards in Archives and rezzed Hokusai Grid on R&D. They used Political Operative on it and paid 12 to trash it. (4 + 4 < 12)

**Comment by JoelCFC25** [comment]
Just tried this exact scenario and was made to pay the correct 8 credits to trash the Hokusai Grid. I expect this was either a double-click or a latency situation.
