### ISSUE TITLE
Titanium Ribs + Stimhack buged

### ISSUE THREAD

**Issue by Inermis2** [mtgred/netrunner#2668]
When I have Titanium Ribs installed an play Stimhack. 
After the run ends, Titanium makes me choose 1 card to discard, and then Stimhack fires a random card once more. 

expected result: 
Titanium Ribs allows to chose cards to trash with Stimhack brain damage. No additional/random damage is applied.

**Comment by JoelCFC25** [comment]
Amazing. I fixed this recently and I swear I tested a whole bunch of Titanium Ribs cases.

**Comment by Inermis2** [comment]
Here is the bug on stream: 
https://youtu.be/jLwls18Qs38?t=40m32s

**Comment by JoelCFC25** [comment]
Have an idea on this now.

**Comment by HongkongKoma** [comment]
We encountered the McRibs bug again. My opponent had 7 cards in hand, Titanium Ribs installed and ran into an Obokata Protocol. He took the damage, so discarding 4 cards but then the chat prompt said that he again trashed 3 cards and was flatlined. But he won the match!

**Comment by JoelCFC25** [comment]
I'm aware it's still a bug. My idea didn't pan out, so I'm still completely stumped.
