### ISSUE TITLE
Reaver draws multiple cards when using Freelance Coding Contract.

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#2671]
Playing Freelance Coding Construct with an installed Reaver causes it to draw cards.

**Comment by JoelCFC25** [comment]
Reaver line 676 is definitely wrong. `:req (effect`  should never appear anywhere, it should be: `:req (req (first-installed-trash? state side))`

But even fixing that, Reaver is still drawing, so something is screwy with the new `get-installed-trashed` function.

**Comment by danhut** [comment]
Reaver is giving me that Maw feeling... will take a look.  Of course I now have Maw 100% working in every scenario...
