### ISSUE TITLE
Customised Secretary duplicates Parasite when used

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#2672]
Not sure what caused it, but I installed a Parasite off of a Customised Secretary (which was hosted on a Djinn, in case that somehow matters) and it resulted in a Parasite still on Customised Secretary, and a duplicate Parasite on the piece of ice. Furthermore, the duplicated Parasite didn't gain counters.

**Comment by JoelCFC25** [comment]
Nested hosting is problematic in a lot of ways. I don't think I would know where to begin on this one.

**Comment by Quarg** [comment]
The same error didn't occur when installing other programs, so I suspect that it must be a problem with parasite specifically.

**Comment by danhut** [comment]
Good bye Parasite!

**Comment by NoahTheDuke** [comment]
This doesn't happen anymore.
