### ISSUE TITLE
Counter Surveillance causes Obelus to draw pre-access

### ISSUE THREAD

**Issue by Sabre0001** [mtgred/netrunner#2675]
Currently, after the runner pays to access x cards, Obelus draws that many cards in advance, pre-access rather than after the runner has accessed all the cards they are entitled to and then drawing based on that number.

**Comment by JoelCFC25** [comment]
Looks like `do-access` needs adjustment to move `handle-end-run` to a spot after `choose-access` is finished, which it's currently not doing.

**Comment by JoelCFC25** [comment]
This is actually a symptom of a much deeper and more systemic problem. If you carefully watch `[:turn-events]` in the game state as a run unfolds, you'll actually see the `:run-ends` and `:successful-run-ends` events go into the turn events vector _before_ all access is completed, which is obviously quite wrong.

**Comment by artturipi** [comment]
This is surprisingly annoying to fix manually during game. It doesn't matter that much usually, but vs Jinteki net damage decks the difference is pretty crucial.

**Comment by JoelCFC25** [comment]
I don't doubt it. But if it were easy to fix, it would have been fixed by now.

**Comment by Saintis** [comment]
This is probably due to the funky way Counter Surveillance is implemented, with registering new things on `:successful-run`. I am guessing the run is marked as ended before the newly added access replacement is performed.
