### ISSUE TITLE
Dhegdheer gives you a buck even when you host a free program on it

### ISSUE THREAD

**Issue by ZeromusPE** [mtgred/netrunner#2676]

**Comment by stoppableforce** [comment]
Specifically it seems to be the 'Host an installed program on Dhegdheer' command. I hosted a Paricia on a Dhegdheer from my hand and everything behaved as expected; I installed a Paricia normally then used 'Host an installed program on Dhegdheer' to move it onto Dhegdheer and gained a credit.

**Comment by JoelCFC25** [comment]
Lines 211-213 is where the adjustment needs to be made:  should become `:effect (req ...` so you can use conditional logic, then the line with `gain` needs something along the lines of: 

`(gain state side :memory (:memoryunits target) (when (pos? (:cost target)) :credit 1))`  

...probably don't have all the parens right, but you get the drift.
