### ISSUE TITLE
Can't install a program on Dhegdheer using Clone Chip if you don't have the full price

### ISSUE THREAD

**Issue by ZeromusPE** [mtgred/netrunner#2677]
Example: Clot when you have only 1 credit.  Clone Chip fails.

**Comment by JoelCFC25** [comment]
There's no infrastructure to support this. Someone would have to write some pretty complicated logic for targeting eligible hosts as part of `runner-install`, and by extension account for any installation effects of those hosts.

**Comment by NoahTheDuke** [comment]
This is currently handled.
