### ISSUE TITLE
Bifrost array firing ABT put non-ice back on R&D

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2681]
Corp scores Bifrost Array and uses it to fire a scored ABT. After one ice was installed onto a server, the remaining two cards were put back onto R&D rather than being trashed.

**Comment by JoelCFC25** [comment]
Cannot replicate on my first attempt--made sure there was only 1 ICE in the top 3 at the time I scored Bifrost, after installing the ICE the remaining 2 non-ICE cards ended up in Archives.

**Comment by x3N1GM4x** [comment]
Yep, also tried to reproduce this and couldn't.

I played around with the number of ICE in the top 3 of R&D, which servers I installed the ICE onto when ABT was re-fired by Bifrost (centrals, remotes, multiple ICE onto the same server, etc), whether the original firing of ABT when it was scored caused ICE to be installed or not (and a bunch of other variables), but still worked every time for me.

I certainly didn't do a full exhaustive test of every permutation of the above variables, but I tried quite a lot.

Can you recall anything else significant about the game state @tolaasin?
