### ISSUE TITLE
Chronos project ain't doing nothing.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2682]
Chronos project ain't doing nothing.

**Comment by JoelCFC25** [comment]
This is an extremely unhelpful type of bug report. Can you supply a *minimum* level of detail?

**Comment by JoelCFC25** [comment]
![screen shot 2017-08-01 at 6 30 28 pm](https://user-images.githubusercontent.com/10407969/28851358-89f45dc8-76e7-11e7-8a61-92042f4d5d84.png)
Working for me. Make sure a Blacklist wasn't rezzed.

**Comment by vkl125** [comment]
![image](https://user-images.githubusercontent.com/18687557/28857899-e5688ab8-7709-11e7-9564-b55cab183b2c.png)

**Comment by JoelCFC25** [comment]
Then it's not a bug. An active Blacklist will result in Chronos Project giving you 1 agenda point and nothing else.
