### ISSUE TITLE
Archives Interface & card flip

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2685]
Firstly, thanks for the awesome work on ironing out Archives Interface timing!

There's one little tiny bit that would make it perfect (assuming it's not a massive pain to change). Would it be easy to get the Archives cards to flip over when the "Yes/No" box for using Archives Interface comes up?

**Comment by PesiTheWizard** [comment]
In the meantime, for others in this situation; you can click 'yes', then do '/close-prompt'
