### ISSUE TITLE
Jinteki : PU scoring philotic entanglement while employee strike is active.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2688]
When the Jinteki : PU scoring philotic entanglement while employee strike is active, the ID ability of PU will fire.

**Comment by danhut** [comment]
What else was in play?  I wrote a test for this - and it does not happen.  Final line you can see zero cards in the runner's discard pile.

```
(deftest employee-strike-pu-philotic
  ;; Employee Strike - vs PU/Philotic
  (do-game
    (new-game (make-deck "Jinteki: Potential Unleashed" [(qty "Philotic Entanglement" 1)])
              (default-runner [(qty "Employee Strike" 10)]))
    (take-credits state :corp)
    (play-from-hand state :runner "Employee Strike")
    (take-credits state :runner)
    (play-from-hand state :corp "Philotic Entanglement" "New remote")
    (score-agenda state :corp (get-content state :remote1 0))
    (= 0 (count (:discard (get-runner))))))
```

With no EStrike the discard happens.

**Comment by JoelCFC25** [comment]
The score of Philotic in that test won't do any damage because the Runner has no agendas, therefore PU won't fire.

**Comment by danhut** [comment]
Doh... hang on ;)

**Comment by danhut** [comment]
In the score agenda function we clear any current - then the agenda ability fires - hence the issue.  

Looking through EStrike on netrunner DB someone says:
"Currents aren't trashed as active effects, they're a constant ability. They are removed straight away before triggers."

Doesn't that mean PU's ID should be active?  I am not much good at strict rulings.

**Comment by JoelCFC25** [comment]
See #871 for some history on EStrike...

**Comment by danhut** [comment]
Maybe an extra key on Estrike to tell fn: scored not to do any more than trash the current?

**Comment by danhut** [comment]
Pushed a fix.  It is a bit ugly as PU now has a check for the ID being disabled - so very specific to this issue.  Could not think of something better right now.  Maybe better if any ID listening to events checked for the disable flag by default - rather than hard coding into PU?
