### ISSUE TITLE
Inversificator acting weird

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#2692]
Broke all subs on a code gate, passed it and tried to swap it with an Eli 1.0. Jnet wouldn't let me do it. When I moved the crosshairs over any other ice, it would change back to the hand icon instead of crosshairs.

Tried again, and did the swap before passing the broken ice, and it said it did something, but tried to swap the picked ice with itself (or something, see screenshot).
![screen shot 2017-08-09 at 5 12 39 pm](https://user-images.githubusercontent.com/2024033/29149064-7644c12e-7d26-11e7-8fed-9d3d777d10ca.png)

**Comment by danhut** [comment]
Do you have a screenshot of the entire board - and which code gate was it?    The "." indicates to me something going on - looks more like a derezzed ICE or something,

**Comment by agileminor** [comment]
I don't have a screenshot. The rezzed code gate was Enigma.
There was 1 unrezzed ice on R&D, 2 rezzed ice on a remote (Enigma followed by Eli 1.0). No other ice on the board. My opponent had 3 cards in the remote - a double advanced GFI, a caprice and 1 other card. They were playing ETF and I was playing Kit. I had Magnum Opus, Inversificator, Personal Workshop (with no cards on it), Astrolabe, Beth and SMC out. 

The main symptom was the not being able to select the ice I'd just passed (Enigma) to swap with anything else. The other thing it did, trying to swap ELI with something else might or might not be related.
