### ISSUE TITLE
Stealing Obokata protocol against Selective Mindmapping

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2693]
Log for the game:
vincentkbl accesses Obokata Protocol from Server 1.
vincentkbl pays 4 net damage to steal Obokata Protocol.
vincentkbl steals Obokata Protocol and gains 3 agenda points.
Scythe M.D. uses Chronos Protocol: Selective Mind-mapping to trash Déjà Vu and deal 3 more net damage.
vincentkbl trashes Counter Surveillance, I've Had Worse, I've Had Worse due to damage.
vincentkbl is flatlined.
Scythe M.D. wins the game.
Note: Ive had worse didnèt even fire.

**Comment by danhut** [comment]
How many cards did you have in hand when Chronos fired?

**Comment by vkl125** [comment]
Four, like in log said: Selective Mind-mapping to trash Déjà Vu and deal 3 more net damage.
vincentkbl trashes Counter Surveillance, I've Had Worse, I've Had Worse due to damage.

**Comment by JoelCFC25** [comment]
Seems like this would require the `pay` function to become wait-completed, particularly line 99.

**Comment by JoelCFC25** [comment]
This is closer to correct--replicating the scenario, Runner with 4 cards in grip runs and steals an Obokata, the Corp now correctly intervenes with a "choose the first card to be discarded", then the Runner finishes the steal...but we get a flatline message for some reason before the Runner scoops the points. 
![screen shot 2018-03-18 at 8 56 15 am](https://user-images.githubusercontent.com/10407969/37566673-79e51060-2a8a-11e8-88c9-50c3b555a518.png)

**Comment by danhut** [comment]
Closed via #2877.  Will be live when code next deployed.
