### ISSUE TITLE
Paige Piper + Rolodex interaction alters deck list during game

### ISSUE THREAD

**Issue by J011235** [mtgred/netrunner#2694]
Hello, today I tried for the first time a decklist featuring Paige Piper and Rolodex. When I installed the latter I wanted before Paige pipier to trigger (to elide other copies of Rolodex) and then use the Rolodex reordering ability.
Prompts of the two abilities appeared at mixed times, like it showed me the first 5 cards of deck, then asked me if I wanted to trigger Paige, then asked me to put the 5th card, then asked me how many copies of rolodex to trash, then asked me the 4th card and all others up to final order confirmation.
It would have not bother me the prompts order as there is always possibility of manual fix if any of the 5 cards were other copies of Rolodex, but issue was that after I reordered the 5 cards in the following turns I drawn copies of those 5 cards which were not in my decklist. For istance I have 1 single copy of The Source because otherwise the deck could not comply with influence and yet I drawn a second copy of that card. and that was one of the card I reordered with Rolodex.

**Comment by J011235** [comment]
Thinking more on this I recall that the total number cards of deck didn't change and the interaction deleted two cards at random and substituted them with 1 copy of the 4th and 5th card I put on the deck after reordering.

**Comment by JoelCFC25** [comment]
The issue here is that the `:runner-install` event is fired only after the installed card has been initialized and completed its effect, so this is why Paige will always come first currently. You could shift Paige to the `:pre-install` event but that would lock it into always going ahead of Rolodex and could have other potential ramifications.

**Comment by J011235** [comment]
I'm not saying about order of prompts (which btw is the reverse you said: currently first start rolodex and mid way comes along paige) I'm saying that even if Paige is used to trash 0 rolodex it alters decklist composition

**Comment by nealterrell** [comment]
I might be able to tackle this, it's the same issue we had with  "when you score..." abilities on scored agendas needing to be given the same timing priority as other cards listening for that event.
