### ISSUE TITLE
Holmegaard should not allow access replacement effects

### ISSUE THREAD

**Issue by J011235** [mtgred/netrunner#2698]
Hello, as per UFAQ at https://netrunnerdb.com/en/card/13036 if the first sub on Holmegaard fires and the trace is successful then runners should not be prompted with any access replacement effects at all.
Please fix this lovely ice which defend against siphon spam. Thank you :-)

**Comment by JoelCFC25** [comment]
This means Feint + SecTesting also needs to be checked to make sure they aren't currently combo-ing.

**Comment by J011235** [comment]
right as well as Utopia shard installation when intended as access replacement

**Comment by J011235** [comment]
actually all shards on respective centrals defended by a successful Holmegaard, thanks for your effort

**Comment by J011235** [comment]
even archive interface is an access replacment effect now that I look at it XD

**Comment by J011235** [comment]
or retrivial run also is a replacement effect
