### ISSUE TITLE
No good way to manually work-around Personal Workshop

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#27]
Not sure what to do about this one, but Personal Workshop is unimplemented, and it's not clear how to do a work-around.  Putting cards "on" Personal Workshop just puts them into play.  For a number of cards, you can pretend they're not in play, but for some (such as R&D Interface), which are implemented to work automatically, they sometimes trigger when they shouldn't.

Probably not the biggest of deals, but I wanted to make sure it got recorded.

**Comment by mtgred** [comment]
Personal Workshop has been finally implemented last week.
