### ISSUE TITLE
Oaktown Renovation Triggers Hacktivist Meeting; It Shouldn't

### ISSUE THREAD

**Issue by scifantasy** [mtgred/netrunner#270]
Installing Oaktown Renovation with Hacktivist Meeting in play triggers the "randomly trash one card from HQ" effect of Hacktivist Meeting, which it shouldn't.

It's easy to understand why: Oaktown appears to be implemented so that installing it triggers an immediate rez, and it's a non-ice card...

The problem is that Oaktown isn't _rezzed_, it's just installed faceup, so it shouldn't trigger Hacktivist.

**Comment by nealterrell** [comment]
Fun with border conditions! Thanks for the report, I'll see what I can do.

**Comment by mtgred** [comment]
The fix has been deployed this morning. It should be ok now.
