### ISSUE TITLE
Unnecessary/distracting start-of-turn prompts

### ISSUE THREAD

**Issue by TheRealC** [mtgred/netrunner#2701]
Certain cards like Apex and Out of the Ashes offer a start-of-turn pop-up asking you whether you want to use them. While thoughtful, this leads to a **lot** of turns opening with you having to click "No" several times - even if you _do_ intend to use these start-of-turn abilities, you might wish to order them differently than the order you are prompted in (e.g. first use Chopbot 3000, then activate Apex's ability, then decide whether you want to use Out of the Ashes - while prompt order is Apex first, then Out of the Ashes, then you can manually activate Chopbot).

I do not have an exhaustive list of such cards, but I'd suggest all such cards found get the same treatment as cards like Chopbot, Clone Suffrage and Hades Shard - usable on-demand, with a friendly reminder in the top-right corner that you have start-of-turn abilities you might consider using, as opposed to a potentially intrusive prompt.

Note that this is separate from the ordering of mandatory start-of-turn cards like Wyldside and PAD Campaign, but I guess that's covered already.

**Comment by JoelCFC25** [comment]
For anyone looking to work on this, mimic other cards that employ `:flags {:runner-phase-12 (req true)}`. This gives you the blue notification toast and a pause before you take your clicks to manually fire "when your turn begins" cards in the order you choose. If left unfired, any remaining cards will fire themselves in an order you can't control when you take your clicks.

**Comment by JoelCFC25** [comment]
I took care of Apex but I have no idea how to make this with for Out of the Ashes.

**Comment by nealterrell** [comment]
The problem with Out of the Ashes is you cannot click cards in the Heap to activate them. The Ashes prompt has to be passive (automatically shown when triggered by the engine), making certain interactions impossible, like doing an Ashes run then following that with Chop Bot.

**Comment by TheRealC** [comment]
Yeah, I've only been able to resolve stuff like that before by doing /rfg on the Ashes and adding a click. Not the most elegant solution, but it at least works. I guess implementing interactions with cards in Archives might be kinda rough, so it's workable for now. Honestly I'd be happier without the Ashes pop-up at all, but I realize there probably needs to exist a non-command way to trigger it, and that's seemingly it.

Thanks for your time, regardless ^^

**Comment by NoahTheDuke** [comment]
Start of Turn effects are much better handled now. There are some occasional "unnecessary" prompts, but especially with simultaneous events, we should be down to specific, limited issues. Please open new issues for specific cards/events.
