### ISSUE TITLE
Tori + Hokusai = 2 successful run triggers

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2702]
Had a game with Tori and Hokusai Grid on HQ. Sneakdoor Beta runs reliably made Hokusai Grid trigger twice. (I paid the Tori-tax)

----
Other things that happened in that game included:
The runner clicking Sneakdoor Beta _during a seperate run_ and it did all the things it normally does (costing a click, even);
The Old Hollywood Grid bug showed up again.

**Comment by PesiTheWizard** [comment]
Update: More expansive than I thought. Alice + Tori + Hokusai on archives and paying 2 also made the Hokusai trigger twice. Furthermore, there was some desynchronization where the runner was waiting for the corp to act (via a wait-prompt), and the corp was waiting for the runner to do something.

**Comment by JoelCFC25** [comment]
This is almost certainly just a Tori Hanzo bug. Pretty much all of the code I wrote a couple years ago for damage replacement/substitution (Tori, Titanium, Chronos Protocol) just plain seems to not work anymore.

**Comment by danhut** [comment]
I don't think this fix is live yet:
https://github.com/mtgred/netrunner/issues/2663

Might not be the issue - but would be good to check once it is.

**Comment by PesiTheWizard** [comment]
What a game I just had. Tori+Hokusai with Titanium Ribs. Titanium ribs triggers before Tori, so runner ended up discarding 3 cards per run. On a later Mad Dash run we got buried in prompts so neither knew who was waiting for whom and I had to /close-prompt 3 times after the runner flatlined 4 times to get the run back on track.

----
Titanium ribs did not double the damage taken from Tori, but seems to still do so for Stimhack.

**Comment by JoelCFC25** [comment]
Finally got this. Tori does a `damage-defer` up front, but then once the ability is chosen (Corp says "Yes") the `resolve-damage` function will run the deferred net damage. We have to defer it in case the Corp declines, but if they choose the ability the deferred net has to be dropped since it's being replaced entirely.

**Comment by PesiTheWizard** [comment]
It is with a heavy heart that I must report that post-15. sept 2017, Tori + Hokusai is still bugged.

It just came to me now, but perhaps a part of it is that every time I manage to actually do brain damage this way, it's because I clicked "action before access" and rezzed them. Just before the 2nd damage is done there is a second "corp wishes to act before run is successful" message after the inevitable /close-prompt that the runner has to do.

Silver lining: Titanium Ribs now works even in this situation.

**Comment by JoelCFC25** [comment]
Astonishing. I tested this backwards, forwards, upside down, and every way I could think of before submitting.
