### ISSUE TITLE
Counter Surveillance+Medium interaction

### ISSUE THREAD

**Issue by lakislavko96** [mtgred/netrunner#2706]
Counter Surveillance is replacment efect that says and i quote "instead of accessing, pay X[credit] to access up to X cards from this server" but it also ask Medium whitch is text for card "Each virus counter after the first on Medium allows you to access 1 additional card from R&D whenever you access cards from R&D." In my opinion it should be CS negate the effect of Medium and Medium should not trigger.

**Comment by JoelCFC25** [comment]
All the Counter Surveillance problems are stacking up in #2661.
