### ISSUE TITLE
Price of Freedom is eternal vigilance and a borked log.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2709]
- [x] Experienced Price of Freedom for the first time just now. After it was used, any time the runner trashed any card, the text from Price of Freedom popped up.
> Aesynil trashes Sacrificial Construct to prevent the corp from advancing cards during their next turn.

*Here they were preventing a hardware trash.*
This also happened when trashing cards due to damage, though I should mention that Titanium Ribs was installed.

----
- [x] Security nexus seems to let the runner use it more than once per turn.

**Comment by JoelCFC25** [comment]
> Security nexus seems to let the runner use it more than once per turn.

Fixed at 6e9d460.

**Comment by JoelCFC25** [comment]
Price of Freedom is all kinds of wrong. It needs to register a `:corp-turn-begins` event that sets a turn flag for not advancing cards, not a persistent flag. And it shouldn't have a `:runner-trash` event hook at all. 

Also, the new options in `pay` for trashing program/hardware/connection all need `{:unpreventable true}` as an argument, as if you prevent the trash then you haven't paid the cost.
