### ISSUE TITLE
resolve-ability called twice when rezzing cards

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#271]
Resolve-ability is being called twice when rezzing corp cards, which is why we are seeing #261, #254, and #252. On [core.clj line 958](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core.clj#L958), `rez` calls `card-init`, which calls `resolve-ability` on the rezzed card's `card-def`. `rez` then itself calls `resolve-ability` on the `card-def`, triggering the "on-rez" effect of the card a second time. For most cards this is no big deal, but it is an issue for Elizabeth Mills, illicit ice, and any ice that prompt on rez (Draco, TMI, Chimera).

I don't know if this is intentional and/or needed for some card interaction, so I have not submitted a fix for it.

**Comment by mtgred** [comment]
Thanks for the analysis. The `resolve-ability` call in the `rez` function was introduced in this merge 2fe828e

I'm tempted to remove it but it might have an impact on the rest of your code. Can you have a look at it?

**Comment by nealterrell** [comment]
Huh, looks like I'm guilty. I don't see a reason for it there, but I will think about it and let you know if I find otherwise.
