### ISSUE TITLE
Joshua B. triggers before MaxX draw

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#2711]
The prompt for deciding to take Joshua click appears before MaxX draw. It is my understanding the runner should be able to decide on the order since they all trigger on "Start of Turn".

**Comment by JoelCFC25** [comment]
MaxX is currently set to only notify for `:runner-phase-12` if there are other cards active flagged with `:runner-draw true`. Joshua B. isn't flagging for `:runner-phase-12` at all, but you can currently click to use him prior to hitting Start Turn (that ability isn't restricted to usage during phase 1.2 like it should be).

**Comment by Saintis** [comment]
Would this best be fixed by adding `:runner-phase-12` stuff to Joshua B.?

**Comment by JoelCFC25** [comment]
Right, the absence of `:flags {:runner-phase-12 true}` means Joshua B. doesn't provide the blue toast and the "pause" to manually trigger abilities prior to the "Take Clicks" button. Everything with this flag that goes unclicked will end up firing when you take clicks, but you've lost control over the order in which they resolve at that point. 

What's the scenario in which the order of Joshua B. and MaxX matters?

**Comment by Saintis** [comment]
The new tag-me Counter Surveillance deck archetype means you might want to go tag-me after drawing some key piece. So you want Joshua B. and God of War to trigger after MaxX.

**Comment by JoelCFC25** [comment]
Feast your eyes on all the open Counter Surveillance issues...

**Comment by Saintis** [comment]
This could be relevant to DLR or any other type of MaxX as well when you want to trigger optional before mandatory. Does MaxX trigger before Bloo Moose for example? But I agree with your point
