### ISSUE TITLE
Titanium ribs makes runner take additional damage?

### ISSUE THREAD

**Issue by the0dox** [mtgred/netrunner#2714]
scenario: I had titanium ribs installed with 4 cards in hand, I steal the obotaka and am prompted to select which cards to trash, I select all 4 cards and trash them. The text box then claims with no indication why, that I was flat-lined.

**Comment by JoelCFC25** [comment]
This is a duplicate of #2668. A fix is already in the works.

**Comment by the0dox** [comment]
oh, wasn't aware of this, sorry for bothering

**Comment by JoelCFC25** [comment]
No problem!
