### ISSUE TITLE
Employee Strike not clearing properly.

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#2717]
The last few games I have played as Corp with Jinteki: Potential Unleashed the Corp ID has fired perfectly fine. Then when the Runner plays Employee Strike, the ID is turned off, as it should be (no trashing the top card of the deck when net damage occurs). Once Employee Strike has been cleared however, the Corp ID has not triggered properly again even once for the entire of the rest of the game.

This was always with Employee Strike being cleared through an agenda score, rather than playing a Corp current, if that's any help. I thought it was a weird bug the first time it happened, as I've never seen it happen before, but it seems to happen every game now.

**Comment by HubGitAccoutn** [comment]
I've just looked at a fix for #2688 a few days ago, which seemed to be something to do with Philotic Entanglement, I was going to say that the problem occurred with other agendas being scored, not Philotic.

But looking at the change log for that fix ("fix #2688" in "fixes #2683") and bearing in mind I don't really know what any of the code I'm looking at means(!), the fix seems to introduce some kind of new variable or flag called disable-id, setting it to true I assume when Employee Strike is played, but I can't see a method in the change log for it to ever get set back to false. This isn't the source of the issue is it?

**Comment by JoelCFC25** [comment]
> I can't see a method in the change log for it to ever get set back to false

It's [here](https://github.com/mtgred/netrunner/blob/master/src/clj/game/core/actions.clj#L404). Will take a look at what's going on here.

**Comment by JoelCFC25** [comment]
I think Employee Strike just needs to clear this custom key as part of its `:leave-effect`.
