### ISSUE TITLE
Scoring Accelerated Beta Test with fewer than 3 cards in R&D leaves game stuck on "Waiting for corp to resolve agenda-scored triggers"

### ISSUE THREAD

**Issue by coljac** [mtgred/netrunner#2724]
Accelerated Beta Test was scored when the corp had one card remaining. They used the "may" ability (perhaps accidentally) and there were not 3 cards to install or discard. Corp trashed the last card in R&D and ended their turn, but the ABT still had a "3" counter and as the runner I only saw "Waiting for corp to resolve agenda-scored triggers".

![abt_stuck](https://user-images.githubusercontent.com/191407/29746384-d08adc56-8b1b-11e7-80f0-5f691980db7c.png)

**Comment by danhut** [comment]
The fix would be to block it firing if they have less than 3 cards in R&D right?
