### ISSUE TITLE
Titanium Ribs -  double damage w Obokata/ Doesn't end access after stealing agenas

### ISSUE THREAD

**Issue by PickAUsername5** [mtgred/netrunner#2726]
I've had issues with this card a few times with ICE like Chiyashi, and self-harm cards (Mad Dash) but when trying to reproduce the only thing I can do consistently is suffering double damage with Obokata (4 using Titanium Ribs, and 4 more on top of that). 

![obokata-jnet](https://user-images.githubusercontent.com/31433495/29812274-b29ed3fc-8cae-11e7-8ae0-0f6be4958fb7.jpg)

Also, when stealing angena from RnD with Titanium Ribs installed, access doesn't end. Tested only against PE.

![multiple-access-jnet](https://user-images.githubusercontent.com/31433495/29812295-c11ddefa-8cae-11e7-923f-65238380a74c.jpg)

**Comment by JoelCFC25** [comment]
As per the site News Header, Titanium Ribs is known to be bugged. The fix is in #2708.
