### ISSUE TITLE
PAD Factory doesn't let you advance your opponents' cards

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#2728]
Apologies for how narrow this issue is, but PAD Factory does not allow you to advance your opponent's cards (which is newly sorta relevant for Mass Commercialization purposes, and I suppose always interesting for Trick of Light).

Can resolve manually with "/counter ad 1" command, however.

**Comment by Saintis** [comment]
Should be easy fix to allow for runner cards to be targeted as well.
