### ISSUE TITLE
Awakening Center is charging its rez cost to install cards

### ISSUE THREAD

**Issue by wombat929** [mtgred/netrunner#2730]
When I install a piece of ice on Awakening Center, it is charging 2 credits. this should be free.

**Comment by JoelCFC25** [comment]
Thanks for the report. It wasn't charging a fixed 2c, but rather factoring in the number of pieces of ICE protecting the server (so I assume you had 2 at that time).

**Comment by wombat929** [comment]
I thought that is what it was doing too -- but I tried removing and adding ice and it was always 2 creds.  That said, if you fixed the bug, you fixed the bug! Thanks.
