### ISSUE TITLE
Oversight AI won't work with Tithonium

### ISSUE THREAD

**Issue by coljac** [mtgred/netrunner#2734]
Playing Oversight AI (rez ICE ignoring all costs) targeting Tithonium brings up the prompt "Do you want to pay the alternative Rez cost?" (forfeit an agenda). If the corp selects no, the ICE remains unrezzed. 

I did not have the 9 credits to pay the non-alternative rez cost, so I don't know if the game would take deduct the 9 at that point.

**Comment by danhut** [comment]
I just tested it and it works ok.  Can you you give a more context on the game state?
In my test: First action install Tithonium on HQ, second action Oversight it.

Also wrote an automated test case which passed... so something is going on less obvious

```
(deftest tithonium-oversight-ai
  ;; Do not prompt for alt cost #2734
  (do-game
    (new-game (default-corp [(qty "Oversight AI" 1) (qty "Tithonium" 1)])
              (default-runner))
    (play-from-hand state :corp "Tithonium" "R&D")
    (let [ti (get-ice state :rd 0)]
      (play-from-hand state :corp "Oversight AI")
      (prompt-select :corp ti)
      (is (get-in (refresh ti) [:rezzed]))
      (is (= "Oversight AI" (:title (first (:hosted (refresh ti)))))
          "Tithonium hosting OAI as a condition"))))
```

**Comment by coljac** [comment]
Interesting - tried it twice in game with the same result.

Corp had 7 credits and 2 agendas scored.

Will see if I can reproduce; if not, will suggest closing for now.

**Comment by butzopower** [comment]
Can confirm I had this happen when I trashed a Muertos Gang Member.
