### ISSUE TITLE
Update Readme to explain how to use compose.sh

### ISSUE THREAD

**Issue by cwgreene** [mtgred/netrunner#2739]
A new Docker compose script has been added to the repo, however, instructions for setting up a local server still use the old manual npm + lein + figwheel + java instructions. The Readme should be updated to reflect the new dev startup process.

**Comment by Saintis** [comment]
I don't think the compose script in normal dev setup. I still use the process described in the README.

**Comment by NoahTheDuke** [comment]
Fixed with #3882
