### ISSUE TITLE
I've Had Worse not drawing 3 when trashed by damage

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#274]
IHW failing to draw when soaking damage was reported in chat. Tested just now by faceplanting a Shock! with IHW as my lone card in hand. 1 net damage was dealt and no cards were drawn--I only got the prompt asking if I wanted to trash Shock!. 

It's also failing for meat damage--tested by stealing an agenda from Argus Security with 2 cards in hand (1 IHW) and elected the 2 meat damage option. No cards drawn. 

Not sure if the new functionality is bugged or if this was from a temporary rollback on the live server...

**Comment by nealterrell** [comment]
Looks like an issue of passing the variadic arguments `& targets` from `trash` to `resolve-trash`. I thought you could just pass them as another argument, but that wraps the arguments in a sequence. I will submit a fix soon.

**Comment by JoelCFC25** [comment]
Fixed by #275.  :+1:
