### ISSUE TITLE
Spectating password protected games multiplies everything

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#2741]
Twice tonight, I've joined a password protected game and found that everything in chat is doubled. Left the game and rejoined, and three copies of me as spectator were present, and runner card installs were doubled too.

**Comment by JoelCFC25** [comment]
Can you still get this to occur after today's update?

**Comment by JoelCFC25** [comment]
Closed due to lack of response (and because a zillion things have changed on the front end in the last 6 months)...
