### ISSUE TITLE
Clicking on an installed Earthrise Hotel causes a power counter to be spent and cards to be drawn

### ISSUE THREAD

**Issue by x3N1GM4x** [mtgred/netrunner#2753]
Perhaps there is some deliberate reason why the ability of Earthrise Hotel (to draw 2 cards for a cost of one power counter) can be triggered manually by clicking the card, but I thought it should only trigger on the start of the runner's turn?

Maybe there's some strange scenario where it might not trigger, so it's been written to allow this manual trigger, but even then it's not particularly difficult for the players to fix the game state themselves (removing a counter and drawing two cards for free), so I wonder if this might be a bug?

**Comment by JoelCFC25** [comment]
> Perhaps there is some deliberate reason why the ability of Earthrise Hotel (to draw 2 cards for a cost of one power counter) can be triggered manually by clicking the card

Yes. The Runner can order "when your turn begins" effects in the order they see fit (or let them fire automatically). 

The ability needs `:req (req (:runner-phase-12 @state))` added.
