### ISSUE TITLE
Titanium Ribs interaction with Amped Up and Jinteki:PE

### ISSUE THREAD

**Issue by Apoorrich** [mtgred/netrunner#2757]
Titanium Ribs seems to be dealing double brain damage with "amped up".

Furthermore, the Jinteki:Personal Evolution corp identity doesn't fire when the runner is dealt net damage while titanium ribs is installed, i.e. it doesn't trash the top card of the stack.

Thanks for your effort.

**Comment by JoelCFC25** [comment]
Fixed at #2708, not yet deployed.
