### ISSUE TITLE
Power Shutdown Glitch

### ISSUE THREAD

**Issue by darlingsensei** [mtgred/netrunner#276]
The dialogue to trash cards pops up, but it is an empty orange button with no way to select the number. It also prevents you from just dragging from R&D to archives or HQ and overrides your normal turn actions.

**Comment by mtgred** [comment]
You have an old version of the Javascript file. Refresh your browser and things should be ok.

**Comment by JoelCFC25** [comment]
I also think this one as bugged--I have a fully cleared cache, forced refresh of the site, etc--I got the same behavior as @darlingsensei. Orange button with no text or choices, then no way to proceed.

**Comment by mtgred** [comment]
I forgot to update the javascript file on the server . If you refresh your browser now. Power Shutdown should work.

**Comment by darlingsensei** [comment]
Confirm Power Shutdown is now working.
