### ISSUE TITLE
Same Old Thing trashing even if u dont have cash to play event from the heap

### ISSUE THREAD

**Issue by fingerzz96** [mtgred/netrunner#2766]
SAM goes in bin even if u dont have credits to pay for the event. Can some one fix this issue since it should not allow you to play that event if you dont have enough to played and not to consume clicks?

**Comment by JoelCFC25** [comment]
The reason SOT doesn't consider your credit total with regard to events in the heap is the existence of Prepaid VoicePAD and Public Terminal. Available recurring credits on those cards won't be in your pool until you pull them off, which players probably wouldn't always think to do before popping SOT.

**Comment by danhut** [comment]
I wonder if SOT (and similar) could be upgraded to give an option to "undo-click" via a button, as well as allowing a choice of cards to handle this... I think it provides the same outcome.

**Comment by NoahTheDuke** [comment]
Given the existence of /undo-click, I'm gonna close this one.
