### ISSUE TITLE
Warroid Tracker glitch?

### ISSUE THREAD

**Issue by FightingWalloon** [mtgred/netrunner#2767]
I played two games today where I think Warroid Tracker was creating glitches.

I was Stronger Together and Runner in both games trashed a card in remote triggering Warroid Tracker trace. In both games, they lost trace and trashed cards. In second game, The Runner could only trash one card with the automatic interface and had to manually trash the other.  (Maybe happened in first game, too, but player did not type anything about that.)

Runner was then caught where the game would not let the run end. They could not jack out and /close-prompt did not fix the problem. I'm not sure if it would have helped had I as Corp also /close-prompt. I had a message saying the game was waiting for the Runner to resolve successful run triggers (I think).

Both games had to be abandoned because we could not move it forward.

In the second game, the remote had an Ash and an MCA Austerity Policy in it. In the first game, I know there was no MCA, but I do think there was an Ash and a Batty as well.

**Comment by JoelCFC25** [comment]
Can do some more tests, but an initial attempt in dev with a rezzed Warroid Tracker, rezzed Ash, and an asset in a remote had everything work as expected.

**Comment by FightingWalloon** [comment]
I wish I could describe better what happened. Thanks for looking. Maybe it was an isolated issue or if it keeps happening maybe someone else can notice something important to the situation that I missed.

**Comment by danhut** [comment]
A screenshot next time if you can!  I implemented Warroid and have not seen an error yet which worries me - as I expected to get a ton.
