### ISSUE TITLE
Corporate Defector revealing too many cards

### ISSUE THREAD

**Issue by FightingWalloon** [mtgred/netrunner#2770]
I played a game where I installed Corporate Defector. I'm pretty sure it then showed me cards that the Corp drew as Mandatory Draw. The card says it only shows cards drawn by using a click.

**Comment by danhut** [comment]
I don't think possible.  Not expecting you to read the code but here it is - you can see it only fires when the corp clicks to draw (:corp-click-draw)
```
   "Corporate Defector"
   {:events {:corp-click-draw {:msg (msg "reveal " (-> target first :title))}}}
```

**Comment by FightingWalloon** [comment]
My apologies. I must have read the log of the game wrong. Sorry to waste your time.

**Comment by danhut** [comment]
All good - we do get a few errors - if you see something it can be helpful to screenshot the whole board and post it.  thanks!
