### ISSUE TITLE
Opponent is typing indicator - can add vertical scrollbar at some resolutions

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#2773]
From Dev Slack:

I think the typing indicator looks fine , although for me (running Chrome 61.0.3163.91 at a res of 2048x1152 with an in-browser zoom of 125%), whenever the typing indicator appears, it causes a second vertical scrollbar to appear to the right of the chat window, which in turn pushes the chat window itself to the left slightly...

**Comment by x3N1GM4x** [comment]
Example of the issue:

![image](https://user-images.githubusercontent.com/10621139/30567245-66ec2c56-9cc7-11e7-891e-978dc93a6a5e.png)
