### ISSUE TITLE
Leave no trace derez all ice that were rezzed on previous turns..

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2775]

**Comment by JoelCFC25** [comment]
I don't have a rewrite handy, but I would approach this card differently. Start listening for rezzes of ICE when the run starts and record a list of their `:cid` in the card, consult that list when the run ends to do derezzing, then drop the list.

**Comment by danhut** [comment]
I tested this and it works fine for me using Ice Walls as the ICE.  This will need a screenshot and a complete list of steps to reproduce this.

**Comment by JoelCFC25** [comment]
Fixed by #3122.
