### ISSUE TITLE
Old Hollywood Grid Preventing All Steals

### ISSUE THREAD

**Issue by NothingPersonal12** [mtgred/netrunner#2776]
Similar to #2344, Old Hollywood Grid is not working correctly. I've reproduced it at least once, as well.
1. trashing a rezzed Old Hollywood Grid, then running the same server prevents from stealing the agenda. I've verified this at least once.
2. Attempting to steal an agenda from a server where there was no Old Hollywood Grid present at any point fails to steal the agenda.
3. Attempting to steal an agenda from a central server does not allow for a steal either.

**Comment by JoelCFC25** [comment]
One issue for this is enough--let's keep ongoing reports and progress (if any) in that one.
