### ISSUE TITLE
The Cleaners causes additional damage when Titanium Ribs or Respirocytes installed

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#2780]
Titanium Ribs deal 3 damage (instead of 2) to runner. Respirocytes only deals 1 but log prints that The Cleaners cause 1 additional damage.

This will likely only be an issue while people play Salvaged Vanadis Armory...

**Comment by JoelCFC25** [comment]
*barf emoji*

**Comment by Saintis** [comment]
Seems like `:unboostable` is used in Respirocytes, NRE, Dadiana and Argus to prevent The Cleaners from having an effect.

Will add that to Titanium Ribs and change requirement of The Cleaners so log isn't printed for damage from runner.

**Comment by JoelCFC25** [comment]
Oh, I guess that wasn't so bad then. Nice!
