### ISSUE TITLE
Gang Sign is treated as successful run to HQ

### ISSUE THREAD

**Issue by SentulAsia** [mtgred/netrunner#2783]
![screen shot 2017-09-22 at 12 44 59 pm](https://user-images.githubusercontent.com/476734/30729857-2e518cb2-9f95-11e7-9510-16509c6bd403.png)
 
attached is the board state when the bug happens, corp score an agenda, gang sign trigger with multi access, runner gets some error popup and corp is asked to react to the successful run.

**Comment by JoelCFC25** [comment]
Did the Corp score the agenda on the Runner's turn? In that picture the Runner has 4 clicks, which has to mean they already hit Start Turn. Scoring an agenda on the Runner's turn is not allowed, even if the system lets you do it. This is probably the source of the error.

**Comment by lakislavko96** [comment]
The worst thing that also works with The Gauntlet. But it should not work with GS

**Comment by Saintis** [comment]
The error pop-up for the runner might also be useful.

**Comment by SentulAsia** [comment]
@JoelCFC25 I decided to take the screenshot way after the error occurred and runner has started to take his turn (but we were still discussing about that and I decided to scroll up and take a screenshot.

@Saintis The runner claimed that there is an error popup before he could start his turn but sadly I didn't ask what's the text inside the error popup...

**Comment by danhut** [comment]
Where is the runner multi-access coming from here?
I see two Gang Sign - each of which will get 1 access.  But in the log I can see two access per Gang Sign.  

I don't actually even see an error other than this.  Am i missing something?

**Comment by SentulAsia** [comment]
@danhut this happens on corp turn after an agenda is scored:
1) employee strike is trashed
2) gang sign is triggered ** WITH the gauntlet multi access (it is treated as a successful run instead of gang sign access)
3) aenas also seems to be triggering separately...

**Comment by danhut** [comment]
Thanks - i tried a few times and cannot reproduce I am afraid.  Gang Sign definitely does not enter the game into "run" state so must be something else.

**Comment by Saintis** [comment]
Maybe this similar to the open access window errors we had with the Executives a while back?
