### ISSUE TITLE
Black level clearance interaction with a bunch of stuffs.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2784]
After clicking take 1 brain damage, a bunch of weird stuff happens.

Here's the log: 
CKirk rezzes Breaker Bay Grid.
CKirk rezzes Black Level Clearance.
CKirk rezzes Ryon Knight.
CKirk uses Ryon Knight to do 1 brain damage.
vincentkbl trashes The Shadow Net due to damage.
CKirk has no further action.
vincentkbl continues the run.
CKirk rezzes Adonis Campaign.
CKirk has no further action.
vincentkbl could not afford to use Counter Surveillance.
vincentkbl trashes Apocalypse due to damage.

**Comment by JoelCFC25** [comment]
This just isn't enough information to go on. You have to be WAY more thorough with these reports if you want anything to happen. It was a Counter Surveillance run? What happened compared to what was supposed to happen?

**Comment by vkl125** [comment]
A run on a server with Black level clearance and ryon knight and breaker bay grid and adonis campaign installed. Runner clicks Take a brain to continue the access while Counter surveillance was installed. Then took another brain damage and run ended without other accesses.
