### ISSUE TITLE
Enhancement: Aumakua - handle replacement run effects like Ash 2X3ZB9CY or non-run access like Gang Sign/Raymond Flint

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#2788]
Took a quick look at this for Ash 2X3ZB9CY - same issue as any other card where we go direct to `handle-access`.  I think this would need a some work to flag when a set of accesses starts, and then when the final access is done for the event.  

Might be a bit painful ;0

**Comment by NoahTheDuke** [comment]
I think this is handled.
