### ISSUE TITLE
Disposable Hq run keeps prompting and firing again with multiple successful runs.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2797]
Screenshot shows the scenario.

![image](https://user-images.githubusercontent.com/18687557/31042056-b1f00112-a55c-11e7-9191-703d512ce181.png)

**Comment by JoelCFC25** [comment]
Again this is not a complete report. How many copies of Disposable HQ were in Archives? If there were 2 or more, each will fire.

**Comment by x3N1GM4x** [comment]
After getting some help from @nealterrell to resolve this one, I'd humbly suggest the "easy" tag was probably inappropriate. 😉

**Comment by JoelCFC25** [comment]
I'm going to defend the easy tag because I knew what the game plan needed to be to fix this one, but real life got in the way

**Comment by x3N1GM4x** [comment]
It's all good @JoelCFC25, I'm only kidding around. Heck, if I could implement the solution (even with help), it can't have been *that* difficult! 😉
