### ISSUE TITLE
En passant doesnt fire vs AgiInfusion change server run.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2804]
Pugontoast spends  to make a run on Archives.
vincentkbl spends 2  to rez Sand Storm.
Pugontoast indicates to fire the "Move Sand Storm and the run to another server" subroutine on Sand Storm.
vincentkbl spends 1  to rez Panic Button.
vincentkbl uses Sand Storm to move Sand Storm and the run. The Runner is now running on HQ. Sand Storm is trashed.
vincentkbl has no further action.
Pugontoast continues the run.
vincentkbl has no further action.
Pugontoast accesses Marcus Batty from HQ.
Pugontoast pays 1  to trash Marcus Batty from HQ.
Pugontoast accesses Panic Button from the root of HQ.
Pugontoast uses Maw to force the Corp to trash a random card from HQ.
Pugontoast spends  to play En Passant.

Pugontoast
mind if I take that back? I thought it would work on HQ

vincentkbl
sure

Pugontoast
ty ty
Pugontoast sets click to 1 (+1).
Pugontoast moves En Passant from their Heap to Grip.

**Comment by Saintis** [comment]
I think the best way to deal with this would be not enforce En Passant's restriction as heavily. Tracking which ice may or may not have been passed as unrezzed is likely to be a nightmare.

Solution: reduce requirement of ice selected for En Passant to just `ice?` and `not rezzed?`.

**Comment by nealterrell** [comment]
Agree with @Saintis.
