### ISSUE TITLE
Chat very often does not display message

### ISSUE THREAD

**Issue by tobiasfielitz** [mtgred/netrunner#2805]
My internet connection is not the best currently, but nevertheless the chat shouldn't swallow any messages. Quite often I have to type and send it twice.

_I have cleared my cache and refreshed the page._

Chrome Version 61.0.3163.100 (Official Build) (64-bit) on OSX

<img width="806" alt="screen shot 2017-10-02 at 7 47 12 pm" src="https://user-images.githubusercontent.com/9712861/31070047-aecfb054-a7aa-11e7-81e5-4b14c8e003c4.png">

**Comment by LiteSpecter** [comment]
I have experienced this issue recently as well

**Comment by x3N1GM4x** [comment]
I've experienced this a few times too.

**Comment by danhut** [comment]
It will be valuable to know if the opponent gets the message once or multiple times. 

The only chat change in a long time is the "someone is typing" indicator which sets a flag in the game state.  I cannot think why that would cause the issue as yet. 

Any chance of a screenshot so we can see the message size?

**Comment by tobiasfielitz** [comment]
@danhut Pretty sure the opponent doesn't get it at all, it just doesn't show up in the chat. Messages can be as short as "gg". Or do you mean payload message size of a request?

**Comment by danhut** [comment]
@tobiasfielitz Thats helpful.  I was wondering if short messages are the cause - ie. if we rapidly move from a game state with the "someone is typing" state set, to one where it is removed.  

The state is set when you hit the first key of a message.

The removal happens when someone either hits Return/Enter to send their message, or when they delete all the contents of the field.

**Comment by danhut** [comment]
Not reproducible on my local machine - but seems to happen often on the live server.  I *think* it happens with short/fast messages only.  Given I have no access to the live server I am pretty stumped.
