### ISSUE TITLE
Full Immersion RecStudio (Multiple)

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#2811]
Bug: A trashed Marlyn Campaign will not prompt a reshuffle when it is hosted on Full Immersion RecStudio.

Bug (rather low priority): Breaker Bay Grid cost reduction does not properly apply to cards hosted on a nested RecStudio. It applies properly to the cards hosted on the root RecStudio, but if the corp installs another RecStudio on top of the first, the BBG reduction is lost.

Enhancement: Current implementation of cards like Restore show RecStudio as a possible location for asset installation, is this method possible for installing assets from HQ?

**Comment by JoelCFC25** [comment]
Part one:  `:req (req (= :servers (first (:previous-zone card))))` probably needs to be: 
`:req (req (= :servers (first (:previous-zone (get-nested-host card)))))`

**Comment by nealterrell** [comment]
Part 2: likewise, Breaker Bay Grid should be comparing the zones of its own nested host and the target's nested host. This could probably use a new `nested-zone` function or similar.

**Comment by nealterrell** [comment]
Part 3: probably not. The UI that shows for installing a card from hand is fundamentally different from the UI you get when a card triggers an install effect without specifying a server. I suppose we could just abandon the former.

**Comment by nealterrell** [comment]
@JoelCFC25 hmm, the previous-zone for a Marilyn on RecStudio is probably going to be `[:onhost]`. That would probably be sufficient evidence to conclude it was trashed while installed on a host.
