### ISSUE TITLE
Rotate symbol should not correspond to faction

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#2820]
Also, I think rotation symbol should not have faction specific colour, but rather just red colour (or similar).

**Comment by Saintis** [comment]
Nevermind, the weyland dark-green constrast was too poor with the background. My colour point still stands, will rename.

**Comment by jwarwick** [comment]
I'm open to tweaking the colors for MWL and rotation. I tried Neutral and Black, but neither seemed quite right.

If someone wants to suggest a color I can change it easily.
