### ISSUE TITLE
Cache Refresh compliance and Core 2.0

### ISSUE THREAD

**Issue by FightingWalloon** [mtgred/netrunner#2828]
None of my Cache Refresh decks are showing up as Cache Refresh compliant. My suspicion is that the Cache Refresh settings are still using Core 1.0, but it might be something else.

If this helps, here is one of my decks that shows as tournament legal but not Cache Refresh compliant, even thought it is.

Khan: Savvy Skiptracer

Creation and Control (10)
3x Sahasrara ( 47)  ●●●●● ●
1x Ice Analyzer ( 51)  ●
3x Dirty Laundry ( 52)
3x Daily Casts ( 53)

Blood Money (2)
2x Golden ( 25)

Escalation (2)
2x Peregrine ( 44)

Intervention (7)
2x The Gauntlet ( 63)
2x Saker ( 64)
2x Blockade Runner ( 65)
1x Citadel Sanctuary ( 70)

Martial Law (1)
1x On the Lam ( 82)

Blood and Water (1)
1x Keros Mcintyre ( 65)

Revised Core Set (17)
1x Stimhack ( 5)  ●
2x Datasucker ( 9)  ●●
2x Scrubber ( 17)  ●●
3x Easy Mark ( 20)
2x Inside Job ( 23)
1x Special Order ( 24)
3x Sure Gamble ( 56)
3x Armitage Codebusting ( 59)

12 influence spent (max 12, available 0)
40 cards (min 40)
Cards up to Revised Core Set

Deck built on https://netrunnerdb.com.

**Comment by nealterrell** [comment]
Indeed, the validation is looking for "Core Set" instead of "Revised Core Set".
