### ISSUE TITLE
Kakugo net damage missing.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2835]
Gerrark spends  and 2  to play Spear Phishing.
Gerrark uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
vincentkbl has no further action.
Gerrark continues the run.
vincentkbl has no further action.
Gerrark accesses Biotic Labor from HQ.
Gerrark accesses Crisium Grid from the root of HQ.

vincentkbl
where's the net damage
ALSO:
When runner passes it by manually clicking -1 credit , net damage doesn't fires.

**Comment by nealterrell** [comment]
This subroutine is manually activated by the Corp player.

**Comment by nealterrell** [comment]
By subroutine, I meant effect.

**Comment by nealterrell** [comment]
Just to be sure, Kakugo was rezzed? I only ask because there's nothing in the log about the subroutine being broken, but you probably just filtered it.

As for the -1 credit thing, that's irrelevant here -- the card is hooked up to the `:pass-ice` event, which is supposed to trigger when Continue Run is pressed.

**Comment by vkl125** [comment]
Kakugo was rezzed a few turns before that's why it isn't in the timeframe of the log. I'd agree with what you are saying with the -1 credit thing.

**Comment by nealterrell** [comment]
Any trickiness with the way it was installed or rezzed? Thanks.

**Comment by vkl125** [comment]
No, just plain old install and rez and spearphising bypass.

**Comment by danhut** [comment]
Works perfectly for me.  Not sure what happened and no chance we can deal with it IMO.

**Comment by Saintis** [comment]
Do you have any memory if the Kakugo was swapped at some point in the game before this bug appeared?

**Comment by vkl125** [comment]
Nope.

**Comment by vkl125** [comment]
Just assume there is a redirect. test it with AGInfusion.
