### ISSUE TITLE
Foundry draw (potentially) not shuffling

### ISSUE THREAD

**Issue by vache** [mtgred/netrunner#2836]
Runner had an effect to see top card of R&D, runs R&D, corp rezzes ICE and triggers Foundry draw, runner breaks ICE and accesses the card they saw originally, seemingly indicating that the shuffle never occurred.  

The code seems to indicate that the shuffle happens, so it is possible that it simply shuffled another copy of the original card on top, but this would be improbable.

**Comment by nealterrell** [comment]
Improbable, but not impossible. I don't see a way that Foundry's message and effect could have happened without the shuffle. Unless this is reproducible, I'm calling it random chance.
