### ISSUE TITLE
"Rematch" button to automatically create a new game with same opponent, and option to switch sides

### ISSUE THREAD

**Issue by hbarsquared** [mtgred/netrunner#2839]
It would be useful to have a rematch button, since it's a pretty common occurrence. Maybe require both parties to agree - i.e. one player clicks "Rematch", causing a "Rematch? Yes/No" prompt to appear for the other player. If both agree a new game is created and they are brought to the side/deck selection screen. Passwords and other settings should remain the same, and spectators ideally would also remain.

**Comment by nealterrell** [comment]
This is a lot more complicated than it may sound, because the server has no way of triggering a client to join a game and show the deck select screen... those screens are entirely controlled client-side. It's a good idea but don't hold your breath :(.

**Comment by yads** [comment]
Even if this feature simply re-created the same lobby as was used to create the game, that might be 80% of the way there.
