### ISSUE TITLE
Dedicated Processor / Femme

### ISSUE THREAD

**Issue by NorwegianLegion** [mtgred/netrunner#2846]
Dedicated Processor disappeared from host (Femme Fatale) and game after trashing an ice with a Femme token on it.

**Comment by nealterrell** [comment]
Nothing stands out after a quick scan... How was the ice trashed? Can you reproduce this?

**Comment by NorwegianLegion** [comment]
Runner: Install Femme Fetale => Choose ice for token => Install Dedicated Processor on Femme
Corp: Drag ice with token to archives => Dedicated Processor disappears from Femme and is not in Runner's heap. I'll try to take some screenshots.

**Comment by NorwegianLegion** [comment]
![dedicated_femme](https://user-images.githubusercontent.com/12424752/31314245-bde2b512-abc1-11e7-9fa4-f306d28a9452.JPG)
![dedicated_femme2](https://user-images.githubusercontent.com/12424752/31314271-513bf026-abc2-11e7-81a5-384a8773157a.JPG)

**Comment by nealterrell** [comment]
Confirmed this also happens with The Personal Touch...hmm.
