### ISSUE TITLE
Film critic and The Future Perfect doesn't work,.

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#2847]
![image](https://user-images.githubusercontent.com/18687557/31304050-417faed0-aad6-11e7-87f4-7538bddc9a7f.png) Tried pressing film critic on You must "access the agenda".

**Comment by JoelCFC25** [comment]
Can't replicate. Using Film Critic while the "Access" prompt is displayed is the correct time. The fact that the psi prompt is showing in the picture makes it look like Access was clicked instead.

**Comment by vkl125** [comment]
Yeah I clicked the host agenda on film critic during the "Access" prompt. Nothing happened. That's why I tried the psi game phase to host it and hence the screen shot.

**Comment by JoelCFC25** [comment]
OK, I have this one figured out now.

**Comment by JoelCFC25** [comment]
I took care of this in #2857, but will still have to revisit a method of stopping FC once the TFP psi game has started.
