### ISSUE TITLE
Wrong rez cost with Quarantine System

### ISSUE THREAD

**Issue by lorion42** [mtgred/netrunner#2849]
If you use Quarantine System to forfeit a Hostile Takeover the rez cost of each ice stays the same. The cost is not lowered. I use them in Jemison so I'm not sure if the problem is associated with the IDs abbility. I also tried to use a New Construction to rez a Fire Wall but then I didn't pay anything. The correct cost should be 1 credit (5-2x2)

**Comment by JoelCFC25** [comment]
This seems like a Jemison issue, as I tested it in a draft ID and Quarantine System correctly reduced rez cost of ICE by 2 credits after forfeiting a Hostile Takeover. 

> I also tried to use a New Construction to rez a Fire Wall but then I didn't pay anything. The correct cost should be 1 credit (5-2x2)

I am not following this at all. New Construction should not have any impact on rez cost unless there are 5+ advancements on it, in which case rezzing for free is correct.

**Comment by JoelCFC25** [comment]
Oh, now I understand. You were using QS to forfeit a scored New Construction. I tried this just now and it looks OK: 
![screen shot 2017-10-07 at 10 07 01 am](https://user-images.githubusercontent.com/10407969/31309155-59413108-ab47-11e7-93ef-3a6ff65d223c.png)
