### ISSUE TITLE
Scoring Project Atlas off of SanSan in Titan does not yield a counter BUT clicking on it still yields the tutor dialog BUT clicking on any of the options yields nothing.

### ISSUE THREAD

**Issue by JoeyKL** [mtgred/netrunner#285]

**Comment by nealterrell** [comment]
Confirmed. Atlas' ability sets its agenda counters to -1 since it only has 2 advancement counters when scored. Titan then adds 1 to make 0 agenda counters.

Thanks for the report, I'll push a fix soon.

**Comment by JoeyKL** [comment]
That is such a classic example of computer logic I find it entertaining.

**Comment by nealterrell** [comment]
When in doubt, use `max` :).

**Comment by JoelCFC25** [comment]
This should have been fixed by #292. @JoeyKL, can you confirm that?

**Comment by JoeyKL** [comment]
It is indeed fixed! Thank you!
