### ISSUE TITLE
Run events trying to trigger counter surveillance

### ISSUE THREAD

**Issue by saetzero** [mtgred/netrunner#2851]
Played a game. A Stimhack-initiated run on RD with Counter Surveillance on the board let the runner Trigger the ability, pay the credits, access the extra cards, and did not trash Counter from the board.

A Retrieval Run-initiated on Archives also tried to do this, but was stopped becasue runner lacked credits in the amount of tags. But the log spat an error out.

This is a serious bug.

**Comment by JoelCFC25** [comment]
Wait, people are clicking Counter Surveillance in the midst of runs initiated through other means? While preventing it should be pretty straightforward, this is serious user error first and foremost. There are hundreds upon hundreds of card effects that can be triggered when it is not permitted (rules-wise) to do so.
