### ISSUE TITLE
Gang Sign/HQI in Leela accesses too many cards

### ISSUE THREAD

**Issue by Evilpyro25** [mtgred/netrunner#2855]
A gang sign fire with a single HQI installed accessed 4 cards where it should only have accessed 2. Installed as Leela vs a CI deck.

**Comment by nealterrell** [comment]
What was scored, and how? Sounds like agenda-scored was triggered twice.

**Comment by danhut** [comment]
Closing this as we got no input to help diagnose or fix it.

**Comment by Saintis** [comment]
Repeated here: #2957

Looking like HQI is not the issue.
