### ISSUE TITLE
Equivocation with Daily Business Show gives extra access

### ISSUE THREAD

**Issue by Smirnoffico** [mtgred/netrunner#2860]
Encountered this issue in a game today:
Corp has a rezed Daily Buisiness Show on the table;
Runner has installed Equivocation;
Runner makes a run on R&D and uses Equivocation to reveal top card;
After revealing the card runner forces corp to draw the card;
Runner Accesses another card (new top deck);
Daily Business Show fires (as it should);
Runner is still in the run and gets another access after Daily Business Show fires

**Comment by JoelCFC25** [comment]
I think the `force-draw` function in Equivocation's code is missing delayed completion. @nealterrell does that sound right?

**Comment by nealterrell** [comment]
Half right... it also needs to await `draw`, which thanks to DBS is a delayable operation, but unfortunately it's not hooked up that way at the moment. Will require some surgery.

**Comment by nealterrell** [comment]
I have this fixed and will push it soon.
