### ISSUE TITLE
Paige Piper causes strange (but harmless) messages

### ISSUE THREAD

**Issue by TheRealC** [mtgred/netrunner#2865]
Evening.

Lately, I've been seeing what appears to be a completely harmless bug associated with Paige Piper. When Paige is installed and the Runner plays a card & chooses to trash extra copies of it as per Paige's ability, messages of the following kind tend to appear:

- XXX trashes 11 copy of Maw.

There doesn't seem to be any actual error in the game state, although I might have just been missing something. Honestly it doesn't seem to do much else than give people an opportunity to shout "JUDGE!", but figured I'd report it anyways. I'd not be _opposed_ to just leaving it in as an easter egg ^^'

Oh, and the bug I'm talking about is obviously the lack of pluralization on "copy". Obviously!~

**Comment by nealterrell** [comment]
@jwarwick is way ahead of ya ;) #2863

**Comment by TheRealC** [comment]
Oh, I only looked in open issues. Cheers! RIP the funzies I guess ^^

**Comment by jwarwick** [comment]
I was poking around the server this evening to figure out how the update was going and happened to jump into a game and see 22 copies of a card get trashed.
