### ISSUE TITLE
Net damage fails to take effect after Titanium Ribs is turned facedown after Apocalypse

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#2871]
The Runner had Earthrise Hotel, Daily Casts, Vigil, Eater, and Titanium Ribs installed. The Runner played Apocalypse, turning these five cards facedown. The Corp was Jinteki: Personal Evolution. Any net damage taken by the Runner, including the /take-net command, did not cause a card to be lost from hand. No error message was raised. The problem persevered even after the facedown Titanium Ribs was trashed by the Runner.

**Comment by PesiTheWizard** [comment]
It's known that :leave-play clauses don't stop when the cards are turned face-down. Titanium Ribs uses such to stop working. If this happens again, try - if possible - to install Titanium Ribs again and trash it while it's face up.

**Comment by JoelCFC25** [comment]
This all worked at one point in time, when it changed is anyone's guess. The (incorrect) order of effects seems to currently be: 

1. Apocalypse does a `move` on all Runner cards to `[:rig :facedown]`
2. `move` assocs `:facedown true` with the card being moved *before* any attempt to `deactivate`
3. `deactivate` tries `trigger-leave-effect`...which has logic to not operate on cards that are facedown

*** headdesk ***

**Comment by NoahTheDuke** [comment]
Using git bisect, you should be able to narrow it down somewhat quickly.

**Comment by jwarwick** [comment]
Fixed by #3284
