### ISSUE TITLE
Dummy box and tapewrm

### ISSUE THREAD

**Issue by gammanet** [mtgred/netrunner#2872]
Dummy box should not prevent the trash of Tapewrm due to the phrasing of the cards. 

likely also exists for Clot,The Source, and those other viruses.

**Comment by Saintis** [comment]
This will not be an easy fix since we don't have a way of adding requirements / conditions to prevention effects. Will need some work to get this correct.

**Comment by Saintis** [comment]
Might be possible to add a specific prevent trigger for `:corp-trash` and put that on Dummy Box instead.
