### ISSUE TITLE
Chronos ID, I've Had worse and obokata

### ISSUE THREAD

**Issue by gammanet** [mtgred/netrunner#2877]
I dont know what happened, I just know I've had worse didn't trigger, and it thought i flatlined.

**Comment by gammanet** [comment]
![image](https://user-images.githubusercontent.com/7133323/31578010-66b27a58-b0de-11e7-9e53-4039d8a5afd7.png)

**Comment by ouroboros8** [comment]
I've also seen this: when you steal an Obokata vs. Chronos it deals 5 net damage.

**Comment by ouroboros8** [comment]
Specifically, if the runner chooses to pay net damage to steal obokata and the corp then fires chronos, the chronos net damage is dealt in addition to the 4 obokata damage instead of replacing one of them. The same issue occurs with Ben Musashi.

**Comment by duval84** [comment]
i didn't know there was this issue

i had the same experience just now with the same id and agenda, runner had 4 cards in hand and decide to steal obokata, the announcement was correct but somehow the the runner was flatlined

![bug jinteki ss1](https://user-images.githubusercontent.com/34717325/34215791-152855f6-e5d9-11e7-9c85-6f6dc69436f2.jpg)
