### ISSUE TITLE
Implementing host cards (in particular Street Peddler)

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#288]
If we could find a way of implementing these soon it would be appreciated. It's easy to work around Djinn, Dino etc., but everybody (okay, my last two games) wants to use Street Peddler now and I don't see a way to work around that.

**Comment by nealterrell** [comment]
These cards were checked in by mtgred today and will be published soon :).

**Comment by mtgred** [comment]
Cards that host face down card (ie. Street Peddler, Glen Station, Awakening Center) are not implemented yet. Other hosting should work for other cards.

**Comment by mtgred** [comment]
Street Peddler and Glenn Station have been implemented.

Awakening Center causes some UI issues and will be implemented later.
