### ISSUE TITLE
Enhanced Login Protocol and Runner able to make click-less runs 

### ISSUE THREAD

**Issue by AlecNelson** [mtgred/netrunner#2887]
Just played a game against New Angles Sol, where they played an Enhanced Login Protocol, after which I played Hacktivist Meeting. I noticed, after ELP had been trashed, I now did not automatically spend a click to make a run. Once ELP was played again, the run functionality worked normally. But every time ELP was gone, I had clickless runs again. RUNNERS OP!!! Just thought I should bring this to your attention.

<img width="189" alt="screen shot 2017-10-17 at 3 55 49 pm" src="https://user-images.githubusercontent.com/7873277/31686340-de9eaa1a-b353-11e7-9e66-d0e6990bfcd3.png">

**Comment by Saintis** [comment]
Seems to be some spelling issues in the "make a run" text as well. Will investigate.
