### ISSUE TITLE
Force Ultraviolet Clearance's install

### ISSUE THREAD

**Issue by TheRealC** [mtgred/netrunner#2889]
Evening.

Since the new UFAQ made a point out of updating freakin' NEXT Opal to go from mandatory to optional, but didn't mention Ultraviolet Clearance at all, I'm starting to lose hope that it'll ever get errata'd. As it stands, Ultraviolet Clearance's install is mandatory, which can be rather important as you might end up having to install an agenda from hand even when you don't want to do so, or otherwise put you in sticky situations. However, unless this was recently changed, this is not enforced by the client; you can decline to install even if you have installable cards in hand, and the Runner will not be able to know whether you were able and declined, or whether you legitimately weren't able (with the former being illegal and the second being legal).

So yeah, I guess for the sanity of the players, at the cost of the sanity of the coders, either make UVC's install mandatory, or - maybe (?) easier, have it print a message if the Corp refused to install with installable cards in hand and watch the shitstorm erupt.

...and now that I finally went ahead and asked for this after postponing it for months already, I'm 100% sure they'll update the UFAQ for Terminal Directive next week or something. Yay.

**Comment by Saintis** [comment]
Best approach is probably to add a `force-install` effect where the corp has to pick something to install. If nothing is available there should be a message to confirm this.

How does this interact with additional costs though? Can you choose to install a card in a Diwan targeted server and then decline to pay the cost, like Gagarin and accessing?

**Comment by JoelCFC25** [comment]
How about just adding an `if` "at least 1 agenda/asset/upgrade in hand" do the existing `continue-ability` with precisely 1 selection (we can enforce minimums now)--else just `effect-completed` and a message that they had no cards they could install.

**Comment by TheRealC** [comment]
> force-install

This sounds good.

> additional costs

This is a valid point. I admit I'm not 100% sure; my gut instinct is that you can only refuse to pay additional costs if there was no way to avoid said cost, e.g. you _could_ have installed your card in a different server and thus avoided the cost, so it's not allowed to refuse to pay it. But I mean, this is kind of a garbage-template card anyways, so I think just code it any way you want and look forward to it getting UFAQ'd at some random point in the future.

**Comment by LiteSpecter** [comment]
> additional costs

This (currently) seems like an almost moot point. The parenthetical "paying all costs" on UVC seems to answer the Diwan install cost case.

That said, if I may offer an extreme example, say HQ is protected by 11 ice and you have an installable ice in HQ. If you were on the minimum 10 credits post UVC, could you attempt and fail to install ice on HQ? Would you be forced to install on another server, trash HQ ice, or install another card?

**Comment by NoahTheDuke** [comment]
No longer mandatory.
