### ISSUE TITLE
Manhunt triggers on every run, and the trace doesn't pause the runner's action

### ISSUE THREAD

**Issue by aiannacc** [mtgred/netrunner#289]
1. Manhunt's trace should only trigger on the first successful run each turn.  Presently it triggers on every successful run.

2. The trace should occur when the run is successful, before the runner accesses cards.  Presently the corp gets a trace dialog, but the runner isn't made to wait for the trace (or notified of it).  As a result:

-- subtle timing interactions don't work right (e.g. with Dedicated Response Team)
-- the runner may spend money to trash or steal NAPD before the corp picks the trace strength
-- the runner may actually complete additional clicks before the corp notices and fires the trace

**Comment by JoelCFC25** [comment]
Fixed by #313.

**Comment by nealterrell** [comment]
I am working on a general fix that will address this.

**Comment by nealterrell** [comment]
Fix submitted in #1059.
