### ISSUE TITLE
Cleaners and Builder of nations.

### ISSUE THREAD

**Issue by tsuruki23** [mtgred/netrunner#2891]
The extra meat damage doesn't proc with Builder of nations once you've scored a "The Cleaners" agenda.

**Comment by jacobbillings** [comment]
BoN's effect has:
`damage state :runner eid :meat 1 {:card card}`
Changing that to `damage state side eid :meat 1 {:card card}`, which looks more like other meat damage cards, seems to fix the problem, however I'm a baby newbie at this so there may be a reason it was written with `:runner` that I'm not aware of.

**Comment by jacobbillings** [comment]
#2893 I went ahead and did the pull request for that change
