### ISSUE TITLE
Punitive Counterstrike/Hades Shard interaction

### ISSUE THREAD

**Issue by LittleBigStone** [mtgred/netrunner#2894]
Punitive Counterstrike takes into account agenda points from agendas stolen during Corporation's current turn (for example by pulling agendas out of archives with Hades Shard). This is against the rules (PC only cares for points stolen during the Runner's last turn.)

**Comment by jacobbillings** [comment]
I reproduced this as described. Also works this way with Hunter Seeker and Midseason Replacement.

**Comment by JoelCFC25** [comment]
A player's `:register` in state is not flushed until the start of their turn--so really it's collecting all the things that happen on your own turn plus the subsequent opponent turn.

**Comment by danhut** [comment]
Pushed a fix.  I took the approach of keeping `:register` to include the player turn plus the subsequent turn, and then `:register-last-turn` to be just the last turn.  I am not sure we have a use for `:register` but we don't have perfect test coverage so kept it.
