### ISSUE TITLE
Run Amok is not trashing

### ISSUE THREAD

**Issue by fingerzz96** [mtgred/netrunner#2899]
When run ends at the server with Run Amok, the rezzed ice that was rezzed during the run does not get trashed. The worst thing is that ICE does not allow to get trash from the server and hand. Had to do it with cmd.

**Comment by fingerzz96** [comment]
P.S Now is creating the issue that i can't put cards back from the servers

**Comment by JoelCFC25** [comment]
This card doesn't do automated ICE trashing. Hover over Run Amok, then read its implementation note: "Ice trash is manual"
