### ISSUE TITLE
No way to look at the other player's deck

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#29]
This means that cards like Indexing and Data Hound can not be manually worked-around.

**Comment by JoelCFC25** [comment]
Indexing should work. Data Hound very definitely does not. Bug!

**Comment by queueseven** [comment]
Indexing and Data Hound show the top X cards, and the one card that Data Hound trashes can be simply put into the Heap instead of the Stack. 

Data Hound is currently broken, a fix is here: #510 

This issue can be closed (or at least when the fix is merged)
