### ISSUE TITLE
Personal Workshop Creating duplicate copies of a card

### ISSUE THREAD

**Issue by silman** [mtgred/netrunner#290]
Steps to repeat

Play Personal workshop
Activate its ability to host a program while also having enough credits to install the program directly to the field
when the list of names of programs comes up, click the a program in your grip to install it to the field
now click the name of the card you just installed from the list personal workshop brings up
Now you will have two copies of the card, one installed and one hosted by personal workshop.

**Comment by chazak** [comment]
The same thing may happen with the Supplier, had this yesterday.

**Comment by JoelCFC25** [comment]
Both of these cards were changed to use the card targeting system in #863, so these problems should be impossible to produce now.
