### ISSUE TITLE
Standoff fired for random trash events

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#2901]
Very weird game and jnet behaviour. I tried to score a Standoff from hand, runner wanted to SMC into Clot and I didn't give them time, so we re-constructed it and then they stole the agenda.

After that, there were a few instances where the runner trashed something (a Whampoa on my board, a Trope from their board) and jnet fired the Standoff prompts about trashing a card, etc.

On top of that, at the end of the game, they fired a Same Old Thing to trigger an Indexing and instead it shuffled it into his stack!

Entire game log copied below:

originalme takes a mulligan.
runthenets takes a mulligan.
originalme started their turn 1 with 5 and 5 cards in HQ.
originalme spends  to install ICE protecting R&D.
originalme spends  to install a card in R&D.
originalme spends  and 2  to play Housekeeping.
originalme is ending their turn 1 with 3 and 3 cards in HQ.
runthenets started their turn 1 with 5 and 5 cards in their Grip.
runthenets spends  and 1  to play Peace in Our Time.
runthenets uses Peace in Our Time to gain 10 . The Corp gains 5 .
runthenets spends  to draw a card.
runthenets spends  and 1  to play Employee Strike.
Housekeeping is trashed.
runthenets uses Employee Strike to disable the Corp's identity.
runthenets spends  and 3  to install Daily Casts.
runthenets is ending their turn 1 with 10  and 3 cards in their Grip.
originalme started their turn 2 with 8 and 3 cards in HQ.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme spends  and 8  to play IPO.
originalme uses IPO to gain 13 .
originalme is ending their turn 2 with 13  and 5 cards in HQ.
runthenets started their turn 2 with 10  and 3 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  and 1  to play Peace in Our Time.
runthenets uses Peace in Our Time to gain 10 . The Corp gains 5 .
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets is ending their turn 2 with 21  and 5 cards in their Grip.
originalme started their turn 3 with 18 and 5 cards in HQ.
originalme spends  to draw a card.
originalme spends  and 2  to play Housekeeping.
Employee Strike is trashed.
originalme spends  and 8  to play IPO.
originalme uses IPO to gain 13 .
originalme is ending their turn 3 with 21  and 5 cards in HQ.
runthenets started their turn 3 with 21  and 5 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  to draw a card.
runthenets spends  and 3  to install Net Mercur.
originalme uses Housekeeping to force the Runner to trash Same Old Thing from their Grip.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hunter Seeker from HQ.
runthenets spends  to install Sacrificial Construct.
runthenets is ending their turn 3 with 20  and 3 cards in their Grip.
originalme started their turn 4 with 21 and 5 cards in HQ.
originalme spends  to draw a card.
originalme spends  to install a card in Server 1 (new remote).
originalme spends  to install a card in Server 1.
originalme spends 3  to rez Whampoa Reclamation.
originalme uses Whampoa Reclamation to trash 1 card from HQ and add a card from Archives to the bottom of R&D.
originalme is ending their turn 4 with 18  and 4 cards in HQ.
runthenets started their turn 4 with 20  and 3 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets spends  and 1  to play Employee Strike.
Housekeeping is trashed.
runthenets uses Employee Strike to disable the Corp's identity.
runthenets spends  to install Self-modifying Code.
runthenets is ending their turn 4 with 21  and 3 cards in their Grip.
originalme started their turn 5 with 18 and 4 cards in HQ.
originalme spends  to draw a card.
originalme spends  to install a card in Server 2 (new remote).
originalme spends  to install a card in Server 3 (new remote).
originalme uses Whampoa Reclamation to trash 1 card from HQ and add Housekeeping from Archives to the bottom of R&D.
originalme is ending their turn 5 with 18  and 3 cards in HQ.
runthenets started their turn 5 with 21  and 3 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  and 1  to play Peace in Our Time.
runthenets uses Peace in Our Time to gain 10 . The Corp gains 5 .
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets is ending their turn 5 with 32  and 5 cards in their Grip.
originalme started their turn 6 with 23 and 3 cards in HQ.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
Employee Strike is trashed.
originalme scores False Lead and gains 1 agenda point.
originalme is ending their turn 6 with 20  and 4 cards in HQ.
runthenets started their turn 6 with 32  and 5 cards in their Grip.
runthenets spends  to install Misdirection.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hunter Seeker from HQ.
serpentskin joined the game as a spectator.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hunter Seeker from HQ.
runthenets spends  to gain 1 .
runthenets is ending their turn 6 with 33  and 4 cards in their Grip.
originalme started their turn 7 with 20 and 4 cards in HQ.
originalme spends  to install a card in Server 4 (new remote).
originalme spends  and 1  to advance a card in Server 4.
originalme spends  and 1  to advance a card in Server 4.
originalme scores Standoff and gains 0 agenda points.
runthenets spends 2  to use Self-modifying Code to install Clot.
runthenets spends 2  to install Clot.

originalme
shit, sorry.
!originalme uses a command: /close-prompt
originalme moves a card to HQ.
!runthenets uses a command: /close-prompt
originalme sets click to 1 (+1).
originalme spends  to install a card in Server 5 (new remote).
originalme sets credit to 19 (+1).
originalme sets credit to 20 (+1).
originalme sets click to 1 (+1).
originalme sets click to 2 (+1).
originalme spends  and 1  to advance a card in Server 5.
originalme spends  and 1  to advance a card in Server 5.
originalme is ending their turn 7 with 18  and 4 cards in HQ.
runthenets started their turn 7 with 29  and 4 cards in their Grip.
runthenets spends  to make a run on Server 5.

originalme
you should get es back

originalme
before you steal that
runthenets moves Employee Strike from their Heap to Grip.
originalme has no further action.
runthenets jacks out.
runthenets sets click to 4 (+1).
runthenets sets click to 5 (+1).
runthenets spends  and 1  to play Employee Strike.
runthenets uses Employee Strike to disable the Corp's identity.
runthenets sets credit to 29 (+1).
runthenets spends  to make a run on Server 5.
originalme has no further action.
runthenets accesses Standoff from Server 5.
runthenets steals Standoff and gains 0 agenda points.
runthenets spends  to draw a card.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hunter Seeker from HQ.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Show of Force from HQ.
runthenets steals Show of Force and gains 2 agenda points.
runthenets is ending their turn 7 with 29  and 5 cards in their Grip.
originalme started their turn 8 with 18 and 3 cards in HQ.
originalme spends  to gain 1 .
originalme spends  and 2  to play Hunter Seeker.
originalme uses Hunter Seeker to trash Misdirection.
runthenets has the option to prevent trash effects.
runthenets prevents the trashing of Misdirection.
originalme is ending their turn 8 with 17  and 3 cards in HQ.
runthenets started their turn 8 with 29  and 5 cards in their Grip.
runthenets spends  to make a run on Server 1.
originalme has no further action.
runthenets trashes a card in Server 1 due to Standoff.

originalme
? what just happened

runthenets
Right? I'm quite confused
!originalme uses a command: /close-prompt

runthenets
what was the upgrade in the server?
!runthenets uses a command: /close-prompt

originalme
prisec

runthenets
are you able to move it back in?
originalme moves a card from their Archives to HQ.
originalme sets click to 1 (+1).
originalme spends  to install a card in Server 1.
runthenets accesses Prisec from Server 1.
originalme spends 2  to use Prisec to do 1 meat damage and give the Runner 1 tag.
runthenets trashes Sure Gamble due to damage.
runthenets pays 3  to trash Prisec from Server 1.
runthenets accesses Whampoa Reclamation from Server 1.
runthenets pays 3  to trash Whampoa Reclamation from Server 1.
runthenets spends  and 2  to remove 1 tag .
runthenets spends  to draw a card.
runthenets spends  to install Sacrificial Construct.
runthenets is ending their turn 8 with 21  and 4 cards in their Grip.
originalme started their turn 9 with 15 and 3 cards in HQ.
runthenets has the option to prevent trash effects.
originalme spends  to purge all virus counters.
runthenets will not prevent the trashing of Clot.
originalme is ending their turn 9 with 15  and 4 cards in HQ.
runthenets started their turn 9 with 21  and 4 cards in their Grip.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hard-Hitting News from HQ.
runthenets spends  to draw a card.
runthenets spends  to make a run on HQ.
originalme has no further action.
runthenets accesses Hard-Hitting News from HQ.
runthenets spends  to gain 1 .
runthenets is ending their turn 9 with 22  and 5 cards in their Grip.
originalme started their turn 10 with 15  and 4 cards in HQ.
originalme spends  to draw a card.
originalme spends  to install ICE protecting HQ.
originalme spends  to install ICE protecting Archives.
originalme is ending their turn 10 with 15  and 4 cards in HQ.
runthenets started their turn 10 with 22  and 5 cards in their Grip.
runthenets spends  to draw a card.
runthenets spends  to play Diesel.
runthenets uses Diesel to draw 3 cards.
runthenets spends  and 1  to install Trope.
runthenets spends  and 1  to install Astrolabe.
runthenets discards Paperclip from their Grip.
runthenets is ending their turn 10 with 20  and 5 cards in their Grip.
originalme started their turn 11 with 15  and 4 cards in HQ.
originalme spends  to draw a card.
runthenets uses Astrolabe to draw 1 card.
originalme spends  to install a card in Server 6 (new remote).
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme is ending their turn 11 with 19  and 4 cards in HQ.
runthenets started their turn 11 with 20  and 6 cards in their Grip.
runthenets spends  to make a run on Server 6.
originalme spends 3  to rez Whampoa Reclamation.

originalme
/close-promt
!originalme uses a command: /close-prompt
originalme has no further action.
!runthenets uses a command: /close-prompt
originalme wants to act before the run is successful.
!originalme uses a command: /close-prompt

originalme
hmm

originalme
can you access?
runthenets accesses Whampoa Reclamation from Server 6.
runthenets pays 3  to trash Whampoa Reclamation from Server 6.

runthenets
good?

originalme
yeah
runthenets spends  to install Same Old Thing.
runthenets spends  to draw a card.
runthenets spends  and 5  to play Sure Gamble.
runthenets uses Sure Gamble to gain 9 .
runthenets is ending their turn 11 with 21  and 5 cards in their Grip.
originalme started their turn 12 with 16  and 4 cards in HQ.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme discards a card from their HQ.
originalme discards a card from their HQ.
originalme discards a card from their HQ.
originalme is ending their turn 12 with 16  and 5 cards in HQ.
runthenets started their turn 12 with 21  and 5 cards in their Grip.
runthenets spends  to make a run on HQ.
originalme spends 1  to rez Ice Wall.
runthenets spends 4  to install Paperclip.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
originalme has no further action.
runthenets uses Paperclip to spend 1 , increase strength by 1, and break 1 Barrier subroutine.
runthenets continues the run.
originalme has no further action.
runthenets accesses Hard-Hitting News from HQ.
runthenets spends  to draw a card.

runthenets
pass window

originalme
no action
runthenets spends  to make a run on HQ.
runthenets uses Net Mercur to gain 1 .
runthenets places 1  on Net Mercur.
originalme has no further action.
runthenets uses Paperclip to spend 1 , increase strength by 1, and break 1 Barrier subroutine.
runthenets continues the run.
originalme has no further action.
runthenets accesses Hard-Hitting News from HQ.
runthenets spends  to gain 1 .
runthenets discards Indexing from their Grip.
runthenets is ending their turn 12 with 18  and 5 cards in their Grip.
originalme started their turn 13 with 15  and 5 cards in HQ.
originalme spends  to draw a card.
originalme spends  and 2  to play Best Defense.
originalme trashes Sacrificial Construct due to Standoff.

originalme
!!!
!originalme uses a command: /close-prompt
!runthenets uses a command: /close-prompt
originalme spends  and 8  to play IPO.
originalme uses IPO to gain 13 .
originalme is ending their turn 13 with 18  and 5 cards in HQ.
runthenets started their turn 13 with 18  and 5 cards in their Grip.
runthenets spends  to play Indexing.
originalme spends 2  to rez IP Block.
originalme spends 1  to rez K. P. Lynn.
originalme has no further action.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
runthenets uses Paperclip to spend 3 , increase strength by 3, and break 3 Barrier subroutines.
originalme uses K. P. Lynn. Runner chooses to take 1 tag.
runthenets continues the run.
originalme has no further action.
runthenets accesses K. P. Lynn from the root of R&D.
runthenets pays 3  to trash K. P. Lynn from the root of R&D.
originalme spends 2  to rez Zealous Judge.
runthenets accesses an unseen card from R&D.
runthenets steals Show of Force and gains 2 agenda points.

runthenets
pass window

originalme
no action
runthenets spends  to use Misdirection to spend 1  and remove 1 tags.
runthenets spends  to make a run on Server 3.
originalme has no further action.
runthenets accesses Zealous Judge from Server 3.
runthenets pays 2  to trash Zealous Judge from Server 3.
runthenets is ending their turn 13 with 10  and 4 cards in their Grip.
originalme started their turn 14 with 13  and 5 cards in HQ.

originalme
thinking

runthenets
np
originalme spends  to draw a card.
originalme spends  and 1  to install ICE protecting R&D.
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme is ending their turn 14 with 16  and 5 cards in HQ.
runthenets started their turn 14 with 10  and 4 cards in their Grip.
runthenets spends  to play Diesel.
runthenets uses Diesel to draw 3 cards.
runthenets spends  and 5  to play Sure Gamble.
runthenets uses Sure Gamble to gain 9 .
runthenets spends  to make a run on HQ.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
originalme has no further action.
runthenets uses Paperclip to spend 1 , increase strength by 1, and break 1 Barrier subroutine.
runthenets continues the run.
originalme has no further action.
runthenets accesses Wraparound from HQ.
runthenets spends  and 1  to install Refractor.
runthenets is ending their turn 14 with 13  and 4 cards in their Grip.
Vermithrax joined the game as a spectator.
originalme started their turn 15 with 16  and 5 cards in HQ.
runthenets uses Astrolabe to draw 1 card.
originalme spends  to install ICE protecting Server 7 (new remote).
originalme spends  to gain 1 .
originalme spends  to install a card in Server 7.
originalme is ending their turn 15 with 17  and 4 cards in HQ.
runthenets started their turn 15 with 13  and 5 cards in their Grip.
runthenets spends  to play Indexing.
originalme spends 2  to rez Authenticator.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
runthenets spends 1  to increase the strength of Refractor to 5.
runthenets spends 1  to use Refractor to break 1 Code Gate subroutine.
originalme has no further action.
runthenets indicates to fire the "Gain 2 " subroutine on Authenticator.
runthenets continues the run.
originalme uses Authenticator to gain 2 .
originalme has no further action.
runthenets uses Paperclip to spend 3 , increase strength by 3, and break 3 Barrier subroutines.
runthenets continues the run.
originalme has no further action.
runthenets uses Indexing to rearrange the top 5 cards of R&D.

originalme
gg?
runthenets spends  to play Mad Dash.
runthenets uses Net Mercur to gain 1 .

runthenets
nope
runthenets uses Net Mercur to draw 1 card.
runthenets spends 1  to increase the strength of Refractor to 5.
runthenets spends 1  to use Refractor to break 1 Code Gate subroutine.
runthenets indicates to fire the "Gain 2 " subroutine on Authenticator.
originalme uses Authenticator to gain 2 .
originalme has no further action.
runthenets continues the run.
runthenets uses Net Mercur to gain 1 .

originalme
did you just mad dash a standoff?
runthenets uses Net Mercur to gain 1 .
originalme has no further action.
runthenets uses Paperclip to spend 3 , increase strength by 3, and break 3 Barrier subroutines.
runthenets continues the run.
originalme has no further action.
runthenets accesses an unseen card from R&D.
runthenets steals False Lead and gains 1 agenda point.
runthenets adds Mad Dash to their score area as an agenda worth 1 agenda point.

runthenets
pass window

originalme
no action
runthenets spends  to draw a card.
runthenets spends  to gain 1 .
runthenets is ending their turn 15 with 8  and 5 cards in their Grip.
originalme started their turn 16 with 19  and 4 cards in HQ.
originalme spends  and 1  to advance a card in Server 7.
originalme spends  and 1  to advance a card in Server 7.
originalme spends  and 1  to advance a card in Server 7.

originalme
action?

runthenets
you're good
Employee Strike is trashed.
originalme scores Project Atlas and gains 2 agenda points.
originalme is ending their turn 16 with 16  and 5 cards in HQ.
runthenets started their turn 16 with 8  and 5 cards in their Grip.
runthenets spends  to draw a card.
runthenets spends  to draw a card.
runthenets spends  and 3  to install Daily Casts.
runthenets spends  to install Sacrificial Construct.
runthenets is ending their turn 16 with 5  and 5 cards in their Grip.
originalme started their turn 17 with 16  and 5 cards in HQ.
runthenets uses Astrolabe to draw 1 card.
originalme spends  to install a card in Server 8 (new remote).
originalme spends  and 1  to advance a card in Server 8.
originalme spends  and 1  to advance a card in Server 8.

originalme
action?

runthenets
pass
originalme scores Standoff and gains 0 agenda points.
runthenets declines to trash a card due to Standoff.
originalme draws a card and gains 5 from Standoff.
originalme discards a card from their HQ.
originalme is ending their turn 17 with 19  and 5 cards in HQ.
runthenets started their turn 17 with 5  and 6 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  to draw a card.
!runthenets uses a command: /close-prompt
runthenets moves Trope to Grip.
runthenets sets click to 3 (+1).
runthenets sets credit to 8 (+1).
runthenets spends  and 1  to install Trope.

runthenets
/set-counter

runthenets
nope... what's that command? haha

runthenets
(Trope prompt was fucked)

originalme
lemme look

originalme
it's counter n, with a / in front
!runthenets uses a command: /counter 7
runthenets trashes Trope due to Standoff.

originalme
lol

originalme
fucking standoff
!originalme uses a command: /close-prompt
!runthenets uses a command: /close-prompt
runthenets sets click to 3 (+1).

originalme
just move the cards you want and shuffle r&d

originalme
stack
runthenets moves Clot from their Heap to the top of Stack.
runthenets moves Sacrificial Construct from their Heap to the top of Stack.
runthenets moves Self-modifying Code from their Heap to the top of Stack.
runthenets moves Sacrificial Construct from their Heap to the top of Stack.
runthenets moves Indexing from their Heap to the top of Stack.

originalme
aw. jeez. you don't need any of those cards.
runthenets moves Sure Gamble from their Heap to the top of Stack.
runthenets moves Employee Strike from their Heap to the top of Stack.

runthenets
is it just / shuffle?

originalme
click on it and choose shuffle
runthenets shuffles their deck.

runthenets
Trope is also RFG, but I don't think that should be relevant vs. heap

originalme
my apologies for playing that stupid card.

originalme
not for this game, no.

runthenets
haha not your fault
runthenets sets click to 2 (-1).

runthenets
Okay haha
runthenets spends  to install Self-modifying Code.
runthenets spends  to gain 1 .
runthenets discards Astrolabe from their Grip.
runthenets is ending their turn 17 with 8  and 5 cards in their Grip.
originalme started their turn 18 with 19  and 5 cards in HQ.
originalme spends  and 1  to install ICE protecting Server 7.
originalme spends  to install a card in Server 7.
originalme spends  to gain 1 .
originalme is ending their turn 18 with 19  and 4 cards in HQ.
runthenets started their turn 18 with 8  and 5 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets spends  to play Stimhack.
originalme spends 4  to rez Data Raven.
runthenets chooses to take 1 tag on encountering Data Raven.
runthenets spends 2  to use Self-modifying Code to install Dagger.
runthenets spends 3  to install Dagger.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
runthenets spends 1  to increase the strength of Dagger to 5.
runthenets spends 1  to use Dagger to break 1 Sentry subroutine.
originalme has no further action.
runthenets continues the run.
originalme spends 4  and 1 Agenda to rez Archer.
runthenets uses Net Mercur to gain 1 .
runthenets uses Net Mercur to gain 1 .
runthenets spends 2  to increase the strength of Dagger to 10.
runthenets spends 1  to use Dagger to break 1 Sentry subroutine.
runthenets spends 1  to use Dagger to break 1 Sentry subroutine.
!originalme uses a command: /close-prompt
runthenets spends 1  to use Dagger to break 1 Sentry subroutine.
originalme has no further action.
runthenets spends 1  to use Dagger to break 1 Sentry subroutine.
originalme trashes a card.
runthenets continues the run.
originalme has no further action.
runthenets accesses Prisec from Server 7.
originalme spends 2  to use Prisec to do 1 meat damage and give the Runner 1 tag.
runthenets trashes Cloak due to damage.
runthenets pays 3  to trash Prisec from Server 7.
runthenets uses Stimhack to take 1 brain damage.
runthenets trashes Employee Strike due to damage.

runthenets
pass window

originalme
no action
runthenets spends  to use Misdirection to spend 2  and remove 2 tags.
runthenets spends  to draw a card.
runthenets is ending their turn 18 with 4  and 3 cards in their Grip.
originalme started their turn 19 with 9 and 4 cards in HQ.

originalme
thinking
originalme spends  to gain 1 .
originalme spends  to gain 1 .
originalme spends  and 3  to play Hard-Hitting News.
originalme uses Hard-Hitting News to initiate a trace with strength 5 (4 + 1 ) (Give the Runner 4 tags).
runthenets spends 0  to increase link strength to 0.
originalme uses Hard-Hitting News to give the Runner 4 tags.
originalme is ending their turn 19 with 7  and 4 cards in HQ.
runthenets started their turn 19 with 4  and 3 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
originalme uses False Lead to force the Runner to lose .
originalme forfeits False Lead.
runthenets spends  to use Misdirection to spend 4  and remove 4 tags.
runthenets is ending their turn 19 with 2  and 3 cards in their Grip.
originalme started their turn 20 with 7 and 4 cards in HQ.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme discards a card from their HQ.
originalme is ending their turn 20 with 11  and 5 cards in HQ.
runthenets started their turn 20 with 2  and 3 cards in their Grip.
runthenets uses Daily Casts to gain 2 .
runthenets uses Same Old Thing to shuffle Indexing into their Stack.

runthenets
That... was not suppose to be the result of that haha

originalme
huh?

originalme
what the hell is going on?
runthenets moves Indexing from their Heap to Grip.
runthenets sets click to 3 (-1).
runthenets spends  to play Indexing.
originalme has no further action.

runthenets
(we'll deal with my stack if I don't win here haha)
runthenets takes 1 tag on encountering Authenticator to Bypass it.
runthenets continues the run.
runthenets uses Ele "Smoke" Scovak: Cynosure of the Net to take 1 .
runthenets places 1  on Net Mercur.
originalme has no further action.
runthenets uses Paperclip to spend 3 , increase strength by 3, and break 3 Barrier subroutines.
runthenets continues the run.
originalme has no further action.
runthenets uses Indexing to rearrange the top 5 cards of R&D.
runthenets spends  to make a run on R&D.
originalme has no further action.
runthenets takes 1 tag on encountering Authenticator to Bypass it.
runthenets continues the run.
runthenets uses Net Mercur to gain 1 .
originalme has no further action.
runthenets places 1  on Net Mercur.
runthenets uses Net Mercur to gain 1 .
runthenets uses Paperclip to spend 3 , increase strength by 3, and break 3 Barrier subroutines.
runthenets continues the run.
originalme has no further action.
runthenets accesses an unseen card from R&D.
runthenets steals Project Atlas and gains 2 agenda points.
runthenets wins the game.

runthenets
gg

originalme
gg

runthenets
Was... interesting to say the least

originalme
thanks for the game

originalme
I'll go file some jnet bugs. :)

runthenets
haha thanks
runthenets left the game.

**Comment by Saintis** [comment]
My guess is that the `/close-prompt` on Standoff didn't remove the trigger itself properly. This is my guess on why the bug happened.

For future reference a workaround might be if the corp declines to trash a card instead of using `/close-prompt`.
