### ISSUE TITLE
Inside Job goes to heap, doesn't trigger

### ISSUE THREAD

**Issue by VoxDracones** [mtgred/netrunner#2905]
Twice now in games, Inside job has not triggered the run when I've played it. The costs are charged and it goes to the heap, but it hangs up instead of triggering the run. I could not manually start a run to simulate the effect, and my opponent could not reveal the card on the server I would have accessed (we played out the run). I attempted to refresh the browser and rejoin the game, and although it went back the proper game state, again I couldn't play Inside Job, and we had to give up the game.

I've noticed a similar problem with Deuces Wild at times, when selecting to make a run after exposing ice. Is it possible there's an issue with cards that allow you to make a non-click run?

**Comment by danhut** [comment]
Can you get a game-log and screen shot next time please?  We have zero information to work on so cannot help as yet with this.  It *could* happen - we just need help to find the trigger.
