### ISSUE TITLE
Cannot edit decks or join games when logged in

### ISSUE THREAD

**Issue by ACG8** [mtgred/netrunner#2908]
I joined Jinteki.net a few weeks ago and it worked fine. Now, however, when I go to the Deck Builder page it just displays "loading deck collection" forever and never displays the decks that I previously made, and if I click "New corp deck" it will sometimes do nothing and sometimes take me to the deck building page and does not let me save any decks I create there (sometimes it does not even let me create any decks.

Also, when I go to the play lobby none of the games show up and it is impossible for me to join any (there is simply nothing in the list). However, the Casual/Competitive indicators show that some games are happening.

Strangely, if I log out of my account, the guest decklists display just fine, as do the games in the lobby.

I have tried loading the site with both google chrome and microsoft edge, and I get the same problems. I have also tried disabling all of my chrome extensions, but the same problem still happens.

**Comment by ACG8** [comment]
I created a new account, and it solved the problem. So something about my old account caused the bug.

**Comment by jwarwick** [comment]
@ACG8 can you share your old jnet username? I'd like to look at your deck collection on the production server and see if I can figure out what is causing it to hang.

**Comment by ACG8** [comment]
It is ACG, but the problem no longer seems to be occurring.

**Comment by jwarwick** [comment]
Thanks for getting back to me. We found a bug where decks that did not save correctly would keep all decks from loading. The bug is fixed (#3165) and the production server has been updated to remove any decks that were causing issues.
