### ISSUE TITLE
Armand "Geist" Walker's Ability Yields Extra Text

### ISSUE THREAD

**Issue by scifantasy** [mtgred/netrunner#291]
Armand "Geist" Walker's ability seems to suggest there's a missing close-brace or something. When the Runner used Spike's trash ability and clicked yes to the prompt (which, by the way, is also wrong, it's a mandatory action), the text box showed:

"<Runner> uses Armand "Geist" Walker to draw a card({:faction "Criminal", :factioncost 2, :setname "The Valley", :agendapoints nil, :influencelimit nil, :number 4, :zone (:rig :program), :advancementcost nil, :cid 22484, :type "Program", :abilities ["Break up to 3 barrier subroutines"], :title "Spike", :counter 0, :uniqueness false, :host nil, :strength 0, :baselink nil, :code "08004", :side "Runner", :current-strength nil, :cost 1, :hosted nil, :installed true, :advance-counter 0, :memoryunits 1, :trash nil, :subtype "Icebreaker - Fracter - Cloud", :minimumdecksize nil, :text "If you have at least 2, the memory cost of Spike is 0, even if it is not installed.\r\nSpike has +1 strength for each installed icebreaker.\r\n: Break up to 3 barrier subroutines."} :ability-cost)."

**Comment by JoelCFC25** [comment]
Tested against a Geist runner just now and it all seems to work perfectly (fixed by #292). Probably safe to close this, @scifantasy. 

Also, Spike, Shiv, and Crowbar have been patched to stop that prompt from coming up.

**Comment by scifantasy** [comment]
Those three? What about other trash abilities like Clone Chip--did they not have the problem? (I'm not clear on the nature of the issue, I just reported it this time.)

**Comment by JoelCFC25** [comment]
Most everything else was in #283--cards with trash abilities got an additional `{:cause :trash-ability}' 

If there are any that slipped through the cracks let @nealterrell know or just patch them up. :)

**Comment by scifantasy** [comment]
Ah, gotcha.

**Comment by mtgred** [comment]
Neal fixed the issue so it should work fine now.
