### ISSUE TITLE
Gauntlet + Sneakdoor Beta

### ISSUE THREAD

**Issue by Pandageddon** [mtgred/netrunner#2910]
Combo allows additional accesses from HQ for each piece of ice on archives that a broken by the runner. Is this intended?

**Comment by JoelCFC25** [comment]
This card needs an implementation note. It basically uses the honor system--presents the Runner with a "How many ICE on HQ did you break?" with the number of ICE protecting HQ as the upper bound. Currently it is incumbent on the Runner to know that they should choose 0 here, but the system does not prevent them from picking a larger number.
