### ISSUE TITLE
Leaving game before it starts counts as incomplete game

### ISSUE THREAD

**Issue by carlsondc** [mtgred/netrunner#2917]
To reproduce:
1. Create a game
2. Hit "leave game" before the second player joins

Expected behavior: no change to "started," "completed," or "not completed" counts on stats page
Actual behavior: "not completed" increments

I hit "clear stats" after I did this, and after this I see no change in any counts when I attempt to reproduce the issue (all stay at 0). So maybe this only happens when you have some completed or started games in your stats already.

**Comment by danhut** [comment]
Should be fixed once #2924 is live

**Comment by danhut** [comment]
Should be fine now - let us know any more issues.
