### ISSUE TITLE
Domestic Sleepers/Mark Yale - can of worms.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#2920]
Domestic Sleepers that has been "activated" and then eaten by Mark Yale is still worth 1 point.

_(Fixed this manually. After that; Exchange of Information'ing the Domestic Sleepers gave the corp a point as if it was still active, which it basically was, so had to fix it back.
The game became weird after that. 3 points and scoring a tagged Market Research triggered an agenda-win with 6 points despite Market Research not having an agenda counter on it. After manually adding an agenda counter to it, it was somehow still not a valid target for Mark Yale. (Corp was The Shadow))_

Note to whomever decides to fix this:Keep Genetic Resequencing in mind.

**Comment by JoelCFC25** [comment]
Ugh. Domestic Sleepers will probably need a watch state to know when it goes down to 0 agenda counters. I don't think there's any system event for that.

**Comment by presheaf** [comment]
I don't know if this is still an issue, but we could avoid a watch state by using the `:counter-added` event, which may have been added sometime after the preceding comment.

**Comment by NoahTheDuke** [comment]
Closed by #4852
