### ISSUE TITLE
Maw trigger on Shi.Kyu access

### ISSUE THREAD

**Issue by SieglHertzberg** [mtgred/netrunner#2923]
Accessing a Shi.Kyu in a remote (not sure what happens on jnet on other servers) and adding it to the score area, with a Maw installed doesn't trigger Maw.

Since adding it to score area is different from stealing and you certainly don't trash it, Maw should trigger.
I think the issue might be that the card is no longer there when the access is over, but that shouldn't stop Maw from resolving according to UFAQ: 

   "If the first card the Runner accesses not in Archives that they do not steal or trash is an agenda that 
   they host on Film Critic, does Maw trigger?

   Yes. The Runner accessed a card and did not steal or trash it. Maw's trigger condition can only ever be 
   met after an access ends, so it isn't a condition met by entering the "accessing a card" timing structure. 
   Ending the access prematurely with Film Critic won't invalidate its trigger condition."

**Comment by roitk** [comment]
Does this also happen with News Team?

**Comment by SieglHertzberg** [comment]
Don't know, I just encountered this interaction and haven't tried any other scenarios.
