### ISSUE TITLE
Edward Kim and (non)trashing triggers

### ISSUE THREAD

**Issue by mykonian** [mtgred/netrunner#2927]
First and most basic issue, Aumakua doesn't see that kim trashes an operation, and adds a virus counter. 

Second, Maw does see that an operation gets trashed, unless it's an operation with a trash cost. In that case, kim triggers automatically, then a menu pops up if you want to pay the trash cost as well (which naturally you decline) at which point Maw figures you haven't trashed it and trashes a card from the corps hand.

**Comment by danhut** [comment]
Another issue here is that once Ed Kim has auto-trashed the operation with a trash cost - you should not really get the Yes/No prompt to pay to trash it - as it was already trashed
