### ISSUE TITLE
CTM Salsette Slums interaction

### ISSUE THREAD

**Issue by MasterAir** [mtgred/netrunner#2928]
A runner ran a remote with an Asset and Mumbad Virtual Tour installed. They removed the asset from game with Salsette Slums, then trashed the MVT automatically. At this point I was prompted for the CTM trace, I believe that CTM does not meet its trigger following this sequence.

Obviously a very minor issue.

**Comment by danhut** [comment]
Under FAQ 4.1 any trash after the first remove-from-game done via Salsette should trigger CTM I think?  Noting that 4.1 logic is not live for Salsette yet so this WAS a bug prior to 4.1 if you saw it. Let me know what you think.

**Comment by nealterrell** [comment]
@danhut is correct, this is now the correct interaction.

**Comment by danhut** [comment]
Closing this based on the discussion.
