### ISSUE TITLE
Improve Client Lock

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#2930]
1. Lock is removed by any incoming command from the server.  Explore if we can remove this only in response to our own action - this should remove "too fast" clicking incidents which I suspect are the result of another action clearing the lock
2. Confirm typing indicator is a system event and as such will not set or clear lock
3. Explore making own "say" commands not set a lock as they don't change game state

**Comment by Saintis** [comment]
I think these are good ideas!

I am fairly convinced the lock being removed by opponent action / system action is cause of "too fast" clicking incidents.
