### ISSUE TITLE
Shard(s) install windows not suppressing access

### ISSUE THREAD

**Issue by wombat929** [mtgred/netrunner#2934]
Hello,

When the runner has any of the shards in hand, there is no window between "successful run" and "access" in which they can install the shards. The system seems to allow them to install BEFORE clicking successful run without paying the install cost or a credit, but it doesn't then stop the access.

I've tested this with all three shards (Utopia Shard, Eden Shard, and Hades Shard)

Thanks,
Brendan

**Comment by danhut** [comment]
Fixed.  And added a note to explain when the install window is.  Will be live on next code deploy.

**Comment by wombat929** [comment]
Thanks so much! Y'all are the best.
