### ISSUE TITLE
close-prompt after Special Report still executes its effect when playing another operation

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#2940]
This happened during a game:

Opponent spends and 1 to play Special Report.
Opponent uses a command: /close-prompt
Opponent sets click to 3 (+1).
Opponent sets credit to 19 (+1).
Opponent moves Special Report from their Archives to HQ.
Opponent spends 3 to rez Cyberdex Virus Suite.
Opponent spends to play Shipment from Kaguya.
Opponent uses Shipment from Kaguya to shuffle 12 cards in HQ into R&D and draw 12 cards.

This did shuffle back his whole HQ into R&D.

**Comment by danhut** [comment]
This is as per design - /close-prompt is not an undo button - so once the card is played the effect will occur.  We do not have an undo button and it would be very difficult to implement for reasons I won't go into here.

Sorry!
