### ISSUE TITLE
Run restrictions (Peace in our Time) don't prevent run events with specific targets

### ISSUE THREAD

**Issue by mcyalcin** [mtgred/netrunner#2941]
Hit the issue when someone could use Indexing after playing Peace in our Time. I don't know if there are other conditions that can cause the issue but ":req (req (not (:<hq/rd/archives> (get-in runner [:register :cannot-run-on-server]))))" seems a simple general purpose fix to the issue for all affected cards but Demolition Run. If you give me the go-ahead, I can open a pull request for it.

Affected cards:
Account Siphon
CBI Raid
Code Siphon
Data Breach
Deep Data Mining
Demolition Run
Escher
Fear The Masses
Feint
Immolation Script
Indexing
Information Sifting
Legwork
Möbius
Political Graffiti
Retrieval Run
Rip Deal
Showing Off
The Maker's Eye
Vamp
Wanton Destruction

**Comment by nealterrell** [comment]
Go for it :+1:
