### ISSUE TITLE
Information Sifting + The Turning Wheel

### ISSUE THREAD

**Issue by MGillett** [mtgred/netrunner#2945]
If you make a successful Information Sifting run with The Turning Wheel out, The Turning Wheel gets a power counter when the run is successful - i.e. before the accesses from Information Sifting happen.
Example:

tf34 spends  to use Same Old Thing to play Information Sifting.
tf34 spends 1  to play Information Sifting.
...
tf34 continues the run.
Crunchums has no further action.
tf34 places a power counter on The Turning Wheel.
tf34 accesses Architect from HQ.
tf34 accesses Scarcity of Resources from HQ.
tf34 accesses Vanilla from HQ.
tf34 accesses Bryan Stinson from HQ.
tf34 accesses Biotic Labor from HQ.
tf34 accesses Cyberdex Virus Suite from HQ.
...

**Comment by danhut** [comment]
Does this happen if an Agenda is stolen during sifting?

**Comment by MGillett** [comment]
Yes.
