### ISSUE TITLE
Salsette Slums and Mumbad Virtual Tour

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#2948]
As per the new FAQ, you can't Salsette MVT as trashing and RFG are now distinct things. At the moment it still allows the runner to Salsette it.

**Comment by danhut** [comment]
Waiting on this pull request to get merged and put on live server. I have no ETA sorry
https://github.com/mtgred/netrunner/pull/2933

There is a remaining “hard” issue for this FAQ which is doppelgänger + mobius. Needs a new system in the engine. 

Closing this issue.
