### ISSUE TITLE
Executives trashed when Worlds Plaza is trashed go into Runner's score area

### ISSUE THREAD

**Issue by limnrix** [mtgred/netrunner#2949]
The Board, Victoria Jenkins, Director Haas, and Chairman Hiro read "if the runner trashes while accessing, add to the runner's score area as an agenda worth 2 points". If they are hosted on Worlds Plaza, and the runner accesses and trashes Worlds Plaza but not the executives individually, they currently still go into the score area when trashed. They should go into Archives. Hope this is fixable and I'm not wrong about the technicality here!

**Comment by limnrix** [comment]
Got a bug where even trashing out of hand puts it in their score area, as does trying to drag it back to archives from there.

**Comment by limnrix** [comment]
This doesn't seem to be technically fixed, but thank you for adding it to the faq

**Comment by danhut** [comment]
The fix is not live yet and I don’t know when the next server update is. Or do you mean something else?

**Comment by limnrix** [comment]
Ah, okay! I understand. Sorry.
