### ISSUE TITLE
Indexing epic dafuq ruination

### ISSUE THREAD

**Issue by p3t00h** [mtgred/netrunner#295]
![dafuq](https://cloud.githubusercontent.com/assets/11166143/8405921/ba5e4c08-1e60-11e5-9fca-29dbdfda1430.png)
This happened after I played indexing. 5 cards were removed from the game constantly and began to fall into my heap for gawd knows reason. My opponent told me that his Root stopped spawning renewable creds at some moment as well.

Offtop, but still a bug: I could not move virus counters from Virus Breeding Ground to Chakana hosted on Progenitor while playing EVER-FAMOUS WHUPASS DECK. 
Thank you for support and your service!

**Comment by mtgred** [comment]
1. Indexing shows you the top 5 cards of R&D. It's then up to you to drag and drop them back to R&D in the order of your choice.

2. There is an issue with cards being "locked" remote server when your an upgrade is being trashed or moved to hand. For such locked cards, the recurring credits don't refresh and it's possible to advance or move the card anymore. It's in the todo list of things to fix. The only workaround to "unlock" the card is to install an upgrade again in that remove server.

3. The issue with Virus Breeding Ground when targeting hosted cards will be fixed soon.

**Comment by mtgred** [comment]
I just tested Virus Breeding Ground with Chakana hosted on Progenitor and it actually works.

Virus Breeding grounds requires that the target has at least 1 Virus counter. I think your Chakana had none and that's why it didn't work for you.

**Comment by p3t00h** [comment]
Thank you!
I will try to donate you soon, jinteki.net is very cool!

2015-06-29 20:35 GMT+03:00 Minh Tran <notifications@github.com>:
