### ISSUE TITLE
Respirocytes: multiples and Levy AR

### ISSUE THREAD

**Issue by sperry023** [mtgred/netrunner#2951]
Sorry, didn't take a screenshot. I had 3 Respirocytes installed and only one fired when the condition was met (all 3 fire, confirmed in UFAQ).

Also, I believe it should fire during Levy AR Lab Access, but it didn't.

**Comment by Saintis** [comment]
Ugh that sounds like a can of worms getting Respirocytes to fire when LARLA is played...

**Comment by sperry023** [comment]
It just fired on LARLA, so either you guys are super quick or something else is up. This time there was only one in play and it definitely didn't fire already that turn -- I'm starting to wonder if maybe I already triggered Respirocytes that turn in my other game...

**Comment by danhut** [comment]
Hi - thanks for this - if you have not seen this again I suggest we close the issue.  You can re-open this if it happens again.  Can you please take a capture of the game log and screen shot if it does?

cheers
