### ISSUE TITLE
Gang Sign Inappropriately Accessing Multiple Cards from HQ

### ISSUE THREAD

**Issue by grimwalker** [mtgred/netrunner#2957]
AOT scored a CST while Leela had 2 Gang Sign. Each GS accessed 2 cards; no HQ Interface was installed.

Game Log follows (skip to the end for incident; Runner conceded due to extra accesses)

2woke2smoke
glgl
Capslock Intern keeps their hand.
2woke2smoke keeps their hand.

Capslock Intern
you too
Capslock Intern started their turn 1 with 5  and 5 cards in HQ.
Capslock Intern spends  to install ICE protecting R&D.
Capslock Intern spends  to gain 1 .
Capslock Intern spends  to gain 1 .
Capslock Intern is ending their turn 1 with 7  and 5 cards in HQ.
2woke2smoke started their turn 1 with 5  and 5 cards in their Grip.
Oldem joined the game as a spectator.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 5  to play Sure Gamble.
2woke2smoke uses Sure Gamble to gain 9 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Daily Casts.
2woke2smoke is ending their turn 1 with 6  and 5 cards in their Grip.
Capslock Intern started their turn 2 with 7  and 5 cards in HQ.
Capslock Intern spends  and 1 to play Special Report.
Capslock Intern uses Special Report to shuffle 3 cards in HQ into R&D and draw 3 cards.
Capslock Intern spends  to gain 1 .
Capslock Intern spends  to gain 1 .
Capslock Intern is ending their turn 2 with 8  and 5 cards in HQ.
2woke2smoke started their turn 2 with 6  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke accesses Fairchild from HQ.
2woke2smoke spends  and 1  to install Gang Sign.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke is ending their turn 2 with 9  and 4 cards in their Grip.
Capslock Intern started their turn 3 with 8  and 5 cards in HQ.
Capslock Intern spends  and 5 to play Hedge Fund.
Capslock Intern uses Hedge Fund to gain 9 .
Capslock Intern spends  to install ICE protecting Server 1 (new remote).
Capslock Intern spends  to install a card in Server 1.
Capslock Intern is ending their turn 3 with 12  and 3 cards in HQ.
2woke2smoke started their turn 3 with 9  and 4 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Daily Casts.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 3 with 7  and 4 cards in their Grip.
Capslock Intern uses Museum of History to shuffle Hedge Fund into R&D.
Capslock Intern started their turn 4 with 11  and 3 cards in HQ.
Capslock Intern spends  to install ICE protecting HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 8 to play IPO.
Capslock Intern uses IPO to gain 13 .
Capslock Intern is ending their turn 4 with 16  and 3 cards in HQ.
2woke2smoke started their turn 4 with 7  and 4 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Aumakua.
2woke2smoke spends  to draw a card.
2woke2smoke discards Daredevil from their Grip.
2woke2smoke is ending their turn 4 with 8  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle IPO into R&D.
Capslock Intern started their turn 5 with 16  and 3 cards in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to install ICE protecting Archives.
Capslock Intern is ending their turn 5 with 16  and 5 cards in HQ.
2woke2smoke started their turn 5 with 8  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  and 1  to play Peace in Our Time.
2woke2smoke uses Peace in Our Time to gain 10 . The Corp gains 5 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to install Dean Lister.
2woke2smoke is ending their turn 5 with 19  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle Special Report into R&D.
Capslock Intern started their turn 6 with 21  and 5 cards in HQ.
Capslock Intern spends  to install a card in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern is ending their turn 6 with 21  and 5 cards in HQ.
2woke2smoke started their turn 6 with 19  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to install The Turning Wheel.
2woke2smoke spends  and 3  to install GPI Net Tap.
2woke2smoke is ending their turn 6 with 16  and 5 cards in their Grip.
Capslock Intern started their turn 7 with 21  and 5 cards in HQ.
Capslock Intern spends  and 1 to install ICE protecting R&D.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 8 to play IPO.
Capslock Intern uses IPO to gain 13 .
Capslock Intern is ending their turn 7 with 25  and 5 cards in HQ.
2woke2smoke started their turn 7 with 16  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to play Deuces Wild.
2woke2smoke uses Deuces Wild to draw 2 cards.
2woke2smoke uses Deuces Wild to expose 1 ice and make a run.
2woke2smoke exposes Fairchild 2.0 protecting Archives at position 0.
2woke2smoke exposes Fairchild 2.0 protecting Archives at position 0.
Capslock Intern spends 4  to rez Fairchild 2.0.
2woke2smoke uses Dean Lister to add +1 strength for each card in their Grip to Aumakua until the end of the run.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke indicates to fire the "Force the Runner to pay 2  or trash an installed card" subroutine on Fairchild 2.0.
Capslock Intern uses Fairchild 2.0 to force the Runner to pay 2  or trash an installed card.
Capslock Intern uses Fairchild 2.0 to force the Runner to trash Cache.
Capslock Intern has no further action.
Capslock Intern uses Haas-Bioroid: Architects of Tomorrow to rez Ravana 1.0.
Capslock Intern rezzes Ravana 1.0.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke spends  and 2  to install Dean Lister.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 7 with 11  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle IPO into R&D.
Capslock Intern started their turn 8 with 21  and 5 cards in HQ.
Capslock Intern spends  to install ICE protecting Server 2 (new remote).
Capslock Intern moves a card from their Server 2 to HQ.
Capslock Intern sets click to 3 (+1).
Capslock Intern spends  to install ICE protecting Server 3 (new remote).
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  to draw a card.
Capslock Intern is ending their turn 8 with 21  and 5 cards in HQ.
2woke2smoke started their turn 8 with 11  and 5 cards in their Grip.
2woke2smoke spends  and 2  to play Deuces Wild.
2woke2smoke uses Deuces Wild to draw 2 cards.
2woke2smoke uses Deuces Wild to gain 3 .
2woke2smoke spends  and 5  to play Sure Gamble.
2woke2smoke uses Sure Gamble to gain 9 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 8 with 15  and 5 cards in their Grip.
Capslock Intern started their turn 9 with 21  and 5 cards in HQ.
Capslock Intern spends  to install a card in Server 3.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern trashes Museum of History in Server 1.
Capslock Intern spends 1  to rez MCA Austerity Policy.
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern is ending their turn 9 with 20  and 4 cards in HQ.
2woke2smoke started their turn 9 with 15  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to play On the Lam.
2woke2smoke hosts On the Lam on Gang Sign.
2woke2smoke spends  to draw a card.
2woke2smoke discards Aumakua from their Grip.
2woke2smoke is ending their turn 9 with 12  and 5 cards in their Grip.
Capslock Intern spends 2  to rez Marilyn Campaign.
Capslock Intern started their turn 10 with 18  and 4 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  and 5 to play Hedge Fund.
Capslock Intern uses Hedge Fund to gain 9 .
Capslock Intern spends 2  to rez Awakening Center.
Capslock Intern spends  to use Awakening Center to host a piece of Bioroid ICE.
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern is ending their turn 10 with 22  and 3 cards in HQ.
2woke2smoke started their turn 10 with 12  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install The Supplier.
2woke2smoke spends  to use The Supplier to host Daredevil.
2woke2smoke is ending their turn 10 with 9  and 4 cards in their Grip.
Capslock Intern started their turn 11 with 22  and 3 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern spends  to use MCA Austerity Policy to gain 4 and trash itself.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern gains 4  from CFC Excavation Contract.
Capslock Intern scores CFC Excavation Contract and gains 2 agenda points.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Viktor 1.0 from HQ.
2woke2smoke uses Leela Patel: Trained Pragmatist to add ICE protecting HQ at position 0 to HQ.
Capslock Intern is ending their turn 11 with 24  and 4 cards in HQ.
2woke2smoke started their turn 11 with 9  and 4 cards in their Grip.
2woke2smoke spends 3  to install Daredevil.
2woke2smoke uses The Supplier to install Daredevil lowering its install cost by 2.
2woke2smoke spends  to make a run on HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke jacks out.
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke jacks out.
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
2woke2smoke accesses Fairchild 2.0 from HQ.
2woke2smoke accesses Viktor 1.0 from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke is ending their turn 11 with 12  and 4 cards in their Grip.
Capslock Intern started their turn 12 with 24  and 4 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  to install ICE protecting HQ.
Capslock Intern spends  and 1 to install ICE protecting HQ.
Capslock Intern spends  to draw a card.
Capslock Intern is ending their turn 12 with 25  and 4 cards in HQ.
2woke2smoke started their turn 12 with 12  and 4 cards in their Grip.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke spends  and 4  to install Sneakdoor Beta.
2woke2smoke trashes Cache from their Rig.
2woke2smoke spends  to use Sneakdoor Beta to make a run on Archives.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
Capslock Intern has no further action.
Capslock Intern uses Haas-Bioroid: Architects of Tomorrow to rez Fairchild 2.0.
Capslock Intern rezzes Fairchild 2.0.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke uses Sneakdoor Beta to make a successful run on HQ.
2woke2smoke accesses Museum of History from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke spends  to use Sneakdoor Beta to make a run on Archives.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
Capslock Intern has no further action.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
2woke2smoke uses Sneakdoor Beta to make a successful run on HQ.
2woke2smoke accesses Howler from HQ.
2woke2smoke accesses Museum of History from HQ.
2woke2smoke pays 3  to trash Museum of History from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke is ending their turn 12 with 1  and 2 cards in their Grip.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern uses Marilyn Campaign to shuffle it back into R&D.
Capslock Intern started their turn 13 with 27  and 3 cards in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 1 to install ICE protecting Archives.
Capslock Intern is ending their turn 13 with 26  and 5 cards in HQ.
2woke2smoke started their turn 13 with 1  and 2 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 1  to install Gang Sign.
2woke2smoke is ending their turn 13 with 0  and 4 cards in their Grip.
Capslock Intern started their turn 14 with 26  and 5 cards in HQ.
Capslock Intern spends  to purge all virus counters.
Capslock Intern discards a card from their HQ.
Capslock Intern is ending their turn 14 with 26  and 5 cards in HQ.
2woke2smoke started their turn 14 with 0  and 4 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to gain 1 .
2woke2smoke discards The Turning Wheel from their Grip.
2woke2smoke discards Aumakua from their Grip.
2woke2smoke is ending their turn 14 with 1  and 5 cards in their Grip.
Capslock Intern started their turn 15 with 26  and 5 cards in HQ.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  to install a card in Server 3.
Capslock Intern is ending their turn 15 with 25  and 4 cards in HQ.
2woke2smoke started their turn 15 with 1  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke trashes Sneakdoor Beta from their Rig.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke spends  to use The Supplier to host GPI Net Tap.
2woke2smoke is ending their turn 15 with 3  and 5 cards in their Grip.
Capslock Intern spends 1  to rez Museum of History.
Capslock Intern uses Museum of History to shuffle Museum of History into R&D.
Capslock Intern started their turn 16 with 24  and 4 cards in HQ.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern scores Corporate Sales Team and gains 2 agenda points.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Special Report from HQ.
2woke2smoke accesses Hedge Fund from HQ.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Special Report from HQ.
2woke2smoke accesses Project Vitruvius from HQ.
2woke2smoke steals Project Vitruvius and gains 2 agenda points.
2woke2smoke uses Leela Patel: Trained Pragmatist to add ICE protecting Server 3 at position 0 to HQ.

Capslock Intern
hold on

2woke2smoke
ok

Capslock Intern
You accessed 2 cards for each gang sign

2woke2smoke
crap

2woke2smoke
well

Capslock Intern
how did that happen

2woke2smoke
glitch

2woke2smoke
hm

2woke2smoke
ok

2woke2smoke
well

2woke2smoke
i'll concede then

2woke2smoke
cheers

2woke2smoke
gg

Capslock Intern
sorry man
2woke2smoke concedes.
Capslock Intern wins the game.
2woke2smoke left the game.

![image](https://user-images.githubusercontent.com/8509084/33536942-11b3d052-d87e-11e7-80f0-5151065b69d8.png)

**Comment by Saintis** [comment]
I wonder if this some strange interaction with Gang Sign, Turning Wheel and Sneakdoor...

**Comment by JoelCFC25** [comment]
This is going to be a Turning Wheel problem, not a Gang Sign problem. The `:counters-spent` key in TTW is probably not being dissoc'd properly after usage, which then makes TTW wrongly respond to the `:pre-access` event coming from Gang Sign(s).
