### ISSUE TITLE
Dadiana Chacon not trashed when played at 2c with Scarcity of Resources in play

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#2958]
EricF spends 2  and  to install Dadiana Chacon.
EricF spends  to make a run on HQ.
EricF places a power counter on The Turning Wheel.
EricF jacks out.
EricF discards GS Striker M1 from their Grip.
EricF is ending their turn 5 with 0 and 5 cards in their Grip.

**Comment by nealterrell** [comment]
Card should check the credits when it is installed, in addition to other state changes.
