### ISSUE TITLE
Daily Failness Show

### ISSUE THREAD

**Issue by jbrz** [mtgred/netrunner#2959]
DBS has a litany of problems in regards to draw triggers outside of mandatory draws.

Chief amongst these problems is:
`The runner is not stopped from acting (during runs, for instance) while the corp chooses card(s) to bottom`

So if the corp fires a draw during the runner's turn, ideally a `waiting for corp to use DBS` pop-up should appear (imo).  During runs this can cause exceptionally awkward game state problems where a runner accesses and steals an agenda or accesses and trashes an asset which the corp will be bottoming/drawing.

Examples of this happening:
- Literally anything to do with Fisk running Centrals (R&D and HQ specifically re: game state issues).
- Any time a runner event/resource causes corp draws, no prompt or notice other than in chat (again, should probably be a pop-up/blocking prompt to stop runner from doing anything until the draw/bottom is finished)

**Equivocation** (oh god):
- If runner chooses to reveal _and_ force draw, magically a "waiting for corp to draw" window appears, exactly as it probably should any other time dbs fires.
- As fisk, you can choose to fire the fisk draw first, and you _won't_ be prompted to wait for DBS, so you can reveal and force corp to draw before that's all done - this _shouldn't_ cause any gamestate issues as the cards you are accessing/revealing are irrelevant to the DBS firing, but it can be exceptionally confusing if you're not clear on all the interactions at play (can imagine corp being confused about what was drawn with DBS).

Moving on:
`DBS doesn't watch for "first" instance of draw in a turn`
Meaning if the corp draws, rezzes DBS, and then clicks to draw, DBS will fire.  oops.
Similarly, if runner forces corp to draw, corp then rezzes DBS, and corp is forced to draw again on runner's turn, DBS will then fire on that second draw.  oops.
I recognize that this particular issue is an old and known one.  Not sure if there's been any change to engine to support handling this better or not...

Combine the above instances and you run into a huge headache to manually resolve.

**Comment by danhut** [comment]
I think stuff can be done - this write up explains it very well compared to previous reports and makes work on it very viable.  Prior - I had no idea what the issues actually was.

**Comment by jbrz** [comment]
Looking at DBS, it's pretty specifically enabled currently to `:pre-corp-draw` and `:post-corp-draw` with what looks like the latter having a check for draws, but that's clearly not matching the actual usage of the card.

Probably just a true/false register on any `:corp-draw` event would solve this particular aspect, no? Would have to reset on end-turn, ofc... (i'll maybe try this weekend if a smarter individual doesn't get to it before then)

As for the other half of this issue, I guess it's just missing a `:msg` to display for runner?  I'm not familiar enough with that aspect of card implementations.

**Comment by nealterrell** [comment]
I think these can be solved with two small changes:

* Show a "waiting for" prompt to the Runner in DBS's `:post-corp-draw` handler, which is where the Corp is selecting a card to bury. Clear the prompt when the cards are selected.
* Add a requirement of `first-event?` to the two handlers, which is how we deal with "first this turn" that happened before a card was activated.

**Comment by jbrz** [comment]
good catch, I was seeing the card-bottom prompt without even noticing the singleton drawn.  fix you pushed _appears_ to have solved all issues - I think I tested them all, but it's been almost 2mo, so i might have missed an edge case.  Thanks!
