### ISSUE TITLE
Interaction with Unique Ice and Jinteki AGInfusion Ability

### ISSUE THREAD

**Issue by Matt500** [mtgred/netrunner#2965]
Hi there, apologies if you are already aware of this!

Just played a game in which the following occured:

1. i have non-unique ice installed on R & D and HQ and rezzed
2. i have a unique Excalibur on Archives rezzed
3. I have a unique Mother Goddess on remote 1, rezzed;
4. I have an asset installed in remote 2, with an unrezzed piece of ice, being Mother Goddess.

The Runner on his first click initiates a run on the second remote with an unrezzed Mother Goddess.

As the Corp, i decide to trigger AGInfusion ID ability instead of rezzing the ice. When i click the image of AGInfusion, the error message is then displayed:

"Cannot rez a second copy of Mother Goddess since it is unique. Please trash the other copy first"

Clicking multiple times does not work (obviously)

Based on my understanding of Netrunner, even though there is a rezzed unique copy of the ice already rezzed, i should still be able to use AGInfusion ability on the unrezzed Mother Goddess as at the time i had 13 credits and could have chosen to rez server 2 mother goddess by trashing server 1 mother goddess.

Thank you happy to be corrected as always!

Cheers,
Matt500

**Comment by Eric-Fletcher** [comment]
As a workaround, you can de-rez one copy, use Agfusion, then manually add credits and re-rez.

Note that the "block rez" functionality is to avoid the feel-bad of accidentally trashing your other copy. Something like DDS should still stop AgFusion, though.

**Comment by Saintis** [comment]
Another workaround could be to allow multiple unique Ice rezzed and mark the older one in red outline (like the new cards are marked) and let Corp trash these manually.

That or tweak the AgInfusion check..

**Comment by nealterrell** [comment]
Yeah, I'd say have AgInfusion pass a "ignore uniqueness" flag to the can-rez routine.

**Comment by Matt500** [comment]
Thanks all for being on top of it so quick really appreciate the hard work!

Cheers
Matt500
