### ISSUE TITLE
Maw sometimes reveals the trashed card

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#2969]
When Maw automatically trashes a card, if it randomly chooses the card being accessed, it is trashed face up instead of face down. Has been tested on hands with one card (so will certainly be picked by Maw) and hands with multiple non-trashable cards (where it will sometimes pick the card being accessed and trash it face up).

**Comment by Eric-Fletcher** [comment]
This is the correct behavior, per FAQ.

**Comment by finnbar** [comment]
In which case, my bad (I didn't realise that ruling was a thing and am a little confused about it, but anyway). Closing.
