### ISSUE TITLE
Card Collection Not Loading

### ISSUE THREAD

**Issue by drwormmd** [mtgred/netrunner#2971]
I can't figure out a pattern as to why, but when logging in sometimes my deck collection loads, and sometimes it doesn't. 

Refreshing doesn't seem to work until it does. Not sure what is going on.

**Comment by JoelCFC25** [comment]
You'll have to indicate which browser you are using. Note that IE and Edge are not supported.

**Comment by drwormmd** [comment]
IE and Edge.

Gotcha.

**Comment by drwormmd** [comment]
What about Firefox?

**Comment by danhut** [comment]
Can you see if this occurs now?  We just went live with a total server re-write.
