### ISSUE TITLE
Tinkering not placing markers

### ISSUE THREAD

**Issue by Zerothmaxima** [mtgred/netrunner#2972]
No tinkering token on Tinkering'd ice anymore?

**Comment by danhut** [comment]
What behaviour are you expecting here?  I looked at the last 3 years of code for this card and we've never placed markers for it.

Are you expecting something like the "F" placed by Femme Fatale?

**Comment by Zerothmaxima** [comment]
Hey Dan,

Yes, either something like a T for tinkering would make sense, or B-C-S
like Mother Goddess.

Thanks!
