### ISSUE TITLE
Legwork Accessing Too Many Cards (Archangel or Muertos Gang Member Interaction?)

### ISSUE THREAD

**Issue by grimwalker** [mtgred/netrunner#2978]
On a Legwork run, Ken Tenma accessed Hedge Fund, Enigma, Archangel. Corp used Archangel to uninstall Muertos Gang Member, creating a hanging effect for the corp to rez a card.. Runner then accessed Tollbooth, Hedge Fund, (Corp rezzed Data Raven over R&D), Estelle Moon, and Archangel again. Corp did not pay to trigger Archangel.  

Full Game Log:

Pampelmuse takes a mulligan.
Pampelmuse
Pampelmuse
gl hf
Silk keeps their hand.
Pampelmuse started their turn 1 with 5  and 5 cards in HQ.
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse spends  to install a card in Server 1 (new remote).
Pampelmuse spends  to install a card in Server 2 (new remote).
Pampelmuse spends  to gain 1 .
Pampelmuse is ending their turn 1 with 6  and 5 cards in HQ.
Pampelmuse uses Advanced Assembly Lines to gain 3 .
Pampelmuse spends 1  to rez Advanced Assembly Lines.
Silk started their turn 1 with 5  and 5 cards in their Grip.
Silk spends  to play Fisk Investment Seminar.
Silk uses Fisk Investment Seminar to make each player draw 3 cards.
Pampelmuse uses Advanced Assembly Lines to install an unseen card from HQ.
Pampelmuse installs ICE protecting R&D.
Silk spends  and 2  to play Dirty Laundry.
Silk uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
Pampelmuse has no further action.
Silk accesses Enigma from HQ.
Silk uses Dirty Laundry to gain 5 .
Silk spends  and 5  to play Sure Gamble.
Silk uses Sure Gamble to gain 9 .
Silk spends  to gain 1 .
Silk is ending their turn 1 with 14 and 5 cards in their Grip.
Pampelmuse started their turn 2 with 8  and 7 cards in HQ.
Pampelmuse spends 2  to rez Jeeves Model Bioroids.
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse spends  to install a card in Server 3 (new remote).
Pampelmuse spends  to install a card in Server 4 (new remote).
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse spends  to install a card in Server 5 (new remote).
Pampelmuse spends  to install ICE protecting HQ.
Pampelmuse is ending their turn 2 with 6  and 5 cards in HQ.
Silk started their turn 2 with 14 and 5 cards in their Grip.
Silk spends  to play Fisk Investment Seminar.
Silk uses Fisk Investment Seminar to make each player draw 3 cards.
Silk spends  to play Process Automation.
Silk uses Process Automation to gain 2  and draw 1 card.
Silk spends  to install Muertos Gang Member.
Silk spends  to install Same Old Thing.
Pampelmuse derezzes Jeeves Model Bioroids.
Silk is ending their turn 2 with 16 and 5 cards in their Grip.
Pampelmuse started their turn 3 with 6  and 8 cards in HQ.
Pampelmuse spends  and 5  to play Hedge Fund.
Pampelmuse uses Hedge Fund to gain 9 .
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse spends  to install a card in Server 6 (new remote).
Pampelmuse spends 2  to rez Turtlebacks.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse spends  to install a card in Server 7 (new remote).
Pampelmuse discards a card from their HQ.
Pampelmuse discards a card from their HQ.
Pampelmuse is ending their turn 3 with 9  and 5 cards in HQ.
Silk started their turn 3 with 16 and 5 cards in their Grip.
Silk spends  to play Build Script.
Silk uses Build Script to gain 1  and draw 2 cards.
Silk spends  to play Process Automation.
Silk uses Process Automation to gain 2  and draw 1 card.
Silk spends  and 5  to install Lustig.
Silk spends  to make a run on HQ.
Pampelmuse
Pampelmuse
Gotta wonder if a Comet is coming down at some point
Pampelmuse has no further action.
Silk continues the run.
Pampelmuse has no further action.
Silk accesses Tollbooth from HQ.
Silk is ending their turn 3 with 14 and 5 cards in their Grip.
Pampelmuse spends 2  to rez Daily Business Show.
Silk
Silk
hardware is for sucks
Silk
Silk
cucks
Pampelmuse started their turn 4 with 7  and 5 cards in HQ.
Pampelmuse uses Daily Business Show to draw additional cards.
Pampelmuse uses Daily Business Show to add 1 card to the bottom of R&D.
Pampelmuse spends 2  to rez Jeeves Model Bioroids.
Pampelmuse spends  and 1  to advance a card in Server 4.
Pampelmuse spends  and 1  to advance a card in Server 4.
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse spends  and 1  to advance a card in Server 4.
Pampelmuse spends  and 1  to advance a card in Server 4.
Pampelmuse spends 1  to rez Team Sponsorship.
Pampelmuse uses Team Sponsorship to install Advanced Assembly Lines from Archives.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse installs a card in Server 8 (new remote).
Pampelmuse scores Explode-a-palooza and gains 2 agenda points.
Pampelmuse uses Advanced Assembly Lines to gain 3 .
Pampelmuse spends 1  to rez Advanced Assembly Lines.
Pampelmuse uses Advanced Assembly Lines to install an unseen card from HQ.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse installs a card in Server 9 (new remote).
Pampelmuse discards a card from their HQ.
Pampelmuse is ending their turn 4 with 4  and 5 cards in HQ.
Silk started their turn 4 with 14 and 5 cards in their Grip.
Silk spends  to draw a card.
Silk spends  and 4  to install Demara.
Silk spends  to make a run on Server 9.
Pampelmuse has no further action.
Silk accesses Estelle Moon from Server 9.
Silk pays 3  to trash Estelle Moon from Server 9.
Silk spends  to gain 1 .
Silk is ending their turn 4 with 8 and 5 cards in their Grip.
Pampelmuse started their turn 5 with 4  and 5 cards in HQ.
Pampelmuse uses Daily Business Show to draw additional cards.
Pampelmuse uses Daily Business Show to add 1 card to the bottom of R&D.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse spends  to install a card in Server 10 (new remote).
Pampelmuse spends 2  to rez Turtlebacks.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse spends  to install a card in Server 11 (new remote).
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse spends  to install a card in Server 12 (new remote).
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse spends  to install a card in Server 13 (new remote).
Pampelmuse is ending their turn 5 with 9  and 3 cards in HQ.
Silk started their turn 5 with 8  and 5 cards in their Grip.
Silk spends  to play Fisk Investment Seminar.
Silk uses Fisk Investment Seminar to make each player draw 3 cards.
Pampelmuse uses Daily Business Show to draw additional cards.
Silk spends  and 1  to install Public Terminal.
Pampelmuse uses Daily Business Show to add 1 card to the bottom of R&D.
Pampelmuse
Pampelmuse
all 3 Fisk, nice
Pampelmuse
Pampelmuse
I have an SC on Saturday
Silk
Silk
?
Pampelmuse
Pampelmuse
hope to pick up a set of alt art FIS
Silk
Silk
oh
Silk spends  and 2  to play Inside Job.
Silk uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
Pampelmuse has no further action.
Silk continues the run.
Pampelmuse has no further action.
Silk accesses an unseen card from R&D.
Silk pays 1  to trash Advanced Assembly Lines from R&D.
Silk spends  to gain 1 .
Silk is ending their turn 5 with 6 and 5 cards in their Grip.
Pampelmuse started their turn 6 with 9  and 6 cards in HQ.
Pampelmuse uses Daily Business Show to draw additional cards.
Pampelmuse uses Daily Business Show to add 1 card to the bottom of R&D.
Pampelmuse
Pampelmuse
hmm
Silk uses Public Terminal to take 1 .
Pampelmuse spends  and 1  to advance a card in Server 11.
Pampelmuse spends  and 1  to advance a card in Server 11.
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse spends  and 1  to advance a card in Server 11.
Pampelmuse uses License Acquisition to install and rez Estelle Moon, ignoring all costs.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse installs Estelle Moon in Server 14 (new remote).
Pampelmuse rezzes Estelle Moon at no cost.
Pampelmuse uses Team Sponsorship to install an unseen card from HQ.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse installs a card in Server 15 (new remote).
Pampelmuse places 1 power counter on Estelle Moon.
Pampelmuse scores License Acquisition and gains 1 agenda point.
Pampelmuse uses Advanced Assembly Lines to gain 3 .
Pampelmuse spends 1  to rez Advanced Assembly Lines.
Pampelmuse uses Advanced Assembly Lines to install an unseen card from HQ.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse installs a card in Server 16 (new remote).
Pampelmuse places 1 power counter on Estelle Moon.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse spends  to install a card in Server 17 (new remote).
Pampelmuse places 1 power counter on Estelle Moon.
Pampelmuse is ending their turn 6 with 16  and 5 cards in HQ.
Silk started their turn 6 with 7  and 5 cards in their Grip.
Silk spends  to draw a card.
Silk spends  and 5  to play Sure Gamble.
Silk uses Sure Gamble to gain 9 .
Silk spends  to draw a card.
**Silk spends  and 2  to play Legwork.
Silk uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
Silk uses Public Terminal to take 1 .
Pampelmuse has no further action.
Silk continues the run.
Pampelmuse has no further action.
Silk accesses Hedge Fund from HQ.
Silk accesses Enigma from HQ.
Silk accesses Archangel from HQ.
Pampelmuse pays 3  to force the Runner to encounter Archangel.
Pampelmuse uses Archangel to initiate a trace with strength 6 (6 + 0 ) ().
Silk spends 0  to increase link strength to 0.
Pampelmuse uses Archangel to add 1 installed card to the Runner's Grip.
Pampelmuse adds Muertos Gang Member to the Runner's Grip.
Silk accesses Tollbooth from HQ.
Silk accesses Hedge Fund from HQ.
Pampelmuse rezzes Data Raven at no cost.
Pampelmuse rezzes Data Raven at no cost.
Silk accesses Estelle Moon from HQ.
Silk accesses Archangel from HQ.**
Silk
Silk
hmmmm
Pampelmuse
Pampelmuse
what happened?
Silk
Silk
i'll jack out
Pampelmuse
Pampelmuse
did it just keep feeding you cards to access?
Pampelmuse declines to force the Runner to encounter Archangel.
Silk accesses Enigma from HQ.
Silk discards Muertos Gang Member from their Grip.
Silk is ending their turn 6 with 11 and 5 cards in their Grip.
Pampelmuse spends 2  to rez Daily Business Show.
Pampelmuse started their turn 7 with 11  and 5 cards in HQ.
Pampelmuse uses Daily Business Show to draw additional cards.
Pampelmuse uses Daily Business Show to add 2 cards to the bottom of R&D.
Pampelmuse spends  and 1  to advance a card in Server 13.
Pampelmuse spends  and 1  to advance a card in Server 13.
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse spends  and 1  to advance a card in Server 13.
Pampelmuse spends  and 1  to advance a card in Server 13.
Pampelmuse uses Team Sponsorship to install an unseen card from HQ.
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Turtlebacks to gain 1 .
Pampelmuse uses Near-Earth Hub: Broadcast Center to draw 1 card.
Pampelmuse installs a card in Server 18 (new remote).
Pampelmuse places 1 power counter on Estelle Moon.
Pampelmuse scores Corporate Sales Team and gains 2 agenda points.
Pampelmuse discards a card from their HQ.
Pampelmuse is ending their turn 7 with 9  and 5 cards in HQ.
Silk started their turn 7 with 11 and 5 cards in their Grip.
Pampelmuse uses Corporate Sales Team to gain 1 .
Silk spends  to draw a card.
Silk spends  to install Muertos Gang Member.
Silk spends  to draw a card.
Pampelmuse derezzes Team Sponsorship.
Silk spends  and 2  to play Deuces Wild.
Silk uses Deuces Wild to gain 3 .
Silk uses Deuces Wild to expose 1 ice and make a run.
Silk exposes Enigma protecting HQ at position 0.
Pampelmuse has no further action.
Silk is ending their turn 7 with 12 and 5 cards in their Grip.
Pampelmuse started their turn 8 with 10  and 5 cards in HQ.
Pampelmuse uses Corporate Sales Team to gain 1 .
Pampelmuse uses Daily Business Show to draw additional cards.
Pampelmuse uses Daily Business Show to add 2 cards to the bottom of R&D.
Pampelmuse spends  and 1  to advance a card in Server 5.
Pampelmuse spends  and 1  to advance a card in Server 5.
Pampelmuse uses Jeeves Model Bioroids to gain .
Pampelmuse spends  and 1  to advance a card in Server 5.
Pampelmuse spends  and 1  to advance a card in Server 5.
Pampelmuse scores Explode-a-palooza and gains 2 agenda points.
Pampelmuse wins the game.
Silk left the game.
Pampelmuse
Pampelmuse
gg

**Comment by JoelCFC25** [comment]
This is a Muertos Gang Member problem, nothing to do with Legwork or Archangel. Although it's quite a corner case, MGM needs to use delayed completion for all of this to work as expected.
