### ISSUE TITLE
Guru Davinder and Obokata protocol

### ISSUE THREAD

**Issue by Porkobolo** [mtgred/netrunner#2985]
Obokata deal damage BEFORE Guru prevents it. Why?
This is the relevant log of the game:

Porkobolo uses Hades Shard to access all cards in Archives.
Porkobolo accesses Nisei MK II from Archives.
Porkobolo steals Nisei MK II and gains 2 agenda points.
Porkobolo accesses Nisei MK II from Archives.
Porkobolo steals Nisei MK II and gains 2 agenda points.
Porkobolo accesses Philotic Entanglement from Archives.
Porkobolo steals Philotic Entanglement and gains 2 agenda points.
Porkobolo accesses Obokata Protocol from Archives.
Porkobolo uses Guru Davinder to prevent all net damage.
Porkobolo trashes due to damage.
Porkobolo is flatlined.
Synisill wins the game.
Porkobolo pays 4 net damage to steal Obokata Protocol.
Porkobolo steals Obokata Protocol and gains 3 agenda points.
Porkobolo pays 4  to prevent Guru Davinder from being trashed.

**Comment by nealterrell** [comment]
You cannot steal Obokata while Guru is installed. This is a difficult fix, so you should manually resolve it in the future by declining the steal and deciding whether to trash Guru manually.

**Comment by danhut** [comment]
@nealterrell Couldn't we just add a :cannot-pay-net flag to Guru then check for it when trying to pay net?
