### ISSUE TITLE
Pheromones not implemented?

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#299]
Thought I'd seen another log but couldn't find it.

Pheromones doesn't seem to do anything at the moment. It doesn't get a counter automatically and you can't add manually.

**Comment by JoelCFC25** [comment]
It's not implemented at all. I could submit a patch that at least adds the virus counter on successful HQ runs, but right now the only way to support variable numbers of recurring credits (currently just this card and Net Police) is with a special function that I don't know how to write.

**Comment by qmsm** [comment]
My naivety goes well beyond my play and into not checking the card status list and not realising that counters wouldn't fully fix it.

Having said that, I think having the virus counter would be a useful workaround for now if it's straightforward to implement.

**Comment by mtgred** [comment]
Pheromones and Net Police has been implemented. The update will be deployed this afternoon.

**Comment by JoelCFC25** [comment]
Implemented at c295d128ed84496e0e1a775c42545600e9a4e004.
