### ISSUE TITLE
RIP Deal

### ISSUE THREAD

**Issue by elstyr** [mtgred/netrunner#2995]
RIP Deal let's the runner access Upgrades in the root of HQ. It shouldn't.

Cheers.

**Comment by Eric-Fletcher** [comment]
Per card text, upgrades in the root should be accessed normally.

**Comment by Saintis** [comment]
As the [UFAQ entry](https://netrunnerdb.com/en/card/12084) of this card says:

> If the Runner chooses to use Rip Deal's ability, they still access cards from the root of HQ, but those cards do not add to the number of cards that the Runner adds from the heap to the grip.

This is working as intended.
