### ISSUE TITLE
trashing R&D Interface from Supplier

### ISSUE THREAD

**Issue by javel-by** [mtgred/netrunner#300]
(seems similar with issue #39)
Runner got Supplier installed.
Runner hosted RnD Interface on Supplier.
Runner got tagged.
Corp used "Trash resource" button, and trashed Supplier with Interface hosted.
Runner accessed 0 cards during runs on RnD.

(after installing second RnD interface, Runner could access 1 card more)

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

**Comment by JoelCFC25** [comment]
Confirmed that this is fixed--tested the exact same scenario in the initial report and correctly accessed 2 cards from R&D after installing a new R&D Interface.
