### ISSUE TITLE
Rezzing Tithonium with alternate rez cost broke the game

### ISSUE THREAD

**Issue by agileminor** [mtgred/netrunner#3022]
On turn 17, I rezzed a tithonium, picked the alternate rez cost and then tried to select an agenda from my score area. It wouldn't let me select either agenda (2 nisei). After that, it wouldn't let me click on anything in response to any prompts.

Except for one time, when I tried to boost an ice using ITD, and it removed the ice from the game!

Game log pasted below. I was playing as Aginfusion against Omar.

originalme
originalme
glhf
tf34
tf34
hi
tf34
tf34
glgl
originalme keeps their hand.
tf34 takes a mulligan.
originalme started their turn 1 with 5 and 5 cards in HQ.
originalme spends  to install ICE protecting Server 1 (new remote).
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme spends  and 8  to play IPO.
originalme uses IPO to gain 13 .
originalme is ending their turn 1 with 14  and 3 cards in HQ.
tf34 started their turn 1 with 5  and 5 cards in their Grip.
tf34 spends  and 1  to play Inject.
tf34 adds Data Folding to Grip.
tf34 adds Stimhack to Grip.
tf34 adds Liberated Account to Grip.
tf34 adds Sure Gamble to Grip.
tf34 spends  to gain 1 .
tf34 spends  and 5  to play Sure Gamble.
tf34 uses Sure Gamble to gain 9 .
tf34 spends  and 3  to install Data Folding.
tf34 discards Black Orchestra from their Grip.
tf34 is ending their turn 1 with 6  and 5 cards in their Grip.
originalme started their turn 2 with 14 and 3 cards in HQ.
originalme spends  to install ICE protecting HQ.
originalme spends  to install ICE protecting R&D.
originalme spends  to install ICE protecting Archives.
originalme is ending their turn 2 with 14  and 1 cards in HQ.
tf34 started their turn 2 with 6  and 5 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  and 6  to install Liberated Account.
tf34 spends  to use Liberated Account to gain 4 .
tf34 spends  to use Liberated Account to gain 4 .
tf34 is ending their turn 2 with 9  and 5 cards in their Grip.
originalme started their turn 3 with 14 and 1 cards in HQ.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme spends  and 8  to play IPO.
originalme uses IPO to gain 13 .
originalme is ending their turn 3 with 19  and 3 cards in HQ.
tf34 started their turn 3 with 9  and 5 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  and 3  to install Data Folding.
tf34 spends  and 1  to install Film Critic.
tf34 spends  to use Liberated Account to gain 4 .
tf34 is ending their turn 3 with 10  and 4 cards in their Grip.
originalme started their turn 4 with 19 and 3 cards in HQ.
originalme spends  to draw a card.
originalme spends  and 1  to install ICE protecting R&D.
originalme spends  to install a card in Server 1.
originalme is ending their turn 4 with 18  and 3 cards in HQ.
tf34 started their turn 4 with 10  and 4 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  and 1  to play Inject.
tf34 adds Hacktivist Meeting to Grip.
tf34 adds Daily Casts to Grip.
tf34 adds Sure Gamble to Grip.
tf34 adds Career Fair to Grip.
tf34 spends  to play Career Fair.
tf34 installs Daily Casts.
tf34 spends  and 2  to install The Turning Wheel.
tf34 is ending their turn 4 with 9  and 5 cards in their Grip.
originalme rezzes Tech Startup.
originalme uses Tech Startup to install IT Department.
originalme installs a card in Server 1.
originalme started their turn 5 with 18 and 3 cards in HQ.
originalme spends 2  to rez IT Department.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 5 with 16  and 4 cards in HQ.
tf34 started their turn 5 with 9  and 5 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to make a run on Server 1.
originalme spends 4  to rez Mother Goddess.
tf34 jacks out.
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  and 5  to play Sure Gamble.
tf34 uses Sure Gamble to gain 9 .
tf34 discards Aeneas Informant from their Grip.
tf34 is ending their turn 5 with 17  and 5 cards in their Grip.
originalme started their turn 6 with 12 and 4 cards in HQ.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 6 with 12  and 5 cards in HQ.
tf34 started their turn 6 with 17  and 5 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  to install Street Peddler.
tf34 discards Aeneas Informant from their Grip.
tf34 discards Film Critic from their Grip.
tf34 is ending their turn 6 with 21  and 5 cards in their Grip.
originalme started their turn 7 with 12 and 5 cards in HQ.
originalme spends  to install ICE protecting Server 2 (new remote).
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 7 with 12  and 5 cards in HQ.
tf34 started their turn 7 with 21  and 5 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  and 4  to install Paperclip.
tf34 spends  to make a run on HQ.
zhw2275368 joined the game as a spectator.
originalme has no further action.
tf34 continues the run.
originalme has no further action.
tf34 uses Street Peddler to install Aumakua lowering its install cost by 1 .
tf34 spends 2  to install Aumakua.
tf34 accesses Marcus Batty from HQ.
tf34 pays 1  to trash Marcus Batty from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to make a run on HQ.
originalme
originalme
thinking
originalme has no further action.
tf34 continues the run.
originalme has no further action.
tf34 accesses Blacklist from HQ.
tf34 pays 3  to trash Blacklist from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to make a run on HQ.
originalme spends 8  to rez DNA Tracker.
tf34 spends 3  to install Black Orchestra.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Hacktivist Meeting due to damage.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Liberated Account due to damage.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Stimhack due to damage.
originalme has no further action.
tf34 continues the run.
originalme has no further action.
tf34 accesses Marcus Batty from HQ.
tf34 pays 1  to trash Marcus Batty from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 is ending their turn 7 with 5  and 1 cards in their Grip.
originalme started their turn 8 with 4 and 2 cards in HQ.
originalme spends  to install a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 8 with 3 and 2 cards in HQ.
tf34 started their turn 8 with 5  and 1 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 jacks out.
tf34 spends  to make a run on Server 1.
tf34 jacks out.
tf34 sets click to 3 (+1).
tf34 spends  to draw a card.
tf34 spends  to use Liberated Account to gain 4 .
tf34 spends  and 3  to install Data Folding.
tf34 is ending their turn 8 with 8  and 1 cards in their Grip.
originalme started their turn 9 with 3 and 2 cards in HQ.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme scores Nisei MK II and gains 2 agenda points.
originalme is ending their turn 9 with 0 and 3 cards in HQ.
tf34 started their turn 9 with 8  and 1 cards in their Grip.
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 jacks out.
tf34 spends  and 3  to install Daily Casts.
tf34 is ending their turn 9 with 5  and 2 cards in their Grip.
originalme started their turn 10 with 0 and 3 cards in HQ.
originalme spends  to gain 1 .
originalme spends  to gain 1 .
Eskimo Sniper joined the game as a spectator.
originalme spends  to gain 1 .
originalme is ending their turn 10 with 3  and 4 cards in HQ.
tf34 started their turn 10 with 5  and 2 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 spends  to draw a card.
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 jacks out.
tf34 spends  to gain 1 .
tf34 spends  and 6  to install Maw.
tf34 is ending their turn 10 with 2  and 2 cards in their Grip.
originalme started their turn 11 with 3 and 4 cards in HQ.
originalme spends  to gain 1 .
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 11 with 4  and 5 cards in HQ.
tf34 started their turn 11 with 2  and 2 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  to make a run on Server 1.
Phantom joined the game as a spectator.
originalme uses IT Department to add strength to a rezzed ICE.
originalme has no further action.
tf34 jacks out.
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 is ending their turn 11 with 7  and 5 cards in their Grip.
originalme started their turn 12 with 4 and 5 cards in HQ.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme discards a card from their HQ.
originalme is ending their turn 12 with 4  and 5 cards in HQ.
tf34 started their turn 12 with 7  and 5 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 jacks out.
tf34 spends  to use Omar Keung: Conspiracy Theorist to make a run on Archives.
originalme
originalme
hmm
originalme
originalme
thinking
originalme uses AgInfusion: New Miracles for a New World to trash the approached ICE. The Runner is now running on HQ.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme has no further action.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Career Fair due to damage.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Black Orchestra due to damage.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Stimhack due to damage.
tf34 continues the run.
originalme has no further action.
tf34 uses Omar Keung: Conspiracy Theorist to make a successful run on HQ.
tf34 accesses Obokata Protocol from HQ.
tf34 uses Film Critic to host Obokata Protocol instead of accessing it.
tf34 uses Maw to force the Corp to trash a random card from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to gain 1 .
tf34 is ending their turn 12 with 7  and 3 cards in their Grip.
originalme started their turn 13 with 4 and 3 cards in HQ.
originalme spends  to gain 1 .
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme spends  to install ICE protecting Archives.
originalme is ending their turn 13 with 9  and 2 cards in HQ.
tf34 started their turn 13 with 7  and 3 cards in their Grip.
tf34 uses Daily Casts to gain 2 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
originalme has no further action.
tf34 jacks out.
tf34 spends  to draw a card.
tf34 spends  to use Film Critic to add Obokata Protocol to their score area and gain 3 agenda points.
tf34 is ending their turn 13 with 12 and 4 cards in their Grip.
originalme started their turn 14 with 9 and 2 cards in HQ.
originalme spends  to play Fast Track.
originalme adds Nisei MK II to HQ and shuffle R&D.
originalme spends  to install a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme is ending their turn 14 with 8  and 2 cards in HQ.
tf34 started their turn 14 with 12  and 4 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to make a run on Server 2.
originalme spends 4  to rez Rototurret.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 indicates to fire all subroutines on Rototurret.
originalme uses Rototurret to trash Aumakua.
originalme uses Rototurret to end the run.
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
originalme has no further action.
tf34 jacks out.
tf34 spends  to gain 1 .
tf34 spends  to make a run on Server 1.
originalme has no further action.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 continues the run.
originalme uses Nisei MK II to end the run.
tf34 is ending their turn 14 with 4  and 4 cards in their Grip.
originalme started their turn 15 with 4 and 2 cards in HQ.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme spends  and 1  to advance a card in Server 2.
originalme scores Nisei MK II and gains 2 agenda points.
originalme is ending their turn 15 with 1  and 3 cards in HQ.
tf34 started their turn 15 with 4  and 4 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  and 5  to play Sure Gamble.
tf34 uses Sure Gamble to gain 9 .
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
originalme has no further action.
tf34 jacks out.
tf34 spends  to use Omar Keung: Conspiracy Theorist to make a run on Archives.
originalme has no further action.
tf34 continues the run.
tf34 uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
originalme has no further action.
tf34 uses Omar Keung: Conspiracy Theorist to make a successful run on R&D.
tf34 accesses an unseen card from R&D.
tf34 uses Maw to force the Corp to trash a random card from HQ.
tf34 accesses an unseen card from R&D.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to draw a card.
tf34 is ending their turn 15 with 11 and 4 cards in their Grip.
originalme started their turn 16 with 1 and 2 cards in HQ.
!originalme uses a command: /close-prompt
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 16 with 1  and 3 cards in HQ.
tf34 started their turn 16 with 11  and 4 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
originalme has no further action.
tf34 jacks out.
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to make a run on Server 1.
originalme has no further action.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
tf34 continues the run.
originalme uses Nisei MK II to end the run.
tf34 is ending their turn 16 with 4  and 4 cards in their Grip.
originalme started their turn 17 with 1 and 3 cards in HQ.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 17 with 1  and 4 cards in HQ.
tf34 started their turn 17 with 4  and 4 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
zhw2275368 left the game.
tf34 spends  to make a run on Server 1.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 jacks out.
tf34 spends  to use Omar Keung: Conspiracy Theorist to make a run on Archives.
originalme uses AgInfusion: New Miracles for a New World to trash the approached ICE. The Runner is now running on HQ.
originalme uses IT Department to add strength to a rezzed ICE.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Hacktivist Meeting due to damage.
tf34 indicates to fire the "Do 1 net damage and make the Runner lose 2 " subroutine on DNA Tracker.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Maw due to damage.
originalme uses DNA Tracker to do 1 net damage and make the Runner lose 2 .
tf34 trashes Career Fair due to damage.
originalme has no further action.
zhw2275368 joined the game as a spectator.
tf34 continues the run.
originalme has no further action.
tf34 uses Omar Keung: Conspiracy Theorist to make a successful run on HQ.
tf34 accesses Enigma from HQ.
tf34 uses Maw to force the Corp to trash a random card from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to make a run on R&D.
zhw2275368 left the game.
originalme has no further action.
tf34 continues the run.
originalme rezzes Tithonium by paying its alternative cost.
zhw2275368 joined the game as a spectator.
zhw2275368 left the game.
originalme trashes a card.
tf34 indicates to fire all subroutines on Tithonium.
originalme has no further action.
tf34 indicates to fire all subroutines on Tithonium.
originalme
originalme
hmm. won't let me click on things.
!originalme uses a command: /close-prompt
tf34
tf34
what are you trashing?
originalme
originalme
trash bo/paperclip
tf34 trashes Black Orchestra from their Rig.
tf34 trashes Paperclip from their Rig.
originalme
originalme
fc
tf34 trashes Film Critic from their Rig.
tf34 places a power counter on The Turning Wheel.
tf34 jacks out.
tf34 spends  to make a run on Archives.
originalme
originalme
I've also got a nisei in archives that should be out of the game. :)
originalme
originalme
is there a remove from game command?
tf34
tf34
haha ok
Phantom
Phantom
yup
!tf34 uses a command: /rfg
!originalme uses a command: /rfg
originalme
originalme
/close-prompt.
originalme has no further action.
originalme
originalme
still can't click on anything.
tf34 accesses Obokata Protocol from Archives.
tf34 accesses Obokata Protocol from Archives.
originalme
originalme
So don't steal the nisei :(
tf34 accesses Nisei MK II from Archives.
tf34 steals Nisei MK II and gains 2 agenda points.
!tf34 uses a command: /rfg
vslice joined the game as a spectator.
tf34 sets agenda point to 6 (+1).
tf34 sets agenda point to 7 (+1).
tf34 sets agenda point to 6 (-1).
tf34 sets agenda point to 5 (-1).
tf34 sets agenda point to 4 (-1).
tf34 sets agenda point to 3 (-1).
tf34 is ending their turn 17 with 1  and 1 cards in their Grip.
originalme sets agenda point to 3 (-1).
originalme sets agenda point to 2 (-1).
originalme started their turn 18 with 1 and 3 cards in HQ.
tf34
tf34
if you want to shuffle it back in
tf34
tf34
then i will move it to archives
tf34
tf34
if i can...
originalme
originalme
ah, not worth it.
Phantom
Phantom
you can rfg it from score pile
Phantom
Phantom
I believe
tf34
tf34
i just tried
Phantom
Phantom
really?
Phantom
Phantom
huh
Phantom
Phantom
weird
!tf34 uses a command: /rfg
originalme spends  to draw a card.
originalme spends  to install ICE protecting Archives.
originalme spends  to gain 1 .
originalme is ending their turn 18 with 2  and 4 cards in HQ.
tf34 started their turn 18 with 1  and 1 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  to draw a card.
Phantom
Phantom
well, as long as the points are correct
tf34 spends  and 4  to install Earthrise Hotel.
tf34 is ending their turn 18 with 0  and 3 cards in their Grip.
originalme started their turn 19 with 2 and 4 cards in HQ.
originalme spends  to gain 1 .
originalme spends  to gain 1 .
originalme spends  to gain 1 .
originalme is ending their turn 19 with 5  and 5 cards in HQ.
tf34 started their turn 19 with 0  and 3 cards in their Grip.
tf34 uses Earthrise Hotel to draw 2 cards.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to use Omar Keung: Conspiracy Theorist to make a run on Archives.
vslice left the game.
vslice joined the game as a spectator.
originalme has no further action.
tf34 continues the run.
originalme has no further action.
tf34 uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
tf34 uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
tf34 uses Omar Keung: Conspiracy Theorist to make a successful run on R&D.
tf34 accesses an unseen card from R&D.
tf34 uses Maw to force the Corp to trash a random card from HQ.
tf34 accesses an unseen card from R&D.
tf34 accesses an unseen card from R&D.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 is ending their turn 19 with 6  and 5 cards in their Grip.
originalme started their turn 20 with 5 and 4 cards in HQ.
originalme spends  to draw a card.
originalme trashes a card from their the root of Archives.
originalme spends  to install ICE protecting Archives.
originalme spends  and 5  to play Hedge Fund.
originalme uses Hedge Fund to gain 9 .
originalme is ending their turn 20 with 9  and 4 cards in HQ.
tf34 started their turn 20 with 6  and 5 cards in their Grip.
tf34 uses Earthrise Hotel to draw 2 cards.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to use Omar Keung: Conspiracy Theorist to make a run on Archives.
originalme spends 2  to rez Cortex Lock.
tf34 indicates to fire the "Do 1 net damage for each unused memory unit the Runner has" subroutine on Cortex Lock.
originalme uses Cortex Lock to do 6 net damage.
tf34 trashes Street Peddler, Aeneas Informant, Liberated Account, Maw, The Turning Wheel, Daily Casts due to damage.
originalme has no further action.
tf34 continues the run.
tf34 uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
originalme has no further action.
tf34 uses Omar Keung: Conspiracy Theorist to make a successful run on HQ.
tf34 accesses Tech Startup from HQ.
tf34 pays 1  to trash Tech Startup from HQ.
tf34 accesses Enigma from HQ.
tf34 uses Maw to force the Corp to trash a random card from HQ.
tf34 places a power counter on The Turning Wheel.
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 is ending their turn 20 with 11 and 1 cards in their Grip.
originalme started their turn 21 with 7 and 2 cards in HQ.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme spends  to draw a card.
originalme discards a card from their HQ.
originalme is ending their turn 21 with 7  and 5 cards in HQ.
tf34 started their turn 21 with 11  and 1 cards in their Grip.
tf34 uses Earthrise Hotel to draw 2 cards.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 spends  to gain 1 .
tf34 is ending their turn 21 with 18 and 3 cards in their Grip.
originalme started their turn 22 with 7 and 5 cards in HQ.
originalme spends  and 3  to play Celebrity Gift.
originalme sets credit to 5 (+1).
originalme sets credit to 6 (+1).
originalme sets credit to 7 (+1).
originalme sets credit to 8 (+1).
originalme sets credit to 9 (+1).
originalme sets credit to 10 (+1).
originalme sets credit to 11 (+1).
originalme sets credit to 12 (+1).
originalme sets credit to 13 (+1).
originalme sets credit to 14 (+1).
originalme sets credit to 15 (+1).
originalme sets credit to 14 (-1).
originalme
originalme
hand is batty, excalibur, tech startup, medical fundraiser and vanilla
tf34
tf34
k
originalme spends  to use IT Department to add 1 counter.
originalme is ending their turn 22 with 14  and 5 cards in HQ.
vslice left the game.
tf34 started their turn 22 with 18  and 3 cards in their Grip.
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 uses Data Folding to gain 1 .
tf34 spends  to draw a card.
tf34 spends  to draw a card.
tf34 spends  to make a run on Server 1.
tf34
tf34
wut
originalme
originalme
what!
tf34
tf34
haha
originalme moves a card to HQ.
tf34 moves Black Orchestra from their Heap to Grip.
tf34 sets click to 2 (+1).
Phantom
Phantom
that's a new one
tf34 spends  and 3  to install Black Orchestra.
tf34 jacks out.
tf34 sets click to 2 (+1).
originalme sets click to 1 (+1).
originalme spends  to install ICE protecting Server 1.
originalme spends 4  to rez Mother Goddess.
originalme sets credit to 11 (+1).
originalme sets credit to 12 (+1).
originalme sets credit to 13 (+1).
originalme sets credit to 14 (+1).
tf34 spends  to make a run on Server 1.
originalme
originalme
damn. It's strength 11.
originalme has no further action.
tf34
tf34
ok
!originalme uses a command: /counter 6
Phantom left the game.
tf34
tf34
not working?
originalme
originalme
and that doesn't work either.
tf34
tf34
yeah game broken
tf34
tf34
this is a problem
originalme concedes.
tf34 wins the game.
tf34
tf34
yeah we gotta end it i think
tf34
tf34
too bad
originalme
originalme
Most of my wincons are in the bin anyways.
tf34
tf34
was interested to see how it played out
originalme
originalme
fun game though
tf34
tf34
yup
tf34
tf34
thx for the game
Eskimo Sniper left the game.
originalme
originalme
u2
tf34 left the game.

**Comment by danhut** [comment]
Do you recall why you trashed a card when rezzing Tithonium? I wonder if this broke something.

tf34 spends to make a run on R&D.
originalme has no further action.
tf34 continues the run.
originalme rezzes Tithonium by paying its alternative cost.
**originalme trashes a card.**
tf34 indicates to fire all subroutines on Tithonium.
originalme has no further action.

**Comment by agileminor** [comment]
That is me trashing the Nisei for the Tithonium alternate cost.

What I can't remember is whether it wouldn't let me forfeit the Nisei for the Tithonium cost, and therefore I manually trashed it, or whether I manually trashed it accidentally instead of clicking on it to forfeit it. I think it was the first, but I honestly can't remember now.

**Comment by danhut** [comment]
I could not reproduce this sorry,  Would need more exact details or no fix possible.  There must be some other non obvious trigger.

What I tried to get your exact log
1/ Score Nisei
2/ Attempt to rez Tithonium
3/ Answer Yes to question on if I want to pay alternate cost
4/ Drag the Nisei from the scored area to discard rather than selecting it as the forfeit target

If it happens again I would suggest a screen shot at the point when you are meant to select the agenda to forfeit.
