### ISSUE TITLE
Chat channel for russian speakers

### ISSUE THREAD

**Issue by Deomind** [mtgred/netrunner#3034]
I believe russian-speaking part of Netrunner community has grown large enough to have separate channel. I propose channel name "russian-speakers" to hint that it is not only for people from Russia itself, but also from all other countries where russian language is common.

**Comment by danhut** [comment]
Can you provide the name for the channel please?  We have localised versions already which are not the "Anglo" way of saying the language name

Do we use one of these?  Excuse my ignorance!

#русский
#russkiy

**Comment by Deomind** [comment]
Hi,
#русский will do. It's language name, people who speak it will understand
it.

2018-02-18 14:17 GMT+03:00 Dan Hutchins <notifications@github.com>:

**Comment by ParasitePromo** [comment]
Thank you so much from the Russian community!
