### ISSUE TITLE
Acacia trash cannot be prevented by LLDS Energy Regulator

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#3035]
I believe that the trashing of Acacia can be prevented after using its effect, as gaining the money is not conditional on the trash.

However, when Acacia is used with LLDS Energy Regulator installed no prompt is displayed to save it.

**Comment by nealterrell** [comment]
I agree with this reading of the rules. It would be the opposite if Acacia read "you may trash Acacia to gain...", but as it is written I believe the trash is _not_ unpreventable.
