### ISSUE TITLE
Aumakua + Find the Truth/Neutralize all threaths interaction

### ISSUE THREAD

**Issue by RyanPatrick26** [mtgred/netrunner#3039]
I've had this happen a couple of times now
with amuakua, neutralize all threats and find the truth installed, if you access a card with a trash cost, and use find the truth to look at the top card of R&D, if the card you access would be force trashed, then you still get the virus counter on aumakua

**Comment by butzopower** [comment]
Was able to reproduce this with just Aumakua and Neutralize All Threats, I don't think Find The Truth is playing a part of this.  It looks like `:force-trash` doesn't associate the `:did-trash` flag with the run, as there doesn't seem to be a run to associate it with.  I'm not sure why there's no run, possibly Neutralize All Threats is trashing the card after the run ended?

I've created a branch in my fork with the code so far if anyone has advice: https://github.com/butzopower/netrunner/commit/3fb99a839cd1865e5960f527539912cb39dc32a7
