### ISSUE TITLE
using hayley to install extra program after using london library yields extra text

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#304]
From the game log:
Balkmeister uses London Library to host Overmind.
Balkmeister installs Overmind on London Library at no cost.
Balkmeister uses Hayley Kaplan: Universal Scholar to install Chameleon.
Balkmeister installs Chameleon.
Balkmeister uses Chameleon to choose {:faction "Shaper", :factioncost 3, :setname "The Underway", :agendapoints nil, :influencelimit nil, :number 69, :zone (:hand), :advancementcost nil, :cid 191551, :type "Program", :title "Chameleon", :uniqueness false, :strength 3, :baselink nil, :code "08069", :side "Runner", :cost 2, :memoryunits 1, :trash nil, :subtype "Icebreaker", :minimumdecksize nil, :text "When you install Chameleon, name sentry, code gate or barrier.\r\nAdd Chameleon to your grip when your turn ends.\r\n1: Break a subroutine of the named subtype."}.

**Comment by Balkmeister** [comment]
It also didn't give me the option to choose sub type

**Comment by JoelCFC25** [comment]
Tested this exact scenario just now and it worked for me, including the subtype choice.

**Comment by JoelCFC25** [comment]
Closing this for now. If it happens again and you can reliably reproduce it, open a new issue.
