### ISSUE TITLE
Obelus + Information Sifting doesn't draw you cards

### ISSUE THREAD

**Issue by ouroboros8** [mtgred/netrunner#3048]
After Info Sifting with Obelus down you should draw cards equal to the size of the pile you accessed.

**Comment by danhut** [comment]
Fixed.  Will need some work if other replacement access effect cards provide multi-access.  Right now it looks like Obelus would work for Info Sifting & Hades Shard only.  I cannot recall if there are others.  Feel free to comment here or open new defects for those.
