### ISSUE TITLE
hosted on leprechaun icebreaker's strength do not reset

### ISSUE THREAD

**Issue by javel-by** [mtgred/netrunner#305]
Install Leprechaun, use it to install & host icebreaker on it
Make run, boost icebreaker's strength
Ending run, or transiting to next piece of ice does not reset icebreaker's strength
(issue encountered with Dagger and Refractor)

**Comment by nealterrell** [comment]
This applies generally to all icebreakers hosted on cards and is fixed in #298, which is awaiting deployment. Thanks for the report!
