### ISSUE TITLE
Game freezes after accidentally Installing Ice while resolving Priority Construction 

### ISSUE THREAD

**Issue by lambertwang** [mtgred/netrunner#3050]
I encountered this bug while playing Priority Construction.

1. Play Priority Construction
2. Select an ice
3. Install the ice normally (without using the priority construction prompt)
4. The game freezes up.

**Comment by danhut** [comment]
Fix presents the freezing when you do this (as per similar such as Replanting).  Still lets you do the normal install - as per other similar operations.
