### ISSUE TITLE
TESTING SERVER: Game locks after scoring agendas

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#3058]
In both games we played, the corp would score their first agenda, and then the game would lock. The runner sees the "Waiting for Corp to resolve agenda-scored triggers" message, and nothing would happen for the corp (agenda remained in server, no points were allotted, and the corp could end turn). At this point the game just hung.

The first time it was a Palana deck scoring Obokata, and the second time it was an Asa deck scoring Vitruvius. The runner was Adam both times, with RNGKey installed.

**Comment by nealterrell** [comment]
Thanks, all cleared up!
