### ISSUE TITLE
 [Test server] Unable to select deck containing SSL Endorsement in game lobby

### ISSUE THREAD

**Issue by JensLoveCarlsson** [mtgred/netrunner#3060]
**What I tried to do**
I was in a game lobby (that I hosted) and selected a corp deck containing the two DtWN cards SSL Endorsement and NGO Front. The deck was marked as "Tournament Legal" in the list of available decks. Decklist, for referernce: https://netrunnerdb.com/en/decklist/48382/proposing-always-advance

**What happened**
The deck-selector disappeared, like normal, but no deck was selected. I could click "select deck" again, there was no warning message and the lobby did not behave oddly in any way after this.

**Additional information**
Replacing the single copy of SSL endorsement with Priority Requisition from the deckbuilder allowed me to select the deck and start the game, without having to exit the lobby inbetween.

**Comment by nealterrell** [comment]
Fix on test server. Thanks!
