### ISSUE TITLE
[Test Server] Hasty Relocation + Jinja City Grid locked things up.

### ISSUE THREAD

**Issue by dinte** [mtgred/netrunner#3062]
Corp played Hasty Relocation with Jinja City Grid installed. I wasn't the corp, but apparently they got caught in some sort of loop between installing and replacing cards. In any case, chat froze up and we couldn't continue.

**Comment by butzopower** [comment]
I played Hasty Relocation and Jinja City Grid fired, and it alternated between offering to install a card via Jinja, and putting a card from HQ onto R&D.  The list of cards that could be added to R&D included the ICE that I had installed on the Jinja server, and when I choose one of those ICE, the game crashed.
