### ISSUE TITLE
[[Test server]] Bacterial Programming posts card swaps to chat

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#3064]
Looking at the agenda text, I think the runner should not know the cards that are re-arranged but it looks like the code is set to reveal the card information into the chat. I only tested this quickly with a corp deck against a blank runner but you can see the details of the swaps are being sent to the chat box.

I'm not the initial reporter but I offered to submit the issue in the reporter's stead.

![image](https://user-images.githubusercontent.com/35308609/36003990-551e81c8-0d28-11e8-83fa-22cc3f08de53.png)

**Comment by hiddenaway1** [comment]
Another picture, just confirming that the trash to archives and add to HQ both report the cards to the chat. However, the re-arranging of the cards is fine.

![image](https://user-images.githubusercontent.com/35308609/36004193-3c549fc8-0d29-11e8-96c2-d09d2e345cde.png)

**Comment by Quarg** [comment]
I just want to mention, that according to existing rulings, we know that technically, both players should know where each card goes, even if they don't know what that card was. (As with Architect and Indexing, and this is why Bamboo Dome specifies that it is secret.)

**Comment by nealterrell** [comment]
Thanks, I believe that was debug information during development.

**Comment by nealterrell** [comment]
@Quarg so the appropriate message would be "add cards 1, 3, 7 to HQ, trash card 2, and rearrange cards 4, 5, 6"?

**Comment by jwarwick** [comment]
Yup, those are clearly debugging statements some moron programmer left in the code...
