### ISSUE TITLE
Aeneas Informant + Salsette Slums

### ISSUE THREAD

**Issue by sdfkjhsekfheknb** [mtgred/netrunner#3065]
At the moment it lets you use Aeneas Informant when you RFG cards with Salsette. In the UFAQ it says this should not be allowed. Might be good to fix.

**Comment by butzopower** [comment]
Looks like Maw isn't supposed to trigger either according to UFAQ.

**Comment by yads** [comment]
Salsette has since been errata'd to "Once per turn, you may pay the trash cost of a card you access that is not in Archives to remove that card from the game." You're now no longer trashing the card to activate Slums so it works with both Aeneas and Maw. The UFAQ entry is no longer correct.

**Comment by yads** [comment]
UFAQ has now been updated to the correct interaction.

**Comment by danhut** [comment]
Great - closing this.
