### ISSUE TITLE
Recronstruction Contract #21020 triggers also on Net-Damage...

### ISSUE THREAD

**Issue by ANR-PeterPan** [mtgred/netrunner#3068]
... also its "may", so perhaps a prompt to ask?
See below
![image](https://user-images.githubusercontent.com/24223024/36052578-8dc1d61c-0dee-11e8-8bdc-b99ed132c505.png)

**Comment by nealterrell** [comment]
Thanks. We'll keep it automatic until there is a valid reason to not want the counter.

**Comment by nealterrell** [comment]
Duplicate of #2982.
