### ISSUE TITLE
Leela Patel + Research Grant

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#3069]
Leela Patel and Research Grant's abilities seem to be slightly mistimed at the moment. When Research Grant was scored, I was able to select another copy of research Grant and place advancement counters on it, but the runner was given the option to bounce before the second Research Grant was scored, specifically allowing them to erroneously bounce the Second Grant which should have been scored already. I would guess that Leela needs some code to wait until all the research grants are scored, then bounce multiple cards before resolving. 
![leela grant issue](https://user-images.githubusercontent.com/22971454/36058180-20f60b30-0de8-11e8-81fa-143c65112c95.PNG)

**Comment by nealterrell** [comment]
So there wasn't actually an issue with Leela here... Research Grant is just broken. It's supposed to automatically score the second copy, but is only placing advancement tokens on it. Will have a fix shortly.
