### ISSUE TITLE
BUG: Multiple Skorpios Dialog 

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3074]
> ABC spends  and 2  to play Leave No Trace.
> ABC uses Leave No Trace to make a run and derez any ICE that are rezzed during this run.
> XYZ has no further action.
> ABC continues the run.
> XYZ has no further action.
> ABC accesses an unseen card from R&D.

XYZ clicked Skorpios Identity twice because the dialog was slow to open.

> ABC spends [click] to play En Passant.
> XYZ uses Skorpios Defense Systems: Persuasive Power to remove Leave No Trace from the game. (Another dialog was waiting beneath)

XYZ clicked cancel on the second dialog prompt and it disappeared.

The runner still had the "Waiting for Corp to use Skorpios' ability" prompt and cannot do player actions.

Tried reloading the runner, still there. Then tried reloading corp, still there. Tried reducing clicks on the runner to 0, did not change. 

Seems as if the ability for the second dialog to cancel was removed by executing the first dialog while the second one was waiting beneath. 

I've often had two dialogs stacked because I clicked a card multiple times before the dialog loaded. Suggested fix is to prevent multiple of the same dialogs from presenting if one is already active.

**Comment by Eric-Fletcher** [comment]
Note that the runner can use /close-prompt to get past this.

**Comment by msbeck** [comment]
Noted. Average Joe may never realize/know of this option, but I'll remember now!

**Comment by danhut** [comment]
I added a means to have this only active once.  Similar code would need to be added for other cards where "too fast clicking" causes you a problem.  Suggest to raise a defect if you find more.  Or just chill out on the click speed ;)

**Comment by msbeck** [comment]
Can you add the functionality to also not show this dialog to runners?

I clicked it a second time after using it once previously on my turn. I did not get a prompt, but the runner did. He got a stack of them as well and had to /close-prompt many times.

**Comment by msbeck** [comment]
@nealterrell suggest re-opening per above. This implementation only fixed corp side, not runner's.

**Comment by danhut** [comment]
Fixed via #3218
