### ISSUE TITLE
Issue: Dr Lovegood interaction with Find the Truth's "end of turn" trigger resolving unintuitively with Safety First's.

### ISSUE THREAD

**Issue by Divadus1** [mtgred/netrunner#3078]
Using Dr Lovegood to blank Find the Truth for the turn leads to it being unblanked at the end of the turn (as is appropriate); however, Dr Lovegood's "end of turn" 'unblank' trigger resolves before Safety First's "end of turn" draw trigger. Consequently, the Corp sees the Runner's drawn card when they should not. Aside from "mind games!!1!1", there is no reason the Runner would choose to allow their triggers to resolve in this fashion.

**Comment by danhut** [comment]
Two ways to handle this I guess
1/ Add a new event :runner-turn-ends-priority
2/ Add extra logic to existing function `trigger-event` and a new flag called 'priority' which is resolved first

The first is simpler, the latter probably more consistent

**Comment by danhut** [comment]
A thought on this.  If Dr. Lovegood always 'unblanked' last - could that cause problems if cards other than Find The Truth were targetted?  We could force Lovegood to always unblank as the final thing of a turn quite easily - other approaches would require the user to do a bunch of extra clicking.
