### ISSUE TITLE
Gang sign does not stack with HQ Interface

### ISSUE THREAD

**Issue by darlingsensei** [mtgred/netrunner#308]
The corp scoring yields only one access when Gang Sign and HQ interface are present. Gang sign also sometimes results in a "Jack Out or Continue" prompt on the corp's turn.

**Comment by JoelCFC25** [comment]
My thought on this today...it could be as simple as how the access is being done. Currently Gang Sign does: `:effect (req (let [c (first (shuffle (:hand corp)))`

But we could simply do it the same way the `(defn access :hq` works in `core.clj`. The default for `:hq-access` is 1, and simply gets incremented when you install an HQ Interface. 

So something in Gang Sign along the lines of: 
`:effect (req (let [c (take :hq-access (shuffle (:hand corp)))]`

...ought to give as many accesses as desired from HQ while ignoring any upgrades, right? However, we're still left with the problem of ordering simultaneous effects if you have multiple Gang Signs and/or multiple HQ Interfaces.

**Comment by nealterrell** [comment]
That feels like it should work, even for multiple interfaces, if you turn the `let` into a `doseq`. But you're right, it won't solve multiple Gang Signs... You'll get the second access procedure while the runner is resolving prompts to trash, so the second access will use the same card options as the first.

**Comment by JoelCFC25** [comment]
Would there be a way to put logic into Gang Sign to first count how many Gang Signs are installed, then "for each" do <insert access code here>?
