### ISSUE TITLE
Updating Deck Builder UX

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3080]
**Background**
Howdy guys. I'm new to the project and I want to learn how everything is set up and eventually be helpful in getting new card packs up and contributing with other things. I'm coming from C#/C++/AS3/Python educational game development and asset pipeline work so I'm also bringing myself up to speed with web stuff. I have experience with UX as well, so I thought some UX/UI work would be the easiest thing for me to tinker with to feel my way through the code.

**Topic**
I always seem to mess up in the deck builder when editing cards. I click the "-" button trying to increase the number of cards from 1 or 2, only to realize I was clicking on the "-" and not the "+".

**Context**
![screen shot 2018-02-13 at 12 24 01 pm](https://user-images.githubusercontent.com/2982395/36175455-1c56eb40-10d5-11e8-8a26-9e15d4c1fa9a.png)
When this happens, the card goes to 0 and then is removed from the list. I then have to go back to the Add Cards section to search and then re-add it.

This frustrates me a bit, so I thought I'd see what I could to do improve the deck building experience. This is certainly not the only reason to make a change, but it triggered a desire to look deeper into how the UI was set up and the User Experience behind it.
____
### UX Patterns
**Pattern A**
In the west, the reading pattern is left to right, and numbers progress from lower to higher from left to right as well. This is counter to the order of the buttons on the Deck Builder.

![screen shot 2018-02-13 at 3 53 19 pm](https://user-images.githubusercontent.com/2982395/36175744-1dc0fc7c-10d6-11e8-999e-e4b1cf07fb57.png)

**Potential Improvement**
I think changing the order to have the decrement "-" button on the left and the increment "+" button on the right would conform better to this standard.
____
**Pattern B**
Secondly, the number of cards is slightly dissociated with the input buttons. The left button is far removed from the number it is modifying. This creates an odd association where the right button is more strongly associated with the value it is modifying than the left. During use, this can also cause a user to not catch that they are changing the number in ways they are not intending to per Pattern A.

![screen shot 2018-02-13 at 3 53 27 pm](https://user-images.githubusercontent.com/2982395/36175932-a765004a-10d6-11e8-9b92-f22521aa8da1.png)

**Potential Improvement**
I believe the number being placed between the two buttons to create a natural flow of increment and decrement as well as provide equal association with the buttons for the number would be beneficial.

![screen shot 2018-02-13 at 3 53 05 pm](https://user-images.githubusercontent.com/2982395/36175800-472debec-10d6-11e8-86d6-c530955229dc.png)
____
**Summary**
Overall, I believe this follows UX patterns a bit more closely and creates a more pleasant interaction and sense of aesthetics for the interface. The following would be the result of the changes:
 
![screen shot 2018-02-13 at 4 18 42 pm](https://user-images.githubusercontent.com/2982395/36176862-9e28ea8e-10d9-11e8-9c7b-778e69b30d82.png)

I realize that many people may just copy pasta their decks in from other places where they store them and not use these buttons, but as a visual person I personally like to use jnet to make my decks so I use these buttons a lot.

What do you guys think? I have tinkered with the code to create these mockups, so I could submit a pull request if you guys feel like it looks good.

**Comment by danhut** [comment]
I like the changes.  Nice one.

**Comment by nealterrell** [comment]
These are insightful suggestions. Let's see a PR!

**Comment by msbeck** [comment]
Great. Can you help me with my first time PR? I've never used GitHub as a programmer on a team and I've always just used repos as the owner for backups.
![screen shot 2018-02-13 at 4 47 52 pm](https://user-images.githubusercontent.com/2982395/36178203-c0ae80f6-10dd-11e8-8252-1dd3f560d08d.png)

I'm assuming I submit a PR to dev, yes?

When I switch to the dev branch-
![screen shot 2018-02-13 at 4 33 24 pm](https://user-images.githubusercontent.com/2982395/36178235-d34df106-10dd-11e8-939c-94ecc1678fdd.png)

My Uncommitted Changes no longer appear in the queue.
![screen shot 2018-02-13 at 4 50 25 pm](https://user-images.githubusercontent.com/2982395/36178303-06bc4146-10de-11e8-951c-b4293cb8f7e3.png)

**Comment by nealterrell** [comment]
You should commit your changes to a new branch of your personal fork of the project. Then sync/push that branch to GitHub. Once you've done that, GH web UI should show a "create PR" button when viewing the project home page.

**Comment by msbeck** [comment]
Do I need authentication to do so?

**Comment by msbeck** [comment]
Got it: https://github.com/mtgred/netrunner/pull/3081

TYVM

**Comment by JoelCFC25** [comment]
A very sensible, well-reasoned change. 🍺

**Comment by Eric-Fletcher** [comment]
::frown::
Verbally, the association is "plus or minus" and in most applications the "first" button is the "add more" (e.g. insert comes before delete in Excel, Confluence, Jira)

Putting the number between the buttons seems ok, though it hurts the ability to study the list.

A better solution to the originally expressed issue would be retaining 0 count cards in the list until the deck changes are saved.

**Comment by Saintis** [comment]
The Net Deck has it as minus button to the left of the plus button, so I'm happy with -/+ order. 

I do agree that having the numbers between the buttons feels a bit disruptive, but I'm not feeling strongly about it.

I like the idea of keeping "0" count cards in until save.

An additional idea is to have NRDB style 0/1/2/3 style radio buttons, although that might raise the question of screen space and be a general CSS nightmare.

**Comment by msbeck** [comment]
![screen shot 2018-02-15 at 11 38 00 am](https://user-images.githubusercontent.com/2982395/36271639-cac7f3f2-1244-11e8-8054-ec1c81b2a4e8.png)
> The Net Deck has it as minus button to the left of the plus button, so I'm happy with -/+ order.

Deck Builder for Netrunner (Android) also shares this same order. 

![screen shot 2018-02-15 at 11 44 56 am](https://user-images.githubusercontent.com/2982395/36271961-ba0dac86-1245-11e8-9437-b1946b5e33ff.png)

They have the counts in between the buttons as well, for symmetry, which is another good reason for our numbers to be in the middle that I did not mention in my original case.
> An additional idea is to have NRDB style 0/1/2/3 style radio buttons, although that might raise the question of screen space and be a **general CSS nightmare**.

I agree with it being a CSS trouble, especially for the cards which you can have more than 3 of. A few edge cases perhaps, but would be messy ones. Also, it would likely take up **more** horizontal and even vertical space. Imported cards with long names will be squeezed even further, especially those which already are.

![screen shot 2018-02-15 at 12 34 00 pm](https://user-images.githubusercontent.com/2982395/36274171-8cea3b14-124c-11e8-922c-6ba3c1bdc2df.png)
![screen shot 2018-02-15 at 12 35 02 pm](https://user-images.githubusercontent.com/2982395/36274232-b0067630-124c-11e8-809a-73c34b2c8c91.png)


> Verbally, the association is "plus or minus"

Colloquial phrases don't have bearing on web interactions when it comes to UX decisions.

> and in most applications the "first" button is the "add more" (e.g. insert comes before delete in Excel, Confluence, Jira)

Though easily mistaken as similar, an insert and delete function does not share strong analogies with incrementing and decrementing. Insert and delete in the contexts of spreadsheets confers the sense of placement, reorganization, and position. The interaction under consideration is a number increasing or decreasing.

Also, insert and delete generally appear as menu items, among many others, and usually as a second click after a right click; thus they are distanced quite far from being likened to consecutively clicking a small button to increment or decrement a numeral.

Finally, excel does not use the analogy you are asserting in other parts of their program.

![screen shot 2018-02-15 at 12 26 10 pm](https://user-images.githubusercontent.com/2982395/36273837-7130feb8-124b-11e8-9ff8-293effaad15c.png)


Increasing the zoom is accomplished by clicking the "+" on the right and vise versa.

**Comment by JoelCFC25** [comment]
Merged!

**Comment by prozz** [comment]
i dont think this is a good change. just a heads up.

**Comment by JoelCFC25** [comment]
You're not alone, but I seriously doubt it will be reverted. Everyone has been conditioned to these UI components arranged the opposite of just about everything else similar to it. You'll get used to it.

**Comment by prozz** [comment]
for me its not about +/- placement, i can get used to whatever order u plan to put it. 
it's about reading decklist in edit mode which is very troublesome:
+ - 3 injects  
not
3 [blablabla] injects
