### ISSUE TITLE
The Gauntlet not activating on HQ runs when Crisium Grid active.

### ISSUE THREAD

**Issue by Zerothmaxima** [mtgred/netrunner#3082]
The wording from The Gauntlet should trigger on card accesses, not on successful run.

**Comment by danhut** [comment]
You are right this currently fires on success- does that cause a problem in terms of game play?

**Comment by Zerothmaxima** [comment]
Thanks for looking into it!

Yes, Gauntlet specifies on access, so run success as defined by Crisium
should not impact its trigger. Maybe I'm not aware of a command to enable
multiaccess on runs, that could be a substitute. I could run this by Jako
if we need confirmation, but the language on the cards seems pretty clear.

**Comment by danhut** [comment]
Makes sense - thanks for the reasoning - it helps understand the situation.  Text is clear - just implementation not.
