### ISSUE TITLE
Installed Surfer on an ice, then it disappeared from the game.

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#3084]
Running a Wu deck with Egret, Brahman and Surfer. Somehow installed Surfer **on** a Barrier. When I used it, it worked properly but then vanished from the game board.

**_Other oddities_**
When the incident occurred, I had 7 MU total. Brahman + Surfer = 3 MU. Yet, after surfer disappeared, it said I had 3 MU left.

**Comment by nealterrell** [comment]
You'll need to describe exactly how Surfer was installed on an ice...

**Comment by mcalvo** [comment]
I attempted to use Surfer. It gave me a prompt to click on the ice was attempting to swap. I clicked on the barrier I was encountering at the time (IP Block). It installed onto the IP Block, as if it were an Egret.

**Comment by JoelCFC25** [comment]
> I clicked on the barrier I was encountering at the time (IP Block).
Surfer prompts you to select a piece of ICE *before or after* the ICE you are currently encountering. I'm surprised the targeting logic as currently written would even give a response if you clicked on the ICE you're encountering--it shouldn't do anything at all. Very odd.

**Comment by JoelCFC25** [comment]
Update: I just tried this, and as I had surmised, after clicking Surfer to use its ability, and clicking the barrier I was currently encountering, there is no response. Nothing happens until I click the next innermost piece of ICE.

**Comment by NoahTheDuke** [comment]
I suspect this has something to do with the `move` logic as is seen in #3932, #3832, #3808, etc. All has to do with ice being moved and tricky stuff happening with the `:hosted` logic.
