### ISSUE TITLE
IPO does not get added to deck when pressing enter in deck builder

### ISSUE THREAD

**Issue by Tengfred** [mtgred/netrunner#3087]
Typing exactly "IPO" in the Card name box under Add cards, and then pressing enter, does not add 3 IPO to deck. Instead it selects "shipment from mirrormorph", so that pressing enter again adds 3 of those to deck.
Typing e.g. "ipo" instead auto-completes to IPO and adds 3 IPO after two presses of enter.
Adding an exact match of another card (e.g. "Aiki") adds 3 copies after one press of enter.

**Comment by JoelCFC25** [comment]
For problematic card names (especially those with diacritics), typing directly into the large Decklist box is much more effective than using the Add Cards dialog. For example: 

"3 ipo"  adds 3 IPO
"3 r&" adds 3 R&D Interface
"3 ifr" adds 3 Şifr

**Comment by Zerothmaxima** [comment]
Yeah for some reason "ipo" works, but "IPO" does not.
