### ISSUE TITLE
Replicator vs. Housekeeping order of activation

### ISSUE THREAD

**Issue by Marimbist11** [mtgred/netrunner#309]
Opponent has Housekeeping active
Play Replicator or another hardware with Replicator out
The Housekeeping prompt activates before the Replicator prompt, causing Runner to discard a card before receiving their Replicated card, which Runner may want to discard for Housekeeping instead.

**Comment by nealterrell** [comment]
Thanks for the report. This is related to #189 in that we don't have a good way to manually resolve multiple triggers during the same event. Ideally we would present a list of all cards that want to respond to the event and then let the player choose their order, but that is going to be difficult.
