### ISSUE TITLE
Can't use Jeeves click

### ISSUE THREAD

**Issue by AjarKeen** [mtgred/netrunner#3091]
Jeeves gains me a click as expected, but for the last ~week, I can't click to play cards from my hand after gaining the Jeeves click.

For Operations, nothing happens.

For installables, the menu comes up, but when I choose an install location, nothing happens.

Sometimes, even the basic action buttons don't work with a Jeeves click. When they do, I can manually click for a credit, end my turn, add a click and then play my card... but over time, this seems to mess up the game state until we eventually can't fix it anymore.

Sorry I can't be more specific than that, but something is definitely wrong with Jeeves.

**Comment by danhut** [comment]
We have good test coverage for Jeeves and I tried to reproduce this - but no good.  I would suggest you take a screenshot next time, and also capture the logs.  There must be something complex going on I don't know about.

**Comment by nealterrell** [comment]
Fixed in #3115
