### ISSUE TITLE
Deck name styles are broken in game lobby

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#3092]
The styles for deck names seem to be broken (they lack the color they had before). 

Randomly had my inspector open, and I noticed that the deck class had `class="[Object object]"`.

<img width="381" alt="broken-deck-styles" src="https://user-images.githubusercontent.com/2737888/36365744-2a5487f0-154b-11e8-8e55-9a90866e4374.png">

**Comment by danhut** [comment]
Something to do with server side deck validation changes I guess?   Especially this function in deckbuilder name space `deck-status-label`

**Comment by jwarwick** [comment]
Just pushed some fixes to server side deck validation. Might see if that helps.
