### ISSUE TITLE
Advanced Assembly Lines installs Jua from HQ, prompt doesn't go away

### ISSUE THREAD

**Issue by hencook** [mtgred/netrunner#3093]
The target icon prompts me to select a card from HQ. I select Jua. The prompt won't go away. Upon entering a /close-prompt command, it was temporarily solved... until I installed a DBS, and when DBS asked me to bottom a card, DBS instead performed Advanced Assembly Lines's trash ability.

**Comment by danhut** [comment]
I cannot reproduce this.  If it happens again can you take a screen shot and capture the game logs?  Nothing can be done right now without more to work from.

**Comment by hencook** [comment]
I was able to reproduce.  

This time the sequence was:
DBS is installed and rezzed.
Install AAL.
Play hedge fund; can't.

![weird](https://user-images.githubusercontent.com/35521586/36393277-863e08ba-1574-11e8-80f4-c47ff3caa262.jpg)
![weird2](https://user-images.githubusercontent.com/35521586/36393283-88316414-1574-11e8-9c05-b777107ec4bc.jpg)
![weird3](https://user-images.githubusercontent.com/35521586/36393288-89a09482-1574-11e8-93c3-27777aafff35.jpg)

**Comment by hencook** [comment]
r00tSunday Feb 18th - 12:49
Yes, lots of bugs
r00tSunday Feb 18th - 12:49
Advanced Assembly Lines and Daily Business Show

^another user getting hit by this

**Comment by danhut** [comment]
Thanks.  I believe DBS just got its code changed - so makes sense we have a new problem ;)

**Comment by nealterrell** [comment]
I believe Jeeves was the cause of this.
