### ISSUE TITLE
Crisium grid does not prevent auto-triggering run completion abilities

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#31]
Certainly Medium and Datasucker still gain tokens when running against a server with Crisium grid.  I suspect that all other auto-completion-checking cards do, too (Dirty Laundry, Security Testing, Nerve Agent, etc.)

**Comment by qmsm** [comment]
Just had this with Gabriel claiming his credits. Assume Crisium isn't implemented?

**Comment by JoelCFC25** [comment]
Implemented at #483.
