### ISSUE TITLE
Cant log in, even after password-change

### ISSUE THREAD

**Issue by ANR-PeterPan** [mtgred/netrunner#3100]
normally i got automaticly logged in using Chrome.
Now i have to login, but  I always get an "Invalid login or password".
Even resetting Password via email-Link didnt work.
Username : PeterPan

**Comment by Saintis** [comment]
Logins are now case-sensitive, see #3095. Are you using the correct case?

**Comment by ANR-PeterPan** [comment]
Thx for the hint, problem was the Login-Nick :)
