### ISSUE TITLE
Game starts with a client thinking a run has initiated

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#3101]
Sometimes starting a game will have one client display a run has initiated, and the game will not start till that player uses the "/end-run" command. (To be specific, it hangs after players have accepted starting hands)

I'm not sure the exact sequence to reproduce, but I think it happens if you are spectating a game that ends mid-multi access and then you start a new game.

**Comment by danhut** [comment]
Seems to have happened to a couple of people though no clue why..

**Comment by Saintis** [comment]
Issue #3322 seems to suggest this happens when the previous game ended or was left with the player in question still in a run on a server.
