### ISSUE TITLE
logging in

### ISSUE THREAD

**Issue by abaegaeial** [mtgred/netrunner#3102]
I have had my password and username saved on jinteki.net for about a year. I recently created an account on jigoku for L5R, using the same username and password. A couple of days after I created the account, I tried to log in (with the username and password I had saved, as well as by typing them in manually), but was unable to access my account or receive a reset email through that site. As a result, I tried resetting my passwork on jinteki.net to see if that would work, and I have not been able to log in since. I am able to receive the passwork reset email, but once I reset my password and try to log in, I get an error message saying that my information is incorrect. Help!

**Comment by danhut** [comment]
username is now case sensitive - can you try that and let us know?
