### ISSUE TITLE
Colossus

### ISSUE THREAD

**Issue by Sedatedfork** [mtgred/netrunner#3103]
There doesn't seem to be a button to advance colossus.  I have just done manually.

**Comment by danhut** [comment]
Looks ok to me.  You might need to share more on what you think the issue is as I am not seeing it.  thanks.
<img width="800" alt="screen shot 2018-03-03 at 6 35 50 pm" src="https://user-images.githubusercontent.com/11830223/36931793-d08088c0-1f11-11e8-8e58-c6d4d922a2b9.png">

**Comment by Sedatedfork** [comment]
Agree.  It is working now.  I thought you guys fixed it.  😀. Probably just a temp bug.
