### ISSUE TITLE
Sneakdoor Beta doens't trigger Silhouette's expose ability.

### ISSUE THREAD

**Issue by nberndt** [mtgred/netrunner#3104]
Sneakdoor Beta doens't trigger Silhouette's expose ability. I found this out while using Chrome for Windows on 2/20/2018.

**Comment by Sedatedfork** [comment]
Same with Steve Cambridge

**Comment by JoelCFC25** [comment]
Just tried Sneakdoor + Silhouette and it worked fine.

**Comment by yads** [comment]
I've had this happen with Steve. Near as I could find this typically only triggered if I started the turn with 1 card in heap. I would pawn another card, making 2 in heap. I would install Sneakdoor, run, and not get the Steve prompt.

**Comment by NoahTheDuke** [comment]
Still can't reproduce.
