### ISSUE TITLE
Breaker Auto-Pump Enhancement (Single click breaking)

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#3105]
The goal of this enhancement is to reduce user clicks and precision needed when breaking ice with most icebreakers. With some clever code modification, both Architect and Colossus could be broken by Femme in three mouse clicks.

I suggest doing this by enhancing the breaker-auto-pump and auto-icebreaker functions. Instead of adding a pseudo-ability to trigger auto-pump, instead temporarily overwrite card with a single ability of "Match Strength" that when activated again temporarily overwrites the card with the proper "break sub" ability. The icebreaker would return to its original abilities once the encounter ends, as it does now.

Players are already familiar with single-click breaking implementation on Black Orchestra, so I don't think this will be too confusing. The implementation will have to check for additional abilitites on the icebreaker (such as Derez with Saker or Swap with Inversificator), so while not universal it should apply to the majority of icebreakers.

Aside:
I'm attempting to learn Clojure to implement enhancements like this this myself, but am still a bit new. I would appreciate it if someone could help me guide me through how to implement this.

**Comment by Saintis** [comment]
Oooh that is clever! Should at least make it easier to use ice breakers that don't have additional abilities.

**Comment by Saintis** [comment]
Regarding learning Clojure and the code base, I'd suggest starting with implementing a card before you tackle this idea. The way auto-pump works is quite complex.

**Comment by nealterrell** [comment]
Interesting idea. I would insist on it being gated behind an opt-in user setting, because the visual cost labels on the pump/break abilities are important for new players. (I understand you would only want the single-click abilities to activate during a run, but a lot of players lean on the site calculating and displaying the total cost to match strength.) But it's a promising proposal.

**Comment by NoahTheDuke** [comment]
This should be taken care of the subroutine implementation work and updates to `auto-pump-and-break`.
