### ISSUE TITLE
Find the Truth while trashing Marilyn Campaign triggers out of order.

### ISSUE THREAD

**Issue by dinte** [mtgred/netrunner#3108]
When making the first successful run of the turn and then trashing a rezzed Marilyn Campaign, the Marilyn Campaign shuffles into R&D before the runner looks at the top card, when it should happen in the other order.

This may only happen with Neutralize all Threats out, I haven't been able to test otherwise.

**Comment by LiteSpecter** [comment]
This happens with other corp successful run/trash triggers as well, for example an Ash trace resolves before the runner sees the top card.

**Comment by jbrz** [comment]
also occurs with CtM trace firing due to Neutralize before showing the FtT card.

**Comment by danhut** [comment]
I think a proper fix is to have the :delayed-completion on Find The Truth only happen when the "OK" button on Find the Truth is pressed to complete its effect.  Could be handled by making the prompt into a selection with no valid options such that "Done" will complete the effect.
