### ISSUE TITLE
Advanced Assembly Lines not prompting install

### ISSUE THREAD

**Issue by FoilFlaws** [mtgred/netrunner#3109]
Usually happens with large CI hands, click on AAL, target appears but no prompt to install when card is selected from HQ. Expanding HQ did not resolve. 

Did not occur with a smaller HQ, only with 8-10 cards in hand.

**Comment by nealterrell** [comment]
Guessing this was because of Jeeves, which we just fixed.

**Comment by JoelCFC25** [comment]
Confirmed fixed...
