### ISSUE TITLE
Ice carver, parasite, quicksand

### ISSUE THREAD

**Issue by MasterAir** [mtgred/netrunner#311]
I'm fine if this never gets resolved, but I encountered it and it might be easy to solve.

A quicksand is installed and has 1 power counter on it. A parasite is installed on said quicksand with 0 virus tokens. Ice Carver is installed.

When the runner runs the quicksand ice carver should resolve reducing the strength of the quicksand to 0 and trash the quicksand before it gains a power counter.

In fact, in the jinteki.net implementation the quicksand gains a strength and is therefore not trashed.

**Comment by nealterrell** [comment]
Same issue as #309 etc.; we don't deal well with simultaneous effects resolution. The order they resolve is largely random. I don't think we have a timetable for fixing this as it's very very complicated. Thanks for the report though!

**Comment by JoelCFC25** [comment]
We made adding power counters to Quicksand a manual process, so the correct result (Parasite + Ice Carver insta-trashing it on encounter) should happen now.
