### ISSUE TITLE
Swapping SSL Endorsement to the runner's score area doesn't allow the corp to gain 3.

### ISSUE THREAD

**Issue by ryan-ormsby** [mtgred/netrunner#3114]
- Corp Scores SSL Endorsement
- Runner installs Turntable
- Runner steals another agenda and swaps with SSL
- Corp can no longer gain 3 from it.  Wording on the card would suggest you can.

**Comment by JoelCFC25** [comment]
Ugh, I positively HATE these special snowflake cards that break all precedent from 1000+ cards that have come before.

**Comment by Saintis** [comment]
Got a fix coming for this.
