### ISSUE TITLE
repeated acces

### ISSUE THREAD

**Issue by slyphs** [mtgred/netrunner#3117]
After bouncing an ice with leela my turning wheel acces resetted

**Comment by Zerothmaxima** [comment]
Same thing happened when I accessed a Future Perfect and lost the psi game, went on to access a bunch more cards.

**Comment by Zerothmaxima** [comment]
Also just happened after runner accessed Cyberdex and it fired

**Comment by finnbar** [comment]
It seems like Turning Wheel is giving more accesses than it should regardless of the situation. I just made a normal run and used Turning Wheel twice, giving me more than three accesses.

**Comment by bugielmarek** [comment]
Experienced same thing as finnbar.

**Comment by danhut** [comment]
Looks like I broke something with a recent "fix" of TTW for another issue. Will take a look.

**Comment by danhut** [comment]
I might need an exact process to fix whatever the problem is - I have tried a bunch of things and do not see a problem.  There very much could be!  A game log and screenshot would be a good start - but a reproducible process really needed.

**Comment by bugielmarek** [comment]
I'm not sure whether screenshot can be any help, as what it'd bring to the table is something like: "Player x uses TTW token to access an additional card this turn" and then "Player x accessec an unseen card from R&D" more times than tokens were used. That being said if it happens again I'll try to provide any data that can help, screenshot included.

**Comment by bugielmarek** [comment]
![ttw](https://user-images.githubusercontent.com/32525977/36643771-8b821cea-1a50-11e8-8b46-0e17b7664a29.png)

Got a ss, 3 additional cards should be seen yet runner could smash the 'access card' button all day long.

**Comment by jbrz** [comment]
Can give you one repro example:

Turning Wheel installed with 10 counters;
Runner runs R&D (1 ice) > breaks ice, continues;
Corp player presses "actions before access" prompt;
Runner then pops all 10 turning wheel counters (for an eventual access of 6 total cards) before hitting the "successful run" button.
At that point, corp is prompted to take actions, rezzes a bunch of stuff (irrelevant for the access);
runner is then prompted to access cards...in perpetuity.  No limit.

So clearly something's buggered with TTW access being (probably) recalculated at certain steps.

This happened in the past as well, so my guess is that latest changes ended up causing some accidental reversion of how that card behaves.

**Comment by danhut** [comment]
Thanks - it seems to be something to do with "actions before access".  I can reproduce it now.  Will look for a fix when I get time.

**Comment by nealterrell** [comment]
I am going to revert the previous change until we can get it fixed.

**Comment by danhut** [comment]
Fixed TTW  "floating" event handling.  Each click registers a unique event with an access-bonus each rather than a snowball effect which caused the issue.
