### ISSUE TITLE
Leave No Trace derezzes ICE advanced via Reconstruction Contract

### ISSUE THREAD

**Issue by butzopower** [mtgred/netrunner#3121]
This one is a bit weird to reproduce.

I had a rezzed Firewall on HQ and my opponent used Leave No Trace to make a run on a remote server.  I trashed a Reconstruction Contract with some counters on it and advanced the Firewall.  Once the run ended, the Firewall derezzed due to Leave No Trace.  I'm guessing it's not specifically Reconstruction Contract, might be easier to reproduce with Matrix Analyzer or Space Camp.

**Comment by Saintis** [comment]
Seems like the way Leave No Trace is implemented it thinks the new ice with advancements was rezzed and therefore derezzes it.

**Comment by butzopower** [comment]
Reproduced in a test, but don't have time to figure it out tonight.

```clojure
(deftest leave-no-trace-does-not-derez-modified-ice
  ;; Leave No Trace should not derez ICE that has changed during a run
  (do-game
    (new-game (default-corp [(qty "Ice Wall" 1)])
              (default-runner [(qty "Leave No Trace" 1)]))
    (play-from-hand state :corp "Ice Wall" "HQ")
    (core/rez state :corp (get-ice state :hq 0))
    (take-credits state :corp)
    (is (:rezzed (get-ice state :hq 0)) "Ice Wall should be rezzed initially")
    (play-from-hand state :runner "Leave No Trace")
    (prompt-choice :runner "Server 1")
    (core/add-counter state :corp (get-ice state :hq 0) :advance-counter 1)
    (run-successful state)
    (is (= 1 (get-counters (get-ice state :hq 0) :advance-counter)))
    (is (:rezzed (get-ice state :hq 0)) "Ice Wall should still be rezzed")))
```
