### ISSUE TITLE
Jua encounter effects persists through the entire game

### ISSUE THREAD

**Issue by NothingPersonal12** [mtgred/netrunner#3130]
Was recently playing a game as Azmari Edtech against Kabonesa Wu. On the turn in which the runner encountered a Jua, the runner played Apocalypse, which worked as expected. However, any subsequent attempts to install cards on the runner side failed, presumably due to Jua thinking the turn never ended. All encounters with Jua before the apocalypse worked normally, however.

**Comment by mikeprosser** [comment]
To add to this (having just hit the same issue), facedown cards on the runner side in our game also seemed to remain active. An origami and an astrolabe were both turned face down and the runner's hand size stayed at 6, then once the encore turns ended the corp installed a new remote and the runner automatically drew a new card.

**Comment by JoelCFC25** [comment]
Things are a bit of a shambles with regard to cards getting turned facedown (see #2871, #2469).

**Comment by JoelCFC25** [comment]
So back to Jua...I guess it needs a `:trash-effect` handler to check `[:runner :lock-install]` and if its `cid` is found, do an `unlock-install`.
