### ISSUE TITLE
Feature request: Show runner stats on traces

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#3135]
When the corp is paying a trace, the dialog could show the runner's current link and credits. This would make doing the math a bit easier.

**Comment by nealterrell** [comment]
Watching Metropole Grid? :)

**Comment by FarCryFromHuman** [comment]
I catch the odd stream...

**Comment by Eric-Fletcher** [comment]
Just look in the generic status window on the left side of the screen: it shows runner credits and link.

**Comment by FarCryFromHuman** [comment]
True, but they are mingled among the other stats the game keeps track of, and shoved into the corner of the screen. Presenting the player with the information they need to make small decisions front and center is good interface design. It also helps with spectators watching streams since the small text on the side of the screen can he hard to read at a smaller resolution.

**Comment by Saintis** [comment]
I've had a go at this previously but haven't manage to make it pretty so far. Can have another go at it.
