### ISSUE TITLE
Invalid passsword

### ISSUE THREAD

**Issue by Jintekimirai** [mtgred/netrunner#3136]
Hi, 

Since yesterday I can't connect to the website anymore as it says that may login/password is not valid anymore.

When I follow the password reset procedure and try to log in again, still doesn't work. Anybody facing same issue  ?

**Comment by Saintis** [comment]
User names are now case sensitive, see #3095. Let us know if that doesn't solve your issue 😄

**Comment by Jintekimirai** [comment]
ok ! that was the issue !

Thanks a lot
