### ISSUE TITLE
Card abilities in the UI

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#314]
@mtgred, I have been playing around with #259 trying to get a "pump to strength" ability onto icebreakers. I think I can do it if I'm allowed to change the way abilities are merged into card data in state. Right now, abilities get merged into a card's data using just their label strings. I think that's to simplify the UI, so you can build ability buttons just using the strings as given. I would like to change this setup to use an equivalent to the maps from the card's definition, perhaps minus the `:req` and `:effect` (anything that would execute code). The data would be useful in the UI -- could automatically add costs in front of abilities, and there is some meta-information that I will need to do auto-pumping in a nice way.

I don't want to change this setup in case there's a reason for only using the labels other than simplicity. Let me know!

**Comment by mtgred** [comment]
Sure go ahead.
