### ISSUE TITLE
Deckbuilder issues in Google Chrome

### ISSUE THREAD

**Issue by sperry023** [mtgred/netrunner#3140]
The deckbuilder window is missing images and no longer recognizes cards. When making a new deck, it doesn't show IDs. The test server is OK.
![jnetchromeissue](https://user-images.githubusercontent.com/13188311/36937185-7f422eca-1edd-11e8-8f27-6a41b728d043.png)

**Comment by nealterrell** [comment]
I reset the server. Are you still having these issues?

**Comment by sperry023** [comment]
All set, thanks!
