### ISSUE TITLE
Azmari EdTech doesn't prevent runner from starting turn

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#3142]
From the dev server: "While playing Azmari Edtech, my opponent was able to start their turn and take actions before I had finished choosing what type of card to name."

Either:

1. `end-turn` needs to wait for the `:corp-turn-ends` event trigger to resolve by using `when-completed` and `trigger-event-sync` before proceeding with the end-of-turn routines; or
2. Azmari needs to show a wait prompt while the Corp is making its selection so runner can't start their turn.

**Comment by Saintis** [comment]
Making `end-turn` await seems best.
