### ISSUE TITLE
Deckbuilding broken and can't select decks in Play

### ISSUE THREAD

**Issue by profwacko** [mtgred/netrunner#3143]
I would suspect it's just a connection issue but I would like to make sure. See attached files:

![screen shot 2018-03-04 at 9 02 59 pm](https://user-images.githubusercontent.com/4827688/36945935-0012e70c-1ff0-11e8-97a5-eafc4aaa7013.png)
![screen shot 2018-03-04 at 8 57 59 pm](https://user-images.githubusercontent.com/4827688/36945936-00519ea2-1ff0-11e8-9f98-484f143f519a.png)

**Comment by nealterrell** [comment]
Try clearing your cache and reloading the page.
