### ISSUE TITLE
Guru Davinder triggers on 0 damage

### ISSUE THREAD

**Issue by sdfkjhsekfheknb** [mtgred/netrunner#3149]
Guru Davinder asks to Pay 4 credits after it was used to prevent 0 meat damage from a played Punitive Counterstrike on a turn after the runner stole no agendas.
I guess this isn't a common problem but the card reads "at least 1 net or meat damage" so it shouldn't trigger. Don't know if this is true for other cards that "deal 0 damage"

**Comment by JoelCFC25** [comment]
The `:req` on the `:pre-damage` event handler needs to have something like `(pos? (second targets))` added.
