### ISSUE TITLE
Scheherezade targeting issues

### ISSUE THREAD

**Issue by log0s** [mtgred/netrunner#315]
Hosting cards on Scheherezade seems to cause targeting problems. The two I noticed were that I could not sell an Imp with Aesop's Pawnshop and that I could not target a Medium with Incubator's activated ability.

**Comment by nealterrell** [comment]
Thanks for the report. We have cleaned up the hosting code recently and need to propogate some of the changes throughout the card base. A lot of abilities that target installed cards will probably be broken for a while when targeting hosted cards. Let us know if you find any more!

**Comment by nealterrell** [comment]
The two interactions mentioned here were fixed in b403e4be8d88d3c211615a8402253f6cd6b0084f !

**Comment by log0s** [comment]
Awesome, thanks for the fix!
