### ISSUE TITLE
RNG Key triggers despite unsuccessful Ash 2X3ZB9CY trace

### ISSUE THREAD

**Issue by Ozasuke-san** [mtgred/netrunner#3150]
Summary:
RNG Key still fires even though Ash 2X3ZB9CY trace was unsuccessful.

Repro Steps:
1. Successfully run HQ with unrezzed Ash 2X3ZB9CY
2. Select "Yes" to RNG Key usage prompt and "2" as the guessed number
3. Corp rezzes Ash 2X3ZB9CY and fires the trace with a lot of strength
4. Add 0 credits to the strength as a Runner

Results:
Runner is unable to access HQ except for Ash 2X3ZB9CY. RNG Key considers Ash 2X3ZB9CY as the accessed card and prompts 2 credits or 2 cards.

Notes:
Sorry for a lack of screenshot here. Was playing with a friend and we got talking about it after the game.

**Comment by nealterrell** [comment]
That was the correct behavior until the recent UFAQ which ruled that you cannot reveal rezzed cards. We have not yet implemented that change. Thanks for the report.
