### ISSUE TITLE
Armed Interrogation Leaving Waiting For Runner Prompt Open

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#3151]
-  [x]  On the test server I had some issues scoring Armed Interrogation. I was playing as Jemison. When scored normally, I would have the 'Waiting for Runner' prompt left open even after they had taken the tags or meat damage. I had to /close-prompt to clear it.
-  [x]  When I triggered the 'when scored' using 24/7 News Cycle, it said waiting for runner on corp side, and waiting for corp to place counters on the runner side. Using /close-prompt as corp cleared the waiting for runner message and allowed me to place advancement tokens, and then runner was able to make choice and prompt cleared.

**Comment by Saintis** [comment]
Looks like I goofed the implementation a bit. Will look into it.

**Comment by Saintis** [comment]
Fixed the first part. The second part requires await-able cost-payment to work properly, which is a quite serious undertaking...
