### ISSUE TITLE
Clone chip with zero MU

### ISSUE THREAD

**Issue by log0s** [mtgred/netrunner#316]
Basically, because of the way the interface forces you to trash programs before installing a new one, clone chipping something (in this case a Parasite) with no open MU will consume the Clone Chip with no effect.

**Comment by nealterrell** [comment]
I think this one is a won't-fix... part of learning the system, and even for new players it is possible to fix with a few quick adjustments to clicks and credits.

**Comment by log0s** [comment]
Sounds good, just figured I'd document it. Thanks for all the work on this awesome client!

**Comment by nealterrell** [comment]
We appreciate your thoroughness :).
