### ISSUE TITLE
Death and Taxes giving double credits on some installs AND discards

### ISSUE THREAD

**Issue by kusoash** [mtgred/netrunner#3160]
- [ ] Doesn't seem to be on all installs only some. The ones I witnessed were Aumakua, Maya, and Egret being hosted on a Veritas.
![image](https://user-images.githubusercontent.com/37168378/37133694-9ed22072-22e0-11e8-84c2-c0c25e43c2b9.png)
![image](https://user-images.githubusercontent.com/37168378/37133709-b4833154-22e0-11e8-9471-73681db743dd.png)
![image](https://user-images.githubusercontent.com/37168378/37133722-c441283a-22e0-11e8-837e-8918f9ae17f4.png)

- [x] It also appears to be checking for cards at discard that have a trash ability on them or can be installed. 
- [ ] This one also looks like the runner clicking for credits is proccing it.
![image](https://user-images.githubusercontent.com/37168378/37133767-f8324a48-22e0-11e8-934e-a26cb7bea78b.png)

**Comment by Saintis** [comment]
I'll look into this tonight, or this weekend.

**Comment by Saintis** [comment]
I done goofed on the second part, should be fixed in #3168. Not sure what could cause part 1 though...

**Comment by JoelCFC25** [comment]
With the previous fix merged, I'm not seeing doubled D-and-T credits on installs, nor credits given on Runner clicking for credits. And actually I think that picture may have been showing a credit given from Armitage self-trashing after getting emptied, not from the Runner clicking for a credit.

**Comment by Saintis** [comment]
I'll consider this issue solved. Any repeat occurances can either reopen this or create a new issue.
