### ISSUE TITLE
Friday Chip triggering on Runner discards

### ISSUE THREAD

**Issue by CirclMastr** [mtgred/netrunner#3161]
When the Runner discards down to their max hand size at the end of their turn, each trash is triggering the prompt to place a virus counter on Friday Chip.

**Comment by NoahTheDuke** [comment]
On it.

**Comment by FarCryFromHuman** [comment]
While you are in there, you might prevent the start of turn move virus counter ability from firing when there are no installed viruses.

**Comment by yads** [comment]
It also I think triggers on Runner card trashes as well. E.g. Earthrise trashing itself when running out of counters.
