### ISSUE TITLE
Kakugo and Inversificator

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3164]
Hi,

I have just played a game against a runner with Inversificator and a few Kakugoes floating around on my side. The usual net damage firing (when the Runner "continues" past the ICE) happened as usual, until Kakugo was swapped with Inversificator. It then never fired again for the rest of the game in its new position. This happened for every individual copy of Kakugo, working fine until it was swapped somewhere else, so it looks like the switching positions with Inversificator turns off the function somehow.
 
Not sure if this relates to #2835 in some way too?

**Comment by Saintis** [comment]
It seems like only events for hosted cards are updated when ice are swapped. Looks like an easy fix: adding unregistering / registering for the ice itself might fix it.
