### ISSUE TITLE
Degree Mill grants extra accesses

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#3167]
Degree Mill grants the runner another access (including any multiaccess modifiers) when it's stolen. It also erroneously specifies "programs" in the prompt, but still allows the runner to choose any installed cards.

**Comment by JoelCFC25** [comment]
Prompt can be fixed in `costs-to-symbol` in `utils.clj`

**Comment by Eric-Fletcher** [comment]
Also, with Another Day, Another Paycheck in effect, the prompt to shuffle away appears after the trace has fired, when it should show up before the steal is completed.
This has the effect of letting Sunny benefit from Power Tap/link that should have been shuffled away.

**Comment by JoelCFC25** [comment]
The brand new cost of "Runner has to shuffle in 2 installed cards" has to be modified to incorporate delayed completion.
