### ISSUE TITLE
Architect can be trashed

### ISSUE THREAD

**Issue by log0s** [mtgred/netrunner#317]
As the title says, had a brain fart and tried to trash a rezzed Architect with a Parasite. My opponent was understandably surprised when it worked; guess sometimes I get rewarded for being dumb.

**Comment by JoelCFC25** [comment]
Many of the cards that prevent normally allowable actions rely on the players' mutual understanding and cooperation to enforce right now: Blacklist, Clot, Haarpsichord Studios (unreleased), Lockdown, Underway Grid, Hudson 1.0, et al.

**Comment by Kiv** [comment]
Would be really nice to have this fixed now that Apocalypse will force trash Architect.
