### ISSUE TITLE
Counter Surveillance doesnt work with friday chip installed.

### ISSUE THREAD

**Issue by BillRye** [mtgred/netrunner#3171]
Had friday chip installed ran rnd with ten tags had 14 credits on access only accessed one card.

**Comment by JoelCFC25** [comment]
What happens if you use Counter Surveillance *without* Friday Chip installed? With a known Friday Chip issue being fixed at #3163 I'm willing to bet CS is in fact working just fine in isolation...

**Comment by BillRye** [comment]
Yup friday chip buggs it, works without friday chip doesnt when friday chip is installed.

**Comment by JoelCFC25** [comment]
Friday Chip fixed at #3163.
