### ISSUE TITLE
All cards in hand are facedown

### ISSUE THREAD

**Issue by Jinteki1** [mtgred/netrunner#3175]
<img width="1677" alt="screen shot 2018-03-11 at 12 53 02 am" src="https://user-images.githubusercontent.com/37251421/37250269-c0acd290-24c6-11e8-9769-6d5c2f78e775.png">

Sometimes when the game freezes, I need to leave the game and return or I click refresh, and when I rejoin the game, all my cards in my hand are facedown. How do I fix or prevent this from happening?

**Comment by HongkongKoma** [comment]
The sme happened to me today, see screenshot attached. Not on the corp side, but as runner.
<img width="1865" alt="bildschirmfoto 2018-03-19 um 11 38 36" src="https://user-images.githubusercontent.com/11632063/37591016-61031c1e-2b6a-11e8-9241-193c324468aa.png">
