### ISSUE TITLE
Autoscripter grants clicks for all installs (I think)

### ISSUE THREAD

**Issue by MasterAir** [mtgred/netrunner#318]
Autoscripter seems to be bugged. It gives extra clicks every time you install hardware or programs from your grip. It should only give a click the first install per turn. Most egregious is that it gives a click for installing itself.

**Comment by nealterrell** [comment]
Well that's embarrassing. It is indeed granting clicks for ALL installs as long as there hasn't been a program installed this turn yet. Missed the easiest part of that card! :(

**Comment by MasterAir** [comment]
Need to learn some clojure so I can help out on this project. It's fantastic work you're all doing!

**Comment by JoelCFC25** [comment]
Tested just now, looks like this one is fixed. The click is being gained only for the first program installed each turn.
