### ISSUE TITLE
Kakugo does not fire pass ability if it has been moved

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#3189]
![image](https://user-images.githubusercontent.com/7817263/37409551-fdf187a8-2774-11e8-869c-8a623ecf8a83.png)

Saw this happen in a real game, then reproduced it in a test game.
Runner plays Escher, moving a Kakugo from one server to another.
Later, when runner runs against Kakugo, it doesnt automatically deal net damage when runner passes.

**Comment by tblackwe** [comment]
ugh, forgot to scroll up in logs, and closed the game. but my description is how it happened

**Comment by NoahTheDuke** [comment]
Should be fixed by #3179.

**Comment by tblackwe** [comment]
Thanks! Didn't remember seeing that report.
