### ISSUE TITLE
Exposing a card should show the enlarged card information

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#319]
Although exposing a card shows the name of the card in the chat, players who aren't familiar with the card have no idea what it is.

It would be nice if the card was actually exposed in the UI for the player. One suggestion is to have a "ghost" version of the card (opacity ~50%) and when the runner mouses over the card, they can see a pop up. Maybe it lasts for the turn, for example.

**Comment by nealterrell** [comment]
This is related to #216 and #4, but limited in the amount of time you can do the hover. It's a good idea but will probably be a while before we can tackle it.

**Comment by Astrochelys** [comment]
One thing I often do when I access or expose cards I don't know or can't remember certain relevant details (rez cost, ice types or subtypes, etc), I simply click on the 'Cards' tab and look it up. It doesn't affect the game and it's quite fast.
