### ISSUE TITLE
Femme Fatale breaks subroutines one-by-one rather than paying X credits for X subroutines

### ISSUE THREAD

**Issue by archmage** [mtgred/netrunner#3197]
[Femme Fatale](https://netrunnerdb.com/en/card/01026) does not break subroutines; however, in two games I played against a friend, they were able to place a Femme token on a piece of ice and break each subroutine individually. This is not how Femme works; instead, you pay X credits to bypass the ice entirely, where X is the number of its subroutines. 

I made sure to check that Femme was not at sufficient strength to break the subroutines. Something weird's happening here.

**Comment by JoelCFC25** [comment]
You are right, but the system as currently designed does not have a mechanism for identifying how many subroutines a piece of ICE has (this is quite complicated, given all the cards that can *add* subroutines to ICE that it doesn't have by default). 

So as a design conceit, players simply use the "break subroutine" ability to achieve the same outcome as "pay 1c per sub to bypass". The log message inaccuracy is purely cosmetic.

**Comment by archmage** [comment]
Right! Seems like it's working as intended, and I just didn't know how it worked :)

Closing this issue.
