### ISSUE TITLE
Ekomind/kab Origami deck

### ISSUE THREAD

**Issue by Dloaf** [mtgred/netrunner#3198]
An opponent was telling me that the ekomind deck that kab has been using with origami and unused MU isn't working right.

Is it the cards writing or do I have to adjust my MU with each card in hand and memory used?

Cheers.

**Comment by JoelCFC25** [comment]
Ekomind has actually NEVER worked right. The bug is in at #2829.

**Comment by danhut** [comment]
Closing as it is a duplicate
