### ISSUE TITLE
Mopus Ability Sound Effect

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3199]
I play Mopus often, and I found an opportunity to enhance its interaction a little bit.

Normally before I pick up a Mopus, I'll have to click a few times. Once I get it, I click the Mopus to gain my two rather than the "Gain Credit" button.

When one hits the "Gain Credit" button so many times beforehand, one becomes accustomed to hearing the coin sound effect upon gaining credits. 

I'd like to cut my teeth on tinkering with card abilities, so I thought this might be a good opportunity to do so.

I propose adding the coin sound effect to Mopus when clicked to create similar feedback as to the "Gain Credits" button.

I can also search through the cards to compile a list of other credit gaining ones (like a trashed Fall Guy) to add this effect to as well.

What do you guys think?

**Comment by msbeck** [comment]
While investigating the sound engine, I came across a few questions. I'll add the questions here in addition to the standing ones about adding sounds to card interactions in the first place.

```
 (let [audio-sfx (fn [name] (list (keyword name)
                                       (new js/Howl (clj->js {:urls [(str "/sound/" name ".ogg")
                                                                     (str "/sound/" name ".mp3")]}))))]
        {:soundbank
         (apply hash-map (concat
                          (audio-sfx "agenda-score")
                          (audio-sfx "agenda-steal")
```
In gameboard.cljs I see the sounds being set up, but I don't understand where they are coming from. I only have two game lobby sounds locally (ting.mp3 and ting.ogg). Are these being pulled from the web?

Part of why I'm asking about where they are coming from is that I cannot find them locally in my clone of the repo and sounds are not working in game locally either.

**Comment by JoelCFC25** [comment]
Sounds work in my dev environment, and the files are found in `~/netrunner/resources/public/sound`

**Comment by msbeck** [comment]
They aren't in the repo. Did I miss some initialization command to pull them from somewhere else?

https://github.com/mtgred/netrunner/tree/master/resources/public/sound

**Comment by JoelCFC25** [comment]
It's all coming back to me now...I think you can [get them from here](https://github.com/mtgred/netrunner/issues/968#issuecomment-253191666).

**Comment by msbeck** [comment]
The regular process is to download these and put them in the sounds directory manually? I'm curious why they aren't in the repo. And what the process is for when new code is deployed live.

**Comment by Saintis** [comment]
If this get's done, you could add "credit + card" sound to ProCo. And credit sound to first draw with SymVis etc.

**Comment by msbeck** [comment]
Yep, that's what I'm imagining!
