### ISSUE TITLE
Bacterial Programming could do with undo options on all 3 menus

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#3204]
Using Bacterial Programming, I accidentally selected almost everything to trash, before realising that I was selecting cards to trash, rather than rearrangement, and there was no option to undo this mistake, meaning I had to resolve it manually.

Other solutions could be an improved UI for Bacterial Programming; Even the old style of indexing implemention where all the cards are added to a temporary area to be dragged back to their appropriate locations might be better.

**Comment by Saintis** [comment]
We could have the corp drag cards to Archives or HQ from temporary zone, and the use the Indexing style ordering prompt for the cards going to R&D.

Or alternatively a prompt at the end of BP saying which cards go where with a "Correct" and an "Undo" button.
