### ISSUE TITLE
Make IDs visible in lobby without mousing over icons

### ISSUE THREAD

**Issue by hotlinemarty** [mtgred/netrunner#3211]
Hi there, just started Netrunner and have been watching a lot of games on Jinteki. I love it so far.

One thing I've noticed that bothers me a little though: When I am looking through the list of active games, I cannot see at a glance which identities players have chosen, In order to find that out without entering the game, I have to mouse over the tiny ID icon and wait for the alt text to appear:

Would it be possible to have the full identities players have chosen visible in the lobby at a glance, without taking the extra time to mouse over a small icon?
![id](https://user-images.githubusercontent.com/37604866/37692098-d52a3320-2c73-11e8-8f98-0b6ffad39d0a.png)

**Comment by NoahTheDuke** [comment]
How would you like it to look?

**Comment by hotlinemarty** [comment]
Hmm, you could do something like this:

`FatBuddha's Game (1 Spectator)
[UserAvatar]FatBuddha [ID Icon] vs [UserAvatar2]ruby_fell [ID Icon2]
[ID Icon]Weyland Consortium: Builder of Nations
[ID Icon2]Adam: Compulsive Hacker`

Or maybe:

`FatBuddha's Game (1 Spectator)
[UserAvatar]FatBuddha [ID Icon] vs [UserAvatar2]ruby_fell [ID Icon2]
Weyland Consortium: Builder of Nations vs Adam: Compulsive Hacker`

Or, and this is a bit more drastic:

`FatBuddha's Game (1 Spectator)
Corp: [UserAvatar]FatBuddha [ID Icon] Weyland Consortium: Builder of Nations
Runner: [UserAvatar2]ruby_fell [ID Icon2] Adam: Compulsive Hacker'

**Comment by jwarwick** [comment]
I like the idea of having mini icons for each identity. But we don't have those assets. Any chance NRDB has something similar? Maybe we can borrow from them.

**Comment by FarCryFromHuman** [comment]
What about something more like:

![image](https://user-images.githubusercontent.com/12355388/37743943-33c91612-2d32-11e8-9f01-f115f1f58a76.png)

**Comment by hotlinemarty** [comment]
I like that quite a lot as well. Apologies for not really having the means to create my own mock-up images.

Really anything that makes the frame a one-stop shop for knowing exactly who and what is being played is what I'd love to see. I'm not really married to any specifics.

**Comment by FarCryFromHuman** [comment]
I used this: https://www.dotpdn.com/downloads/pdn.html

**Comment by nealterrell** [comment]
I'm not loving the increase in game lobby size.

**Comment by Saintis** [comment]
I'd also like to keep the size more or less the same. I'd be happy to replace faction icons with ID icons grabbed from the cards, if this makes it clear enough. Alternatively we could add a short name after each icon for the "nickname" of each id: e.g. Sunny vs BABW, BoN vs Hayley etc.

**Comment by hotlinemarty** [comment]
Well, there also seems to be a lot of horizontal space not being used very well at the moment which this could be expanded out into (towards the left side of the window, as the right has more of the same lobby information when a player joins it)

**Comment by hotlinemarty** [comment]
Though as mentioned above, I feel almost any change would be more elegant than what is currently there.

**Comment by FarCryFromHuman** [comment]
What's the reasoning behind not wanting the lobby to be larger? It seems like the vast majority of players trying to join games are going to click among the top few. Anyone who wants to search for a game by player is already going to use CTRL+F, as there are too many games to easily scan, even with the small panes. With this change players would also be able to search for games by ID in the same fashion, which seems useful.

**Comment by HongkongKoma** [comment]
I'm not a pro at all, so sorry for jumping in, but I'd love to help. Since I think no ID icons exist, maybe a solution would be to use a part of each ID card's illustration as background image for that box?

**Comment by Saintis** [comment]
I think that would be very cool, if it's possible to do!

**Comment by jwarwick** [comment]
If someone wants to make identity icons, it would be straightforward to use them instead of the faction icons.

**Comment by HongkongKoma** [comment]
Here is what I had in mind it might look like with background images (rough, I know: But I hope you get the idea):
<img width="498" alt="background" src="https://user-images.githubusercontent.com/11632063/38091447-e2e8b7b8-3365-11e8-9c74-bc9304e30501.png">
