### ISSUE TITLE
Apocalypse destroys host relations and does not keep counters on facedowned runner cards.

### ISSUE THREAD

**Issue by nicohasa** [mtgred/netrunner#3213]
If you apocalypse with an Aumakua on Progenitor, the cards will be facedowned but the host relation will be destroyed and Aumakua will lose its counters.

**Comment by JoelCFC25** [comment]
Related to #2871

**Comment by Skeskrske** [comment]
Fwiw I just found the same thing happens with Friday Chip and Apocalypse - the chip activates and prompts the user from Apocalypse trashing cards as expected, but the virus counters are either never added to the Chip or immediately removed when it's turned facedown.
