### ISSUE TITLE
Bryan Stinson doesn't RFG Death and Taxes when it gets trashed

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#3216]
Repro:
Use Bryan Stinson to play Death and Taxes
Have the runner steal an agenda
Observe that Death and Taxes is trashed, rather than removed from the game.

--this might just need an implementation note on D&T to use the /rfg command?

**Comment by JoelCFC25** [comment]
Hmm, I'm surprised this hasn't come up previously, since Paywall Implementation is a transaction and a current. I would guess the same thing has to happen with that.
