### ISSUE TITLE
Runner stuck with Skorpios prompt and could not clear

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#3218]
Guess I will look when I feel the energy as it was my game
Maybe something horrible with breached dome and Skorp...
<img width="227" alt="screen shot 2018-03-23 at 10 46 27 pm" src="https://user-images.githubusercontent.com/11830223/37828263-ab9d4a74-2eee-11e8-8987-f8c9969ea8d5.png">

<img width="1259" alt="screen shot 2018-03-23 at 10 45 52 pm" src="https://user-images.githubusercontent.com/11830223/37828215-776d4b14-2eee-11e8-8f61-16706f8dc1da.png">

**Comment by msbeck** [comment]
Related to BUG: Multiple Skorpios Dialog (#3074)

The corp can click Skorp after it's already been triggered on a turn. They will not get a prompt, but the runner will.
