### ISSUE TITLE
The Devil and the Dragon Card Implementations

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3219]
Rumored to be released 5 April 2018 in the US.

Checked off means that the card is merged into `master`.
Place a link to the pull request next to the card when it is pushed.
If you wish to claim a card, make a comment on this issue or put your name next to the card.

- [x] [Glut Cipher](https://netrunnerdb.com/en/card/21061) (#3272)
- [x] [Knobkierie](https://netrunnerdb.com/en/card/21062) (#3252)
- [x] [419: Amoral Scammer](https://netrunnerdb.com/en/card/21063) (#3223)
- [x] [Falsified Credentials](https://netrunnerdb.com/en/card/21064) (#3006)
- [x] [Rogue Trading](https://netrunnerdb.com/en/card/21065) (#3266)
- [x] [Because I Can](https://netrunnerdb.com/en/card/21066) (#3257)
- [x] [Nyashia](https://netrunnerdb.com/en/card/21067) (#3270)
- [x] [Consume](https://netrunnerdb.com/en/card/21068) (#3263)
- [x] [Malia Z0L0K4](https://netrunnerdb.com/en/card/21069) (#3275)
- [x] [Kill Switch](https://netrunnerdb.com/en/card/21070) (#3265)
- [x] [Tempus](https://netrunnerdb.com/en/card/21071) (#3261)
- [x] [Bio Vault](https://netrunnerdb.com/en/card/21072) (#3255)
- [x] [Sadaka](https://netrunnerdb.com/en/card/21073) (#3262)
- [x] [Endless EULA](https://netrunnerdb.com/en/card/21074) (#3254)
- [x] [Sandman](https://netrunnerdb.com/en/card/21075) (#3256)
- [x] [Amani Senai](https://netrunnerdb.com/en/card/21076) (#3258)
- [x] [SSO Industries: Fueling Innovation](https://netrunnerdb.com/en/card/21077) (#3228)
- [x] [City Works Project](https://netrunnerdb.com/en/card/21078) (#3195)
- [x] [Oduduwa](https://netrunnerdb.com/en/card/21079) (#3210)
- [x] [Rashida Jaheem](https://netrunnerdb.com/en/card/21080) (#3267)

**Comment by NoahTheDuke** [comment]
Yeah, they're not leaving us a lot of time to get these implemented, heh. We need them leaks!

**Comment by msbeck** [comment]
Consume, EULA, Kill Switch, and Rouge Trading would be good learner ones for me. I can start on those soon. Maybe Sandman and Rashida but I don't want to hog them all or delay their implementation.

**Comment by NoahTheDuke** [comment]
Lemme claim Nyashia and Rashida Jaheem! Those look fun to write.

**Comment by presheaf** [comment]
I can start on Because We Can.

**Comment by presheaf** [comment]
Finished Because I Can - will make a PR once NRDB is up and I can make a test for it. I'll start on Amani Senai next.

**Comment by presheaf** [comment]
Finished with Amani Senai, but as before am waiting for NRDB to go up for a final test before I make a PR. I can try Malia Z0L0K4.

**Comment by nicohasa** [comment]
I'm looking at Glut Cipher right now.

**Comment by presheaf** [comment]
@jwarwick This one's all done. I can't edit it, or I'd do so.

**Comment by jwarwick** [comment]
All cards merged into `master`. Any further bugs should be opened as individual issues.
