### ISSUE TITLE
Diana's Hunt trashes program even if you reinstall it during the run.

### ISSUE THREAD

**Issue by nicohasa** [mtgred/netrunner#3221]
If you run on a server with Diana's Hunt, install a program, then trash it, and then reinstall the same program (with e.g. Clone Chip), Diana's Hunt will still trash it at the end of the run.

**Comment by danhut** [comment]
Added a new key {:special} to resolve this to the cards which are installed, along with an update of the card-reset function to clear this key on trash or move to hand to make {:special} equal to nil.
