### ISSUE TITLE
You can build illegal decks

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#323]
You can include more than 3 copies of a card if you simply write e.g.:

    3 Hedge Fund
    3 Hedge Fund
    3 Hedge Fund
    3 Hedge Fund

Now you have 12 Hedge Funds in your deck

**Comment by nealterrell** [comment]
Yes, there are few/no enforcements of rules when saving decks. Honor system :).

**Comment by DominicKexel** [comment]
Actually, it's quite usefull for debugging. But when playing online I would like to be sure my opponent does not run 6 Sure Gambles and 5 Diesels :-)

**Comment by Saintis** [comment]
Invalid decks are specified as such in the game lobby, does that satisfy this issue?

**Comment by zaroth** [comment]
@saintis, this type of wrong decks wasn't actually detected as invalid. However it got fixed in #1082, so it can be closed now.
