### ISSUE TITLE
Bacterial Programming blocks game without cards to rearrange.

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#3235]
Bacterial Programming leaves the runner with a "waiting for corp" prompt if the corp removes all of the 7 cards seen with BP from R&D, as the corp never gets the rearrange R&D prompt which would presumably otherwise close that prompt.

This means that if the corp adds all 7 cards to Archives or HQ, the runner has to use /close-prompt a few times to continue accessing.

**EDIT:** It also appears that this causes the runner to access an additional card too if they have no accesses remaining.

**Comment by Saintis** [comment]
Did you experience this on a run on HQ, R&D or Archives?

**Comment by Quarg** [comment]
I'm fairly sure I've had this occur on during runs on HQ, R&D, and Remotes, I have not tested to see if it occurs from accessing archives, but I expect it would happen there too.

As for the additional access, I think that has only occurred during runs on R&D, though, again, I have not actually tested to see if it does only occur there.
