### ISSUE TITLE
Forced Connection not "revealed" for corp

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3238]
A runner hit my Forced Connection in RnD. Once it did, I got a trace prompt, but was not told that Forced Connection was the card that was hit.

![screen shot 2018-03-27 at 8 32 11 pm](https://user-images.githubusercontent.com/2982395/38041992-c4ec6568-3278-11e8-8048-18c991413bf0.png)

If it were Snare, it would ask "would you like to pay 4 for Snare" or something. If it were Breached Dome it would do the damage and print "takes damage due to breached dome", but it's not clear exactly what card was hit in this case since the trace just appears. Of course, it's the only trace ambush upon access in RnD card, and one would expect to know their own deck, but not everybody has the full pool and knows its the only one that could have been hit and they could just have pasted a new deck from somewhere and is playing around with it.

Suggest printing "must reveal" ambush cards which are accessed in the chat window with something like the following text:

> Runner must reveal [Forced Connection] upon accessing from R&D.

This also allows the corp to review what exactly the trace will result in and allow them to ruminate on how to interact with it whereas otherwise the text of the card is not available.

**Comment by JoelCFC25** [comment]
Adding `:effect (effect (system-msg :runner (str "accesses Forced Connection")))` (or similar message to the log) would be sufficient.

**Comment by msbeck** [comment]
Ok, I can do that.

**Comment by jwarwick** [comment]
Fixed in #3240
