### ISSUE TITLE
Can't see games until I create one myself

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#324]
I started the server locally. I login with a user A with browser A and create A's game. Then I open Browser B, login with user B, and want to join A's game. But I don't see it. If I create a new game with user B, suddenly I see both (A's game and B's game) in the list.

The browser in question that does not work is Internet Explorer 11. Chrome works fine.

**Comment by nealterrell** [comment]
What browser is this on? I definitely see this behavior on my test server when using Internet Explorer.

**Comment by DominicKexel** [comment]
Ah, yeah, sorry for leaving out that information. Yes, it's the amazing Internet Explorer that does not work. Chrome works fine. Maybe some WebSockets issue?

**Comment by DominicKexel** [comment]
This also happens on Firefox. Chrome works *most of the time*.

**Comment by zaroth** [comment]
Did this improve in Firefox? I never saw this behavior.

**Comment by zaroth** [comment]
Scratch that, noticed this behavior a few times since. Seems weird and tough to track.

**Comment by erbridge** [comment]
I get this on Firefox reliably. To reproduce, open two sessions. Load local Jinteki in one session, and create a game. Then load Jinteki in the other session and see no games. If both sessions are already connected when a game is created, it appears as expected. This includes the need to reload the sessions after builds.

**Comment by danhut** [comment]
This still happens in firefox... did not look further as I fell asleep
