### ISSUE TITLE
Feature Request: Reduce Server Width

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#3242]
Currently servers have a default wide that appears to be defined by the width of a piece of ICE. This is fine for glacier style servers. For Asset Spam style decks, some horizontal space could be gained by reducing the width of un-ICEd servers. 

The code is already there automatically widen a server when the upgrades get excessive. I suggest using that code to reduce width of servers (at least remotes, but no reason it couldn't be all) and then widening the server when ICE is installed.

**Comment by NoahTheDuke** [comment]
This is taken care of by #4326
