### ISSUE TITLE
Net Quarantine and new link display

### ISSUE THREAD

**Issue by cspieker** [mtgred/netrunner#3244]
Corp scored a Net Quarantine.  The runner (Val) had one link for ID and another link for an installed card (The Archivist).   

When a trace happened, the new (awesome) link display for the runner read, "has x credits and 1 link".  It probably should read "0 link" since Net Quarantine is supposed to reduce the link of the runner and from any installed link cards.

**Comment by JoelCFC25** [comment]
The issue here lies in `init-trace`:  the `:trace` event (what Net Quarantine listens for) is being triggered _after_ the prompt has been built with `show-trace-prompt`.

**Comment by JoelCFC25** [comment]
Nope, this is still an issue. The first trace of a turn in the originally listed conditions (scored Net Quarantine, Val + 1 link from Dyson Mem Chip, for example) shows: 
![screen shot 2018-04-14 at 7 45 06 am](https://user-images.githubusercontent.com/10407969/38768336-cf5eeb82-3fb7-11e8-9a9d-957a5ecbe8c7.png)

**Comment by Saintis** [comment]
Should have been fixed by #3661
