### ISSUE TITLE
Jua on-encounter effect does not end if Jua is trashed before the end of turn

### ISSUE THREAD

**Issue by rubyfell** [mtgred/netrunner#3245]
If Jua is encountered, then trashed (by Kit/Spooned in the cases I've experienced), its on-encounter effect does not end. The runner is then unable to install cards on subsequent turns. 

If later, Jua is reinstalled and rezzed before the end of the runner's turn, the effect will go away. But it's a clunky work-around.

**Comment by danhut** [comment]
Fixed already in next code deployment via #3150
