### ISSUE TITLE
Maxx and dummy box

### ISSUE THREAD

**Issue by kevkcc** [mtgred/netrunner#3246]
Maxx's beginning of turn trashes triggers dummy box and if you decline to prevent the trash, the would-be-trashed cards end up in her hand.

**Comment by danhut** [comment]
Seems to be fall-out from #3187 
Appears we need a version of `mill` that triggers trash events, and one that does not.

**Comment by NoahTheDuke** [comment]
It looks like Dummy Box’s `:prevent { :trash` isn’t checking for where the trashed item is coming from. Dummy Box can only block installed cards from being trashed, and MaxX does trigger trash effects (Skorpios, etc).

**Comment by JoelCFC25** [comment]
There isn't any conditional prevention anywhere in the system, actually. Is there anything that can prevent a mill? I can't think of one. Maybe the `trash` being done in `mill` needs to be unpreventable. That'll stop prevention from kicking in.

**Comment by danhut** [comment]
Good thinking @JoelCFC25 !
