### ISSUE TITLE
Friday Chip automation

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#3247]
When multiple Friday Chips are installed and the runner is trashing something every turn, manually confirming each additional counter can slow the game down somewhat.  Could this be changed to automatically accept counters?  

(While it is optional, I can't think of a situation where the runner wouldn't want to gain them.)

**Comment by nealterrell** [comment]
This decision was made because of Reverse Infection, and because counters are moderately difficult to adjust manually.

**Comment by Skeskrske** [comment]
Ahhh gotcha. I figured it must have been justified by some interaction, but for the life of me couldn't figure out what. :)
