### ISSUE TITLE
Chameleon + London Library

### ISSUE THREAD

**Issue by sperry023** [mtgred/netrunner#325]
Encountered an issue where a duplicate card was created and sent to the heap when Chameleon bounced back to hand at end of turn when hosted on London Library.

**Comment by MasterAir** [comment]
I was about to submit something similar, though I hadn't figured out that it was a London Library + Chameleon issue at the time, that makes sense. I can confirm that I was using London Library when I noticed it happening.

**Comment by mtgred** [comment]
I will try to fix this. Meanwhile you can drag and drop Chameleon back to Grip before click "End Turn" as a work around.
