### ISSUE TITLE
No One Home triggers on every instance of net damage

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#3264]
No One Home should only provide an option to prevent damage/tags once per turn. Currently it triggers every time Net Damage happens:

EricF uses Aiki to make the Runner draw 2 cards.
EricF uses Aiki to do 1 net damage.
jarlstig has the option to avoid damage.
jarlstig will not prevent damage.
jarlstig trashes Data Folding due to net damage.
EricF uses Aiki to do 1 net damage.
jarlstig has the option to avoid damage.
jarlstig will not prevent damage.
jarlstig trashes Saker due to net damage.
jarlstig continues the run.
jarlstig
jarlstig
?
EricF has no further action.
jarlstig accesses Project Kusanagi from Server 5.
jarlstig steals Project Kusanagi and gains 0 agenda points.
EricF uses Jinteki: Personal Evolution to do 1 net damage.
jarlstig has the option to avoid damage.
jarlstig will not prevent damage.
jarlstig trashes Underworld Contact due to net damage.
EricF
EricF
sorry, writing bug report on NOH

**Comment by JoelCFC25** [comment]
There is no support in the system for conditional prevention. Net Shield has always done this, FWIW--it'll prompt on every instance of net damage for the turn, even though it's only usable to actually DO the prevention once.

**Comment by Eric-Fletcher** [comment]
If net shield stops triggering after being used, could saying "no" set the
same flag as saying "yes" that would prevent future triggers?

**Comment by JoelCFC25** [comment]
No, I meant that Net Shield does this exact same thing. It keeps prompting the Runner "Do you want to prevent?" every time during the turn that it sees net damage, even if it has been previously been used to _actually_ do a prevention the one allotted time per turn. 

The idea of stopping the prompt from appearing at all on the 2nd and subsequent instances is what is not supported. It's complicated.

**Comment by presheaf** [comment]
This doesn't make resolving the issue any easier, but also (and for the same reason) No One Home also offers tag prevention even if the Runner has taken damage that turn.

**Comment by Eric-Fletcher** [comment]
Could No One Home and similar cards make themselves inactive / blank until
end of turn, so they aren't seen as available protection options?

**Comment by nealterrell** [comment]
In effect, yes, but it would be a dirty hack. I'd rather overhaul the prevention system -- it's several years old and we have engine improvements that can be applied now.
