### ISSUE TITLE
Sometimes you can't start new games

### ISSUE THREAD

**Issue by DominicKexel** [mtgred/netrunner#327]
I created a new game. I joined the game with a second client.

After I click *Start*, the game does not start as expected, but the clients are requested to select a deck again.

Restarting the server didn't help, I had to remove the entries in the `sessions` collection of the database; then I could join/start games as normal.

I encoutered the same issue online on Friday, 07/05/2015 (?) on Jinteki.net

**Comment by nealterrell** [comment]
I take it this is on your development server?

Typically when this happens it's because the Java game server isn't running, and if you see it happen on Live it's because the game server crashed but the Web frontend is still running. I haven't seen it happen for other reasons, but please post here if you get something reproducible.

**Comment by DominicKexel** [comment]
Yes, it was on my development server.

The game server was running. I even stopped, recompiled and restartet it several times to no avail.

Sorry, if I could reproduce it I would have posted the steps to do so.

**Comment by DominicKexel** [comment]
I close this because I think this was just an issue with my development environment.

**Comment by krasnopolsky** [comment]
Any clues as to what fixed this? I am setting up a dev server and am running into a similar issue.

**Comment by queueseven** [comment]
@krasnopolsky I nuked everything and rebuild everything from scratch. Open the dev tools of your browser, maybe you get a hint. Sometimes the cljs compiler generates invalid javascript.

**Comment by krasnopolsky** [comment]
@queueseven Scorched earth eh? Ok I will give that a shot, thanks for taking a look!

**Comment by JoelCFC25** [comment]
I experienced the same thing one time and could only cure it by the same method--delete everything, reclone the repository, then rebuild.

**Comment by krasnopolsky** [comment]
That ended up working for me, thanks all for the help.
