### ISSUE TITLE
Investigate Clojure Documentation Generators

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3274]
I think it would be interesting to look into a few kinds of automated doc generation solutions that are available to us and come up with sample outputs and hooks to a few keywords to showcase integration.

If you are interested, claim one below.

http://clojure-doc.org/articles/ecosystem/generating_documentation.html

- [ ] Codox
- [ ] Marginalia
- [ ] Cadastre

**Comment by Saintis** [comment]
I had a go trying all of these, they all threw very weird errors. I think the approach to take is to generate docs for each source file separately instead if possible.

**Comment by msbeck** [comment]
Oh, is this re: the size of some of the files or the formatting of things that mess up things like Noah's Eastwood things?

If you've had a go, I wasn't planning on getting much deeper then that kind of investigation personally, so idk if anybody wants to go further.
