### ISSUE TITLE
Zamba

### ISSUE THREAD

**Issue by jbrz** [mtgred/netrunner#3277]
Doesn't appear to be giving cred during corp turn.  Only just noticed a single instance of it and had to be pointed out by my opponent, so need to investigate further.

Was playing 419 and it occurred on 419's expose trigger, so that could be relevant as well?  Will update with more info after I have a chance to test

**Comment by JoelCFC25** [comment]
It's currently `(gain :credit 1)` and almost certainly needs to be `(gain :runner :credit 1)`

**Comment by Saintis** [comment]
Is Zamba giving credits to the corp on the corp's turn perhaps?

**Comment by hiddenaway1** [comment]
Zamba does indeed give credits to the corp on the corp turn. I believe it'll happen when you decide to allow 419 to see the first card you install.
