### ISSUE TITLE
Second sub on Anansi - Runner Draw/Decline Chat Log

### ISSUE THREAD

**Issue by nickbrown10** [mtgred/netrunner#3289]
When the second sub on Anansi fires, can a prompt be added that notifies in the chat log whether the runner chooses or declines to pay 2 credits to draw a card? Currently, there is no message displayed in the chat. This leads to the corp having to ask the runner whether they decline or not before firing the 3rd sub's net damage.

**Comment by msbeck** [comment]
Seems reasonable. We can look into that.
