### ISSUE TITLE
You can start a game before the runner decided to mulligan or not.

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#329]
As the title says.

I start a game, keep my hand, and start my turn (the runner has not yet decided to keep or mulligan).

I purge viruses, and try to end my turn. I can't discard cards, and when I click at a card in my hand I draw a 7th card. Then the game is stucked at this situation.

**Comment by DominicKexel** [comment]
I think the main problem here is that when you purge virus counters on your first turn (who want's to do this, anyway?) crahses the game

**Comment by nealterrell** [comment]
Fix submitted in #1059.
