### ISSUE TITLE
Aumakua + Information Sifting

### ISSUE THREAD

**Issue by NoobusMagnus** [mtgred/netrunner#3290]
When using Information Sifting, Aumakua doesn't automatically trigger to add a virus counter, and has to be done manually.

**Comment by danhut** [comment]
Thanks.  This is noted in the implementation note in the GUI:
"Add counters manually for access outside of a run or cards that replace access like Ash"

Would need some work on replacement accesses which someone might eventually implement via #2788 one day.  In the mean time you can add a counter manually by clicking on Aumakua
