### ISSUE TITLE
Gang sign procc needs to add virus counter to installed Aumakua 

### ISSUE THREAD

**Issue by Wickedgood** [mtgred/netrunner#3292]
when gang sign is procced, one or more of them, virus counter(s) are not added to aumakua.

edit: sorry, I don't know how to add labels.

**Comment by danhut** [comment]
Thanks. This is noted in the implementation note in the GUI:
"Add counters manually for access outside of a run or cards that replace access like Ash"

Would need some work on replacement accesses which someone might eventually implement via #2788 one day. In the mean time you can add a counter manually by clicking on Aumakua
