### ISSUE TITLE
Opponent Doesn't See My Guess w/ Falsified Credentials

### ISSUE THREAD

**Issue by mwerner2113** [mtgred/netrunner#3294]
If I play Falsified Credentials, I get a prompt asking me to pick a card type, but the opponent does not see what I picked, just whether I got the five credits or not. Not a gamebreaking bug by any means but a potentially good QoL update.

**Comment by Saintis** [comment]
Should be an Easy QoL update. I believe there are other similar cards that also don't log enough.
