### ISSUE TITLE
On-access effects are not orderable

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#3298]
Ruins interaction between Kill Switch and Explod-a-palooza. Need to upgrade access/steal routines.

**Comment by NoahTheDuke** [comment]
Related to #3271 and #2968 and #1844? `:access` triggers are weird right now, especially with `:no-trash` and `:no-steal` firing before `:access` instead of after.

**Comment by NoahTheDuke** [comment]
Closed via #3428.
