### ISSUE TITLE
Caissa / Rook dupe bug

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#330]
![rookfactory](https://cloud.githubusercontent.com/assets/6743892/8514350/a33b9e5c-2385-11e5-9d80-75f4c9921f8b.png)

I don't know what caused it, but after moving the Rook from the Pup to the HQ ice, there was a "Ghost Rook" left on the pup. Attempting to trash it did not remove it, instead resulting in an additional "Ghost Rook".

The only thing of note I could think of here, was that I had clicked on the Rook where the Pup is beneath it and it appeared that nothing had happened (and as such, I clicked there a couple extra times).

**Comment by JoelCFC25** [comment]
I am wondering if you were experiencing some latency--I tested all the Caissa just now and moving them from one ice to another didn't result in any duplicates. Trashing them off the ice where they were hosted also worked fine.

**Comment by Quarg** [comment]
I don't remember experiencing any notable lag or latency issues; and my opponent also saw these duplications.

**Comment by JoelCFC25** [comment]
We'll close this one for now. If it keeps happening (hopefully reproducible), add a comment and we'll reopen it.
