### ISSUE TITLE
Guru Davinder + Additional Cost Net Damage

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3304]
![screen shot 2018-04-11 at 9 38 29 am](https://user-images.githubusercontent.com/2982395/38638219-3840d11e-3d93-11e8-8b7a-1fbb4b2e6136.png)

The net damage from Ben Musashi was accepted as a condition to steal City Works, but was actually dealt instead of being prevented by Guru. It says it prevented it, but it then prints the cards lost due to Ben. The agenda was stolen when the additional cost being prevented should have prevented the steal.

Guru needs to prevent all damage from additional costs (and original costs, of any accumulated type) and then the stealing of the agenda needs to be prevented.

**Comment by danhut** [comment]
Fixed here but not live. 
https://github.com/mtgred/netrunner/pull/3250
