### ISSUE TITLE
Always agenda flooded as corp

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#331]
This might not be actually an issue, but in the past week every single time I play a corp, in the first 10 cards I usually see 4-5 agendas or more (my decks run 9-10 agendas in 49 cards). I don't know how shuffle works on your site or if there were any changes to it, but if possible, can you look into if it's my luck or something actually wrong with shuffling?

**Comment by mtgred** [comment]
Decks are shuffled with standard shuffle function provided by Clojure. So unless there is a bug there, your decks should be well shuffled.

You are also free to shuffle your deck manually before you start a game if you really want. :)
