### ISSUE TITLE
Enhancement: Rashida Jaheem reminder for start of turn

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#3318]
Like the campaigns and various other cards that pop up the "reminders" for the corp for start of turn triggers, I think it'll be good to have the same added to Rashida. I assume this is the code that needs to be added to the card:

`:derezzed-events {:runner-turn-ends corp-rez-toast}`

**Comment by Saintis** [comment]
An easy fix for anyone wishing to start contributing.
