### ISSUE TITLE
thinking button

### ISSUE THREAD

**Issue by prozz** [mtgred/netrunner#332]
it would be helpful if there was a button or some keyboard shortcut to notify my opponent im actually not disconnected but taking my time thinking. button/shortcut will encourage people to use it. not a lot of guys type 'thinking' in chat box otherwise. 

regards
PR

**Comment by eah13** [comment]
+1 nice idea.  Implementation detail: could be active only while clicked and held to prevent it getting turned on and forgotten

**Comment by bmatsuo** [comment]
I would like this, as I am a new player that is regularly surprised by previously unknown cards. Sometimes my whole plan is gets messed up and I need to think for a while. I think it would work better as a one time message, like a chat macro.

I don't think the button needs to have active/inactive states. I would prefer it as an emote-style message that is echoed to the chat log whenever it is clicked. The player can click it every 10-30 seconds -- as they realize they are still not ready -- to continue letting their opponent that they haven't disconnected.

> bmatsuo starts his turn
> _bmatsuo is thinking_
> bmatsuo spends :click to play Hedge Fund.

**Comment by NoahTheDuke** [comment]
Taken care of with #4759
