### ISSUE TITLE
Find the Truth and Equivocation triggers

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#3326]
Find the Truth now triggers automatically before Equivocation. Perhaps this is my misunderstanding of the rules, but the triggers used to be ordered manually, allowing the runner to use Equivocation first, then FtT (especially relevant with RNG Key).

**Comment by JoelCFC25** [comment]
This was broken by the attempt to fix Find the Truth + Marilyn Campaign here:  f8ee42

**Comment by groenkaaf** [comment]
Not actually fixed.

**Comment by JoelCFC25** [comment]
The fix is not yet live.

**Comment by groenkaaf** [comment]
Aha! Sorry sorry. Thanks for working on the site.
