### ISSUE TITLE
Scheherezade - hosting things not installed as a click from grip

### ISSUE THREAD

**Issue by MasterAir** [mtgred/netrunner#333]
If an install isn't standard (i.e. click - install program from grip) then you cannot host the installed program on Scheherezade. One alternative implementation would be the ability to use scheherezade on an installed program to host said program and increment the runners credits by 1. Rely on the players to only use the ability on programs that have just been installed.

This crops up with Hayley Kaplan, SMC, Scavenge, Retrieval Run, Clone Chip, Street Peddler (once that's implemented), Savoir Faire.

I'm not sure whether or not this should be associated with this issue. It seemed different enough to me to create a new issue. https://github.com/mtgred/netrunner/issues/315

**Comment by mtgred** [comment]
Thanks for reporting the issue. The option to host an installed card will be added to "install and host" cards such as Scheherazade.

**Comment by JoelCFC25** [comment]
Implemented by d8e25ca42034a791ad1976f9e6a9241f7659e7b7!

**Comment by mtgred** [comment]
It's live now.
