### ISSUE TITLE
Trope frees up 2 MU instead of 1 MU when its ability is used

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#3335]
When you remove Trope from the game to recur X cards to Stack, the card is coded to give the runner 1 MU and remove itself from the game. The problem with this is that getting removed from the game also gives the runner 1 MU back, resulting in 2 MU gained from removing a 1 MU program.

**Comment by JoelCFC25** [comment]
Introduced by #3032. Just needs Trope to stop doing the adjustment itself.
