### ISSUE TITLE
Sacrificial Construct vs Purge

### ISSUE THREAD

**Issue by SugoiFactory** [mtgred/netrunner#3336]
When the corp purges virus counters, cards such as Clot, eXer, and Tapwrm get triggered to trash themselves, which can be prevented with the use of Sacrificial Construct. However, using Sacrificial Construct to prevent the trashing of any one of them results in everything else after that prompt that might've gotten trashed to also prevent getting trashed, even if you don't do any further SacCon usage.

**Comment by JoelCFC25** [comment]
Seems identical to #3329 and should be taken care of by the not-yet-live fix for that.

**Comment by nealterrell** [comment]
The fix should now be live.
