### ISSUE TITLE
Sunny Lebeau alt card

### ISSUE THREAD

**Issue by jordanearle** [mtgred/netrunner#3339]
Any plans to add Sunny Lebeau's promo to the list of available alt-arts?

Also noticed Magnum Opus is missing, a scan for it can be found here: https://imgur.com/r/Netrunner/ppYk9XK

**Comment by JoelCFC25** [comment]
For missing alt-arts, we have to be supplied with the art asset, as you did with Magnum Opus.

**Comment by jordanearle** [comment]
Here's a high-res scan of Sunny. Hope that works. https://i.imgur.com/LfDIFz4.jpgOn Apr 18, 2018 5:42 AM, Joel Koepp <notifications@github.com> wrote:For missing alt-arts, we have to be supplied with the art asset, as you did with Magnum Opus.

**Comment by jordanearle** [comment]
Any update on adding these two?
