### ISSUE TITLE
By Any Means turns off after playing Levy AR Lab Access

### ISSUE THREAD

**Issue by Snake-e-y-e-s** [mtgred/netrunner#3341]
Has happened twice, 

Click 1 By Any Means, https://netrunnerdb.com/en/card/21001 run normally or with Multiaccess and it triggers properly.  Hit levy, https://netrunnerdb.com/en/card/03035 Run again, Stops triggering.  This has caused me to steal agendas that were supposed to be trashed each time.

**Comment by NoahTheDuke** [comment]
Run again on a separate turn? Or run again on the same turn?

**Comment by JoelCFC25** [comment]
This is because the `:pre-access-card` event is registered to the played copy of By All Means expected to be in the discard--this bit:  `(assoc card :zone '(:discard))`. 

After Levy-ing, it's not there anymore, it's in the stack.

**Comment by presheaf** [comment]
I think this and #3377 were fixed in #3911 by b9b817 , which used a hack to circumvent the issue Saintis brings up. I haven't tested these exact issues, though.

**Comment by NoahTheDuke** [comment]
Should be closed by #4434
