### ISSUE TITLE
Aumakua + Obokata + Imp

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3347]
I accessed an Obokata from HQ, and when it was asking to pay the cost of 4 cards, I Imp trashed it. I got a turtle counter.

**Comment by nicohasa** [comment]
Imp + Aumakua does not work in general, agenda or not. If you run a remote with Aumakua and imp the card, you get Aumakua counter.

**Comment by mikeprosser** [comment]
This is related to https://github.com/mtgred/netrunner/issues/2968 about how imp also has issues with Maw firing, looks like a fix is WIP but it's complicated

**Comment by Saintis** [comment]
Looks like it was fixed by #3480
