### ISSUE TITLE
Whispers in Nalubaale Card implementations

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3348]
Rumored to be released 3 May 2018.

Checked off means that the card is merged into master.
Place a link to the pull request next to the card when it is pushed.
If you wish to claim a card, make a comment on this issue or put your name next to the card.

- [x] Freedom Khumalo: Crypto Anarchist (#3414)
- [x] Trypano (#3398)
- [x] Contaminate (#3352)
- [x] Embezzle (#3385)
- [x] Slipstream (#3402)
- [x] Laamb (#3397)
- [x] Gebrselassie (#3396)
- [x] Compile (#3387)
- [x] Logic Bomb (#3413)
- [x] Jackpot! (#3392)
- [x] Remote Enforcement (#3401)
- [x] Kamali 1.0 (#3389)
- [x] Warden Fatuma (#3407)
- [x] Viral Weaponization (#3355)
- [x] Envelope (#3382)
- [x] Mwanza City Grid (#3372)
- [x] Standard Procedure (#3350)
- [x] Intake (#3383)
- [x] Masvingo (#3412)
- [x] Overseer Matrix (#3359)

**Comment by presheaf** [comment]
I can take Trypano.

**Comment by presheaf** [comment]
I can do Remote Enforcement.

**Comment by NoahTheDuke** [comment]
Logic Bomb: #3413

**Comment by presheaf** [comment]
Unless I'm missing something, that's all of them. Well done, all!
