### ISSUE TITLE
Marcus Batty misspelled in Deck Builder

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#335]
The card Marcus Batty is labeled as "Markus Batty" in the Deck Builder (making imports from deck building sites not work correctly).

**Comment by JoelCFC25** [comment]
I think all card data is pulled directly from NetrunnerDB in JSON. This card was misspelled for awhile on NRDB when spoilers of the newest datapack were still dribbling out, so it's probably an artifact of that.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
