### ISSUE TITLE
Student Loans Misfiring

### ISSUE THREAD

**Issue by bobiojimbo** [mtgred/netrunner#3354]
Student Loans can misfire or fire multiple times under certain conditions. Noticed that it would fire when Beth Kilrain-Chang gave an extra click, and when Find the Truth would reveal drawn cards. I believe it fired multiple times (twice, each) when Beth first gave an extra click. When this happened, there were copies of some of the cards revealed in the Heap. For example, this happened when an Employee Strike was revealed and there was a copy in the Heap.
![studentloanmisfiring](https://user-images.githubusercontent.com/38572956/39076191-c26f88fe-44ae-11e8-95a8-76b2b98f57a2.PNG)

**Comment by jwarwick** [comment]
I can't reproduce this in a dev environment. I thought it might also be something with `Sports Hopper`, `Beth`, or `Find the Truth`, but couldn't get any combination of them to misbehave either.

I wonder if there was something else in the Heap that was being compared against.
