### ISSUE TITLE
Auto-pumping icebreakers implementation

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#336]
I am working on the auto-pumping functionality for icebreakers suggested in #259 . This is what I have so far: 

![curtain1](https://cloud.githubusercontent.com/assets/10083341/8505138/b154cbce-2193-11e5-9dcd-b419abbbbf52.PNG)
![curtain2](https://cloud.githubusercontent.com/assets/10083341/8505139/b155d2d0-2193-11e5-8e57-156f7d08d976.PNG)

There is some technical trickery to get this to work that I won't get into here... it involves self-modifying a card's Abilities vector to insert or remove the "match strength" pseudo-ability when appropriate. I was able to implement this using the event-handling system we already have, so there are very few changes to the core... but now I'm trying to find the best way to incorporate the system into all the icebreaker code.

I have created an event handler `breaker-auto-pump` ([here](https://github.com/nealterrell/netrunner/blob/auto-pump/src/clj/game/cards.clj#L13)) that needs to be hooked up to 5 events for the system to work. That would mean adding event handlers manually to every icebreaker so they all look something like this:

```clojure
"Corroder"
{:abilities [{:cost [:credit 1] :msg "break 1 barrier subroutine"}
             {:cost [:credit 1] :msg "add 1 strength" :effect (effect (pump card 1)) :pump 1}]
  :data {:breaks ["Barrier"]}
  :events {:encounter-ice breaker-auto-pump :pass-ice breaker-auto-pump
           :run-ends breaker-auto-pump :ice-strength-changed breaker-auto-pump
           :breaker-strength-changed breaker-auto-pump}}
```

Not the end of the world, but tedious, and if the system should need expanding to include new events.... ugh. So I then wrote a helper function `auto-icebreaker` to merge the necessary events into a card definition ([here](https://github.com/nealterrell/netrunner/blob/auto-pump/src/clj/game/cards.clj#L27)). This turns Corroder into

```clojure
"Corroder"
 (auto-icebreaker ["Barrier"]
   {:abilities [{:cost [:credit 1] :msg "break 1 barrier subroutine"}
                {:cost [:credit 1] :msg "add 1 strength" :effect (effect (pump card 1)) :pump 1}]})
```

I think this works well. It will mean updating all icebreakers with the `auto-icebreaker` line and the closing `)`, and marking all "pump" abilities with `:pump _X_`, but after that small bit of tedious work the whole system should adapt well to future changes.

@mtgred, what do you think of this? Particularly incorporating the events into each icebreaker. Is there something more Clojurely I should look into? (If this was OOP, for example, I would probably introduce a new base class `AutoIcebreaker` and then derive icebreaker programs from that class.) 

@JoelCFC25, would you be up for helping me incorporate this into the ~50 icebreakers?

**Comment by JoelCFC25** [comment]
I'll for sure do some copy/paste grunt work assuming this plan gets a :+1: from the boss.

**Comment by mtgred** [comment]
The helper approach looks good. You can go ahead.

**Comment by nealterrell** [comment]
Alrighty @JoelCFC25, let's give this a shot. I've synced my changes to https://github.com/nealterrell/netrunner/ branch "auto-pump". If you have some free time, check out the change to Gordian Blade and Corroder, then try modifying a few icebreakers and submit a change to my repo. In general, you will be taking the body of an icebreaker's definition and wrapping it in an `(auto-icebreaker)` function call.  You will also be annotating "pump" abilities with a key `:pump X`, where X is the amount the ability pumps by. We will only do this for pumpable breakers.

**Comment by JoelCFC25** [comment]
What will the first line of Crypsis and Eater look like? Will it have to include the oddball subtypes to be able to autopump on them?

`(auto-icebreaker ["Barrier" "Code Gate" "Sentry" "Trap" "Mythic]`

**Comment by nealterrell** [comment]
Let's go with just "All". I will amend the code to reflect that option.

**Comment by JoelCFC25** [comment]
Sorry to ask a follow-up: will `(auto-icebreaker ["Tracer"]` work for Gingerbread and `(auto-icebreaker ["Destroyer"]`work for Sharpshooter, or should I leave these alone for now?

**Comment by nealterrell** [comment]
Those should indeed work as you expect.
