### ISSUE TITLE
Fisk + Daily Business Show

### ISSUE THREAD

**Issue by The-Calamity** [mtgred/netrunner#3361]
When Fisk runs and forces the corp to draw a card it seems as if the access is queued up directly after. If the corp has Daily Business Show out this messes with the order of access and prompts a 2nd access.

This is a copy paste from J.net (name of opponent changed)

The Calamity uses Laramy Fisk: Savvy Investor to force the Corp to draw 1 card.
//// uses Daily Business Show to draw additional cards.
The Calamity accesses Mumbad Virtual Tour from HQ.
//// uses Daily Business Show to add 1 card to the bottom of R&D.
The Calamity accesses BOOM! from HQ.

I think this happens with Jinja City Grid as well, as i noticed some weird stuff last night with it, but I wasn't thinking about it enough to document it.

Hope this helps, this is my first time reporting a bug.

**Comment by JoelCFC25** [comment]
Early hunch is to focus on the DBS `:post-corp-draw` event handler which is uses delayed completion but never actually calls `effect-completed`.

**Comment by nealterrell** [comment]
The issues is actually with Fisk. Now that `draw` is awaitable, his `yes-ability` needs to be delayed completion and pass its `eid` to `draw`.
