### ISSUE TITLE
Upgrade prevention effects to have conditional logic

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#3363]
We need to update the prevention logic to handle things like No One Home.  The idea is to not show the prevention window if the only cards that can prevent can't actually act because of once-per-turn or other restrictions

This can be taken from Recon Drone where I implemented this already - but did not generalise the solution.

I think it would take the form of a `can-prevent?` function much like `can-pay?` and then have each card insert itself if this check returns true.

**Comment by Saintis** [comment]
Could we add a `:req` key to each prevent map to have a 5-fn to check if it can prevent?

So Feedback Filter would be `:prevent {:damage [:net :brain] :req (req true)}` cause it can always prevent. And No One Home would use `:req` to check it's the first case of tags / damage

**Comment by danhut** [comment]
Yes! Feedback filter looks like this now...  just one bit to do.  I decided I don't like the vector as we have some cards where the :req might very in future.

```clojure
   "Feedback Filter"
   {:prevent {:damage {:net {:req (req true)}
                       :brain {:req (req true)}}}
    :abilities [{:cost [:credit 3] :msg "prevent 1 net damage"
                 :effect (effect (damage-prevent :net 1))}
                {:label "[Trash]: Prevent up to 2 brain damage"
                 :msg "prevent up to 2 brain damage"
                 :effect (effect (trash card {:cause :ability-cost})
                                 (damage-prevent :brain 2))}]}
```
