### ISSUE TITLE
Because I Can (21066) shuffle effect should be optional

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#3367]
"Make a run on a remote server. If successful, instead of accessing cards, you _may_ force the Corp to shuffle all cards in that server into R&D."

The "force the Corp to shuffle all cards installed in that server into R&D" effect should be optional - the runner should have the option, on succesful run, to not fire the effect but instead access cards normally.

The current implementation does not give the option to access - on succesful run, all installed cards in the remote are automatically shuffled into R&D.

**Comment by NoahTheDuke** [comment]
Easy fix for someone: remove `:mandatory true`!

**Comment by ben-albon** [comment]
@NoahTheDuke - Thanks!

If this looks good, and you don't think I've missed anything, I'll submit a pull request:

https://github.com/ben-albon/netrunner/commit/ac6480a5d615f66cfcb08270acc7464a86c437a3
https://github.com/ben-albon/netrunner/commit/afb11c7df6dfbb9d1e156cbab3bf5ad8e4d03ef2

**Comment by Saintis** [comment]
This will be fixed once code is deployed. Good work!
