### ISSUE TITLE
By any means not working with counter surveilance

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#3377]
![image](https://user-images.githubusercontent.com/18687557/39390530-09640dbc-4a53-11e8-8353-96afe0576d82.png)
Log of game: Below show after playing by any means, the cards accessed by counter surveilance did not work. 
vincentkbl takes 1 tag to place 2 virus counters on God of War.
vincentkbl started their turn 21 with 28  and 4 cards in their Grip.
vincentkbl spends  and 2  to play By Any Means.
vincentkbl spends  and 1  to install Counter Surveillance.
titonosfe uses Housekeeping to force the Runner to trash I've Had Worse from their Grip.
vincentkbl uses Trope to shuffle Exclusive Party, By Any Means, Exclusive Party, I've Had Worse into their Stack.
vincentkbl spends  to use Counter Surveillance to run R&D and trashes Counter Surveillance.
titonosfe spends 4  to rez Hortum.
vincentkbl spends 3  to install Black Orchestra.
vincentkbl spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
titonosfe has no further action.
vincentkbl continues the run.
vincentkbl indicates to fire all subroutines on Colossus.
titonosfe uses Colossus to give the Runner 1 tag.
titonosfe uses Colossus to trash 1 program.
titonosfe uses Colossus to trash Black Orchestra.
titonosfe uses Skorpios Defense Systems: Persuasive Power to remove Black Orchestra from the game.
titonosfe has no further action.
vincentkbl continues the run.
titonosfe spends 3  to rez Cyberdex Virus Suite.
titonosfe uses Cyberdex Virus Suite to purge virus counters.
vincentkbl uses Acacia and gains 14.
vincentkbl indicates to fire all subroutines on Mausolus.
titonosfe uses Mausolus to gain 1 .
titonosfe uses Mausolus to do 1 net damage.
vincentkbl trashes Mars for Martians due to net damage.
titonosfe uses Mausolus to give the Runner 1 tag.
titonosfe has no further action.
vincentkbl continues the run.
titonosfe has no further action.
vincentkbl uses Knobkierie to place 1 virus counter on God of War.
vincentkbl uses Counter Surveillance to access up to 16 cards by paying 16 .
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl
vincentkbl
huh?
vincentkbl
vincentkbl
i tot trashing
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
!vincentkbl uses a command: /close-prompt
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
vincentkbl accesses an unseen card from R&D.
!vincentkbl uses a command: /close-prompt
vincentkbl accesses an unseen card from R&D.

**Comment by Saintis** [comment]
I think this happened because BAM was shuffled into Stack with Trope, breaking the card lookup thingy. I think that might be the case until we get a better system to handle "card effects independent of cards".

**Comment by Saintis** [comment]
Same core issue as #3341

**Comment by NoahTheDuke** [comment]
Should be closed by #4434
