### ISSUE TITLE
Multiple copies of Warroid Tracker tripping over their own triggers.

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3386]
I don't know if this is related to #2767  at all?

In a few games this issue has come up where with a server with multiple copies of Warroid Tracker (and sometimes Ash too, although I'm not sure if this was _always_ the case), the sequence of events went like this:

(* Ash trace where present)
* Runner accesses and trashes Warroid Tracker (should trigger as many Warroid Tracker triggers as are present)
* Trace for the first Warroid trigger
* Runner trashes first of two cards from prompt
* Runner can't trash second card, trace for second Warroid Tracker trigger barges in instead

I'm not entirely sure of the sequence after this second trace fires, having only seen it from the Corp side, but apparently it is very annoying, requiring either multiple /close-prompts or the whole thing seizing up.

It seems that the trace for subsequent copies of Warroid Tracker should wait until all cards have been trashed from the first trigger and this doesn't happen at present. I'm assuming that will clear it up?

**Comment by HubGitAccoutn** [comment]
Oh I forgot, in one instance after the first Warroid trace, Runner trashing one card only, then the second trace, /close-prompting out a couple of levels at the Runner's request this then even kicked me (as Corp) back to the "Actions before run is successful" dialogue for some weird reason.

**Comment by HubGitAccoutn** [comment]
Update: Just had this also happen in another game over multiple card trashes this time, instead of multiple Warroid Trackers triggering from a single card trash, in case that helps diagnose the problem.

Server: Ash, Warroid, Warroid, MCA Austerity Policy, Breaker Bay Grid.

Runner beats Ash trace.
Runner accesses a Warroid, trashes it triggering two Warroid traces.
Runner wins the first trace. (All good so far)
Runner loses the second trace.
Runner trashes only one card to the lost Warroid trace.
Runner now accesses a new card: MCA Austerity Policy and trashes this.
A new trace fires for the remaining untrashed Warroid Tracker.
Everything seizes up in an endless loop of prompts that we can't /close-prompt our way out of.

**Comment by Saintis** [comment]
Looks like there is delayed-completion problems with the continue ability in Warroid tracker.

Warroid could maybe use a targetting prompt to select the 2 cards to trash instead of the current prompt chain implementation.

**Comment by NoahTheDuke** [comment]
I recently cleaned up warriod tracker. Does this still happen?
