### ISSUE TITLE
Maw not triggering

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3388]
Just flagging up a case when Maw didn't trigger when it should have.

Situation:

Alice as the ID with Maw and Archives Interface installed does something on her side of the board for a couple of clicks, then runs archives third click. The Corp trashes an Obokata to her ability and she accesses archives seeing, but not stealing, the Obokata in the bin and removing from game some other card with Archives Interface. Then last click she runs HQ, accessing the sole card in HQ, another Obokata which she declines to steal. As the first card accessed not in Archives for the turn, this should have triggered Maw to send it to the bin, but it didn't trigger.

They're the cards I remember that seem relevant, hope that is helpful!

**Comment by Saintis** [comment]
Yep, that would happen when you get a `:no-steal` trigger from Archives before you run a different server. Will be tricky to get working correctly I think..

**Comment by HubGitAccoutn** [comment]
Just an update, in case this helps. I've just seen a different situation where Maw fired when it shouldn't in this case!

(Corp) uses Azmari EdTech: Shaping the Future to name Event.
(Runner) started their turn 6 with 7  and 4 cards in their Grip.
(Runner) uses Daily Casts to gain 2 .
(Runner) spends  to use Liberated Account to gain 4 .
(Runner) spends  to make a run on Archives.
(Corp) spends 6  to rez Fairchild 3.0.
(Runner) spends 3  to install Black Orchestra.
(Corp) has no further action.
(Runner) spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
(Runner) spends 3  to use Black Orchestra to add 2 strength and break up to 2 subroutines.
(Runner) trashes Black Orchestra from their Rig.
(Runner) continues the run.
(Corp) has no further action.
(Runner) uses Alice Merchant: Clan Agitator to force the Corp to trash 1 card from HQ.
(Runner) accesses Cyberdex Virus Suite from Archives.
(Corp) uses Cyberdex Virus Suite to purge virus counters.
(Runner) spends  to make a run on R&D.
(Corp) has no further action.
(Runner) accesses an unseen card from R&D.
(Runner) pays 1 to trash Rashida Jaheem from R&D.
(Runner) uses Maw to force the Corp to trash a random card from HQ.
(Runner) spends  to make a run on R&D.
(Corp) has no further action.
(Runner) accesses an unseen card from R&D.
(Runner) is ending their turn 6 with 3  and 4 cards in their Grip.

The first cards accessed were in Archives. No unstolen agenda trigger this time, although there was a Cyberdex. The first non-archive access was the Rashida on R&D on click three, and Maw triggered this time, even though Rashida was trashed. Maw ought to have first triggered on the subsequent R&D access (no steal or trash) on click four.

**Comment by NoahTheDuke** [comment]
This happened recently?

**Comment by HubGitAccoutn** [comment]
Yep, earlier today.
