### ISSUE TITLE
Research Grant on-score effect does not trigger if no other copies are installed

### ISSUE THREAD

**Issue by CelestialSpark** [mtgred/netrunner#3390]
Simply put, the corp cannot trigger the on-score effect of Research Grant at all if no other copies are installed at the time the agenda is scored. This is an issue because of Team Sponsorship, which resolves at the same time. A legal play would be to score Research Grant, resolve Team Sponsorship to install a copy of Research Grant, then resolve the scored Research Grant to score the newly installed one. However, Jinteki.net does not check if Research Grant is installed after Team Sponsorship resolves, giving no opportunity to immediately score it.

If a second copy of Research Grant _is_ installed when the first is scored, then a third can be installed and immediately scored using Team Sponsorship, as the option to resolve simultaneous effects in the order of the corp's choice will correctly appear.

Additionally, when scoring Bifrost Array while Research Grant is scored, options for simultaneous effects will correctly appear and allow the corp to install a copy of Research Grant using Team Sponsorship before resolving Bifrost Array and in turn the previously scored Research Grant.

This issue is extremely trivial to reproduce: simply score Research Grant while Team Sponsorship is rezzed and a Research Grant is present in HQ or Archives, but no Research Grants other than the one being scored exist in remote servers. No option to resolve Research Grant's effect will be given even if one is installed during the agenda-scored triggers phase.

**Comment by Saintis** [comment]
So I see two choices to get this working:

1. Remove the checks for installed Research Grants and just always show the interaction prompt.
2. Expand the interactivity system to look for types of cards, in this case cards that can install on score (Team Sponsorship).

**Comment by CelestialSpark** [comment]
Option one should be fine in this case. This is a very specific instance of the current implementation of simultaneous triggers lacking--Team Sponsorship's interactions with other cards should be fine. Research Grant isn't played enough to warrant revisiting for specific logic checks every time a new card that allows an install on agenda score is released.

**Comment by nealterrell** [comment]
Or; 

3. Remove the `:req` on Research Grant so that it always fires. In the ability, resolve an optional prompt if there is another copy of Grant installed. Make this `:interactive true`. 

The simultaneous prompt system checks each handler's `:req` to see if it should be put into the "choose this or that" menu. If Research Grant's req is removed, then it will always show up in the menu, and when it is finally resolved, we can show the optional prompt in an intelligent way.
