### ISSUE TITLE
Project Ares scoring issue

### ISSUE THREAD

**Issue by OlariV1** [mtgred/netrunner#3394]
Project Ares was advanced to 5 and then scored.  After trashing an installed card as runner, the corp won the game even though they should have only had 6 agenda points.

**Comment by danhut** [comment]
We will need more information to look at this - ie. logs and screenshots.  Do you have anything?

**Comment by OlariV1** [comment]
I don't have a screenshot. Where would logs be if they are recorded?

**Comment by JoelCFC25** [comment]
There aren't stored logs, you would've had to copy/paste at the time. Things that would be important to know include:  what identities were used by both players, which card was trashed, what other active cards were in play at the time, etc.

**Comment by OlariV1** [comment]
Ok. I didn't record that information. Next time I encounter a bug I'll make sure to gather all the info for troubleshooting. Thanks for a great site.
