### ISSUE TITLE
Magnum Opus and Sunny promo scans for donator alt-arts

### ISSUE THREAD

**Issue by jordanearle** [mtgred/netrunner#3395]
Hi guys,

Here are some scans for the missing promos:

https://i.imgur.com/ppYk9XK.jpg - Mopus
https://i.imgur.com/LfDIFz4.jpg - Sunny

**Comment by nealterrell** [comment]
Does anyone have time to convert these to PNG with transparent rounded corners?

**Comment by nealterrell** [comment]
These will be active on the next reset.
