### ISSUE TITLE
Gang Signs + Friday Chips + IMP + Kim trashing = bad

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3399]
Scenario:
gang sign #1 access, accessed a card prompt shows, clicked to imp, friday chip #1 prompt and placement, previous access prompt that I click ok, friday chip #1 prompt, then gang sign #2, click access card from hand, then kim auto trashed, friday #1 prompt, accessed card OK clicked, friday #2 prompt.

Runner is now prompted with "continue" or "jack out", even though they were never in a run. Corp is also in a run prompt.

I would expect that the Friday Chips happen one right after the other instead of having to click "OK" from the "X is accessed" prompt, as well as it end gracefully instead of being stuck in a run.

@JoelCFC25  says "I would say it's this line in Ed Kim:   `(swap! state assoc-in [:run :did-trash] true)`. It should do this conditionally, i.e. only if a run exists" and that "Friday Chip's `:runner-trash` event handler is not using delayed completion"

**Comment by msbeck** [comment]
Confirmed the simplest case - any time Kim trashes an operation from a Gang Sign access it thinks it's in a run and you get stuck in that prompt.

**Comment by NoahTheDuke** [comment]
Does this still happen?

**Comment by KubikM161** [comment]
Happened to me several times today, gang sign + Kim trash and I get prompt about continue run. It's possible to jack out.

**Comment by NoahTheDuke** [comment]
Thank you for the report! I’ll take a closer look
