### ISSUE TITLE
Error messages when using prompt-(choice/select) incorrectly are unhelpful

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#3404]
When writing a test, I sometimes get a very strange error I can't for the life of me figure out until I realize that I'm using prompt-choice and prompt-select incorrectly (to say nothing of prompt-card!). Given that one expects a string while the other expects a card (I think), I think it should be possible to make slightly more informative error messages. To keep things simple and not force anyone to relearn anything, I was thinking of just prepending an assertion verifying that the thing you're passing into prompt-(choice/select) is a (string/map), so that if one does make a mistake, an error message like "you're using the wrong function" is thrown. It should be pretty simple, I just need to look through the uses of these functions and make sure they aren't used more generally than I think.

**Comment by presheaf** [comment]
Can't seem to assign this issue to myself, but yeah, I was thinking this would be managable for me.

**Comment by danhut** [comment]
An opportunity to use clojure.spec ?  (my new area of interest).
From playing around with it recently I think it should fit well.

There might be other ways of doing the assertion - but spec is new & shiny.

**Comment by presheaf** [comment]
Reading a bit about it, I'm interested in trying it, at least. I don't know enough to have an opinion about whether it's a huge improvement.

Regarding this, I put it on hold until Noah's stuff is merged, as it's related.

**Comment by presheaf** [comment]
This one got fixed by Noah eventually.
