### ISSUE TITLE
Enhancement: Consume/Friday Chip implementation Consistency

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#3408]
Friday Chip and Consume have the same trigger condition for adding a virus counter. The current card implementation for Consume contains an extra prompt asking for number of counters to add. I recommend copying the simpler Friday Chip implementation of "Add counter Yes/No" to Consume.

**Comment by nealterrell** [comment]
I believe this was done to deal with bulk-trash effects like Apocalypse, to not bombard the runner with a Yes/No prompt for each trashed card. It would take some fiddling to show a Yes/No for single-trash effects but it could be done.

**Comment by nicohasa** [comment]
Can confirm Consume is written to handle Apocalypse (I think there are no other bulk-trash effects tbf).
I can fix Friday chip to also work correctly with Apocalypse, possibly add a yes/no if there's only one counter to add.

**Comment by Eric-Fletcher** [comment]
Is there any way to "remember" the choice, for matchups where you are "always" going to say yes?

Perhaps a menu option on the card to toggle Always YES/Ask each time?

**Comment by nicohasa** [comment]
Should not be too hard to add. Will look into it.

**Comment by nicohasa** [comment]
Toggle button added to #3415!
