### ISSUE TITLE
Shipment from Mirrormorph triggers Asa Group ID ability after the second install, with incorrect prompt

### ISSUE THREAD

**Issue by CelestialSpark** [mtgred/netrunner#3409]
When playing Shipment from Mirrormorph as the ID Asa Group: Security Through Vigilance as the first install of the turn, the following happens:

1. You are prompted to install a card using Shipment from Mirrormorph, then asked where to install it.

_(If you install a card, continue.)_

2. You are prompted to install a non-agenda card using the Asa Group ID ability. This card may be an agenda (or any other installable card) and you will be asked where to install it. (In other words, you're making the second Mirrormorph install, with the wrong prompt.)

_(Whether you install a card or not, continue.)_

3. You are prompted to install a card using Shipment from Mirrormorph. This card cannot be an agenda, and once selected, will immediately be installed in or protecting the server where card 1 was installed. (In other words, it behaves as the Asa ID ability, with the wrong prompt, triggering off the first card installed, at the wrong time.)

_(If you installed a card in step 2, continue, regardless of whether you installed a card in step 3.)_

4. You are prompted to install a card using Shipment from Mirrormorph, then asked where to install it.

This results in extreme confusion on the user side, often leading to the card installed in step 3 trashing the card installed in step 1 since it attempts to force itself into the same server. Additionally, since step 3 and 4 have identical prompts, clicking "done" without installing in step 3 visually appears to do nothing, even though it really takes you to step 4.

The issue is easy to reproduce and absolutely consistent in this pattern, regardless of the types of cards being installed, cards in play, turn number, or servers involved. All that is required is to play the Asa Group ID, then play Shipment from Mirrormorph and install cards before triggering the ID ability on a given turn.

Note that Shipment from Mirrormorph behaves correctly when playing this ID if the ID ability has already been triggered on the current turn, simply allowing three sequential installs in any location and terminating the first time "done" is chosen without an install.

**Comment by CelestialSpark** [comment]
The text shown in the second prompt is correct (the Asa group prompt), but the behavior is reversed with that of the third prompt. 

For the second card, any installable card including an agenda may be selected, which prompts the user to select a server for the install, and the card will be placed in the selected server. This is contrary to the displayed prompt that the install must be a non-agenda card for the optional Asa group install.

For the third card, the text box indicates that it is a Mirrormorph install, but selecting an agenda does not work. Upon selecting any other card, it is immediately installed in the same server as the first install was with no further prompts, possibly trashing an agenda or asset installed in that server if the new card is an asset. In other words, it behaves entirely like the Asa group install should, except with the wrong prompt and occurring out of order.

If the second install is skipped, the logic still proceeds to the third card (as it should), but not the fourth, regardless of whether the third card is installed. This is presumably because the second card is really the second Mirrormorph install, and there would be no need for a third Mirrormorph install if there wasn't a second.

**Comment by Eric-Fletcher** [comment]
This also happens when scoring a Successful Field Test.

There is similar mixed behavior with any ID if you score a Director Ha's Pet Project while you have a Team Sponsorship rezzed (If you pick the Project to resolve first, it prompts you for the 1st Project card, then a Team Sponsorship card, then the other two Project cards)

**Comment by nicohasa** [comment]
I'm working on fixing this btw, but have introduced a new bug with Asa + Eden Fragment, so not quite done yet.

**Comment by Saintis** [comment]
Should have been fixed by #3513
