### ISSUE TITLE
Feature: Activity sounds

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#342]
Would it be possible to have a sound when the other player does something?

**Comment by DominicKexel** [comment]
Seems like a good idea to me. 
Play a sound everytime someone spends a click for an action, so the game catches your attention again. Different actions could make different sounds.

**Comment by bozmond** [comment]
I'm a professional sound designer and happy to contribute to this feature. 

I think some simple clean sounds for the basic major actions would be good and all that is needed. If this feature was to be implemented, it should absolutely come with a user-based preference to disable sounds. Some people just won't want them!

I think the sounds could be:
- click (different for corp & runner)
- begin run
- score
- turn end (different for corp & runner)

I think the OCTGN sounds are annoying and too numerous, but also kind of charming in their jank - much like OCTGN! I don't know which of these über futuristic corps would have a squeaky door made out of cheap wood anywhere in their facilities!

**Comment by nealterrell** [comment]
I think this would be nice. @mtgred might be able to comment on how to approach the integration if you're able to produce a few demos :).

**Comment by DominicKexel** [comment]
We need an  explosion and car crash sound when someone plays Scorched Earth / Traffic Accident!

Just kidding (but that would be a cool april 1st joke or easteregg :-)

**Comment by bozmond** [comment]
Cool. I will make a bunch of demos of the content and post them up for feedback. I won't be any help with the code, but I can deliver the audio in whatever format is most appropriate.

**Comment by mtgred** [comment]
@bozmond Cool, looking forward to it.

**Comment by JoelCFC25** [comment]
Let's continue all discussion on this topic in #968.
