### ISSUE TITLE
Khumalo grants extra access when used to trash cards from R&D

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#3423]
On Zaroth, I made a deck with 3x Datasucker, 3x Slipstream in Khumalo, pitting it against a corp with 3x Ice Wall, 3x Wall of Static. When running on R&D with a loaded data sucker, it seemed that when I used freedom to trash the card I accessed, I got to access another one without needing to run again.

**Comment by NoahTheDuke** [comment]
Working on it.
