### ISSUE TITLE
Feature: Colors in Chat

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#343]
Would it be possible to assign colors to chat?

Like when there's a run the text is displayed in RED or when you get coins in BLUE etc?

**Comment by DominicKexel** [comment]
I took at shot at this. You can checkout my [branch](https://github.com/DominicKexel/netrunner/tree/colors_in_chat) or [commit](https://github.com/DominicKexel/netrunner/commit/b1939480876cbcdd279218c4cfeefdf07012259a)

Here are some silly colors:

![bild 2](https://cloud.githubusercontent.com/assets/3126597/9040737/4e3c9d12-3a04-11e5-9935-f645c47532dc.png)

When using `system-msg`, you can pass a style (which maps 1-1 to a CSS style) which is then applied to the message in the log pane (like e.g. `start-turn` or `change` or `click-draw`).

The styles that are currently used are of course only for demonstration purposes. I'm open for ideas of which style to apply to which event.

I think the messages could be further improved by providing more information (e.g. how much credits you had at the start of your turn) like OCTGN does, which would help keeping track what happened during a turn, especially if something was manually adjusted, but that's another topic.

comments & criticism welcome :-)

**Comment by zaroth** [comment]
I'm not sure this example adds to readability... Some different shades for Corp/Runner maybe, but not a whole rainbow of colors ;-)

Also the manual changes via non-prompt interface - dragging cards, +/- credits being higlighted (not necessarily with red) is a nice touch, I like it.

**Comment by erbridge** [comment]
Suggestion of colour scheme:

- Corp action: slight blue shade
- Runner action: slight red shade
- Card trashes: orange
- Manual changes: aqua
- System message: grey
- Chat: white

My thoughts for singling trashing out are to make things like server overwrites more obvious (it can be easy to miss).

**Comment by mtgred** [comment]
At the moment card names are highlighted in orange and stand out. If everything in the chat log is coloured then nothing stands out anymore.
