### ISSUE TITLE
Friday Chip has weird log message when placing virus counters automatically

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#3431]
When Friday Chip is not toggled to auto-place counters, its console log message is "... uses Friday Chip to place 1 virus counter on Friday Chip.". When it is toggled to auto-place, it seems the message is "... uses Friday Chip to place 1 virus counter on .".

**Comment by JoelCFC25** [comment]
For these kind of messages ("Players uses X to place counters on X") I like the passive usage better by using `system-msg` inside the `:effect`.

**Comment by msbeck** [comment]
I like your suggestion @joelcfc25 . It's very odd to see it say it placed it on itself by name. The passive form sounds much nicer.
