### ISSUE TITLE
Anansi "Runner may pay 2 to draw" subroutine does not wait for Runner response

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#3432]
When the Corp fires the subroutine giving the Runner the choice to pay 2 credits to draw, there is no "waiting for the Runner to choose" prompt on the Corp end, meaning it's easy to get eager and resolve the remaining subs.

**Comment by msbeck** [comment]
This just happened to me several times as well. Good call on the corp prompt to help things out!
