### ISSUE TITLE
Dev server - Maw triggering on stolen agenda 

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#3433]
On the dev server, When runner steals an agenda, Maw triggered and trashed card from hq. We reproduced it 3 times. I didn't have many trash able cards so didn't test the trash asset interaction.

![image](https://user-images.githubusercontent.com/7817263/39663695-fd38cb38-5045-11e8-93f7-8614fa2025e1.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! Working on it!
