### ISSUE TITLE
Game History and Stats

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3435]
I propose a Game History page which shows a tidbit of information about each game played. When clicked it expands into full Stats for each player for that game.

Game listings would look similar to:
![screen shot 2018-05-05 at 9 33 35 am](https://user-images.githubusercontent.com/2982395/39664340-6df0b830-5047-11e8-8db3-faac566e245c.png)

A user can click replay to load into a game state (ticket #XXXX)

Once a game listing is clicked, we could have stats for each player in the game either appear on the right like in deck building or replace the content on the screen for better viewing (and provide a link to go back to listings)

Stats can include but are not limited to:
Turns, Runs Made, Cards Accessed, Click for Credits, Click for Draw, Total Creds, Total Draw, Tags Gained, Clicks Gained. (@danhut)

Number of installs [total], number of credits spent on traces, number of bad pub spent, number of ice subroutines fired, number of runs, number of remotes. (@NoahTheDuke)

Total game time, game time per player, tags removed, tags self-inflicted, clicks to install, bad pub inflicted, bad pub given, bad pub cleared, number of bypasses, number of server changes during run, run events played, credits gained from events, cards milled from RnD, corp trashing corps cards, corp trashing runner cards, runner forcing corp to trash, runner trashing corp cards, runner trashing runner cards (any maybe a breakdown of each type of card trashed in each of the previous cases), cards exposed, credits gained from expose, credits spent on events/resources/programs/hardware, adjusted +/- clicks/credits/tags/etc., max hand size corp/runner, min hand size corp/runner, max remotes, viruses accrued at start of turn, viruses accrued from runs, viruses accrued from events, total viruses purged, number of purges, money gained from purges, total net/meat/brain damage given/taken, total net/brain/meat damage prevented or avoided, money spent on avoiding net/meat/brain damage, number of resources/hardware/programs saved from trashing by other resources/hardware/programs, card drawn from trashing, money gained from trashing, cards discarded at end of turn corp/runner. (@msbeck)

Can look something like this:
<img width="267" alt="screen shot 2018-05-05 at 4 05 21 pm" src="https://user-images.githubusercontent.com/2982395/39664297-c897a74a-5046-11e8-8e6b-a7bbaf2c6dd1.png"> (danhut)

For stat gathering, we could slowly add what we track and show on the page as we implement hooks to listen to such things.

Depending on true server limitations, we could track up to X games (at least 10) with replays.

We should make available all game stats as .csv download either by game or by the last X games.

A set or subset of _appropriate to reveal_ stats should be viewable/toggle-able during a game (as well as available in its replay)

**Comment by jwarwick** [comment]
We have game stats, game logs, and replays now. Think this covers most things in this ticket.

**Comment by msbeck** [comment]
Awesome! Glad to see the ideas in this ticket get implemented! Are there pull requests associated with these features that can be linked/tagged here for record by chance?

**Comment by jwarwick** [comment]
This is probably the big one #5495
