### ISSUE TITLE
Game Replay/Scrubbing

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3438]
Record messages sent from client to server and back to perfectly replicate a game.

Game Replay interface which allows for scrubbing forwards and backwards.

Scrubber can be set to click- or turn-resolution.

Buttons to skip-to-next click or turn.

Replay speed - auto scrub through click or turns every X seconds, or in real time (provided we capture timestamps on actions).

Game Replays available through the History/Stats page (#3435).

Can be downloaded from a game's history plug.

Can be uploaded to play archived games of your own or others' shared games from within Play (Replay button next to New Game).

Recordings take into account the "Make players' hidden information visible to spectators" selection and will only show hidden information in the recordings as such. A Game Replay file could then potentially be different for each player. This would require the "hidden information" selection to be public in a game queue listing so that players can choose whether to join a game in which their hidden information will be available in the recording.

Users watching a replay can select between showing or hiding either player's hidden information.

Users can select which perspective the replay should be played at (runner/corp) i.e. which "side of the table" the replay is watched from.

Some way to share would be nice. A publish feature could give a link to be posted into an NRDB deck description. This could be used to showcase good/winning games with said deck. Can also be posted in a youtube stream/screenshare description so that viewers can replay the game and scrub through it themselves.

**Comment by felipesere** [comment]
This would be really cool.
Possibly even with a note-taking ability. 
Often time I'll play with my buddy and we'll say stuff like "Oh, I'm curious if you have X" or "I'm going to do something, and I want to ask you later what you think".

Such a feature would make it really nice for beginners to play and learn.
