### ISSUE TITLE
Dedicated Neural Net blocks additional accesses from TTW

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#3449]
Two cards in HQ, runner ran with TTW at two counters, and used them before clicking Successful Run.
Corp had a Dedicated Neural Net scored, which fired, corp won psi game.
Corp forced runner to access Hyoubu Research Facility, which the runner trashed.
The access phase ended without an additional access.

**Comment by msbeck** [comment]
Thanks for the report.

This sounds similar to the other "abnormal accesses" issues @noahtheduke

**Comment by NoahTheDuke** [comment]
I’ll look into it!

**Comment by Kubik161** [comment]
Should be closed, Dedicated Neural Net with TTW accesses correct number of cards.
