### ISSUE TITLE
Suggestion: Game type prompt

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#345]
When starting a new game it would be good to have a drop down or some sort of prompt asking for what type of game you're looking for; tournament practice, social, new player etc. I know you can manually type something in the game name but most people don't. A quick mandatory field would force it.

**Comment by JoelCFC25** [comment]
Related to #179. I think it's a good idea--not sure about it being mandatory. In my experience using game names to explicitly mark things as for testing or "not a real game" people don't read them anyway, so I have pretty low expectations about people respecting tagged/classified open games either.

**Comment by DominicKexel** [comment]
I noticed that on jinteki.net nobody cares about the game title (it's always FooBar's game).

On OCTGN its common to use a pattern like `(league) LF  [side/playername] (level)`, for example:

- LF ThatOneUser
- LF either - beginner
- LF runner (advanced)
- SHL4 LF corp

A dropdown would be cool, but it should not be mandatory (or the default could be something generic like `regular`).

**Comment by qmsm** [comment]
Haha, sounds like the argument I have with the President of my rugby club:

"People don't do as they're told!"
"We should put signs up to remind them."
"People don't read signs"
Repeat.

**Comment by Quarg** [comment]
Perhaps a drop-down box is the correct solution, it would allow for having a few different "tags" for games, such as "private", "rematch", "tournament" etc, which can be shown in bold and brightly coloured so they can be distinguished at a glance; thus not requireing the users to actually read what is written.

**Comment by JoelCFC25** [comment]
Would be handled by #755. I really want this!
