### ISSUE TITLE
Message on runner ability on Pop-up Window is incorrect

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#3450]
![image](https://user-images.githubusercontent.com/12355388/39729919-a216e406-521b-11e8-9ba1-0257404eafe3.png)

The runner isn't actually breaking a subroutine, the subroutine is firing and the runner is paying 1c. You might change this to "the runner pays 1" so that it doesn't confuse messaging with effects like Cyberdelia.

**Comment by Saintis** [comment]
Minor bug that should be easy to fix by changing how the runner ability on Pop-up is implemented. 
I am assuming the same bug applies to Endless EULA and similar "sub triggers but runner pays" subroutines.

**Comment by LiteSpecter** [comment]
Same goes for Turing
