### ISSUE TITLE
Minor Imp message log improvement

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3451]
Currently the message log for Imp just records when it trashes for no cost. It would be really helpful if the message included the name of the card that was just was trashed with Imp, as it does when the Runner pays credits to trash something.

**Comment by NoahTheDuke** [comment]
I’ll get that done!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NoahTheDuke** [comment]
I just checked, and the current print out is `noah uses Imp to trash Ice Wall at no cost.` What would you like it to say instead?

**Comment by HubGitAccoutn** [comment]
Ah cool. That seems perfect! I know it didn't used to name the card, but am I right in thinking that some of the viruses recently got re-written so that might have already been changed? I might be thinking of what is now an old version!

**Comment by msbeck** [comment]
@Hitgubaccountn can you play and confirm here that the print out is as described?

**Comment by HubGitAccoutn** [comment]
Yep, all good!
