### ISSUE TITLE
Equivocation and Mwanza City grid not syncing

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#3455]
![image](https://user-images.githubusercontent.com/18687557/39734913-7c9d7562-5236-11e8-8b60-764a269256af.png)

**Comment by msbeck** [comment]
I cannot understand what is happening from the screenshot.

Did Mwanza fire before you got a chance to use Equivocation to make the Corp draw?

**Comment by vkl125** [comment]
well it was a RnD run. Mwanza fired for the duration of the rnd run. Equi force corp to draw a card. Then Corp gained 10 credits.

**Comment by Saintis** [comment]
This looks like it's working as it should. 5 cards were accessed (including Mwanza) and 10 credits were gained. 

Unless there is something else that is the bug this can be closed.

**Comment by msbeck** [comment]
@vkl125 To help us out we need an explanation of what happened, **and** what was actually wrong about it. You explained what happened, but we have to guess what was wrong.

Was the issue that Mwanza gave the player 10 credits instead of 8? So they got money from the Equivocation reveal?

**Comment by vkl125** [comment]
I didn't know that Mwanza City grid was also an accessd card. Wonderful guys. Please close this.
