### ISSUE TITLE
Gang Sign a Snare!, runner gets prompts

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3458]
A runner Gang Signed into my Snare! in HQ. After that, he got a "waiting for the corp to resolve trigger", but I did not get a Snare! prompt. When he `/close-prompt`'ed, the prompt to use Snare! was waiting for him. He triggered it, paying 2 credits (and dying).

**Comment by SubTric** [comment]
This has been happening to me as well. Snare! works as above, asking for the runner to trigger the snare. In addition, Bacterial Programming, when stolen via Gang Sign access will ask the runner to rearrange the cards on top of the corps deck. This seems to have only state happening within the last 7 days or so.

**Comment by msbeck** [comment]
Yep. It seems that all corp actions are assigned to the runner when the runner gang signs into HQ and triggers an ambush.
