### ISSUE TITLE
Inconsistent UI (number of running games)

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#346]
Just a minor usability nitpick:

In the top bar the number of running games is shown.

It uses the same font/color as the navigation items on the left (Jinteki/Deck Builder/Play etc.), but the 'Games' text is actually not a button (nothing happens when you click on that text).

This is irritating.

**Comment by zaroth** [comment]
I'm not sure what would it do - serve as a second lobby button? But what about when you're in-game, you can't access lobby then...

**Comment by Saintis** [comment]
Solution is to make it a button that moves the carousel to "Play", then it is a button :wink:

**Comment by zaroth** [comment]
^ The above comment makes my head spin. I need to get off that carousel of yours ;-)
