### ISSUE TITLE
Kitsune + Mwanza on HQ doesn't prompt for additional accesses

### ISSUE THREAD

**Issue by aRotondi1990** [mtgred/netrunner#3469]
If you have kitsune fire and the runner accesses a card from HQ with a rezzed Mwanza grid in the root of HQ the runner only accesses the single card, mwanza doesn't seem to trigger for additional accesses and does not pay credits to the corp for the single card accessed.

**Comment by msbeck** [comment]
Interesting. I wonder what the order of things should be. Corp picks a card, then shuffles, then the three mwanza accesses happen from the top?

@noahtheduke, could this potentially be associated with the "abnormal accesses" issues?

**Comment by Saintis** [comment]
Does Kitsune work with HQI? That should suggest if the problem is with Mwanza or Kitsune access.

**Comment by LiteSpecter** [comment]
The HQI/Kitsune thing was closed a while ago, it should work? Per Joel's comment on Kitsune:

https://github.com/mtgred/netrunner/issues/2476#issuecomment-292687378

> You would want to mimic what was altered in Gang Sign and Raymond Flint in #2158.

**Comment by Saintis** [comment]
This works locally when Kitsune is on HQ. I'm looking at a fix.
