### ISSUE TITLE
Logging when Corp trashes a resource

### ISSUE THREAD

**Issue by athayn** [mtgred/netrunner#347]
It would be great if at least the log registered to the users when the Corp trashes a resource. Right now it doesn't show as taking a click or action by the Corp, the card just appears in your heap. It can be easy to not even know this happened for a turn or two.

**Comment by DominicKexel** [comment]
duplicate of #326

**Comment by athayn** [comment]
it's not fixed as of this writing, but i will close this issue as duplicate.
