### ISSUE TITLE
Darwin not prompting for virus counter at start of turn (no 100% repro steps)

### ISSUE THREAD

**Issue by sodwyer** [mtgred/netrunner#348]
This only happened during one game, tried to reproduce it again afterwards and wasnt able, so not sure how it happened exactly.

When it occurred, the prompt only worked the first time. 
After that the game would freeze for a short time when clicking "start turn".
There was no prompt to pay 1 to add a token on Darwin and I had to spam the chat until the situation unblocked. It remained this way for the entire game.

Other cards in play were Armitage Codebusting, Kati Jones & Deep Thought.

**Comment by javel-by** [comment]
I had this issue once when Darwin was hosted on Progenitor.
