### ISSUE TITLE
QPM v. Turntable

### ISSUE THREAD

**Issue by Sedatedfork** [mtgred/netrunner#3491]
So, on corp turn, offer you can't refuse.  Runner takes tag from ice and accesses and steals QPM.  Seems like a bug.  Runner was Freedom.  Corp was Haarpsichord.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I believe we are working on a fix.

**Comment by msbeck** [comment]
So you stole the QPM and instead of the corp scoring it the Turntable prompt allowed you to switch it with something?

**Comment by Sedatedfork** [comment]
I was corp so I dont know what prompt runner received.  They didnt turntable it.  They just stole it.  I just wanted to give full picture of situation so that bug could be investigated.
