### ISSUE TITLE
Maya steal-trigger-events unbound

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3493]
Looks like this function disappeared in one of @NoahTheDuke trash PRs.

**Comment by jwarwick** [comment]
PR about trashing cards, not a PR of low quality :)

**Comment by NoahTheDuke** [comment]
Oh yikes, that’s my bad. I saw it used in runs.clj and thought it was internal.

**Comment by NoahTheDuke** [comment]
Looking at Maya, I would expect it to be a `:post-access-card` effect, not an ability. Looks like it was firing the `:access` step manually, which now will happen before the access prompt appears, so things should be fine? If that's removed and the test changed to include an agenda, it seems to work fine!
