### ISSUE TITLE
Magnet doesn't see programs hosted on face-down ice

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#3494]
Trypano makes this relevant. No 'click a hosted program' prompt shows up if there isn't at least 1 program hosted on a rezzed piece of ice. If there IS at least one such program, then clicking on a program hosted on an unrezzed ice works fine.

While testing this, I found out that if a Parasite is installed on a Magnet and the Magnet then derezzed, the Parasite no longer gains virus counters at the start of the runner's turn.

**Comment by Saintis** [comment]
Should be easy to fix the first bit. Needs to just change the filter from `all-active-installed` to `all-installed` or similar. 

For the second part Magnet probably needs some sort of `:leave-play` effect
