### ISSUE TITLE
Knobkierie doesn't distinguish between virus and non-virus programs when installed. 

### ISSUE THREAD

**Issue by helldrivers** [mtgred/netrunner#3505]
Like the title suggests, Knobkierie doesn't seem to recognize if an installed program is a virus or not with regards to its MU ability. I had 2x Laamb, 1x Yusuf and 1x Trope installed, and it had me at exactly 0 MU left.

**Comment by NoahTheDuke** [comment]
Yeah, we don’t have virus MU implemented. It’s been discussed, but nothing yet.

**Comment by NoahTheDuke** [comment]
Gonna close this as virus MU isn't implemented and isn't planned for implementation.
