### ISSUE TITLE
Deep Data Mining

### ISSUE THREAD

**Issue by djnrrd** [mtgred/netrunner#3519]
When attempting to click "Successful Run" at the end of a Deep Data Mining run, the site does not respond.  Other people have reported similar issues in chat (times in BST):

TattletaylesThursday May 17th - 21:29
may be a bug here
Tattletayles
TattletaylesThursday May 17th - 21:31
run on rnd with Deep Data Mining , hit a Miraju and let it fire, then run into RND with rezzed Mwana City Grid , causes the run to break
Tattletayles
TattletaylesThursday May 17th - 21:31
Mwanza City Grid
Tattletayles
TattletaylesThursday May 17th - 21:47
confirmed in a second game
Tattletayles
TattletaylesThursday May 17th - 21:47
Deep Data Mining does not work with Mwanza City Grid, where do i send this bug to?
demoy
demoyThursday May 17th - 21:52
https://github.com/mtgred/netrunner/issues/new
KimmyZerg
KimmyZergThursday May 17th - 22:11
Deep Data Mining keeps freezing up my run when I finally reach R&D
djnrrd
djnrrdThursday May 17th - 22:20
KimmyZerg > Thought it was just me
djnrrd
djnrrdThursday May 17th - 22:21
Deep Data Mining, same deal :(

**Comment by Saintis** [comment]
My bad, I broke it.
