### ISSUE TITLE
Newly installed cards (assets/agendas) sometimes can't be interacted with at all.

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#352]
I've been playing Cerebral Imaging today and I've found that when I've installed a card in a remote, I'm then not able to rez or advance it. When I hover over the card with the mouse, it doesn't show the card where it normally would (top right corner). I can't even drag it around, so I have to install some other card in that remote and keep cycling this until it works (it isn't a consistent bug, annoyingly). These cards can be accessed, however, and work perfectly in that regard. I've tested this on Chrome 43.0.2357.132 m on a Windows tablet (with keyboard) and on a Toshiba Laptop with the latest stable Firefox.

(Sorry if this has been reported before.)

Also, thank you for the amazing work you've done on jinteki.net! It's really helpful to be able to play on Linux without disconnecting most of the time (silly Wine...).

**Comment by nealterrell** [comment]
This may be related to #357, as it exhibits the same symptom: no menu showing on click.

**Comment by mtgred** [comment]
The issue has been fixed. Refresh your browser to get the latest CSS and it should work fine.

**Comment by finnbar** [comment]
Yep, it's all fixed! Thank you very much!
