### ISSUE TITLE
Viral Weaponization scored via a Plan B only does the net damage at the end of the Corp's following turn, rather than the end of the Runner turn.

### ISSUE THREAD

**Issue by LeonardQuirm** [mtgred/netrunner#3521]
Viral Weaponization should do its net damage at the end of the turn it is scored, even if that is the runner turn due to their accessing a 4-advanced Plan B.  When I (as Corp) did this, the runner was left with their hand after the end of the turn, then they lost all their cards in hand after the end of my following turn.

**Comment by JoelCFC25** [comment]
Just needs to add a `:runner-turn-ends` handler identical to the current `:corp-turn-ends` one.
