### ISSUE TITLE
Kitsune and Mwanza City Grid interaction 

### ISSUE THREAD

**Issue by vkl125** [mtgred/netrunner#3529]
Corp had 3 snares, and uses kitsune to make the runner access multiple cards with Mwanza City Grid. That is wrong I assume?

**Comment by Saintis** [comment]
Accessing cards through Kitsune counts as accessing cards _from_ HQ, hence it benefits from cards such as Mwanza and HQI. This is working as intended. See #3469 as well.

**Comment by Saintis** [comment]
Unless the Corp decided _all_ the accesses (not just the first one), then there is a bug.
