### ISSUE TITLE
Knight menu sideways

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#353]
The menu that appears when you click on knight is sideways, and hard to click due to being behind installed ice.

**Comment by nealterrell** [comment]
Confirmed. This is an amazing bug.
![knight](https://cloud.githubusercontent.com/assets/10083341/8632340/1b50dc9a-274b-11e5-8100-0e3f44698ca8.PNG)

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed. Refresh your browser to get the latest CSS and it should work fine.
