### ISSUE TITLE
Multiple copies of cards and prompts

### ISSUE THREAD

**Issue by msbeck** [mtgred/netrunner#3534]
When you have multiple copies of cards like Imp or Jackpot! installed, when a trigger for them hits you can't tell which one you are choosing.

For cards like Acacia this doesn't really matter, but ones like Imp or Jackpot! which have different potential states it does.

Perhaps we can highlight cards when you miss over their associated prompt choice?

**Comment by kevintame** [comment]
Yeah this is an issue with Jackpot. If you guess wrong you have to fix manually. In the pop up dialog a solution might be to show the credits on that card so you can select the correct one.
