### ISSUE TITLE
Consume and Hivemind

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3550]
Consume doesn't seem to play nicely with Hivemind when Consume itself is "empty" (i.e only has counters borrowed from Hivemind).

When Consume has counters and Hivemind has counters, using the Consume ability removes all counters from Consume, all counters from Hivemind and gives credits equal to twice the total. All as it should be.

When Consume has no counters of its own and Hivemind has some counters, using the Consume ability seems to do the following:

Lose one click from the total;
No message in the log for either player;
Runner interface freezes up: no action buttons operational, resource values can't be manually changed etc. (requires leaving and rejoining the game to overcome);
No credits added;
No counters removed from Hivemind.

**Comment by NoahTheDuke** [comment]
Thanks for the report! We’ve long wrestled with Hivemind, and it looks like there’s more wrestling to do.
