### ISSUE TITLE
Troll on Jinteki making runner boost first?

### ISSUE THREAD

**Issue by cwhttiger** [mtgred/netrunner#3553]
I just got done with a net runner game on jinteki.net were every time the runner encountered the nbn card troll it made them boost first. Is this supost to happen? I could not find any info on this card in fantasy flights faqs.

**Comment by NoahTheDuke** [comment]
We recently implemented Surveillance Sweep. Was the Corp playing that Current? If not, you encountered a bug resulting from that work.

**Comment by NoahTheDuke** [comment]
Ah yes, the `:player :runner` bit in Troll is making that happen. I’ll fix it shortly.

**Comment by jwarwick** [comment]
Fixed in #3556
