### ISSUE TITLE
Incorrect English on Embezzle when choosing ICE

### ISSUE THREAD

**Issue by squogfloogle** [mtgred/netrunner#3554]
When choosing the option 'ICE' for Embezzle, displays the incorrect plural (ICEs)

"x uses Embezzle to reveal 2 cards from HQ and trash all ICEs."

The plural of ICE is ICE, it should read"

"x uses Embezzle to reveal 2 cards from HQ and trash all ICE."

I tested the other options (asset, upgrade, operation) - they're all correct.

**Comment by NoahTheDuke** [comment]
Thanks so much!

**Comment by NoahTheDuke** [comment]
Thanks so much! A fix should be forthcoming.
