### ISSUE TITLE
Using Jackson back to back in a turn doesn't work

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#357]
It seems like Jackson will not bring up his menu the second time you try to use him.

I had an opponent report this then later experienced it myself.  Taking another action then using Jackson fixed it for me.  I haven't had the opportunity to try to reproduce fresh so don't know if there are other factors.

**Comment by nealterrell** [comment]
Confirmed. That is very interesting...

**Comment by nealterrell** [comment]
Tested on my dev machine and Jackson is working fine there. My repo is only synced to commit f80e26f7f0639399c87994cef7513211824e7015 , so perhaps something after that broke things.

**Comment by nealterrell** [comment]
@mtgred, I have confirmed that this started with commit cd6a1ebb7b78adc6b56f2fe7f520afa3ef0342a7, having worked all the way up to the previous commit 6b5573d07c10c8cff103ae7b8717088b30d45f7c. Not sure what part of that commit is breaking it.

**Comment by nealterrell** [comment]
I believe the error is in the server code, but can't confirm. I checked out the previous commit and recompiled the server and client code, then checked out the broken commit and recompiled only the server code... and Jackson was broken. So it doesn't seem like the client code would be responsible.

**Comment by mtgred** [comment]
Thanks for identifying the commit causing the issue. I'll have a look tonight.

**Comment by mtgred** [comment]
The issue has been solved. Refresh your browser and it should work fine.

**Comment by nealterrell** [comment]
So it wasn't Jackson specifically, it was ending up with 7 cards in hand. Awesome :).
