### ISSUE TITLE
Tagged Runner accesses Quantum Predictive Model, doesn't see rezzed Franchise City prompt

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#3575]
From my understanding of ruling: since Quantum Predictive Model (QPM) and Franchise City (FC) have the same trigger the corp should be able to use FC before using QPM. If they choose to use QPM first (like what seem to be happening automatically right now) the access ends because QPM is nolonger being accessed, and FC wont apply.

**Comment by NoahTheDuke** [comment]
Thanks for the report! We’ll look into it!

**Comment by nealterrell** [comment]
I'd guess that QPM should be `:interactive true`, since you probably always want to order it a particular way due to it canceling other on-access effects.
