### ISSUE TITLE
Faerie sometimes trashes itself during runs it went unused.

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#3578]
I don't know how to reproduce this bug consistently, I have observe while spectating games and when using Faerie myself.  Faerie would attempt to trash itself after another ICE breaker was used.

 If Sacrificial Construct is installed when this bug occurs, it prompts the runner to prevent it's trashing. Otherwise Faerie trashes itself without leaving anything in the log: so several turn later, both players noticed the fairy had vanished :).

**Comment by nealterrell** [comment]
Fairie needs to move its trash flag to :special.
