### ISSUE TITLE
Add a Setting for lobby sounds

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3579]
Currently lobby sounds and game sounds use the same preference setting. Split them into two separate preferences.

**Comment by danhut** [comment]
If you don't mind - can you commit any change to the Reagent branch instead / as well.  I assume this will need cljs changes.  tyt!!

**Comment by jwarwick** [comment]
Confirmed that live site splits lobby and game sound controls and they operate independently.
