### ISSUE TITLE
Architect doesn't print to the console (possible to cheat)

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#358]
Architect, when rezzed, does not print that the corp is using the look at 5 cards sub.  This allows the corp to cheat by looking at the top 5 cards then choosing no install.  Seems like it should print to the chat that the corp is looking at the top 5 cards and also that the corp chooses not to install

**Comment by nealterrell** [comment]
Architect does print a message, but only if the Corp does not click "No install". So you're right, a Corp can fire the subroutine to peek at the top of R&D without alerting the Runner. 

My repo is in a difficult state right now, so I can't fix this quite yet, but if anyone else wants to take a crack at it... maybe try removing the `:req` and augmenting the effect to make sure target is not `"No install"` before calling `corp-install`. The message _should_ then print regardless, and a second message to indicate the installation will fire from `corp-install`.

**Comment by DominicKexel** [comment]
Maybe I'll take a look if I find some time this weekend
