### ISSUE TITLE
Marilyn Campaign rez grants extra clicks

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3585]
If you rez a `Marilyn Campaign` before the Corp's turn starts, you are granted 3 extra clicks. The log contains two `corp started their turn...` messages with a `Marilyn credit gain` message in between.

**Comment by NoahTheDuke** [comment]
That's wild! What is happening, I wonder?

**Comment by demoy** [comment]
I also find that since the update, on the final turn Marilyn is to trash itself, the corp can't shuffle it back into deck before the mandatory draw. Only after.
