### ISSUE TITLE
Possible Enhancement: end-game stats

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#3586]
Currently, the count of "credits gained" is misleading because it counts credits spent on economy cards in the total (Sure Gamble counts as +9 instead of +4, IPO counts as +13 instead of +5). This makes the total not comparable between different decks - especially if one is using significant drip economy.

This also doesn't account for the opportunity cost of the clicks spent on, say, Magnum Opus.

If the intent is to have a feeling for how much money you had available in a game, perhaps an additional stat of "credits spent on credit-gaining cards" would help - not sure if the subtraction should be done automatically, or just provide both numbers. Credit gaining cards could be defined as any card with "gain " in its text (to eliminate things where the opponent "gains").

**Comment by danhut** [comment]
This seems fair. I’ll sort something out soon!
