### ISSUE TITLE
Odd interaction with Hivemind, Trypano and Friday Chip

### ISSUE THREAD

**Issue by jhulme** [mtgred/netrunner#3589]
My opponent on runner had 2 x Friday Chips installed with a Hivemind. When placing Trypano onto ice where tokens reached the limit of 5 resulting in an ice trash the UI would freeze briefly before spamming hundreds of virus tokens onto Friday Chip.

There seems to be a loop when the logic decides the ice is to be trashed resulting in a huge run in the log of the following:
```
dr_foobar uses Trypano to trash ICE protecting R&D at position 0.
dr_foobar places 1 virus counter on Friday Chip.
dr_foobar uses Trypano to trash ICE protecting R&D at position 0.
dr_foobar places 1 virus counter on Friday Chip.
dr_foobar uses Trypano to trash ICE protecting R&D at position 0.
dr_foobar places 1 virus counter on Friday Chip.
```
Screenshot below also for reference:
![image](https://user-images.githubusercontent.com/809451/41064343-319b2ef6-69d3-11e8-95d3-11d01654d3ff.png)

If required I have copied out the whole chat log before the game ended.

**Comment by NoahTheDuke** [comment]
That's no good! Thanks for the report, we'll take a look!

**Comment by erinrockabitch** [comment]
Had a similar thing happen:
Trypano, Friday Chip and Knobkerie installed - Trypano is at four counters.  Make a successful run and try to add a counter to Trypano.  Game froze up and Friday chip added 154 counters.  Game state uploaded.

![virus bug](https://user-images.githubusercontent.com/9438049/41071782-0c0b244e-69c8-11e8-9d2b-557ed94195e5.png)

**Comment by nealterrell** [comment]
Thanks for the report, we got it.
