### ISSUE TITLE
Hortum's "Gain 1 credit" subroutine not giving a credit

### ISSUE THREAD

**Issue by Kenneth-Siu** [mtgred/netrunner#3592]
On Chrome, when attempting to fire the subroutine for gaining a credit, the corp's credit level doesn't change.

Reproducible by a private game with a deck of 3 Hortums and 3 Hedge Funds.

![image](https://user-images.githubusercontent.com/8361722/41068137-1bc7d270-69e0-11e8-9a26-fb35c4945663.png)

**Comment by NoahTheDuke** [comment]
Thanks for the bug report! Confirmed, and a fix is on the way.
