### ISSUE TITLE
PAD Tap - Triggers on "take #c" at start of turn campaigns (Adonis)

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#3595]
PAD Tap triggers when corp "takes" credits from temporary campaigns like Adonis.
Triggers fine with say PAD Campaign which reads "gain 1c".

**Comment by nealterrell** [comment]
We'll fix this and then wait for a UFAQ clarification, because this does seem overly pedantic and against the spirit of the card.

**Comment by xdfubar** [comment]
Probably, but they will need to go back and change the UFAQ for NASX as well.
https://netrunnerdb.com/find/?q=nasx

Q: Does taking credits from a card (e.g. Corporate Sales Team) trigger NASX?
A: No. Taking credits from a card is not the same as gaining credits.

**Comment by nealterrell** [comment]
Thanks for the source of this ruling! We'll keep an eye out.
