### ISSUE TITLE
Azmari + Mining Accident + PAD Tap Interaction

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#3596]
Runner - 419 (has PAD Tap already installed)
Corp - Azmari
Azmari named "resource"
Runner first click runs empty archives, then second click plays "Mining Accident".
Azmari ID triggers, PAD Tap triggers, and Mining Accident still has to be resolved.
419 runner had to use "close-prompt" to close the  "Waiting for corp to choose bad pub/lose 5c".
Then choose to gain 1c from PAD tap.
Azmari was then able to choose between Bad Pub/lose 5c.

**Comment by nealterrell** [comment]
I am making PAD Tap automatic so this should clear up.
