### ISSUE TITLE
Psi

### ISSUE THREAD

**Issue by Heartthrob-** [mtgred/netrunner#36]
I'm sure this is already on the radar. But no way to Psi is difficult. A lot of The Future Perfect and Caprice in competitive decks.

**Comment by mtgred** [comment]
All Psi cards except Bullfrog are now implemented.

**Comment by Heartthrob-** [comment]
You're than man Mihn!

Spencer Healey
Marketing Communication Senior//
ProPay Inc. // A TSYS Company
spencer.healey@propay.com
801.227.9836
