### ISSUE TITLE
Impossible to put R&D INTERFACE in my deck

### ISSUE THREAD

**Issue by ModesteetGenial** [mtgred/netrunner#360]
Hello,
When I build my deck, I can't to put R&D Interface in my deck...
Do you know why?
Do you give me one solution for my problem?
Thanx

Modeste et Génial

**Comment by mtgred** [comment]
I believe there is an issue with unicode (`&` in this case) on Windows.
The workaround is type "2 R&D Interface" in the text area and it should be added.
