### ISSUE TITLE
Automating and un-automating Apex

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#3601]
A friend new to Apex was playing an Assimilator + Aesop deck against me the other day, and was experiencing some pain points. Here are a couple notes:

- Defaulting to manual-triggering for start of turn effects when Apex has one other manually-triggered start of turn card installed would be nice. It is mentally taxing and mechanically difficult to reverse the interactions between Apex, Chopbot, Aesop, and Reaver. This is especially awful for new players who frequently don't even know they can order the interactions. For example, it's not uncommon to want to Chopbot first to activate Reaver, then install the newly drawn card face down with Apex, then sell the installed card to Aesop. This gets additionally weird with automatic start of turn effects like Data Folding, but that's true across the entire application.
- Blocking the user from installing non-virtual resources (probably accompanied with a toast) would keep newer players or even experienced players that aren't paying attention from having to revert their boardstate and re-plan their turn. I think you have something similar in place that prevents priority events from being played after the first click.

**Comment by JoelCFC25** [comment]
> Defaulting to manual-triggering for start of turn effects when Apex has one other manually-triggered start of turn card installed would be nice. 

Currently Apex is setting the `:runner-phase-12` _(still named that way despite the fact that FAQ updates in the interim mean it's really 1.4, but we digress)_ if the Runner has 1 or more cards in hand. Are you saying this is too broad and to limit it to "at least 1 other active card is also `:runner-phase-12`" instead?

**Comment by FarCryFromHuman** [comment]
If the Apex trigger was something like this (sorry pseudocode, not even going to attempt Clojure):
```
IF cards in play with manual start of turn effects > 0
   THEN manual resolution menu for all cards in play with manual start of turn effects (including Apex)
ELSE IF cards in hand > 0
   THEN trigger and resolve Apex automatically
ELSE don't resolve Apex
```

By manual start of turn effects, I mean cards you would traditionally click to activate before taking clicks, like Chopbot, Aesop, etc. I don't mean automatically resolved cards like Data Folding (that would add a lot more clicks, and at least in this case, credit pool doesn't matter).

By manual resolution menu I mean your delayed completion menu (I think?) like when Leela steals an agenda with Gang Signs installed, where it lists the cards by name and lets the player resolve each in the order of their choosing.

**Comment by Saintis** [comment]
Apex should certainly be orderable with cards that draw at the start of runner's turn, and also with Aesop's. Maybe making Apex always orderable will be easiest.
