### ISSUE TITLE
On the Lam doesn't trigger a prompt

### ISSUE THREAD

**Issue by phette23** [mtgred/netrunner#3603]
As of yesterday's (June 6th) update, On the Lam no longer triggers a dialog prompt to prevent damage. To create:

- runner installs OTL
- corp fires a damage source (e.g. Neural, Ronin, Urban Renewal)
- damage happens immediately without a chance for OTL to intercede

Thanks for all your work! This team is **the best**!

**Comment by NoahTheDuke** [comment]
Thanks for the report! A fix is forthcoming.
