### ISSUE TITLE
No wait for Political Dealings

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3607]
When the Political Dealings dialogue comes up, this doesn't lock the board for the Runner as they wait for the Corp to act.

Usually, this wouldn't be too much of an issue as most card draw is in the Corp turn. However, with things like Fisk Investment Seminar, they Runner will on taking clicks unaware that the Corp is thinking or trying to install an agenda somewhere.

When waiting for the Corp choice to install, the Runner should really get a "Waiting for Corp action" type message.

This will have to come up every time the Corp draws while Political Dealings is active though, otherwise the very fact that the dialogue appears will alert the Runner to the fact that the Corp just drew an agenda, even if they don't then choose to reveal and install it. I'd suggest the Corp could maybe get a: "You didn't draw any agendas for Political Dealings" dialogue when no agendas are drawn, with just an "Okay" button or something similar.

**Comment by NoahTheDuke** [comment]
Thanks for the report! We'll have to see the best way to make this happen.

**Comment by NoahTheDuke** [comment]
Note to self: Jinja City Grid has the same issue.

**Comment by Saintis** [comment]
In order to minimise obstructive prompts, I would suggest that Jinja and Political Dealings only do wait-prompts on the runner's turn.
