### ISSUE TITLE
The Source doesn't work

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#361]
Installing The Source leaves the Corp in a state where no agendas can be advanced at all. It also isn't trashing itself when the Runner steals an agenda. 

It got modified by #260, but it looks like there is an `{:effect` missing in a couple places in the `:events` section. I'll try to look at it tonight.

**Comment by nealterrell** [comment]
Whoops. Thanks for cleaning this up.

**Comment by JoelCFC25** [comment]
Fixed at #374.
