### ISSUE TITLE
Jua preventing Corp install as well as Runner install

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3613]
Having fired the Jua on encounter ability ("When the Runner encounters Jua, he or she cannot install cards for the remainder of the turn.") previously in the turn, the Corp then can't use the Mti Mwekundu ID ability to install ICE. It returns the message "Installing is currently locked."

**Comment by HubGitAccoutn** [comment]
(I've just checked this out with Jua->Architect and it's the same problem, so it looks like a general block on Corp installation after Jua's effect fires, rather that something specific to Mti Mwekundu.)

**Comment by NoahTheDuke** [comment]
Yeah, we're using a more general lock than we should be. Thanks for the report! We'll get it fixed right quick.
