### ISSUE TITLE
Mti Mwekundu: Life Improved has no usage prompt

### ISSUE THREAD

**Issue by RJayz** [mtgred/netrunner#3618]
The last two days I've been testing this ID, and got confused as it is marked as fully automated on the automation page, but didn't figure out how to use it. After some experimentation I found it involves clicking the ID when getting the "action before access" prompt. I might have missed it but would it be possible to have a pop-up or message indicating when it's possible to use Mti Mwekundu? Thank you!

**Comment by JoelCFC25** [comment]
Indeed--I noted this to the team a couple days ago. Either an implementation note on the card or a Runner toast when you pass the last ICE would be good.

**Comment by ChooJeremy** [comment]
Going to try working on this. Need to figure out the best way to have the toast only appear if the ability is available,, as the ability lets the corp choose when to fire.
