### ISSUE TITLE
Better Citizen Program + Mining Accident

### ISSUE THREAD

**Issue by poi2000** [mtgred/netrunner#3619]
Just participated in a game where Mining Accident triggered Better Citizen Program erroneously, I'm not exactly sure what the cause of the bug would be, might have been related to something else.

**Comment by NoahTheDuke** [comment]
Mining Accident is an Event, and Better Citizen Program triggers on the first Event played each turn. It's only a bug if the runner installed an Icebreaker or played an Event earlier in the turn.

**Comment by NoahTheDuke** [comment]
Unless the runner played a run event earlier in the turn, merely spending a click to make a run does not trigger Better Citizen Program. BCP only triggers from playing run events, not from making runs.
