### ISSUE TITLE
You can install Operations into a server

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#363]
`corp-install` does not check the card type, so it's possible that you can install operations via this function. It should check the card type and prevent installing operations.

I noticed it while working at #358; I'll try to fix both issues in one go, but it may take some time....

**Comment by DominicKexel** [comment]
It would be cool do have an option to disable buttons in the UI when a player has a choice to make.
So we could e.g. disable Operations when firing Architect, or disable abilities that the player can't pay for (see #367).

**Comment by DominicKexel** [comment]
Maybe we could keep it simple and just prepend a  ^ to the string when an Option should be disabled when showing a prompt and check for it at client side. I will test this and report if and how it's working.
