### ISSUE TITLE
Apocalypse flips On the Lam

### ISSUE THREAD

**Issue by extreme-tcpdump-enthusiast** [mtgred/netrunner#3634]
It's a weird interaction but on the lam is not a card when it's installed, it's a hosted condition counter and should not go upside down post-apoc.  This used to work correctly.

**Comment by NoahTheDuke** [comment]
Lmao Heck. This is probably because t get t to work after some backend changes, it had to be marked as `:installed`. I’ll take a look. Thanks for the report!
