### ISSUE TITLE
Parasite onto 0-str ice doesn't trigger Noise's ability

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#364]
When playing Noise, installing a Parasite onto a 0 strength ice correctly kills the ice immediately, but doesn't trigger Noise's ability to mill the Corp due to the virus install. 

For all other ice strengths the mill is occurring.

**Comment by nealterrell** [comment]
Ugh... probably because by the time `:runner-install` event gets invoked, Parasite is no longer installed, so no argument is passed to Noise, so he can't see that it was a virus. I'll look into it.
