### ISSUE TITLE
Implement Builder of Nation Alt art? and tooltip for Errata

### ISSUE THREAD

**Issue by Zerothmaxima** [mtgred/netrunner#3645]
People still don't know builder of nations was errata'd. Can we get the correctly worded art and a tooltip on the base ID with the proper wording:

-------------------------------

The first time an encounter with a piece of ice with at least 1 advancement token ends each turn, do 1 meat damage.

Errata from FAQ 3.1.1

----------------------------------

https://i.imgur.com/mZhfhFl.jpg

**Comment by Kubik161** [comment]
@NoahTheDuke We have errata for Builder of Nations. This issue should be closed.
