### ISSUE TITLE
Neutralize All Threats no longer trashes automatically.

### ISSUE THREAD

**Issue by PesiTheWizard** [mtgred/netrunner#3647]
2018/6/4
Neutralize All Threats no longer trashes automatically. (Intentional?)

**Comment by danhut** [comment]
Thanks for the report.  I am Splitting this into two issues.  Please do not pile up multiple into one issue if you can avoid it - it does not suit the team workflow.

**Comment by NoahTheDuke** [comment]
Thanks, Pesi! I’ll take a look.

**Comment by NoahTheDuke** [comment]
Should be handled by all of the access prompt stuff
