### ISSUE TITLE
Pad Tap is triggered by cards that 'Take'

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3651]
eg marilyn campaign.

According to ancur, these are not the same ...

14. Does taking credits from a card (e.g. Corporate Sales Team) trigger NASX?

📷No. Taking credits from a card is not the same as gaining credits.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I thought we fixed this, but it might’ve stilled missed something. I’ll take a look!

**Comment by tolaasin** [comment]
Marilyn is bugged for sure

**Comment by NoahTheDuke** [comment]
Thanks so much!
