### ISSUE TITLE
Mumbad Virtual Tour is too restrictive

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#3653]
I have 4 credits and Daily Casts installed. I make a run and access Mumbad Virtual Tour.

Now the only option the pop up gives me is 'Pay 5c to trash', but I can't, since I only have 4c and I can't.

The workaround is of course to use '/close-prompt', but I think one could do better.

Eihter there should be an option to close the dialog without me looking up the help page, or the game has to check if I can actually take credits from my cards (which is a probably not feasible).

Maybe always show both options (trash / close dialog)? Because often, credits on installed cards have certain restrictions, like 'use only for icebreakers' or something.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I’ll take a look.

**Comment by Saintis** [comment]
What we could do is mark credits on cards that can be used for trashing cards as such. This will go some way towards implementing recurring credit specific use

**Comment by NoahTheDuke** [comment]
Previously, everything was fine but I think when I changed the `can-pay?` logic to accommodate paying with recurring credits, it hit MVT. I'll whip up a fix once I get situated.

**Comment by Chemscribbler** [comment]
In addition this is counting things Bankroll, which cannot have its credits used while accessing cards

**Comment by tolaasin** [comment]
Can I bump this? MVT is still broken if you access and don't have the credits to trash. Close-prompt is the only option.
