### ISSUE TITLE
Mlinzi trashing from the stack

### ISSUE THREAD

**Issue by HubGitAccoutn** [mtgred/netrunner#3659]
The subroutines on Mlinzi do net damage *unless* the Runner trashes a certain number of cards from the Stack.

Currently this is always implemented as a choice for the Runner to choose the damage or the trashing. This means that with no cards in the Stack nothing happens if the Runner nevertheless chooses the second option (that they can't fulfil), or that with less that the required amount in the Stack, all remaining cards are trashed.

It would be good if a check could be introduced so that if the required number of cards are available in the Stack (i.e. 2 for the first subroutine, 3 for the second, 4 for the third) the Runner would get the option as currently, but if an insufficient amount of cards are present there would be no option and the net damage would fire automatically (as the Runner can't fulfil the alternative to prevent it).

**Comment by danhut** [comment]
Are there any cards in the game which allow a runner to add cards to the Stack at instant speed?  Either from installed or the heap?  This would break our ability to check this - or complicate it.  Same as per why we don't do this sort of thing with credits (i.e. there are ways to get credits instantly)

**Comment by HubGitAccoutn** [comment]
When you say "instant speed" do you mean triggered effects? Or are you using "instant speed" to mean paid abilities?

'Cos in the latter case there are no windows for paid abilities once you are onto the stage of firing subroutines. For triggered abilities, it'd have to be something that triggered off: "When a subroutine begins to resolve" that added or removed cards from the stack, wouldn't it? I can't think of anything that even has that type of trigger.

I can certainly think of a card that removes cards from the Stack (I've Had Worse) that could trigger from previous subroutines firing, but I was imagining that a check could be done at the time the individual subroutine fired and the Runner is given the prompt to choose. You certainly wouldn't want to do the check beforehand when the ICE was encountered or something like that. The Stack size shouldn't be changing between the Runner getting the choice dialogue and making a choice, should it?

**Comment by Saintis** [comment]
This is a case of "people should know the rules / cards", but I think it is easy to implement a check inside the subroutine where you only present the choice to the runner if relevant.
