### ISSUE TITLE
Enhancement: Delete Multiple/All Decklists

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#3664]
It can be very cumbersome to delete decks one at a time, especially when you have a lot of them. Allow selecting multiple or all of the decks and performing actions on them.

**Comment by JoelCFC25** [comment]
Actually a duplicate of #2287.

**Comment by NoahTheDuke** [comment]
Whoops, thanks.

**Comment by queueseven** [comment]
closed because duplicate of #2287.
