### ISSUE TITLE
Peace in Our Time vs. Azmari?

### ISSUE THREAD

**Issue by limnrix** [mtgred/netrunner#3667]
Peace in Our Time went into the "temporary" zone instead of the heap when played. No other cards could then be played. Azmari had called Event, Technoco was rezzed. Couldn't be dragged out, nothing else could be dragged. Attempted to close prompt, then undo click, and the undo alert kept popping up. Was still unable to play anything. No idea what else might be behind this bug.<img width="1399" alt="screenshot 2018-06-24 21 05 39" src="https://user-images.githubusercontent.com/30281448/41825892-08eb96de-77f3-11e8-805b-2be624bc3b4f.png">

**Comment by nealterrell** [comment]
Should be good now.
