### ISSUE TITLE
Biased reporting does not give the corp credits

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3678]
Baralai started their turn 27 with 5 and 5 cards in HQ.
Baralai spends  and 2  to play Biased Reporting.
Baralai
oh that explains a lot!
i got the feeling that last biased didnt gave me credit
but got no chance to check
!Baralai uses a command: /undo-click
Baralai spends  and 2  to play Biased Reporting.
Baralai
Baralai
^^

**Comment by NoahTheDuke** [comment]
How many cards did the runner have installed?

**Comment by tolaasin** [comment]
I had 9 resources, 3 programs, 1 console

**Comment by tolaasin** [comment]
I did get the prompt about 'do you want to trash any resources'

**Comment by NoahTheDuke** [comment]
So the steps are: Baralai used Biased Reporting, you got the prompt "Do you want to trash any resources?", before you clicked anything they said, "I didn't get any credits" and then undid their click? They should have gotten a Wait Prompt that said, "Runner to choose cards to trash".

Unless I've missed something, it's working like it should.

**Comment by tolaasin** [comment]
Not quite. I got the prompt 'do you want to trash any resources'. I say 'no'. They accepted their prompt - but got no credits. They undid the click, and tried it again - same thing happened. I don't have a record of what prompts they got, but that's my understanding.

**Comment by NoahTheDuke** [comment]
Ah, okay. Yeah, that’s no good. I’ll see if I am replicate and fix. Thanks for helping me understand!
