### ISSUE TITLE
Alice Merchant trash ability

### ISSUE THREAD

**Issue by TheTrain87** [mtgred/netrunner#3684]
Currently, Alice Merchant's ability forces the corp trash the card from HQ face-up.  I'm pretty sure this isn't correct (as far as I can tell it's supposed to be face down), and it's hard to work around.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look at it.

**Comment by nealterrell** [comment]
This is the correct interaction, because Alice triggers on successful run, which is prior to turning all cards in archives face up.

**Comment by TheTrain87** [comment]
But, I think (I might be wrong) it was happening when Eater was making successful runs too.  Shouldn't they only be turned up if archives is actually accessed?

**Comment by Saintis** [comment]
If eater was the root of the issue, then it is working at intended and we might not have to fix anything.

**Comment by nealterrell** [comment]
Closing this as it looks to have been a rules misunderstanding, and Noah's #3686 shows Alice working well.
