### ISSUE TITLE
Clone Chip Medium on to Djinn with Grimoire

### ISSUE THREAD

**Issue by timeh300** [mtgred/netrunner#369]
I used clone chip to first install a medium on to my rig normally. It gained the token from the installed Grimoire, and then I manually hosted it on to djinn.  The medium would not gain further tokens on successful R&D runs until i removed it back to my hand and re-installed on to my rig unhosted by djinn. I did not attempt to re-host it on djinn to see if the issue was caused by the clone chip or not.

**Comment by mtgred** [comment]
Thanks for reporting the issue. I will try to fix the problem by the end of the week. Meanwhile, a workaround is to drag Medium back to hand, add yourself 3 credits, 1 click and install on Djinn directly.

**Comment by JoelCFC25** [comment]
Somewhat related--I think `get-virus-counters` in `core.clj` needs an update on the line for the Hivemind. When Hivemind has counters and is hosted on Djinn, they don't get counted when doing an R&D access with Medium.

**Comment by nealterrell** [comment]
Yes, get-virus-counters needs to be updated to use `(all-installed)`. Generally anything that looks in `[:runner :rig]` needs to be updated. `all-installed` will find installed cards even if they are install-hosted (not counting Personal Workshop/Supplier).

**Comment by mtgred** [comment]
The issue has been fixed. The server will be updated tomorrow.

**Comment by mtgred** [comment]
The fix has been deployed.
