### ISSUE TITLE
Respirocytes effect does not deactivate upon trash

### ISSUE THREAD

**Issue by inniscor** [mtgred/netrunner#3699]
Respirocytes expires after three draws (tokens keep track of this) and should be discarded and its effect end. Currently the draw effect from respirocytes doesn't expire after the card trashes.

Steps to reproduce:
1. Install respirocytes and discard all cards in hand. Pass turn.
2. On another turn discard last card in hand. Pass turn.
3. Repeat step 2 twice more.

Expected result: The first three turns you are down to 0 cards you draw one card, but the fourth you do not draw as respirocytes was trashed.

Actual result: Every turn you drop down to 0 cards (up to and beyond three turns) you draw a card from respirocytes.

**Comment by nealterrell** [comment]
The issue is on this line: https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/hardware.clj#L952 . The `keyword` function takes 1 argument, not two; the line should be `(keyword (str "repirocytes" (:cid card)))`.
