### ISSUE TITLE
Mwanza and Shiro (different problem)

### ISSUE THREAD

**Issue by mystermerry** [mtgred/netrunner#3714]
Issue 1: Upon firing of second Shiro sub mandating access, all access effects are fired at once and the chat log shows both players what cards were accessed regardless of access effect or not.
Issue 2: Credits are not granted to Corp following the end of this access.
Issue 3: Upon successful run and access of R&D following a Shiro access, the runner accesses an additional 3 cards on top of the  extra 3 mandated by Mwanza.

**Comment by Saintis** [comment]
This might be deal with in the upcoming access rewrite

**Comment by presheaf** [comment]
I am not sure if it will properly fix issue 1, but one can hope. The other 2 should be.

**Comment by NoahTheDuke** [comment]
This should be fixed. Does this still happen?
