### ISSUE TITLE
R&R cards not loading

### ISSUE THREAD

**Issue by TheRealC** [mtgred/netrunner#3718]
Hia! 

I realize this may just be me being impatient, but the newly uploaded R&R cards _mostly_ don't seem to load into games. If you pick an R&R Identity, it will not let you choose the deck from the lobby, and if you add R&R cards to an old deck, those cards will simply cease to exist once the game begins, leading to 37-cards decks and such.

This doesn't affect every card; Acme Consulting loaded just fine, The Outfit seemingly works, and I've heard Hangeki exists. However, Sportsmetal, Saraswati, Game Changer and Fast Break all are not selectable/do not load in.

And yes, I've force refreshed. Repeatedly.

Cheers,
The Real C

**Comment by jwarwick** [comment]
We updated the database, but I believe the game server didn't reload the cards. I've paged the right people to try and get the server restarted.

**Comment by nealterrell** [comment]
Just fixd.
