### ISSUE TITLE
Checkpoint. dmg doenst fire and trace causes long lag spike 

### ISSUE THREAD

**Issue by t-lor** [mtgred/netrunner#373]
So i recently played around with checkpoint ice.

-If u let the trace fire, the corp can set the trace,  the runner gets the trace window.  but setting it and clicking on ok  creates a 2 - 3 min lag burst before actually doing something

-if the trace fires, and the run is succesfull.  theres no way to apply he dmg ?

this was discovered when playing with online vs someome.  Then i tried it playing a agame against myself using 2 browsers  on the same pc.  Same thing happens.
Normal traces (eg. sea source)  where no problem.

**Comment by qmsm** [comment]
Just got the exact same thing with Checkpoint. Trace causes a long lag and the damage has to be applied manually (haven't checked if it's actually implemented though).

**Comment by nealterrell** [comment]
Fix submitted in #556!
