### ISSUE TITLE
Bug: The endgame 'Damage dealt' stat is not calculated correctly if the runner has Titanium Ribs installed.

### ISSUE THREAD

**Issue by Jonathan-L** [mtgred/netrunner#3732]
Any damage taken by the runner while titanium ribs is installed does not count towards the 'Damage Dealt' stat on the end game stats screen.

To reproduce as the runner:
1) Perform /take-net 1 
2) Install Titanium ribs
3) Perform /take-net 1
4) Concede

We'd expect to see 4 damage dealt here, but only one is shown.

**Comment by NoahTheDuke** [comment]
Good catch. We'll get it fixed!
