### ISSUE TITLE
Game Completion Rate of 106%?

### ISSUE THREAD

**Issue by x3N1GM4x** [mtgred/netrunner#3737]
Saw someone with a 106% completion rate earlier:

![image](https://user-images.githubusercontent.com/10621139/42478161-97f3be5e-83cb-11e8-9c3c-a5e2d41e0594.png)

Am guessing this is some kind of bug with the calculation - have obfuscated the username here, but can provide it if this is necessary for resolving the issue.

**Comment by danhut** [comment]
I suspect this is due to a bug in the first interaction of the stats code.  We did not do a reset to resolve it.  Simple "fix" is to hide by maxxing the completion rate at 100%
