### ISSUE TITLE
On The Lam does not work successfully after Hard Hitting News

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3746]
When HHN is played and On The Lam is installed, the trigger to 'avoid tags' appears, but the effect does to trigger if you say 'yes'. There is no way manually to trigger On The Lam either.

For completeness, this was in Geist, with OTL installed on Tech Trader.

**Comment by LessRekkless** [comment]
On the Lam doesn't seem to be functional in _any_ situation.
