### ISSUE TITLE
Citadel Sanctuary, Corporate Grant, and Thunder Art Gallery causing credit loss on Corp turn

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#3751]
Expected interaction: Citadel Sanctuary initiates a trace at the end of the Runner's turn. If successful, Thunder Art Gallery installs a card, triggering Corporate Grant on the Runner's turn.

Current interaction: The Corporate Grant trigger happens on the Corp's turn.

**Comment by Saintis** [comment]
Sounds like the logic for checking when the turn changes is too early, hopefully an easy fix.

**Comment by Saintis** [comment]
Actually, looks like Citadel Sanctuary effect is not async, which might be the cause of the problem.

**Comment by nealterrell** [comment]
Citadel shouldn't need to be async, I don't think -- its resulting effect is not async, and traces (like prompts) are automatically inferred to be async and completed when the resulting effect completes.
