### ISSUE TITLE
Geist + Laguna Velasco

### ISSUE THREAD

**Issue by djkokakola** [mtgred/netrunner#3759]
So, was testing hayley with DJ fenris today, and found that using a bin ability triggered geist (as it should), but that laguna also gave me an extra draw off it, which it shouldn't. I know it's unimplemented, so I don't know if this is an error with DJ Fenris, or if it's merely the geist + laguna interaction causing it.

**Comment by Saintis** [comment]
I cannot reproduce this locally, it works fine for me. Was this on the main server or the dev server?

Do you have any other details that could help reproduce the issue? What card did you trash to trigger Geist? Did you have any other cards installed?

**Comment by djkokakola** [comment]
Hayley, fenris hosted Geist, Laguna installed. Same Old Thing triggered
Geist, and then it drew two instead of one, if I'm remembering correctly.
