### ISSUE TITLE
Dev: Thunder Art Gallery not working with Liza properly

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#3763]
Thunder Art Gallery offers the ability to install - but does not include cards just drawn with Liza in the prompt list

Combo in play is:
- Qianju PT (to avoid tag)
- Adjusted Chronotype
- Liza

**Comment by nealterrell** [comment]
This is fixed by #3756 which turns TAG into a selection prompt.

**Comment by nealterrell** [comment]
Actually it's not. Liza is coded as tag first, then draw. Technically the two events happen simultaneously and the runner chooses the order. I think we can safely reverse them -- is there ever a reason you'd want to be tagged first, BEFORE the draw occurs?

**Comment by Saintis** [comment]
I coded it that way since that's how Account Siphon is coded. I'm not sure account siphon has a specific reason for that. There might be some ruling saying you cannot use AS money to avoid tags with NACH

**Comment by nealterrell** [comment]
That is exactly the reason; you gain the tag and the money in the same window and can't spend the funds on avoidance.

**Comment by nealterrell** [comment]
Great question. Might need to go to Jako.

**Comment by nealterrell** [comment]
General consensus is it's the same exact wording and ruling at Siphon and NACH, so... NO BUG!

**Comment by Saintis** [comment]
Yay!

**Comment by nealterrell** [comment]
Jakodrako confirms. BAD DAN.

**Comment by Saintis** [comment]
Makes me sad cause that makes TAG less useful 😞

**Comment by danhut** [comment]
Oh crap. I had my deck ready for a GNK tonight.

**Comment by danhut** [comment]
And now have to go to work
