### ISSUE TITLE
Dev: Patchwork cannot be used with a Thunder Art Gallery free install

### ISSUE THREAD

**Issue by danhut** [mtgred/netrunner#3765]
These two cards cannot be used together as the install from Thunder Art Gallery does not allow you to interact with the Patchwork ability which you click on from the tableau

**Comment by nealterrell** [comment]
Yes, even with #3756 this will be problematic. You will need to prime Patchwork before you avoid/remove the tag, because once TAG triggers the cursor will turn into a selection and you won't be able to click Patchwork. I don't see a way around except manual adjustment.

**Comment by danhut** [comment]
Maybe an option on Patchwork to refund the 2c at the cost of a card?
A bit like how we handle Dinosaurus and others.

**Comment by NoahTheDuke** [comment]
Should be handled by #4262
