### ISSUE TITLE
Personal Workshop + Autoscripter

### ISSUE THREAD

**Issue by KevinElias** [mtgred/netrunner#377]
Autoscripter still gives an extra click when installing programs off of personal workshop.

**Comment by nealterrell** [comment]
Hmm, "from the grip"... that's gonna be tricky. Thanks for the report.

**Comment by DominicKexel** [comment]
I'll take a look if I find the time

**Comment by DominicKexel** [comment]
I would solve this as follows:

when a card get's moved, let's keep track where it came from by adding the keys `:previous-zone` and `:previous-hosted`, so we can check if `:hand` in `:previous-zone`  and `nil? :previous-hosted` in `req` of Autoscripter.

This works, but I think it would be better to change the `:zone` of hosted cards. E.g. when you host something on Personal Workshop, the `:zone` of the card is still `(:hand)`.

Is there are reason for this? I think we could change this to something like `:hosted`, so it would be enough to add the `:previous-zone` key to a card that is moved and then let Autoscripter check if `:previous-zone` contains `:hand`.

**Comment by mtgred** [comment]
It's best to change the `:zone` when the card is hosted.

However the `:runner-install` event get the installed card as a parameter, that is with the destination `:zone` so you lose the origin information. 

Beside Personal Workshop, it should be tested with cards like Clone Chip or Scavenge too. You can also implement Exile once the origin mechanism is in place.

**Comment by DominicKexel** [comment]
As I said I would simply add a `:previous-zone` to a card once it gets moved.

This should also make it easy to implement Exils ability.

Let's see if I find some time this weekend.
