### ISSUE TITLE
RNG Key + Crisium Grid

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#3772]
When you run R&D, and they rez Crisium Grid, RNG key does not fire. This is correct.

If you trash Crisium Grid and run again, RNG key should fire, but does not. This is incorrect.

**Comment by queueseven** [comment]
True. Here's the relevant ruling: http://ancur.wikia.com/wiki/Crisium_Grid_v._Security_Testing_Reversal_Ruling

It's worth to note that this behaviour (not triggering on the second run) was ruled to be correct some time ago.

If this is indeed broken, I guess Security Testing and other cards may not work correctly with Crisium Grid, too.

**Comment by LessRekkless** [comment]
I know Paragon doesn't trigger if Crisium Grid was hit on the first run.

**Comment by NoahTheDuke** [comment]
At some point this was fixed!
