### ISSUE TITLE
Broad Daylight does not add agenda counters when scored and disrupts other when scored abilities

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#3777]
Broad Daylight was scored against Leela with Gang Signs installed. Arella was installed on the Corp side.

All 'when scored' abilities were disrupted, except the gain bad publicity ability of Broad Daylight, and no agenda counters were added to Broad Daylight, although the advancement counters remained on the agenda.

When agenda counters were added to Broad Daylight with the /counter command, the ability worked as expected.

**Comment by nealterrell** [comment]
What other corp cards were in play? It definitely sounds like the gain-bad-pub routine hung. Did you have any prompt as corp?

**Comment by nealterrell** [comment]
NM, it's a simple problem with The Outfit.

**Comment by marc-jones** [comment]
Sorry, I should have said it was in The Outfit, well deduced!

**Comment by nealterrell** [comment]
No problem, it's the only card in the game that triggers off gaining bad publicity, which based on your description was exactly where the game got stuck :). I was able to reproduce it on the dev server only as The Outfit.
