### ISSUE TITLE
Code Replicator/Thimblerig - 'when runner passes' issue?

### ISSUE THREAD

**Issue by e10hssanamai** [mtgred/netrunner#3778]
Played a I ran against a jijna ice tower. It had Kagugo on the top, two unrezzed ice, another kagugo, and a thimblerig on the innermost position. He rezzed the Thimblerig, and rezzed a Code Replicator. After I passes the thimblerig, he tried to put the thimblerig on the outermost position, swapping it with the first kagugo. It only put me at the Kagugo and not on the outermost Thimblerig. 

So it looks like maybe the program has an issue with multiple simultaneous 'when the runner passes' corp triggers.

**Comment by nealterrell** [comment]
What are you expecting to happen here? A Thimblerig swap does not change the position of your run.

**Comment by nealterrell** [comment]
Also, neither of these cards have automatic triggers, they both use manual abilities, so there shouldn't be any _automation_ issues.

**Comment by e10hssanamai** [comment]
I guess what they were thinking was, Thimblerig fires first, moving itself to the top of the server. Then they wanted code replicator to fire, forcing the runner to go back to Thimblerig, which is now on the top of the server.
They attempted to do that. Thimblerig (innermost ice) fired, and moved itself onto the outermost position just fine. They then fired code replicator, and code replicator made me re-approach the innermost ice again.
I honestly don't know if that is an allowed rule. It seemed correct to me and a few spectators. I'm sorry to waste your time if it isn't an issue.

**Comment by nealterrell** [comment]
Reporting issues is never a waste of time 😃 .

We'll probably have to wait for a UFAQ to get this right. Not sure right now what the correct interaction is when you Thimble first and Replicator second.
