### ISSUE TITLE
Feature Request: Installing a new region over an old one

### ISSUE THREAD

**Issue by CasMat9** [mtgred/netrunner#3784]
I meant to request this a while ago. So the situation happened where I wanted to install Lady Liberty with Tech Startup into a server that already had a region in it. Obviously, I would just want to trash the region to install the new one. But the way region overwriting works now, the install just fizzled with the reminder message popping up, meaning I had to go back and fix it manually.

I know there's an easy workaround here of just pre-trashing the installed region, but I thought maybe given the way asset/agenda overwriting works, there could be a similar solution for overwriting regions as well?

**Comment by NoahTheDuke** [comment]
This is a great idea
