### ISSUE TITLE
Hades Shard creates a Successful Run / Jack Out prompt outside a run

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#3788]
Install Hades Shard (not during a run, pay the 7 credits).

Trash Hades Shard to access Archives.

Suddenly there's a dialog that should only be shown during a run:

![image](https://user-images.githubusercontent.com/3126597/42998199-9f82eaa4-8c19-11e8-9453-4f64048e8ab2.png)

(the corp sees a dialog, too).

**Comment by Zerothmaxima** [comment]
Popping Hades also lets you access upgrades at the root of Archives, which is wrong.
