### ISSUE TITLE
Edward Kim Ability Activating on Archive Run

### ISSUE THREAD

**Issue by timeh300** [mtgred/netrunner#379]
Hi, Edward's ability should be disabled but not activate to re-trash an operation in archives on a run. This is completely irrelevant in 99.9% of cases, but can have an impact if Hostile Infrastructure is in play.

**Comment by DominicKexel** [comment]
Shouldn't be that hard to fix. Either some lambda mumbo jumbo in the card itself, or better change the trash function to ignore cards that are already in :discard.

**Comment by gammanet** [comment]
if i recall the ruling, his ability actually does trigger when you run archives. 

28 Edward Kim
•	 If the first operation Edward Kim accesses is in Archives,
then he cannot trash another operation with his ability that
turn.https://images-cdn.fantasyflightgames.com/filer_public/f5/2e/f52e015b-dd10-4290-9fba-9b9d0303e0cc/adn_faq_21.pdf

realize this is annoying with hostile infrastruture, perhaps if it was a prompt on the first one you access?

**Comment by nealterrell** [comment]
What needs to happen here is for Kim's ability to not call `(trash target)` if target is in Archives. Everything else is working fine.

**Comment by DominicKexel** [comment]
Since the rulebook says

> Trash: The act of moving a card to its owner's trash pile.

and accessing archives:

> Archives: The Runner accesses all cards in Archives and any upgrades in its root. The Runner turns all cards faceup when accessing them, and does not need to keep them in order. The Runner steals all agendas in Archives and **cannot trash cards that are already in Archives**. After accessing Archives, all cards in Archives return to Archives faceup.

I think this should be handled by the `trash` function; this is nothing special to Kim's ability, but a general rule that cards in archive can never be trashed. The game engine should not allow that.
