### ISSUE TITLE
Uninstalling DJ Fenris ID bug

### ISSUE THREAD

**Issue by BifftheBawss** [mtgred/netrunner#3791]
I've had in happen in a couple of games now where, when having to uninstall DJ Fenris, the hosted ID is removed from game, but the Runner's ID is "overwritten" as well. 

Ex: playing Geist with Hayley hosted. Uninstalling Fenris removes Halyey from game, but also changes Geist into Hayley, though only visually (I.e. Geist still triggers normally).

Love the work you do, thank you so much for contributing this to the community!

**Comment by NoahTheDuke** [comment]
Thanks for the report! We'll take a look.
