### ISSUE TITLE
Action sounds delayed until further actions

### ISSUE THREAD

**Issue by Quarg** [mtgred/netrunner#3793]
Various sounds from the opponent taking actions, (eg: playing events) are delayed until further later actions (eg: making a run, ending the turn.)

I have not actively tried to keep track of details in order to try to determine when exactly this does / doesn't occur, but my immediate thought is that the sound events are only being sent at the same time as some other thing being sent; with my immediate suspicion being that it's tied to changing the set of prompts available to the player receiving the packets.

**Comment by nealterrell** [comment]
I deployed a maybe-fix around an hour ago. Any improvement?
