### ISSUE TITLE
Divide and Conquer should access HQ before R&D, but does it the other way around

### ISSUE THREAD

**Issue by LeonardQuirm** [mtgred/netrunner#3795]
Divide and Conquer text:
"Make a run on Archives. If successful, after accessing Archives, access 1 card from HQ, then access the top card from R&D."

In the current implementation, it accesses R&D first, then HQ after all R&D accesses are done.

**Comment by NoahTheDuke** [comment]
Thanks!

**Comment by hiddenaway1** [comment]
Am I right in thinking that this just requires the following change in events.clj?

Before:
`{:async true
                   :effect
                   (req (wait-for (do-access state side [:**rd**] {:no-root true})
                                  (wait-for (do-access state side [:**hq**] {:no-root true})
                                            (effect-completed state side eid))))}`

After:
`{:async true
                   :effect
                   (req (wait-for (do-access state side [:**hq**] {:no-root true})
                                  (wait-for (do-access state side [:**rd**] {:no-root true})
                                            (effect-completed state side eid))))}`

**Comment by NoahTheDuke** [comment]
That’s very possibly it. I don’t know why the first is getting resolved before the second, but as a stopgap that would probably work. Best thing would be to try it yourself!

**Comment by nealterrell** [comment]
Yeah the effect is just backwards.
