### ISSUE TITLE
Ronin's conditional ability is in the list of things you can do with it when it is unadvanced

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#38]
The deal 3 damage ability (without text, see #37) is listed as available as long as the card is rezzed.  Note that clicking on it while the card has fewer than four advancement counters __does not__ trigger the ability, so this isn't a game breaker, but I wanted to get it recorded.

**Comment by JoelCFC25** [comment]
I asked about this some time ago, and as I recall it was going to be very tricky to hide/reveal card abilities on a conditional basis.
