### ISSUE TITLE
Missing a spectator mode

### ISSUE THREAD

**Issue by DominicKexel** [mtgred/netrunner#380]
I know you want it, too :-)

**Comment by JoelCFC25** [comment]
Requested way back in #49! ;)

**Comment by DominicKexel** [comment]
Ha, totally missed that somehow. Feel free to close as duplicate. I'm working  on the list of active users, but I don't know if it makes auch sense if you can't directly message a user.

**Comment by DominicKexel** [comment]
Closing this because it's a duplicate.
