### ISSUE TITLE
Patchwork doesn't trigger on certain cards. 

### ISSUE THREAD

**Issue by yehaaa6** [mtgred/netrunner#3800]
Just played a game where I hard installed Paperclip and D4v1d from hand, Patchwork did not trigger on either install. when I played Same Old Thing after playing Paperclip, Patchwork triggered. Just a heads up.

**Comment by nealterrell** [comment]
Did you click Patchwork before the install?

**Comment by yehaaa6** [comment]
oh oops! I forgot that it's a "may" and not "the first card" played the turn. yeah it works.
