### ISSUE TITLE
Local JNet Card Browser Issues

### ISSUE THREAD

**Issue by Kortako** [mtgred/netrunner#3805]
Sorry if this isn't the right place for this....

About a month ago I was fiddling with trying to set up a local jnet instance on my Windows desktop and managed to get it working.  Now, after pulling the newest changes from Git (SHA-1 5ed3f), the card browser no longer allows me to change any of the dropdown filters on the side; the focus is always forced to the search box and I can't click out of it.   Also, there is noticeable lag in the transition from the Cards tab to the Deck Builder tab, which didn't exist before.

If I revert to the commit I was at previously (it's a bit old, SHA-1 starting with 5e401) and rebuild everything, all of these issues go away and it works fine.  And then re-updating again brings it back.  I've tried clearing browser cache in Chrome, etc.  It doesn't look like actual JNet has any of these issues on my browser at all.  Any ideas?

**Comment by Saintis** [comment]
Have you rebuilt the ClojureScript files? We recently changed the client side quite heavily.

**Comment by Kortako** [comment]
I believe so..that's just doing "lein cljsbuild auto dev", right? I'm still learning how all this fits together, so you'll have to bear with me...

**Comment by Kortako** [comment]
So I decided to try this again from scratch, cloning a new copy of the repository.  After doing that, I did these commands found on the [guide page](https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development) (skipped the mongodb part because I already have it set up from the old instance):

$ lein deps
$ bower install
$ lein fetch --no-card-images
$ lein cljsbuild auto dev
$ stylus -w src/css -o resources/public/css/
$ lein repl

After doing this, I still have the issues I mentioned with the filters on the cards tab (even with no images, of course).  I've also tried switching to Edge just to test a different browser, and am still seeing funky results, but spam clicking on the filters will eventually let it open.

Is there anything you see that I'm doing wrong here?

**Comment by Kortako** [comment]
Just a small update, I've noticed that the issue only shows up after the commit that merged the dev branch into master (3687bc).  The one right before it still works (3e521).  It looks like that branch was a fairly extensive rewrite of the clientside UI files, and with a bit of testing and rebuilding that branch at various commits, the cardbrowser bug I'm talking about happens to me all the way since the beginning of the rewrite back in May.  I'm not sure why I'm experiencing this on my computer, and not on Jinteki.net proper, unless it's not actually updated that far yet?

**Comment by jwarwick** [comment]
I just pushed a PR (#3839) which might help with some of these issues.
