### ISSUE TITLE
Game stuck with Jinja waiting for 419 and 419 waiting for Jinja

### ISSUE THREAD

**Issue by samb91** [mtgred/netrunner#3806]
The game entered a state that couldn't be continued with both sides waiting for the opponent's trigger to resolve - a 419 trigger on the runner side and a Jinja City Grid trigger on the corp side.

The screenshot below should show the flow of events that led to the bug, but I've added it in text as well:

The corp (Sportsmetal) has a remote server with a Jinja City Grid installed and rezzed in it, and Arella Salvatore and Ash installed in it and unrezzed.
The runner (419) ran HQ and used 4 Turning Wheel counters to access 2 additional cards
419 accessed and stole a Corporate Sales Team. Sportsmetal chose to gain 2 credits.
419 then accessed another Corporate Sales Team. Sportsmetal then chose to draw 2 cards.
Sportsmetal drew Turing and IP Block (I believe in that order). Jinja City Grid fired, and Sportsmetal chose to reveal and install Turing. Before Sportsmetal could resolve the Jinja trigger for IP Block, Sportsmetal had to wait for 419 to choose to resolve its trigger on the installed-via-Jinja Turing. However, the 419 player stated that on their end they had a message saying "Waiting for the corp to resolve Jinja City Grid".
The game could not be continued as both players were waiting for the opponent's trigger to resolve before they could resolve their trigger (that the opponent was waiting on to be resolved before they could resolve their's). A deadlock, of sorts.

![jinja419bug](https://user-images.githubusercontent.com/2511188/43049882-435f1984-8df7-11e8-9c74-4417105cfe66.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! Does this still happen?
