### ISSUE TITLE
Exchange of Information and Game End

### ISSUE THREAD

**Issue by dullveggie** [mtgred/netrunner#3807]
I used Exchange of Information to attempt to swap Global Food Initiative in Runner area for Breaking News in Corp (i think it was this combination). This should have left me on 6 agenda points as I assume the swap should be simultaneous. Instead it ended the game with me winning as I gained GFI before losing BN.

**Comment by NoahTheDuke** [comment]
Thanks for the report! We'll take a look.

**Comment by NoahTheDuke** [comment]
Does this still happen?

**Comment by dullveggie** [comment]
Haven’t had another game where it could have happened, so can’t tell.

**Comment by NoahTheDuke** [comment]
Cool, no worries. I’ll try again this week
