### ISSUE TITLE
Rover Algorithm does not fire if ICE is rearranged

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#3808]
Rover Algorithm is supposed to build up counters whenever the runner passes the ICE it is hosted on. However, if that ICE has _ever_ moves to a different position and/or server, the trigger seems to break and the card will never again add counters. 

Tested with Thimblerig.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by LessRekkless** [comment]
I've noticed this also breaks Kyuban, so I would guess it breaks any card that is hosted on a card that is rearranged.

**Comment by NoahTheDuke** [comment]
Having solved the "Kyuban disappearing" issue, I feel like I could tackle this one too.
