### ISSUE TITLE
Scheherazade misclick causes programs to disappear

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#381]
Sorry, I've got two issues to report today! It turns out playing a Professor deck means you get to play with lots of different cards, so it's quite easy to find bugs with them.

If you misclick when using Scheherazade's "Host an installed program" action and ask it to host itself, it gets into a loop of some kind and all of the programs disappear. They're not trashed, removed from play, returned to your grip or whatever, they just disappear. This makes it especially hard if you're playing with Levy. Any newly installed programs also disappear, and your used MU stays the same which would suggest that the programs are still considered to be there, but aren't visible at all.

**Comment by JoelCFC25** [comment]
I have an idea to fix this that I'll try tonight.
