### ISSUE TITLE
Turning Wheel and Divide and Conquer

### ISSUE THREAD

**Issue by yehaaa6** [mtgred/netrunner#3810]
The first run on R&D or HQ after using TTW with Divide and Conquer does not leave a counter on TTW, even if I jack out on that first run. seems to work on subsequent runs.

**Comment by NoahTheDuke** [comment]
So I'm understanding this, you mean that you have a Turning Wheel installed, and you play Divide and Conquer. After the D&C run ends, you make a new run on R&D or HQ, and when you access a non-agenda, Turning Wheel doesn't gain a counter. Then you make a second run on R&D or HQ, and when you access a non-agenda, Turning Wheel does gain a counter. Do I have that right?

In my testing, I can't replicate this. Every time I make a non-agenda-accessing run on R&D or HQ with TTW installed, it gains a counter. Do you have any screenshots or logs of this happening?
