### ISSUE TITLE
Acme

### ISSUE THREAD

**Issue by limnrix** [mtgred/netrunner#3814]
Virtual extra tag remains throughout run, rather than after first ice, wrongly triggering cards like Quantum Predictive Model and Dedicated Response Team. Would be useful to have a tag indication like that of Paparazzi, as well.

**Comment by nealterrell** [comment]
Acme is coded to disable itself after passing the first piece of ice. We'll need more information about the run you made in order to diagnose this.

**Comment by Zeofar** [comment]
I've figured out the likely issue here; The :rez event on Acme will be triggered by assets/upgrades/etc while in the outermost position, which makes the runner float extra virtual tags. Just needs a little extra logic to prevent irrelevant cards from interacting with the ability.

**Comment by limnrix** [comment]
Now that the tag UI is broken by the attempt to show the virtual tags, I can see that an upgrade or asset rez results in 2 virtual tags.
