### ISSUE TITLE
Paragon does not say where the card went

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#3817]
The log message for Paragon does not tell the corp if the card was put on the bottom of the deck or not.

Also, Paragon triggers even with the play pattern of:
Dirty Laundry (successful)
install Paragon
run again (successful) - but not first successful run of turn

**Comment by nealterrell** [comment]
It actually does print a message _only_ when the card is put on the bottom of the stack. We'll add the second message too.
