### ISSUE TITLE
Medium hosted on Scheherazade doesn't accumulate counters

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#382]
I haven't tested this for Nerve Agent, but if you host Medium on Scheherazade it doesn't accumulate counters on successful R&D runs.

**Comment by JoelCFC25** [comment]
The root cause is the same issue from #369, but it's good to confirm that it's definitely the state of being hosted rather than anything specific to Djinn or Scheherazade.

**Comment by darlingsensei** [comment]
Confirm that this is true and I would also add that it will not gain counters at all. Successful runs and grimoire both yield no counters.

**Comment by nealterrell** [comment]
This has been fixed!
