### ISSUE TITLE
Aumakua - Archives

### ISSUE THREAD

**Issue by darkmite2** [mtgred/netrunner#3821]
Aumakua gives counters with zero cards in archives. It should only give counters when it accesses / exposes a card

**Comment by nealterrell** [comment]
Thank you for the report, but this is the correct behavior. "Whenever you access cards" refers to reaching the Access step; it does not require any individual card to be accessed. 

Related UFAQ ruling:

"Q: Does Aumakua trigger if the Runner uses Eater during the run?

A: Yes. Aumakua cares about the access step as a whole, not about accessing any specific card(s)."
