### ISSUE TITLE
Dedicated Response Team + Doppleganger

### ISSUE THREAD

**Issue by sebastian-nowakowski** [mtgred/netrunner#3825]
I just had strange behaviour on jineki, concerning the Dedicated Response Team. Runner was tagged, initiated run with doppleganger on HQ. Accessed cards. Then used doppleganger, and started run on the remote server. The dedicated response team (which have been rezzed during the HQ run) didn't fire. So we triggered it manually. And, when the second doppleganger run ended, the dedicated response team fired twice, for both runs. As far as i know, it should fire separately after each run, right? Posting as a bug, or smth :)

**Comment by Saintis** [comment]
Sounds like Doppelgänger isn't triggering `:successful-run-ends` correctly, or Doppelgänger's trigger takes too high priority over DRT.

**Comment by nicohasa** [comment]
This is actually the _correct_ behavior. Both DRT and Dopplegänger trigger on successful run, but as it's runner's turn Dopplegänger happens first, starting a new run. When this run ends, DRT triggers again, and then the first DRT trigger happens.

(See [this](http://ancur.wikia.com/wiki/Doppelg%C3%A4nger_%26_Dedicated_Response_Team_Interaction_Ruling))
