### ISSUE TITLE
Malia Z0l0k4 + DJ Fenris

### ISSUE THREAD

**Issue by mcalvo** [mtgred/netrunner#3835]
Using Malia Z0l0k4 to blank DJ Fenris does not stop the hosted ID ability from triggering.

**Comment by Saintis** [comment]
This is not implemented yet, needs some extra magic to work.

**Comment by Saintis** [comment]
Magic has been applied, should be fixed in the next update hopefully :)

**Comment by mcalvo** [comment]
Thanks for the quick fix!
