### ISSUE TITLE
Some Surveillance Sweep (+Sol) interactions bugged

### ISSUE THREAD

**Issue by rapku** [mtgred/netrunner#3837]
Was playing New Angeles Sol, and encountered the following bugs when using Surveillance Sweep
**Case 1**: Server with 1 agenda and 1 Intake:
Runner steals agenda, Surveillance Sweep trashed from scoring. After replaying Surveillance Sweep using Sol, trace on Intake + other sources (ie. Senai) followed normal trace rules rather than Surveillance Sweep rules.

Additionally, not sure if this is due to Surveillance Sweep or not, but after trashing Intake, the run didn't end by itself, and we've had to close the prompt for the runner manually.

**Case 2**: Surveillance Sweep and Amani Senai:
I encountered 1 instance in which the Surveillance Sweep trace fired when I scored an agenda on my turn.

**Comment by NoahTheDuke** [comment]
I believe this was fixed with #4051. Please let me know if the issue reappears. (Fix should hit prod next week.)
