### ISSUE TITLE
Mulligan cards not flipping faceup on Safari

### ISSUE THREAD

**Issue by nicohasa** [mtgred/netrunner#3838]
Happened to @Saintis and Elwin, at least

**Comment by Saintis** [comment]
Cards are animated flipping briefly (you see a sliver of the card) but they end up face-down. You can still hover the cards (and see the cards in your hand as normal). This does detract from the start screen to the point where I now mostly just immediately click to close it.

**Comment by NoahTheDuke** [comment]
I suspect this can't be fixed because of Safari's bad handling of css stuff.
