### ISSUE TITLE
Shadow parsing issue in deckbuilder

### ISSUE THREAD

**Issue by jakerosen** [mtgred/netrunner#3844]
I happened upon a minor bug when pasting some beginner decklists into the deckbuilder.  Most cards seemed to parse correctly when formatted as:
1x Pop-up Window (Revised Core Set)

or even:
1x Pop-up Window (asdflk)

However, Shadow was an exception.  It seemed that anything following the word Shadow would cause the parser to fail and be unable to find the card, for instance this did not work:
2x Shadow (Revised Core Set)

I was able to reproduce this bug every time I tried.

Edit: 
Assassin suffers from the same bug.
1x Assassin (Data and Destiny)

did not successfully parse.  It's worth noting that most cards appear to parse regardless of what follows the legal card name, but Shadow and Assassin (possibly others) continue to attempt to parse garbage.  It just occurred to me that this may be due to other cards having Shadow and Assassin in their name (The Shadow Net, The Shadow: Pulling the Strings, and Character Assassination).  Perhaps it's not a bug after all.  Please close the issue if it's not noteworthy.

**Comment by NoahTheDuke** [comment]
Is this still happening?
