### ISSUE TITLE
Data Raven Issue

### ISSUE THREAD

**Issue by CritHitd20** [mtgred/netrunner#3848]
I'm not exactly sure what is causing it, but my ability to perform actions as runner has completely locked up when I encounter a Data Raven. In all cases I was Valencia Rebirthed into Omar with DJ Fenris (in 2 cases Steve and in 1 Los), Patchwork, and Turning Wheel installed. All three corp IDs were different, as was everything else about the game state (different breakers, different economy cards, different currents, etc.). After reaching the encounter phase I am unable to take click actions, use abilities on installed cards, or modify the game state using the + and - buttons. I am able to take actions using /prompt. Please let me know if there's anything I can do to help further.

**Comment by NoahTheDuke** [comment]
Might be issue with the recent tag rewrite. Thanks for the report!

**Comment by CritHitd20** [comment]
Np. As an update, this happened again when tagged mid-run by Mausolus.

**Comment by jwarwick** [comment]
Any chance you took the Data Raven tag by clicking on the `+` button next to your tag count when you encountered it?

That's definitely broken in the current build.

**Comment by NoahTheDuke** [comment]
Played with a Data Raven recently, experienced no problems. Closing for now.
