### ISSUE TITLE
Jeeves Model Bioroids Incorrectly Adding a Click

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#3850]
Following happened with a rezzed Jeeves Model Bioroids: 4 clicks with 3 different actions before Jeeves added a click.

aenimosity spends  to use Elective Upgrade to gain .
suzume18
suzume18
actually i have to get ready and you are obviously gonna wint
aenimosity spends  and 4  to play Biotic Labor.
aenimosity uses Biotic Labor to gain .
aenimosity spends 2  and  to install a card in Server 2.
suzume18
suzume18
wait here it is
aenimosity spends  and 1  to advance a card in Server 2.
aenimosity spends  and 1  to advance a card in Server 2.
aenimosity uses Jeeves Model Bioroids to gain .
aenimosity spends  and 1  to advance a card in Server 2.
aenimosity spends  and 1  to advance a card in Server 2.
aenimosity spends  and 1  to advance a card in Server 2.
aenimosity scores Elective Upgrade and gains 3 agenda points.

**Comment by Saintis** [comment]
This is working as it should, the issue is that Jeeves will log that the Corp gains a click before the Corp spend click message. It still only triggers on the third advancement. 

This is unfortunately confusing and should be improved.

**Comment by aenimosity** [comment]
Ah fair enough. Derp on my part.
