### ISSUE TITLE
Sneakdoor Beta triggers successful run on HQ when deflected.

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#3852]
If the runner makes a run with Sneakdoor Beta, is deflected to another non-HQ server with a deflection effect such as Sand Storm, AgInfusion, or Mind Game, the run is still considered a run on HQ if it was successful. 

According to "if successful..." section on page 2 of the FAQ, this should not be the case.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Does this still happen?

**Comment by LessRekkless** [comment]
Yes, this still occurs.

**Comment by NoahTheDuke** [comment]
Thank you! I'll take a look!

**Comment by LessRekkless** [comment]
Happens with **Hot Pursuit** as well, so this may be endemic to many/most server-specific run cards.

**Comment by NoahTheDuke** [comment]
Whoops, forgot about this one! Thanks for the reminder.

**Comment by NBKelly** [comment]
This was fixed, and we've got unit tests for it via #6238
