### ISSUE TITLE
Haley and Off-Campus Apartment triggers

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#3854]
I believe Haley's ability and Off-Campus Apartment's ability (OCA) trigger in the same window.  I should be able to draw with OCA and then see if the new card is resource that I could install with Haley's ability.  This currently does not happen: Haley always fires first unless there is a _third_ trigger, at which point the interface allows me to choose the order of triggers (although if I don't choose to trigger OCA first, Haley again takes precedence and stops me from choosing it second).

This issue was seen with DJ Fenris hosting Haley.

**Comment by NoahTheDuke** [comment]
Sounds like one or both cards needs `:interactive true`
