### ISSUE TITLE
Rashida Jaheem automatic trigger

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#3855]
I just discovered that Rashida Jaheem triggers automatically when I click the Mandatory Draw button! Unfortunately, the mandatorily drawn card is shown before Rashida's prompt opens, so it's illegal to use Rashida this way.  Is there anyway for the prompt to occur before the mandatory draw, or are we stuck clicking Rashida, rezzing Rashida, clicking Start Turn, clicking Rashida, clicking her use ability, clicking Yes on the prompt, then clicking Mandatory Draw?

At worst, could we bypass the prompt if we click her "gain 3, draw 3" ability? It's pretty obvious that anyone who is going to click on that button will want to use that ability.

**Comment by ChooJeremy** [comment]
I'd like to try solving this issue.
