### ISSUE TITLE
Stealth breakers + Per-Run credits (bad pub/stimhack)

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#3858]
If you stimhack with cloak + dagger, and encounter a sentry, you will have to gain a credit with cloak before you use dagger. The money spent on dagger is taken from the stimhack money, and if you don't use all your stimhack money, the cloak credit lingers at the end of the run.

For example.

Start with 8c, use stimhack on news hound remote. Credit total is 17c (9c for run) SMC for dagger (5c, so 12c 4c for run) and use cloak to take a credit and then pay 3c on dagger to boost + break (here is the problem, it says 10c 1c for run but should be 2c for the run). When the run ends, you have 9c instead of the 8c you started with.

**Comment by LessRekkless** [comment]
This has been an open issue since 2015:
See #454, #1457, #2056.

**Comment by NoahTheDuke** [comment]
Implemented with #4262
