### ISSUE TITLE
Blockchain counts facedown transactions for its "on encounter" effect

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#3859]
When the "Gain Subroutines" option is clicked on Blockchain, the resulting number of subroutines counts facedown transactions as well as faceup ones - for example, if there are five faceup transactions and one facedown transaction in Archives, Blockchain will gain three subroutines when it should only gain two.

As an aside, it would also be useful to change the message to say "x uses Blockchain to gain y **additional** subroutines", as that makes the distinction between the printed and gained subroutines clear. (This may be useful wording to change on all ice that gain subroutines, even those that have no printed subroutines like Komainu just in case someone decides to pair it and Sub Boost or whatever, but it's a very fringe case!)

**Comment by ben-albon** [comment]
I think I could work on this?  It seems relatively straight forward?
