### ISSUE TITLE
When using Thunder Art Gallery with Jesminder Sareen, the "Successful Run" prompt duplicates.

### ISSUE THREAD

**Issue by CasMat9** [mtgred/netrunner#3860]
E.g., if Jesminder has Thunder Art Gallery installed and uses Hot Pursuit, the successful run prompt comes up an extra time. This doubles some successful run effects, e.g. Datasucker receiving 2 counters instead of 1. Also, this causes erroneous successful run triggers on cards installed with Thunder Art Gallery, such as Datasucker  gaining 1 counter despite not being installed until after the "Successful Run" trigger condition has been met.

**Comment by NoahTheDuke** [comment]
Does this still happen?
