### ISSUE TITLE
Upgrade install fizzles

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#3862]
Jinja City Grid installed in root of RnD. 
Runner Omar runs into archives.
Corp rezzes Architect, fires. Corps selects of the 5 cards a Crisium Grid and wants to over install on RnD (b/c it's another region Upgrade). 
Not working. Crisium Grid card is gone (both players count and see only 48 cards instead of 49) and CG turns up in the next turn in the corps temporary zone. No warning message as when over-installing assets in remote.

**Comment by NoahTheDuke** [comment]
Is this still happening?
