### ISSUE TITLE
Leela's ability bugs game when corp has no cards out

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#387]
Title. I stole agenda when there was nothing on board and game froze.

**Comment by JoelCFC25** [comment]
I can't reproduce this--I tried scoring as Corp against Leela with no other cards installed, got the prompt as Leela, and just hit "Done". Ditto for running a naked agenda with no other Corp cards installed--hit "Done" as everything proceeded normally.

**Comment by JoelCFC25** [comment]
Has anyone else seen this or been able to reproduce it?

**Comment by queueseven** [comment]
I played some games with Leela; no issues found (even with no cards installed).

**Comment by JoelCFC25** [comment]
Closing this until we see more reports (if at all).
