### ISSUE TITLE
Ability to add new, unimplemented cards on a person by person basis. 

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#3870]
This may be a little premature, given the likely reduced volume of card releases, but would would it be possible for players/deckbuilders to add unimplemented/unreleased cards to decklists. 

For example, if one of the nisei designers wanted to test a card, can we make it so they can add  "testresource1" to their decklists and make it possible to draw and play those cards, even if they had to arbitrate all the game changes (costs and effects and such) manually?

**Comment by NoahTheDuke** [comment]
We're currently working on something similar. One aspect that needs changing (which I'm working on) is our reliance on NRDB for all data. Once we move away from that, modifications such as yours will be much simpler to implement.

Thanks for thinking ahead!

**Comment by nealterrell** [comment]
To be clear, this is not something we will have on the main site, but will be an option for adding your own cards to a local instance of the site.

**Comment by NoahTheDuke** [comment]
Thanks for the clarification, Neal!

**Comment by bcsj** [comment]
Does this mean that the mail site in this future could "somewhat easily" potentially also support the custom identities for sealed play? (www.anrsealed.com)

**Comment by NoahTheDuke** [comment]
With the new reliance on the edn schema and data, this is now easily achievable.
