### ISSUE TITLE
Uninstalling Brain Chip does not revert memory and hand size increase.

### ISSUE THREAD

**Issue by crobinson-finmason** [mtgred/netrunner#3871]
In my most recent game, I used Emergent Creativity to install Brain Chip, but wished to undo that action. After checking with my opponent, I used /undo-click, which reverted the placement of the cards(EM in trash,BC installed), but the increase in memory and hand size was erroneously still active.

**Comment by Kubik161** [comment]
@NoahTheDuke I have tested this and there is no problem with undo-click and Brain Chip. This issue should be closed, thanks :)
