### ISSUE TITLE
Request: Trash stolen agendas

### ISSUE THREAD

**Issue by EnderAtreides** [mtgred/netrunner#3877]
Currently we have no way of manually performing Hired Help. Would it be possible to implement trashing scored/stolen agendas manually? Either dragging to Archives or a command would work, whichever is easier.

**Comment by NoahTheDuke** [comment]
I thought you could drag scored agendas to your hand. Can you not? (I'm not at my dev computer or I'd check right now.)

**Comment by EnderAtreides** [comment]
Oh, my bad. Looks like I needed the Corp to trash a stolen agenda, not the runner.

**Comment by NoahTheDuke** [comment]
Ah perfect! Thanks for letting us know!
