### ISSUE TITLE
Request: Command to install ice on non-outermost position

### ISSUE THREAD

**Issue by EnderAtreides** [mtgred/netrunner#3879]
This is to manually resolve Timely Public Release.

Currently, to the only way I can think of resolving it manually is to move all ICE outside the position back to HQ, install it, then install the ice outside it, then rez all ICE that was rezzed before. If it's during a run, you have to re-run, too.

Presumably a command would be easier than fully implementing all the card functionality, and the code could be reused when implementing it.

**Comment by NoahTheDuke** [comment]
That’s a good idea. Currently, the ice positioning logic is super janky, so either will require a rework, but this card is as good a reason as any to do it.

Thanks!

**Comment by justinliew** [comment]
I might try to take a look at this.

**Comment by NoahTheDuke** [comment]
The current use of `front` in `move` (core/cards.clj:149,170) is where you'd want to put the "insert into a vector" logic. The biggest issue I found when I was looking at it last night was how to communicate where you want to put it. Should it be a chat command? Should it be part of the drag-and-drop functionality of ice? Should it be placed normally and then you click a button to move it one place at a time?

@EnderAtreides, what would be good UX for you? How would you like it to function?

**Comment by justinliew** [comment]
Thanks for the tips, Noah.

**Comment by EnderAtreides** [comment]
Something like:
* "/install-ice [##]"
* Brings up a prompt to select a card in HQ/Archives (with a Cancel button).
* Once selected, asks which server to install the ICE in (same as usual).
* Once chosen, installs the ICE in [##] position, pushing all ICE in that position or beyond it out one position.
* If the runner is approaching/encountering one of those outer ice, they continue to encounter it (i.e. they are pushed out to match their currently approached/encountered ICE).

A minor improvement, instead of a [##] parameter, there is a prompt to choose a number out of the number of ICE positions in the chosen server. (N+1 possible positions, if N is how many ICE are there.) In the prompt it should specify that position 1 is innermost (or outermost if that's preferred, but I think it's easier to count inner -> outer than vice versa).

**Comment by justinliew** [comment]
This is great - I'll start from this design and see how it works out.

**Comment by NoahTheDuke** [comment]
After @presheaf wrote #3909, I realized it could be easily ported to this command, so here we are!

**Comment by justinliew** [comment]
Cool! I've been too busy to touch this so glad it got done with other functionality.
