### ISSUE TITLE
Medium on progenitor gains virus token after purge

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#388]
If you have medium on progenitor with 0 virus tokens and the corp purges then medium gains one virus token.

**Comment by JoelCFC25** [comment]
Yep, this is a Progenitor problem. It's just adding back 1 virus counter after a purge regardless of how many the hosted program had before.

**Comment by nealterrell** [comment]
This will need some more event support, since `:purge` fires once the purge is complete and Progenitor can't know at that point how many tokens were on its hosted card before the purge.
