### ISSUE TITLE
Surveillance Sweep - triggers on corp side (hard-hitting news)

### ISSUE THREAD

**Issue by theoneakaneo** [mtgred/netrunner#3880]
apparently surveillance sweep also triggers incorrectly on the corp's turn when playing a hard-hitting news for instance

**Comment by NoahTheDuke** [comment]
I can't reproduce this at all. Do any of you have a reproducible set of steps I can take to make it happen?

**Comment by bcsj** [comment]
I remember looking at the for Surveillance Sweep and thinking "how could this possibly have gone wrong?" after commenting here. I'm guessing some kind of out of sequence actions must have happened, but I don't remember. On a related note, have you considered adding an option of "saving replays"? That could potentially help understand singular occurences like this.

**Comment by NoahTheDuke** [comment]
Yeah, we've talked about it, but sadly that's a big hassle given how the engine is written. If you come across it again, please post a screen shot or copy the log.
