### ISSUE TITLE
Divide and Conquer and Edward Kim

### ISSUE THREAD

**Issue by gmuench** [mtgred/netrunner#3889]
Divide And Conquer reads

"Make a run on Archives. If successful, after accessing Archives, access 1 card from HQ, then access the top card from R&D."

As Edward Kim, after you access previously trashed operations in archives, Kim should not be able to trash operations with his identity ability from RND or HQ that turn. The current Jnet behavior ignores this. Thanks!

**Comment by NoahTheDuke** [comment]
Can you explain it further? I'm not quite sure what's happening based on your description.

**Comment by gmuench** [comment]
https://images-cdn.fantasyflightgames.com/filer_public/1f/a4/1fa4d5c6-3f6b-47b6-94e7-ba54c3dd70d5/adn_faq_42_hires.pdf

"28 Edward Kim
• If the first operation Edward Kim accesses is in Archives, then he
cannot trash another operation with his ability that turn."

Steps to recreate:
1. as corp have a hedge fund and IPO in HQ.
2. as corp play a hedge fund to add it to archives.
--- End of corp turn ---
3. As Edward Kim runner, play a divide and conquer and make the run successful.
3.a Access all of archives including the Hedge Fund operation.
3.b Access HQ and access the IPO.
4. Current JNET behavior has Edward trashing the IPO when it technically should not have this behavior.

**Comment by NoahTheDuke** [comment]
Ah, okay! Cool, thanks for the explanation.
