### ISSUE TITLE
Kate's ability fires even if you can't install the card...

### ISSUE THREAD

**Issue by DominicKexel** [mtgred/netrunner#389]
Example:

Have 1 Credit, click on a programm in your hand that cost 3 credits to install it.

Kate's ability fires, but you didn't install the card (since you didn't have enough credits).

When you then try to play another hardware/programm, e.g. Clone Chip which costs 1, you don't get the discount.

**Comment by JoelCFC25** [comment]
Could we just steal from Street Peddler and add a condition to the `req` that the cost of the targeted item be no larger than credits + 1?   I.e., `(<= (:cost %) (inc (:credit runner)))`

**Comment by mtgred** [comment]
There would be an issue if another cost modifier like Modded or Street Peddler is used in combination with Kate.

Ideally the `can-pay?` function should take the `install-cost-bonus` into account. That way the `:req` in Kate, Street Peddler, Clone Chip or Self-Modyfing could check the discounted cost properly.

**Comment by nealterrell** [comment]
I know that system best, I'll take a look. `:pre-install-cost` will need an argument to indicate if it's being called as part of the actual install or if it's "just to check if I can afford this."
