### ISSUE TITLE
Deck incorrectly flagged as illegal for 1.1.1.1 format

### ISSUE THREAD

**Issue by x3N1GM4x** [mtgred/netrunner#3891]
When loading the following Skorpios deck into the Deck Builder:
```
1 False Lead
1 Government Takeover
1 Hostile Takeover
2 Private Security Force
3 Project Atlas
1 Aggressive Secretary
2 False Flag
3 GRNDL Refinery
2 Snare!
3 Beanstalk Royalties
1 Biotic Labor
3 Consulting Visit
3 Hedge Fund
1 High-Profile Target
3 Housekeeping
2 Punitive Counterstrike
2 Ice Wall
2 Wall of Static
3 Enigma
1 Tollbooth
1 Archer
2 Caduceus
1 Mlinzi
```

The tooltip for the "Tournament Legal" text shown next to the ID image stets the deck is not 1.1.1.1 format legal, even though I believe it is. Furthermore, the additional tooltip on that specific line of popup states:

![image](https://user-images.githubusercontent.com/10621139/46895972-be5a9080-ce72-11e8-9f77-04fd3917f884.png)
> Only one Datapack permitted - check: Government Takeover, Housekeeping

Not only are these two cards from the same product (Order & Chaos), it's not even a Datapack, so there's definitely something strange going on.

I took a look at [the relevant code](https://github.com/mtgred/netrunner/blob/79e0d33ace4f3c1243dc4beee150f10d67040ea9/src/cljc/jinteki/decks.cljc#L288), but it's been a while and I couldn't see what was at fault (or what I was missing), so I thought I should log an issue instead.

**Comment by presheaf** [comment]
I thought this would be because the ID Skorpios is from Terminal Directive and therefore not allowed, but even changing Skorpios to Gagarin and adding in an agenda didn't fix this, so that's not the issue.

**Comment by NoahTheDuke** [comment]
I'm closing this as when we roll out the new deck checker along Nisei's new System Core 2019 and MWL we'll be dropping support for 1.1.1.1.
