### ISSUE TITLE
Daruma: cannot be trashed to swap cards

### ISSUE THREAD

**Issue by m00nc** [mtgred/netrunner#3893]
Daruma is supposed to be possible to be trashed when a runner aproaches the server, but you can only rez and derez it. trashing it manually didnt help

**Comment by ChooJeremy** [comment]
I can't reproduce this, this works for me.

**Comment by Kubik161** [comment]
@NoahTheDuke Couldn't reproduce, Daruma seems to be working fine. This issue should be closed :)
