### ISSUE TITLE
Paper Tripping freezes the game

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#3896]
Playing Paper Tripping causes the game to become unresponsive. On the first occasion this happened to me, Paper Tripping remained in the "temporary zone" window and the game would not respond. The play cost had been paid, the tags had been removed, but the event did not trash itself and the game state would not proceed: I was unable to drag it from the "temporary zone" to my heap, and I wasn't able to play cards or use basic actions either. See the attached screenshot for details. [tripping](https://user-images.githubusercontent.com/44246400/47119277-2d185f00-d262-11e8-8825-63f65c46e0cc.jpg)
I used /undo-click and the card moved itself back to my grip, but trying to play it again would do nothing at all. I tried to resolve its effect manually by manipulating my tags and credit total through the +/- arrows on the display, but they were unresponsive. I then used commands to resolve the effect (/credit and /tags) , but again I could not trash Paper Tripping from my grip by dragging it to the heap, so I had to use the /trash #x command to do it. However, even after trashing it, the game was frozen, and I was unable to play cards or perform basic actions. 

I then tried to reproduce the problem, by setting up a test game against my other jinteki.net account. On this occasion, clicking on Paper Tripping to play it did nothing: the event did not resolve, and the game became unresponsive. I was unable to perform basic actions or play cards. 

To test whether this is might be just a Chrome problem, I did another test game using Firefox. Just like in the second game, playing Paper Tripping froze the game. However, on this occasion, while I was writing this bug report, about 15' after I played Paper Tripping, it actually resolved, and then stayed in the "temporary zone" just like on the first occasion I encountered the bug. On this occasion, however, the interface is not entirely unresponsive: I am able to click the buttons for basic actions, and when I click "make a run" it even prompts me to pick a server. However, the game state never proceeds and the run doesn't initiate. Paper Tripping is still stuck in the temporary zone.

**Comment by jwarwick** [comment]
Thanks for the detailed bug report. I'll take a look.

**Comment by jwarwick** [comment]
Screenshot FTW. Bug was actually in Obelus, but Paper Tripping triggered it.

**Comment by manveruppd** [comment]
Huh! I actually installed obelus in the two tests I did after it happened
in my live game, only so I would save a few fractions of a second every
turn from not having to discard. Didn't occur to me that I would be
contaminating the test :D
