### ISSUE TITLE
Magnum Opus card implementations

### ISSUE THREAD

**Issue by jwarwick** [mtgred/netrunner#3899]
Checked off means that the card is merged into master.
Place a link to the pull request next to the card when it is pushed.
If you wish to claim a card, make a comment on this issue or put your name next to the card.

- [x] Labor Rights (#3904)
- [x] Crowdfunding (#3903)
- [x] Slot Machine (#3906)
- [x] Border Control (#3905)
- [x] Timely Public Release (#3909)
- [x] Embolus (#3908)
- [x] Watch the World Burn (#3911)
- [x] Hired Help (#3914)

**Comment by NoahTheDuke** [comment]
I'll take Border Control! This'll be a good reason to actually work on new cards.

**Comment by jwarwick** [comment]
All merged to master.
