### ISSUE TITLE
Feature request: Stimhack Online Cache Refresh 8 Legality checker

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#3913]
I was wondering if a legality checker could be implemented on Jnet for the upcoming SOCR8 tournament.

This post on the stimhack forum summarizes the format rules:

https://forum.stimhack.com/t/stimhack-online-cache-refresh-8-starts-november-4th/10194?u=sanjay

I will reproduce them here too:

**3x** Revised Core Set (Core Set 2.0)
1 Big Box **or Terminal Directive** (this may be different for Runner and Corp)
1 Copy of Reign & Reverie
All 6 Packs of the Kitara Cycle
**Magnum Opus Champion Cards
Magnum Opus Orgcrime Cards
Custom MWL (see forum post)**

Changes from SOCR7 in bold.

Sorry for asking so last minute!

**Comment by NoahTheDuke** [comment]
Thanks for letting us know! I'll see about getting this updated in time for week 2 to start.

**Comment by NoahTheDuke** [comment]
Closed with #3940
