### ISSUE TITLE
Keros McIntyre does not give credits for Leave No Trace, because Leave No Trace has the Corp derez cards

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#3919]
Leave No Trace says "When the run ends, derez all ice that was rezzed during this run." So that should be the Runner derezzes the cards, similar to Rubicon Switch or Emergency Shutdown, right?  FAQ for Keros says that in this case the Runner should gain credits.  It looks like Leave No Trace has the Corp derez the cards, and so no credits are gained by Keros.  Maybe I'm misunderstanding the rules, but figured it might be worth looking into.

**Comment by NoahTheDuke** [comment]
Good to know! Thanks for the report

**Comment by NoahTheDuke** [comment]
I just tried it out and can't reproduce this. Have you seen it happen?

**Comment by dnddmdb** [comment]
It happened twice to me.  I can try again and see if I get the same result.  But are you saying you double-checked and it might be fixed now?  That is, if it was broken to begin with?

**Comment by NoahTheDuke** [comment]
Yeah, I couldn't seem to make it _not_ fire. Every time I tried, Keros would pay out after Leave No Trace ended. Do you have a screenshot or the game log? That'd help a lot.
