### ISSUE TITLE
Slot Machine reveals card advanced by third subroutine to runner

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#3923]
![jnet reveal advanced card runner](https://user-images.githubusercontent.com/13881796/47985858-e97f7b00-e0d2-11e8-9bf5-d70f5582359c.png)
![jnet reveal advanced card](https://user-images.githubusercontent.com/13881796/47985723-7c6be580-e0d2-11e8-8f2c-5f5690a11f3c.png)
The face down card that you place 3 advancement counters on from the third subroutine is revealed to the runner.

**Comment by NoahTheDuke** [comment]
Thank you!
