### ISSUE TITLE
sensie + DBS makes you put only 1 card back, should be 2

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#3931]
TheBytemaster is ending their turn 3 with 4 and **3 cards in HQ**.

(runner turn; no interaction with corp's hand at all)

TheBytemaster rezzes Sensie Actors Union.
TheBytemaster uses Sensie Actors Union to draw 3 cards.
TheBytemaster uses Daily Business Show to draw additional cards.
TheBytemaster uses Daily Business Show to add 1 card to the bottom of R&D.
TheBytemaster started their turn 4 with 3 and **6 cards in HQ**.

This was all before the mandatory draw (had 7 cards in HQ, after mando during click 1, when we realized something was off), so it should have been 5, not 6, above.

Something related appears to already have been filed in #1508 but this is more than just failing to log one move-bottom.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
![image](https://user-images.githubusercontent.com/1409906/58125215-5c37ea00-7c10-11e9-9ce8-ed19f6e1c6ee.png)

The prompts for Sensie and DBS look pretty much alike. It could be that you pressed done on the second prompt and thereby skipped the DBS action.

**Comment by NoahTheDuke** [comment]
This brings up a good point, tho. We should be showing the card name that generates a given prompt like this.
