### ISSUE TITLE
Kyuban disappears

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3932]
Runner is Jesminder, runs R&D which has two ice, Data Raven on the outside. Runner installs Kyuban with SMC during a run, Kyuban disappears from the board - though MU is used up - it doesn't appear in the heap.

**Comment by Tamijo-Netrunner** [comment]
I have a similar event. Enclosing a screenshot and log in case it helps.

![image](https://user-images.githubusercontent.com/39098450/49479220-20ec5f00-f81a-11e8-80d6-d9b1ca158f72.png)

Hyperbolic_Mess started their turn 11 with 23  and 4 cards in their Grip.
Hyperbolic_Mess spends  to draw a card.
Hyperbolic_Mess spends  to draw a card.
Hyperbolic_Mess spends  and 3  to install Cyberdelia.
Hyperbolic_Mess spends  to make a run on R&D.
Tamijo has no further action.
Hyperbolic_Mess continues the run.
Tamijo takes 1 bad publicity from Bulwark.
Tamijo spends 10  to rez Bulwark.
Hyperbolic_Mess uses Rielle "Kit" Peddler: Transhuman to make Bulwark gain Code Gate until the end of the run.
Hyperbolic_Mess spends 4  to increase the strength of Engolo to 10.
Hyperbolic_Mess spends 1  to use Engolo to break 1 Code Gate subroutine.
Hyperbolic_Mess spends 1  to use Engolo to break 1 Code Gate subroutine.
Hyperbolic_Mess spends 1  to use Engolo to break 1 Code Gate subroutine.
Tamijo has no further action.
Hyperbolic_Mess uses Clone Chip to install Kyuban.
Hyperbolic_Mess installs Kyuban on Bulwark protecting R&D at position 1.
Hyperbolic_Mess uses Cyberdelia to gain 1  for breaking all subroutines on a piece of ice.
Hyperbolic_Mess uses Kyuban to gain 2 credits.
Hyperbolic_Mess continues the run.
Tamijo has no further action.
Hyperbolic_Mess spends 2  to increase the strength of Engolo to 6.
Hyperbolic_Mess spends 1  to use Engolo to break 1 Code Gate subroutine.
Hyperbolic_Mess spends 1  to use Engolo to break 1 Code Gate subroutine.
Hyperbolic_Mess continues the run.
Tamijo has no further action.
Hyperbolic_Mess accesses an unseen card from R&D.
Hyperbolic_Mess accesses an unseen card from R&D.
Hyperbolic_Mess accesses an unseen card from R&D.
Hyperbolic_Mess
Hyperbolic_Mess
why did kyuban die?

**Comment by lostgeek** [comment]
Are these maybe related? #3832
