### ISSUE TITLE
Scarcity of Resources and /undo-click

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#3937]
When the runner uses the command "/undo-click" after installing a resource when Scarcity of Resources is active, the game does not refund the Runner the total credits spent (ie. Daily Casts, 3+2c).

Furthermore, the next install that same turn, regardless of whether it is a hardware, resource or program, costs the runner an additional 2c.

**Comment by NoahTheDuke** [comment]
The first part is a bug: you should be refunded your total credits spent. The second sounds correct: If you play a resource and then undo the click, you should have undone the "first time you installed a resource", and so should trigger Scarcity on the subsequent "first install".

**Comment by NoahTheDuke** [comment]
Oh I misunderstood, any install costs 2c additional. Yes, that's a bug. Thanks, I'll look into it.

**Comment by NoahTheDuke** [comment]
Does this still happen?

**Comment by xdfubar** [comment]
Just tested. Maxx vs Mti
=================================================================
Scarcity played turn 1.
Maxx installs TTW. Pays 4c
Uses /undo-click feature. Credits get refunding properly.
Maxx attempts to reinstall TTW. Has to click through 2 x "Cannot pay" prompt before being able to install TTW.
Maxx uses undoclick again and installs Aumukua for 3c as expected.
Maxx uses undoclick, installs daily casts for 5c as expected.
=================================================================
Seems fixed for the most part, but some unanticipated prompts coming up (cannot pay).

**Comment by juliendeville** [comment]
Steps:
Current: Scarcity
The runner have 5 credits.
Runner plays The turning Wheel and now have 1 credit
runner runs /undo-click
Runner plays The turning Wheel again, gets the following prompt "Unable to pay"
Runner plays The turning Wheel again, it works!
![image](https://user-images.githubusercontent.com/2876861/64086955-ee1fba80-cd08-11e9-85e5-e9672fb297d1.png)

**Comment by juliendeville** [comment]
:slowpoke:

**Comment by xdfubar** [comment]
nah you got the screenshot. plus it's better to have more than 1 person anyway. ty for helping me retest.

**Comment by NoahTheDuke** [comment]
This is great, thank you! I’ll dive in this week, get it sorted
