### ISSUE TITLE
Constellation Protocol start of turn trigger

### ISSUE THREAD

**Issue by mcgreenhalgh** [mtgred/netrunner#3941]
I can't believe you've missed a massively important error like this.

When someone (my opponent) has Constellation Protocol in play, the runner gets the message "Waiting for Corp to resolve corp-mandatory-draw triggers" which persists until you /close-prompt.

I expect this becomes your top priority!

**Comment by NoahTheDuke** [comment]
Sorry for the delay, here's a fix!
