### ISSUE TITLE
Disposable HQ is broken

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#3942]
I can see earlier issues (2797, 2161) about Disposable HQ, and that they have been closed - I'm not sure whether this is because the issue has been fixed or it's too hard to fix. Nonetheless, access to Disposable HQ results in multiple recurring HQ accesses and the only fix is to /close-prompt and /jack-out - so the issue is not fixed at the moment.

**Comment by NoahTheDuke** [comment]
Thanks, I’ll look into it.

**Comment by NoahTheDuke** [comment]
I tried to look into this with #3971, but couldn't reproduce. Does this still happen?

**Comment by tolaasin** [comment]
Haven't seen it again - i'll let you know if I do.
