### ISSUE TITLE
John Masanori Triggers with Paragon

### ISSUE THREAD

**Issue by dj88c** [mtgred/netrunner#3948]
I had John Masanori and Paragon installed. When I achieved a successful run, John Masanori triggered first before I was asked to use Paragon (thus looking at what card I *could* draw or put on the bottom of my deck). I imagine this is going to be a very prominent combo so might want to ask order.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look!

**Comment by NoahTheDuke** [comment]
Closed with #4005.
