### ISSUE TITLE
Turning Wheel adds accesses to both halves of Divide and Conquer

### ISSUE THREAD

**Issue by gannicottb** [mtgred/netrunner#3956]
Per the [UFAQ](https://netrunnerdb.com/en/card/22002):

> What happens if the Runner uses The Turning Wheel during a run made with Divide and Conquer?
> 
> Because Runner must choose whether they wish to access an additional card from either R&D or HQ each time they use The Turning Wheel, each use of The Turning Wheel will only affect one of the accesses from Divide and Conquer.

It looks like the extra accesses from The Turning Wheel apply to both of the HQ and R&D accesses made during the resolution of Divide and Conquer.

**Comment by NoahTheDuke** [comment]
Thanks for writing this up. I programmed Divide and Conquer before that ruling came out and never got around to fixing it. I’ll do that now.
