### ISSUE TITLE
Alt-Art Nero is showing up instead of Prisec

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#3958]
Just started a game with Argus in Chrome v70 and Windows 10. My account has alt arts enabled, I've been trying to workaround the alt art issue on  j-net by setting all cards to champion art, then all cards to alt-art and submitting the settings menu. 

Prisec is showing up in that deck as the alt-art Nero. Card behaves exactly as a prisec including prompt to pay 2c for meat and a tag. Nero shows up in the deck builder as well. Issue persists in Deck Builder and when I start an empty new game with the deck. Screenshots attached. 

It appears this is related to Ticket #3868 

![image](https://user-images.githubusercontent.com/45369203/49035178-019e6380-f182-11e8-9eae-43b592d1aa69.png)
![image](https://user-images.githubusercontent.com/45369203/49035184-05ca8100-f182-11e8-802a-c4b82a7f5b49.png)
![image](https://user-images.githubusercontent.com/45369203/49035187-095e0800-f182-11e8-950b-69e9aecf2250.png)
![image](https://user-images.githubusercontent.com/45369203/49035203-1d096e80-f182-11e8-84c9-15a4fb2a733e.png)

**Comment by ZomBagus** [comment]
I had the same issue today where a Nero alt showed up on a mandatory draw as corp. Also when I checked my deck the Prisec shows as a Nero image.

 
![nero severn draw bug](https://user-images.githubusercontent.com/13881796/52171084-3f090980-274e-11e9-9080-b07808868fd9.png)

**Comment by AndersRask** [comment]
This one should be pretty easy to fix i guess! Saw the Prisec/Nero today so still having this issue

**Comment by NoahTheDuke** [comment]
Is this still happening?

**Comment by rongydoge** [comment]
Alt arts haven't worked on J-net for... more than 6 months? Either way it's a non-issue because alt arts aren't implemented.
