### ISSUE TITLE
Missing Popup Window alt-art

### ISSUE THREAD

**Issue by allenmanning** [mtgred/netrunner#3960]
I think there was an alt-art of PopUp window and now I can't see it anymore.  Was it removed?  Is there a doc where I can see the alt art change history?

Thank you for an awesome project.

**Comment by Saintis** [comment]
Related to #3958. The change to internal card format has broken alt-arts sadly.

**Comment by jwarwick** [comment]
Alt arts have been fixed. Closing this issue.
