### ISSUE TITLE
Core experience legal flag is causing layout issues in Deck Builder list

### ISSUE THREAD

**Issue by yads** [mtgred/netrunner#3963]
I manually edited the HTML to shorten the legality tag and it fixed the layout. You can see it here

![image](https://user-images.githubusercontent.com/527463/49614322-2efbc600-f967-11e8-9157-abe2bf5fa5ab.png)

**Comment by NoahTheDuke** [comment]
Ah heck, okay, thanks

**Comment by jwarwick** [comment]
This appears to be fixed now. Closing.
