### ISSUE TITLE
Alliance cards not using influence properly

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [mtgred/netrunner#3965]
Alliance cards are counting themselves to the "Minimum of six non-alliance cards". Screenshots:

![image](https://user-images.githubusercontent.com/39098450/49662427-b3bc1200-fa43-11e8-827c-7f31abc0ce67.png)

![image](https://user-images.githubusercontent.com/39098450/49662450-c1719780-fa43-11e8-89c2-f5fdacf62d8e.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report, I'll take a look at it!
