### ISSUE TITLE
Disposable HQ hangs game

### ISSUE THREAD

**Issue by allanb2** [mtgred/netrunner#3971]
Last week played a Casual Legal game with Weyland Titan Transnational against Whizzard.

Had a remote with Agenda and Disposable HQ in it. Runner accessed Agenda first, stole it, then accessed Disposable HQ. Corp was able to select & move cards to R&D, then clicked Done.

Nothing more happened on Corp side and nothing more happened on Runner side. Never switched control back to the Runner after Corp selected Done.

This seems to be a new and different bug behaviour than previous Bug reports for Disposable HQ.

**Comment by NoahTheDuke** [comment]
I can't reproduce this at all. I've tried having enough money to trash, not enough to trash, accessing the agenda first, accessing disposable HQ first, running last click, accessing the agenda first and the clicking Done, accessing disposable HQ first and then clicking Done.

Do you have a log or screenshot?
