### ISSUE TITLE
Game doesn't allow tying (from Medtech + Employee Strike)

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#3974]
The runner played Strike while we both were on 3 agenda point. They stole the next agenda taking them to 6 points. After I score the next agenda Strike was trash so my Medtech ID took effect and I "won" according to jinteki.net. Since both the runner and the corp were on 6 point at the same time this should have been a tie.

**Comment by NBKelly** [comment]
Closed as completed via #5638
