### ISSUE TITLE
Smoke (Stealth Creds) + Bad Pub

### ISSUE THREAD

**Issue by 5N00P1** [mtgred/netrunner#3978]
When using Stealth in a bad pub matchup where you don't use all your Stealth + Bad Pub Creds, you are coming out of the run with to many creds, as it's not calculated correctly.

Situation:
2 Bad Pub
Net Mercure
5 Creds

Example of the Issue when Smoke is running R&D:
7 Creds (2 for run)
Getting a cred from her ID
8 Creds (2 for run)
using a cred to pump a breaker & load Net Mercure
7 Creds (1 for run)
Access R&D, Run ends
at the end of the Run, Smoke has 6 Creds, although she should have 5.

I hope this is a good explanation of the issue, it's easily reproducible.

**Comment by Saintis** [comment]
One of our oldest issues (see #454) that sadly requires a major rework of how (stealth) credits are handled to fix.

**Comment by NoahTheDuke** [comment]
Gonna close as it's a duplicate.
