### ISSUE TITLE
Testing icebreaker auto-pumping

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#399]
I would appreciate the help of other developers in testing my auto-pumping code for icebreakers. 

A summary is here: #259. In general, any icebreakers that can boost strength have received some trickery to enable a "Match strength with ____" button when encountering an ice during a run. The button shows how much money the boost will cost, and then applies the necessary pump commands.

I could use some help testing this. I have done a good amount of testing myself, but I'm sure there are issues I haven't considered. For anyone with some free time, please clone my branch https://github.com/nealterrell/netrunner/tree/auto-pump and give it a shot. There are a number of other changes wrapped up in the branch, including a split of cards.clj into multiple files (necessary for technical reasons), and a UI change to show costs of abilities when clicking a card. 

THANKS :D.

**Comment by DominicKexel** [comment]
Sure, I'll try to take a look this evening.
