### ISSUE TITLE
"If successful" abilities shouldn't trigger on server the run couldn't be initiated on

### ISSUE THREAD

**Issue by olahesoo** [mtgred/netrunner#3997]
According to NISEI Comprehensive Rules Document section 6.7.3.a:

> If an effect that initiates a run specifies that that run must be made against a
specific server or servers, any “If successful” abilities associated with that effect are
tied to that server or servers. If the attacked server has changed since the run was
initiated, and no longer is a server that could have been chosen for this run, the “If
successful” abilities do not resolve.

Current behavior:
When runner initiates a run with Hot Pursuit and gets redirected from HQ (with Mind Game), if the run is successful the runner still gets 9 credits and a tag.

Expected behavior:
If the run is successful on a server other than HQ then effects from Hot Pursuit do not trigger.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Fixed by #5500?
