### ISSUE TITLE
Password game not working

### ISSUE THREAD

**Issue by JeffSkyrunner** [mtgred/netrunner#3998]
Hi everybody.

I'm trying to create a password protected game to play with myself (... ok, that's sound weird, but you know what I mean) but even if I am 100% sure of the password I've set, I cannot log in the game with the second browser, receiving the error "Invalid password"

**Comment by presheaf** [comment]
I occasionally do this to test issues, and it works just fine for me. The password I use is just "test". Maybe you're using a more complicated password and some special character in it is stored wrong or something? It's probably best not to share your password on here, but if you could test 1) that a simple password like 'test' works for you, 2) that whatever password you usually use does not, and if so also 3) what characters in your usual password are causing trouble, that would be great. Also, are you using 2 different accounts or the same?

**Comment by JeffSkyrunner** [comment]
Hi!
Thanks for the answer :)

I am totally sure about the password: it was something very easy and, to be more sure, I also pasted it on notepad.

I "workarounded" it by creating two different accounts, since some guys suggested it as a solution...

**Comment by presheaf** [comment]
I guess then the issue seems to be that you can't be in a game with the same account twice, right?

**Comment by JeffSkyrunner** [comment]
Yes, that is the issue.

Somewhere I read you could use the same account twice, but, at this point, I may have misread...
