### ISSUE TITLE
Suggestion: Cards names in chat

### ISSUE THREAD

**Issue by guirto** [mtgred/netrunner#4]
First of all, congrats on a great job. Can't wait to see it finished. If it is something I can do, I will be glad to help. I'm a web developer, and can help on javascript, jquery, html and mongodb.

I want to make a suggestion. What if card names in chat offers a card view when hovering? Just like when you hover an actual card.

Best regards.
Víctor.

**Comment by DominicKexel** [comment]
I'm trying to implement this, but I have no knowledge about om/react etc. If someone want's to help me, I described my problem here: #328

**Comment by DominicKexel** [comment]
I'm making progress. 

You can take a look here: https://i.imgur.com/HWxlWG7.gif
or see my branch here: https://github.com/DominicKexel/netrunner/tree/cards

Currently I pass a string like `[Paige Piper|08004]` to the client, so the client knows what URL to display. 

I would like the players to be able to also simply type the card name, and the preview should automatically work, as this would also allow me to let the server side mostly unchanged.

I was thinking of fetching all cards (just `:title` and `:code`) once from the database (maybe store it locally?) and then look up if I find a card title in the message once it gets displayed, and attach the event handler with the correct card code.

Thoughts?

**Comment by mtgred** [comment]
All the cards data are already fetched on init and kept in memory on the client side. You can access the cards array with `(:cards @app-state)`.

Based on the card name you can look up the card code to display the card image. Have a look at `cardbrowser.cljs` as an example.

**Comment by DominicKexel** [comment]
Thanks, good to know.
