### ISSUE TITLE
Hernando Cortez causes Blue Sun to gain too much money

### ISSUE THREAD

**Issue by chaosof99** [mtgred/netrunner#4000]
I observed this issue in one of Self-Modifying Code's Videos
https://www.youtube.com/watch?v=ky6I9hs0ysM

At about 55:02 the Corp uses Blue Sun to return a Chiyashi that has Oversight AI on it to its hand. However, for some reason automatically the Hernando Cortez controlled by the runner "increases the rez cost by 3 credits", even though Chiyashi was not being rezzed at that moment. What's more Blue Sun gains 15 credits instead of the 12 it should have received.

![hernandosun](https://user-images.githubusercontent.com/44696340/51269552-0d104d00-19c3-11e9-9eb4-81502fce5ff6.PNG)

Seems like Hernando Cortez is reacting to more in-game events than he should. I am also not sure whether the "increasing rez cost" implementation is the best way, though probably the only usable version of such an effect. Also not sure whether Oversight AI is a factor but probably not.

Possibly this affects other cards that deal with rez cost as well, e.g. Brute-Force-Hack.

**Comment by NoahTheDuke** [comment]
Good report! I’ll take a look.
