### ISSUE TITLE
Enhancement Suggestion: command completion

### ISSUE THREAD

**Issue by truefalsename** [mtgred/netrunner#4001]
Hi,

first of all thank you again for the work that you continue to put into Jnet! 

Would it be possible to enhance the experience by having some sort of auto completion for the commands in the chat? It would be great if we could hit /, a few letters and use tab to have the full command pop out.

**Comment by NoahTheDuke** [comment]
That’s an interesting idea! I’ll think on it, maybe figure out a solid way to make it work. Thanks so much.

**Comment by francescopellegrini** [comment]
Closed by #5806?
