### ISSUE TITLE
The dialog where you select deck when starting a game does not sort newest first

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4002]
The dialog where you select deck when starting a game used to sort newest deck first
Now the sort order is... well i'm actually not sure. It's not by any date and not alphabetic either.
It is rather annoying, and something that seems to have been introduced recently!

thx
Anders 'Zombie' Rask

**Comment by NoahTheDuke** [comment]
It was changed to first sort by all decks legal for the chosen format and then by most recently updated. Does it not do that anymore? Do you have a screenshot of the incorrect behavior?

**Comment by AndersRask** [comment]
Sure
![image](https://user-images.githubusercontent.com/1651150/51498080-9493fc80-1dc5-11e9-9f5a-b47c0c4d3aca.png)
It lists some of the newer deck on the top, then older and older, and then the most recent ones and older. If there is a deeper mening i cant see it :)
[My browser info](https://www.whatsmybrowser.org/b/H4FEDRG)

**Comment by NoahTheDuke** [comment]
That’s a great screenshot. Thanks for sharing! I’ll take a look when I get back to my computer and see if I can fix this.
