### ISSUE TITLE
New version of The Turning Wheel does not write where it is used in log

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4004]
The new TTW where you select HQ or RnD writes the following in log:
Zombie uses The Turning Wheel to access 1 additional card from .
I guess it should have said HQ or RnD?
I also had issues where it did not show anything in log when runner used it against me, but can't repro at the moment.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I know where the bug is so hopefully I can get a fix in soon.
