### ISSUE TITLE
Guru Davinder bug

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4007]
When the corp fires a Wake Up Call and I choose trash in stead of 4 meat dmg, Guru Davider fires.
It should only fire if i choose 4 meat dmg

**Comment by AndersRask** [comment]
Well the above should do it: Corp plays WUC, runner choose trash instead of meat dmg. Guru Davider fires.

**Comment by presheaf** [comment]
I was unable to reproduce this. Do you remember what resource was targeted with WUC? I tested both with the Corp choosing Guru Davinder and Same Old Thing, and neither caused Guru Davinder to trigger.
