### ISSUE TITLE
Add the time spent per player to the game stats

### ISSUE THREAD

**Issue by McAvity** [mtgred/netrunner#4014]
Would be really nice to add the time spent per player to the game stats. I'm a new player, and I would like to improve my decision making time.

**Comment by NoahTheDuke** [comment]
Interesting idea! How would you propose we measure it?

**Comment by ZomBagus** [comment]
In turn time: Time between pressing start turn and end turn.
Inbetween turn time: Time between previous player pressing end turn and you pressing start turn.

**Comment by ZomBagus** [comment]
Hmm, so whenever waiting on a player keyboard action the timer is with them. 
Thinking about any exceptions: runner deciding to carry on after mti inner ice install is chat dependent but it was runner priority anyway. There are probably some exceptions if we monitor them. But want to keep it simple code so likely just record on "waiting" prompts. 
Is it useful enough to devote coding resource to this? 
Possibly just display a countup timer whenever you are waiting on a player action?

**Comment by NoahTheDuke** [comment]
This is definitely something I'm interested in doing way down the line, but right now we don't have a strict enough definition of "who is the active player?" to know at any given moment which player should be tracked.
