### ISSUE TITLE
Border control chat message shows "[credits]" instead of credit symbol

### ISSUE THREAD

**Issue by x3N1GM4x** [mtgred/netrunner#4017]
If the first sub on Border Control fires, a message like the following is shown:

> PlayerName uses Border Control to gain 2 [credits].

![image](https://user-images.githubusercontent.com/10621139/52213628-834bf500-2887-11e9-9cd5-bc6549b88fc1.png)

The text `[credits]` is shown rather than the credit symbol like on other cards.

Not 100% sure why and don't have a dev environment stood up right now, but could is be because `[credits]` in this line should be `[Credits]` like it is on other cards?

https://github.com/mtgred/netrunner/blob/f7f6d8fb6bd25ce622716c01ddb6d79e2d559a47/src/clj/game/cards/ice.clj#L479

**Comment by NoahTheDuke** [comment]
You're right on the money! In fact, #3996 has a fix for this, we just need to get it into prod.

Seeing as you're now reading the source, can you find where we do the transformation in netrunner/src/cljs/nr/gameboard.cljs? Sounds like we could do with adding lowercase versions or maybe checking everything against the lowercase version.

**Comment by x3N1GM4x** [comment]
Oh, unless it's here?

https://github.com/mtgred/netrunner/blob/e96b2b25a37cd1fba5e7869e70c9c4dcb4bb739d/src/cljs/nr/gameboard.cljs#L101-L119

**Comment by ouroboros8** [comment]
Thanks for the pointer btw, I was looking in completely the wrong place for this. Didn't clock that `cardbrowser` is the, uh, card browser, not the game board :sweat_smile:

**Comment by NoahTheDuke** [comment]
haha Yeah, the names aren't great! And nicely done, Ian, that's exactly it.
