### ISSUE TITLE
Press End Turn with too many cards in hand and then drag discard - hangs

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4019]
If you press end turn when your hand is over hand size and then drag excess cards into the bin, then nothing happens once you get down to hand size and you have to type /close-prompt to get the end turn prompt again.

After playing around with this to prove what was happening I realized that the interface has changed and you are meant to just click on cards to discard. Note if you do this after a drag discard you have to click enough cards to satisfy the original hand size discard requirement and not the hand size after drag discard.

**Comment by NoahTheDuke** [comment]
I'm sorry you didn't know about the change. Adding a changelog or some highlighting system so new/changed features are more discoverable is on my radar.

With the way prompts currently work, it's not possible to make it responsive to you manually dragging cards from your hand to your discard. As it is, there's not much we can do except for you to input `/close-prompt` when you find yourself in such a situation.

I'm gonna close this for now.
