### ISSUE TITLE
Leela + Turntable = Crash ?

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#403]
i experienced a crash when i stole an agenda with Gang Sign and 2 HQ Interface.
It was during my oppenent turns. He scores an agenda so Gang Sign triggers and give me access to three cards. i found an agenda and the game ask me to bounce an unrezzed card (Leela power), i select an upgrade in HQ and the game crash.
Turntable was on the table, so maybe the game crash when it triggers his effect ?

**Comment by JoelCFC25** [comment]
Turntable isn't implemented other than the +1 MU, so that can't be it.

**Comment by JoelCFC25** [comment]
Closing this for now. If it happens again and you can reproduce it, add a comment and we can reopen it.
