### ISSUE TITLE
Street Peddler dosen't let you install Event cards type

### ISSUE THREAD

**Issue by JamieRed** [mtgred/netrunner#4032]
It happened multiple times during my games today.

If "Street Peddler" host any Event and you try to install one of them, they do not appear in the selection window.

**Comment by Saintis** [comment]
I'm not sure what you are trying to do. The runner is not able to install events so I would take this as working-as-intended. This is also true for hostable events such as On the lam.

**Comment by JamieRed** [comment]
Yeah, my bad.
I misread the term "install" with "play", sorry for bothering you.

**Comment by Saintis** [comment]
No worries!
