### ISSUE TITLE
Update decks for new players

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#4037]
At the moment, new accounts have (outdated) revised core decks added to their deck collections automatically when they sign up. Would it be possible to update them to the new system core decks?

**Comment by NoahTheDuke** [comment]
Good catch! I can do that.

**Comment by y1fanwang** [comment]
Hi, I'm interested in helping this one.

I took a look at src/clj/web/auth.clj and it looks like we would need to modify the decklists for the user "__demo__". (But not sure how to access that account)

I would probably copy in these system core 2019 decks on nrdb:
[BlackCherries' System Core Decks](https://netrunnerdb.com/en/decklists/find?author=BlackCherries)

Thanks!
