### ISSUE TITLE
Wrestling breakers (Laamb / Engolo) additional subtype stays on ICE if breaker is trashed during encounter

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#4039]
If a wrestling breaker is trashed before passing the ICE, the new subtype stays on the ICE forever.

>Bob spends 2 to use Laamb to make Rototurret gain Barrier.
>Alice uses Rototurret to trash Laamb.
>Alice uses Rototurret to end the run.

![image](https://user-images.githubusercontent.com/1409906/52971654-90ed9880-33b8-11e9-8402-3722261a481e.png)

This will not go away even if passing the ICE later on.

**Comment by NoahTheDuke** [comment]
This will be taken care of by #4434
