### ISSUE TITLE
My decks won't load and I'm not sure why 

### ISSUE THREAD

**Issue by kevintame** [mtgred/netrunner#4043]
**Troubleshooting**
* I've tried clearing the cache. 
* Logging in with a different browser
* I tried creating a deck
* I waited for an hour for it to load

username: kevintame

<img width="777" alt="screen shot 2019-02-19 at 10 17 30 am" src="https://user-images.githubusercontent.com/1868988/53025945-f892fa80-342f-11e9-80ff-f246732596a5.png">

**Comment by jwarwick** [comment]
Can you check the browser console and see if there are any error messages?

**Comment by kevintame** [comment]
<img width="1259" alt="screen shot 2019-02-19 at 3 04 49 pm" src="https://user-images.githubusercontent.com/1868988/53043985-bed5ea00-3457-11e9-8f6a-f29f4e8d0db1.png">

**Comment by kevintame** [comment]
The decks have loaded but they are broken. When I click to edit I'm unable to select an ID from the picklist. 

<img width="1339" alt="screen shot 2019-02-19 at 3 00 46 pm" src="https://user-images.githubusercontent.com/1868988/53044030-df05a900-3457-11e9-9059-81c9cf3e527b.png">

<img width="1272" alt="screen shot 2019-02-19 at 3 01 15 pm" src="https://user-images.githubusercontent.com/1868988/53044035-e3ca5d00-3457-11e9-919a-7f79533669b7.png">

**Comment by jwarwick** [comment]
Hmmm. The `gameboard.js` error is from Jankteki. I can reproduce that, but my decks still load correctly. The 404 on the png file is likely from being unable to parse the deck card ID correctly, so a symptom, not the cause of the problem.

I was hoping to see an error parsing your deck list, but that doesn't seem to be the case.

Next thing to check would be to see what's happening in the browser `Network` tab and see if there's something strange with either the request to `decks` or in `Local Storage` and see if the card data is somehow corrupt.

If you have time, we could talk through some of that on slack.

**Comment by kevintame** [comment]
It looks like a custom chrome extension that I build and use for changing my background might have broken things. I disabled that and things are working fine. Sorry to take your time.

**Comment by NoahTheDuke** [comment]
I'm glad you found out the issue! Hopefully you can rewrite your extension to allow for changing the background still.
