### ISSUE TITLE
New discard functionality does not write discarded card in console for runner

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4047]
The new discard functionality is really cool! 

However it seems kind of unfair (to corp) that discarding this way does not write anything in console, like it would if you had discarded down normally.

I have seen this with at least one other card: Labor Right, where you are confused as a runner (and corp) what cards were actually discarded from top of deck.

It would be nice if all "discard" functionalities wrote what they did in console

**Comment by NoahTheDuke** [comment]
I believe #4038 has taken care of this! Just hasn’t made it onto the live server yet.

**Comment by NoahTheDuke** [comment]
How would you like Labor Rights to work?

**Comment by AndersRask** [comment]
Cool! I will test it when new release is published.

Labor Rights should show in console what cards were trashed

**Comment by NoahTheDuke** [comment]
Any other cards you can think of that need it? I can put them all into a patch

**Comment by AndersRask** [comment]
Not currently no unfortunately. Not knowing the source code and specific language used it is a stretch, but since it is a common effect (runner trash) if the code is made object oriented, this may be something that could be added one place :-D

**Comment by NoahTheDuke** [comment]
I wish! Sadly, the engine doesn’t quite work like that
