### ISSUE TITLE
Make SSL Endorsement autoresolvable

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4061]
On Slack, someone suggested adding autoresolve to SSL Endorsement. I thought this was a good idea, but am postponing doing it myself because I thought it might be a good issue to get started with for people interested in development. So here are some pointers on where to begin:

The ability which needs `:autoresolve` added is a line or so away from here: https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/agendas.clj#L1180

You also need to add an ability allowing the user to set autoresolve settings (examples can be found in e.g. CtM or Aeneas Informant), which needs to be usable even while SSL Endorsement is in the Runner's score area (see 15 Minutes).

**Comment by presheaf** [comment]
@NoahTheDuke I don't have permissions to do so myself, but could this be marked as a feature request and as a good starting issue?

**Comment by Dirjel** [comment]
You can only auto-resolve an SSL you score - you can't auto-resolve SSL's in the runner's score area.

**Comment by NoahTheDuke** [comment]
This is a bug, you mean?

**Comment by Dirjel** [comment]
yes, you should be able to auto-resolve SSL in the runner's score area as well.
