### ISSUE TITLE
Cleanup: add `:activated` effect  to separate 'when installed' effects from engine's 'when activated' effects

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4069]
See @nealterrell 's comment on #3077 - to the best of my knowledge, nothing was ever done about this, and I think #4057 is also caused by this issue. 

I think a reasonable proposal is to add a key `:activated` to the ability map of a card. This would be called by `card-init` after card events are registered, but just before the play effect is resolved. Any cards with 'constant effects' like Guillherme, The Black File, Zona Sul Shipping or Dadiana Chacon could enable these in `:activated`. Effectively, the game effects currently handled in `:effect` would be split into the effects happening when a card is played, and ones happening when a card "becomes active" (I think this term is made precise in the latest rules).

By symmetry, it also seems reasonable to split the `:leaves-play` effect into effects happening when a card is actually removed from the play area (i.e. trashed) and effects happening when a card becomes inactive, and reworking methods removing a card from play to first trigger the `:leaves-play` ability, then the hypothetical `:becomes-inactive` ability. I think cards can leave play in more ways than they can enter play, though, `move` and `trash` being the two I can think of off the top of my head, so before doing this probably have a think about which functions need to be altered and see if the change is feasible.

Once either of these have been done, of course, there is the cleanup work of going through all the cards existing and separating out what is currently done in `:effect` as a hack. I don't think there are that many difficult alterations needed. The ones I can think of in addition to the ones already named is that essentially all currents need to have `:effect` swapped for `:activated`, without any other major changes, and run events like Blackmail or Direct Access with a constant effect during their run should have that part moved as well.

**Comment by NBKelly** [comment]
Hi, I'm closing this issue as stale because this was superseded by our effects (static abilities, floating abilities, etc) system, so I believe it's no longer relevant to our current game engine.
