### ISSUE TITLE
Make events/operations stay in play until they finish resolving.

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4072]
Currently, events/operations go straight into discard. This causes a multitude of minor issues - for example, if you play Reboot, you can select the Reboot just played as one of the 5 cards to install facedown (the game will RFG it correctly, meaning you then only get 4 facedown installs). This should not be an issue because at the time of choosing, Reboot is still resolving, so should not be in the discard, but the game discards events prematurely. The correct resolution seems to be what Noah suggested on #4026 , i.e. waiting for events to completely resolve before moving them to discard. 

I don't think this fix is actually that hard, although given the multitude of hacks done in run events like Diana's Hunt or Compile to work around the existing system, it probably requires some cleanup work to not break anything. Also, if I could sneak in a small bonus feature request, maybe make the common "remove X from the game instead of trashing it" clause specifiable by having the game check the card definition for a `:rfg-after-resolving` flag.

**Comment by NoahTheDuke** [comment]
ayyy I did this! both parts in fact!
