### ISSUE TITLE
Data Loop on-encounter effect

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#4078]
Is it possible the corp could (also) activate the on-encounter effect for the runner?  This seems to be the only piece of ice where the runner has to do it, and so i'm often having to remind my opponents of this effect.

If there is a technical reason that prevents this, an option on Data Loop for a pre-written message asking the runner to use the effect would be really nice too.

**Comment by NoahTheDuke** [comment]
That’s a good idea! Thanks for letting us know
