### ISSUE TITLE
London library + activate hosted icebreaker problem

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#408]
After the latest patch i can no longer activate an icebreaker hosted on london library (tested with overmind and chameleon). I click the card but no menu is shown.

**Comment by JoelCFC25** [comment]
Yep, this is a big one--but it's not specific to London Library. Regardless of where an icebreaker gets hosted (hardware, other program, etc) its menu will not come up.

**Comment by nealterrell** [comment]
Hard to say. Preliminary tests show that the card-view for the hosted card is not being built in the gameboard UI, and the :hosted key of the host card is empty when building its UI. I can do more thorough testing in a few hours.

**Comment by nealterrell** [comment]
So I rolled back my repo prior to the commit in #391 and things seems to be working, so it must be a bad interaction. @DominicKexel, did you try using hosted icebreakers with the change in #391?

**Comment by nealterrell** [comment]
Fix submitted!
