### ISSUE TITLE
Complete Image does not properly interact with Chronos Protocol

### ISSUE THREAD

**Issue by eniteris** [mtgred/netrunner#4084]
Naming a card with Complete Image, then selecting that card with Chronos Protocol, does not make Complete Image fire again.

Although it seems to work fine if you don't use Chronos Protocol.

**Comment by NoahTheDuke** [comment]
Thank you!

**Comment by AndersRask** [comment]
+1 on that issue!

**Comment by nealterrell** [comment]
Workin' on it.
