### ISSUE TITLE
installing events face-down triggers the play effect

### ISSUE THREAD

**Issue by CarlHawley** [mtgred/netrunner#4085]
Just your friendly neighborhood noodle monster chiming in.

issue: installing events face-down triggers the play effect
replicate: install an event face-down via reboot or apex's ID.
effect: card acts as if it were played: initiating runs, triggering effects, etc.
conjecture: might trigger off of non-events with play effects as well, but I haven't tested it.

**Comment by NoahTheDuke** [comment]
Thank you!

**Comment by Saintis** [comment]
I will split this issue into two to make it easier to track.
