### ISSUE TITLE
Flip Switch Text Boxes Small, No Text

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4086]
Hey. When Flip Switch is clicked, it comes up with two text boxes, but both are small and blank. They work when clicked, but don't display the action each does. 

Thanks.

**Comment by Saintis** [comment]
Have you tried a hard refresh?

**Comment by Jelley07** [comment]
I have not. I will do.

Thanks.

**Comment by Jelley07** [comment]
That hasn't fixed the problem. I've tried it on Chrome and Edge. It's the only card that seems to be doing it. I don't know much about these issues so it's entirely possible it's an issue on my end. 

Thanks.

**Comment by NoahTheDuke** [comment]
Hmmm weird. Thanks!

**Comment by ZomBagus** [comment]
I noticed this during codemarvelous live stream earlier too.

**Comment by AndersRask** [comment]
Weird. I did search for Flip before opening a task 🤔
