### ISSUE TITLE
Chop bot inoperable

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#4088]
choppy:
replicate: install chopbot, attempt to use the ability on any card.
effect: mouse crosshair remains, user unable to interact with the UI. Rejoining the server or starting to type into chat outputs chop bot trash text and disables chopbot, but doesn't change the boardstate.

**Comment by Saintis** [comment]
First reported in #4085

**Comment by NoahTheDuke** [comment]
Thanks Saintis!
