### ISSUE TITLE
Interface Locks up when Exclusive Party is Played

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4089]
Problem:  When Exclusive Party is played, interface locks up (as if disconnected or lagging).  If you refresh and rejoin, exclusive party will have executed and be in the temporary zone.

To replicate:  Play Exclusive Party (so far as I can tell anytime).

**Comment by hiddenaway1** [comment]
I had the same problem. Also appears that Levy AR Lab Access locked the game up in a similar fashion.

**Comment by MHGray** [comment]
@hiddenaway1 Also had this happen with Levy AR Lab Access. Levy goes to temp zone after being played and takes a while to resolve, does not draw the 5 cards after resolving either.
