### ISSUE TITLE
London Library clones chameleon at end of turn.

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#409]
If i install a chameleon on london library and leave it there untill end of turn it clones the card and puts one in my hand and one in my heap.

**Comment by JoelCFC25** [comment]
Duplicate of #325. Use the workaround suggested there in the meantime.

**Comment by gtgettel** [comment]
Might work to split the end of turn into a end of turn phase and clean up phase. chameleon could occur in end of turn and london library happens in clean up. thoughts?
