### ISSUE TITLE
Legality Checker for Stimhack Online Cache Refresh 9

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#4096]
I was hoping for a legality checker for the next Stimhack Online Cache Refresh 9 tournament.

The format is:

* 3x System Core 2019
* 1 Big Box (Creation and Control/Honor and Profit/Order and Chaos/Data and Destiny)_ (this may be different for Runner and Corp)
* 1 Copy of Reign & Reverie
* Magnum Opus Champion Cards (Labor Rights, Crowdfunding, Slot Machine, Border Control, Timely Public Release, Embolus)
* All 6 Packs of the Kitara Cycle
* Downfall, the first half of the Ashes Cycle

Plus the Standard MWL

There is a tournament thread with details here:
https://forum.stimhack.com/t/stimhack-online-cache-refresh-9-information-thread/10419

The tournament starts April 7th, so ideally the checker would be online before that, but any time during the tournament would be great.

**Comment by NoahTheDuke** [comment]
It’s on my radar! Thank you!

**Comment by NoahTheDuke** [comment]
Done!
