### ISSUE TITLE
Masterwork doesn't give MU and gives too many bonuses

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#4097]
1) Masterwork doesn't give any MU.

2) If you install a hardware, every card you install after it in that turn will also result in a draw.

**Comment by NoahTheDuke** [comment]
I wonder who’s fault this is???? 🤔

**Comment by ZomBagus** [comment]
I just came here to report the same thing.

I bet it was Enigma ;-)

**Comment by NoahTheDuke** [comment]
Hint: it’s me. It’s my fault.
