### ISSUE TITLE
Class Act does not draw cards when installed off a Street Peddler on Corp turn

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#4106]
Here's a copied and pasted game log for a game I was spectating:

> CORP started their turn 4 with 8  and 5 cards in HQ.
> CORP spends  and 1  to advance a card in Server 1.
> CORP spends  and 1  to advance a card in Server 1.
> CORP spends  and 1  to advance a card in Server 1.
> CORP scores The Future Perfect and gains 3 agenda points.
> RUNNER uses Street Peddler to install The Class Act lowering its install cost by 1 .
> RUNNER spends 2  to install The Class Act.
> RUNNER uses Az McCaffrey: Mechanical Prodigy to reduce the install cost of The Class Act by 1 .
> CORP discards 1 card from HQ at end of turn.
> CORP is ending their turn 4 with 5 and 5 cards in HQ.

Class Act did not cause the runner to draw any cards, either on this turn or their following turn.

**Comment by frenchban** [comment]
Hi,
it seems that the bug is not fixed.  I had the same issue today.
