### ISSUE TITLE
Divested Trust with multiple accesses in Archives

### ISSUE THREAD

**Issue by EqualzDee** [mtgred/netrunner#4107]
The runner accessed my Archives (which contained both SDS Drone Deployment and City Works Project) while on 3 agenda points, and while I had Divested Trust in my score area. They stole SDS Drone Deployment, at which point I used Divested Trust to move it to HQ. They then stole City Works Project and Jinteki.net declared them the winner of the game. Although there is no yet errata for Divested Trust to clarify it's interaction with the winning agenda, clearly they should not win the game because they were only ever at a maximum of 6 points in their score area.

I have not yet tried to reproduce this bug.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look.

**Comment by EqualzDee** [comment]
Played another game where it came up, looks like Divested Trust doesn't update the runner's agenda points correctly. It gives them the points from the stolen agenda and doesn't take them away. I'm not familiar enough with the rules to know if they should ever be there at all.

**Comment by NoahTheDuke** [comment]
They should! If you steal the game-winning agenda, the Corp doesn't have the chance to use Divested Trust to switch it out. But you're correct that they're not losing the agenda points. We'll get a fix up today.
