### ISSUE TITLE
Muertos Gang Member uninstall trigger when blanked by Dr. Lovegood

### ISSUE THREAD

**Issue by eniteris** [mtgred/netrunner#4108]
Muertos Gang Member fires the uninstall trigger when blanked by Dr. Lovegood, despite not being uninstalled.

Might also want to test its interaction with Apocalypse, and trashed while blanked.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Yep, Muertos Gang Member is def messed up right now.
