### ISSUE TITLE
Az triggers twice with DJ Hayley installed

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4120]
Playing against an Az which installed DJ Fenris and hosted Hayley, Az triggered twice on both hardware and resourced. In every case there was a 0 cost card amongst the 2, so nothing of actual consequence went wrong, but the Az trigger message was printed to console, so I assume the Az ability fired.

**Comment by NoahTheDuke** [comment]
Is this still happening, @presheaf? Think it's the same bug that caused double draws?

**Comment by presheaf** [comment]
Sorry about the SUPER late reply here, but I haven't encountered it since, so I'm assuming it's closed. :)
