### ISSUE TITLE
Doing takebacks with Bacterial Programming messes with runners mu and hand size

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4121]
Me: Corp on Chronos Protocol
Runner: Chaos Theory

I messed up my Bacterial Programming turn when runner stole it, so we did 2 takebacks getting runner to do /undo-click

We then observed something weird: when doing undo, runners mem went to -1 and his hand size was suddently 2 instead of 5. On the screenshot runner had already adjusted back to 5

![image](https://user-images.githubusercontent.com/1651150/54632988-8db0ff80-4a7f-11e9-93ef-d46a8caa8dd7.png)

**Comment by Saintis** [comment]
Brain Chip is definitely the culprit here as that changes MU and hand-size.
