### ISSUE TITLE
Personal Evolution is firing the damage when clearing strike by scoring an agenda

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4124]
It should still be inactive on score and thus not trigger.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Eric-Fletcher** [comment]
This is present with Sportsmetal as well: scoring an agenda clears the current before checking for ID triggers

**Comment by NoahTheDuke** [comment]
It’s an issue with all “when scored/stolen” abilities. Thank you for the report!
