### ISSUE TITLE
Khusyuk run automatically procs The Turning Wheel

### ISSUE THREAD

**Issue by elzilch0** [mtgred/netrunner#4125]
Got Khusyuk'd, and TTW got a counter before the Khusyuk reveal happened.

**Comment by NoahTheDuke** [comment]
What do you mean? They just happened slightly out of order? Or something more dramatic?

**Comment by elzilch0** [comment]
The Turning Wheel gained a counter, and then the runner accessed and stole
an agenda. Steal an agenda? No counter! :)

**Comment by NoahTheDuke** [comment]
Oh duh, of course. Thank you for the report!
