### ISSUE TITLE
Game becomes unresponsive after trying to play Exclusive Party

### ISSUE THREAD

**Issue by thomasbalmer** [mtgred/netrunner#4142]
When trying to play exclusive party game becomes unresponsive. Card is eventually moved to the temporary zone. I cannot then click on any elements in the game window and get a response.

Can leave and rejoin game and that seems to solve the issue until the next copy of the card comes out again.

**Comment by NoahTheDuke** [comment]
Duplicate of #4089. Gonna leave this one up so others can see.
