### ISSUE TITLE
Installing events facedown with Reboot causes them to be played at no cost

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#4143]
Look, I love Apex and I think this is a good functional change to Reboot and I think we should consider just letting this go. Buuuut...

dis spends  and 1  to play Reboot.
dis make a run ons :archives.
Sanjay has no further action.
dis uses Sure Gamble to gain 9 .
dis: and when I install an event facedown it treats it like the event has been played ><
dis make a run ons Archives.
dis uses Spec Work to gain 4  and draw 2 cards.
dis uses Reboot to install Sure Gamble, Prey, Harbinger, Spec Work, Heartbeat facedown.

Pretty neat!

**Comment by lostgeek** [comment]
Duplicate of #4085

**Comment by NoahTheDuke** [comment]
We should leave this open so other folks searching for it can find it.
