### ISSUE TITLE
Rook duplicating

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#415]
Setup: Rook installed on an ice of server 1 and Deep red also installed.
When you click on Rook to use it's ability and move it to another ice it duplicates and now two Rooks are in game (one on the old ice and one on the new).

**Comment by gtgettel** [comment]
I was unable to reproduce this. Anymore information about whether ice was rezzed or not? In the process of trying to reproduce I did find that rook can be moved to any ice not just moved horizontally or laterally. Also deep red is not completely implemented.

**Comment by JoelCFC25** [comment]
I can't reproduce this either. Note that several updates were applied today and yesterday, and that you need to forcibly refresh your browser to get the updated client side code. 

@gtgettel: none of the Caissa programs have their placement restrictions implemented at this time--that is up to the players to police for themselves.

**Comment by davide-ceretti** [comment]
The ice was not rezzed. I'll try to reproduce it myself!

**Comment by JoelCFC25** [comment]
Any progress on reproducing this? Haven't seen other reports of it recently.

**Comment by davide-ceretti** [comment]
I have tried several times but couldn't really reproduce it :(

**Comment by JoelCFC25** [comment]
It this becomes widespread, we can reopen it.
