### ISSUE TITLE
Data Raven - Counters aren't removed when spent

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#4151]
Spending counters racked up on Data Raven doesn't remove them.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by xdfubar** [comment]
Has this been tested again to be sure? I used Data Raven the other day and it was fine.
There are two options on Data Raven:
1. Give the Runner 1 Tag (this is used for the on encounter tag)
2. Token: Give the Runner 1 Tag (this is used for spending a token to give the runner 1 tag).

**Comment by NoahTheDuke** [comment]
Once its worked on, I or someone else will come back and either marked t as resolved or unable to be duplicated. If you didn’t experience it, that’s def good to know and points to something else breaking.

**Comment by aenimosity** [comment]
Haven't tested it since.

Game was vs Akiko Nisei with an installed Psych Mike and probably some other stuff.
Data Raven was hosting Kyuban. Runner ran through it twice allowing 2 successful traces for some reason.

Clicking Data Raven to spend counters to give tags - gives tags without removing counters.

**Comment by aenimosity** [comment]
Jeez, now I'm doubting myself. Maybe I went full retard and didn't select the correct option as xdfubar has suggested. This would make my 3rd bug report that is false :(

**Comment by aenimosity** [comment]
Can't reproduce. I'm guessing full-retard was the cause of the bug. Closing.

**Comment by AndersRask** [comment]
This issue is back! 
Azmari vs Jesminder, i got Power Counter on Data Raven, and when I used it it did not remove it self
![image](https://user-images.githubusercontent.com/1651150/57636967-8bb07c00-75aa-11e9-9b97-b291f46cca2d.png)
