### ISSUE TITLE
Jeeves Triggering on Three Different Nanoetching Abilities

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#4154]
![image](https://user-images.githubusercontent.com/44735253/54888883-96d30f80-4e77-11e9-82fc-ce7ef4e894c5.png)

Jeeves Model Bioroids triggers off three different Nanoetching Matrix abilities.  I was just spectating this game so I can't verify that it wasn't an issue with clicking the same Nanoetching three times or not.  I believe the Jeeves FAQ, along with how Mirrormorph is intended to work, says that three different Nanoetching clicks should be three different abilities for the purposes of Mirrormorph/Jeeves.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Yes, that’s a bug. Hopefully we can fix that when we wrap up MirrorMorph’s implementation.
