### ISSUE TITLE
Earthrise causing corp to hang on prompt

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#4156]
While the Runner has an Earthrise Hotel installed, the corp gets a prompt of 'Waiting for Runner to resolve pre-draw triggers,' followed by a prompt of 'Waiting for Runner to resolve pre-play-instant triggers' which never goes away and has to be /close-prompt'd.

**Comment by NoahTheDuke** [comment]
Duplicate of #4113, and "fixed" in #4115. I'll leave this one open so folks in the future know what's up.
