### ISSUE TITLE
Reduced Service keeps tax after moved to hand

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4157]
I was playing Blue Sun and took up the Reduced Service on RnD as part of my ID ability.
I then installed Reduced Service in a remote.
After that the tax was still 8credit for the runner.
![image](https://user-images.githubusercontent.com/1651150/55012816-48914e00-4fe8-11e9-99ba-27dce7ab7696.png)

Note: not sure if I used ability or simply dragged it to HQ, since i forgot to use the ability a couple of times.

~Also, the spend credit dialogue is blank for Reduced service, so you have to guess the amount~ :-)
See below
![image](https://user-images.githubusercontent.com/1651150/55012850-5515a680-4fe8-11e9-92ae-9f1246838048.png)

**Comment by NoahTheDuke** [comment]
Good catch! The second is a duplicated of #4083, but the first is something we need to fix. I'll write one up!

**Comment by AndersRask** [comment]
Ok. Just a note: I always search for the card before submitting bugs, but apparently they are often closed (eg i searched 'is:issue is:open Reduced', I think I need to remove is:open :-) )

**Comment by NoahTheDuke** [comment]
No worries! It's my fault for merging fixes too quick. All your reports are appreciated!

**Comment by NoahTheDuke** [comment]
Okay, I've tested your Blue Sun/Reduced Service issue and I can't reproduce it. Do you have a more specific set of steps I can try?

**Comment by AndersRask** [comment]
Did you try trashing it manually by adding to the hand? On mobile now so can't test.
it costed 8c to run RnD for the rest of the game 😭

**Comment by NoahTheDuke** [comment]
I didn't! I'll try that. If you ever get into such a situation, you can use the `/counter X` command to lower the number of counters on a given card manually to whatever you write as `X`.

**Comment by AndersRask** [comment]
Ok, let me explain better. 🤔
I had reduced service on RnD and wanted to take it to hand to move it to the scoring remote (it's unique)
I forgot to use blue sun to do this, so I dragged it to HQ instead 😊
After this, runs on RnD still was extra 8c for the rest of the game, even with reduced service in another server

**Comment by NoahTheDuke** [comment]
Ahhhhhhh okay! I’ll try that! I suspect that’s still an issue. Thank you for following up!
