### ISSUE TITLE
Exclusive Party does not resolve fully

### ISSUE THREAD

**Issue by Synisill** [mtgred/netrunner#4162]
Another card that seems to be bugged after the latest patch is Exclusive Party. After i play it, there is a loooong pause (break of about 10 seconds). After that, the played card appears in the Temporary Zone and the interface/game is frozen. Meaning i can't drag n drop anymore or push buttons. Workaround: rejoining the match. (Or playing the card effect manually)

**Comment by NoahTheDuke** [comment]
Duplicate of #4089.
