### ISSUE TITLE
Secure and Protect does not reveal the ICE installed

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#4163]
Secure and Protect requires the corp to reveal the ICE. The name of the ICE installed with Secure and Protect is not displayed in the chat log

![image](https://user-images.githubusercontent.com/35308609/55103565-9f6a5680-50c0-11e9-9725-ed7d77391d23.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
