### ISSUE TITLE
MCA Informant leads to game crash?

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#4166]
A maybe-a-bug report: 
In my last match, the last action before the game crashed (opponent runner had blanked cards, I tried to fix by leaving and re-joining and I could not join) was me installing an MCA informant on runner's Beth Kilrain-Chang.
We did not do anything else, so I suppose the error must have been caused by that MCA informant.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look.

**Comment by NoahTheDuke** [comment]
On further investigation, I suspect this is an issue with Beth, not MCA Informant. I'm writing up a test of MCA Informant to help against regressions in the future, but we should be good to go either way.
