### ISSUE TITLE
"Failed to execute removechild" error on hand card mouseover

### ISSUE THREAD

**Issue by wagnonbe** [mtgred/netrunner#4169]
I've been seeing this off and on, but finally got it to happen in a more reproducible situation. At points during a game, I'll find that mousing over one of my cards will crash the game for me (black screen). After refreshing and rejoining, the same card will continue to cause this. Post crash, if I hold my mouse over the card, the last error in that screenshot will continue to error for me. The card itself doesn't seem to be constant - I've seen this from both sides and with different cards.

This happens after varying amounts of time - my last game, on my first turn as Runner, I drew twice, maybe installed a Daily Casts/Crowdfunding, and then this began happening for Earthrise. I made a game by myself, and saw it immediately with Career Fair.

![image](https://user-images.githubusercontent.com/1815998/55281569-cfa63500-530c-11e9-8448-573da0d2aa09.png)

This issue happens consistently on one computer for me (even with clearing cookies/local storage), but not elsewhere. Currently on Win10 Google Chrome 73.0.3683.86 (current as of today).

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'm sorry I never followed up with this. Is it still happening?

**Comment by wagnonbe** [comment]
So embarrassingly, the most likely culprit was some hacky Chrome extension - I should have tried in incognito mode before submitting this.
