### ISSUE TITLE
Flip Switch prompts during a trace in corps turn

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4172]
Hi,

![image](https://user-images.githubusercontent.com/1651150/55293073-5123c300-53f2-11e9-9f8c-6616bf303d40.png)

Flip Switch states that it cannot be used in corps turn, but it prompts the runner to use it, if the corp initiates a trace, for example with a Punitive Counterstrike.

None of the effects should be able to be triggered during corps turn

**Comment by NoahTheDuke** [comment]
The final trace ability currently works on the corps turn but the other abilities do not. Thanks for the report!

**Comment by BlueHairedHackerCatgirl** [comment]
![image](https://user-images.githubusercontent.com/46433823/55430258-81e83180-5585-11e9-80d5-f2acfd54fecc.png)
Also experienced this.
