### ISSUE TITLE
Architect Deployment Test Works Only On ICE

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#4174]
Architect Deployment Test only works if an ICE is revealed.  But it should work with non-ice cards as well.  This has happened to me twice, but I don't have a screenshot, sorry.

**Comment by x3N1GM4x** [comment]
Paging @presheaf as the person who implemented this card - I've only glanced at the code (and my Jnet Clojure is rusty as a very rusty thing!), but it looks like it's deliberately only allowing ice to be installed, so maybe the card was just misunderstood during implementation?

**Comment by NoahTheDuke** [comment]
Yeah I think it was based on Accelerated Beta Test, not Architect, lol. It’s an easy fix, and I’ll put one in my bug fix pr tomorrow!

**Comment by AndersRask** [comment]
this one is still buggy! :-)

**Comment by NoahTheDuke** [comment]
We haven't deployed any bug fixes yet.
