### ISSUE TITLE
Hacktivist message on ice rez

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4176]
The log shows a message about discarding a card from hand from Hacktivist when ice is rezzed with Hacktivist active.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Do you have an example?

This is the log from my attempt:
![image](https://user-images.githubusercontent.com/603677/55351073-70bafa00-548b-11e9-805b-3e480dee9748.png)

**Comment by tolaasin** [comment]
Corp had no cards in hand, don't know if that's relevant. Ice was IP Block.

**Comment by tolaasin** [comment]
it was during a run

**Comment by tolaasin** [comment]
ok, more information on this - I think I understand it. The message triggers when corp tries to rez a card but has no cards in hand, I think? In this instance, the corp tried to rez the card in server 2 with no cards in hand (twice).
AxWill started their turn 5 with 15  and 1 cards in HQ.
AxWill spends  to install a card in Server 2.
AxWill spends  to gain 1 .
AxWill spends  and 5  to play Hedge Fund.
AxWill uses Hedge Fund to gain 9 .
TugtetguT uses Hacktivist Meeting to force the Corp to trash 1 card from HQ at random.
TugtetguT uses Hacktivist Meeting to force the Corp to trash 1 card from HQ at random.
