### ISSUE TITLE
Flip Switch in the Log

### ISSUE THREAD

**Issue by 5N00P1** [mtgred/netrunner#4178]
Using Flip Switch to remove a tag is not logged in the console.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by AndersRask** [comment]
Same with "jack out" on Flip Switch. It just say "<runner> jacks out".
It should say "<runner> used Flip Switch to jack out".
I've seen some confusion like "you cant jack out" as the log didnt state they used FS
