### ISSUE TITLE
New Feautues: Multiplayer Cube Draft

### ISSUE THREAD

**Issue by izram123** [mtgred/netrunner#4179]
Hi, 

Is it possible to make multiplayer a thing and cube draft on the site. Just wondering.

IZRAM

**Comment by NoahTheDuke** [comment]
Neither is possible. Sorry, but we can’t keep up with existing bugs; there’s no way we could implement either of those things.

**Comment by Saintis** [comment]
Also previously discussed in #2080 and #2088.

**Comment by presheaf** [comment]
Note that you can do cube draft on https://meteor.stimhack.com/draftinfo . Doesn't handle everything for you like setting up a legality checker ensuring decks are legal and so on and so forth, but it does a good 90% of what you want.
