### ISSUE TITLE
Khusyuk trying to count cards of with a cost of 99 credits.

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#4180]
I don't know what would cause this, but using Khusyuk in this scenario led to the option of choosing cards that cost 99 credits. The system correctly counted that I had 0 installed, however I don't know why it would look for cards that cost 99 credits. My only guess is the Liza ID hosted on DJ Fenris, however I did not get any other information from the game.

<img width="670" alt="Screen Shot 2019-04-02 at 10 48 11 AM" src="https://user-images.githubusercontent.com/2737888/55427423-d5ce2880-553b-11e9-9031-3dfb7a81b5a8.png">

**Comment by NoahTheDuke** [comment]
You have to be able to choose any number, so we show 99 as there aren’t any cards that cost 99.

**Comment by armerpaul** [comment]
I see. When I was playing it wasn't obvious. I guess I'll just close this issue then.

**Comment by NoahTheDuke** [comment]
I appreciate you letting us know it was confusing! I'll add an Implementation note so folks understand.
