### ISSUE TITLE
Divide and Conquer doesn' t access the card from R&D

### ISSUE THREAD

**Issue by Anubisauman** [mtgred/netrunner#4182]
Log says I accessed the card but after accessing Archives and HQ the card resolution ends.
![BugReport](https://user-images.githubusercontent.com/49250326/55505010-ceea0780-565a-11e9-9009-1f7b0158025c.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I can't reproduce this. Do you have a reproduceable set of steps I could take to make it happen?

**Comment by Anubisauman** [comment]
No sorry I can't seem to reproduce it either.
