### ISSUE TITLE
Mouse over when showing cards in prompt, so you can see the card

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4186]
It would be awesome, if the dialogue that shows cards (for example with Stargate) if you could have the card shown when you mouse-over the cards.
If it is some weird card that is rarely played, it is hard to tell what card it is. Showing the card on mouse over the card name would really be helpful!

**Comment by NoahTheDuke** [comment]
I’m confused. How is this different than normal?

**Comment by Saintis** [comment]
When you use Stargate and get the prompt to chose which card to trash, the choices do not link to card images

**Comment by Saintis** [comment]
One alternative solution is to have Stargate reveal the cards _before_ the runner makes the choice to allow the names in the chat to be hovered and therefore viewed.

**Comment by AndersRask** [comment]
Stargate was just an example. I think it is the same with Khusyuk.
Basically I want the same information as IRL: to see the actual card, not just the name. Stargate showed 2 agendas, but the second one was some obscure card so could not remember if it was a 4/2 or 5/3 so had to write name in chat to verify

**Comment by AndersRask** [comment]
It could be solved simply by showing the card mouse over for all these kind of dialogues (both when runner sees corp cards and own cards, and when corp sees own cards (eg. Anansi, Architect, DBS) or runners cards)
