### ISSUE TITLE
Wake Up Call cannot be played after Embezzle or Stargate trashes a card.

### ISSUE THREAD

**Issue by TokaysAX** [mtgred/netrunner#4188]
Wake Up Call cannot be played after Embezzle or Stargate trashes a card, even if there are valid targets.
Example #1: Embezzle targetting operations, Runner hits operation and Agenda. Operation is trashed but Wake Up Call is not playable on the corps turn.
Example #2 Stargate trashes a card from R&D but Wake Up Call is not playable on the corps turn.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
