### ISSUE TITLE
Using Eater in Archives reveals all cards in Archives

### ISSUE THREAD

**Issue by McBEASTse** [mtgred/netrunner#419]
Caduceus was protecting Archives, and the Runner (Edward Kim) was using Eater to break the subroutines (and should not be able to see the hidden cards in Archives) and continued the run. The Runner didn't access any cards in Archives, but still revealed all face down cards. The chat didn't say anything about access.

As far as I know, using Eater shouldn't let the Runner see any face down cards in Archives, as he/she is not accessing it.

**Comment by DominicKexel** [comment]
Turning all cards face up in archives is the correct behaviour.

Lukas clarified it some time ago:

> You flip all cards in Archives faceup, but you do not access any cards. This is because Eater does not replace the entire access, it only prevents you from accessing more than 0 cards.

**Comment by McBEASTse** [comment]
All right, sorry for the "bug" post. Didn't know that about Eater. The more
you know!

Thanks

2015-07-22 10:48 GMT+02:00 DominicKexel <notifications@github.com>:

> Turning all cards face up in archives is the correct behaviour.
>
> Lukas clarified it some time ago:
>
> You flip all cards in Archives faceup, but you do not access any cards.
> This is because Eater does not replace the entire access, it only prevents
> you from accessing more than 0 cards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtgred/netrunner/issues/419#issuecomment-123621691>.
>



-- 
________________________________________________
M a r c u s  P e t t e r s s o n

http://dtms.se/
+46 (0) 70 55 70 785
________________________________________________
