### ISSUE TITLE
Aggressive Secretary does not record cost to pay in the chat log

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4196]
Not sure whether this is also the case for other traps such as Junebug ... corp 'uses' agg sec, but it would be more consistent to say 'pays 2c to use Agg Sec'

jamesgrey accesses Aggressive Secretary from Server 8.
campino uses Aggressive Secretary to trash Yusuf.
jamesgrey pays 0  to trash Aggressive Secretary from Server 8.
jamesgrey spends  and 1  to install Clone Chip.
jamesgrey spends 1  to install Yusuf.

**Comment by NoahTheDuke** [comment]
I would suspect it's an issue with most all abilities. I'll have to think about this and see what a solution would look like. Thanks for bringing it up!

**Comment by NoahTheDuke** [comment]
jk Turns out this was just a problem with Aggressive Secretary. Fixed!
