### ISSUE TITLE
Searchlight chat text

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#4200]
In rare circumstances, you can meet a Searchlight out there in Weylandia. Unfortunately, the chat message is a weirdo.
<img width="260" alt="searchlight" src="https://user-images.githubusercontent.com/11632063/55960842-e08c6a00-5c6d-11e9-86e7-1a9e590e96cc.png">

**Comment by NoahTheDuke** [comment]
Thanks for the report!
