### ISSUE TITLE
Console should state what cards runner trashes for Degree Mill

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4206]
When a runner steals Degree Mill the console does not tell what cards the runner trashed as additional cost for stealing the agenda.

![image](https://user-images.githubusercontent.com/1651150/56099136-62e48a80-5f09-11e9-8c94-28ee691cae20.png)

**Comment by NoahTheDuke** [comment]
Good point, I’ll see what we can do about that
