### ISSUE TITLE
MaxX + Wyldside stalls game

### ISSUE THREAD

**Issue by jtoman** [mtgred/netrunner#4213]
When beginning a turn with Maxx, the following stalls the game:

* Click start turn
* Click Wyldside
* Click Maxx
* Click "take clicks"

Nothing happens, except the number of clicks decreases (you can't advance to the next prompt). Manually moving wyldside back to hand allows the clicks to be taken, but the corp screen stays at "waiting for runner to resolve take click actions", even after the runner clicks "end turn".

**Comment by NoahTheDuke** [comment]
Huh! Thanks for the report, that's wild.

**Comment by jtoman** [comment]
*wyld
