### ISSUE TITLE
Maw does not trigger on a run on news team access

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4214]
Maw does not currently trigger when News Team is accessed and added to the score area. Documented in #2923 which was fixed for Shikyu, apparently.

**Comment by tolaasin** [comment]
analyzechris spends  and 6  to install Maw.
analyzechris spends  to install Same Old Thing.
analyzechris spends  to use Stargate to make a run on R&D.
HouseofCards has no further action.
HouseofCards uses Paywall Implementation to gain 1 .
analyzechris uses Stargate to reveal NGO Front, Back Channels, Mushin No Shin from the top of R&D and trash Mushin No Shin.
analyzechris spends  to make a run on HQ.
HouseofCards has no further action.
HouseofCards uses Paywall Implementation to gain 1 .
analyzechris accesses News Team from HQ.
HouseofCards uses News Team to force the Runner take 2 tags or add it to their score area as an agenda worth -1 agenda point.
analyzechris adds News Team to their score area as an agenda worth -1 agenda point.
analyzechris is ending their turn 8 with 11  and 5 cards in their Grip

**Comment by NoahTheDuke** [comment]
Stupid Maw! Thanks for the report!
