### ISSUE TITLE
Rejig applying half cost reduction

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4215]
![image](https://user-images.githubusercontent.com/7817263/56761503-7eeaf600-676b-11e9-9603-06d50d056f16.png)

When you play rejig, you have to pay half the cost (rounded up) to replay the card. When I tested with Femme I had to pay 5 credits. 

This may have been closed and not deployed by #4105

**Comment by NoahTheDuke** [comment]
This is entirely due to my inability to read a gd card, ha. It clearly says "printed cost", and yet I misread it as "half the printed cost". Fix forthcoming.

Thanks for the report!
