### ISSUE TITLE
Start Game window doesnt clear if you click old 'Start Game' button

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4216]
If you click the 'Start Game' button from the original UI the Start Game window does not clear, and you can play the whole game with it open.

![image](https://user-images.githubusercontent.com/7817263/56761774-3253ea80-676c-11e9-9640-d47c729253fd.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! This is very silly and completely understandable. I'll get a fix up!

**Comment by NoahTheDuke** [comment]
jk this is complicated lol
