### ISSUE TITLE
Rezeki consistently does not give the right number of credits for the number installed

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4218]
Playing today, 2 rezeki installed, often saw runner get 3 credits rather than 2 and have to adjust manually downwards.

**Comment by NoahTheDuke** [comment]
Huh! That's super weird. I wonder what's going on! Thanks for the report, I'll take a look.

**Comment by Eric-Fletcher** [comment]
Did you have a Beth installed with the Corp below 5 credits?

**Comment by tolaasin** [comment]
That could be.

**Comment by NoahTheDuke** [comment]
Have you seen this again, Tolaasin? I'd love to get it fixed if you have any more details.
