### ISSUE TITLE
Khusyuk doesn't register card accessed for Under the Bus

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4224]

**Comment by NoahTheDuke** [comment]
Do you have any additional information? Looks like it's working in the code.

**Comment by BlueHairedHackerCatgirl** [comment]
It was a judge call in a game today:

Runner had accessed a card with Kyushuk, but the corp couldn't play under the bus next turn. The Kyusuk card was the only card they'd accessed the previous turn.

**Comment by NoahTheDuke** [comment]
That's super weird! I'll check it out.
