### ISSUE TITLE
Pelangi subtypes list omits all previous choices (gets shorter with every use)

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4227]
When you use Pelangi it seems to remove that subtype from the list for all future uses.
See attached file where one turn I used it to give Barrier. The next turn Barrier was not in the list.
![pelangi list shortening](https://user-images.githubusercontent.com/13881796/57195988-304e1080-6f50-11e9-95e8-12d9e3522da7.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I’ll take a look!

**Comment by ZomBagus** [comment]
i think its because i bounce the ice to HQ before the encounter ends something isnt being reset.
i suspect all ice have all the types ever granted but would need to test

**Comment by NoahTheDuke** [comment]
That’s it exactly! Thanks so much!

**Comment by NoahTheDuke** [comment]
What card were you using to jack out?

**Comment by ZomBagus** [comment]
Ankusa
