### ISSUE TITLE
No Sound In-game

### ISSUE THREAD

**Issue by Agent-Chezni** [mtgred/netrunner#4228]
First off, thanks for providing countless hours of entertainment, as well as keeping ANR alive (let's be real, it's the best card game around).

I'd like to report that the sound doesn't seem to be working for multiple users while in-game. Oddly, entering a game lobby still makes the "ding-dong" sound, but when you actually make it into the game, the sound cuts out. I personally am accessing jnet through Chrome, and can confirm that 3~4 others have reported similar issues in general chat.

Let me know if I can provide any additional detail or assistance.

Thanks!
--Chezni

**Comment by nealterrell** [comment]
Should be fixed now!

**Comment by AndersRask** [comment]
cool! what was the fix? I have had this a while too

**Comment by nealterrell** [comment]
Server misconfiguration after moving to a new machine.

**Comment by Agent-Chezni** [comment]
Thank you Neal!! <3
