### ISSUE TITLE
"Legal" Decks Showing As "Illegal"

### ISSUE THREAD

**Issue by Agent-Chezni** [mtgred/netrunner#4242]
Hello,
When creating a deck for standard 3.2 format, all seems well--the deck below shows as legal:
![image](https://user-images.githubusercontent.com/37345646/57576203-02187700-740f-11e9-899e-2f9f57cee7fa.png)

When selecting the deck in a game lobby, it shows legal:
![image](https://user-images.githubusercontent.com/37345646/57576211-21af9f80-740f-11e9-8568-f8997b90d058.png)

However, once selected, it shows as illegal:
![image](https://user-images.githubusercontent.com/37345646/57576216-312ee880-740f-11e9-8fcd-78533fd96fb8.png)

After some testing, I discovered that removing the restricted card (in this case, Global Food) and replacing it makes the deck change to legal. Likewise, I tested the same with Mumba Temple and got the same results.

Browser is Google Chrome. Let me know if I can provide any other detail!

Thanks,
--Chezni

**Comment by AndersRask** [comment]
I can second this. It also shows up as STANDARD LEGAL in selection, but it is way down in list! Deck also is not showed on top of Standard list, even though it was the newest one
![image](https://user-images.githubusercontent.com/1651150/57587353-fa86ca00-7503-11e9-95a7-f2319612075f.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I’m working on a fix.

**Comment by pat-gardner** [comment]
I have a similar issue. In my case, decks with Violet Level Clearance and a restricted card show as standard legal in the deckbuilder, but aren't present in the list of standard decks in the game lobby.

Deck is legal according to deckbuilder: 
![image](https://user-images.githubusercontent.com/39884514/58047230-4392db80-7b0d-11e9-9fcf-84cbf3a6a5de.png)

But doesn't appear in the lobby (Notice the Gagarin deck with Mumba Temple and Bankers also doesn't appear):
![image](https://user-images.githubusercontent.com/39884514/58047254-59a09c00-7b0d-11e9-88d0-f0b84c651ee4.png)

Removing VLC causes it to show up:
![image](https://user-images.githubusercontent.com/39884514/58047281-6d4c0280-7b0d-11e9-87e9-58429d67c833.png)
