### ISSUE TITLE
Gnat does not gain credit with 2 or fewer cards in deck when Earthrise Hotel is installed

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4245]
Runner should be able to order the effect of Gnat and Earthrise Hotel, so that he gets his Gnat credits before Earthrise triggers

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
This is already working. When Earthrise Hotel is installed, you get a phase 1.2 toast and can click on Gnat to fire it first.
