### ISSUE TITLE
Some kind of socket error?

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#4246]
My coworker and I tried starting and joining games today and weren't able to. We regularly play at work without issue. 

When attempting to start a game, we click "Create" on the New game screen, the screen reverts to just the game list, and nothing else happens.

When attempting to join or watch a game, the respective button shows its click animation, and then nothing else happens.

In the console after attempting any of these, we see this error:

![image](https://user-images.githubusercontent.com/12355388/57875556-774dc880-77d0-11e9-8e53-1fe1392ce797.png)

I looked up taoensso.sente and it appears to be a clojurescript websocket library. I assume Jinteki.net uses this to establish a communication channel between clients and the game server. I also assume that our work protocols changed recently and blocked our ability to use websockets, but I don't know for sure. I thought I'd pass this along just in case. If this is nothing on your end, feel free to close the issue.

Thanks!

P.S.: This was in Chrome, but also happens identically in IE (I know you don't support IE, just extra information).

**Comment by NBKelly** [comment]
Hi, I think the conditions relevant to this issue are no longer reproducible, so I'm closing it as stale. If you have something like this happen again, please feel free to create another issue.
