### ISSUE TITLE
Möbius triggers indefinitely (again)

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#4253]
Möbius triggers on every RnD run after use. This issue was fixed in 2017 (#2483, #2481, #2456), but it seems to be back once more.

**Comment by NoahTheDuke** [comment]
Dang it, thank you. I'll take a look! Do you have any screen shots or game log?

**Comment by NBKelly** [comment]
Whoops, missed the notification for a while.

Was playing leela every game this happened so far, and in this particular instance I had:
*Equivocation installed
* Bankroll installed
* Paragon installed
* Used inside job

It bugs out with no triggers attached though, ata whopping 100% hit rate for me.

To reproduce:
* Use mobius
* Make the second run on RnD with Mobius and succeed
* Make any run on RnD afterwards to get bonus Mobius credits

![_untitledimage](https://user-images.githubusercontent.com/9095245/59142480-0dad8c80-8a13-11e9-97ba-18de30fd8937.png)

**Comment by lostgeek** [comment]
This is weird. Looking at the code, I'm wondering how it ever worked. I'll take a look once I'm at home.
