### ISSUE TITLE
Crisium Grid implementation is incorrect with respect to effect on future runs

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4255]
Liza makes a run on R&D which has a Crisium Grid installed. That run is neither successful nor unsuccessful. Liza trashes CG and runs a second time with Paragon installed. At the moment, that second run is not treated as the first successful run that turn by either Liza or Paragon and the card effects do not fire.

This implementation is incorrect and does not reflect the relevant rulings. I have confirmed this with Jakodraco on Nisei Slack. The second run should be treated as the first successful run that turn.

**Comment by NoahTheDuke** [comment]
Sadly, this will probably have to be relegated to “won’t-fix” as we don’t have a way to store the two different event logs and know when to check them.

**Comment by tolaasin** [comment]
Right - though I'm not sure I follow re. two event logs. I'm assuming at the moment Liza looks back and sees a successful run earlier in the turn - but not how that was recorded, and how crisium inactivates it.

**Comment by tolaasin** [comment]
i think that a way to highlight in game that the effect is not correctly implemented would be useful.
