### ISSUE TITLE
Masterwork V37/The Class Act - Installing on Opponent's Turn Locks Prompt

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#4256]
Prompt wont' close with the following situation:

**Installed cards:** 
Masterwork v37, DJ Fenris hosting Hayley, The Class Act, Street Peddler.

**Play:**
Pop Street Peddler on Corp's turn to install hardware, which triggers a draw from Masterwork v37. The Class Act prompts one of two cards to be placed on the bottom of the stack. Selecting one of the options does not close the prompt. "/close-prompt" closes prompt but either draws both cards or just the first (can't remember which). Hosted Hayley does not trigger when this happens.

It's a bit of a long-winded combo so reproducing to confirm may take a little while.

**Comment by NoahTheDuke** [comment]
Huh that’s super weird! Thanks for the report, I’ll take a look.

**Comment by aenimosity** [comment]
Forgot to mention that the runner ID was Geist

Just played a bug-test match to try to confirm. First attempt didn't work. Second attempt sort of did - both cards shown by TCA were Spy Cameras, however one of them got placed in hand before interacting with the prompt.

Clicking the first prompt option didn't do anything, but clicking the second option did. I would hazard a guess that the game can't do anything with the first option because that particular card is already in hand.

Hayley still doesn't trigger on opponent turn.

**Comment by NoahTheDuke** [comment]
Sorry for the delay, got around to trying this out and I can't get it to work. On the other hand, I'm trying it on the most up to date jnet and not what's on prod so it's possible it got fixed accidentally at some point? I'm gonna close this for now, but please let me know if you see it again.
