### ISSUE TITLE
Faerie installed mid-run has bonus strength

### ISSUE THREAD

**Issue by MasterAir** [mtgred/netrunner#426]
When playing with Geist I installed Faerie during a run using a clone chip. The Faerie was installed and immediately pumped to match the strength of the ICE currently being encountered (apparently at no cost).

**Comment by DominicKexel** [comment]
Remeber what ICE it was?

**Comment by nealterrell** [comment]
Did you get a chat log message about Faerie being boosted?

**Comment by nealterrell** [comment]
Was the Faerie used previously to break the same ice? I am now seeing that a trashed icebreaker retains its "current strength", so the next time you install it will have the strength it was boosted to previously. This is really only visible to Sharpshooter and Faerie, who boost and then trash themselves before their strength would have been reset by the normal run flow.

**Comment by MasterAir** [comment]
I'm unsure. If I see it again, I'll be more careful to note the specifics and report back.

The strength boost was visible only from the bottom right of Faerie, if I recall correctly. I'm not sure if I had used the Faerie on the same run. I do recall it happening multiple times in one game though.

**Comment by nealterrell** [comment]
Thanks. I have confirmed what is likely the cause, that trashing an icebreaker while it is pumped does not clear the pump effect, so next time you install it from heap it will have the previously-pumped strength. Let me know if this is not the pattern you're seeing :).
