### ISSUE TITLE
Can't click on cards in servers with 2 upgrades and agenda

### ISSUE THREAD

**Issue by sperry023** [mtgred/netrunner#427]
This occurred in two separate games for me -- I had a scoring server started (Server 0 in the image below), and then created Server 1. As the game went on and I added more upgrades to Server 0, Server 1 did not shift to allow space for it (there is a Server 0 upgrade under the PAD Campaign). Even though I can see the card, hovering over it did not show me anything in the preview window and clicking did not rez it. Zooming out did not make the cards shift. I am using Google Chrome on a MacBook Air.
![upgrades problem](https://cloud.githubusercontent.com/assets/13188311/8853468/cddc7b62-3128-11e5-9468-d7ba1423d591.png)

**Comment by mtgred** [comment]
Thanks for reporting the issue. The last update causes a layout issue with upgrade positioning. When there are more than 2 cards in a remote, the cards on the right go are underneath the next remote server and they can’t be clicked anymore.

The code has been reverted on the server while this is being investigated.

**Comment by mtgred** [comment]
It seems to be problem with the latest Chrome update (version 44). The problem is also present on Firefox on Mac OS though.

**Comment by eedok** [comment]
![card-overlap](https://cloud.githubusercontent.com/assets/7716019/9767509/c9084d2c-56db-11e5-9214-7dd6b6391250.jpg)

Looks like it happens on the windows version of firefox as well, as a temp workaround maybe we can have it so we can manually drag servers around(or create empty servers and rearrange them by dragging the label)?

**Comment by JoelCFC25** [comment]
This is more or less fixed, though remotes with 4 or more items might still be a little tricky.
