### ISSUE TITLE
Chopbot not working

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#4279]
Hi not sure if this has been posted before but chopbot is not functioning at all clicking on it brings up no menu and I've been having to do it manually for awhile now.

**Comment by lostgeek** [comment]
I can't replicate this. Are you clicking on it during your start of turn triggers? Can you maybe take a screenshot of the board state when this is happening?

**Comment by PinkWarrior** [comment]
I am clicking before hitting start turn and after neither seems to work i will take a screenshot next time i play it.

________________________________

**Comment by PinkWarrior** [comment]
Here you go i got 2 shots of chopbot before turn and after not responding, I also got one of rejig costing me money to install engolo after bouncing engolo to hand.

________________________________

**Comment by NoahTheDuke** [comment]
I don’t think you can attach images through email. Try it from the website?

**Comment by PinkWarrior** [comment]
ok well nm then i think i know what the issuse is now, it's not working like it uster do in fireing before of after clicking start turn button except when it's asking for triggers like when you click start turn with a rez'd rashida down the problem is it's not giving me that window unless i have something else to trigger that window. Also it uster work fine before and after when that window wasn't their so it's probably todo with that. i'll look at linking the screen shots on the website also

________________________________

**Comment by PinkWarrior** [comment]
![Chopbot](https://user-images.githubusercontent.com/11097296/59964408-1795bc00-94f8-11e9-8ff5-c11e8c733f0e.jpg)

**Comment by NoahTheDuke** [comment]
Yeah, it has to be used at the start of the turn. The game pauses before you gain your clicks, allowing you to use it by clicking on it, but it won't automatically fire for you.
