### ISSUE TITLE
LLDS Energy Regulator and Acacia

### ISSUE THREAD

**Issue by Matjek** [mtgred/netrunner#4280]
When both Acacia and LLDS Energy Regulator are installed and the corp purges, it is giving the Runner the credits before prompting if they want to prevent the trash with LLDS Energy Regulator.  Nisei's rule sheet 9.8.1.a states "A composite effect is one that uses the word “and” to combine multiple effects into one. Both parts resolve simultaneously, and the opportunity to prevent either or both parts occurs before either effect."  The runner therefore shouldn't gain credits until after they've made the decision to prevent the trash, so if they don't have (or can't gain) 3 credits to activate LLDS they can't prevent the trash.

**Comment by lostgeek** [comment]
Wow. Good catch!
