### ISSUE TITLE
scroll in console not working after latest update

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4289]
Looks like scroll in console have stopped working after latest update
The text stays where u scroll to, and doesnt follow the new events

![image](https://user-images.githubusercontent.com/1651150/60205903-aedd7500-9852-11e9-8be2-004068249d64.png)

**Comment by NoahTheDuke** [comment]
Ah heck, thanks. I'll see if I can get a fix up quick.

**Comment by danrs** [comment]
@NoahTheDuke I've seen this issue when using jnet in Firefox on Windows. However, autoscroll works fine in Chrome on MacOS. Hopefully that information is helpful

**Comment by x3N1GM4x** [comment]
FWIW, I have experienced the issue on Chrome (75.0.3770.100) under Windows 10.

**Comment by aenimosity** [comment]
Had this issue intermittently for the last week or so. I think it's a problem with the zoom level of the browser. 100% zoom has no issues. Will post in the other thread as I have no idea how the github system works.

**Comment by AndersRask** [comment]
Yeah I can confirm it has to do with zoom level @NoahTheDuke . I have a large display running 3440x1440 and normally i zoom in to 170% due to the high rez. If i zoom out to like 140% it is tiny, but scroll works!

**Comment by AndersRask** [comment]
@NoahTheDuke can we expect the fix being released to live? :)

**Comment by NoahTheDuke** [comment]
At some point! I don’t have access to the server, so it’s not up to me sadly.

**Comment by AndersRask** [comment]
@NoahTheDuke wow, still not published! Who is responsible for releasing changes? It seems rather sub-optimal that you spend so much time fixing these bugs, and nobody bother to put them live? :-(

**Comment by NoahTheDuke** [comment]
You’re late to the party, my friend! I just updated the server 8 hours ago! Go play around with it and let me know if it’s still broken.
