### ISSUE TITLE
Bad publicity spontaneoulsy removed

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4292]
start of turn, runner has 1 bad pub, message appears in chat 'runner removes 1 bad pub'. not triggered by a runner action.

**Comment by tolaasin** [comment]
spilgrim16 started their turn 6 with 20  and 5 cards in HQ.
spilgrim16 spends  and pays 0 to install a card in Server 6.
spilgrim16 sets bad publicity to {:base 0, :additional 0} (-1).
spilgrim16
spilgrim16
no idea why that happened?
tolaasin
tolaasin
what
spilgrim16
spilgrim16
the bad pub change
tolaasin
tolaasin
you should have 1
tolaasin
tolaasin
why remove it
spilgrim16
spilgrim16
i know
spilgrim16
spilgrim16
i didn't

**Comment by NoahTheDuke** [comment]
What else was happening? Do you remember?

**Comment by tolaasin** [comment]
It was nothing at all unusual. The Outfit had scored hostile.
