### ISSUE TITLE
Jnet eats my CPU

### ISSUE THREAD

**Issue by gegenzeit** [mtgred/netrunner#4293]
When playing, my CPU usage goes through the roof. The activity monitor clearly shows jnet being the culprit with 90-100+ % CPU usage.

In my last match, I talked tpo my opponent and he had the same issue. He uses a PC.

I tried Chrome, Safari and Firefox. Happens in all browsers and all games at the moment.

**Comment by lechaz79** [comment]
I noticed the same problem, as did several players in the chat.

**Comment by sebastian-nowakowski** [comment]
My laptop CPU usage is still very high. Guys behind jnet, dont you think this should be priority ticket? Something's very wrong with the code behind.

**Comment by 5N00P1** [comment]
have the same issue and my laptop is dying in summer!

**Comment by NoahTheDuke** [comment]
Lmao we’re unpaid volunteers, there are no priorities but what we both know how to do and have the desire to do. There’s a lot that goes on to make jnet work, and not everyone who knows all of the underlying code still works on it. 

I believe a recent change I made will have the desired performance impact, but I have no way to say when it will be deployed.

**Comment by sebastian-nowakowski** [comment]
Dont get me wrong, I really appreciate the project, and cannot say anything but "good work guyz". Didn't mean to sound like that, I'm sorry.

**Comment by NoahTheDuke** [comment]
No worries, and I’m sorry if my reply came across as more upset than I had intended. I meant it to be playful, but in rereading it doesn’t look so playful.

**Comment by sebastian-nowakowski** [comment]
http://www.netrunnerdb.com/en/card/11109

**Comment by 5N00P1** [comment]
We surely appreciate your efforts, but without an answer you get the feeling nothing is done.
My understanding is, when a new version of JNet is published we will report back if it solves our issues.
