### ISSUE TITLE
MIss Bones does not trash when empty

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4303]
Nuff said

**Comment by NoahTheDuke** [comment]
Did it drop to 0 credits from clicking the card during a pay-credits prompt or from clicking the card outside of a payment?

**Comment by tolaasin** [comment]
I'm not sure. I don't think they were using the pay-credits prompt, but
can't be sure. I've def seen this myself as well but can't recall. I can
simulate it if that helps.

**Comment by NoahTheDuke** [comment]
No worries, I think I know the culprit. Good catch!
