### ISSUE TITLE
Storgotic Resonator did not a gain a counter from a card trashed by Hostile Infrastructure

### ISSUE THREAD

**Issue by ScrappySPJ** [mtgred/netrunner#4306]
During the runners turn they ran and trashed an installed asset when I had rezzed both Storgotic Resonator and Hostile Infrastructure. The card trashed matched the runner's faction but Storgotic Resonator did not gain a power counter.

**Comment by AndersRask** [comment]
Not sure I understand this.
Storgothic say 

> The first time each turn you trash (from any location) a card that matches the faction of the Runner's identity, place 1 power counter on this asset.

If the runner trashes, then it should not trigger, as it say "you" (corp).
Hostile Infrastructure on the other hand say

> Whenever the Runner trashes a Corp card (including Hostile Infrastructure), do 1 net damage.

Doing a net damage is not trashing a card.

**Comment by lostgeek** [comment]
Doing net damage is trashing a card. Nisei Comp Rules 10.4. Damage:
>10.4.2.a. MEAT DAMAGE​ and ​ NET DAMAGE​ are resolved the same way. ​For each point of damage suffered, one card is randomly trashed from the grip.

So the Corp trashing runner cards (trashing Resources while tagged, trashing cards directly via Hunter Seeker, etc. , trashing cards via damage) should trigger Storgotic Resonator, while the Runner trashing their own cards (playing Events, cards trashing when empty, overinstalling stuff) should not trigger it.

**Comment by ScrappySPJ** [comment]
My Hostile Infrastructure dealt a point a damage, which caused a card to be trashed from the runner's hand. It matched the faction of the runner's ID but I did not gain a power counter on Storgotic Resonator.
