### ISSUE TITLE
Fencer Fueno - No prompts to use credits

### ISSUE THREAD

**Issue by AlecGamble** [mtgred/netrunner#4318]
Hey guys,

I'm playing Fencer Fueno in Jesminder with Thunder Art Gallery and there are a number of situations where I should be able to take Fencer Fueno credits but other prompts override my ability to click on Fencer Fueno.

When using Thunder Art Gallery +  DJ Fenris (Liza) or Hot Pursuit (Install prompt overrides my ability to use Fencer)
When accessing cards against Gagarin Deep Space (Access prompt overrides my ability to use fencer)

Also if I access a card I don't have credits to trash (but do have enough credits on Fencer) it won't give me the prompt to trash the card, only No Action even if I can boost my credits after. (which I can't do before because the run isn't successful yet)

I would personally like to see an implementation similar to Net Mercur because when that's installed it asks if I'd like to use any of those credits (although there's the current issue with that and using icebreakers, but obviously fencer fueno is a much more specific window so it's less)

I've tried to be as clear as possible but if you have any questions please don't hesitate.

Thanks a bunch in advance.

**Comment by lostgeek** [comment]
Hey, thanks for the detailed report! First of all: That sounds like a great deck :smile:

When implementing the new `pay-credits` prompt, I seem to have overlooked Fueno. I think including it in the new framework should solve all of those problems.

**Comment by AlecGamble** [comment]
Thank you very much lostgeek, that's perfect! yeah it's a really fun deck :). I look forward to busting out this jank a lot >:)
