### ISSUE TITLE
Itinerant Protesters causes disconnect

### ISSUE THREAD

**Issue by misterashtray** [mtgred/netrunner#4321]
Hello.

Everytime I play Itinerant Protesters the game appears to disconnect both users (leaving and rejoining doesn't allow anything to be played anymore and showing the contents of the Stack/R&D just shows the card backs).

There doesn't appear to be any correlation to what ID etc you are playing. This can be swiftly reproduced by starting a game, manually dragging the card from the stack into your grip and then playing it. The game "disconnects" as soon as you click the card (everything looks find, but cards/actions cannot be played, viewing your deck shows just card backs etc). I've tried this on two different machines and two different browsers (chrome and firefox) and the behaviour is the same

**Comment by NoahTheDuke** [comment]
Is fixed in #4315, but still needs to hit the site. Thanks for the report!
