### ISSUE TITLE
Slowdown (possibly) due to Superior Cyberwalls

### ISSUE THREAD

**Issue by qmsm** [mtgred/netrunner#433]
![slow](https://cloud.githubusercontent.com/assets/12899472/8874114/8a5adc02-3205-11e5-89a5-d6cb6f5775e4.jpg)

This was the situation at the end of the game I just played. I don't know exactly when the lag started but for quite a while it was almost unbearable. I speculated it might be something to do with the number of barriers and having two SCs scored.

I guess I could investigate further but it's not the easiest thing to test.

**Comment by nealterrell** [comment]
This is speculation on my part. I don't know what about Cyberwalls would cause this. Ice strengths are updated during very specific moments: ending a run, approaching an ice, rezzing an ice... that's really it. Cyberwalls adds a simple calculation during that process to give the +strength, and I don't see why that would cause server lag. Could you describe the lag a little?

**Comment by DominicKexel** [comment]
I also don't think it was because of the cyberwalls. I don't See the log window in the Screenshot, but if the card preview feature was active at the time, this could have been the source of the lag. I already provided a fix for that which reduces the need for memory.

**Comment by mtgred** [comment]
The card preview in the chat log has been deployed yesterday and might be the cause.

It has been removed today from the live server due to other issues (#427, #424). Can you try now and see if there is any difference in performance?

**Comment by qmsm** [comment]
I'm pretty sure this was caused by the card preview in chat log so I'm gonna close it.
