### ISSUE TITLE
Warroid Tracker doesn't allow runner to trash 2 cards

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#4333]
I played a couple games with it using Industrial Genomics, I noticed that after the runner loses the trace and selects the first trash it hangs and they are never given the choice to trash another, I have to use /close-prompt to continue the game.

**Comment by NoahTheDuke** [comment]
Do you have any more information? I can't recreate this.

**Comment by demoy** [comment]
Mhmm it hasn't work once (as in allowing the runner to trash more than 1 card) while I been playing it in IG  the only detail I see is the runners always trashes the Bio-Ethic it is guarding and I always boost to more money than they have.

**Comment by NoahTheDuke** [comment]
Okay, I’ll keep trying! Thanks for the feedback, I’ll see what I can figure out

**Comment by demoy** [comment]
I just realized I have only played Warriod Tracker from the corp perspective.. so far all I know the card works perfectly fine and runners just don't know when/how to select the second card. So I am going to close this issue, I am sorry for all the effort I made you put into solving this.

**Comment by NoahTheDuke** [comment]
No need to jump the gun my friend! As you can see in the linked PR, you were right and I just missed it. I found the bug and wrote a fix for it. Should be up with the next batch of fixes!
