### ISSUE TITLE
Reuse lets the runner know which cards are being trashed

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#434]
When the corp uses Reuse it states clearly in the runners log which cards are being trashed
Also, the reuse log entry doesn't name the card being used for the effect.
example: 
PlayerA plays Reuse.
uses to trash Fetal AI, The Future Perfect, Lockdown, Closed Accounts and gain 8 .

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.
