### ISSUE TITLE
Dirty Laundry playable after Peace In Our Time

### ISSUE THREAD

**Issue by Caknuckleguy** [mtgred/netrunner#4362]
Currently Dirty Laundry is allowed to be played after Peace In Our Time is played during the same turn. Per the rules this is not allowed (NCIGS 1.2.5) but Jnet allows the click to be spent, the credits to be used and then returns no further action. DL gets placed in the heap. 
This should be an action that reminds the runner PIOT has been played and not allow DL to be used.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look.
