### ISSUE TITLE
Daily Quest start of turn trigger can't be used before Blue Sun start of turn trigger

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#4366]
I been trying out Daily Quest in Blue Sun for the reoccurring value. But I noticed I have to manually add 3 credits before returning Daily Quest to HQ with Blue Sun because clicking Daily Quest in the start of turn window does nothing. Am I misunderstanding the rules and cheating by adding 3 credits? or is this a bug and I can gain 3 credits from it before returning it to HQ like with Adonis and Marilyn Campaign?

**Comment by NoahTheDuke** [comment]
Probably just missed that! I’ll see about adding it!

**Comment by NoahTheDuke** [comment]
Closed by #4387

**Comment by AndersRask** [comment]
This one is not entirely fixed. Or, it seems to be the same issue with Marilyn Campain: You cannot choose to get 2 c from MC before trashing it to BS

**Comment by NoahTheDuke** [comment]
@AndersRask What exactly happens?

**Comment by AndersRask** [comment]
@NoahTheDuke well, it was my opponent that said, that during the game fixed the Marilyn manually, so I asked him if it didn't allow for him to choose to do BS first. He said it didn't and I took his word for it, so didn't test myself
