### ISSUE TITLE
Game log doesn't display icebreaker strength boost correctly

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#4367]
![refractorbug](https://user-images.githubusercontent.com/44246400/62811339-32001500-baf9-11e9-90a7-f964937f1f40.jpg)
The game log isn't displaying the strength that icebreakers are being boosted by correctly. Screenshot shows a Refractor being boosted to 2 strength instead of 5, despite a stealth credit having been spent. I've also seen a Switchblade being boosted to 0.

**Comment by NoahTheDuke** [comment]
Thanks for the report! To be clear, this is just a game log issue, not an issue with underlying mechanics?

**Comment by manveruppd** [comment]
Sorry Noah, it's just the log. The screenshot actually made it clear, as
you could see that refractor was at 5 on re card, but I cropped too
aggressively and forgot to include that info! 😂

**Comment by NoahTheDuke** [comment]
I’m gonna close this cuz I suspect it’s been fixed but please let me know if it hasn’t.
