### ISSUE TITLE
:msg is broken when using a :choices.

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#437]
When using the :msg field in an operation (probably also other card types, don't know) and :choices is used to show a prompt, sometimes the player name and card name is missing.

Reuse says: `uses to trash 2 cards and gain 4[c].`

Celebrity Gift says: `uses to reveal Reuse, Power Shutdown and gain 4[c].` when not showing all cards, but works when used to show all cards in hand: `foo@example.com uses Celebrity Gift to reveal Reuse, Priority Requisition, Reuse, Reuse, Power Shutdown and gain 10[c].`

Power Shutdown works: `foo@example.com uses Power Shutdown to trash 0 cards from the top of R&D.`

**Comment by nealterrell** [comment]
Yes, same with Grail ice reveals. I believe it is specifically when you have to use the "done" button to finish the select instead of it finishing immediately; this is when there is a :max key on the select.

**Comment by DominicKexel** [comment]
I also have a related problem with implementing Paige Piper. I need to use an :event, and inside the :event a :prompt, but then the :effect does not get fired... :-(

**Comment by mtgred** [comment]
Thanks for reporting the issue. It should be fixed now.
