### ISSUE TITLE
Game Crash/Connection Issue and reconnection leads to face-down cards in hand

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#4374]
![image](https://user-images.githubusercontent.com/44735253/62843215-2ee65f80-bc86-11e9-83c2-3a407315b350.png)

During this game I had a connection issue and had to reconnect.  When I rejoined, the cards in my hand were face-down.  Mousing over the card showed "unimplemented".  Wasn't able to fix.
Clicking on a card caused it to move to my opponent's hand.

![image](https://user-images.githubusercontent.com/44735253/62843241-605f2b00-bc86-11e9-9a66-30b9788f90f1.png)

**Comment by NoahTheDuke** [comment]
Yeah this is a long standing bug. The best solution is to reload jnet, find the game in the lobby, and wait for your name to clear out of the old game before pressing the Join button.

**Comment by NBKelly** [comment]
I think this issue is too old to be reproducible. If it ever comes back, feel free to make another issue.
