### ISSUE TITLE
Inconsistency in the UI

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#4376]
![Screenshot from 2019-08-12 09-18-25](https://user-images.githubusercontent.com/1409906/62850165-61be4100-bce2-11e9-8801-b789e5fc0b29.png)
- The textbox should be at the bottom of the whole server. Possibly happens because of the root of a central being handled differently.

![Screenshot from 2019-08-12 09-19-10](https://user-images.githubusercontent.com/1409906/62850296-bc579d00-bce2-11e9-9388-d69eb1121494.png)
![Screenshot from 2019-08-12 09-19-22](https://user-images.githubusercontent.com/1409906/62850300-bd88ca00-bce2-11e9-8cfd-1b4d675c3a84.png)
- Zones should have the same font size as other areas.

**Comment by dkellner** [comment]
@NoahTheDuke I think this can be closed now.
