### ISSUE TITLE
Clicking Tenin Institute opens empty pop-up menu

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#4388]
Minor issue, I'm sure this might be included in a larger bug fix with pop-up windows but figured I would mention it.

Clicking on Tenin Institute to use its ability opens an empty pop-up window with a very thin button (I'm guessing it looks like that because it's a button with no text).  Then clicking on that allows you to place an advancement counter on a card.  It would be easier to just have clicking on Tenin allow you to place the counter, as it used to be, since that would be the only thing you would think to click on your identity for, especially after being prompted by the game.

**Comment by NoahTheDuke** [comment]
Thanks for the report, this “feature” is being reverted!
