### ISSUE TITLE
Peeping Tom broken

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#4389]
![peeping](https://user-images.githubusercontent.com/44246400/62971392-a395d700-be09-11e9-92fb-c462017eb3b4.jpg)
Using the "Name a card type...." ability on Peeping Tom freezes the game. It doesn't ask you for a type or reveal the grip, chat still works but both corp and runner are unable to use any card abilities, corp is unable to click "no more actions", and even manual commands like "counter x" or "credit x" do nothing. The only way to get out of it is to /undo-turn. We tried it repeatedly and each time Peeping Tom was rezzed it completely froze the game.

**Comment by NoahTheDuke** [comment]
Yikes, thanks for the report! A fix should be up soon!
