### ISSUE TITLE
Dirty Laundry does not pay 5c with SecTesting

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4390]
After doing a SecTesting run on archives with Dirty Laundry, the runner did not get paid 5c.

See attached!
![image](https://user-images.githubusercontent.com/1651150/62976597-3c821d80-be1d-11e9-994c-133eb02f5f4f.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Damn, this is all about `:run-event` overwriting. I'm gonna have to figure something out about these damn `:run-events` lol

**Comment by metamatik** [comment]
Just FYI, this happened to me as well tonight :)

**Comment by NoahTheDuke** [comment]
Oh yeah this is broken for everyone right now

**Comment by demoy** [comment]
High-Stakes Job doesn't work with Security Testing either
