### ISSUE TITLE
After scoring agenda against Leela, corp gets another turn

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4391]
This is a bit weird.
After spending my turn scoring an SSL against Leela, and after she bounced my IP Block from HQ i got the "mandatory draw" instead of End Turn (see attached).
As i did not have an "end turn" command (that i know of) I had to click "mandatory draw" which first prompted SSL money and then gave me a card.
I then had to put card back on top and shuffle, so that runner could take his turn.
Not sure why this happened. Note that Thimblerig was also installed.
![image](https://user-images.githubusercontent.com/1651150/62977056-48baaa80-be1e-11e9-971e-3480bd40f626.png)

**Comment by NoahTheDuke** [comment]
Lmao what the hell. Thanks for the report! I’ll check it out
