### ISSUE TITLE
Recent Interface Change

### ISSUE THREAD

**Issue by Zanzibon** [mtgred/netrunner#4398]
Recent interface changes have caused a few issues
-Conspiracy/Bin breakers don't seem to pay their costs when used
-Some combination of clicking with newly rezzed ICE allows either player to derez the ice accidentally
-Ran into problems with "on access" ICE (sapper etc) locking up the interface
-Problems manually trashing cards when the new ICE interface is open

As general feedback the "completely break" option on other breakers is really nice and speeds up play. On the other hand the ICE menu popping up feels like it gets in the way a lot and leads to a lot of clicking around. I kind of feel bombarded by menus when a run is going on

Appreciate all the work you guys do

**Comment by NoahTheDuke** [comment]
Thanks for the report! We’re working on the next release and hope to have all these fixed soon

**Comment by NoahTheDuke** [comment]
In the future, can you split up your comments into multiple issues? That way I can close each individual issue as I tackle it.
