### ISSUE TITLE
Subroutine UI doesn't show added sub from a current on News Hound

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4399]
With a current out, News Hound is not showing the added "End the run" subroutine.

![Screenshot 2019-08-14 at 8 41 47 PM](https://user-images.githubusercontent.com/396562/63071123-9b11cf00-bee3-11e9-99a4-961d4c41aa6a.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
