### ISSUE TITLE
Gaining bad publicity mid run grants run credits

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#440]
I don't have reproducible steps, but saw this twice yesterday: rezzing Grim during a run gave the Runner a runcredit for that run, when you aren't supposed to get the credit until the next run (to the best of my knowledge). This might only happen for the outermost ice on a server, as it did not happen to the second of two Grim I rezzed in the run. 
Paging @laganojunior !

**Comment by JoelCFC25** [comment]
You're right. Bad publicity credits are gained only once at the outset of the run--any new bad publicity gained mid-run doesn't become a spendable credit until the next run is made.

**Comment by laganojunior** [comment]
Huh, this is indeed a bug. I'll have to check when the run is technically "started" in the back-end because I can't imagine that the bad pub credits are being added anywhere else.

**Comment by laganojunior** [comment]
I can't seem to reproduce this bug. I'm testing locally with a corp deck with just 3 grims. It doesn't seem to add the BP credits if I rez the outermost grim during the run, even if if I start stacking them.
