### ISSUE TITLE
Runner clicking on a subroutine to resolve, derezzes the ice

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4400]
I saw this with an Afshar on HQ.   As the runner, i pelangi'd it into a barrier, broke a sub with Lady and then went to click the sub i wanted to let fire (runner loses 2 credits) and it derezzed the ice.

**Comment by NoahTheDuke** [comment]
Yeah I’ve heard this a bunch now. I wonder how it’s happening! Thanks for the report
