### ISSUE TITLE
Ika menu grows with more interactions

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4401]
I noticed Ika's menu growing and growing as i interacted with ice during a game.

![Screenshot 2019-08-14 at 11 07 15 PM - Edited](https://user-images.githubusercontent.com/396562/63073418-52abde80-beee-11e9-8e18-e732aa8066d1.png)

I am pretty sure it kept growing, but it was definitely *way* more than it needed to be.

**Comment by NoahTheDuke** [comment]
Lmaoooo yeah that’s an issue! Thanks for the report!
