### ISSUE TITLE
Icebreaker menu retained some part of first ice encounter, not current ice enounter

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4402]
I used Pelangi to make Hortum a Barrier and used Lady to break it.

On a subsequent run on the following turn, while accessing Afshar on HQ, Lady shows info about interacting with Hortum instead of something for Afshar (after using Pelangi again).

![Screenshot 2019-08-14 at 10 54 15 PM - Edited](https://user-images.githubusercontent.com/396562/63073503-b7673900-beee-11e9-8b6a-fe2211f5b67e.png)

**Comment by NoahTheDuke** [comment]
Yeah it’s the same issue as the growing abilities one. Thanks for letting me know!
