### ISSUE TITLE
Match & Break item on subroutine doesn't have the right cost listed

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4403]
Ika hosted on Architect shows $2 to Match & Break.  That should be $3.

![Screenshot 2019-08-14 at 11 05 51 PM - Edited](https://user-images.githubusercontent.com/396562/63073571-04e3a600-beef-11e9-9f99-25b50043afca.png)

Clicking that does spend the right amount of credits, though.

**Comment by NoahTheDuke** [comment]
Good catch!
