### ISSUE TITLE
Predictive algorithm doesn't prevent stealing

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#441]
Title. I was at 5 creds and was able to steal NAPD with predictive algorithm active.

**Comment by JoelCFC25** [comment]
Other than the per-card costs on Fetal AI and NAPD Contract, steal costs in general are a yet-to-be-implemented feature:   https://github.com/mtgred/netrunner/wiki/Jinteki.net-Guide#gameplay-limitations

It's on the radar but there is no timeline. See some discussion in #260.

**Comment by nealterrell** [comment]
This is now implemented!

**Comment by mtgred** [comment]
It's deployed now.
