### ISSUE TITLE
IP Block does not give the prompt to fire the trace when clicked on

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4411]
Corp rezzes IP Block. Click on the ice to select fire trace 3 but it doesn't trigger this in chat for the corp to respond to.

**Comment by NoahTheDuke** [comment]
What happens when you click on it? There should be 1 ability and 2 subroutines in the menu

**Comment by tolaasin** [comment]
The menu appears, and can be clicked on to say 'fire the trace'. But nothing then happened. The corp did not get a prompt to fire the trace. I tried twice, no deal.

**Comment by NoahTheDuke** [comment]
Thank you! I’ll take a look!

**Comment by tolaasin** [comment]
Just saw exactly the same thing with Aiki. Use CyCy to break two subs. Click on the psi sub to say 'fire it' but corp gets no prompt and nothing in the chat.

**Comment by NoahTheDuke** [comment]
As I mentioned on slack (but for the public record here), this is actually due to changes to how the sub "buttons" work now. They don't say "fire this specific sub" anymore. I'll see about changing the buttons to look different to indicate this change.
