### ISSUE TITLE
Cyber-Cypher preventing interaction after use when installed by Assimilator

### ISSUE THREAD

**Issue by KiYellow** [mtgred/netrunner#4412]
(For all 3 of us Apex players...)

When Cyber-Cipher is installed face-down then flipped by Assimilator attempted to Break a Subroutine or Boost the program prevents the user from interacting with the UI; (Prompts, modifying credit total, etc).

This might be related to the check for what server Cyber-Cipher is targetting returning a null value.

Undoing the click does clear the error and allow the game to proceed as a workaround.

**Comment by NoahTheDuke** [comment]
Good catch!!
