### ISSUE TITLE
Tycoon no longer working automatically

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#4423]

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Do you have any other details or information?

**Comment by groenkaaf** [comment]
hmhm. my opponent was the one running tycoon so i'm not certain, but it happened in two different games against different people. i'll see if i can reproduce.

**Comment by NoahTheDuke** [comment]
Cool, thanks.

**Comment by lostgeek** [comment]
I managed to reproduce the bug. Here's the board state:
![image](https://user-images.githubusercontent.com/1409906/63223088-a1889b00-c1b0-11e9-919d-770a1b0afb0b.png)
