### ISSUE TITLE
Sapper nolonger works when accessed

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#4428]
When the runner accesses Sapper the UI froze, /close-prompt by both players does nothing. We had to undo-click and manual the trashing and breaking of Sapper. This occur both times 2 different Sapper cards was access in the same match.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by demoy** [comment]
Question I noticed today that the Chrysalis gave the same problem, does this fix cover it too?

**Comment by NoahTheDuke** [comment]
Oooh shit, no, it doesn't. That'll hit the next patch in a couple days!

**Comment by demoy** [comment]
Thank you.
