### ISSUE TITLE
jackson howard remove ability not working

### ISSUE THREAD

**Issue by luclabelleis** [mtgred/netrunner#443]
Using the Jackson Howard's "Remove Jackson Howard from the game: Shuffle up to 3 cards from Archives to R&D." does not work. Using it removes Jackson Howard from the game, but doesn't ever prompt the player to or shuffle 3 cards from archives back into R&D.

**Comment by JoelCFC25** [comment]
It never has offered such a prompt. You're meant to manually open up Archives, drag the 3 cards you want onto R&D, then click R&D and reshuffle.

**Comment by queueseven** [comment]
I thought about implementing Jackson Howard's ability, but the code would not be that easy and you basically would just save 2 clicks. In the end, I don't think it's worth it.
