### ISSUE TITLE
Corp UI Suggestion: Trash option beside Derez is on ICE

### ISSUE THREAD

**Issue by demoy** [mtgred/netrunner#4431]
Having to drag ICE to trash it on touchscreens and touchpads is errorprone and awkward (dependent on the quality of the touch device on both these points). Could you add a trash option to install corps card above or below the derez option that's already there?

I can't remember the last time I needed to derez something while with cards like Cutlery events and ICE overwriting almost every games I have to trash ice.

**Comment by NoahTheDuke** [comment]
That’s a great point! I’ll add it to the list!
