### ISSUE TITLE
Laamb breaking subs did not trigger prompts with surfer

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4433]
Run a remote, paint anansi with Laamb. Surf in with surfer. There is no menu prompt to match and break, the strength can be boosted manually but the 'break subs' prompt does not trigger an in-game effect and nothing appears in chat.

This is the console prompt:

app10.js?v=6:1397 Warning: Every element in a seq should have a unique :key: ([FZ {:faction "Shaper", :format {:standard "restricted", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "restricted", :classic "legal"}, :rotated false, :pump {}, :cycle_code "kitara", :agendapoints nil, :init nil, :runner-abilities [], :zone ["onhost"], :advancementcost nil, :cid 106691, :art nil, :type "Program", :abilities [{:label "2 [Credits]: break any number of Barrier subroutines", :break 0, :breaks "Barrier", :break-cost ["credit" 2]} {:label "3 [Credits]: Add 6 strength", :msg "game.core$strength_pump$fn__12535@5a069edd", :cost ["credit" 3], :pump 6} {:label "2 [Credits]: Make currently encountered ice gain Barrier", :once "per-turn", :cost ["credit" 2], :msg "game.cards.programs$give_ice_subtype$fn__1401@8731195"}], :image_url "http://www.cardgamedb.com/forums/uploads/an/med_ADN54_86.png", :title "Laamb", :uniqueness false, :host {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "legal", :classic "legal"}, :rotated false, :cycle_code "lunar", :agendapoints nil, :init nil, :runner-abilities [], :zone ["rig" "program"], :advancementcost nil, :cid 106689, :new true, :art nil, :type "Program", :abilities [{:label "Install a program on Leprechaun"} {:label "Host an installed program on Leprechaun", :prompt "Choose an installed program to host on Leprechaun", :choices {:req "game.cards.programs$fn__6326@4e3c9b42"}, :msg "game.cards.programs$fn__6340@641db6f7"}], :image_url "https://netrunnerdb.com/card_image/06019.png", :title "Leprechaun", :uniqueness false, :host nil, :strength 0, :baselink nil, :corp-abilities [], :normalizedtitle "leprechaun", :code "06019", :side "Runner", :cost 2, :subroutines nil, :quantity 3, :installed "this-turn", :deck-limit 3, :memoryunits 1, :implementation "full", :trash nil, :set_code "up", :previous-versions nil, :subtype "Daemon", :previous-zone ["discard"], :minimumdecksize nil}, :strength 2, :baselink nil, :corp-abilities [], :normalizedtitle "laamb", :code "21086", :side "Runner", :current-strength 2, :facedown nil, :cost 4, :hosted [], :subroutines nil, :quantity 3, :installed true, :deck-limit 3, :memoryunits 2, :implementation "full", :trash nil, :set_code "win", :previous-versions nil, :subtype "Icebreaker - Fracter", :previous-zone ["rig" "program"], :minimumdecksize nil} nil] [FZ {:faction "Anarch", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "rotated", :classic "legal"}, :rotated false, :cycle_code "sansan", :agendapoints nil, :init nil, :runner-abilities [], :zone ["onhost"], :advancementcost nil, :cid 106699, :art nil, :type "Program", :abilities [{:cost ["credit" 2], :msg "swap a piece of Barrier ICE", :label "2 [Credits]: Swap the Barrier ICE currently being encountered with a piece of ICE directly before or after it", :async true}], :image_url "http://www.cardgamedb.com/forums/uploads/an/med_ADN28_102.png", :title "Surfer", :uniqueness false, :host {:faction "Shaper", :format {:standard "legal", :eternal "legal", :core-experience "rotated", :snapshot "legal", :snapshot-plus "legal", :socr "legal", :classic "legal"}, :special {:hosted-programs [106691]}, :rotated false, :cycle_code "lunar", :agendapoints nil, :init nil, :runner-abilities [], :zone ["rig" "program"], :advancementcost nil, :cid 106689, :art nil, :type "Program", :abilities [{:label "Install a program on Leprechaun"} {:label "Host an installed program on Leprechaun", :prompt "Choose an installed program to host on Leprechaun", :choices {:req "game.cards.programs$fn__6326@4e3c9b42"}, :msg "game.cards.programs$fn__6340@641db6f7"}], :image_url "https://netrunnerdb.com/card_image/06019.png", :title "Leprechaun", :uniqueness false, :host nil, :strength 0, :baselink nil, :corp-abilities [], :normalizedtitle "leprechaun", :code "06019", :side "Runner", :cost 2, :subroutines nil, :quantity 3, :installed true, :deck-limit 3, :memoryunits 1, :implementation "full", :trash nil, :set_code "up", :previous-versions nil, :subtype "Daemon", :previous-zone ["discard"], :minimumdecksize nil}, :strength 0, :baselink nil, :corp-abilities [], :normalizedtitle "surfer", :code "08102", :side "Runner", :facedown nil, :cost 2, :hosted [], :subroutines nil, :quantity 3, :installed true, :deck-limit 3, :memoryunits 1, :implementation "full", :trash nil, :set_code "uot", :previous-versions nil, :subtype nil, :previous-zone ["hand"], :minimumdecksize nil} nil])
 (in reagent10 > gameboard >  >  > b_ >  >  >  >  > FZ)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look!
