### ISSUE TITLE
Rezzing Tithonium with the alternative Rez cost broke the game

### ISSUE THREAD

**Issue by tefering** [mtgred/netrunner#4439]
When I tried to rez Tithonium with the alternative cost and pressed "Yes" in the prompt window (see the attached picture), the game broke down and I could not do anything from that point.

![Pic 2](https://user-images.githubusercontent.com/16436783/63342450-7eafdf80-c386-11e9-92b4-d76133773e67.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
