### ISSUE TITLE
Game Start time isn't accurate

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#4449]
The Game Start time doesn't seem to report the game start time, but rather the time you joined the game. So if you are a spectator, the time will just be whenever you joined this game instead of when the game you're viewing started. 

The phrase "Game start" is not what I associate with "the time you joined the game". If it's intended to just be when you joined the game, I'd recommend changing that label. Otherwise I think this is a bug 😄 

#### Here's when I joined some game at 1:49PM: 
<img width="842" alt="Screen Shot 2019-08-22 at 1 50 47 PM" src="https://user-images.githubusercontent.com/2737888/63549053-7c639780-c4e4-11e9-9823-a6839fee6f82.png">

#### Here's when I joined the same game 5 minutes later (1:54PM):
<img width="842" alt="Screen Shot 2019-08-22 at 1 54 54 PM" src="https://user-images.githubusercontent.com/2737888/63549077-8e453a80-c4e4-11e9-84ac-b747635127de.png">

**Comment by NoahTheDuke** [comment]
Lmao it was the simplest implementation possible so we went with it. I tried to get a better one working but couldn’t quite figure it out. I’ll try again!

**Comment by francescopellegrini** [comment]
Hi, today I noticed that the game start timer updates every few seconds to reflect the current time, definitely not the intended behavior..

**Comment by francescopellegrini** [comment]
Did #5542 fix this?

**Comment by NoahTheDuke** [comment]
Looks like! Good catch.
