### ISSUE TITLE
Edge of World doesn't deal the correct amount of brain damage

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#445]
When the Runner accesses Edge of World, they usually trash it before the ability is triggered, so it no longer has any ICE protecting it so deals no brain damage (I'm unsure whether it deals brain damage equal to the number of pieces of ICE on Archives or just zero damage, as in both cases Archives has been unprotected). Maybe the Corp should get a chance to trigger any on-access effects before the Runner can trash?

**Comment by DominicKexel** [comment]
there's currently no way to stop the game for one side to wait for a decission from the other.

**Comment by nealterrell** [comment]
This is basically the same problem as #423.

**Comment by DominicKexel** [comment]
We already have the `"Waiting for Corp's actions"` message during a run; maybe a similiar message should be shown when there's a `prompt` for the other side. I'll take a look at this if I find the time and no one else wants to try it.

**Comment by nealterrell** [comment]
@queueseven the prophet strikes again! I have implemented this fix in #1059.
