### ISSUE TITLE
News Hound triggers a psi game when a current is played

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4452]
wu v Palana with cerebral static. Whenever News hound  is rezzed or a current played/lost eg on stealing, a psi game was triggered.

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Do you have any other information or steps to reproduce?

**Comment by tolaasin** [comment]
Alas, no - was a single instance in a game.

**Comment by francescopellegrini** [comment]
Might as well close this.
