### ISSUE TITLE
Bazaar and Replicator leaves open prompts

### ISSUE THREAD

**Issue by tucker87** [mtgred/netrunner#4456]
Replication: 
- Bazaar on Board. 
- 3x Replicators in Hand
- Install all of them via the prompts

Result: 
Corp is stuck with multiple "Waiting for runner to resolve [runner install/pre-install] triggers"

If you add _In the Groove_ to the mix you also get [pre-runner-draw] trigger messages.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
