### ISSUE TITLE
Cyber-Cypher Bugged payments

### ISSUE THREAD

**Issue by dj88c** [mtgred/netrunner#4458]
When you use the top paid ability on Cyber-Cypher to pump and break, the game pays the pump cost separately and then pays that same amount again as part of the full pump and break cost. So for example, if you use the top paid ability to fully break a piece of ICE like Tollbooth, it will pay 1 to boost strength to 5 and then will pay 2 credits to boost strength to 5 and break 1 subroutine.

Issue is it needs to stop spending the extra boost credit(s) ahead of boosting + breaking.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
