### ISSUE TITLE
Sting! doesn't seem quite right

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4460]
Sting! may have two issues. 

Firstly, when I stole it, it did 2 damage, as it should have, but then it did another 2 damage for no reason. I've only tried this once, but it was definitely wrong.

The second one I suspect is wrong but not 100% sure. When I accessed Sting!, it gave me the option to decline stealing it as though it was an additional cost, but I didn't think you could decline Sting! It isn't worded like an additional cost. I think it should be an automatic steal, and do the damage automatically, but I could be wrong.

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report! Both sound like bugs to me!

**Comment by NoahTheDuke** [comment]
Next time it happens, can you post screenshots of either situation? They help a lot

**Comment by Jelley07** [comment]
Damn, I forgot :( sorry. I'll see if I can!

**Comment by Jelley07** [comment]
Okay, I'm really embarrassed. I just went to see if I could repeat it and I can't. It works fine. I've tried recreating the original conditions and... there may have been a screw up with Ben Musashi? And because it was a long thing and the game crashed and I reconnected during the original incident, I forgot I'd trashed the Musashi. I'm really sorry to waste your time :(

**Comment by NoahTheDuke** [comment]
I appreciate the effort to post the issue! No worries about wasting time, this is al part of the process.
