### ISSUE TITLE
Superfluous Brahman prompts

### ISSUE THREAD

**Issue by giles-davis** [mtgred/netrunner#4461]
Hi team,

Built a new Brahman Hayley list, due to it being the objectively best breaker in all of NR. Now whenever any encounter with any ice ends I'm getting the 'move a non-virus program to the the to of the stack.

This is occurring even when Brahman wasn't used during the the run at all.

Thanks for all your ongoing work Noah (and the rest of the team, you're all amazing and I need to setup a recurring paypal donation as my one off donations are way too few and far between!

![brahman](https://user-images.githubusercontent.com/17352285/63643798-50caf200-c71c-11e9-81a7-332f1b7ef404.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
The solution looks to be uninstall Brahman and reinstall it. Seems that the flag to show the prompt is only reset when you make a decision, so if for whatever reason you use it and then /close-prompt, it’ll bug you every future usage until you follow through or “reset” it by uninstalling and reinstalling it.
