### ISSUE TITLE
ICE Strength is covering art

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#4462]
If the ICE strength tokens are going to be a permanent feature on the game board, then could they please cover up text instead of card art? That is, put them on the left side of the card for the corp, and the right side of the card for runner. 

The art is the primary way of recognizing a card at-a-glance when you're observing the board state, and covering the art up impedes that. The other tokens generally aren't permanent fixtures to ICE and/or won't be on a card in every situation, but the strength indicator now is.

**Comment by NoahTheDuke** [comment]
This is a good point! Thanks, we’ll take a look

**Comment by LessRekkless** [comment]
Did you make a decision against doing this?

**Comment by NoahTheDuke** [comment]
No one has had time or desire to work on it yet.
