### ISSUE TITLE
Corp can click on liberated to give Runner 4c

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4467]
Weird situation where if Corp clicks on Liberated Account it gives Corp 4c ...

cableCarnage
let me try again for reproducability
tolaasin spends  to use Liberated Account to gain 4 .
!cableCarnage uses a command: /undo-click
cableCarnage
cableCarnage
yep

**Comment by Kubik161** [comment]
This issue should be closed, I have just retested this and couldn't reproduce.
