### ISSUE TITLE
Card implementation list suggestion

### ISSUE THREAD

**Issue by justinliew** [mtgred/netrunner#447]
Just a thought: would it make sense to add a column to the card list that describes the state of unimplemented or partially implemented cards? For example knowing that Stimhack granted 9 credits but never removed them post run might be a good quick description that might help someone hone in on what needs to be looked at. Currently I'm looking at partial cards but then have to grok the code to figure out what's missing.

**Comment by justinliew** [comment]
Another option might be to create git issues for each card that's Partial, and then link to the issues from the spreadsheet. Might make it easier to know who's looking at each card, but would incur the overhead of entering all the (~116) issues.

**Comment by mtgred** [comment]
The last column contains remarks about the cards. For some partially implemented cards, it is mentioned what's missing. But because I was the only dev and everything is in my head, I didn't bother writing it systematically. I will try to go though to the partially implemented cards and update them with remarks.

**Comment by justinliew** [comment]
Cool, thanks. I didn't notice that some of the cards had comments, as I got unlucky and looked at a few that didn't happen to have them :)

**Comment by JoelCFC25** [comment]
One idea would be to migrate the content to Google Sheets and allow editing to the group.

**Comment by DominicKexel** [comment]
How about a wiki page? Then everything is in one place and you could link to issues etc.

**Comment by JoelCFC25** [comment]
I kind of like the ability to filter and sort in a spreadsheet format--can that be done on the wiki?

**Comment by mtgred** [comment]
I like the convenience of being able to code and update the spreadsheet with an internet connection.

But I can share the write access to the file on Dropbox if you want.

**Comment by nealterrell** [comment]
I also never realized there is another column! Here is a list of cards are Done but aren't marked as such in the document, for whoever will be updating it:

Aggressive Secretary
Scrubbed
Refractor (partial, no stealth check)
Helium-3 Deposit
Traffic Jam
