### ISSUE TITLE
Create a new landing page for entry to jnet

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4470]
At the moment, the landing page for jinteki.net is the chat page. I would like to propose that we work to create a new landing page which is more useful to new people/players, including links to nisei, for example. and explaining the basics of the site.

It might also contain a basic set of guidelines for behaviour on site. The Chat page should still exist but be moved to an alternate tab.

**Comment by tolaasin** [comment]
Pointing people to the text shortcuts, and so on, on the front page would be nice. Also highlighting potential to donate.

**Comment by NBKelly** [comment]
Closed as completed via https://github.com/mtgred/netrunner/pull/7578
