### ISSUE TITLE
Divide and Conquer accessing zero cards on succesful run

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4473]
Divide and Conquer accessed zero cards on successful run.
Tried undo-click and rerun and undo-turn and rerun to no effect
![dc](https://user-images.githubusercontent.com/13881796/63980778-7e18f680-cab4-11e9-9267-ff893fa03564.png)
I note this worked yesterday.

**Comment by ZomBagus** [comment]
yesterday i was playing quetzal vs sol, today is quetzal vs acme

**Comment by NoahTheDuke** [comment]
Thanks for the report and screenshot! Very helpful
