### ISSUE TITLE
Hosted datasucker doesn't get tokens

### ISSUE THREAD

**Issue by log0s** [mtgred/netrunner#448]
Ran into this in a recent game, a Datasucker I had hosted on Scheherazade wasn't getting virus counters at the end of a successful run on a central. This particular Datasucker had been installed and then hosted on Scheherazade using its ability (so not hosted directly from hand). Another interesting thing to note is that it had one counter on it before it was hosted (basically had just messed up hosting it from hand so had to host later) and when I clicked on it mid-run it used a counter, said in chat that the counter was used to give the ice -1 strength, but didn't actually lower the ice's strength in the GUI. Let me know if you need any more info/clarification.

**Comment by JoelCFC25** [comment]
See #382.

**Comment by nealterrell** [comment]
This has been fixed!
