### ISSUE TITLE
Corp can click liberated account to lose :click: and gain 4$ of it

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4480]
This seems to be an extension of a previous issue where the corp could pay to pump up Blorc or spend sucker counters. However as this is actively gaining the corp credits it seems more abusable.

**Comment by BlueHairedHackerCatgirl** [comment]
I see it a similar issue was reported here: https://github.com/mtgred/netrunner/issues/4467

But now the CORP is gaining the money, not the runner when it's clicked.

**Comment by Kubik161** [comment]
@NoahTheDuke This issue should be closed, I have just retested this and couldn't reproduce.
