### ISSUE TITLE
419's ability should not expose when using Building Blocks

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#4485]
Currently, when playing Building Blocks vs 419 they can use their ability to expose the ice (can be important for getting an Aumakua counter) but, according to the UFAQ, this should use up their trigger without exposing the ice.

> If the first time the Corp installs a card in a turn is with Building Blocks, does 419 trigger?

> Yes, but the barrier is both installed and rezzed simultaneously, thus rendering the ice ineligible to be exposed. Because the barrier cannot be exposed, the Corp can decline to pay 1 and 419's ability will simply do nothing.

**Comment by NoahTheDuke** [comment]
That's a cool interaction. Thanks for the report!
