### ISSUE TITLE
Errand Boy - only 2 subs

### ISSUE THREAD

**Issue by spagcore** [mtgred/netrunner#4488]
Errand Boy only has two subs listed, and if you select 'Let unbroken subs fire', it just draws one card, and gains one credit.

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by AndersRask** [comment]
![image](https://user-images.githubusercontent.com/1651150/65393556-77636380-dd82-11e9-96aa-54049ac8209d.png)
I can confirm. When Bukhgalter try and break it, it say "all 2 subs on Errand Boy"
