### ISSUE TITLE
Corp optional triggered ID abilities are blank when clicked

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#4489]
***Blue Sun*** and ***Tennin Institute*** each have an ability that trigger at the beginning of the turn. To activate each ability, the ID must be manually clicked *during* the beginning of the turn step after clicking Start Turn.  This is what the runner sees for these three IDS:
![image](https://user-images.githubusercontent.com/34615525/64496216-7a356300-d270-11e9-88ec-fb3c0f19e700.png)
The abilities themselves work just fine.

1. could these gain auto-resolve functionality (always/ask/never) when Mandatory Draw is clicked?
2. More importantly, could these get actual text in the pop-up so that it's not so difficult to click?

***Sync*** and ***AgInfusion*** also have a blank ability pop-up:
![image](https://user-images.githubusercontent.com/34615525/64496269-28d9a380-d271-11e9-8b3c-2de0e5f0a0b3.png)

I tested all of the IDs, and I'm pretty sure that these 4 are the only ones that have this issue.

**Comment by NoahTheDuke** [comment]
Damn, thank you for checking all of the IDs! That's very kind of you! These can definitely be updated.
