### ISSUE TITLE
The Supplier & Off Campus

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#449]
Strange bug where I had a daily casts hosted on the supplier and it kept cloning the daily as I took them off it was only when I realized I could see 4 daily casts that I realized something was wrong. I am guessing it was a bug with me having the supplier hosted on off campus apartment and then hosting daily casts on the supplier. If not then i am unsure why it happened but it was doing it with my RDI that was also on the supplier.

**Comment by nealterrell** [comment]
I submitted a fix for this in #648.

**Comment by JoelCFC25** [comment]
Deployed!
