### ISSUE TITLE
Uprising Grids don't trigger at the correct step

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#4490]
***La Costa Grid*** and ***Cayambe Grid*** only trigger when the runner clicks Mandatory Draw. There is no ability pop-up that the runner can use to order triggers after the Start Turn step.  

For example, this is necessary for ***API-S Keeper Isabel*** to be able to remove a counter that either of these two Grids can create.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll add the manual ability to both!
