### ISSUE TITLE
Daily Quest has Mandatory Draw pop-up

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#4495]
For some reason, while ***Daily Quest*** is rezzed,  it forces the Corp to click through the Mandatory Draw step, even though there's zero choice to be made by the Corp at this point.  It should function exactly like ***PAD Campaign***, assuming the runner didn't make a successful run on the server.
![image](https://user-images.githubusercontent.com/34615525/64914574-fb826f00-d722-11e9-9cc6-92f7efb0f18f.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
On second thought, we're not gonna fix this because we don't have a method of determining when is or is not a good idea to pause before Mandatory Draw, and Daily Quest needs to pause because of the interaction with cards like Blue Sun (as seen in #4366).

**Comment by LessRekkless** [comment]
How come this is an issue with **Daily Quest**, but not **Adonis Campaign** etc?

**Comment by NoahTheDuke** [comment]
Hmm, good point. Maybe having added the clickable ability to DQ is good enough? I'll reopen and fix this come the next update.
