### ISSUE TITLE
Old Hollywood Grid staying active after Apoc

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4501]
Corp had 3 unique agendas in Archives, protected by Old Hollywood Grid. After landing an apoc was still unable to steal the agendas. Logs showed that Old Hollywood Grid was still preventing steal.

5 click turn
1: Run HQ
2: Run R&D
3: Run archives with faceup Hollywood
4: Apoc
5: Run archives, still unable to steal agendas.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
