### ISSUE TITLE
Tour Guide ignores subs for assets rezzed after you rez the ice

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4505]
Rezzed a tour guide on approach then an asset. Bukhgalter said 5 to fully break, but there were 6 assets. Undo-click and run again rezzing the asset first and Bukhgalter said 6 to fully break..

**Comment by ZomBagus** [comment]
Further information: Have seen this again and noted that this only affects the "fully break" prompt. For example the fully break prompt shows 3 to fully break with 4 assets. However if you click the "break subroutine" prompt it shows 4 "end the run" buttons in the bottom of page dialog.

**Comment by NoahTheDuke** [comment]
A-ha! That's it then. Thank you! I'll see what I can do.
