### ISSUE TITLE
Degree mill and CVS in archives, CVS didnt fire

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4515]
Accessed archives containing CVS and Degree Mill. Stole Degree Mill and CVS did not fire.
CVS had fired on earlier access. (Had turtle with 2 virus counters so certain it didn't fire)

**Comment by NoahTheDuke** [comment]
Thank you for the report!

**Comment by NoahTheDuke** [comment]
I don't know what could have caused this because I can't reproduce the effect. Do you have any further details?

**Comment by ZomBagus** [comment]
Degree Mill had been stargated so was face up. Will capture if it happens again.
