### ISSUE TITLE
Sandstone doesn't gain virus counters after encounters

### ISSUE THREAD

**Issue by doorisajar** [mtgred/netrunner#4517]
I fully broke multiple Sandstones with Corroder during a game and it never gained any virus counters. Maybe related to the changes around breaking ice? If I encounter this again, I'll see if I can share additional info.

**Comment by NoahTheDuke** [comment]
Thanks for the report! The virus gaining is currently manual, but it looks like there's no implementation note telling the Corp to add them manually.
