### ISSUE TITLE
Runner is considered to be trashing currents by agenda steal/current overwrite

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#4529]
Game was Leela vs IG, there was a Hostile Infrastructure rezzed and Guru Davinder on the board. 

Leela overwrites IG current with Corporate Grant, Hostile Infrastructure deals 1 net damage to Leela (Jnet considered Leela to have "trashed" the IG current). 

Later, Leela steals an agenda, trashing an IG current - Hostile Infrastructure again deals 1 net damage to Leela.

**Comment by NoahTheDuke** [comment]
Damn, okay, so here's the use-case I didn't realize. Thanks for the report, I'll see about getting a fix up!

**Comment by rongydoge** [comment]
Awesome, thanks!
