### ISSUE TITLE
Accelerated Diagnostics - Cheaters favorite

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#453]
Hey,

While I know that there might be a lot of ways to cheat in the game, I think that it could be avoided by forcing the player to trash the non-operation and the unplayed ones. 

I know that you can do the same in the original game as well.

Just saying :)

**Comment by nealterrell** [comment]
This card is not implemented at all, unfortunately.

**Comment by JoelCFC25** [comment]
Accelerated Diagnostics is now partially implemented. The Corp player still needs to know the finer points of using this card when any of the played operations result in drawing cards or shuffles of R&D--in these cases, move remaining cards back onto R&D manually (and reshuffle if needed).
