### ISSUE TITLE
Aumakua Reveals Subroutines On Unrezzed Ice

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#4530]
Maxx against Palana, Aumakua on the board with Yusuf, runs a remote server with 1 piece of unrezzed ice and no cards installed in it. 

Runner clicks on Aumakua, clicks break subroutine. Menu comes up on the left with a list of the subroutines (in this case, "Runner cannot make another run this turn" from Excalibur. Excalibur was indeed the ice installed protecting the serve.r Ice was unrezzed the whole time. 

Thanks again for all the great work that you do!

**Comment by rongydoge** [comment]
New wrinkle: Aumakua has to have enough virus counters to break the ice in question. I tried with turtle at 0 strength and it didn't do anything, turtle at 3 str brought up the prompt: 

![image](https://user-images.githubusercontent.com/45369203/65823883-aec38b80-e22c-11e9-8020-fd7b845df0ca.png)

Thanks again!

**Comment by NoahTheDuke** [comment]
Nice catch! Thank you, I’ll take a look.
