### ISSUE TITLE
Always Have a Backup Plan has too good a backup plan.

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4538]
Hey! 

Always Have a Backup Plan fires a prompt to ask if you want to make a second run even if the first run is successful. The 'if unsuccessful' text is a clause on the card I always forget, and having JNet allow a second run after a successful run reinforces this and could cause problems in physical play. 

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!
