### ISSUE TITLE
Trebuchet does not prevent Stargate trash

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#4539]
When the second subroutine of Trebuchet fires (Trace 6 - The Runner cannot steal or trash Corp cards for the remainder of this run) and the Corp wins the trace during a Stargate run, the runner is still capable of trashing a card with Stargate.

<img width="148" alt="Screenshot 2019-09-30 at 17 54 03" src="https://user-images.githubusercontent.com/661871/65909638-583f8400-e3c9-11e9-958b-11f09631cd07.png">

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
This no longer happens, should be closed :)
