### ISSUE TITLE
Eater inconsistently allows access after ice is broken

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4540]
it appears that the effect of eater to prevent access after breaking subs isn't functioning all the time. Just ran archives to break 2 cricks and while the cards were flipped, I was also asked to access 2 breached domes.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by kalotay** [comment]
I have witnessed this in a game. Archives was protected by 2 ice. Outermost was Asteroid Belt, which got broken by Eater. The runner could access the cards in archives.

<img width="150" alt="Screenshot 2019-11-01 at 21 45 14" src="https://user-images.githubusercontent.com/661871/68056003-5c293380-fcf2-11e9-8db3-452f3a8cc023.png">
