### ISSUE TITLE
Apex can install non-virtual resources

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#4543]
Apex installed an Aesop's Pawnshop (a non-virtual resource) from grip.

Unfortunately I failed to get a screenshot.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Do you have any other details?

**Comment by kalotay** [comment]
That is fine. Not sure I saw a note when hovering over the Apex id that the restriction is unimplemented.

**Comment by NoahTheDuke** [comment]
That can easily be added.
