### ISSUE TITLE
As corp I can set my opponents auto resolve state on Paragon and they arent notified

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4544]
As corp I misclicked on Paragon and the auto resolve state popped up. I set it to Ask (from Always) to see if it would work and it did. I checked the runner window and they aren't notified.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by ouroboros8** [comment]
Looks like this affects all runner cards which use `set-autoresolve`, interestingly.

**Comment by Kubik161** [comment]
@NoahTheDuke retested. Corp cannot click and set auto resolve on runner cards. This issue should be closed.
