### ISSUE TITLE
Kongamato Reveals Information About Unrezzed ICE

### ISSUE THREAD

**Issue by timurleng1** [mtgred/netrunner#4545]
Discovered in a game when my opponent accidentally used Kongamato to break a subroutine after clicking "Continue" so that Kongamato fired on the next (unrezzed) ICE. Tested again and was able to reproduce on any unrezzed ICE.

Reproduction steps:
1. Runner initiates a run with Kongamato installed
2. Runner uses Kongamato while approaching unrezzed ICE
3. Kongamato is trashed and the following text is displayed in the log:
[Runner] trashes Kongamato to use Kongamato to break the first subroutine on Eli 1.0 (" End the run").

This has the potential to reveal information about unrezzed ICE if the runner mis-times the use of Kongamato during a run. It is also possible that this bug affects Gbahali, but I have not had a chance to test that.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
