### ISSUE TITLE
Slot Machine + Hunting Grounds

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4547]
If runner uses Hunting Grounds to prevent the encountered ability on Slot Machine, the second two subs should have no effect.  Currently if the corp hits "Fire Unbroken Subroutines" in this case, slot machine will fire the second two subs if matching cards are on top of the stack (and technically give away hidden information). 

Edit:  I confirmed with Jako that it should use cards revealed during that encounter (so something like drawing cards with gheist after the encounter effect fires shouldn't effect anything, but currently does).

**Comment by NoahTheDuke** [comment]
Thanks for the report!
