### ISSUE TITLE
Leela is able to push runner cards into HQ

### ISSUE THREAD

**Issue by justinliew** [mtgred/netrunner#455]
I was at 4 points and accessed Superior Cyberwalls from R&D. I had Turntable out and tried to click it to see if it was implemented and if there was a UI for it (it isn't, which I realized later) as I would have won switching it for Execute Bootcamp which my opponent had scored. This accidentally put Turntable into the Corp's HQ.

**Comment by nealterrell** [comment]
Nice. Looks like Leela's ability only filters for `not :rezzed`, which of course applies to Runner's cards.

**Comment by justinliew** [comment]
So would it be as simple as adding a condition of `= side :corp` as well?

**Comment by mtgred** [comment]
@justinliew Yes that would do it.

**Comment by JoelCFC25** [comment]
Fixed at #463.
