### ISSUE TITLE
"Fire all subs" doesn't play nice with some subs (Architect)

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4551]
The implementation of the (awesome) "fire all unbroken subs" button reveals an issue with a couple of pieces of ice whose subs require interaction to resolve. As an example, clicking it for an unbroken Architect will ask the Corp to pick a card from R&D for the first sub, but when that's chosen, it will interrupt the prompt asking where it should go with the prompt asking what card to install for the second sub. Once this is chosen, the prompt for where to install returns, suggesting that the subs are resolving concurrently. My guess is that Architect's subs should be marked `async`.

I also think I've seen a similar issue on another piece of ice, although I can't recall which one. Maybe FC3, with the second "pay 3 or trash an installed card" prompt appearing before the runner has chosen the card trash for the second one, or the Corp getting the choice of brain damage or ETR before the runner trashes stuff? Not quite sure.

**Comment by NoahTheDuke** [comment]
Sounds like normal async issues. Thanks for the report! I’ll take a look
