### ISSUE TITLE
KITs ability not working (with Engolo)

### ISSUE THREAD

**Issue by CrackCracker** [mtgred/netrunner#4553]
KITs ability to give the first encountered ice the type "Codegate" is not working when encountering with Engolo. I didnt check it with any other Codegate breakers.

**Comment by lostgeek** [comment]
Did you try to use Kits ability by clicking on the Identity card?

**Comment by CrackCracker** [comment]
Somehow I was expecting for it to work automatically and didn't consider clicking on kit to use its ability:-) Thanks for the reminder!
