### ISSUE TITLE
Corp able to see/install cards on Street Peddler, SMC

### ISSUE THREAD

**Issue by McBEASTse** [mtgred/netrunner#4562]
After Runner installs Street Peddler, the Corp can just click on it and see the cards on Street Peddler and "install" them (although this makes the card just disappear, and Street Peddler together with the other cards are trashed as it should be).

Tried it with SMC also, seems to work as well (you can see the Runners programs and such).

![image](https://user-images.githubusercontent.com/12558577/66806136-0cdbb880-ef27-11e9-9a44-8388d7e511ad.png)

![image](https://user-images.githubusercontent.com/12558577/66806160-1d8c2e80-ef27-11e9-87cf-ca4399943da1.png)

**Comment by NoahTheDuke** [comment]
Yeah this has plagued us for a while. Thanks for the screenshots, they’re helpful.
