### ISSUE TITLE
Patchwork doesn't allow you to play cards that you couldn't afford without the discount

### ISSUE THREAD

**Issue by mikeprosser** [mtgred/netrunner#4563]
The full implementation of patchwork as a discount source on cards (rather than having to pre-click it and not really be able to see if it was going to work before playing the follow up card) is very good but seems to have caused some minor issues with cards that couldn't be afforded without it so they have to be manually played (discarding a card and adding 2) which then means patch still registers as an available discount for future plays that turn.

Steps to recreate:

* Have 3 credits, patchwork installed and a sure gamble in hand, attempt to play sure gamble
* Have 3 credits, patchwork installed, scarcity of resources active and a daily casts in hand, attempt to install daily casts

**Comment by NoahTheDuke** [comment]
Thanks for the report!
