### ISSUE TITLE
Trick of Light can't be played twice

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#4565]
As corp, when I play Trick of Light, the next copy of Trick of Light will not fire.  Nothing shows up for me in console or chat.  Clicking on the card has no effect.

**Comment by NoahTheDuke** [comment]
Can you give me more details? I just tried it out and it worked fine for me.

**Comment by Merlin8000** [comment]
I'm not sure how much more detail there is to provide.  

If it matters, this is as Tennin with advancement counters only on cards which normally cannot be advanced (Psychic Field,  runner cards) .

**Comment by NoahTheDuke** [comment]
That’s good to know! Thank you! I’ll take another look
