### ISSUE TITLE
Feature: Time-stamps for Chat

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#458]
Would it be possible to implement time-stamps for the public chats?

Note: I don't think the in-game chat needs one.

**Comment by mtgred** [comment]
There's already a timestamp in the public chats.

**Comment by SephiTrax** [comment]
Weird, they are not displayed for me. 

Sorry then.

**Comment by mtgred** [comment]
Can you post a screenshot of your public chat page ?

**Comment by SephiTrax** [comment]
I'm very sorry, I somehow missed that the time-stamps are next to the User name and not in front. 

Please close this.

/self-slap

**Comment by mtgred** [comment]
No problem :)
