### ISSUE TITLE
Marilyn Campaign Does not Retain Credits when Derezzed then Rezzed

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4581]
Marilyn Campaign is not properly retaining credits when it is derezed and then rezed.  So if the corp rezzes marilyn, then plays divert power to derez it, then rezzes it again, there should be 16 credits on Marilyn, but it is resetting to 8 instead.

**Comment by NoahTheDuke** [comment]
Thanks for the report! How did this come up? Haha I love it

**Comment by doomrat** [comment]
My opponent was rezzing Next diamonds with Divert Power.  They ended up having to manually reset the marilyns 3 or 4 times.

**Comment by NoahTheDuke** [comment]
That’s fun. I’ll see about getting a fix up soon!
