### ISSUE TITLE
Change in the way start of turn triggers are handled with DBS

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#4582]
This might be working as intended, but it creates extra steps: 

You used to be able to rez and use rashida before clicking the start turn button and get your DBS triggers, then take your mandatory draw and DBS would not fire. 

Now, using rashida before you hit start turn causes DBS to fire on rashida and on the mandatory draw. 

This changes the correct sequence from: 

Old: 

1. Runner ends turn
2. Rez rashida
3. Pop rashida
4. Hit start turn

To: 

New: 

1. Runner ends turn
2. Rez rashida
3. Hit start turn
4. Pop rashida
5. Hit mandatory draw button

It's not such a huge change, more muscle memory than anything else, but it does create an extra step. If this is working as intended, please ignore - thanks again for all your excellent work!

**Comment by NoahTheDuke** [comment]
Hmmm this is tough. I recently changed how the "has happened this turn" events are cleared, so Hayley can trigger her ability before clicking "Start Turn" and have it count for the end of the Corp's turn. Looks like DBS is triggering because you're popping Rashida during the Runner's turn (technically).

Does the Mandatory Draw button not show if you wait to rez Rashida until after you've clicked "Start Turn"?

**Comment by rongydoge** [comment]
That's correct - the mandatory draw button doesn't show if Rashida is unrezzed. 

This is primarily a problem of muscle memory, but in horizontal decks it's a little annoying to scroll over, rez rashida, hit start turn, scroll over, use rashida, and then hit mandatory draw, vs just rezzing and using rashida before hitting start turn. However, that's a small price to pay for Hayley prompts working properly.

**Comment by NoahTheDuke** [comment]
Thanks for bringing this to my attention. I'll give this some thought, as I suspect there are more elegant solutions.

**Comment by NoahTheDuke** [comment]
Okay, the new click-flow will be:

1. Runner ends turn
1. Click start turn
1. Rez rashida
1. Pop rashida
1. Click mando

I've changed the "pause during start of turn" logic to pause if you have derezzed installed cards, to allow for handling cases like this.

**Comment by rongydoge** [comment]
Awesome! Great job on this, you're incredible :)
