### ISSUE TITLE
Undo Click not interacting properly with 1.0 Bioroids

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4584]
If runner clicks a 1.0 Bioroid and then uses /undo-click, the run-ends but the bioroid remains partially broken and only one click is refunded.  Seems like its doing a mix of trying to reset to before the run started and to before the last click was spent on the bioroid.

**Comment by NoahTheDuke** [comment]
Thanks for the report! This is very annoying. I'll see about fixing it up.
