### ISSUE TITLE
Chat Log displays corp breaking Bioroids with click abilities

### ISSUE THREAD

**Issue by hiddenaway1** [mtgred/netrunner#4585]
![Bioroid Chat Log issue](https://user-images.githubusercontent.com/35308609/67610989-57aec900-f78e-11e9-80d3-7986923c273c.png)

See attached image. This was the only time I tried to break a piece of Bioroid ICE with clicks so I haven't verified the issue yet.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Fixed by #5639?
