### ISSUE TITLE
Feature request: have UI seperate MU into normaal and specialized (eg virus)

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4590]
If possible, it would be very helpful, if the UI seperate MU into normal MU and specialized MU (virus, Caissa).
For example when Freedom use Knobk and has to use the MU only for vira

**Comment by NoahTheDuke** [comment]
This is a good suggestion, thanks!

**Comment by francescopellegrini** [comment]
Closed by #5464?
