### ISSUE TITLE
Intermittently Pad Tap triggers more than once per turn

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4591]
Not sure how to reproduce, but pad tap is sometimes triggering more than once per turn.  Pic of game state included.  
![image](https://user-images.githubusercontent.com/17117909/67712779-a0cf6a80-f992-11e9-8cd4-9a36952254c6.png)

**Comment by NoahTheDuke** [comment]
This happens when the Corp uses an ability before they click "Start Turn". Looks like we need to be stricter about this stuff!

Thanks for the report!
