### ISSUE TITLE
Thimblerig fires even if not rezzed

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4605]
At turn start Thimblerig gave me the swap notification, even though it was not rezzed.
May have to do with that it had Eavesdrop installed on it

![image](https://user-images.githubusercontent.com/1651150/68056876-87ad1d80-fcf4-11e9-8929-680bb4bbdb6a.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
