### ISSUE TITLE
Az McCaffrey + Hostage

### ISSUE THREAD

**Issue by Aube88** [mtgred/netrunner#4607]
Jinteki doesn't take Az 's ID into account when playing Hostage with 5 credits to search and install Professional Contact, and so it doesn't allow you to install it at the same time, considering you don't have the money to do so.

**Comment by NoahTheDuke** [comment]
Can you give more details? What card are you trying to install?

**Comment by Aube88** [comment]
Edit  ;)
Thank you !

**Comment by NoahTheDuke** [comment]
Thanks for the report!
