### ISSUE TITLE
Trebuchet Second Sub only partially working

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4609]
If the runner accesses a trashable card after after Trebuchet's second sub fires, the button for Pay X to trash still appears.  If the runner clicks that button, the card isn't trashed, but the runner still loses credits equal to the trash cost.  I'm not sure what the intended implementation is, but this result seems undesirable.

**Comment by lostgeek** [comment]
Thanks for the report! Unfortunately, with how the engine is wired up right now, it is impossible to know whether the Runner has paid the trash cost or used an other way of trashing (Imp, Freedom, ...). So I decided to only implement the prevention part and let the Runner fix the board state manually, if they should click on the prompt.

<strike>If we ever</strike> When we redo the prevention systems at some point, this should be adressed as well 😄

**Comment by NoahTheDuke** [comment]
This is a reminder to myself to work on this. I know the solution, I can do it.
