### ISSUE TITLE
Advancement tokens gained from La Costa Grid can not be put on Hortum

### ISSUE THREAD

**Issue by mathunter25** [mtgred/netrunner#4610]
I run into this problem while playing Tennin Instutute. Hortum ICE can not be advanced by La Costa Grid even to the card states that you can place a token on the installed card (on this server). The ICE is untargetable and I had to forfeit the action of La Costa Grid just to start the turn.

**Comment by NoahTheDuke** [comment]
I’m sorry this disrupted your game but it isn’t a bug. La Costa can only target cards installed IN the server, not PROTECTING the server. See Simone Diego for an example of where it applies to both.
