### ISSUE TITLE
Q-Coherence Chip Errata not implemented

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4611]
Q-Coherence chip was errata'd to say "Trash Q-Coherence Chip when an _installed_ program is trashed" instead of "Trash Q-Coherence Chip when a program is trashed" in FAQ 3.0.1, but JNet is still using the old rules text (i.e. trashing q-chip when a program is hit by net damage).  

This card pretty much never gets used, so not urgent. Link to NRDB for eratta text: https://netrunnerdb.com/en/card/05052

**Comment by NoahTheDuke** [comment]
Used or not, good to know! Thanks, we’ll get this cleared up quick
