### ISSUE TITLE
DaVinci bug

### ISSUE THREAD

**Issue by giles-davis** [mtgred/netrunner#4613]
Hey hey!

I have tested this via a game with myself using two independent browsers and profiles. DaVinci is only able to install cards with an install cost of 0, no matter how many power counters are on it.

Cheers :)

**Comment by lostgeek** [comment]
I've debugged this so far that I can say, that the bug happens in the `actions/select` routine at line 288 where it calls the `card-req` with `(:card ability)`, which it expects to be the DaVinci, but getting a `nil`.

This seems to be set at `prompts/show-select` at line 113, and I assume it's a mix-up between the the usage of the word card in `{:choices {:card ...}}` and the `card` that is saved in the ability. But I can't seem to get to the bottom of it.

Leaving this mostly as a note to myself, but everyone can feel free to dig further :smile:

**Comment by NoahTheDuke** [comment]
I’ll take a look!
