### ISSUE TITLE
Career Fair + Patchwork don't properly allow playing of cards only playable with both discounts

### ISSUE THREAD

**Issue by wagnonbe** [mtgred/netrunner#4617]
At 3 credits or more, this flow functions properly: Click Career Fair, click Liberated Accounts, click Patchwork, click the card to discard.

At 1 or 2 credits, after clicking Career Fair, clicking on Liberated does nothing (assuming that this is because the cost is viewed as unpayable).

**Comment by lostgeek** [comment]
Thanks for the report! I'll take a look
