### ISSUE TITLE
Lockdown does not stop I've Had Worse from firing

### ISSUE THREAD

**Issue by thrdechelonelite** [mtgred/netrunner#462]
Opponent ran into a Lockdown and did not break the subroutine. Then they ran a Fetal AI in the remote, which hit an IHW, causing the runner to draw 3 cards from it.

**Comment by JoelCFC25** [comment]
Unfortunately Lockdown is one of several cards with far-reaching prevention effects that doesn't work at this time--others include Blacklist, Crisium Grid, etc.  

You can read about other current limitations in the [help guide](https://github.com/mtgred/netrunner/wiki/Jinteki.net-Guide).
