### ISSUE TITLE
Rezzing ICE automatically and instantly triggers Nasir's ability

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#4623]
Rezzing ICE automatically (which is helpful) and instantly (which is an issue) triggers Nasir's encounter ability (Lose all creds then gain equal to rez cost). This is not correct as there is a paid ability window on approach before Nasir triggers during which the runner can use paid abilities.

**Comment by NoahTheDuke** [comment]
Thanks for the report! This is currently being worked on in #4603 and should be resolved by it.

**Comment by Kubik161** [comment]
Test OK. Should be closed.
