### ISSUE TITLE
Multiple cayambe grid triggers should specify server

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#4625]
As it stands, if you have multiple servers with cayambe grid installed at the start of the turn, you just receive multiple prompts with the text 'cayambe grid'
The pop-up window states "place 1 advancement token on an ice protecting this server", without a specification as to which server it is.
I believe either the prompt should specify the server, or the popup after clicking it should specify the server.

**Comment by NoahTheDuke** [comment]
Good call! This can easily be done.
