### ISSUE TITLE
Lag when clicking "make runner pay 3" on Tollbooth

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4628]
Ok, this is a weird one!

The game started to lag every time **exactly** when i clicked "make runner pay 3" on Tollbooth.
It would lag for both of us.
As an additional annoyance, I was not able to click "no more actions". I had to F5 to rejoin the server, then I could click "no more action".

We ended doing TB manual since it was very consistent: every time i clicked TB to make runner loose credits, the game grinded to a laggy halt :(

![image](https://user-images.githubusercontent.com/1651150/69186423-c9bdc800-0b18-11ea-867e-871553f4da57.png)

**Comment by NoahTheDuke** [comment]
Sounds like the engine is crashing when it's clicked! Thanks for the report, I'll take a look.

**Comment by NoahTheDuke** [comment]
Is this still happening?

**Comment by Kubik161** [comment]
@NoahTheDuke Tollboth has been changed to automatic on-encounter effect and works fine. This issue should be closed :)
