### ISSUE TITLE
Playing Emergent Creativity to install Monolith causes on-install trigger to fail, controls to stop responding

### ISSUE THREAD

**Issue by brogueleader** [mtgred/netrunner#4630]
When using Emergent Creativity to search for and install a Monolith from stack while holding programs to install from grip with Monolith's on-install trigger, the following occurs:

1. The Monolith is installed (after a delay of several seconds)
2. The prompt listing possible targets for Emergent Creativity is not closed
3. No prompt is raised to select targets for Monolith's on-install trigger.
4. All input aside from chat and top level game controls (i.e. Concede) becomes unresponsive, including gaining and losing clicks and credits, and playing and installing cards from hand, making not only manual resolution of the trigger impossible, but continuing the game also virtually impossible.

Chat console command /close-prompt successfully closes the Emergent Creativity search prompt, but this does not cause controls to become responsive.

**Comment by NoahTheDuke** [comment]
I’m sorry that happened, sounds like you hit a crash. Thanks for the report!
