### ISSUE TITLE
Baba Yaga & installed abilities

### ISSUE THREAD

**Issue by Nibbles-N-Bytes** [mtgred/netrunner#4632]
Baba can't use any abilites of installed breakers on it.

**Comment by NoahTheDuke** [comment]
Glad to see someone’s playing my favorite card! Sorry that happened. Thanks for the report! I’ll take a look.

**Comment by Nibbles-N-Bytes** [comment]
Sure thing. Also, just for clarity, the first installed program shows the
click icon, but any subsequent programs won't show the icon (but *do* use
said click).

**Comment by lostgeek** [comment]
I can't seem to reproduce the bug. Can you please tell me, how exactly you used Baba Yaga and what you expected to get?

**Comment by Nibbles-N-Bytes** [comment]
Example
I have excess credits to play anything.
Click 1) Install Baba Yaga //everything's fine
Click 2) *click on* Baga Yaga, see [Click]: Install program on Baga Yaga.
Install say Passport. //everything is still fine. When I *click on* BY I
now see Passports paid abilities and BY's 2 abilities (install & host an
installed program)
Click 3) *click on* BY. I no longer see the [Click] icon to install onto
BY, but when used the ability properly uses a [Click]. I install another
program like Faerie. //Now both Faerie's & Passport's appear on BY.
Click 4) Run HQ. Encounter Ichi 2.0. None of BY's inherited paid abilities
will "fire" when *clicked on*.

If this is insufficient, I do offer the opportunity to test with you at
your convenience.

**Comment by Nibbles-N-Bytes** [comment]
BabaYaga.mp4
<https://drive.google.com/a/students.mclennan.edu/file/d/1EPthS_aReWtsjNoOQHRb3c4hJ054mewA/view?usp=drive_web>

Hopefully this helps

**Comment by NoahTheDuke** [comment]
I think I’ve seen this in the logs. Very weird. Thanks for the report!

**Comment by Nibbles-N-Bytes** [comment]
Glad to be of help!

**Comment by Nibbles-N-Bytes** [comment]
Perhaps the problem lies in the line:
(update! state :runner (assoc card :abilities (concat new-abis [host-click host-free])))))]

Where the new abilities are simply listed with Baba Yaga, instead of being usable. 
;;Granted lisp is new grounds for me. So, what do I know :p
