### ISSUE TITLE
Start of turn isn't counted as during Runner's turn by Genetics Pavilion

### ISSUE THREAD

**Issue by doorisajar** [mtgred/netrunner#4635]
The limitation of Genetics Pavilion is incorrectly ignored when (for example) some combination of Crowdfundings and Class Act triggers 2+ Runner draws at the start of their turn.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I'm having trouble recreating this. If it comes up again, mind taking a screenshot for me?

**Comment by doorisajar** [comment]
Tested it some more, looks like it happens when Crowdfunding draws trigger The Class Act to draw additional cards. I definitely saw that during the Eternal event, but it didn't occur to me that the issue might be TCA rather than CF.

For example, ajar1 has a rezzed GenPav here, but ajar gets the the CF trash draw and the TCA additional draw, then clicks to draw a card and it works. The click to draw should be prevented by GenPav. 

![Screenshot 2019-12-15 14 57 30](https://user-images.githubusercontent.com/3525775/70868993-e4cefc80-1f4b-11ea-9217-61867c6aeace.png)

**Comment by NoahTheDuke** [comment]
Awesome, thank you! I’ll try that tonight

**Comment by NBKelly** [comment]
The class act is now "look at the top X+1 cards", rather than "draw X+1 cards", so this issue has been obsoleted.
