### ISSUE TITLE
Shiro's future side - picture broken

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4640]
![image](https://user-images.githubusercontent.com/46433823/69969627-b21d1100-1514-11ea-8189-31e91c38ba88.png)

As seen on code marvloeus stream.

**Comment by BlueHairedHackerCatgirl** [comment]
Also noticed it didn't give a link strength.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
The link issue should be taken care of. Sadly, the image is still being figured out.

**Comment by NoahTheDuke** [comment]
Got the new images figured out!
