### ISSUE TITLE
Kill Switch / Film Critic  interaction

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#4641]
Film Critic should prevent the ability on Kill Switch from firing (since the card is no longer being accessed).

Currently, this is not the case.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
I think this is also true for Kill Switch + By Any Means.

**Comment by Kubik161** [comment]
@NoahTheDuke retested (both Film Critic and By Any Means), works as expected. This issue should be closed :)
