### ISSUE TITLE
Integer underflow when stealing City Works Project, 2x Paparazzi & Citadel Sanctuary installed

### ISSUE THREAD

**Issue by bryantjs6** [mtgred/netrunner#4642]
Chat log:

![image](https://user-images.githubusercontent.com/5322147/70023224-b6711a80-1564-11ea-8ed8-b2e686cbe8a4.png)

It had no advancement tokens.

**Comment by lostgeek** [comment]
Paparazzi is implemented by just preventing `MAX_INT` damage instead of adding an option to really prevent _all_ damage. I do not know why the message is showing `MAX_INT-1` though.

```
    :events [{:event :pre-damage
              :req (req (= target :meat)) :msg "prevent all meat damage"
              :effect (effect (damage-prevent :meat Integer/MAX_VALUE))}]
```
