### ISSUE TITLE
Déjà Vu isn't shown correctly in the log

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#465]
When you play Déjà Vu, the text in the log pane gets messed up:

> ThePlayer plays DÃƒÂ©jÃƒÂ  Vu.

 I'm sure it's because of the javascript regex that is used to find the card names:

    (defn add-image-codes [text]
      (reduce #(.replace %1 (js/RegExp. (str "\\b" (:title %2) "\\b") "g") (str "[" (:title %2) "~"(:code %2) "]")) text (prepared-cards)))

If someone knows a quick fix I would be glad to hear; otherwise I try to fix this tonight.

**Comment by nealterrell** [comment]
I get this only on my Windows dev machine for any cards with non-standard characters, like Draco or Shi.Kyu. It is not an issue on live from what I've seen.

**Comment by DominicKexel** [comment]
Can confirm. Only Windows seems to be affected. Some kind of encoding issue :-(

**Comment by JoelCFC25** [comment]
> Only Windows seems to be affected.

Typical!!
