### ISSUE TITLE
Buffer Drive Buttons Don't Work

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4650]
When Buffer Drive triggers (i.e. MaxX or Frantic coding), buttons appear for each card that could be put on bottom.  But none of the buttons do anything.  Easiest way to duplicate is to play Frantic Coding with Buffer Drive out.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I believe #4645 handles this, which will be merged and deployed soon!
