### ISSUE TITLE
Overseer Matrix does not trigger on Apocalypse

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4651]
I had Overseer Matrix installed and rezzed in a remote server, along with 2 other upgrades, when runner played Apocalypse.
I should have been prompted to give runner 3 tags for 3 credits, but it never triggered

**Comment by AndersRask** [comment]
Ah, not sure if it is 1 or 3 tags. Depends on who gets to decide what order cards gets trashed when doing an apoc?

**Comment by NoahTheDuke** [comment]
Thanks for the report! Looks like you’re right, ‘‘tis is a bug
