### ISSUE TITLE
System Seizure Does not Retain Boost

### ISSUE THREAD

**Issue by Zanzibon** [mtgred/netrunner#4653]
I was using System Seizure in combination with Engolo. On the first piece of ICE I boosted Engolo twice, to strength 10. However after that ICE the strength went down to 6, my understanding is that it should have stayed at 10 for the rest of the run. I boosted Engolo to 10 again at the second ICE and it return to 6 once more for the final ice. I did not boost on the last ICE. System Seizure does not seem to quite function as intended

**Comment by NoahTheDuke** [comment]
Thanks for the report!
