### ISSUE TITLE
Akhet is 5str when not advanced

### ISSUE THREAD

**Issue by giles-davis** [mtgred/netrunner#4654]
Hey lovely people <3

Title says it all, really :) I didn't get a chance to trip-adv it and see how it handles, I'll set up a test game with myself after work and report back if I see any other problems.

Cheeeeers!

**Comment by NoahTheDuke** [comment]
Haha it’s currently backwards. Thanks for the report!

**Comment by giles-davis** [comment]
Hey peeps,

There is something more serious also happening with this card, I've noticed that whenever the first sub is triggered it wigs out completely, both players need to /close-prompt and then resolve it manually :/

Cheers
