### ISSUE TITLE
The virus program installed on Djinn will not add virus counts

### ISSUE THREAD

**Issue by BenTsui** [mtgred/netrunner#466]
If the virus program is installed before Djinn, 
and then select "Host an installed non-Icebreaker program on Djinn", 
virus counts can never be added on this virus program. 
(If Djinn is installed first and then select "Click: Install a non-Icebreaker program on Djinn", 
there's no problem on virus counts.)

**Comment by JoelCFC25** [comment]
Duplicate of #369.

**Comment by mtgred** [comment]
The fix has been deployed.
