### ISSUE TITLE
Hoshiko Shiro still prevents Runner from ending turn if you don't run on her front side.

### ISSUE THREAD

**Issue by wern212** [mtgred/netrunner#4681]
I saw that about ten hours ago, the bug that causes the runner to be unable to end the turn with Hoshiko Shiro if you accessed cards while flipped was fixed, but it appears she is still bugged. In a game I finished some ten minutes ago, after not running while on the Next-Level Shut-In side, I got the same glitch: clicking "End your turn" didn't accomplish anything. I tried flipping her to see if that helped, but it didn't seem to accomplish anything.

**Comment by NoahTheDuke** [comment]
I haven’t deployed the fix yet. Should be happening today!
