### ISSUE TITLE
Trebuchet firing does not stop the trash card prompt

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4691]
Trebuchet fires on HQ, access Rashida, still get prompt asking if I want to pay to trash it. Not sure what should happen here - maybe saying yes has no effect?

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
Same as #4609 ?

**Comment by NoahTheDuke** [comment]
Good catch
