### ISSUE TITLE
New cards not working with the Back

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4694]
Hey!

So neither Simulchip nor Boomerang register as being cards with trash icons when in the heap. The Back does not allow you to trigger it and shuffle anything in at all unless you add an older card, like Demara, and then, when you do try to use the Back, you cannot select either Simulchip nor Boomerang. 

Some of this may be to do with Simulchip being unimplemented? But I have no idea what the issue with Boomerang is. 

I supplied a picture to JNet earlier. 

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!
