### ISSUE TITLE
Keiko firing on Corroder install

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4705]
Hey! 

So I installed Keiko, and it triggered, and then installed Corroder and Keiko installed again. This happened even when I undid the click. I did not have Paladin to help with the install to trigger Keiko. This may not be high priority as it didn't happen in the game after?

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report! I'll take a look!

**Comment by Jelley07** [comment]
As a follow up, Keiko also triggered twice in a turn just now!

The first was on Paladin install, as it should, but then it triggered on installing Earthrise? 

Thanks!

**Comment by NoahTheDuke** [comment]
https://github.com/mtgred/netrunner/blob/c8919e9a50859aa8173361d78e9d361b6c474c25/src/clj/game/cards/hardware.clj#L890-L892

This doesn't actually check that it's the first time, just that the count is 1. We need to add a check for this firing.
