### ISSUE TITLE
DreamNet does not give 1 credit when Hoshiko runs as Mahou Shoujo 

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4708]
DreamNet should give both a credit and a card when Hoshiko is Mahou Shoujo, as she is Digital

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't recreate this. Do you have more details?

**Comment by francescopellegrini** [comment]
Fixed by #5449?
