### ISSUE TITLE
Tyr's second subroutine should be corp choice

### ISSUE THREAD

**Issue by Jelley07** [mtgred/netrunner#4709]
Hey!

So Tyr's second subroutine is worded and configured incorrectly. The subroutine is supposed to read 'Trash 1 installed runner card. Gain 3', meaning the corp chooses the card to trash. Instead, JNet has it as 'Force the runner to trash 1 installed card. Gain 3.' Firing the subroutines works as worded, and brings up a prompt for the runner to trash a card. 

The rest of Tyr is working perfectly.

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
This is already fixed, should be closed :)
