### ISSUE TITLE
Thimblerig remembers prior locations for passing

### ISSUE THREAD

**Issue by greyfield** [mtgred/netrunner#4714]
The title above may not be an exact representation but is what it appeared to be. I played a game with Thimblerig and did several exchanges. Suddenly, if my opponent was running a server, every time they passed a piece of ice, the game asked if I wanted to trigger Thimblerig, even though they hadn't passed Thimblerig.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
Should be closed, duplicity of issue that was fixed yesterday.
