### ISSUE TITLE
Earth Station could use a manual flip option

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#4720]
Earth Station could use a manual/clickless/override/whatever flip option for fixing broken game states.

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion! What situations are you running into where this would be helpful? Have you discovered any bugs?

**Comment by dinte** [comment]
I already reported the bug that lead to needing this.

**Comment by sayden** [comment]
I guess this issue can be closed after https://github.com/mtgred/netrunner/pull/5316 was merged?

**Comment by NoahTheDuke** [comment]
Ah yes, thank you.
