### ISSUE TITLE
Thimblerig Firing On Every Ice Pass

### ISSUE THREAD

**Issue by se4n** [mtgred/netrunner#4729]
Had a game yesterday (playing PE, the PU 2.0 deck with a few Engram Flushes in there for fun). We had to abort a run mid-run and /undo-click in which Thimblerig was, I think, being encountered (maybe approached). After that, I got a Thimberig prompt after every ice (rezzed or unrezzed, regardless of location) was passed. This seems akin to but different from some of the other outstanding Thimblerig issues, so thought I'd mention it though I don't recall any more detail than this unfortunately.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
