### ISSUE TITLE
Formicary and Cayambe Grid bugged

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#4751]
Formicary not always moving when rez'd in approach and sometimes when it dose move it freezes the new interface so the runner can't progress. Also Formicary and Cayambe Grid together not always working correctly triggering Cayambe Grid before allowing Formicary or even allowing the corp to choose the order which is how it should be really.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
