### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4753]
- [x] Davinci isn't reading it's counters, can only install cost 0 things whether on 0 counters or 100

- [x] Tyr 2nd sub the runner erroneously chooses the card to trash

- [ ] Keiko double triggers the credit gain a lot - usually when used with paladin

- [ ] Tranquility home grid trigger is being consumed by installing cards protecting the remote

Possible QoL update

- [x] Make it more transparent which ice boomerang is targeting, when they're unrezzed boomerang will say something like "Remote(1) Position (2)" what isn't clear is the innermost ice is position 0. Perhaps put a B on the ice that's cursed by boomerang similar to how femme marks ice?

**Comment by x3N1GM4x** [comment]
Strong second for the Boomerang enhancement - most people don't know that ice are numbered with a zero-index from innermost to outermost, so it seems to cause significant confusion.

**Comment by AndersRask** [comment]
Came here to report same Boomerang issue. Non-devs have no idea about 0-indexing ;-) And naming should be along the lines of above suggested, both on Boomerang itself and in Console when installed.

**Comment by Kubik161** [comment]
@NoahTheDuke retested. Both Keiko and Tranquility home grid works correctly. This issue should be closed.
