### ISSUE TITLE
Option to host  on Flame-Out resets strength from Cybertrooper Talut

### ISSUE THREAD

**Issue by yojimbosteel** [mtgred/netrunner#4758]
If after installing an Icebreaker you use Flame-Out to host, the strength of the Icebreaker will reset on the next click.

**Comment by mgsholte** [comment]
Duplicate of #4770 

I know this ticket came first and the other is technically the duplicate, but the other ticket has more activity at this point.

**Comment by francescopellegrini** [comment]
Might as well close this.
