### ISSUE TITLE
Clicking "new corp deck" or "new runner deck" while decks are loading causes weird stuff to happen...

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4761]
If you click "new runner deck" or "new corp deck" while the decklist is loading (which it does for quite a long time since i have quite a few decks!), instead of giving me a blank deck it edits the latest deck.

If i then click cancel, and "new corp deck" it will again show the latest (here runner) deck in edit mode!

![image](https://user-images.githubusercontent.com/1651150/70927780-f12c8580-202f-11ea-987f-80305faba729.png)
![image](https://user-images.githubusercontent.com/1651150/70927894-276a0500-2030-11ea-884e-f87de33fbb8d.png)

**Comment by jwarwick** [comment]
Blocked create buttons until decks are loaded in #5409
