### ISSUE TITLE
unable to use credit from Mantle to pay for Mu Safecracker

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4765]
With Mu Safecracker and mantle installed, as well as some Penumbral toolkits, i wasn't able to use Mantle to pay for Mu Safecracker and had to spend a different stealth credit and then manually fix the penumbral or Net Mercur.

![Screenshot 2019-12-16 at 9 02 42 PM](https://user-images.githubusercontent.com/396562/70961444-6f485680-2047-11ea-8954-5d4c97467342.png)

**Comment by NoahTheDuke** [comment]
Huh! Thanks for the report, I’ll take a look

**Comment by Kubik161** [comment]
@NoahTheDuke retested, cannot reproduce. Should be closed?

**Comment by NoahTheDuke** [comment]
Yes
