### ISSUE TITLE
Logos fires even when not installed....

### ISSUE THREAD

**Issue by DominicKexel** [mtgred/netrunner#477]
....but hosted on The Supplier.

When the corp scores an agenda, and Logos is hosted on The Supllier, the Runner has to pick a card from this stack. This should not happend, and also it's a *may* ability, not a *must* abitlity.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed with the next server update.

**Comment by qmsm** [comment]
This applies to Doppelganger too (so I'm guessing anything temporarily hosted on The Supplier).

**Comment by mtgred** [comment]
It applies for all hosted cards that are not installed yet.

**Comment by DominicKexel** [comment]
Yeah, Grimoire on a Street Peddler gives extra Virus tokens, for example
