### ISSUE TITLE
Moving breaker to Flame Out removes Cybertrooper boost strenght

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4770]
Euler/Chameleon looses Cybertrooper strenght after being moved to Flame Out and then initiating a run (not on host)

**Comment by Chemscribbler** [comment]
Ika has this issue as well, whenever it changes host location it loses the Cybertrooper bonus

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by pawnstorm-runner** [comment]
I had the same issue with moving Chameleon to Dinosaurus (strength 5 instead of 7).

**Comment by mgsholte** [comment]
I suspect that any breaker which is re-hosted in any way is immediately reset to it's base strength. I can confirm it happens with the anarch heap breakers getting hosted onto Flame-out and losing the Cybertrooper Talut bonus.

Also -- even though this should never be possible under netrunner rules -- if you use Takobi to raise the strength of a breaker then re-host it, the strength gain is lost.

It's a problematic issue for the [current decklist of the week](http://netrunnerdb.com/en/decklist/62322/xandorius-wu) on netrunnerdb.
