### ISSUE TITLE
Buffer "continue" inputs on Runner side

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#4773]
There are several prompts during a run, where the Runner needs to wait on the Corp. This creates unnecessary waiting time, since often there is no sensible decision to be made by the Runner.

These are the prompts:
- `:approach-ice`
![image](https://user-images.githubusercontent.com/1409906/71039571-bbb59400-2124-11ea-8bf0-0cd05af69bf4.png)
  - Here the "Continue to Encounter ice" button should be changed
- `:encounter-ice`
![image](https://user-images.githubusercontent.com/1409906/71039662-f6b7c780-2124-11ea-822d-abb83becf8e7.png)
  - Here the "Continue to Pass ice" button should be changed

These buttons should be active even before the Corp presses their corresponding "Continue" button. The functionality should be different, depending on whether the Corp already pressed their button or not:
- Corp did already press button: Current functionality can stay: Continue to next phase
- Corp did not press button: New functionality: Set a flag in the game state. When Corp presses their Corp button, if this flag is set, instantly continue to next phase.

This will fix the "lag" issue, discussed today on Slack.

**Comment by NoahTheDuke** [comment]
Agreed.

**Comment by lostgeek** [comment]
Slept over it for a night: We should indicate this buffered input by changing the button color or something similar.
