### ISSUE TITLE
Gachapon Doesn't let you choose not to install

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4776]
Gachapon should have a button for choosing not to install, since it is a may effect.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by presheaf** [comment]
Hijacking this issue to note that if Gachapon finds no valid targets, it seems to stop the ability resolution with nothing happening, as opposed to having you put 3 back and RFG the other 3. (I have not tested this since today's update.)

**Comment by Kubik161** [comment]
@NoahTheDuke retested. Gachapon works fine even with no valid targets. No action button is also present. This issue should be closed.
