### ISSUE TITLE
Please re-order the actions menu

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#4779]
The indicate action button is neat, but it is placed too close to the cards. Other than that action, everything is ordered from bottom to top in (rough) order of frequency - gain credit, draw card,Run, Remove Tag.
The most frequent buttons are also placed closest to the other most frequent part of the interface, which is the hand. Having a very infrequently used action between those is a (minor) annoyance.
Also, I can think of very few reasons to use that button on your own turn outside of a run - on your opponents turn, considering is the only available option that is active, the placement is less important.

![runnerActions](https://user-images.githubusercontent.com/9095245/71043266-fc4bf680-2192-11ea-9e05-c869bd416a6b.jpg)
![corpActions](https://user-images.githubusercontent.com/9095245/71043293-1ab1f200-2193-11ea-852c-0c5b82fb6b9d.jpg)

**Comment by NoahTheDuke** [comment]
Agreed! This is hopefully changing very soon. Thanks for writing up the issue.

**Comment by MHGray** [comment]
This was fixed it looks like, though the indicate action's new position under the messages has caused the last message to be obscured. Style needs to be changed on netrunner/src/css/base.styl for the .messages class, bottom should be changed from 43px to 68px or 69px to fix it.

**Comment by NoahTheDuke** [comment]
Will be handled by #4916!
