### ISSUE TITLE
Hardware should be in second row and Resources last

### ISSUE THREAD

**Issue by bjoernsteffen** [mtgred/netrunner#478]
According to the rules, programs belong into the first row, hardware in the second and resources in the last row. Not that it matters, but why is it not like this on jinteki.net? I think there is no reason it should not be as written in the rulebook. It also helps when it is the same as in games on the table.

**Comment by mtgred** [comment]
It is already the case.

<img width="1552" alt="screen shot 2015-08-23 at 04 50 55" src="https://cloud.githubusercontent.com/assets/284114/9426707/9b89aea4-4952-11e5-8aba-b2e1504d0672.png">
