### ISSUE TITLE
Sportsmetal's log entry isn't printing correctly

### ISSUE THREAD

**Issue by bryantjs6** [mtgred/netrunner#4780]
When an agenda is scored/stolen, it prints one of the following:

![image](https://user-images.githubusercontent.com/5322147/71045240-4042eb00-2102-11ea-9889-0107efbf46ac.png)

![image](https://user-images.githubusercontent.com/5322147/71045291-6c5e6c00-2102-11ea-9440-c646cd138a1f.png)

It's false when drawing cards, true when taking credits.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
