### ISSUE TITLE
Paladin Poemu, issue when trashing itself

### ISSUE THREAD

**Issue by McBEASTse** [mtgred/netrunner#4784]
If the Runner has 3 or more credits on Paladin Poemu at the end of the Runners turn and trashes Paladin Poemu (by clicking on it when prompted), a trigger window for the Corp gets stuck saying: Waiting for Runner to resolve runner-trash triggers.

It's possible to get around this if the Corp uses /close-prompt. Seems only to happen if Paladin Poemu trashes itself.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
According to Stimslack, this also happens when trashing other cards with Poemu.
