### ISSUE TITLE
Parasite events hooked up twice on install

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#479]
Parasite and any other card that installs directly from hand onto a target (Personal Touch, or using Off-Campus Apartment to host/install from hand) are receiving events twice, causing lots of goofiness. This is from today's changes to registering events in `host`. Flow of logic:

1. Parasite is clicked, which calls `runner-install` which sees that Parasite has a `:hosting` key and recursively resolves `runner-install` with a `:host-card`.
2. `runner-install` calls `host`, which calls `register-events` in order to handle the situation of hosting a card that was already installed.
3. We return to `runner-install` which immediately calls `card-init`; this registers events again.
4. Parasite now receives 2 `:runner-turn-begins` events and gains 2 tokens per turn; and 2 `:pre-ice-strength` events, granting -2 strength per token. OP.

**Comment by nealterrell** [comment]
Paging @mtgred !

**Comment by nealterrell** [comment]
So this appears to be fixed by 1d3c86fdaf9da4cacfd2d4ce84a1f48141afffba . It seems to be working fine on my dev machine after syncing with upstream. @mtgred, does this sound like something you just fixed?

**Comment by DominicKexel** [comment]
I guess this also fixed the issue that hosted, but uninstalled cards react to events? Like Logos on The Supplier or Grimoire/Parasite hidden on Street Peddler

**Comment by mtgred** [comment]
The fix has been deployed on Friday. Should work fine now.
