### ISSUE TITLE
Knifed (and maybe all cutlery?) can trash multiple ice

### ISSUE THREAD

**Issue by tanderson11** [mtgred/netrunner#4791]
Steps that happened in game:

Play knifed.
Break Eli 1.0 with Paperclip. It is trashed and passed as normal.
Encounter Aiki, break 2/3 subs with Blorch (note! not all subs even had to be broken!) and Aiki is instantly trashed.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by OtisF** [comment]
Just hit the same issue with Spooned, broke only one sub on the second ICE and yet trashed it too.

![image](https://user-images.githubusercontent.com/4820473/71217040-542e4e80-22b4-11ea-9f0f-f59d3be426aa.png)

**Comment by NoahTheDuke** [comment]
Yep, it's happening to all of them
