### ISSUE TITLE
Viper causes the runner to have negative clicks

### ISSUE THREAD

**Issue by junkmail22** [mtgred/netrunner#480]
When Viper's first trace fires and the runner has 0 clicks, it causes the runner to go to -1 clicks. This makes ending your turn impossible without manually adding clicks.

**Comment by JoelCFC25** [comment]
With the Runner already at 0 clicks, there is no point to firing the trace in the first place, so this one is pretty easily avoidable.

**Comment by junkmail22** [comment]
I know, but with interactions with things like spinal modem, power tap, and chilo grid, it's still partly relevant.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
