### ISSUE TITLE
Boomerang doesn't update its ice position label when the ice is moved

### ISSUE THREAD

**Issue by FarCryFromHuman** [mtgred/netrunner#4811]
You can see this happen a bunch in Andrej's latest stream (the stream is still live, I'll update with link and timestamp later if needed).

**Comment by lostgeek** [comment]
Timestamps would be incredibly helpful, because I tried to update them when ice is swapped moved or trashed.

**Comment by FarCryFromHuman** [comment]
Andrej's opponent plays the boomerang [here](https://youtu.be/6hzqUxkD-Lw?t=12270). Immediately after Andrej does his first swap, so it might be something with that specific timing, and him messing up the prompt resolution by trying to do things out of order. Good luck, this looks like a tricky one!

**Comment by Kubik161** [comment]
@FarCryFromHuman I have checked that stream, runner was talking about targeting innermost ICE, but actually selected outermost ICE on HQ and didn't undo click. And that ICE was never moved. So label on boomerang is correct.

**Comment by FarCryFromHuman** [comment]
Well that would definitely be an issue... Thanks for looking into it!
