### ISSUE TITLE
Paule's Café discounts its activation cost

### ISSUE THREAD

**Issue by j4nw** [mtgred/netrunner#4816]
The second ability of Paule's Café has a 1c activation cost. Currently, this can be nullified by having enough unique connections, but this shouldn't be possible. The discount should only apply to the hosted card's installation cost.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by f1axle** [comment]
In Current Version, Paule's Cafe isn't able to handle the discount right (not lowing the cost at all) when there are several Unique Connection (Kati Jones, Beth, Dadiana Chacon , Miss Bones) installed on the table.
