### ISSUE TITLE
Conditional effect :"When encounter" effect and "breaking all subs" fired too many times when you have multiple ICE layers.

### ISSUE THREAD

**Issue by f1axle** [mtgred/netrunner#4817]
"Cyberdelia" (Euler ICEbreaker to break) fires too many times when breaking all subs on different ICE (bugged over 2 layers) , and triggers wrongly when you don't fully break subs (Slot Machine, ichi 1.0).
Turnpike isn't trigger once during encounter, instead firing every encounter during that run.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by x3N1GM4x** [comment]
> Turnpike isn't trigger once during encounter, instead firing every encounter during that run.
This is also mentioned in #4814.
