### ISSUE TITLE
Snapshot and Snapshot Plus legality isn't properly handling some cards

### ISSUE THREAD

**Issue by wagnonbe** [mtgred/netrunner#4818]
![image](https://user-images.githubusercontent.com/1815998/71265665-b323b000-2314-11ea-8661-a906f8a10e86.png)
Some cards (mostly new core ones?) are showing up as rotated in Snapshot formats despite being legal.

**Comment by NoahTheDuke** [comment]
Thanks for the report! A fix is forthcoming!
