### ISSUE TITLE
Akhet cannot place 1 advancement counter on "installed" card ( ICE ). Overly restrictive.

### ISSUE THREAD

**Issue by f1axle** [mtgred/netrunner#4819]
Akhet which have 3 advancement counters cannot put 1 advancement counter on Mausolus which is on the same server rezzed before Akhet, after the runner break the last sub. This Happened Once in game.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I can't reproduce this. Can you give more details?

**Comment by Kubik161** [comment]
@f1axle I have tested this, couldn't reproduce. Could you provide more information? What card/breaker did you used to break End the run sub? Was first sub completely disabled? Could you click any other card and advance, just not Mausolus? Was there something else installed that could have affected Akhet? Thanks for any new information.

**Comment by f1axle** [comment]
I guess that It was occurred by lost connection or having a connection delay. My friends and I cannot reproduce the bug. Big Thanks for help.
