### ISSUE TITLE
Director Hass' Pet Project does not work with the card preview

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#482]
Because the regex checks for word boundaries and the `'` messes this up. Sorry, I'll go and smash my head on the table.

**Comment by nealterrell** [comment]
Likewise for Shock! and Snare! :)

**Comment by DominicKexel** [comment]
Yeah, but it should be easy to fix.

**Comment by DominicKexel** [comment]
OK, it was not that easy. Javascript's Regex sucks for sure :-)
