### ISSUE TITLE
Project Vacheron gives runner 0 agenda points when stolen from archives

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4823]
![image](https://user-images.githubusercontent.com/1651150/71312228-abedc680-2428-11ea-81e0-2460b3545859.png)

> When this agenda would be added to the Runner's score area from anywhere except Archives, instead it is added to their score area with 4 hosted agenda counters.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
