### ISSUE TITLE
Deck order are messed up again

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4824]
When creating a standard legal deck, the order of the decks are not sorted correctly

This looks like a regression bug from earlier. Right now it means that Uprising decks are *way* down in the list, even though they should be Std Legal now

![image](https://user-images.githubusercontent.com/1651150/71312599-038e3100-242d-11ea-9203-bcfa4a49227b.png)

**Comment by jwarwick** [comment]
This should be fixed now.
