### ISSUE TITLE
Gachpon effect breaks when it misses

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#4826]
It the top 6 cards are all non-programs or non-virtual cards Gachpod just puts them back on the stack instead of RFGing 3 and shuffling 3 back.

**Comment by BlueHairedHackerCatgirl** [comment]
![image](https://user-images.githubusercontent.com/46433823/71316351-64862b00-2466-11ea-9314-06ea8765bac6.png)
![image](https://user-images.githubusercontent.com/46433823/71316356-841d5380-2466-11ea-8c69-b26e5982f46f.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
