### ISSUE TITLE
ACME not working correctly, or at all.

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#4832]
ACME did not give tags on encounter, had to do everything manually, plus many prompts about 'waiting for corp to resolve X effect'.

**Comment by NoahTheDuke** [comment]
Uh oh! Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't recreate this. Do you have any further details about the board state when this happened?

**Comment by NBKelly** [comment]
I think the exact conditions surrounding this issue are no longer reproducible, so I'm closing this issue as stale. If anything like this happens again, please create a new issue.
