### ISSUE TITLE
DeckBuilder - list of decks - vertical text overflow when deck format is long (Core Experience legal)

### ISSUE THREAD

**Issue by bagl** [mtgred/netrunner#4833]
related to #1548

The fixed width of the `h4` element of the `.deckline` causes the name of the deck to be pushed a "line" below when deck format name is long.

![pushed_down](https://user-images.githubusercontent.com/2178708/71378056-b645c700-25c6-11ea-95d3-0a5af683fd30.PNG)

I think no width is needed, as the width of all the elements are given by the `.viewport` with `display: flex`.

Deleting the width of the `h4` element fixes the issue, checked in chrome/firefox (latest). The horizontal overflow with ellipsis was implemented correctly in solution to #1548

**Comment by NoahTheDuke** [comment]
Nice find! I'm trash at css so I'm very glad you're looking into this.
