### ISSUE TITLE
Restricted cards that have rotated are not showing as rotated when deck building

### ISSUE THREAD

**Issue by bryantjs6** [mtgred/netrunner#4840]
![image](https://user-images.githubusercontent.com/5322147/71418448-89ca9300-2638-11ea-8471-ff42b2bea184.png)

Confirmed for Au Revoir, Power Tap, and Mother Goddess. Decks are still showing as Standard legal if any of these are in a deck as long as the rest of deck is legal.

**Comment by NoahTheDuke** [comment]
Sorry, but this is intentional. With the release of Uprising on the 16th, we decided to make jnet's Standard follow rotation immediately instead of waiting for the 27th.

**Comment by LessRekkless** [comment]
I don't think you understand.

Power Tap, Au Revoir and Mother Goddess are still considered **legal**, even though you said that rotation has already happened on Jnet.

**Comment by NoahTheDuke** [comment]
Uh really?

**Comment by LessRekkless** [comment]
(this is still considered closed)

**Comment by LessRekkless** [comment]
I figured out a possible cause, high-level, at least.  All of these cards are on MWL 3.4, but have also rotated.

**Comment by NoahTheDuke** [comment]
Fixed today!
