### ISSUE TITLE
Is Sync BRE worked on remote server?

### ISSUE THREAD

**Issue by f1axle** [mtgred/netrunner#4845]
According to F&Q,

> If SYNC BRE’s second trace resolves during a run on a remote server, how will the access step be affected? What if there are multiple cards installed in the server?

> Just like normal, the Runner chooses the order they will access the cards installed in the remote server. If there is only one card installed in the remote server, then the Runner does not access that card. If there are multiple cards installed in the remote server, the Runner chooses and accesses one card from the remote server at a time. The Runner will not be able to access the last card, so in practice this means the Runner chooses a card to not access.

When the second trace successfully fired, the only card in remote ( my situation is the only card in the remote: Daily Quest) can be accessed and trashed. I don't know if the prompt only works for 2 or more cards to be accessed inside the remote sever/R&D/HQ (if "total access" >1, then...).

**Comment by NoahTheDuke** [comment]
I believe Sync BRE is broken but I could be mistaken. Thanks for the report!
