### ISSUE TITLE
Breaking disconnect

### ISSUE THREAD

**Issue by Gurkenglas** [mtgred/netrunner#4846]
> mcg spends  to make a run on Server 6.
> mcg approaches Server 6.
> Gurkenglas has no further action.
> Gurkenglas
> Gurkenglas
> The time for thinking about that was before you used a click >:D
> mcg rejoined the game.
> Gurkenglas accesses Vaporframe Fabricator from Server 6.
> Gurkenglas
> Gurkenglas
> uh oh, it never said that you disconnected
> Gurkenglas
> Gurkenglas
> And now it says I'm accessing the Fabricator lol
> mcg
> mcg
> uh oh
> mcg
> mcg
> all my cards are facedown too
> mcg
> mcg
> let me try rejoining again
> mcg has left the game.
> mcg rejoined the game.
> !mcg uses a command: /undo-click
> mcg
> mcg
> it won't let me do anything :(
> Gurkenglas
> Gurkenglas
> Let's post that to github
> mcg
> mcg
> yep

(And as you can see, Ctrl-c on the chat duplicates names.)

**Comment by Gurkenglas** [comment]
A little later, (the log said that) he left. And about as mcg joined another game, the log finally said that he disconnected.

**Comment by NBKelly** [comment]
I think this issue is too old to be reproducible. If it ever comes back, feel free to make another issue.
