### ISSUE TITLE
Sandstorm combination with Jinteki: replicating perfection

### ISSUE THREAD

**Issue by fdemey** [mtgred/netrunner#4851]
Sandstorm was on R&D. First run of runner rezzed sandstorm. Deflected at remote server. Both runner and corp had no action possibilities. With replicating perfection, the corp cannot run on a remote server before running on a central one first.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Eric-Fletcher** [comment]
Just to clarify: the correct behavior would be that the run continues on the remote server selected by the Corp, with full interaction.

Note that Replicating Perfection should have been satisfied as soon as the initial run was declared, before any actions by either player.
