### ISSUE TITLE
Ambushes (Intake) in the remote / R&D cannot end the access when finishing resolving effect. 

### ISSUE THREAD

**Issue by f1axle** [mtgred/netrunner#4856]
Intake (maybe other trace-based ambushes) in the remote cannot work properly no matter how the the traces is successful or not. The runner has to use "close-prompt" order to end the access phase, and then is allowed to jack-out.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Intake doesn't end the run, so what do you mean? Which prompt do you have to type `/close-prompt` for?
