### ISSUE TITLE
Inversificator - subs stay broken

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#4857]
When I break a piece of ice with Inversificator and then move it somewhere else on the board, next time I encounter that ice all of the subs are pre-broken.  This behavior persists across multiple turns and runs.

![Subs stay broken](https://user-images.githubusercontent.com/42731111/71636550-32579480-2bef-11ea-89e5-3b29160193b9.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
