### ISSUE TITLE
Inversificator - breaking with Maven allows swap

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#4858]
When I break ice with Maven while Inversificator is installed but I have not used it yet, I get the prompt to swap the passed ice as if I had used Inversificator.

![Broke with Maven, got swap prompt (also Maven does not show up in log)](https://user-images.githubusercontent.com/42731111/71636590-7ba7e400-2bef-11ea-9c6f-6e682aaac40d.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
