### ISSUE TITLE
Inversificator - prompts to swap unrezzed ice

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#4859]
I've only seen this behavior once, but it's a pretty serious issue.

I made a run on Server 1, broke the IP block (now on Archives) and moved it to Archives.  I proceeded past the second ice and corp chose not to rez.  When I passed it, I got the Inversificator ice swap prompt, and it revealed the name of the ice I had just passed.

![Unrezzed Ice prompt](https://user-images.githubusercontent.com/42731111/71636627-d6d9d680-2bef-11ea-94c3-859507b4a8d7.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
