### ISSUE TITLE
Maven - name of program does not appear in chat log

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#4860]
When you break a program with Maven, it just says

> {player name} pays $2 to break 1 subroutine on {ice name}.  

It should probably say
> {player name} pays $2 to break 1 subroutine on {ice name} with Maven.  

Is this normal behavior on any breaker interaction where the Icebreaker does not need to gain strength?  I tried to test it, but couldn't find examples.

![Broke with Maven, got swap prompt (also Maven does not show up in log)](https://user-images.githubusercontent.com/42731111/71636835-49988100-2bf3-11ea-9e55-2a1d9e5e7f77.PNG)

**Comment by NoahTheDuke** [comment]
Sounds like a normal bug to me, probably got missed somewhere! Thanks for the report.
