### ISSUE TITLE
Reverse Infection print error with two Cyberdex Sandboxes scored

### ISSUE THREAD

**Issue by bryantjs6** [mtgred/netrunner#4861]
![image](https://user-images.githubusercontent.com/5322147/71645300-4d381080-2ca4-11ea-91c1-a1e62a0f94a9.png)

There were 2 virus counters in play on a Sandstone at the time. I think it's saying 22 and 00 because of the two scored Cyberdex agendas?

**Comment by NoahTheDuke** [comment]
Thanks for the report! This one is very easy and has nothing to do with the cyberdex sandbox!
