### ISSUE TITLE
pop smc to install afterimage with only 5 credits makes the afterimage disappear.

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#4863]
this isn't a valid move, but the game apparently hid the afterimage card so my opponent couldn't play it.

Board state:

runner has SMC down and 5 credits.

Clicks SMC to go fetch Afterimage.  Can't actually pay for it.  Card ..,. disappears?  We had to unwind.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
