### ISSUE TITLE
Doppelgänger doubling The Maker's Eye effect

### ISSUE THREAD

**Issue by TaakoMagnusen** [mtgred/netrunner#4864]
When the runner plays [The Maker's Eye](https://netrunnerdb.com/en/card/01036) while [Doppelgänger](https://netrunnerdb.com/en/card/20025) is on the field, if the run is successful they can choose to make another run with Doppelganger's effect, if they choose to make this free run on R&D the effect from The Maker's Eye triggers again if the run is successful, allowing them to access three cards from R&D twice.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
