### ISSUE TITLE
Engram Flush Bug

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4865]
If you see two of the same card with engram flush, you can't trash both of them when using "Fire All Subs".  In game I named event, and saw two moshing and some resources.  For the first sub I named moshing and it was trashed.  For the second sub I named moshing and nothing happened.  As a quality of life improvement, it would also be nice if the button for trashed cards went away (i.e. if runners hand is Liberated Accounts and Turning Wheel, and I trash Turning Wheel, the button for Turning Wheel still appears for the second sub even though its its already been trashed).  Its not clear that anything has happened unless you look at the runners discard pile.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
