### ISSUE TITLE
Misdirection + Flame-Out

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4868]
When installing Flame-Out + Misdirection after Wu'ing out the misdirection the following issues came up.

- Not prompted to spend flame-out credits on misdirection.
- Will spend credits you don't have on misdirection (so if you have 0 credits and 5 on flame-out, you can remove 4 tags and the log will say you spent 4, but nothing happens).
- If you Wu out the misdirection, there needs to be a prompt for runner to choose whether they want Wu or Flame-Out to be first (usually so the program can be trashed by flame-out instead of rfg'd).  This may be an issue with other programs as well, I haven't tested it.
- Got a black screen twice while testing this issue, see logs below:

First Time:
https://docs.google.com/document/d/1EqFqdNA7J4Ny1axSCdp0QzWPXXrdcLM4vEbMrrK7EDU/edit?usp=sharing

Second Time (this one occurred after a leave and rejoin):
https://docs.google.com/document/d/1Nal4OEyKCXWwKJsy54wxcaLajNYlRvuoYgfPRCaeXfE/edit?usp=sharing

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Dirjel** [comment]
Misdirection + Multithreader exhibit the same behavior (spending credits you don't have).

**Comment by NoahTheDuke** [comment]
Can you post the exact steps you took to get to that point? I had trouble recreating the original situation.

**Comment by Dirjel** [comment]
yeah man.

![image](https://user-images.githubusercontent.com/42731111/72169810-0b3a5900-338d-11ea-92ac-e9f420687bcb.png)


So you see here I have 4 tags, $2, a Multithreader and Misdirection.  I fire Misdirection for 4, hit okay, and....

![image](https://user-images.githubusercontent.com/42731111/72169870-24430a00-338d-11ea-9521-f2130fb71500.png)

Success!  Kind of!

Log says I spent $4 to clear 4 tags, but I only had $2 in my credit pool.

If I trash the Multithreader and try Misdirection, it only lets me go up to 2 tags...
![image](https://user-images.githubusercontent.com/42731111/72169989-594f5c80-338d-11ea-93cf-8c70188f5540.png)

The engine clearly recognizes I have the Multithreader installed, but when I fire the program it does not prompt for the "Select a credit providing card (0 of 4)" prompt.  It just spends money out of my credit pool, regardless of whether or not I can afford it.

**Comment by Dirjel** [comment]
thanks for the fixes, Noah!
