### ISSUE TITLE
End Game statistics miscounts "cards drawn"

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#4871]
I just finished a game in which I used Rashida twice and Fully Operational twice (first time draw 2, then gain 2. Second time Draw 2, then Gain 2 x3)
In the end I had 22 cards in R&D (with one trashed by Runner during the game), but the stats showed 31 cards drawn (and only two "by click" which is correct)

![1-3-2020 11-31-48 AM](https://user-images.githubusercontent.com/33155579/71744936-965fa000-2e1d-11ea-9c11-dc3225c34c87.png)

**Comment by NBKelly** [comment]
Hi, we used to count the mulligan as draws.

This was fixed a couple of years later in #6206.
