### ISSUE TITLE
Hortum (3 Advancements) allowed to be broken by AI

### ISSUE THREAD

**Issue by dj88c** [mtgred/netrunner#4877]
Was in a game where my opponent was able to use a Brahman (AI) to break Hortum despite my Hortum having the necessary 3 advancement tokens which prevents AI from breaking it. This lead to me having the opponent /undo-click because the subroutines were registered as broken.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Actually, this is currently unimplemented. Sorry we don't have an implementation note saying so.
