### ISSUE TITLE
Corp can view Cards from R&D Accesses

### ISSUE THREAD

**Issue by SomeSketchyGuy** [mtgred/netrunner#488]
After the latest server restart I noticed that the chat bar will tell the corp what cards were accessed by the runner

**Comment by gandrasch** [comment]
Same for me, but also the shown card isn't drawn on the next round. 

He accessed Jackson, Hedge Fund and Meru Mati but I drew an Archer.

**Comment by nealterrell** [comment]
Yeah, my bad. Submitting a fix now. 

I can't reproduce the Jackson/Archer thing. Every single or multi access does access from the top of R&D in my tests.

**Comment by queueseven** [comment]
Maybe the runner used Keyhole, which shows 3 cards and then shuffles RnD?
