### ISSUE TITLE
SOCR11 Legality Update

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4882]
Could we please get the SOCR deck legality updated for our upcoming SOCR11 tournament? We plan to start on 2020-01-19

Deck construction rules are:

- System Core 2019
- Honor and Profit
- Order and Chaos
- Data and Destiny
- Reign and Reverie
- Kitara
- Ashes
- Magnum Opus

We will adhere to the current MWL 3.4b

Link: https://forum.stimhack.com/t/stimhack-online-cache-refresh-11-starts-january-19th/10635

**Comment by NoahTheDuke** [comment]
Exciting! Thanks for the heads up, I'll make the changes.
