### ISSUE TITLE
Simulchip should trash before finding targets

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#4889]
When no programs have been trashed on the turn where simulchip is used, it should have the trash prompt come first.

In theory this should check for a legal target in the heap (an install-able program)

**Comment by NoahTheDuke** [comment]
Thanks for the report! This is a fundamental issue with our engine at the moment: Choices are made before costs are paid. Until this is "fixed", we might have to make the cost payment manual in Simulchip.
