### ISSUE TITLE
Hemorrhage: no trashing

### ISSUE THREAD

**Issue by adamskopl** [mtgred/netrunner#489]
Hi, when spending counters on Hemorrhage nothing happens.

> "Whenever you make a successful run, place 1 virus counter on Hemorrhage.
> {click}, 2 hosted virus counters: The Corp trashes 1 card from HQ."

Honest players are removing cards from HQ by themselves by asking for a number : )
Or You can ask for a free run on a HQ, but then it triggers all 'when You successfully make a run on a HQ' events. 
Anyway, it's possible to play with that card, but I thought it should be reported.

**Comment by adamskopl** [comment]
(Sorry, haven't noticed, that there's a list with card's implementation status. So I guess reporting such issues is useless :) )

**Comment by JoelCFC25** [comment]
I added this in #654.
