### ISSUE TITLE
engram flush and 2 of the same card

### ISSUE THREAD

**Issue by triorph-emacs** [mtgred/netrunner#4894]
Runner encounters engram flush and I name event, then the subs both fire at the same time. I named IHW both times, but it hits the same IHW. I spent a few moments confused because they'd already used an IHW earlier in the game and that should have been all of them. It appears that the engram flush reveal happens simultaneously despite the fact that the trash should happen between hand, and then naming IHW a second time targetted the same IHW that was already trashed.

**Comment by NoahTheDuke** [comment]
Closed by #4876
