### ISSUE TITLE
Dedicated Neural Net wants to select more cards than in hand

### ISSUE THREAD

**Issue by Kubik161** [mtgred/netrunner#4898]
I have scored Dedicated Neural Net, rezzed Mwanza City Grid on HQ and 3 cards in hand/HQ. I win PSI game, runner should access 4 cards (1 normal + 3 from Mwanza), UI wants me to select 4 cards from hand. But I have only 3 cards. I'm stuck.

Fix: Dedicated Neural Net should have limit :)

**Comment by NoahTheDuke** [comment]
Nicely caught!
