### ISSUE TITLE
Suggested features

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#49]
It would be great to see a list of online users. 

Also a spectator mode.

Thanks,

Louis

**Comment by mtgred** [comment]
I would like to add both features too. The development focus is on the game engine at the moment so you will have to be patient.

**Comment by queueseven** [comment]
I spend some thoughts on how to implement a list of users currently online. How would you do it? Simply looking in the `session` collection for non-expired sessions is probably not enough

**Comment by zaroth** [comment]
Moved to #1253. Spectator mode is ready.
