### ISSUE TITLE
Purpose of "Runner rig layout" checkbox is highly unclear

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#4900]
![image](https://user-images.githubusercontent.com/1972929/72175038-1c915e80-33a9-11ea-83cb-7b0255ee9133.png)

There are a number of problems with this checkbox from a user experience perspective.

* What the alternative is, is extremely unclear (one can intuit the opposite of "server stacking is on" or "sounds are enabled," but not this)
* There is no indication that, despite what you would expect from a runner rig layout preference, this is a layout preference meant for when you're playing _corp_
* This isn't actually a true-false value, so semantically the checkbox isn't... great

There should either be an explanation of this in the help, an explanation below the checkbox, or the option reworked to be a radio button so the two options can be more clearly presented, perhaps something like:

![image](https://user-images.githubusercontent.com/1972929/72175408-1485ee80-33aa-11ea-83f4-d464836f5050.png)

**Comment by NoahTheDuke** [comment]
Thanks for this! Yeah, the first pass is pretty unclear. I'll see what I can whip up!
