### ISSUE TITLE
Mid-game screen blackout

### ISSUE THREAD

**Issue by greyfield** [mtgred/netrunner#4901]
This issue has happened to me five or six times now, on different computers. I'll be midgame - usually it's mid-run - and suddenly everything below the top menu bar goes completely black, including the chat box. Leaving the game and rejoining it doesn't fix the issue, nor does CTRL+F5ing. I don't know if my opponents experience this issue or not, since I have no way to communicate with them in-game after the bug hits. But joining a new game often presents no problems, and the bug is so irregular and unpredictable I don't know more about what's causing it.

**Comment by GilboD** [comment]
Reports on chat seem to indicate this is triggered by the Runner jacking out before accessing a server with no cards in it, or when they select a menu option that has no text from a card but only shows a border.

**Comment by NoahTheDuke** [comment]
Thanks for the report! This is being taken care of soon!
