### ISSUE TITLE
Paule's Cafe barfing nonsense into the logs

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#4907]
Anything my opponent installed off of Paule's Cafe (at least Gauss, 2 RDIs, and an Atman) spit a line of nonsense into the logs:

![image](https://user-images.githubusercontent.com/1972929/72208313-2b424900-346f-11ea-83bb-6ded38a26fcd.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
