### ISSUE TITLE
Buffer Drive offering to let me keep a corp card

### ISSUE THREAD

**Issue by stoppableforce** [mtgred/netrunner#4908]
Game state:

![image](https://user-images.githubusercontent.com/1972929/72208646-25e6fd80-3473-11ea-8c23-bd369be64032.png)

Click 1: installed Hippo
Click 2: Installed Buffer Drive
Click 3: took a credit
Click 4: ran HQ, trashing the Archer with Hippo after a break. Buffer Drive offered to let me put it on the bottom of my stack.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
