### ISSUE TITLE
disappearing Parasite when installed from Street Peddler at 1 credit

### ISSUE THREAD

**Issue by JoelCFC25** [mtgred/netrunner#491]
Reporting on behalf of someone in chat...I did reproduce it to confirm. 

If the Runner tries installing a Parasite off Street Peddler when sitting at 1 credit, the Parasite disappears altogether (though the log does report the install). Plenty of MU were available and there was a piece of rezzed ice ready to host it. Street Peddler and the other 2 cards hosted on it went into the Heap as expected.

**Comment by ZomBagus** [comment]
I just had a similar experience with a mid run install of Faust disappearing from the game, with enough MU available. Again the log reported the install. Peddler and other 2 cards went to the heap. Card was not in heap or stack or grip. Corp could not see it either.

**Comment by nealterrell** [comment]
Working on a fix.
