### ISSUE TITLE
Disposable HQ doesn't complete

### ISSUE THREAD

**Issue by cannibul** [mtgred/netrunner#4912]
After the corp resolves the disposable HQ effect the game doesnt continue.

Corp side:
![dhqq](https://user-images.githubusercontent.com/59792922/72217935-103a0c80-3535-11ea-8516-0000a7650bbe.PNG)

Runner side:
![dhq2](https://user-images.githubusercontent.com/59792922/72217945-3b246080-3535-11ea-894c-cc4ba3753a1c.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
