### ISSUE TITLE
Indicate Action button occludes log

### ISSUE THREAD

**Issue by Gurkenglas** [mtgred/netrunner#4923]
Ask any player. So much priority. As a stopgap, Adblock can remove the button. How is this the first issue report on this?

**Comment by NoahTheDuke** [comment]
> How is this the first issue report on this?

I noticed in the first game played after restarting, but haven't had a chance to patch. I put up a fix in #4916. Please don't forget that we have lives outside of developing jnet.

**Comment by Gurkenglas** [comment]
(Sorry, should have checked the commits too.)
