### ISSUE TITLE
Professional Contacts should have sounds

### ISSUE THREAD

**Issue by Gurkenglas** [mtgred/netrunner#4924]
I keep being confused where all the enemy clicks went.

**Comment by NoahTheDuke** [comment]
Interesting idea! What would you like the sound to be like? We don't have anyone who produces sounds, so we'll have to source it from somewhere.

**Comment by Gurkenglas** [comment]
Barring better ideas, the simplest would be an overlay of the draw and gaincred sounds.

**Comment by presheaf** [comment]
I like this suggestion, although for clarity it might be even better to have the draw sound followed by the cred sound when it finishes.

**Comment by NoahTheDuke** [comment]
If someone wants to stitch the sounds together or create a new one, I'm totally down to use it!

**Comment by theolen** [comment]
> 
> 
> If someone wants to stitch the sounds together or create a new one, I'm totally down to use it!

Here's the cred sound stitched together with the draw sound - that seemed like the least confusing option, and matches the description of the card.

[ProfessionalContacts.zip](https://github.com/mtgred/netrunner/files/4493623/ProfessionalContacts.zip)
