### ISSUE TITLE
Deckbuilder issue

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#4932]
A couple of days ago, it was still working, but now the deckbuilder looks like that:
<img width="1432" alt="adfgajsdhg" src="https://user-images.githubusercontent.com/11632063/72277013-75732800-3631-11ea-843b-ae3cbda82fe1.png">
All cards are unknown, no IDs available, no images. Weird.
I emptied the cache und restarted Chrome. Nothing changed.
Chrome 79.0.3945.117 on Mac OS 10.15.2

**Comment by NoahTheDuke** [comment]
Looks like some part of the app isn't being loaded, images included. Can you load the source and check to see if the app.js file you're being sent from the server is called `app10.js?v=34`? That's the current, latest version.

**Comment by HongkongKoma** [comment]
It is:
<img width="1423" alt="klkokjfj" src="https://user-images.githubusercontent.com/11632063/72322415-96c22b80-36a6-11ea-92a5-cd6789b1e2e9.png">

**Comment by HongkongKoma** [comment]
Solved
