### ISSUE TITLE
Unable to interrupt Emergent Creativity with Buffer Drive

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4939]
Buffer Drive should interrupt the resolving of EC and allow you to bottom the trashed program.

Instead it fires after EC is done. This prevents me from playing silly combos.

![image](https://user-images.githubusercontent.com/7817263/72378616-bcb7f200-36df-11ea-98dd-7e82fd6c36c8.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
