### ISSUE TITLE
R&D accesses are shown in the console and corp can see it

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#494]
sosad accesses 2 cards.
sosad accesses Quandary.
sosad accesses Jackson Howard.

Clearly the corp shouldn't be seeing what cards are being accessed by the runner in R&D.

**Comment by queueseven** [comment]
thanks for reporting. already fixed. not deployed yet.

**Comment by queueseven** [comment]
@JoelCFC25 I think you can close this issue.
