### ISSUE TITLE
Jeeves triggered on only 2 same action

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#4953]
Performed an action twice in a turn and then Jeeves triggered.

<img width="150" alt="Screenshot 2020-01-16 at 14 40 12" src="https://user-images.githubusercontent.com/661871/72546322-e3665c00-388a-11ea-8bda-fd834f72868b.png">

**Comment by NoahTheDuke** [comment]
Huh! Looks like a bug to me! Thanks for the report!

**Comment by OtisF** [comment]
Same thing for me just now, one draw and two creds and it fired.

![image](https://user-images.githubusercontent.com/4820473/78077533-6c783400-73a0-11ea-8402-c419f68b9977.png)

**Comment by p4ulyg** [comment]
I have also seen this in a game (clicked twice for a credit and was awarded a Jeeves click). Screenshot of full board state included in case it helps.
![Screenshot 2020-05-19 at 13 53 36](https://user-images.githubusercontent.com/31340324/82419946-faa29980-9a76-11ea-8a61-eddbc75eddc3.png)
