### ISSUE TITLE
Jeeves + Corp basic action card

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#4959]
With jeeves rezzed, i trashed 2 resources and then clicked for a cred. Seems that jeeves is counting all basic actions as the same.
<img width="224" alt="Screen Shot 2020-01-18 at 09 38 24" src="https://user-images.githubusercontent.com/7129465/72669616-197a1c00-3a02-11ea-8b8a-a95fcb155401.png">

**Comment by NoahTheDuke** [comment]
Good catch! Thanks for the report!

**Comment by Kubik161** [comment]
Duplicate of #4953
