### ISSUE TITLE
MaxX + Aniccam + Buffer Drive with 1 card left in stack doesn't effectively draw it

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4966]
I was playing as MaxX with both Aniccam and Buffer Drive installed and 1 card left in stack (Hacktivist). What happened was MaxX trashed it, triggering both, and the game prompted me to shuffle it back in with Buffer Drive, but Aniccam didn't then trigger to draw it, and it was left in deck. What should happen (I think?) is that you end up drawing the card, unless you choose to resolve Aniccam first (although this seems like a pretty rare edge case, and picking the order of these would be super annoying otherwise).

Because Aniccam does usually draw a card after the Buffer Drive trigger, I would guess that what's happening is Aniccam doesn't wait for Buffer Drive to bottom the card before drawing, but that's speculation.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I await your pr 😉
