### ISSUE TITLE
Hippo sometimes triggers when it shouldn't

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#4970]
Hippo should only trigger the first time all subroutines are broken on an outermost piece of ice each turn. However, by putting a Hortum on R&D, a Sapper on HQ, I was able to cheat using hippo by running R&D, breaking Hortum fully, jacking out, installing Hippo, running HQ and breaking Sapper again, at which point Hippo triggered erroneously. 

I think the predicate in Hippo's req isn't quite right and is checking whether this specific ice has been broken already this turn as opposed to whether any (at the time) outermost piece of ice has been broken.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
