### ISSUE TITLE
Masterwork + Q-Loop Ordering Doesn't Work

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#4973]
In the event that I want to make a run and trigger Q-Loop before masterwork, I get the sequence of prompts below (order is from top to bottom), which forces me to make a masterwork decision before I see the top of my deck.

![image](https://user-images.githubusercontent.com/17117909/73388933-c07b7500-4298-11ea-8bdf-fe831f07d573.png)

**Comment by NoahTheDuke** [comment]
Sounds like one of those effects isn’t async, which is why they line up like that! I’ll check it out!
