### ISSUE TITLE
Cybertooper + Flameout + Gauss + Hagen = wrong str breaker.

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#4974]
There is a rezzed hagen and runner has cybertrooper talut on board.
Runner installs Gauss, hosts on Flameout, and runs. 
Gauss strength drops from 6 to 4. 

Install Gauss 
![image](https://user-images.githubusercontent.com/7817263/73393727-2b817780-42aa-11ea-8cc8-66693d78e9ed.png)

Host Gauss on Flameout and Run
![image](https://user-images.githubusercontent.com/7817263/73393750-3805d000-42aa-11ea-964a-f8414340d1f9.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I suspect this is because of how hosting works (and doesn’t, lol)
