### ISSUE TITLE
Agenda stolen by Film Critic leaves empty server

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#4976]
I watched a game where a server was left empty (23) after runner placed a Medical Breakthrough on Film Critic
![image](https://user-images.githubusercontent.com/1651150/73486700-ee9aab00-43a5-11ea-986f-de343acaecca.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
This could be solved by implementing Checkpoints. We could check for empty servers at a checkpoint and remove them from the game state.

**Comment by NoahTheDuke** [comment]
does this still happen?

**Comment by NBKelly** [comment]
This got fixed in #7394
