### ISSUE TITLE
Saisentan not firing all 3 subs when one of them hits an extra card.

### ISSUE THREAD

**Issue by ZomBagus** [mtgred/netrunner#4982]
Runner ran into Saisentan with no sentry breaker and 3 cards in hand (2 hardware, 1 resource).
Named hardware and pressed fire all subs
First sub fired hit Hardware and did a second damage (another hardware)
Second sub fired and hit Resource.
Third sub did not fire.

![saisentan not firing 3 times](https://user-images.githubusercontent.com/13881796/73595364-af886900-450f-11ea-9722-332655e14d8b.PNG)

**Comment by lostgeek** [comment]
Couldn't exactly reproduce this situation, but found another bug with damage prevention. I've rewritten how Saisentan works and hope this also resolves this bug.

**Comment by tvaduva** [comment]
Ran into this issue today (playing as Chronos, but used my ability earlier that run), has this fix been deployed yet?

**Comment by NoahTheDuke** [comment]
Nope
