### ISSUE TITLE
Acme ID Bugs

### ISSUE THREAD

**Issue by TheRelamer** [mtgred/netrunner#4984]
ACME ID tag multiplies on Hippo interraction and saves after run ends, may be it caused by Data Ward interraction.

**Comment by NoahTheDuke** [comment]
Can you explain more clearly what’s happening? I don’t understand

**Comment by TheRelamer** [comment]
Data Ward bugs on ACME ID interraction and sometimes runner gain tag after he passes it. When runner trash ice by Hyppo - on encounter next ice he gain anoter tag and as i understood only one bonus tag removes in the end of the run.

**Comment by pCox532** [comment]
Just had this happen to me. The temporary tag given by Acme doesn't go away if the runner uses hippo to trash the ice. It also can't be removed manually.
