### ISSUE TITLE
Davinci + Draw on Trash Effects

### ISSUE THREAD

**Issue by ADumbBrick** [mtgred/netrunner#4987]
At the moment DaVinci is not quite properly implemented. Effects that happen when a card is trashed (like Geist's draw) do not trigger until after you choose a target. While there needs to be a valid target in your hand to use DaVinci's ability the card you install does not need to be in your hand when you trash it. 

This is the same behaviour that is currently properly implemented on Self Modifying code. You draw a card before searching the stack.

**Comment by ADumbBrick** [comment]
I brought this up only because I was starting to look to see if I could make myself helpful. I have a fix working locally, I'm not sure what the etiquette is to contribute.

**Comment by NoahTheDuke** [comment]
You can get on #jinteki_net on stimslack where we hang out, you can open a PR with the fix, you can describe it here!
