### ISSUE TITLE
Autoscroll in chat window sucks.

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#499]
When a new message arrives in chat, the chat log automatically scrolls down to the New message. This makes it impossible to read older messages when there's some activity going on in the chat.

I think it would be better if, when already scrolled up, New messages would not change the scroll state.

**Comment by mtgred** [comment]
It's indeed an issue. I'll fix that.

**Comment by queueseven** [comment]
It's not high priority; as a workaround I can just browse to `/messages/general` (if I'm not on mobile)

**Comment by mtgred** [comment]
It's a serious usability issue in my opinion. I often scroll up the game log to check what happened and it repeatedly scroll down to the bottom if the opponent does something.

**Comment by mtgred** [comment]
It was indeed a cache. It works on the live server now.

**Comment by queueseven** [comment]
Cool.
