### ISSUE TITLE
Self-Modifying Code hosted on Flame-out doesn't list all affordable programs

### ISSUE THREAD

**Issue by j4nw** [mtgred/netrunner#4993]
When you're at 2 credits and use SMC hosted on a fully loaded Flame-out, the SMC will only list 0c programs from the stack as potential installs, because it doesn't know its 2c activation cost can be paid for with the Flame-out creds.

**Comment by Kubik161** [comment]
Thanks for report. Will be closed by #4994

**Comment by Kubik161** [comment]
@NoahTheDuke retested, this issue should be closed.
