### ISSUE TITLE
DBS and TCA should print the position of the card bottomed

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#4996]
The position of the card that is moved with Daily Business Show (under new errata for CR 1.4) and The Class Act is open information. There should be a log message printed with the position(s) (1st, 2nd, etc.) of card(s) that was/were bottomed.

You shouldn't need to keep track if the card was revealed or accessed earlier (probably making this issue much easier to resolve), because the message that the 2nd card was bottomed wouldn't help an opponent that has not seen the second card.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kiv** [comment]
I'm interested in working on this one, but I'm having trouble getting started. My environment is up and running, but the "Getting Started with Development" guide seems to be out of date - for example the videos are gone, and the `reset-card-defs` function doesn't exist anymore.

Any tips on what the current workflow is for setting up to test a fix for this?

**Comment by NoahTheDuke** [comment]
Get on [stimslack](https://stimslackinvite.herokuapp.com/), join the #jinteki_net channel, and we'll get you set up!

**Comment by Kubik161** [comment]
@NoahTheDuke this issue should be closed.
