### ISSUE TITLE
Card in server displayed when playing vs Gagarin

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#5011]
With the new interface that displays the card name, that information is shown before the decision to "pay 1 to access" happens. This results in the Runner knowing what is in the server before deciding to access or not.

**Comment by BishopGit** [comment]
I'm having the same issue.  We have to rely on runners paying the 1 cred even, after they've been given the opportunity to see that it's a trap.  Makes Gagarin Deep Space unusuable.

**Comment by NoahTheDuke** [comment]
Thanks for the report, it’s been on the agenda for a while, just haven’t had time yet

**Comment by NoahTheDuke** [comment]
This has been fixed!
