### ISSUE TITLE
Update card scans

### ISSUE THREAD

**Issue by tarantegui** [mtgred/netrunner#5012]
Update card assets with scans from 

https://www.reddit.com/r/Netrunner/comments/8pgfbj/android_netrunner_cards_up_to_kitara_600dpi/?st=JI7PEUI0&sh=511d914f

 To remove watermarks and improve quality

**Comment by NoahTheDuke** [comment]
Sadly, those are too big and too grainy at smaller sizes. I believe Nisei is planning on cleaning them up for NRDB v2, so once they do that, we’ll switch over.
