### ISSUE TITLE
Successful Trace from Ash 2X3ZB9CY Still Allows Access to Cards in Archives

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#5015]
2 copies of Ash 2X3ZB9CY in play, one rezzed in S1 remote, the other unrezzed in root of Archives. Runner Spear Fishes archives clicking once to get through an outermost Ravana 1.0 and bypassing the innermost Ravana 1.0 (both ice were rezzed before the run started)

On approach I manually trashed the remote Ash to rez the one in archives, incidentally adding a counter to an installed Gravedigger. Trace fires, beats runner, then runner accesses all cards instead of just the Ash.

Chat Log below:

Opponent spends and pays 2 to play Spear Phishing.
Opponent uses Ken "Express" Tenma: Disappeared Clone to gain 1 .
Opponent approaches Ravana 1.0 protecting Archives at position 2.
aenimosity uses Advanced Concept Hopper to gain 1 .
aenimosity has no further action.
Opponent encounters Ravana 1.0 protecting Archives at position 2.
Opponent spends to use Ravana 1.0 to break 1 subroutine on Ravana 1.0 (" Resolve a subroutine on a rezzed bioroid ice").
Opponent indicates to fire all unbroken subroutines on Ravana 1.0.
aenimosity: you sure?
aenimosity: i can just end the run
Opponent: well not many other options rreally! go ahead!
aenimosity: kk
aenimosity uses Ravana 1.0 to resolve the subroutine (" Do 2 brain damage") from Týr.
aenimosity uses Týr to do 2 brain damage.
Opponent trashes Networking, HQ Interface due to brain damage.
aenimosity resolves 1 unbroken subroutine on Ravana 1.0 (" Resolve a subroutine on a rezzed bioroid ice").
Opponent passes Ravana 1.0 protecting Archives at position 2.
aenimosity: thinking
Opponent: ok mnp
aenimosity uses Haas-Bioroid: Architects of Tomorrow to rez Fairchild 3.0.
aenimosity pays 2 to rez Fairchild 3.0.
Opponent approaches ICE protecting Archives at position 1.
Opponent passes ICE protecting Archives at position 1.
Opponent approaches Ravana 1.0 protecting Archives at position 0.
aenimosity has no further action.
Opponent encounters Ravana 1.0 protecting Archives at position 0.
Opponent uses Spear Phishing to bypass Ravana 1.0.
Opponent passes Ravana 1.0 protecting Archives at position 0.
Opponent approaches Archives.
Opponent uses Gravedigger to place 1 virus counter on Gravedigger.
aenimosity trashes Ash 2X3ZB9CY in Server 1.
aenimosity pays 2 to rez Ash 2X3ZB9CY.
aenimosity has no further action.
aenimosity uses Ash 2X3ZB9CY to initiate a trace with strength 4.
aenimosity pays 1 to increase trace strength to 5.
Opponent pays 0 to increase link strength to 0.
The trace was successful.
aenimosity uses Ash 2X3ZB9CY to prevent the Runner from accessing cards other than Ash 2X3ZB9CY.
Opponent accesses Advanced Concept Hopper from Archives.
Opponent steals Advanced Concept Hopper and gains 2 agenda points.
Opponent wins the game.
aenimosity: oh shit what happened there?

**Comment by NoahTheDuke** [comment]
Thanks for the report!
