### ISSUE TITLE
Adding information to the 'help' panel.

### ISSUE THREAD

**Issue by giles-davis** [mtgred/netrunner#5023]
Hi fam!

Some newbies have asked in splash chat how programs and ice can be overwritten, as the need to drag & drop is not readily apparent. I think it might help to add it to the help page :)

Cheeeers <3

**Comment by NoahTheDuke** [comment]
Thanks for the feedback!

**Comment by Kubik161** [comment]
@NoahTheDuke This issue should be closed. We have added "Trash" ability to every ICE and Program some time ago, it should be possible to trash without dragging.

**Comment by NBKelly** [comment]
As per Kubik's comment, I'm closing this one as no longer relevant.
