### ISSUE TITLE
Page transitions?

### ISSUE THREAD

**Issue by Travis42** [mtgred/netrunner#5027]
Not really an issue, I just really like how the app scrolls to a new scene when you click on the various sections.  Could you point me to where in the code you do that?  I'd like to learn, thanks!

**Comment by Travis42** [comment]
I keep seeing references to Stimslack.  How do I access this?

**Comment by NoahTheDuke** [comment]
https://stimslackinvite.herokuapp.com/

**Comment by NoahTheDuke** [comment]
Join the #jinteki_net channel and I can answer all questions!
