### ISSUE TITLE
Was looking for some advice...

### ISSUE THREAD

**Issue by powershellwhizz** [mtgred/netrunner#5029]
Hi Minh,
Just trying to get in contact with you through here as I can't see any other way to do so. I was looking at this project and I am trying to learn coding. I want to build an app like yours so I wondering if I can ask you some questions about it? Is there another way I can contact you, email address or something maybe?

thanks,
Graham

**Comment by NoahTheDuke** [comment]
Hey Graham,

Minh doesn’t really contribute to the site anymore. If you join the #jinteki_net channel on stimslack, I can help out a bit.

**Comment by powershellwhizz** [comment]
hi noah, sorry for posting here again, I won't do it again after this. I've messaged you on stimhack but it says you're on DND there so won't get notifications. thanks,
