### ISSUE TITLE
Makler gains a credit after Konjin psi game

### ISSUE THREAD

**Issue by aenimosity** [mtgred/netrunner#5031]
Encountered Konjin with Makler installed. Runner and Corp both pay 1. Makler gained 1 credit.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Next time it happens, can you snap a screenshot?

**Comment by francescopellegrini** [comment]
Might as well close this.
