### ISSUE TITLE
Turntable + Project Vacheron

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#5036]
When I used Turntable to swap a Project Vacheron that the corp had scored into my score area:

- No counters were added to Vacheron, when it should have.
- No points were added to my total. (Which would be correct, if the first point had happened correctly.)
- I was unable to use /counter a # to add counter to Vacheron.

**Comment by Kubik161** [comment]
@NoahTheDuke retested, works correctly. You have fixed it few weeks ago :) Should be closed.
