### ISSUE TITLE
Hunting Grounds non-functional with Konjin

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5037]
419 has Hunting Grounds installed. Corp has Konjin installed on a remote. Run remote, click Hunting Grounds to avoid encounter, no message appears in the chat to indicate that the effect has taken place - though - the on encounter itself also did not seem to trigger. Not sure how Konjin is implemented since it's not a sub that fires.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
