### ISSUE TITLE
"Ganked" not implemented?

### ISSUE THREAD

**Issue by Itachi18** [mtgred/netrunner#5038]
Behaviour: When the runner accesses "Ganked", it gives the runner the option to trash it.  It doesn't give the corp the option to trash to have the runner encounter a piece of ice.  

I did notice that "Ganked" doesn't appear in the list of upgrades in netrunner/src/clj/game/cards/upgrades.clj.

**Comment by NoahTheDuke** [comment]
Yeah it’s not implemented at the moment. Does it not have a note saying so when you hover the card? It should

**Comment by Itachi18** [comment]
I see it now - yes it does.

**Comment by rdlester** [comment]
Is this fixed? The note is no longer appearing but it's still not triggering.

**Comment by NoahTheDuke** [comment]
Next time this happens, can you take a screenshot? When I look at the card, I see the implementation note saying it's unimplemented.
