### ISSUE TITLE
Same card accessed twice on HQ multiaccess

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#5039]
Corp on Sportsmetal vs Legwork. One Biotic Labor in HQ. Runner accesses Biotic Labor, Agenda -> corp draws 2 with no Biotic Labor drawn, runner accesses Biotic Labor again.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I couldn't recreate this. Closing for now. Post again if you figure it out?
