### ISSUE TITLE
(Thimblerig + Inversificator) AND Switcheroo = Game Crash

### ISSUE THREAD

**Issue by AIM-54-Phoenix** [mtgred/netrunner#5042]
How to repoduce:

1. Have 2 different servers with ICE
2. Have Thimblerig installed as ICE on one server, preferably outermost
3. Runner Runs with Inversificator
4. Rez Thimblerig
5. Break all subroutines with Inversificator
6. Corp has to click pass ICE
7. Corp (for unknown reason) has to decide after passing first, if he wants to swap thimblerig. Corp has to switch the Thimblerig with an ice in another server.
8. Inversificator triggers, click yes, choose any ICE.
9. Screen turns black.

Remarks:
1. We have two competing triggers: "When you pass an ice", one on each side. The Trigger on the side who's active turn it is, should be triggered first but isn't currently. (Phrasing due to "An Offer You Can't refuse")
So the runner should normally decide first, if Thimblerig should be removed/swapped elsewhere.
 1.1. If this is a Pointer Thing, maybe this could fix the issue already?
 1.2. This issue would then still persist on "An Offer you can't refuse"
 1.3. I am not shure, if Thimblerig still triggers, when it gets swapped away.
2. The screen did not turn black on switches with ICE in the same server, at least we only tested this once, and the game did not crash then.
3. This issue might happen as well, if thimblerig triggers second, but can't confirm this on current state, I would be happy to investigate after Fixing the first issue.
4. Runner ID was Kit, in case somebody is unable to reproduce. I can provide a demo deck on runner side, on corp side I am pretty certain it is independent.

**Comment by NoahTheDuke** [comment]
Thanks for this detailed report! Very helpful
