### ISSUE TITLE
Gang sign with Maw trash = stuck in "no current run" 

### ISSUE THREAD

**Issue by Kubik161** [mtgred/netrunner#5043]
Situation:
1. Corp scores agenda
2. Leela triggers, returns ICE to HQ
3. gang sign access to operation in HQ
4. maw triggers, trashes returned ICE
5. there is Mwanza on HQ, but no more cards to access
6. game now thinks that we are inside "No current run"
7. Run cannot be ended, close prompt didn't work

Screenshot attached.

Maybe related to #3399 ? It was similar bug with Kim trashing cards from Gang Sign access. 

![stuck-jinteki](https://user-images.githubusercontent.com/30665071/79045664-8ae5f700-7c0c-11ea-9f3b-a9aac757ff40.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I’ll have a look

**Comment by NoahTheDuke** [comment]
There’s an “/end-run” command I think which could help in this situation.

**Comment by plural** [comment]
yeah, this happened in one of my games and we had to use /end-run to get out of it, but it worked.  They rezzed mwanza, scored an agenda and i activated all 3 of my gang signs.  Yikes!  :)
