### ISSUE TITLE
Boomerang returns to stack from heap with rezzed Blacklist

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#5044]
With Blacklist rezzed and installed, Boomerang's triggered ability to return from the heap to the stack still returns Boomerang to the heap to the stack.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
I'm also experiencing issues with Blacklist, namely nor the Runner nor the Corp are able to trash it once rezzed...

**Comment by NoahTheDuke** [comment]
So I’ve heard. Thanks for letting me know!

**Comment by NoahTheDuke** [comment]
So it turns out that Boomerang doesn't actually go back to the deck, it just says it does. I have a fix up for this, but rest assured that the bug is only visual.
