### ISSUE TITLE
Mind Game redirect

### ISSUE THREAD

**Issue by LessRekkless** [mtgred/netrunner#5047]
When **Mind Game**'s subroutine fires, the runner is redirected to the proper server, and can approach (and therefore jack out).  However, if the runner chooses to continue and encounter:
1. the log states that the runner is encountering **Mind Game** again, instead of the ICE they're supposed to. 
2. Runner cards interact as if they were encountering Mind Game (eg **Black Orchestra**, **Ice Carver**, **MKUltra**).
3. The Corp button prompt "Fire unbroken subroutines" works properly (eg. Anansi subroutines fire).
![Capture](https://user-images.githubusercontent.com/34615525/79166223-b73b7800-7db2-11ea-98d9-94f001c49ff5.PNG)
4. The runner passes the correct ICE and will complete the run in the correct server (eg. Archives). We did not check to see what happens if there is another ICE after the outmost ICE.

**Comment by iref** [comment]
Here is screenshot from runner side:

![Screenshot from 2020-04-14 00-05-07](https://user-images.githubusercontent.com/1167154/79166461-86286b00-7de5-11ea-89df-00af2491c87d.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by LessRekkless** [comment]
Subsequent testing:
1. If the first ICE is unrezzed, the Runner is treated as if they were approaching an ICE for the very first time (ie, they aren't given the option to jack out, only undo click).  The Corp is given the option to rez the ICE and this immediately transitions to the encounter phase.
2. Encountering a second ICE after the redirect functions properly.
