### ISSUE TITLE
Daily Business Show and La Costa Grid Freaky Friday

### ISSUE THREAD

**Issue by erinrockabitch** [mtgred/netrunner#5049]
I had a DBS and an LCG rezzed and they seemed to have swapped spots. The DBS prompt would advance a card in the remote and the La Costa prompt (and clicking on the grid) would bottomdeck a card from HQ

![DBS LCG](https://user-images.githubusercontent.com/9438049/79289635-d233e800-7e97-11ea-813a-221a3cf952df.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! “Freaky Friday” lmao
