### ISSUE TITLE
Enhanced Vision doesn't reveal card. 

### ISSUE THREAD

**Issue by martinimon** [mtgred/netrunner#5052]
Enhanced vision does not make the corp reveal a random card from HQ upon the first (or any) successful run each turn. 
Chat log will say "NAME force the corp to reveal" but not reveal a card at random, nor prompt the corp to reveal a card. Once prompted that the corp has been forced without revealing a card the access to the server happens normally. 

This error has occured multiple times over various livestreams, and can be seen on the timestamp of hte linked video; https://www.youtube.com/watch?v=L5m6NO40cMc&feature=youtu.be&t=6272
In the case in our video the chat log is "Just Play Better force the corp to reveal" followed by card accesses from targeted server.

This should reveal a random card from HQ upon first succesful run each turn.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by martinimon** [comment]
Cool, thanks can finally play our favourite card!
