### ISSUE TITLE
Using AgInfusion ID ability does not function correctly

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#5056]
When using AgInfusion's ID ability, I receive the message "Current phase: Approach Ice", even if no ice is installed on the server the runner is redirected to. Clicking the runner through takes them to the "approach server" step, but the runner's option to approach the server is greyed out, and they can't click through to make a successful run. Attached are 5 screenshots showing the prompts we get from both sides (with the chat log showing in which my opponent describes what prompts they're seeing)

![aginfusionbug2](https://user-images.githubusercontent.com/44246400/79700420-579b0c00-828d-11ea-9494-22f4350f1a21.png)
![aginfusionbug3](https://user-images.githubusercontent.com/44246400/79700421-58cc3900-828d-11ea-8d48-eec566bcefd1.png)
![aginfusionbug4](https://user-images.githubusercontent.com/44246400/79700423-5964cf80-828d-11ea-9f90-f4ff6e5fd83a.png)

![aginfusionbug5](https://user-images.githubusercontent.com/44246400/79700417-536eee80-828d-11ea-9426-7b853203f49e.png)
![aginfusionbug1](https://user-images.githubusercontent.com/44246400/79700418-55d14880-828d-11ea-9ada-a88ab2559995.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
