### ISSUE TITLE
Credits from cards not accounted for while resolving Crypt

### ISSUE THREAD

**Issue by rdlester** [mtgred/netrunner#5058]
Example: With Paladin Poemu installed, Crypt should give the option to use credits from it when using its tutoring ability. It should also account for those credits when determining if a card can be installed (eg. you have no credits in your pool but 2 on Poemu, and should be able to spend those to install eg. Pelangi).

I saw this issue for the latter case, so I'm not sure if the issue is that no option is given to spend credits when resolving, or that Crypt fails resolution if credits from cards are needed to meet the install cost.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
