### ISSUE TITLE
Street Magic does not exit from prompt on selecting an ETR routine

### ISSUE THREAD

**Issue by rdlester** [mtgred/netrunner#5059]
Once the ETR is selected, the encounter is over and remaining routines should not fire. Currently, the only way to do this in the client is to /close-prompt.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Glad someone is playing with this card

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Can you give me more details? Maybe snap a picture next time this happens?
