### ISSUE TITLE
Cannot install agendas or assets on a server created before starting the game

### ISSUE THREAD

**Issue by josemgarcia** [mtgred/netrunner#506]
So, I tried to play with NEXT Design, and manually added clicks to install ICE as per identity's text. However, if I install a piece of ICE in a new remote, I cannot install agendas or assets on that server (#0) during the regular game. I can install more ICE and upgrades, though.

**Comment by queueseven** [comment]
I tested this and could not reproduce this. I created a new remote server with an ICE, started my turn, and could install an agenda in that new server just fine.

**Comment by josemgarcia** [comment]
Tried again and apparently it works this time. Closing the issue.
