### ISSUE TITLE
Improved Tracers minor bug

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5062]
When there is an Improved Tracers scored, the addition to the base strength of the trace on an ice is not included in the prompt shown to the corp at the point where they can pump it. However, the +1 to base strength *is* shown in the log and the trace is calculated correctly.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't recreate this. Next time it happens, can you snap a pic for me?

**Comment by p4ulyg** [comment]
![Screenshot 2020-05-03 at 11 07 21](https://user-images.githubusercontent.com/31340324/80911515-b7ce8b00-8d2e-11ea-9076-a3711230ce6f.png)

Here's an example. Whilst the log shows the trace correctly as starting at 6 (5+1), the prompt to the corp suggests that the trace is starting from base strength 5.

**Comment by NoahTheDuke** [comment]
Huh! Okay, I’ll try thT
