### ISSUE TITLE
Unable to Delete Decks

### ISSUE THREAD

**Issue by analyzechris** [mtgred/netrunner#5065]
The "Confirm Delete" button doesn't have any effect on the following platforms:

**Mac OS X 10.15.2**
- Chrome – 81.0.4044.129
- FireFox – 71.0
- Safari – 13.0.4 

I've tried both old and new decks.

**Comment by francescopellegrini** [comment]
I'm also experiencing this.
From what I can see all requests to the following endpoint end up in 404: ` https://www.jinteki.net/data/validator/<deck_id>`

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Did 5ddfec0 fix this?

**Comment by NoahTheDuke** [comment]
yep! good catch
