### ISSUE TITLE
Unable to sign up as a new user

### ISSUE THREAD

**Issue by Erwan-r1** [mtgred/netrunner#5067]
Hi, 

It's been a very long time since I played Netrunner, and I wanted to give it a try online with Jinteki.net.

When I want to create a new account, the sign up form tells me that "Passwords must match"... I tried everything, including the auto generating password, but nothing seems to work. I tried on Windows 10 with Chrome an IE, and on my iPhone with Chrome and Safari, it's always the same message. Tried with very simple passwords suche as "a" and complex ones, the same.

Tried to search the issues but couldn't find anything like that. 

Can anyone help me with this ?

Thanks a lot.

Erwan

**Comment by NoahTheDuke** [comment]
Sounds like a bug! I just changed the logic on Wednesday, so I'm unsurprised. I'll see what I can do!
