### ISSUE TITLE
Runner is not tagged when playing Acme

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#5074]
Noticed it now when playing Acme, even though the ID ability works, it's the only time that the runner is considered "tagged". Even if they receive tags from elsewhere, they are marked and the stat says "N Tags", but the blue exclamation mark isn't there and cards like Closed Accounts and Exchange of Information don't work and can't be played. Runner also can't remove tags if they don't have the blue "tagged" symbol.

**Comment by NoahTheDuke** [comment]
Can you explain this better? I don't quite understand. How does Acme interact with playing operations? Those can't be played during a run.

**Comment by anarchomushroom** [comment]
So the Acme ability works fine, but for example, I was playing against Sunny and my opponent didn't win the trace with Security Nexus, so ended the run and took a tag. Except they couldn't clear the tag, despite the fact that their tag indicator said "1 Tags". The same thing happened when I Sea Source'd them, they had two tags but couldn't remove the tag and I couldn't use any "If the runner is tagged" cards like Closed Accounts.

**Comment by chmontgomery** [comment]
I experienced this as well. As ACME, giving the runner 1 tag (say with Sea Source), doesn't consider them "tagged", so you can't followup with Closed Accounts, EoI, etc. Manual fix is required to have the runner give themselves another tag, do tag punishment, and then manually remove it.

**Comment by NBKelly** [comment]
I think the conditions surrounding this issue are no longer reproducible, so I'm closing this issue as stale. If anything like this happens again, please create a new issue.
