### ISSUE TITLE
Maya trigger occasionally fires when it shouldn't

### ISSUE THREAD

**Issue by mgsholte** [mtgred/netrunner#5075]
The text for Maya says the decision to move a card to the bottom of R&D must be made immediately after accessing that card from R&D. If the runner access a card this way and declines to activate Maya and then accesses it again later, then they are re-prompted to activate the Maya trigger.

Example: 
- run R&D
- access a card from R&D
- trash that card
- decline to use the Maya trigger
- run archives
- the game prompts the runner to trigger Maya again for the card that was just trashed

A more contrived scenario:
- ensure the corp has no cards in hand
- run R&D
- access a card from R&D
- decline to trash that card
- decline to use the Maya trigger
- install Equivocation
- run R&D again
- use Equivocation to force the corp to draw the card that was previously accessed
- run HQ
- when the runner accesses the card in HQ, the game will prompt to use Maya

I think this only happens if the runner re-accesses a card on the same turn that they declined to use Maya on it, but I can't confirm that.

**Comment by NoahTheDuke** [comment]
Excellent, thank you!

**Comment by Diogened** [comment]
2020-08-26
I recently noticed that Maya give a prompt after a successful run on HQ. It allowed to use that card ability on a card located in HQ.

**Comment by NBKelly** [comment]
Closed as completed via 71b5c9b and #6198
