### ISSUE TITLE
Howler does not allow jacking out or using icebreakers on new ICE

### ISSUE THREAD

**Issue by hillmark61** [mtgred/netrunner#5079]
Corp rez'd Howler, the runner could not break the ICE, so the subroutine fired.  Corp brought out Heimdall 1.0 and it was placed appropriately after Howler.  At that point the game showed the runner as encountering Heimdall 1.0 and restricted runner options to only "bypass the ice" or "let all subroutines fire".  After Howler subroutines completed there should have been an opportunity to jack out or engage with Heimdall 1.0 normally (using icebreakers to break the subroutine).  We used /undo-turn and tried several times to have the game work correctly, but instead choosing "bypass the ice" would bypass Heimdall 1.0 completely, and choosing "let subroutines fire" would run the Heimdall 1.0 subroutines.  There was never a way to use an icebreaker to break the subroutines, and there was not an option to jack out before encountering Heimdall 1.0.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
