### ISSUE TITLE
Hippo Trashes Clash with Acme's Ability

### ISSUE THREAD

**Issue by LuteTheArrow** [mtgred/netrunner#5080]
An opponent used Hippo to trash outermost ices and the "considered as tagged" condition remained permanently, and it was impossible to remove with the subtract button of the tag menu. This provoked that we had to work around my opponent being permanently tagged.

Thank you, and thanks for the amazing work.

**Comment by Kubik161** [comment]
@NoahTheDuke retested, works correctly. This issue should be closed.
