### ISSUE TITLE
Rejoined as myself twice

### ISSUE THREAD

**Issue by tssmits** [mtgred/netrunner#5081]
Hi! (First of all thanks so much for developing this!!)

I ran into a little bug it seems.

Me running firefox, my opponent running Chrome. In the developer console i see a message about a socket having closed, and not reconnection. So i restart the browser. Can't rejoin the game. My opponent restarts the browser, now we can both rejoin. But when we do, I am picked as both players:

![image](https://user-images.githubusercontent.com/6974879/81018474-e2bafb00-8e64-11ea-8fd6-a791578307bd.png)

Is there any more info that you would need?

Edit:

Also, I can't start a new game now, even after logging out and signing back in.

**Comment by LuteTheArrow** [comment]
Same happened to me, I finished a game and left, my oponent didn't appear to leave the game and I couldn't join other games. I rejoined to see if this fixed it and got stuck as the two players, not being able to start or join games.

**Comment by tssmits** [comment]
After <1hour the game seemed to have been removed, and the "new game" button was enabled again.
