### ISSUE TITLE
Need to reconnect after most "End Turn" or "Trash Resource" prompts.

### ISSUE THREAD

**Issue by LuteTheArrow** [mtgred/netrunner#5087]
Runner prompts dont work.
I experienced this playing as runner as Kabonesa vs Mirrormorph, and later while playing as Acme vs an Adam deck, runners usually could press "End turn" but it didn't work until reconnect.

**Comment by NoahTheDuke** [comment]
Thanks for the report. This is the highest priority and I am working hard to fix it.

**Comment by NBKelly** [comment]
Closed as too old to reproduce
