### ISSUE TITLE
Red Planet Couriers doesn`t clear info correctly

### ISSUE THREAD

**Issue by Dreadnote** [mtgred/netrunner#5090]
Red Planet Couriers doesn`t update subs on Masvingo correctly. so when it used, but no new advancement tokens still placed - Masvingo shows incorrect number of subs. (In example 1 token got moved, but Masvingo still have 1 ETR subs. And its relevant to even 11-token-Masvingos)
Maybe this is bug with Masvingo itself.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
