### ISSUE TITLE
No Alice Merchant trigger on second run on Archives when first was fizzled by Crisium

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5092]
Steps:
- Have a Crisium on Archives
- Alice runs Archives and trashes the Crisum
- Alice runs Archives again
- Alice ability should fire, but does not

(In the example screenshot here, clicks 1 and 2 were install DDOS and running HQ)
![Screenshot 2020-05-06 at 14 45 45](https://user-images.githubusercontent.com/31340324/81184860-d2ac3400-8fa8-11ea-8cdf-016062bc512e.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
