### ISSUE TITLE
Gauntlet interaction with trashing ices

### ISSUE THREAD

**Issue by CapitanShinChan** [mtgred/netrunner#5093]
Case:
1. Hippo and Gauntlet are installed.
2. Run HQ, with 1 ice protecting it.
3. Break all the subroutines in the ice and trash it
4. Approach HQ, the selector for Gauntlet appears, but it doesn't allow to choose more than 0.

Gauntlet only cares about ices for which all subroutines have been broken during that run, doesn't matter if they've been trashed during that run.

**Comment by NoahTheDuke** [comment]
According to the [FAQ](https://netrunnerdb.com/en/card/11063), "The Gauntlet can count derezzed pieces of ice on which all subroutines were broken, but it cannot count trashed pieces of ice because they are no longer protecting HQ."
