### ISSUE TITLE
Action before access button is non-functional

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5094]
NGO front in remote, runner runs, hit 'action before access', no prompt to take actions, runner accesses NGO front.

**Comment by NoahTheDuke** [comment]
Ah damn. Thanks for the report.

**Comment by JessicaEArmstrong** [comment]
Just as an update, it also isn't working on centrals, not allowing corps the window to rez Mwanza or other such upgrade before access!

**Comment by Kubik161** [comment]
@NoahTheDuke Action before access are working as expected. This issue should be closed.
