### ISSUE TITLE
Paige Piper and Frantic Coding interaction

### ISSUE THREAD

**Issue by marc-jones** [mtgred/netrunner#5096]
It's the same issue as the closed [#2190](https://github.com/mtgred/netrunner/issues/2190), namely, Paige Piper should interrupt and shuffle the remaining 9 cards you look at with Frantic Coding into the deck instead of trashing them. Current behaviour is that they're trashed.

However, I'm not sure if this is due to a change to the rules / an errata.

**Comment by NoahTheDuke** [comment]
Do you have any additional details? I can't reproduce this.

**Comment by marc-jones** [comment]
I apologise, each time I "experienced" the bug I must have installed earlier in the turn and not realised it. Many thanks for looking into it.

**Comment by NoahTheDuke** [comment]
If it happens again, snap a pic! There might still be a bug lurking.
