### ISSUE TITLE
White Hat doesn't reveal cards in chat log

### ISSUE THREAD

**Issue by JessicaEArmstrong** [mtgred/netrunner#5097]
Hey!

So White Hate 'reveals' cards, and then shows the cards shuffled back in the chat, but doesn't show the cards initially revealed when this should be open information. 

The runner still sees them, and the corp can obviously see HQ all the time, but it means spectators can't, and if the players need to refer back, they are missing!

Thanks :)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
