### ISSUE TITLE
Orion and conspiracy breakers

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5099]
Hitting an Orion with multiple conspiracy breakers in the bin, the runner is only prompted to install one of them (not sure what affects which one) rather than all.

**Comment by NoahTheDuke** [comment]
Thanks for the report! If you see this again, could you snap a pic?

**Comment by lostgeek** [comment]
I think I got, what you're describing. When the Runner now runs Orion, they get 3 separate prompts for Paperclip, MKUltra, and Black Orchestra.
