### ISSUE TITLE
Casual decks shown as "Standard Legal"

### ISSUE THREAD

**Issue by Bradicalwilcox** [mtgred/netrunner#5103]
While starting in a casual lobby with standard non-legal decks (e.g. rotated ID's) the deck selections are shown as "Standard Legal" as opposed to "Casual Legal" in the lobby deck selection display.

![Casual Bug](https://user-images.githubusercontent.com/65184601/81589740-4f5f5980-937f-11ea-8b1e-3fd4b213f0a8.png)
![Deck Selection](https://user-images.githubusercontent.com/65184601/81589757-55553a80-937f-11ea-8bff-45ddcd896b37.png)

OS: Windows 10 Version 1809 (Build 17763.1098)
Browsers: Vivaldi 2.6.1566.44 (Stable channel) (32-bit)
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by jwarwick** [comment]
Fixed by #5402
