### ISSUE TITLE
Peace In Our Time playable after Agenda Score

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#5110]
EricF spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 2.
EricF scores SSL Endorsement and gains 3 agenda points.
EricF is ending their turn 8 with 2  and 4 cards in HQ.
VitarZ started their turn 8 with 6  and 4 cards in their Grip.
VitarZ uses Rezeki to gain 1 .
VitarZ uses Rezeki to gain 1 .
VitarZ spends  and pays 1  to play Peace in Our Time.
VitarZ uses Peace in Our Time to gain 10 . The Corp gains 5 .
VitarZ spends  to use Runner Basic Action Card to draw 1 card.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
