### ISSUE TITLE
Kasi String does not trigger 

### ISSUE THREAD

**Issue by willybn1** [mtgred/netrunner#5111]
Hi ... i installed Kasi String and ran on a remote but the Power Counter did not add. i accesses Jahinda and trashed her on the run. 
I didn't think to try manual until after the turn ended and it didn't give me an option so not sure whether adding manually is possible (someone in chat suggests it is) or whether adding a fourth with trigger the 'add as a one point agenda'
thanks for your work t keep this going!
Will

**Comment by Kubik161** [comment]
Could you please submit log from that game? (Go to Stats tab on jinteki, find correct game, click View log, and copy & paste). Thanks :)

**Comment by willybn1** [comment]
Sure .... apologies I’ve gone out now so Will do that in a couple of hours. Thanks. Will. 


Sent from Yahoo Mail for iPhone


On Saturday, May 16, 2020, 10:34 am, Kubik161 <notifications@github.com> wrote:




Could you please submit log from that game? (Go to Stats tab on jinteki, find correct game, click View log, and copy & paste). Thanks :)

**Comment by willybn1** [comment]
beginning of Turn 6 below in red. 

thanks
Will. 


aladwagon has created the game.willybn1 joined the game.saladwagon takes a mulligan.willybn1 takes a mulligan.willybn1heysaladwagon started their turn 1 with 5  and 5 cards in HQ.saladwagon spends  and pays 5  to play Hedge Fund.saladwagon uses Hedge Fund to gain 9 .saladwagon spends  and pays 5  to play Hedge Fund.saladwagon uses Hedge Fund to gain 9 .saladwagon spends  and pays 0  to install ICE protecting R&D.saladwagon is ending their turn 1 with 13  and 3 cards in HQ.willybn1 started their turn 1 with 5  and 5 cards in their Grip.willybn1 spends  to use Runner Basic Action Card to draw 1 card.willybn1 spends  and pays 3  to install Keiko.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  to install Paladin Poemu.willybn1 spends  to make a run on HQ.willybn1 approaches HQ.saladwagon has no further action.willybn1 accesses Vanilla from HQ.willybn1 is ending their turn 1 with 2  and 4 cards in their Grip.willybn1 gains 2  and flips their identity to Hoshiko Shiro: Mahou Shoujo.saladwagon started their turn 2 with 13  and 3 cards in HQ.saladwagon spends  and pays 0  to install ICE protecting HQ.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon is ending their turn 2 with 13  and 5 cards in HQ.willybn1 started their turn 2 with 4  and 4 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 spends  to use Runner Basic Action Card to draw 1 card.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Paladin Poemu and 1  from their credit pool to install Boomerang.willybn1 uses Boomerang to target ICE protecting R&D at position 0.willybn1 spends  to use Runner Basic Action Card to draw 1 card.willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 discards Stargate from their Grip at end of turn.willybn1 is ending their turn 2 with 4  and 5 cards in their Grip.willybn1 flips their identity to Hoshiko Shiro: Untold Protagonist.saladwagon started their turn 3 with 13  and 5 cards in HQ.saladwagon spends  and pays 0  to install ICE protecting Server 1 (new remote).saladwagon spends  to install a card in Server 1.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon is ending their turn 3 with 13  and 5 cards in HQ.willybn1 started their turn 3 with 4  and 5 cards in their Grip.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Paladin Poemu and 3  from their credit pool to install Stargate.willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 spends  and pays 3  to install DreamNet.willybn1 spends  to use Stargate to make a run on R&D.willybn1 approaches ICE protecting R&D at position 0.saladwagon pays 0  to rez Vanilla.willybn1 encounters Vanilla protecting R&D at position 0.willybn1 trashes Boomerang to use Boomerang to break 1 subroutine on Vanilla (" End the run").willybn1 has no further action.willybn1 passes Vanilla protecting R&D at position 0.willybn1 approaches R&D.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card.willybn1 must use the replacement effect from Stargate.willybn1 uses Stargate to reveal Hagen, Project Vitruvius, Gatekeeper.willybn1 uses Stargate to trash Hagen.willybn1 uses Boomerang to shuffle a copy of Boomerang back into the Stack.willybn1 is ending their turn 3 with 0  and 4 cards in their Grip.saladwagon started their turn 4 with 13  and 5 cards in HQ.saladwagon spends  to install a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon is ending their turn 4 with 11  and 5 cards in HQ.willybn1 started their turn 4 with 0  and 4 cards in their Grip.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 spends  and pays 1  to play I've Had Worse.willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Paladin Poemu to install Mystic Maemi.willybn1 is ending their turn 4 with 2  and 5 cards in their Grip.saladwagon started their turn 5 with 11  and 5 cards in HQ.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon scores Global Food Initiative and gains 3 agenda points.saladwagon uses Sportsmetal: Go Big or Go Home to gain 2 credits.saladwagon discards 1 card from HQ at end of turn.saladwagon is ending their turn 5 with 10  and 5 cards in HQ.willybn1 started their turn 5 with 2  and 5 cards in their Grip.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 spends  to make a run on Archives.willybn1 approaches Archives.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card.willybn1 accesses everything else in Archives.willybn1 spends  to use Runner Basic Action Card to draw 1 card.willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 discards Odore, Keiko from their Grip at end of turn.willybn1 is ending their turn 5 with 4  and 5 cards in their Grip.willybn1 gains 2  and flips their identity to Hoshiko Shiro: Mahou Shoujo.saladwagon started their turn 6 with 10  and 5 cards in HQ.saladwagon spends  to install a card in Server 2 (new remote).saladwagon spends  to install a card in Server 3 (new remote).saladwagon pays 0  to rez Rashida Jaheem.saladwagon derezzes Rashida Jaheem.saladwagon pays 1  to rez Tranquility Home Grid.willybn1:)saladwagon spends  and pays 1  to install ICE protecting Server 1.saladwagon is ending their turn 6 with 8  and 3 cards in HQ.willybn1 started their turn 6 with 6  and 5 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Paladin Poemu to install Kasi String.willybn1 spends  and pays 2  from Mystic Maemi to play Dirty Laundry.willybn1 approaches Server 2.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 accesses Rashida Jaheem from Server 2.willybn1 pays 1  to trash Rashida Jaheem from Server 2.willybn1 uses Dirty Laundry to gain 5 .willybn1 spends  to make a run on Server 3.willybn1 approaches Server 3.saladwagon has no further action.willybn1 accesses Rashida Jaheem from Server 3.willybn1 pays 1  to trash Rashida Jaheem from Server 3.willybn1does Kasi String not trigger?willybn1 spends  to use Runner Basic Action Card to gain 1 .willybn1 is ending their turn 6 with 11  and 5 cards in their Grip.saladwagonhmmm. can you do it manually?saladwagon started their turn 7 with 8  and 3 cards in HQ.willybn1no. doesnt appear sowillybn1npsaladwagonyeesh. sorrysaladwagon spends  to install a card in Server 1.saladwagon uses Tranquility Home Grid to gain 2 .saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon is ending their turn 7 with 8  and 3 cards in HQ.willybn1 started their turn 7 with 11  and 5 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Mystic Maemi to play I've Had Worse.willybn1 spends  and pays 2  from Paladin Poemu and 2  from their credit pool to install Odore.willybn1 spends  and pays 4  to install Abagnale.willybn1 spends  to make a run on HQ.willybn1 approaches ICE protecting HQ at position 0.saladwagon pays 0  to rez Vanilla.willybn1 encounters Vanilla protecting HQ at position 0.willybn1 indicates to fire all unbroken subroutines on Vanilla.saladwagon uses Vanilla to end the run.saladwagon resolves 1 unbroken subroutine on Vanilla (" End the run").willybn1 discards Paladin Poemu from their Grip at end of turn.willybn1 is ending their turn 7 with 5  and 5 cards in their Grip.willybn1 flips their identity to Hoshiko Shiro: Untold Protagonist.saladwagon started their turn 8 with 8  and 3 cards in HQ.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon scores Project Vitruvius and gains 2 agenda points.saladwagon uses Sportsmetal: Go Big or Go Home to gain 2 credits.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  to install a card in Server 1.saladwagon uses Tranquility Home Grid to gain 2 .saladwagon is ending their turn 8 with 11  and 4 cards in HQ.willybn1 started their turn 8 with 5  and 5 cards in their Grip.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Mystic Maemi to play I've Had Worse.willybn1 spends  and pays 1  from Paladin Poemu and 1  from their credit pool to install Corroder.willybn1 spends  and pays 2  to install Boomerang.willybn1 uses Boomerang to target ICE protecting Server 1 at position 1.willybn1 spends  to make a run on Server 1.willybn1 approaches ICE protecting Server 1 at position 1.saladwagon pays 3  to rez Gatekeeper.willybn1 encounters Gatekeeper protecting Server 1 at position 1.willybn1 trashes Boomerang to use Boomerang to break 2 subroutines on Gatekeeper (" Draw cards, reveal and shuffle agendas" and " End the run").willybn1 has no further action.willybn1 passes Gatekeeper protecting Server 1 at position 1.willybn1 approaches ICE protecting Server 1 at position 0.saladwagon pays 6  to rez Fairchild 3.0.saladwagon has no further action.willybn1 encounters Fairchild 3.0 protecting Server 1 at position 0.willybn1 trashes Abagnale to use Abagnale to bypass Fairchild 3.0.willybn1 passes Fairchild 3.0 protecting Server 1 at position 0.willybn1 approaches Server 1.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card.willybn1 accesses Cyberdex Sandbox from Server 1.willybn1 steals Cyberdex Sandbox and gains 2 agenda points.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.saladwagon uses Sportsmetal: Go Big or Go Home to gain 2 credits.willybn1 accesses Tranquility Home Grid from Server 1.willybn1 uses Boomerang to shuffle a copy of Boomerang back into the Stack.willybn1 discards Mystic Maemi from their Grip at end of turn.willybn1 is ending their turn 8 with 3  and 5 cards in their Grip.willybn1 gains 2  and flips their identity to Hoshiko Shiro: Mahou Shoujo.saladwagon started their turn 9 with 4  and 4 cards in HQ.saladwagon spends  to install a card in Server 1.!saladwagon uses a command: /undo-clicksaladwagon spends  to install a card in Server 4 (new remote).saladwagon uses Advanced Assembly Lines to gain 3 .saladwagon pays 1  to rez Advanced Assembly Lines.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  and pays 2  to install ICE protecting Server 1.saladwagon is ending their turn 9 with 4  and 4 cards in HQ.willybn1 started their turn 9 with 5  and 5 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 spends  to use Stargate to make a run on R&D.willybn1 approaches Vanilla protecting R&D at position 0.willybn1 encounters Vanilla protecting R&D at position 0.willybn1 pays 1  to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting R&D at position 0.willybn1 approaches R&D.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 must use the replacement effect from Stargate.willybn1 uses Stargate to reveal Biotic Labor, Drafter, Drafter.willybn1 uses Stargate to trash Biotic Labor.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 2  from Mystic Maemi to play Dirty Laundry.willybn1 approaches Vanilla protecting HQ at position 0.saladwagon has no further action.willybn1 encounters Vanilla protecting HQ at position 0.willybn1 pays 1  to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting HQ at position 0.willybn1 approaches HQ.saladwagon has no further action.willybn1 accesses NGO Front from HQ.willybn1 pays 1  to trash NGO Front from HQ.willybn1 uses Dirty Laundry to gain 5 .willybn1 spends  and pays 2  from Paladin Poemu to install Hippo.willybn1 spends  and pays 1  to install Trickster Taka.willybn1 is ending their turn 9 with 7  and 4 cards in their Grip.saladwagon started their turn 10 with 4  and 3 cards in HQ.saladwagon spends  to install a card in Server 1.saladwagon uses Tranquility Home Grid to gain 2 .saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  and pays 1  to install ICE protecting R&D.saladwagon is ending their turn 10 with 5  and 3 cards in HQ.willybn1 started their turn 10 with 7  and 4 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.willybn1thinkingsaladwagonnpwillybn1 spends  to use Stargate to make a run on R&D.willybn1 approaches ICE protecting R&D at position 1.willybn1 passes ICE protecting R&D at position 1.willybn1 approaches Vanilla protecting R&D at position 0.willybn1 encounters Vanilla protecting R&D at position 0.willybn1 uses Keiko to gain 1 .willybn1 pays 1  from Trickster Taka to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting R&D at position 0.willybn1 approaches R&D.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 must use the replacement effect from Stargate.willybn1 uses Stargate to reveal Arella Salvatore, Gatekeeper, Arella Salvatore.willybn1 uses Stargate to trash top Arella Salvatore.willybn1 spends  to make a run on HQ.willybn1 approaches Vanilla protecting HQ at position 0.willybn1 encounters Vanilla protecting HQ at position 0.willybn1 pays 1  to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting HQ at position 0.willybn1 approaches HQ.saladwagon has no further action.willybn1 accesses NGO Front from HQ.willybn1 pays 1  to trash NGO Front from HQ.willybn1 spends  to use Runner Basic Action Card to draw 1 card.willybn1 spends  and pays 1  from Mystic Maemi and 4  from their credit pool to play Sure Gamble.willybn1 uses Sure Gamble to gain 9 .willybn1 discards Trickster Taka from their Grip at end of turn.willybn1 is ending their turn 10 with 11  and 5 cards in their Grip.saladwagon started their turn 11 with 5  and 2 cards in HQ.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon scores Hyperloop Extension and gains 1 agenda point.willybn1wpsaladwagon uses Hyperloop Extension to gain 3 .saladwagon uses Sportsmetal: Go Big or Go Home to gain 2 credits.saladwagon is ending their turn 11 with 7  and 3 cards in HQ.willybn1oh, 1 poinr!willybn1point!willybn1 started their turn 11 with 11  and 5 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.saladwagonhaha yepwillybn1 spends  to use Stargate to make a run on R&D.willybn1 approaches ICE protecting R&D at position 1.saladwagon pays 3  to rez Drafter.willybn1 encounters Drafter protecting R&D at position 1.willybn1 uses Keiko to gain 1 .willybn1 removes Hippo from the game to trash Drafter protecting R&D at position 1.willybn1 pays 1  from Trickster Taka and 2  from their credit pool to increase the strength of Odore to 3 and break all 2 subroutines on Drafter.willybn1 has no further action.willybn1 passes Drafter protecting R&D at position .willybn1 approaches Vanilla protecting R&D at position 0.saladwagon has no further action.willybn1 encounters Vanilla protecting R&D at position 0.willybn1 pays 1  to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting R&D at position 0.willybn1 approaches R&D.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 must use the replacement effect from Stargate.willybn1 uses Stargate to reveal Arella Salvatore, Cyberdex Virus Suite, Hyperloop Extension.willybn1 uses Stargate to trash Hyperloop Extension.willybn1 spends  and pays 2  from Paladin Poemu to install Hippo.willybn1 spends  to make a run on Archives.willybn1 approaches Archives.saladwagon has no further action.willybn1 accesses Hyperloop Extension from Archives.willybn1 steals Hyperloop Extension and gains 1 agenda point.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.saladwagon uses Hyperloop Extension to gain 3 .saladwagon uses Sportsmetal: Go Big or Go Home to draw 2 cards.willybn1 accesses everything else in Archives.willybn1 spends  and pays 2  from Mystic Maemi and 3  from their credit pool to play Sure Gamble.willybn1 uses Sure Gamble to gain 9 .willybn1 is ending their turn 11 with 15  and 5 cards in their Grip.saladwagon started their turn 12 with 7  and 5 cards in HQ.saladwagon spends  to install a card in Server 1.saladwagon uses Tranquility Home Grid to gain 2 .saladwagon spends  and pays 3  to install ICE protecting Server 1.saladwagon spends  and pays 1  to use Corp Basic Action Card to advance a card in Server 1.saladwagon is ending their turn 12 with 5  and 4 cards in HQ.willybn1 started their turn 12 with 15  and 5 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.willybn1 uses Keiko to gain 1 .willybn1 spends  and pays 1  from Mystic Maemi and 1  from their credit pool and trashes 1 resource (Kasi String) to play Isolation.willybn1 uses Isolation to gain 7 .willybn1 spends  and pays 3  to play Test Run.willybn1 uses Test Run to install a program from their Heap.willybn1 pays 0  to install Abagnale.willybn1 spends  to make a run on Server 1.willybn1 approaches ICE protecting Server 1 at position 3.saladwagon pays 3  to rez Gatekeeper.willybn1 encounters Gatekeeper protecting Server 1 at position 3.willybn1 removes Hippo from the game to trash Gatekeeper protecting Server 1 at position 3.willybn1 pays 2  from Trickster Taka and 4  from their credit pool to increase the strength of Abagnale to 6 and break all 2 subroutines on Gatekeeper.willybn1 has no further action.willybn1 passes Gatekeeper protecting Server 1 at position .willybn1 approaches ICE protecting Server 1 at position 2.willybn1 passes ICE protecting Server 1 at position 2.willybn1 approaches Gatekeeper protecting Server 1 at position 1.willybn1 encounters Gatekeeper protecting Server 1 at position 1.willybn1 pays 2  to use Abagnale to break all 2 subroutines on Gatekeeper.willybn1 has no further action.willybn1 passes Gatekeeper protecting Server 1 at position 1.willybn1 approaches Fairchild 3.0 protecting Server 1 at position 0.willybn1 encounters Fairchild 3.0 protecting Server 1 at position 0.willybn1 pays 7  to increase the strength of Abagnale to 6 and break all 3 subroutines on Fairchild 3.0.willybn1 has no further action.willybn1 passes Fairchild 3.0 protecting Server 1 at position 0.willybn1 approaches Server 1.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 accesses Cyberdex Sandbox from Server 1.willybn1 steals Cyberdex Sandbox and gains 2 agenda points.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.saladwagon uses Sportsmetal: Go Big or Go Home to gain 2 credits.willybn1 accesses Tranquility Home Grid from Server 1.willybn1 spends  and pays 2  from Paladin Poemu to install Hippo.willybn1 is ending their turn 12 with 6  and 4 cards in their Grip.willybn1 uses Abagnale to move Abagnale to the top of the stack.saladwagon started their turn 13 with 4  and 4 cards in HQ.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon spends  to use Corp Basic Action Card to draw 1 card.saladwagon discards 3 cards from HQ at end of turn.saladwagon is ending their turn 13 with 4  and 5 cards in HQ.willybn1 started their turn 13 with 6  and 4 cards in their Grip.willybn1 uses Hoshiko Shiro: Untold Protagonist to draw 1 card and lose 1 .willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.willybn1 spends  to use Stargate to make a run on R&D.willybn1 approaches Vanilla protecting R&D at position 0.willybn1 encounters Vanilla protecting R&D at position 0.willybn1 uses Keiko to gain 1 .willybn1 pays 1  from Trickster Taka to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting R&D at position 0.willybn1 approaches R&D.saladwagon has no further action.willybn1 uses DreamNet to draw 1 card and gain 1 .willybn1 must use the replacement effect from Stargate.willybn1 uses Stargate to reveal Biotic Labor, Drafter, Spiderweb.willybn1 uses Stargate to trash Biotic Labor.willybn1 spends  to make a run on HQ.willybn1 approaches Vanilla protecting HQ at position 0.willybn1 encounters Vanilla protecting HQ at position 0.willybn1 pays 1  from Trickster Taka to use Corroder to break all 1 subroutines on Vanilla.willybn1 has no further action.willybn1 passes Vanilla protecting HQ at position 0.willybn1 approaches HQ.saladwagon has no further action.willybn1 accesses Project Vitruvius from HQ.willybn1 steals Project Vitruvius and gains 2 agenda points.willybn1 wins the game.willybn1 uses Paladin Poemu to add 1  to itself.willybn1 uses Mystic Maemi to add 1  to itself.willybn1 uses Trickster Taka to add 1  to itself.saladwagonggsaladwagon has left the game.willybn1gg

    On Saturday, 16 May 2020, 10:34:42 BST, Kubik161 <notifications@github.com> wrote:  
 
 


Could you please submit log from that game? (Go to Stats tab on jinteki, find correct game, click View log, and copy & paste). Thanks :)
