### ISSUE TITLE
Only one boomerang shuffles after successful run

### ISSUE THREAD

**Issue by Kubik161** [mtgred/netrunner#5112]
I have used two boomerangs during run, run was successful, only one got shuffled. 

Expected behavior is both being shuffled back.

I assume, that our current implementation: 
```
   ... after boomerang is used...

(register-events
    ;; Boomerang is trashed at this point
    (find-card "Boomerang" (:discard (:runner @state)))

    ... etc ...
```
is selecting same card from discard every time. We should probably somehow track every copy of boomerang separately?

**Comment by NoahTheDuke** [comment]
Thanks for the report, and good point. The issue is that trashed cards have a new cid, so finding them becomes hard. I’ll have to think on this.
