### ISSUE TITLE
Adjusted Chronotype giving extra click even when no click is lost.

### ISSUE THREAD

**Issue by JessicaEArmstrong** [mtgred/netrunner#5119]
Hey!

So watching a few games with people recreating 2015 Netrunner, Adjusted Chronotype seems to be bugged. It is giving extra clicks even when the runner doesn't lose any. I have a screenshot of the log showing this, but during the game when I tried to recreate it, I couldn't get it to happen. It has happened in numerous games I've observed though.

Thanks! 

[Adjusted Chronotype.docx](https://github.com/mtgred/netrunner/files/4653309/Adjusted.Chronotype.docx)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by ban-tantale** [comment]
Hi there.
this issue appears here: 
https://youtu.be/nwKlKjxtg5Q?t=367
At the beginning of the turn, Theyla has 4 clicks.  When he spend his first click to draw, he gains an extra click.
