### ISSUE TITLE
issues with disconnects and being locked out of a game when leaving and trying to reconnect

### ISSUE THREAD

**Issue by maxmick6299** [mtgred/netrunner#5122]
![Capture](https://user-images.githubusercontent.com/65583965/82414460-f2713c80-9a2b-11ea-9d17-5e02fc5fc94d.PNG)
I very often get disconnected from the server and am unable to take actions until I leave and rejoin the game. When I say very often here I mean about 1/3 games. In many of those games, when I leave I am unable to rejoin or create a new game because it says I am still in the current game. Sometimes it says multiple copies of me are still in that game. No amount of CTRL + F5 restarting my browser or installing and using a new browser fixes this, and I can't replicate the issue consistently so I have no idea if something I am doing is causing it. Anyways other than that love the site! thanks!

**Comment by NBKelly** [comment]
Hi, I think the conditions relevant to this issue are no longer possible to reproduce (We still have network issues, but I think they're all different ones now), so I'm closing it as stale. If anything like this happens again, please create a new issue.
