### ISSUE TITLE
Using 'On The Lam' should not trigger Aniccam

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5123]
This is very much a rules edge case, but the NISEI rules team have confirmed that an On The Lam 'counter' does not return to being an Event card until after the trash and so Aniccam should not trigger from a usage of On The Lam. Currently on Jnet it does.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Looks like an issue with our handling of card counters.
