### ISSUE TITLE
Paule's Café ability cost is not logged

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#5126]
I saw this issue during a Stimhack run (if that matters), where the runner installed 3 programs, the log said (line after line) the cost of each program being installed (first discounted), but not that it cost them 1 credit to use each time.

But, it does appear that the cost is taken out of the Runner's credit pool correctly.

**Comment by lostgeek** [comment]
Thanks for the report. Credits have been calculated correctly, but the message was wrong. Has been fixed!
