### ISSUE TITLE
Overseer Matrix Interaction with MaxX

### ISSUE THREAD

**Issue by tanderson11** [mtgred/netrunner#5129]
I had an Overseer Matrix trigger (offer to let me tag the runner) from the cards trashed from MaxX stack. Unfortunately I can't narrow it down super well, but here was the setup:

Overseer matrix installed and rezzed in the root of R&D.
Overseer matrix installed and rezzed in a remote server.

And this caused the bugged triggers.

Cheers!

**Comment by tanderson11** [comment]
I opened up jnet in a second tab to test, and it is the overseer matrix rezzed in the root of R&D that caused the bug (remotes don't and HQ doesn't).

**Comment by NoahTheDuke** [comment]
Thanks for the report!
