### ISSUE TITLE
Boomerang does not shuffle on successful run if the targeted server changed

### ISSUE THREAD

**Issue by p4ulyg** [mtgred/netrunner#5130]
Issue title is I *think* what caused the problem but the particular scenario is below.

I put a Boomerang on a rezzed Crick on Archives and made an Omar run. I used Hippo to trash the Crick after breaking with Boomerang, and then Omar’d into R&D. The Boomerang did not shuffle back into the deck. We *think* this was caused by the targeted server changing due to Omar.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
