### ISSUE TITLE
Inversificator interaction with Kakugo

### ISSUE THREAD

**Issue by Protolich** [mtgred/netrunner#5143]
When breaking, passing and swapping Kakugo using Inversificator the runner should not take any damage. Instead damage occurs immediately before using the option to swap the ICE.

To reproduce:
Break Kakugo using Inversificator.

Expected result:
You can swap Kakugo with another piece of ICE, thereby avoiding the net damage.

Actual Result:
You take the net damage before choosing whether or not to swap the ICE.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
