### ISSUE TITLE
Power Shutdown Nisei 1.4 vs FAQ 4.0

### ISSUE THREAD

**Issue by Bradicalwilcox** [mtgred/netrunner#5144]
Power Shutdown is still operating according to the errata added in FAQ 4.0: X cannot exceed highest install cost among all programs/hardware (see issue #2556,#2557).  
According to Nisei Comprehensive rules 1.4 (page 2) this errata is removed, and the only limit on X should be the size of R&D.

https://nisei.net/files/Comprehensive_Rules.pdf

![Notes](https://user-images.githubusercontent.com/65184601/83068965-c27af800-a02e-11ea-9f7b-cb239bd97c09.png)

[Comprehensive_Rules.pdf](https://github.com/mtgred/netrunner/files/4691615/Comprehensive_Rules.pdf)

**Comment by lostgeek** [comment]
From https://nisei.net/files/Uprising_Release_Notes.pdf

**Power Shutdown**

The Organized Play team asked us to remove the functional errata adding a restriction to the values that could be chosen for X. We have done so, and now Power Shutdown​ can be used to trash the Corp’s entire deck just like it could before the errata was originally given. 

Old text:
Play only if the Runner made a run during his or her last turn. Trash X cards from the top of R&D. The Runner trashes 1 installed program or piece of hardware with an install cost of X or less. X is equal to or less than the highest install cost among all installed programs and pieces of hardware.

New text:
Play only if the Runner made a run during his or her last turn. Trash X cards from the top of R&D. The Runner trashes 1 installed program or piece of hardware with an install cost of X or less.

**Comment by Bradicalwilcox** [comment]
![Power Shutdown](https://user-images.githubusercontent.com/65184601/83144774-7aed7e00-a0b9-11ea-8778-77792a54a754.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
