### ISSUE TITLE
Some text boxes are too thin to show text on cards when using their abilities

### ISSUE THREAD

**Issue by LeonardQuirm** [mtgred/netrunner#5150]
The following was seen on Misdirection and Self-Modifying Code in a game on Tuesday 2nd June 2020.  There was also discussion on Slack for the same thing happening for Restructured Datapool.

A box appears underneath "Actions:" with the text "Trash" in it but following that is "Abilities" and the space for a box, but too thin to display any text.  Either the text is not being pulled for these cards (meaning the text box, automatically sizing, is just a tiny border gap) or the box is sizing too small, hiding the text in it.  The box is still clickable and performs the correct Ability for the card in each case I've seen.

Seen on Chrome 83.0.4103.61.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
@NoahTheDuke retested with SMC and Misdirection, has been fixed. This issue should be closed :)
