### ISSUE TITLE
Choosing "Everything else" first when accessing Archives accesses no other cards

### ISSUE THREAD

**Issue by LeonardQuirm** [mtgred/netrunner#5151]
Scenario witnessed (and repro'd by Noah Bogart):
- Play Deuces Wild
- For first action, expose an ICE then run on Archives
- Archives contains some Operations and a GFI.  On accessing Archives, the game asks if you want to access the GFI or Everything Else first.
- Choosing Everything Else immediately completes the Access step and moves you to choosing the second Deuces Wild action without accessing or stealing the GFI.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Looks like this actually comes from choosing "Everything else" first, which none of my tests handled! Whoops.
