### ISSUE TITLE
Surfer not swapping ice after first swap

### ISSUE THREAD

**Issue by metalgaiden** [mtgred/netrunner#5154]
When using surfer (with pelangi and paperclip) I had multiple instances of ice not swapping or saying it swapped without doing so. It seems like it occurred after the ice was swapped once regardless of if it was in the same run or not.

Here is a video I took on my third test: https://www.youtube.com/watch?v=RtHFxchP6Uw

I am using waterfox(firefox base) on windows and have found this bug in all of my (3) tests. I can provide more info and screenshots if you would like.

Just realized #5145 had the same issue (i searched for surf not surfer my bad) I'll leave this up since it has video if that helps.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Closing as duplicate.
