### ISSUE TITLE
Amazon industrial zone not automating any process nor reducing rez cost.

### ISSUE THREAD

**Issue by BakyraBA** [mtgred/netrunner#516]
http://www.acoo.net/card-detail/151/amazon-industrial-zone/

a dialog box could pop up when installing ice saying "rez ice with the cost reduced by 3?"

**Comment by queueseven** [comment]
Amazon Industrial Zone was implemented yesterday. Expect it to work with the next server update.

**Comment by mtgred** [comment]
The server has been updated.

**Comment by JoelCFC25** [comment]
Implemented at #507.
