### ISSUE TITLE
Possible bug between Fencer Fueno and Giordano Memorial Field

### ISSUE THREAD

**Issue by erinrockabitch** [mtgred/netrunner#5166]
We had an issue where the runner was not able to access cards / take actions after paying the GDM cost. We weren't able to figure out what caused it or how to work around it in the client but our best guess was some sort of negative interaction between FF and GDM. Relevent board state and chat log attached

![image](https://user-images.githubusercontent.com/9438049/85063042-880d0280-b177-11ea-874f-90c15f2db598.png)

houxflower uses Giordano Memorial Field to force the Runner to pay or end the run.
potat
potat
i am trying to click pay
potat has left the game.
Mokei has left the game.
potat rejoined the game.
potat
potat
sorry, disconnected
chouxflower
chouxflower
np
chouxflower
chouxflower
can you pay now?
potat
potat
yep
potat
potat
now I'm witing on corp triggers
!
chouxflower uses a command: /close-prompt
potat
potat
i might have clicked a few times
chouxflower
chouxflower
I can't do anything
!
potat uses a command: /close-prompt
!
chouxflower uses a command: /close-prompt
potat
potat
ah
potat
potat
got it
chouxflower
chouxflower
got it?
!
potat uses a command: /close-prompt
potat
potat
now access server button isn't doing anything
!
potat uses a command: /close-prompt
chouxflower
chouxflower
weird
chouxflower
chouxflower
/closes-prompt
!
chouxflower uses a command: /close-prompt
chouxflower
chouxflower
try undoing
!
potat uses a command: /undo-click
potat spends to make a run on Server 2.
potat approaches Gold Farmer protecting Server 2 at position 1.
chouxflower pays 3 to rez Giordano Memorial Field.
chouxflower has no further action.
potat trashes Simulchip and trashes 1 program (Euler) to use Simulchip to install a program.
potat pays 0 to install Euler.
potat encounters Gold Farmer protecting Server 2 at position 1.
potat spends a hosted virus counter from on Pelangi to use Pelangi to make Gold Farmer protecting Server 2 at position 1 gain Code Gate.
chouxflower uses Gold Farmer to force the runner to lose 1 for breaking printed subs.
chouxflower uses Gold Farmer to force the runner to lose 1 for breaking printed subs.
potat pays 0 to use Euler to break all 2 subroutines on Gold Farmer.
potat passes Gold Farmer protecting Server 2 at position 1.
potat approaches Gatekeeper protecting Server 2 at position 0.
potat encounters Gatekeeper protecting Server 2 at position 0.
potat pays 0 to use Euler to break all 2 subroutines on Gatekeeper.
potat passes Gatekeeper protecting Server 2 at position 0.
potat approaches Server 2.
chouxflower uses Giordano Memorial Field to force the Runner to pay or end the run.
potat
potat
not again
potat has left the game.
chouxflower
chouxflower
aiii
potat rejoined the game.
potat
potat
i wonder if it's to do with giordano with fencer down
potat
potat
do you normally have bugs with giordano
chouxflower
chouxflower
maybe
chouxflower
chouxflower
not normally
potat
potat
neither

**Comment by NoahTheDuke** [comment]
That's weird! Thanks for the report, I'll take a look.

**Comment by francescopellegrini** [comment]
The interaction works correctly now, I tested it locally. Maybe the rework of GMF introduced in #6599 was of some help.
