### ISSUE TITLE
AgInfusion runner prompts

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#5168]
Using the Aginf ability to boop a diversion onto an un-iced remote gives the runner a prompt to access server or undo click, but no opportunity to jack out.

![image](https://user-images.githubusercontent.com/7129465/85206549-faedb900-b2f0-11ea-947e-1aa34a91b7d8.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by groenkaaf** [comment]
yvw!
