### ISSUE TITLE
Flame-out and Kabonesa Wu don't allow for trigger ordering to prevent RFG

### ISSUE THREAD

**Issue by CarlHawley** [mtgred/netrunner#5169]
repro:
Install Flame-out.
Use Kabonesa Wu to install-and-host a program on Flame-out.
Use a credit from Flame-out on the program.
End turn.
Card hosted on Flame-out is RFG'd before being given the option to trash.
workaround:
Drag from RFG area to heap.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
