### ISSUE TITLE
Blue Sun power does not take modified rez costs into account

### ISSUE THREAD

**Issue by BakyraBA** [mtgred/netrunner#517]
If a piece of Space ICE has been advanced (Orion, Wormhole, etc), once retrieved from board it should only give the reduced rez cost back.
If a piece of ICE has been made more expensive by a PERMANENT effect (Rook, Xanadu) it should give the increased money cost back.

**Comment by mtgred** [comment]
Also upgrades and assets cost in a server with a rezzed Breaker Bay Grid.

Paging @nealterrell.

**Comment by JoelCFC25** [comment]
I got part of the way on this last night, and had Blue Sun correctly gaining only 3 credits for a twice-advanced space ice that was pulled back to HQ--but I couldn't get it to take into account an installed Xanadu (didn't try a Rook but I assume that would've had the same problem).

**Comment by nealterrell** [comment]
Submitted a fix in #535 which might be helpful for Nasir as well.
