### ISSUE TITLE
Inversificator is copying ice

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5170]
From Slack:

![image](https://user-images.githubusercontent.com/1409906/85285274-e6482700-b490-11ea-82e8-032d53c7eb7c.png)

Runner is Kit. Stargate run on R&D. Innermost ICE is Data Raven that gets rezzed. Runner handles it with Kit + Hunting Grounds + Inversificator and swaps it with Archives ice.
Result: Both ice become rezzed Data Raven.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't reproduce this.

**Comment by Dirjel** [comment]
This has happened to me a bunch of times, but I haven't opened an issue because I can't reproduce it consistently.

**Comment by NoahTheDuke** [comment]
It's happened recently?

**Comment by Dirjel** [comment]
relatively, certainly after you fixed all the other Inversificator bugs I've submitted ;)

I play a decent amount of Inversificator still, and if I'm ever able to nail it down I'll give you more info.  I wouldn't stress too much about it on your end in the meantime.

**Comment by NBKelly** [comment]
I think the conditions related to this bug are no longer possible to reproduce, so I'm closing this issue as stale. If anything like this happens again, please create a new issue.
