### ISSUE TITLE
Cyberdex Sandbox Second purge check

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#5174]
A newly scored Cyberdex Sandbox doesn't check if the purge from scoring is first purge of the turn. Recommend adding an implementation note on this card for this extreme edge case.

Relevant situation: Fast advancing Cyberdex Sandbox through Clot using CVS to purge clot before score

**Comment by NoahTheDuke** [comment]
Thanks for the report! The restriction can definitely be added.
