### ISSUE TITLE
Apex Install Triggers Better Citizen Program 

### ISSUE THREAD

**Issue by dj88c** [mtgred/netrunner#5175]
I had a Better Citizen Program scored (Agenda) and the Runner playing as Apex installed a card facedown that triggered the Agenda ability (The first time the Runner plays a run event or installs an icebreaker program each turn, you may give the Runner 1 tag.) which gave away that the installed card was a program/run event. Not sure which exactly but I imagine this bug would be pretty easily testable?

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!
