### ISSUE TITLE
Runner becomes untagged despite having a tag against ACME

### ISSUE THREAD

**Issue by datlo** [mtgred/netrunner#5178]
Likely related to #4984

Runner has tags but his status is set as untagged. Cant play tagged cards, trash ressources, or remove tags on the runner side.

Likely steps to reproduce, havent confirmed :

1. Have the runner run on a server only protected by Data Ward against ACME consulting. Choose to take a tag
2. Break data ward, access server
3. Run ends, runner has a tag but his status is permanently set to 'untagged'

**Comment by artturipi** [comment]
I had something happen to me with ACME as well. Hippo'd a Data Ward (did not take tag). Afterwards got hit by HHN, cleared 3 of the tags, got hit by another one for a total of 5 tags (showed correctly in sidebar). Corp played High-Profile Target and only did 8 damage (should've been 10 with 5 tags) so 1 tag was "missing" for the operation.
