### ISSUE TITLE
Format legality

### ISSUE THREAD

**Issue by Nibbles-N-Bytes** [mtgred/netrunner#5181]
Currently (as of 1/7/2020) regardless of what format you choose, decks will show as either standard legal or illegal. 

When playing a non-standard game, Jnet will only check if the deck is standard legal, ignoring the format's legality. 

When building a deck, Jnet will check if the deck is legal for the chosen format, but will display it as standard.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Do you have a picture demonstrating the issue? That would help recreate it.

**Comment by Nibbles-N-Bytes** [comment]
https://imgur.com/a/cDTaExi

**Comment by Nibbles-N-Bytes** [comment]
I can produce more if you would like
