### ISSUE TITLE
Fairchild 3 end the run sub doesn't always immediately do so

### ISSUE THREAD

**Issue by mikeprosser** [mtgred/netrunner#5184]
Clicking the "fire all unbroken subs" button on Fairchild 3 presents the corp with the "do 1 brain damage or end the run" subroutine as soon as the runner has selected an option for the second sub. If the runner chooses to trash an installed card, and the corp then chooses to end the run while the runner is deciding which installed card to trash the end the run is logged to chat but doesn't actually do anything until both players then click no more action.

Pretty minor as it does eventually end the run but a bit confusing about what's actually happening, I've seen a few people manually re-fire the sub rather than click no more action because of the ambiguity

https://youtu.be/Vbgq-wigaDw

**Comment by NoahTheDuke** [comment]
Thanks for the report! Sounds like an async issue.

**Comment by mikeprosser** [comment]
Yea it looks like it, I'm just having a look at it now but hopefully an easy fix. It looks like it also has a related oddity where as the runner, if you click "trash an installed card" you can't actually do that until you then select what you're doing for the second one (which again is barely ever actually going to matter but is just a bit confusing to experience)

**Comment by NoahTheDuke** [comment]
Also an async issue!
