### ISSUE TITLE
Multiple Gang Sign doesn't seems to work properly

### ISSUE THREAD

**Issue by Zulyen** [mtgred/netrunner#519]
My opponent scores an agenda. My 2 Gang Sign triggers.
I have also HQ Interface.
First access : Howard Jackson + Howard Jackson. i trash them both.
Second access : Howard Jackson + EMP.
This case is impossible because i trashed 2 jacksons before and one is already used and out of the game.

later in the same game, a similar scenario is reproduced.
My opponent scores an agenda. My 2 Gang Sign triggers.
First access : Psychic Field + Neural EMP. I trash the Psychic.
Second access : Psychic Field + Scorched Earth. I trash the Psychic but nothing appears in Archives.

It's like the second access is done with the same cards in hand than the first.

**Comment by JoelCFC25** [comment]
Known issue, and it's noted in the site guide on the wiki as a limitation. Ultimately it boils down to #189--multiple simultaneous effects can't be ordered at this time.
