### ISSUE TITLE
Imp works even without virus counters

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#5190]
Looks like Imp always prompts and allows a runner to trash an accessed card, even if there are no virus counters on it. I've run into it a few times, but I keep forgetting to get some screenshots. If I run into this again, I'll update this issue.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't reproduce this. If you see it again, please take a screenshot.
