### ISSUE TITLE
Deckbuilder: Pressing "Add to Deck" with no card entered leads to random cards

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5191]
Steps:
1. Select Deck in Deckbuilder
2. Press "Add to Deck" without any card name entered

Effect:
Some random card gets added to the deck. It seems to be different on different accounts. For me it was Corporate Troubleshooter, for Jakuza it was Beth Kilrain-Chang...
![image](https://user-images.githubusercontent.com/1409906/87591861-44aba280-c6e9-11ea-96d7-6c8325466959.png)

**Comment by NoahTheDuke** [comment]
That’s amazing

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Any ideas why?
