### ISSUE TITLE
Using broad daylight counter does not trigger storgotic resonator even when correct faction card is trashed from hand

### ISSUE THREAD

**Issue by joechip90** [mtgred/netrunner#5194]
When you use an agenda counter from a scored Broad Daylight agenda the cards trashed from hand do not trigger a rezzed storgotic resonator when one of the cards trashed match the faction of the runner. Yes I am testing absolute jank right now....

**Comment by NoahTheDuke** [comment]
I can't reproduce this. Next time it happens, can you take a pic for me?
