### ISSUE TITLE
Mirrormorph - Manual Fixing Causes Game to Hang

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#5200]
If corp tries to manually fix mirrormorph, the game hangs and the runner is unable to take clicks.  To duplicate:

Mirrormorph draws a card.
Mirrormorph takes a credit.
Mirrormorph installs a card.
Mirrormorph box appears and corp clicks "Gain Click."
At this point Corp decides that they would have rather taken the credit from mirrormorph and does -1 click +1 credit.
Mirrormorph Passes Turn.
Runners Start Turn triggers happen but they are unable to spend clicks.

Granted, this can only happen if corp makes an error and tries to manually fix it, but by the time the bug happens if you haven't seen it before its unclear what the cause is.  This can be resolved by undo-click if players know to use that remedy.

Similar issue:

If Mirrormorph player needs to manually fix something during runners turn (i.e. drafter fires but corp misclicks which server to install on, drags drafter to HQ, gives them self a click and installs it again) that click will count towards mirrormorph on the corps next turn.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by lostgeek** [comment]
Note to myself: Add event trigger on `:runner-turn-begins` that clears the `:mm-click` counter and `:mm-actions` map
