### ISSUE TITLE
DBS still drawing

### ISSUE THREAD

**Issue by IAmJessica** [mtgred/netrunner#5202]
Hey! 

So DBS got an errata to change the way it interacts with the rules. It now doesn't draw any more cards than you would ordinarily draw. But DBS on JNet still draws an additional card! 

[DBS error!.docx](https://github.com/mtgred/netrunner/files/4969116/DBS.error.docx)
This means that when you are really low on cards, DBS can cause you to lose by being decked earlier than should happen. This is confusing, as the DBS reads 'draw' and the chat log says you draw with it, it seems correct you should lose, but this is inconsistent with the new rules. 

Thanks!

**Comment by francescopellegrini** [comment]
@NoahTheDuke DBS text from System Update 2021 mentions "drawing", so this issue can be closed.
