### ISSUE TITLE
Lewi Guilherme with added prompts

### ISSUE THREAD

**Issue by alphalamda4** [mtgred/netrunner#5208]
The runner has duplicate prompts for Corp timing windows when the corp previously agreed to pay to keep Lewi. These prompts happen most often running a run.

**Comment by NoahTheDuke** [comment]
Can you be more specific? Which prompts? Which parts of the run?

**Comment by alphalamda4** [comment]
I just played using Lewi. It usually starts giving the corp a runner triggers prompt, after I agree to pay the credit to keep him in play. If the prompt goes unnoticed, the corp will lock into that prompt at the start of runs. A "/close-prompt" command does bring it down, but then hand size alters when paired with Dr. Lovegood (it grew randomly from 4 to 13 over the final half of a game).

**Comment by NoahTheDuke** [comment]
Ah okay. Thanks.

**Comment by NBKelly** [comment]
As per #5229, this issue was completed.
