### ISSUE TITLE
Game log not scrolling down

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#521]
I noticed that when playing a game (in Firefox) the game log on the bottom right of the interface does not automatically scroll down anymore!

**Comment by queueseven** [comment]
This should only happen when you already scrolled up. 

Did you move the scrollbar? If not, then it seems a Firefox issue, because on Chrome, this works fine for me.

**Comment by davide-ceretti** [comment]
No, I did not move the scrollbar up, it just stopped going down automatically.

**Comment by mtgred** [comment]
The chat autoscroll down has been modified. See #499.

The new autoscroll might need some fine tuning. A chat window currently scrolls down on new messages only if it is already all the way down, all the way up or when you send a chat message. If the chat is scroll up by more than 100 pixels, it won't scroll down automatically. This allow users to read the chat log history without being interrupted when a new message comes in.

**Comment by mtgred** [comment]
The threshold has been changed to 500px. The game log seems to work fine now.

**Comment by mkfmnn** [comment]
500px seems like way too much—on my display, the log is only ~400px high. When spectating a few fast moving games I've had a lot of trouble reading the recent backlog. Was there a problem with 100px?
