### ISSUE TITLE
Bounce shortcut for turning wheel doesn't count as having made run for hard hitting news

### ISSUE THREAD

**Issue by stephenomaze** [mtgred/netrunner#5214]
After bouncing with turning wheel, the corp should be able to play hard hitting news because it just requires a run, not a successful run.  However, I was unable to play HHN after the runner bounced with turning wheel on the previous turn.

**Comment by NoahTheDuke** [comment]
Yeah, this is intended, sadly. The bounce shortcut is specifically just adding the counters to the card, with no additional tracking done. In the future, I'd suggest the runner make a run and jack out for their first usage each turn, and then use the shortcut the rest of the turn.

**Comment by francescopellegrini** [comment]
Fixed by #5928?
