### ISSUE TITLE
Feature Request: Visual indicator for counter type (Power, Virus, etc)

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#522]
When playing, the user normally has to check the card text to inspect which counter type is being represented on the card.  Some kind of coloring or visual indicator of counter type would be very helpful when deciding whether to take actions like purging virus counters

**Comment by queueseven** [comment]
Is that really an issue? 

I mean, if the card is red, the counters are virus counters, except on D4v1d (and the breaker no one plays); and there a only 5 non-anarch virus cards.

**Comment by Merlin8000** [comment]
For newer players, I think it would be nice.  I was hoping that it would be as simple as a style rule.

Personally, I'm not familiar enough with the card pool to know which cards host virus counters and which ones don't, so I usually double-check the text of the card before deciding whether a purge would be a good idea.

**Comment by bmatsuo** [comment]
I did make a mistake related to this when I was a new player, specifically trying to clear a D4v1d of its counters. Assuming that counters on **Virus** cards are always virus counters then it does seem like it is (basically) a styling issue.

I will open a pull request with the changes shortly.
