### ISSUE TITLE
Hosting cards does not check for uniqueness

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#523]
e.g. you can install multiple copies of Kati Jones on Off-Campus Apartment.

Workaround: Just-don't-do-it™

**Comment by queueseven** [comment]
But you can't install Scheherazade on Scheherazade...

**Comment by JoelCFC25** [comment]
I'm not sure this is still valid. Just now I hosted a Kati Jones on Off-Campus Apartment, then tried to host a 2nd copy on it and it did not install (though I was charged a click).

**Comment by JoelCFC25** [comment]
I'll have a fix and test for this soon--finishing up some small changes to Off-Campus Apartment, Scheherazade, Djinn, Leprechaun, and NetChip.
