### ISSUE TITLE
Successful run effects trigger on empty Jackson Howard server

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#5234]
This seems to have been introduced in the run timing rework, and might also be an issue stemming from incorrect use of the buttons. To reproduce, have a server with only Jackson Howard, and have the runner run the server with Desperado installed. Have the Corp use Jackson before pressing "No further action" or anything else. When the Corp presses "No further action" and the Runner presses "Access server", Desperado will trigger. This does not happen if the Corp instead presses "Action before access" to go to 4.3 and triggers Jackson in that window. 

I don't actually know whether the Corp is allowed to use Jackson before 4.3 or not (although I think they are), so this might be a non-issue, but I think several players might be used to doing it this way, so it might happen often enough to be annoying. The root problem seems to be that the run doesn't automatically end when Jackson is triggered (meaning that the Runner could for example hit "Jack out" to trigger Au Revoir even if the Corp wanted to deny them the money by using Jackson), but a quickfix might be modifying [this function](https://github.com/mtgred/netrunner/blob/571667450c36f1c80f8b1314330f23c551888090/src/clj/game/core/runs.clj#L362) to check whether the server is empty before calling successful run, and doing `handle-end-run` instead if it is.

**Comment by NoahTheDuke** [comment]
Who the heck is playing Jackson? 🧐

**Comment by presheaf** [comment]
Presumably both of the Eternal players.
