### ISSUE TITLE
Dirty Laundry triggers twice off Doppelgänger

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#5235]
If the Runner has Doppelgänger installed and plays Dirty Laundry, when the successful run ends, they do not get the option to gain the Dirty Laundry money before triggering Doppelgänger. Additionally, if the Doppelgänger run is also successful, when it ends they gain 5 creds and then 5 more creds, as Dirty Laundry also triggers off the Doppelgänger run.

I think the issue here mainly has to do with [this event in the Dirty Laundry definition.](https://github.com/mtgred/netrunner/blob/571667450c36f1c80f8b1314330f23c551888090/src/clj/game/cards/events.clj#L751) Firstly, (I think) the Runner should have the option to gain the Dirty Laundry money before triggering Doppelgänger. They don't get this because the event is `:silent true`, so removing this will allow them to trigger Dirty Laundry first. However, if they choose to make the Doppelgänger run first, they still shouldn't get two triggers. This seems to be because Dirty Laundry doesn't check that the run it sees finish is the run it started. I'm not totally sure whether the engine has support for determining the ID of a run or whatever, so a proper fix for this might be impossible, but a pretty good fix would be just making this event `:once :per-turn`.

**Comment by presheaf** [comment]
Oh, and High-stakes Job probably has all the same issues.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by presheaf** [comment]
It also seems Legwork has the same issue, as do multiple other cards. I'll fix the ones I see, but I think the root cause here is really that the engine doesn't have (?) support for checking whether a successful run occurring during the resolution of a run event was the run the run event initiated, meaning a lot of run events end up using the same trick. I can't think of any other cards this causes issues with except Doppelgänger, but I'll try adding support for giving each run a unique id and registering that id in the card initiating it. I think it won't be that gnarly, but we can see how well it turns out in the PR, and I'll understand if the simple fix is best.
