### ISSUE TITLE
Rex Campaign triggers when trashed by the Runner

### ISSUE THREAD

**Issue by presheaf** [mtgred/netrunner#5236]
When a rezzed Rex Campaign is trashed by the Runner, the Corp gets the choice to remove a bad publicity or gain 5 creds. This happens because the effect of Rex Campaign is implemented by having it auto-trash when there are no counters left, and [trigger its effect](https://github.com/mtgred/netrunner/blob/571667450c36f1c80f8b1314330f23c551888090/src/clj/game/cards/assets.clj#L1718) as an effect of trashing the card. I can't think of a good reason to do this, so a simple fix is just rewriting it to be like e.g. [Urban Renewal.](https://github.com/mtgred/netrunner/blob/571667450c36f1c80f8b1314330f23c551888090/src/clj/game/cards/assets.clj#L2137)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
