### ISSUE TITLE
Oversight AI appearing face down for Runner and Spectators

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5246]
![image](https://user-images.githubusercontent.com/1409906/89190012-1fe87380-d5a1-11ea-8f27-4f521c2e17f4.png)

Oversight AI appears to be hosted facedown for both Runner and Spectators.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by LiteSpecter** [comment]
This bug seems to apply to other hosted condition counters such as Casting Call

**Comment by Kubik161** [comment]
Some other conditions, like MCA Informant and Eavesdrop, seems to work correctly.
