### ISSUE TITLE
Prana Condenser Doesn't Trigger Pad Tap

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#5250]
Me (RP) do big ouchie with Bio Ethics. 

Runner (419) say, oh no. 

Prana condenser say, Me take big ouchie, convert into money. 

Runner say, oh yes, me get pad tap. 

But no pad tap! 

Why no pad tap?

**Comment by Kubik161** [comment]
Thanks for report. Will be fixed when #5252 is merged :)
