### ISSUE TITLE
Consume doesn´t interact with Gravedigger or Grimoire

### ISSUE THREAD

**Issue by hec22** [mtgred/netrunner#5262]
Hello, when i trash a card with Gravedigger i can´t add a token on Consume, i have the same problem when installing Consume + Grimoire.

thank you

Héctor

**Comment by p4ulyg** [comment]
The behaviour with Gravedigger is correct as that is the corp, and not the runner, trashing a card and so Consume should not gain a counter.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
Cannot reproduce. Grimoire + Consume works as expected (adds counter on install). @NoahTheDuke this issue should be closed.
