### ISSUE TITLE
Government Takeover lets you click for credits when installed

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#5273]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/2737888/91087741-ca364280-e605-11ea-8445-6f0126abcc98.png">

It's not in the screenshot, but the installed card is Government Takeover, which shows the "[click]: Gain 3 credits" option when you click on it.

**Comment by Eric-Fletcher** [comment]
This appears for all installed face down cards in servers (Agendas and Assets), and makes advancing/rezing them difficult, as I have to look & find the exact box to click on, rather than just move my mouse up a fixed amount to the "default click location"
