### ISSUE TITLE
Khan breaks game, doesn't allow installs from other cards or closing of prompts

### ISSUE THREAD

**Issue by chaosof99** [mtgred/netrunner#5276]
I tried playing a Khan deck today. Repeatedly it did not allow me an additional install after passing an ice. In addition other install cards such as Career Fair did not allow it either. It also completely broke down when I tried running R&D. It did not allow for an additional install, and when I did not it no longer allowed me to click the "Access Server" button. The close-prompt command also did not work. Issue persisted even through undo-click and undo-turn commands.

![BorkedKhan](https://user-images.githubusercontent.com/44696340/91581312-9719e900-e94e-11ea-8528-6e9f70e6df87.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't reproduce this. If you see it again, can you let me know?

**Comment by NBKelly** [comment]
Hi, I think the conditions relevant to this issue are no longer possible to reproduce, so I'm closing it as stale. If anything like this happens again, please create a new issue.
