### ISSUE TITLE
ISSUE - Virus Breeding Ground can target itself to generate counters

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5277]
Virus breeding ground can choose itself to move a counter from itself to, causing an extra counter to spawn.

![image](https://user-images.githubusercontent.com/46433823/91634601-72268400-e9e9-11ea-8505-ec80d0ba3958.png)

**Comment by NoahTheDuke** [comment]
Lol thanks for the report!
