### ISSUE TITLE
ISSUE - Using /counter with a negative number causes weird game behavior

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5278]
Using the console command

/Counter -N

To set the counters to a negative value causes screwy game behavior, as the game doesn't reconise you can't have negative of a counter only zero.

The most intresting of this is trying to do something such as move Incubator counters onto a gravedigger with -2 counters, the ability fails, then clicking Virus breeding gounds to add 1 counter to a virus, VBG will instead resolve the incubator ability trashing itself and moving all it's counters.

![image](https://user-images.githubusercontent.com/46433823/91634656-d0536700-e9e9-11ea-9b41-22c84cced426.png)

**Comment by NoahTheDuke** [comment]
Lmao thanks for letting us know
