### ISSUE TITLE
Check for MU before installing programs....

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#528]
Nothing sucks more than clone chipping a parasite and it doesn't get installed because there's not enough MU left. Maybe before installing programs there should be a prompt asking for programs to trash (at least when there's not enough MU).

**Comment by davide-ceretti** [comment]
Or perhaps the action of trashing a clone chip should be cancelled if the runner cancels the action or  select a program when there is no MU left?

**Comment by queueseven** [comment]
@JoelCFC25 suggested that MU could go negative in this case, and a prompt should show up asking the runner to trash programs until MU >= 0 again.

**Comment by JoelCFC25** [comment]
This will get fixed by #600.
