### ISSUE TITLE
Only 1 simulchip is allowed to be trashed per turn

### ISSUE THREAD

**Issue by BurntRope** [mtgred/netrunner#5281]
Currently, jnet only allows one Simulchip to be trashed per turn. 
When the runner fires the second Simulchip jnet asks the runner to select a program to trash, but won't select the chosen program.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by ouroboros8** [comment]
I can't replicate this, does this happen consistently for you @BurntRope?
