### ISSUE TITLE
Virus Start of Turn Triggers

### ISSUE THREAD

**Issue by LiteSpecter** [mtgred/netrunner#5284]
Summary:

- The Nihilist should ask for trigger even if there are no existing virus counters.
- God of War should prompt a start of turn trigger (with Auto-Resolve option) like Trypano and Virus Breeding Grounds

Issue:
If The Nihilist is installed pre start of turn and there are no virus counters the prompt to use the card is not given even if other cards will add virus counters at start of turn. Additionally, God of War also does not prompt a start of turn ordering trigger, could also use an Auto-Resolve toggle like Trypano.

No virus counters:
![image](https://user-images.githubusercontent.com/19494270/93642139-2b61f380-f9c3-11ea-889a-1f54c8c8667d.png)
With virus counters:
![image](https://user-images.githubusercontent.com/19494270/93642702-218cc000-f9c4-11ea-8f73-e4753c9e7535.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
