### ISSUE TITLE
Konjin and encountering other ice with effects (Slot Machine etc.)

### ISSUE THREAD

**Issue by AxW1ll** [mtgred/netrunner#5285]
Konjin ice is not implemented at the moment, which I perfectly understand why. Unfortunately I can’t seem to get the manual encounter effect to work with slot machine as there is no button for that. There might be commands to add cards to the bottom of the deck, but I'm not familiar with those and that does seem clunky. I realized same might apply to anansi that 3 net damage does not happen easily if there is no button (and similary with other unorthodox ice), but that I did not check while playing.

Not that Konjin is too common, but just something I ran into when fooling around with decks.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
