### ISSUE TITLE
Attitude Adjustment doesn't trigger Hyoubu's ID

### ISSUE THREAD

**Issue by OtisF** [mtgred/netrunner#5290]
As title. It should say something like "[user] uses Hyoubu Institute: Absolute Clarity to gain 1" after the card is used, but it doesn't, and you only gain the money that it would give you in any other ID.

![image](https://user-images.githubusercontent.com/4820473/94073400-55664c00-fdef-11ea-8134-52ff90378500.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
