### ISSUE TITLE
Grappling Hook and Gbahali potentially not interacting as intended

### ISSUE THREAD

**Issue by ValeNetrunner** [mtgred/netrunner#5291]
Situation where the potential bug occurred was running against a Tour Guide that had 3 subroutines, with a Grappling Hook and Gbahali in play. I activated Grappling Hook, and selected the bottom tour guide subroutine on the pop-up window. I then was unable to click my Gbahali, putting my cursor over the card in play and left clicking didn't do anything. We undid the click, and I ran again, this time selecting the top subroutine and attempting the same thing, to no avail. Clicking the Gabhali didn't seem to be doing anything.

Im not an experienced bugtester by any means, so potentially could be user error in some capacity.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
