### ISSUE TITLE
Can’t login 

### ISSUE THREAD

**Issue by tumbando** [mtgred/netrunner#5297]
Hi, I signed up on jinteki.net, but when I go to log in, it says it’s invalid. I’ve reset my password several times, but I still get the same error. Please advise.

**Comment by NoahTheDuke** [comment]
hey hey! sounds like a bug. are you on stim slack? hop on there, join #jinteki_net, and we'll chat about the exact steps you've taken, so I can look into things for you

**Comment by tumbando** [comment]
I’m not on there yet. Do you mean stimback slack? Is there a link you can
send me to sign up?

**Comment by Kubik161** [comment]
if you haven't received link yet, you can try this: https://stimslackinvite.herokuapp.com/

**Comment by NBKelly** [comment]
Hi, I think this issue is no longer relevant so I'm closing this issue as stale. If anything like this happens again, please create a new issue.
