### ISSUE TITLE
Warroid tracker doesn't work on R&D

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5300]
Warroid Tracker on R&D does not trigger if something is trashed in R&D or if itself is trashed.

Thank for your work and contribution.
Diogene

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Kubik161** [comment]
That is correct behavior. Upgrades on central servers are not "in or protecting this server" (as requested by Warroid Tracker), but they are "in the root of central server". So Warroid Tracker on R&D should trigger when ICE protecting R&D is trashed or when something is trashed from R&D, like Stargate trashing card.

**Comment by Kubik161** [comment]
Card just says that trace is fired even if runner trashes Warroid Tracker while installed in server. Important part is that its `in server`. So it doesn't trigger if Warroid is trashed from HQ (hand) or from R&D (deck) and it also doesn't trigger while installed in root of server. 

So:
If you install Warroid in remote server, it is `in server` and trace fires when trashed.
If you install Warroid in central server (HQ, R&D, Archives), it is `in root of server` and trace won't fire when trashed.

**Comment by Diogened** [comment]
I see the difference. But my interpretation is also reasonable. Especially
because there is a specific statement written on the card about the trigger
if it is trashed.

If your interpretation hold, I think it would be fair to have a ruling by
Nisei to present this nuance.

Because, the current ruling suggest the card can be use as prevention
against Stargate. But now, the card cannot protect itself on R&D, which is
counter intuitive to what it written on the card and in the rulings of the
card.

Should I ask for such a ruling?
Thanks.

**Comment by Kubik161** [comment]
Yes, it protects against Stargate, because Stargate trashes card in R&D and Stargate runs cannot access upgrades. Cards in your deck are `in R&D`, so if someone trashes something from R&D, Warroid Tracker will trigger. 
But upgrades on central servers are `in root of server`, so trashing upgrades from R&D is not considered trashing card `in server`. 
 
Ask NISEI for rulling :+1:

**Comment by Diogened** [comment]
Thank you for your fast answer. I posted on Project ANCUR. If you know the
channel to ask Nisei for ruling, please tell me. I did not find anything
else.
Cheers.
Diogene

**Comment by Kubik161** [comment]
Official rulling from Nisei: https://twitter.com/AnOrdinaryHaxx/status/1211073078618468356?s=19 

They will update netrunnerdb page for Warroid Tracker later.
