### ISSUE TITLE
Current Phase: Unknown Phase appears after undo-click

### ISSUE THREAD

**Issue by hbarsquared** [mtgred/netrunner#5313]
Situation: Runner is running Server 1 with a Faust installed, maybe second click? They accidentally install a card from hand instead of trashing it with Faust. The /undo-click command put us into an unknown state.

Eventually was able to fix (after a disconnect, unsure if it is related) with the /undo-turn command.

Log and screenshot [here](https://docs.google.com/document/d/1IURaMNKUvxdWmJ0-Qbn3rwh8zil9bzz6uRKuk_80YwQ/edit?usp=sharing).

**Comment by NBKelly** [comment]
Closed as completed via #7498 (you will no longer be able to click-install cards from hand during a run)
