### ISSUE TITLE
In the deckbuilder, there are text collisions if the influence dots take more than one line

### ISSUE THREAD

**Issue by Hunter16g** [mtgred/netrunner#5314]
Obviously this can only happen if inputting a sealed or draft deck, but it would be nice to see the new & shiny tournament hash :p

**Comment by jwarwick** [comment]
Looks like we are abbreviating the influence dots in the deck builder now. Should we close this? Or is there another place we need to apply this fix?
![image](https://user-images.githubusercontent.com/47226/100694148-69cd4480-335c-11eb-9c3b-dc6766ff42fa.png)

**Comment by Hunter16g** [comment]
It seems to abbreviate above 20 ? But it doesn't prevent the dots from taking two lines.
![Screenshot from 2021-01-30 13-54-28](https://user-images.githubusercontent.com/15839619/106356930-59592c00-6303-11eb-8629-e730ddf1af3f.png)

**Comment by jwarwick** [comment]
Yup, good catch. I think I've got the text floating next to the image correctly now and pushing the card list down the page.
