### ISSUE TITLE
Crisium on Archives does not prevent Divide and Conquer from activating.

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#5315]
The runner made a Divide and Conquer run on archives with a face down Crisium installed on Archives. I rezzed the Crisium Grid at the last window before successful, and the runner accessed archives. It then allowed them to access HQ and R&D, which they should not have.

(I'm sure this scenario happens all the time :doge:.)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
