### ISSUE TITLE
Harmony AR should be playable with empty heap.

### ISSUE THREAD

**Issue by tblackwe** [mtgred/netrunner#5321]
Opening issue for tracking, I will resolve along with blacklist messaging changes.

Per Nisei release notes, HART can be played with an empty heap.

discard count requirement should be removed from card implementation

http://netrunnerdb.com/en/card/26083

**Comment by NoahTheDuke** [comment]
Thanks for the report1!

**Comment by tblackwe** [comment]
resolved with PR #5323
