### ISSUE TITLE
Valley Grid does not reduce Runner's hand size to below 0

### ISSUE THREAD

**Issue by Frizzler** [mtgred/netrunner#5325]
Using Mozilla firefox on Windows 10, the following went wrong:
Runner started the turn with hand size 2.
He fully broke two Ice and was automatically set to hand size 0 by Valley Grid (although in the card automation status list, Valley Grid is marked as "manually triggered"). So far everything was correct.
Then, Runner fully broke a third ICE, but his hand size was not set to -1 as expected, but remained at 0.
According to the judge of this tournament, it should go to -1.

Here is a screenshot:
![FrizzlerBattyVSLongiSmoke](https://user-images.githubusercontent.com/3587409/96623695-076c3780-130c-11eb-9fe1-891c84dcad44.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by Frizzler** [comment]
Hello, thank you for fixing this!
Negative handsize now works fine!

However, the prompt at end of Runner's turn says "Discard down to -1 card".
Nice to have: This prompt should in that special case say somthing like: "You have a negative handsize, so you are flatlined".

Also, if Runner trashes Valley Grid, his hand size is restored.
I am quite sure that the hand size reduction is not bound to the card, but it should persist even if Valley Grid gets trashed.
