### ISSUE TITLE
Caprice Nisei doesn't trigger if the innermost ice is removed mid-encounter

### ISSUE THREAD

**Issue by mikeprosser** [mtgred/netrunner#5327]
If a server has a rezzed Caprice, the Caprice psi game doesn't fire if the innermost ice is destroyed or bounced by the runner mid encounter. I've tested this with Ankusa to bounce it and Knifed to uninstall it and once that happens the runner appears to bypass straight into the actions before access window, then confirms and accesses Caprice/the agenda in a server with her whereas they should drop straight into the Caprice passes-all-ice psi game.

I do not yet know if this also happens for Cayambe which has very similar timing

**Comment by NoahTheDuke** [comment]
Thanks for the report!
