### ISSUE TITLE
Imp cannot trash while accessing remote servers

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#533]
This may be tied to the new system of accessing cards, but in remote servers when I access a card and click Imp, nothing happens. It does work when accessing cards in HQ (I assume R&D too, but didn't test it).

**Comment by queueseven** [comment]
Can you give more information? I works for me. Did you have multiple cards in the remote? What cards?

**Comment by percomis** [comment]
Interesting. Yes, I tried it in two runs, both had 2 cards in the remote. Once SanSan City Grid and Adonis Campaign, the second time SanSan City Grid and Ash.

**Comment by JoelCFC25** [comment]
So far in my tests, (with a SanSan City Grid and Adonis in the same remote), I am unable to use Imp on the first of the 2 cards I choose to access. It doesn't seem to matter which one I pick first or whether it's rezzed or not--Imp simply won't work on the first one. You have to either pay credits to trash it or choose "No". Then Imp **does** work on the second card accessed.

**Comment by percomis** [comment]
Interesting work around, thank you.

**Comment by queueseven** [comment]
What heppens when there are three cards in the server?

**Comment by JoelCFC25** [comment]
The plot thickens--I put a SanSan City Grid, Adonis Campaign, and Bernice Mai all in the same server, all unrezzed. Ran with Imp, was only able to use Imp on the **final** card I accessed.

**Comment by queueseven** [comment]
Workaround: don't use upgrades :-)

**Comment by nealterrell** [comment]
So clicking Imp on anything but the last access just flat out does nothing?

**Comment by JoelCFC25** [comment]
Correct. :(

**Comment by nealterrell** [comment]
Does it print "trash at no cost" to the log?

**Comment by nealterrell** [comment]
Fix submitted in #540. Thanks for the report.
