### ISSUE TITLE
Nanoetching Matrix locks up the run when trashed

### ISSUE THREAD

**Issue by OtisF** [mtgred/netrunner#5330]
Steps:

Corp installs Nanoetching into a remote and rezzes, then installs ICE protecting it.
Runner runs the remote.
Runner passes ICE (doesn't matter if the ICE is rezzed or not) and approaches the server.
Runner chooses to access server, and then trash NM.
Corps chooses to use the NM ability to gain 2 credits (Runner is shown a "waiting for corp action" prompt at this point).
Runner then has a prompt to "Access Server" again, even though they're at the end of the access steps. Clicking the button does nothing (the prompt does not disappear), the only solution seems to be to use the /jack-out command to end the run.

<img width="699" alt="Screenshot 2020-10-23 at 10 27 14" src="https://user-images.githubusercontent.com/4820473/96988804-bed79880-151c-11eb-835a-c7fa89266344.png">
<img width="703" alt="Screenshot 2020-10-23 at 10 27 36" src="https://user-images.githubusercontent.com/4820473/96988814-c0a15c00-151c-11eb-86ea-c11546d31fa4.png">

Tested this without ICE on the remote and the issue does not occur. Also tested Vaporframe Fabricator, which has a similar on-trash ability, and the issue did not happen there either (with or without ICE protecting it).

**Comment by Kubik161** [comment]
I'm able to reproduce this issue on production server, but not on current development build. It seems that it has been fixed during last 2 weeks.
This issue should be closed after next deploy.
