### ISSUE TITLE
Anansi 2nd Sub can be used on 0c

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5335]
Anansi's sub "You may draw a card, the runner may pay 2 to draw a card", allows the runner to "pay" 2c when on 0c and get the card.

See attached image
![image](https://user-images.githubusercontent.com/46433823/97063614-97beac80-1598-11eb-8ca8-a1c16398fb9e.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
