### ISSUE TITLE
Personalised Portals and Palana Agroplex issue

### ISSUE THREAD

**Issue by IAmJessica** [mtgred/netrunner#5338]
Hey! 

A minor thing, given the lack of play either of these cards see, but there is a timing issue with Personalised Portals and Palana Agroplex. 

Both of these cards have the same 'when your turn begins' trigger, and so the runner should be able to choose the order. Most of the time, the corp is likely to choose for the runner to draw first with Agroplex so the runner has the extra card for when Personalised Portals makes them draw and gains the corp credits, but currently there is no option to choose, JNet automatically does this, and does it in the 'wrong' order, so the corp often misses out on the extra credit! 

Could an option be added to allow the runner to choose the order, or else automatically resolve Agroplex before Portals? 

Thanks!

**Comment by NoahTheDuke** [comment]
Thanks for the report!
