### ISSUE TITLE
Hoshiko flip and citadel firing are bugged. 

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5339]
tolaasin gains 2  and flips their identity to Hoshiko Shiro: Mahou Shoujo.
tolaasin uses Citadel Sanctuary to force the Corp to initiate a trace.
xxxx uses Citadel Sanctuary to initiate a trace with strength 1.
xxxx pays 0  to increase trace strength to 1.
tolaasin pays 0  to increase link strength to 0.
The trace was successful.

The link post flip should be 1.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
