### ISSUE TITLE
SSCG + Amani Senai

### ISSUE THREAD

**Issue by Keith-thike** [mtgred/netrunner#5344]
When scoring an agenda from a remote with an active SanSan City Grid, the trace is reduced as if the SSCG is still affecting the advancement requirement. It should not, since the agenda is in the score area when Senai fires. (Jade has confirmed that this is the case.)

Example: Scoring a Beale with SSCG costs 2 advancements, but Senai's trace should be 3. Jnet is currently tracing for 2.

<3

**Comment by NoahTheDuke** [comment]
Thanks for the report!
