### ISSUE TITLE
The Class Act doesn't communicate which position is bottomed.

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5347]
The class act, looks at the top N cards of the stack and puts one on the bottom, the cards never leave the stack thus what position the bottomed card was in is public information, and matters for class act triggers when the top card/s of the stack are known to the corp ie: after a slot machine.

Something like:

Chrome uses the class act to put card #4 on the bottom of the stack
Chrome draws 3 cards

should ideally be coming up in chat.

**Comment by Kubik161** [comment]
This has been already fixed by #5318 , but hasn't been deployed yet. @NoahTheDuke This issue should be closed.
