### ISSUE TITLE
Malia blanking Miss Bones still gives a prompt on option to use the credits

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5350]
tolaasin started their turn 1 with 4  and 5 cards in their Grip.
tolaasin spends  and pays 2  to install Miss Bones.
tolaasin spends  to make a run on Server 1.
tolaasin approaches Server 1.
Rajah pays 1  to rez Malia Z0L0K4.
Rajah uses Malia Z0L0K4 to blank the text box of Miss Bones.
tolaasin accesses Marilyn Campaign from Server 1.
tolaasin spends  to make a run on Server 3.
tolaasin approaches Server 3.
tolaasin accesses Malia Z0L0K4 from Server 3.
tolaasin pays 3  from Miss Bones to trash Malia Z0L0K4 from Server 3.
Rajah uses Malia Z0L0K4 to unblank Miss Bones.
tolaasin spends  to make a run on Server 1.
tolaasin approaches Server 1.
Rajah
Rajah
how could you pay from miss bones if i blanked it?
tolaasin
mm

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by tblackwe** [comment]
confirmed via unit test
