### ISSUE TITLE
Chat log is inconsistent with Jesminder v CTM (cf boomerang and blacklist)

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5353]
Jesminder v CTM, trashing a card gives the message 'Jesminder avoids the first tag', though the implementation is correct, and the CTM tag does stick. The chat log should indicate that the Jesminder effect fizzles due to the CTM cannot avoid text.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
In fact, closed by #5323.
