### ISSUE TITLE
Seidr has broken ability to add cards to HQ

### ISSUE THREAD

**Issue by postinternetsyndrome** [mtgred/netrunner#5356]
Clicking the Seidr ID shows an ability with the text "Add cards from Archives to HQ". Selecting this ability has no effect, and if it did work that would also be wrong since Seidr moves cards to the top of RnD, not to HQ.

It would be useful if clicking Seidr did activate the ID ability, since there's no automatic implementation currently (you have to manually drag cards from Archives to RnD), but regardless of that, this nonfunctional "add to hq" ability should probably be removed to reduce confusion.

![bild](https://user-images.githubusercontent.com/9281105/98444468-1d526880-2112-11eb-89aa-a64315ee1409.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! Seems that the label is wrong, and it correctly moves cards from Archives to R&D. However, it can only be used during a run and when there are cards in Archives, which might explain why it wasn't working for you.
