### ISSUE TITLE
Rolodex tells the corp which cards the runner looks at...

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#536]
...and in which order they are returned to the stack.

**Comment by JHonaker** [comment]
So I've narrowed it down. This is not a problem with the implementation of Rolodex. It's from the implementation of move-card in core.clj. When the runner moves a card to the Stack, it doesn't hide the name of the card, but when the runner moves it to R&D it does.

**Comment by mtgred** [comment]
This should be fixed now. Thanks @JHonaker !
