### ISSUE TITLE
Opponents Leaving Lobby Remain in Lobby

### ISSUE THREAD

**Issue by analyzechris** [mtgred/netrunner#5365]
If someone leaves your game before it begins, the interface shows them as still being in your game lobby.

<img width="1253" alt="Screen Shot 2020-11-09 at 4 10 47 PM" src="https://user-images.githubusercontent.com/64614578/98596936-34c25a80-22a6-11eb-9888-04df07ceb4bc.png">
<img width="630" alt="Screen Shot 2020-11-09 at 4 06 11 PM" src="https://user-images.githubusercontent.com/64614578/98596938-355af100-22a6-11eb-82d8-113fab85725c.png">

**Comment by NoahTheDuke** [comment]
Thanks for the report!
