### ISSUE TITLE
Using Jackson Howard's re-shuffle ability breaks the game

### ISSUE THREAD

**Issue by mbrochu-six** [mtgred/netrunner#5374]
Using Jackson Howard's second ability caused my browser window to permanently turn black, making it impossible to keep playing. Reloading the game, exiting and rejoining did not change anything. My whole game screen was completely black and there was nothing I could interact with.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by mbrochu-six** [comment]
Some more info:

The bug seemed to have a 100% repro rate, I tried it again in the following game and it blacked out my screen making play impossible. I had cards in Archives to shuffle, so it doesn't look like an unhandled edge case of "what if there are no cards to shuffle back in."

I am playing on Chrome on a Windows machine.

**Comment by Bovrill** [comment]
That fix doesn't seem to have worked @jwarwick
