### ISSUE TITLE
Paladin Poemu does not prompt for credit usage when bin breakers are installed from the bin

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5375]
Loaded Paladin with 3 credits, run a code gate, black orchestra installs from the bin but no prompt to use Paladin credits to discount the install.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by wern212** [comment]
Not sure if this was already mentioned elsewhere, I looked through the open issues and didn't see it. Also not sure if it needs its own report, but currently you are able to use Trickster Taka to install bin breakers.

**Comment by jwarwick** [comment]
@wern212 thanks for the report!
The PR to address the Paladin issues actually fixes Trickster Taka as well.
