### ISSUE TITLE
NGO weird bug?

### ISSUE THREAD

**Issue by edfortune572** [mtgred/netrunner#5381]
Sorry I don't understand things but -
When I tried to fire NGO - a box came up top right saying "not implemented"

![Screenshot 2020-11-13 003742](https://user-images.githubusercontent.com/71883319/99013530-9b66a300-2548-11eb-999c-c9ed08b84782.png)

**Comment by NBKelly** [comment]
Hi, I think the conditions surrounding this bug are no longer possible to reproduce, so I'm closing this issue as stale. If something like this ever happens again, please create a new issue.
