### ISSUE TITLE
Facedown cards after refresh

### ISSUE THREAD

**Issue by edfortune572** [mtgred/netrunner#5382]
I've posted in the slack about this a couple of times - have recreated the facedown bug. I am computer illiterate and forgot i could screen snip. I took a pic with my phone that I have uploaded

Thanks Again
Ed
![Facedown bug](https://user-images.githubusercontent.com/71883319/99013635-d49f1300-2548-11eb-9394-c7696adf6c8b.jpg)

**Comment by edfortune572** [comment]
has now happened 3 times
![Screenshot 2020-11-13 021951](https://user-images.githubusercontent.com/71883319/99020491-a9232500-2556-11eb-8a19-8a9923b2ba92.png)

**Comment by NBKelly** [comment]
I think this issue is too old to be reproducible. If it ever comes back, feel free to make another issue.
