### ISSUE TITLE
Datapike breaks the game

### ISSUE THREAD

**Issue by IAmJessica** [mtgred/netrunner#5389]
Hey!

So the ice Datapike (which I maintain is pretty good! Or was, it is rotated out of Standard :( ) seems to be broken. Whenever I rez it and try to fire the subroutines, they don't fire. Nothing happens on the corp side. It's possible to manually adjust things on the runner's side and finish the turn as normal, but then the corp cannot start their turn. 

Thanks!

**Comment by jwarwick** [comment]
Fixed in #5387
