### ISSUE TITLE
Black Screen console error 

### ISSUE THREAD

**Issue by qwitwa** [mtgred/netrunner#5390]
Before this happened I rejoined and experienced the cards face down bug (see #5382, something my friends with spotty connections commonly run into).

<img width="1673" alt="Screen Shot 2020-11-18 at 03 31 32" src="https://user-images.githubusercontent.com/2302478/99480173-79f22680-294f-11eb-8c59-0507057e19d3.png">

Attempting to play ICE resulted in this

<img width="1675" alt="Screen Shot 2020-11-18 at 03 30 52" src="https://user-images.githubusercontent.com/2302478/99480201-84142500-294f-11eb-8487-17e8f0e2a707.png">

**Comment by qwitwa** [comment]
Attempting to install resulted in the prompt instead of the usual floating menu:

<img width="866" alt="Screen Shot 2020-11-18 at 03 33 02" src="https://user-images.githubusercontent.com/2302478/99480351-d05f6500-294f-11eb-98b8-07fa160af2ef.png">

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
I think this issue is too old to be reproducible. If it ever comes back, feel free to make another issue.
