### ISSUE TITLE
Chisel does not account for other sources of strength modification on hosted ICE

### ISSUE THREAD

**Issue by mgsholte** [mtgred/netrunner#5391]
Chisel does not correctly trash hosted ICE with 0 or less strength if the strength of the ICE is being modified by a source other than Chisel itself.

Some examples of situations where Chisel should trash host ICE, but instead adds another virus counter to itself:

- Triggering an installed Devil Charm before Chisel triggers on an ICE with 6 strength or less.
- Encountering a 1 strength ICE while Ice Carver is installed.
- Triggering the id ability for Null: Whistleblower  before Chisel triggers on an ICE with 2 strength or less.

Steps to reproduce:

1. Install Chisel on an ICE with 6 str or less.
2. Install Devil Charm.
3. Run and encounter the ICE hosting Chisel.
4. During the 'when encountered' trigger window, select Devil Charm before Chisel and select yes to RFG the Devil Charm and reduce the strength of the ICE.

Once Chisel triggers it will add another virus counter to itself instead of trashing the host ICE (which will have a negative strength at this point). Triggering Chisel before the Devil Charm will have the same effect (which is correct in this case). 

Note that Chisel works just fine on it's own. If the strength of it's host ICE is zero without any other sources of modification then it will be trashed. So encountering a Tour Guide with Chisel hosted will immediately trash the Tour Guide. Also, encountering an Enigma when Chisel already has 2 virus counters will trash the Enigma.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
