### ISSUE TITLE
misdirection with a credit from mantle only clears one tag

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#5401]
i played a game against an opponent who tried to clear tags after HHN with misdirection and a mantle credit.  It worked sort of, but only removed 1 tag.  Maybe the # of tags is tied to the # of credits from the last source selected?

![mantle-misdirection](https://user-images.githubusercontent.com/396562/100062574-6a625a00-2df5-11eb-99a7-f7ed0c6756ca.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
