### ISSUE TITLE
We killed Jackson

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#542]
Long live the king.

Clicking "Done" to move the selected cards back into R&D crashes the game. 

The interface is also really clunky. When you click Archives to open it, the top card gets selected for Jackson. The next card you click selects that card, but closes Archives, so you get this awkward pattern of opening and closing Archives to hopefully select all the cards you intended. I refreshed the JS scripts before trying this so I don't think that's the issue.

**Comment by mtgred** [comment]
You still have the old version. If you try in Chrome Incognito Mode you should have the new javascript. The interface to interact with the Archives has been changed to have a close button to be like R&D. Selecting cards shouldn't close the Archives menu. Opening Archives does select the top card though but i couldn't find a easy workaround yet.

I'll have a look at the crash when clicking "Done".

**Comment by nealterrell** [comment]
I actually did try in Incognito Mode and it performs as I indicated :(. I have noticed, though, that the crash is only when you click Done with fewer than 3 cards. If you can manage to get 3 cards selected the system does work as intended.

**Comment by mtgred** [comment]
A similar issue has been reported for Celebrity Gift. Selecting 5 cards works fine. Selecting less than 5 and the log message lack the card and player name if I remember correctly.

**Comment by nealterrell** [comment]
Yes, I found that with Grail ice too -- if you select less than `:max`, `resolve-ability` doesn't seem to pass the side or card correctly.

**Comment by Merlin8000** [comment]
Could this be the same cause for Project Atlas not keeping counters from having more than 3 advancement tokens?

**Comment by mtgred** [comment]
Jackson has been fixed.
