### ISSUE TITLE
Expand pronouns list

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#5425]
- Pronouns not set
- Any
- Prefer not to say
- [Blank]
- He/him
- She/her
- It
- They/them
- Ne/nem
- Ve/ver
- Ey/em
- Ze/hir
- Ze/zir
- Xe/xem

**Comment by qwitwa** [comment]
Is blank intended to be completely blank or a write-in field? What would the technical complexity be of allowing users to enter anything as their pronoun, and would that be a desirable option to implement given some users inevitably writing non-pronoun things in the box?

**Comment by NoahTheDuke** [comment]
Blank would be an empty field. Until we have proper moderation, there's too much opportunity for bad actors to write shit in the space.

**Comment by qwitwa** [comment]
A new player without a github account has pointed out to me that he/they and she/they are conspicuously missing, let's add those.
