### ISSUE TITLE
When looking at heap a wrong message is displayed in the console

### ISSUE THREAD

**Issue by davide-ceretti** [mtgred/netrunner#543]
"<player name> stops looking at their deck."

**Comment by gammanet** [comment]
when the runner stops looking at the heap or archives it displays that message.

**Comment by davide-ceretti** [comment]
Well that is wrong, they are not looking at the deck. Also why would you say anything in the console when this happens?

**Comment by nealterrell** [comment]
Confirmed.

**Comment by davide-ceretti** [comment]
This seems to happens when the corp looks at archives as well

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
