### ISSUE TITLE
Account Siphon does effects in the wrong order

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5433]
Account Siphon should first make the Corp lose 5c and then simultaneously take 2 tags and gain 2c for each credit lost.

Relevant scenario: No One Home + Account Siphon

What should happen: Corp loses 5c, then NOH triggers and the Runner has to win the trace without the 10c from Siphon to dodge tags.

**Comment by NoahTheDuke** [comment]
We don't have "simultaneous" triggers right now. :-(

**Comment by lostgeek** [comment]
Yeah I know, but even just ordering it exactly as written would resolve this bug ;)
