### ISSUE TITLE
Direct Runs on Archive with Sneakdoor Installed Goes to HQ Anyway

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#5436]
May be a weird state in this specific game. Gabe with Sneakdoor makes runs against Earth Station (with rezzed Crisium) on HQ when running directly on Archives (i.e. Bravado), still trigger the Sneakdoor boop.
![image](https://user-images.githubusercontent.com/7111681/101677532-b08cff80-3a2a-11eb-8c1d-cb8a584a8cd9.png)

**Comment by tvaduva** [comment]
May be related to other open issue: https://github.com/mtgred/netrunner/issues/3852.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Yeah, Sneakdoor effects are tough. I've tried to fix them up a couple times but they remain elusive!

**Comment by qwitwa** [comment]
@NoahTheDuke how are lingering effects handled more generally in the codebase?
