### ISSUE TITLE
Saisentan does not fire all unbroken subroutines when used

### ISSUE THREAD

**Issue by OtisF** [mtgred/netrunner#5437]
I think this is a fairly new issue because I haven't seen it before today - when Saisentan is encountered and the corp fires all unbroken subroutines, it will stop after the first subroutine that _does not hit the target type_. If you click the "fire all unbroken subroutines" again, it will repeat the process, but start from the first sub again.

So, for example, if you name Event, the runner doesn't break anything, you fire all subs, and the first damage hits a Resource, it will not automatically fire the remaining two subs. If you fire all again and hit an Event this time, it will deal the extra damage and then move onto the second sub. If the sub also hits an Event, you will end up firing all subs, but you've done extra damage than should have been possible.

Clicking each subroutine individually on the ICE itself does at least mark them all as fired though.

[After clicking "Fire unbroken subs" once]
<img width="1396" alt="Screenshot 2020-12-11 at 14 21 30" src="https://user-images.githubusercontent.com/4820473/101916266-9ab04380-3bbe-11eb-978c-e0da121d24ac.png">

[After clicking "Fire unbroken subs" for a second time in the same encounter]
<img width="1248" alt="Screenshot 2020-12-11 at 14 21 52" src="https://user-images.githubusercontent.com/4820473/101916459-de0ab200-3bbe-11eb-8a29-cab074bbdcd6.png">

[A different encounter where I named "Resource" as the card type]
<img width="1254" alt="Screenshot 2020-12-11 at 14 24 37" src="https://user-images.githubusercontent.com/4820473/101916507-eebb2800-3bbe-11eb-8d47-0d414bff883d.png">

**Comment by NoahTheDuke** [comment]
Thanks for the report!
