### ISSUE TITLE
Reverse Overseer Matrix & Apocalypse interaction.

### ISSUE THREAD

**Issue by Mezuzi** [mtgred/netrunner#5438]
Pending a conversation on Slack, it looks like Overseer Matrix should not trigger on Apocalypse anymore as it previously had been. This appears to have been fixed in the past by https://github.com/mtgred/netrunner/issues/4651 but now needs to be undone.

Still trying to locate the original ruling that allowed the two to interact back in FFG land but now it appears this ruling has been overturned.

**Comment by NBKelly** [comment]
Hi, the current ruling has changed since then, and they now do interact again as per the NSG CR - so I'm closing this one as completed.
