### ISSUE TITLE
Sneakdoor Beta took effect even though trashed earlier in match

### ISSUE THREAD

**Issue by 5auc3** [mtgred/netrunner#5447]
As can see in attached screenshot, Sneakdoor Beta took effect even though was not in play. Had been trashed by the rototurret in an earlier turn.
<img width="1438" alt="Screenshot 2020-12-19 at 01 07 06" src="https://user-images.githubusercontent.com/76234114/102677171-1438ca80-4199-11eb-926e-cecd6b2ba97e.png">

Using Firefox in MacOS

**Comment by NoahTheDuke** [comment]
Thanks for the report!
