### ISSUE TITLE
Bug - Project Atlas

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#545]
I got Project Atlas with one agenda counter on it (Due to Titan T). When I activate the Hosted agenda counter, the game will list the possible cards I can get.

Problem is that after I choose one, the menu won't go away until I choose at least 5.

**Comment by Merlin8000** [comment]
I experienced the same issue (mentioned in #542).  From what I saw, it didn't actually keep counters from over-advancing the card.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
