### ISSUE TITLE
Kicked out of my own game and cannot rejoin or create new game

### ISSUE THREAD

**Issue by Neutrino-Sunset** [mtgred/netrunner#5452]
I start a new game, select the card set and deck, click Start and then get kicked out to the game list with no way to rejoin the game I just created and no way to start a new game.

Sometime it lets me create a couple of games and kicks me out each time.

This doesn't only happen to me. As you can see from this screenshot this has happened to two players at once and I've been seeing this happen to other players all day.

![jinteki](https://user-images.githubusercontent.com/18445931/103033393-47dd7100-455a-11eb-96e5-bba673f3c49b.jpeg)

**Comment by Neutrino-Sunset** [comment]
Exactly the same, still happening today.

**Comment by NBKelly** [comment]
Hi, I think the conditions relevant to this issue are no longer possible to reproduce, so I'm closing it as stale. If anything like this happens again, please create a new issue.
