### ISSUE TITLE
Consume trashed off Street Peddler is duplicated and installed

### ISSUE THREAD

**Issue by manveruppd** [mtgred/netrunner#5456]
![consumebug](https://user-images.githubusercontent.com/44246400/103157834-e0285f80-47bf-11eb-9f39-2c0c1de5ceae.png)
A street peddler was trashed to install a parasite, trashing a paperclip and a consume, but the consume was instead duplicated and installed automatically, with another copy ending up in the heap.  Was not able to duplicate

**Comment by francescopellegrini** [comment]
@NoahTheDuke Can be closed as obsolete.
