### ISSUE TITLE
Game crashes every few minutes CST PMs

### ISSUE THREAD

**Issue by Raiddinn** [mtgred/netrunner#5467]
Every time I play a game after roughly 5PM CST, I disconnect and reconnect over and over again, at least 10 times during the course of each game.

I played a game roughly from 3PM CST on and not a single disconnect.

I asked in chat and nobody else seemed to believe this was a thing.

I need help understanding why this happens and if it's on the devs to fix it or if it is somehow something on my side even though I can play just fine outside of CSTs 5PM-2AMish time frame.  I didn't stay up later than that to test further.

**Comment by Raiddinn** [comment]
Correction, I don't even have to be in a game.

Roughly 5 min ago, a little after 10 PM CST, I got disconnect/reconnect while in deck builder.

Ping -t on www.jinteki.net is stable no dropped packets that I am seeing.

**Comment by Raiddinn** [comment]
Ping is up from roughly 12ms at around 3 PM CST when I was testing earlier to around 30 - 40ms now.

**Comment by jwarwick** [comment]
That's an interesting analysis. Can you try running a `traceroute` both before and during the drop window? Would be curious if some leg looks different.

If not, then maybe it's something happening on the server.

**Comment by Raiddinn** [comment]
The drops are less than one second long, just long enough to kick me out of the game and force me to go all the way back in.

I don't think I can try to pull of a traceroute between disconnect and reconnect, even if I type the right info into a command prompt and even if I sit there watching JNet like a hawk for the drop message.

**Comment by Raiddinn** [comment]
These drops seem to have gone away without me doing anything.

I am left to believe that the servers just like to kick me, in particular, out when they are overburdened.

**Comment by jwarwick** [comment]
This was probably fixed by the db indexes that were added to address the lag problem.
