### ISSUE TITLE
Feature Request: Draft Identities in Deckbuilder

### ISSUE THREAD

**Issue by taylorh** [mtgred/netrunner#547]
I'd like to use Jinteki.net to play online cube drafts. Unfortunately, the Masque and Shadow aren't available for use in the deckbuilder.

Draft decks will be smaller than the minimum deck size allowed by the regular IDs, and the Shadow is allowed to use agendas from any faction. Would it be too difficult to implement a the draft IDs to allow for draft games?

**Comment by nealterrell** [comment]
Just FYI, the deck builder only warns you about deck violations; it does not stop you from playing with "illegal" decks. So you can pick an ID with no in-game effect, like Professor or Custom Biotics, then use whatever deck size, influence, and agendas that you like.

**Comment by mtgred** [comment]
The draft identities are now available in the deck builder.
