### ISSUE TITLE
Hot Pursuit pays out even when the run is directed away from HQ

### ISSUE THREAD

**Issue by MrCowbird** [mtgred/netrunner#5483]
When a run initiated by Hot Pursuit on HQ is redirected to another server, like for example with the AgInfusion ability, the runner gets 9 credits when the run is successful on that non-HQ server.

The relevant rules entry is here: 6.7.3.a "If an effect that initiates a run specifies that that run must be made against a specific server or servers, any “If successful” abilities associated with that effect are tied to that server or servers. If the attacked server has changed since the run was initiated, and no longer is a server that could have been chosen for this run, the “If successful” abilities do not meet their trigger conditions."

**Comment by NoahTheDuke** [comment]
Thanks for the report! This one should be p simple.
