### ISSUE TITLE
Data Folding does not trigger if MU from Memstrips

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5488]
With 3 Data Folding installed, I had 2 MU left on Memstrips (6 Mu used for program and 1 MU used for a virus, with Keiko installed) and Data Folding did not give credits at the beginning of turn.

My understanding was that MU specialized for viruses count as free MU for Data Folding.

Is that correct?
Thank you.
Diogene

**Comment by NoahTheDuke** [comment]
You have it correct! This is a bug, and will be fixed when #5476 is deployed. I don't have a timeline for that fix, but it should come in the week or two.
