### ISSUE TITLE
Is there any plan to support Chinese?

### ISSUE THREAD

**Issue by darmac** [mtgred/netrunner#5493]
Hi., guys I really like this game and want to share it to my Chinese friends. 
Is there any interface to show Chinese in the web (just for card detail. not for the web content). 
If that's OK. I can make some PR for card translation(just for card explanation,not for the project framework). 

I also found the card data in 
https://github.com/NoahTheDuke/netrunner-data/blob/master/edn/cards/
I think it's a perfect interface for some `Chinese`(or `Other languages`) translation.

**Comment by jwarwick** [comment]
Do you have scans of the cards in Chinese? We could do something smarter with a user's language preference when showing the card image.
Could probably do something similar with the card text, though I think we modify it in more places to insert symbols and markup.
Currently we don't have any of the UI designed around internationalization.

Actually it looks like there's already some translation started: https://github.com/NetrunnerDB/netrunner-cards-json/tree/master/translations/zh

Though I guess we don't grab it for the edn data that's used. I'm sure @NoahTheDuke knows that part of the system better than I.

**Comment by darmac** [comment]
Thanks for your guiding.
Is there any license issue if I upload some scan cards?
And also, Chinese card is not enough because some latest card is not published in China region.
But if you accept that we can try part of cards internationalization at first.

**Comment by jwarwick** [comment]
I am unqualified to comment on any licensing or copyright issues.
Let's just start with the text :)

**Comment by darmac** [comment]
I reviewed the zh text yesterday，and found that  no more translation after  2017. which means almost 600 cards are not finished. 🤣

But I still think that will be a good start with zh text in it。
So,  any plan? 
Or, what  can  I do for that?

**Comment by jwarwick** [comment]
Oof. That's a lot of translation.
NISEI is preparing to release a new set with good beginner decks. Maybe we should focus translation efforts there, especially if your goal is to introduce new people to the game. Are you on the stimhack slack? Maybe we can ask this in the NISEI channel.

**Comment by jwarwick** [comment]
FYI NISEI already has translations for their releases. For example: https://nisei.net/products/Uprising/uprising-zh_simp
The rest are available under 'Products'.

Let me figure out how to add a language selector and load images based on that.

**Comment by darmac** [comment]
Well，Something new here，
I got all of the cards with Chinese。 Looks like some non-official org have done the translation。

So，how about I packed these image to you？
And maybe we can add a language option on the setting. If there is a corresponding card to the language,  jinteki can just load  it.  otherwise, it load  the  English version  by the default.

**Comment by jwarwick** [comment]
See #5502 for an implementation.

**Comment by darmac** [comment]
Got it, thanks so much.

**Comment by darmac** [comment]
Sorry，I'm not a web developer，so I still don't understand how should I push the card image to the DB。And what's the rule（e. g.  image naming
 rule)

**Comment by jwarwick** [comment]
Sorry, our documentation needs work. If you are setting up your own server, you run a few command line applications to seed the database:
```
% lein fetch
% lein add-art
% lein add-language
```

These pull down the latest card database and images, find any alternate art cards on your server, and find any additional language cards on your server.

All the commands assume that card images live in `resources/public/img/cards/`.

A card image has the base format of `cardnumber.png` (eg. `26004.png`). The `add-language` script looks for files of the form `cardnumber[language].png` (eg. `26004[zh-simp].png`). 

So if you dump your translated cards there and fix the naming format, they should show up when you select a language in the `Account` web page (and refresh your browser).

Currently I've hardcoded the language choices to match NISEI's releases : `zh-simp`, `zh-trad`, `fr`, `de`, `it`, `jp`, and `ko`.

**Comment by darmac** [comment]
OK, that's fine, I will try to make a local server.
But still, I think, is there possible to upload the language card image to `www.jinteki.net`, so everyone can share your effects directly.
As I know, so many people using the live server now. It's easy to surprise them at next release version~   ^ ^

**Comment by jwarwick** [comment]
Right, sorry, I thought you wanted to run a separate server based on the previous comment. I'm trying to find someone who manages jnet and can put the files there for us.

**Comment by darmac** [comment]
Now I have made my local server successfully, when the patch https://github.com/mtgred/netrunner/pull/5502 merged, I can test it locally too.
: )

**Comment by jwarwick** [comment]
Are the card images accessible somewhere? Not sure what file sharing services are available.

**Comment by darmac** [comment]
I'm not sure too... 
How about open an ftp or samba service on jinteki？

**Comment by darmac** [comment]
We got some people who will upload these image to jinteki soon. 
But still there's a question, It looks hard to transfer the UI to another language, because so many words are fixed in clj files. 
Any suggestion for that?

**Comment by jwarwick** [comment]
Chinese card images are now live on the site. Let me know if there are any issues. Seems like some cards are still in English.
There are now hooks to translate the front end pieces here: https://github.com/mtgred/netrunner/blob/master/src/cljs/nr/translations.cljs

But, a lot of text is generated from the engine. That will be much harder to translate. If there's enough interest we can try.

**Comment by jwarwick** [comment]
See also #5538

**Comment by darmac** [comment]
Got it, we know each other and make some communication already. Thanks for your kindly help, I think we can close this issue now.
