### ISSUE TITLE
Aeneas Informant trigger on accessing an agenda

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5494]
The runner went in a serve (unprotected) and discovered an agenda, but could not steal it (not enough credits for Bellona). The 3x Aeneas Informant installed on the runner side triggered, giving each a cred.

I think it the Aeneas should not have triggered.

Am I correct?
Thanks.
Diogene

**Comment by jwarwick** [comment]
I can't reproduce this. Any chance you saved a replay of the game?

**Comment by osiccha** [comment]
@jwarwick #5501 fixed this, but only #5491 was closed

**Comment by Diogened** [comment]
Thanks a lot!

Le sam. 27 févr. 2021 10 h 00, John Warwick <notifications@github.com> a
écrit :

**Comment by Diogened** [comment]
Thanks a lot!
