### ISSUE TITLE
assortment of UI needs

### ISSUE THREAD

**Issue by sonatinas** [mtgred/netrunner#55]
1. able to undo ice breaker strength 
2. be able to dismiss menus when clicking on a card
3. be able to exit a finish game instead of reloading the browser
4. move cards installed in the wrong server to the right one

**Comment by mtgred** [comment]
1. The Ice breaker strength normally reset after each ICE encounter.
2. To dismiss a card menu, just click on the card again.
3. It's in the TODO list.
4. You can drag and drop a card back to your hand, add yourself 1 click and install it again in the right server.

**Comment by eah13** [comment]
@sonatinas or @mtgred OK to close this issue?  Looks like everything's dealt with.

**Comment by mtgred** [comment]
Yeah the only thing missing in the list was the leave button but it has been implemented.

**Comment by eah13** [comment]
Killer.  I can't close issues without some sort of permission in the repo.  Happy to do issue cleanup here and there if that's helpful - just add me. For now you or @sonatinas will have to close this one.
