### ISSUE TITLE
Lots of broken images where some share names (like Paperclip, Off-Campus Apartment and Street Peddler)

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#5505]
Seeing a lot of broken card images.

Weird thing is, that some have the same name: Paperclip, Off-Campus Apartment and Street Peddler (and probably more) all are now named wc2015.png that gives 404

Also BoN are "alt.png" and also does not work (404).

![image](https://user-images.githubusercontent.com/1651150/105234278-5162f480-5b6b-11eb-8671-ddb9efde0733.png)
![image](https://user-images.githubusercontent.com/1651150/105234398-7e170c00-5b6b-11eb-82ad-e30f2736fed2.png)

**Comment by jwarwick** [comment]
I think it's confused about your alt art settings (since the alt cards got deleted).
Trying pressing the `Settings->Reset All to Official Art` button. Then hitting the `Update Profile` button and refreshing your browser.

**Comment by AndersRask** [comment]
@jwarwick thanx, that was indeed the case! It must have been a recent change though, because I haven't touched those alt-art settings since i became a subscriber some years ago.
