### ISSUE TITLE
Add Green Level Clearance to "other communities" list

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#5508]
https://discord.gg/VxgbNj5

**Comment by Dirjel** [comment]
Updated list:
1) Stimslack herokuapp invite link: https://stimslackinvite.herokuapp.com/
2) GLC Discord server: https://discord.gg/VxgbNj5
3) r/Netrunner http://reddit.com/r/netrunner/
4) Netrunner Dorks on Facebook: https://www.facebook.com/groups/netrunnerdorks/
5) NearEarthHub, has links to lots of resources & other forums: https://www.nearearthhub.net/#h.c28pw9eqowgt

**Comment by Dirjel** [comment]
Relevant code (thanks Noah <3): https://github.com/mtgred/netrunner/blob/d14b02d7ee979c049b9aef06a610f895a2226259/src/cljs/nr/help.cljs#L122-L130

**Comment by bbbbbbbbba** [comment]
Working on this. Do we remove Stimhack forums from the list? It seems not-dead to me.

**Comment by bbbbbbbbba** [comment]
Also do we keep the mention of "_multiple_ Facebook groups", or is Netrunner Dorks now the de facto go-to group?

**Comment by NoahTheDuke** [comment]
No need to delete the Stimhack forums, and switching to Dorks is probably best.
