### ISSUE TITLE
Feature Request: Dynamic spacing of servers to avoid overlapping upgrades

### ISSUE THREAD

**Issue by jannn** [mtgred/netrunner#551]
This is a prety major annoyance with decks that like to put 2 or sometimes even more upgrades on servers, for both sides. The third card in a remote server isn't clickable at all if there's another one to the right, and it just looks messy and confusing. Multiple upgrades on central servers are less common, but also very messy.

**Comment by JoelCFC25** [comment]
This is a known bug--see #427.

**Comment by jannn** [comment]
Searched a few keywords and couldn't find it - sorry! Still, I think it'd be nice to implement dynamic spacing for aesthetic/readability purposes as a more general solution, even if it's technically functional once fixed.

**Comment by JoelCFC25** [comment]
Not a problem--when in doubt, report it!
