### ISSUE TITLE
Finding Myself in Others' Games in the Lobby?

### ISSUE THREAD

**Issue by se4n** [mtgred/netrunner#5518]
I've had a persistent, weird issue lately -- this has been going on for at least the past week or two, across multiple updates. I will leave my computer, leaving a tab open on jinteki.net (either the chat or jinteki.net/play) and I'll come back later to find that I'm inexplicably in someone else's game in the lobby. See attached screencap from today:
<img width="931" alt="Screen Shot 2021-01-27 at 4 32 25 PM" src="https://user-images.githubusercontent.com/1520529/106057434-f9257880-60bd-11eb-96ee-d261d3ffc92b.png">

When this happens, clicking "Leave" does nothing. I have to close out the tab and then reopen it, and that usually works. Before the last few updates this issue wasn't fixable that way -- it persisted over an entire day, across my reloading/refreshing of the site, rebooting the computer, etc. I'm really at a loss for why this is occurring. Happy to try to replicate it.

I'm on Chrome for OSX (v. 88.0.4324.96 currently), running Mac OSX Mojave (10.14.6).

**Comment by jwarwick** [comment]
I'd be interested in tracking this down if you have time. I've seen it when game list messages from the server get corrupted. My hunch is that some of the info we put into local storage might be to blame.

Next time it happens, check in `Developer Tools -> Applications -> Local Storage -> www.jinteki.net`. Grab those values and post them here.

Then try deleting those values and see if it starts working again.

**Comment by se4n** [comment]
Will do!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NBKelly** [comment]
Hi, I think the conditions relevant to this issue are no longer possible to reproduce, so I'm closing it as stale. If anything like this happens again, please create a new issue.
