### ISSUE TITLE
unable to see bottom of screen on tablet since update

### ISSUE THREAD

**Issue by chrisferg** [mtgred/netrunner#5523]
Hi,

I just tried playing on a tablet for the first time since the jnet update, and i can no longer see or access the bottom of the screen at all. I can't scroll down to the bottom of the page, and if i zoom in and drag it there is just a black line there (see screenshot below). It's quite possibly a problem my end, but nothing has changed to my tablet as far as I know, so wondering if it might be something to do with the jnet update?
 
Edit: i have tried it on chrome and kiwi browsers.

![Screenshot_20210129-122403_Chrome](https://user-images.githubusercontent.com/17046175/106276482-8f2ce080-622f-11eb-988a-6580cf8a20fd.jpg)

**Comment by lostgeek** [comment]
This should not be because of my recent replay update, since I'm only displaying the `:div.bottompane`, when the game is in replay mode.

**Comment by jwarwick** [comment]
Probably has to do with the additional nesting of the pages in the front-end update. I'll see if I can figure out what scrolling thingy changed.

**Comment by chrisferg** [comment]
Thanks jwarwick! Any luck? It would be great to be able to play again when the new cards are out :)

**Comment by jwarwick** [comment]
Sorry, I was hoping @lostgeek css update would fix it and it fell off my radar. Let me try to find a tablet and take a look.

**Comment by chrisferg** [comment]
Amazing thanks @jwarwick !!

**Comment by jwarwick** [comment]
Think I figured something out. Will push it in the high-res cards PR.

**Comment by chrisferg** [comment]
Amazing thanks so much @jwarwick !! Just tried it and it looks like it works fine now :)
