### ISSUE TITLE
Cannot load image of multiple cards

### ISSUE THREAD

**Issue by hugeheadliang** [mtgred/netrunner#5525]
I cannot load images of multiple cards, the list includes:
Paperclip, I've Had Worse, CtM, Commercial Bankers Group
I can view them in "Cards" normally but cannot load the images in “Deck Builder" and "Play".
Then I found my opponent's Paperclip is normal so I tried to reset the Alt arts setting and everything goes back to normal.

Don't want you to fix it but maybe can remove the "world champion" alt arts option to avoid future confusions?

**Comment by jwarwick** [comment]
Thanks for the feedback. I think we need to wipe everyone's alt settings. Hopefully we'll get all the alt sets available again, but I'm not sure that will fix it.

**Comment by jwarwick** [comment]
I think the alt art update fixed this. If it still happens for folks we can reset individually.
