### ISSUE TITLE
Zed2.0 Brain Damage sub does damage when it shouldnt

### ISSUE THREAD

**Issue by Zerothmaxima** [mtgred/netrunner#5529]
We (0thmxma and TheKing) played a game vs a Zed2.0, shockingly. The last sub fired and did brain damage even though no clicks were used to break or do anything during the run. There were 2 pieces of ice on top of it on HQ, one FC3 that we broke with Engolo and one Ichi1.0 broken with bukhalter. We then broke the two first subs on Zed2.0 with buhkalter and let the third sub fire. 

In my professional opinion, we were playing leela so you know maybe the free brain damage was warranted, but as written it should not have fired.

**Comment by jwarwick** [comment]
The restriction on the 3rd Zed sub is not implemented. It probably says it when you hover over the card, but that's not an obvious thing.

With @NoahTheDuke 's crazy new cost system we can probably check the run log and implement this.
