### ISSUE TITLE
Missing label when a game ends by flatline

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#5532]
Hi, I just found a missing label displayed on a game ended by flatline (Complete Image kill).

Could be related to #5502. My selected language is English, if that could help.

![Schermata 2021-02-02 alle 23 43 30](https://user-images.githubusercontent.com/1105053/106672800-f7bde980-65b0-11eb-8a62-775b3c0fd172.png)

**Comment by jwarwick** [comment]
Thanks for the report! I'll get that text added.
