### ISSUE TITLE
MacOS Chrome volume slider does not change volume

### ISSUE THREAD

**Issue by marckubischta** [mtgred/netrunner#5535]
The slider is there but doesn't seem to do anything. In fact, I can disable game sounds and return to a game and the sounds still play.

This is on MacOS 10.15.6 and Chrome 88.0.4324.96.

**Comment by NBKelly** [comment]
In this case, you're required to click the "update profile" button after adjusting the slider. I'm going to close this issue as I think it's probably no longer relevant, but if you have this issue again please do open another one.
