### ISSUE TITLE
Cards trashed from a host erroneously trigger "leaves-play" text

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#557]
From a code perspective, this is probably identical to #350.  It's just more generally applicable than I had realized, as it applies to cards that are not installed.

I've tested this with The Supplier, but presumably it affects Personal Workshop as well.  I haven't confirmed.

If cards which give you resources while they are installed, and take them away when trashed (memchips, consoles, link-boosters, etc.) are hosted and inactive on a resource when that resource is trashed, their leaves-play effects trigger, taking away resources that they have not yet granted.  Install a Rabbit Hole and an Akamatsu Memchip on The Supplier, then trash The Supplier to watch your MU and Link both fall by one.

**Comment by mtgred** [comment]
Thanks for reporting the issue. We'll take care of the problem.

**Comment by JoelCFC25** [comment]
Fixed at https://github.com/mtgred/netrunner/commit/e8da85c5b3f22f64cb90a34ac601473ca8f6d943 and now deployed.
