### ISSUE TITLE
Using Compile to install Atman cost credits to boost Atman

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5573]
Hi.

When I use compile to install Atman, it take credits to 'boost' Atman on the installation. Since Compile state that installation should cost nothing, Atman, at whatever strenght, should also not cost any creds.

Unless I am wrong in my interpretation of the rule.

Thank you very much for your time and effort.

Cheers.
Diogene

**Comment by osiccha** [comment]
Hi,

placing power counters on Atman is not part of the install cost, but an ability that triggers when Atman enters the game.
Thus, compile doesn't give you the credits to pay for those counters.
