### ISSUE TITLE
Alt art cards do not appear as a Set in the Cards tab for non-donor

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#5574]
![image](https://user-images.githubusercontent.com/44735253/107986901-089c3100-6f9b-11eb-8007-8c0e0ea1296e.png)
![image](https://user-images.githubusercontent.com/44735253/107986919-1487f300-6f9b-11eb-955e-14db8d6a0a01.png)
![image](https://user-images.githubusercontent.com/44735253/107986941-1ea9f180-6f9b-11eb-911d-637c3a0fcc25.png)
![image](https://user-images.githubusercontent.com/44735253/107986982-2c5f7700-6f9b-11eb-82b5-3756276a3c34.png)

I'm a non-donor, and although I apparently should be able to see possible Alt-Art cards as a set in jnet, they don't appear here, for me.

**Comment by jwarwick** [comment]
Check if `Alt Arts` are enabled in Settings. If that's off, they won't show up in the Card browser.

**Comment by dnddmdb** [comment]
Ah, there was the issue.  Thank you!
