### ISSUE TITLE
Rover on Thimblerig does not trigger

### ISSUE THREAD

**Issue by Diogened** [mtgred/netrunner#5591]
Hello.

After installing Rover Algorithm on Thimblerig, it does not trigger when the runner pass Thimblerig and I move Thimblerig to the next position, so that the runner must pass it again (which would then boost its strength).

Is this normal?

Thanks.
Diogene

**Comment by 4lki** [comment]
I had this issue today, i think you should reopen it.

**Comment by 4lki** [comment]
Sry, my fault. The problem i watched was a bit different, since Rover triggered BUT the strength of Thimblerig did not update correctly. I will create a new issue for that as soon as I can give the exact conditions in which it occured.
