### ISSUE TITLE
Notoriety is not Noteriety in the runner's score area

### ISSUE THREAD

**Issue by mikehurl** [mtgred/netrunner#5592]
I played Notoriety and it rendered as Rezeki in my score area 🤔 
![Screenshot_2021-02-23 Play Android Netrunner in your browser](https://user-images.githubusercontent.com/18559606/108890499-931d0a00-7605-11eb-90a2-ddce83122564.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
I'm not sure how this got garbled, but I don't think it's possible to reproduce anymore, so I'm going to close this issue as stale. If anything like this happens again, please create a new issue.

![noto](https://github.com/user-attachments/assets/ec53b84a-0c7a-4713-9928-2c34fdfdc5ff)
![noto_000](https://github.com/user-attachments/assets/17fdee10-322a-4468-b371-49314e85c1b8)
