### ISSUE TITLE
Showing Off and Medium - SO triggered double access?

### ISSUE THREAD

**Issue by willybn1** [mtgred/netrunner#5607]
Hi .. I ran RnD with Showing Off. I had a Medium installed and this had 4 counters on (i had previously run RnD earlier in my turn)

When i accessed cards from the bottom of RnD I got the usual prompt 'how many additional do you want to access' and accessed an additional 4, 

2nd card was an Agenda (i stole, but it didn't win me the game) but when i had accessed all cards for the run Showing Off seemed to trigger again - i was prompted again 'how many additional do you want to access' and started to access from the bottom of RnD again. in fact i accessed something like 8 or 9 cards and had to 'close-prompt' top avoid me stealing any further agendas i accessed (2 in fact). 

I captured some of the text in attached pics

thanks, Will. 

![showing off 1](https://user-images.githubusercontent.com/36125436/109415557-49d80c00-79b1-11eb-9056-7c908c79d71f.PNG)
![showing off 2](https://user-images.githubusercontent.com/36125436/109415560-4c3a6600-79b1-11eb-82cc-ccfd48258716.PNG)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
