### ISSUE TITLE
Terminal Directive card legality is wrong for Snapshot and Snapshot Plus

### ISSUE THREAD

**Issue by IAmJessica** [mtgred/netrunner#5608]
Hey!

So a minor one, but the Snapshot legality doesn't seem correct. All of the Terminal Directive non-campaign cards are listed as rotated in both Snapshot and Snapshot plus, but Terminal Directive wasn't rotated until Nisei took over. The only Terminal Directive cards that aren't listed as rotated are the ones that were restricted at the time, as they are listed as being legal but restricted. 

With the new Terminal Directive campaign cards being added recently, there may be an uptick in interest, and this is confusing. 

Thanks!

**Comment by jwarwick** [comment]
Thanks for the report! I think this data update should address the issue: https://github.com/NoahTheDuke/netrunner-data/pull/10

**Comment by jwarwick** [comment]
Fixed in the latest server update.
