### ISSUE TITLE
Jinteki biotech showing the hidden identity

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#561]
http://puu.sh/jHusa/c9915be62d.png <-upper right corner, just under where it shows their identity-card. One line of text.

**Comment by JoelCFC25** [comment]
I think it was previously determined that it's actually showing the entire text of the card--the partially visible portion is always the same, thus may or may not be the Corp's chosen version.

**Comment by nealterrell** [comment]
Yes, it's just showing the end of the card text -- it does not reveal what the Corp chose. #558 removes the text from cards to improve network performance, which will most likely solve this issue. We'll see when it's deployed.

**Comment by queueseven** [comment]
If the card text is removed, the relevant part in the client code in `gameboard.cljs` that displays that information can also be removed.

**Comment by JoelCFC25** [comment]
This one is still happening.

**Comment by queueseven** [comment]
It seems it's always the same text displayed (from The Greenhouse) regardless what flip ID you selected at the start of the game.

**Comment by queueseven** [comment]
the problem is that it is not the card data from the game state that is shown, but the card data from the _local_ `@cards` atom (which is also used in the deckbuilder IIRC).

**Comment by Saintis** [comment]
Is this still happening?

**Comment by queueseven** [comment]
I think so (but I didn't acutally check). There is a method in the game board cljs  file that renders a Text version of the card, then the actual card Image is rendered above it so you don't see the text, expect when the text is too long.

I think that method can entirely be kicked. It only has some value when you Test cards that have no Image yet.

**Comment by JoelCFC25** [comment]
Yes, it's still happening. I agree with @queueseven's proposal that we just jettison the card text.
