### ISSUE TITLE
Dragging function broken (Runner)

### ISSUE THREAD

**Issue by Joseph7695** [mtgred/netrunner#5611]
No way to drag cards from anywhere to anywhere.

Corp was Replicating Perfection, on Inazuma, Archer, Tithonium. Other cards are more common
Runner side, Hayley:
3 Rezeki
1 Harmony AR Therapy
1 Miss Bones
3 Sure Gamble
3 Peace in Our Time
3 Pelangi
3 In the Groove
3 Simulchip
3 Data Folding
1 Clot
1 Dedicated Processor
3 Akamatsu Mem Chip
1 Ankusa
1 Supercorridor
1 DJ Fenris
3 Hyperdriver
3 Career Fair
1 Stargate
3 Diesel
1 Hernando Cortez
3 Daily Casts

**Comment by NoahTheDuke** [comment]
Thanks for the report! Do you have more details about what happened in the game?

**Comment by Joseph7695** [comment]
What kind of details ? 

I realized that the dragging doesn't work when I wanted to drag-trash my programs when installing another program.

**Comment by NBKelly** [comment]
Hi, I think there's not enough information to reproduce this issue, so I'm going to close it as stale. If something like this ever happens again, please create a new issue.
