### ISSUE TITLE
Sunny start of turn breaks

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#5612]
Sunny with Jak Sinclair install - make a jak run at start of turn, but then UI gets stuck on 'take clicks' with nothing able to reset the situation (undo-turn, undo-click, close prompt etc).

Console message is 

app10.js?v=67:981 Warning: Every element in a seq should have a unique :key: (() () [:div.card-wrapper {:class nil} [H9 {:faction "Neutral", :format nil, :rotated false, :cycle_code "ashes", :agendapoints nil, :index 0, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "e803050d-3c69-4f08-add1-b9056f33c73a", :persistent nil, :art nil, :type "Resource", :abilities [], :title "DreamNet", :uniqueness true, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "dreamnet", :code "26095", :side "Runner", :cost 3, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "full", :trash nil, :set_code "ur", :previous-versions nil, :subtype "Virtual", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Virtual"]} nil]] () () [J9 ({:faction "Neutral", :format nil, :rotated false, :cycle_code "order-and-chaos", :agendapoints nil, :index 1, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "143339c5-16f2-4d83-a7e7-7015bbfd94cf", :persistent nil, :art nil, :type "Resource", :abilities [{:label "Gain 1 [Credits] (start of turn)", :msg "gain 1 [Credits]", :once "per-turn", :req "game.cards.resources$fn__46425$fn__46426@722b4708", :async true, :effect "game.cards.resources$fn__46425$fn__46429@261c5511", :cost-label nil}], :title "Data Folding", :uniqueness false, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "data-folding", :code "07055", :side "Runner", :cost 3, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "full", :trash nil, :set_code "oac", :previous-versions nil, :subtype "Virtual", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Virtual"]} {:faction "Neutral", :format nil, :rotated false, :cycle_code "order-and-chaos", :agendapoints nil, :index 3, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "60f1c627-0c59-45b7-b82d-899ea83e8988", :persistent nil, :art nil, :type "Resource", :abilities [{:label "Gain 1 [Credits] (start of turn)", :msg "gain 1 [Credits]", :once "per-turn", :req "game.cards.resources$fn__46425$fn__46426@44ad3390", :async true, :effect "game.cards.resources$fn__46425$fn__46429@6baa1f5c", :cost-label nil}], :title "Data Folding", :uniqueness false, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "data-folding", :code "07055", :side "Runner", :cost 3, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "full", :trash nil, :set_code "oac", :previous-versions nil, :subtype "Virtual", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Virtual"]} {:faction "Neutral", :format nil, :rotated false, :cycle_code "order-and-chaos", :agendapoints nil, :index 4, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "45ca37b4-d479-43d5-b7fe-242d20424823", :persistent nil, :art nil, :type "Resource", :abilities [{:label "Gain 1 [Credits] (start of turn)", :msg "gain 1 [Credits]", :once "per-turn", :req "game.cards.resources$fn__46425$fn__46426@22e0f73f", :async true, :effect "game.cards.resources$fn__46425$fn__46429@2f728e9d", :cost-label nil}], :title "Data Folding", :uniqueness false, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "data-folding", :code "07055", :side "Runner", :cost 3, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "full", :trash nil, :set_code "oac", :previous-versions nil, :subtype "Virtual", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Virtual"]})] () () [:div.card-wrapper {:class nil} [H9 {:faction "Sunny Lebeau", :format nil, :special {:run-id {:eid 65637}}, :rotated false, :cycle_code "data-and-destiny", :agendapoints nil, :index 2, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "ea697fcc-cb2a-48a7-8934-52b19b79fc8d", :persistent nil, :art nil, :type "Resource", :abilities [{:msg "game.cards.resources$fn__47132$fn__47137@c65de4d", :choices "game.cards.resources$fn__47132$fn__47135@266de05b", :prompt "Choose a server to run with Jak Sinclair", :req "game.cards.resources$fn__47132$fn__47133@38384fb", :cost-label nil, :label "Make a run (start of turn)", :once "per-turn", :effect "game.cards.resources$fn__47132$fn__47141@3fc504e1", :makes-run true}], :title "Jak Sinclair", :uniqueness true, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "jak-sinclair", :code "09052", :side "Runner", :cost 3, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "Doesn't prevent program use", :trash nil, :set_code "dad", :previous-versions nil, :subtype "Connection", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Connection"]} nil]] () () [:div.card-wrapper {:class nil} [H9 {:faction "Anarch", :format nil, :rotated false, :cycle_code "red-sand", :agendapoints nil, :index 5, :runner-abilities [], :zone ["rig" "resource"], :advancementcost nil, :cid "ca226d70-f283-4de1-919e-98694c7790bc", :persistent nil, :art nil, :type "Resource", :abilities [], :title "The Archivist", :uniqueness true, :host nil, :strength nil, :seen nil, :baselink nil, :corp-abilities [], :normalizedtitle "the-archivist", :code "12003", :side "Runner", :cost 1, :hosted nil, :subroutines [], :quantity nil, :languages ["zh-simp"], :installed true, :deck-limit 3, :memoryunits nil, :implementation "full", :trash nil, :set_code "dc", :previous-versions nil, :subtype "Connection", :previous-zone ["hand"], :minimumdecksize nil, :subtypes ["Connection"]} nil]])
 (in pba > oba > main-pages >  >  >  >  > eaa > gameboard >  >  >  > i.)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
