### ISSUE TITLE
Recon Drone lets one prevent damage any time

### ISSUE THREAD

**Issue by Hunter16g** [mtgred/netrunner#5615]
Seems like a tricky card to implement, but there should be a warning that the ability isn't properly restricted.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Whoever tackles this, add `:req (req (:access @state))` to the paid ability.

**Comment by Hunter16g** [comment]
Will that restrict to "during access" or to "damage from the card accessed" ?

**Comment by NoahTheDuke** [comment]
We don't have a method for determining that, given how prevention abilities are written.
