### ISSUE TITLE
Shiro + Mwanzo gives way too many accesses and credits

### ISSUE THREAD

**Issue by movableobejct** [mtgred/netrunner#5616]
If the runner is forced to access R&D multiple times with Mwanza Grid installed and Shiro's second sub, then jnet gives way too many accesses on the 2nd or later access. More specifically, it gives 1+3n accesses on the nth time that they access (4, 7, 10, 13...). Similarly, the payout in credits is way too much, yet different. It instead gives the sum of (2+6n) from 1 to n (8, 22, 42, 68...). To reproduce, simply rez a Mwanza on R&D and fire the Shiro second sub as however many times during a single run. It becomes relevant in normal play when using cards like Ganked and Marcus Batty to fire the subroutine multiple times.

**Comment by lostgeek** [comment]
Amazingly detailed find. Good detective work there 😄

**Comment by NoahTheDuke** [comment]
Thanks for the report!
