### ISSUE TITLE
Keyhole still proccing even after running into archives because of susanoo-no-mikoto

### ISSUE THREAD

**Issue by Nipazz** [mtgred/netrunner#562]
Title. Run was succesful into archives, but it shouldn't proc keyhole.

**Comment by nealterrell** [comment]
This is going to be a colossal pain in the butt to fix. If you like Susanoo, I might recommend doing this manually: asking the Runner to jack out, take a click, then initiate a run on Archives.

**Comment by mtgred** [comment]
Adding a `:req (req (= target :rd))` should do it. The condition should also be added to all other run abilities specific to a given server (eg. Account Siphon).

**Comment by mtgred** [comment]
It has been fixed and will be deployed with the next server update.

**Comment by JoelCFC25** [comment]
Deployed!
