### ISSUE TITLE
Hoshiko Shiro not flipping

### ISSUE THREAD

**Issue by mikehurl** [mtgred/netrunner#5622]
I thought something was wrong yesterday and I've just played another game, which seems to confirm that the current implementation in Hoshiko is broken/there is a regex issue in the codebase - when you access a card now, at the end of your turn you receive 2 credits and it states in the log that the identity has been flipped but a) it hasn't been flipped and therefore you do not automatically lose a cred and draw a card at the start of your next turn and b) it seems the issue is related to the fact that when it states your ID has been flipped, the text states the runner's name but only the 'Shiro' part is highlighted (i.e. links to https://netrunnerdb.com/en/card/05019).

**Comment by jwarwick** [comment]
Thanks for the report. Looks like I broke the image flipping (again). I'll get it sorted out.
The `Shiro` text thing is actually a different problem; the engine doesn't view the two sides of Hoshiko as different cards, so it doesn't have a link to use for the flip side. I'll see if I can come up with something there as well, so you can zoom in on whatever side is up.
