### ISSUE TITLE
Utae lacks "match strength" ability

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#5642]
Hi,
it looks like Utae doesn't have the shortcut for matching the strength of the encountered Ice.
When I noticed it I had less than 3 `virtual` resources installed, FWIW.

**Comment by francescopellegrini** [comment]
It looks like [this lack was intentional](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/programs.clj#L2592)..

**Comment by NoahTheDuke** [comment]
Yes it is. We can't currently do auto-pumping/breaking with X costs because of how auto-pumping/breaking is built. Maybe some day in the future we could do it, but it would require rewriting all of that stuff first.
