### ISSUE TITLE
Jak Sinclair causes "waiting for runner start-of-turn effects" window on the corp turn

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#5646]
I've only been the causer of this bug, not the reciever, so this description might be lacking. This bug is probably caused when Jak Sinclair is combined with other start of turn effects like Rezeki or Data Folding. I haven't caused any issue with just Rezekis and Data Foldings. This bug makes the corp player have to input /close-prompt every turn. I haven't tested it thoroughly, but it seems to bug both on manual activation as well as on the reminder activation.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
