### ISSUE TITLE
Zahya gives the option to take credits equal to accesses on any server, not just R&D or HQ.

### ISSUE THREAD

**Issue by wern212** [mtgred/netrunner#5652]
On both Archives and Remote servers, Zahya will give the option to take credits equal to accesses.

![image](https://user-images.githubusercontent.com/55791889/111798842-c08a6a00-88ca-11eb-9a6f-6ca1cb4766dd.png)

![image](https://user-images.githubusercontent.com/55791889/111798964-db5cde80-88ca-11eb-9b44-64c6e9821350.png)

![image](https://user-images.githubusercontent.com/55791889/111799083-faf40700-88ca-11eb-8049-2b246ae0a347.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
