### ISSUE TITLE
Giordano Memorial Field not checking for credits on Net Mercur

### ISSUE THREAD

**Issue by mcgreenhalgh** [mtgred/netrunner#5663]
What happened: Running on an iceless HQ, they rez Giordano Memorial. I have five agendas in my score area so need to pay 10 on a successful run. Currently I have 8 credits in my pool plus 1 on Net Mercur. However, I also have Mu Safecracker and Mantle installed. As it's my turn, Mu Safecracker fires first asking me if I want to pay 1 to access an extra card. I say yes, using Mantle, which allows me to place 1 on Net Mercur. In theory I now have 10 credits to pay for the Giordano, but it didn't give me that option, it only presented end the run.

What Noah said: for whoever decides to fix it, change (:credit runner) to (total-available-credits state :runner eid card) on line 557 of upgrades.clj)

What lostgeek said: Doesn't total-available-credits at that point also need some source info in the eid? (not for Net Mercur obviously but for example for.. Fueno maybe?)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
