### ISSUE TITLE
Fairchild 3 not resolving subs

### ISSUE THREAD

**Issue by edfortune572** [mtgred/netrunner#5667]
Intermittent problem with Botulus and Fairchild 3 - later with boomerang I believe with Botulus still hosted.
![image](https://user-images.githubusercontent.com/71883319/112157716-685faa80-8bdf-11eb-85a8-049ba846ea7a.png)
Let all subroutines fire didn't work, prompt wouldn't close. Undo-click resolved, but repeated a few turns later

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
I think reproducing this issue is no longer possible, so I'm going to close this as stale. If it happens again, please create a new issue.
