### ISSUE TITLE
Earth Station: SEA Headquarters shows giant warning when running central servers

### ISSUE THREAD

**Issue by Lokkij** [mtgred/netrunner#5669]
Playing against an Earth Station: SEA Headquarters deck, jinteki popped up a giant warning (see screenshot) whenever I ran a central server. Notably this happened when Red Team was installed, which is also mentioned in the warning. It definitely appeared when making a run with Red Team, though I also recall it happening when making a run not through Red Team. This warning did not appear when using Red Team against other corp IDs.

To reproduce:
- Play against an Earth Station: SEA Headquarters deck (and maybe flip the ID - not sure if this matters)
- Play Red Team
- Make a run on a central server using Red Team

As far as I can tell, the warning should then appear.

![Screenshot 2021-03-23 at 21 01 30](https://user-images.githubusercontent.com/1315413/112220740-e3987f00-8c26-11eb-9ded-30c08997c202.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
