### ISSUE TITLE
Trashed cards keep their counters instead of having them cleared

### ISSUE THREAD

**Issue by Makai** [mtgred/netrunner#567]
Trashed installed cards keep their counters while in the heap or archives. This can be an issue as, if the card is later reinstalled, it will still keep all its previous counters.

Reproduced with a Datasucker loaded with counters that is trashed by an Ichi1.0 and after being Clone Chipped back and still contains all its previous virus tokens.

**Comment by queueseven** [comment]
Maybe introduced with #563 where I've accidentally put something into the `and` part while it should be in the `or` part of the `move` function, but I fixed it with #572.

**Comment by JoelCFC25** [comment]
Fix has been deployed.
