### ISSUE TITLE
Jailbreak multi-access should work even when the run is not successful

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#5672]
https://github.com/mtgred/netrunner/blob/717d3cc8573141b16a271fa7a8b30dc100ef5739/src/clj/game/cards/events.clj#L1644

If I understood correctly how [Jailbreak](https://netrunnerdb.com/en/card/30028) works, it should grant multi-access even when the run is not successful, e.g. when there is a rezzed Crisium Grid, right?

**Comment by NoahTheDuke** [comment]
Thanks for the report! Looks like the card text has been updated since the card went live on NRDB to make this interaction clear, meaning jnet is currently implementing the card correctly: you shouldn't get the extra access if the run isn't marked successful.

**Comment by francescopellegrini** [comment]
Oh.. that's weird.. I always thought effects separated by "." were independent from each other. Well, good to know.

**Comment by NoahTheDuke** [comment]
You're absolutely correct, which is why they're changing it. In playtesting (when we implemented these cards), Jailbreak was written to make the intention clear, and this intention was lost momentarily after the rules team cleaned up the wording.
