### ISSUE TITLE
Tinkering errors

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#568]
Tinkering grants sentry, code gate, __and__ barrier to a piece of ice, not just one of those; we show a prompt to choose one subtype. It is also printing the name of the targeted ice to the log even if that ice is not rezzed.

**Comment by queueseven** [comment]
@nealterrell Tinkering granting sentry, code gate, and barrier is correct. The card reads: "Choose a piece of ice. That ice gains sentry, code gate, and barrier until the end of the turn."

**Comment by queueseven** [comment]
I hang my head in shame...
