### ISSUE TITLE
Leech gives the runner the option to place a virus token, but the ability is mandatory.

### ISSUE THREAD

**Issue by wern212** [mtgred/netrunner#5685]
[Leech](https://netrunnerdb.com/en/card/30008) gives the runner a choice to place a virus counter (or not) when making a successful run. However, the ability is mandatory.

![image](https://user-images.githubusercontent.com/55791889/112521179-83c3e480-8d9c-11eb-89ee-2dc4f388f067.png)

![image](https://user-images.githubusercontent.com/55791889/112521192-88889880-8d9c-11eb-96a8-11cf0b5c690a.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
