### ISSUE TITLE
Jailbreak + Crisium

### ISSUE THREAD

**Issue by armerpaul** [mtgred/netrunner#5690]
Expected: When running on a server with Crisium Grid, Jailbreak should grant an additional access when breaching. Jailbreak should not grant the draw since the run wasn't "successful" due to Crisum.

Observed: Jailbreak does not grant an additional access on a server with Crisium. It does however not give the draw.

**Comment by francescopellegrini** [comment]
I thought so as well, but apparently I was wrong: see #5672

**Comment by armerpaul** [comment]
Oh good to know! Thanks for the context. Closing this now!
