### ISSUE TITLE
Anoetic Void ends the run, but still triggered successful

### ISSUE THREAD

**Issue by Eric-Fletcher** [mtgred/netrunner#5692]
Spraybizzle3 approaches ICE protecting Server 2 at position 0.
EricF pays 0  to rez Anoetic Void.
Spraybizzle3 passes ICE protecting Server 2 at position 0.
Spraybizzle3 approaches Server 2.
EricF has no further action.
EricF pays 2  and trashes 2 cards (a card in HQ, a card in HQ) from HQ to use Anoetic Void to end the run.
Spraybizzle3 uses Dirty Laundry to gain 5 .
Spraybizzle3 is ending their turn 14 with 14  and 3 cards in their Grip.

**Comment by francescopellegrini** [comment]
Fixed by #5676?
