### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#57]
Is it possible to have the chat extend all the way up the right side of the window? Card scroll over would obscure the top portion of chat history.

Can you add a turn counter somewhere?

**Comment by PinkWarrior** [comment]
I don't know if this is the right thread for new features or whatever but it would be nice to have a successful no access button as the runner for use with cards like Security Testing, Ash or any of the Shards as jacking out can also screw with Virus's (like data sucker or haemorrhage) and John Masanori.
