### ISSUE TITLE
Malapert Data Vault + Armed Intimidation - "when you score" forced resolution order

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#5702]
When scoring an Armed Intimidation from a server with _Malapert Data Vault_, the Corp player is forced to resolve _Malapert Data Vault_ first, before the Runner is given the choice between taking 2 tags or taking 5 meat damage.

**Expected Behaviour:** when scoring an agenda with a "when you score" ability (such as _Armed Intimidation_) from a server with _Malapert Data Vault_ installed and rezzed, the Corp player should be able to choose the order of ability resolution.

**Actual Behaviour:** scoring some agendas works as expected, scoring _Armed Intimidation_ forces the order of resolution

Standoff - OK
Hostile Takeover - OK
Armed Initimidation - NOT OK

**Comment by NoahTheDuke** [comment]
Thanks for the report!
