### ISSUE TITLE
Feature idea: Do not allow cards to resolve abilities while a prompt of that card is open

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5705]
There often are situations, where players open a second prompt, while still resolving the first on the same card (e.g. trying to break a subroutine, while already being in the prompt for breaking subroutines with the same card). We could disable resolving card abilities on cards, while a prompt of that card is still open.

**Comment by NoahTheDuke** [comment]
Let's bundle this into disallowing taking actions while resolving actions.
