### ISSUE TITLE
Omar, DJ Fenris, Steve, Crisium Grid

### ISSUE THREAD

**Issue by greyfield** [mtgred/netrunner#5713]
I know the above combination creates a whole set of issues, but: I made an Omar run with DJ Fenris installed set to Steve on Archives, which I diverted to HQ, which had a rezzed Crisium Grid. Jnet prompted me to choose cards for Steve, which it shouldn't do.

**Comment by NoahTheDuke** [comment]
Thanks for the report! That's quite a bundle of abilities all at once, but I think we can work it out.

**Comment by AlexBoyd** [comment]
In another game I saw something similar. 

There was a rezzed Crisium oh HQ and a Steve Sneak doored into HQ. That triggered an Earth Station flip and Steve's ability.

Later in the game a rezzed Crisum on Archives did correctly block the sneakdoor though, so it looks like redirect + crisum is the common factor in all cases.
