### ISSUE TITLE
Suggestion: Checkbox for posting Tournament Hash of both players decks in game log at start-of-game

### ISSUE THREAD

**Issue by Terrificy** [mtgred/netrunner#5714]
By letting players see the tournament hash of decks, the process of deck checks during online tournaments can be made easier - by cross-referencing a list of the tournament hash of all players' decks at the tournament with the one in the game log, a player can verify that their opponent is playing the submitted decklist, eliminating the possibility of cheating, and thus also eliminating the need for tournament organizers to deck-check players.

**Comment by NoahTheDuke** [comment]
Thanks for reminding me about this, it was indeed our goal to reveal the tournament hashes in game lobbies.
