### ISSUE TITLE
Distinguish between System Gateway games

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#5720]
It should be pretty forward to make it so we can distinguish between types of System Gateway games:

- System Gateway [starter deck] (either specific starter decks or decks with 30/34 cards and the neutral identities)
- System Gateway [booster deck] (either specific booster deck, or cards from SG using neutral identities)
- System Gateway (the rest where whole SG card pool is legal

There seem to be some confusion especially when creating the games (title) and decks are valid so you dont discover it until after game is started :)

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion!
