### ISSUE TITLE
Exchange of Information + Tomorrow's Headline = tagged Runner

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#5725]
Tomorrow's Headline should not give the Runner a tag when it's swapped via Exchange of Information.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Couldn't reproduce it anymore. Probably it's been fixed by https://github.com/mtgred/netrunner/commit/5267e80a84ee55e7b2f33efa2b84c07d9785b853.
