### ISSUE TITLE
No horizontal scroll bar - can't use remote servers

### ISSUE THREAD

**Issue by KenExpressTenma** [mtgred/netrunner#5732]
<img width="960" alt="jnet scroll problem 2" src="https://user-images.githubusercontent.com/81697731/113161785-b3e00d00-920c-11eb-9784-27b4f1b4f7b2.PNG">

Hello. I was playing last night as the Corp and I had created 7 remote servers, but I couldn't scroll over to use servers 4 to 7. They were hidden behind the chat box, and server 7 was off screen completely. There was no way from me to scroll over to reach them. Would it be possible to get this fixed? Thank you!

**Comment by NoahTheDuke** [comment]
Thanks for the report!
