### ISSUE TITLE
Move card to front on hover

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5735]
When having stacked cards on a server (or runner board), move currently hovered card to front to make situations with multiple cards with counters more readable.

**Comment by Dirjel** [comment]
This update broke the ability to use cards in some situations:

If you install 3 cards and they auto-stack (e.g. 3 Smartware), you can't click the middle one.  This is bad for cards with activated abilities (again, e.g. Smartware) and also for cards with recurring credits (e.g. Multithreader), where you can't click the middle card to remove its hosted credits.

This issue can also be seen on Corp side, e.g. by installing 3 Shell Corporations in 1 remote server.

**Comment by NoahTheDuke** [comment]
If you need to select a specific card in a stacked server or in the rig, click the "Unstack Servers" button in the toolbar at the top of the screen.

**Comment by Dirjel** [comment]
I tried that, and the "unstack servers" button did not unstack the installed runner cards. 

I did not try on corp side, but I am fairly certain that would not work, as all three cards are in the same server.
