### ISSUE TITLE
Subliminal Messaging should trigger Hyoubu

### ISSUE THREAD

**Issue by marckubischta** [mtgred/netrunner#5744]
[Subliminal](https://netrunnerdb.com/en/card/31082):
> When your turn begins, if this card is in Archives and the Runner did not initiate any runs during their last turn, you may reveal this card and add it to HQ.

[Hyoubu](https://netrunnerdb.com/en/card/26039):
> The first time each turn you reveal a card, gain 1 credit.

**Comment by marckubischta** [comment]
Currently this has to be done manually.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
