### ISSUE TITLE
Decklists showing up as empty in the replay function

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#5745]
As shown in image 

![image](https://user-images.githubusercontent.com/3453320/113392173-b05e9a00-9362-11eb-8ba2-97cbba4681a4.png)

The replay in question is this one https://www.jinteki.net/replay/c42f1387-f003-48c4-adbd-dc689e7822f6

**Comment by NoahTheDuke** [comment]
Thanks for the report!
