### ISSUE TITLE
New accounts get every starter deck twice

### ISSUE THREAD

**Issue by Hunter16g** [mtgred/netrunner#5759]
![Screenshot from 2021-04-05 21-07-46](https://user-images.githubusercontent.com/15839619/113614607-02e5d200-9653-11eb-990a-0d6f309ec869.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by jwarwick** [comment]
Thanks! It appears we had extra decks in the set of new user decks. I've updated the server. Should only get 4 now.
