### ISSUE TITLE
Forged Activation Orders does not block the runner while the corp is selecting if rez or trash

### ISSUE THREAD

**Issue by PreNic** [mtgred/netrunner#5760]
Once the runner has selected an ice as target for Forged Activation Orders, I would expect, as runner, to see a message that the corp is deciding to rez or trash, preventing me to click. Instead, as soon as the target for FAO is selected, the usual "Remove Tag", "Run" etc. buttons are immediately available.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
