### ISSUE TITLE
Odd results when recurring ice from archives

### ISSUE THREAD

**Issue by mikeprosser** [mtgred/netrunner#5762]
No real downside here but slightly odd messaging when archived memories-ing a piece of ice from archives

![image](https://user-images.githubusercontent.com/14224523/113710417-92cf5e80-96db-11eb-8965-ea61eb9bfd57.png)

![image](https://user-images.githubusercontent.com/14224523/113710534-bc888580-96db-11eb-8abf-0f5c6194a8db.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! I believe this is being worked on.
