### ISSUE TITLE
Improve "Cards Accessed" endgame stat

### ISSUE THREAD

**Issue by lopert** [mtgred/netrunner#5763]
Currently, the `Cards Accessed` endgame stat increments for every card in archives, every time the runner accesses archives.  
Ex: If there's 10 faceup cards in archives, and I run archives 4 times, I've accessed +40 cards.

This leads to inflated stats, and sort of ruins the usability of the stat.  

Rework ideas:

- The count increases only from facedown cards in archives.  This way it still represents new information being gained.
- The count excludes archives entirely. This way it represents `Cards Accessed from HQ+RnD` instead.

**Comment by NoahTheDuke** [comment]
Thanks for the idea! I'll be working on this when I get a chance.

**Comment by bblum** [comment]
thread necro but +1 to this one
