### ISSUE TITLE
Sneakdoor is still declaring a successful HQ run when HQ has crissum on it.

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5764]
This shouldn't be the case, what should happen is you get a not-successful run on HQ and enter the access phase.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
@NoahTheDuke this one has a test asserting the correct behavior and can be closed (see #6238)

**Comment by NBKelly** [comment]
This was fixed, and we've got unit tests for it now via #6238
