### ISSUE TITLE
Atman does not work with recurring credits

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#5772]
When you select how many power counters to place on Atman, it does not take into account recurring credits from e.g. Mantle or Multithreader, and does not prompt to use recurring credits from those sources when resolving the ability.

So if you have two Multithreaders installed and 1 c in your credit pool, you should be allowed to go up to 5 power counters, but the prompt will only give you the option for 1, and when you resolve the ability it automatically takes your 1c from your credit pool.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
