### ISSUE TITLE
Add timing chart to somewhere in the Jinteki.net UI

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#5773]
Maybe in a tab in the log? maybe as a full main tab on the top? Maybe as a background image? I dunno! 

but I'm adding this just because I've talked to someone before about this, but was just reminded that all of those discussions are ephemeral, it's the Github Issue list that is forever

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion! This or something like it is planned, along with stricter enforcement of timing related stuff.
