### ISSUE TITLE
Make the text commands more visible

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#5774]
At the moment I need to go to help -> scroll down, but I feel like the text commands have turned into somewhat basic functionality at this point, new players won't know to go there.

Maybe in a tab in the log? maybe as a full main tab on the top? Maybe as a background image? I know that Bobtomatoes suggested making them as a tab in the log that provided buttons. That works too.

but I'm adding this just because I've talked to someone before about this, but was just reminded that all of those discussions are ephemeral, it's the Github Issue list that is forever

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion!

**Comment by merrickbrown** [comment]
I'm very tempted to take a stab at autocomplete in the chat box for this
