### ISSUE TITLE
Street Peddler and The Supplier do not take Kate's install discount into account

### ISSUE THREAD

**Issue by Makai** [mtgred/netrunner#578]
Cards like Street Peddler and The Supplier do not take Kate's discount into account when displaying cards you are allowed to install from them. 
Example: If you have a Plascrete hosted on The Supplier and have no credits at the beginning of your turn you will not be prompted to install it even though it should cost zero to install with Kate.

This is due to the card filtering using ```(:cost %)``` to figure out what cards to allow the user to attempt to install which does not take any discounts into account.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It's added to the TODO list.
