### ISSUE TITLE
Mayfly & Compile Need Window to Choose Ordering

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#5781]
If runner uses compile to install Mayfly, then uses it to break a subroutine during that run, when the run ends Mayfly and Compile will meet their conditions simultaneously, and mayfly should go to heap or bottom of the stack depending on how the runner chooses to order their triggers (it should have the box that lets you pick which trigger goes first).  Currently, no box appears and mayfly always goes to the bottom of the stack.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
