### ISSUE TITLE
Magnet Doesn't Print Moved Programs to the Log

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#5788]
When magnet pulls a program, it seems like it should print something like "<Player> uses Magnet to move <Program Name> to Magnet" but currently prints nothing.  See image below, where magnet pulled a tranquilizer:  
![image](https://user-images.githubusercontent.com/17117909/114327628-7c703b00-9aff-11eb-9c99-420cef76991b.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! We can def add something for this.
