### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Rorschach71** [mtgred/netrunner#5789]
Hi, I'm trying to get back into Jinteki.net

When I signup - it says "email account already in use", so then I...
Reset password and enter same email account when it then says "No account with that email address exists"

It's a viscous circle....

Have cleared cookies and closed down Chrome before retrying but still no luck.

Any help?

**Comment by NoahTheDuke** [comment]
Thanks for letting me know. Have you made sure to check your capslock? I think our checker is case sensitive.

**Comment by NBKelly** [comment]
I don't think this issue is relevant to the current state of the code base, so I'm going to close it as stale. If you're still having this issue, please create a new issue.
