### ISSUE TITLE
Blue Sun ability retains rez state

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#579]
To reproduce:

install curtain wall, end turn
runner runs on server protected by curtain wall, rez curtain wall
activate blue sun's ability and target rezzed curtain wall
re-install curtain wall on same server (in my case, at least)
curtain wall installs rezzed

**Comment by queueseven** [comment]
Fixed with https://github.com/mtgred/netrunner/pull/572

**Comment by JoelCFC25** [comment]
Deployed!
