### ISSUE TITLE
Harishchandra reveal does not display cards in the log, or allow spectators to see the cards

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#5791]
I believe the Harishchandra Ent. cards revealed while the runner is tagged should be printed in the log when the runner receives a tag, and whenever the runner draws a card or has a card added to grip while tagged that should also show up in the log.
Currently, while both players know the contents of the runners hand (making it no longer hidden information), spectators are unaware of the cards and the corp player is likely required to take notes as to cards seen, and the runner player notes as to which cards the corp has seen.

**Comment by NoahTheDuke** [comment]
Thanks for the report! I actually have a fix for this wrapped up in a larger PR. I'll see about pulling it out.
