### ISSUE TITLE
Add a Dev channel to jinteki.net

### ISSUE THREAD

**Issue by domtancredi** [mtgred/netrunner#580]
Would it be possible and beneficial to add a "dev" or "development" channel to jinteki.net? Given I'd like to contribute, and having followed instructions in tool setup, and local environment setup, I'm not sure what task is the priority. Talking with someone via IRQ would make sense. Although the system already supports chat as a feature, so why not leverage that as a place to discuss and collaborate on feature development?

Just a thought.

**Comment by queueseven** [comment]
We use Slack and Trello for coordinating the work. I can send you an invitation to our Trello board if you want (I just need your mail adress). For Slack, you'll have to ask @mtgred, or I will ask him to invite you once I have your mail adress.

**Comment by domtancredi** [comment]
Awesome. I'm dom@domandtom.com. We use Slack and Jira, though I also use Trello.

Maybe that should be in the wiki pages documentation because that is awesome!

**Comment by mtgred** [comment]
Invitation sent for Slack.

Neal made nice video explaining some of the concept. It will help you get started. https://www.livecoding.tv/video/jintekinet-intro-tenma-line-12/

**Comment by queueseven** [comment]
@JoelCFC25 I think this issue can be closed

**Comment by domtancredi** [comment]
Agreed, good call.

*Dom Tancredi* | *Partner*
*DOM & TOM*
*A 2014* *Inc.* 500* Fastest Growing Company*
55 Broadway, 7th Floor, New York, NY 10006
Office: 646 741 5043 | Mobile: 718.431.5137
dom@domandtom.com | domandtom.com
