### ISSUE TITLE
Issues with Spending Overclock Credits Crashing Game?

### ISSUE THREAD

**Issue by AgashaKC** [mtgred/netrunner#5804]
Game seems to glitch after spending credits from Overclock to trash cards. When it does, I can't get back into the game.

**Comment by AgashaKC** [comment]
May be trashing in general. Not sure.

**Comment by greyfield** [comment]
I've had two crashes today which didn't involve Overclock, though one of them happened during a run in which I tried accessing two cards from a remote server (first time I encountered the new card-flipping effect to make it easier to click overlapping cards); the moment I tried clicking on the second card in the remote was when it crashed. By crashed in both cases, I mean the game wouldn't register I'd done anything, including pressing buttons or sending chat messages, unless I left the game and rejoined every single time. My opponent seemed to have a similar problem, as he left and came back, and then suddenly the engine duplicated the agenda I'd just stolen in the aforementioned run. So I think maybe that card-flipping interface has something to do with it? I dunno, this is a new one for me.

**Comment by NoahTheDuke** [comment]
We rolled out some changes today that fundamentally broke some parts of the game, but obscure enough that we spent the day trying to figure out why or how. Thankfully, we should have a fix up tonight or tomorrow that will fix these issues.

**Comment by jwarwick** [comment]
I believe the crashing fix is addressed now. Thanks for the info helping us track it down.
