### ISSUE TITLE
Mirrormorph Triggering Before Third Action Resolves

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#5809]
Currently, mirrormorph is triggering before the corps third action resolves.  This is relevant for the case where cards are being drawn on click 3, and corp would like to see them before deciding whether to take an action or a credit.  

For example, if Corp takes the following turn:

Click 1:  Install
Click 2:  Gain a Credit
Click 3:  Draw a Card

They receive the mirrormorph prompt before seeing the card drawn by click 3.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
