### ISSUE TITLE
Suggestion: Have two different panels for games: Open and In-Progress. Sort Open games with oldest on top.

### ISSUE THREAD

**Issue by JoeyKL** [mtgred/netrunner#581]
It's not a huge problem, but it happens from time to time that you'll make a game and then a few other games will be made on top of you. Then people will join those games since they're on top and new games will be made and you'll become buried.

Sorting the games as waiting to start or already in progress makes since anyway, and this way the people who have had an open game longest will be most likely to get a match up.

**Comment by nealterrell** [comment]
This has been addressed so that open games are always on top.
