### ISSUE TITLE
Flame-Out Trigger Appearing Many Times When Resolving End of Turn Triggers

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#5810]
If there are multiple end of turn triggers, and one of them is flame-out, the flame-out trigger one time for each time credits were taken from it.  It should appear only once.  While its hard to conceive of a situation where it matters for gameplay reasons, it makes a pretty big mess in the abilities ordering box.

![image](https://user-images.githubusercontent.com/17117909/115046989-b2b20f80-9e9d-11eb-95a0-1578ea08bf3c.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report! That's very funny and very annoying.
