### ISSUE TITLE
Feature Request: Game/Player timer

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#582]
This is really just a would-be-nice for those that concern themselves with time when it comes to prepping for tournaments and what not, just a clock somewhere on the board that shows how long each player's turn takes.  An additional nice feature would be how long the overall game takes.

**Comment by erithtotl** [comment]
I took think this is an excellent idea.  Basically, the creator of the game picks a length, and this appears in the lobby, so people playing them will be aware of the game length before going forward.

**Comment by msbeck** [comment]
I see two different requests reflected in these comments. One seems to be a clock present in-game that counts up starting at the beginning of each turn. The second is a countdown clock in game, as well as the selected time indicated in the lobby.
