### ISSUE TITLE
Feature Request: make chat window on right-hand side resizable

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#583]
For many resolutions, there's a lot of unused horizontal real estate between the chat window and the cards, and the chat window frequently has wrapped text.  It would be nice if this had a resize bar to make it possible to change the horizontal size of the chat pane.

**Comment by dtelad11** [comment]
A temporary solution: you can zoom-in/zoom-out in your browser (Ctrl-(+), Ctrl-(-)) to resize the whole interface.

**Comment by zaroth** [comment]
Related to #512
