### ISSUE TITLE
Spooned will not trash ice painted with Engolo

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#5842]
I've been playing Kit with Engolo and Spooned. Spooned will trash ice when painting it with Kit's ability, but not with Engolo's ability.
Edit: seems like spooned will only trash the first codegate encountered each turn and it's not related to engolo or kit.

**Comment by NoahTheDuke** [comment]
The issue is that Spooned won't trash a fully broken Code Gate later in a run after not breaking an earlier Code Gate?

**Comment by gorka-larrea-montoya** [comment]
The issue seems to be that spooned will only trash the encountered ice if it is the first codegate encountered that turn. 
If I encounter and break a codegate without Spooned, then play spooned in a second run, it will not trash. Seems like painting abilities like Engolo and Kit don't interfere.
https://www.jinteki.net/replay/960cbe88-6d7d-4495-9920-711d93e3ca6a - test game with Kit
https://www.jinteki.net/replay/08c1f78d-4a1c-452f-8965-25f83c678229 - test game with Tao
