### ISSUE TITLE
Unauthenticated users see "0 games"

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#5845]
When not logged in, users see this:
![screenshot](https://i.imgur.com/7CK71S6.png)

We should either remove that display entirely or reveal lobby information to unauthenticated users as well. The current state pushes away newer players that are interested in Netrunner.

**Comment by NoahTheDuke** [comment]
Good point. I'll take a look cuz it's something to do with the csrf routes and web sockets.

**Comment by lallmon** [comment]
I agree with @lostgeek about pushing away new players at worst, or being confusing at best. I taught someone Jinteki the other day and they said: "Why does it say 17 games next to my name? I haven't played any yet." AND, they tried to click it.

If folks are tied to it, a UX solution might  be to add it to the Play link. Something like `Play (22 Tables)`, or the number in a badge, though typically on apps with low user numbers, you don't wanna disclose how low 😆

**Comment by lallmon** [comment]
I was fiddling with CSS in the browser today, and mocked up this:
![bubble](https://user-images.githubusercontent.com/1824267/117522018-bfd69180-af65-11eb-904f-9916b3ae6810.png)

While it's a little disingenuous that there are 22 _available games_, it could possibly help turn the PLAY button into **the** call to action. (pay no attention to the other changes, I did it in browser and didn't wanna lose changes)

**Comment by queueseven** [comment]
When not logged in, I can see the number of games. So I guess somebody fixed it already?

![grafik](https://user-images.githubusercontent.com/3126597/181013871-a70f032d-dd73-443c-98b9-ad6b075b5b40.png)
