### ISSUE TITLE
chisel installed after encounter still trashed ice.

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#5852]
Link to bug replay: https://jinteki.net/bug-report/2fea897a-1682-430d-99df-e4d5ccbbb69b?b=0

Description: Chisel installed via SMC after encounter still fired and trashed ice.

Runner ran on server 1, devil charm popped when ice rezzed, then popped SMC to install chisel and chisel trashed the ice.  checking on #rules on stimhack, jade said: Smc is a paid ability
10:01
You can’t do SMC until “when encountered” is over (edited) 

The only way to install chisel and have it trigger is to use SMC (or simulchip or whatever) during the approach

The runner had all the pieces, so no saltiness, but i was surprised it fired this way.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
#7669 makes it so you can't pull this off anymore.

Closed as completed via #7669
