### ISSUE TITLE
[Ice] Bran should report what ice was installed if it was installed faceup from archives. 

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#5854]
Link to bug replay: https://jinteki.net/bug-report/2d238063-e362-4fff-afad-e7d5966bac93?b=0

This is talking about the 3rd subroutine

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by h4pp7** [comment]
Maybe I'm mistunderstanding the issue, but the log says "$CORP uses Brân 1.0 to install Whitespace from Archives."
