### ISSUE TITLE
Feature discussion: ELO rating

### ISSUE THREAD

**Issue by lbrande** [mtgred/netrunner#5855]
Based on some initial discussions in the Green Level Clearance #jinteki-net channel I propose the addition of ELO rating to [https://www.jinteki.net](https://www.jinteki.net) as follows:

- Each player has 2 ELO ratings, one for "Startup" and one for "Standard"
- All games played in the "Competitive" lobby impact your ELO for the format being played.
- In all games your ELO (for the format being played) is shown together with your name (so that your opponent has an idea of your skill/experience).
- A new tab is added to the right of "Stats" called "ELO Ratings" in which all player's ELO ratings for both formats are shown in a list that can be sorted based on either the "Startup" ELO or the "Standard" ELO.

Before implementing ELO rating we need to make sure this is something the community is interested in. Please use the following poll to share your opinion: [https://www.strawpoll.me/45204798](https://www.strawpoll.me/45204798)

If you have any suggestions for the actual implementation, or any other comments please write them as replies below.

**Comment by lbrande** [comment]
The following was missed in the above proposal:

- If a player leaves a competitive game in progress the opponent is given a win.

**Comment by NBKelly** [comment]
The ship has probably sailed, but there's now a tournament ranking system (beanstalk, independent of jinteki.net).

See: https://netrunner-beanstalk.net/
