### ISSUE TITLE
Aginfusion skips outermost unrezzed ice

### ISSUE THREAD

**Issue by MarsKiu** [mtgred/netrunner#5866]
Aginfusion special ability skips the outermost unrezzed ice of a server for some reason hitting either the second unrezzed ice if available or server directly.

**Comment by ais523** [comment]
This is not a bug, it's how the AgInfusion ability actually works. It moves directly to the "encounter ice" phase, skipping the "approach ice" phase. So if the outermost ice is unrezzed, the corp gets no chance to rez it and the Runner just passes it automatically.
