### ISSUE TITLE
Street Peddler can duplicate cards

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#587]
Click on an installed Street Peddler to install a card, but don't click on a card in the prompt yet. Trash Street Peddler manually (by dragging it into your discard).Then select a card from the prompt. That card gets installed, but it's also in your discard.

**Comment by queueseven** [comment]
Duplicate to #290. Same problem I think

**Comment by queueseven** [comment]
Well, since this issue is still open it seems like I have to fix it myself if the issue is still relevant... :-p

**Comment by queueseven** [comment]
Checked this. Issue is still relevant.

**Comment by Saintis** [comment]
Could this be solved by reloading the card before installing so that it will be moved out from the heap?
