### ISSUE TITLE
Feature request: Prevent runners from installing programs from grip during runs

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#5870]
Was teaching a friend the game earlier this week and I was surprised to see the platform allowed them to do this. I explained the rule and we undo-turn'ed of course but it seems like it could be a good pedagogy moment if jnet could pop up a warning saying why that's not allowed instead.

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion! Currently, we don't disallow most things during a run, but this limit has been considered and I have plans for it (as seen in #5718).

**Comment by ais523** [comment]
Note that if you do this, there needs to be some way to allow the Runner to override and install manually. The main situation in which this is required is if the Runner wants to install multiple copies of MKUltra from the heap upon encountering a sentry – the interface only allows one to be installed (which is probably sensible, as it's what you'll want in 99% of situations), so when the Runner does want to install multiples, the extras have to be installed manually. (Perhaps this could be done by clicking on the MKUltra in the heap.)
