### ISSUE TITLE
Recon drone offering to prevent damage even when cards are not being accessed by the runner.

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#5874]
Link to bug replay: https://jinteki.net/bug-report/b713bd1a-4b9b-4195-8f66-f1853c43668b?b=0

Description:  Recon drone installed, offered option to prevent damage from Neurospike, despite there not being a card accessed at the time.

**Comment by francescopellegrini** [comment]
Hi @plural, could you please update the title for this issue?

@NoahTheDuke could Recon Drone be refactored to work as Imp (which works great)?

Recon Drone:
https://github.com/mtgred/netrunner/blob/5a189c3135b21af2814e35bdd19256011e167a39/src/clj/game/cards/hardware.clj#L1556-L1557

Imp:
https://github.com/mtgred/netrunner/blob/5a189c3135b21af2814e35bdd19256011e167a39/src/clj/game/cards/programs.clj#L1419

**Comment by NoahTheDuke** [comment]
Probably! I'll have to take a look.
