### ISSUE TITLE
Ice not trashed on Spooned run if painted but not broken with Engolo

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#5877]
On a run with Spooned, I used Engolo to make a Karuna on RnD a code gate, but used an MKUltra to break it (as it was both a sentry and code gate). It didn't trash however despite matching the conditions for Spooned.

![image](https://user-images.githubusercontent.com/52526629/117738534-2a9cfc80-b1f4-11eb-9d28-9c9ec7fb8219.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Duplicate of #5842?

**Comment by NoahTheDuke** [comment]
Yes, I think so.

**Comment by francescopellegrini** [comment]
Might as well close this.
