### ISSUE TITLE
Not a contributor -- a couple of tweaks

### ISSUE THREAD

**Issue by dtelad11** [mtgred/netrunner#588]
Added the following:

To `cards-programs.clv`,

    "Multithreader"
    {:recurring 2}

To `cards-identities.clv`,

    "Sunny Labeau: Security Specialist"
    {:effect (effect (gain :link 2))}

It's not much but could one of the contributors copy/paste it into the relevant sections?

**Comment by nealterrell** [comment]
Looks like you took care of this :)

**Comment by dtelad11** [comment]
Yep sorry -- completely forgot about forks (it has been years since I
contributed to open source). Should have closed this after Minh's tweet.
Thanks!

**Comment by nealterrell** [comment]
Not a problem. Thanks for the contribution!
