### ISSUE TITLE
Taking brain damage didn't cause runner loss when it should have

### ISSUE THREAD

**Issue by mgsholte** [mtgred/netrunner#5893]
Link to bug replay: https://jinteki.net/bug-report/3f632c5f-913a-45e4-ad12-70606b56eb01?b=0

Description:

Took brain damage from a Brainstorm to a total of 8 brain damage. Runner's max hand size was -3, but the game didn't register a victory for the corp.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
This is an old issue, but the game doesn't end for the runner *until they are forced to discard more cards than they have in hand* - which will be the end of the turn.

I'll make sure we've got a unit test for this case anyway.
