### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by Sonalator** [mtgred/netrunner#5894]
Link to bug replay: https://jinteki.net/bug-report/76d0c170-6778-4bea-b0bb-2399e1064adb?b=0

Description: Rebirth on Shaper (from Wu) showed Kate as an option on Standard.

1. Play Rebirth
2. Choose Kate
3. ???
4. Profit

**Comment by francescopellegrini** [comment]
Similar to #5125?

**Comment by Sonalator** [comment]
Exactly like #5125 .

Στις Τετ, 19 Μαΐ 2021, 13:49 ο χρήστης Francesco Pellegrini <
***@***.***> έγραψε:

**Comment by NoahTheDuke** [comment]
Thanks for the report! Closing as it's a duplicate.
