### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Yog0** [mtgred/netrunner#5895]
Browsers used: Brave, Chrome, Firefox.
Operating system: Windows 10

Unable to log in - I receive the message "Invalid login or password". This persists after resetting my password, and also occurs if I create a new account. However, I am still able to log in to my account on a different computer running Mac OSX 11.13.1 and Chrome. Until 18 May, I was able to log in on my Windows computer with no issues. No network, hardware or software changes have been made. 

Attempted fixes:
- Hard refresh browser
- Clear cache
- Create new account
- Reset password

**Comment by NBKelly** [comment]
Hi, I think this issue is no longer relevant to the current state of the codebase, so I'm going to close it as stale. If you have any more issues like this, please create a new issue.
