### ISSUE TITLE
Daily Business Show 

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#5896]
While playing a game in the StartUp format as NEH and having two rezzed Daily Business Shows on the board, the game stuck after several turns working as intended. 
The additional cards were drawn, but I could not click on any cards in my hand to select those that go to the bottom. Logging in and out did not help either. 

Machine: MacBook Pro 13-inch, M1, 2020. macOS Big Sur 11.3.1
Browser: Google Chrome 90.0.4430.212

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
I don't know if the original issue here was fixed, but we since redesigned how cards like DBS worked in a way that makes this issue obsolete - see #6362 for more details.
