### ISSUE TITLE
Demolisher triggers multiple times if multiple cards are trashed simultaneously

### ISSUE THREAD

**Issue by mgsholte** [mtgred/netrunner#5898]
Link to bug replay: https://jinteki.net/bug-report/4fb7650f-993a-47d2-9f7c-28f00ca1ce96?b=0

Description:

Used Persephone to trash 3 cards from R&D in a single trigger. Demolisher provided 3 credits to the runner instead of 1.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
