### ISSUE TITLE
Rabbit Hole Hard Lock

### ISSUE THREAD

**Issue by 4716** [mtgred/netrunner#59]
1) Installed a Rabbit Hole as part of my turn.
2) Clicked yes to install a second rabbit hole, as written on card
3) Given option to install third rabbit hole, clicked yes on accident, did not work since I had insufficient credits or a third rabbit hole in the deck, and game will not allow me to click no, add more credits, or anything else. Can take no action at all.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The problem is now fixed. The server will be updated tomorrow.
