### ISSUE TITLE
Public Support cannot be forfeited in score area to rez Archer

### ISSUE THREAD

**Issue by BenTsui** [mtgred/netrunner#590]
as title

**Comment by JoelCFC25** [comment]
I'm guessing this is because all the cards that can get added to the score area "as an Agenda" have no `:agendapoints`, which the definition of `forfeit` needs. Could be as simple as an `assoc` to the card definition for everything that can end up in the score area this way.

**Comment by mtgred** [comment]
Thanks for the reporting the issue. We'll take care of the issue.

@JoelCFC25 It's indeed the issue.

**Comment by JoelCFC25** [comment]
Fixed at https://github.com/mtgred/netrunner/commit/f9ba35d5518117220497a21eadcbbc678b0fc423 and now deployed.
