### ISSUE TITLE
Omar ability prevents Turning Wheel additional accesses

### ISSUE THREAD

**Issue by mgsholte** [mtgred/netrunner#5911]
Link to bug replay: https://jinteki.net/bug-report/f9f5fa81-ebef-497d-8361-eae1ea6bfa44?b=0

Description:

When the runner uses Omar's ID ability to run archives and switch to HQ or R&D, spending tokens on Turning Wheel does not cause additional cards to be accessed.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
