### ISSUE TITLE
During Attitude Adjustment, clicking on archives w/ agenda displayed on top simultaneously selects agenda and opens archives window

### ISSUE THREAD

**Issue by JordanFoley** [mtgred/netrunner#5912]
When using Attitude Adjustment, it is common to split the agenda shuffles between HQ and archives. It is also natural to select the more immediately available agenda in HQ before selecting the agenda in archives.

However, if the visually displayed card on top of archives is an agenda, clicking on archives after Attitude Adjustment is live simultaneously selects the agenda on top *and* opens the archives window. If you have already selected an agenda from HQ, it immediately shuffles without an opportunity to select a different agenda from archives.

For example, lets say you play Attitude Adjustment and are in the window to select agendas from archives and HQ. You have a Bellona in hand, and both a License Acquisition and a Global Food Initiative in archives. The License Acquisition is visually displayed at the top of archives to the Corp. After selecting the Bellona in HQ, clicking on archives in an attempt to select and shuffle Global Food Initiative will instead shuffle the Bellona and the License Acquisition immediately, before you have an opportunity to select the Global Food Initiative.

The easy user solution is to always remember to select the shuffled agendas in archives first, but this feels like a very unnatural action. If you did that in the above scenario, archives would open with the License Acquisition selected as a targeted card to be shuffled, requiring you to de-select it before selecting the two intended targets, Bellona and Global Food Initiative. Alternatively, if you did not realize the first agenda was selected, you could just as easily accidentally shuffle the Global Food Initiative and License Acquisition and not have an opportunity to select the Bellona in HQ.

Is it possible to disaggregate the 'agenda selection' action during the Attitude Adjustment card effect and the 'open archives' action? If not, is it possible to create a line command that will open the archives window without requiring you to click on archives?

I encountered this issue using Google Chrome on Windows 10.

**Comment by NoahTheDuke** [comment]
Thanks for the idea! We generally try to open Archives for all relevant cards, so it sounds like this is just missing the flag, but having a specific button like how the hand has that little [+] would be great.

**Comment by cardboardtech** [comment]
There is an existing way to open archives without selecting the top card which is to click the area at the bottom where there is a semi-transparent black box with the next "Archives (x↑ y↓)". You know you want select the card, because the card preview does not appear when you hover over it. That being said, that isn't obvious and maybe even unintentional, so I think adding a + button like with the hand is a great idea.

**Comment by JordanFoley** [comment]
I was unaware of the click trigger below archives, that is very helpful to know! 

One small addition after further poking on this, after clicking archives to open the window and having the top agenda be selected, attempting to de-select that agenda by clicking it again also closes the archives window. Not sure if this activity is related to the flagging issue mentioned above, but felt worth mentioning.

Agree that a little [+] would be both intuitive and helpful, but cardboardtech's suggestion resolves the main functional issue I was facing.

**Comment by cardboardtech** [comment]
I noticed this as well. It seems like any click within the bounds of the archives window will close the window. This is especially strange when using an ability that is properly tagged to open the archives window while resolving. For example, if you use Allele Repression with more than 1 counter, the archives window will close and then immediately reopen after you select each card.
