### ISSUE TITLE
Exchange of information will activate On-steal effect on Sting!

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#5923]
Link to bug replay: https://jinteki.net/bug-report/fd3572fb-0ebf-44bd-899d-b449bc14e57c?b=0

Corp plays exchange of information, trading Sting! for Obokata protocol. Runner gets 1 net damage from the on-steal ability.
Note: Corp was playing Jinteki Personal Evolution, maybe that would activate too if i hadn't died from the sting first? Worth looking at too

**Comment by francescopellegrini** [comment]
Duplicate of #5725?

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Probably fixed by https://github.com/mtgred/netrunner/commit/5267e80a84ee55e7b2f33efa2b84c07d9785b853.
