### ISSUE TITLE
Archives Interface listed on nrdb as costing 3c but jnet image shows 2c

### ISSUE THREAD

**Issue by JordanFoley** [mtgred/netrunner#5929]
This card is listed in NRDB as costing 3c to install:

NRDB listing: https://netrunnerdb.com/en/card/07044

But jnet displays a version that is 2c to install:

![image](https://user-images.githubusercontent.com/24964927/120275000-83950900-c265-11eb-9539-f2477a811b6a.png)

It looks like a discrepancy between the hi-res and lower-res images for the card:

https://www.jinteki.net/img/cards/en/high/stock/07044.jpg
https://www.jinteki.net/img/cards/en/default/stock/07044.png

Because the hi and low-res card image options were fairly recent, I suspect its just an image display issue but I generally haven't played with the card so not sure if there is an issue w/ implementation as well.

**Comment by NoahTheDuke** [comment]
haha I believe the 2 cost was a misprint from way back. We haven't updated the original images in a _long_ time. I'll update it when I get a chance.

**Comment by jwarwick** [comment]
Server is updated with the correct art. Should be picked up on next `lein fetch` and restart.
