### ISSUE TITLE
Stealth breakers don't reset strenght 

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#5935]
Link to bug replay: https://jinteki.net/bug-report/feb570f4-0d37-4aa8-b63a-127ddd97b8ee?b=0
Testing Replay : https://jinteki.net/bug-report/d865dd2a-5167-4591-ab63-277481652fcc?b=0

Description: Afterimage and Penrose's Strenght will not go down at end of encounter

**Comment by francescopellegrini** [comment]
Fixed by #5942 @NoahTheDuke
