### ISSUE TITLE
Sunset swaps only 2 pieces of ice

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#5940]
https://github.com/mtgred/netrunner/blob/592ef51d6645c9f2648bb6d9d6980bf67c0f66f9/src/clj/game/cards/operations.clj#L2333-L2336

The card should "[Arrange the ice protecting that server in any order](https://netrunnerdb.com/en/card/02054)".

**Comment by cardboardtech** [comment]
Sunset is working correctly. The block of code highlighted here is used to swap two pieces of ice, but is called repeatedly after each swap until the player clicks Done.
