### ISSUE TITLE
Hayley Install

### ISSUE THREAD

**Issue by ihmcallister** [mtgred/netrunner#596]
After the first install from Hayley on a turn if you choose no to installing another card with Hayley's ability the interface keeps asking if you want to install another from grip on all subsequent installs. Hayley's ability is a 1 time thing each turn, if you don't use it you have missed your opportunity and you shouldn't be able to trigger the ability on subsequent installs.

**Comment by JHonaker** [comment]
I think this has something to do with the optional flag. The same bug is affecting Laramy Fisk, Comet, and (unverified) the rest of the cards that say "The first time X, you may Y."

**Comment by JoelCFC25** [comment]
Deployed!
