### ISSUE TITLE
Glitch with Political Dealings + Daily Business Show + Near-Earth Hub

### ISSUE THREAD

**Issue by mxmxyz** [mtgred/netrunner#5974]
Bug reproduced multiple times today, it seems solid.

Steps:

(1) while being NEH, install Political Dealings and one or more Daily Business Show.
(2) Draw an agenda at the start of your turn.
(3) Choose to install the agenda in a new remote server for the PD trigger. This draws you a card with NEH.
(4) You now get the Daily Business Show trigger for the draw at step 2. BUT, you are only allowed to discard the card you drew at step 3. If you had multiple DBSs, you are unable to select enough cards to satisfy the trigger.

Note that the game doesn't allow you to order PD and DBS triggers the way you want (which would be the correct behavior, imo): it always puts PD first.

My hunch is that DBS asks you to select one of the cards that you have 'just drawn', which doesn't work well if you have drawn other cards by other means before it resolves.

I would post a replay, but I don't think you can see the problem (which is mostly a UI problem) from the replay anyway.

thx :heart:

**Comment by NoahTheDuke** [comment]
Thanks for the report!
