### ISSUE TITLE
Python script for updating matchup quotes

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#5975]
Hi everyone :). MeatDad begged me to upload this so here we go.

[quotes.zip](https://github.com/mtgred/netrunner/files/6756071/quotes.zip)

From what I remember, you need to run this in the same directory as `quotes-runner.tsv` and `quotes-corp.tsv`, both TSV files exported from the shared Google doc of quotes. My *very old* examples of those files are in the ZIP, you'll need to re-export them.

The generated .edn files then go in /data. 

That *might* work...

**Comment by NBKelly** [comment]
I added this into the wiki
