### ISSUE TITLE
Thunder Art Gallery Unclosable Prompt Bug

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#5976]
The runner ended with a Thunder Art Gallery and Citadel Sanctuary installed. The runner paid into the Citadel Trace and went to 0 credits, and then TAG fired, and the prompt would not clear for the corp.

Replay here: https://www.jinteki.net/replay/ba929aa7-ca9a-4b11-ad4d-64ad5b04b638

**Comment by NoahTheDuke** [comment]
Thanks for the report!
