### ISSUE TITLE
Allow CORS responses to the game-state API using x-jnet-api headers

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#5978]
The game state API can currently be accessed using curl or other similar tools, but (as far as I can tell, I'm very bad at webdev) it's not possible to make requests to the API from within a browser because that violates the same-origin policy AND the server does not respond to CORS requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

As far as I can tell (from running `curl -v -X OPTIONS https://jinteki.net/game/deck`), CORS is not enabled on the server.

I believe the following headers should be present to allow easy usage of the API:

`Access-Control-Allow-Origin: *`
`Access-Control-Allow-Headers: X-JNET-API`
`Access-Control-Allow-Methods: GET`

**Comment by NoahTheDuke** [comment]
This is a great point, thanks so much. I don't know anything about CORS, so I'll ask the other members of the team and see if we can get someone who knows more to help out!
