### ISSUE TITLE
Number of Spectators in Game Lobby

### ISSUE THREAD

**Issue by Rallenkov** [mtgred/netrunner#598]
When a Spectator leaves a game the numer in the Game Lobby does not adjust.

**Comment by mtgred** [comment]
There was indeed an issue with spectators not being removed from games.

There was also another issue. When a spectator leaves a game and watch another one, he was still in the first game. This caused the game board switch between the 2 games at every game action from both games.

This should be fixed now.

**Comment by mtgred** [comment]
It was still not fixed.

But now it should work fine. (Crossing fingers)
