### ISSUE TITLE
Mti prompt missing when no ICE in HQ

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#5988]
Runners can infer when Mti has no ice in hand by the lack of a prompt. Further, if the corp draws into ICE mid-run, there is currently no way to install off the ID trigger (e.g., runner runs facedown Spin Dr while no ICE is in HQ, corp rezzes Spin and draws an ICE). Not 100% sure what the timing structure is there and if Mti should be able to install freshly drawn ICE on an unICEd server in that situation. Either way, a dummy prompt along the lines of Jinja would be great.

**Comment by NoahTheDuke** [comment]
Thanks for the idea!
