### ISSUE TITLE
Card moving zone during Accelerated Diagnostics caused the game to hardlock

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5991]
It during playing the revealed operations the cards in RnD change, the game attempts to still cast the operation, fizzling the effect but hard locking the game.

Expected behavior: The cards shouldn't be able to be played once they move off the top of RnD.

What currently happens: The game lags, pays the credit cost, no effect happens, all button inputs stop working.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
