### ISSUE TITLE
Longevity Serum scored vs Tao causes Tao to trigger in between the ability.

### ISSUE THREAD

**Issue by BlueHairedHackerCatgirl** [mtgred/netrunner#5992]
Expected behavior: Longevity fully resolves both parts of its ability (discard from HQ, then shuffle from archives), then Tao gets to swap 2 pieces of ice.

What is actually happening: After the corp discards from HQ, Tao, gets prompted to swap ice before the corp can shuffle from archives.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
