### ISSUE TITLE
Stealth breakers keep strength

### ISSUE THREAD

**Issue by sirloathing1209** [mtgred/netrunner#5993]
Penrose and Afterimage will maintain strength boost from stealth credits for the entire game. This has been true for awhile. I have noticed this when feeding them stealth credits from Mantle, Trickster Taka and Penumbral Toolkit.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Duplicate of #5935, will be fixed by #5942.

**Comment by francescopellegrini** [comment]
Fixed by #5942
