### ISSUE TITLE
Labor Rights prompt minimises on select and makes it impossible to select the correct cards

### ISSUE THREAD

**Issue by mikeprosser** [mtgred/netrunner#6001]
When you play labor rights and select the first card it minimises the archives window, if you click archives to open it back up it selects the top card from archives as one of your targets, you then can't de-select that because doing so closes the prompt again

**Comment by anarchomushroom** [comment]
This also happens with Spin Doctor as well, fwiw

**Comment by francescopellegrini** [comment]
And Steve Cambridge as well

**Comment by SubTric** [comment]
Preemptive action also causes this behaviour
