### ISSUE TITLE
Layout Error for Play UI

### ISSUE THREAD

**Issue by darmac** [mtgred/netrunner#6008]
Hi, Sirs, I found there always a layout error since I use some latest version.
Is that my setting mistake or some thing like bug?
![image](https://user-images.githubusercontent.com/29532367/127586895-268f0ff4-48b9-4118-b1c8-fd77fe01feb7.png)

**Comment by darmac** [comment]
Any body can help to resolve this issue?

**Comment by cardboardtech** [comment]
Are you still getting this layout problem? What web browser and language settings are you using?

**Comment by darmac** [comment]
I tried both Edge & Chrome browser, and English/Chinese language, it's all the same issue.
I used the follow step to enalbe the server:
```
# lein compile
# lein cljsbuild once
# lein run prod
```

**Comment by cardboardtech** [comment]
Maybe your CSS hasn't been generated. 

Try running this:
`stylus src/css -o resources/public/css/`

**Comment by darmac** [comment]
Got, Thanks for your help, the layout is OK now.
