### ISSUE TITLE
Spin Doctor Bug

### ISSUE THREAD

**Issue by maninthem00n** [mtgred/netrunner#6009]
Once you select the first cards to shuffle back in the archives window closes. If you click on archives to open it back up again it shuffles the top card of archives. If you click specifically on the bottom half of archives it opens back up archives without selecting the top card to be returned with spin.

**Comment by francescopellegrini** [comment]
See #6001 and #6003. Will be fixed by #6007

**Comment by maninthem00n** [comment]
Thx ❤
