### ISSUE TITLE
Drawing during DBS resolution semi-locks the UI

### ISSUE THREAD

**Issue by otisfarnsworth** [mtgred/netrunner#6019]
Scenario: My corp ID was NEH. I had two Daily Business Shows and a Political Operative installed and rezzed. On the start of my turn I drew three cards, one of which was an agenda, the other two assets.

I clicked the pop-up from Pol Op to install the agenda, which in turn triggered my ID and drew another card. Then the resolution of DBS was still pending, requiring me to bottom two of my original three cards, but I could now only select the card I'd just drawn, and no others. So I couldn't even select two cards to close the prompt, never mind the correct ones.

Undoing the turn start and installing the agenda onto an existing server worked around the issue, as I then no longer drew a new card before resolving DBS.

Hope that all made sense because it was hard enough for me to remember the order of everything!

<img width="438" alt="Screenshot 2021-08-17 at 22 08 17" src="https://user-images.githubusercontent.com/61184445/129800964-0321a9d8-626c-46dd-b134-984a881994ea.png">

**Comment by cardboardtech** [comment]
@NoahTheDuke closed by https://github.com/mtgred/netrunner/pull/6055
