### ISSUE TITLE
card missing from heap

### ISSUE THREAD

**Issue by aiannacc** [mtgred/netrunner#6023]
See attached screenshot, from my perspective as the corp. There are 10 cards in the heap, as is reported correctly by the number displayed. But only 9 cards are shown when I click on the heap. I believe the missing card was another Chisel, but I'm not certain. For the runner, all 10 cards were visible.
![heap bug](https://user-images.githubusercontent.com/1271376/130279489-00ce72c2-d059-4043-974f-58cfa8389c65.png)

**Comment by aiannacc** [comment]
Oh... is it just that the 10th card is the visible one where "Heap (10)" is displayed? If so, then ignore this bug report. Still, I'd suggest putting that card in the pop-up too, and maybe hiding the one under the "Heap (10)" while the pop-up is being displayed. Right now the ambiguity is confusing IMO.

**Comment by NBKelly** [comment]
Hi, I know this is way too late but the card on the window is the last card in the heap, so you were indeed missing a card.
Unfortunately, I don't think we have enough information to reproduce this issue (i.e. how the card should have traveled to the heap, etc), so I'm going to close it as stale.
If anything like this happens again though, please create a new issue and I'll do my best to figure it out.
