### ISSUE TITLE
Saisenten resolving all subs after 2 broken

### ISSUE THREAD

**Issue by essexmcintosh** [mtgred/netrunner#6036]
Link to bug replay: https://jinteki.net/bug-report/02b8777e-0c48-41ce-bee4-3e1957a67e5b?b=0

Description:
Saisenten resolving all subs after 2 broken

Saisenten was approached while unrezzed, corp rezzes, we move to the next step, runner breaks with boomerang, corp selects program,  runner indicates to fire, corp fires, Runner takes 3+ net damage. We undid the click and tried again, same order, same result. When the corp selects a type before 2 subs are broken with boomer, only one net damage was done.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Somehow related to #6013 (Saisentan and Boomerang are both involved)?

**Comment by francescopellegrini** [comment]
Might as well close this.
