### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#6052]
Link to bug replay: https://jinteki.net/bug-report/f9320ea7-d11e-4d6e-b60b-91b16c551e9a?b=0

Description:

After purging a Data Raven with Parasite Tokens on it, it's strength went up to 6. At the start of the Runner's turn the strength went down but parasite did not get a virus token visually marked on it

**Comment by Chemscribbler** [comment]
Parasite started displaying 1 virus token once it had lowered the strength below 4 (i.e. 3 tokens)

**Comment by cardboardtech** [comment]
Thanks for the report. This should be fixed by #6048
