### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by Xtreme6115** [mtgred/netrunner#6062]
Link to bug replay: https://jinteki.net/bug-report/dbe3f90b-5886-4cec-a3a4-8bd2f0184970?b=0

Description: I can not draw a card in the beginning of my turn. I tried to click for credit, run etc. but it didn't work

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by Xtreme6115** [comment]
I tried to create a new game, but the bug is still there

**Comment by Xtreme6115** [comment]
The game was against Palana, and the bug didn't occurred when playing against other IDs (The bug occurred for the runner playing against Palana)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
