### ISSUE TITLE
Arella and Standoff

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#6078]
Link to bug replay: https://jinteki.net/bug-report/c85916fc-f6a0-4785-b996-8b0703187e45?b=0

Description:

Should give Corp a chance to choose Arella or Standoff first when it is scored.

**Comment by cardboardtech** [comment]
@NoahTheDuke, I was unable to recreate this issue. 
Both Standoff and Arella have defined `:interactive` keys. Arella's is more defined and checks that the corp has any cards they can install as well as a `:silent` key doing the opposite. I couldn't view the replay, but perhaps the corp did not have any valid cards to install which would make Standoff fire first without prompt.
![image](https://user-images.githubusercontent.com/5953664/140418280-f7d7c05b-b16b-4614-9fee-16e6038b1bf7.png)

**Comment by tvaduva** [comment]
That's exactly the issue, right? It should allow the Standoff to go first, then _still_ have the option to choose Arella in case they drew an installable. If you don't give them a choice, does Arella pop up later if you do draw an installable?

**Comment by cardboardtech** [comment]
Yes, Arella's trigger is still pending. After Standoff finishes, if you drew something from Standoff you could install then Arella _should_ prompt to install. That being said, I hadn't thought of that scenario while testing so I will double check to make sure it works.

**Comment by cardboardtech** [comment]
Just confirmed that the scenario you outlined did not work, Arella failed to fire even though I drew a piece of ice. This is an issue that needs to be fixed. Thanks for the help figuring out the problem scenario.

**Comment by tvaduva** [comment]
Great! Glad we were able to nail it down. Thanks for your effort!

**Comment by NoahTheDuke** [comment]
Excellent detective work, you two!
