### ISSUE TITLE
Feature Suggestion: Make two buttons for a New Game (Runner/Corp)

### ISSUE THREAD

**Issue by Rallenkov** [mtgred/netrunner#609]
I often want to play as a specific Side but and it happens ever so often that I join a Game that was advertised as Runner but the second I join it gets switched around.
A Simple Solution would be to allow the User to select witch side he wants to Play during Game Creation, hence two New Game Buttons one For a new Corp Game and one for a new Runner Game.

**Comment by queueseven** [comment]
I like this suggestion as I know the situation you describe is very annoying.
