### ISSUE TITLE
Boomerang's end of run effect fails to target copies of Boomerang other than the one which was used

### ISSUE THREAD

**Issue by brogueleader** [mtgred/netrunner#6093]
When Boomerang's "shuffle a copy of Boomerang from your heap into your stack" effect resolves when a run ends, it only ever shuffles the copy of Boomerang which was used during that run and generated that lingering effect. This conflicts with card effects that can remove a copy of Boomerang from the heap during a run, such as Reboot: if the used Boomerang is selected as one of the cards to be installed facedown by Reboot, currently no Boomerang will be shuffled back even if there is another copy still in the heap that would be a valid target for the lingering effect.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
