### ISSUE TITLE
Help page should refer to Nisei “Learn to Play” guide

### ISSUE THREAD

**Issue by bignose-debian** [mtgred/netrunner#6100]
The “Help” page contains this content:

> The first step is reading the official rulebook.

with “the official rulebook” a link to the FFG Rulebook PDF document.

Should this be changed, to instead link to the current “Learn to Play” guide at Nisei?

**Comment by bignose-debian** [comment]
I have implemented a change to the Help page, to link to the Nisei “Learn to Play” guide. The branch ‘[issue/6100/learn-to-play](https://git.sr.ht/~bignose/netrunner/tree/issue/6100/learn-to-play)’ in my personal fork repository should merge cleanly to the ‘master’ branch.

**Comment by NBKelly** [comment]
Closed as completed via #6885
