### ISSUE TITLE
Daily Business Show & The Class Act won't let you select a card to move to the bottom

### ISSUE THREAD

**Issue by jonniemarbles** [mtgred/netrunner#6107]
As stated in the title, this bug sometimes occurs when attempting to choose a card with DBS or TCA. 

This bug is intermittent and seems to be resolved by:
Undoing the turn
Leaving and rejoining

It is variable whether it is the active player (the one drawing the cards) or their competitor who needs to leave and rejoin. 

I'm sorry I can't offer more detail at this time, I will try to replicate the behaviour in my next few games and provide things like game state etc.

**Comment by francescopellegrini** [comment]
See also #6107

**Comment by francescopellegrini** [comment]
Fixed by #6265

**Comment by francescopellegrini** [comment]
Might as well close this.
