### ISSUE TITLE
Chat Autofill In Chromium Browsers 

### ISSUE THREAD

**Issue by NiichansGirl** [mtgred/netrunner#6109]
Chromium based browsers offer auto complete suggestions to the chat field. While it is possible some people find these helpful, there doesn't seem to be a way to turn them off and I find the way they obscure the game log annoying.

![image](https://user-images.githubusercontent.com/93306637/139191509-da4aef21-ccd8-490f-87cc-1c485a7c2186.png)

**Comment by NiichansGirl** [comment]
It doesn't seem to be happening any more so I guess I'll kill the thread.

**Comment by NoahTheDuke** [comment]
Ope, yes! Taken care of by #6089.
