### ISSUE TITLE
Password-protected lobbies should *not* use a "password" field

### ISSUE THREAD

**Issue by Dirjel** [mtgred/netrunner#6116]
I don't care if someone reads my j-net lobby password over my shoulder when I create a private lobby, and making it a cleartext field would:
a) let me make 100% sure I have the right password
b) make chrome stop trying to update my j-net password every time I make a private lobby

**Comment by mertenhanisch** [comment]
But what about screen-casting? Could that be a problem?

There is an HTML attribute, though, that stops autocompletion. autocomplete="false"
There could also be a button next to the password, that reveals/hides it on demand. Some browsers implement these buttons natively.

**Comment by Dirjel** [comment]
I don't see a duplicate issue for this?

But if you're streaming and set up a private lobby, then there is a risk of people either:
a) joining the lobby before the intended player
-or-
b) joining the game as a spectator

Either of those could be annoying behaviors, but COULD be worked around by the streamer a number of ways, e.g. moving the box offscreen while setting up the lobby.  This would be a minor inconvenience for specific people in very specific situations, but I feel the "would you like to update your password" is a much more widespread & annoying problem.

I'm not so worried about the inability to see the password while entering it on a lobby for verification purposes, but I *really* don't like the browser suggestion to update my j-net password with my lobby-specific password.  If that HTML tag fixes it, good enough.

I added the "autocomplete:false" flag, and it's still prompting to _fill_ my jnet password, but upon game creation there was 
no browser prompt to _update_ my account password.
![image](https://user-images.githubusercontent.com/42731111/140401420-e9d4e7cb-3530-44b6-930e-1e56e3c75094.png)
