### ISSUE TITLE
Harischandra Ent. ID is not automated on Jnet

### ISSUE THREAD

**Issue by Jamil7564** [mtgred/netrunner#6118]
When the runner takes a tag with this ID (Harischandra Ent., very rare I admit !), the Corp cannot see the runner's grip. 
It would be great if you could fix that. Thanks!

**Comment by NoahTheDuke** [comment]
well, it used to work! haha thanks I'll take a look

**Comment by Jamil7564** [comment]
thanks a lot ! 
Your game is the game, guys :)Cheers

    Le mardi 2 novembre 2021, 02:34:25 UTC+1, Noah ***@***.***> a écrit :  
 
 


well, it used to work! haha thanks I'll take a look

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
