### ISSUE TITLE
Loup on DJ Fenris blanked by Malia

### ISSUE THREAD

**Issue by kalotay** [mtgred/netrunner#6122]
This is an open question whether when Loup hosted on DJ Fenris is blanked by Malia, Loup should trigger if Malia is the first card trashed on access.

The current jnet implementation is such that Loup DOES trigger on Malia trash.

The correct behavior should be confirmed by the rules team.

**Comment by NoahTheDuke** [comment]
Thanks for letting us know! Seems the Nisei rules team is looking into it. I'll close this when I hear which way it goes.

**Comment by NBKelly** [comment]
Current ruling from NSG: loup does trigger. See: https://nullsignal.games/blog/card-text-updates-v1-2-released/

I'll write a unit test for this.
