### ISSUE TITLE
Hidden information is available to spectators through browser inspection

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6124]
Spectators may view hidden information on any face-down installed cards through the inspector on their browser - the card-name field is filled.

I have checked that a player is not able to to view this information, and as far as I can tell:
* A player can't see this information while in game
* Leaving and reconnecting does not allow the player to see this information
* Leaving a joining as a spectator does allow the player to see this information
* Any spectator is capable of seeing this information

Though I don't imagine it's likely, this does provide an avenue for for players to cheat through the use of a third party or sock-puppet account.

Steps to reproduce:
Join any game as a spectator, open up your inspector, and select a face-down card.

![inspect_01](https://user-images.githubusercontent.com/9095245/140008979-26a8f314-dba1-4688-aa16-44ca1754b229.jpg)

![inspect_02](https://user-images.githubusercontent.com/9095245/140008989-90a6b959-a081-4ed1-98b2-27f3908eabad.jpg)

**Comment by NoahTheDuke** [comment]
Excellent work, detective! Thanks so much, we'll get this cleaned up shortly.
