### ISSUE TITLE
C&C Daily Casts doesn't automatically update after import

### ISSUE THREAD

**Issue by postinternetsyndrome** [mtgred/netrunner#6126]
I imported a deck via text paste, and a bunch of the cards where detected as their old rotated variants. I used the "click here to update rotated cards" function and it updated all of them correctly except for Daily Casts, which stayed as the C&C version.

I don't know if this consistently happens with C&C Daily Casts in other contexts, or if it's connected to the text import specifically.

**Comment by NoahTheDuke** [comment]
Looks like this is for [NRDB](https://github.com/NetrunnerDB/netrunnerdb). Maybe open the issue there?

**Comment by postinternetsyndrome** [comment]
You are absolutely right lol. I even came here once, was like "no wait this is jnet", re-googled and managed to end up here again.
