### ISSUE TITLE
London Library + Overmind not counting MUs correctly

### ISSUE THREAD

**Issue by dollopuss** [mtgred/netrunner#613]
When Hosting Overmind on London Library, Overmind is getting counters equal to the MUs before hosting Overmind.  It should be getting counters equal to the MUs after Overmind is installed.  As a result, when bringing Overmind back to one's grip, MU amount goes up one above total MU.

**Comment by nealterrell** [comment]
I'm on it.

**Comment by nealterrell** [comment]
Submitted a fix in #614.
