### ISSUE TITLE
"If you made a Successful Run" effects not checking until after a run is complete.

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [mtgred/netrunner#6133]
![Screenshot_20211107-094211_Discord](https://user-images.githubusercontent.com/39098450/140640074-a99277e2-cb69-4d22-977c-a5850f390fd5.jpg)

As per this screenshot; the runner made a successful run on HQ, then during the access phase installed a Penumbral Toolkit. This card cost them 2c instead of the 0c it should've cost.

**Comment by cardboardtech** [comment]
I was unable to recreate this issue at least in the basic case of stealing an agenda from HQ and using Pantograph to install Penumbral Toolkit. Maybe there was more to the scenario? 

I did write a test for this in PR #6135 so we at least catch if this becomes an issue in the future.
