### ISSUE TITLE
Worlds 2021 bugfix tracking issue

### ISSUE THREAD

**Issue by NoahTheDuke** [mtgred/netrunner#6134]
Please link/tag bugs (not feature requests) you wish to see fixed (or at least attempted to be fixed) in time for Worlds 2021 here.

**Comment by anarchomushroom** [comment]
https://github.com/mtgred/netrunner/issues/6137

**Comment by Dirjel** [comment]
#5790

If the chisel trashes the magnet, that could be pretty nasty to untangle. Just saw someone mention on GLC and the issue was already open. Haven't tested myself.

**Comment by SashaIr** [comment]
#6152

I've been asked on GLC to add this to the queue. Essentially the Ansel + Ganked combo doesn't fire on a The Maker's Eye run, for some reason.

**Comment by francescopellegrini** [comment]
Might as well close this.
