### ISSUE TITLE
Turning Wheel + Border Control ability causes immediate run after not to work

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#6137]
Link to bug replay: https://jinteki.net/bug-report/79a6cb77-36dc-45a4-837e-6511f0792e5d?b=0

Description:

Make a run on RnD
Outermost ice is Border Control, innermost is Masvingo with 4 counters
Corp has 3 bad pub
There is also a Turning Wheel installed
Breaks Border Control with Paperclip
Breaks Masvingo with Paperclip
Runner uses Border Control to end the run (this also doesn't trash Border Control, BC stays around so has to be manually trashed, but the run still ends (:bancat:))
try running RnD again the log says the runner approaches Masvingo, but nothing actually happens (runner still loses a click, counter still goes on Turning Wheel)
If you run RnD again then the run works as normal

**Comment by NoahTheDuke** [comment]
Thanks for the report!
