### ISSUE TITLE
Runner not moving forward after Trypano trashes current ICE

### ISSUE THREAD

**Issue by Joseph7695** [mtgred/netrunner#6143]
1. Trypano trashes inner ICE.
2. BUG: Encountering the outer ICE

Expected: 
2. Breaching server.

jtfq99999 spends  to make a run on Server 2.
jtfq99999 approaches Anansi protecting Server 2 at position 1.
jtfq99999 encounters Anansi protecting Server 2 at position 1.
jtfq99999 pays 3  to use Aumakua to break all 3 subroutines on Anansi.
jtfq99999 has no further action.
jtfq99999 passes Anansi protecting Server 2 at position 1.
jtfq99999 trashes Simulchip to use Simulchip to install a program.
jtfq99999 pays 0  to install Trypano on Kakugo protecting Server 2 at position 0.
jtfq99999 uses Cookbook to place 1 virus counter on Trypano hosted on Kakugo protecting Server 2 at position 0.
jtfq99999 uses Trypano to trash Kakugo protecting Server 2 at position 0.
jtfq99999 will continue the run.
jtfq99999 approaches Anansi protecting Server 2 at position 0.
jtfq99999 encounters Anansi protecting Server 2 at position 0.
jtfq99999 has no further action.
Chillsection uses Anansi to do 3 net damage.
jtfq99999 trashes due to net damage.
jtfq99999 is flatlined.

**Comment by Chillsection** [comment]
*bump

confirming this just happened in our game
