### ISSUE TITLE
Show Spectators not displaying when spectators are in the game

### ISSUE THREAD

**Issue by rongydoge** [mtgred/netrunner#6146]
Title. There's no "Show Spectators" next to the Leave Game button in the upper right to mouse over and see who's spectating the game. 

<3 <3 <3 because I sound terse in this ticket for some reason.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by AndersRask** [comment]
I can second this bug! 
Sometimes it will show spectators at the top, but most times it will not.
In tournaments where you might not want spectators, it is harder to detect them when they do not show up unless when they join or leave the game

**Comment by NBKelly** [comment]
I'm 99% sure we fixed this when noah did the last lobby rewrite, so I'm going to close this as completed. If I'm wrong and it happens again, please create a new issue.
