### ISSUE TITLE
Returned to a game lobby after game ended

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#6151]
This is a weird one:
every time i finish a game and leave the game, i enter a game lobby for a game in stead of going to casual lobby.
In this game (to the right of the screen) i cannot join the game.
The only way to get back to game lobby is F5

It happens only when I play a game, not when i spectate

**Comment by AndersRask** [comment]
Example : i played a game, i leave and now i am here:
![image](https://user-images.githubusercontent.com/1651150/142285260-791610e8-65a3-4ad7-aa89-c551c7e7e05b.png)

**Comment by NoahTheDuke** [comment]
What happens when you refresh?

**Comment by AndersRask** [comment]
If i F5 the casual lobby returns to normal (nothing in right side).
It seems to be related to some script that runs at intervals, because i had the lobby on full screen for maybe an hour, and suddenly a game showed up in the right exactly as on the pic above.

**Comment by AndersRask** [comment]
It also looks like a game lobby starts during my game: i hear the "ding dong" sound of someone joining a lobby

**Comment by AndersRask** [comment]
It is EVERY time i log into jnet I have this issue @NoahTheDuke  so if u want we can schedule a session with a dev and I can show it

**Comment by NoahTheDuke** [comment]
That won't be necessary, thanks for the answers.

**Comment by AndersRask** [comment]
@NoahTheDuke this is still an issue, and very annoying. It can cause me to not be able to join games, because it "remembers" that i joined another game.
For example i spectated a game, left it and then in the right part of lobby i could ONLY see "leave" option for the game I had already just left!!! On the left, if I joined another game, the join sound would play, but I would still only see the "leave" option for the old game. I could not get this to go away: an F5 would bring it back, and "reload list" would bring it back. I basically had **to WAIT for that game to end and be completely dropped, before I could join an new game!!!**
Would really appreciate this gets fixed :)

**Comment by NoahTheDuke** [comment]
It will get fixed when it gets fixed. Yelling about it won't get it fixed any faster.

**Comment by AndersRask** [comment]
hey, did not mean to be pushy, just added some further detail if you needed more context to repro :)

**Comment by NBKelly** [comment]
I think this issue is no longer relevant (as far as I can tell we solved this case ages ago, but I can't pick out any specific PR), so I'm going to close it as stale. If anything like this happens again, please make a new issue.
