### ISSUE TITLE
Wake Up Call trashes hand even when runner use Citadel Sanctuary

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#6153]
I trashed Citadel Sanctuary to avoid damage from Wake Up Call, but still the hand was trashed (one card).

I also had Buffer Driver installed, if that matters

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
@AndersRask Citadel Sanctuary ability's cost **is** to trash all cards in your grip..
