### ISSUE TITLE
Aeneas Informant trigger does not fire when a card is removed from game using Salsette Slums

### ISSUE THREAD

**Issue by AlexBoyd** [mtgred/netrunner#6161]
There's a ruling that if a card is removed from game with Salsette Slums that should trigger the condition of Aeneas informant that the runner may gain 1 credit for accessing a card and not trashing it. 

Currently this doesn't fire on jnet though. Other triggers like Aumakua and Maw, and use similar wording do fire, so there is likely something specific in the implementation of Aeneas Informant that doesn't handle this case fully.  

![image](https://user-images.githubusercontent.com/841094/143495105-038299cb-a766-4744-ba89-46f7508681c0.png)

![image](https://user-images.githubusercontent.com/841094/143495127-df5443fe-19bd-4de2-b871-9061be72d9ea.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
