### ISSUE TITLE
Hippo Is able to work Multiple times in 1 turn

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#6170]
"The first time each turn you fully break the outermost piece of ice protecting the attacked server during a run, you may remove this hardware from the game to trash that ice."

Currently the runner can install and use two hippos on the same turn. This has never been allowed, and despite the awkward wording, it still can only trigger once per turn

**Comment by NoahTheDuke** [comment]
Thanks for the report!
