### ISSUE TITLE
Dhgdeer stops having abilities 1 turn after it's installed

### ISSUE THREAD

**Issue by Chemscribbler** [mtgred/netrunner#6171]
Link to bug replay: https://jinteki.net/bug-report/d787ac29-b6fa-4380-95c6-f2fcd0c5735d?b=0

Description:

After installing Dhgdeer it was able to used once, but was greyed out for the rest of the game

**Comment by Chemscribbler** [comment]
Not turn based in retrospect, instead it was 1 host per installed instance of Dhgdeer.

Re-installing it fixed the issue

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
Closed as completed via #7491
