### ISSUE TITLE
Subroutines on Kamali 1.0 do not all fire when attempting to "Fire Unbroken Subroutines"

### ISSUE THREAD

**Issue by verumvenari** [mtgred/netrunner#6175]
Often, when the runner encounters Kamali 1.0, does not break any subroutines, and indicates to fire all unbroken, and the corp then clicks "Fire Unbroken Subroutines," only the first subroutine will fire (Runner takes 1 brain damage or trashes an installed program). They are presented with the choice in the subroutine, but after that no more choices from the other subroutines appear.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
