### ISSUE TITLE
Hellion Beta Test activating any time the runner trashes a corp card, rather than only when they trash an accessed card

### ISSUE THREAD

**Issue by verumvenari** [mtgred/netrunner#6177]
The text on Hellion Beta Test allows it to be used only when the runner has trashed an accessed corp card in the previous turn. Currently, the corp is allowed to play Hellion Beta Test even if the trashed card was not accessed. Specifically, the trash effects from both Hippo and Stargate allow the corp to use Hellion Beta Test on the following turn, even if the runner trashed no accessed cards.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
Cards been accessed and cards been trashed are separate events, so from my understanding there is currently no way of telling when the Runner is allowed to play Hellion Beta Test because they might have trashed one card and accessed a different one.

**Comment by NoahTheDuke** [comment]
The `:X-trash` event knows whether the card was being accessed when trashed, so if you look through the last turn's `:runner-trash` events and see any that are being accessed, then you could implement this card better. Looks like we're only checking if a card was trashed at all last turn, not an accessed card.
