### ISSUE TITLE
Tori Hanzō does not prevent Potential Unleashed from trashing from the stack

### ISSUE THREAD

**Issue by distributive** [mtgred/netrunner#6179]
First of all having read previous issues regarding Tori I'd like to apologise for finding another.

The incident was caused by a Kakugo protecting a Tori in PU dealing 1 net damage. The corp chose to convert this into a brain damage, however PU still saw the net damage dealt and trashed the top card of the stack. We tested it again with Sting!, Hokasai, and an AP subroutine (specifically on Saisentan) and it seems to be an ordering bug, where the stack is milled before the corp has the option to prevent the net damage.

This interaction isn't completely unreasonable to expect, as it occured during a Random Access Memories game and the bug almost went unnoticed (which would have cost the runner the game otherwise).

**Comment by NoahTheDuke** [comment]
Thanks for the report!
