### ISSUE TITLE
Bailiff doesn't trigger with (Rebirth-ed) Queztal's new wording

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#6190]
Link to bug replay: https://jinteki.net/bug-report/bfb55719-ada4-4890-a5f0-ac05be12a6aa?b=0

Bailiff doesn't trigger with (Rebirth-ed) Queztal's new wording. See linked replay. I used Rebirth to be Queztal and when I broke Bailiff the Corp didn't gain a credit. Not sure if it's new wording of Queztal has updated to work with Bailiff or if it's because I Rebirth-ed into the ID.

**Comment by francescopellegrini** [comment]
The gain-credit trigger on Bailiff [is not yet implemented](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/ice.clj#L596).

**Comment by NoahTheDuke** [comment]
I don't know why it isn't, we have the technology for tracking breaking subs. Hopefully someone can get around to it at some point.

**Comment by tvaduva** [comment]
Ah, that makes sense! I didn't even think to check if it was implemented in the game. Just expecting that it was, as Noah noted, since so many of the breaking subs logic works so well. No big deal; I thought I caught an edge case that was missed. Thanks for all your effort to get so many of these cards working correctly.
