### ISSUE TITLE
[wiki] How do I insert cards on a local server?

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6202]
This one's not quite a proper issue, but more information I couldn't figure out or find in the wiki.

Suppose I wanted to try implementing a card (like Deep Dive), or even implementing something like classic ONR cards - I would need to fetch the other cards (lein fetch) and then insert a new entry into the database of cards before I can begin writing a definition for that card.

How would I go about doing that, and could an entry be added to the wiki detailing the process?

**Comment by NoahTheDuke** [comment]
A wiki entry is totally doable. I'm on vacation so I'll be brief: clone the noahtheduke/netrunner-data repo, then edit/add cards in the cards/ directory, then edit/add an entry into a set-cards/ file (which holds the printing information like illustrator and position within a set), then if it's a new set, add the set information to sets.edn (and likewise add a cycle entry in cycles.edn if there's a new cycle too). Then run clj -M:combine I think (look in deps.edn for the right alias), which will create a raw_data.edn file.

Then in the jnet repo, run lein fetch --local ../path/to/netrunner-data and it'll pull in your new card information.

There's other details such as adding new subtypes but I trust you to figure all that out. I wrote no comments but except for the mwl stuff I think it's overall fairly readable lol.

Good luck!

**Comment by NoahTheDuke** [comment]
I forgot to add: think of the repo as a sql database: everything references each other by :id, so look for the :X-id references.

**Comment by NBKelly** [comment]
Neat, was able to get it to work - thanks!

**Comment by NBKelly** [comment]
Closed as completed via https://github.com/mtgred/netrunner/wiki/Local-Development-with-Custom-Cards
