### ISSUE TITLE
Loki's subroutines getting broken by the click ability on a copied bioroid

### ISSUE THREAD

**Issue by verumvenari** [mtgred/netrunner#6204]
Loki was installed on R&D. The runner encountered Loki, and the corp chose Ansel 1.0 on a remote server as the copy target. The runner then used the click-to-break ability on Ansel 1.0 to break subroutines on Loki (log specifically said the runner used the ability on Ansel to break the subroutines on Loki, not that the click-to-break ability was copied). When then selecting "fire all," the subs were considered broken. This is a bug because Loki copies subroutines and subtypes, but no abilities.

**Comment by NBKelly** [comment]
Hi, thanks for the bug report!

This isn't actually a bug on Loki, but how the bioroid-break functions are implemented. You'll find in game that you can use the break abilities on any bioroid (or f2p, negotiator) regardless of which ice you're encountering - when that obviously isn't correct.

I'll be pushing a fix for this soon.

**Comment by verumvenari** [comment]
Very cool, thanks! Appreciate all your excellent work.
