### ISSUE TITLE
Run Amok prevented by Ansel 1.0

### ISSUE THREAD

**Issue by verumvenari** [mtgred/netrunner#6205]
If the runner makes a run using the Run Amok event during which Ansel 1.0 was rezzed, and allows the final subroutine on Ansel to fire, the runner will be prevented from trashing Ansel with Run Amok's effect. The final subroutine on Ansel prevents the runner from trashing or stealing "for the remainder of this run," where Run Amok happens "when this run ends."

**Comment by francescopellegrini** [comment]
Allegedly fixed by #7415
