### ISSUE TITLE
No prompt to use Mumba Temple credits with Divert Power

### ISSUE THREAD

**Issue by picatpicat** [mtgred/netrunner#6213]
I had two copies of Mumba Temple rezzed and an unrezzed Fairchild. I used Divert Power to derez Spin Doctor and Gatekeeper and rez Fairchild. Since Fairchild costs 9 total, Divert Power would only lower its cost by 6, leaving 3 credits. I wanted to use Mumba Temple credits to avoid using credits from my pool, but there was no prompt for me to use them. I'm using Microsoft Edge on Windows.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
