### ISSUE TITLE
Show the game duration time

### ISSUE THREAD

**Issue by sebastian-zarzycki** [mtgred/netrunner#6215]
In the upper left corner, we have the game start time and while this is important information and the game duration can be naturally derived from it, it would be helpful, if that information was shown next to it, as well. 

An extension to that: show the game duration when it's ended, in log, together with how many rounds it took.

**Comment by sebastian-zarzycki** [comment]
Awesome, thank you!

**Comment by NBKelly** [comment]
Completed via #6864
