### ISSUE TITLE
Hansei Review gives the Corp credits before the card has been discarded

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#6217]
https://github.com/mtgred/netrunner/blob/b96d87b28dddce154814d7446162ab6809bcbc6d/src/clj/game/cards/operations.clj#L947-L948

The `gain-credits` effect should probably be moved to L943.

**Comment by Saintis** [comment]
Hansei Review should give credits before the corp trashes a card, and trigger related effects such as Zwicky. The full stop in the text makes it a separate checkpoint. 

As the card works currently, Zwicky can draw first _after_ a card has been trashed. As I read the netrunner rules, Zwicky should be able to draw a card on the first sentence, then trash a card from hand (including the newly drawn card).
