### ISSUE TITLE
Deck from NRDB import broken

### ISSUE THREAD

**Issue by 11-41-41** [mtgred/netrunner#6233]
NRDB's URLs changed with the new update which broke the import function.

old format
> https://netrunnerdb.com/en/decklist/67949

new format
> https://netrunnerdb.com/en/decklist/f897a951-fa78-49fc-ba0f-77f26c942e01

both reference the same deck, a user only sees the new one though, so they can't enter the old one into the import field.

**Comment by francescopellegrini** [comment]
Fixed by #6429?
