### ISSUE TITLE
Red Team lets you run on a central you've already run, and if successful, you gain 3 but it doesn't take it from Red Team

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#6235]
Link to bug replay: https://jinteki.net/bug-report/8b9d0300-e67b-444f-b13d-72b29f8d41b6?b=0

Description:

Runner installed Red Team
Ran RnD with Red Team, took 3 off Red Team
Ran RnD again with Red Team, gained 3 from the bank

**Comment by tolaasin** [comment]
can we just leave it like this? Fixes runner economy problems right there.
