### ISSUE TITLE
Aeneas Informant does not correctly trigger when a card is removed from the game with Salsette Slums

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#6241]
Runner has Maw, Salsette Slums, and Aeneas Informant installed
Runner runs a remote and rfg's an asset using Slums. Maw triggers correctly. Should Aeneas fire as well here, because the card was accessed and not trashed? At the moment, it does not fire on jnet.
According to the old UFAQ, it should fire, unless the new rules on trash have changed this.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
I though #6201 had it fixed.. :(

**Comment by NoahTheDuke** [comment]
Oh hmmm. I don't know if that's been deployed yet. I'm really really behind on deploying

**Comment by francescopellegrini** [comment]
The first deploy of the year would be really appreciated! :)

**Comment by francescopellegrini** [comment]
Should be fixed now that #6201 has been released.

**Comment by NBKelly** [comment]
Completed via #6201
