### ISSUE TITLE
Winchester retains extra sub when Tao'd off of HQ

### ISSUE THREAD

**Issue by jhoscar1** [mtgred/netrunner#6247]
My opponent was Tao and moved my Winchester to a remote server and we still saw the ETR subroutine when encountering the ICE. It also came up in the interactive modals I (the corp) saw when trying to help resolve the issue during the game.

Not sure if this is specific to Tao or if other ways of moving ICE would have this same outcome.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
I can't seem to recreate this. Any more details?
