### ISSUE TITLE
When undoing a card play, it should be put back into your hand

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6251]
Whenever you use undo-click to undo a card play (such as Overclock), I think it should be put back into your hand by default (without having to manually drag it back to your hand).

**Comment by francescopellegrini** [comment]
Duplicate of #5362

**Comment by francescopellegrini** [comment]
Might as well close this.

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed already.
