### ISSUE TITLE
Ad Blitz does not allow choosing of a number greater than 0 for X.

### ISSUE THREAD

**Issue by Veronica-212** [mtgred/netrunner#6252]
Saw this posted on Reddit, went back and double-checked this myself:
https://www.reddit.com/r/Netrunner/comments/ssvb18/so_as_far_as_i_understand_what_ad_blitz_does/ 
![image](https://user-images.githubusercontent.com/55791889/154004124-cfaa6021-e6d4-44a0-a5e6-fa6cbca64906.png)

Reproduction path: 

- Load a deck with advertisments and Ad Blitz ([I used this one](https://netrunnerdb.com/en/decklist/879b1fca-30af-441d-a1fd-786a498a3577/like-share-and-subscribe-)), start a game as corp with that deck.
- Draw cards until you have at least one Ad Blitz and some number of advertisments.
- Trash a few advertisments manually.
- Ensure the Corp has credits (this should by default be 5).
- Play Ad Blitz, try to select a number greater than 0.

Expected behavior: should be able to choose any number, or at least up to the number of credits the corp has.

_Browser: Chrome. Operating System: Windows. I cannot speak for the broswer or operating system of this reddit user._

**Comment by Veronica-212** [comment]
Oh, here's the card on NetrunnerDB, should probably add that: https://netrunnerdb.com/en/card/09020

**Comment by onifizirib** [comment]
I have encountered the same issue with Angel Arena, I only could choose 0 as X when installing the card. ([https://netrunnerdb.com/en/card/06080](https://netrunnerdb.com/en/card/06080))
