### ISSUE TITLE
Ability to print decks in deck builder

### ISSUE THREAD

**Issue by lf94** [mtgred/netrunner#6255]
As the title says, it'd be nice to be able to print decks created in the deck builder. People can then play in real life with their Jinteki decks!

The feature should:

* print the cards using the correct dimensions of real NetRunner cards.
* print as many cards per page as possible.
* have an alternative "micro mode" where just the card information is printed in the most optimal way to reduce paper and ink usage.

**Comment by lf94** [comment]
The feature could additionally have a "print on demand" function which sends it to pre-vetted printers. Maybe said printers can give discounts due to the project being nonprofit and community driven.

**Comment by NoahTheDuke** [comment]
This is significantly outside the scope of jnet and is better suited for netrunnerdb.

**Comment by lf94** [comment]
A lot of users solely use jinteki / netrunner to build their decks... I certainly don't recreate my deck in NetrunnerDB.

**Comment by lf94** [comment]
TIL https://proxynexus.net/ , which means this issue is unnecessary :slightly_smiling_face:
