### ISSUE TITLE
Improve Derez/Rerez Handling

### ISSUE THREAD

**Issue by Bad-Epsilon** [mtgred/netrunner#6256]
Turning this conversation on Discord into an issue:

![image](https://user-images.githubusercontent.com/81654397/154590587-56f3b589-89b6-429e-8c2a-1ec93cc5b29f.png)

The rerez issue is well-explained in the image.

For further context on the Derez suggestion:
Currently Derez is available as a menu item when the corp clicks on a rezzed card. Since derezzing is almost entirely a "manually fix a broken game state" command, it makes sense to only make the derez command available as a slash-command (where the other "fix the game state" commands live). This would reduce accidental derezzes (partially mitigating the rerez issue) and help new players who sometimes are confused about whether the corp can voluntarily derez cards.

**Comment by NoahTheDuke** [comment]
That's a really good idea, tbh. Thanks for the thought!

**Comment by lf94** [comment]
+1 for moving it to a command
