### ISSUE TITLE
[EDITME] Anenome not working in Startup

### ISSUE THREAD

**Issue by jonniemarbles** [mtgred/netrunner#6269]
Link to bug replay: https://jinteki.net/bug-report/e79dc415-662d-475d-bf29-81ee760b20fd?b=0

Description:

[EDITME] Rezzed anenome during a run. No option to trash a card from HQ to fire the one-off 2 net damage, no opportunity to fire the sub. This was a Startup game.

**Comment by NoahTheDuke** [comment]
None of the cards are implemented yet

**Comment by jonniemarbles** [comment]
Apologies for jumping the gun!
