### ISSUE TITLE
Adam installs all Directives

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#628]
Not only one of each. Seems like I was so naive to think nobody would ever want to play *more* than one of each :-)

Should not be hard to fix, will tackle it tomorrow

**Comment by PinkWarrior** [comment]
Great stuff, Id certainly do it if I knew what I was doing but I don't have a clue all I can do is report any bugs I run into.

**Comment by queueseven** [comment]
@PinkWarrior reporting bugs is a great help, since our time is limited, and we certainly can't test every card and every possible interaction. So we depend on users like you that are willing to sacrifice some time to report bugs or make feature suggestions!
