### ISSUE TITLE
Failing tests that can be fixed

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6282]
The following tests currently fail or throw errors when running `lein test`:

- [x]  One of the Vladisibirsk Grid tests has a typo somewhere, or is written wrong (the card itself is functional)
- [x]  There's a pending test for street peddler
- [x]  There's three failing tests for cookbook/grimoire interaction (it seems that it sets the virus counters to zero now, and a prompt doesn't exist where it should)
- [x]  There's 7 failures on parasite (I believe these are all related to grimoire)
- [x]  There's three failures on one of the tests for Azef Protocol (attempting to select itself as the trash target - there's a typo somewhere or the test is written wrong, the actual functionality works as expected)

**Comment by francescopellegrini** [comment]
> The following tests currently fail or throw errors when running `lein test`:
> 
> * [ ]   There's three failing tests for cookbook/grimoire interaction (it seems that it sets the virus counters to zero now, and a prompt doesn't exist where it should)
> * [ ]   There's 7 failures on parasite (I believe these are all related to grimoire)

See #6284

**Comment by francescopellegrini** [comment]
> The following tests currently fail or throw errors when running `lein test`:
> 
> * [x]   One of the Vladisibirsk Grid tests has a typo somewhere, or is written wrong (the card itself is functional)

See #6285

**Comment by francescopellegrini** [comment]
> The following tests currently fail or throw errors when running `lein test`:
> 
> * [ ]   There's three failures on one of the tests for Azef Protocol (attempting to select itself as the trash target - there's a typo somewhere or the test is written wrong, the actual functionality works as expected)

See #6286
