### ISSUE TITLE
Game froze after the game is completed

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6287]
After the victory screen popped-up, I was about to type "gg" to my opponent, but I couldn't send a single message to my opponent. (The chat log seems to froze) I could also see my opponent is typing something, but I've never received their message. Additionally, my scored agenda is "Above the Law" so when it prompts me to trash a resource, I tried to click one, but nothing happened. So after a while, I refreshed the page and apparently, I got kicked out of the game. After that, I checked the Stats page to view the log of my past game. Apparently, I've missed all the messages from my opponent. Makes me kinda feel bad. :(

Screenshot of my froze screen (after I closed the victory screen's stat window):
![chrome_GEoVbMDXLF](https://user-images.githubusercontent.com/96459501/158485813-585b01be-86ae-4cd6-a72e-5d284212277a.png)

Missed messages after the game is over.
![chrome_EF3PLC89s5](https://user-images.githubusercontent.com/96459501/158486632-cbf8d53e-6d95-408a-a817-c1dca362b20a.png)

**Comment by NBKelly** [comment]
I think the conditions surrounding this instance of the black screen issue are no longer possible to reproduce, so I'm closing this issue as stale. If anything like this happens again, please create another issue.
