### ISSUE TITLE
Gamenet not giving you credit when Gold Farmer subroutines fire

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6314]
The Gamenet ID should give the Corp 1 credit every time the Runner pay at least 1 credit from Corp card’s ability. This doesn’t work after Gold Farmer subroutines fire, when the Runner decides to pay 6 credit to get through instead of breaking subroutines. Should end up gaining 2 credit, one per subroutine. 

Not sure if this helps, but the Runner partially pays the cost from Overclock.

**Comment by NBKelly** [comment]
Hi,

As far as I can tell, when a cost is arbitrarily paid, we can see the reason it was paid (gold farmer), and what was paid (3 credits), but we can't see where those 3 credits came from.

I think for the time being, this is one of the cases where you have to manually use the gamenet ability.
