### ISSUE TITLE
Deep Dive + Bacterial Programming bug

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#6324]
as runner, i played deep dive vs saraswati. accessed bact prog, corp resolved, then i spent a click to access a snare, which i trashed. we both saw a button that said "Continue to No current run." couldn't use /close-prompt. game pretty much locked up. not sure what would have happened if i had undone the click as my opponent conceded.

**Comment by francescopellegrini** [comment]
Fixed by #6362?
