### ISSUE TITLE
"You are running on [servername]"

### ISSUE THREAD

**Issue by thebigunit3000** [mtgred/netrunner#6325]
After initiating any run, I'm getting the prompt "You are running on [servername]" with no buttons to continue.  I've had to use /close-prompt to get out of it for every run.

Here is the board state where it happened.  Potential card interactions causing it -- CTM or Overclock?
![image](https://user-images.githubusercontent.com/16762630/161993642-e5708303-2bd6-4abe-8505-cbf1ae37003a.png)

**Comment by thebigunit3000** [comment]
It occurs before encountering ICE, as seen in this screenshot below
![image](https://user-images.githubusercontent.com/16762630/161994038-dd0f366f-c02c-4e20-9425-e42f48d756ef.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
I think the UI been swapped is a hint of something been messed up with sides..

**Comment by francescopellegrini** [comment]
Might as well close this.
