### ISSUE TITLE
Forger

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#633]
Forger does not activate to allow the runner to choose to discard to prevent a tag.

**Comment by JoelCFC25** [comment]
Tag prevention is not live yet on the server. Implemented in #629, so it's coming at the next restart.

**Comment by CptHilts** [comment]
Cool, thanks awesome thanks man!

**Comment by nealterrell** [comment]
This went live today.

**Comment by CptHilts** [comment]
Very cool. Thanks for all the work!
