### ISSUE TITLE
You can start with only 1 player with decklist.

### ISSUE THREAD

**Issue by AndroidNetrunner** [mtgred/netrunner#6332]
Hello jinteki.net!

In Lobby page, you can press 'Start' button when there is only 1 player (with deck). Is there any reason to allow it? If it is bug, I want to try to fix it.

By the way, as you may know from my nickname, I love A:NR, and this website. Thanks for your work!

**Comment by NoahTheDuke** [comment]
So glad you like it! We allow starting alone to let folks practice.
