### ISSUE TITLE
Pelangi lasts until end of run, not end of encounter

### ISSUE THREAD

**Issue by nishadham** [mtgred/netrunner#6339]
Pelangi's card text says it should last until end of encounter, but J.net makes it last until end of run. Issues with multiple encounters per run e.g. Ganked!, Letheia Nisei... 
<img width="431" alt="Screenshot 2022-04-24 at 14 55 19" src="https://user-images.githubusercontent.com/58484015/164979938-448af9e0-e0a0-4cca-9355-d063b40c27fa.png">

**Comment by francescopellegrini** [comment]
Fixed by #6364
