### ISSUE TITLE
Woman in the Red Dress

### ISSUE THREAD

**Issue by CptHilts** [mtgred/netrunner#634]
With what I think is the most recent update. At the start of Runner's turn the choice box is given to the runner not the corp.

**Comment by JHonaker** [comment]
The corp still draws the card though, correct?

**Comment by CptHilts** [comment]
The corp must manually click up to draw a card

**Comment by JHonaker** [comment]
I'll take a look at it.

**Comment by CptHilts** [comment]
cool thanks!

**Comment by JHonaker** [comment]
Fixed it with the latest pull request.
