### ISSUE TITLE
Bug in interaction between Hyoubu Precog Manifold and Light the Fire

### ISSUE THREAD

**Issue by lcrandall** [mtgred/netrunner#6345]
Both Hyoubu and LtF trigger at the same time (when the run is successful) but since it is the runner's turn LtF should fire and trash everything before the Psi Game for Hyoubu can be played to end the run. Currently the Psi Game happens first and if the runner loses, LtF doesn't trash everything.

**Comment by lcrandall** [comment]
I looked into this a bit and it looks like LtF is coded as a breach replacement effect as opposed to the on success effect it should be.  I'm working on getting everything I need to change and test this on my laptop then I'll look into it more.

**Comment by francescopellegrini** [comment]
@NoahTheDuke can be closed as fixed.
