### ISSUE TITLE
Class act leaves a card in the stack when drawing your entire deck (unless it's one card)

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6347]
I only noticed because I've been playing a lot of Obelus.

If you draw cards equal to (or greater than) your deck size, you have to bottom one, then it stays. I think we can probably skip the class act trigger altogether if `cards-drawn >= cards-in-deck` (right now we skip it if there's exactly one card in deck).

**Comment by francescopellegrini** [comment]
I tried to fix the behaviour of Class Act in #6265 but I probably did it wrong..
Feel free to fix it :)

**Comment by NBKelly** [comment]
hmm - so it seems like the eid and context on `draw-cards` has no notion of how many cards it intended to draw (only how many it was able to draw). I wonder if that's the angle of attack we need to find a solution.
