### ISSUE TITLE
[feature request] Player perspective when spectating games.

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6351]
I would like to see a player perspective option on spectated games, like we have in replays.

I think games with public information available should start with all cards unknown to spectators.

* Each player has a dropdown at the top of the screen which they can use to set their information to public/private.
* Each spectator has a dropdown at the top of the screen, allowing them to set their desired perspective (no-open-info, corp, runner, both)
* A spectator can only see the private info if they've opted in to that side (or both), and if that player has set their info to public
* Whenever a player selects a perspective, or a player changes info availability, it's printed in the log
* A player could potentially select only specific spectators to share information with (this would be a more formal 'tournament friendly' option)

I think this could be a reasonable way to enable team tournaments or pair gaming without players needing to rely on third party screen sharing tools, and it could be a useful teaching tool for GLC players.

**Comment by NoahTheDuke** [comment]
Yeah this would be nice
