### ISSUE TITLE
Polyhistor doesn't work as intended.

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#6352]
Polyhistor currently reads "The first time each turn you pass all of the ice protecting HQ, you may draw 1 card to force the Corp to draw 1 card." I just played a game where it didn't activate when passing a 1-ice deep HQ, however it activated when it passed the 1st ice of a 2 ICE deep HQ.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
