### ISSUE TITLE
Blacklist persists after being trashed

### ISSUE THREAD

**Issue by nicemoreoften** [mtgred/netrunner#6353]
I was in a game where Crowdfunding could not be installed from heap after Blacklists were trashed. There was a red error message about it being in a locked zone. The Blacklists were often installed with Friends in High Places. The effect persisted even on turns where a Blacklist was not installed. I attempted to use the /bug command to get a replay but it did nothing.

**Comment by NBKelly** [comment]
Is there any chance blacklist was trashed with Light the Fire?

**Comment by nicemoreoften** [comment]
It was definitely not but Paricia credits may have been involved.
