### ISSUE TITLE
Feature Suggestion: Changelog and/or "What's New?" page/tab

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#637]
I looked around for a few minutes and didn't see a duplicate issue posted, so I apologize if I'm re-suggesting something here.

I'd really love some sort of convenient way to stay up-to-date with changes and updates to the site, as well as possible event announcements. As it is (as far as I know), you have to *happen* to be in the lobby when something is announced, or otherwise be so completely up-to-date on card automation status that you can immediately recognize any changes.

I also missed out on the recent Jinteki.net tournament, which I assume was advertised in the lobby (probably repeatedly, to be fair).

The most obvious way to do this seems like it would be a new tab in the Jinteki.net browser, something like a "HOME" tab that posted any updates in a blog-like format. Ideally you could also have a big warning box off to the side that listed any major known issues with the current patch. Having something like this on a front page would go a very long way towards reducing drama in games when certain features are known to be broken (for example, before Jackson Howard was automated he was briefly preventing you from using him twice in the same turn, and currently, Snare is not charging the Corp any credits to fire). 

An easier temporary solution could be to just set up a mailing list for news and updates. 

As always, I offer suggestions with the disclaimer that I don't know how hard any of this is to code, but am ever-grateful to those who put in those long hours.

**Comment by JoelCFC25** [comment]
We now have the ability to post updates into the News header directly from Trello, so I think this one is largely accomplished. To see the real meat of technical changes, interested users can bookmark [closed Pull Requests](https://github.com/mtgred/netrunner/pulls?q=is%3Apr+is%3Aclosed).
