### ISSUE TITLE
Street peddler should make use of the set-aside zone

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6371]
This one is in CR 9.5.5 - the cards should be set aside during the resolution of street peddler. 

I think that would let us clean up the implementation a lot, fix a few of the remaining issues with it, and fix the pending tests it has.

**Comment by NoahTheDuke** [comment]
I think y'all accomplished this, right?

**Comment by NBKelly** [comment]
I haven't done this one yet - I'll have a go at it next weekend

**Comment by francescopellegrini** [comment]
Closed by #6583
