### ISSUE TITLE
Paying Tollbooth from Overclock doesn't trigger GameNET

### ISSUE THREAD

**Issue by aiannacc** [mtgred/netrunner#6372]
Runner pays Tollbooth's $3 on-encounter toll from Overclock. GameNET should trigger to give the corp $1, but it doesn't.

This looks like the same issue as the closed #6367 (Overclock vs F2P doesn't trigger GameNET).

**Comment by NBKelly** [comment]
Hi,

You'll find out in game that simply having any source of fake credits (overclock, mantle, net mercur) prevents gamenet from triggering for now.

The issue has been fixed here (on github), but it's not live on jinteki.net yet.

**Comment by francescopellegrini** [comment]
Fixed in #6370?
