### ISSUE TITLE
Cold Site Server is not displaying it's "tax" correctly

### ISSUE THREAD

**Issue by Oddball01** [mtgred/netrunner#6379]
From what I can tell Jnet is properly taxing a Runner a click and a cred per power counter on Cold Site Server (https://netrunnerdb.com/en/card/26038), but it is not actually showing it in the chat log which is causing some confusion for Runners.

Thanks!

**Comment by Oddball01** [comment]
![ColdSiteServer](https://user-images.githubusercontent.com/88608704/171965472-2e5de763-ffa8-4890-b294-b5087256c147.png)

**Comment by francescopellegrini** [comment]
There are many cards affected by this issue: Reduced Service, Ruhr Valley, Enhanced Login Protocol, Service Outage.

The only one I could find which logs the additional cost been paid is [Hired Help](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/upgrades.clj#L653-L654).
