### ISSUE TITLE
Cold Site Server not properly taxing Light the Fire

### ISSUE THREAD

**Issue by Oddball01** [mtgred/netrunner#6381]
[Cold Site Server Server](https://netrunnerdb.com/en/card/26038) is not properly applying its tax of a click and credit per power counter to [Light the Fire](https://netrunnerdb.com/en/card/32001) runs.

- Thank you!

----

Info:

"6.3.4 Some abilities look for particular conditions occurring “during a run” or are restricted to being used “during a run.” For purposes of abilities, the run formally begins only after the attacked server is announced and any costs are paid."

Steps of a run (Comprehensive rules section 6.9)

a. The Runner announces the attacked server.

b. The Runner gains 1[c] to spend during the run for each bad publicity the Corp has.

c. The run formally begins. Conditions related to the run beginning or initiating are met.

d. The Initiation Phase is complete.

So LtF still needs to pay the price of using its cost, pay the Cold Site Server fee and then once the initiation phase of the run is complete does it's "During a run" abilities come into play.

**Comment by NBKelly** [comment]
Hi,

This was fixed in #6342, and should hopefully be live on Jinteki.net some time soon.

**Comment by Oddball01** [comment]
Thanks for letting me know! Apologies that I missed that.
