### ISSUE TITLE
Scrollover for cards in play not complete

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [mtgred/netrunner#6383]
When you scroll over cards in play and have the text only feature enabled, the card does not show up complete. When scrolling over in the chat box it is correct.

Example of scrollover of a card in play. (Missing some important statistics, like Ice subtype.)
![unknown-10](https://user-images.githubusercontent.com/39098450/172947346-75722ecf-9b0a-4422-9c35-9fb7624ae586.png)

Example of scrollover of card in chat box. 
![unknown-15](https://user-images.githubusercontent.com/39098450/172947631-2a58bea3-161f-412a-80f0-63b84cff222b.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!
