### ISSUE TITLE
Asa Group lets Corp install assets on centrals...?!

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#6384]
Take a look at what happened [here](https://youtu.be/qN7CnImaFcA?t=3836): Corp uses AAL to install an upgrade and an additional card on R&D. Lately, the latter is revealed to be [another AAL](https://youtu.be/qN7CnImaFcA?t=4044)! 😲

**Comment by NoahTheDuke** [comment]
Thanks for the report!
