### ISSUE TITLE
Private lobby doesn't allow host to rejoin.

### ISSUE THREAD

**Issue by RomanQrr** [mtgred/netrunner#6385]
For various reasons I've sometimes been kicked out of the lobby I made to play with my fiend. Nothing happens when clicking the "Rejoin" button.

I assume the problem is that the site expects to just drop me back into the game, while the server expects a password. The site doesn't expect me to need a password and just waits for the game state instead of showing me the password prompt. I can join as a spectator.

**Comment by jaypumpkin** [comment]
I've experienced a similar issue both as host and not.

**Comment by shdblowers** [comment]
Had the same thing yesterday when not the host.

**Comment by crimsonknave** [comment]
I saw this today. From the lobby I was able to successfully watch the match as that button created a password prompt, but the rejoin button does not.
