### ISSUE TITLE
Jinja Grid gives a prompt that makes it obvious when the Corp has drawn ice

### ISSUE THREAD

**Issue by RotomAppliance** [mtgred/netrunner#6390]
When the Corp has a rezzed Jinja Grid, anytime they draw ice the game gives a "waiting for Corp to make a decision" prompt that the runner can see. Presumably that information shouldn't be given away unless the Corp decides to use Jinja Grid to install the ice.

**Comment by NoahTheDuke** [comment]
Actually, on second thought, Jinja shows the prompt for every draw the Corp gets. Is that what you're seeing?

**Comment by RotomAppliance** [comment]
Just tested it to be sure, and no - the prompt doesn't come up when the Corp draws non-ice. We verified this from the runner side too. 

There have been occasions where the prompt comes up that "you didn't draw any ice, carry on!", but I couldn't recreate it in the test game. I'm not sure under what conditions it comes up.

**Comment by NoahTheDuke** [comment]
Damn, okay. That fake prompt is supposed to show up every time, so we've bungled something lol

**Comment by francescopellegrini** [comment]
Apparently the fake prompt is shown [only during the Runner's turn](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/upgrades.clj#L814) for some reason.. 🤷

**Comment by NoahTheDuke** [comment]
Good find, I looked over the impl when this was opened and didn't even notice that. An easy fix.
