### ISSUE TITLE
Issues with Compile triggers preventing turns proceeding - possibly interaction with Apoc

### ISSUE THREAD

**Issue by 5auc3** [mtgred/netrunner#6393]
I  just had a game where I used Compile to run HQ on an Apoc turn, installing an engolo, and from then on it would not let my opponent start their turn unless they /close-prompt, even though I had no triggers. Then, on a later turn after I installed paperclip  from the bin, every time i finished a run it would give me an option for a paperclip and a compile trigger but they didn't seem to do anything. Unfortunately I don't have a replay to share.

**Comment by 5auc3** [comment]
Ok after a few more games I think i've realised the problem, I didnt notice before but Compile is getting stuck in the play area and not trashing after it's being played. Once you manually drag it to heap the issues go away.

**Comment by NoahTheDuke** [comment]
Thanks for the report and the follow up!

**Comment by ais523** [comment]
I'm seeing the same bug. There are three symptoms:

1. After finishing a run using Compile, the Compile doesn't trash itself – it just stays around in the play area.
2. At the end of the turn on which Compile is played, the next player's turn doesn't start. They can use /close-prompt to get past this and start the game normally.
3. While Compile is in the play area, you get a Compile prompt on every run, regardless of whether it's a Compile run or not.

Symptoms 1 and 3 can be worked around by dragging Compile to the heap manually at the end of the run, and symptom 2 by the Corp doing /close-prompt.

I couldn't get the /bug command to work, but hopefully this description helps to work out what's causing the problem.
