### ISSUE TITLE
Constant Disconnects But Internet is Working Fine

### ISSUE THREAD

**Issue by Crime-Pigeon** [mtgred/netrunner#6396]
Hello! Sorry if this isn't a good bug report, I've not submitted one before. As far as I can tell, this is the most similar issue to what I've had https://github.com/mtgred/netrunner/issues/5467 but I keep getting disconnected from the server for like a second, which if I'm in a game means I'm getting kicked out and having to rejoin. I've tried every thing that I can to fix this issue, like using a different browser, turning off adblock and all my extensions, but the issue persists even on my phone. I've pulled a HAR report that I'm hoping captures several disconnects, I just really wanna fix this so I can play netrunner again ;-;

Also sorry, the only way I can seem to attach this file is as a google drive link because the file size is too big. https://drive.google.com/file/d/1VSzBVIFsbnHcThfSzGjM5FOrV30KKSOQ/view?usp=sharing

**Comment by NBKelly** [comment]
Hi,

Thanks for the report!

Is there any chance you can use a tool (even just ping) to check for packet loss while these disconnects happen? As far as I know, websockets can't cope with packet loss particularly well, and when this used to happen to me that was the culprit. Alternatively, do you know which sections of the HAR report are relevant? My eyes kinda gloss over on a large file like that.

This could be something to do with us, something to do with your setup, or (more likely) something happening on an AS somewhere in transit that's out of all of our hands.

**Comment by Crime-Pigeon** [comment]
![image](https://user-images.githubusercontent.com/91174488/208001568-4fd2ea73-bf8e-4b17-81ff-f56cec332a56.png)

I managed to get a smaller amount of information to look at with regards to the HAR report, it seems that it has to do with a status 101?
