### ISSUE TITLE
Build Fails (IndexOutOfBoundsException: Method code too large)

### ISSUE THREAD

**Issue by PietroCarrara** [mtgred/netrunner#6397]
Steps to reproduce:
- Make a fresh clone of the project
- `lein fetch`

Expected behavior: Code is compiled and fetch is run

Observed behavior: Compilation fails
```
Compiling web.core
Syntax error macroexpanding at (agendas.clj:1:1).
Execution error (IndexOutOfBoundsException) at clojure.asm.MethodWriter/computeMethodInfoSize (MethodWriter.java:2061).
Method code too large!

Full report at:
/tmp/clojure-7174747273417157914.edn
Compilation failed: Subprocess failed (exit code: 1)
```
Running `Arch Linux 5.18.3-arch1-1` from looking at circle-ci, this seems to be an issue since 639ff9265d27263f3b034ac5a6ab8bb317dae6c0.

Since I have 0 clojure experience, I have no idea what this error means or a useful way to fix it, but for now disabling AOT compilation seems to fix it:
[project.clj](../blob/master/project.clj)
```clojure
(defproject netrunner "1.0"
  :description "Browser implementation of Android: Netrunner card game."
  :url "https://github.com/mtgred/netrunner"
  :license {:name "The MIT License (MIT)"
            :url "https://opensource.org/licenses/MIT"}
  :min-lein-version "2.7.1"

  :source-paths ["src/clj" "src/cljs/nr" "src/cljc"]
  :test-paths ["test/clj"]

  ;;    :aot [web.core]
  :jar-name "netrunner.jar"
  :jar-exclusions [#"public/img/cards/*"]
  :uberjar-name "netrunner-standalone.jar"
  :uberjar-exclusions [#"public/img/cards/*"]
  :omit-source true
  :main web.core

  ...
```

**Comment by NoahTheDuke** [comment]
Nice sleuthing! Glad to hear dialing aot fixes it, cuz that's very easy.

**Comment by PietroCarrara** [comment]
Someone with more experience in this project could analyze the implications of disabling AOT. If they are minimal, this might become a valid solution for this problem.

**Comment by NBKelly** [comment]
As a side, once you've run the project once and you have all the partially compiled fragments in your `targets/` folder, you may be able to re-enable AOT and compile it again (not 100% on this though).
