### ISSUE TITLE
Kate / Spark Agency Block Each Other

### ISSUE THREAD

**Issue by TheoClifford** [mtgred/netrunner#640]
If the runner has received a Kate discount in a given turn, they don't then lose credits if Spark Agency rezzes an Advertisement. If Spark rezzes the ad first, Kate's discount then fails to trigger.

**Comment by nealterrell** [comment]
Thanks for the report. It occurs in games with Kate/Reina and any Corp with a "once per turn" ability.

**Comment by nealterrell** [comment]
Fix submitted in #645.
