### ISSUE TITLE
Eater did not trigger Chiyashi's trash top 2 cards of Runner's stack

### ISSUE THREAD

**Issue by ezRAez** [mtgred/netrunner#6404]
When I broke Chiyashi's subs while Eater was installed, it did not trigger the "trash 2 cards from top of stack."

Here's the [log history url](https://jinteki.net/profile/history/075e5fed-0cdf-4e26-848e-15412e36ba45).

**Comment by francescopellegrini** [comment]
The milling part of Chiyashi [is not implemented yet](https://github.com/mtgred/netrunner/blob/master/src/clj/game/cards/ice.clj#L907).

**Comment by NBKelly** [comment]
I feel like we probably could do an automated implementation here. I'll have a look at it over the weekend.
