### ISSUE TITLE
Add a NISEI-only format

### ISSUE THREAD

**Issue by distributive** [mtgred/netrunner#6405]
When Startup rotates with Midnight Sun a lot of players have said they'll continue playing with Ashes in an unofficial NISEI-only format. Given the number of people who have said this it might be good to support them with a NISEI-only option for deckbuilding/matchmaking.

**Comment by distributive** [comment]
Someone pointed out that if jnet starts supporting unofficial formats then it might be useful to give official NISEI formats a prefix for clarity.

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed by #6991?
