### ISSUE TITLE
Joshua B.

### ISSUE THREAD

**Issue by moraesm** [mtgred/netrunner#641]
The card is not adding tags at the end of the turn.

**Comment by JHonaker** [comment]
Just fixed this with PR #652

**Comment by moraesm** [comment]
Not working anymore.

**Comment by queueseven** [comment]
Maybe simply not deployed yet.

**Comment by moraesm** [comment]
It was working couple of weeks ago. The card automation status says also it's done. Stopped to work after some update.

**Comment by JoelCFC25** [comment]
The `:optional` framework was significantly changed in #620, but it broke a few cards and required a couple subsequent patches to iron it out all. Even though the fixes were applied, they don't take effect until the next server restart (which has now happened).

**Comment by JHonaker** [comment]
Yea, this one was because I made a different mistake. I didn't know `:end-turn` was not `:runner-turn-ends`. Fixed and pull requested.

**Comment by JoelCFC25** [comment]
Deployed and working.
