### ISSUE TITLE
Winchester having all the subs even if protecting R&D

### ISSUE THREAD

**Issue by PreNic** [mtgred/netrunner#6412]
Yesterday I was running against a Winchester being installed on R&D and the "End the run" sub was listed when I tried to break the subs. Moreover, the trace of the third sub would start if I did not break it.

**Comment by francescopellegrini** [comment]
Releated to #6247

**Comment by NoahTheDuke** [comment]
I can't recreate this. Any details?

**Comment by francescopellegrini** [comment]
Might have been fixed by #6667

**Comment by francescopellegrini** [comment]
Might as well close this.
