### ISSUE TITLE
Virtuoso doesn't let the runner access upgrades in the root of HQ after a Mark run

### ISSUE THREAD

**Issue by polpiantina** [mtgred/netrunner#6423]
The current implementation doesn't let the runner access upgrades in the root of HQ during the Virtuoso breach after a run on non-HQ marked servers. Maybe it's implemented as "access HQ" rather than full "breach"?

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NBKelly** [comment]
Whoops, I left `:no-root true` in the breach call - I'll add it in to the patch for next week

**Comment by francescopellegrini** [comment]
Closed by #6432
