### ISSUE TITLE
Loki copies Swordsman's static ability

### ISSUE THREAD

**Issue by groenkaaf** [mtgred/netrunner#6424]
Loki cannot be broken using AI when it copies Swordsman's subtypes and subroutines.

**Comment by NoahTheDuke** [comment]
Are you saying it doesn't and it should? Or it does and it shouldn't?

**Comment by groenkaaf** [comment]
Currently, it does. I think I'm correct in saying that it should not.

**Comment by groenkaaf** [comment]
Sorry more potential ambiguity. On jnet right now, if the corp copies swordsman with loki, loki also gains the static ability. It shouldn't gain swordsman's static ability as far as i understand the rules.

**Comment by NoahTheDuke** [comment]
Cool, thanks for the clarification.

**Comment by NoahTheDuke** [comment]
I have a fix ready but haven't pushed it yet, in case another dev thinks about tackling this.
