### ISSUE TITLE
Virtuoso and Sable triggers the mark selection twice.

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#6425]
ChrisFerg started their turn 12 with 12  and 5 cards in their Grip.
ChrisFerg identifies their mark to be R&D.
ChrisFerg identifies their mark to be R&D.

**Comment by francescopellegrini** [comment]
I've also experienced this bug: only the latest mark is valid, of course, so one must keep an eye on the log for multiple messages.
