### ISSUE TITLE
Spectators become players if they spectate then join a game as a player later

### ISSUE THREAD

**Issue by jcmorrow** [mtgred/netrunner#643]
Hi!

 I know you just added spectate mode. I was playing earlier and started by spectating a game (I'll call it game A). I then stopped spectating by clicking "Leave Game". I then joined a game as a runner (I'll call it game B) and after Game B started my view would flash back and forth between Game A and Game B, but in both cases (including Game A, in which I was a spectator earlier) I had full control of the runner. I actually went ahead and made a run just to make sure that was what was happening and the server allowed it. The players in Game A commented to confirm that it had worked.

**Comment by mtgred** [comment]
It should be fixed now.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It should be fixed now.

**Comment by jcmorrow** [comment]
Cheers!
