### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by leekenwen** [mtgred/netrunner#6437]
[www.jinteki.net-1658542249563.log](https://github.com/mtgred/netrunner/files/9172906/www.jinteki.net-1658542249563.log)

I can get into every page except the Play page, which is just a black screen. Chat seems to not work as well and signup+login buttons are  not responsive

**Comment by sunlordy** [comment]
Hiya, I had the same problem and in MY too, I changed my DNS to google's and it works fine now. Not sure if it's the same for you, but you can try.

**Comment by NBKelly** [comment]
I think the conditions surrounding this instance of the black screen issue are no longer possible to reproduce, so I'm closing this issue as stale. If anything like this happens again, please create another issue.
