### ISSUE TITLE
Élivágar Bifurcation Prompt doesnt close

### ISSUE THREAD

**Issue by SimplyTheOnion** [mtgred/netrunner#6443]
The prompt for scoring Bifurcation doesnt close when clicking done. The derez ability is a may so I expected this to be the way to "refuse" the trigger. Clicking "done" multiple times didnt remove the window for me either. It has happened every time I score the agenda. This issue has occured to me while playing sportsmetal which also triggers on score so the issue might be related to multiple triggers on score happening.

There is a workaround by just using the /close-prompt command. Hasnt caused any further issues for me after using it.

To replicate the issue you start the game with sportsmetal and just score the agenda normally (install adv adv).

**Comment by NoahTheDuke** [comment]
Thanks for the report!
