### ISSUE TITLE
Log doesn't show spent credits when using sources other than credit pool

### ISSUE THREAD

**Issue by Amyx9** [mtgred/netrunner#6459]
Whenever a player uses credits from sources other than credit pool, the log doesn't show how much was paid.

It prints:
> \<player\> spends [click] and pays to install Keiko.

It should print:

> \<player\> spends [click] and pays 1 from Paladin Poemu and 2 from their credit pool to install Keiko.

I can confirm it happens on Trickster Taka, Paladin Poemu, Cezve and Overclock, I havent tested Smoke, Net Mercur, Mantle and other less common cards but it looks like a general issue to me.
It happens regardless of whether the credits were spent from a single source or multiple different ones.

**Comment by francescopellegrini** [comment]
I also noticed this strange behavior :(

**Comment by NoahTheDuke** [comment]
This is really weird. Thanks for the report.
