### ISSUE TITLE
Regenisis Don't Trigger if Runner has Taken Damage That Turn

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#6466]
Regenisis triggers so long as no cards have been added to archives on the turn when its scored, but right now if the runner takes damage (for example, bladderwort at start of turn), it does not.  Not sure if this extends to any runner discard/trashes.  To duplicate:

Corp has Agenda in Archives
Corp has Bladderwort on the board and 2 credits.
Corp has Regenisis on the board.
Corp starts turn, does 1 net damage, and gains a credit.  
Corp Advances Regeneisis 3 times.  This should allow you to add the face down archives agenda to score area, but it does not.

**Comment by artemmikhalitsin** [comment]
I'll write a test for this and look into it
