### ISSUE TITLE
Bifurcation 2/1 HB agenda has a bug if there are no rezzed cards

### ISSUE THREAD

**Issue by tanderson11** [mtgred/netrunner#6468]
You have to close the prompt manually after scoring.

**Comment by artemmikhalitsin** [comment]
I tried replicating this but I'm able to see the "Done" button when there are no targets. Could you let me know if this is the behavior you're getting?

![Screenshot from 2022-07-25 12-48-06](https://user-images.githubusercontent.com/19959515/180831720-c6255ccf-1d4d-4927-a558-a9dd9181c947.png)

**Comment by artemmikhalitsin** [comment]
Ah it seems that this was fixed in https://github.com/mtgred/netrunner/issues/6443 and hasn't made it into a release yet
