### ISSUE TITLE
Glacial Lag

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#6479]
Huge amount of lag experienced in games lately, independent of game state.  Lag comes and goes.  Navigation to other tabs works fine, but all in-game navigation is laggy.

**Comment by adamstradomski** [comment]
Is there a way the community can contribute/donate to better hardware/servers to remove lag ?

**Comment by jeremyorion** [comment]
> Is there a way the community can contribute/donate to better hardware/servers to remove lag ?

+1 would subscribe

**Comment by STOpandthink** [comment]
+1 would pay and subscribe

**Comment by NBKelly** [comment]
I'm closing this as stale, please use the more recent issue for further discussion, as that is more relevant to the current state of the game engine: #7584
