### ISSUE TITLE
Cannot trash Public Agendas with Ob Superheavy ability available

### ISSUE THREAD

**Issue by SilentKror** [mtgred/netrunner#6488]
Attempting to trash Oaktown Renovation causes an Internal Error. Fails both through card abilities (ie. Stavka, Extract) and Drag+Drop or /trash. Have done a bit of testing and it seems to happen with all Public Agendas. 

I'm guessing it hangs because it doesn't know what to do with a non-rezzed+non-derezzed card, or the agenda is seen as rezzed but doesn't have a rez cost.

There is no issue if the Ob trigger has already been fired that turn though.

**Comment by NoahTheDuke** [comment]
Thanks for the report and the exploration!

**Comment by artemmikhalitsin** [comment]
seems like ob probably just shouldnt fire on trashed agendas
