### ISSUE TITLE
City Works Project appears facedown for runner in game view

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#6496]
City Works Project appears faceup for the Corp as expected but apparently facedown to the Runner.

However in the log, it says "[Corp] installs City Works Project" so the Runner does have the information.

The card can be exposed with Falsified Credentials, which shouldn't be possible with a face-up card.

![Screenshot (17)](https://user-images.githubusercontent.com/44735253/181934751-f77359b3-33dc-4457-9bde-f688c610c67f.png)
![Screenshot (18)](https://user-images.githubusercontent.com/44735253/181934753-b7606d2b-56d8-4478-9224-bb4701554ef3.png)

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by NoahTheDuke** [comment]
Fixed as of #6536
