### ISSUE TITLE
Kasi String does not add to score area after a Daeg trigger puts 4 counters on it.

### ISSUE THREAD

**Issue by tolaasin** [mtgred/netrunner#6498]
Kasi String on 2 counters, run R&D, Padma adds a counter to go to 3 on Kasi, access Project Atlas off R&D to steal, Daeg adds a counter to Kasi to go to 4 counters, but Kasi did not go to score area. Running a remote to go to 5 effective counters did trigger add to score area.. So maybe the timing on checking Kasi needs a look?

**Comment by NoahTheDuke** [comment]
Thanks for the report!
