### ISSUE TITLE
Ob triggers when trashing during install

### ISSUE THREAD

**Issue by postinternetsyndrome** [mtgred/netrunner#6501]
I installed an agenda over an asset in a remote server, which prompted jnet to confirm that the asset will now be automatically trashed. I accepted and then Ob triggered. This should not happen, since trashes during install are explicitly exempt from the Ob ability.

I don't think this is likely to happen when installing ice or otherwise voluntarily trashing when you don't have to (like when installing an upgrade into a remote, or installing a non-upgrade in a remote with upgrades), since ice trashing in this scenario is typically handled by manually trashing before you install.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
