### ISSUE TITLE
docker-compose build seems to be broken due to nodesource version

### ISSUE THREAD

**Issue by VioletHynes** [mtgred/netrunner#6513]
In particular, this line of the dockerfile:

```
# Install npm+dependencies
RUN curl -sL https://deb.nodesource.com/setup_17.x | bash -
```

Results in these logs during a normal `docker-compose up --build` (running `docker-compose up --build` should reproduce this issue)

```
#8 61.53 ## Confirming "jammy" is supported...
#8 61.53
#8 61.53 + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_17.x/dists/jammy/Release'
#8 62.36
#8 62.36 ## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
#8 62.36
------
executor failed running [/bin/sh -c curl -sL https://deb.nodesource.com/setup_17.x | bash -]: exit code: 1
ERROR: Service 'server' failed to build : Build failed
```

Essentially, this version results in a request to https://deb.nodesource.com/node_17.x/dists/jammy/Release which 404s. Jammy is the distribution the clojure image is based off: https://github.com/Quantisan/docker-clojure/blob/df0494190416457847fad16be62fd620b4d186b6/target/eclipse-temurin-17-jdk-jammy/latest/Dockerfile

I managed to get it to build by changing the line to both
`RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -`
and
`RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -`

So either Node version (16 or 18) should work great. I would have opened a pull request, but I'm not sure which version would be preferred (and the change is small), and I'm not entirely sure how to validate that everything is good afterwards (was only just starting to poke my head into development).

**Comment by NoahTheDuke** [comment]
If you decide you want to get further into jnet dev, holler at me with your email address (either here or email me directly at noah.bogart@hey.com) and I'll add you to our dev slack.

**Comment by VioletHynes** [comment]
Will do! Sorry that I missed the PR. I checked the issues but didn't see anything. I'll close the issue as it's already in hand.
