### ISSUE TITLE
Trying to install a card: prompt hidden

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#6522]
![grafik](https://user-images.githubusercontent.com/3126597/183412101-2048682c-585e-4a8e-b567-fba3d261a062.png)

Workaround:

.gameboard .leftpane .inner-leftpane .right-inner-leftpane .button-pane .panel {
    z-index: 0 !important;
}

**Comment by queueseven** [comment]
I may be wrong but IIRC it was always the case that the basic action box is still displayed when opening a card menu (in this case, choosing the server to install a card).

**Comment by NoahTheDuke** [comment]
I thought I changed it but I guess not. An easy fix tho.

**Comment by queueseven** [comment]
And the commit message in my pull request makes it sound like I knew how CSS works!
