### ISSUE TITLE
Into the Depths only works when approaching server, not after passing ice

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6524]
See the log in screenshot below.

**What it supposed to happen:**
Into the Depths triggers its effect every time I passed a piece of ice. So after I passed an unrezzed ice, it should trigger. And after I passed the last piece of ice, it should trigger the 2nd time.

**What it actually happened:**
Into the Depths only triggered after approaching the server. And it triggered twice all at once.

Replay: (Screenshot taken at turn 10)
https://jinteki.net/replay/0cf135a6-b18f-40f8-960b-b22b1c41f130

![Untitled](https://user-images.githubusercontent.com/96459501/183443512-c4d68114-c255-489f-9e65-9daf5e5d2d16.png)

**Comment by NoahTheDuke** [comment]
Your reading of the cards is incorrect: "Run any server. If successful, for each time you passed ice this run, resolve 1 of the following that you have not yet resolved this run:"

"If successful" applies to the run, meaning it only triggers when the run is declared successful.
