### ISSUE TITLE
Softlock when using Prav's ability

### ISSUE THREAD

**Issue by locks** [mtgred/netrunner#6530]
I'm using [Pravdivost Consulting](https://netrunnerdb.com/en/card/33048).
The runner makes a successful run, and I'm shown the yes/no prompt about using Prav's ability.
I choose yes, but then I don't have any card that can be advanced so I click done. The game softlocks at this point.

**Comment by queueseven** [comment]
related: #6518

**Comment by francescopellegrini** [comment]
#6559 should've fixed this.
