### ISSUE TITLE
Some recent bugs I found

### ISSUE THREAD

**Issue by maninthem00n** [mtgred/netrunner#6537]
- [x] Ob is triggering on over install even thought, this had me believing the ID was significantly better then I thought XD

- [ ] Clyde Van Rite has a strange bug where the ability triggers twice and then it also triggers the start of turn effects for the corp twice? This didn't happen every turn, but it happened more then not. It ended up giving the corp 2 mandatory draws and once firing a urban renewal 2x.

- [x] not exactly a bug, but Jnet UI shows "Brain Damage", I assuming someone is already planning to fix this. 

Thanks for all you "coders of Jnet" do!

**Comment by NoahTheDuke** [comment]
Thanks for the report!

> Ob is triggering on over install even thought

Can you explain in more detail? I don't understand.

**Comment by maninthem00n** [comment]
Yeah sorry I only half finshed that thought 😅 

When you over install a remedy assets, upgrade or ice, I'm getting an Ob prompt. 

When I install an asset in a server with another assets the game prompts me with "the assets already there is being trashed" and then after I click OK I get an Ob trigger. Since Ob specifically says "not during installation" I assume this is a bug? Or just something that got missed.

Since trashing ice before installation is done manually there probably isn't a good fix for that specifically, but overinstalling isn't supposed to trigger ob, and I'm sure this will be confusing for other players. 

Maybe whenever there is a manual trash there could be a pop-up asking if it's because of installation before the ob trigger? 

Sorry for typos on my 3% battery phone.

**Comment by NBKelly** [comment]
Clyde triggering twice fits surprisingly well with his flavor text :joy:.

I know why ob does what it does, I'll try to figure out a good way to fix it some time soon.

**Comment by francescopellegrini** [comment]
Brain vs core damage was fixed by #6806
