### ISSUE TITLE
Jinteki.net Cannot Load (black screen)

### ISSUE THREAD

**Issue by sunlordy** [mtgred/netrunner#6540]
Hi, I'm from Malaysia, and  I can't access to playing on jinteki.net, see screenshot, I think it's not isolated to me either. Can help advise?

![image](https://user-images.githubusercontent.com/111221612/184528735-87614f71-f221-46e3-a2bf-0fe3b5bdc510.png)

**Comment by queueseven** [comment]
It seems like bootstrap and probably other javascript files could not be loaded. They are not hosted on jinteki.net, but on https://code.jquery.com and https://maxcdn.bootstrapcdn.com.

Please check the network tab of your browser and if you can manually access these URLs:

https://code.jquery.com/jquery-2.1.1.min.js
https://code.jquery.com/ui/1.13.0/jquery-ui.min.js
https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js

**Comment by sunlordy** [comment]
<img width="416" alt="URL 1" src="https://user-images.githubusercontent.com/111221612/185132336-67c69b7b-99c2-4305-9361-ec2696190e35.png">
<img width="1087" alt="URL 2" src="https://user-images.githubusercontent.com/111221612/185132382-97db7785-4d1d-4d05-a51a-2eac86c9784c.png">
<img width="1087" alt="URL 2" src="https://user-images.githubusercontent.com/111221612/185132361-2d46987a-fa26-41ae-a4a6-3a457891bc88.png">
This is what happens when I clicked the URL in order. I am unfamiliar with these stuff, so not sure if I am doing this right.


> It seems like bootstrap and probably other javascript files could not be loaded. They are not hosted on jinteki.net, but on https://code.jquery.com and https://maxcdn.bootstrapcdn.com.
> 
> Please check the network tab of your browser and if you can manually access these URLs:
> 
> https://code.jquery.com/jquery-2.1.1.min.js https://code.jquery.com/ui/1.13.0/jquery-ui.min.js https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js

**Comment by queueseven** [comment]
Can you open jinteki.net again and see if it works now? If now, open the network tab and refresh the browser window. Maybe try a hard refresh (shift + F5 IIRC)

**Comment by sunlordy** [comment]
> Can you open jinteki.net again and see if it works now? If now, open the network tab and refresh the browser window. Maybe try a hard refresh (shift + F5 IIRC)
<img width="1130" alt="Hard refresh" src="https://user-images.githubusercontent.com/111221612/185148279-1d9374b2-837e-4cac-ba32-14841d338bd8.png">
Seems like the boostrap still shows error.

**Comment by NoahTheDuke** [comment]
Aside: I wonder if we can move off bootstrap, we don't do nearly enough "normal" design to need it.

**Comment by queueseven** [comment]
I think that's also true for jquery. Using react and jQuery together is an anti-pattern.

**Comment by NoahTheDuke** [comment]
> I think that's also true for jquery. Using react and jQuery together is an anti-pattern.

Welcome to jnet development! :smile:

**Comment by sunlordy** [comment]
I've tried other browsers, still doesn't work, is it just a local ISP issue?

**Comment by sunlordy** [comment]
I changed DNS to google's and it works now.. Silly me.
