### ISSUE TITLE
importing a deck from NRDB results in a busted deck

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#6550]
if i import a deck URL from NRDB, it loads, says it was successful, but leaves me with a deck with no id selected, and the ID drop down is locked as blank - clicking on it does nothing.  

:( :( :(

<img width="447" alt="Screen Shot 2022-08-17 at 9 03 52 PM" src="https://user-images.githubusercontent.com/396562/185276197-83e32a66-8510-42ca-87cd-753aa43c450e.png">

<img width="1421" alt="Screen Shot 2022-08-17 at 9 05 17 PM" src="https://user-images.githubusercontent.com/396562/185276244-3ce851ef-77b7-4db4-9f9b-fdfe14851cc0.png">

Additionally:
* the imported from still lists the old decklist format: imported from https://netrunnerdb.com/en/decklist/71597
* importing with the old numeric IDs format doesn't work any longer either.

On the plus side, i can copy and paste into a new deck....

**Comment by locks** [comment]
Should be fixed once https://github.com/mtgred/netrunner/pull/6505 is deployed!
