### ISSUE TITLE
Runner can't see tags

### ISSUE THREAD

**Issue by xdfubar** [mtgred/netrunner#6553]
During a game the runner became tagged but they couldn't see that they were tagged, but the corp could.
![image](https://user-images.githubusercontent.com/17418819/185724752-1a02cec2-985c-4556-9462-3d6dbe2ef405.png)
![image](https://user-images.githubusercontent.com/17418819/185724757-13f75f33-611e-4e01-9722-c3cc93b4521a.png)

**Comment by Shaedal** [comment]
It looks like the Runner's info box has been switched with the corp's, similar to [issue 6517](https://github.com/mtgred/netrunner/issues/6517).
