### ISSUE TITLE
Runner/Corp stats got switched?

### ISSUE THREAD

**Issue by DDarkray** [mtgred/netrunner#6557]
For some reason, the Runner has bad publicity stat while the Corp has MU/link/tag stats. No idea when or how it became this way.

![Untitled](https://user-images.githubusercontent.com/96459501/186228773-1c27f5db-196d-4e58-83b1-e9d1279de34b.png)

**Comment by DDarkray** [comment]
The credit and click counts are both fine BTW.

**Comment by francescopellegrini** [comment]
Same issue of #6517
