### ISSUE TITLE
Some optional abilities are not implemented correctly... or are they?

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#6563]
I found a series of card abilities which, although technically optional, are implemented as mandatory.

Most of their effects are so good that I can hardly imagine someone opting out, but I'd like another opinion on the subject before embarking on refactoring each and every card which would greatly reduce player quality of play (even if we add autoresolve)

- "virus breakers" (i.e. Musaazi, Yusuf) gaining virus counters on successful runs
- [MirrorMorph: Endless Iteration](https://netrunnerdb.com/en/card/26031)'s ability (!)
- [Personalized Portal](https://netrunnerdb.com/en/card/21056) giving the Corp credits
- [Death and Taxes](https://netrunnerdb.com/en/card/21058) giving the Corp credits
- [TechnoCo](https://netrunnerdb.com/en/card/21060) giving the Corp credits
- [Plague](https://netrunnerdb.com/en/card/21022) gaining virus counters
- [PAD Tap](https://netrunnerdb.com/en/card/21106) giving the Runner credits
- [Steelskin Scarring](https://netrunnerdb.com/en/card/33004) giving the Runner cards when trashed
- [Titan Transnational: Investing In Your Future](https://netrunnerdb.com/en/card/07003) placing agenda counters on scored  agendas
- [Bankroll](https://netrunnerdb.com/en/card/22011) getting credits placed on itself
- [Insight](https://netrunnerdb.com/en/card/22016) letting the Corp sort the top cards of R&D
- [Mind's Eye](https://netrunnerdb.com/en/card/22017) gaining power counters
- [Mâché](https://netrunnerdb.com/en/card/22018) gaining power counters
- [Zamba](https://netrunnerdb.com/en/card/21003) giving the Runner credits
- [Upya](https://netrunnerdb.com/en/card/21007) gaining power counters
- [Veterans Program](https://netrunnerdb.com/en/card/04080) removing bad publicity
- [Deep Thought](https://netrunnerdb.com/en/card/02108) letting the Runner peek the top card of R&D

**Comment by NoahTheDuke** [comment]
Unless we want to change all optionals to be "yes" by default, I am against this. We have to make trade-offs for accuracy, and while I am generally quite the stickler for it, this would be so annoying.

**Comment by francescopellegrini** [comment]
> Unless we want to change all optionals to be "yes" by default, I am against this. We have to make trade-offs for accuracy, and while I am generally quite the stickler for it, this would be so annoying.

I definitely agree with you, it would be super annoying.

Is there a way to set the autoresolve to Always in those cases?

**Comment by NoahTheDuke** [comment]
Not at the moment. If it's added, I think we'd want a user option to set the default for all cards to Yes, No, and Ask. I think it would be too much to allow setting per card defaults across games.
