### ISSUE TITLE
Console swapping not possible when over base MU limit due to MU enforcement

### ISSUE THREAD

**Issue by nicemoreoften** [mtgred/netrunner#6579]
Replicate:
1. Install a console that gives memory.
2. Install 5 MU of programs (on a 4 base MU runner)
3. Attempt to swap the console for another console (legal under NISEI rules)
jinteki.net will stop you from doing this as it will leave you over memory because in most circumstances you cannot install uniques/consoles and let the rules handle the trashing. Instead, you must currently manually trash uniques of the same name and/or consoles before installing another which will temporarily leave you above your MU limit.

**Comment by NoahTheDuke** [comment]
Thanks for the report! Yeah, based on a misunderstanding of the rules (didn't know 1.5 changed the console rule), we currently don't allow installing a second console. Hoping to get that changed soon.

**Comment by Tamijo-Netrunner** [comment]
This now works properly and this can be closed
