### ISSUE TITLE
Envelopment gains second "Trash this ice" Subroutine

### ISSUE THREAD

**Issue by gorka-larrea-montoya** [mtgred/netrunner#6584]
![image](https://user-images.githubusercontent.com/72439125/187949563-28d6c682-a099-456e-888a-d529c5b0adc8.png)
Envelop seems to be gaining a second "Trash this ice" subroutine when it loses its last power counter.

**Comment by NoahTheDuke** [comment]
Thanks for the report!

**Comment by francescopellegrini** [comment]
From my little investigation, the second "trash this ice" subroutine appears when

- there is no power counter left on Envelopment
- the Runner approaches Envelopment

The latter condition lead me to the `reset-all-ice` function, but I kinda got lost there.. :(

Hope this additional details can help
