### ISSUE TITLE
Trashing Lag Time after an agenda is stolen hangs the game.

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#659]
In three separate occasions, I've played as corp and played the current Lag Time. After my opponent steals an agenda, Lag Time stays installed despite the chat reporting it being trashed, and the runner is unable to perform any more actions. I am not certain if the runner had to break through ice before each instance.

**Comment by nealterrell** [comment]
Thanks for the report. I'll have a fix in a little bit.

**Comment by queueseven** [comment]
@yang573 If something like this happens (sounds like an error on the server side), just type something into the chat box. That should 'unlock' the game for the other player, and *maybe* you can continue your game (if not, try trashing the card in question manually with the mouse).

**Comment by yang573** [comment]
@queueseven I've tried both of those things before, and it hasn't worked.

**Comment by JoelCFC25** [comment]
Fixed at #660 and deployed.
