### ISSUE TITLE
Ob should let you search (and fail) when trashing a 0 cost card

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6595]
I think it's basically a 1-liner to fix (I had an "if cost is not 0" there), and I just never considered that use case :joy:

**Comment by francescopellegrini** [comment]
Isn't it allowed to search R&D anyway since you're changing the game state by shuffling the deck?

**Comment by NBKelly** [comment]
Yeah, I just didn't consider it when I first implemented ob :joy:
