### ISSUE TITLE
Dedicated Response Team activates even when unrezzed.

### ISSUE THREAD

**Issue by JoeyKL** [mtgred/netrunner#66]

**Comment by mtgred** [comment]
I can't reproduce the issue. Can you specify what actions were done before the problem appeared?

**Comment by athayn** [comment]
I was able to reproduce the issue. If DRT is installed but not rezzed, and the runner receives a tag from Snare, DRT inflicts meat damage.

**Comment by mtgred** [comment]
I found the cause of the issue. It's fixed and will be deployed tomorrow.

**Comment by anathomical** [comment]
Confirmed as fixed.
