### ISSUE TITLE
When Rime gets moved via Tao, it has 0 strength

### ISSUE THREAD

**Issue by mertenhanisch** [mtgred/netrunner#6620]
Minor bug, that can be easily fixed in game:
After an agenda got stolen, Rime got moved from R&D to Archives. It was then the only ICE on Archives. Rime usually gives itself strength +1, too. But it had 0 strength. It was a bit relevant, since there was an Atman with strength 1 out.
We were able to fix it, via derezzing and rezzing it.

**Comment by francescopellegrini** [comment]
Some friends of mine reported a similar issue with Colossus: once moved by Tao, its strength got back to 4 even if it had some advancement counters on it.
