### ISSUE TITLE
UI turns black randomly

### ISSUE THREAD

**Issue by ignition-ctrl** [mtgred/netrunner#6632]
I recently experienced this in a game, after I played Rashida 3 times, the screen would turn black every other button/prompt click. Only was able to see if I reloaded the page. My console showed an Exception error with some variable 'd'. I should've copied the error, but I reloaded, and the other player left the game and so I didn't get the error again. If it happens again, I'll reply with it here. 
Using Firefox 104.0.2 with a few privacy extensions, but disabled them for Jinteki.net

**Comment by NBKelly** [comment]
I think the conditions surrounding this instance of the black screen issue are no longer possible to reproduce, so I'm closing this issue as stale. If anything like this happens again, please create another issue.
