### ISSUE TITLE
Itinerant Protesters

### ISSUE THREAD

**Issue by alcohollywood** [mtgred/netrunner#664]
If at all possible, it would be great if Itinerant Protesters could automatically reduce max hand size based on bad pub. This way, it doesn't have to be manually set/reset when the current goes away, and runners playing Vigil are able to get their card if the Corp has their new max hand size.

**Comment by JoelCFC25** [comment]
The game plan for this one seems like it would be to add a watch state like with Raymond Flint, Ekomind, Theophilius Bagbiter, etc.

**Comment by JoelCFC25** [comment]
Implemented at #698!
