### ISSUE TITLE
Daily Business Show Triggers on turn start and cannot be bypassed

### ISSUE THREAD

**Issue by dutchoh1** [mtgred/netrunner#6640]
When corp turn initiates the turn after Daily Business show has been rezzed, it triggers the request to choose which card to put at the bottom of R&D immediately after the turn starts.  No cards have been drawn or clicks taken.  No matter what I click or try to undo, it will not go away.

<img width="1129" alt="Screen Shot 2022-09-20 at 10 19 50 PM" src="https://user-images.githubusercontent.com/8203740/191399870-3b2bf4d8-b9de-47d9-b760-352d7bab447a.png">

**Comment by NBKelly** [comment]
Hi, the cards are in the set aside zone (top left of the screen).

Cards are set aside while drawing, which is when effects like DBS or Raman Rai can manipulate them.

I should update the DBS prompt to mention set-aside though.
