### ISSUE TITLE
Request for Reminder for La Costa Grid

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#6642]
There is no reminder to rez La Costa Grid, which triggers at the start of the Corp's turn.  It would be helpful to have a reminder, similar to other start-of-turn triggering assets.

**Comment by francescopellegrini** [comment]
La Costa Grid does have [end-of-runner-turn toast](https://github.com/mtgred/netrunner/blob/a0897c9438403def3523da4c86e927ea03d20683/src/clj/game/cards/upgrades.clj#L868), so it should already work exactly the same as Marilyn Campaign does.
