### ISSUE TITLE
No Indicator that Runner is choosing for Fairchild 3.0 subroutine

### ISSUE THREAD

**Issue by dnddmdb** [mtgred/netrunner#6643]
When the Corp fires Fairchild 3.0 subroutines, there is no indication while the runner is choosing to pay 3 credits or trash an installed card.  It would be helpful to have an indicator that says the Runner is choosing, to avoid the Corp mistakenly firing the subroutines twice.

**Comment by francescopellegrini** [comment]
Closed by #6658
