### ISSUE TITLE
Suggestion - Hosted programs have outline in runner's program row

### ISSUE THREAD

**Issue by GhostMeatz** [mtgred/netrunner#6645]
Suggestion: Programs hosted on Ice have an outline in the Runner program row, maybe a kind of ghosty image or something to remind that MU is being used on Corp's side of the board. I very often install a program only to be surprised by the pop-up that MU is over and I have to trash a program, then look up and see a Botulus or something. Would be a nice feature!

**Comment by NBKelly** [comment]
That does sound like a neat idea.

**Comment by NBKelly** [comment]
Only took me a year and a half :joy:
