### ISSUE TITLE
419 vs. Restore - Doesn't prompt for expose/credit on install

### ISSUE THREAD

**Issue by tvaduva** [mtgred/netrunner#6646]
Link to bug replay: https://jinteki.net/bug-report/bdb5e95f-bead-43f7-b33d-54d2b624d088?b=0

Description:

419 vs. Restore - Doesn't prompt for expose/credit on install

**Comment by NBKelly** [comment]
Hi,

Is the issue 1) that it asks when it shouldn't or 2) that it shouldn't ask but does?

As far as I know, since the install and rez are simultaneous, 419 shouldn't be able to expose the card (but maybe the corp is still allowed to siphon themselves?).

**Comment by tvaduva** [comment]
Haha, I think 1 & 2 are the same thing but re-ordered.

But, you're correct; both parts of instructions happen before the next checkpoint and trigger fizzles are the asset is rezzed. Asked and was given the ruling from a similar card:

https://netrunnerdb.com/en/card/22055

Thanks for your response!
