### ISSUE TITLE
when declining to use a Malapert Datavault after scoring the winning agenda (a project Atlas), a red "internal Server error"  - prompt asked me to use the /bug command in order to help submit this report

### ISSUE THREAD

**Issue by Jinteki-QA** [mtgred/netrunner#6649]
Link to bug replay: https://jinteki.net/bug-report/85865d86-72f0-4664-a6a1-632c7ac97cba?b=0

Description:

Steps to reproduce:
 - be on 6 points
 - have a rezzed Malapert Datavault installed in Server 1
 - score a Project Atlas as the winning agenda (no additional advancements, maybe need a SanSan City Grid in the same server, to 'fast advance' score with only 2 advancements)
 - for the prompt asking whether to use Malapert Datavault,, decline to use it
 - get prompted with a red "internal Server error" - prompt at the top right screen corner

**Comment by NBKelly** [comment]
Thanks for the report.

Fixed by #6647

**Comment by francescopellegrini** [comment]
Might as well close this.
