### ISSUE TITLE
Standard Ban List isn't implemented correctly

### ISSUE THREAD

**Issue by antisocrates** [mtgred/netrunner#6666]
Rezeki is still allowed in standard games, and runner identity 419 is not.

I try to find where allowed/banned cards per format are defined, but i can't find it.

If you can direct me i will submit a pull request.

**Comment by jsfuchs** [comment]
I did some digging around. I think the ban list is available, but this project just needs to be redeployed to pick up the changes.

Ban list (and frankly all of the card data) source: https://github.com/mtgred/netrunner/blob/master/src/clj/tasks/nrdb.clj#L18 comes from an outside source which is up to date.

The ban lists are still referred to as MWL (most wanted list). The latest one is selected based on the date of the banlist: 
https://github.com/mtgred/netrunner/blob/95782884690bf5c71ac17026a8fc5a67df890cb7/src/clj/web/system.clj#L144

I'm guessing this happens on server startup, so a restart/redeploy would fix that. Unfortunately, there doesn't seem to be any docs around how/where this is deployed :/

**Comment by francescopellegrini** [comment]
Fixed quite some time ago. :)
