### ISSUE TITLE
Player notes

### ISSUE THREAD

**Issue by aiannacc** [mtgred/netrunner#6674]
I'd like to be able to make notes about a player during or after a game. Stuff like "new player, appreciates advice" or "friendly, really savvy playing shaper." When I have a bad experience, the Block User feature is sufficient, but it'd be nice to be able to remember when I have a good experience with a particular player.

**Comment by aiannacc** [comment]
Ideal would be if players I've made notes about show up differently in the lobby, or if I could see those notes by mousing over their names. But it'd also be fine if there was just a notes section in the main UI during the game.

**Comment by NoahTheDuke** [comment]
Thanks for the cool  idea but I don't think it's right for jnet.
