### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by oggbonaian** [mtgred/netrunner#6675]
Link to bug replay: https://jinteki.net/bug-report/ee448369-27a9-48dc-940f-c35959b8df6f?b=0

Description:

in the midgame there were situations where selecting targets for longevity serum, spin doctor and sabotage didnt work propperly. also there were some prompts not working propperly although im not sure what of that was due to obanos (my opponent) not correctly clicking through them as he seemed to be somewhat new to the game.

I am not sure how to reproduce these bugs sadly

**Comment by francescopellegrini** [comment]
Might as well close this.
