### ISSUE TITLE
Class Act choice does not work

### ISSUE THREAD

**Issue by ignition-ctrl** [mtgred/netrunner#6677]
Link to bug replay: https://jinteki.net/bug-report/1e93384c-038f-4973-86ef-1fa6d3207492?b=0

Description: Runner cannot move Class Act cards set aside to grip or move cards from grip to bottom to deck with /move-bottom.

Install Class Act, use one click to draw (basic action) start of turn, cannot move cards. 
Note: Not my bug, but runner said they could not move them. Reporting for them

**Comment by francescopellegrini** [comment]
If cards are in the set-aside zone thanks to The Class Act, you just have to select the one to move to the bottom and the rest will move to your grip as normal

**Comment by francescopellegrini** [comment]
Might as well close this.
