### ISSUE TITLE
Resourced blanked by malia should be marked

### ISSUE THREAD

**Issue by kjchiu** [mtgred/netrunner#6678]

**Comment by kjchiu** [comment]
There should probably be a universal effect for blanked textbox that could be re-used with Dr Lovegood

**Comment by francescopellegrini** [comment]
I think the current icon feature (e.g. Boomerang, Femme Fatale, Trieste Model Bioroids) should be improved: currently there can be at most 1 icon per card, so if I use Trieste Model Bioroids on an ice targeted by Boomerang, the icon gets overridden.
