### ISSUE TITLE
Doppelgänger is broken

### ISSUE THREAD

**Issue by Balkmeister** [mtgred/netrunner#668]
Doppelgänger no longer seem to offer a free run after successfully running a server.

**Comment by mn200** [comment]
I am not sure this is working in conjunction with successful Security Testing runs.

**Comment by queueseven** [comment]
Maybe related to #753 ?

**Comment by JoelCFC25** [comment]
Remember that although the fix for Doppelganger has been merged, it is not yet deployed on the live server. I'll check its interaction with Security Testing in dev shortly.

**Comment by JoelCFC25** [comment]
Seems to work as I would expect--Security Testing on Archives with Doppelgänger out, run Archives, get 2 credits instead of accessing when successful, then get prompted to do the free Doppelgänger run. I think we just need to wait for this one to get deployed.

**Comment by mn200** [comment]
Ah OK.  I didn't realise there was a "fixed but not yet deployed" status for issues here.  Thanks for taking the time to check.
