### ISSUE TITLE
Can't create a NEXT Design Deck

### ISSUE THREAD

**Issue by RobRob** [mtgred/netrunner#669]
In the deck creator, when selecting any ID to build the deck with, works as normal. When I select NEXT Design, the ID Field goes blank and cannot be change, no image thumbnail for the ID appears, influence just says 0/

![image](https://cloud.githubusercontent.com/assets/1928146/9683721/8b7d950e-530a-11e5-997f-869c0e5bacf9.png)

**Comment by queueseven** [comment]
Can't reproduce on the live server. Could you do a forced reload (<kbd>CTRL</kbd> + <kbd>F5</kbd>) and try again?

**Comment by JoelCFC25** [comment]
@RobRob is this still happening or was it something just briefly wrong on your end? I have tried repeatedly in the last day and don't see this at all.

**Comment by RobRob** [comment]
I tried forced reload and that didn't appear to help. I've gone through all the IDs, selecting each in turn, and NEXT Design is the only one not working for me. Still getting this problem.

**Comment by RobRob** [comment]
I've just tried it in Internet Explorer and it seems to be working fine, but it's still not working with Chrome.

**Comment by locks** [comment]
I cannot reproduce as well. 

OS X 10.11
Chrome 45.0.2454.85

**Comment by queueseven** [comment]
@RobRob Could you try nuking the cache? Open the dev tools by pressing <kbd>F12</kbd>, then right click the refresh button (while on jinteki.net). A context menu should appear (only when the dev tools are open), then select the last option ('clear cache and full reload' or something like that).
