### ISSUE TITLE
Cloud Breakers cost MU to install, even if you meet Link requirement

### ISSUE THREAD

**Issue by mRIGHTstuff** [mtgred/netrunner#6693]
Jnet will prompt you to trash a program to install any cloud breaker (GS Sherman M3, GS Striker M1, GS Shrike M2) even if you have 2 link. The programs are 0 MU at 2 link, even when not installed, so this seems like an error for installing them on Jnet. Once installed, they cost 0 MU correctly, however you can't install them without trashing a program on Jnet.

**Comment by francescopellegrini** [comment]
See also #6607
