### ISSUE TITLE
Egret installed from hosting on Paule's Cafe did not provide hosted ICE all breakers

### ISSUE THREAD

**Issue by HeWhoWantsJeansAgain** [mtgred/netrunner#6696]
Good evening,

In a match tonight a Runner we encountered what might be an issue. I'll explain the play area:

Corp server structure:
Enigma (outermost)
Rototurret (innermost)
HQ (no Upgrades installed)

Runner actions (Runner had Paule's Cafe already installed)
1) Hosted Egret on Paule's Cafe
2) Hosted Egret on Rototurret
3) Installed Chameleon Icebreaker - declared Code Gate
4) Ran on Server outlined above

When the Runner encountered the Rototurret, they claimed Chameleon gave them no options to break Rototurret - even though Egret should have given Rotorurret Barrier, Code Gate and Sentry types. It may be worth noting that while the Log indicated that Egret was hosted on the Rototurret - the Play Area showed Paule's Cafe as being hosted on the Rototurret.

We couldn't get around it and ended up just firing Subroutines and I opted not to Trash anything.

**Comment by francescopellegrini** [comment]
I cannot reproduce it using the latest version of the code (not yet released)
