### ISSUE TITLE
Crisium Grid blocking R&D accesses when Medium is installed

### ISSUE THREAD

**Issue by JDCaron** [mtgred/netrunner#670]
Have not tried to replicate on other servers, but the temporary solution was to bounce Medium to the grip upon a successful run.

**Comment by nealterrell** [comment]
Could you be more specific about this? What do you mean by "block"? I just tried this with a simple setup: Medium for runner, Crisium on R&D; run R&D, rez Crisium before successful run. On success, Medium gains no tokens, runner accesses 1 card from hand, 1 upgrade in R&D.

**Comment by nealterrell** [comment]
OK, I have a fix. Was this specifically with a Medium that had no counters on it during the run in which Crisium was used?

**Comment by JDCaron** [comment]
Sorry for the delay, yes it was. Medium(s) were empty. Thanks!
