### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by TweeDice** [mtgred/netrunner#6700]
Link to bug replay: https://jinteki.net/bug-report/d35f7171-7367-4d8f-a4ec-357f2697db5e?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by TweeDice** [comment]
Regenesis would not let me select a facedown agenda to score.

**Comment by francescopellegrini** [comment]
See also #6717

**Comment by francescopellegrini** [comment]
Might as well close this.
