### ISSUE TITLE
flame out trashes a program that was simulchipped after flame out trashed it

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#6703]
Link to bug replay: https://jinteki.net/bug-report/85cd0c4f-aa9f-4837-a1cb-3a41cce89ddf?b=0

Description:

i *think* this should dodge the trash, akin to test run + scavenge.

**Comment by francescopellegrini** [comment]
It looks like Flame-out doesn't care: any hosted program is trashed at the end of turn.

> When a turn ends in which you used credits on Flame-out, trash hosted program.

**Comment by bblum** [comment]
oh huh, guess that's intended. thanks
