### ISSUE TITLE
Architects of Tomorrow + Tread Lightly on a 3 rez bioroid

### ISSUE THREAD

**Issue by znsolomon** [mtgred/netrunner#6712]
Playing AoT. Runner plays Tread Lightly, and I use AoT's ability to rez a Ravana 1.0 (3 rez cost). The action costs me 3 credits according to Jinteki.net, whereas it should cost 2 (base cost 3 + TL 3 - AoT 4).
Probably what's happening is the cost reduction is being applied first, reducing 3 to 0, then TL is applying to increase it back to 3.

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed by #7216
