### ISSUE TITLE
Leaving Subliminal in Archives at start of turn shuts off Regenesis ability

### ISSUE THREAD

**Issue by Keredar** [mtgred/netrunner#6719]
Link to bug replay: https://jinteki.net/bug-report/8331b978-0f6a-4ee6-83ae-499ba199cdcc?b=0

Description: When using Regenesis and Subliminal Messaging, if the decision is made to not take the trigger on Subliminal Messaging to return it to the hand, it shuts off the ability for Regenesis to bring back an agenda to score. I believe it registers as having left and entering archives.

**Comment by francescopellegrini** [comment]
Cannot reproduce it (see #6859).
