### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by dormio** [mtgred/netrunner#6726]
Link to bug replay: https://jinteki.net/bug-report/5c24e6f3-a259-4396-a327-183e85fd08fa?b=0

Description:

At the end of the corp's turn, but before I (the runner) click "Start Turn," I pump the strength of Penrose using Mantle to charge The Twinning. Then I click the "Start Turn" and Mantle regains its credit, but Penrose keeps it's strength, and I am able to initiate a run with it at 5 strength.

**Comment by francescopellegrini** [comment]
Fixed by #6773
