### ISSUE TITLE
Palisade moved to remote by Thimblerig swap does not have additional strength following the move

### ISSUE THREAD

**Issue by elimeckler** [mtgred/netrunner#6742]
Link to bug replay: https://jinteki.net/bug-report/d2bbdf4d-5e72-40c7-9a0a-baa2f4b5d1c9?b=0

Description:
Moved rezzed palisade off a central and onto the remote using thimblerig. It only had 2 strength following the move
1. Rez palisade on a central server and thimblerig on the remote
2. Swap them

**Comment by francescopellegrini** [comment]
I believe this was fixed by #6667.

**Comment by damnedGeek** [comment]
Just 30 minutes ago encountered the same problem using Tāo Salonga special ability, moved Palisade from Server 3 to server 2
![photo_2022-12-09_13-46-58](https://user-images.githubusercontent.com/120177876/206685591-d96b02cc-85fc-40c3-836d-36b76e27d39f.jpg)

**Comment by francescopellegrini** [comment]
Might as well close this.
