### ISSUE TITLE
Red Level Clearance shows "Waiting for true" on Runner side

### ISSUE THREAD

**Issue by lostgeek** [mtgred/netrunner#6756]
Link to bug replay: https://jinteki.net/bug-report/0f19f818-9ee6-48d7-a5e4-d61dce438947?b=0

Description:
When the Corp plays Red Level Clearance, the Runner gets a wrong waiting prompt showing "Waiting for true"

**Comment by francescopellegrini** [comment]
Fixed by #6767

**Comment by francescopellegrini** [comment]
Might as well close this.
