### ISSUE TITLE
Info Bounty triggers on the next run after breaching my mark

### ISSUE THREAD

**Issue by pat-gardner** [mtgred/netrunner#6759]
Link to bug replay: https://jinteki.net/bug-report/b7f6a80b-079a-46ac-aa66-a54c92b54509?b=0

Description:

I ran my mark (R&D), then used Inside Job on a remote. After stealing a Bellona and going down to zero credits, Info Bounty triggered again.

**Comment by groenkaaf** [comment]
it seems to trigger every time the breach step is reached. effects like virtuoso cause it to trigger twice in a single run.

**Comment by ben-albon** [comment]
I've observed the same thing

Link to bug replay: https://jinteki.net/bug-report/65b01cd9-bed8-4fcf-ae53-280d1601ee8a?b=0

**Comment by francescopellegrini** [comment]
Should've been fixed by #6810

**Comment by pat-gardner** [comment]
Yep, looks fixed
