### ISSUE TITLE
ESA interaction with thule subsea

### ISSUE THREAD

**Issue by linuxdropout** [mtgred/netrunner#6774]
Link to bug replay: https://jinteki.net/bug-report/9a2bb20f-4b09-40a0-aa3e-8e7399cedac4?b=0

Description:

Esa identity runner accesses archives
They steal an agenda
They take 1 core damage due to thule
This causes 2 cards to be trashed
Does esa then get to access these cards or not?

Not sure if it's a bug or intended, but reporting anyway.

**Comment by NBKelly** [comment]
Yes, esa gets to access these cards under the current CR (but I think they stay face-down)

**Comment by NBKelly** [comment]
Closed as already correctly implemented
