### ISSUE TITLE
World Tree prompt taking over accessing prompt

### ISSUE THREAD

**Issue by AyahN3** [mtgred/netrunner#6777]
Link to bug replay: https://jinteki.net/bug-report/18d42b7e-e614-455c-aab6-78cc6ec00b81?b=1

Description: World Tree code seemed to take over the "access cards in the root" code from pinhole threading AND a simple run. 
The text box was still the right one, but the code behind it wasn't. I checked that by clicking on one of my installed cards and that confirmed what I thought
I'll be honest, the replay speaks for itself.

**Comment by francescopellegrini** [comment]
Should be fixed by #6775
