### ISSUE TITLE
Game immediately ended with a win when Superdeep borehold was rezzed.

### ISSUE THREAD

**Issue by mikesuderman** [mtgred/netrunner#6778]
Link to bug replay: https://jinteki.net/bug-report/2b2e5215-5a86-4192-a54b-69ffbebd8962?b=0

Description:

prior to clicking "Start turn", I rezzed an installed Superdeep borehole. The game ended in an immediate win for me.

**Comment by francescopellegrini** [comment]
Duplicate of #6776
