### ISSUE TITLE
Vientiane gets counters whenever ANY card is rezzed

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#6781]
Link to bug replay: https://jinteki.net/bug-report/2e5bd52a-c7df-4170-828e-e5a7f4b2a83e?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by francescopellegrini** [comment]
Fixed by #6748

**Comment by francescopellegrini** [comment]
Might as well close this.
