### ISSUE TITLE
tremolo can't be used when the cost goes below 0

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#6782]
Link to bug replay: https://jinteki.net/bug-report/e1ac86e0-e9be-437f-bee9-e5126540e15f?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by francescopellegrini** [comment]
Fixed by #6763

**Comment by francescopellegrini** [comment]
Might as well close this.
