### ISSUE TITLE
Character Assassination - choosing between duplicate cards

### ISSUE THREAD

**Issue by meepmeep13** [mtgred/netrunner#679]
In a game the runner had 2 Liberated Accounts installed, one with 4 credits left (installed first) and one with 8 credits left. The Corp scored a Character Assassination, and wanted to trash the Liberated Accounts with the greater money still on it (obviously). However, only one option for Liberated Accounts appeared in the list, and on selecting it the 4 credit one was chosen by the server.

**Comment by JoelCFC25** [comment]
That implementation is so old it probably pre-dates the card targeting system. It will be pretty easy to rewrite it to target a specific card instead of giving the prompt list.

**Comment by JoelCFC25** [comment]
Fix submitted at #682.

**Comment by JoelCFC25** [comment]
Should be live now.
