### ISSUE TITLE
Spectators unable to leave game after both players have left

### ISSUE THREAD

**Issue by meepmeep13** [mtgred/netrunner#680]
If you spectate a game, and both players leave, the option to leave the game disappears from the top menu and you have to close the browser window entirely to return to the lobby,

**Comment by queueseven** [comment]
As a workaround, you could also refresh the page (<kbd>F5</kbd>)

**Comment by meepmeep13** [comment]
Not sure at what point this was corrected, but it now appears to have been resolved.

**Comment by queueseven** [comment]
I fixed it some time ago but didn't link the commit to this issue:

https://github.com/mtgred/netrunner/commit/447c780b79dfe332fc371cb4224232ce39ada782
