### ISSUE TITLE
No Sabotage option for the Corp when cards in HQ < Sabotage (forced sabotage from HQ)

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#6802]
Link to bug replay: https://jinteki.net/bug-report/05601ac3-62bc-4b9a-bfe7-657253b7b2ff?b=0

Description:

**Circumstance**
_sabotage_ occurs, but the Corp has less cards in hand than the amount being sabotaged

**Expected Behaviour**
Corp is prompted to **choose** to discard from HQ **and/or** R&D

**Actual Behaviour**
The Corp is forced to discard all cards from HQ, and any remainder from R&D, without any prompt

**Comment by francescopellegrini** [comment]
Fixed by #6762

**Comment by francescopellegrini** [comment]
Might as well close this.
