### ISSUE TITLE
Hostile Architecture not triggering

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#6803]
Link to bug replay: https://jinteki.net/bug-report/05601ac3-62bc-4b9a-bfe7-657253b7b2ff?b=1

Description:

**Circumstance**
The runner runs a remote server containing _Hostile Architecture_. Hostile Architecture is rezzed during the run. Hostile Architecture is trashed. It is the first installed card to be trashed this turn.

**Expected Behaviour**
The runner takes 2 meat damage.

**Observed Behaviour**
The runner takes no meat damage.

**Comment by NoahTheDuke** [comment]
Thanks for the report!
