### ISSUE TITLE
Hush does not host on ICE at install (and cannot host on ICE at all)

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#6804]
Link to bug replay: https://jinteki.net/bug-report/e5517681-8720-414a-8f0b-abc562d8e59a?b=0

Description:

**Circumstance**
The runner installs Hush. There is a rezzed Anansi on the board.

**Expected behaviour**
The runner is prompted to choose an ICE to install Hush on.

**Observed behaviour**
Hush is installed in the runner play area. No prompt is given.

**Other notes**
The click ability did not appear for Hush, so the ICE could not be manually fixed.

The /host command did not allow the runner to select corp cards.

**Comment by NoahTheDuke** [comment]
As noted by the implementation message, Hush is not implemented.
