### ISSUE TITLE
Hybrid Release trigger cancels Personal Evolution trigger

### ISSUE THREAD

**Issue by ben-albon** [mtgred/netrunner#6805]
Link to bug replay: https://jinteki.net/bug-report/d9750a1a-01d2-4f56-97ef-53fad6bc69e5?b=0

Description:

**Circumstance**
Playing as _Personal Evolution_, I score _Hybrid Release_, and choose to fire Hybrid Release on score trigger before the Personal Evolution on score trigger

**Expected Behaviour**
Both triggers fire

**Observed Behaviour**
The Hybrid Release trigger fires, but the Personal Evolution trigger does not

**Other Notes**
If you choose the Personal Evolution trigger first, then both triggers fire.

**Comment by francescopellegrini** [comment]
Fixed by #6773

**Comment by francescopellegrini** [comment]
Might as well close this.
