### ISSUE TITLE
world tree prompt occurs after run completes, not on success

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#6811]
Link to bug replay: https://jinteki.net/bug-report/d90502f6-83a1-479c-8540-531fa980323d?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by francescopellegrini** [comment]
Fixed by #6775

**Comment by francescopellegrini** [comment]
Might as well close this.
