### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by Keredar** [mtgred/netrunner#6812]
Link to bug replay: https://jinteki.net/bug-report/0279824a-0bd1-4b8c-be72-6ec1ed2ed840?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

Scored an agenda with Issuaq, game immediately counted as ending, got the postgame screen.

Continued playing, scored Hybrid release, a turn after, did not get a counter on the identity when I chose to trigger Hybrid Release first. (possibly due to installing an agenda)

Prompt remaining open at end of turn after scoring Hybrid Release.

**Comment by ben-albon** [comment]
fwiw, here is another replay of the _Issuaq_ issue (not the hybrid release issue)

Link to bug replay: https://jinteki.net/bug-report/faa93e29-aebd-4579-835e-3adf5bc8fa34?b=0
