### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by perenxiao** [mtgred/netrunner#6825]
Link to bug replay: https://jinteki.net/bug-report/507a3eee-5ff9-4b80-8df1-62a3857f8080?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

Hush doesn't allow me to attach to any ice

**Comment by NoahTheDuke** [comment]
As noted in the implementation details and message, Hush is currently completely unimplemented.
