### ISSUE TITLE
Rezzing Superdeep Borehole STILL causes you to instantly win the game

### ISSUE THREAD

**Issue by Lavander42** [mtgred/netrunner#6832]
Link to bug replay: https://jinteki.net/bug-report/4b58fd0b-3dc9-4636-9bff-886e11ed7209?b=0

Description:

I was told that this issue was resolved but upon rezzing it in a new game days later it still instantly wins me the game.

![image](https://user-images.githubusercontent.com/57498276/207915575-d33dbd90-27df-459f-9cbe-c4819cb0c4b3.png)

**Comment by Lavander42** [comment]
#6783 is the ticket I am referring to where this issue was supposedly solved.

**Comment by NoahTheDuke** [comment]
Thanks for following up

**Comment by francescopellegrini** [comment]
Fixed by #6853
