### ISSUE TITLE
Feature Request - Set Mark command

### ISSUE THREAD

**Issue by lcrandall** [mtgred/netrunner#6833]
Was playing a game recently and we had to undo turn on the second click. After doing so and re-starting the turn the mark had changed. We wound up undoing turn until it hit the same mark we originally had but having a way to just fix it with a single command would be nice.

**Comment by francescopellegrini** [comment]
This request looks similar to #6815 to me, a way of having reproducible randomness in a game, given a starting seed.

**Comment by lcrandall** [comment]
Yea in this specific case. There may be some cases where /set-mark could help fix or change something that wasn't caused by non-reproduceable randomness.

**Comment by NoahTheDuke** [comment]
I think both reproducible randomness and having a mark command are good. I'm surprised the mark one doesn't already exist. Can be easily added!
