### ISSUE TITLE
Having Hyperdriver installed makes it hard to end your turn

### ISSUE THREAD

**Issue by Lavander42** [mtgred/netrunner#6840]
Link to bug replay: https://jinteki.net/bug-report/2ee69cc2-b533-4f91-bc3b-7e7848763f67?b=0

Description:

For some reason, when the runner had Supercharger installed, they kept talking about having problems ending their turn and it asking them to "Take Clicks" at the end of their turn.

**Comment by francescopellegrini** [comment]
Do you mean [Supercorridor](https://netrunnerdb.com/en/card/26023)?

**Comment by Lavander42** [comment]
No, I mean [Hyperdriver](https://netrunnerdb.com/en/card/08070) my apologies
