### ISSUE TITLE
susanoo-no-mikoto + DataSucker == weird

### ISSUE THREAD

**Issue by steveklabnik** [mtgred/netrunner#685]
![2015-09-07-194533_189x167_scrot](https://cloud.githubusercontent.com/assets/27786/9724052/268029a4-559f-11e5-8940-1f6671dc2560.png)

So here, I trigger susanoo. Runner is now running on archive. works great. They decide they're gonna complete the run because they were just gonna run on archives next click anyway, and break the Enigma. To break the wall of static, they wanted to use datasucker, so they clicked it, and the sucker token applied to Eli, rather than to the wall of static.

This was of course easy to fix manually by just having them break it anyway, but still some weirdness.

**Comment by JoelCFC25** [comment]
The reason this happens is that when you initiate a run, the details of the ice installed over the targeted server are put in the `[:run :ices]` portion of the game state, but then not replaced when a redirect occurs mid-run (currently possible with Bullfrog, Sneakdoor Beta, Susanoo-No-Mikoto, and Copycat...maybe others). These cards do update `[:run :server]` and `[:run :position]`, but they'll need to associate in the new server's ice too for any cards like Datasucker that use `current-ice` to give correct outcomes.
