### ISSUE TITLE
The runner trashing Yakov doesn't give the corp 2 creds

### ISSUE THREAD

**Issue by anarchomushroom** [mtgred/netrunner#6861]
Link to bug replay: https://jinteki.net/bug-report/6859ab8e-fcc8-4387-956c-d7b88f5c5e95?b=0

Description: 

Runner played Pinhole Threading on RnD
Successful run: runner chooses to access the rezzed Yakov in the remote
Trashing Yakov did not give the corp 2 credits

**Comment by NoahTheDuke** [comment]
Thanks for the report!
