### ISSUE TITLE
Hush doesn't install onto ICE, and can't be moved

### ISSUE THREAD

**Issue by ValiantCid** [mtgred/netrunner#6872]
Link to bug replay: https://jinteki.net/bug-report/ba68b3b0-820b-44e2-8091-a4ac5eae5d7d?b=0

Description:

Hush doesn't target ICE when it's installed, and its ability can't be used when it's installed to host it / move it on to ICE.
Thought this was a bug with Prognostic Q-Loop at first, but it seems like it happens even on install from hand as well.

**Comment by ValiantCid** [comment]
Another instance here =)
Link to bug replay: https://jinteki.net/bug-report/89620795-7381-4809-820d-1b676495ae2d?b=0

**Comment by ValiantCid** [comment]
One thing I did not test was using /host to host it manually on the ICE (loki in the first link, anansi in the second link) to see if that worked. Apologies, I didn't realise that was a command at the time.

**Comment by NoahTheDuke** [comment]
Hush is fully unimplemented.

**Comment by NBKelly** [comment]
Maybe we should add the unimplemented tag onto it for the time being (I honestly thought that was automated for any card without a def - maybe it should be)

**Comment by NoahTheDuke** [comment]
It is. If it's not appearing, that's a bug. But it's supposed to have been automated for as long as I've been working in jnet.

**Comment by francescopellegrini** [comment]
Partially addressed by #6876
