### ISSUE TITLE
Bankhar + Saisentan interaction

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6875]
This one probably needs input from the rules team.

I use bankar to force the corp to resolve "Do 1 net damage" on saisentan instead of the printed subroutine, so it shouldn't do additional net damage (I think).

Additionally, the same is true with marcus batty (we have confirmation on that one, but it works differently).

I genuinely haven't tested how the cards work together implementation wise, so we probably need to confirm it works right then add a test. (and then I can implement tracker too...)

**Comment by Tamijo-Netrunner** [comment]
Bankhar makes the ice the source of the subroutine, so Saisentan's ability would still trigger in this case. 

`The encountered ice is the source of the “{sub} Do 1 net damage.” subroutine, meaning the runner can use [First Responders](https://netrunnerdb.com/en/card/11048) and [Persephone](https://netrunnerdb.com/en/card/12042).`

**Comment by frontierpsycho** [comment]
> I genuinely haven't tested how the cards work together implementation wise, so we probably need to confirm it works right then add a test. (and then I can implement tracker too...)

I encountered this in the wild and can confirm that it doesn't work correctly.
