### ISSUE TITLE
Winning by agenda points by acessing Superdeep Borehole

### ISSUE THREAD

**Issue by ArminFirecracker** [mtgred/netrunner#6878]
Link to bug replay: https://jinteki.net/bug-report/f6a81673-c4eb-4407-8ed0-4079edce3237?b=0

Description:
When I accessed an installed unrezzed Super deep Borehole the "corp wins by agenda points" window popped up. Which was not true. It immediately happened again at the start of the corps turn. After that we didn't clear the win.

**Comment by francescopellegrini** [comment]
I played Borehole on Circuit Breaker Invitational yesterday an this has never occurred to me.

**Comment by NBKelly** [comment]
This was fixed a while ago, but the server didn't get updated until *just before* the invitational.
