### ISSUE TITLE
Trashing multiple Steelskin Scarring does not present Corp with a "waiting" prompt

### ISSUE THREAD

**Issue by Saintis** [mtgred/netrunner#6887]
When trashing more than one Steelskin Scarring (for example with End of the Line) the runner is presented with a choice of which one to trigger first (since Steelskin is marked with `:interactive (req true)`). The Corp is not presented with a "waiting" prompt and can therefore continue to play more damage cards.

**Comment by francescopellegrini** [comment]
Fixed by #7003
