### ISSUE TITLE
Donor + AltArt cards

### ISSUE THREAD

**Issue by Thorin81** [mtgred/netrunner#6892]
Hi.
Around the beginning of the year, all my AltArt cards disappeared despite being a donor. Is the "Donor" timely and should payments be made periodically for a certain period of time?? If not, please fix it.

**Comment by NBKelly** [comment]
You're in the donor list as `-Thorin-`. In any case, this isn't a codebase issue, this is a site administration issue - if you're still having issues, I suggest you use the email provided on the help page of Jinteki.net.

I'm closing this issue because it's not relevant to the codebase.
