### ISSUE TITLE
Corp player cannot end turn due to discard even with proper hand size 5/5

### ISSUE THREAD

**Issue by tillmas** [mtgred/netrunner#6893]
Link to bug replay: https://jinteki.net/bug-report/f798f955-d98b-42cf-96cf-9e029575bec3?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.
Corp player had 8 cards in hand.  Was told to discard to 5, but upon discarding to 5, was still told to discard.  Could not end turn even after discarding down to 4 cards.

**Comment by NBKelly** [comment]
I went and checked the logs - in this case, the player dragged the cards from HQ to archives instead of using the presented dialog.

I guess I can see if there's a way to prevent that behavior.
