### ISSUE TITLE
Repeatedly losing connection to server, dropped games

### ISSUE THREAD

**Issue by FroFrolfer** [mtgred/netrunner#6894]
My buddy and I have had our last 5 out of 6 games dropped. I've tried everything....factory resets, cleared cache, etc etc

Usually takes about 10-20 minutes. No other connectivity issues within my home network. Halp!

**Comment by FroFrolfer** [comment]
![Screenshot 2023-01-22 11 35 40 AM](https://user-images.githubusercontent.com/116298621/213927461-afe08bb5-5baf-419c-9428-77d34a2b6f3b.png)

**Comment by francescopellegrini** [comment]
Should we close this now @NoahTheDuke ?
