### ISSUE TITLE
Archives accessing order

### ISSUE THREAD

**Issue by iMarco84** [mtgred/netrunner#69]
No way to choose the accessing order when running on Archives.

**Comment by Zulyen** [comment]
It's a real problem because last time i was playing genomic and so put some Shock and Shi.kyu in the Archive.
The runner wants to play Shi.Kyu first (if he or she is smart) to make me pay more.
Shock were triggered first so it was like a discount for me ! :)

**Comment by JoelCFC25** [comment]
Implemented at #485!
