### ISSUE TITLE
Passing ICE bug that is swapped

### ISSUE THREAD

**Issue by NL24VEN** [mtgred/netrunner#6915]
When an ICE is passed and is swapped by Inversificator, it does not seem to be treated as passed.

This bug can be identified in the following situations:

- Inversificator went through the Bioroid ICE and swapped it; Haas-Bioroid: Architects of Tomorrow's ability does not trigger.
- Successful in the run with Inversificator, exchanging multiple ices, but the Into the Depth ability counted fewer ices that passed through.

**Comment by NBKelly** [comment]
The first one is intended behavior.

When you swap a piece of ice, you are no longer passing it (because it's not there). It's the same scenario with no longer accessing an agenda on film critic.

Second one is an actual bug.
