### ISSUE TITLE
Hush didn't counter the printed words on Tollbooth

### ISSUE THREAD

**Issue by azakaria0** [mtgred/netrunner#6916]
Link to bug replay: https://jinteki.net/bug-report/6101253f-2b9a-49c5-8730-4b07b67a9a4c?b=0

Description:

Make a run on Tollbooth with Hush installed on Tollbooth using Overclock and see that 3 credits are still removed from Overclock.   Hush should nullify this effect.

**Comment by francescopellegrini** [comment]
Hush is not implemented yet
