### ISSUE TITLE
Magnet disables the MU cost of hosted programs

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#6917]
I think this is because we unregister events and effects, one of which is [update used MU](https://github.com/mtgred/netrunner/blob/220a4dd5f26fda0923105f11ec726403c6ff4b0b/src/clj/game/core/hosting.clj#L65-L69).

**Comment by NoahTheDuke** [comment]
It seemed like a good idea at the time, but I shouldn't have made MU a constant effect. What an annoying mess.
