### ISSUE TITLE
R&D and Archives don't display multiple upgrades in their respective Roots (newer upgrades cover old)

### ISSUE THREAD

**Issue by Oddball01** [mtgred/netrunner#6922]
This might be a bit unusual, but in my Startup deck, when I install multiple upgrades in the root of R&D and Archives they cover each other up. 

Example 1: One upgrade in the root of Archives

![upgrade on Archive   R D issue1](https://user-images.githubusercontent.com/88608704/231028324-a75e1063-7764-4cc5-b6e7-939a982e816e.png)

Example 2: The second, newer, upgrade now covers the first.

![upgrade on Archive   R D issue2](https://user-images.githubusercontent.com/88608704/231028343-80e05e1a-eb79-46b7-948e-9960c51745ec.png)

Is there any way to get R&D or HQ (or Server 1) to shift to the right when multiple cards are installed in the root of a central?

Thank you!

**Comment by NoahTheDuke** [comment]
Oh interesting. Yeah, they should be layered the other way.

**Comment by butzopower** [comment]
Fixed by #7236
