### ISSUE TITLE
Sounds still not working - can't play without them.

### ISSUE THREAD

**Issue by Bovrill** [mtgred/netrunner#6926]
As in the previous oddly closed thread:

@NoahTheDuke if you have time please have a look at this, looks like a misdirected link for the sound files.

**Comment by GRichardson90** [comment]
Same here. It's not the same without the sound :( seems that a recent commit can't find the audio files, but they are still in the repo.

**Comment by AndersRask** [comment]
@NoahTheDuke same here it is really hard for me to play without sound, due to the way my brain is wired (suffer from misophonia)

**Comment by AndersRask** [comment]
@Bovrill should be fixed now, plz test and close this if fixed for u as well

**Comment by Bovrill** [comment]
Fantastic! Thank you so much!

**Comment by Bovrill** [comment]
Fantastic! Thank you so much! Just in time for our Tuesday night games session too, you chaps are the best.
