### ISSUE TITLE
Bug with Gemini (or perhaps Rutherford Grid or Improved Tracers.)

### ISSUE THREAD

**Issue by StashAugustine** [mtgred/netrunner#693]
I had two seperate games where, upon firing Gemini's trace sub, the runner would repeatedly receive prompts to boost the trace with no way out of the loop. Each trace would do damage, leading to an inevitable flatline. In both cases, the Gemini trace was boosted with money and with either Improved Tracers or Rutherford Grid. Other tracer ice (Ichi 2.0 and Flare were tested) worked fine with the agenda/upgrade boosts. I didn't test other constellation ice nor Gemini without agenda/upgrade boosts, but Gemini was consistently bugged each time the sub fired.

**Comment by StashAugustine** [comment]
Update: Gemini is bugged even without the Corp boosting the trace or with Rutherford/Improved Tracers. Runner had to beat the trace to break the loop.

**Comment by JoelCFC25** [comment]
I see the problem--there's a closing paren in line 229 in the wrong place. 

Current (wrong): `:effect (effect (damage :net 1) {:card card})`
Intended (right): `:effect (effect (damage :net 1 {:card card}))`
