### ISSUE TITLE
Friday chip shows code text in chat log

### ISSUE THREAD

**Issue by marckubischta** [mtgred/netrunner#6931]
Link to bug replay: https://jinteki.net/bug-report/48a9ba9b-0df3-4d4c-bd34-e0626f93cb98?b=0

Description:

Run friday chip and trigger it.

`player1 game.cards.hardware$fn__30348$fn__30374$fn__30380$fn__30381@71fb84c.`
appears in the chat log

**Comment by francescopellegrini** [comment]
Fixed by #6913
