### ISSUE TITLE
Not able to trigger Odore's second routine

### ISSUE THREAD

**Issue by locks** [mtgred/netrunner#6940]
Reported on GLC:

> When you have 3 virtual resources installed, jnet does not offer the option of using the 2: break any number of subs option on Odore.
Had a game where I wanted to charge the Twinning using that, but only was allowed to break for 0.

Card: [Odore](https://netrunnerdb.com/en/card/26071)

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed by #7220
