### ISSUE TITLE
Clicking on Simulchip to install while first Masterwork prompt is open, then trying to undo and redo locked run

### ISSUE THREAD

**Issue by Renolak** [mtgred/netrunner#6944]
Link to bug replay: https://jinteki.net/bug-report/2dba09a0-08c0-48eb-b386-5c41200c58db?b=1

Description:

- Had Masterwork (v37) and Prognostic Q-Loop installed
- Started a run
- Masterwork prompt "Install? yes/no" appeared.
- Clicked on Simulchip before clicking yes on Masterwork prompt, spending a click and underpaying
- /undo-click and put Simulchip back in hand
- Clicked yes in Masterwork prompt and installed Simulchip appropriately
- Q-Loop prompt showing next 2 cards appeared, but would not close when clicking "ok"
- Refreshed the browser window.  Q-loop prompt is gone, but "Current phase: Movement" window is now up and will not respond.
- Fixed by doing /jack-out and resetting to beginning

**Comment by NBKelly** [comment]
You took a click in the middle of a run, which basically bricks how our undo-click works. This is probably unlikely to change in the next few years.

You have to use `/undo-turn` to fix things like this.
