### ISSUE TITLE
Maw triggering on Archives run

### ISSUE THREAD

**Issue by thebigunit3000** [mtgred/netrunner#6946]
Link to bug replay: https://jinteki.net/bug-report/ad1f7268-8cee-4ded-9e72-ae15d11d874c?b=0

Description:

Maw triggered on a different access than it was supposed to.  I ran R&D checked and didn't trash/steal a card, Maw didn't fire.  I ran Archives later in the turn, and it *did* fire then (during the access step).

thebigunit3000 uses Hoshiko Shiro: Mahou Shoujo to draw 1 card and lose 1 .
thebigunit3000 uses Paladin Poemu to add 1 to itself.
thebigunit3000 spends and trashes Fermenter to use Fermenter to gain 6 .
thebigunit3000 spends to make a run on R&D.
thebigunit3000 approaches ice protecting R&D at position 0.
thebigunit3000 passes ice protecting R&D at position 0.
thebigunit3000 approaches R&D.
thebigunit3000 breaches R&D.
thebigunit3000 accesses an unseen card from R&D.
thebigunit3000 spends and pays 1 from Paladin Poemu to install Mystic Maemi.
thebigunit3000 spends to make a run on Archives.
thebigunit3000 will continue the run.
thebigunit3000 approaches Archives.
thebigunit3000 breaches Archives.
thebigunit3000 accesses Megaprix Qualifier from Archives.
thebigunit3000 steals Megaprix Qualifier and gains 1 agenda point.
thebigunit3000 uses Paladin Poemu to add 1 to itself.
thebigunit3000 uses Mystic Maemi to add 1 to itself.
 uses Sportsmetal: Go Big or Go Home to draw 2 cards.
thebigunit3000 uses Maw to force the Corp to trash a random card from HQ.

**Comment by NBKelly** [comment]
Just to double-check on this, the first time maw couldn't fire because HQ was empty, right?

I think I have a fix for this.
