### ISSUE TITLE
Eternal Points List is outdated

### ISSUE THREAD

**Issue by AugustusCeasar** [mtgred/netrunner#6952]
The automatic calculation of points for an eternal deck is currently outdated compared to the list in the [nsg website](https://nullsignal.games/blog/eternal-points-list-23-03/#Eternal2303).

The cards I found did not match the points in the list were:
-Museum of History. Should be 2 points, is listed as 1.
-Ob. Should be 2 points, is listed as 0.
-Mti Mwekundu. Should be 1 points, is listed as 2.
-Mutually Assured Destruction should be 1 points, is listed as 0.
-Tech Trader should be 1 points, is listed as 2.

**Comment by francescopellegrini** [comment]
Eternal points was technically [updated back in May](https://github.com/NoahTheDuke/netrunner-data/pull/34), but I'm not sure changes were deployed since then.. @NoahTheDuke ?

**Comment by tblackwe** [comment]
completed, can be closed.
