### ISSUE TITLE
Deck builder shows Endurance as Standard legal

### ISSUE THREAD

**Issue by tsujigiri** [mtgred/netrunner#6953]
I have a deck with Endurance in it and it's shown as Standard legal in the deck builder, while [NetrunnerDB says it isn't](https://netrunnerdb.com/en/card/33025).

**Comment by francescopellegrini** [comment]
Hi @tsujigiri , have you tried editing the deck and saving it again? I know this is an issue with old decks that were created when a different banlist was active.

**Comment by tsujigiri** [comment]
Hmmm, no. It's still the same after editing or creating a new deck and copying the card list into the new one

**Comment by francescopellegrini** [comment]
I guess, as mentioned on #6952, [the changes merged back in May](https://github.com/NoahTheDuke/netrunner-data/pull/34) have not been released yet.. @NoahTheDuke ?

**Comment by NBKelly** [comment]
We've updated the format legality, this can get closed now @NoahTheDuke
