### ISSUE TITLE
Support for Chinese language card data is sort of broken

### ISSUE THREAD

**Issue by csbisa** [mtgred/netrunner#6960]
With https://github.com/mtgred/netrunner/pull/6902 we have a problem with the Chinese language code that will prevent card titles, images, etc from being not loaded for both Simplified and Traditional Chinese. The problem comes from jnet using `zh-simp` and `zh-trad` for the internal setting while external sources use `zh-hans` and `zh-hant`. We have a few options:

1) Change the internal codes from simp/trad to hans/hant. Users with those languages selected will get reverted to English when the update rolls out and they will have to update their language once again.
2) Have a mapping between those two codes when doing conversion (done somewhere in the API layer).

**Comment by NBKelly** [comment]
Closed as completed via  #7616
