### ISSUE TITLE
Jaguarundi threat 4 error on approach

### ISSUE THREAD

**Issue by TheColourfulDev** [mtgred/netrunner#6968]
Link to bug replay: https://jinteki.net/bug-report/f292c1a6-47c7-4488-b194-76a4cfef4894?b=0

Description:

Jaguarundi seems to error when approached while threat 4 condition is reached - causing an internal server error. This happens when clicking the "Encounter Ice" button I think... and the game state freezes

**Comment by TheColourfulDev** [comment]
This seems very simple to fix. Line `2235` of the Jaguarundi card has an unwanted `;` semicolon. I suspect this is the issue

**Comment by NBKelly** [comment]
Almost - I used the wrong give-tags subroutine. I've put a PR up for it.
