### ISSUE TITLE
Show game time in lobby

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#6994]
We're already sorting the lobby based on the time created/time started, it would be cool to put the current game time in the lobby. 

This would help you decide if a game is worth watching.

**Comment by Wikignometry** [comment]
Hi I'm working on this issue right now. Does it make sense to refresh the times every minute or would that cause performance issues? Any advice you have would be appeciated!

**Comment by NBKelly** [comment]
Closed as completed via https://github.com/mtgred/netrunner/pull/7407
