### ISSUE TITLE
Starlit Knight in Acme

### ISSUE THREAD

**Issue by mcgreenhalgh** [mtgred/netrunner#6996]
If I'm understanding the wording/rules correctly, in Acme, once threat=4, Starlit Knight should gain an ETR sub.

**Comment by NBKelly** [comment]
That makes sense to me, and looking at it in the code is looks right, so I feel like figuring it out in engine is going to be a nightmare.

Poor ACME.

**Comment by francescopellegrini** [comment]
Fixed by #7073
