### ISSUE TITLE
Suggestion: user profile, public stats

### ISSUE THREAD

**Issue by iMarco84** [mtgred/netrunner#70]
It would be cool if you could implement public stats (win/loss, % id used, etc.) and more settings to personalize user profile (avatar, background pics, etc.).

Thanks!

**Comment by domtancredi** [comment]
Updated in https://github.com/mtgred/netrunner/pull/1047

**Comment by JoelCFC25** [comment]
OK, stats have been on the fritz for awhile, but a User Profile NOW EXISTS! Sound the trumpets, we're closing the oldest open issue.
