### ISSUE TITLE
Negative runner hand size does not trigger game win for Corp

### ISSUE THREAD

**Issue by PeterH139** [mtgred/netrunner#700]
Pretty much described in title: was playing Kate against Cybernetics Division and hit two Cerebral Overwriters and one scored Self-Destruct Chips giving me 5 brain damage and -2 hand size from ID and scored agenda. Image attached of game board at point of loss.

![negative-hand-size](https://cloud.githubusercontent.com/assets/1383575/9775666/dd3de56e-5748-11e5-982a-05775b18516a.png)

**Comment by JoelCFC25** [comment]
In that screenshot, would it let you hit End Turn or not? There is a flatline message in the `core.clj` code for when the turn end occurs and the Runner's hand size is negative, but if you were prevented from hitting End Turn, you never would've seen it. Remember that this flatline condition is not instantaneous--the Runner has until the end of the turn to bring max hand size up to 0 or more.

**Comment by queueseven** [comment]
I think that's only fair because decking the corp does not result in a win for the runner.
