### ISSUE TITLE
New Feature Request: Start of Turn Order

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#705]
Could we get a way to change the order things trigger at start of turn. On a few occasions with drug dealer the games giving me money then it's taking it away where id rather it do it the other way round. maybe this is just that drug dealer should really take money first rather than when played but been able to change the trigger order would be nice.

**Comment by queueseven** [comment]
Yeah, that would be nice to have.

**Comment by zaroth** [comment]
This was touched recently in a discussion about priority of card effects (such as Drug Dealer / Daily Casts). What is its status? @nealterrell ?

**Comment by JoelCFC25** [comment]
Keep an eye on the discussion in #282--a new system for "when your turn begins" handling is coming soon.
