### ISSUE TITLE
Can't create new server from Timely Public Release Counter

### ISSUE THREAD

**Issue by asertus** [mtgred/netrunner#7076]
I can only install ice on existing server, and not create new remote

**Comment by asertus** [comment]
Sorry but this still does not work properly. See my game from today:
https://jinteki.net/bug-report/a259164f-0a8f-4857-95a3-61c68fd1004e?b=0

**Comment by NoahTheDuke** [comment]
The fix hasn't been deployed yet so it's not live on the site. Hopefully will go out soon.
