### ISSUE TITLE
Adrian Seis on HQ doesn't trigger when running with Sneakdoor Beta

### ISSUE THREAD

**Issue by rgdelato** [mtgred/netrunner#7080]
This happened on Metropole Grid's livestream today, timestamp here: https://www.youtube.com/live/NW2acgeT0rA?feature=share&t=17967

**Comment by TreffnonX** [comment]
It shouldn't trigger. Both windows are missed, as the runner's abilities must resolve before the Corps'. If Adrian is on Archives, the runner moves to HQ before Adrian can resolve. If Adrian is on HQ, the run was already successful, when being shifted to HQ, making the card not 'see' the run succeeding on it's server. So the implementation is correct imho.

**Comment by postinternetsyndrome** [comment]
@TreffnonX Not correct. Sneakdoor has been the source of a lot of confusion over the years, but the current wording is crystal clear:

"[click]: Run Archives. If that run would be declared successful, change the attacked server to HQ for the remainder of that run."

Emphasis on "would be" successful. Sneakdoor triggers on interrupt timing, which means the run is not yet successful, it is merely about to be. The run is transferred over the HQ and continues when the interrupt window closes, resulting in a conventional successful run on HQ.

Adrian Seis should trigger.

**Comment by TreffnonX** [comment]
@postinternetsyndrome Thank you for the clarification.

**Comment by francescopellegrini** [comment]
#6989 should've fixed this

**Comment by francescopellegrini** [comment]
@NoahTheDuke fixed already
