### ISSUE TITLE
Zero games

### ISSUE THREAD

**Issue by AndersRask** [mtgred/netrunner#7107]
I am seeing this _a lot_ recently!
It even happens when I have to refresh the game (F5) because the game becomes unresponsive.

Pressing F5 eventually solves it, or waiting for like 5 minutes. CTRL+F5 does not seem to work, so it does not look like a client cache issue.

I have heard of many players seeing this recently, so surprised to find no other bug requests (that i could find)
![image](https://github.com/mtgred/netrunner/assets/1651150/fe878ad9-c079-4c35-81a3-a05043d1c66c)

**Comment by AndersRask** [comment]
I can also add that when i "cheat" it to reload using multiple x F5, it sometimes also does not show my game on the left side, as if the game does not exist. Also no-one ever joins the game, so it is probably not even visible!
As shown below, game does not show up in the list on the left
![image](https://github.com/mtgred/netrunner/assets/1651150/3a720239-1225-485e-b9da-eeef3af3b832)

**Comment by AndersRask** [comment]
Looking in F12 view i see these WS requests. Could that be related? They are all 3rd party requests
![image](https://github.com/mtgred/netrunner/assets/1651150/7cd09465-6f4b-45a3-8f24-bf0a0f33a3c3)

**Comment by butzopower** [comment]
That's the client trying to connect to the server via a websocket and the error is it saying it hasn't opened correctly. This is indeed the issue causing 0 games (and anything game related) but isn't the source of the problem, which is the server seeming to be very flaky on fully establishing new websocket connections.

**Comment by AndersRask** [comment]
> That's the client trying to connect to the server via a websocket and the error is it saying it hasn't opened correctly. This is indeed the issue causing 0 games (and anything game related) but isn't the source of the problem, which is the server seeming to be very flaky on fully establishing new websocket connections.

thanx for the response!
I have had a browser open for 8 hours today in the background waiting for a game, but so far no dice! :(
I have posted on Netrunner Dorks, and a lot are seeing this issue. Is there any way to fix it?

**Comment by postinternetsyndrome** [comment]
It's been discovered that double-clicking the "attempt reconnect" button seems to get it working again.

**Comment by AndersRask** [comment]
> It's been discovered that double-clicking the "attempt reconnect" button seems to get it working again.

trust me i clicked every button many times, it just will not give me a connection. In the beginning doing 2 F5 after each other solved it for me, but now its just blocked where no amount of clicking or refreshing helps

**Comment by tsujigiri** [comment]
> It's been discovered that double-clicking the "attempt reconnect" button seems to get it working again.

This works for me, too!

**Comment by MGillett** [comment]
Clicking the "Attempt reconnect" doesn't work for me and neither does F5. Double-clicking "Attempt reconnect" has worked two times, but most of the time the second click just highlights text ("Games Attempt" or "reconnect") and nothing happens.

**Comment by ivorking** [comment]
I see this issue a lot. Games list vanishes then later reappears appears after a couple of reloads.

**Comment by francescopellegrini** [comment]
Should we close this now @NoahTheDuke ?
