### ISSUE TITLE
Cannot select any decks (decks are not showing)

### ISSUE THREAD

**Issue by nguthrie** [mtgred/netrunner#7126]
Hi, I'm new to using Jinteki. I was able to start a game normally but I was then disconnected for internet issue on my end, and when I returned, I couldn't load into the game. My friend conceded and we started a new game, but my decks wouldn't show. I only have the starter decks, with no modification. I've logged in and out, created a new account, tried with Edge and Chrome, and my decks still won't show. 

Specifically, after clicking `Select Deck` all I see is the following:
 
![image](https://github.com/mtgred/netrunner/assets/8152676/3082147a-fcce-4857-908f-10612b7c1573)

**Comment by lolabug4** [comment]
I’ve also been experiencing the same issue.
