### ISSUE TITLE
We need to handle face-down cards in archives better

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#7135]
When the runner has to randomly access face-downs in archives, we can get weird effects like them making more accesses than there are face-downs, or hitting the same face-down multiple times, etc.

I'm not sure exactly why this is, but it does make our friendly eternal IG players a bit more powerful than they should be.

**Comment by NoahTheDuke** [comment]
Randomly access facedown cards in archives?

**Comment by NBKelly** [comment]
for when something like bacterial puts cards in archives face-down mid-access
