### ISSUE TITLE
Sage, Savant, and Adept don't cost credits per usage

### ISSUE THREAD

**Issue by Lavander42** [mtgred/netrunner#7137]
When you use one of the three ICEBreakers, Sage, Savant, or Adept to break more than once on a single piece of ICE, it only costs 2 credits total, no matter how many subroutines you break.

**Comment by Lavander42** [comment]
It's not fixed. It just happened to me. I just spent 2 credits with Savant, broke 2 Code Gate subroutines, then it gave me the option to break 2 more despite not having any credits to spend on it.

**Comment by NoahTheDuke** [comment]
The fix is merged into the code base but we haven't updated the server yet. It'll hopefully happen soon.
