### ISSUE TITLE
Hunting Grounds and Quicksand

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#714]
When the runner uses Hunting Grounds to prevent the "when encountered" ability on Quicksand, Quicksand still gains a power counter.

**Comment by queueseven** [comment]
Yes, Hunting Grounds currently simply displays the message. All "when encountered" abilities are manual, expect Quicksand.

**Comment by queueseven** [comment]
Makes me wonder if Quicksand works correctly with Femme Fatale and Inside Job. I guess not.

**Comment by nealterrell** [comment]
Yeah, it's a sloppy implementation. Should probably make the Gain a Counter ability manual on card click.

**Comment by nealterrell** [comment]
Joel submitted a fix in #732 to make the effect completely manual.
