### ISSUE TITLE
Amani Senai not taking into account San San City Grid discount in the trace

### ISSUE THREAD

**Issue by Joseph7695** [mtgred/netrunner#7148]
Link to bug replay: https://jinteki.net/bug-report/0494b789-43ae-4866-a265-3a44c268bc1c?b=0

Description:

Amani Senai not taking into account San San City Grid discount in the trace

**Comment by butzopower** [comment]
Dug into the comprehensive rules and I think the current behavior is correct

![image](https://github.com/mtgred/netrunner/assets/5345/d04227db-69b5-44ac-875c-52e23af428c3)

**Comment by Joseph7695** [comment]
Very precise wording here, thanks for checking
