### ISSUE TITLE
Virtual Service Agent on Archives with Reality Plus leads to Unplayable State.

### ISSUE THREAD

**Issue by surfur2** [mtgred/netrunner#7162]
Link to bug replay: https://jinteki.net/bug-report/1d212b71-c5be-46de-9686-7f476f7c4c2a?b=0

Description:

When rezzing Virtual Service Agent on archives, the runner took a tag from not breaking all subroutines. This triggered the NBM Reality Plus corp power, which I took 2 credits from. The issue is after doing this, the runner side was waiting for the corp to resolve all actions and the corp had no additional actions to resolve, leading to a gamestate that could not be progressed through.

**Comment by butzopower** [comment]
This was fixed in #7136

**Comment by francescopellegrini** [comment]
cc @NoahTheDuke
