### ISSUE TITLE
Pinhole Threading - Unable to Click in Root

### ISSUE THREAD

**Issue by The-BenBen** [mtgred/netrunner#7165]
Link to bug replay: https://jinteki.net/bug-report/94b7eff9-b85f-4215-952b-c022c7056c56?b=0

Description:

Was against the Jinteki identity that can install in two remote servers, but is limited to two remote servers. Previous turn they had installed in their remotes.

I pinholed one of them, and could not click the root of the server to view it.

Later on also had trouble with Moriera being unable to click to use credits from her while using her run ability.

**Comment by NBKelly** [comment]
>I pinholed one of them, and could not click the root of the server to view it.

Please clarify this a little. Which card were you unable to target with pinhole threading? Was it the same server you were running on or a different one? Were there multiple cards in the server overlapping and you couldn't click the one you wanted?

**Comment by The-BenBen** [comment]
On corp's turn they had used the _A Teia: IP Recovery_ identity ability to install in their two remotes.

I ran Archives. I could not access the stuff in the root of the servers. Clicking on it nothing happened. 

I am not sure why I can't see the replay for this :(
