### ISSUE TITLE
Daily Business Show lead to unplayable state

### ISSUE THREAD

**Issue by bakedgoodsx** [mtgred/netrunner#7167]
I rezed Daily Business Show on the opponents turn. On my turn at draw the prompt appeared 'Choose 1 card to put at bottom of R&D' and each card in my hand lit up yellow. If I selected a card (it went blue) nothing else happened, double click didn't do anything either. If I dragged that card to R&D it placed it on the top, but the prompt remained. I undid the turn a number of times and basically clicked all the cards multiple times but could not progress/move a card to R&D.

I didn't save a replay, I'm also new to Jinetki so not sure if I missed something or there was a bug. I ended up conceding.

**Comment by francescopellegrini** [comment]
DBS cards are shown in the Set-aside zone, they're not added to HQ anymore since the errata, so you should see them on the top-left corner of your screen.

**Comment by NBKelly** [comment]
DBS (and all drawing) was changed to operate on the set-aside zone during triggers, rather than the hand.
