### ISSUE TITLE
[EDITME] Please give a short description of your bug here

### ISSUE THREAD

**Issue by Adam1210** [mtgred/netrunner#7183]
Link to bug replay: https://jinteki.net/bug-report/112e220e-4986-493e-8e01-bfa410f4df63?b=0

Description:

Inside job would not allow me to choose the remote server as my server to run. Only allowed centrals

**Comment by butzopower** [comment]
I just rewatched this replay and you didn't have enough credits to run the remote server due to Earth Sea Station being flipped.

**Comment by butzopower** [comment]
<img width="244" alt="image" src="https://github.com/mtgred/netrunner/assets/5345/ae58d4ce-f8ab-4769-9029-7bdbcbd7b6a6">

**Comment by francescopellegrini** [comment]
Close as Won't fix?

**Comment by butzopower** [comment]
@NoahTheDuke
