### ISSUE TITLE
"bblum uses Stegodon MK IV to shuffle Spin Doctor and 1 unseen card into R&D."

### ISSUE THREAD

**Issue by bblum** [mtgred/netrunner#7198]
Link to bug replay: https://jinteki.net/bug-report/549a9087-06ef-47b5-945a-698fee7a1adf?b=0

Description:

I believe this is similar to other multiple-overlapping-prompt issues, like #6727 and #6718, but this time it manifested in the game log in this amusing and also surprisingly self-explanatory way, so I thought I'd share.

Additional detail: After resolving the first shuffle-2 ability, I got another prompt to shuffle 2 with spin dr, and _no_ stegodon prompt (which I just resolved manually) -- as if spin's ability had been copied onto the stegodon prompt.

**Comment by NBKelly** [comment]
Did you click on spin doctor while stegodon was pending?
