### ISSUE TITLE
Bankhar incorrectly interact with Envelopment

### ISSUE THREAD

**Issue by yaozheng1996** [mtgred/netrunner#7201]
Link to bug replay: https://jinteki.net/bug-report/c1176d41-2534-4fa2-82d1-947e9369d17a?b=0

Description:
Running a remote server with Bankhar on an empty Envelopment.
Should be just 1 damage? 

But log shows 

Tankston trashes Lago Paranoá Shelter due to net damage.
Tankston uses Tsakhia "Bankhar" Gantulga to force the Corp to resolve " Do 1 net damage".
yaozheng1996 uses Envelopment to do 1 net damage.
Tankston has the option to prevent damage.
Tankston will not prevent damage.
Tankston trashes due to net damage.
Tankston is flatlined.
yaozheng1996 wins the game.
yaozheng1996 resolves **2** unbroken subroutines on Envelopment (**" Trash this ice" and " Trash this ice"**).

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by francescopellegrini** [comment]
Duplicates #6584
