### ISSUE TITLE
Slash Disable Command doesn't seem to be disabling the 7 wonder Ice's 3-advancement abilities

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7247]
Link to bug replay: https://jinteki.net/bug-report/4187e717-289c-448a-ae61-36cc0d39dbf5?b=0

Description:
Read on discord that a Slap Vandal couldn't break a Hushed Hortum. Decided to test and found that a hushed akhet doesn't allow slap vandal+vial to break the ice either.

**Comment by NBKelly** [comment]
Interesting. 

Yeah, until we figure out the engine rewrite for disabling cards the proper way, I'm not sure how fixed this will get.

In the mean time, (so long as you're not getting chummed), I suggest manual resolution.
