### ISSUE TITLE
couldn't resolve the daily business effect ...

### ISSUE THREAD

**Issue by Wenjong359** [mtgred/netrunner#7258]
log for the play involved:

Deathandtaxes's game
Lobby: Casual
Format: Standard
Winner: Corp
Win method: Agenda
Started: Sunday, Dec 31, 2024 - 00:45
Ended: Sunday, Dec 31, 2024 - 01:13

**Comment by NBKelly** [comment]
You need to click on the cards in the set aside zone (top left), and you need to make sure you don't try to run other effects (like using spin doctors shuffle ability) before resolving DBS.

If both of those things were accounted for, then we really need more info to do anything here.

**Comment by NBKelly** [comment]
DBS (and all drawing) was changed to operate on the set-aside zone during triggers, rather than the hand.
