### ISSUE TITLE
Feature Request - Add Sunset as a Format

### ISSUE THREAD

**Issue by newmanr4** [mtgred/netrunner#7260]
Currently, as a user I need to indicate via the game title that I want to play Sunset as the format is not in the list of valid formats. This is problematic because many people accidentally join these games with decks that contain cards that are banned in the Sunset format. 

GIVEN I want to play a Sunset game
WHEN I select a format (e.g. Standard, Casual, Startup ...)
THEN Sunset is in the list of formats for me to select, and selecting it enforces the Sunset banlist

**Comment by NoahTheDuke** [comment]
Already implemented in https://github.com/mtgred/netrunner/pull/7259, will be included in the next release.

**Comment by newmanr4** [comment]
> Already implemented in #7259, will be included in the next release.

Thanks! Will mark as resolved
