### ISSUE TITLE
Neo banlist changes 23.09

### ISSUE THREAD

**Issue by xiaat** [mtgred/netrunner#7268]
@tblackwe there were some banlist changes in Neo format back in September. The current banlist is:

**Runner:**
Endurance
Rezeki
Hoshiko Shiro
Paladin Poemu
**Corp:**
Drago Ivanov
Nanisivik Grid
Cyberdex Sandbox

K2CP Turbine was unbanned. 

There's a Neo tournament this Sunday, it would be awesome to see these live by then.

**Comment by tblackwe** [comment]
The update is ready, but I am unable to deploy code to production. 🤞 it is released in time

**Comment by NBKelly** [comment]
Did these changed ever get put through?

**Comment by francescopellegrini** [comment]
@NBKelly No, although the changes were pushed in [this commit](https://github.com/NoahTheDuke/netrunner-data/commit/700f6abdf1160ca2802c37ff137586a522be725e) I tried creating a new Neo deck with Turbine in it and it's still valid

**Comment by NoahTheDuke** [comment]
huh that's weird. how did they not go through? is something broken in our combination logic?

**Comment by NBKelly** [comment]
Just checked again: turbine was *unbanned* (so it being valid is right) and the others on the banlist are invalid, so we did *eventually* put this through. Apologies it wasn't on time!
