### ISSUE TITLE
Swapping multiple Thimblerigs loses a prompt

### ISSUE THREAD

**Issue by xiaat** [mtgred/netrunner#7269]
Start your turn, have 2 Thimblerigs rezzed.
See prompt for swapping Thimblerig №1. Swap it with Thimblerig №2. (for _reasons_)
No prompt for swapping Thimblerig №2 occurs in this case.

**Comment by NBKelly** [comment]
So currently in engine, swapping any ice will actually fizzle pending events (I believe you can use this to make envelopment not lose a counter). At some point it will be fixed, but for now, I *really* don't know how :shrug:
