### ISSUE TITLE
Duplicate, lagged sounds heard during play with multiple tabs open

### ISSUE THREAD

**Issue by xdg** [mtgred/netrunner#7275]
Link to bug replay: https://jinteki.net/bug-report/a962ae27-25dd-4d50-bc17-0515ff3862c7?b=0

Description:

I was playing a game and was hearing sound for install or rez in the game at an appropriate time, then I'd hear sounds again sometimes up to 30 seconds later, even on the other player's turn.  Muting the tab I was on did not fix the problem, but muting another jnet tab (with a decklist) seemed to stop the problem.

**Comment by NBKelly** [comment]
The sounds were playing from the second tab. Each jinteki.net tab is connected to the active game, and receives all events as if it was. I'm not sure we have the technology to determine which tab is the active one (in-engine).

I believe they try to play only when the tab is active, but they stay in queue until the tab is active (like if you tab away from a game, then tab back after the corp clicks for 3 credits) - only three sounds can be in queue at once though.

If one tab is only being used for the decklist, best bet is muting that tab.

**Comment by xdg** [comment]
Cool. Thanks!
