### ISSUE TITLE
"Actions" on jinteki.net

### ISSUE THREAD

**Issue by mo0man** [mtgred/netrunner#7279]
There are various references to "actions" on jnet which I believe colloquially meant refer to abilities (paid, triggered, etc etc), but "Actions" have a specific meaning in netrunner which might be confusing to new players learning the game. I'm not certain how many other ones there are, but 

On the right side, for example, below the chat log there is the option to indicate actions.

**Comment by NoahTheDuke** [comment]
I'm confused about what you're saying or trying to ask for. Can you phrase it as a problem statement?

**Comment by mo0man** [comment]
On the right side, below the chat log there is a button that says "Indicate Actions", when it should say "Indicate Paid Abilities". I believe there are some other examples of similarly inaccurate language.

"Actions" in Netrunner refers to click abilities
