### ISSUE TITLE
Feature: The Run Arrow to contain information

### ISSUE THREAD

**Issue by SephiTrax** [mtgred/netrunner#729]
Hey,

Can you adjust the Yellow Arrow that's displayed when a run start to point out if it's either an Inside Job or a Blackmail etc?

You could either add a small box on top that informs the Corp if the run is a special one? 

I keep playing a LOT of games where people don't look at the chat and they rez their ice's in vain. 

Thanks

**Comment by queueseven** [comment]
I had this idea myself, since it's an annoying problem, but couldn't come up with a satisfying solution. If you have any specific ideas of how this could look like, please feel free to share.

Maybe simply showing the card title in a little box at the end of the run arrow is enough?

Another idea I had was to display the card image barely visible underneath or at the end of the arrow.

**Comment by SephiTrax** [comment]
I would love to do a mockup but I'm currently on holiday.

Should look like:

Inside Job
       i
       i
       i
       i
       i
       v

Where "Inside Job" is in inside a box.

O the text is displayed sideways on the Arrow itself...

**Comment by Merlin8000** [comment]
This is a great idea - same would be nice for any card that initiates a run (I'm looking at you, Account Siphon)

**Comment by nealterrell** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/10083341/9973461/0f4205fa-5e28-11e5-9698-a29c81ea3464.png)

Is the orange too hard to read? It can be hovered to view the card like other orange card links.

**Comment by Merlin8000** [comment]
looks good - maybe with a solid background rounded-corner-magic-div-of-eyeball-friendliness to keep it more consistently readable?

**Comment by HongkongKoma** [comment]
Great idea! +1

**Comment by thehunter518** [comment]
Love this idea

**Comment by domtancredi** [comment]
Minor styling and positioning for this. @nealterrell added the structure, card-hover, and other stuff; I took on the style and positioning
