### ISSUE TITLE
Ice with "when passed" abilities should still fire when moved by Inversificator

### ISSUE THREAD

**Issue by OtisF** [mtgred/netrunner#7295]
Under FFG I believe this was ruled the opposite way, and this is what jnet still has implemented. (see https://github.com/mtgred/netrunner/issues/5143)

However, the current ruling by NSG is that "when the runner passes this ice" abilities (Tatu-Bola, AoT, Kakugo, etc) still fire even if the ice is moved. See the second official ruling on the NRDB page for Inversificator: https://netrunnerdb.com/en/card/12048

**Comment by butzopower** [comment]
This was fixed in #7285 and should go out with next release.
