### ISSUE TITLE
SEA source

### ISSUE THREAD

**Issue by iMarco84** [mtgred/netrunner#73]
After retrieving SEA Source with Project Atlas agenda counter, it doesn't let me play it first click, even if the runner run successfully last turn. Please investigate!

Thanks.

**Comment by mtgred** [comment]
I did some testing and could reproduce the issue.

On top of the successful run condition, you must also have 2 credits and 1 click left to play SEA Source else nothing will happen when you click the card. It might explain why nothing happened.

By the way SEA Source is not fully automated.

**Comment by iMarco84** [comment]
I had tons of credits, 3 clicks left and retrieved SS via PA token. Weird.

**Comment by anathomical** [comment]
After some quick testing, my best guess is that the runner did not actually run on the previous turn.  This is a required condition to play SEA Source, and is silently enforced by the game engine.  That is, the card will be highlighted as if you can play it, but clicking on it will do nothing.  If the runner did run on the previous turn, then the card is playable as expected.

So: best guess is that this is not a bug.  But in the long-run it may be worth considering some way of indicating to a user why the card won't let itself be played.
