### ISSUE TITLE
"Pretty" Mary da Silva not copying over from netrunnerdb

### ISSUE THREAD

**Issue by mpwcode** [mtgred/netrunner#7318]
When you copy your deck from NetrunnerDB into Jnet and it has Mary in it, instead of going in the resources section of the deck and costing the appropriate amount of influence, it instead ends up as an "unknown" card and makes your deck illegal. Adding in manually from Jnet works. I would say it had to do with different quotation marks being used by each site, but Bankhar works, so idk.

**Comment by butzopower** [comment]
Arguably this is a bug in NetrunnerDB's Jinteki export functionality - I believe it's going to be fixed in their codebase.

**Comment by francescopellegrini** [comment]
Fixed by https://github.com/NetrunnerDB/netrunnerdb/pull/813

**Comment by NBKelly** [comment]
Closed as completed via https://github.com/NetrunnerDB/netrunnerdb/pull/813
