### ISSUE TITLE
Kingmaking offers no option on how many cards to draw

### ISSUE THREAD

**Issue by TheSovietLoveHammer** [mtgred/netrunner#7325]
Link to bug replay: https://jinteki.net/bug-report/70bc7226-e5b4-451d-b4b7-941389f559dd?b=0

Description:

When kingmaking was scored 3 cards were automatically drawn, rather than a choice of 0, 1, 2 or 3 cards.

**Comment by NBKelly** [comment]
Duplicate of #7316
