### ISSUE TITLE
Lady Liberty Needs prompt for Ordering

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#7331]
Link to bug replay: https://jinteki.net/bug-report/281296ac-c7d7-4428-87c3-dfaabe7138db?b=0

Description:

With Lady Liberty and Warm Reception installed, you should be able to use warm reception to derez Lady Liberty and keep it from getting a counter, but lady liberties trigger doesn't appear in the ordering prompt and always triggers before warm reception.

**Comment by NBKelly** [comment]
I think it's probably more important to add it to warm reception (since that will probably interact with a trillion other cards) - so I'll do that in the next patch
