### ISSUE TITLE
Minor visual bug when The Price trashes Strike Fund

### ISSUE THREAD

**Issue by ais523** [mtgred/netrunner#7332]
Link to bug replay: https://jinteki.net/bug-report/db116525-7c88-44bc-9271-178569de909a?b=0

Description:

When the Runner used The Price, and the first card trashed happened to be Strike Fund (with none of the others having interesting side effects), to my view (as the Corp) the prompt telling me that the Runner was making a decision showed a picture of Strike Fund, rather than of The Price.

**Comment by NBKelly** [comment]
The runner has to make a decision on whether or not to trigger strike fund, since it's optional (for some reason).

**Comment by ais523** [comment]
You're right – jinetki.net is actually correct here, but the rules are so weird it looks wrong. I guess this report is invalid then.
