### ISSUE TITLE
Trick Shot gives a third run if the second run is redirected to R&D

### ISSUE THREAD

**Issue by ais523** [mtgred/netrunner#7335]
Link to bug replay: https://jinteki.net/bug-report/6f5238dc-a03c-4d53-9cc5-9f6ce91c004f?b=0

Description:

During the second part of a Trick Shot run (onto a remote), the Corp redirected the Runner back onto R&D (using AgInfusion's ID ability). I continued the run until it was successful; at that point, Trick Shot prompted to make another remote run (and also gained another two credits). Expected behaviour is for the run to end after the second run is successful, even if it's on R&D.

**Comment by AlexBoyd** [comment]
this is likely related to: https://github.com/mtgred/netrunner/issues/7328

**Comment by LiteSpecter** [comment]
Trick Shot is giving a third run in a lot of instances for me, I think it has to do with other successful R&D run triggers. I know it gives a third run when "Pretty" Mary da Silva and Psych Mike are installed using Akiko Nisei: Head Case as the ID.

**Comment by xiaat** [comment]
Can confirm, I've seen a lot of 3rd Trick Shot run prompts both myself and by my opponents.
