### ISSUE TITLE
Cards on Cupellation Still Not Disabled

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#7337]
Link to bug replay: https://jinteki.net/bug-report/20fde847-35e7-4c37-bbf5-82e947e08762?b=0

Description:

Cards on Cupellation still aren't disabled (in replay Front Company is still active and Warden Fatuma cannot be rezzed because there's another active copy).  I think this was supposed to be fixed by #7326 but if I'm reading github correctly that went out in the last update and they still aren't disabled.  (Apologies if this is fixed and just hasn't made it live yet).

**Comment by francescopellegrini** [comment]
Allegedly fixed by #7366
