### ISSUE TITLE
Trick Shot Preventing Trash after Ansel Fire on R&D Run

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#7343]
Link to bug replay: https://jinteki.net/bug-report/aae7fb74-e09e-4e09-92b1-c0cde7be1063?b=0

Description:

If runner uses trick shot and third Ansel sub fired on R&D ("Runner cannot steal or trash cards") that text is still applying on the remote run.  Seems like Jnet is treating the remote run as a redirect instead of a new run.

**Comment by NBKelly** [comment]
jnet is treating it as a new run, it's just that in our effect system, the runner's `:end-run` triggers go first (making a new run), while the corp's `:end-run` triggers (ansel no longer applying) are still pending.
I've been thinking about this, and I'm not 100% sure what the actual solution is. Maybe we'll need a `:pre-run-ends` trigger for this sort of stuff, even though that's ugly.

**Comment by NoahTheDuke** [comment]
I think i know the solution, I'll take a look.
