### ISSUE TITLE
yusuf not removing counters properly, then /counter v n was working inconsistently

### ISSUE THREAD

**Issue by RomeoSierra** [mtgred/netrunner#7368]
Link to bug replay: https://jinteki.net/bug-report/eb086619-1b11-487d-9dfc-a47b286d4708?b=0

Description:

yusuf removing counters stopped working part way through the match and it really seemed like that was also causing problems with the runner's start of turn triggers on the following turn.

**Comment by NBKelly** [comment]
Hi, these were ephemeral issues related to #7346.
I'm closing this as completed/fixed via #7383, but if anything like this happens again, please do open another issue.
