### ISSUE TITLE
A few suggested improvements

### ISSUE THREAD

**Issue by ihmcallister** [mtgred/netrunner#737]
Been really enjoying the work you guys are doing but I think the game experience could be improved by the addition of some of the following:

1) A mem warning if you are about to exceed yours when installing a programme. Reversing this when it happens can be a bit of a pain.

2) A way to say that you want to trigger an ability during the other players turn, but without making it something you have to click after every action. Maybe just a button you can press that signals you want to do something. By the time you have typed it in the chat log it is often past the time you want to do it. This is especially important for things like clot. 

3) A way to see who is playing what faction in the active game list. 

Thanks

Iain

**Comment by zaroth** [comment]
Please avoid grouping multiple issues in one such as this. One suggestion, one issue.
