### ISSUE TITLE
Kit giving Hammer Code Gate + Lobisomem allowed to break multiple subs

### ISSUE THREAD

**Issue by xdg** [mtgred/netrunner#7374]
Link to bug replay: https://jinteki.net/bug-report/09d7d946-4e41-4e72-b6d5-6d4efe535831?b=0

Description:

Kit gave Hammer Code Gate on encounter and then I was able to use Lobi to break multiple subs, which should not be allowed.

**Comment by butzopower** [comment]
The breaking restrictions are not implemented for Hammer - so this isn't actually because of Kit but would happen with something like Botulus as well

<img width="459" alt="image" src="https://github.com/mtgred/netrunner/assets/5345/b8abf76b-b97e-4ba3-9226-8093bd2cb870">

**Comment by NBKelly** [comment]
^^ - the amount of hacking required to make this actually work is pretty extreme, and it probably cannot be done correctly in our current engine

**Comment by xdg** [comment]
Makes sense. Would it be possible to make the breaking restriction notice more visible? Perhaps it could be put next to the "break subs" dialog rather than only appearing with the card image popup?

**Comment by NBKelly** [comment]
There's already a big message with a big exclamation mark icon beside it that pops up in the chat log whenever one of those gets rezzed (like all our other impl messages). If your opponent isn't going to read that, and they're not going to read the card itself, I'm not sure any visual indicator will work for them.

**Comment by xdg** [comment]
Cool. Closing.
