### ISSUE TITLE
Certain cards did not work during a match

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7381]
Link to bug replay: https://jinteki.net/bug-report/a9179945-b3c1-49ef-bc67-7f9dc6617218?b=0

Description: During our game, the following bugs happened:
The corp could not use NGO front to trash and gain money.
The runner could not use Lobisomem's barrier-breaking ability against Tree Line.
The runner could not use Cataloguer after making a succesful run on RnD.

**Comment by NBKelly** [comment]
Hi, these were ephemeral issues related to #7346.
I'm closing this as completed/fixed via #7383, but if anything like this happens again, please do open another issue.
