### ISSUE TITLE
Spin Doctor does not remove itself as part of the ability cost

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7382]
Link to Bug Replay:https://jinteki.net/bug-report/9d02cd29-17ef-432f-9c3f-db7c0bcf0b59?b=0

Description: As seen in the replay, spin doctor uses its ability and does not remove itself from the game.

**Comment by xdg** [comment]
More examples:
* https://jinteki.net/bug-report/9a95a3eb-17b3-46c3-b76d-ce7ce4efafa5?b=0
* https://jinteki.net/bug-report/5e289e1f-a1cf-4898-bbaf-da5dcf10e24f?b=0

**Comment by NBKelly** [comment]
Hi, these were ephemeral issues related to #7346.
I'm closing this as completed/fixed via #7383, but if anything like this happens again, please do open another issue.
