### ISSUE TITLE
Cohort Guidance Program and DBS

### ISSUE THREAD

**Issue by doomrat** [mtgred/netrunner#7391]
Link to bug replay: https://jinteki.net/bug-report/f9757824-94b8-4e19-a05f-69fdcdfdae14?b=0

Description:

When you trigger cohort guidance program (draw 1 gain 2) with daily business show installed at start of turn you get your mandatory draw before making the DBS decision.  Additionally, if you additionally have warm reception installed, it doesn't let you chose the DBS trigger, and locks up if you try to proceed with warm reception.  You can get past this /close-prompt, but it strands the DBS cards in the set-aside zone.

**Comment by NBKelly** [comment]
The interior ability on cohort needs an `:async true`. I'll add a PR with that and a few other fixes some time soon.
