### ISSUE TITLE
Levy turned me into Corp

### ISSUE THREAD

**Issue by cdrock** [mtgred/netrunner#74]
I used LEVY and I was turned into the corporation.  My ID turned into my opponents ID, my heap was turned into Archives, etc.  It also removed all installed cards from the game.

**Comment by anathomical** [comment]
I have been unable to reproduce this one across multiple attempts.  Possibly this was some weird one-off occurrence?

**Comment by eah13** [comment]
@cdrock has this happened again?  If not, perhaps we can close this issue for now?

**Comment by JoelCFC25** [comment]
Closing this. Reopen a new issue if it comes back and you can reliably reproduce it!
