### ISSUE TITLE
Business As Usual did not resolve both modes when threat was active

### ISSUE THREAD

**Issue by xdg** [mtgred/netrunner#7404]
Link to bug replay: https://jinteki.net/bug-report/b3da9467-ca76-4836-9474-2f14e4d7b8d6?b=1

Description:

[Business As Usual](https://netrunnerdb.com/en/card/34128) still prompted only a single choice, even through threat was active.

**Comment by NBKelly** [comment]
I believe the card has a "Both" option as the third button on the prompt. Was that not available?

I don't particularly like that though, so I want to change it to `pick one -> asked about the other`.

**Comment by xdg** [comment]
I don't recall if it was there or not. I do think "pick one ask about the other" would be more like how other prompts work.
