### ISSUE TITLE
Overseer Matrix' UI shows additionalt blank options

### ISSUE THREAD

**Issue by wowarlok** [mtgred/netrunner#7424]
When multiple Overseer Matrix trigger for the second time on the same run the UI shows 2 blank buttons each above the options to select the Overseer Matrix trigger. It looks similar to the weird UI bugs that showed up in the past with vampironassa and bacterial programming.

**Comment by NBKelly** [comment]
Hi, thanks for the report. Can confirm that I am able to reproduce this, thanks for the example case.
