### ISSUE TITLE
Dr. Lovegood breaks Always Be Running

### ISSUE THREAD

**Issue by tjvans** [mtgred/netrunner#7425]
Link to bug replay: https://jinteki.net/bug-report/2ba7ed6b-8671-4cc0-96a5-27514df3db86?b=0

Description:
[edit] After using Dr. Lovegood on Always Be Running, Always Be Running's "break subroutine" ability does not trigger when used and the click buttons become unresponsive.

**Comment by NBKelly** [comment]
ok, so the break ability *shouldn't trigger* because the card is disabled, but the other behavior was definitely due to a bug on our end with the newly reworked card-disable system.
I added a fix, which will probably be live next time we update jinteki.net

**Comment by tjvans** [comment]
Sorry, forgot to add that the card is otherwise used legally. So after using Dr. Lovegood, in subsequent turns the ability doesn't work.
