### ISSUE TITLE
Rogue Trading + Juli Moreira Lee Softlock

### ISSUE THREAD

**Issue by asphyxia-dev** [mtgred/netrunner#7426]
To replicate: 

Have 1 click left with Rogue Trading and Juli Moreira Lee installed.

Click Rogue trading without understanding you need 2 clicks to pay for a rogue trading action before you get the refund.

Cannot take actions through context menu, (in a situation where I couldn't /undo-click due to HQ run information)

Thanks

**Comment by NBKelly** [comment]
Fixed by #7431

**Comment by NBKelly** [comment]
Closed as completed via https://github.com/mtgred/netrunner/pull/7431
