### ISSUE TITLE
[Hush] Hush does not remove the ETR subs of Envelopment

### ISSUE THREAD

**Issue by ArminGitH** [mtgred/netrunner#7428]
Link to bug replay: https://jinteki.net/bug-report/f5961d05-c7a3-423c-8ecd-a48e11719d18?b=0

**Comment by NBKelly** [comment]
I believe we rolled back the update, not sure if that was before or after your issue.
I'll check in on it again once we've got everything figured out.

**Comment by NBKelly** [comment]
We rolled the update back forward and now this works again, so I'm closing this issue as completed.
