### ISSUE TITLE
Ashes cycle card images should use Remastered prints (modern templating/copyright)

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7429]
Chief examples:

Konjin currently in JNET:
![](https://jinteki.net/img/cards/en/default/stock/26109.png)
Konjin in NetrunnerDB:
![](https://card-images.netrunnerdb.com/v2/large/26109.jpg)

Cerebral Overwriter in JNET:
![](https://jinteki.net/img/cards/en/default/stock/26099.png)
Cerebral Overwriter in NetrunnerDB:
![](https://card-images.netrunnerdb.com/v2/large/26099.jpg)

Templating/terminology is improved and NISEI copyright is updated.

**Comment by NBKelly** [comment]
Closed as completed.
