### ISSUE TITLE
Kate's ability is triggered after a card is installed.

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#744]
While using Kate, you are unable to install a program or hardware unless you have the indicated number of creds on the card. (ex. You can't install Magnum Opus with 4 creds even though it's your first installation for the turn.) The game doesn't take into consideration Kate's discount until after the card has been installed and creds are removed.

**Comment by nealterrell** [comment]
It's just a UI issue. You can still install the card if you click it, it just won't have the normal yellow border that normally shows around cards you can play.

**Comment by JoelCFC25** [comment]
Can this one be closed?

**Comment by Saintis** [comment]
Could be closed and re-opened under clearer title referring to the lack of a visual effect.
