### ISSUE TITLE
Endless Hunger mistakenly break non-ETR subroutines

### ISSUE THREAD

**Issue by frankzgq** [mtgred/netrunner#7440]
![image](https://github.com/mtgred/netrunner/assets/23350107/4bfcba82-fe59-40b1-bc3d-c99461c89cfa)

Here is the figure. [Endless Hunger] says "Trash 1 installed card: Break 1 "[subroutine] End the run." subroutine."

But in the game above, I could use it to break all subroutines even if it is not ETR subroutine.

**Comment by NBKelly** [comment]
Yes, the restriction on breaking is not implemented. You can see that in the corner when you hover over the card, and in the chat box whenever the card is installed.
Just like when you're sitting down and playing at a table, you're expected to read the cards and pay attention to the board state.

**Comment by frankzgq** [comment]
> Yes, the restriction on breaking is not implemented. You can see that in the corner when you hover over the card, and in the chat box whenever the card is installed. Just like when you're sitting down and playing at a table, you're expected to read the cards and pay attention to the board state.

Thanks for the clarification. Appreicated it!
