### ISSUE TITLE
Invisible advancement counter

### ISSUE THREAD

**Issue by xiaat** [mtgred/netrunner#7445]
Link to bug replay: https://jinteki.net/bug-report/a00095fe-1c25-4adf-94cf-0d7d447db1ee?b=0
![634634](https://github.com/mtgred/netrunner/assets/133262510/c9cefc31-7837-433d-9b96-d71837a77368)
Hard to say if it effectively was there or not since the opponent used /counter to fix this

**Comment by NBKelly** [comment]
Hi, was this in the same game as the hearts and minds bug?
It sounds dumb, but I think that bug has the potential to set the advancement counters on a card to negative amounts.

**Comment by xiaat** [comment]
It was indeed. I actually thought about that, however the card in question wasn’t targeted by Hearts and Minds previously, which is why I had my doubts that maybe something else was going on. But it would make sense.

**Comment by NBKelly** [comment]
I just went back and checked the game log - turn 3 had a (fictional) counter taken from that card
> {"user":"__system__","text":"creditzathotmail started their turn 3 with 7 [Credit] and 4 cards in HQ.","timestamp":"2024-06-07T09:30:58.617"},
> {"user":"__system__","text":"creditzathotmail uses Hearts and Minds to move 1 hosted advancement counter from a card in Server 2 to a card in Server 3.","timestamp":"2024-06-07T09:31:11.121"}

So this one got solved with the other issue :100: 

Closed as completed via #7448
