### ISSUE TITLE
Zato city grid does not provide an opportunity to prevent the "when encountered" ability with airbladeX.

### ISSUE THREAD

**Issue by cablooshe** [mtgred/netrunner#7456]
https://jinteki.net/replay/81d8fa93-da7b-40db-9853-caac1e1b25af

(Runner turn 12 is the interaction)

Had a game where the runner ran the remote server that was defended by [Zato City Grid](https://netrunnerdb.com/en/card/33127) after having [airbladeX](https://netrunnerdb.com/en/card/34022) installed. 

Some additional details:
- Zato city grid was installed before airblades in the recorded game. Not sure if that changes any behavior if the installs are reversed.
- The subroutine in the recorded game was an "end the run" sub, other subroutines might have different behaviors but I haven't tested.
- From [the airblades netrunnerdb card page](https://netrunnerdb.com/en/card/34022) it seems like current Jnet ordering for Ob/Zato needs to be changed to fix this behavior? Currently what happens is you get a prompt to trigger zato, do the ob trigger, then choose the subroutine to fire on the trashed ice. I think due to this ruling, what it should be is:
    1. Corp gets a prompt to use zato, and presses yes.
    2. Corp chooses a subroutine to fire from the encountering ice
    3. Runner is given the opportunity to cancel with AirbladeX
      a. If they do, the ice is encountered as normal and not trashed
      b. If they do not, the ice is trashed as normal and the ob trigger happens, followed by the subroutine being fired.

**Comment by NBKelly** [comment]
Hi,

I'm not sure when I'll be able to fix this, but (this is primarily to remind me later so I don't have to look it up again) the correct procedure would be:
* The runner encounters the ice
* They choose to prevent the when-encountered ability
* The corporation is not given any prompt or choice at all

Bear in mind that each piece of ice essentially has the following text on it, and that you prevent everything to the right of "when the runner encounters this ice":
> When the Runner encounters this ice, choose 1 subroutine on it. You may trash this ice to resolve that subroutine.
