### ISSUE TITLE
Couldn't install a unique resource over an existing one

### ISSUE THREAD

**Issue by znsolomon** [mtgred/netrunner#7464]
Link to bug replay: https://jinteki.net/bug-report/62186fcd-a2ae-47c1-b42e-caad51da4a80?b=0

Description: Attempting to install a third class act over the second one.

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

**Comment by NBKelly** [comment]
I couldn't reproduce this bug.

But in the future, if this is an issue, you can just drag the already installed unique card to the trash first.
