### ISSUE TITLE
Team Sponsorship timing

### ISSUE THREAD

**Issue by StashAugustine** [mtgred/netrunner#748]
There's a small timing issue with Team Sponsorship. If you have two Team Sponsorships installed, it will prompt you to select both cards then prompt install both. This can cause trouble in NEH where you may want to install a card in a new remote, drawing a card, and then potentially install the new card.

**Comment by JoelCFC25** [comment]
Unfortunately this one falls into the ever-growing bin of items that can't be addressed until there is a way for the player to choose the sequence of simultaneously triggered effects. See #189, #309, #519, etc.

**Comment by queueseven** [comment]
This is an issue with non-blocking prompts. The first TS puts a prompt into the state, then the second TS puts also another prompt into the state. So you now have two prompts at the same time.

**Comment by nealterrell** [comment]
This could probably be resolved similarly to Daily Business Show. Use a `:once-key` so that only one TS triggers, then use recursive ability resolution a la Escher, where the second/third TS is only resolved once the server for the first TS is selected.

**Comment by nealterrell** [comment]
Fix submitted in #756.

**Comment by Apotropaeus** [comment]
The Bifrost into ABT with Team Sponsorship does not quite work right, since you can not install the cards discarded to archives by the Bifrost'd ABT. ABT + Team Sponsorship works, though.
