### ISSUE TITLE
Stats suggestion: "Credits by Click" would be better as "Credits by the Basic Action" (and same with "Cards Drawn by Click")

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7487]
Proposal:
• Change "Credits by Click" in end_of_game_stats to "Credits by the Basic Action"
• Change "Cards Drawn by Click" to "Cards Drawn by the Basic Action"
Reasons:
• Makes it unambiguous what it means (could be misinterpreted as "credits /per/ click" or something)
• Terminology of "by/using the basic action" already established by Sebastião's templating

**Comment by NBKelly** [comment]
I think that's a pretty good idea. Sooner or later we'll get around to it.
