### ISSUE TITLE
Clairvoyant Monitor is overly restrictive with token placement

### ISSUE THREAD

**Issue by marckubischta** [mtgred/netrunner#749]
Card text reads:
> If you and the Runner spent a different number of credits, place 1 advancement token on an installed card and end the run.

As per the related text on Tennin which reads `on a card` and [the Tennin rulings](http://ancur.wikia.com/wiki/Tennin_Institute) allowing advancement tokens to be placed literally on any card, Clairvoyant Monitor should similarly allow advancement tokens to be placed on any `installed card`, not just advanceable ones.

This was a total pain to keep track of in my Nisei Division / Clairvoyant Monitor / Trick of Light deck.

**Comment by JoelCFC25** [comment]
Thanks for the report. I bundled a fix for this into #747.

**Comment by marckubischta** [comment]
Awesome, thanks.
