### ISSUE TITLE
Proposal: add rez/play cost of cards alongside their names and influence

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7493]
![image](https://github.com/mtgred/netrunner/assets/83939/d630a2e2-8410-4a35-b892-188c53a6b3fe)
Like this ↑
This could make it a bit easier to distinguish in-faction cards at a glance using more than just their name - plus as a new deckbuilder I tend to check card costs quite a lot.

If you want to use that CSS, it's
```
  margin: 0px 4px;
  display: inline-flex;
  border-radius: 8px;
  width: 16px;
  height: 16px;
  background: #000;
  border: 1px solid rgb(203, 173, 7);
  justify-content: center;
  align-items: center;
  font-weight:bold;
```

Similar CSS can be made for rez costs by removing the border and replacing the background with
```
background: radial-gradient(black, transparent 80%);
```

**Comment by NBKelly** [comment]
That's a pretty neat idea.
