### ISSUE TITLE
Caprice

### ISSUE THREAD

**Issue by osiridecascioli** [mtgred/netrunner#75]
sorry for my english.
I was the runner, playing against Jinteki RP.
run on a server with 3 ICE
encountered and resolved the first.
the Corp rez Capice
I continue
passed the 2° and the 3°
the U.I. ask me if I wont to trash Caprice, without asking psy game
(the corp still have 6 credits)

**Comment by mtgred** [comment]
You have to click on Caprice to trigger the Psi game.

**Comment by osiridecascioli** [comment]
thanks for F.A. (Fast Answer:P ) the runner or the corp?

**Comment by mtgred** [comment]
The Corp. It basically act as Snowflake.
