### ISSUE TITLE
Chakana installed on a Djinn prevents advancement tokens

### ISSUE THREAD

**Issue by CZCuckoo** [mtgred/netrunner#750]
This may be related to the issue I had with hivemind. Opponent lost clicks, and text SAID it advanced, but card does not advance. I trashed my djinn (and the 2 chakana on top of it) on his turn, and instantly he could advance. No tokens were on any of my runner cards, chakana etc.

**Comment by CZCuckoo** [comment]
I am able to replicate this multiple times on different advanced agendas.

**Comment by JoelCFC25** [comment]
This should have been fixed with #671, but I don't believe it's deployed yet. There will be a big server restart coming this weekend.

**Comment by CZCuckoo** [comment]
Perfect. Thanks.

**Comment by nealterrell** [comment]
Confirmed that this is working on the dev branch which hasn't been pushed to the live server. Thanks for the report, the fix is coming this weekend :).

**Comment by CZCuckoo** [comment]
Wonderful. Thanks.
