### ISSUE TITLE
A Teia and Earth Station should not allow users to create server beyond their limit

### ISSUE THREAD

**Issue by francescopellegrini** [mtgred/netrunner#7503]
Asked a judge during EMEA and I got confirmation that both these ID should not allow the Corp to install a card in a new remote server if they have reached the max.

Currently there's an option to install in a new server and trash an existing one, if I remember correctly

**Comment by NBKelly** [comment]
As far as I can tell, "New remote" appears on the install list, but it doesn't do anything when you select it.

We should probably still see if we can fix that though.
