### ISSUE TITLE
Vera hosted on Cupellation prevents rez of another Vera.

### ISSUE THREAD

**Issue by plural** [mtgred/netrunner#7507]
Link to bug replay: https://jinteki.net/bug-report/7385f181-7a67-48ec-9cd3-216f225f5cc1?b=0

Description:

I had a Vera hosted on Cupellation and that prevented the rez of another Vera by the corp.  We tried /disable-card on the hosted vera to no avail.  I assume, but didn't test, that this is not specific to Vera, but to unique (maybe only previously rezzed) corp cards.

**Comment by NBKelly** [comment]
Hi, this is fixed by #7448 - we're just waiting on deployment right now.

**Comment by NBKelly** [comment]
Closed as completed via #7448
