### ISSUE TITLE
Replacement effects on runs don't trigger success state in game (datasucker, data leak, notoriety, quest complete)

### ISSUE THREAD

**Issue by StalkerB** [mtgred/netrunner#753]
If I run on archives and install Hades Shard when Successful Run comes up, it doesn't count as a successful run for the purposes of gaining sucker tokens or counting towards a successful run on that central.

**Comment by JoelCFC25** [comment]
I think we can fix this by manually swapping some stuff into `[:runner :register]` and `[:run :successful]`. I'll give it a shot...
