### ISSUE TITLE
Architect Deployment Test - and maybe others - install from the deck chat log issues.

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7549]
With the latest update, installing from the deck with Architect Deployment Test shows this interesting message.
![image](https://github.com/user-attachments/assets/55682328-bba0-4f14-9020-2060f4b3c270)
This behavior seems expected (until today, architect deployment test has been on a "the runner does not know which card is being installed" setting). However I asked Cephalopod Wizard about this and it seems like it might be getting an update that reveals the position of the card installed. 
**
![image](https://github.com/user-attachments/assets/851dadcd-42e7-4030-84e3-b5b06c4c9ed0)
**

Now I'm not saying that you should beat the rules team to the punch with implementing this but maybe in a few weeks you can circle back to this and see if it has been codified into the rules and implement it then.

**Comment by NBKelly** [comment]
Oh yeah, I copied the code from Stargate and forgot to change the number to 5. 

I actually preempted you with this, funny enough: #7544 - (also covers epiphany, psychokinetics, etc)
