### ISSUE TITLE
Tri-maf & Faust bugs

### ISSUE THREAD

**Issue by PinkWarrior** [mtgred/netrunner#760]
Played a few games and noticed that Tri-maf contact is triggering from hand when trashed with Faust or through net/meat damage. I've also noticed that fall guy asks me if I want to prevent resources been trashed from my hand in the same situations.

**Comment by JoelCFC25** [comment]
Thanks for the report. This was also submitted at #724--the fix is in and will be deployed this weekend.

**Comment by nealterrell** [comment]
#629 fixes Fall Guy when trashing by _dragging_ from hand, but that doesn't apply to Faust, which is the real problem card.

**Comment by JoelCFC25** [comment]
Yep, confirmed that in dev just now. Suffering net damage with Fall Guy in play and only resources in hand doesn't throw up the prevention prompt, but Faust does.

**Comment by PinkWarrior** [comment]
Ah sorry, I thought id seen fall guy doing it with both I must have been mistaken.
