### ISSUE TITLE
Cascade of warning messages softlocking the game after running through "Jua" last turn and Corp playing Public Trail

### ISSUE THREAD

**Issue by Schr0dinger** [mtgred/netrunner#7608]
I was playing a game in jnet as a runner. Corp turns began and he played Public Trail, then all of the sudden a cascade of warning messages appeared saying "you can't install (insert program name here) cause installing is locked". I run through Jua last turn, but it was not the first time running through that ICE and I had no problems before. I couldn't take the tag or do any action, not even access the in-game chat. I tried to f5, leave-reload-join, etc. Nothing worked and I got the warning messages still going on even in the general Chat. I attach two screenshots, from the game and the general chat. No replay could be saved as I couldn't access the chat to write the command.

![bug 01](https://github.com/user-attachments/assets/6deb7391-2b21-47bd-983f-a4861b609e6c)
![bug02](https://github.com/user-attachments/assets/a15c9c5d-3654-4ae0-9702-8b33167c5719)

PD: Sorry, first time reporting a bug. Apparently this bug was already reported https://github.com/mtgred/netrunner/issues/7433 :-S

**Comment by NBKelly** [comment]
No worries, this report has info the other one didn't have.

I think the screenshot is enough to tell me that simulchip is causing the issue (since the warnings are all for cards in the heap), so I actually have a path to recreating the bug now.
