### ISSUE TITLE
Tranquilizer doesn't name itself in its derez log message

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7609]
![image](https://github.com/user-attachments/assets/a7e86c2d-1bd6-42a2-bbe4-401b9595afa1)
As you can see, it just says "<player> derezzes <ice>" which is indistinguishable from this action being done manually. There also isn't a log message for incrementing the virus counters, either.

**Comment by NBKelly** [comment]
Not having log messages for the virus counters is (mostly) intended - there are so many irrelevant start of turn effects in the game that if everything like that got logged any useful information would get drowned out in noise.

I will change the derez part though.
