### ISSUE TITLE
Log: Matryoshka doesn't say how much cash was spent to activate its break ability

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7617]
![image](https://github.com/user-attachments/assets/a5328077-0c06-479a-babc-775353ec05f5)
As you can see, the message is borked. You can work it out by counting how many subroutines were broken, but it interferes with the log and makes it hard to scan for credit spending at a glance.

**Comment by NBKelly** [comment]
cost is displayed in the previous log message.

![matryoshka-log](https://github.com/user-attachments/assets/df5be7a8-36ee-4512-8af6-53d426a3a844)

**Comment by webbedspace** [comment]
OK…… but now that you mention it, why is the "turn facedown" cost listed as an effect? (Personally I think it should really just be one message.)

**Comment by NoahTheDuke** [comment]
Due to how our roles engine works, that's currently not possible.
