### ISSUE TITLE
[Description] Winchester's abilities are listed in the wrong order relative to the current official rules text

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7632]
![image](https://github.com/user-attachments/assets/fefb18df-7459-4a7a-ba6b-2006dd6277f4)
In Ashes Remastered, this ice's abilities were reordered for readability reasons like so:
![image](https://github.com/user-attachments/assets/1e4222d4-c252-4a82-a59f-0f2428bc58ce)
The text should be updated to reflect this ordering.

**Comment by NBKelly** [comment]
Sooner or later I'll update netrunner-data to use the current rules text for everything again. It'll probably be close to the dawn release, whenever that happens to be.

**Comment by NBKelly** [comment]
Turns out I actually did that within the last year (when plural decided to use the fancy quotes), and we just never ran fetch again. It's correct on jinteki.net now.
