### ISSUE TITLE
Two bugs with Team sponsorship

### ISSUE THREAD

**Issue by heydevhey** [mtgred/netrunner#765]
HI guys,

Awesome site!  I've noticed two bugs using the new team sponsorship:

1- I have two pad campaigns in the archives.  I score a breaking news while two team sponsorships are installed and rezzed.  I'm prompted to install a card from archives and click PAD Campaign both times.  I'm able to install the first time, but the second time the install fails and no cards are installed.

2- I have 2 cards in archives. One faceup pad campaign and one face up pad campaign.  When I score a breaking news with a Team sponsorship installed, i can choose to install a pad campaign, but am not able to choose weather to install the face down pad in archives or the face up one in order to make make the runner check a card.

Hope this makes sense.

Devin

**Comment by nealterrell** [comment]
Thanks for the report! We have addressed the first issue in #756, but the second won't be addressed. I'll see how easy it will be; probably we'll make it repeat card titles for duplicate cards, and they'll be in the same order they appear in archives.

**Comment by nealterrell** [comment]
Alright, that was easy. I am applying the logic to Interns, Crick and Architect as well.

**Comment by HongkongKoma** [comment]
I can report another bug: Opponent has 2 Gang Signs installed, me 1 Team Sponsorship. When I score, the Gang Signs fire before I can choose a card to install. Since it's my turn, I might want to install an agenda from HQ first - before Gang Sign triggers.

**Comment by JoelCFC25** [comment]
Yet another example of #309, I'm afraid--until blocking prompts are developed, there isn't a way to properly order multiple effects firing from a single triggering event. It's a priority!

**Comment by JoelCFC25** [comment]
Both Gang Sign and Team Sponsorship are now manually triggered, so players can properly sequence everything when multiple copies of each are in play.
