### ISSUE TITLE
Overinstall Boomerang caused an error

### ISSUE THREAD

**Issue by Meathirwastaken** [mtgred/netrunner#7662]
Link to bug replay: https://jinteki.net/bug-report/322e261e-0e2b-4db8-bb10-fb02cdc67226?b=0

Description:

Tried to overinstall a (stranded) Boomerang with a second one against Pradivost on a HQ ICE whilst taking a credit from Paladin Poemu when the error message appeared in the top right and it would not take the credit or install the Boomrang. I tried undoing and not taking the credit from Poemu but the error message still appeared. Using /trash to manually trash the Boomerang let me install the new one.

**Comment by NBKelly** [comment]
I think I figured out a fix, but in the mean time you can always drag the installed card to the trash first if this issue happens to you again.
