### ISSUE TITLE
Haarpsichord Studios: + Franchise City result in game crash

### ISSUE THREAD

**Issue by lorion42** [mtgred/netrunner#767]
If the corp creates two new servers one with an agenda and one with Franchise City. On the runners turn he runs on the agenda server, while the corp rez Franchise City. Result: the runner can't click on the steal button. Franchise City is scored before the agenda could be stolen. There is no way to go to standard game flow again - the code seems to be in a loop. If the agenda is for exampe TGTBT, the runner gets a tag for each mouse click but he can't get TGTBT into his scoring area.
This happend 3 times in a row. There are turns where Franchise City works as it should, but with this bug a deck with both cards is unplayable.

**Comment by nealterrell** [comment]
This will crash if the asset is in a lower numbered server than the agenda. Obviously we can't expect you to always put your cards down in one order, but we are aware of the issue and working on a fix. Thanks!
