### ISSUE TITLE
Implement run "memory" or allow players to save bulk run effects

### ISSUE THREAD

**Issue by aswan89** [mtgred/netrunner#768]
While its great that Jinteki.net has discretely implemented things like server and ice position and all the timing events that go along with it, it would be great if players had the option to "remember" the outcome of a run on a server that has not changed since the last run made. When starting another run, each side could review the final outcome of the last run made against the server and agree to skip directly to right before the successful run phase.

I know this would be enormously difficult to detect automatically since there are any number of paid abilities that could fire during a run, but it would greatly simplify runs on servers like R&D that don't change very often, especially when Ice can't be rezzed.

**Comment by queueseven** [comment]
We have a feature in the pipeline that allows you to set your credits directly, e.g. `/credit 12` will set your credits to 12. So when you know a run will be successful if you pay X for your ice breakers, you could just use this command to adjust your credits by X.

I agree a third button (something like `to innermost`) would make the game faster in combination with the new feature.

**Comment by aswan89** [comment]
That will be a good start but would need a command to jump past the ice to be worthwhile. Otherwise you're still clicking back and forth for the timing windows. Being able to mutually agree to skip the windows without hitting the chatbox would be ideal.

Date: Mon, 28 Sep 2015 08:37:23 -0700

**Comment by queueseven** [comment]
Yeah, that's what I wanted to say. A button to directly jump past all ICE.
