### ISSUE TITLE
Charlotte and La Costa ordering broken

### ISSUE THREAD

**Issue by postinternetsyndrome** [mtgred/netrunner#7686]
There are two older issues about this that are closed as fixed, but I'm seeing this behavior regularly (don't know if it's a regression or if the fix just never worked).

Charlotte should be able to get a counter from La Costa and immediately use it. As it is, you're forced to manually trigger the ability after mandatory draw, which introduces some angle shooting opportunities since you see the mandatory draw before you trigger Charlotte.

https://github.com/mtgred/netrunner/issues/7372
https://github.com/mtgred/netrunner/issues/7306

**Comment by NBKelly** [comment]
I added another fix for it, which should go out in our next release (whenever that is). In the mean time, you can always click on either of the two cards to resolve their abilities.

**Comment by postinternetsyndrome** [comment]
That's what I've done. However, clicking on la Costa before turn begins will still have it trigger automatically too, which forces you to place an extra counter (the ability isn't optional).
