### ISSUE TITLE
Feature Request: Referee Mode

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#769]
Similar to how spectator mode works, this would probably be a second checkbox in game creation "Allow Referee(s)". 

A referee would be like a spectator, but could see player hands and unrezzed cards, and perhaps could interact with the board (dragging cards, etc) as if they were a player. While this could be used for a more serious tournament setting, I imagine it being mainly used as a more intimate spectator mode (between friends, for example) or as a helpful tool for teaching other players the game.

**Comment by Merlin8000** [comment]
At first glance I didn't care for this idea but after a second read I have to +1 this assuming that it included required approval from both players.

**Comment by Saintis** [comment]
This is partially possible by allowing spectators to view the players' hands.

**Comment by JoelCFC25** [comment]
There is now an option to let spectators see hidden cards, so I think that's close enough to call this fulfilled. Not really wild about ever letting spectators move things around and interact with the board state.
