### ISSUE TITLE
Games Remain Open After Abandoned

### ISSUE THREAD

**Issue by bryanpost** [mtgred/netrunner#770]
Sorry if this has been caught before, but it seems that many games stay open after they are abandoned or over, with no option to close them out. This leads to many open games slowing down the service.

![image](https://cloud.githubusercontent.com/assets/8421608/10154114/0a46219a-6629-11e5-9bad-e195568f00e8.png)

**Comment by nealterrell** [comment]
![image](https://cloud.githubusercontent.com/assets/10083341/10155867/0f10326e-662f-11e5-9b0c-8d4f250fe4de.png)

Sorry for the snark, but it's all related, and it will just take a little time to figure out what's wrong :).
