### ISSUE TITLE
Feature suggestion: Language in chat

### ISSUE THREAD

**Issue by HongkongKoma** [mtgred/netrunner#771]
Dear dev team,
how about a small list in the "New game" settings with checkboxes showing flags: english (default), french, german, swedish, italian, russian, spanish. So when I set up a match I can enter which languages I speak. For example, if I check "german" maybe a german speaking player joins me and we can chat in our language and say "Guten Tag" and "Bratwurst". 
Does not affect gameplay, it's just improving comfort on an awesome site and may help mixing up metas.

**Comment by JoelCFC25** [comment]
I think the goal so far has been to limit the game creation UI complexity. For the time being, I would either sort this out with the opponent in the lobby prior to starting the game, or add it to your game name somehow, e.g.  "HongkongKoma's game:  Lang: DE, FR, IT, ESP"  or similar.

**Comment by zaroth** [comment]
How about just naming the game "Guten Tag Meine Freunde"? ;-)

**Comment by queueseven** [comment]
Thanks for your feature suggestion.

But as JoelCFC25 already said: that would increase the UI complexity for not much gain. I think I speak for everyone when I say we won't implement this.
