### ISSUE TITLE
Game incorrectly goes to "[Corp] has no further actions" after Corp rezzes ice

### ISSUE THREAD

**Issue by the-all** [mtgred/netrunner#7726]
When rezzing an ice in paid ability window 2b of the approach ice phase, the chat indicates that the Corp has no further action. However, the paid ability window should go on as normal.

An example where this is important is the interaction between Arruaceiras Crew and Border Control. In the approach ice phase, the Corp has the chance to rez and then trash BC to end the run, that is before the runner gets to trash it with Crew in the Encounter Ice phase.

Another example: Ari + Physarum Entangler + Mavirus.

**Comment by xiaat** [comment]
@NBKelly This option currently only exists in-game and not in general settings. Also, something to consider is maybe having it off by default, it's been causing some minor confusion on jnet today due to the corp suddenly having to click an extra button they haven't in years. 😃

**Comment by NBKelly** [comment]
Small learning curve :joy:
