### ISSUE TITLE
Game Frozen : Cannot begin turn

### ISSUE THREAD

**Issue by itskando** [mtgred/netrunner#7728]
Link to bug replay: https://jinteki.net/bug-report/6a3a905d-7314-4cef-a277-02356684e77a?b=0

Description:

Issue occurred after a Gain cred, Gain cred, SarswatiID action to install Spin Doctor with advance, followed by /undo-turn agreed upon by both players.

Clicking Start Turn does nothing.
Reloading page / Leaving + Reentering private game does nothing.

**Comment by NBKelly** [comment]
Hi, `/undo-turn` is bugged in the last release. We've already set up a fix (#7719), which should be deployed soon in our next release.

**Comment by NBKelly** [comment]
Closed as completed via #7719
