### ISSUE TITLE
Additional pronouns request

### ISSUE THREAD

**Issue by Anzekay** [mtgred/netrunner#7743]
Could the pronouns xi/xir be added? Same ones that Esa, the anarch runner, uses.

Also, would it be possibly to add a line in the settings menu, under the pronouns dropdown, with a link to this github and a note to post an issue here to request additional pronouns? Would greatly help folks whose pronouns aren't current options know that they are more than welcome to request them being added.

**Comment by NBKelly** [comment]
Sure, no worries.

**Comment by Anzekay** [comment]
Thanks mate, love ya! <3

**Comment by NoahTheDuke** [comment]
we should probably change it to a text field.

**Comment by NBKelly** [comment]
That would be convenient, but I think it would be abusable. Adding this in on request is a nice easy chore right now.
