### ISSUE TITLE
The supplier install does not trigger the installed card's "start of turn" trigger.

### ISSUE THREAD

**Issue by BakyraBA** [mtgred/netrunner#775]
For example, if you are using the Supplier to install "Data folding" or "Underworld Contact" or "Daily Cast", the cards should still be able to trigger "start of turn" conditions, as, well, it's still "start of turn".

**Comment by queueseven** [comment]
Actually, no. The implementation is right. The "when your turn begins" trigger triggers only once, for all cards. If a card is not installed at that point in time, it will not trigger that turn.

**Comment by queueseven** [comment]
Related ruling: https://boardgamegeek.com/article/11686680#11686680
