### ISSUE TITLE
Startup Banlist and Agenda Requirement enforcement

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#7754]
see: https://nullsignal.games/blog/startup-balance-update-24-09/

Banlist shouldn't be put through until after next weekend.

https://github.com/NoahTheDuke/netrunner-data/pull/57

Summary:
- [x] Tributary banned
- [x] Pharos Banned
- [x] Creative Commission banned
- [x] #7755

**Comment by LLBlumire** [comment]
Heya! The article mentioned having it be effective immediately for online play, is there a reason to delay it until after next weekend, other than to give time for implementation

**Comment by NBKelly** [comment]
next weekend was in reference to the one that just passed.
Basically, pushing a release hours before, or during, and active tournament is extremely dumb, and I'm not going to sabotage one (or multiple) tournaments because somebody in nsg says "apply instantly"

**Comment by NBKelly** [comment]
Closed as completed
