### ISSUE TITLE
Password Resets Not Working

### ISSUE THREAD

**Issue by ahshah** [mtgred/netrunner#778]
When I request a reset of my password, I get an email with a link. When I click the link it takes me to a reset form. When I fill out the form, the game logs me in and I'm on my way playing. 

If I then clear my cookies, or use a secondary browser, I cannot login with the new password.

**Comment by domtancredi** [comment]
Hi @ahshah 

That's odd. Does the previous password work?

**Comment by ahshah** [comment]
I've reset the password to the same password, about four or five times. The new password doesn't work, and neither does the old (if I am recalling it correctly). 
If it helps, I login with my gmail account: caffein@gmail.com

**Comment by domtancredi** [comment]
I've tested this locally and it works (tracking this in the database, and then matching to the bcrypt generator from here: https://www.bcrypt-generator.com/ 

Are you logging in with your *username* or your *email address*? 

What is your username?

**Comment by ahshah** [comment]
I've been logging in with my email this whole time. It works when I login with my username (eclipse). Sorry about wasting your time!
