### ISSUE TITLE
Street Peddler game log typo

### ISSUE THREAD

**Issue by xiaat** [mtgred/netrunner#7782]
> xiaat uses Street Peddler to install Hippo, lowering its install cost by 1 . Stimhack and Sure **Gambleare** trashed as a result.

Missing a space.

**Comment by xiaat** [comment]
> lowering its install cost by 1 .

While we're at it, there shouldn't be a space after "1".

**Comment by NBKelly** [comment]
Neat. Fixed the first. Second one is fine, the credits token doesn't get picked up by your browsers copy function.
