### ISSUE TITLE
stats info on games

### ISSUE THREAD

**Issue by jaimefps** [mtgred/netrunner#7793]
As a player, I would benefit from more detailed stats from the Stats tab. I would like to see `cards accessed` broken down by centrals or maybe by unique cards accessed. I'm not sure if the way data is shown at the end is by unqiue cards or just touched in general, even if you touch the same card more than once.

**Comment by NBKelly** [comment]
We already have unique cards accessed, which discounts touching the same card more than once (if it moves from one zone to another, it's a different card though - and it discounts cards in archives). It's in the bottom right-hand corner.

The other one, cards accessed, it's exactly what it says. 

![unique](https://github.com/user-attachments/assets/36d3397a-2558-442f-8d7b-853f68254d2f)

**Comment by jaimefps** [comment]
im blind ,haha, thanks

**Comment by NBKelly** [comment]
no worries, it's a lot to parse :)
