### ISSUE TITLE
Feature Request: Have a timestamp next to log messages.

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7799]
![image](https://github.com/user-attachments/assets/c61d358b-0783-4985-b897-16044a0471f2)
![image](https://github.com/user-attachments/assets/42ad6ac2-b16e-456d-a866-0b2caa5c8ffc)

Lifted straight from pokemon showdown, this feature would allow the users to see what time the logs on a battle were printed.

**Comment by NBKelly** [comment]
That sounds pretty neat, but I'm not sure how to make it look pretty.

Sooner or later I'll figure it out, if somebody else doesn't first.
