### ISSUE TITLE
Future Perfect and Gabe Hq runs

### ISSUE THREAD

**Issue by sonatinas** [mtgred/netrunner#78]
First click HQ run with Desperado and Lamprey out, access future perfect, lost psi game but ended up in a loop of keep on clicking successful run and the run wouldn't end. Desperado, Lamprey, and Gabe's ability i think hit. Not sure what happened but was just stuck in some HQ run limbo after losing Psi game.

**Comment by sonatinas** [comment]
In another game (reina vs tennin) runner accesses future perfect and is about to do psi game. runner plays the game but the result isn't shown until later because the system makes the runner "jack out"(but really doesn't )and accesses other cards in HQ.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The problem has been fixed and will be deployed with the next server update.
