### ISSUE TITLE
Facedown cards in Archives are visible to spectators

### ISSUE THREAD

**Issue by Smashman** [mtgred/netrunner#781]
When spectating a game, clicking on Archives shows the cards in a similar fashion as it does to the Corp when they view their Archives. (Slighty greyed out)

**Comment by Saintis** [comment]
Confirming that this is still an issue.

**Comment by JoelCFC25** [comment]
Line 455 of `gameboard.cljs` looks like the cause. Currently it reads: 

'{:ref "popup" :class (when (= (:side @game-state) :runner) "opponent")}'

I think it should be: 

`{:ref "popup" :class (when-not (= (:side @game-state) :corp) "opponent")}`

**Comment by JoelCFC25** [comment]
Correction--it's line 461 that needs to be changed.
