### ISSUE TITLE
Foundry & Accelerated Beta Test don't behave like ruling says they should

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#782]
here's the ruling: http://ancur.wikia.com/wiki/Accelerated_Beta_Test_%26_The_Foundry_Interaction_Ruling

Have to do it manually as the game automatically trashes the non-ice cards

**Comment by JoelCFC25** [comment]
When #772 goes live at the next restart, this will become much easier. Right now when you install ice from firing ABT it doesn't trigger The Foundry at all--the new version will. You'll still have to shuffle back in any trashed cards and remaining uninstalled ice from the play area if you choose to use The Foundry ability on the first ice install, however. But it should be much more workable.
