### ISSUE TITLE
Add helper functions for having one of multiple, or all of a set of subtypes

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#7821]
Writing this so I don't forget later

We've written
```Clojure
(and/or (has-subtype? x a)
        ...
        (has-subtype? x z))
```

enough times that they might as well be helper functions for clarity, like:

```Clojure
(defn has-a-subtype? x [a...]) ;; this will get used a ton
(defn has-every-subtype? x [a...]) ;; not sure how much this will get used
```

**Comment by heyshiloh** [comment]
@NBKelly https://github.com/mtgred/netrunner/compare/master...heyshiloh:netrunner:nr-7821-multi-subtypes

here is helpers + tests, but i am having trouble finding places in the code where this would easily refactor existing logic. Do you have examples of the above pattern that I could test refactor in?

**Comment by NBKelly** [comment]
I might have imagined a need for the has-every-subtype one (it's still good to have), but for multiple subtypes (this will be used for some dawn cards too):
* Az McCaffery
* Asmund Pudlat
* Adept/Savant
* Laser Pointer
* Hammer
* Hagen
* Foxfire
* Executive Search Firm
* Restoring Face
* [Unregistered S&W '35](https://netrunnerdb.com/en/card/05039)

**Comment by heyshiloh** [comment]
@NBKelly i'll take a look at refactoring these with the method i wrote and let you know

**Comment by heyshiloh** [comment]
- passing tests for the first few

I see that greek philosopher suite holds logic in `break-multiple-types` so i will be a bit more meticulous on testing those

**Comment by NBKelly** [comment]
Ah, no need to touch those ones if it doesn't make the code simpler

**Comment by heyshiloh** [comment]
it should make the brewak-multiple function simpler, its just separated out logic so i will have to make sure im not breaking anything

**Comment by heyshiloh** [comment]
@NBKelly 

> Ah, no need to touch those ones if it doesn't make the code simpler

This ended up being the case, it is a different situation than others because it applies break quantity per subtype rather than just checking if any subtype

https://github.com/mtgred/netrunner/compare/master...heyshiloh:netrunner:nr-7821-multi-subtypes

Here is the diff for now. not trying to bombard you with PRs so let me know if you have time for this and I will send it over

**Comment by NBKelly** [comment]
Make as many PR's as you want as fast as you want :) Worst case scenario is we just look at them later.

**Comment by NoahTheDuke** [comment]
one time @francescopellegrini  opened like 22 one line prs in a row lol. i reviewed and merged every one. don't worry about us.

**Comment by heyshiloh** [comment]
@NBKelly @NoahTheDuke You two are great, I still aim to be mindful about wasting time or generating too much noise 😅
