### ISSUE TITLE
Installing programs mid-run leads to broken game-state

### ISSUE THREAD

**Issue by Larrea-Mon** [mtgred/netrunner#7824]
You are playing Hoshiko. Currently, you are not in a run. you click the Unity in your hand to install it. Egads! you are over MU. no worries, jnet  simply stops you from playing it, you never even lost the credits or the click. You hit "done". You trash a Leech and try again, this time succesfully installing Cleaver.

You are playing Arissana. You make a run on a remote defended by a Wall of Static. You look at your hand and click on Arissana. A little menu pops up and you select Cleaver. Oh no! you don't have MU so you can't install Cleaver. You drag a Coalescence to the heap and click "done". The cleaver is not installed. Confused, you click on arissana to find out that she doesn't activate again. You have spent your one use of arissana, misplayed and you're going to have to /undo-click. This sucks.

This also happens with SMC and simulchip and any other sources of installing programs that are not the basic action.

**Comment by NBKelly** [comment]
hmm, you can actually click to select whatever programs you want to trash then click done (which is I think what the prompt directs you to do).

I'll see if I can make it work if the player just drags the stuff, but it'll still rely on them counting right.

**Comment by Larrea-Mon** [comment]
Really? I've never even thought of doing that. 😓.

**Comment by NBKelly** [comment]
I think Noah added it a few years ago? Learned memory is so hard to stop. I think I definitely took months to realize and start using it.
