### ISSUE TITLE
Info bounty with no mark

### ISSUE THREAD

**Issue by NBKelly** [mtgred/netrunner#7831]
You can force info bounty to give you credits if you have no mark
* Breach any server
* Install info bounty
* Run any server and then jack out

**Comment by heyshiloh** [comment]
@NBKelly can this be reproduced with any runner id or is there a specific id that this affects?

**Comment by heyshiloh** [comment]
![Screenshot 2024-10-20 at 2 16 58 PM](https://github.com/user-attachments/assets/13f4f619-b60e-4748-afa1-6c0854ebf739)

Testing with runner is: `419`

- ran remote
- install info bounty
- ran remote + jack out 
`Unable to Reproduce`

![Screenshot 2024-10-20 at 2 22 03 PM](https://github.com/user-attachments/assets/409668e1-4af7-4576-bf5b-904fab6b5f94)
- ran central
- install info bounty
- ran remote + jack out
`Unable to Reproduce`

**Comment by NBKelly** [comment]
Oh, my instructions slightly were wrong before. Check the unit tests in the linked PR, they have an actual repro case.

**Comment by heyshiloh** [comment]
oh i see i see. for some reason I read past the PR on the page as well. Thank you for your response
