### ISSUE TITLE
Mirrormorph paid ability window ruling

### ISSUE THREAD

**Issue by heyshiloh** [mtgred/netrunner#7836]
There are several instances of paid ability window enforcement that should eventually be addressed (`see Lat`)

This one came up today in a game. I think there are people that play this ability incorrectly in paper all of the time, but maybe a warning like rashida will suffice in lieu of paid ability window rework at this time

https://netrunnerdb.com/en/card/26031

---
If the Corp clears Employee Strike with one of their three actions (or between), does MirrorMorph trigger?

Yes.

If the Corp’s third action is to install a Calvin B4L3Y, can they rez Calvin and use its action with MirrorMorph?

No, there is no window to rez cards between completing your third action and resolving MirrorMorph’s ability.

Is there a paid ability window for the Runner to install Clot with Clone Chip after the Corp’s third action, or can the Corp immediately use the bonus action to place the final advancement counter on an agenda and score it in the next paid ability window?

There is no paid ability window between completing the Corp’s third action and resolving MirrorMorph’s ability. Clot must be installed before the third action (or in the middle of it, if the action includes a nested timing structure with a paid ability window) to be able to stop the Corp from scoring with their extra action.

---

**Steps to Reproduce**
- As `Mirrormorph`, play a card that can be rezzed and clicked on your third click
- choose gain click
- rez and click to trigger the card's ability

**Expectation of ruling**
If the card was not rezzed before the mirrormoph trigger, you will not be able to select that action with the mirrormorph ability due to there not being a paid ability window

**Comment by NoahTheDuke** [comment]
Jnet doesn't support paid ability windows and likely never will.

**Comment by heyshiloh** [comment]
@NoahTheDuke  This seemed to be the case, which is why i was saying maybe we could add an alert like we have with rashida

**Comment by NBKelly** [comment]
Nah, this one's fine to leave. If we start adding rulings for cards, that's a pretty big can of worms.

**Comment by heyshiloh** [comment]
makes sense
