### ISSUE TITLE
Error Warning Bricking match and Bryan Stinson not working correctly with Ultraviolet Clearance

### ISSUE THREAD

**Issue by RivitheGuide** [mtgred/netrunner#7837]
So firstly, for the Error Warnings:
One was definitely my fault. I was trying to rez an asset I already had a copy of. Clicked it a whoooole bunch of times. Wasn't until later the error message popped up, and they wouldn't go away, and it froze my whole game, and I had to leave and start a new game.

The other, was me using Efficiency Committee to gain clicks, and then the game warning me I can't advance even though I wasn't trying to advance anything. The warning would loop, appearing and disappearing over and over again, and caused me to be unable to perform any actions. Same as the other, had to leave the entire match.

As for Bryan:
Upon using his effect with Ultraviolet Clearance, nothing happened. Unless I am reading/understanding the effect incorrectly, the additional cost of 2 clicks should not matter, and thus it should play the card. It did not however do this. Initially I thought his effect was bugged or not put in properly, but later learned that it's probably due to the additional cost text, as using Bryan to play IPO functioned as intended.

My entire experience with the Stinson Reversed precon deck was ruined by these literally game breaking bugs. I do hope you get the chance to get back to me in some way shape or form about these issues and that they can be resolved, and I also hope I provided adequate enough detail for you to attempt to recreate these situations in hopes of finding said resolutions to these issues.
I wish whoever reads this well and I apologize in advance if I didn't do enough searching either for active posts regarding these issues.

Sincerely, someone trying to enjoy this game with their friend.

**Comment by NBKelly** [comment]
Hi,

There's a fix for the effcom one already done that will be included in our next release which should also make the rezzing asset one also not happen as well.

I figured out what was wrong with stinson and put a PR up too (for the time being, you can just add clicks before firing it if you need to)
