### ISSUE TITLE
Media Blitz doesn't work 

### ISSUE THREAD

**Issue by maferri24** [mtgred/netrunner#7846]
Link to bug replay: https://jinteki.net/bug-report/91b3a86f-f460-4051-9f7c-90ab2ffd8366?b=0

Description:

When New Angeles Sol triggers after a stolen agenda, I choose Media Blitz as the Current I want to play.  At that point, the pop-up for Media Blitz asks me to select an agenda in the opponent's score area.  I see the crosshair-pointer and I select the agenda, but then the pop-up dissapears before I can click the "done" box.   The game is now frozen.  at that point, we had to "undo-click" and NOT pick an agenda (keeping track of it outside of the game automation and using manual overrides when necessary)

**Comment by NBKelly** [comment]
What agenda were you trying to target?

**Comment by maferri24** [comment]
Sorry... didn't see your question until just now.  Seems like you fixed it already?  Wow.  For the record, the agenda was "Restructured Datapool"

**Comment by NBKelly** [comment]
Yeah it turned out to be something easy to spot. Fix still needs to wait on our next patch though (hopefully within a week).

**Comment by maferri24** [comment]
Very gratifying as a player to see this level of attention.  Respect.
