### ISSUE TITLE
Casual format doesn't allow 3x AstroScript

### ISSUE THREAD

**Issue by rgdelato** [mtgred/netrunner#7851]
Apologies if I've misunderstood how the "Casual" format is supposed to work, but I tried adding a deck from 2015 and it's not allowed for casual play due to having 3 copies of AstroScript:

Is there a different format I should be using for playing these 2015 decks?

<img width="655" alt="Screenshot 2024-10-30 at 4 31 37 PM" src="https://github.com/user-attachments/assets/c4b80db5-61f6-45e1-85bb-420e04c85363">

**Comment by NBKelly** [comment]
You should still be able to play in the casual format with that list, it's just illegal for the deckbuilding requirements (since astro got erratad instead of just having some wierd banlist update).

**Comment by rgdelato** [comment]
@NBKelly Sounds good. Thank you! I'll close out this issue.
