### ISSUE TITLE
Jailbreak trigger fizzled

### ISSUE THREAD

**Issue by xiaat** [mtgred/netrunner#7855]
![455u546](https://github.com/user-attachments/assets/311453c9-c14a-438f-a3c6-59505c30445f)
Something to do with Tatu/Asa interaction?  
Usernames are redacted for purposes of smurf safekeeping. I can share the replay privately with a dev on Discord/Slack

**Comment by NBKelly** [comment]
hmm - seems like we just don't have a message for jailbreak. Can you check the replay and confirm a card definitely wasn't drawn?

I'll update jailbreak to actually print a message for drawing the card.

**Comment by xiaat** [comment]
You're right of course, I should've had a better look at my own screenshot. The triggers all happened as they should. A lot of stuff went down at the same moment (Tatu swaps and Cupellation etc) so I skimmed through the log to take account of it and was confused by the lack of mention of jailbreak in the log
