### ISSUE TITLE
Trick Shot is able to run remote when Crisium Grid is on R&D

### ISSUE THREAD

**Issue by 7flames** [mtgred/netrunner#7867]
Link to bug replay: https://jinteki.net/bug-report/343d4403-cac6-4ff9-9e41-bcdac6caed45?b=0

Description:

Trick Shot is able to run remote when Crisium Grid is on R&D

**Comment by NBKelly** [comment]
That's the correct behaviour

**Comment by 7flames** [comment]
> That's the correct behaviour (there are too many words on that card)

Oof. Good thing my opponent won that match anyways.
