### ISSUE TITLE
Can't stop surfing

### ISSUE THREAD

**Issue by cwoac** [mtgred/netrunner#789]
Attempted to use surfer (on a 4 deep remote), had the following issues:

* After swapping two pieces of ice (one ressed, one not), it didn't deduct cash
* the 'done' button did nothing - couldn't stop surfing!
* I was (for a while) unable to surf deeper - all I could do was swap the two pieces back and forth. After a while, I figured that click ice, click done click ice allowed me to surf one deeper (problems above remained), but when I tried to go deeper, it swapped me back with the outside (an illegal swap)

Further details of game state:
the ice was unrezzed as I approached it, it was hive. Opponent was blue sun, I was kit, had yog+corroder installed and plenty of cash.

**Comment by JoelCFC25** [comment]
So far I can't reproduce this in my dev environment. Were there any other extenuating circumstances you can think of, such as any of the ice over that server hosting something?

**Comment by albatar21** [comment]
i got the same problem, encounter 2 times. after thinkering or paintbrush an ice, i surf (my credit was deducted), i can swap with the next unrezzed ice, but button done didn't work (clic on it but never disapear), and i can't do anything (can't use breaker), only swap the 2 ice again and again...

my browser is chrome v45

**Comment by cwoac** [comment]
None of the ice was hosting anything. It was my first run of the turn as kit (I don't know if kit's typing is enforced or not).
I'm also running chrome - version 45.0.2454.101 m

**Comment by queueseven** [comment]
The enforcing of ice types is a new feature. This seems to be a problem with surfer

**Comment by gandrasch** [comment]
Happened to me too.

**Comment by JoelCFC25** [comment]
I've had several people report it and in some cases supply me with a screenshot--to this point I simply cannot reproduce it in dev at all, so I'm still a little mystified as to the root cause. A key piece of information will be if Paintbrush usage is involved in all the cases where this is happening.

**Comment by cwoac** [comment]
I had paintbrush installed, but I had not used it. I was modifying the ice's type with Kit's ability though.

**Comment by JoelCFC25** [comment]
Yep, that is definitely useful information.

**Comment by JoelCFC25** [comment]
Even though I can't yet reproduce it, I wonder if changing Surfer's subtype check in the `:req` to `(has? (get-card state current-ice) :subtype "Barrier")` would do the trick.

**Comment by eedok** [comment]
I can get it to happen pretty consistently

Make a game as NEH vs Kit, get the NEH side to make a server that's an asset, Tollbooth as the inside ice and wraparound as the outside ice

on kits turn have her install surfer and run the server, have NEH rez the Wraparound and have kit use surfer on it to push it back, and then try to hit the done button

**Comment by JoelCFC25** [comment]
Yeah, I tried this precise scenario as you've laid it out and it works perfectly in my dev environment--hence the frustration with pinning down the cause.

**Comment by albatar21** [comment]
i try under firefox, and it work perfectly, the bug is under chrome, it bug 100% under chrome (3 times with 3 different set up) and not under firefox for me.

**Comment by queueseven** [comment]
Well that is very strange

**Comment by tarmann** [comment]
Happened to me as well. With Kit, first round swapping for an unrezzed piece of ice.

**Comment by albatar21** [comment]
maybe it's not a bug with surfer, because the last time, corpo have swap manually the ice (i haven't use surfer), and the bug was the same, i click on my menu "continue" but nothing happend, and all menu are disabled (credit, click etc..). So the bug is maybe link to the manipulation of ice under chrome browser during run.

**Comment by dlrowb** [comment]
I think the issue is a simple copy and paste bug.

cards-programs.clj:506 (update-ice-strength state side (cons :corp (:zone cice)))
should be
(update-ice-strength state side cice)

This change will fix the problem.

**Comment by JoelCFC25** [comment]
Well spotted! This should probably just change to `update-all-ice state side` so that both the ice being surfed and the one you swap with get strengths updated (if necessary).
