### ISSUE TITLE
LOG: Kill Switch says "accessed" when it's triggered by score

### ISSUE THREAD

**Issue by webbedspace** [mtgred/netrunner#7896]
![image](https://github.com/user-attachments/assets/63c08f1b-40c4-46a7-a938-71ef22986578)
See picture. Message should read "reveal that they scored Lightning Laboratory" instead of "reveal that they accessed".

**Comment by NoahTheDuke** [comment]
The existing message is correct. Kill Switch says "While the Runner is accessing an agenda in R&D, they must reveal it."
