### ISSUE TITLE
Certain cards that alter ICE strength don't trigger until after a run

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#790]
So far I have noticed this issue with the agendas "Superior Cyberwalls" and "Encrypted Portals", as well as the ice "Quicksand".

With the agendas, it seems that the strength increase to ice does not kick in until the runner has completed a run (sometimes the strength suddenly kicks in mid-run, and sometimes it only kicks in for the server currently being run on).

Quicksand's strength from new power counters doesn't kick in until after the runner is done encountering it. For example, if the runner encounters a fresh, newly rezzed Quicksand, you can click it to add a power counter, but its strength remains at 0 while being encountered. As soon as the runner clicks to continue (or jacks out), the strength suddenly correctly adjusts to where it should be for the power counter you added.

**Comment by JoelCFC25** [comment]
These cards should call `update-all-ice`, which they currently are not doing. Should be an easy addition, thanks!
