### ISSUE TITLE
Double security testing not working

### ISSUE THREAD

**Issue by ValentinHirschi** [mtgred/netrunner#792]
When playing two security testing on the same server (archives for example), it works fine the first time a run is initiated on the archives (automatically not accessing the cards and gaining 2), but when initiating a second run on the archive (within the same turn), then I access card instead of having the replacement effect of the second security testing taking place.

**Comment by Objelisks** [comment]
The replacement effect only happens during the **first** successful run on that server. You can only get at most one payout from a single server no matter how many Security Testings you have.

**Comment by ValentinHirschi** [comment]
Sorry, you are of course right. My bad. See, jinteki.net teaches me stuff. Great website, keep up this awesome work!
