### ISSUE TITLE
Franchise city doesn't respect Film Critic

### ISSUE THREAD

**Issue by cwoac** [mtgred/netrunner#793]
A ressed franchise city gets auto-added to the score area before the runner has a chance to host on film critic and stop it.

**Comment by nealterrell** [comment]
I believe this was a hack to deal with crashing issues when scoring Franchise City causes a server to "disappear" and breaks the existing attempt to steal an agenda. We have a fix for that issue coming soon and can implement the proper behavior for Franchise City now. Thanks for the report!
