### ISSUE TITLE
When the runner boosts their link to fight a trace, they do not lose the credits

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#80]
When handling traces, a corp boosting their trace strength removes the specified number of credits from the corp's pool, as expected.  However, when the runner increases their link strength, the maximum they are allowed to boost by is set by their credit pool, but choosing a value does not actually remove that many credits from the runner's pool.

Easy to work around this by manually decreasing credits in the runner's pool as long as one of the players notices what happened.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It's fixed now.
