### ISSUE TITLE
Snoop encounter

### ISSUE THREAD

**Issue by GrantZilla1979** [mtgred/netrunner#803]
There is no reveal of the Runner's hand when they encounter Snoop currently.
In addition, the tracer subroutine is not listed as an option upon click - only "add hosted power counter" and the effect of the power counter.

**Comment by JoelCFC25** [comment]
Thanks for the report. I don't think we want the reveal to happen automagically on encounter (look at the problems Quicksand had). But yes, this card needs some work--submitting shortly.

**Comment by queueseven** [comment]
Yes, all the encounter abilities should be manually.
