### ISSUE TITLE
When a server ceases to exist mid-run a new server takes its place instantly

### ISSUE THREAD

**Issue by dummiesday** [mtgred/netrunner#805]
Here's the situation:

- I had two unprotected remote servers. Server (0) had Jackson installed and Server (1) had another asset installed.

- The runner had chosen Server(0) as their target for one of their copies of Security Testing.

- The runner ran Server(0) (Howard) to get the two credits from Security Testing.

- I rezzed Jackson Howard and used its ability. Server(0) ceased to exist, which should have made the run neither successful nor unsuccessful, as usual.

- However, for some reason, the runner did get the two credits. I strongly suspect this is because as soon as Server(0) ceased to exist, Server(1) took its place and became Server(0).

Is this possible? Could you please have a look?

I'm attaching a screenshot of the log in case it helps. Please note that the screenshot was taken at a later stage and the board position doesn't reflect the situation of the issue.

Thanks!

![bug howard](https://cloud.githubusercontent.com/assets/14167840/10417243/4efb66b2-702c-11e5-90c1-9622e4a7d501.png)

**Comment by queueseven** [comment]
This has been fixed, but the fix is probably not deployed yet. 

With the fix remote servers will keep their name (so server 1 won't automatically become server 0 when the original server 0 ceases to exists).

**Comment by dummiesday** [comment]
Excellent! Thank you very much for your hard work!
