### ISSUE TITLE
Neutralize All Threats interacts poorly with point-reducing Ambushes

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#809]
Neutralize All Threats triggers a trash as soon as a trashable card is encountered.  This causes weird interactions with Shi-Kyu and News Team.  In both cases the card is trashed, and then the runner is given the prompt regarding whether to take the non-point effect, or to put it in their score area as an agenda worth -1 point.

However, because the card has already been trashed, it apparently can't be found if the runner selects the -1 point option.  They still get the effect (their point total is reduced), but the card remains in Archives where it may trigger again.

**Comment by anathomical** [comment]
Possibly related to #303

**Comment by JoelCFC25** [comment]
Shi.Kyu works now in this situation as of #914, and I'll have a PR with the fix for News Team soon.
