### ISSUE TITLE
Order of Sol should fire upon instillation if the runner goes to 0 for the first time in the turn

### ISSUE THREAD

**Issue by ChickieDrake** [mtgred/netrunner#812]
As per the ruling on the card:

If the runner has exactly 2 credits, and hasn't been at 0 credits during the current turn and installs Order of Sol, does it immediately trigger and give the runner a credit?

Lukas: You would get the credit, since this is the first time you are at 0 credits for the turn. “Have” does imply an ongoing state (you remain in that state as long as you have 0 credits), so you could draw a distinction between “going to” as a one-time event.

http://ancur.wikia.com/wiki/Order_of_Sol_Triggering_on_Install_Ruling

Order of Sol does not currently fire in this situation on Jinteki.net.

**Comment by JoelCFC25** [comment]
Thanks for the report--fix coming in #811.
