### ISSUE TITLE
Feature request :  Free textfield in deckbuilder

### ISSUE THREAD

**Issue by t-lor** [mtgred/netrunner#814]
Hey

First of all, thanks for this awesome site !
I have a small request.

Is it possible to add a small textfield into the deckssection builder ?
Sometime i just want to add a small reminder or sourcelink  to a net-decked deck.
Its not a big problem, but it would be nice and relatively simple to add i gues.

**Comment by NoahTheDuke** [comment]
NetrunnerDB has this functionality
