### ISSUE TITLE
Drive By not interacting with cards

### ISSUE THREAD

**Issue by anyothername** [mtgred/netrunner#815]
Drive By isn't allowing the runner to select a card in the remote server. The menu to choose a target for Drive By comes up correctly and the cost to play is correct, but nothing occurs when the runner clicks on the card.

**Comment by JoelCFC25** [comment]
This card (and the others broken by the new way remote servers are structured) will be fixed when #811 is merged and deployed.

**Comment by anyothername** [comment]
Got it, thanks so much!

**Comment by JoelCFC25** [comment]
Should be deployed now.
