### ISSUE TITLE
24/7 News Cycle doesn't seem to fire anymore

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#817]
The trashing an agenda part works but then the effect doesn't seem to happen

**Comment by JoelCFC25** [comment]
It's missing a `:choices` entirely. Did this card ever work?

**Comment by eedok** [comment]
maybe not, marked as finished in the document

**Comment by JoelCFC25** [comment]
I'm stumped on this one. I tried adding `:choices` to effectively make it the operation version of scoring a Bifrost Array. Bifrost works just fine but 24/7 doesn't.

**Comment by JoelCFC25** [comment]
I have it now.
