### ISSUE TITLE
Ice moved to Runner's hand with Parasite

### ISSUE THREAD

**Issue by anyothername** [mtgred/netrunner#819]
This is a strange one that came out of a pretty unique situation, so it may not actually need to be addressed. What happened was the runner installed a Parasite on a piece of rezzed ice (Mother Goddess on R&D as the innermost piece of ice), but wanted to actually install on a different piece of ice. They took back the play, but when they moved the Parasite back to their hand, the Mother Goddess came with it. 

Then when the runner clicked on the ice, they were given the menu to install as if they were a corp, though clicking on R&D did not install it on my server. When they trashed the ice, it ended up in my Archives. We took some screenshots below.

http://i.imgur.com/Xo8iQ9q.jpg - Full board state
http://i.imgur.com/6qv9IHE.png - Install ice menu as runner

Seems like it might not be a regular occurrence, but thought it was worth bringing up.

**Comment by JoelCFC25** [comment]
I'm going to close this for now. If anyone can reliably reproduce it we can open it back up.
