### ISSUE TITLE
Laramy Fisk ability doesn't work after a run on a remote server

### ISSUE THREAD

**Issue by Merlin8000** [mtgred/netrunner#820]
If Laramy Fisk runs on a remote server before the first time running on central server, his ability doesn't activate.  

As a work around, the runner can jack out so the corp can take a click to draw and then run back in, with the corp allowing the runner back through to the same point at the successful run.

**Comment by JoelCFC25** [comment]
Thanks for the report. I have this fixed and will probably submit it tonight. We keep uncovering more cards that were affected by the remote server restructuring (Gagarin Deep Space and Bishop will also be getting fixed).

**Comment by JoelCFC25** [comment]
Should be deployed now.
