### ISSUE TITLE
Leela and post-agenda-score Corp abilities

### ISSUE THREAD

**Issue by justinliew** [mtgred/netrunner#822]
Leela's ability fires immediately after the Corp scores an agenda. If something like Team Sponsorship fires, Leela should be able to push the unrezzed card installed by Team Sponsorship since TS is a Corp ability which takes precedence since it's the Corp's turn.

**Comment by nealterrell** [comment]
This can at least be worked around by not selecting a Leela target until Corp resolves Team Sponsorship, since the prompts are for different players. But yet another example of poor resolution of multiple effects.

**Comment by JoelCFC25** [comment]
#834 will make both Team Sponsorship and Leela Patel manually triggered, which will let the correct resolution order play out.

**Comment by JoelCFC25** [comment]
Leela and TS are both manually triggered now, so players are able to sequence them properly.
