### ISSUE TITLE
Utopia Shard + Sneakdoor Beta

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#824]
if you get into HQ through Sneakdoor Beta you can't click Utopia shard to install it for free like you can with a successful run on HQ

**Comment by JoelCFC25** [comment]
Interesting...can't reproduce this so far. Were there any other cards in play that might have been relevant? I Sneakdoored in dev just now and hit an agenda after "bouncing" to HQ and was able to click Utopia Shard in hand to install it for free.

**Comment by eedok** [comment]
You can't access cards and install Utopia Shard in the same run, it's an instead of accessing cards

**Comment by JoelCFC25** [comment]
Understood, but the install did work using the method that was developed for it. I suppose that was only because a steal prompt came up--if it hadn't been an agenda it would've blown right past the "pause" where the Runner is meant to click the Shard in hand.

**Comment by erbridge** [comment]
Maybe make HQ access work in the same way as R&D, so you get a prompt showing the accessed card.

**Comment by zaroth** [comment]
Related to #2016.
