### ISSUE TITLE
Dedicated Response Team firing when it is trashed and the runner is tagged

### ISSUE THREAD

**Issue by lynkfox** [mtgred/netrunner#826]
The run is considered successful at 4.4, and trashing is done at 4.5

DRT does not seem to be applying the 2 meat damage if the runner makes a successful run on it while they are tagged. 

Happened to me in two games, but haven't taken any evidence yet. If it happens again I'll try and post a screenshot.

**Comment by JoelCFC25** [comment]
Dedicated Response Team triggers when a successful run **ends**--i.e., step 5 in the timing chart rather than 4.4. So a tagged Runner who runs a DRT with 3 or more credits will trash it before DRT can fire, resulting in no meat damage being dealt. Of course, any DRTs in _other_ remotes will fire.

**Comment by lynkfox** [comment]
ah my bad. I thought it was different, so my fault! Never mind, never mind! :)
