### ISSUE TITLE
Manual Virus Counters

### ISSUE THREAD

**Issue by spoonfunk** [mtgred/netrunner#83]
Hi!

I was wondering if it would at all be possible to include a function that allowed the user to add or subtract virus counters from virus manually. I ask about this because it occurred to me that even though the new cards that manipulate virus tokens would be implemented eventually, we have no way of anticipating in what ways this mechanic may take shape in the future and it seemed a sensible function to include so cards could become playable in a manual fashion even though they had not been implemented yet.

Thanks for you time and all the work you have been doing on this site btw.

**Comment by Agnate** [comment]
I think this could be achieved by adding a menu option for all cards to add 1 counter (at least as a temp measure).

**Comment by eah13** [comment]
+1

**Comment by mtgred** [comment]
Surge, Incubator and Virus Breeding Ground have been automated.
