### ISSUE TITLE
Have triggered effects manually resolve

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#832]
To help with the order of triggered effects, could they be made like Fisk's ID ability(When they're triggered it says so in the chat log, then you click to resolve them)?

This will give us the ability to choose the order which they resolve, and fix some things that currently cause issues(like having multiple gang signs out)

**Comment by nealterrell** [comment]
We are probably going to port several important cards in this direction while we work on engine support for doing it manually. Gang Sign in particular, but also Leela. @JoelCFC25 is working on this already.

**Comment by JoelCFC25** [comment]
So far I have modified Leela Patel, Gang Sign, and Comet to work like this--see #834. If you think of any others please post them!

**Comment by JoelCFC25** [comment]
I'm going to close this one for now because we have addressed the highest-profile problem cases. If new ones crop up, please comment on this issue again or create a new one and we'll take a look!
