### ISSUE TITLE
Enable/Disable Identity Console Command

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#833]
Would be a nice feature to have when undoing a play or working around a bug (Like rescoring an agenda as PE due to a faulty 24/7 News Cycle)

**Comment by Saintis** [comment]
Could bind the new `enable` `disable` functions to user commands.

**Comment by Kubik161** [comment]
@NoahTheDuke This issue should be probably closed. We have `/undo-click` that takes care of original issue.
