### ISSUE TITLE
importing 'Director Haas Pet Project' in text deck list

### ISSUE THREAD

**Issue by zerotonin** [mtgred/netrunner#836]
Hello 
while importing a text-file deck list from netrunnerdb.com, the agenda 'Director Haas Pet Project' is falsly imported as 'Director Haas' the asset. [Link to both cards] (http://netrunnerdb.com/find/?q=director+haas) This is not very important. Anyway great works folks, I am very impressed, by Jinteki.net.

cheers

Bart

**Comment by JoelCFC25** [comment]
As a workaround, type directly into the decklist area instead of using the Add Cards tool. Typing this should add it:  `1 Pet Project`

**Comment by JoelCFC25** [comment]
As of earlier this week, NetrunnerDB has a new "Export to Jinteki.net" option--if you use this for decks containing Director Haas' Pet Project, it's parsed correctly now when pasted here. 

![image](https://cloud.githubusercontent.com/assets/10407969/12326691/f5951b02-ba97-11e5-854c-a30197c51bba.png)
