### ISSUE TITLE
Menus need a close button

### ISSUE THREAD

**Issue by beamdogcody** [mtgred/netrunner#838]
Things that suck to misclick on as there's no way to get rid of them once you click them
-Street Peddler
-Clone Chip
-Self-Modifying Code
-Same Old Thing

What's worse is the impulse to close the menu is to click the card, which bring up the menu a second time without a close button

**Comment by lostie** [comment]
:+1:

**Comment by beamdogcody** [comment]
looks like this is a duplicate of #85

**Comment by nealterrell** [comment]
We're working on this one.

**Comment by nealterrell** [comment]
We recently added cancel options for the vast majority of menus. If you are asked to Select or Target a card directly, click Done to cancel the action. If you have a list of options in a list, there should be a Cancel button to do the same.
