### ISSUE TITLE
Archived Memories reveals the name of the retrieved card in the console when it is face down

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#84]
It appears that there is no conditional logic on Archived Memories to tell if it should publicly name the card being retrieved or not, and it defaults to doing so.  This means that in cases where the card is face-down, and theoretically unknown to the runner, it is revealed as it is pulled into HQ.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed and will be deployed on the next server update.
