### ISSUE TITLE
Feature// Event rooms  

### ISSUE THREAD

**Issue by shielserido** [mtgred/netrunner#841]
The feature is a “room” under the play tab, in which event participants could assemble, and that a TO could create games for paired players within.  The paired players could join up the game just as in the regular room, and the advantage would be participants could find their game with relative ease, without disrupting regular pick-up-games at the same time.

Another advantage of an event room would be that the TO could make announcements into the the chat feed of each individual game.  This would surely be disruptive to players not playing in the event, but would be a fantastic tool for announcing round starts or finishes, and general tournament announcements like time in round.

**Comment by Kubik161** [comment]
@NoahTheDuke This is now obsolete with new tournament support. Can be closed?
