### ISSUE TITLE
Impossible to install Harbinger since latest update

### ISSUE THREAD

**Issue by Ivan0xFF** [mtgred/netrunner#846]
The update that was last deployed fixing the spelling of Harbinger has made the card impossible to install via any means(from hand, via Haley's ability, via SMC, via Clone Chip, etc). Clicking on it from hand does nothing, using a card effect to install it causes the card effect to trigger and nothing to be installed. It also displays no card art.

**Comment by mtgred** [comment]
Thanks for reporting the issue. It has been fixed.
