### ISSUE TITLE
Scoring Breaking News while Forger is in installed should still remove up to 2 tags

### ISSUE THREAD

**Issue by haplesshero13** [mtgred/netrunner#849]
It appears that if you score Breaking News while Forger is installed, it doesn't remove 2 tags (the runner, of course, declined to use Forger to remove these tags since they go away automatically).

**Comment by JoelCFC25** [comment]
Were there any other cards in play that could have impacted this situation? I tried it just now in dev and it worked how you'd expect--scored the BN, the Runner (I was using Geist) with Forger installed simply clicked "Done" when prompted about tag prevention, then when the Corp click End Turn the 2 tags went away.

**Comment by haplesshero13** [comment]
I'll have to try it out again. Unfortunately I didn't screenshot it or anything.

**Comment by haplesshero13** [comment]
Just kidding, I have no idea how to use the website. LOL
