### ISSUE TITLE
Some odd behaviors for activated ability selection menus

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#85]
A number of cards, when activated, bring up a target selection menu (Self-modifying Code and Clone Chip are examples of this).  If you change your mind, or clicked accidentally, there is no apparent way to dismiss this menu.  You must complete the action to get the menu to go away.

Further, clicking on the target card multiple times seems to bring the targeting menu multiple times, stacking them visually on top of each other (such that only one is visible at a time), but all triggered menus require resolution before access to the basic actions menu will be granted again (required for things like ending turns).

Note that it will actually break game-state in some ways as it resolves multiple times.  Allowing, for instance, the installation of two copies of a card that you only have one copy of as an available target.

**Comment by mtgred** [comment]
It's indeed problematic. I will try to find a way to handle both issues.

**Comment by JoelCFC25** [comment]
In the case of Clone Chip specifically, it has been changed in #863 to use the card targeting system, which will let you just hit Done with no effect if you change your mind after popping it.
