### ISSUE TITLE
Haarpsichord Studios - runner can steal more than one agenda if he accesses multiple agendas in archives

### ISSUE THREAD

**Issue by Shadowseeker** [mtgred/netrunner#853]
In a game I played against Haarpsichord i was able to steal more than one agenda in the archives.

**Comment by nealterrell** [comment]
Which agendas in particular?

**Comment by nealterrell** [comment]
I believe this is because NetrunnerDB recently corrected the title of the card in their database to "Haarpsichord Studios: Entertainment Unleashed" (it was previously listed as just "Haarpsichord Studios"). Our code uses the old name and will have to be updated. Thanks for the report.

**Comment by Shadowseeker** [comment]
I believe there were 4 in archives: TBT,Breaking News, exploda palooza and quantum predictive model.
