### ISSUE TITLE
Shi.Kyū should provide a null option, preventing it from being taken as -1 point

### ISSUE THREAD

**Issue by StalkerB** [mtgred/netrunner#862]
As per the ruling found here - http://ancur.wikia.com/wiki/Shi.Ky%C5%AB - bidding 0 is not the same as not bidding. If the corp does not bid it cannot be taken.

Relevant for Data Dealer.

**Comment by JoelCFC25** [comment]
I'll have this one taken care of soon--it still won't prevent wonkiness when the Runner trashes it before the Corp finishes deciding, unfortunately.

**Comment by JoelCFC25** [comment]
Fixed at #914.
