### ISSUE TITLE
Turntable & Agenda Counters

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#867]
Here's what happened: 

The corp scored a House of Knives and used it once, so 2 counters remaining.  Then I stole a second HoK from R&D and swapped it with the corp's.  I got the HoK with 2 counters in my score area, but the new HoK in the corp's area has 3 counters when it should have none.

It seems when Turntable swaps agendas, it treats the agenda it pushes into the corp's score area as if it were just scored (or at least grants agenda counters as if just scored)?

**Comment by JoelCFC25** [comment]
Thanks for the report. My first attempt at re-enabling the agenda swapped back to the Corp was to call `card-init` on it, but that is not going to work--any agendas that get counters added to when scored are going to gain them, even if they've already been sent. Back to the drawing board...
