### ISSUE TITLE
Subliminal Messaging

### ISSUE THREAD

**Issue by mmychal** [mtgred/netrunner#87]
This card should either create a reminder to tell you it can be put in your hand when the runner doesn't make a run or just automatically go into your hand at start of turn.

Right now, at least you can put it into your hand by manually pulling it back from Archives.

**Comment by mtgred** [comment]
I feel adding a reminder gives an edge to the Corp compared to how Subliminal Messaging is played in real life game. Lukas also indicated that memory is part of the game. In that spirit, i will just leave it to the Corp to remember to take it back.
