### ISSUE TITLE
Chakana + Cyberdex virus suite

### ISSUE THREAD

**Issue by DavePickles** [mtgred/netrunner#875]
I advanced an NAPD 4 times whilst my opponent had 2 copies of chakana and a hive mind with 3 or more counters on it,rezzed and purged virus counters with the cyberdex virus suite, but was then unable to score the NAPD. No menu popped up when clicking the agenda to score it

**Comment by JoelCFC25** [comment]
My first hunch is that Chakana is missing a `:purge` event hook that would fire `update-all-advancement-costs`. I'll dig into it.
