### ISSUE TITLE
Chronos Protocol and Hokusai Grid

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#876]
I was playing Chronos Protocol, and when the runner hit a rezzed Hokusai Grid my ID's "reveal and trash" prompt appeared to them, not me. (After talking it through with my opponent, he described his hand and I chose which card to throw out - then the report appeared in the chat to show he'd used the Chronos ID dialog to trash it.)

Other cards that cause net damage during the runner's turn (eg. Fetal AI) do work as intended with Chronos, so I'm not sure if this problem is limited to just Hokusai Grid.

Additional info:
Hokusai Grid was installed in a remote server, no other upgrades or assets in that server.
Runner ID was Chaos Theory, no damage prevention abilities in play.

**Comment by JoelCFC25** [comment]
This one will be easy...the `:prompt` needs `:player :corp` added.
