### ISSUE TITLE
Parasite Gaining Counters

### ISSUE THREAD

**Issue by Skeskrske** [mtgred/netrunner#877]
Parasite seems to be gaining multiple virus counters at start of the runner's turn.

What happened: 
My runner opponent installed Parasite onto a Swordsman. It was installed from the runner's grip, cost paid from their credit pool. No Grimoire. At the start of their next turn, the Swordsman was insta-trashed from strength 2.

**Comment by JoelCFC25** [comment]
Still trying to track down the offending commit...you said the Parasite was installed from his Grip, but was there a chance that specific copy had previously been in play, trashed, and then brought back to his hand with Deja Vu or similar?

**Comment by JoelCFC25** [comment]
Never mind--figured out that I broke it with #871. Still working on a solution...

**Comment by Skeskrske** [comment]
No worries. Fwiw I was pretty sure my memory of events is correct, but can't be certain now.  I'll test the fix when it arrives.
