### ISSUE TITLE
Invalid decks can be used

### ISSUE THREAD

**Issue by percomis** [mtgred/netrunner#884]
I don't know if this is on purpose or something overlooked, but players can use invalid decks (out-of-faction agendas, less cards than required and overspending influence are the ones we tested).

**Comment by JoelCFC25** [comment]
While I don't think we want to prevent starting a game when an invalid deck is loaded (it's incredibly useful for testing), I did manage to alter the game lobby code to do this: 

![image](https://cloud.githubusercontent.com/assets/10407969/11186660/45d0829c-8c48-11e5-9c16-de5ae0c0eb87.png)

What does everyone think of this idea? If you're playing an unknown opponent you can either use this as a sign to bail from the game or talk it through with them, but on the other hand you could still play draft format with someone you know.

**Comment by percomis** [comment]
Sounds cool, I think it's a perfect solution.

**Comment by sjohnc** [comment]
I'd prefer to keep invalid decks so that fun modes like draft and other fan made formats can be ran in this system.
