### ISSUE TITLE
Unplayable lag

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#89]
Tried out this web app for the first time, but there was 30-45 seconds of lag in between each action and chat message, making it essentially impossible to play.

The app looks good, though. Keep it up!

**Comment by mtgred** [comment]
Jinteki.net is currently running on a very limited server. When there are 8+ games, there are sometime periods of lags of 5+ seconds. With 12+ games, there are frequent periods of very long lag.

I have some ideas about optimisations to reduce the load on the server. I'm also in the process of looking for some faster hosting solution.

**Comment by mtgred** [comment]
The website is now running on a faster server. There should be less lag now.

**Comment by Agnate** [comment]
Woo woo! So excited for this! :D

**Comment by eah13** [comment]
@Agnate there is still lag at times but I've had good games with 30+ games running simultaneously.  Can this issue be closed? (aiming for a little cleanup of issues in the repo)

**Comment by Agnate** [comment]
Sure, you can close it. To be fair, most of the time I've seen 30+ games is when 50% of them are crashed servers where someone dropped out or something, but it's okay to close the thread. :)
