### ISSUE TITLE
Public Agendas incorrectly "firing" when tokens are placed (not advanced)

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#898]
All 3 of the Weyland public agendas have special abilities that trigger when they are advanced, but these abilities should NOT fire when advancement tokens are placed on them through other means that don't specifically say "advance the agenda". Currently I've noticed this working incorrectly with Early Premiere + Oaktown Renovation and Hollywood Renovation, but it may also be similarly broken with Space Camp, Trick of Light, Matrix Analyzer, Shipment from SanSan, and Shipment from Kayuga.

**Comment by JoelCFC25** [comment]
I think this could be fixed by modifying the `add-prop` function to accept an optional key `placed` and then not trigger the `:advance` event if `:placed true` is passed in...
