### ISSUE TITLE
Ice installed to protect servers that have had ice deleted from them install in the incorrect order

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#9]
If ice are deleted from a server (either from Parasite or to save on install costs), the next piece of ice installed to that server appears in the innermost slot rather than the outermost slot.  This appears to be the case no matter how many ice are on the server, and also seems to happen only to the first piece of ice as deleting 3 ice from a 4 ice server, and then installing two more results in the first installed ice appearing in the innermost slot, but the second ice appearing on the outermost slot.

**Comment by mtgred** [comment]
The issue has been solved.
