### ISSUE TITLE
Media Blitz not gaining agenda text

### ISSUE THREAD

**Issue by AlvazHall** [mtgred/netrunner#900]
No action once played.  Display's "select agenda to gain text" but unable to select agenda or click on Media Blitz to activate.  Trying to use with Mandatory Upgrades when scored by the runner.

**Comment by JoelCFC25** [comment]
Media Blitz is not implemented at this time. Check the link on the Github front page for a (mostly) up-to-date implementation status of the card pool.

**Comment by justinliew** [comment]
https://github.com/mtgred/netrunner/pull/910
