### ISSUE TITLE
Apocalypse triggers "if trashed" effects for runner cards

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#901]
When Apocalypse fires successfully, it is supposed to trash all installed corp cards and turn all runner cards facedown. While the latter should cause the original cards to become uninstalled, it explicitly does NOT trash them. 

Certain cards like Gang Sign, Rolodex, and Tri-Maf Contact have significant penalties that occur when they are *trashed*, and these penalties are all currently firing off automatically when they are turned facedown. I'm not sure if this also occurs with effects that cause runner cards to leave the board through other means, such as Archangel, but it's worth investigating.

**Comment by JoelCFC25** [comment]
It's because the `move` function is calling `desactivate` on cards headed to `[:rig :facedown]`, which in turn is firing the `leave-effect` if the card has one. We just need to block that for this case.

**Comment by JoelCFC25** [comment]
I think I have a fix for this, but since I've been guilty of breaking things inadvertently a lot lately, I want to test it more thoroughly.
