### ISSUE TITLE
Haarpsichord and Hades Shard

### ISSUE THREAD

**Issue by yang573** [mtgred/netrunner#902]
If the runner uses Hades Shard on the corp's turn, s/he can only access agendas if s/he stole one during his/her previous turn.

**Comment by JoelCFC25** [comment]
I can't reproduce this. Hades Shard was modified recently--have you (or the opponent) done a forced refresh of the site since Wednesday. 

However, I was able to steal _multiple_ agendas by using Hades Shard against Haarpsichord, so that's an error that needs to be investigated.

**Comment by JoelCFC25** [comment]
I reverted to the way Hades Shard was before I did any modifications to it and found that it was also capable of stealing multiple agendas from Haarpsichord then, too--so this has been a bug waiting to be discovered for quite awhile.
