### ISSUE TITLE
Separate prompt for entering 1.2/start of turn triggers

### ISSUE THREAD

**Issue by jannn** [mtgred/netrunner#904]
Equivalent to the 1.1 window, I wish we'd get a separate prompt to enter 1.2 after starting our turn because it comes up in every game with Spark (rezzing drip econ assets to fire the ID ability for this turn, but still get the dosh in 1.2). Not sure if it's worth the additional clickthrough for all players since it's irrelevant in the vast majority of matchups, just something to consider. Kind of related to #705.

**Comment by GordonsBeard** [comment]
Can it not be rezzed right before hitting "Start Turn"?

**Comment by JoelCFC25** [comment]
Keep an eye on the discussion in #282--a new system for "when your turn begins" handling is coming soon.
