### ISSUE TITLE
Chronos Protocol Trash Menu Stuck

### ISSUE THREAD

**Issue by anyothername** [mtgred/netrunner#907]
Ran into an issue with Chronos Protocol's ID menu getting stuck. The board state was I had a Hostile Infrastructure rezzed. The runner used Maker's Eye to run R&D, leaving four cards in hand. They hit a Snare, which I fired. Before I could choose the card to discard with Snare and Chronos' ability, they trashed it. This made another net damage fire because of Hostile and trash a card from their hand before I could use Snare's ability. After that, none of the button's on my menu worked. The runner tried adding back the cards to their hand, but I still couldn't trash anything to get out of the menu.

**Comment by JoelCFC25** [comment]
Unfortunately there's nothing that can be done about this right now until there is a global solution for blocking Runner trashing until the Corp has concluded all optional abilities or made all the decisions generated by any given triggering event. The only way to get the correct outcome from this scenario is for the Runner to hold off on trashing the Snare! until the Corp is done--but there's no way to know in advance that you need to do this unless you've seen the problem crop up before. 

See #886 for a bit more discussion on this issue.

**Comment by anyothername** [comment]
Got it, thanks so much! Just played out a second Chronos game and it went fine with me asking the Runner to hold off.

**Comment by nealterrell** [comment]
Fix submitted in #1059.

**Comment by JoelCFC25** [comment]
Deployed today!
