### ISSUE TITLE
Full player-setup code triggers on mulligan

### ISSUE THREAD

**Issue by anathomical** [mtgred/netrunner#91]
I noticed this one when testing with Valencia Estevez.  When a player mulligans, the full player-state setup code seems to run, setting their credits to 5, their handsize to 5, and so on.  This can result in effects from the other player's ID being reset.

In this case, if the corp is playing against Valencia Estevez, they begin with one bad publicity as expected.  However, if the corp mulligans, this bad publicity goes away and their starting values are reset.  If, after this, Valencia Estevez also mulligans, her text seems to be checked again, re-applying the bad publicity.

In the short term, this isn't a huge deal, but the vagaries of mulligans means that unless players understand the underlying cause for this behavior, it appears largely random.  At the moment, I believe that the only ID that effects the other player's starting state (as opposed to the ID player's state) is Valencia Estevez, so this problem shouldn't be widespread at this point.

**Comment by mtgred** [comment]
Thanks for reporting the issue. The mulligan code will be updated to handle the Valencia case.
