### ISSUE TITLE
Philotic Entanglement for zero still triggers CP's ID

### ISSUE THREAD

**Issue by Amphiprison** [mtgred/netrunner#913]
When playing as Chronos Protocol, scoring Philotic Entanglement while the Runner has no agendas in their score area will still trigger the Chronos Protocol ID, effectively doing 1 net damage although no net damage should be done.

Thanks much!

**Comment by JoelCFC25** [comment]
Thanks for the report--a simple `:req` on Philotic to make sure there are 1 or more stolen agendas should do the trick!
