### ISSUE TITLE
Can't seem to drag cards to trash [on a laptop NOT a tablet)

### ISSUE THREAD

**Issue by Amphiprison** [mtgred/netrunner#917]
As the Corp, I find that I cannot drag cards in play or in my HQ to Archives or R&D.  The cards can be highlighted, but not actually moved.  The Runner can drag and trash my cards without issue.

Caveat:  I find that this generally happens not during the first game I play on jinteki.net, but the second or afterwards.  Perhaps a memory leak of some kind?

SPECIFICATION 12/7/15:  Using Chrome.  Also, bug hasn't reproduced itself since 11/27/2015.  Might have been resolved by another fix.

**Comment by nealterrell** [comment]
What browser? Dragging is known to not work on Internet Explorer or Edge.
