### ISSUE TITLE
Multiple calls to callback functions?

### ISSUE THREAD

**Issue by finnbar** [mtgred/netrunner#919]
Parasite seems to give -2 strength per token, and Medium seems to give two extra accesses per extra token. Furthermore, Underworld Contacts triggers twice per turn, and John Masanori gives two free cards on a successful run. Is there some place where callbacks are being run twice in the code by mistake? In the case of Parasite and Medium, neither of them gain more tokens than expected, they just seem to have a greater effect than usual.

(sorry if these issues are unrelated and I've filed them in the same Issue)

**Comment by JoelCFC25** [comment]
It will be investigated, but it's a holiday weekend despite the fact that this one is almost certainly my fault, I can't get to it until Monday at the earliest.

**Comment by finnbar** [comment]
That's OK, don't worry about it! Have a good weekend. :)
Also, while I remember, during these games all of the mentioned cards were hosted (Underworld and Masanori on Off-Campus Apartment, Medium on Djinn and Parasite on various ICE), so maybe both the host and the card is triggering or something? I'm not sure why I didn't mention that before, and I'm sorry that I seem to be throwing more and more random bits of information into a slightly incoherent report, but hopefully this is actually helpful and not just my hypothesising over little evidence. :P

**Comment by JoelCFC25** [comment]
I have submitted a fix in #923.
