### ISSUE TITLE
Players be the one triggering the start of turn effects.

### ISSUE THREAD

**Issue by Azgaroux** [mtgred/netrunner#920]
I think players should be the one who triggers the start of turn effects. This will practice the players in F2F matches when they play IRL. 

This will also correct optimum triggers on some cards like:
Daily Cast + Drug Dealer (with 0 creds, trigger Drug Dealer first then trigger Daily Cast).

This Enhancement/Feature could only be an option.

**Comment by JoelCFC25** [comment]
Keep an eye on #282--there is going to be a new way of handling these cards soon.
