### ISSUE TITLE
Street Peddler facedown cards acting like they're actively installed

### ISSUE THREAD

**Issue by thehunter518** [mtgred/netrunner#921]
So far I've only noticed this with Adjusted Chronotype - the Noise player had a Wyldside installed, and a Street Peddler with an Adjusted Chronotype facedown under it. The Adjusted Chronotype was giving him back his lost click from Wyldside as if it was actually installed, and was reporting this in chat.

Haven't tested it with other facedown cards on Peddler (or with Apex), so this may be an isolated incident.

**Comment by JoelCFC25** [comment]
We're aware of a major problem with at least one of the recent commits. Unfortunately it's a holiday weekend here in the States and some of us won't have much availability until early next week.

**Comment by GordonsBeard** [comment]
https://github.com/mtgred/netrunner/issues/919

This looks like a related issue.

**Comment by JoelCFC25** [comment]
Have submitted the fix for all of these issues in #923.
