### ISSUE TITLE
Shi.Kyu and Archives run bug

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#93]
**Problem:**
While the Corp is deciding whether to use Shi.Kyu or not, the "Successful Run" and "Jack Out" commands stay on the screen. Clicking on "Successful Run" again causes the Shi.Kyu process to happen a second time.

**Solution:**
Grey-out the Successful Run and Jack Out options, or remove those actions and add plain text that says "Waiting for Corp action".

**Comment by mtgred** [comment]
Thanks for reporting the issue. The problem has been fixed and will be deployed with the next server update.
