### ISSUE TITLE
Medium not allowing multiaccess

### ISSUE THREAD

**Issue by MHGray** [mtgred/netrunner#930]
So I had Hivemind with 1 counter on it, a Medium hosted on a Djinn and another Medium by itself. Ran R&D and was successful, so mediums triggered and got a counter each, so should have been accessing 3 cards - 1 base and 1 for each '2 counter' Medium thanks to Hive mind, but it only let me access 1 card. Chalked it up to weirdness. 

Ran on a later turn and before clicking successful run, moved virus counters from hivemind over to one of the mediums so I could at least access a couple cards. Medium had 4 counters, none on hivemind. Still only let me access 1 card. I don't even know why Hivemind has the ability to move counters onto other viruses. That actually wouldn't be a bad implementation if it didn't also lose the counter itself when you placed them.

**Comment by JoelCFC25** [comment]
You're right, something's goofy here with Hivemind added to the mix. You aren't meant to have to actually use the ability to move Hivemind tokens here--I think that's for when you want to "spend" them like from Cache. 

When I replicate your scenario (Hivemind with 1, both Mediums initially with none), I accessed 1 card on the initial run when I should have accessed 3, as you say. When I run again, I correctly access 5 (Hivemind's 1 "added" to what becomes 2 counters on each Medium). I'll investigate.

**Comment by JoelCFC25** [comment]
Thanks for the report--found the cause and fixed it. The `:req` for the `:no-action` event needed to use `get-virus-counters` instead of simply checking the card's own counters. I don't think I would have caught that one for a long time...

**Comment by MHGray** [comment]
Glad I could be of some use and thank you for fixing it.
