### ISSUE TITLE
Medium/Cyberdex Virus Suite interaction

### ISSUE THREAD

**Issue by eedok** [mtgred/netrunner#936]
seems in the current live version if your medium hits a cyberdex, it stops gaining counters permanently.

**Comment by JoelCFC25** [comment]
I'm not seeing this in dev right now--were there any other cards in play that could possibly have impacted this scenario? I did submit a patch to Medium/Nerve Agent last night, maybe check this again after the next server restart when it goes live.

**Comment by eedok** [comment]
Nope, can replicate it every time on the site too, just make it NEH vs Whizzard, make the top card of R & D CVS and set clicks to 0, then put medium in Whizzards hand and run the R & D, purge then run R & D again and you get no tokens

**Comment by mtgred** [comment]
Another user reported that when viruses get purged medium stops charging counters after. It can be fixed by putting it back in hand and reinstalling.

**Comment by JoelCFC25** [comment]
Yep, fixed that in #935--it was only handling when there were 1 or more counters or `:counter` didn't exist at all, but CVS sets it to 0.

**Comment by mtgred** [comment]
:+1:
