### ISSUE TITLE
Jackson Howard ends the run

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#94]
Using Jackson Howard before a successful run seems to end the run?

**Comment by mtgred** [comment]
If the Jackson Howard is the only card in the server, the server is "destroyed". This end the run and neither successful run or unsuccessful run abilities triggers.

**Comment by Agnate** [comment]
Ahh so there's the bug! If you use Jackson Howard from ANOTHER server, it still ends the run (as it checks the server Jackson is in instead of the server you're running on).

**Comment by mtgred** [comment]
I see. Thanks for reporting the issue. It will be fixed in the next server update.
