### ISSUE TITLE
Trashing [Hellion Alpha Test] prints incorrectly in chat

### ISSUE THREAD

**Issue by GordonsBeard** [mtgred/netrunner#948]
When Ed Kim accessed Hellion Alpha Test from R&D it was automatically trashed by the Runner, and then printed this to the chatlog:

![image](https://cloud.githubusercontent.com/assets/4015791/11582188/3b21cfa2-9a00-11e5-959a-60b41723c3a1.png)

**Comment by GordonsBeard** [comment]
This happens any time the card is printed, even playing the card from hand will cause the incorrect text.

**Comment by nealterrell** [comment]
@queueseven is going to have to chime in here, he did the card name highlighting.

**Comment by Saintis** [comment]
Problem lies in the `add-image-codes-impl` function. The regex finds Alpha inside Hellion Alpha Test and links that card instead. So you get `[Hellion [Alpha~04087] Test~04031]` instead of `[Hellion Alpha Test~04031]`.

**Comment by zaroth** [comment]
Also tried looking at this, but didn't have enough willpower today to perserve through and pick it apart. For brave souls looking at this, the regex in question is [here](https://github.com/mtgred/netrunner/blob/0aa976f2e3e21a2bbde33713b0d84f03c36353d9/src/cljs/netrunner/gameboard.cljs#L233)

**Comment by zaroth** [comment]
Fixed by #1456.
