### ISSUE TITLE
Can't fully view all cards in hand when browser is zoomed-in and have exactly six cards.

### ISSUE THREAD

**Issue by Azgaroux** [mtgred/netrunner#949]
Can't fully view all cards in hand when browser is zoomed-in to 50/60% and have exactly six(6) cards.

**Comment by GordonsBeard** [comment]
Which browser? What is your resolution?

**Comment by Azgaroux** [comment]
Browsers: Chrome ver. 47.0.2526.73, Chromium ver. 46.0.2480.0 and Foxfire ver. 42.0. Resolution 1366x768.

**Comment by nealterrell** [comment]
Do you mean maximized instead of minimized? Which part of the cards gets cut off? Have you tried F11 (full screen) and/or zooming out?

**Comment by Azgaroux** [comment]
It's either minimized,maximized or in full screen and as long as you have 6 cards in hand and a zoomed-in browser below 50%. Sorry the title is confusing, I'll just edit it for clarification.

**Comment by zaroth** [comment]
#1335 is a possible fix for this.

**Comment by JoelCFC25** [comment]
Confirmed that this is still an issue--a bizarre one--at least in Chrome 53.0.2785.101 (64-bit) on MacOS.

**Comment by Saintis** [comment]
Cannot reproduce on Chrome. On Firefox and Safari, the 6th card sometimes moves to a second row on very zoomed out settings (but doesn't disappear). And now with the ability to expand the hand to a bigger window this will not be an issue.
