### ISSUE TITLE
Test Run forces installed card into stack even when uninstalled and reinstalled

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#95]
Trashing and reinstalling a card brought out with Test Run still causes it to be placed on top of the stack (despite the trashing and reinstalling of it technically being a new instance of the card).

Example:

- Play Test Run to retrieve and install a Femme Fatale.
- Play Scavenge (not yet functional, so simply trashing Femme has the same result) and reinstall Femme from somewhere (archives or grip).
- When the turn ends, even though it's a new copy that is installed, it gets put back on top of the stack.

I'm not sure if it's worth implementing the solution right now since a lot of cards are unfinished, but if the card is uninstalled and then reinstalled, it is a new version of the card and Test Run should no longer be able to target it (and thus it should stay in play).

**Comment by mtgred** [comment]
Test Run has been improved to handle the case where the fetched card is reinstalled before the end of the turn.
