### ISSUE TITLE
Mulligan should be corp first! 

### ISSUE THREAD

**Issue by Zach-ER** [mtgred/netrunner#956]
Could you please change it so that it does not reveal the runner's mulligan decision until after the corp has chosen? That would be much appreciated!

**Comment by nealterrell** [comment]
It's a low priority item, but it's on the list. As runner, you should just wait until the Corp reveals their decision, as you would when playing in person.

**Comment by zaroth** [comment]
Connected to #329

**Comment by nealterrell** [comment]
Fix submitted in #1059.

**Comment by JoelCFC25** [comment]
Deployed!
