### ISSUE TITLE
Mutate on Remote Broken

### ISSUE THREAD

**Issue by trafalco** [mtgred/netrunner#957]
Details:  As playing as the foundry I rezzed a quandary in a remote server (only ice on server).  Later I mutated that ice and it went through the motions of looking through R&D but did not install card and kept asking for another target to mutate.  I was able to reproduce in testing.

When testing, Mutate appears to work on a central server just not on a remote server.  A side note: the cursor icon looks like targeting crosshair on a central ice, but does not on the remote ice.

**Comment by JoelCFC25** [comment]
My diagnosis is that Mutate bugs the game when targeting an ICE to trash that is the only ICE protecting a server with no contents. Trashing it triggers the code that collapses servers, so when Mutate attempts to identify a `subvec` on line 266, the targeted vector (of server ICE) doesn't exist.
