### ISSUE TITLE
Global Food Initiative and Human First interaction

### ISSUE THREAD

**Issue by Amphiprison** [mtgred/netrunner#958]
When the Corp scores GFI, Human First gives the runner 2 credits when it should give 3.

**Comment by JoelCFC25** [comment]
Thanks for the report. It's an easy fix, I'll bundle it into my next batch of stuff.

**Comment by rajgiriUW** [comment]
this is not fixed, by the way, as of today.

**Comment by JoelCFC25** [comment]
No, as the OP states, the original scenario was a **Corp score** of GFI. I don't agree this is bugged--tested it just now: Corp score of GFI gives the Runner 3 credits (correct), Runner steal of GFI gives the Runner 2 credits (correct).

**Comment by JoelCFC25** [comment]
Guess this needs an updated ruling.

**Comment by JoelCFC25** [comment]
Have confirmation that Human First + GFI scored = 3 Runner creds, GFI stolen = 2 Runner creds.
