### ISSUE TITLE
Suggestion: +5 and -5 Credit buttons

### ISSUE THREAD

**Issue by Agnate** [mtgred/netrunner#96]
Since there are a lot of incomplete card rules, it would be nice to have +5 and -5 credit buttons for when manual manipulation of credits needs to happen.

Either way, keep up the great work! Loving the web app! :D

**Comment by HongkongKoma** [comment]
Great idea, I second this.

**Comment by Agnate** [comment]
This can probably be closed considering that a majority of the implementations have been added, so frequently manipulating credits isn't required anymore.

**Comment by JoelCFC25** [comment]
Fair enough--if it becomes a big need again in the future it can be revisited!
