### ISSUE TITLE
Breaking News and 24/7 News Cycle not correct

### ISSUE THREAD

**Issue by StashAugustine** [mtgred/netrunner#961]
If you fire Breaking News with 24/7 News Cycle, it shouldn't remove the tags at the end of the turn (since the turn you have scored breaking news wasn't this turn.) Additionally it shouldn't remove the tags if you forfeit the BN the turn you score it, but I haven't tested to see if that's implemented.

**Comment by JoelCFC25** [comment]
We've known about this for some time. I've tried several ways of fixing it but have had no success thus far.
