### ISSUE TITLE
'when scored' id abilities incorrectly trigger with employee strike out

### ISSUE THREAD

**Issue by cwoac** [mtgred/netrunner#976]
example:

Employee strike is in play, titan transnational scores an agenda, no other on score effects in play.

What should happen:
The only 'on score' ability (strike) in play triggers and Employee strike is trashed.

What does happen
Employee strike is trashed and titan gets a counter on the agenda.

**Comment by JoelCFC25** [comment]
I can't reproduce this in dev, it yields the correct behavior. I'll try it on live.

**Comment by cwoac** [comment]
Pretty certain it was not over-advanced, but I will keep my eyes out and reopen if I see it again.
