### ISSUE TITLE
Installing a faceup card from Archives makes them retain :seen true

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#979]
This bug should be fixed by adding :seen parameter card update in corp-install function in core.clj, however this function seems a bit too big for me to parse for now :^)

(Example card installing from Archives: Interns)

**Comment by nealterrell** [comment]
I think we can dissoc `:seen` from the card in corp-install, and then `assoc` it later in the function if installing face-up.

**Comment by nealterrell** [comment]
Fix submitted in #983.
