### ISSUE TITLE
Dirty Laundry

### ISSUE THREAD

**Issue by mercviper** [mtgred/netrunner#98]
If Dirty Laundry steals an agenda on a remote server, it doesn't gain the 5 credits after the run is completed. Works fine on centrals though.

Edit: seems to also not work if you trash assets/upgrades from remotes during the run as well, so something to do with end-run handling in remotes?

**Comment by mtgred** [comment]
Thanks for reporting the issue. When the last card of a remote server is moved the server is destroyed and the run is ended. This prevented end of run effects to trigger.

The problem is now solved. The fix will be deployed with the next server update.

**Comment by Ivan0xFF** [comment]
I've also noticed that the corp is sometimes gaining the 5 credits from Dirty Laundry when the above conditions are met(Agenda stolen, or asset trashed with no ICE)

**Comment by Agnate** [comment]
Someone was telling me that if you use Jackson Howard before a successful run and there is no ICE or upgrades in that remote, the remote is "destroyed" and the run is considered neither successful nor unsuccessful.

Might be worth double-checking to see if this is still true when fixing the stolen-agendas scenario.

**Comment by Ivan0xFF** [comment]
Agnate: In the Jackson(and Mark Yale, and Executive Bootcamp) case, the run is neither successful nor unsuccessful due to the server ceasing to exist before the access phase. 
In these cases, the run is successful, the runner enters the access phase, the server then ceases to exist, then the run ends, then Dirty Laundry should trigger.

**Comment by Agnate** [comment]
That's how I assumed it worked, so I'm glad to see it validated. I just wanted to comment on the Jackson Howard scenario so that it could be properly tested after those other cases were addressed. :)

**Comment by dimarco70** [comment]
I confirm that sometimes (asset trashed in my case) the Corporation gets the money instead of the runner

**Comment by JoelCFC25** [comment]
I *think* this one is obsolete but I'll leave it open for now.

**Comment by mtgred** [comment]
The problem with the Corp sometime getting the 5 credits has been fixed a while ago.

Dirty Laundry should work fine now.
