### ISSUE TITLE
Identity Shadow do not allow agenda from other faction

### ISSUE THREAD

**Issue by percycpcpc** [mtgred/netrunner#981]
Now adding agenda from other faction for Shadow is not valid.

**Comment by nealterrell** [comment]
FYI, you can type the agenda name into the big "Decklist" text box and it will add it to the deck.

**Comment by percycpcpc** [comment]
I know but it will shows that it is not a valid deck.

**Comment by Saintis** [comment]
This seems to be fixed now.
