### ISSUE TITLE
AstroScript tokens can be placed on scored agendas

### ISSUE THREAD

**Issue by nealterrell** [mtgred/netrunner#984]
Minor issue, but nothing stops AstroScript's selection prompt from targeting a scored agenda, or even an agenda in HQ for that matter. Needs a check to see if the target is installed.

**Comment by nealterrell** [comment]
Probably also applies to Trick of Light and other token-placing cards, but I haven't verified.

**Comment by Saintis** [comment]
Probably because it allows any :type "Agenda" to be the target (in the cards-agendas file). Maybe change to Agenda type and installed?

**Comment by nealterrell** [comment]
Yep! I'm leaving it for a newer developer to work on, since it's not a pressing issue. Take a crack at it!
