### ISSUE TITLE
New Angeles City Hall doesn't ask me to avoid Vamp tags

### ISSUE THREAD

**Issue by CrispyCrunch** [mtgred/netrunner#985]
and everytime my Rachel is trashed due to being tagged. this is more of a nuisance, but it has spawned a rules discussion with my opponent two times already.

**Comment by JoelCFC25** [comment]
Thanks for the report. Vamp is using outdated code...where it says `(gain :tag 1)` it should be `(tag-runner 1)`, which will enable NACH to do the avoid tag. We'll fix it soon.
