### ISSUE TITLE
Mr. Li only draws one card sometimes.

### ISSUE THREAD

**Issue by homeiss** [mtgred/netrunner#987]
It doesn't happen often but sometimes Mr. Li only draws one card instead of two.

**Comment by GordonsBeard** [comment]
Do you have any other information about the board state that could help?

**Comment by homeiss** [comment]
I will try and recreate it and post more info.

**Comment by homeiss** [comment]
![mrli](https://cloud.githubusercontent.com/assets/16271715/11775140/067ffb04-a1f1-11e5-96ff-0d1968768453.jpg)

See attached image of it only displaying one card to select instead of two.

**Comment by JoelCFC25** [comment]
Thanks for the report! The `:choices` in Mr. Li isn't currently using `:not-distinct true`, so every time you see this behavior, it means you drew 2 identical cards. We just have to add this missing flag and it will show both card titles even though they're the same.

**Comment by homeiss** [comment]
Makes sense. Thanks for the quick answer!
