### ISSUE TITLE
After 15 Minutes Shuffled Back, Agenda Point Was Still Counted

### ISSUE THREAD

**Issue by greyfield** [mtgred/netrunner#988]
Pretty simple situation. I was running, and stole a 15 Minutes. On a later turn, the corp shuffled it back in, but unbeknownst to us, Jnet didn't subtract the point from my total, so when I stole two more agendas a few turns later to get up to 6 points, Jnet informed me I'd "won the game".

It wasn't entirely clear whether it was due to 15 Minutes or a Global Food Initiative that I'd also scored; I assume the former. A minor bug all told, but thought you should know.

**Comment by JoelCFC25** [comment]
15 Minutes is not yet implemented, so any the Corp decides to use a stolen copy, it requires manual adjustments by both players--the Corp to shuffle it back into R&D, and the Runner to manually deduct 1 agenda point. Although the card status list linked on the main Github page is a bit outdated, it is correct with regard to this card. :)
