### ISSUE TITLE
Deckbuilder periodically returns to current identity during identity selection

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#997]
Happens on Firefox 42.0. Can be quite annoying when trying to find the identity you want, especially since they are sorted in a seemingly random (?) order.

**Comment by zaroth** [comment]
It seems related to http://stackoverflow.com/questions/17498123/firefox-select-dropdown-keeps-refreshing-reverting-to-default-option-due-to-runn . So probably a bug in a JS library the UI side uses.

**Comment by zaroth** [comment]
This issue is unfortunately still happening on 'production' (jinteki.net), while me and @Saintis were unable to reproduce it in the dev environment. Possibly connected to card letters deleting themselves when entered in the card search box (can't reproduce this now, but saw reports in chat today). Please reopen this.

**Comment by zaroth** [comment]
Made a screencast of this bug. First you can observe the selection jumping to PE out of nowhere, second it jumps to The Shadow which was originally selected before using dropdown. No keys were pressed and mouse roll during this video: https://gfycat.com/LoathsomeBigDavidstiger

**Comment by erbridge** [comment]
Does this still happen? Sounds like it could be an issue with React bindings.

**Comment by zaroth** [comment]
Confirmed still happening on production. However I couldn't get it to happen on the test server - seems like the blanket dependency upgrade (react in particular) may have taken care of this one.

**Comment by erbridge** [comment]
I doubt it would have been an issue with React itself, but with our use of it...

**Comment by Saintis** [comment]
Could not reproduce. Might have been fixed at some point, or with the move to Reagent.
